# -*- coding: utf-8 -*-
# 第 11 批（C3）：危險性機械及設備安全檢查規則（OSH-53）第101條～第143條（補題）
# ※ 四個選項刻意寫成相近長度。
L = "OSH-53"
Q = [
(L,"第101條",2,"第一種壓力容器-構造檢查",
 "第一種壓力容器本體製造完成時，應由何人向何機構申請構造檢查？有無例外？",
 ["由製造人向製造所在地檢查機構申請；但在設置地組合之分割組合式者，得在安裝前向設置所在地檢查機構申請","由雇主向設置所在地檢查機構申請；但在工廠一次製造完成者，得於出廠前向製造所在地檢查機構申請","由所有人向中央主管機關指定之代行檢查機構申請；但分割組合式者一律應於全部組裝完成後始得申請","由製造人向中央主管機關申請並取得認可；但分割組合式者得由雇主於設置完成後併同竣工檢查申請"],"a",
 "第101條：製造第一種壓力容器本體完成時，應由製造人向製造所在地檢查機構申請構造檢查；但在設置地組合之分割組合式第一種壓力容器，得在安裝前，向設置所在地檢查機構申請構造檢查。鍋爐之構造檢查（第77條）亦有分割組合式之類似例外。",
 "Who applies to which agency for the structural inspection of a Class 1 pressure vessel, and what is the exception?",
 ["The maker applies to the agency where it is made; a sectional vessel assembled on site may be applied for before installation to the agency of the site","The employer applies to the agency of the installation site; one wholly built in the factory may be applied for before shipment to the making agency","The owner applies to a designated inspection body; a sectional vessel may only be applied for after it has been completely assembled on the site","The maker applies to the central competent authority for recognition; a sectional one may be applied for with the completion inspection later"],
 "Article 101; cf. Article 77."),

(L,"第102條",3,"第一種壓力容器-構造項目",
 "第一種壓力容器構造檢查之項目及書件免檢附之情形為何？",
 ["項目為施工方法、材料厚度、構造、尺寸、最高使用壓力、強度計算審查、人孔、清掃孔、安全裝置之規劃、耐壓試驗及胴體端板管板材料等；由同一檢查機構實施熔接及構造檢查者，得免檢附構造詳圖強度計算書及熔接明細表","項目為安全閥數量、容量、吹洩試驗、安全裝置、壓力表之數量及尺寸等；由同一檢查機構實施熔接及構造檢查者，仍應逐項檢附構造詳圖、強度計算書及加蓋熔接檢查合格戳記之熔接明細表，不得免除任何書件","項目為外觀檢查、外部之腐蝕裂痕變形污穢洩漏檢測、易腐蝕處定點超音波測厚及附屬裝置檢查等；凡經型式檢查合格者，得免檢附全部書件並由檢查機構逕依型式檢查紀錄認定其構造檢查合格","項目為材料檢查、外表檢查、熔接部之機械性能試驗、放射線檢查及熱處理檢查等；凡以鉚接製造者，得免檢附製造設施型式檢查合格證明，並由製造人自行出具品質保證書替代之"],"a",
 "第102條：申請構造檢查應檢附第一種壓力容器明細表二份、構造詳圖及強度計算書各二份、以熔接製造者附加蓋熔接檢查合格戳記之熔接明細表、以鉚接製造者附製造設施型式檢查合格證明；由同一檢查機構實施同一座容器之熔接檢查及構造檢查者，得免檢附第2款、第3款書件。構造檢查項目為施工方法、材料厚度、構造、尺寸、最高使用壓力、強度計算審查、人孔、清掃孔、安全裝置之規劃、耐壓試驗、胴體端板管板等使用之材料及其他必要之檢查。",
 "What does a Class 1 pressure vessel's structural inspection cover, and when are documents waived?",
 ["Construction method, material thickness, structure, dimensions, maximum working pressure, strength review, manholes, cleaning holes, safety device layout, pressure test and shell, end and tube plate materials; where one agency does both the welding and structural inspections, the drawings, calculations and welding schedule may be omitted","Number and capacity of safety valves, blow-off testing, safety devices and the number and size of pressure gauges; even where one agency does both the welding and the structural inspections, the detailed drawings, strength calculations and stamped welding schedule must still all be attached item by item, without any exception whatsoever","Appearance, detection of external corrosion, cracking, deformation, fouling and leakage, spot ultrasonic thickness measurement and accessories; where the type inspection has been passed all documents may be omitted and the agency simply deems the structural inspection passed on the type record","Material inspection, surface inspection, mechanical property testing of the weld, radiographic examination and heat treatment inspection; where riveting is used the facility type inspection certificate may be omitted and replaced by a quality warranty issued by the maker itself"],
 "Article 102."),

(L,"第103條",1,"第一種壓力容器-構造準備",
 "檢查機構實施第一種壓力容器構造檢查時，製造人應事先備妥哪些事項？",
 ["將被檢查物件放置於易檢查位置，並準備水壓等耐壓試驗","將被檢查物件放置於易檢查位置，並準備機械性能試驗片","將被檢查物件加熱至常用溫度，並準備放射線檢查之器材","將被檢查物件完全分解為零件，並準備氣密試驗用之氣體"],"a",
 "第103條：檢查機構實施第一種壓力容器之構造檢查時，製造人或其指派人員應在場，並應事先備妥將被檢查物件放置於易檢查位置、準備水壓等耐壓試驗。第115條第2項、第118條第2項：重新檢查及變更檢查準用第102條第3項及第103條規定。",
 "What must the maker prepare in advance for a Class 1 pressure vessel's structural inspection?",
 ["Place the object to be inspected where it is easy to inspect and prepare a hydrostatic or other pressure test","Place the object to be inspected where it is easy to inspect and prepare the mechanical property test pieces","Heat the object to be inspected to its usual working temperature and prepare the radiographic testing gear","Dismantle the object to be inspected completely into parts and prepare the gas for the airtightness test"],
 "Article 103."),

(L,"第104條",1,"第一種壓力容器-構造合格",
 "第一種壓力容器經構造檢查合格者，檢查機構應如何處理？",
 ["在第一種壓力容器明細表上加蓋構造檢查合格戳記，檢查員簽章後交付申請人一份作為證明，並在物體明顯部位打印","在熔接明細表上加蓋熔接檢查合格戳記，檢查員簽章後交付申請人二份作為構造檢查合格證明，並發給檢查合格證","逕行核發第一種壓力容器檢查合格證及竣工檢查結果報告表，有效期限最長為一年，並由雇主置掛於作業場所明顯處","由製造人自行於明細表註記構造檢查合格後留存備查，檢查機構僅須以書面將檢查結果通知申請人即可無須打印"],"a",
 "第104條：第一種壓力容器經構造檢查合格者，檢查機構應在第一種壓力容器明細表上加蓋構造檢查合格戳記，檢查員簽章後交付申請人一份，做為構造檢查合格證明，並應在被檢查物體上明顯部位打印，以資識別。第106條第1項第1款：申請竣工檢查時應檢附加蓋構造檢查或重新檢查合格戳記之明細表。",
 "How does the agency handle a Class 1 pressure vessel passing its structural inspection?",
 ["It stamps the vessel specification table with the structural pass mark, the inspector signs, one copy is given as proof, and the object is marked conspicuously","It stamps the welding schedule with the welding pass mark, the inspector signs, two copies are given as structural proof, and a certificate is issued as well","It directly issues the vessel inspection certificate and a completion inspection result report valid at most one year, posted conspicuously at the workplace","The maker notes the structural pass on the specification table itself and keeps it, the agency merely notifying the applicant in writing without marking"],
 "Article 104."),

(L,"第105條",1,"第一種壓力容器-竣工檢查",
 "第一種壓力容器設置完成時，雇主應辦理何事？未經竣工檢查合格有何限制？",
 ["應向檢查機構申請竣工檢查，未經竣工檢查合格不得使用；實施竣工檢查時雇主或其指派人員應在場","應向檢查機構申請構造檢查，未經構造檢查合格不得設置；實施構造檢查時製造人或其指派人應在場","應向中央主管機關申請型式檢查，未經型式檢查合格不得使用；檢查時主任設計者及施工者應在場","應向當地主管機關報請備查後即得使用，並於使用滿一年後再併同定期檢查補辦竣工檢查之手續"],"a",
 "第105條：雇主於第一種壓力容器設置完成時，應向檢查機構申請竣工檢查；未經竣工檢查合格，不得使用；檢查機構實施竣工檢查時，雇主或其指派人員應在場。第106條：竣工檢查合格者核發竣工檢查結果報告表及檢查合格證，有效期限最長為一年。",
 "What must an employer do once a Class 1 pressure vessel is installed, and what if it has not passed?",
 ["Apply to the agency for a completion inspection; without passing it may not be used, and the employer or a designee must attend the inspection","Apply to the agency for a structural inspection; without passing it may not be installed, and the maker or a designee must attend the inspection","Apply to the central competent authority for a type inspection; without passing it may not be used, the chief designer and workers attending","File it with the local competent authority and use may begin, the completion inspection being done with the periodic one after a year"],
 "Article 105."),

(L,"第106條",2,"第一種壓力容器-竣工項目",
 "第一種壓力容器竣工檢查之項目及合格證有效期限為何？",
 ["項目為安全閥數量、容量、吹洩試驗、安全裝置、壓力表之數量、尺寸及其他必要之檢查；合格證有效期限最長為一年","項目為施工方法、材料厚度、構造、尺寸、最高使用壓力及強度計算審查等；合格證有效期限最長為二年並得延長","項目為材料檢查、外表檢查、熔接部機械性能試驗及放射線檢查等；合格證有效期限最長為三年並由雇主自行認定","項目為外觀檢查、外部腐蝕裂痕變形之檢測及定點超音波測厚等；合格證有效期限最長為五年並應每年重新換發"],"a",
 "第106條：雇主申請第一種壓力容器竣工檢查時，應檢附加蓋構造檢查或重新檢查合格戳記之明細表及設置場所與設備周圍狀況圖；竣工檢查項目為安全閥數量、容量、吹洩試驗、安全裝置、壓力表之數量、尺寸及其他必要之檢查；經竣工檢查合格者核發竣工檢查結果報告表及檢查合格證，有效期限最長為一年。",
 "What does a Class 1 pressure vessel's completion inspection cover, and how long is the certificate valid?",
 ["Number and capacity of safety valves, blow-off testing, safety devices, the number and size of pressure gauges and other necessary checks; valid at most one year","Construction method, material thickness, structure, dimensions, maximum working pressure and review of the strength calculations; valid at most two years, extendable","Material inspection, surface inspection, mechanical property testing of the weld and radiographic examination; valid at most three years as determined by the employer","Appearance, detection of external corrosion, cracking and deformation and spot thickness measurement; valid at most five years but reissued every year in any event"],
 "Article 106."),

(L,"第107條",1,"第一種壓力容器-定期申請",
 "雇主應於何時向檢查機構申請第一種壓力容器之定期檢查？",
 ["應於檢查合格證有效期限屆滿前一個月，填具定期檢查申請書向檢查機構申請","應於檢查合格證有效期限屆滿前六個月，填具定期檢查申請書向檢查機構申請","應於檢查合格證有效期限屆滿後一個月內，填具定期檢查申請書向檢查機構申請","應於竣工檢查合格後每滿二年時，填具定期檢查申請書向中央主管機關提出申請"],"a",
 "第107條：雇主於第一種壓力容器檢查合格證有效期限屆滿前一個月，應填具定期檢查申請書向檢查機構申請定期檢查。第108條：定期檢查應每年實施外部檢查一次以上；內部檢查則以管路連接從事連續生產程序之化工設備或發電用者每二年一次以上，其餘每年一次以上。",
 "When must the employer apply for a Class 1 pressure vessel's periodic inspection?",
 ["One month before the inspection certificate expires, by filing a periodic inspection application with the agency","Six months before the inspection certificate expires, by filing a periodic inspection application with the agency","Within one month after the inspection certificate has expired, by filing a periodic inspection application with it","Every two years after the completion inspection is passed, by applying to the central competent authority instead"],
 "Article 107; see Article 108."),

(L,"第109條",3,"第一種壓力容器-內部延長",
 "第一種壓力容器無法依規定期限實施內部檢查者，於何種情形得申請延長或以其他方式替代？",
 ["依規定免設人孔或構造上無法設置人孔掃除孔檢查孔者、內存觸媒分子篩或其他特殊內容物者、連續生產製程中無法分隔之系統設備者、其他實施內部檢查困難者","僅限於依規定免設人孔或構造上無法設置人孔者一種情形；至於內存觸媒分子篩或連續生產製程中無法分隔之系統設備，均應停爐後依規定期限實施內部檢查","僅限於容器已使用滿十五年以上或最高使用壓力未超過每平方公分十公斤者；其餘情形一律應依規定期限實施內部檢查，不得申請延長或以其他方式替代","僅限於經檢查機構認定外部檢查結果良好且無腐蝕之虞者；至於免設人孔、內存觸媒或連續製程無法分隔者，均應報請中央主管機關逐案專案核准"],"a",
 "第109條第1項：雇主對於依規定免設人孔或構造上無法設置人孔、掃除孔或檢查孔者，內存觸媒、分子篩或其他特殊內容物者，連續生產製程中無法分隔之系統設備者，及其他實施內部檢查困難者，無法依規定期限實施內部檢查時，得申請延長內部檢查期限或以其他檢查方式替代。",
 "In what cases may a Class 1 pressure vessel's internal inspection interval be extended or replaced?",
 ["Where manholes are exempt or cannot be fitted, where catalysts, molecular sieves or other special contents are held, where the system cannot be isolated in continuous production, and where internal inspection is otherwise difficult","Only where manholes are exempt by rule or cannot structurally be fitted; vessels holding catalysts or molecular sieves and systems that cannot be isolated in continuous production must all be shut down and inspected on time","Only where the vessel has been in service for fifteen years or more or its maximum working pressure is not over 10 kg/cm2; in every other case the internal inspection must be done on time with no extension or substitute","Only where the agency finds the external inspection results good and no risk of corrosion; exempt manholes, catalyst contents or inseparable continuous processes all need case-by-case approval of the central competent authority"],
 "Article 109, Paragraph 1."),

(L,"第109條",3,"第一種壓力容器-延長程序",
 "第一種壓力容器申請延長內部檢查期限之時點、應檢附資料及核定機關為何？",
 ["應於內部檢查有效期限屆滿前三個月，檢附安全衛生管理狀況、自動檢查計畫暨執行紀錄、構造檢查合格明細表影本、構造詳圖、生產流程圖、緊急應變處置計畫、自動控制系統及檢查替代方式建議，報經檢查機構核定","應於內部檢查有效期限屆滿前一個月，檢附安全衛生管理狀況、自動檢查計畫暨執行紀錄、構造檢查合格明細表影本、構造詳圖、生產流程圖及緊急應變處置計畫等資料，報經當地主管機關核定後始得延長期限","應於內部檢查有效期限屆滿後三個月內，檢附最近一次外部檢查結果報告表、超音波測厚紀錄、耐壓試驗紀錄及氣密試驗紀錄等資料，報經中央主管機關核定後追認其延長內部檢查期限之效力","應於內部檢查有效期限屆滿前六個月，檢附設置場所及周圍狀況圖、內容物種類申報表、安全閥吹洩量計算書及操作人員名冊等資料，報經代行檢查機構核定，並由其函報中央主管機關備查"],"a",
 "第109條第1項：得於內部檢查有效期限屆滿前三個月，檢附其安全衛生管理狀況、自動檢查計畫暨執行紀錄、該容器之構造檢查合格明細表影本、構造詳圖、生產流程圖、緊急應變處置計畫、自動控制系統及檢查替代方式建議等資料，報經檢查機構核定後，延長其內部檢查期限或以其他檢查方式替代。第2項：該容器有附屬鍋爐時，其檢查期限得隨同延長之。",
 "When, with what documents and to whom is an extension of a vessel's internal inspection applied for?",
 ["Three months before the internal inspection period expires, attaching the safety management status, automatic inspection plan and records, a copy of the structural pass table, detailed drawings, flow chart, emergency plan, control system and proposed substitute, for the agency to approve","One month before the internal inspection period expires, attaching the safety management status, automatic inspection plan and records, a copy of the structural pass table, detailed drawings, the flow chart and the emergency response plan, for the local competent authority to approve","Within three months after the internal inspection period has expired, attaching the latest external inspection result report, ultrasonic thickness records, pressure test records and airtightness test records, for the central competent authority to ratify the extension afterwards","Six months before the internal inspection period expires, attaching drawings of the site and surroundings, a declaration of contents, safety valve blow-off calculations and the operator roster, for the designated inspection body to approve and report to the authority"],
 "Article 109."),

(L,"第110條",3,"第一種壓力容器-內部檢查",
 "第一種壓力容器內容物不具腐蝕性而內部檢查有困難者，得以何種方式代替？",
 ["得以常用壓力一點五倍以上壓力實施耐壓試驗，或以常用壓力一點一倍以上壓力就內容物實施耐壓試驗，並以常用壓力以上壓力實施氣密試驗及外觀檢查等代替","得以常用壓力一點二倍以上壓力實施耐壓試驗，或以常用壓力一點零五倍以上壓力就內容物實施耐壓試驗，並以最高使用壓力實施吹洩試驗及超音波測厚代替","得以最高使用壓力二倍以上壓力實施水壓試驗，或以設計壓力三倍以上壓力就空氣實施耐壓試驗，並以常用壓力以下壓力實施放射線檢查及熱處理檢查代替","得由雇主自行以目視方式檢查外部並作成紀錄留存三年，無須實施任何耐壓試驗或氣密試驗，僅須於下次定期檢查時一併補行實施內部檢查即可"],"a",
 "第110條第3項：內容物不具腐蝕性之第一種壓力容器之內部檢查有困難者，得以常用壓力一點五倍以上壓力實施耐壓試驗或常用壓力一點一倍以上壓力以內容物實施耐壓試驗，並以常用壓力以上壓力實施氣密試驗及外觀檢查等代替之。第1項、第2項：內部檢查應通知雇主預先恢復常溫常壓、排放內容物、通風換氣、整理清掃內部；項目包括表面檢查及厚度腐蝕裂痕變形污穢等檢測。",
 "How may the internal inspection of a Class 1 pressure vessel with non-corrosive contents be replaced?",
 ["By a pressure test at 1.5 times the usual pressure, or at 1.1 times using the contents themselves, together with an airtightness test above the usual pressure and a visual inspection","By a pressure test at 1.2 times the usual pressure, or at 1.05 times using the contents themselves, together with a blow-off test at maximum working pressure and thickness measurement","By a hydrostatic test at twice the maximum working pressure, or an air pressure test at three times the design pressure, together with radiographic and heat treatment inspection below usual pressure","By the employer visually checking the exterior and keeping the record three years, with no pressure or airtightness test at all, the internal inspection simply being made up at the next periodic inspection"],
 "Article 110, Paragraph 3."),

(L,"第111條",2,"第一種壓力容器-外部檢查",
 "第一種壓力容器外部檢查之項目及超音波測厚免除情形為何？",
 ["項目為外觀檢查、外部腐蝕裂痕變形污穢洩漏之檢測、必要時之非破壞檢查、易腐蝕處定點超音波測厚及其他必要檢查；因特別高溫等致測厚確有困難者得免實施","項目為外觀檢查、外部腐蝕裂痕變形污穢洩漏之檢測、必要時之非破壞檢查、易腐蝕處定點超音波測厚及其他必要檢查；惟超音波測厚於任何情形均不得免除實施","項目為內部表面檢查、厚度腐蝕裂痕變形污穢之檢測及耐壓試驗等；因容器內部空間狹小人員無法進入者，得免實施超音波測厚並改以放射線檢查方式替代之","項目為安全閥吹洩試驗、壓力表校正及安全裝置動作測試等；因設備連續運轉無法停機者，得免實施超音波測厚並由雇主自行檢測後作成紀錄報請備查"],"a",
 "第111條：第一種壓力容器外部檢查之項目為外觀檢查、外部之腐蝕、裂痕、變形、污穢、洩漏之檢測、必要時實施之非破壞檢查、易腐蝕處之定點超音波測厚及其他必要之檢查；必要時得以適當儀器檢測其內部，發現有異狀者應併實施內部檢查；超音波測厚因特別高溫等致測厚確有困難者，得免實施。受理外部檢查時應通知雇主，實施檢查時雇主或其指派人員應在場。",
 "What does a Class 1 pressure vessel's external inspection cover, and when is thickness measurement waived?",
 ["Appearance, detection of external corrosion, cracking, deformation, fouling and leakage, NDT where needed, spot ultrasonic thickness measurement at corrosion-prone points and other necessary checks; waived where high temperature makes measuring genuinely difficult","Appearance, detection of external corrosion, cracking, deformation, fouling and leakage, NDT where needed, spot ultrasonic thickness measurement at corrosion-prone points and other necessary checks; thickness measurement may never be waived in any circumstances","Internal surface inspection, detection of thickness, corrosion, cracking, deformation and fouling and pressure testing; where the interior is too cramped for entry, thickness measurement is waived and radiographic examination is used in its place instead","Safety valve blow-off testing, pressure gauge calibration and testing the action of safety devices; where the plant runs continuously and cannot be stopped, thickness measurement is waived and the employer measures and records it itself"],
 "Article 111."),

(L,"第112條",2,"第一種壓力容器-定期效期",
 "第一種壓力容器經定期檢查合格者，其使用有效期限最長為何？有無例外？",
 ["應於原檢查合格證上簽署註明使用有效期限，最長為一年；但依第108條第2項延長外部檢查期限者，最長得為二年","應於原檢查合格證上簽署註明使用有效期限，最長為二年；但發電用第一種壓力容器一律縮短為一年且不得延長","應重新核發檢查合格證並註明使用有效期限，最長為三年；但連續生產製程之化工設備得由雇主自行延長為五年","應重新核發檢查合格證並註明使用有效期限，最長為五年；但經檢查機構認有必要時得縮短為二年並通知雇主"],"a",
 "第112條：檢查機構對定期檢查合格之第一種壓力容器，應於原檢查合格證上簽署，註明使用有效期限，最長為一年；但第108條第2項（發電容量二萬瓩以上之發電用第一種壓力容器外部檢查得延長並與內部檢查同時辦理）者，最長得為二年。檢查員並應填報定期檢查結果報告表通知雇主。",
 "How long at most is a Class 1 pressure vessel valid after periodic inspection, and is there an exception?",
 ["The original certificate is endorsed for at most one year; where the external inspection interval is extended under Article 108(2) it may be at most two years","The original certificate is endorsed for at most two years; vessels used for power generation are always cut to one year and that may never be extended","A new certificate is issued for at most three years; vessels in continuous chemical production may be extended by the employer itself up to five years","A new certificate is issued for at most five years; where the agency considers it necessary the period is shortened to two years and the employer notified"],
 "Article 112; see Article 108."),

(L,"第113條",2,"第一種壓力容器-不合格",
 "第一種壓力容器經定期檢查不合格者，應如何處理？",
 ["檢查員應即於檢查合格證記事欄記載不合格情形並通知改善；情形嚴重有發生危害之虞者，應報請所屬檢查機構限制其最高使用壓力或禁止使用","檢查員應即註銷其檢查合格證並命令拆除該設備；情形輕微者始得於檢查合格證記事欄記載不合格情形，並限期一個月內完成各項改善","檢查員應即函報中央主管機關逕行裁處罰鍰；情形嚴重有發生危害之虞者，另由中央主管機關公告該事業單位名稱及不合格之具體情形","檢查員僅需以口頭告知雇主不合格之情形；是否限制最高使用壓力或禁止使用，由雇主依營運需要自行決定並作成書面紀錄留存備查"],"a",
 "第113條：第一種壓力容器經定期檢查不合格者，檢查員應即於檢查合格證記事欄內記載不合格情形並通知改善；其情形嚴重有發生危害之虞者，並應報請所屬檢查機構限制其最高使用壓力或禁止使用。鍋爐（第88條）、高壓氣體特定設備（第137條）、高壓氣體容器（第159條）均有相同規定。",
 "What must be done when a Class 1 pressure vessel fails its periodic inspection?",
 ["The inspector notes the failure in the remarks column of the certificate and calls for improvement; if serious enough to risk harm, the agency limits the working pressure or bans use","The inspector cancels the certificate at once and orders the vessel dismantled; only in slight cases is the failure noted in the remarks column with one month allowed to improve","The inspector reports it to the central competent authority to impose a fine; if serious enough to risk harm, that authority announces the undertaking's name and the defects","The inspector need only tell the employer orally; whether to limit the working pressure or stop use is left to the employer as its operations require, with a written record kept"],
 "Article 113."),

(L,"第114條",3,"第一種壓力容器-重新檢查",
 "第一種壓力容器有下列何種情事之一時，應由所有人或雇主申請重新檢查？",
 ["從外國進口、構造重新竣工或定期檢查合格後閒置一年以上擬裝設或恢復使用、經禁止使用擬恢復使用、固定式者遷移裝置地點重新裝設、擬提升最高使用壓力、擬變更內容物種類","從外國進口、構造重新竣工或定期檢查合格後閒置三個月以上擬恢復使用、更換操作人員、固定式者變更設置場所名稱、擬降低最高使用壓力、擬變更保溫材料之種類","變更安全閥廠牌型號、更換壓力表或水位計、變更保養廠商、變更公司負責人、變更設備編號或塗裝顏色、變更設備所屬部門等管理事項之一者，均應申請重新檢查","僅限於從外國進口一種情事；其餘閒置一年以上、經禁止使用、遷移裝置地點、提升最高使用壓力或變更內容物種類者，均得於下次定期檢查時一併辦理而免申請"],"a",
 "第114條第1項：第一種壓力容器有從外國進口、構造檢查重新檢查竣工檢查或定期檢查合格後經閒置一年以上擬裝設或恢復使用（但由檢查機構認可者不在此限）、經禁止使用擬恢復使用、固定式者遷移裝置地點而重新裝設、擬提升最高使用壓力、擬變更內容物種類等情事之一者，應由所有人或雇主向檢查機構申請重新檢查。第3項：外國進口具相當檢查證明文件者得免除全部或一部之檢查。",
 "Which circumstances require the owner or employer to apply for a Class 1 pressure vessel's re-inspection?",
 ["Import from abroad; idleness over a year after passing a structural, re-, completion or periodic inspection with use to resume; resumption after a ban; relocation and reinstallation of a fixed vessel; raising the maximum working pressure; changing the contents","Import from abroad; idleness over three months after passing an inspection with use to resume; a change of operator; a change of the fixed vessel's site name; lowering the maximum working pressure; or changing the kind of insulating material used on the shell","Changing the brand and model of the safety valve, replacing the pressure or water gauge, changing the maintenance contractor, changing the company head, changing the equipment number or paint colour, or changing the department that owns it","Only import from abroad; idleness over a year, resumption after a ban, relocation, raising the maximum working pressure or changing the contents may all simply be handled together at the next periodic inspection without any application"],
 "Article 114, Paragraph 1."),

(L,"第114條",3,"第一種壓力容器-種類變更",
 "第一種壓力容器因變更內容物種類致設備種類變更為高壓氣體特定設備者，應如何辦理檢查？",
 ["應依高壓氣體特定設備相關規定辦理檢查","應依原第一種壓力容器規定辦理定期檢查即可","應報請中央主管機關核准後即得免除各項檢查","應由製造人重新辦理型式檢查及熔接檢查程序"],"a",
 "第114條第2項：因擬變更內容物種類致第一種壓力容器變更設備種類為高壓氣體特定設備者，應依高壓氣體特定設備相關規定辦理檢查。第4條：高壓氣體特定設備係指供高壓氣體製造（含相關儲存）之設備及其支持構造物，其設計壓力與內容積之積超過零點零四者。",
 "If a change of contents turns a Class 1 pressure vessel into high pressure gas special equipment, what applies?",
 ["Inspection must follow the rules applicable to high pressure gas special equipment","Inspection may still follow the periodic inspection rules for Class 1 pressure vessels","Approval by the central competent authority exempts it from all further inspections","The maker must carry out the type inspection and the welding inspection all over again"],
 "Article 114, Paragraph 2."),

(L,"第115條",2,"第一種壓力容器-重新申請",
 "所有人或雇主申請第一種壓力容器重新檢查時，應檢附哪些書件？",
 ["第一種壓力容器明細表二份、構造詳圖及強度計算書各二份（檢查機構認無必要者得免檢附）、前經檢查合格證明文件或其影本","第一種壓力容器明細表一份、設置場所及周圍狀況圖二份、內容物種類申報表、安全閥吹洩量計算書及操作人員名冊各一份","熔接明細表二份及施工位置分類圖一份、熔接技術士資格證件、熔接程序規範及熔接程序資格檢定紀錄影本各一份等文件","公司登記證明文件、工廠登記證影本、勞工保險投保名冊、自動檢查計畫及緊急應變計畫各一份等行政管理性質之相關文件"],"a",
 "第115條：所有人或雇主申請第一種壓力容器之重新檢查時，應填具重新檢查申請書，並檢附第一種壓力容器明細表二份、構造詳圖及強度計算書各二份（但檢查機構認無必要者得免檢附）、前經檢查合格證明文件或其影本；第102條第3項及第103條規定於重新檢查時準用之。",
 "What documents must accompany an application for a Class 1 pressure vessel's re-inspection?",
 ["Two vessel specification tables, two sets each of detailed drawings and strength calculations (waivable if the agency finds them unnecessary), and the previous certificate or a copy of it","One vessel specification table, two drawings of the site and its surroundings, a declaration of the contents, safety valve blow-off calculations and the operator roster, one each","Two welding schedules and one work position classification chart, the welders' skill certificates, and one copy each of the welding procedure specification and the qualification records","The company registration documents, a copy of the factory registration, the labor insurance roster, the automatic inspection plan and the emergency response plan, one copy of each of them"],
 "Article 115."),

(L,"第116條",3,"第一種壓力容器-重新合格",
 "第一種壓力容器經重新檢查合格者，檢查機構應如何處理？",
 ["在明細表加蓋重新檢查合格戳記交付一份作為證明以辦理竣工檢查；但屬閒置後停用或經禁止使用而未遷移裝設者，得在原合格證記載並註明有效期限最長一年","在明細表加蓋構造檢查合格戳記交付二份作為證明以辦理型式檢查；但屬外國進口者，得在原合格證記載檢查結果並註明使用有效期限最長二年而免予打印","逕行核發新檢查合格證並註明使用有效期限最長為二年；凡經重新檢查合格者一律免再辦理竣工檢查，外國進口者亦免於物體明顯部位打印以資識別","由所有人自行於明細表註記重新檢查合格後留存備查；檢查機構僅須將檢查結果通知申請人，由申請人逕行辦理竣工檢查而無須加蓋任何合格戳記"],"a",
 "第116條：第一種壓力容器經重新檢查合格者，檢查機構應在明細表上加蓋重新檢查合格戳記，交付申請人一份，做為重新檢查合格證明，以辦理竣工檢查；但符合第114條第2款之竣工檢查或定期檢查合格後停用或第3款（經禁止使用擬恢復使用），其未遷移裝設或遷移至廠內其他位置重新裝設，經檢查合格者，得在原檢查合格證上記載檢查日期、檢查結果及註明使用有效期限，最長為一年。外國進口者應在被檢查物體上明顯部位打印。",
 "How does the agency handle a Class 1 pressure vessel that passes re-inspection?",
 ["It stamps the specification table with the re-inspection pass mark and gives one copy as proof for the completion inspection; if idled or banned but not relocated, the original certificate is endorsed for at most one year","It stamps the specification table with the structural pass mark and gives two copies as proof for the type inspection; imported vessels may have the original certificate endorsed for at most two years without marking","It directly issues a new certificate valid at most two years; every vessel passing re-inspection is exempt from any completion inspection, and imported ones need not be marked conspicuously either","The owner notes the re-inspection pass on the specification table itself and keeps it; the agency merely notifies the applicant, who proceeds to the completion inspection with no pass stamp at all"],
 "Article 116; see Article 114."),

(L,"第117條",2,"第一種壓力容器-變更檢查",
 "第一種壓力容器經修改致哪些部分變動時應申請變更檢查？修改達何程度應重辦型式檢查？",
 ["胴體、集管器、端板、管板、頂蓋板、補強支撐有變動者應申請變更檢查；胴體或集管器修改達三分之一以上，或端板管板全部修改者，應依第95條規定辦理","胴體、集管器、端板、管板、頂蓋板、補強支撐有變動者應申請變更檢查；胴體或集管器修改達五分之一以上，或端板管板半數修改者，應重新辦理竣工檢查","僅安全閥、壓力表或安全裝置有變動者應申請變更檢查；胴體或集管器修改達二分之一以上者，僅需檢附變更部分圖件報請檢查機構備查而無須重辦型式檢查","僅內容物種類或操作溫度有變動者應申請變更檢查；不論胴體集管器端板管板修改達何程度，均得於下次定期檢查時一併查核而無須另行申請變更檢查"],"a",
 "第117條：第一種壓力容器經修改致其胴體、集管器、端板、管板、頂蓋板、補強支撐等有變動者，所有人或雇主應向所在地檢查機構申請變更檢查；變更檢查合格者，檢查員應在原檢查合格證記事欄內記載檢查日期、變更部分及檢查結果；胴體或集管器經修改達三分之一以上，或其端板、管板全部修改者，應依第95條規定（型式檢查）辦理。",
 "Which modifications require an alteration inspection of a Class 1 pressure vessel, and when is a type inspection redone?",
 ["Changes to the shell, header, end plate, tube plate, cover plate or stays require an alteration inspection; a shell or header modified by a third, or plates wholly replaced, falls under Article 95","Changes to the shell, header, end plate, tube plate, cover plate or stays require an alteration inspection; a shell or header modified by a fifth, or half the plates, means redoing the completion inspection","Only changes to the safety valve, pressure gauge or safety devices require an alteration inspection; a shell or header modified by a half needs only drawings filed for recordation without a fresh type inspection","Only a change of contents or operating temperature requires an alteration inspection; however far the shell, header, end plate or tube plate is modified it may simply be reviewed at the next periodic inspection"],
 "Article 117."),

(L,"第118條",2,"第一種壓力容器-變更申請",
 "所有人或雇主申請第一種壓力容器變更檢查時，應檢附哪些書件？",
 ["製造設施型式檢查合格證明、明細表二份、變更部分圖件、構造詳圖及強度計算書各二份（檢查機構認無必要者得免）、前經檢查合格證明或其影本","製造設施型式檢查合格證明、熔接明細表二份、施工位置分類圖一份、熔接技術士資格證件及熔接程序資格檢定紀錄影本各一份等相關文件","設置場所及設備周圍狀況圖二份、內容物種類申報表、安全閥吹洩量計算書、壓力表校正報告及操作人員名冊各一份等現場管理性質之文件","公司登記證明文件、工廠登記證影本、最近三年財務報表、勞工保險投保名冊及職業安全衛生管理計畫各一份等行政管理性質之相關文件"],"a",
 "第118條：所有人或雇主申請第一種壓力容器變更檢查時，應填具變更檢查申請書一份，並檢附製造設施型式檢查合格證明、第一種壓力容器明細表二份、變更部分圖件、構造詳圖及強度計算書各二份（但檢查機構認無必要者得免檢附）、前經檢查合格證明或其影本；第102條第3項及第103條規定於變更檢查時準用之。",
 "What documents must accompany an application for a Class 1 pressure vessel's alteration inspection?",
 ["The facility type inspection certificate, two specification tables, drawings of the altered part, two sets each of detailed drawings and strength calculations (waivable), and the previous certificate or a copy","The facility type inspection certificate, two welding schedules, one work position classification chart, the welders' skill certificates and one copy each of the welding procedure specification and the qualification records","Two drawings of the site and the surroundings of the equipment, a declaration of the contents, safety valve blow-off calculations, a pressure gauge calibration report and the operator roster","The company registration documents, a copy of the factory registration, three years of financial statements, the labor insurance roster and the occupational safety and health management plan"],
 "Article 118."),

(L,"第119條",2,"第一種壓力容器-必要措施",
 "檢查機構實施第一種壓力容器各項檢查認有必要時，得告知所有人或雇主為哪些措施？",
 ["除去被檢查物體上被覆物之全部或一部、拔出鉚釘或管、在板上或管上鑽孔、熱交換器之分解及其他必要事項；鑽孔部分申請人得申請改以非破壞檢查","除去被檢查物體上被覆物之全部或一部、拔出鉚釘或管、在板上或管上鑽孔、鑄鐵鍋爐之解體及其他必要事項；惟均不得以非破壞檢查方式替代其實施","僅得要求除去被檢查物體上被覆物之全部或一部；其餘拔出鉚釘或管、鑽孔及熱交換器之分解等，均應報請中央主管機關逐案核准後始得為之","僅得要求所有人提供構造詳圖及強度計算書等文件供審查；不得要求為除去被覆物、拔出鉚釘或管、鑽孔或分解等影響設備完整性之措施"],"a",
 "第119條：檢查機構於實施第一種壓力容器之構造檢查、竣工檢查、定期檢查、重新檢查或變更檢查認有必要時，得告知所有人、雇主或其代理人為除去被檢查物體上被覆物之全部或一部、拔出鉚釘或管、在板上或管上鑽孔、熱交換器之分解及其他認為必要事項；其中鑽孔部分，申請人得申請改以非破壞檢查，並提出證明文件。鍋爐部分則列鑄鐵鍋爐之解體（第94條）。",
 "What measures may the agency require for a Class 1 pressure vessel when it deems them necessary?",
 ["Removing all or part of the covering, drawing out rivets or tubes, drilling holes in plates or tubes, dismantling a heat exchanger and other necessary steps; drilling may be replaced by NDT on application","Removing all or part of the covering, drawing out rivets or tubes, drilling holes in plates or tubes, dismantling a cast iron boiler and other necessary steps; none of these may be replaced by NDT at all","Only removal of all or part of the covering may be required; drawing out rivets or tubes, drilling and dismantling a heat exchanger all need case-by-case approval of the central competent authority","Only production of detailed drawings and strength calculations for review may be required; no removal of covering, drawing of rivets, drilling or dismantling that affects integrity may be demanded"],
 "Article 119; cf. Article 94."),

(L,"第120條",2,"高壓氣體特定設備-型式檢查",
 "高壓氣體特定設備之製造或修改，其型式檢查之品管品保規定準用何條？未合格有何限制？",
 ["品管、品保措施、設備及人員準用第96條規定；未經檢查合格不得製造或修改，但與業經型式檢查合格之型式及條件相同者不在此限","品管、品保措施、設備及人員準用第11條規定；未經檢查合格仍得製造，僅不得對外銷售或出租，且應於出廠前補辦型式檢查","品管、品保措施、設備及人員準用第145條規定；未經檢查合格不得製造，但外國進口之高壓氣體特定設備完全不受本規則限制","品管、品保措施、設備及人員由製造人自行訂定；未經檢查合格得先行製造，並於竣工檢查前補辦型式檢查手續即為已足"],"a",
 "第120條：高壓氣體特定設備之製造或修改，製造人應於事前填具型式檢查申請書，檢附型式、構造詳圖及強度計算書、製造與檢查設備之種類能力及數量、主任設計者與施工負責人學經歷概要、施工者資格及人數，以熔接製造或修改者並附熔接人員資格證件、熔接程序規範及資格檢定紀錄；型式檢查之品管、品保措施、設備及人員準用第96條規定；未經檢查合格，不得製造或修改，但與業經型式檢查合格之型式及條件相同者不在此限。",
 "Which article governs quality control for a high pressure gas special equipment type inspection, and what if it fails?",
 ["Quality control measures, facilities and personnel follow Article 96; without passing it may not be made or modified, except for a type and conditions already passed","Quality control measures, facilities and personnel follow Article 11; it may still be made without passing, only sale or lease being barred, with the papers done before shipment","Quality control measures, facilities and personnel follow Article 145; without passing it may not be made, though imported equipment is wholly outside these Rules","Quality control measures, facilities and personnel are set by the maker itself; it may be made without passing so long as the type inspection precedes the completion inspection"],
 "Article 120."),

(L,"第121條",2,"高壓氣體特定設備-熔接檢查",
 "以熔接製造之高壓氣體特定設備，於何種情形得免申請熔接檢查？",
 ["附屬設備或僅對不產生壓縮應力以外之應力部分施以熔接者；或僅就內徑三百公厘以下管之圓周接頭、加強材料管管台凸緣閥座熔接於胴體端板、支持架等不承受壓力物件之熔接及防漏熔接者","附屬設備或僅對產生壓縮應力部分施以熔接者；或僅就內徑六百公厘以下管之圓周接頭、加強材料管管台凸緣閥座熔接於胴體端板、支持架等承受壓力物件之熔接及防漏熔接者，均得免申請","凡以熔接製造之高壓氣體特定設備均應申請熔接檢查而無任何例外；惟檢查機構得視情形要求製造人另行實施熱處理檢查、放射線檢查及熔接部之機械性能試驗等項目","凡設計壓力未超過每平方公分十公斤或內容積未超過一立方公尺者均得免申請熔接檢查；其餘情形應於製造完成後併同構造檢查一併向檢查機構申請辦理熔接檢查"],"a",
 "第121條：以熔接製造之高壓氣體特定設備，應於施工前由製造人向製造所在地檢查機構申請熔接檢查；但附屬設備或僅對不產生壓縮應力以外之應力部分施以熔接者，或僅就內徑三百公厘以下之管之圓周接頭、加強材料管管台凸緣及閥座等熔接在胴體或端板上、支持架或其他不承受壓力之物件熔接於胴體端板、防漏熔接等部分施以熔接者，不在此限。熔接檢查項目為材料檢查、外表檢查、熔接部之機械性能試驗、放射線檢查、熱處理檢查及其他必要檢查。",
 "When is welded high pressure gas special equipment exempt from applying for a welding inspection?",
 ["Where only accessories or parts bearing stresses other than compressive are welded; or where welding is confined to circumferential joints of pipes up to 300 mm bore, reinforcements, nozzles, flanges and valve seats, non-pressure supports and seal welds","Where only accessories or parts bearing compressive stress are welded; or where welding is confined to circumferential joints of pipes up to 600 mm bore, reinforcements, nozzles, flanges and valve seats, pressure-bearing supports and every seal weld","Every welded high pressure gas special equipment must apply for a welding inspection with no exception; the agency may however require heat treatment inspection, radiography and mechanical property testing of the weld as it sees fit","Any equipment whose design pressure is not over 10 kg/cm2 or whose volume is not over one cubic metre is exempt; otherwise the welding inspection is applied for together with the structural inspection after manufacture"],
 "Article 121."),

(L,"第122條",2,"高壓氣體特定設備-熔接申請",
 "製造人申請高壓氣體特定設備熔接檢查時，應檢附哪些書件？",
 ["材質證明一份、熔接明細表二份及施工位置分類圖一份、構造詳圖及強度計算書各二份、熔接技術士資格證件、型式檢查合格證明與熔接程序規範及資格檢定紀錄影本各一份","材質證明二份、設備設置場所及周圍狀況圖一份、內容物種類申報表、安全閥吹洩量計算書、壓力指示裝置校正紀錄及操作人員名冊各一份等現場性質文件","加蓋構造檢查合格戳記之明細表二份、竣工檢查結果報告表一份、耐壓試驗紀錄、絕熱性能試驗報告及非破壞檢查報告書各一份，並附前經檢查合格證明影本","公司登記證明文件、工廠登記證影本、勞工保險投保名冊、職業安全衛生管理計畫、自動檢查計畫及緊急應變計畫各一份等行政管理性質之相關文件"],"a",
 "第122條：製造人申請高壓氣體特定設備之熔接檢查時，應填具熔接檢查申請書，並檢附材質證明一份、熔接明細表二份及施工位置分類圖一份、構造詳圖及強度計算書各二份、熔接施工人員之熔接技術士資格證件、製造設施型式檢查合格證明與熔接程序規範及熔接程序資格檢定紀錄等影本各一份。",
 "What documents must accompany a welding inspection application for high pressure gas special equipment?",
 ["One material certificate, two welding schedules and one work position chart, two sets each of detailed drawings and strength calculations, welders' certificates, and one copy each of the type certificate and welding procedure records","Two material certificates, one drawing of the site and surroundings, a declaration of contents, safety valve blow-off calculations, pressure indicator calibration records and the operator roster, one copy of each of them","Two specification tables bearing the structural inspection stamp, one completion inspection result report, pressure test records, an insulation performance report and a non-destructive testing report, plus the previous certificate","The company registration documents, a copy of the factory registration, the labor insurance roster, the safety and health management plan, the automatic inspection plan and the emergency response plan, one each"],
 "Article 122."),

(L,"第123條",1,"高壓氣體特定設備-熔接程序",
 "檢查機構實施高壓氣體特定設備熔接檢查之程序及現場準備事項為何？",
 ["應就書件先行審查合格後實施現場實物檢查；現場檢查時製造人或其指派人員應在場，並事前備妥機械性能試驗片及放射線檢查","應先實施現場實物檢查合格後再審查書件；現場檢查時雇主或其指派人員應在場，並事前備妥荷重試驗用荷物及必要吊掛器具","得僅實施書面審查而免現場實物檢查；如認有必要實施現場檢查時，由檢查機構自行備妥機械性能試驗片及放射線檢查設備","應由製造人自行實施現場實物檢查並作成紀錄；檢查機構僅就其提送之紀錄實施書面審查，並將審查結果通知申請人即可"],"a",
 "第123條：檢查機構實施高壓氣體特定設備之熔接檢查時，應就製造人檢附之書件先行審查合格後，依熔接檢查項目實施現場實物檢查；實施現場實物檢查時，製造人或其指派人員應在場，並應事前備妥機械性能試驗片及放射線檢查。鍋爐（第75條）、第一種壓力容器（第99條）亦同。",
 "What is the procedure and on-site preparation for a welding inspection of high pressure gas special equipment?",
 ["Documents are reviewed and approved first, then the object is inspected on site; the maker or a designee attends and prepares mechanical test pieces and radiographic examination","The object is inspected on site and passed first, then the documents are reviewed; the employer or a designee attends and prepares the load test loads and the necessary rigging gear","A documentary review alone suffices with no on-site inspection; where one is thought necessary, the agency itself prepares the mechanical test pieces and the radiographic equipment","The maker inspects the object on site itself and records it; the agency merely reviews the records submitted and notifies the applicant of the outcome of that review"],
 "Article 123."),

(L,"第124條",1,"高壓氣體特定設備-熔接合格",
 "高壓氣體特定設備經熔接檢查合格者，檢查機構應如何處理？",
 ["在熔接明細表上加蓋熔接檢查合格戳記，檢查員簽章後交付申請人一份作為熔接檢查合格證明，並在物體明顯部位打印","在設備明細表上加蓋構造檢查合格戳記，檢查員簽章後交付申請人二份作為熔接檢查合格證明，並核發檢查合格證","逕行核發高壓氣體特定設備檢查合格證及竣工檢查結果報告表，有效期限最長一年，並由雇主置掛於作業場所明顯處","由製造人自行於熔接明細表註記熔接檢查合格後留存備查，檢查機構僅須以書面將檢查結果通知申請人即無須打印"],"a",
 "第124條：高壓氣體特定設備經熔接檢查合格者，檢查機構應在熔接明細表上加蓋熔接檢查合格戳記，檢查員簽章後交付申請人一份，做為熔接檢查合格證明，並應在被檢查物體上明顯部位打印，以資識別。第126條第1項第3款：申請構造檢查時，以熔接製造者應附加蓋熔接檢查合格戳記之熔接明細表。",
 "How does the agency handle high pressure gas special equipment that passes its welding inspection?",
 ["It stamps the welding schedule with the welding pass mark, the inspector signs, one copy is given as proof, and the object is marked conspicuously for identification","It stamps the equipment specification table with the structural pass mark, the inspector signs, two copies are given as proof, and a certificate is issued as well","It directly issues the equipment inspection certificate and a completion inspection result report valid at most one year, posted conspicuously at the workplace","The maker notes the welding pass on the welding schedule itself and keeps it, the agency merely notifying the applicant in writing without marking the object"],
 "Article 124."),

(L,"第125條",2,"高壓氣體特定設備-構造檢查",
 "高壓氣體特定設備之塔、槽等本體完成時，應向何機構申請構造檢查？有無例外？",
 ["應由製造人向製造所在地檢查機構申請；但在設置地組合之分割組合式者，得在安裝前向設置所在地檢查機構申請","應由雇主向設置所在地檢查機構申請；但在工廠一次製造完成者，得於出廠前向製造所在地檢查機構申請辦理","應由所有人向中央主管機關指定之代行檢查機構申請；但分割組合式者一律應於全部組裝完成並試車後始得申請","應由製造人向中央主管機關申請並取得認可證明；但分割組合式者得由雇主於設置完成後併同竣工檢查一併申請"],"a",
 "第125條：製造高壓氣體特定設備之塔、槽等本體完成時，應由製造人向製造所在地檢查機構申請構造檢查；但在設置地組合之分割組合式高壓氣體特定設備，得在安裝前，向設置所在地檢查機構申請構造檢查。第一種壓力容器（第101條）亦有相同例外規定。",
 "To which agency is the structural inspection of a completed high pressure gas tower or tank applied for?",
 ["The maker applies to the agency where it is made; a sectional one assembled on site may be applied for before installation to the agency of the site","The employer applies to the agency of the installation site; one wholly built in the factory may be applied for before shipment to the making agency","The owner applies to a designated inspection body; a sectional one may only be applied for after it is fully assembled and trial run on site","The maker applies to the central competent authority for recognition; a sectional one may be applied for with the completion inspection afterwards"],
 "Article 125; cf. Article 101."),

(L,"第126條",3,"高壓氣體特定設備-構造項目",
 "高壓氣體特定設備構造檢查之項目，與第一種壓力容器相較有何特別之處？",
 ["除施工方法、材料厚度、構造、尺寸、最高使用壓力、強度計算審查、人孔、清掃孔、安全裝置之規劃及耐壓試驗外，另包括超低溫設備之絕熱性能試驗","除施工方法、材料厚度、構造、尺寸及最高使用壓力外，另包括荷重試驗與安定性試驗；至於耐壓試驗及安全裝置之規劃則不列為構造檢查之項目","除外觀檢查及外部腐蝕裂痕變形之檢測外，另包括易腐蝕處之定點超音波測厚；至於強度計算審查及人孔清掃孔則於竣工檢查時始一併實施","除材料檢查、外表檢查及熔接部之機械性能試驗外，另包括放射線檢查與熱處理檢查；至於材料厚度及尺寸則由製造人自行確認後報請備查"],"a",
 "第126條第3項、第4項：高壓氣體特定設備構造檢查項目為施工方法、材料厚度、構造、尺寸、最高使用壓力、強度計算審查、人孔、清掃孔、安全裝置之規劃、耐壓試驗、超低溫設備之絕熱性能試驗、胴體端板管板等使用之材料及其他必要之檢查；其中超低溫設備之絕熱性能試驗，得採絕熱性能相關佐證文件資料認定之。",
 "How does the structural inspection of high pressure gas special equipment differ from a Class 1 vessel's?",
 ["Besides construction method, thickness, structure, dimensions, maximum working pressure, strength review, manholes, cleaning holes, safety device layout and pressure testing, it adds the insulation performance test for cryogenic equipment","Besides construction method, thickness, structure, dimensions and maximum working pressure, it adds load testing and stability testing; pressure testing and safety device layout are not part of the structural inspection at all in any case","Besides visual inspection and detection of external corrosion, cracking and deformation, it adds spot ultrasonic thickness measurement; strength review, manholes and cleaning holes wait for the completion inspection","Besides material inspection, surface inspection and mechanical property testing of the weld, it adds radiography and heat treatment inspection; thickness and dimensions are simply confirmed by the maker and filed"],
 "Article 126, Paragraphs 3-4."),

(L,"第126條",2,"高壓氣體特定設備-構造申請",
 "製造人申請高壓氣體特定設備構造檢查時，應檢附哪些書件？何種情形得免檢附部分書件？",
 ["設備明細表二份、構造詳圖及強度計算書各二份、以熔接製造者附加蓋熔接合格戳記之熔接明細表、以鉚接製造者附型式檢查合格證明；由同一檢查機構實施熔接及構造檢查者得免檢附後二者","設備明細表一份、設置場所及周圍狀況圖二份、內容物種類申報表及安全閥吹洩量計算書各一份；凡經型式檢查合格者，一律得免檢附全部書件而由檢查機構逕依型式檢查紀錄認定","熔接明細表二份、施工位置分類圖一份、熔接技術士資格證件及熔接程序資格檢定紀錄影本各一份；由不同檢查機構實施熔接及構造檢查者，始得免檢附構造詳圖及強度計算書","公司登記證明文件、工廠登記證影本、勞工保險投保名冊及自動檢查計畫各一份；凡屬外國進口之設備，得免檢附前經檢查合格證明文件並由雇主自行出具切結書替代"],"a",
 "第126條第1項、第2項：申請構造檢查應檢附高壓氣體特定設備明細表二份、構造詳圖及強度計算書各二份、以熔接製造者附加蓋熔接檢查合格戳記之熔接明細表、以鉚接製造者附製造設施型式檢查合格證明；由同一檢查機構實施同一座設備之熔接檢查及構造檢查者，得免檢附第2款、第3款之書件。",
 "What documents accompany a structural inspection application for high pressure gas special equipment, and when may some be omitted?",
 ["Two specification tables, two sets each of drawings and strength calculations, a stamped welding schedule if welded, a type certificate if riveted; where one agency does both the welding and structural inspections the latter two may be omitted","One specification table, two drawings of the site and surroundings, a declaration of contents and safety valve blow-off calculations; wherever the type inspection has been passed all documents may be omitted and the type record relied on","Two welding schedules, one work position chart, welders' certificates and one copy of the welding procedure qualification records; only where different agencies do the welding and structural inspections may drawings and calculations be omitted","The company registration documents, a copy of the factory registration, the labor insurance roster and the automatic inspection plan; for imported equipment the previous certificate may be omitted and an employer's affidavit used"],
 "Article 126, Paragraphs 1-2."),

(L,"第127條",1,"高壓氣體特定設備-構造準備",
 "檢查機構實施高壓氣體特定設備構造檢查時，製造人應事先備妥何事項？",
 ["製造人或其指派人員應在場，並事先將被檢查物件放置於易檢查位置及準備水壓等耐壓試驗","製造人或其指派人員應在場，並事先將被檢查物件加熱至常用溫度及準備放射線檢查設備","雇主或其指派人員應在場，並事先將被檢查物件移至戶外空曠處及準備荷重試驗用荷物","所有人或其代理人應在場，並事先將被檢查物件完全分解為零件及準備氣密試驗用氣體"],"a",
 "第127條：檢查機構實施高壓氣體特定設備之構造檢查時，製造人或其指派人員應在場，並應事先備妥將被檢查物件放置於易檢查位置、準備水壓等耐壓試驗。第139條第2項、第142條第2項：重新檢查及變更檢查準用第126條第3項及第127條規定。",
 "What must the maker prepare for the structural inspection of high pressure gas special equipment?",
 ["The maker or a designee attends and beforehand places the object where it is easy to inspect and prepares a hydrostatic or other pressure test","The maker or a designee attends and beforehand heats the object to its usual working temperature and prepares the radiographic testing equipment","The employer or a designee attends and beforehand moves the object to an open outdoor area and prepares the loads to be used in the load test","The owner or an agent attends and beforehand dismantles the object completely into parts and prepares the gas used for the airtightness test"],
 "Article 127."),

(L,"第128條",1,"高壓氣體特定設備-構造合格",
 "高壓氣體特定設備經構造檢查合格者，檢查機構應如何處理？",
 ["在設備明細表上加蓋構造檢查合格戳記，檢查員簽章後交付申請人一份作為構造檢查合格證明，並在物體明顯部位打印","在熔接明細表上加蓋熔接檢查合格戳記，檢查員簽章後交付申請人二份作為構造檢查合格證明，並核發檢查合格證","逕行核發高壓氣體特定設備檢查合格證及定期檢查結果報告表，有效期限最長二年，並由雇主置掛於作業場所明顯處","由製造人自行於設備明細表註記構造檢查合格後留存備查，檢查機構僅須以書面將檢查結果通知申請人即無須打印"],"a",
 "第128條：高壓氣體特定設備經構造檢查合格者，檢查機構應在高壓氣體特定設備明細表上加蓋構造檢查合格戳記，檢查員簽章後交付申請人一份，做為構造檢查合格證明，並應在被檢查物體上明顯部位打印，以資識別。第130條第1項第1款：申請竣工檢查時應檢附加蓋構造檢查或重新檢查合格戳記之明細表。",
 "How does the agency handle high pressure gas special equipment passing its structural inspection?",
 ["It stamps the equipment specification table with the structural pass mark, the inspector signs, one copy is given as proof, and the object is marked conspicuously","It stamps the welding schedule with the welding pass mark, the inspector signs, two copies are given as structural proof, and an inspection certificate is issued","It directly issues the equipment inspection certificate and a periodic inspection result report valid at most two years, posted conspicuously at the workplace","The maker notes the structural pass on the specification table itself and keeps it, the agency merely notifying the applicant in writing without any marking"],
 "Article 128."),

(L,"第129條",1,"高壓氣體特定設備-竣工檢查",
 "高壓氣體特定設備設置完成時，雇主應辦理何事？未經竣工檢查合格有何限制？",
 ["應向檢查機構申請竣工檢查，未經竣工檢查合格不得使用；實施竣工檢查時雇主或其指派人員應在場","應向檢查機構申請構造檢查，未經構造檢查合格不得設置；實施構造檢查時製造人或其指派人應在場","應向中央主管機關申請型式檢查，未經型式檢查合格不得使用；檢查時主任設計者及施工者應在場","應向當地主管機關報請備查後即得使用，並於使用滿二年後再併同定期檢查補辦竣工檢查之手續"],"a",
 "第129條：雇主於高壓氣體特定設備設置完成時，應向檢查機構申請竣工檢查；未經竣工檢查合格，不得使用；檢查機構實施竣工檢查時，雇主或其指派人員應在場。第130條：竣工檢查合格者核發竣工檢查結果報告表及檢查合格證，有效期限最長為一年。",
 "What must an employer do once high pressure gas special equipment is installed, and what if it has not passed?",
 ["Apply to the agency for a completion inspection; without passing it may not be used, and the employer or a designee must attend the inspection","Apply to the agency for a structural inspection; without passing it may not be installed, and the maker or a designee must attend the inspection","Apply to the central competent authority for a type inspection; without passing it may not be used, the chief designer and workers attending","File it with the local competent authority and use may begin, the completion inspection being made up with the periodic one two years later"],
 "Article 129."),

(L,"第130條",2,"高壓氣體特定設備-竣工項目",
 "高壓氣體特定設備竣工檢查之項目及合格證有效期限為何？",
 ["項目為安全閥數量、容量、吹洩試驗、安全裝置、壓力指示裝置及其他必要之檢查；合格證有效期限最長為一年","項目為施工方法、材料厚度、構造、尺寸、最高使用壓力及強度計算審查等；合格證有效期限最長為二年並得延長","項目為材料檢查、外表檢查、熔接部機械性能試驗及放射線檢查等；合格證有效期限最長為三年並由雇主自行認定","項目為外觀檢查、外部腐蝕裂痕變形之檢測及定點超音波測厚等；合格證有效期限最長為五年並應每年重新換發"],"a",
 "第130條：雇主申請高壓氣體特定設備竣工檢查時，應檢附加蓋構造檢查或重新檢查合格戳記之明細表及設備設置場所與周圍狀況圖；竣工檢查項目為安全閥數量、容量、吹洩試驗、安全裝置、壓力指示裝置及其他必要之檢查；經竣工檢查合格者核發竣工檢查結果報告表及檢查合格證，有效期限最長為一年。",
 "What does the completion inspection of high pressure gas special equipment cover, and how long is the certificate valid?",
 ["Number and capacity of safety valves, blow-off testing, safety devices, pressure indicating devices and other necessary checks; the certificate is valid at most one year","Construction method, material thickness, structure, dimensions, maximum working pressure and review of the strength calculations; valid at most two years and extendable","Material inspection, surface inspection, mechanical property testing of the weld and radiographic examination; valid at most three years as the employer itself determines","Appearance, detection of external corrosion, cracking and deformation and spot thickness measurement; valid at most five years but reissued every year in any event"],
 "Article 130."),

(L,"第131條",1,"高壓氣體特定設備-定期申請",
 "雇主應於何時向檢查機構申請高壓氣體特定設備之定期檢查？",
 ["應於檢查合格證有效期限屆滿前一個月，填具定期檢查申請書向檢查機構申請","應於檢查合格證有效期限屆滿前六個月，填具定期檢查申請書向檢查機構申請","應於檢查合格證有效期限屆滿後一個月內，填具定期檢查申請書向檢查機構申請","應於竣工檢查合格後每滿三年時，填具定期檢查申請書向中央主管機關提出申請"],"a",
 "第131條：雇主於高壓氣體特定設備檢查合格證有效期限屆滿前一個月，應填具定期檢查申請書向檢查機構申請定期檢查。第132條：定期檢查應每年實施外部檢查一次以上；內部檢查則依設備種類及使用材料，依該條附表所定期限（如儲槽使用沃斯田鐵系不銹鋼或鋁者十五年、鎳鋼十年等）實施。",
 "When must the employer apply for the periodic inspection of high pressure gas special equipment?",
 ["One month before the inspection certificate expires, by filing a periodic inspection application with the agency","Six months before the inspection certificate expires, by filing a periodic inspection application with the agency","Within one month after the inspection certificate has expired, by filing a periodic inspection application with it","Every three years after the completion inspection is passed, by applying to the central competent authority instead"],
 "Article 131; see Article 132."),

(L,"第133條",3,"高壓氣體特定設備-內部延長",
 "高壓氣體特定設備無法依規定期限實施內部檢查者，於何種情形得申請延長或以其他方式替代？",
 ["免設人孔或無法設置人孔掃除孔檢查孔者、冷箱平底低溫儲槽液氧液氮液氬儲槽低溫蒸發器等低溫或超低溫設備、內存觸媒分子篩或特殊內容物者、連續製程無法分隔者、隔膜式儲槽或無腐蝕之虞者及其他困難者","僅限於免設人孔或構造上無法設置人孔者一種情形；至於冷箱、低溫儲槽、內存觸媒或連續製程無法分隔之系統設備，均應於停機檢修時依規定期限實地實施內部檢查而不得申請延長或以其他檢查方式替代之","僅限於設備已使用滿二十年以上或設計壓力未超過每平方公分十公斤者；其餘情形一律應依所定期限實施內部檢查，不得申請延長內部檢查期限或以其他檢查方式替代其實施","僅限於經檢查機構認定外部檢查結果良好者；至於免設人孔、低溫或超低溫設備、內存觸媒、連續製程無法分隔或隔膜式儲槽等情形，均應報請中央主管機關逐案專案核准"],"a",
 "第133條第1項：雇主對於依規定免設人孔或構造上無法設置人孔、掃除孔或檢查孔者，冷箱、平底低溫儲槽、液氧儲槽、液氮儲槽、液氬儲槽、低溫蒸發器及其他低溫或超低溫之高壓氣體特定設備，內存觸媒、分子篩或其他特殊內容物者，連續生產製程中無法分隔之系統設備者，隔膜式儲槽或無腐蝕之虞者，及其他實施內部檢查困難者，得申請延長內部檢查期限或以其他檢查方式替代。",
 "In what cases may the internal inspection interval of high pressure gas special equipment be extended?",
 ["Manholes exempt or impossible; cold boxes, flat-bottomed, liquid oxygen, nitrogen or argon tanks, vaporisers and other cryogenic equipment; catalysts or special contents; inseparable continuous processes; diaphragm tanks or no corrosion risk","Only where manholes are exempt by rule or cannot structurally be fitted; cold boxes, low temperature tanks, equipment holding catalysts and systems inseparable in continuous production must all be internally inspected on time during a shutdown and may never be extended","Only where the equipment has been in service for twenty years or more or its design pressure is not over 10 kg/cm2; in every other case the internal inspection must be carried out on time with no extension and no substitute method","Only where the agency finds the external inspection results good; exempt manholes, cryogenic equipment, catalyst contents, inseparable continuous processes and diaphragm tanks all need case-by-case approval of the central competent authority"],
 "Article 133, Paragraph 1."),

(L,"第133條",3,"高壓氣體特定設備-延長程序",
 "高壓氣體特定設備申請延長內部檢查期限之時點、檢附資料及附屬設備之處理為何？",
 ["應於內部檢查有效期限屆滿前三個月，檢附安全衛生管理狀況、自動檢查計畫暨執行紀錄、構造檢查合格明細表影本、構造詳圖、生產流程圖、緊急應變處置計畫、自動控制系統及檢查替代方式建議報經檢查機構核定；有附屬鍋爐或第一種壓力容器者其檢查期限得隨同延長","應於內部檢查有效期限屆滿前一個月，檢附安全衛生管理狀況、自動檢查計畫暨執行紀錄、構造詳圖、生產流程圖、緊急應變處置計畫及自動控制系統等資料報經當地主管機關核定；有附屬鍋爐或第一種壓力容器者，其檢查期限仍應依原規定辦理而不得隨同延長之","應於內部檢查有效期限屆滿後三個月內，檢附最近一次外部檢查結果報告表、超音波測厚紀錄及耐壓試驗紀錄等資料報經中央主管機關追認；有附屬鍋爐或第一種壓力容器者，應另行分別提出延長之申請並各別核定","應於內部檢查有效期限屆滿前六個月，檢附設備設置場所及周圍狀況圖、內容物種類申報表及操作人員名冊等資料報經代行檢查機構核定；有附屬鍋爐或第一種壓力容器者，其檢查期限應相對縮短為原期限之半數"],"a",
 "第133條第1項：得於內部檢查有效期限屆滿前三個月，檢附其安全衛生管理狀況、自動檢查計畫暨執行紀錄、該設備之構造檢查合格明細表影本、構造詳圖、生產流程圖、緊急應變處置計畫、自動控制系統及檢查替代方式建議等資料，報經檢查機構核定後，延長其內部檢查期限或以其他檢查方式替代。第2項：該設備有附屬鍋爐或第一種壓力容器時，其檢查期限得隨同延長之。",
 "When, with what papers, and with what effect on attached plant is such an extension applied for?",
 ["Three months before the internal inspection period expires, attaching the safety management status, automatic inspection plan and records, a copy of the structural pass table, drawings, flow chart, emergency plan, control system and proposed substitute for the agency to approve; an attached boiler or Class 1 vessel may be extended with it","One month before the internal inspection period expires, attaching the safety management status, automatic inspection plan and records, detailed drawings, the production flow chart, the emergency response plan and the automatic control system for the local competent authority to approve; an attached boiler or Class 1 vessel must still keep to its own original interval","Within three months after the internal inspection period expires, attaching the latest external inspection result report, ultrasonic thickness records and pressure test records for the central competent authority to ratify; an attached boiler or Class 1 vessel needs its own separate application","Six months before the internal inspection period expires, attaching drawings of the site and surroundings, a declaration of contents and the operator roster for the designated inspection body to approve; an attached boiler or Class 1 vessel has its interval halved accordingly"],
 "Article 133."),

(L,"第134條",2,"高壓氣體特定設備-內部檢查",
 "檢查機構受理高壓氣體特定設備內部檢查時，應使雇主預先辦理何事？檢查項目為何？",
 ["應使其預先將設備內部恢復常溫常壓、排放內容物、通風換氣、整理清掃內部；項目為內部表面檢查及厚度腐蝕裂痕變形污穢等檢測、必要時之非破壞檢查與依結果判定需要之耐壓試驗","應使其預先將設備加壓至設計壓力並保持低溫、封存內容物；項目為外觀檢查及外部腐蝕裂痕變形污穢洩漏之檢測、易腐蝕處之定點超音波測厚及附屬品與附屬裝置之檢查","應使其預先將設備完全解體為零件並運送至檢查機構；項目為材料檢查、外表檢查、熔接部之機械性能試驗、放射線檢查及熱處理檢查等以熔接品質為主之各項檢查","應使其預先備妥荷重試驗用荷物及必要之吊掛器具；項目為安全閥數量容量吹洩試驗、安全裝置、壓力指示裝置及設備周圍狀況等以配置事項為主之各項檢查"],"a",
 "第134條：檢查機構受理實施高壓氣體特定設備內部檢查時，應將檢查日期通知雇主，使其預先將設備之內部恢復至常溫、常壓、排放內容物、通風換氣、整理清掃內部及為其他定期檢查必要準備事項；內部檢查項目為設備內部之表面檢查及厚度、腐蝕、裂痕、變形、污穢等之檢測、必要時實施之非破壞檢查、以檢查結果判定需要實施之耐壓試驗及其他必要之檢查。",
 "What must the employer prepare for the internal inspection of high pressure gas special equipment, and what does it cover?",
 ["Restore the interior to normal temperature and pressure, drain contents, ventilate and clean it; the check covers internal surfaces, thickness, corrosion, cracking, deformation and fouling, NDT where needed and pressure testing if the results warrant","Pressurise to design pressure and keep it cold with contents sealed in; the check covers appearance, external corrosion, cracking, deformation, fouling and leakage, spot thickness measurement and the accessories and attachments, together with a blow-off test","Dismantle the equipment entirely into parts and deliver them to the inspection agency; the check covers material and surface inspection, mechanical property testing of welds, radiography and heat treatment inspection","Prepare the loads and rigging gear for the load test; the check covers safety valve numbers and blow-off testing, safety devices, pressure indicating devices and the state of the surroundings of the equipment"],
 "Article 134."),

(L,"第135條",2,"高壓氣體特定設備-外部檢查",
 "高壓氣體特定設備外部檢查之超音波測厚，於何種情形得免實施？",
 ["對具一體成形之保溫材、夾套型或因特別高溫等致測厚確有困難者，得免實施","對內容積未滿一立方公尺或使用未滿五年之設備，得由雇主自行決定免予實施","對經檢查機構認定外部無異狀者一律免實施，並得同時免除外觀檢查之項目","對低溫或超低溫設備一律免實施，並得以放射線檢查及熱處理檢查替代之"],"a",
 "第135條：高壓氣體特定設備外部檢查之項目為外觀檢查、外部之腐蝕、裂痕、變形、污穢、洩漏之檢測、必要時實施之非破壞檢查、易腐蝕處之定點超音波測厚及其他必要之檢查；必要時得以適當儀器檢測其內部，發現有異狀者應併實施內部檢查；超音波測厚對具一體成形之保溫材、夾套型或因特別高溫等致測厚確有困難者，得免實施。",
 "When may the spot ultrasonic thickness measurement in an external inspection of such equipment be waived?",
 ["Where integrally formed insulation or a jacketed type, or particularly high temperature, makes the measurement genuinely difficult to carry out","Where the internal volume is under one cubic metre or the equipment has been in service under five years, as the employer itself decides","Wherever the agency finds nothing unusual outside, in which case the visual inspection item may equally be dispensed with at the same time","For all low temperature or cryogenic equipment, radiographic examination and heat treatment inspection being carried out in its place instead"],
 "Article 135."),

(L,"第136條",1,"高壓氣體特定設備-定期效期",
 "高壓氣體特定設備經定期檢查合格者，其使用有效期限最長為何？",
 ["應於原檢查合格證上簽署，註明使用有效期限，最長為一年","應於原檢查合格證上簽署，註明使用有效期限，最長為三年","應重新核發檢查合格證，註明使用有效期限最長為五年","應重新核發檢查合格證，註明使用有效期限最長為十年"],"a",
 "第136條：檢查機構對經定期檢查合格之高壓氣體特定設備，應於原檢查合格證上簽署，註明使用有效期限，最長為一年；檢查員於實施定期檢查後，應填報高壓氣體特定設備定期檢查結果報告表，並將定期檢查結果通知雇主。第132條第1項：定期檢查應每年實施外部檢查一次以上。",
 "How long at most is high pressure gas special equipment valid after passing periodic inspection?",
 ["The original inspection certificate is endorsed with a valid period of at most one year","The original inspection certificate is endorsed with a valid period of at most three years","A new inspection certificate is issued with a valid period of at most five years thereafter","A new inspection certificate is issued with a valid period of at most ten years thereafter"],
 "Article 136."),

(L,"第137條",2,"高壓氣體特定設備-不合格",
 "高壓氣體特定設備經定期檢查不合格者，應如何處理？",
 ["檢查員應即於檢查合格證記事欄記載不合格情形並通知改善；情形嚴重有發生危害之虞者，應報請所屬檢查機構限制其最高使用壓力或禁止使用","檢查員應即註銷其檢查合格證並命令拆除該設備；情形輕微者始得於檢查合格證記事欄記載不合格情形，並限期一個月內完成各項之改善","檢查員應即函報中央主管機關逕行裁處罰鍰；情形嚴重有發生危害之虞者，另由中央主管機關公告該事業單位名稱及其不合格之具體情形","檢查員僅需以口頭告知雇主不合格情形即可；是否限制最高使用壓力或禁止使用，由雇主依營運需要自行決定並作成書面紀錄留存備查"],"a",
 "第137條：高壓氣體特定設備經定期檢查不合格者，檢查員應即於檢查合格證記事欄內記載不合格情形並通知改善；其情形嚴重有發生危害之虞者，並應報請所屬檢查機構限制其最高使用壓力或禁止使用。第88條（鍋爐）、第113條（第一種壓力容器）、第159條（高壓氣體容器）亦同。",
 "What must be done when high pressure gas special equipment fails its periodic inspection?",
 ["The inspector notes the failure in the remarks column of the certificate and calls for improvement; if serious enough to risk harm, the agency limits the working pressure or bans use","The inspector cancels the certificate at once and orders the equipment dismantled; only in slight cases is the failure noted in the remarks column with one month allowed to improve","The inspector reports it to the central competent authority to impose a fine; if serious enough to risk harm, that authority announces the undertaking's name and the defects found","The inspector need only tell the employer orally; whether to limit the working pressure or stop use is left to the employer as its operations require, with a written record kept"],
 "Article 137."),

(L,"第138條",3,"高壓氣體特定設備-重新檢查",
 "高壓氣體特定設備有下列何種情事之一時，應由所有人或雇主申請重新檢查？",
 ["從外國進口、構造重新竣工或定期檢查合格後閒置一年以上擬裝設或恢復使用、經禁止使用擬恢復使用、遷移裝置地點而重新裝設、擬提升最高使用壓力、擬變更內容物種類","從外國進口、構造重新竣工或定期檢查合格後閒置三個月以上擬恢復使用、更換操作人員、變更設置場所名稱、擬降低最高使用壓力、擬變更保溫材料之種類等情形","變更安全閥廠牌型號、更換壓力指示裝置、變更保養廠商、變更公司負責人、變更設備編號或塗裝顏色、變更設備所屬部門等管理性質事項之一者，均應申請重新檢查","僅限於從外國進口一種情事；其餘閒置一年以上、經禁止使用、遷移裝置地點、提升最高使用壓力或變更內容物種類者，均得於下次定期檢查時一併辦理而免申請"],"a",
 "第138條：高壓氣體特定設備有從外國進口、構造檢查重新檢查竣工檢查或定期檢查合格後經閒置一年以上擬裝設或恢復使用（但由檢查機構認可者不在此限）、經禁止使用擬恢復使用、遷移裝置地點而重新裝設、擬提升最高使用壓力、擬變更內容物種類等情事之一者，應由所有人或雇主向檢查機構申請重新檢查；對外國進口具有相當檢查證明文件者，檢查機構得免除全部或一部之檢查。",
 "Which circumstances require a re-inspection of high pressure gas special equipment?",
 ["Import from abroad; idleness over a year after a structural, re-, completion or periodic inspection with use to resume; resumption after a ban; relocation and reinstallation; raising the maximum working pressure; changing the contents","Import from abroad; idleness over three months after an inspection with use to resume; a change of operator; a change of the name of the site; lowering the maximum working pressure; or changing the kind of insulating material used on the shell","Changing the brand and model of the safety valve, replacing the pressure indicating device, changing the maintenance contractor, changing the company head, changing the equipment number or paint colour, or changing the owning department","Only import from abroad; idleness over a year, resumption after a ban, relocation, raising the maximum working pressure or changing the contents may all be handled at the next periodic inspection without any application"],
 "Article 138."),

(L,"第139條",2,"高壓氣體特定設備-重新申請",
 "所有人或雇主申請高壓氣體特定設備重新檢查時，應檢附哪些書件？",
 ["高壓氣體特定設備明細表二份、構造詳圖及強度計算書各二份（檢查機構認無必要者得免檢附）、前經檢查合格證明文件或其影本","高壓氣體特定設備明細表一份、設備設置場所及周圍狀況圖二份、內容物種類申報表、安全閥吹洩量計算書及操作人員名冊各一份","熔接明細表二份及施工位置分類圖一份、熔接技術士資格證件、熔接程序規範及熔接程序資格檢定紀錄影本各一份等相關文件","公司登記證明文件、工廠登記證影本、勞工保險投保名冊、自動檢查計畫及緊急應變計畫各一份等行政管理性質之相關文件"],"a",
 "第139條：所有人或雇主申請高壓氣體特定設備之重新檢查時，應填具重新檢查申請書，並檢附高壓氣體特定設備明細表二份、構造詳圖及強度計算書各二份（但檢查機構認無必要者得免檢附）、前經檢查合格證明文件或其影本；第126條第3項及第127條規定於重新檢查時準用之。",
 "What documents must accompany a re-inspection application for high pressure gas special equipment?",
 ["Two equipment specification tables, two sets each of detailed drawings and strength calculations (waivable if the agency finds them unnecessary), and the previous certificate or a copy","One equipment specification table, two drawings of the site and its surroundings, a declaration of the contents, safety valve blow-off calculations and the operator roster, one each","Two welding schedules and one work position classification chart, welders' skill certificates, and one copy each of the welding procedure specification and the qualification records","The company registration documents, a copy of the factory registration, the labor insurance roster, the automatic inspection plan and the emergency response plan, one copy of each"],
 "Article 139."),

(L,"第140條",3,"高壓氣體特定設備-重新合格",
 "高壓氣體特定設備經重新檢查合格者，檢查機構應如何處理？",
 ["在明細表加蓋重新檢查合格戳記交付一份作為證明以辦理竣工檢查；但屬閒置後停用或經禁止使用而未遷移裝設者，得在原合格證記載並註明有效期限最長一年","在明細表加蓋構造檢查合格戳記交付二份作為證明以辦理型式檢查；但屬外國進口者，得在原合格證記載檢查結果並註明使用有效期限最長二年而免予打印","逕行核發新檢查合格證並註明使用有效期限最長為二年；凡經重新檢查合格者一律免再辦理竣工檢查，外國進口者亦免於物體明顯部位打印以資識別","由所有人自行於明細表註記重新檢查合格後留存備查；檢查機構僅須將檢查結果通知申請人，由申請人逕行辦理竣工檢查而無須加蓋任何合格戳記"],"a",
 "第140條：高壓氣體特定設備經重新檢查合格者，檢查機構應在明細表上加蓋重新檢查合格戳記，交付申請人一份，做為重新檢查合格證明，以辦理竣工檢查；但符合第138條第2款之竣工檢查或定期檢查合格後停用或第3款（經禁止使用擬恢復使用），其未遷移裝設或遷移至廠內其他位置重新裝設，經檢查合格者，得在原檢查合格證上記載檢查日期、檢查結果及註明使用有效期限，最長為一年。外國進口者應在被檢查物體上明顯部位打印。",
 "How does the agency handle high pressure gas special equipment that passes re-inspection?",
 ["It stamps the specification table with the re-inspection pass mark and gives one copy as proof for the completion inspection; if idled or banned but not relocated, the original certificate is endorsed for at most one year","It stamps the specification table with the structural pass mark and gives two copies as proof for the type inspection; imported equipment may have the original certificate endorsed for at most two years without marking","It directly issues a new certificate valid at most two years; everything passing re-inspection is exempt from any completion inspection, and imported items need not be marked conspicuously either","The owner notes the re-inspection pass on the specification table itself and keeps it; the agency merely notifies the applicant, who proceeds to the completion inspection with no pass stamp at all"],
 "Article 140; see Article 138."),

(L,"第141條",2,"高壓氣體特定設備-變更檢查",
 "高壓氣體特定設備經修改致哪些部分變動時應申請變更檢查？修改達何程度應重辦型式檢查？",
 ["塔槽、胴體、端板、頂蓋板、管板、集管器或補強支撐有變動者應申請變更檢查；塔槽胴體或集管器修改達三分之一以上，或端板管板全部修改者，應依第120條規定辦理","塔槽、胴體、端板、頂蓋板、管板、集管器或補強支撐有變動者應申請變更檢查；塔槽胴體或集管器修改達五分之一以上，或端板管板半數修改者，應重新辦理竣工檢查","僅安全閥、壓力指示裝置或安全裝置有變動者應申請變更檢查；塔槽胴體或集管器修改達二分之一以上者，僅需檢附圖件報請檢查機構備查而無須重辦型式檢查","僅內容物種類或操作溫度有變動者應申請變更檢查；不論塔槽胴體集管器端板管板修改達何程度，均得於下次定期檢查時一併查核而無須另行申請變更檢查"],"a",
 "第141條：高壓氣體特定設備經修改致其塔槽、胴體、端板、頂蓋板、管板、集管器或補強支撐等有變動者，所有人或雇主應向所在地檢查機構申請變更檢查；變更檢查合格者，檢查員應在原檢查合格證記事欄內記載檢查日期、變更部分及檢查結果；其塔槽、胴體或集管器經修改達三分之一以上，或其端板、管板全部修改者，應依第120條規定（型式檢查）辦理。",
 "Which modifications require an alteration inspection of high pressure gas special equipment, and when is the type inspection redone?",
 ["Changes to the tower or tank, shell, end plate, cover plate, tube plate, header or stays require an alteration inspection; a tower, shell or header modified by a third, or plates wholly replaced, falls under Article 120","Changes to the tower or tank, shell, end plate, cover plate, tube plate, header or stays require an alteration inspection; a tower, shell or header modified by a fifth, or half the plates, means redoing the completion inspection","Only changes to the safety valve, pressure indicating device or safety devices require an alteration inspection; a tower, shell or header modified by a half needs only drawings filed for recordation without a fresh type inspection","Only a change of contents or operating temperature requires an alteration inspection; however far the tower, shell, header, end plate or tube plate is modified it may simply be reviewed at the next periodic inspection"],
 "Article 141."),

(L,"第142條",2,"高壓氣體特定設備-變更申請",
 "所有人或雇主申請高壓氣體特定設備變更檢查時，應檢附哪些書件？",
 ["製造設施型式檢查合格證明、設備明細表二份、變更部分圖件、構造詳圖及強度計算書各二份（檢查機構認無必要者得免）、前經檢查合格證明或其影本","製造設施型式檢查合格證明、熔接明細表二份、施工位置分類圖一份、熔接技術士資格證件及熔接程序資格檢定紀錄影本各一份等相關之文件","設備設置場所及周圍狀況圖二份、內容物種類申報表、安全閥吹洩量計算書、壓力指示裝置校正報告及操作人員名冊各一份等現場性質文件","公司登記證明文件、工廠登記證影本、最近三年財務報表、勞工保險投保名冊及職業安全衛生管理計畫各一份等行政管理性質之文件"],"a",
 "第142條：所有人或雇主申請高壓氣體特定設備變更檢查時，應填具變更檢查申請書一份，並檢附製造設施型式檢查合格證明、高壓氣體特定設備明細表二份、變更部分圖件、構造詳圖及強度計算書各二份（但檢查機構認無必要者得免檢附）、前經檢查合格證明或其影本；第126條第3項及第127條規定於變更檢查時準用之。",
 "What documents must accompany an alteration inspection application for high pressure gas special equipment?",
 ["The facility type inspection certificate, two equipment specification tables, drawings of the altered part, two sets each of detailed drawings and strength calculations (waivable), and the previous certificate or a copy","The facility type inspection certificate, two welding schedules, one work position classification chart, the welders' skill certificates and one copy each of the welding procedure specification and the qualification records","Two drawings of the site and the surroundings of the equipment, a declaration of the contents, safety valve blow-off calculations, a pressure indicator calibration report and the operator roster","The company registration documents, a copy of the factory registration, three years of financial statements, the labor insurance roster and the occupational safety and health management plan"],
 "Article 142."),

(L,"第143條",2,"高壓氣體特定設備-必要措施",
 "檢查機構實施高壓氣體特定設備各項檢查認有必要時，得告知所有人或雇主為哪些措施？",
 ["除去被檢查物體上被覆物之全部或一部、拔出鉚釘或管、在板上或管上鑽孔及其他認為必要事項；其中鑽孔部分，申請人得申請改以非破壞檢查並提出證明文件","除去被檢查物體上被覆物之全部或一部、拔出鉚釘或管、在板上或管上鑽孔及熱交換器之分解；惟各該措施均不得以非破壞檢查方式替代，亦不得提出證明文件申請","僅得要求除去被檢查物體上被覆物之全部或一部；其餘拔出鉚釘或管及在板上或管上鑽孔等破壞性措施，均應報請中央主管機關逐案核准後始得要求其實施","僅得要求所有人提供構造詳圖及強度計算書等文件供審查；不得要求為除去被覆物、拔出鉚釘或管或鑽孔等任何影響設備完整性之措施，以免造成設備損害"],"a",
 "第143條：檢查機構於實施高壓氣體特定設備之構造檢查、竣工檢查、定期檢查、重新檢查或變更檢查認有必要時，得告知所有人、雇主或其代理人為除去被檢查物體上被覆物之全部或一部、拔出鉚釘或管、在板上或管上鑽孔及其他認為必要事項；其中鑽孔部分，申請人得申請改以非破壞檢查，並提出證明文件。鍋爐另列鑄鐵鍋爐之解體（第94條）、第一種壓力容器另列熱交換器之分解（第119條）。",
 "What measures may the agency require for high pressure gas special equipment when it deems them necessary?",
 ["Removing all or part of the covering, drawing out rivets or tubes, drilling holes in plates or tubes and other necessary steps; drilling may be replaced by NDT on application with supporting documents","Removing all or part of the covering, drawing out rivets or tubes, drilling holes in plates or tubes and dismantling a heat exchanger; none of these may be replaced by NDT nor may any application be made","Only removal of all or part of the covering may be required; drawing out rivets or tubes and drilling holes in plates or tubes both need case-by-case approval of the central competent authority first","Only production of detailed drawings and strength calculations for review may be required; no removal of covering, drawing of rivets or drilling that affects the integrity of the equipment may be demanded"],
 "Article 143; cf. Articles 94 and 119."),
]
