# -*- coding: utf-8 -*-
# 第 7 批（C）：勞工健康服務專業機構管理規則、預防職業病健康檢查及健康追蹤檢查辦法、職業病鑑定作業實施辦法、職業災害勞工補助及核發辦法
HS = "OSH-76"; PH = "OSH-77"; OD = "OSH-78"; SB = "OSH-79"
Q = [
# ---------- 勞工健康服務專業機構管理規則（115/6/26，116/1/1 施行） ----------
(HS,"第3條",2,"健康服務機構-分類",
 "勞工健康服務專業機構分為哪兩類？乙類專業機構得辦理何種事業之勞工健康服務？",
 ["甲類及乙類；第二類及第三類事業且依勞工健康保護規則附表二無須配置職業醫學科專科醫師者","甲類及乙類；第一類及第二類事業且依勞工健康保護規則附表一必須配置職業醫學科專科醫師者","A 級及 B 級；第三類事業且依勞工健康保護規則附表二應配置專任護理人員二人以上者","一級及二級；第二類及第三類事業且經地方主管機關核准無須配置職業安全衛生管理人員者"],"a",
 "第2條：勞工健康服務指提供勞工健康管理職業病與工作相關疾病預防及健康促進等服務；專業機構指經中央主管機關認可並公布於指定網站接受委託辦理者；勞工健康服務人員指醫師護理人員心理師物理治療師職能治療師或公共衛生師；專一登錄人員指僅為該機構指派服務之人員。第3條：甲類辦理職安管理辦法第一類第二類及第三類事業之勞工健康服務；乙類辦理第二類及第三類事業且依保護規則附表二無須配置職醫者。",
 "Labor health service institutions are classified as, and Class B institutions may serve:",
 ["Class A and Class B; Class 2 and 3 enterprises not required to have an occupational medicine specialist under the Labor Health Protection Rules","Class A and Class B; Class 1 and 2 enterprises required to have an occupational medicine specialist under Appendix 1 of the Labor Health Protection Rules","Levels A and B; Class 3 enterprises required to appoint two or more full-time nurses under Appendix 2 of the Labor Health Protection Rules","Grades 1 and 2; Class 2 and 3 enterprises exempted by the local competent authority from appointing occupational safety and health managers"],
 "Articles 2–3."),

(HS,"第4條",3,"健康服務機構-甲類資格",
 "全民健康保險特約醫院或診所申請認可為甲類勞工健康服務專業機構，人力配置條件為何？",
 ["專一登錄人員至少四人（含醫師護理或相關人員至少二種類別且從事三年以上）、職醫至少一人、專一登錄人員達登錄人員總數百分之六十以上並指定一人綜理","專一登錄人員至少二人（含醫師護理或相關人員至少一種類別且從事一年以上）、職醫至少三人、專一登錄人員達登錄人員總數百分之三十以上並指定二人綜理","登錄人員至少六人（含心理師物理治療師至少三種類別且從事五年以上）、職醫至少二人、專一登錄人員達登錄人員總數百分之八十以上並由院長綜理","專一登錄人員至少四人（含公共衛生師職能治療師各一人且從事三年以上）、護理人員至少一人、兼職登錄人員達登錄人員總數百分之六十以上並指定一人綜理"],"a",
 "第4條：得申請甲類者為經認可之勞工特殊體格及健康檢查醫療機構聘僱職醫綜理業務者、經認可之勞工健康顧問服務類顧問機構、或健保特約醫院診所且專一登錄人員至少四人（醫師護理人員或相關人員至少二種類別且從事勞工健康服務三年以上）職醫至少一人專一登錄人員達登錄人員總數百分之六十以上並指定一人綜理。第5條：乙類為健保特約醫院診所且服務人員至少二人其中至少一人為專一登錄之醫師或護理人員從事三年以上、專一登錄人員達百分之五十以上並指定綜理者。第6條：每年一月四月七月或十月申請認可。第8條：認可有效期間最長五年，屆滿前三個月重新申請。",
 "A NHI-contracted hospital or clinic applying as a Class A institution must staff:",
 ["At least four exclusively registered staff (at least two professional categories with 3+ years' experience), at least one occupational medicine specialist, and exclusive staff making up 60%+ of registered personnel with one designated coordinator","At least two exclusively registered staff (at least one professional category with 1+ year of experience), at least three occupational medicine specialists, and exclusive staff making up 30%+ of registered personnel with two designated coordinators","At least six registered staff (at least three categories including psychologists and physiotherapists with 5+ years' experience), at least two occupational medicine specialists, and exclusive staff making up 80%+ of personnel, coordinated by the superintendent","At least four exclusively registered staff (one public health specialist and one occupational therapist with 3+ years' experience), at least one nurse, and part-time registered staff making up 60%+ of registered personnel with one designated coordinator"],
 "Articles 4–8."),

(HS,"第9條",3,"健康服務機構-變更",
 "勞工健康服務專業機構之登記地址、登錄人員、綜理業務人員變更時，應於變更之次日起幾日內申請變更？停業歇業等情形應於事實發生後幾日內申請廢止認可？",
 ["十五日；三十日","三日；七日","三十日；六十日","七日；十五日"],"a",
 "第9條：登記地址或聯絡方式、登錄人員、指定之綜理業務人員及其他公告事項變更應於變更次日起十五日內申請變更；登錄人員變更未經核定前不得辦理服務；停業或歇業、原認可條件變更致不符、終止辦理服務等應於事實發生後三十日內主動申請廢止認可，中央主管機關亦得逕予廢止。",
 "Changes of address, registered personnel or the coordinator must be filed within how many days, and closure or termination must be reported for revocation within:",
 ["15 days; 30 days","3 days; 7 days","30 days; 60 days","7 days; 15 days"],
 "Article 9."),

(HS,"第10條",3,"健康服務機構-在職訓練",
 "勞工健康服務專業機構之服務人員，在職教育訓練每三年合計至少幾小時？職醫每三年至少幾小時？數位學習時數採計上限？",
 ["十二小時（每類課程至少二小時）；二小時；六小時","六小時（每類課程至少一小時）；六小時；三小時","二十四小時（每類課程至少四小時）；十二小時；十二小時","十二小時（每類課程至少三小時）；四小時；八小時"],"a",
 "第10條：服務人員應接受職安或災保法規、職場健康風險評估及管理實務課程之在職教育訓練，每三年合計至少十二小時且每類課程至少二小時，紀錄保存三年；職醫接受法規課程每三年至少二小時；得於中央主管機關網站接受數位學習，採計不超過六小時；訓練得由主管機關勞檢機構或認可機構訓練單位辦理。第11條：應訂定服務管理規章（組織權責、人員資格訓練、執行程序、文件紀錄管制），會同事業單位擬定服務規劃，臨場服務紀錄簽署建檔，保存三年，資訊應保密。",
 "Institution personnel need at least how many hours of in-service training every 3 years, occupational physicians at least, and e-learning is credited up to:",
 ["12 hours (at least 2 per course type); 2 hours; 6 hours","6 hours (at least 1 per course type); 6 hours; 3 hours","24 hours (at least 4 per course type); 12 hours; 12 hours","12 hours (at least 3 per course type); 4 hours; 8 hours"],
 "Articles 10–11."),

(HS,"第15條",3,"健康服務機構-處罰",
 "勞工健康服務專業機構有下列何種情形，依職安法第48條處以罰鍰？",
 ["認可後不符資格仍繼續辦理、未依認可類別辦理、辦理有虛偽不實、指派非經核定人員提供服務、未依警告改正","遲交年度服務報告、逾期辦理人員登錄、辦公室電話變更未通知、臨場服務紀錄未編頁碼、未張貼認可證書","認可證書遺失未補發、在職訓練遲一個月完成、服務規劃書未經工會簽章、紀錄僅保存二年、未設置服務專線","登記地址遷移已於三十日內申報、指派經核定人員代班、依警告如期改正、紀錄以電子檔保存、每年申請一次"],"a",
 "第14條：違反第9至12條者予以警告並限期改正。第15條：認可後未符第4或5條規定繼續辦理、未依認可類別辦理、辦理有虛偽不實、指派非經核定人員提供服務、未依前條改正者處罰鍰。第16條：屆期未改正或情節重大得撤銷廢止認可或停止業務，二年內不得以同一名稱地點或負責人申請。第17條：服務人員未每三年受訓、未依規定辦理或報告不實、未保密、違反事業單位規定、重複登錄等得註銷登錄，三年或五年內不得再登錄。第19條：自116年1月1日施行。",
 "An institution is fined under Article 48 of the OSH Act when it:",
 ["Continues operating without meeting qualifications, works outside its approved class, falsifies services, assigns unapproved personnel, or fails to correct after warning","Files its annual service report late, registers personnel after the deadline, changes its office phone without notice, leaves on-site records unpaginated, or fails to post its certificate","Loses its certificate without reapplying, finishes in-service training one month late, has its service plan unsigned by the union, keeps records only two years, or has no service hotline","Reports an address move within 30 days, assigns approved personnel as substitutes, corrects on time after a warning, keeps its records electronically, or applies once each year"],
 "Articles 14–17; effective January 1, 2027."),

# ---------- 勞工職業災害保險預防職業病健康檢查及健康追蹤檢查辦法（111/3/14） ----------
(PH,"第3條",2,"預防職業病健檢-資格",
 "被保險人從事附表一之有害作業，最近加保年資連續滿多久，得由投保單位向保險人申請預防職業病健康檢查？投保單位未申請時？",
 ["一年；被保險人得逕向保險人申請","六個月；被保險人應待投保單位申請","三年；被保險人得請雇主代為申請","一個月；被保險人得逕向醫院申請"],"a",
 "第2條：依災保法第63條第1項得申請預防職業病健康檢查之有害作業如附表一，第2項得申請健康追蹤檢查之有害作業如附表二，項目依勞工健康保護規則辦理。第3條：從事附表一作業最近加保年資連續滿一年者得由投保單位申請，未申請者被保險人得逕向保險人申請。第4條：曾從事附表二作業且加保期間年資連續滿一年者，於變更作業離職或退保後得由投保單位或勞工本人申請健康追蹤檢查，資格疑義得請認可醫療機構職醫協助評估。",
 "Insured workers in listed hazardous work with at least how much continuous insured seniority may have their employer apply for preventive occupational disease exams, and if the employer does not apply:",
 ["1 year; the worker may apply directly to the insurer","6 months; the worker must wait for the employer to apply","3 years; the worker may ask the employer to apply","1 month; the worker may apply directly to the hospital"],
 "Articles 2–4."),

(PH,"第5條",2,"預防職業病健檢-頻率",
 "預防職業病健康檢查及健康追蹤檢查，原則一年以幾次為限？檢查結果應通知何人？",
 ["一次；預防檢查通知投保單位被保險人及保險人，追蹤檢查通知受檢人及保險人","二次；預防檢查通知被保險人及雇主，追蹤檢查通知投保單位及勞工本人","不限次數；預防檢查僅通知投保單位，追蹤檢查僅通知認可醫療機構","每三年一次；預防檢查通知保險人及衛生局，追蹤檢查通知受檢人及雇主"],"a",
 "第5條：一年以一次為限，情形特殊經中央主管機關認有必要得另公告頻率。第6條：應填具申請書向保險人提出，審查符合者核發證明單並於規定時間受檢。第7條：醫療機構應符合辦理勞工體格與健康檢查醫療機構認可及管理辦法資格。第8條：結果依公告通報；預防職業病健康檢查後通知投保單位被保險人及保險人，健康追蹤檢查後通知受檢人及保險人；結果異常者中央主管機關得提供服務協助。第10條：費用參照健保支付標準核付。第11條：未經核定資格逕為檢查者不予核付。第12條：溢領誤領者限期返還。",
 "Preventive and follow-up exams are limited to how many per year, and results are notified to:",
 ["Once; the insured unit, insured worker and insurer for preventive exams, the examinee and insurer for follow-up exams","Twice; the insured worker and the employer for preventive exams, the insured unit and the worker for follow-up exams","Unlimited; only the insured unit for preventive exams, only the approved medical institution for follow-up exams","Every 3 years; the insurer and the health bureau for preventive exams, the examinee and employer for follow-up exams"],
 "Articles 5–12."),

# ---------- 勞工職業災害保險職業病鑑定作業實施辦法（111/3/31） ----------
(OD,"第2條",3,"職業病鑑定-受理範圍",
 "職業病鑑定之受理範圍為何？曾經鑑定之案件得再申請之例外？",
 ["保險人審核職業病給付案件認有必要時（審核有困難或經行政救濟撤銷後另為審核）及依災保法第75條第2項申請；應迴避委員參與鑑定、事實發生有利變更、發生新事實或新證據者","被保險人自認有必要時（診斷有困難或經雇主否認後另為認定）及依災保法第57條第2項申請；同一事由駁回已滿一年、原診斷醫師更換、檢查報告重新出具者","雇主為釐清職災責任申請時（勞資爭議或經調解不成立後另為認定）及依職安法第37條第2項申請；委員意見不一致、勞工提出陳情、投保單位申請複核者","認可醫療機構出具診斷書後（結果有疑義或經健保署核減後另為審核）及依災保法第75條第1項申請；鑑定費用已繳納、勞工檢附新病歷、已逾三年期間者"],"a",
 "第2條：保險人審核職業病給付案件認有必要時（審核有困難、核定案件經爭議審議訴願或行政訴訟撤銷後另為審核）及保險人依災保法第75條第2項申請鑑定。第3條：應備給付申請書、診斷書或相驗證明、就醫紀錄、特約職醫醫理意見；依第75條第2項者另備爭議審議申請書件、核定文件、認可醫療機構職醫診斷證明書。第4條：未備齊未補正、不符規定、已重新核定為職業病者得不受理；曾鑑定案件不得以同一事由再申請，但應迴避委員參與、事實事後有利變更、發生新事實或新證據者不在此限。",
 "Occupational disease determination covers, and previously determined cases may be resubmitted only when:",
 ["Cases the insurer finds necessary (difficult review or re-review after remedies) and applications under Article 75(2) of the Act; a member who should have recused participated, facts changed favorably, or new facts or evidence emerged","Cases an insured worker finds necessary (difficult diagnosis or re-review after employer denial) and applications under Article 57(2) of the Act; a year has passed since dismissal, the diagnosing physician changed, or reports were reissued","Cases an employer files to clarify liability (labor dispute or re-review after failed mediation) and applications under Article 37(2) of the OSH Act; committee members disagreed, the worker petitioned, or the insured unit sought review","Cases where an approved institution issued a diagnosis (doubtful result or re-review after NHI reduction) and applications under Article 75(1) of the Act; fees were paid, the worker attached new records, or three years have passed"],
 "Articles 2–4."),

(OD,"第6條",3,"職業病鑑定-分組",
 "職業病鑑定會依疾病類型分為哪三組？",
 ["第一組化學性物理性生物性危害疾病呼吸系統皮膚疾病及職業性癌症、第二組肌肉骨骼疾病、第三組腦血管與心臟疾病及精神疾病","第一組化學性物理性生物性危害疾病及肌肉骨骼疾病、第二組呼吸系統疾病皮膚疾病及職業性癌症、第三組腦血管與心臟疾病","第一組職業性癌症及精神疾病、第二組化學性物理性危害疾病與呼吸系統疾病、第三組肌肉骨骼疾病皮膚疾病及腦血管疾病","第一組腦血管與心臟疾病及呼吸系統疾病、第二組生物性危害疾病與皮膚疾病、第三組肌肉骨骼疾病精神疾病及職業性癌症"],"a",
 "第5條：應建置職業病鑑定專家名冊，由勞工團體雇主團體職安衛職業醫學及相關醫學團體推薦，專家應具職業醫學職安衛或勞動法專業及五年以上教學或實務經驗。第6條：第一組屬化學性物理性生物性危害引起之疾病呼吸系統疾病皮膚疾病及職業性癌症；第二組肌肉骨骼疾病；第三組腦血管與心臟疾病及精神疾病；涉及多種疾病得共同鑑定。第7條：分組鑑定會委員九人，機關代表一人為召集人，職醫五人相關醫學專科醫師一人職安衛專家一人法律專家一人；任期二年；任一性別不少於三分之一。",
 "The three panels of the occupational disease determination committee are:",
 ["Group 1: chemical, physical and biological hazard diseases, respiratory and skin diseases and occupational cancers; Group 2: musculoskeletal diseases; Group 3: cerebrovascular, cardiac and mental diseases","Group 1: chemical, physical and biological hazard diseases and musculoskeletal diseases; Group 2: respiratory and skin diseases and occupational cancers; Group 3: cerebrovascular and cardiac diseases","Group 1: occupational cancers and mental diseases; Group 2: chemical and physical hazard diseases and respiratory diseases; Group 3: musculoskeletal diseases, skin diseases and cerebrovascular diseases","Group 1: cerebrovascular, cardiac and respiratory diseases; Group 2: biological hazard diseases and skin diseases; Group 3: musculoskeletal diseases, mental diseases and occupational cancers"],
 "Articles 5–7: nine members per panel (five occupational physicians), two-year terms."),

(OD,"第8條",3,"職業病鑑定-決定方式",
 "職業病鑑定書面鑑定作業期間以幾日為原則？以委員意見相同者達多少決定之？未能作成時開會鑑定之出席及決定方式？",
 ["十四日；三分之二以上；三分之二以上委員出席且職醫至少三人，出席委員過半數意見","七日；過半數以上；二分之一以上委員出席且職醫至少五人，出席委員三分之二意見","三十日；四分之三以上；三分之二以上委員出席且職醫至少一人，出席委員全體一致","六十日；全體一致；四分之三以上委員出席且法律專家至少三人，出席委員過半數意見"],"a",
 "第8條：受理後依疾病類型送鑑定會委員書面鑑定，作業期間以十四日為原則，以委員意見相同者三分之二以上決定；未能作成時召集開會，應有三分之二以上委員出席其中職醫至少三人，以出席委員過半數意見決定；意見以備具理由勾選方式填列附表。第9條：仍無法作成時得召集全數委員二十七人共同開會，全數委員過半數出席且職醫超過半數，出席過半數決定。第10條：鑑定結果分職業病或非職業病（職業病種類表所列）及工作相關疾病或非工作相關疾病（腦心血管精神疾病）；職業病指職業造成之因果可能性或貢獻程度大於百分之五十者；工作相關疾病指多種致病因素工作僅為其一者。",
 "Written determinations are targeted within how many days, decided by what share of concurring members, and if not reached, meetings require:",
 ["14 days; two-thirds or more; two-thirds attendance with at least three occupational physicians, decided by majority of those present","7 days; a simple majority; one-half attendance with at least five occupational physicians, decided by two-thirds of those present","30 days; three-quarters or more; two-thirds attendance with at least one occupational physician, decided unanimously by those present","60 days; unanimity; three-quarters attendance with at least three legal experts, decided by a majority of those present"],
 "Articles 8–10; occupational disease means the job's causal contribution exceeds 50%."),

(OD,"第11條",2,"職業病鑑定-事證蒐集",
 "中央主管機關為辦理職業病鑑定，得會同何單位至工作場所蒐集事證？該單位應作成何報告？",
 ["財團法人職業災害預防及重建中心；職業醫學證據調查報告書","財團法人職業災害預防及重建中心；職業傷病現場勘查紀錄表","直轄市勞動檢查機構；職業醫學證據調查報告書及裁處建議書","衛生福利部國民健康署；職業醫學證據調查總結報告書"],"a",
 "第11條：得派員或請勞動檢查機構派員會同災保法第70條之財團法人職業災害預防及重建中心人員至被保險人工作場所或暴露有關場所蒐集事證；該中心應實施職業醫學評估作成職業醫學證據調查報告書。第12條：得邀專家學者機關團體提供資料或表示意見。第13條：委員調查人員之迴避及禁止程序外接觸依行政程序法，應保密。第14條：依第75條第2項申請者鑑定前得書面請保險人撤回，撤回後不得再以同一事由申請。第15條：定期分析鑑定結果去識別化後公開。",
 "For occupational disease determination, the central authority may collect evidence at workplaces together with which body, which then prepares:",
 ["The Occupational Accident Prevention and Rehabilitation Center; an occupational medicine evidence investigation report","The Occupational Accident Prevention and Rehabilitation Center; an on-site occupational injury inspection record form","The municipal labor inspection agency; an occupational medicine evidence report and a penalty recommendation","The Health Promotion Administration under the MOHW; a summary occupational medicine evidence report"],
 "Articles 11–15."),

# ---------- 職業災害勞工補助及核發辦法（108/4/30） ----------
(SB,"第2條",3,"職災補助-生活津貼",
 "依職業災害勞工保護法請領職業疾病生活津貼，失能程度應符合勞工保險失能給付標準第幾等級？失能生活津貼？",
 ["第一等級至第十五等級；第一等級至第七等級","第一等級至第七等級；第一等級至第十五等級","第一等級至第三等級；第一等級至第三等級","第八等級至第十等級；第十一等級至第十五等級"],"a",
 "第2條：職業疾病生活津貼須罹患職業疾病請領勞保職災傷病給付期滿或失能給付，經醫師診斷喪失部分或全部工作能力且失能程度符合第一等級至第十五等級。第3條：失能生活津貼須因職業傷害或職業疾病請領傷病給付期滿或失能給付，失能程度符合第一等級至第七等級。第8條：兩者僅得擇一請領。第4條：職業訓練生活津貼須失能第二至第十五等級、參加政府主辦委託或立案機構之職訓每月總訓練時數一百小時以上且未領其他訓練補助。",
 "Occupational disease living allowances require disability grades of, and disability living allowances grades of:",
 ["Grades 1 to 15; grades 1 to 7","Grades 1 to 7; grades 1 to 15","Grades 1 to 3; grades 1 to 3","Grades 8 to 10; grades 11 to 15"],
 "Articles 2–4 and 8."),

(SB,"第11條",3,"職災補助-津貼金額",
 "職業疾病生活津貼，失能程度符合第一至第三等級且喪失全部工作能力者每月發給多少？職業訓練生活津貼每月多少？看護補助每月多少？家屬補助多少？",
 ["八千七百元；一萬四千八百元；一萬二千四百元；十萬元","五千元；一萬元；一萬元；五萬元","一萬元；二萬元；二萬元；二十萬元","三千二百元；六千二百元；八千七百元；一萬元"],"a",
 "第11條：職業疾病生活津貼第一至三等級且喪失全部工作能力每月八千七百元、第二至七等級（或合併升等第一等級）喪失部分能力六千二百元、第八至十等級三千二百元、未遺存永久失能或第十一至十五等級一千九百元。第12條：失能生活津貼八千七百元或六千二百元。第13條：職業訓練生活津貼受訓期間每月一萬四千八百元，自初次參訓起五年內合計二十四個月為限。第15條：看護補助每月一萬二千四百元。第16條：家屬補助十萬元，發給死亡勞工之配偶子女或父母。第17條之1：消費者物價指數累計成長率達正負百分之五時調整。",
 "Monthly occupational disease living allowance for grades 1–3 with total loss of work capacity is, vocational training allowance is, care allowance is, and the family subsidy is:",
 ["NT$8,700; NT$14,800; NT$12,400; NT$100,000","NT$5,000; NT$10,000; NT$10,000; NT$50,000","NT$10,000; NT$20,000; NT$20,000; NT$200,000","NT$3,200; NT$6,200; NT$8,700; NT$10,000"],
 "Articles 11–17-1 (amounts adjusted with CPI changes of ±5%)."),

(SB,"第10條",3,"職災補助-期限",
 "依職災勞工保護法第8條第3項，按月發給之生活津貼及看護補助合計以幾年為限？第9條第2項未加保勞工者合計以幾年為限？",
 ["五年（六十個月）；三年（三十六個月）","三年（三十六個月）；五年（六十個月）","十年（一百二十個月）；五年（六十個月）","一年（十二個月）；二年（二十四個月）"],"a",
 "第10條：災保法（職災勞工保護法）第8條第3項合計五年為限，即生活津貼合計六十個月、看護補助合計六十個月；第9條第2項合計三年為限，即生活津貼合計三十六個月、看護補助三十六個月。第19條：自職安署受理當月起按月發給，未滿一個月以一個月計。第21條：應於每屆滿一年之日前檢具三個月內失能診斷書辦理續領。第22條：受補助人死亡次月起停止，家屬應於三十日內通知。第18條：申請手續完備經審查完竣應於十日內發給。",
 "Monthly living and care allowances under Article 8(3) are capped at a combined, and for uninsured workers under Article 9(2):",
 ["5 years (60 months); 3 years (36 months)","3 years (36 months); 5 years (60 months)","10 years (120 months); 5 years (60 months)","1 year (12 months); 2 years (24 months)"],
 "Articles 10, 18–22."),

(SB,"第14條",2,"職災補助-器具補助",
 "請領器具補助應檢附何種證明？購買器具之發票或收據應於證明文件開具日起幾個月內？",
 ["身心障礙鑑定醫療機構醫師出具需裝配輔助器具文件或專業人員評估證明；六個月內","身心障礙鑑定醫療機構醫師出具需裝配輔助器具文件或專業人員評估證明；一年內","任一健保特約診所醫師出具之診斷證明書或身心障礙證明影本；三個月內","雇主出具之職業災害證明及輔助器具需求評估報告書；十二個月內"],"a",
 "第5條：器具補助須因職業傷害或職業疾病遺存障害經醫師診斷或專業人員評估必須使用輔助器具且未依其他法令領取相同類別補助。第14條：輔助器具類別補助金額使用年限及對象如附表；應備申請書、身心障礙鑑定醫療機構醫師出具需裝配生活或復健輔助器具之文件或其他專業人員評估必須使用就業輔助器具之證明、證明開具日或所載需用日起六個月內購買之統一發票或收據正本、存摺影本、未依其他法令請領之聲明書；必要時送專業人員審核。第6條：看護補助須經醫師診斷終身不能工作需專人周密監護或日常生活需人扶助且符合精神神經胸腹部臟器皮膚失能第一二等級。",
 "Aid device subsidies require what proof, and receipts must be dated within how long after the certificate?",
 ["A physician's certificate from a disability assessment hospital or a professional evaluation of need; 6 months","A physician's certificate from a disability assessment hospital or a professional evaluation of need; 1 year","A diagnosis certificate from any NHI-contracted clinic physician or a copy of the disability card; 3 months","An employer-issued occupational accident certificate and an assessment report on device need; 12 months"],
 "Articles 5–6 and 14."),
]
