# -*- coding: utf-8 -*-
Q = [
("OSH-68","第1條",1,"固定式起重機-總則",
 "固定式起重機安全檢查構造標準之訂定依據為何？",
 ["職業安全衛生法第六條第三項及第十六條第四項","職業安全衛生法第五條第二項及第十六條第三項","職業安全衛生法第六條第一項及第二十三條第四項","職業安全衛生法第十六條第一項及第三十七條第二項"],"a",
 "第1條：本標準依據職業安全衛生法第六條第三項及第十六條第四項訂定之。移動式起重機、升降機及吊籠之安全檢查構造標準亦同以此二項規定為授權依據。",
 "What is the statutory basis of the Fixed Crane Construction Standards?",
 ["Article 6(3) and Article 16(4) of the Occupational Safety and Health Act","Article 5(2) and Article 16(3) of the Occupational Safety and Health Act","Article 6(1) and Article 23(4) of the Occupational Safety and Health Act","Article 16(1) and Article 37(2) of the Occupational Safety and Health Act"],
 "Article 1: issued under Articles 6(3) and 16(4) of the OSH Act."),

("OSH-68","第2條",1,"固定式起重機-總則",
 "固定式起重機構造特殊者，得如何處理本標準之適用？",
 ["得經中央主管機關認可後，免除本標準所定全部或部分之適用","得經檢查機構同意後，免除本標準所定全部或部分之適用","得由雇主自行判斷後，免除本標準所定部分規定之適用","得經製造者聲明後，免除本標準所定全部規定之適用"],"a",
 "第2條：固定式起重機構造特殊者，得經中央主管機關認可後，免除本標準所定全部或部分之適用。移動式起重機安全檢查構造標準第2條、吊籠安全檢查構造標準第2條有相同規定。",
 "How may a fixed crane of special construction be exempted from these Standards?",
 ["By approval of the central competent authority, wholly or partly exempted","By consent of the inspection body, wholly or partly exempted from them","By the employer own judgement, partly exempted from these Standards","By a declaration of the manufacturer, wholly exempted from them"],
 "Article 2 allows exemption on central authority approval."),

("OSH-68","第3條",3,"固定式起重機-材料",
 "關於固定式起重機結構部分材料之規定，下列敘述何者正確？",
 ["結構部分不包括階梯、攀登梯、扶手、走道、駕駛室、鋼索及機械部分等","結構部分包括階梯、攀登梯、扶手、走道、駕駛室、鋼索及機械部分等","吊升荷重未滿十公噸之纜索起重機，其塔及支柱之材料一律得使用木材","經中央主管機關認可之耐蝕鋁合金等材料，仍不得作為結構部分之材料"],"a",
 "第3條：結構部分材料應符合CNS 575、CNS 2473之SS400、CNS 2947等九款國家標準或同等以上鋼材，經中央主管機關認可之耐蝕鋁合金等材料不在此限；結構部分不包括階梯、攀登梯、扶手、走道、駕駛室、護圍、覆罩、鋼索、機械部分等。吊升荷重未滿五公噸之纜索起重機，其塔、支柱及牽條得使用木材。",
 "Which statement on fixed crane structural materials is correct?",
 ["Structural parts exclude stairs, ladders, handrails, walkways, cabs, ropes, machinery","Structural parts include stairs, ladders, handrails, walkways, cabs, ropes, machinery","Cable cranes under ten tonnes lifting load may always use timber towers and posts","Corrosion resistant aluminium approved by the authority may never be used at all"],
 "Article 3 lists CNS steels and excludes non load-bearing parts."),

("OSH-68","第4條",2,"固定式起重機-材料",
 "結構部分鋼材計算應使用之常數，下列何者正確？",
 ["縱彈性係數E為206,000牛頓／平方公厘，剪彈性係數G為79,000，比重為7.85","縱彈性係數E為206,000牛頓／平方公厘，剪彈性係數G為69,000，比重為2.70","縱彈性係數E為79,000牛頓／平方公厘，剪彈性係數G為206,000，比重為7.85","縱彈性係數E為2,100,000牛頓／平方公厘，剪彈性係數G為810,000，比重為0.3"],"a",
 "第4條：結構部分鋼材計算常數為縱彈性係數E＝206,000牛頓／平方公厘（2,100,000公斤／平方公分）、剪彈性係數G＝79,000（810,000）、蒲松氏比0.3、線膨脹係數0.000012、比重7.85。升降機及吊籠標準另定鋁合金之對應常數。",
 "Which constants apply to steel calculations for structural parts?",
 ["Modulus E is 206,000 N/mm2, shear modulus G is 79,000, specific gravity is 7.85","Modulus E is 206,000 N/mm2, shear modulus G is 69,000, specific gravity is 2.70","Modulus E is 79,000 N/mm2, shear modulus G is 206,000, specific gravity is 7.85","Modulus E is 2,100,000 N/mm2, shear modulus G is 810,000, gravity is 0.3"],
 "Article 4 sets E=206,000, G=79,000 and specific gravity 7.85."),

("OSH-68","第6條",3,"固定式起重機-容許應力",
 "結構部分鋼材之容許挫曲應力值，其計算方式為何？",
 ["有效細長比小於二十時等於容許抗壓應力；二十至二百時為容許抗壓應力除以挫曲係數","有效細長比小於二十時等於容許抗拉應力；二十至二百時為容許抗拉應力乘以挫曲係數","有效細長比小於一百時等於容許抗壓應力；一百至三百時為容許抗壓應力除以挫曲係數","有效細長比小於二十時等於容許承壓應力；二十至二百時為容許承壓應力乘以挫曲係數"],"a",
 "第6條：λ小於二十時σk＝σca；二十以上二百以下時σk＝（一／ω）σca。式中λ為有效細長比、σk為容許挫曲應力、σca為容許抗壓應力、ω為挫曲係數依附表一規定。第5條並定σca為σa除以一點一五。",
 "How is the allowable buckling stress of structural steel calculated?",
 ["Below slenderness 20 it equals allowable compressive stress; 20 to 200 divide by omega","Below slenderness 20 it equals allowable tensile stress; 20 to 200 multiply by omega","Below slenderness 100 it equals allowable compressive stress; 100 to 300 divide by omega","Below slenderness 20 it equals allowable bearing stress; 20 to 200 multiply by omega"],
 "Article 6 gives the buckling stress formulas."),

("OSH-68","第7條",3,"固定式起重機-容許應力",
 "對接焊接使用符號Ａ鋼材時，其容許抗拉應力及容許抗壓應力之焊接效率各為何？",
 ["容許抗拉應力為零點八四，容許抗壓應力為零點九四五","容許抗拉應力為零點八零，容許抗壓應力為零點九零零","容許抗拉應力為零點九四五，容許抗壓應力為零點八四零","容許抗拉應力為零點八四，容許抗壓應力為一點零零零"],"a",
 "第7條：對接焊接符號Ａ鋼材之焊接效率，容許抗拉應力零點八四、容許抗壓應力零點九四五、容許彎曲應力零點八四、容許抗剪應力零點八四；符號Ｂ則分別為零點八零、零點九零。對接焊接處全長百分之二十以上實施放射線檢查並符合規定者，焊接效率得取一點零。",
 "For butt welds in symbol A steel, what welding efficiencies apply?",
 ["Allowable tensile efficiency 0.84 and allowable compressive efficiency 0.945","Allowable tensile efficiency 0.80 and allowable compressive efficiency 0.900","Allowable tensile efficiency 0.945 and allowable compressive efficiency 0.840","Allowable tensile efficiency 0.84 and allowable compressive efficiency 1.000"],
 "Article 7 gives 0.84 tensile and 0.945 compressive for symbol A butt welds."),

("OSH-68","第8條",2,"固定式起重機-容許應力",
 "使用經中央主管機關認可之耐蝕鋁合金等材料時，其容許應力值應如何認定？",
 ["應於中央主管機關認可材料之化學成分及機械性質之值以下","應於國家標準所定同類鋼材容許應力值之一點二五倍以下","應由製造者依實測結果自行決定，不受任何上限之限制","應取抗拉強度除以一點八與降伏強度除以一點五之較大者"],"a",
 "第8條：使用第3條第1項但書規定之材料時，其容許應力值及其結構部分焊接處之容許應力值，應於中央主管機關認可材料之化學成分及機械性質之值以下。第59條並規定使用此類材料應依指定之方法實施焊接。",
 "How is allowable stress fixed for authority-approved special materials?",
 ["At or below the values of chemical composition and mechanical properties approved","At or below 1.25 times the allowable stress of comparable national standard steel","By the manufacturer from its own test results, without any upper limit at all","By taking the larger of tensile over 1.8 and yield strength over 1.5 values"],
 "Article 8 caps allowable stress at the approved material values."),

("OSH-68","第9條",2,"固定式起重機-容許應力",
 "承載應力值隨垂直動荷重及水平動荷重之位置或大小而變時，應依何規定確認容許疲勞應力？",
 ["依CNS 6426第六點四節規定，確認在第五條至第八條之容許應力值以下","依CNS 3710規定之缺陷種類分類，確認在第五條之容許應力值以下","依CNS 2930絕緣試驗規定，確認在第七條之焊接效率值以下即可","依CNS 5394吊鉤規定，確認在第八條認可材料之機械性質值以下"],"a",
 "第9條：承載應力值隨垂直動荷重之位置或大小及水平動荷重方向或大小而變時，應依CNS 6426第6.4節規定，確認容許疲勞應力值為第五條至第八條規定之容許應力值以下。",
 "Which standard governs the fatigue stress check when stresses vary?",
 ["CNS 6426 section 6.4, verifying stresses stay within the Articles 5 to 8 limits","CNS 3710 defect classification, verifying stresses stay within the Article 5 limits","CNS 2930 insulation testing, verifying values stay within the Article 7 efficiencies","CNS 5394 crane hooks, verifying values stay within the Article 8 approved properties"],
 "Article 9 requires the CNS 6426 fatigue check."),

("OSH-68","第10條",3,"固定式起重機-容許應力",
 "結構部分使用木材時，赤松、黑松、美國松之容許抗拉應力及容許彎曲應力各為何？",
 ["容許抗拉應力六點零，容許彎曲應力九點五牛頓／平方公厘","容許抗拉應力九點五，容許彎曲應力六點零牛頓／平方公厘","容許抗拉應力八點零，容許彎曲應力十三點零牛頓／平方公厘","容許抗拉應力四點五，容許彎曲應力七點五牛頓／平方公厘"],"a",
 "第10條：赤松、黑松、美國松之容許抗拉應力六點零、抗壓七點五、彎曲九點五、抗剪零點八牛頓／平方公厘；橡樹則為八點零、九點零、十三點零、一點四。木材容許挫曲應力於λ在一百以下時為σca乘以（一減零點零零七λ）。",
 "For red pine, black pine and Douglas fir, what allowable tensile and bending stresses apply?",
 ["Allowable tensile stress 6.0 and allowable bending stress 9.5 N/mm2","Allowable tensile stress 9.5 and allowable bending stress 6.0 N/mm2","Allowable tensile stress 8.0 and allowable bending stress 13.0 N/mm2","Allowable tensile stress 4.5 and allowable bending stress 7.5 N/mm2"],
 "Article 10 tabulates allowable stresses for timber species."),

("OSH-68","第11條",2,"固定式起重機-容許應力",
 "第五條至第八條所定容許應力值，於荷重狀態Ｂ及荷重狀態Ｃ之荷重組合，得各增值多少？",
 ["荷重狀態Ｂ於百分之十五限定範圍內，荷重狀態Ｃ於百分之三十限定範圍內","荷重狀態Ｂ於百分之三十限定範圍內，荷重狀態Ｃ於百分之十五限定範圍內","荷重狀態Ｂ於百分之十限定範圍內，荷重狀態Ｃ於百分之二十限定範圍內","荷重狀態Ｂ於百分之二十限定範圍內，荷重狀態Ｃ於百分之四十限定範圍內"],"a",
 "第11條：第五條至第八條規定之容許應力值，於第二十條第一項表中荷重狀態Ｂ之荷重組合，應於百分之十五限定範圍內增值；同表中荷重狀態Ｃ之荷重組合，應於百分之三十限定範圍內增值。",
 "By how much may allowable stresses be increased for load states B and C?",
 ["Within a limit of 15 per cent for state B and within 30 per cent for state C","Within a limit of 30 per cent for state B and within 15 per cent for state C","Within a limit of 10 per cent for state B and within 20 per cent for state C","Within a limit of 20 per cent for state B and within 40 per cent for state C"],
 "Article 11: 15 per cent for state B, 30 per cent for state C."),

("OSH-68","第13條",2,"固定式起重機-荷重",
 "固定式起重機之垂直動荷重，包括下列何者之重量總合？",
 ["額定荷重、吊鉤組、吊具與揚程五十公尺以上之鋼索等重量之總合","額定荷重、駕駛室、走道與揚程二十公尺以上之鋼索等重量總合","吊升荷重、吊鉤組、桁架與揚程五十公尺以上之鋼索等重量總合","額定荷重、吊鉤組、吊具與所有起重機構造部分之重量之總合"],"a",
 "第13條：垂直動荷重指額定荷重、吊鉤組、吊具（抓斗、吊樑、電磁吸盤等）與揚程五十公尺以上之鋼索等重量之總合。第14條則規定垂直靜荷重為構成起重機之荷重扣除垂直動荷重部分之重量。",
 "What does the vertical dynamic load of a fixed crane comprise?",
 ["Rated load, hook block, lifting gear and ropes where the lift exceeds 50 metres","Rated load, driving cabin, walkways and ropes where the lift exceeds 20 metres","Lifting load, hook block, girders and ropes where the lift exceeds 50 metres","Rated load, hook block, lifting gear and the whole crane structural weight"],
 "Article 13 defines the vertical dynamic load."),

("OSH-68","第14條",2,"固定式起重機-荷重",
 "固定式起重機之垂直靜荷重應如何認定？可移動吊運車之零組件重量如何計算？",
 ["為構成起重機之荷重扣除垂直動荷重部分之重量；該等零組件重量應計入垂直靜荷重","為構成起重機之荷重加計垂直動荷重部分之重量；該等零組件重量應計入垂直動荷重","為額定荷重扣除吊具重量後之荷重；該等零組件之重量得免予計入任何荷重項目","為構成起重機之荷重扣除風荷重部分之重量；該等零組件重量應計入水平動荷重"],"a",
 "第14條：垂直靜荷重為構成起重機之荷重，扣除垂直動荷重部分之重量；可移動之吊運車，置於漏斗內與起重機內輸送機上之零組件重量，應計入垂直靜荷重。",
 "How is the vertical static load determined and where do trolley parts count?",
 ["Crane weight less the vertical dynamic load; such parts count as vertical static load","Crane weight plus the vertical dynamic load; such parts count as vertical dynamic load","Rated load less lifting gear weight; such component weights need not be counted","Crane weight less the wind load; such parts count towards the horizontal dynamic load"],
 "Article 14 defines the vertical static load."),

("OSH-68","第15條",3,"固定式起重機-荷重",
 "水平動荷重中之慣性力，其β值於平動、橫行直行及轉動時之計算式各為何？",
 ["平動β＝0.01√v，橫行直行β＝0.008√v，轉動β＝0.006√v","平動β＝0.006√v，橫行直行β＝0.008√v，轉動β＝0.01√v","平動β＝0.01√v，橫行直行β＝0.006√v，轉動β＝0.008√v","平動β＝0.02√v，橫行直行β＝0.015√v，轉動β＝0.01√v"],"a",
 "第15條：慣性力值為垂直靜荷重與垂直動荷重總合之β倍，平動β＝0.01√v、橫行直行β＝0.008√v、轉動β＝0.006√v，v為各種運動之速度（公尺／每分鐘）；橫行、直行中以車輪驅動時，以動輪荷重之百分之十五為上限。",
 "What beta values apply to inertia forces for translation, travel and slewing?",
 ["Translation 0.01 root v, travel and traverse 0.008 root v, slewing 0.006 root v","Translation 0.006 root v, travel and traverse 0.008 root v, slewing 0.01 root v","Translation 0.01 root v, travel and traverse 0.006 root v, slewing 0.008 root v","Translation 0.02 root v, travel and traverse 0.015 root v, slewing 0.01 root v"],
 "Article 15 gives the beta coefficients for inertia forces."),

("OSH-68","第16條",3,"固定式起重機-荷重",
 "固定式起重機風荷重之速度壓，其作業時與停止時之計算式所依據風速各為何？",
 ["作業時以每秒十六公尺、停止時以每秒五十五公尺計算導出","作業時以每秒十六公尺、停止時以每秒三十五公尺計算導出","作業時以每秒十公尺、停止時以每秒三十公尺計算導出","作業時以每秒二十公尺、停止時以每秒六十公尺計算導出"],"a",
 "第16條：風荷重W＝qCA；速度壓作業時q＝83.4開四次方根h、停止時q＝980.4開四次方根h，h為受風面高度（未滿十六公尺者以十六計）。速度壓計算式係以作業時風速十六公尺／秒、停止時五十五公尺／秒導出。",
 "Which wind speeds underlie the velocity pressure formulas for working and stopped states?",
 ["16 metres per second when working and 55 metres per second when stopped","16 metres per second when working and 35 metres per second when stopped","10 metres per second when working and 30 metres per second when stopped","20 metres per second when working and 60 metres per second when stopped"],
 "Article 16 derives velocity pressure from 16 and 55 m/s."),

("OSH-68","第17條",2,"固定式起重機-荷重",
 "熱荷重之定義及其溫度計算範圍為何？",
 ["構件因溫度變化膨脹或收縮受阻礙所生之力；範圍為攝氏負二十五度至四十五度","構件因溫度變化膨脹或收縮受阻礙所生之力；範圍為攝氏零度至攝氏六十度","構件因日照直接照射所生之熱應力；溫度範圍為攝氏負十度至攝氏三十度","構件因焊接殘留應力所生之附加力；溫度範圍為攝氏負二十度至五十度"],"a",
 "第17條：熱荷重指結構部分之構件材料，因溫度變化膨脹或收縮受阻礙所生之力；其溫度計算之範圍為攝氏負二十五度至四十五度。第4條並定線膨脹係數為0.000012。",
 "How is thermal load defined and what temperature range applies?",
 ["Force from restrained thermal expansion or contraction; range minus 25 to 45 degrees","Force from restrained thermal expansion or contraction; range zero to 60 degrees","Thermal stress caused by direct sunlight; range from minus 10 to 30 degrees","Additional force from welding residual stress; range minus 20 to 50 degrees"],
 "Article 17 sets the range from minus 25 to 45 degrees Celsius."),

("OSH-68","第18條",2,"固定式起重機-荷重",
 "除中央主管機關認可者外，固定式起重機之地震荷重應如何計算？",
 ["以相當於垂直靜荷重百分之二十之水平動荷重計算之","以相當於垂直動荷重百分之二十之水平動荷重計算之","以相當於垂直靜荷重百分之三十五之垂直荷重計算之","以相當於額定荷重百分之十之水平動荷重計算之"],"a",
 "第18條：除中央主管機關認可者外，地震荷重係以相當於垂直靜荷重百分之二十之水平動荷重計算之。升降機安全檢查構造標準第18條及吊籠安全檢查構造標準第16條則以垂直動荷重及垂直靜荷重各百分之二十計算。",
 "How is the seismic load of a fixed crane calculated?",
 ["As a horizontal dynamic load equal to 20 per cent of the vertical static load","As a horizontal dynamic load equal to 20 per cent of the vertical dynamic load","As a vertical load equal to 35 per cent of the vertical static load applied","As a horizontal dynamic load equal to 10 per cent of the crane rated load"],
 "Article 18: 20 per cent of the vertical static load."),

("OSH-68","第19條",3,"固定式起重機-荷重",
 "起重機設有緩衝裝置時，衝擊荷重應以額定速度之多少比例計算其吸收運動能所造成之力？",
 ["額定速度之百分之七十，但緩衝裝置前方設有自動減速裝置者得以減速後速度計算","額定速度之百分之五十，但緩衝裝置前方設有自動減速裝置者仍應以額定速度計算","額定速度之百分之一百，且不論有無自動減速裝置均應以額定速度全值計算之","額定速度之百分之三十，但緩衝裝置前方設有自動減速裝置者得以額定速度計算"],"a",
 "第19條：起重機設有緩衝裝置時，於無吊掛物之狀態下，以額定速度之百分之七十計算其吸收運動能所造成之力；但於緩衝裝置前方設置有自動減速之裝置者，得以其減速後之速度計算。",
 "At what proportion of rated speed is impact load calculated where buffers are fitted?",
 ["70 per cent of rated speed, or the reduced speed if automatic deceleration is fitted","50 per cent of rated speed, and still rated speed even if deceleration is fitted","100 per cent of rated speed regardless of whether deceleration devices are fitted","30 per cent of rated speed, or the full rated speed if deceleration is fitted"],
 "Article 19 uses 70 per cent of rated speed."),

("OSH-68","第21條",2,"固定式起重機-強度",
 "固定式起重機吊鉤之斷裂荷重與所承受最大荷重之比，應為多少以上？",
 ["應為四以上，或依CNS 5394規定辦理","應為五以上，或依CNS 5394規定辦理","應為六以上，或依CNS 6426規定辦理","應為三以上，或依CNS 2930規定辦理"],"a",
 "第21條：吊鉤之斷裂荷重與所承受之最大荷重比，應為四以上，或依CNS 5394規定辦理。移動式起重機安全檢查構造標準第15條有相同規定；起重升降機具安全規則第67條亦定吊鉤安全係數四以上。",
 "What ratio of breaking load to maximum load applies to a fixed crane hook?",
 ["It must be four or more, or otherwise comply with CNS 5394","It must be five or more, or otherwise comply with CNS 5394","It must be six or more, or otherwise comply with CNS 6426","It must be three or more, or otherwise comply with CNS 2930"],
 "Article 21 requires a hook ratio of four or more."),

("OSH-68","第22條",1,"固定式起重機-強度",
 "固定式起重機之結構部分，應具備何種強度與剛性？",
 ["應具有充分強度及保持防止板材挫曲、變形等妨礙安全使用之剛性","應具有相當於吊升荷重三倍之強度，剛性由檢查機構個案認定","應具有充分剛性，強度則以荷重試驗實測值作為唯一判定依據","應具有防止板材挫曲之剛性，強度得低於容許應力值百分之十"],"a",
 "第22條：結構部分應具有充分強度及保持防止板材挫曲、變形等妨礙安全使用之剛性。第20條並要求結構部分材料承載荷重所生之應力值不得超過第5條至第8條規定之容許應力值。",
 "What strength and rigidity must fixed crane structural parts have?",
 ["Sufficient strength plus rigidity preventing plate buckling and unsafe deformation","Strength of three times the lifting load, with rigidity judged case by case","Sufficient rigidity, with strength judged solely from measured load test values","Rigidity against plate buckling, with strength up to ten per cent below limits"],
 "Article 22 requires adequate strength and rigidity."),

("OSH-68","第23條",2,"固定式起重機-強度",
 "架空式起重機之桁架，以額定荷重置於最不利位置吊升時，其最大撓度應為多少以下？",
 ["起重機桁架跨距之八百分之一以下","起重機桁架跨距之四百分之一以下","起重機桁架跨距之一千分之一以下","起重機桁架跨距之二百分之一以下"],"a",
 "第23條：架空式起重機之桁架，以額定荷重置於最不利之位置吊升時，最大撓度應為起重機桁架跨距八百分之一以下；但起重機桁架跨距小，不因撓度致荷物晃動而發生危險之虞者，不在此限。",
 "What maximum deflection applies to an overhead crane girder at rated load?",
 ["Not more than one eight-hundredth of the crane girder span","Not more than one four-hundredth of the crane girder span","Not more than one thousandth of the crane girder span","Not more than one two-hundredth of the crane girder span"],
 "Article 23 limits deflection to span divided by 800."),

("OSH-68","第24條",3,"固定式起重機-安定度",
 "固定式起重機安定度計算中，承受相當於垂直動荷重之荷重倍數，一般起重機與營建用塔式起重機各為何？",
 ["一般為一點六倍，營建用塔式為一點四倍；另有一點三五倍與一點一倍之組合","一般為一點四倍，營建用塔式為一點六倍；另有一點一倍與一點三五倍之組合","一般為一點二五倍，營建用塔式為一點二七倍；另有一點五倍之組合荷重","一般為二點零倍，營建用塔式為一點八倍；另有一點六倍之組合荷重情形"],"a",
 "第24條：安定度應確認翻倒支點之安定力矩大於翻倒力矩，計算情形包括承受垂直動荷重零點三倍之反方向荷重、一點六倍荷重（營建用塔式起重機為一點四倍）、一點三五倍荷重加水平動荷重及作業時風荷重之組合（營建用塔式為一點一倍），及屋外起重機於無吊升荷物狀態承受停止時之風荷重。",
 "What multiples of vertical dynamic load apply in the stability check?",
 ["1.6 for general cranes and 1.4 for tower cranes; also 1.35 and 1.1 combinations","1.4 for general cranes and 1.6 for tower cranes; also 1.1 and 1.35 combinations","1.25 for general cranes and 1.27 for tower cranes; also a 1.5 load combination","2.0 for general cranes and 1.8 for tower cranes; also a 1.6 load combination"],
 "Article 24 sets 1.6 and 1.4 multiples with 1.35 and 1.1 combinations."),

("OSH-68","第25條",2,"固定式起重機-拉條",
 "纜索起重機之拉條，關於安定支柱頂部之拉條數規定為何？",
 ["應為二條以上，且不得接近於架空電路","應為三條以上，且不得接近於架空電路","應為六條以上，惟得跨越架空電路上方","應為四條以上，惟得緊鄰架空電路設置"],"a",
 "第25條：纜索起重機之拉條，安定支柱頂部之拉條數應為二條以上；不得接近於架空電路；以鋼索為拉條時應以鋏、環首、套管等金屬具緊結於支柱、牽索用固定錨或同等以上堅固物；並應以鬆緊螺旋扣等金屬具拉緊且有防止扭轉鬆脫之措施。",
 "How many guys are required at the top of a cable crane stabilising mast?",
 ["Two or more, and they must not come close to any overhead power line","Three or more, and they must not come close to any overhead power line","Six or more, though they may be run above the overhead power lines","Four or more, though they may be placed right beside the power lines"],
 "Article 25 requires two or more guys clear of power lines."),

("OSH-68","第27條",3,"固定式起重機-制動器",
 "起重機之直行裝置應設制動器，下列何者屬於免設之例外情形？",
 ["屋內地面操作且隨荷物移動，直行輪為滾動軸承而額定速度每分鐘二十公尺以下者","屋內地面操作且隨荷物移動，直行輪為滾動軸承而額定速度每分鐘六十公尺以下者","屋外地面操作且隨荷物移動，直行輪為滑動軸承而額定速度每分鐘四十公尺以下者","屋內駕駛室操作且不隨荷物移動，直行輪為滾動軸承而以電動機驅動作動者"],"a",
 "第27條：起重機之直行裝置應設制動器；但設置在屋內、操作人員於地面上操作並隨荷物移動，且直行輪軸承為滑動軸承，或為滾動軸承且直行額定速度在每分鐘二十公尺以下者，以及以油壓作動或以人力作動者，不在此限。",
 "Which case is exempt from fitting a brake to the crane travelling device?",
 ["Indoor floor-operated cranes following the load with roller bearings under 20 m/min","Indoor floor-operated cranes following the load with roller bearings under 60 m/min","Outdoor floor-operated cranes following the load with slide bearings under 40 m/min","Indoor cab-operated cranes not following the load with motor-driven roller bearings"],
 "Article 27 exempts slow indoor floor-operated travelling gear."),

("OSH-68","第28條",2,"固定式起重機-制動器",
 "起重機之橫行裝置應設制動器，下列何者不屬於免設之例外情形？",
 ["設置在屋外，且橫行輪軸承為滾動軸承並由駕駛室操作者","設置在屋內，且橫行輪軸承為滑動軸承者","設置在屋內、地面操作且滾動軸承橫行額定速度每分鐘二十公尺以下者","吊運車以油壓作動者或吊運車以人力作動者"],"a",
 "第28條：起重機之橫行裝置應設制動器；但設置在屋內且橫行輪軸承為滑動軸承者，設置在屋內、操作人員於地面上操作、橫行輪軸承為滾動軸承且橫行額定速度為每分鐘二十公尺以下者，吊運車以油壓作動者及以人力作動者，不在此限。",
 "Which case is NOT exempt from fitting a brake to the traversing device?",
 ["Outdoor cranes with roller bearing traverse wheels operated from the driving cab","Indoor cranes whose traversing wheel bearings are of the slide bearing type","Indoor floor-operated cranes with roller bearings traversing under 20 m/min","Trolleys actuated by hydraulic power or trolleys actuated by manual power"],
 "Article 28 lists four exemptions, all for indoor or non-powered cases."),

("OSH-68","第29條",3,"固定式起重機-捲胴",
 "供作過負荷預防裝置使用之槽輪，其節圓直徑與通過該槽輪鋼索直徑之比值應為多少以上？",
 ["應為五以上","應為十以上","應為十四以上","應為二十以上"],"a",
 "第29條：吊升裝置等之捲胴、槽輪或平衡輪之節圓直徑與鋼索直徑之比，應大於附表所列各等級之值（如等級Ａ第一組捲胴為十四、槽輪為十六、平衡輪為十）；供作過負荷預防裝置使用之槽輪節圓直徑與通過該槽輪鋼索之比值，應為五以上。",
 "What minimum ratio applies to a sheave used for the overload prevention device?",
 ["The ratio must be five or more","The ratio must be ten or more","The ratio must be fourteen or more","The ratio must be twenty or more"],
 "Article 29 requires a ratio of five for overload device sheaves."),

("OSH-68","第30條",2,"固定式起重機-捲胴",
 "固定式起重機有槽式捲胴捲進鋼索時之夾角，及無槽式捲胴之遊角規定各為何？",
 ["有槽式夾角應為四度以下，無槽式遊角應為二度以下","有槽式夾角應為二度以下，無槽式遊角應為四度以下","有槽式夾角應為六度以下，無槽式遊角應為三度以下","有槽式夾角應為四度以下，無槽式遊角應為八度以下"],"a",
 "第30條：固定式起重機之有槽式捲胴捲進鋼索時，鋼索中心線與所進入之槽之中心線間夾角應為四度以下；使用無槽式捲胴時其遊角應為二度以下。移動式起重機標準第25條、升降機標準第35條及吊籠標準第27條有相同規定。",
 "What fleet angles apply to grooved and ungrooved drums on a fixed crane?",
 ["Four degrees or less for grooved drums and two degrees or less for ungrooved","Two degrees or less for grooved drums and four degrees or less for ungrooved","Six degrees or less for grooved drums and three degrees or less for ungrooved","Four degrees or less for grooved drums and eight degrees or less for ungrooved"],
 "Article 30: four degrees grooved, two degrees ungrooved."),

("OSH-68","第31條",1,"固定式起重機-捲胴",
 "鋼索與捲胴、伸臂、吊運車架、吊鉤組等之連結，應使用何種方法緊結？",
 ["應使用合金套筒、壓夾或栓銷等方法緊結之","應使用電弧焊接熔接或以鐵絲纏繞等方法","應使用纖維索綑綁或以塑膠套管包覆固定","應使用鋼索自身打結後回穿之編結方式固定"],"a",
 "第31條：鋼索與捲胴、伸臂、吊運車架、吊鉤組等之連結，應使用合金套筒、壓夾或栓銷等方法緊結之。移動式起重機安全檢查構造標準第26條、吊籠安全檢查構造標準第28條有相同規定。",
 "How must ropes be secured to drums, jibs, trolley frames and hook blocks?",
 ["By alloy sockets, swage clamps or cotter pin methods of fastening","By arc welding the rope end or by wrapping it with binding wire","By binding with fibre rope or by covering it with a plastic sleeve","By knotting the rope on itself and tucking the strands back in"],
 "Article 31 requires alloy sockets, clamps or pins."),

("OSH-68","第32條",1,"固定式起重機-捲胴",
 "構成吊升裝置等之捲胴、軸、銷及其他組件，應符合何項要求？",
 ["應具有充分之強度，且不得有妨礙作動之磨耗、變形或裂隙等缺陷","應具有充分之剛性，磨耗量在百分之十以內者不視為缺陷可續用","應每六個月更換一次，且更換前不得有任何磨耗變形裂隙等缺陷","應具有充分之強度，變形量在容許值以內者得免予記錄及檢點之"],"a",
 "第32條：構成吊升裝置等之捲胴、軸、銷及其他組件應具有充分之強度，且不得有妨礙吊升裝置等作動之磨耗、變形或裂隙等缺陷。移動式起重機標準第27條、升降機標準第32條有相同規定。",
 "What requirement applies to drums, shafts and pins of the hoisting device?",
 ["Sufficient strength and free of wear, deformation or cracks hindering operation","Sufficient rigidity, with wear up to ten per cent not counted as a defect","Replacement every six months, and no wear, deformation or cracks before that","Sufficient strength, with deformation within limits needing no record or check"],
 "Article 32 requires strength and freedom from defects."),

("OSH-68","第33條",2,"固定式起重機-安全裝置",
 "使用鋼索或吊鏈之吊升裝置及起伏裝置應設過捲預防裝置，何者不在此限？",
 ["使用液壓、氣壓、絞車或內燃機為動力之吊升裝置及起伏裝置","使用電動機為動力且吊升荷重未滿三公噸之吊升裝置及起伏裝置","設置於屋內且操作人員於地面操作之吊升裝置及起伏裝置全部","已設置過負荷預防裝置及伸臂傾斜角指示裝置之伸臂起重機者"],"a",
 "第33條：使用鋼索或吊鏈之吊升裝置及起伏裝置，應設置過捲預防裝置；但使用液壓、氣壓、絞車或內燃機為動力之吊升裝置及起伏裝置，不在此限。第34條並定其間隔應保持零點二五公尺以上，直動式為零點零五公尺以上。",
 "Which hoisting or luffing devices are exempt from an over-hoisting device?",
 ["Those powered by hydraulic, pneumatic, winch or internal combustion power","Those powered by an electric motor with a lifting load under three tonnes","All indoor devices where the operator works from ground level positions","Jib cranes already fitted with overload devices and angle indicators"],
 "Article 33 exempts hydraulic, pneumatic, winch and engine drives."),

("OSH-68","第35條",2,"固定式起重機-安全裝置",
 "伸臂起重機應設置過負荷預防裝置，下列何者不屬於免設之要件？",
 ["已另設吊鉤防脫阻擋裝置者","吊升荷重未滿三公噸者","伸臂傾斜角及長度保持一定者","額定荷重保持一定不變者"],"a",
 "第35條：伸臂起重機應設置過負荷預防裝置；但吊升荷重未滿三公噸、伸臂之傾斜角及長度保持一定、額定荷重保持一定，且已裝有其他預防裝置（第三十七條規定之安全閥除外）而能防止過負荷者，不在此限。",
 "Which condition is NOT among the exemptions from the overload prevention device?",
 ["Being fitted with a hook latch to stop slings slipping off","Having a lifting load of less than three tonnes in capacity","Keeping the jib inclination angle and its length constant","Keeping the crane rated load constant during operation"],
 "Article 35 lists three exemption conditions."),

("OSH-68","第36條",1,"固定式起重機-安全裝置",
 "具有起伏動作之伸臂起重機，應於操作人員易見處設置何種裝置？",
 ["伸臂傾斜角之指示裝置，以防止過負荷操作","伸臂長度之自動記錄裝置，以防止過捲操作","吊鉤荷重之數位顯示裝置，以防止碰撞桁架","風速之即時監測裝置，以防止強風作業危害"],"a",
 "第36條：具有起伏動作之伸臂起重機，應於操作人員易見處，設置伸臂傾斜角之指示裝置，以防止過負荷操作。移動式起重機安全檢查構造標準第32條及起重升降機具安全規則第55條有相同規定。",
 "What device must be provided in view of the operator of a luffing jib crane?",
 ["A jib inclination angle indicator, to prevent overload operation","A jib length automatic recorder, to prevent over-hoisting operation","A digital hook load display device, to prevent striking the girder","A real-time wind speed monitor, to prevent hazards in strong wind"],
 "Article 36 requires a jib angle indicator."),

("OSH-68","第37條",2,"固定式起重機-安全裝置",
 "使用液壓或氣壓為動力之固定式起重機，其吊升裝置及起伏裝置應設置何種閥件？",
 ["防止壓力過度升高之安全閥，及防止吊具急劇下降之逆止閥","防止壓力過度升高之安全閥，及防止鋼索過捲之限制閥件","防止壓力異常下降之減壓閥，及防止吊具上升之過捲閥件","防止油溫過高之冷卻閥，及防止柱塞脫離油壓缸之閥件"],"a",
 "第37條：使用液壓或氣壓為動力之固定式起重機之吊升裝置及起伏裝置，應設置防止壓力過度升高之安全閥；並應設置防止液壓或氣壓異常下降致吊具等急劇下降之逆止閥，但設置符合第26條第2項第1款至第3款規定之制動器者不在此限。",
 "Which valves must a hydraulic or pneumatic fixed crane hoisting device have?",
 ["A relief valve against excess pressure and a check valve against sudden drops","A relief valve against excess pressure and a limit valve against over-hoisting","A reducing valve against pressure loss and a valve against gear over-hoisting","A cooling valve against high oil temperature and a plunger retention valve"],
 "Article 37 requires relief and check valves."),

("OSH-68","第38條",2,"固定式起重機-安全裝置",
 "回轉部分之護圍或覆罩設置於工作者踏足之處者，其強度應能承受多少負荷且不變形？",
 ["應能承受九十公斤之負荷","應能承受六十公斤之負荷","應能承受一百二十公斤之負荷","應能承受二百公斤之負荷"],"a",
 "第38條：齒輪、軸、聯結器等回轉部分，有接觸人體引起危害之虞者，應設置護圍或覆罩；該護圍或覆罩設置於工作者踏足之處者，其強度應能承受九十公斤之負荷且不產生變形。移動式起重機安全檢查構造標準第34條有相同規定。",
 "What load must a guard on which workers may step withstand without deforming?",
 ["It must withstand a load of ninety kilograms","It must withstand a load of sixty kilograms","It must withstand a load of one hundred and twenty kilograms","It must withstand a load of two hundred kilograms"],
 "Article 38 requires guards to bear 90 kg."),

("OSH-68","第39條",1,"固定式起重機-安全裝置",
 "走行固定式起重機應設置何種裝置？何者不在此限？",
 ["應設電鈴、警鳴器等警報裝置；地面操作且隨荷物移動或人力移動者除外","應設過捲預防裝置；地面操作且隨荷物移動或以人力移動之起重機除外","應設伸臂傾斜角指示裝置；設置於屋內之走行固定式起重機均得免設","應設防止逸走裝置；設置於屋內之走行固定式起重機一律不得免設之"],"a",
 "第39條：走行固定式起重機應設電鈴、警鳴器等警報裝置；但操作人員於地面上操作，且隨荷物移動或以人力移動之起重機，不在此限。第50條並規定設置於屋外之起重機應設有直行之防止逸走裝置。",
 "What device must a travelling fixed crane have, and what is exempt?",
 ["A bell or siren warning device; floor-operated cranes following the load are exempt","An over-hoisting device; floor-operated cranes following the load are exempt","A jib angle indicator; all indoor travelling fixed cranes may omit the device","An anti-runaway device; indoor travelling fixed cranes may never omit it"],
 "Article 39 requires warning devices with an exemption."),

("OSH-68","第40條",1,"固定式起重機-安全裝置",
 "固定式起重機之吊鉤應設置何種裝置？何種情形得免設？",
 ["應設防止吊掛用鋼索等脫落之阻擋裝置；經全程安全分析報經檢查機構認可者除外","應設防止吊掛用鋼索等脫落之阻擋裝置；吊升荷重未滿三公噸之起重機一律除外","應設過捲預防用之限制開關裝置；經全程安全分析報經檢查機構認可者得免設","應設吊鉤荷重顯示裝置；於特殊環境吊掛特定荷物者得由雇主自行決定免設"],"a",
 "第40條：吊鉤應設置防止吊掛用鋼索等脫落之阻擋裝置；但於特殊環境吊掛特定荷物，實施全程安全分析，報經檢查機構認可者，不在此限。移動式起重機安全檢查構造標準第36條亦要求設置阻擋裝置。",
 "What device must a fixed crane hook have and when may it be omitted?",
 ["A latch preventing slings from slipping off; omitted only on approved safety analysis","A latch preventing slings from slipping off; always omitted below three tonnes","A limit switch for over-hoisting; omitted on an approved full safety analysis","A hook load display device; omitted at the employer discretion in special settings"],
 "Article 40 requires a hook latch with a narrow exemption."),

("OSH-68","第41條",2,"固定式起重機-安全裝置",
 "操作人員於地面上操作並隨荷物移動之起重機，其直行及橫行速度不得逾多少？",
 ["每分鐘六十三公尺","每分鐘二十公尺","每分鐘一百公尺","每分鐘四十五公尺"],"a",
 "第41條：操作人員於地面上操作，並隨荷物移動之起重機，其直行及橫行速度，不得逾每分鐘六十三公尺。第27條、第28條則以每分鐘二十公尺作為免設制動器之速度門檻。",
 "What speed limit applies to floor-operated cranes that follow the load?",
 ["Sixty-three metres per minute","Twenty metres per minute","One hundred metres per minute","Forty-five metres per minute"],
 "Article 41 caps travel and traverse at 63 m/min."),

("OSH-68","第42條",3,"固定式起重機-安全裝置",
 "頂升式吊升裝置之保持機構，應符合下列何項規定？",
 ["具有保持鋼索等必要之功能，並具有防止所有保持機構同時開放及失去功能者","具有保持鋼索等必要之功能，惟得容許所有保持機構同時開放以利快速卸放","僅須具有防止所有保持機構同時開放之功能，保持鋼索之功能得由制動器替代","僅須具有夾緊鋼索之機構，其開閉順序及失效防止由操作人員現場判斷控制"],"a",
 "第42條：頂升式吊升裝置之保持機構，應具有保持鋼索等必要之功能，並具有防止所有保持機構同時開放及失去功能者。頂升式吊升裝置指具有數個保持機構，以動力伸縮使交互開閉該等保持機構，藉由鋼索等吊升或卸放荷物之裝置。第65條並定其鋼索安全係數為三點五五以上。",
 "What must the holding mechanism of a jack-up hoisting device comply with?",
 ["It must hold the ropes and prevent all holding mechanisms opening or failing together","It must hold the ropes but may allow all holding mechanisms to open simultaneously","It need only prevent simultaneous opening, as the brake can replace rope holding","It need only clamp the ropes, with opening order judged by the operator on site"],
 "Article 42 requires holding function plus anti-simultaneous-release."),

("OSH-68","第43條",3,"固定式起重機-電氣部分",
 "固定式起重機之電磁接觸器操作回路接地時，應依何規定辦理？",
 ["線圈之一端應連接於接地側之電線，且線圈與接地側電線間不得有開關裝置","線圈之兩端均應連接於接地側之電線，且線圈與接地側間應加設開關裝置","線圈之一端應連接於非接地側之電線，並於線圈與電源間設置雙極開關器","線圈應以絕緣材料完全包覆，並於接地側電線上串聯一組保險絲及開關器"],"a",
 "第43條：固定式起重機之電磁接觸器之操作回路接地時，該電磁接觸器有接通之虞者，線圈之一端應連接於接地側之電線，且線圈與接地側電線間不得有開關裝置；操作回路並應於停電時切離所有電動機電路，使操作用開關器未回復至停止位置時電源無法啟動。",
 "What rules apply when the contactor control circuit of a fixed crane is earthed?",
 ["One coil end connects to the earthed conductor and no switch lies in between","Both coil ends connect to the earthed conductor with a switch placed in between","One coil end connects to the unearthed conductor with a two-pole switch added","The coil is fully insulated and a fuse and switch are placed in the earthed line"],
 "Article 43 governs earthed contactor control circuits."),

("OSH-68","第44條",2,"固定式起重機-電氣部分",
 "固定式起重機之控制裝置，應於操作人員易見處標示何事項？何者得免標示？",
 ["標示動作種別、動作方向及動作停止位置；放手能自動恢復停止位置者得免標示停止位置","標示製造者名稱、製造年月及吊升荷重；放手能自動恢復停止位置者得免標示吊升荷重","標示額定電壓、額定電流及絕緣等級；具有自動恢復停止位置構造者得免標示額定電流","標示動作種別及動作方向；凡設有過捲預防裝置之起重機均得免予標示動作停止位置"],"a",
 "第44條：固定式起重機之控制裝置，應於操作人員易見處標示起重機之動作種別、動作方向及動作停止位置；但具有操作人員自控制裝置之操作部分放手時，能自動恢復至停止位置之構造者，得不標示該停止動作位置。",
 "What must be marked on a fixed crane control device and what may be omitted?",
 ["Motion type, direction and stop position; the stop position may be omitted if self-returning","Maker name, manufacture date and lifting load; lifting load omitted if self-returning","Rated voltage, current and insulation class; rated current omitted if self-returning","Motion type and direction only; the stop position is omitted whenever a latch is fitted"],
 "Article 44 requires marking of motion type, direction and stop position."),

("OSH-68","第45條",2,"固定式起重機-電氣部分",
 "操作人員於地面上操作並隨荷物移動之固定式起重機，其操作用開關器應符合何項規定？",
 ["放手時能自動使動作停止，引索構造者應有防止扭結措施，並標示動作種類及方向","放手時能自動使動作加速，引索構造者得容許扭結，並免予標示動作種類及方向","放手時應維持既有動作直至再次按壓，引索構造者應以電纜線支撐其全部重量","放手時能自動使動作停止，且電纜線應作為支撐操作用開關器重量之主要引索"],"a",
 "第45條：操作用開關器應具有操作人員自操作部分放手時能自動使動作停止之構造；操作部分為引索構造者應有防止該引索扭結之措施；應於操作人員易見處標示所控制之動作種類及動作方向；電纜線不得作為支撐操作用開關器重量之引索，但該電纜線具有足夠強度時不在此限。",
 "What must the control switch of a floor-operated fixed crane comply with?",
 ["Motion stops on release, pull cords are kink-protected, and motions are marked","Motion accelerates on release, pull cords may kink, and marking is not required","Motion continues until pressed again, and the cable carries the whole switch weight","Motion stops on release, and the cable is the main support for the switch weight"],
 "Article 45 lists four requirements for pendant control switches."),

("OSH-68","第46條",3,"固定式起重機-電氣部分",
 "供電線電壓為七百五十伏特以下直流電或六百伏特以下交流電時，其設置位置有何限制？",
 ["不得設於走道等上方未滿二點三公尺處，或其側方未滿一點二公尺之位置","不得設於走道等上方未滿一點二公尺處，或其側方未滿二點三公尺之位置","不得設於走道等上方未滿三點五公尺處，或其側方未滿二點零公尺之位置","不得設於走道等上方未滿一點八公尺處，或其側方未滿零點六公尺之位置"],"a",
 "第46條：供電線電壓為七百五十伏特以下之直流電或六百伏特以下之交流電時，不得設置於起重機桁架之走道、階梯、攀登梯或檢點台上方未滿二點三公尺處，或其側方未滿一點二公尺之位置；但設有防止感電之圍柵或絕緣覆蓋者，不在此限。第47條規定超過該電壓者應設於專用坑穴或套管內。",
 "What placement limits apply to supply lines of 750 V DC or 600 V AC or less?",
 ["Not less than 2.3 metres above walkways, nor less than 1.2 metres to the side","Not less than 1.2 metres above walkways, nor less than 2.3 metres to the side","Not less than 3.5 metres above walkways, nor less than 2.0 metres to the side","Not less than 1.8 metres above walkways, nor less than 0.6 metres to the side"],
 "Article 46 sets 2.3 m above and 1.2 m to the side."),

("OSH-68","第47條",2,"固定式起重機-電氣部分",
 "供電線電壓超過七百五十伏特直流電或超過六百伏特交流電時，應如何設置？",
 ["應設於專用之坑穴或套管內，但設有防止感電之圍柵或絕緣覆蓋者除外","應設於走道上方二點三公尺以上處，但設有絕緣覆蓋者得降至一點二公尺","應設於駕駛室內之專用配電盤中，並由操作人員每日檢點其絕緣電阻值","應設於起重機桁架外側並以警示色標示，但得免設圍柵或絕緣覆蓋設施"],"a",
 "第47條：供電線電壓超過七百五十伏特之直流電或超過六百伏特之交流電時，應設於專用之坑穴或套管內；但設有防止感電之圍柵或絕緣覆蓋者，不在此限。第46條則規定該電壓以下者之最小距離。",
 "How must supply lines above 750 V DC or 600 V AC be installed?",
 ["In a dedicated trench or conduit, unless guards or insulating covers are provided","Not less than 2.3 metres above walkways, or 1.2 metres where insulation is used","In a dedicated switchboard in the cab, with daily insulation resistance checks","On the outside of the crane girder with warning colours and no guards needed"],
 "Article 47 requires dedicated trenches or conduits."),

("OSH-68","第48條",3,"固定式起重機-緩衝裝置",
 "起重機橫行軌道及直行軌道兩端所設車輪阻擋器，其高度規定各為何？",
 ["橫行為吊運車輪直徑四分之一以上，直行為直行車輪直徑二分之一以上","橫行為吊運車輪直徑二分之一以上，直行為直行車輪直徑四分之一以上","橫行與直行均為各該車輪直徑三分之一以上之高度並得互相替代使用","橫行為吊運車輪直徑五分之一以上，直行為直行車輪直徑三分之一以上"],"a",
 "第48條：架空式起重機、鎚頭型伸臂起重機、牆裝起重機、橋型起重機及卸載機之橫行軌道，應在其兩端或適當場所設置緩衝裝置、緩衝材或相當於吊運車輪直徑四分之一以上高度之車輪阻擋器；起重機之直行軌道則為直行車輪直徑二分之一以上高度之車輪阻擋器。",
 "What stopper heights apply on the traversing rails and on the travelling rails?",
 ["One quarter of the trolley wheel diameter and one half of the travel wheel diameter","One half of the trolley wheel diameter and one quarter of the travel wheel diameter","One third of each respective wheel diameter, and the two may be interchanged","One fifth of the trolley wheel diameter and one third of the travel wheel diameter"],
 "Article 48 sets one quarter and one half wheel diameter stoppers."),

("OSH-68","第49條",2,"固定式起重機-緩衝裝置",
 "二部以上之起重機並置於同一軌道上時，應如何設置防護？",
 ["應分別於各該起重機相對側設置防撞裝置、緩衝裝置或緩衝材","應於軌道兩端設置防撞裝置即可，起重機相對側免設任何裝置","應於各該起重機相對側設置警報裝置，緩衝材則由雇主自行決定","應於軌道中央設置一組共用緩衝裝置，供二部起重機共同使用之"],"a",
 "第49條：二部以上之起重機並置於同一軌道上時，應分別於各該起重機相對側，設置防撞裝置、緩衝裝置或緩衝材；但操作人員於地面上操作，並隨荷物移動之起重機，不在此限。",
 "How must two or more cranes sharing one rail be protected?",
 ["Anti-collision devices, buffers or buffer materials on the facing sides of each crane","Anti-collision devices at both rail ends only, with nothing on the facing sides","Warning devices on the facing sides, with buffer material left to the employer","One shared buffer device at the middle of the rail serving both cranes together"],
 "Article 49 requires buffers on the facing sides of each crane."),

("OSH-68","第50條",2,"固定式起重機-防止逸走",
 "設置於屋外之起重機所設直行防止逸走裝置，其性能應足以承受何種風荷重？",
 ["依W＝1180開四次方根h乘CA計算所得之風荷重，並以逸走最不利狀態計算","依W＝83.4開四次方根h乘CA計算所得之風荷重，並以作業時最有利狀態計算","依W＝980.4開四次方根h乘CA計算所得之風荷重，且高度未滿十公尺以十計","依W＝1180開四次方根h乘CA計算所得之風荷重，且高度未滿二十公尺以二十計"],"a",
 "第50條：設置於屋外之起重機應設有直行之防止逸走裝置，其性能應足以承受W＝1180開四次方根h乘以CA所得之風荷重，h為受風面自地面起算之高度（未滿十六公尺者以十六計），C為風力係數，A為受風面積；該風荷重應以起重機之逸走最不利之狀態計算。",
 "What wind load must an outdoor crane anti-runaway device withstand?",
 ["The load from W = 1180 times fourth root of h times CA, in the worst runaway state","The load from W = 83.4 times fourth root of h times CA, in the best working state","The load from W = 980.4 times fourth root of h times CA, with h taken as 10 minimum","The load from W = 1180 times fourth root of h times CA, with h taken as 20 minimum"],
 "Article 50 gives the anti-runaway wind load formula."),

("OSH-68","第51條",2,"固定式起重機-防止逸走",
 "設置於屋外之起重機，其直行之原動機馬力應具備何種性能？",
 ["應在風速每秒十六公尺時，能安全行駛至防止逸走裝置之處","應在風速每秒三十公尺時，能安全行駛至防止逸走裝置之處","應在風速每秒五十五公尺時，能安全行駛至防止逸走裝置處","應在風速每秒十六公尺時，能將起重機完全制動並停止走行"],"a",
 "第51條：設置於屋外之起重機，其直行之原動機馬力應在風速每秒十六公尺時，能安全行駛至防止逸走裝置之處。起重升降機具安全規則第22條亦要求屋外走行起重機原動機馬力能在風速每秒十六公尺時安全駛至防止逸走裝置之處。",
 "What capability must the travel motor of an outdoor crane have?",
 ["It must travel safely to the anti-runaway device at a wind speed of 16 m/s","It must travel safely to the anti-runaway device at a wind speed of 30 m/s","It must travel safely to the anti-runaway device at a wind speed of 55 m/s","It must fully brake and stop the crane travelling at a wind speed of 16 m/s"],
 "Article 51 requires travel to the anchorage at 16 m/s wind."),

("OSH-68","第53條",2,"固定式起重機-走道等",
 "吊升荷重在三公噸以上之伸臂起重機，其水平伸臂以外之伸臂應設置何者？何時得免設？",
 ["應設攀登梯；設有檢點台或其他檢點設備，或在地面上易於檢點者得免設","應設走道；設有檢點台或其他檢點設備，或在地面上易於檢點者得免設","應設攀登梯；吊升荷重未滿十公噸之伸臂起重機一律得免設攀登梯","應設防護網；設有檢點台或在地面上易於檢點該起重機者均得免設"],"a",
 "第53條：吊升荷重在三公噸以上之伸臂起重機，其水平伸臂以外之伸臂應設攀登梯；但設有檢點台或其他為檢點該起重機之設備，或在地面上易於檢點該起重機者，不在此限。第52條則規定水平伸臂應以全長設置走道。",
 "What must a jib crane over three tonnes have on non-horizontal jibs?",
 ["A climbing ladder, unless an inspection platform or easy ground inspection exists","A walkway, unless an inspection platform or easy ground inspection exists","A climbing ladder, though cranes under ten tonnes lifting load are always exempt","A guard net, unless an inspection platform or easy ground inspection exists"],
 "Article 53 requires ladders on non-horizontal jibs."),
]
