# -*- coding: utf-8 -*-
# 第 11 批（B2）：高壓氣體勞工安全規則（111/9/14）第52條～第107條 補題
HG = "OSH-41"
Q = [
(HG,"第52條",3,"高壓氣體-儲槽配管",
 "儲存可燃性氣體、毒性氣體或氧氣之儲槽，其輸出或接受氣體之配管應設置幾具閥？有何操作要求？",
 ["除緊急遮斷裝置之閥類外應設二具以上之閥，其一應置於儲槽近接處且非輸送期間經常關閉","除緊急遮斷裝置之閥類外應設一具閥即可，該閥應置於儲槽近接處且應經常保持全開放狀態","除逆止閥外應設三具以上之閥，其中二具應置於距儲槽五公尺以外並於輸送期間關閉","除安全閥外應設二具以上之閥，二具均應置於防液堤外側並於輸送期間全部保持關閉"],"a",
 "第52條：設置於儲存可燃性氣體、毒性氣體或氧氣之儲槽之配管（輸出或接受該氣體用，含連接部分），除依第53條設置緊急遮斷裝置之閥類外，應設二具以上之閥；其一應置於該儲槽之近接處，該閥在輸出或接受氣體以外之期間應經常關閉。第53條並定內容積五千公升以上液化氣體儲槽應於距儲槽外側五公尺以上安全處所設緊急遮斷裝置。",
 "How many valves must piping for flammable, toxic or oxygen storage tanks have, and how are they operated?",
 ["At least two valves besides emergency shut-off valves, one close to the tank and kept shut when idle","Only one valve besides emergency shut-off valves, placed close to the tank and kept fully open always","At least three valves besides check valves, two placed over five metres away and shut while transferring","At least two valves besides safety valves, both placed outside the dike and shut while transferring gas"],
 "Article 52; see also Article 53 on emergency shut-off devices."),

(HG,"第55條",2,"高壓氣體-緊急電源",
 "為確保製造安全，哪些設施應設置不因停電導致失卻安全功能之緊急電源或輔助措施？",
 ["自動控制裝置、撒水裝置、消防設備、製造設備之冷卻水泵及緊急照明設備等","僅限緊急照明設備及通報設備，其餘設施得於停電後以人工操作方式因應","僅限氣體漏洩檢知警報設備及除毒設備，其他設施不受緊急電源規定之限制","僅限儲槽之緊急遮斷裝置及液面計，其餘設施得由目的事業主管機關另定之"],"a",
 "第55條：自動控制進行反應、分離、精煉、蒸餾等製造設備之控制裝置，依第56條、第57條或第62條設置之撒水裝置，依第67條設置之消防設備，製造設備之冷卻水泵、緊急照明設備及其他為確保製造安全經中央主管機關規定之設施，應設置不因停電導致該設施失卻安全功能之緊急電源或採取其他輔助措施。第243條定本條不適用於冷凍用高壓氣體。",
 "Which facilities must have an emergency power source so they keep working during a power failure?",
 ["Automatic control devices, sprinkler systems, fire equipment, cooling water pumps and emergency lighting","Only emergency lighting and communication devices, other facilities may be operated manually instead","Only gas leak detection alarms and detoxification equipment, other facilities are exempt from the rule","Only tank emergency shut-off devices and level gauges, the rest being left to the competent authority"],
 "Article 55 lists the facilities needing emergency power."),

(HG,"第56條",2,"高壓氣體-撒水裝置",
 "灌裝壓縮乙炔氣於容器之場所及灌氣容器放置場，應設置何種設施？",
 ["應設置不因火災致使容器發生破裂之撒水裝置","應設置可自動偵測乙炔濃度之漏洩檢知警報設備","應設置厚度九公分以上鋼筋混凝土造之防護牆","應設置可將乙炔緩緩排放至大氣之釋放管設施"],"a",
 "第56條：灌裝壓縮乙炔氣於容器之場所及第79條之灌氣容器放置場應設不因火災致使容器發生破裂之撒水裝置。第58條另規定放置壓縮機或灌裝壓縮乙炔氣之場所與灌氣容器放置場間應分設厚度十二公分以上鋼筋混凝土造防護牆；第71條第四款並定乙炔灌裝壓力在每平方公分二十五公斤以下。",
 "What must be installed at places filling compressed acetylene and at filled-cylinder storage yards?",
 ["A sprinkler system preventing containers from rupturing in a fire","An automatic detection alarm measuring acetylene concentration levels","A protective wall of reinforced concrete at least nine centimetres thick","A relief pipe allowing acetylene to be discharged slowly into the air"],
 "Article 56; compare Article 58."),

(HG,"第57條",3,"高壓氣體-液化石油氣",
 "設置於地盤上之液化石油氣儲槽及其支柱，應採取何種防火措施？",
 ["應以不燃性絕熱材料被覆構築耐熱性構造，或於距外面五公尺以上處設可操作之冷卻撒水設備","應以厚度十二公分以上鋼筋混凝土防護牆包圍，或於距外面二公尺以上處設可操作之滅火設備","應以防液堤圍繞並填足乾砂，或於距外面十公尺以上處設可操作之氣體漏洩檢知警報設備","應以紅色塗裝並標示氣體名稱，或於距外面三公尺以上處設可操作之緊急遮斷與逆止裝置"],"a",
 "第57條：設置於地盤上之液化石油氣儲槽及其支柱，應以不燃性絕熱材料被覆等構築之耐熱性構造；或於距離該儲槽及其支柱之外面五公尺以上之處所設置可操作之冷卻用撒水設備或其他冷卻裝置。第87條加氣站及第120條液化石油氣儲存場均準用本條。",
 "What fire protection is required for above-ground LPG storage tanks and their supports?",
 ["Heat-resistant construction clad in non-combustible insulation, or cooling sprinklers operable from five metres away","Enclosure by reinforced concrete walls twelve centimetres thick, or fire extinguishers operable from two metres away","A dike packed with dry sand around the tank, or gas leak detection alarms operable from ten metres away","Red painting with the gas name displayed, or emergency shut-off and check devices operable from three metres away"],
 "Article 57; applied by Articles 87 and 120."),

(HG,"第59條",3,"高壓氣體-防護牆",
 "壓縮機與使用每平方公分多少壓力以上灌注壓縮氣體於容器之場所或灌氣容器放置場間，應分設何種防護牆？",
 ["每平方公分一百公斤以上；厚度十二公分以上鋼筋混凝土造或同等強度之防護牆","每平方公分五十公斤以上；厚度九公分以上鋼筋混凝土造或同等強度之防護牆","每平方公分二十五公斤以上；厚度十五公分以上鋼筋混凝土造或同等強度防護牆","每平方公分二百公斤以上；厚度六公分以上鋼筋混凝土造或同等強度之防護牆"],"a",
 "第59條：壓縮機與使用每平方公分一百公斤以上之壓力灌注壓縮氣體於容器之場所或與第79條規定之灌氣容器放置場間，應分設厚度在十二公分以上鋼筋混凝土造或具有與此同等以上強度結構之防護牆。第58條對壓縮乙炔氣場所亦定相同厚度之防護牆；第79條第八款則定容器放置場防護牆厚度九公分以上。",
 "Above what filling pressure must a protective wall separate the compressor from the filling place, and of what thickness?",
 ["At or above 100 kg/cm2; a reinforced concrete wall at least 12 centimetres thick or equivalent","At or above 50 kg/cm2; a reinforced concrete wall at least 9 centimetres thick or equivalent","At or above 25 kg/cm2; a reinforced concrete wall at least 15 centimetres thick or equivalent","At or above 200 kg/cm2; a reinforced concrete wall at least 6 centimetres thick or equivalent"],
 "Article 59; compare Articles 58 and 79."),

(HG,"第60條",2,"高壓氣體-警報設備",
 "可燃性氣體或毒性氣體之製造設備中，有氣體漏洩致積滯之虞之場所，應設置何種設備？",
 ["應設可探測該漏洩氣體且自動發出警報之氣體漏洩檢知警報設備","應設可吸收該漏洩氣體且自動中和之除毒設備及吸收劑儲槽","應設可稀釋該漏洩氣體且自動送風之局部排氣及整體換氣設備","應設可遮斷該漏洩氣體且自動停止之緊急遮斷裝置及逆止閥"],"a",
 "第60條：可燃性氣體或毒性氣體之製造設備中，有氣體漏洩致積滯之虞之場所，應設可探測該漏洩氣體，且自動發出警報之氣體漏洩檢知警報設備。第167條對消費設備亦有相同規定，但液氧除外；第61條另規定毒性氣體製造設備之防毒措施。",
 "What must be installed where leaked flammable or toxic gas may accumulate in manufacturing equipment?",
 ["A gas leak detection alarm that detects the leaked gas and sounds an alarm automatically","A detoxification unit with absorbent tanks that absorbs and neutralises the leaked gas","Local exhaust and general ventilation that dilutes the leaked gas and supplies fresh air","An emergency shut-off device with check valve that cuts off the leaked gas automatically"],
 "Article 60; compare Article 167 for consumption equipment."),

(HG,"第61條",2,"高壓氣體-防毒",
 "毒性氣體之製造設備應設置氣體漏洩時之防毒措施，其內容為何？",
 ["防止漏洩氣體擴散之裝置、依氣體毒性選擇吸收設備及吸收劑、防毒面罩保管於安全場所","以水噴霧稀釋漏洩氣體、設置排放於大氣之釋放管、防毒面罩由勞工自行保管備用","設置防液堤及乾砂填充層、以惰性氣體置換設備內部、防毒面罩置於作業現場入口","設置厚度十二公分防護牆、以撒水裝置降溫、防毒面罩由承攬人負責維護及保管"],"a",
 "第61條：毒性氣體之製造設備應依下列規定設置氣體漏洩時之防毒措施：一、可適當防止漏洩氣體擴散之裝置。二、應依該氣體毒性、氣體種類、數量及製程，選擇吸收各該毒性氣體之設備及吸收劑。三、防毒面罩及其他防護具應保管於安全場所，並經常維護於適當狀態。第163條對液氨或液氯之消費設備亦有相同規定。",
 "What anti-poison measures must toxic gas manufacturing equipment provide?",
 ["Devices preventing diffusion, absorbers and absorbents matched to the gas, and masks kept safely maintained","Water spray dilution of leaked gas, a relief pipe discharging to air, and masks kept by each worker himself","A dike with dry sand fill, inert gas purging of the equipment, and masks placed at the worksite entrance","A protective wall twelve centimetres thick, sprinkler cooling, and masks maintained by the contractor"],
 "Article 61; the same scheme appears in Article 163."),

(HG,"第62條",2,"高壓氣體-儲槽",
 "可燃性氣體或毒性氣體之儲槽，及鄰近可燃性氣體儲槽或處置可燃性物質設備之其他儲槽，其四周及支柱應如何處理？",
 ["應採取防止溫升之必要措施","應採取防止靜電蓄積之措施","應採取防止基礎沈陷之措施","應採取防止腐蝕生鏽之措施"],"a",
 "第62條：可燃性氣體或毒性氣體之儲槽，或此等儲槽以外之儲槽而鄰近於可燃性氣體儲槽或處置可燃性物質之設備之四周及此等之支柱，應採取防止溫升之必要措施。第55條所稱撒水裝置即包括依本條設置者；第57條對地盤上液化石油氣儲槽另有耐熱構造或冷卻撒水之規定。",
 "What must be done around flammable or toxic gas tanks and their supports?",
 ["Necessary measures to prevent temperature rise","Necessary measures to prevent static accumulation","Necessary measures to prevent foundation settlement","Necessary measures to prevent corrosion and rusting"],
 "Article 62; see also Articles 55 and 57."),

(HG,"第63條",2,"高壓氣體-標示",
 "為區別毒性氣體製造設施與其他製造設施，應如何標示？",
 ["於其外部設置容易辨識為毒性氣體製造設施之措施，並於泵、閥、接頭等標示毒性危害","於其內部設置紅色警示燈及警報器，並於廠房出入口標示禁止無關人員進入之告示","於其外部塗以紅色或以紅字書明氣體名稱，並於儲槽壁面標示最高使用壓力之位置","於其四周設置境界線與圍籬，並於事業場所大門標示緊急聯絡人姓名及電話號碼"],"a",
 "第63條：為區別毒性氣體製造設施與其他製造設施，應於其外部設置容易辨識其為毒性氣體製造設施之必要措施，且在該設施之泵、閥、接頭及其他有漏洩氣體之虞之處所，標示其具有毒性之危害。第36條另定可燃性氣體儲槽應塗紅色或以紅字書明氣體名稱。",
 "How must toxic gas manufacturing facilities be marked?",
 ["Externally marked so they are easily identified, with toxicity warnings on pumps, valves and joints","Internally fitted with red warning lights and sirens, with no-entry notices at the plant entrances","Externally painted red or lettered in red with the gas name, with maximum pressure marked on tanks","Surrounded by a boundary line and fence, with emergency contact names and numbers at the gate"],
 "Article 63; compare Article 36 on flammable-gas tanks."),

(HG,"第65條",2,"高壓氣體-配管",
 "毒性氣體之氣體設備之配管，在必要處所應採用何種構造？",
 ["應依氣體種類、性狀、壓力及配管鄰近狀況，在必要處所採用二重管構造","應依氣體種類、性狀、壓力及配管鄰近狀況，在必要處所採用可撓管構造","應依氣體種類、性狀、壓力及配管鄰近狀況，在必要處所採用地下埋設構造","應依氣體種類、性狀、壓力及配管鄰近狀況，在必要處所採用玻璃襯裡構造"],"a",
 "第65條：毒性氣體之氣體設備之配管，應依各該氣體之種類、性狀、壓力及該配管鄰近狀況，在必要處所採用二重管構造。第64條並規定毒性氣體氣體設備之配管、管接頭及閥之接合應採熔接接合，不適於熔接者得以具必要強度之凸緣接合代替；第165條對液氨或液氯之消費設備配管亦有二重管規定。",
 "What piping construction is required at necessary points for toxic gas equipment?",
 ["Double-pipe construction according to the gas type, properties, pressure and surroundings","Flexible-hose construction according to the gas type, properties, pressure and surroundings","Underground buried construction according to the gas type, properties, pressure and location","Glass-lined construction according to the gas type, properties, pressure and surroundings"],
 "Article 65; compare Articles 64 and 165."),

(HG,"第66條",1,"高壓氣體-靜電",
 "可燃性氣體製造設備，對靜電應採取何種措施？",
 ["應採取可除卻該設備產生之靜電之措施","應採取可承受該設備爆炸壓力之防爆牆","應採取可探測該設備漏洩氣體之警報器","應採取可降低該設備表面溫度之撒水器"],"a",
 "第66條：可燃性氣體製造設備，應採取可除卻該設備產生之靜電之措施。第92條第五款及第93條第七款對移動式製造設備灌裝時亦要求除卻靜電；第166條對可燃性氣體之消費設備有相同要求。",
 "What must be done about static electricity in flammable gas manufacturing equipment?",
 ["Measures capable of eliminating static electricity generated by the equipment","Blast walls capable of withstanding an explosion pressure of the equipment","Alarm detectors capable of sensing gas leaking from the equipment concerned","Sprinklers capable of lowering the surface temperature of the equipment"],
 "Article 66; compare Articles 92, 93 and 166."),

(HG,"第67條",1,"高壓氣體-消防",
 "可燃性氣體及氧氣之製造設備，應依何規定設置消防設備？",
 ["應依消防法有關規定設置必要之消防設備","應依建築技術規則設置必要之滅火器具","應依職業安全衛生設施規則設置滅火器","應依危險物品管理辦法設置泡沫滅火設施"],"a",
 "第67條：可燃性氣體及氧氣之製造設備，應依消防法有關規定設必要之消防設備。第91條對移動式製造設備、第168條對壓縮氫氣、壓縮天然氣、液氧及液氨之消費設備、第177條對特定液化石油氣消費設備均有依消防法設置消防設備之規定。",
 "Under what law must fire-fighting equipment be provided for flammable gas and oxygen manufacturing equipment?",
 ["Under the relevant provisions of the Fire Services Act","Under the Building Technical Regulations for extinguishers","Under the Occupational Safety and Health Facilities Rules","Under the Regulations on Management of Dangerous Goods"],
 "Article 67; the same requirement appears in Articles 91, 168 and 177."),

(HG,"第68條",1,"高壓氣體-通報",
 "事業場所對緊急災害之聯絡，應設置何種設備？",
 ["應依規模及製造設施形態，設發生緊急災害時可迅速聯絡之通報設備","應依規模及製造設施形態，設可自動偵測災害發生之火警自動警報設備","應依規模及製造設施形態，設可供全體人員避難之緊急避難梯及通道","應依規模及製造設施形態，設可供緊急搶救使用之防護具及急救器材"],"a",
 "第68條：事業場所應依其規模及製造設施之形態，在事業場所內設發生緊急災害時，可迅速聯絡之通報設備。第218條並要求甲類製造事業單位訂定災害防止規章，含製造設施遭遇緊急狀態時之應變措施及演練事項。",
 "What must premises provide for emergency communication?",
 ["Communication equipment allowing rapid contact in an emergency, matched to scale and facility type","Automatic fire alarm equipment able to detect a disaster automatically, matched to scale and type","Emergency escape stairs and passages for all personnel, matched to the scale and facility type","Protective gear and first-aid equipment for emergency rescue, matched to scale and facility type"],
 "Article 68; see also Article 218."),

(HG,"第69條",2,"高壓氣體-閥操作",
 "設於製造設備之閥或旋塞及其開閉按鈕，於標示上應如何處理？",
 ["應標示開閉方向，安全上有重大影響者並應標示開閉狀況；配管應標示流體種類及流動方向","應標示製造年月日，安全上有重大影響者並應標示耐壓試驗值；配管應標示材質及口徑大小","應標示操作人員姓名，安全上有重大影響者並應標示檢查日期；配管應標示最高使用壓力值","應標示氣體容許濃度，安全上有重大影響者並應標示爆炸界限；配管應標示設置年度與長度"],"a",
 "第69條第一款、第二款：閥之相關裝置應設可明確表示其開閉方向之標示，如該裝置之操作對製造設備在安全上有重大影響者，應設表示其開閉狀況之標示；與該裝置有關之配管，應於近接該裝置之部位以容易識別之方法標示該配管內之氣體或其他流體之種類及流動方向，但使用按鈕操作者不在此限。",
 "How must valves, cocks and their operating buttons on manufacturing equipment be marked?",
 ["Open-close direction marked, open-close status also if safety-critical; piping marked with fluid type and flow direction","Manufacturing date marked, hydrostatic test value also if safety-critical; piping marked with material and bore size","Operator name marked, inspection date also if safety-critical; piping marked with maximum working pressure value","Permissible concentration marked, explosive limits also if safety-critical; piping marked with year installed and length"],
 "Article 69, subparagraphs 1 and 2."),

(HG,"第69條",2,"高壓氣體-閥操作",
 "對於操作上有重大安全影響且不經常使用之閥，及閥之操作場所，應如何處理？",
 ["應予加鎖、鉛封或採其他同等有效措施，供緊急使用者除外；並視機能及使用頻率設作業台","應予拆除手輪並由專人保管鑰匙，全部一律適用；並於操作場所設置隔離之防護牆與屏蔽","應予塗以紅色並標示禁止操作字樣，一律不得開啟；並於操作場所設置監視錄影及警報器","應予設置雙重閥並固定於全開放狀態，不得關閉；並於操作場所設置緊急沖淋及洗眼設備"],"a",
 "第69條第三款、第四款：閥之相關裝置之操作對製造設備在安全上有重大影響且不經常使用者，應予加鎖、鉛封或採取其他同等有效之措施，但供緊急使用者不在此限；在閥之相關裝置操作場所，應視該裝置之機能及使用頻率，設置可確實操作該裝置之作業台。第172條規定消費設備準用本條。",
 "How are safety-critical valves that are seldom used, and valve operating locations, to be handled?",
 ["Locked or lead-sealed unless kept for emergencies; and a work platform provided to suit function and use","Handwheels removed and keys held by a designated person in all cases; and a shielded wall at the location","Painted red and marked do not operate and never opened; and video monitoring and alarms at the location","Fitted with double valves fixed fully open and never closed; and emergency showers and eyewash provided"],
 "Article 69, subparagraphs 3 and 4; applied by Article 172."),

(HG,"第73條、第74條",2,"高壓氣體-液化石油氣",
 "供製造霧劑、打火機用氣體或其他工業用液化石油氣之灌氣容器，及其他液化石油氣，對臭劑各有何規定？",
 ["工業用者應張貼紅字未添加臭劑之貼籤；其他者應添加漏洩含量達千分之一即可察覺臭味之臭劑","工業用者應張貼綠字已添加臭劑之貼籤；其他者應添加漏洩含量達百分之一即可察覺臭味之臭劑","工業用者應張貼黃字限工業使用之貼籤；其他者應添加漏洩含量達萬分之一即可察覺臭味之臭劑","工業用者應張貼藍字禁止家用之貼籤；其他者應添加漏洩含量達千分之五即可察覺臭味之臭劑"],"a",
 "第74條：供為製造霧劑、打火機用氣體或其他工業用液化石油氣之灌氣容器，應張貼以紅字書寫未添加臭劑之貼籤，或灌注於有類似意旨表示之容器；其他液化石油氣應添加當該氣體漏洩於空氣中之含量達容量之千分之一時即可察覺臭味之臭劑。第86條第二款對加氣站灌裝亦有相同臭劑規定。第73條已刪除。",
 "What odorant rules apply to industrial-use LPG cylinders and to other LPG?",
 ["Industrial cylinders carry a red no-odorant-added label; other LPG needs odorant detectable at one part per thousand","Industrial cylinders carry a green odorant-added label; other LPG needs odorant detectable at one part per hundred","Industrial cylinders carry a yellow industrial-use-only label; other LPG needs odorant detectable at one in ten thousand","Industrial cylinders carry a blue not-for-household label; other LPG needs odorant detectable at five parts per thousand"],
 "Article 74 (Article 73 has been deleted); compare Article 86."),

(HG,"第76條",2,"高壓氣體-儲槽",
 "儲存能力達多少之儲槽，應隨時注意有無沈陷現象並採取適當因應措施？",
 ["儲存能力在一百立方公尺或一公噸以上之儲槽","儲存能力在三百立方公尺或三公噸以上之儲槽","儲存能力在一千立方公尺或十公噸以上之儲槽","儲存能力在五十立方公尺或零點五公噸以上者"],"a",
 "第76條：儲存能力在一百立方公尺或一公噸以上之儲槽，應隨時注意有無沈陷現象，如有沉陷現象時，應視其沉陷程度採取適當因應措施。第45條對相同規模儲槽之支柱另定應置於同一基礎並緊密結合；第113條第五款、第174條亦有沈陷注意之規定。",
 "Tanks of what capacity must be watched for settlement at all times?",
 ["Tanks with storage capacity of 100 cubic metres or 1 tonne or more","Tanks with storage capacity of 300 cubic metres or 3 tonnes or more","Tanks with storage capacity of 1,000 cubic metres or 10 tonnes or more","Tanks with storage capacity of 50 cubic metres or 0.5 tonne or more"],
 "Article 76; compare Articles 45, 113 and 174."),

(HG,"第77條",2,"高壓氣體-閥操作",
 "操作製造設備之閥時，應考慮何事項並採取措施？該事項應如何落實？",
 ["應考慮閥之材質、構造及使用狀況，防止過巨之力加諸於閥上，並訂入工作守則中","應考慮閥之製造廠牌及價格，防止使用非原廠零件，並報請勞動檢查機構核備","應考慮閥之開啟次數及年限，每屆滿三年即予汰換，並將紀錄保存五年備查","應考慮閥之顏色及編號，由二人以上共同操作，並全程錄影存證備供查核"],"a",
 "第77條：操作製造設備之閥時，應考慮該閥之材質、構造及使用狀況、採取必要措施以防止過巨之力加諸於閥上，並訂入工作守則中。第113條第六款對儲槽配管之閥、第175條對消費設備之閥、第179條對可燃性氣體等灌氣容器之閥均有相同或準用規定。",
 "What must be considered when operating valves on manufacturing equipment, and how is it implemented?",
 ["The valve material, construction and condition, avoiding excessive force, written into the work rules","The valve brand and price, avoiding non-original parts, and reported to the labour inspection agency","The number of operations and service life, replacing every three years, with records kept five years","The valve colour and number, operated by two persons together, with the whole process video recorded"],
 "Article 77; compare Articles 113, 175 and 179."),

(HG,"第78條",3,"高壓氣體-霧劑",
 "霧劑之製造作業，對製造設備四周及霧劑之壓力與容量有何規定？",
 ["四周二公尺以內不得置放危險性物質；攝氏三十五度時容器內壓八公斤以下且容量在九成以下","四周五公尺以內不得置放危險性物質；攝氏四十度時容器內壓十公斤以下且容量在八成以下","四周十公尺以內不得置放危險性物質；攝氏二十度時容器內壓四公斤以下且容量在七成以下","四周一公尺以內不得置放危險性物質；攝氏五十度時容器內壓十五公斤以下且容量在九五成以下"],"a",
 "第78條第二款、第五款：霧劑製造設備之四周二公尺以內不得置放中央主管機關指定之危險性物質；霧劑應控制於溫度攝氏三十五度時該容器內壓可維持在每平方公分八公斤以下，且霧劑容量應保持在該容器內容積百分之九十以下之條件下製造。另第三款規定應在不燃性材料構築或被覆之室內製造並嚴禁煙火。",
 "For aerosol manufacturing, what limits apply around the equipment and to pressure and fill volume?",
 ["No dangerous substances within two metres; internal pressure 8 kg/cm2 at 35 C and volume at 90 percent or less","No dangerous substances within five metres; internal pressure 10 kg/cm2 at 40 C and volume at 80 percent or less","No dangerous substances within ten metres; internal pressure 4 kg/cm2 at 20 C and volume at 70 percent or less","No dangerous substances within one metre; internal pressure 15 kg/cm2 at 50 C and volume at 95 percent or less"],
 "Article 78, subparagraphs 2 and 5."),

(HG,"第78條",3,"高壓氣體-霧劑",
 "霧劑製造時之加熱方式，及灌裝有霧劑之容器之試驗，各應如何辦理？",
 ["加熱應使用熱濕布或攝氏四十度以下溫水；容器應全數置於溫水試驗槽維持攝氏四十八度試驗","加熱應使用電熱毯或攝氏六十度以下溫水；容器應抽驗一成置於溫水試驗槽維持攝氏六十度試驗","加熱應使用蒸汽管或攝氏一百度以下熱水；容器應全數置於冷水試驗槽維持攝氏十度以下試驗","加熱應使用紅外線燈或攝氏三十度以下溫風；容器應抽驗半數置於恆溫試驗槽維持攝氏三十五度"],"a",
 "第78條第六款、第八款：為製造霧劑而必需加熱灌氣容器、閥或灌裝管路時，應使用熱濕布或溫度在攝氏四十度以下之溫水；灌裝有霧劑之容器，應全數置於溫水試驗槽內維持其溫度於攝氏四十八度或依中央主管機關規定方法試驗時，不致使該霧劑發生漏洩。第七款另定必須顛倒容器時應使用可固定該容器之倒轉台。",
 "How may aerosol containers be heated, and how are filled aerosol containers tested?",
 ["Heat with hot wet cloth or warm water up to 40 C; all containers tested in a water bath held at 48 C","Heat with an electric blanket or warm water up to 60 C; ten percent sampled in a water bath held at 60 C","Heat with a steam pipe or hot water up to 100 C; all containers tested in a cold water bath below 10 C","Heat with an infrared lamp or warm air up to 30 C; half sampled in a constant temperature bath at 35 C"],
 "Article 78, subparagraphs 6 and 8."),

(HG,"第81條",2,"高壓氣體-液化石油氣",
 "經認定對公共具有危險之液化石油氣儲槽，應如何設置？",
 ["應埋設於地盤內","應設置於屋頂上","應圍以防液堤","應塗以紅色標記"],"a",
 "第81條：經中央主管機關及目的事業主管機關認定對公共具有危險之液化石油氣儲槽應埋設於地盤內。第82條並定該儲槽應設於厚度三十公分以上混凝土造儲槽室內，頂部至少距地面六十公分，併設二個以上儲槽時面間距應在一公尺以上；第83條定一部分埋於地盤內者，埋設部分應施防鏽措施。",
 "How must LPG tanks recognised as dangerous to the public be installed?",
 ["They must be buried within the ground base","They must be installed on the building roof","They must be surrounded by a liquid dike","They must be painted with red markings"],
 "Article 81; Articles 82 and 83 set the details."),

(HG,"第83條",2,"高壓氣體-液化石油氣",
 "埋設之液化石油氣儲槽如僅一部分埋於地盤內時，應如何處理？",
 ["該埋設部分應施以防鏽措施","該露出部分應施以防火被覆","該埋設部分應填足乾砂圍繞","該露出部分應設置防護柵欄"],"a",
 "第83條：第82條之儲槽之一部分埋於地盤內時，在該埋設部分應施以防鏽措施。第82條第一款並定得以儲槽四周填足乾砂、埋設於水中或於儲槽室內強制換氣等方式辦理，且施有防鏽措施並固定於地盤者得直接埋設於地盤內。",
 "If only part of a buried LPG tank is under ground, what is required?",
 ["The buried portion must be given anti-rust treatment","The exposed portion must be given fireproof cladding","The buried portion must be surrounded with dry sand","The exposed portion must be fitted with a guard fence"],
 "Article 83, read with Article 82."),

(HG,"第84條",3,"高壓氣體-準用",
 "甲類製造事業單位之第二種製造設備，下列何者屬其應準用之規定？",
 ["事業場所境界警戒標示、氣密構造、耐壓與氣密試驗、防爆電氣設備及容器放置場等規定","儲槽相互間之安全距離、防液堤之設置、耐震構造及緊急遮斷裝置設置等相關規定","液化石油氣儲槽埋設於地盤內、儲槽室之構造及埋設深度六十公分以上等相關規定","冷凍設備壓縮機之設置限制、冷媒設備之氣密耐壓試驗及承液器液面計等相關規定"],"a",
 "第84條：甲類製造事業單位之第二種製造設備，準用第31條、第33條、第38條、第39條、第41條、第43條、第44條、第45條前段、第48條至第49條、第54條及第60條、第66條至第69條、第70條第一款、第71條第七款、第74條至第77條及第79條之規定。第35條、第37條、第46條、第53條、第81條至第83條、第32條、第42條、第51條均未列入準用。",
 "Which rules must Class 2 manufacturing equipment of a Class A enterprise follow by reference?",
 ["Site boundary warning signs, gastight construction, pressure and airtightness tests, explosion-proof wiring and cylinder yards","Separation distances between storage tanks, dike installation, earthquake-resistant construction and emergency shut-off devices","Burial of LPG tanks within the ground, the construction of the tank chamber and burial depth of sixty centimetres","Siting limits for refrigeration compressors, airtightness and pressure tests of refrigerant equipment and receiver level gauges"],
 "Article 84 lists the provisions applied by reference."),

(HG,"第86條",2,"高壓氣體-加氣站",
 "加氣站之液化石油氣灌裝，應採取哪些防止氣體漏洩或爆炸之措施？",
 ["應拆卸容器與裝卸設備之連接部分後始得移動車輛；並添加千分之一即可察覺臭味之臭劑","應於車輛熄火並設置輪擋後始得連接裝卸設備；並添加百分之一即可察覺臭味之臭劑","應於灌裝前實施容器音響檢查及內部檢查；並添加萬分之一即可察覺臭味之臭劑","應於灌裝後靜置二十四小時確認無漏洩；並添加千分之五即可察覺臭味之臭劑"],"a",
 "第86條：液化石油氣之灌裝，應採取防止氣體漏洩或爆炸之措施，並依下列規定：一、應拆卸容器與裝卸設備之連接部分後，始得移動車輛。二、應添加當液化石油氣漏洩於空氣中之含量達容量之千分之一即可察覺臭味之臭劑。第85條另定承受灌裝之車輛應距離地面上儲槽外面三公尺以上，設防護柵者不在此限。",
 "What measures must a filling station take when filling LPG?",
 ["Disconnect the container from the loading equipment before moving the vehicle; add odorant detectable at one per thousand","Stop the engine and chock the wheels before connecting the loading equipment; add odorant detectable at one per hundred","Carry out sound and internal inspection of the container before filling; add odorant detectable at one per ten thousand","Leave the container standing 24 hours after filling to confirm no leak; add odorant detectable at five per thousand"],
 "Article 86; see also Article 85."),

(HG,"第87條",3,"高壓氣體-準用",
 "加氣站之設置，除第八十五條、第八十六條外，下列何者屬其準用之規定？",
 ["液化石油氣儲槽之耐熱性構造或冷卻用撒水設備，及儲槽埋設於地盤內等相關規定","灌裝壓縮乙炔氣場所之撒水裝置，及防護牆厚度十二公分以上等相關之規定","毒性氣體製造設備之防毒措施、配管二重管構造及毒性危害標示等相關規定","冷凍設備壓縮機之設置限制，及冷媒設備之氣密試驗與耐壓試驗等相關規定"],"a",
 "第87條：加氣站除依第85條、第86條規定外，並準用第31條、第33條、第35條至第39條、第41條、第43條至第46條、第48條至第54條、第57條、第60條、第66條至第69條、第70條第一款、第75條至第77條、第79條、第81條至第83條之規定。第56條、第58條、第59條、第61條、第63條至第65條、第32條、第42條均未列入準用。",
 "Besides Articles 85 and 86, which rules apply to a gas filling station by reference?",
 ["Heat-resistant construction or cooling sprinklers for LPG tanks, and burial of tanks within the ground base","Sprinkler systems at compressed acetylene filling places, and protective walls at least twelve centimetres thick","Anti-poison measures for toxic gas equipment, double-pipe construction and toxicity hazard marking rules","Siting limits for refrigeration compressors, and airtightness and hydrostatic tests of refrigerant equipment"],
 "Article 87 lists the provisions applied by reference."),

(HG,"第88條",1,"高壓氣體-移動式",
 "甲類製造事業單位之移動式製造設備，對危險性物質堆積場所有何規定？",
 ["製造設備不得靠近危險性物質之堆積場所","製造設備應設於危險性物質堆積場所下風處","製造設備得緊鄰危險性物質堆積場所設置","製造設備應距危險性物質堆積場所一公尺"],"a",
 "第88條：移動式製造設備不得靠近危險性物質之堆積場所。第89條並定製造設備在從事製造作業中應於外面明顯處所設置警戒標示；第96條、第98條第二款規定乙類製造事業單位之移動式製造設備準用第88條至第91條。",
 "What rule applies to mobile manufacturing equipment near stacks of dangerous substances?",
 ["The equipment must not be placed close to places stacking dangerous substances","The equipment must be sited downwind of places stacking dangerous substances","The equipment may be placed immediately adjacent to such stacking places","The equipment must be kept one metre away from such stacking places"],
 "Article 88; see also Articles 89 and 96."),

(HG,"第89條",1,"高壓氣體-移動式",
 "移動式製造設備在從事製造作業中，應如何標示？",
 ["應於外面明顯處所設置警戒標示","應於車輛前後設置車輛編號標示","應於作業區域設置人員管制標示","應於容器外面設置耐壓試驗標示"],"a",
 "第89條：移動式製造設備在從事製造作業中，應於外面明顯處所設置警戒標示。第31條對固定式製造設備之事業場所亦要求設置容易辨識之警戒標示；第79條第一款則要求容器放置場外面明顯處所設置警戒標示。",
 "How must mobile manufacturing equipment be marked while manufacturing is under way?",
 ["A warning sign must be posted at a conspicuous place outside","A vehicle number plate must be posted at the front and rear","A personnel control sign must be posted in the working area","A pressure test mark must be posted on the container outside"],
 "Article 89; compare Articles 31 and 79."),

(HG,"第90條",2,"高壓氣體-移動式",
 "移動式製造設備之高壓氣體設備，其試驗及厚度應準用何項規定？",
 ["應經耐壓試驗及氣密試驗合格並具一定厚度，試驗及厚度準用高壓氣體設備之規定","應經超音波探傷及磁粉探傷檢查合格，試驗及厚度準用冷凍機器容器之相關規定","應經構造檢查及重新檢查合格，試驗及厚度準用高壓氣體特定設備之相關規定","應經放射線檢查及浸透探傷試驗合格，試驗及厚度準用導管設置之相關規定"],"a",
 "第90條：移動式製造設備之高壓氣體設備（除容器及中央主管機關規定者外）應經耐壓試驗、氣密試驗合格，並具一定之厚度；前項試驗及厚度，準用第41條及第43條之規定，即以常用壓力一．五倍以上實施耐壓試驗、常用壓力以上實施氣密試驗，並具常用壓力二倍以上加壓不致降伏變形之厚度。",
 "What tests and thickness rules apply to high-pressure gas equipment of mobile manufacturing equipment?",
 ["It must pass hydrostatic and airtightness tests and meet thickness rules for high-pressure gas equipment","It must pass ultrasonic and magnetic particle testing and meet thickness rules for refrigeration containers","It must pass construction and re-inspection checks and meet thickness rules for specified pressure equipment","It must pass radiographic and penetrant testing and meet thickness rules applying to pipeline installation"],
 "Article 90, applying Articles 41 and 43."),

(HG,"第91條",1,"高壓氣體-移動式",
 "移動式製造設備中可燃性氣體及氧氣之製造設備，應設置何種設備？",
 ["應依消防法有關規定設置必要之滅火設備","應依環境保護有關規定設置必要之除毒設備","應依建築管理法規設置必要之防火區劃設施","應依消防法有關規定設置必要之緊急照明設備"],"a",
 "第91條：移動式製造設備中，可燃性氣體及氧氣之製造設備，應依消防法有關規定設置必要之滅火設備。第67條對固定式製造設備亦定應依消防法設必要之消防設備；第93條第九款規定液化石油氣灌裝並準用第67條。",
 "What must be provided for flammable gas and oxygen mobile manufacturing equipment?",
 ["Necessary fire extinguishing equipment under the Fire Services Act","Necessary detoxification equipment under environmental protection law","Necessary fire compartmentation under the building administration rules","Necessary emergency lighting equipment under the Fire Services Act"],
 "Article 91; compare Article 67."),

(HG,"第92條",3,"高壓氣體-移動式",
 "移動式製造設備灌注液化氣體於儲槽時，其容量限制及對原動機火花之要求為何？",
 ["不得超過該儲槽常用溫度下槽內容積之百分之九十；使用液化石油氣等設備時應防止原動機產生火花","不得超過該儲槽常用溫度下槽內容積之百分之八十；使用液化石油氣等設備時應停止原動機並熄火","不得超過該儲槽常用溫度下槽內容積之百分之九十五；使用液化石油氣等設備時應加裝防爆型排氣管","不得超過該儲槽常用溫度下槽內容積之百分之七十；使用液化石油氣等設備時應以惰性氣體先行置換"],"a",
 "第92條第二款、第三款：灌注液化氣體於儲槽時，應控制該液化氣體容量不超過該儲槽在常用溫度下槽內容積之百分之九十；使用液化石油氣、環丙烷、甲胺、二甲醚及此等之混合物製造設備灌裝高壓氣體時，應採防止該設備之原動機產生之火花。第71條第一款對固定式製造設備亦定百分之九十之上限，並要求液化毒性氣體儲槽設自動探測及警報設施。",
 "When mobile equipment fills liquefied gas into a tank, what volume limit and engine-spark rule apply?",
 ["Not over 90 percent of tank volume at normal temperature; sparks from the prime mover must be prevented","Not over 80 percent of tank volume at normal temperature; the prime mover must be stopped and switched off","Not over 95 percent of tank volume at normal temperature; an explosion-proof exhaust pipe must be fitted","Not over 70 percent of tank volume at normal temperature; the tank must first be purged with inert gas"],
 "Article 92, subparagraphs 2 and 3; compare Article 71."),

(HG,"第92條",2,"高壓氣體-移動式",
 "移動式製造設備將高壓氣體灌注於固定在車輛上內容積多少以上之容器或自其抽出時，應採何措施？並對靜電有何要求？",
 ["內容積五千公升以上；應設置適當之輪擋並加以固定，灌裝可燃性氣體並應除卻靜電","內容積一千公升以上；應設置適當之防護柵並加以固定，灌裝可燃性氣體並應接地","內容積三千公升以上；應設置適當之滅火器並加以固定，灌裝可燃性氣體並應通風","內容積一萬公升以上；應設置適當之防液堤並加以固定，灌裝可燃性氣體並應撒水"],"a",
 "第92條第五款、第六款：灌裝可燃性氣體時應採取可除卻該設備可能產生靜電之措施；將高壓氣體灌注於固定在車輛上內容積在五千公升以上之容器或自該容器抽出高壓氣體時，應在該車輛設置適當之輪擋並加以固定。第71條第三款對固定式製造設備亦有相同之五千公升輪擋規定。",
 "Vehicles with containers of what volume need wheel chocks during filling or withdrawal, and what static rule applies?",
 ["5,000 litres or more; suitable wheel chocks and fixing, plus static elimination when filling flammable gas","1,000 litres or more; suitable guard fences and fixing, plus earthing when filling flammable gas into them","3,000 litres or more; suitable extinguishers and fixing, plus ventilation when filling flammable gas in them","10,000 litres or more; suitable dikes and fixing, plus water spraying when filling flammable gas into them"],
 "Article 92, subparagraphs 5 and 6; compare Article 71."),

(HG,"第94條",2,"高壓氣體-準用",
 "甲類製造事業單位之冷凍用高壓氣體製造設備，下列何者屬其準用之規定？",
 ["境界警戒標示、冷凍設備壓縮機設置限制、冷媒設備之耐壓氣密試驗及承液器液面計等","儲槽相互間安全距離、防液堤設置、耐震構造及儲槽配管緊急遮斷裝置等相關規定","毒性氣體製造設備之防毒措施、配管熔接接合及二重管構造等相關之各項規定","液化石油氣儲槽埋設地盤內、儲槽室構造及加氣站承受灌裝車輛距離等規定"],"a",
 "第94條：冷凍用高壓氣體製造設備，準用第31條、第32條、第38條、第40條、第42條、第48條、第50條、第51條、第67條之規定，即包括事業場所境界線與警戒標示、冷凍設備壓縮機等之設置限制、廠房不滯留構造、防漏洩構造、冷媒設備氣密與耐壓試驗、壓力表與安全裝置、低溫儲槽防破裂措施、液面計及消防設備。",
 "Which rules apply by reference to refrigeration high-pressure gas manufacturing equipment of a Class A enterprise?",
 ["Boundary warning signs, siting limits for refrigeration compressors, refrigerant equipment tests and receiver level gauges","Separation distances between tanks, dike installation, earthquake-resistant construction and tank emergency shut-off devices","Anti-poison measures for toxic gas equipment, welded joints for piping and double-pipe construction requirements","Burial of LPG tanks in the ground, tank chamber construction and vehicle distance rules at gas filling stations"],
 "Article 94 lists the provisions applied by reference."),

(HG,"第95條",3,"高壓氣體-乙類",
 "乙類製造事業單位之固定式製造設備，下列何者屬其準用之規定？",
 ["境界警戒標示、可燃性氣體儲槽塗紅色、氣密構造、防爆電氣設備及毒性氣體防毒措施等","儲槽相互間之安全距離、防液堤設置、耐震構造及儲槽配管之緊急遮斷裝置等規定","液化石油氣儲槽之耐熱構造、埋設於地盤內及儲槽室構造等相關之各項規定","冷凍設備壓縮機之設置限制、冷媒設備之氣密試驗與耐壓試驗等相關規定"],"a",
 "第95條：乙類製造事業單位之固定式製造設備之設置，準用第31條、第33條、第36條、第38條、第39條、第41條、第43條、第48條、第49條、第51條、第54條、第60條、第63條至第67條之規定，包含警戒標示、與處理煙火設備距離八公尺、儲槽塗紅色、氣密構造、耐壓與氣密試驗、壓力表與釋放管、液面計、防爆電氣設備、漏洩警報、毒性標示、熔接接合、二重管、靜電除卻及消防設備。",
 "Which rules apply by reference to fixed manufacturing equipment of a Class B enterprise?",
 ["Boundary warning signs, red painting of flammable gas tanks, gastight construction, explosion-proof wiring and anti-poison measures","Separation distances between storage tanks, dike installation, earthquake-resistant construction and tank emergency shut-off devices","Heat-resistant construction of LPG tanks, burial within the ground base and construction rules for the tank chamber","Siting limits for refrigeration compressors, and airtightness and hydrostatic testing of refrigerant equipment generally"],
 "Article 95 lists the provisions applied by reference."),

(HG,"第96條",1,"高壓氣體-乙類",
 "乙類製造事業單位之移動式製造設備，其設置準用何種規定？",
 ["準用不得靠近危險性物質堆積場所、警戒標示、耐壓氣密試驗及滅火設備等規定","準用儲槽相互間距離、防液堤設置、耐震構造及緊急遮斷裝置設置等相關規定","準用毒性氣體防毒措施、二重管構造、熔接接合及毒性危害標示等相關規定","準用液化石油氣儲槽埋設地盤內、儲槽室構造及防鏽措施等相關之各項規定"],"a",
 "第96條：乙類製造事業單位之移動式製造設備之設置，準用第88條至第91條之規定，即不得靠近危險性物質堆積場所、作業中應設警戒標示、高壓氣體設備應經耐壓與氣密試驗合格並具一定厚度、可燃性氣體及氧氣製造設備應依消防法設滅火設備。",
 "Which rules apply by reference to mobile manufacturing equipment of a Class B enterprise?",
 ["Keeping away from dangerous substance stacks, warning signs, pressure and airtightness tests, and extinguishers","Separation distances between storage tanks, dike installation, earthquake-resistant construction and shut-off devices","Anti-poison measures for toxic gas, double-pipe construction, welded joints and toxicity hazard marking rules","Burial of LPG tanks within the ground base, tank chamber construction and anti-rust treatment requirements"],
 "Article 96, applying Articles 88 to 91."),

(HG,"第98條",3,"高壓氣體-乙類",
 "乙類液化石油氣製造事業單位之製造作業，有哪些特別規定？",
 ["灌裝時應距處置煙火場所、多數人聚集場所或堆置危險性物質場所五公尺以上；不得灌裝於固定在車輛之容器","灌裝時應距處置煙火場所、多數人聚集場所或堆置危險性物質場所八公尺以上；不得灌裝於內容積千公升以下容器","灌裝時應距處置煙火場所、多數人聚集場所或堆置危險性物質場所三公尺以上；不得灌裝於超低溫或低溫之容器","灌裝時應距處置煙火場所、多數人聚集場所或堆置危險性物質場所十公尺以上；不得灌裝於未設液面計之儲槽"],"a",
 "第98條第三款：乙類液化石油氣製造事業單位之製造作業，灌裝液化石油氣時應距離處置煙火場所、多數人聚集場所或堆置有危險性物質場所五公尺以上；不得灌裝於固定在車輛之容器；並準用第71條第七款、第74條及第79條之規定。第97條第一款對乙類製造事業單位灌注高壓氣體於容器亦定五公尺以上。",
 "What special rules govern manufacturing operations of a Class B LPG enterprise?",
 ["Fill at least 5 metres from open flames, crowded places or dangerous substance stacks; no filling of vehicle-mounted containers","Fill at least 8 metres from open flames, crowded places or dangerous substance stacks; no filling of containers under 1,000 litres","Fill at least 3 metres from open flames, crowded places or dangerous substance stacks; no filling of low-temperature containers","Fill at least 10 metres from open flames, crowded places or dangerous substance stacks; no filling of tanks lacking level gauges"],
 "Article 98, subparagraph 3; compare Article 97."),

(HG,"第98條",2,"高壓氣體-乙類",
 "乙類液化石油氣製造事業單位之固定式製造設備，下列何者屬其準用之規定？",
 ["境界警戒標示、儲槽塗紅色、耐震構造、壓力表與安全裝置、液面計及防爆電氣設備等","毒性氣體之防毒措施、二重管構造、熔接接合及毒性危害標示等相關之各項規定","冷凍設備壓縮機設置限制、冷媒設備氣密與耐壓試驗及承液器液面計等相關規定","灌裝壓縮乙炔氣場所之撒水裝置、防護牆及緊急電源設置等相關之各項規定"],"a",
 "第98條第一款：乙類液化石油氣製造事業單位之固定式製造設備之設置，準用第31條、第33條、第36條、第38條、第39條、第41條、第43條至第46條、第48條、第49條、第51條、第54條、第66條、第67條之規定，其中第46條為塔槽等之耐震構造。毒性氣體相關之第61條至第65條、冷凍相關之第32條、第42條及第56條至第59條均未列入。",
 "Which rules apply by reference to fixed manufacturing equipment of a Class B LPG enterprise?",
 ["Boundary warning signs, red tank painting, earthquake-resistant construction, pressure gauges, level gauges and explosion-proof wiring","Anti-poison measures for toxic gas, double-pipe construction, welded joints and toxicity hazard marking requirements","Siting limits for refrigeration compressors, airtightness and pressure testing of refrigerant equipment and receiver level gauges","Sprinkler systems at compressed acetylene filling places, protective walls and emergency power supply requirements"],
 "Article 98, subparagraph 1."),

(HG,"第99條",3,"高壓氣體-乙類冷凍",
 "乙類冷凍用高壓氣體製造事業單位，於設置或變更製造設備之工程終了時，應如何確認後始得供製造作業使用？",
 ["非經以氧氣以外之氣體試運轉，或以最高使用壓力以上之壓力實施氣密試驗後，不得使用","非經以氧氣試運轉，或以常用壓力二倍以上之壓力實施耐壓試驗合格後，不得供使用","非經以空氣直接試運轉，或以設計壓力三倍以上之壓力實施破壞試驗後，不得供使用","非經勞動檢查機構派員實施構造檢查及重新檢查合格並發給檢查合格證後，不得使用"],"a",
 "第99條第三款第一目：設置或變更製造設備之工程終了時，非經以氧氣以外之氣體試運轉或以最高使用壓力以上之壓力實施氣密試驗（使用空氣時，應於事前排除冷媒設備中之可燃性氣體後實施者為限）後，不得供製造作業使用。第103條規定甲乙類以外之冷凍高壓氣體製造事業單位準用本目。",
 "Before a Class B refrigeration enterprise may use newly installed or altered manufacturing equipment, what is required?",
 ["A trial run with a gas other than oxygen, or an airtightness test at or above maximum working pressure","A trial run using oxygen, or a hydrostatic test at twice or more the normal working pressure passed","A direct trial run with air, or a destructive test at three times or more the design pressure passed","An inspection by the labour inspection agency issuing a construction inspection certificate first"],
 "Article 99, subparagraph 3(1); applied by Article 103."),

(HG,"第100條",2,"高壓氣體-其他事業單位",
 "甲類及乙類製造事業單位以外之製造事業單位，以緩衝裝置及中央主管機關規定之設施從事高壓氣體製造者，應準用何規定？",
 ["準用高壓氣體設備耐壓與氣密試驗、厚度規定及安全閥停止閥全開放等規定","準用儲槽相互間之安全距離、防液堤設置及耐震構造等相關之各項規定","準用毒性氣體防毒措施、二重管構造及毒性危害標示等相關之各項規定","準用液化石油氣儲槽埋設地盤內、儲槽室構造與防鏽措施等相關規定"],"a",
 "第100條第一款：以緩衝裝置及中央主管機關規定之設施從事高壓氣體之製造者，準用第41條、第43條及第70條第一款之規定，即耐壓與氣密試驗、厚度規定，及附設於安全閥或釋放閥之停止閥應經常維持全開放狀態。第二款則對其他設施定準用第70條、第71條、第72條、第97條部分款次。",
 "Which rules apply to non-Class A or B enterprises manufacturing with buffer devices and designated facilities?",
 ["Pressure and airtightness tests, thickness rules for equipment, and keeping safety valve stop valves fully open","Separation distances between storage tanks, dike installation and earthquake-resistant construction requirements","Anti-poison measures for toxic gas, double-pipe construction and toxicity hazard marking requirements","Burial of LPG tanks in the ground base, tank chamber construction and anti-rust treatment requirements"],
 "Article 100, subparagraph 1."),

(HG,"第101條",3,"高壓氣體-製造限制",
 "以導管供應原料氣體予甲類製造事業單位者，下列哪一組氣體不得製造？",
 ["乙炔乙烯氫氣以外可燃性氣體含氧達百分之四；乙炔乙烯或氫氣含氧達百分之二","乙炔乙烯氫氣以外可燃性氣體含氧達百分之二；乙炔乙烯或氫氣含氧達百分之四","乙炔乙烯氫氣以外可燃性氣體含氧達百分之十；乙炔乙烯或氫氣含氧達百分之五","乙炔乙烯氫氣以外可燃性氣體含氧達百分之一；乙炔乙烯或氫氣含氧達百分之零點五"],"a",
 "第101條：可燃性氣體（除乙炔、乙烯及氫氣外）中含氧容量佔全體容量百分之四以上者、乙炔乙烯或氫氣中含氧容量佔百分之二以上者、氧氣中乙炔乙烯及氫氣容量合計佔百分之二以上者、氧氣中可燃性氣體容量佔百分之四以上者，均不得製造。第70條第三款對壓縮亦有相同之百分比限制。",
 "Which combination of gases may not be manufactured by an enterprise supplying raw gas by pipeline to a Class A enterprise?",
 ["Flammable gases other than acetylene, ethylene, hydrogen with 4 percent oxygen; those three with 2 percent oxygen","Flammable gases other than acetylene, ethylene, hydrogen with 2 percent oxygen; those three with 4 percent oxygen","Flammable gases other than acetylene, ethylene, hydrogen with 10 percent oxygen; those three with 5 percent oxygen","Flammable gases other than acetylene, ethylene, hydrogen with 1 percent oxygen; those three with 0.5 percent oxygen"],
 "Article 101; the same limits appear in Article 70."),

(HG,"第102條",2,"高壓氣體-液化石油氣",
 "甲類及乙類製造事業單位以外之液化石油氣製造事業單位，其製造設施準用何規定？",
 ["準用工業用容器臭劑貼籤與添加臭劑，及灌裝距離五公尺與禁灌車輛容器之規定","準用儲槽相互間安全距離、防液堤設置及耐震構造設計等相關之各項規定","準用毒性氣體防毒措施、熔接接合與二重管構造等相關之各項規定內容","準用冷凍設備壓縮機設置限制及冷媒設備氣密耐壓試驗等相關之規定"],"a",
 "第102條：甲類製造事業單位及乙類製造事業單位以外之液化石油氣製造事業單位之製造設施，準用第74條及第98條第三款（一）及（二）之規定，即工業用液化石油氣容器應張貼紅字未添加臭劑貼籤、其他液化石油氣應添加臭劑，以及灌裝時應距煙火等場所五公尺以上、不得灌裝於固定在車輛之容器。",
 "Which rules apply to LPG manufacturers other than Class A and Class B enterprises?",
 ["Odorant labels and odorant addition, plus the five-metre filling distance and the ban on vehicle containers","Separation distances between storage tanks, dike installation and earthquake-resistant design requirements","Anti-poison measures for toxic gas, welded joints and double-pipe construction requirements generally","Siting limits for refrigeration compressors and airtightness and hydrostatic testing of refrigerant units"],
 "Article 102, applying Articles 74 and 98."),

(HG,"第103條",2,"高壓氣體-冷凍",
 "甲類及乙類製造事業單位以外之冷凍高壓氣體製造事業單位，其製造作業準用何規定？",
 ["準用工程終了時應以氧氣以外氣體試運轉或以最高使用壓力以上壓力實施氣密試驗之規定","準用高壓氣體設備應以常用壓力二倍以上壓力加壓不致降伏變形之厚度等相關規定","準用毒性氣體製造設備之防毒措施與吸收劑選擇及防毒面罩保管等相關之規定","準用儲槽相互間之安全距離、防液堤設置及緊急遮斷裝置設置等相關之規定"],"a",
 "第103條：甲類製造事業單位及乙類製造事業單位以外之冷凍高壓氣體製造事業單位之製造設施，其製造作業準用第99條第三款第一目之規定，即設置或變更製造設備之工程終了時，非經以氧氣以外之氣體試運轉或以最高使用壓力以上之壓力實施氣密試驗後，不得供製造作業使用。",
 "Which rule applies to refrigeration high-pressure gas manufacturers other than Class A and Class B enterprises?",
 ["The rule requiring a trial run with non-oxygen gas or an airtightness test at maximum working pressure","The rule requiring equipment thickness that will not yield at twice the normal working pressure applied","The rule requiring anti-poison measures, absorbent selection and safe keeping of respirators for toxic gas","The rule requiring separation distances between tanks, dike installation and emergency shut-off devices"],
 "Article 103, applying Article 99."),

(HG,"第104條",2,"高壓氣體-供應",
 "供應高壓氣體予消費事業單位之供應事業單位，應置備何種文件？",
 ["應置備記載有消費事業單位安全狀況之紀錄簿冊","應置備記載有供應數量與金額之交易憑證及帳冊","應置備記載有容器耐壓試驗值之檢查合格證影本","應置備記載有駕駛人資格與車籍之運輸管理紀錄"],"a",
 "第104條：供應（含與供應有關之儲存及以導管之輸送）高壓氣體予高壓氣體消費事業單位之高壓氣體供應事業單位，應置備記載有消費事業單位安全狀況之紀錄簿冊。第105條對以第一種供應設備供應液化石油氣之第一種供應事業單位亦有相同規定。第242條定本條不適用於液化石油氣。",
 "What document must a high-pressure gas supply enterprise keep?",
 ["A record book recording the safety status of the consuming enterprises","A transaction voucher and ledger recording supply quantities and amounts","A copy of the inspection certificate recording container test pressures","A transport management record of driver qualifications and vehicle data"],
 "Article 104; Article 105 applies the same to Class 1 LPG suppliers."),

(HG,"第105條",2,"高壓氣體-液化石油氣",
 "以第一種供應設備供應液化石油氣之第一種供應事業單位，應置備何種文件？",
 ["應置備記載有消費事業單位安全狀況之紀錄簿冊","應置備記載有灌氣容器數量與流向之管制卡片","應置備記載有臭劑添加濃度之檢驗報告及紀錄","應置備記載有調整器耐壓試驗值之合格證影本"],"a",
 "第105條：以第一種供應設備供應液化石油氣予液化石油氣消費事業單位之液化石油氣供應事業單位（第一種供應事業單位），應置備記載有消費事業單位安全狀況之紀錄簿冊。第24條並定第一種供應設備係在供應事業場所以灌氣容器或殘氣容器供應液化石油氣之各該設備；第235條規定供應事業單位應選任高壓氣體供應安全作業主管。",
 "What document must a Class 1 LPG supply enterprise keep?",
 ["A record book recording the safety status of the consuming enterprises","A control card recording the number and movement of filled cylinders","A test report and record of the odorant concentration actually added","A copy of the certificate recording regulator hydrostatic test values"],
 "Article 105; see also Articles 24 and 235."),

(HG,"第106條",2,"高壓氣體-容器",
 "供應之高壓氣體灌氣容器等，應符合何項要求？",
 ["不得有腐蝕、裂隙、裂痕、皺紋等，且應無漏氣情形","不得有塗裝剝落、標示不清等，且應每年檢驗一次以上","不得有超過有效期限六月者，且應張貼製造年月日貼籤","不得有內容積超過五千公升者，且應設置防波板與液面計"],"a",
 "第106條：高壓氣體灌氣容器等，不得有腐蝕、裂隙、裂痕、皺紋等，且無漏氣者。第108條對供應冷媒氣體之設備亦定不得有腐蝕、裂隙、裂痕、皺紋等致減弱其強度且無漏洩冷媒氣體者；第107條則定壓縮天然氣灌氣容器等應標示使用期間不得超過有效期限六月。第243條定本條不適用於冷凍用高壓氣體。",
 "What condition must filled high-pressure gas cylinders for supply meet?",
 ["Free from corrosion, cracks, fissures or wrinkles, and without any gas leakage","Free from peeling paint or unclear marking, and inspected at least once a year","Free from any exceeding six months validity, with a manufacturing date label","Free from any over 5,000 litres volume, and fitted with baffles and level gauges"],
 "Article 106; compare Articles 107 and 108."),

(HG,"第107條",2,"高壓氣體-容器",
 "壓縮天然氣之灌氣容器等，對使用期間應如何標示？",
 ["應明確標示使用期間不得超過有效期限六月","應明確標示使用期間不得超過有效期限一年","應明確標示使用期間不得超過有效期限三月","應明確標示使用期間不得超過有效期限二年"],"a",
 "第107條：壓縮天然氣之灌氣容器等，應明確標示使用期間不得超過有效期限六月。第116條第三款對氰化氫之儲存亦定自灌裝於容器之日起算不得超過六十日，但純度百分之九十八以上且未著色者不在此限；第106條並定灌氣容器等不得有腐蝕裂痕且無漏氣。",
 "How must the usable period of compressed natural gas cylinders be marked?",
 ["Clearly marked that the period may not exceed six months of validity","Clearly marked that the period may not exceed one year of validity","Clearly marked that the period may not exceed three months of validity","Clearly marked that the period may not exceed two years of validity"],
 "Article 107; compare Articles 106 and 116."),
]
