# -*- coding: utf-8 -*-
# 第 13 批（A3）：補題──水污染防治法施行細則、廢（污）水處理專責單位或人員設置及管理辦法
WR = "ENV-44"; WP = "ENV-46"
Q = [
# ---------- 水污染防治法施行細則（ENV-44） ----------
(WR,"第1條",1,"水污細則-法源",
 "水污染防治法施行細則係依何規定訂定？",
 ["依水污染防治法第七十四條規定訂定","依水污染防治法第二十一條第二項規定訂定","依水污染防治法第十八條之一第四項規定訂定","依水污染防治法第六十三條第二項規定訂定"],"a",
 "第1條：本細則依水污染防治法（以下簡稱本法）第七十四條規定訂定之。水污法第二十一條第二項則為廢（污）水處理專責單位或人員設置及管理辦法之授權依據，兩者不同。第2條並規定本法第二條第八款所稱作業環境，指事業使用之範圍。",
 "The Enforcement Rules of the Water Pollution Control Act are enacted under:",
 ["Article 74 of the Water Pollution Control Act","Article 21(2) of the Water Pollution Control Act","Article 18-1(4) of the Water Pollution Control Act","Article 63(2) of the Water Pollution Control Act"],
 "Article 1; Article 21(2) authorizes the dedicated personnel regulations."),

(WR,"第2條",1,"水污細則-作業環境",
 "本法第二條第八款所稱作業環境，其定義為何？",
 ["指該事業使用之範圍","指事業廠房內生產線區域","指放流口周圍五十公尺內","指土地登記謄本之地界線"],"a",
 "第2條：本法第二條第八款所稱作業環境，指事業使用之範圍。第6條並定義建築物污水處理設施，指處理建築物內人類活動所產生之人體排泄物或其他生活污水之設施。第4條之2則定義家戶為本法第十一條第一項收費對象以外之污水排放者。",
 "What does operating environment in Article 2, Subparagraph 8 of the Act mean?",
 ["The scope used by the enterprise","The production line area inside the plant","Fifty metres around the discharge outlet","The land boundary in the title register"],
 "Article 2; compare Articles 6 and 4-2."),

(WR,"第3條",2,"水污細則-中央權責",
 "依本細則規定，下列何者屬中央主管機關之主管事項？",
 ["全國性水污染防治政策方案與計畫之訂定督導、水污染防治費之徵收審核、檢驗測定機構許可及管理","轄內水污染防治計畫之規劃執行、轄內水污染防治費之使用規劃管理執行、轄內防治人員訓練管理","轄內家戶水污染防治費自治法規之制定審核釋示執行、清查收費對象、催繳及處分等相關業務事項","建築物污水處理設施之設置查驗、下水道用戶接管普及率之管考、污水下水道系統之興建與營運"],"a",
 "第3條：中央主管機關主管事項包括全國性水污染防治政策、方案與計畫之訂定及督導，全國性法規之訂定審核釋示，本法第十一條第一項水污染防治費之徵收、審核、使用規劃及管理，全國性研究發展、人員訓練管理、監測檢驗、調查統計、宣導、國際合作，以及水污染物及水質水量之檢驗測定機構許可及管理等。第4條則規定直轄市、縣（市）主管機關之主管事項。",
 "Which is a matter under the central competent authority?",
 ["National policy, plans and supervision; levying and reviewing the water pollution control fee; licensing testing organisations","Planning and implementing local control plans; local use and management of the fee; local training of control personnel","Local household fee bylaws, review and interpretation; identifying payers; demanding payment and imposing sanctions","Inspecting building sewage facilities; monitoring sewer connection rates; building and operating sewerage systems"],
 "Article 3; compare Article 4."),

(WR,"第4條",2,"水污細則-地方權責",
 "依本細則規定，下列何者屬直轄市、縣（市）主管機關之主管事項？",
 ["轄內水污染防治計畫之規劃及執行、水污染防治法規之執行與自治法規制訂、轄內防治之監測及檢驗","全國性水污染防治法規之訂定審核及釋示、水污染防治費之徵收審核、國際合作及科技交流事項","水污染物及水質水量檢驗測定機構之許可及管理、全國性水污染防治之調查及統計資料之製作","轄內家戶水污染防治費之徵收審核、清查收費對象、使用規劃管理執行與催繳處分等相關事項"],"a",
 "第4條：直轄市、縣（市）主管機關主管事項包括轄內水污染防治計畫之規劃及執行，水污染防治法規之執行與轄內自治法規之制（訂）定、審核、釋示及執行，本法第十一條第一項水污染防治費之使用規劃、管理及執行，轄內研究發展、人員訓練管理、監測檢驗、調查統計及宣導等。徵收審核與檢驗測定機構許可屬第3條中央權責；家戶水污染防治費則屬第4條之1所定地方政府事項。",
 "Which is a matter under the municipal or county competent authority?",
 ["Planning and implementing local control plans; enforcing the Act and making local bylaws; local monitoring and testing","Drafting, reviewing and interpreting national control regulations; levying the fee; international cooperation and exchange","Licensing and managing water quality testing organisations; producing national investigation and statistical data","Levying and reviewing the household fee; identifying payers; planning its use, demanding payment and sanctions"],
 "Article 4; compare Articles 3 and 4-1."),

(WR,"第4條之1",2,"水污細則-家戶費權責",
 "依本細則規定，地方政府就轄內家戶水污染防治費之主管事項為何？",
 ["自治法規之制訂審核釋示及執行、徵收審核清查收費對象、使用規劃管理執行、催繳及處分等事項","全國性水污染防治費之徵收審核與使用規劃、全國性防治人員之訓練管理及國際合作科技交流","水污染物及水質水量檢驗測定機構之許可管理、全國性水污染防治之監測檢驗及調查統計製作","建築物污水處理設施之設計審查與完工查驗、污水下水道系統接管普及率之管考及營運管理"],"a",
 "第4條之1：本法第十一條第二項、第七項、第九項及第四十四條第二項、第三項所定地方政府之主管事項，包括轄內家戶水污染防治費自治法規之制（訂）定、審核、釋示及執行，該費之徵收、審核、清查收費對象、使用規劃、管理、執行、催繳及處分，及其他有關轄內家戶水污染防治費事項。第4條之2並定義家戶為本法第十一條第一項收費對象以外之污水排放者。",
 "What are local government duties over the household water pollution control fee?",
 ["Making, reviewing and enforcing bylaws; levying, reviewing and identifying payers; planning use; collection and sanctions","Levying and planning use of the national fee; national training of control personnel; international cooperation","Licensing and managing water quality testing organisations; national monitoring, testing and statistical work","Reviewing designs and inspecting building sewage facilities; monitoring and operating sewer connection rates"],
 "Article 4-1; see also Article 4-2."),

(WR,"第4條之2",1,"水污細則-家戶定義",
 "本法所稱家戶，其定義為何？",
 ["指本法第十一條第一項收費對象以外之污水排放者","指設有獨立門牌並實際居住使用之住宅建築物","指未接管至公共污水下水道系統之社區及聚落","指每日污水排放量未達五十立方公尺之排放者"],"a",
 "第4條之2：本法第十一條第二項、第三項第二款第七目及第四十四條第二項所稱家戶，指本法第十一條第一項收費對象以外之污水排放者。第4條之1並規定地方政府就轄內家戶水污染防治費之自治法規制訂、徵收審核、清查收費對象、使用規劃管理及催繳處分等主管事項。",
 "How is household defined under the Act?",
 ["A sewage discharger other than those charged under Article 11, Paragraph 1","A residential building with its own street number and actually inhabited","A community or settlement not connected to the public sewerage system","A discharger whose daily sewage volume is under fifty cubic metres"],
 "Article 4-2; see also Article 4-1."),

(WR,"第5條",2,"水污細則-涵容能力",
 "本法第五條所稱利用水體以承受或傳運放流水者不得超過水體之涵容能力，其意義為何？",
 ["指所有污染源排放之總量造成該水體水質之變動，不得超過依本法第六條所訂之水體分類及水質標準","指單一污染源排放之濃度不得超過該事業適用之放流水標準，與其他污染源之排放總量無涉","指水體流量減少時應由主管機關逕行命各污染源按比例減少其排放量至符合原設計流量為止","指利用水體傳運放流水者應先取得水利主管機關核准之取水或排水許可後始得為之之意旨"],"a",
 "第5條：本法第五條所稱利用水體以承受或傳運放流水者不得超過水體之涵容能力，指利用水體以承受或傳運放流水之所有污染源，其排放之總量造成該水體水質之變動，不得超過依本法第六條所訂之水體分類及水質標準。第19條並就本法第三十六條第一項所稱各該管制標準之範圍另有界定。",
 "What does not exceeding the assimilative capacity of a water body mean?",
 ["The total load of all sources must not change water quality beyond the classification and quality standards set under Article 6","A single source concentration must not exceed its effluent standard, irrespective of the total load of all other sources","When flow falls the authority may order every source to cut discharge proportionally until the design flow is restored","Anyone using a water body to convey effluent must first obtain a water intake or drainage permit from water authorities"],
 "Article 5; see also Articles 6 and 19."),

(WR,"第6條",1,"水污細則-建築物污水設施",
 "本法所稱建築物污水處理設施，其定義為何？",
 ["指處理建築物內人類活動所產生之人體排泄物或其他生活污水之設施","指處理工廠製程廢水及冷卻水並符合放流水標準之各類處理設施","指公共污水下水道系統之末端污水處理廠及其抽水站等附屬設施","指建築物屋頂雨水回收再利用及中水道系統之貯存與過濾設施"],"a",
 "第6條：本法第七條第一項、第八條、第二十五條、第二十六條第一項、第六十二條、第六十九條第二項、第三項所稱建築物污水處理設施，指處理建築物內人類活動所產生之人體排泄物或其他生活污水之設施。第2條並定義作業環境指事業使用之範圍。",
 "How is a building sewage treatment facility defined?",
 ["A facility treating human excreta or other domestic sewage from human activity inside the building","A facility treating factory process wastewater and cooling water to meet effluent standards","The terminal treatment plant and pumping stations of the public sewerage system","Rooftop rainwater recovery and reclaimed water storage and filtration equipment"],
 "Article 6; compare Article 2."),

(WR,"第7條",3,"水污細則-技師簽證",
 "技師依本法第十七條第四項規定執行簽證業務時，於設計階段應查核之事項為何？",
 ["廢（污）水水質水量調查推估之確實性合理性、是否需經小型實驗取得可靠設計參數、處理系統設計之功能及計算","事業之公司登記與工廠登記文件是否齊全、負責人資格是否符合規定、員工人數與勞健保投保資料之正確性","放流口座標與告示牌標示是否正確、採樣平台通暢與否、累計型水量計測設施是否正常運作並定期校正","檢測申報資料是否按期填具並簽章、藥品使用量與污泥產生量之月統計、電度表累計讀數之每日簽章紀錄"],"a",
 "第7條第一款：設計階段應查核廢（污）水水質水量調查、推估之確實性及合理性，廢（污）水處理設計是否需經小型實驗、是否已取得必需之可靠設計參數，廢（污）水及污泥處理系統設計之功能及計算是否具備足夠功能及設備，其他法定必要設施設計是否符合規定等。第二款則規範現場查核及業者執行功能測試階段應查核之事項。",
 "At the design stage, what must a certifying professional engineer review?",
 ["Reliability of wastewater quality and quantity surveys, whether pilot tests and design parameters are needed, system function and calculations","Whether company and factory registration papers are complete, the qualification of the responsible person, and insurance records of employees","Whether outlet coordinates and signage are correct, whether the sampling platform is clear, and whether flow meters are calibrated","Whether declarations are filed and signed on time, monthly chemical and sludge statistics, and daily signed meter readings"],
 "Article 7, Subparagraph 1; Subparagraph 2 covers on-site and performance testing."),

(WR,"第10條",3,"水污細則-正常操作",
 "廢（污）水（前）處理設施應維持正常操作，其規定為何？",
 ["應於許可文件登記之操作參數範圍內執行、沉澱設施累積污泥高度應低於水深二分之一、放流水導電度不得低於前一處理設施之百分之八十","應於許可文件登記之操作參數範圍內執行、沉澱設施累積污泥高度應低於水深三分之一、放流水導電度不得低於前一處理設施之百分之五十","應於主管機關核定之設計流量範圍內執行、沉澱設施累積污泥高度應低於水深四分之三、放流水導電度不得高於前一處理設施之百分之六十","應於事業自訂之標準作業程序範圍內執行、沉澱設施累積污泥高度不受限制、放流水導電度不得低於前一處理設施之百分之九十"],"a",
 "第10條第一項：應依水污染防治措施計畫核准文件、排放地面水體許可證、簡易排放許可文件、貯留許可文件、稀釋許可文件及土壤處理許可證等登記之操作參數範圍內執行；沉澱設施之進流端與出流端中心距離處所累積污泥高度應低於水深二分之一；放流水導電度不得低於前一處理設施處理後廢（污）水導電度之百分之八十。第二項並就高低導電度二股以上分別處理共同排放且設有各自採樣口者，得分別認定。",
 "What does maintaining normal operation of wastewater treatment facilities require?",
 ["Operating within permitted parameters; sludge in settling units below half the water depth; effluent conductivity at least 80% of the prior unit","Operating within permitted parameters; sludge in settling units below one third of the depth; conductivity at least 50% of the prior unit","Operating within the approved design flow; sludge below three quarters of the depth; conductivity no more than 60% of the prior unit","Operating within self-written procedures; no limit on sludge height; conductivity at least 90% of the prior treatment unit"],
 "Article 10."),

(WR,"第10條之1",2,"水污細則-稀釋除外",
 "本法所稱稀釋，不包括下列何種情形？",
 ["燃煤發電廠採海水排煙脫硫去除硫氧化物之方法","事業引用自來水稀釋原廢水後再行排放之方法","以未接觸冷卻水混合放流水降低污染物濃度之方法","以貯留槽儲水於雨季一併排放降低濃度之方法"],"a",
 "第10條之1：本法所稱稀釋，不包括燃煤發電廠採海水排煙脫硫去除硫氧化物之方法。第10條並就廢（污）水（前）處理設施應維持正常操作定有放流水導電度不得低於前一處理設施處理後廢（污）水導電度百分之八十等規定，即在防止以稀釋方式規避管制。",
 "What is excluded from the meaning of dilution under the Act?",
 ["Seawater flue gas desulphurisation used by coal-fired power plants","Using tap water to dilute raw wastewater before discharging it","Blending non-contact cooling water with effluent to cut concentration","Storing water and discharging it together during the rainy season"],
 "Article 10-1; see also Article 10."),

(WR,"第12條",2,"水污細則-查證委辦",
 "各級主管機關依本法第二十六條第一項規定所為查證工作，於特定區域內得如何辦理？",
 ["得委任、委託或委辦機關（構）或法人、團體辦理","應一律由主管機關自行派員辦理不得委由他人","得委由受查證事業所委託之檢驗測定機構辦理","應報請中央主管機關逐案核准後始得指派人員"],"a",
 "第12條：各級主管機關依本法第二十六條第一項規定所為查證工作，於特定區域內得委任、委託或委辦機關（構）或法人、團體辦理。第11條規定為查證處理設施操作功能，應於檢查十四日前通知事業於檢查當日將生產提高至經常最大水污染產生量之狀態；第13條則規定進入軍事機關查證應會同當地憲兵或軍事機關環保人員。",
 "How may verification work under Article 26, Paragraph 1 be carried out in a specific area?",
 ["It may be delegated, commissioned or devolved to agencies, juridical persons or groups","It must always be carried out by the authority own staff and may never be delegated","It may be handled by the testing organisation commissioned by the inspected enterprise","It requires case-by-case approval of the central authority before staff may be assigned"],
 "Article 12; see also Articles 11 and 13."),

(WR,"第13條",2,"水污細則-軍事機關查證",
 "各級主管機關派員進入軍事機關進行查證工作時，應如何辦理？受檢機關義務為何？",
 ["應攜帶證明文件並會同當地憲兵或軍事機關環保人員前往；受檢之軍事機關應提供必要之協助","應先報請國防主管機關核准並由其派員代為查證；受檢之軍事機關得以機密為由拒絕任何檢查","應於七日前以書面通知並由受檢機關自行檢測後函復；受檢之軍事機關僅須提供書面資料即可","應會同當地警察機關及檢察官前往始得進入場所；受檢之軍事機關得要求先行封存全部紀錄"],"a",
 "第13條：各級主管機關依本法第二十六條第二項規定，派員攜帶證明文件，進入軍事機關進行查證工作時，應會同當地憲兵或軍事機關環保人員前往相關場所或設施；為前項檢查或鑑定時，受檢之軍事機關應提供必要之協助。第12條並規定查證工作於特定區域內得委任、委託或委辦辦理。",
 "How is verification carried out at a military establishment, and what must it do?",
 ["Staff carry credentials and are accompanied by local military police or military environmental staff; the unit must assist","Approval of the defence authority is needed and its own staff verify instead; the unit may refuse citing secrecy","Seven days written notice is given and the unit tests itself and replies; only documents need be provided","Local police and a prosecutor must accompany entry; the unit may demand all records be sealed first"],
 "Article 13; see also Article 12."),

(WR,"第13條之1",2,"水污細則-輸送貯存設備",
 "本法第二十八條第一項所稱輸送或貯存設備及疏漏，其範圍為何？",
 ["設備包括廢水收集貯存處理排放之單元桶槽泵浦閥門管線溝渠，及輸送貯存原料產品油品藥劑廢棄物之設備；疏漏包含溢流滲漏或洩漏","設備僅限於廢水處理設施之曝氣槽與沉澱池等主要處理單元本體；疏漏僅指管線破裂造成之大量洩漏而不包括滲漏及溢流","設備包括事業之全部生產機具與動力設備及其附屬管線；疏漏指經主管機關檢測確認污染物濃度超過放流水標準五倍之情形","設備僅指經核准登記之放流口及其採樣設施；疏漏指未依核准登記之放流口排放廢水並意圖逃避主管機關稽查之各種情形"],"a",
 "第13條之1第一項：本法第二十八條第一項所稱輸送或貯存設備，指廢（污）水收集、貯存、處理或排放之單元、桶槽、泵浦、閥門、管線及溝渠，以及輸送或貯存原料、中間產物、產品、副產品、油品、藥劑、廢棄物之設備。第二項：所稱之疏漏，包含溢流、滲漏或洩漏。第13條之2並列舉本法第三十條第一項第二款所稱其他污染物之種類。",
 "What counts as conveyance or storage equipment and as leakage under Article 28, Paragraph 1?",
 ["Equipment covers wastewater units, tanks, pumps, valves, pipes and channels and equipment conveying materials, oils, chemicals and waste; leakage means overflow, seepage or spill","Equipment covers only the aeration and sedimentation tanks of the treatment plant itself; leakage means only major spills from ruptured pipes, not seepage or overflow","Equipment covers all production machinery and power equipment and their pipes; leakage means measured pollutant concentration exceeding five times the effluent standard","Equipment covers only the registered discharge outlet and its sampling devices; leakage means discharging from an unregistered outlet to evade inspection by the authority"],
 "Article 13-1; see also Article 13-2."),

(WR,"第13條之2",2,"水污細則-其他污染物",
 "本法第三十條第一項第二款所稱其他污染物之種類，包括下列何者？",
 ["事業運作所需原物料及製程產出之中間產物產品副產品下腳料廢棄物、油品藥劑農藥化學肥料調味劑清潔劑、淤泥、廚餘動物屍體排泄物","僅限於經中央主管機關公告之有害健康物質及其容器包裝，其他非屬公告之物質均不列入本款所稱其他污染物之範圍內","僅限於事業廢（污）水及污泥等液態與半固態污染物，固體廢棄物與動物屍體等應依廢棄物清理法規定辦理而不適用","僅限於土壤及地下水污染整治法所定之污染物質，以及水污染防治措施及檢測申報管理辦法所列之各項檢測項目"],"a",
 "第13條之2：本法第三十條第一項第二款所稱其他污染物之種類如下：事業運作過程所需原物料及製程產出之中間產物、產品、副產品、下腳料、廢棄物；油品、藥（品）劑、農藥、化學肥料、調味劑、清潔劑；淤泥；廚餘、動物屍體、排泄物；其他經主管機關公告之物質。第13條之1並定義輸送或貯存設備及疏漏之範圍。",
 "What are the other pollutants referred to in Article 30, Paragraph 1, Subparagraph 2?",
 ["Raw materials, intermediates, products, by-products, scrap, waste; oils, chemicals, pesticides, fertilisers, seasonings, detergents; silt; kitchen waste, carcasses, excreta","Only hazardous substances announced by the central authority and their containers and packaging; anything not so announced falls outside this subparagraph entirely","Only liquid and semi-solid pollutants such as wastewater and sludge; solid waste and animal carcasses are handled under the Waste Disposal Act instead","Only the substances defined in the Soil and Groundwater Pollution Remediation Act and the items listed in the water pollution measures and reporting regulations"],
 "Article 13-2; see also Article 13-1."),

(WR,"第14條",1,"水污細則-刪除條文",
 "水污染防治法施行細則第十四條之現行規定狀態為何？",
 ["業經刪除，不再有規範內容","仍規定技師簽證業務事項","仍規定繞流排放之認定原則","仍規定復工查驗及評鑑方式"],"a",
 "第14條：（刪除）。該條已於歷次修正中刪除，現行條文無規範內容。技師簽證應查核事項規定於第7條，繞流排放之認定規定於第8條，復工查驗及評鑑方式則規定於第21條。",
 "What is the current status of Article 14 of these Enforcement Rules?",
 ["It has been deleted and has no content","It still governs engineer certification","It still governs bypass discharge tests","It still governs resumption inspection"],
 "Article 14 is deleted; compare Articles 7, 8 and 21."),

(WR,"第16條",2,"水污細則-注入地下水體",
 "本法第三十六條第二項所稱注入地下水體，其定義為何？何種情形不屬之？",
 ["指以鑿井、注入管線或加壓設施將事業廢（污）水灌注至地下水體；經依土壤及地下水污染整治法同意注入整治所產生之水者不屬之","指任何使廢（污）水滲入地表以下之行為；經農業主管機關核准之畜牧業沼液沼渣作為農地肥分使用計畫者不屬之","指以桶裝或槽車方式將廢（污）水傾倒於地面之行為；廢（污）水排放至設有不透水布等隔離設施者不屬之","指以管線將廢（污）水排入海洋放流管線之行為；因設備破損導致非常態性短時間疏漏排放者不屬之"],"a",
 "第16條第一項：本法第三十六條第二項所稱注入地下水體，指利用鑿井、注入管線或加壓設施等設備，將事業廢（污）水灌注至地下水體者。第二項：事業或污水下水道系統經直轄市、縣（市）主管機關依土壤及地下水污染整治法規定審查同意，將土壤、地下水污染整治所產生之水注入地下水體之行為，非屬本法第三十二條第一項及第三十六條第二項所稱之注入地下水體。第17條則界定排放於土壤之定義及除外情形。",
 "What is injection into groundwater under Article 36, Paragraph 2, and what is excluded?",
 ["Injecting wastewater into groundwater via wells, lines or pressure devices; water from approved remediation work is excluded","Any act allowing wastewater to seep below ground; approved use of livestock biogas slurry as farmland fertiliser is excluded","Dumping wastewater on the ground by drum or tanker; discharge onto impermeable liner isolation facilities is excluded","Piping wastewater into an ocean outfall line; short non-routine leakage caused by broken equipment is excluded"],
 "Article 16; see also Article 17."),

(WR,"第17條",3,"水污細則-排放於土壤",
 "本法第三十六條第一項所稱排放於土壤，其定義及除外情形為何？",
 ["指以管線溝渠或桶裝槽車等方式將事業廢（污）水排入逸散流布於土壤；經核准之農業廢棄物再利用、沼液沼渣肥分使用計畫、土壤處理許可等不在此限","指以管線溝渠或桶裝槽車等方式將事業廢（污）水排入逸散流布於土壤；任何情形均無例外規定，均應以違反本法第三十六條第一項論處","指利用鑿井或加壓設施將事業廢（污）水灌注至地下水體之行為；經農業主管機關核准之農地灌溉用水回收再利用計畫者不在此限","指事業將廢（污）水排放至地面水體致嚴重影響水質之行為；廢（污）水處理設施發生故障並已依規定通報主管機關者不在此限"],"a",
 "第17條：本法第三十六條第一項所稱排放於土壤，指以管線、溝渠或桶裝、槽車等其他非管線方式，將事業廢（污）水排入、逸散、流布於土壤者；但不包含經農業主管機關依農業事業廢棄物再利用管理辦法核准之再利用運作管理、經核准之畜牧業沼液沼渣作為農地肥分使用計畫、經直轄市縣（市）主管機關核准之土壤處理許可、排放至設有不透水布等隔離設施之非直接接觸土壤，及因管線設備破損或故障導致非常態性短時間疏漏排放至土壤等情形。",
 "How is discharge onto soil defined in Article 36, Paragraph 1, and what is excluded?",
 ["Releasing wastewater onto soil by pipes, channels, drums or tankers; approved waste reuse, biogas slurry fertiliser plans and soil treatment permits are excluded","Releasing wastewater onto soil by pipes, channels, drums or tankers; there is no exception at all, and every such case is treated as a violation","Injecting wastewater into groundwater by wells or pressure devices; approved irrigation water recycling plans of the agricultural authority are excluded","Discharging wastewater into surface water so as to seriously affect quality; breakdowns already notified to the authority as required are excluded"],
 "Article 17; see also Article 16."),

(WR,"第18條",3,"水污細則-排放於地面水體",
 "本法第三十六條第一項所稱排放於地面水體，指下列何種情形？",
 ["大量排放污染物經認定嚴重影響附近水質、處理設施未具足夠功能與設備、設施故障未依規定通報、未遵行停工停業命令而繼續排放","僅指事業未依核准登記之放流口排放廢（污）水，或以共同排放管線之採樣口排放廢（污）水之各種繞流排放情形","僅指排放廢（污）水中污染物濃度為放流水標準限值五倍以上，或氫離子濃度指數小於二或大於十一之情形","僅指事業將含有有害健康物質之廢（污）水利用鑿井或注入管線灌注至地下水體並經主管機關查獲之情形"],"a",
 "第18條：本法第三十六條第一項所稱排放於地面水體，指下列情形之一：大量排放污染物經主管機關認定嚴重影響附近水體水質；廢（污）水（前）處理設施未在最大產能或服務規模下使處理後廢水符合規定、未能處理可預見異常作業之水量負荷；事業廢（污）水處理設施發生故障未依本法第五十九條規定通報主管機關；事業未遵行主管機關命停止作為、停止貯存、停工、停業或歇業而繼續排放廢（污）水者。第8條所定繞流排放則屬本法第十八條之一之範疇。",
 "What counts as discharge into surface water under Article 36, Paragraph 1?",
 ["Massive discharge seriously affecting nearby water, facilities lacking function, breakdowns not notified, and discharging despite a shutdown order","Only discharging wastewater from an outlet that is not registered, or discharging from the sampling port of a shared discharge pipeline","Only discharging wastewater whose pollutant concentration is five times the effluent standard, or with a pH below two or above eleven","Only injecting wastewater containing substances hazardous to health into groundwater through wells or injection lines and being caught"],
 "Article 18; compare Article 8."),

(WR,"第19條",3,"水污細則-管制標準範圍",
 "本法第三十六條第一項所稱本法所定各該管制標準，就排放於地面水體者其範圍為何？",
 ["指事業之放流水標準、海洋放流管線放流水標準及特定業別適用之放流水標準；不包含保護區或總量管制區增訂或加嚴之標準","指事業之放流水標準及保護區、飲用水水源水質保護區、總量管制區所增訂或加嚴之放流水標準；不包含特定業別標準","指地面水體分類及水質標準所定各類水體之水質項目限值；不包含事業放流水標準及海洋放流管線放流水標準","指事業水污染防治措施計畫或許可證所登記之操作參數及自訂管制值；不包含中央主管機關公告之各項標準"],"a",
 "第19條：本法第三十六條第一項所稱本法所定各該管制標準，針對排放於地面水體管制標準，指事業之放流水標準、海洋放流管線放流水標準及特定業別適用之放流水標準；不包含針對自來水水質水量保護區、飲用水水源水質保護區、總量管制區等環境特殊或需特予保護區域之水體增訂或加嚴之放流水標準。第15條並規定故意排放有害健康物質超出各該管制標準而有犯罪嫌疑者應向檢察官告發。",
 "For discharge into surface water, which standards are the control standards in Article 36, Paragraph 1?",
 ["Effluent standards for the enterprise, for ocean outfall pipelines and for specific sectors; not stricter standards added for protected areas","Effluent standards for the enterprise plus stricter standards for water source and total quantity control areas; not sector standards","The water quality limits for each water body class under the classification and quality standards; not effluent standards","Operating parameters and self-set limits registered in the control plan or permit; not standards announced by the central authority"],
 "Article 19; see also Article 15."),

(WR,"第20條",1,"水污細則-通知書",
 "各級主管機關依本法所為限期改善、補正之通知書，應如何作成？",
 ["應與裁處書分別作成","應與裁處書合併作成","應由中央主管機關統一核發","應由受處分人自行具結作成"],"a",
 "第20條：各級主管機關依本法所為限期改善、補正之通知書，應與裁處書分別作成。第21條並規定主管機關執行本法第六十三條規定之復工查驗及評鑑應依所定方式辦理，第22條則界定本法第七十三條第一項第三款所稱一年內之計算方式。",
 "How must improvement or correction notices under the Act be made?",
 ["Made separately from the penalty decision","Made together with the penalty decision","Issued uniformly by the central authority","Made by the offender own written pledge"],
 "Article 20; see also Articles 21 and 22."),

(WR,"第21條",3,"水污細則-復工查驗",
 "主管機關執行本法第六十三條規定之復工查驗及評鑑，應依何方式辦理？",
 ["以事業復工時申報之實際經常最大廢（污）水產生量測試防治措施及污泥處理設施功能，並評估定期申報與主管機關檢驗之水質水量資料","以事業申請復工時之設計處理容量測試防治措施功能，並僅比對事業自行檢測之水質資料而不採計主管機關之檢驗結果","以事業停工前最近一年之平均廢（污）水產生量測試設施，並由事業委託之檢驗測定機構出具報告後即准予復工","以主管機關現場目視判斷處理設施外觀是否完整為準，並就事業提出之改善完成報告書進行書面審查後決定"],"a",
 "第21條：主管機關執行本法第六十三條規定之復工查驗及評鑑，應以事業復工時所申報之實際經常最大廢（污）水產生量測試其水污染防治措施或污泥處理設施；以事業實際經常最大廢（污）水產生量測試其水污染防治措施及污泥處理設施之功能；評估事業定期申報之水質水量資料與主管機關檢驗之水質水量資料及其日平均限值、週平均限值或月平均限值，並比較現有設施功能；及其他經主管機關認定之方式。",
 "How is resumption inspection and appraisal under Article 63 carried out?",
 ["Test the control and sludge facilities at the declared actual maximum wastewater volume, and compare declared and official water quality data","Test the facilities at the design treatment capacity and rely only on the enterprise own testing data, disregarding official results","Test the facilities at the average wastewater volume of the year before shutdown and accept the commissioned testing report as sufficient","Judge visually whether the facilities look intact and decide on a documentary review of the improvement completion report"],
 "Article 21."),

(WR,"第22條",2,"水污細則-一年內計算",
 "本法第七十三條第一項第三款所稱一年內，其計算方式為何？",
 ["指自違反之日起，往前回溯至第三百六十五日止","指自違反之日起，往後推算至第三百六十五日止","指自查獲之日起，往前回溯至第一百八十日止","指自裁處確定之日起，往前回溯至第七百三十日止"],"a",
 "第22條：本法第七十三條第一項第三款所稱一年內，指自違反之日起，往前回溯至第三百六十五日止。廢（污）水處理專責單位或人員設置及管理辦法第25條第二項亦採相同計算方式，指自違規之日起往前回溯至第三百六十五日止。",
 "How is within one year in Article 73, Paragraph 1, Subparagraph 3 counted?",
 ["Counted back from the day of violation to the 365th day before it","Counted forward from the day of violation to the 365th day after","Counted back from the day of detection to the 180th day before it","Counted back from the day the penalty is final to the 730th day"],
 "Article 22."),

(WR,"第23條",2,"水污細則-部分罰鍰",
 "本法第六十六條之三第一項所稱之依本法裁處之部分罰鍰，指何數額？",
 ["指經主管機關依本法裁處後實收罰鍰金額之百分之二十","指經主管機關依本法裁處後實收罰鍰金額之百分之五十","指經主管機關依本法裁處之罰鍰法定最高額之百分之十","指經主管機關依本法裁處後實收罰鍰金額之百分之八十"],"a",
 "第23條：本法第六十六條之三第一項所稱之依本法裁處之部分罰鍰，指經主管機關依本法裁處後實收罰鍰金額之百分之二十。第20條並規定限期改善、補正之通知書應與裁處書分別作成；第22條界定一年內之回溯計算方式。",
 "What is the portion of fines referred to in Article 66-3, Paragraph 1?",
 ["Twenty percent of the fine actually collected after the authority imposes it","Fifty percent of the fine actually collected after the authority imposes it","Ten percent of the statutory maximum fine that the authority may impose","Eighty percent of the fine actually collected after the authority imposes it"],
 "Article 23; see also Articles 20 and 22."),

(WR,"第24條",1,"水污細則-施行",
 "水污染防治法施行細則之施行日期規定為何？",
 ["本細則自發布日施行","本細則自發布後一年施行","本細則自公布後六個月施行","本細則自中央主管機關指定日施行"],"a",
 "第24條：本細則自發布日施行。第1條並規定本細則依水污染防治法第七十四條規定訂定之。廢（污）水處理專責單位或人員設置及管理辦法第28條亦規定自發布日施行。",
 "When do these Enforcement Rules take effect?",
 ["From the date of promulgation","One year after promulgation","Six months after promulgation","On a date designated centrally"],
 "Article 24."),

# ---------- 廢（污）水處理專責單位或人員設置及管理辦法（ENV-46） ----------
(WP,"第1條",1,"廢水專責-法源",
 "廢（污）水處理專責單位或人員設置及管理辦法係依何規定訂定？",
 ["依水污染防治法第二十一條第二項規定訂定","依水污染防治法第七十四條規定訂定","依水污染防治法第十八條之一第四項規定訂定","依水污染防治法第四十八條第三項規定訂定"],"a",
 "第1條：本辦法依水污染防治法（以下簡稱本法）第二十一條第二項規定訂定之。水污法第七十四條則為水污染防治法施行細則之授權依據。第2條並規定廢（污）水處理專責人員分為甲級及乙級，應由經中央主管機關訓練合格並取得合格證書者擔任。",
 "The Regulations for dedicated wastewater treatment units or personnel are enacted under:",
 ["Article 21, Paragraph 2 of the Water Pollution Control Act","Article 74 of the Water Pollution Control Act as amended","Article 18-1, Paragraph 4 of the Water Pollution Control Act","Article 48, Paragraph 3 of the Water Pollution Control Act"],
 "Article 1; Article 74 authorizes the Enforcement Rules."),

(WP,"第2條",1,"廢水專責-分級資格",
 "廢（污）水處理專責人員之分級及擔任資格為何？",
 ["分為甲級及乙級，應由經中央主管機關訓練合格並取得合格證書者擔任","分為甲級、乙級及丙級，應由具備技師證書並經地方主管機關登記者擔任","分為第一級及第二級，應由事業自行遴選並報請目的事業主管機關核備","分為正級及副級，應由具備三年以上實務經驗且經公會推薦之人員擔任"],"a",
 "第2條：本辦法所稱廢（污）水處理專責人員分為甲級及乙級；本法第二十一條第一項規定事業或污水下水道系統應設置之廢（污）水處理專責人員，應由經中央主管機關訓練合格並取得合格證書者擔任。第4條並規定應設置專責單位者，員額至少應有專責人員三人，包括二名以上甲級人員並由其中一名甲級人員擔任專責單位主管。",
 "How are dedicated wastewater treatment personnel graded and who may serve?",
 ["Class A and Class B; the post is held by those trained and certified by the central competent authority","Class A, B and C; the post is held by licensed engineers registered with the local competent authority","Level 1 and Level 2; the enterprise selects them and files the selection with the industry authority","Principal and deputy grades; held by those with three years experience recommended by a trade body"],
 "Article 2; see also Article 4."),

(WP,"第3條",2,"廢水專責-設置條件",
 "事業或污水下水道系統應依何條件設置廢（污）水處理專責單位或專責人員？何種下水道免設？",
 ["依附表一許可核准廢（污）水產生量規模、附表二物質超過放流水標準或違規情事設置；新開發社區專用下水道五百戶以下者免設","依事業員工人數及資本額規模設置；新開發社區專用下水道服務戶數一千戶以下者免設置廢（污）水處理專責人員","依事業所在噪音管制區及空氣品質區類別設置；工業區專用污水下水道系統服務廠家未達十家者免設置專責人員","依主管機關逐案指定之污染潛勢等級設置；公共污水下水道系統處理量每日未達一萬立方公尺者免設置專責人員"],"a",
 "第3條第一項：事業或污水下水道系統應依附表一所列許可核准廢（污）水產生量規模，或原廢（污）水未經處理前所含附表二物質超過放流水標準，或違規情事之條件，設置廢（污）水處理專責單位或專責人員。第二項：依下水道法設置之新開發社區專用下水道，其服務戶數在五百戶以下者，免設置廢（污）水處理專責人員。第14條並規定附表調整致需提升級別或增加員額者，應於一年內完成核定設置。",
 "On what conditions must dedicated wastewater staffing be set up, and which sewer is exempt?",
 ["By permitted wastewater volume in Appendix 1, Appendix 2 substances above effluent standards, or violations; new community sewers serving 500 households are exempt","By the number of employees and the capital of the enterprise; new community sewers serving 1,000 households or fewer are exempt from dedicated personnel","By the noise control zone and air quality area of the site; industrial park sewers serving fewer than ten factories are exempt from dedicated personnel","By a pollution potential grade designated case by case; public sewers treating under 10,000 cubic metres a day are exempt from dedicated personnel"],
 "Article 3; see also Article 14."),

(WP,"第5條",2,"廢水專責-合併設置",
 "事業或污水下水道系統設置之廢（污）水處理專責單位，於同一處所內得如何合併設置？人員可否互兼？",
 ["得與其依法設置之空氣污染防制專責單位合併設置；人員具備空污專責人員資格且設置級別均符合規定者得互兼","得與其依法設置之廢棄物清理專責單位合併設置；人員不論是否具備該類資格及級別均得無條件互相兼任職務","不得與任何其他類專責單位合併設置；人員亦不得兼任其他類環境保護專責及技術人員以確保業務之專責性","得與同一集團其他廠區之專責單位合併設置；人員得跨廠區同時設置於不同事業並分別執行各該場所業務"],"a",
 "第5條：事業或污水下水道系統依第3條第一項規定設置廢（污）水處理專責單位，在同一處所內，得與其依法設置之空氣污染防制專責單位合併設置；且廢（污）水處理專責人員如具備空氣污染防制專責人員之資格，且設置級別均符合法規規定，其人員得互兼之。第6條另規定具備其他類環境保護專責及技術人員資格者，於同一處所內得同時兼任。第17條第二款則禁止同一時間設置於不同事業。",
 "How may the dedicated wastewater unit be merged in the same premises, and may staff cross-serve?",
 ["It may merge with the lawful air pollution control unit; staff qualified as air control personnel of matching grade may cross-serve","It may merge with the lawful waste disposal unit; staff may cross-serve unconditionally whether or not they hold that qualification","It may not merge with any other dedicated unit; staff may not serve as other environmental dedicated or technical personnel","It may merge with units at other plants of the same group; staff may be appointed at different enterprises at the same time"],
 "Article 5; see also Articles 6 and 17."),

(WP,"第6條",2,"廢水專責-兼任他類",
 "廢（污）水處理專責人員得否同時兼任其他類環境保護專責及技術人員？其要件為何？",
 ["得同時兼任，惟須具備其他類環境保護專責及技術人員之資格，且設置級別均符合法規規定，並在同一處所內","得同時兼任，且不以具備其他類專責及技術人員資格為必要，亦不受設置處所是否相同之任何限制","不得同時兼任，廢（污）水處理專責人員僅得專責辦理廢（污）水處理業務而不得兼任任何其他職務","得同時兼任，惟須經中央主管機關逐案核准並公告，且以同一直轄市、縣（市）轄區內之場所為限"],"a",
 "第6條：事業或污水下水道系統依第3條第一項附表一規定設置之廢（污）水處理專責人員，如具備其他類環境保護專責及技術人員之資格，且設置級別均符合法規規定，在同一處所內，得同時兼任其他類環境保護專責及技術人員。第15條第二項並規定應專職者不得兼任環保法規以外其他法規所定專責（任）人員或從事與污染防治無關之工作。",
 "May dedicated wastewater personnel concurrently serve as other environmental personnel?",
 ["Yes, provided they hold the other qualification, the required grades all match, and the posts are in the same premises","Yes, and no other qualification is needed, nor is there any restriction on whether the premises are the same","No, dedicated wastewater personnel may only handle wastewater treatment work and may hold no other post","Yes, but only with case-by-case central approval and publication, and only within the same municipality or county"],
 "Article 6; see also Article 15, Paragraph 2."),

(WP,"第7條",3,"廢水專責-負責人兼任",
 "事業或污水下水道系統員工人數在多少人以下者，負責人得兼任廢（污）水處理專責人員？本辦法施行前已兼任但超過該人數者應如何處理？",
 ["員工人數五十人以下者；應於本辦法施行後六個月內依規定向直轄市、縣（市）主管機關重新申請核定設置","員工人數一百人以下者；應於本辦法施行後三個月內依規定向中央主管機關重新申請核定設置專責人員","員工人數三十人以下者；應於本辦法施行後一年內依規定向目的事業主管機關重新申請核定設置人員","員工人數二百人以下者；得繼續由負責人兼任而毋須重新申請核定設置亦不受本辦法施行之影響"],"a",
 "第7條：事業或污水下水道系統員工人數五十人以下者，負責人得兼任廢（污）水處理專責人員；所稱負責人指水污染防治措施計畫或水污染防治許可證（文件）所登記之負責人或經負責人授權之人。本辦法施行前員工人數超過五十人且負責人已兼任者，應於本辦法施行後六個月內重新申請核定設置。第9條並規定負責人兼任者應至少設置二名代理人。",
 "Below what headcount may the responsible person double as dedicated personnel, and what if the headcount already exceeded it?",
 ["Fifty employees or fewer; re-apply to the municipal or county authority within six months after these Regulations take effect","One hundred employees or fewer; re-apply to the central competent authority within three months after they take effect","Thirty employees or fewer; re-apply to the industry competent authority within one year after they take effect","Two hundred employees or fewer; the arrangement continues with no re-application and is unaffected by the Regulations"],
 "Article 7; see also Article 9."),

(WP,"第8條",3,"廢水專責-共同設置",
 "二以上事業共同設置廢（污）水處理設施共同處理廢（污）水者，其專責單位或人員之級別及員額如何認定？",
 ["經直轄市、縣（市）主管機關核准者得共同設置，依合併計算之產生量、任一事業原廢水超標情形或停工停業復工情形認定，不一致時以最高者認定","經中央主管機關核准者得共同設置，一律依產生量最小之事業所適用之級別及員額認定，不因其他事業之違規情形而受影響","報請目的事業主管機關備查後即得共同設置，由參與事業自行協議級別及員額，主管機關不得就其認定結果予以變更","經直轄市、縣（市）主管機關核准者得共同設置，依參與事業原定級別之平均值認定，不一致時以級別最低者為準"],"a",
 "第8條第一項：二以上事業共同設置廢（污）水處理設施共同處理廢（污）水，經直轄市、縣（市）主管機關核准者，得共同設置專責單位或人員，其級別及員額依下列之一認定：廢（污）水產生量以共同設置事業許可核准量合併計算後依附表一認定；各該事業之一之原廢（污）水未經處理前所含附表二物質超過放流水標準情形；各該事業之一有違反本法經認定情節重大處以停工或停業者於申請復工（業）時。第二項：認定不一致時，以設置級別最高者認定之。",
 "For jointly built wastewater facilities, how are the grade and staffing of the dedicated unit determined?",
 ["With municipal or county approval, by combined permitted volume, any member exceeding standards, or resumption after shutdown; the highest wins","With central approval, always by the grade and staffing of the member with the smallest volume, unaffected by other members violations","On filing with the industry authority, the members agree the grade and staffing themselves and the authority may not alter the result","With municipal or county approval, by the average of the members original grades, and where they differ the lowest grade prevails"],
 "Article 8."),

(WP,"第10條",2,"廢水專責-申請核定",
 "事業或污水下水道系統申請核定設置廢（污）水處理專責單位或人員時，應檢具何文件？申請方式為何？",
 ["應檢具設置申請書、專責人員合格證書、勞健保查詢同意書及代理人訓練資格學經歷證明，向直轄市、縣（市）主管機關申請","應檢具水污染防治措施計畫、放流水檢測報告及污泥處理紀錄，向中央主管機關申請並經公告後始生效力","應檢具工廠登記證明、公司章程及員工名冊，向目的事業主管機關報備，經其轉知環保主管機關後即完成","應檢具在職訓練證明、技師簽證文件及設施設計圖說，向鄉（鎮、市、區）公所辦理登記並繳納規費"],"a",
 "第10條第一項：應檢具設置申請書並附上廢（污）水處理專責人員之合格證書及其同意查詢勞健保資料同意書，與代理人具參加同一級別以上專責人員訓練資格之學（經）歷證明及其同意查詢勞健保資料同意書，向直轄市、縣（市）主管機關申請核定設置。第二項：除經該機關同意得以書面方式申請者外，自中央主管機關指定之日起，應採網路傳輸方式辦理。",
 "What documents must be filed to obtain approval of dedicated wastewater staffing, and to whom?",
 ["The application form, the certificate, insurance data consent forms and the deputy training qualification records, to the municipal or county authority","The water pollution control plan, effluent test reports and sludge records, to the central authority, effective only after publication","Factory registration, articles of incorporation and a staff roster, filed with the industry authority which then informs the environmental authority","On-the-job training records, engineer certification documents and facility drawings, registered at the township office with a fee"],
 "Article 10; online filing applies from the designated date."),

(WP,"第11條",2,"廢水專責-代操作營運",
 "事業或污水下水道系統得否以委任之代操作營運機構派任人員擔任廢（污）水處理專責人員或代理人？管理責任歸屬為何？",
 ["得由代操作營運機構派任具資格人員申請核定設置，惟事業或污水下水道系統仍應負本辦法所定管理之責","得由代操作營運機構派任具資格人員申請核定設置，本辦法所定管理責任即隨之全部移轉由該機構承擔","不得由代操作營運機構派任，專責人員應由事業或污水下水道系統正式僱用之員工擔任並由其負全責","得由代操作營運機構自行指派人員而免經主管機關核定，事業與該機構就管理責任按契約約定自行分配"],"a",
 "第11條：事業或污水下水道系統得以其委任之代操作營運機構派任具資格之人員，依第10條規定向直轄市、縣（市）主管機關申請核定設置為該事業或污水下水道系統之廢（污）水處理專責人員或代理人；除派任外，事業或污水下水道系統仍應負本辦法所定管理之責。第18條並課予監督常駐、專職及執行第22條業務之義務。",
 "May a contracted operating firm supply the dedicated person or deputy, and who bears management duty?",
 ["Yes, it may assign qualified staff for approval, but the enterprise or sewerage system still bears the management duty","Yes, it may assign qualified staff for approval, and all management duty under these Regulations transfers to that firm","No, the dedicated person must be a formally hired employee of the enterprise, which bears the full responsibility","Yes, the firm may assign staff without approval, and duty is divided between them as their contract provides"],
 "Article 11; see also Article 18."),

(WP,"第12條",3,"廢水專責-到職訓練",
 "廢（污）水處理專責人員取得合格證書後連續多久未經核准設置者應完成到職訓練？期限及報備規定為何？",
 ["連續三年以上；應於到職之翌日起六個月內完成到職訓練；設置屆滿六個月後十五日內檢具證明向主管機關報備","連續一年以上；應於到職之翌日起三個月內完成到職訓練；設置屆滿三個月後三十日內檢具證明向主管機關報備","連續五年以上；應於到職之翌日起一年內完成到職訓練；設置屆滿一年後六十日內檢具證明向主管機關報備","連續二年以上；應於到職之翌日起三十日內完成到職訓練；設置屆滿一年後七日內檢具證明向主管機關報備"],"a",
 "第12條第一項、第二項：專責人員於取得合格證書後連續三年以上未經核准設置者，應於到職之翌日起六個月內依環境保護專責及技術人員訓練管理辦法規定完成到職訓練；設置屆滿六個月後十五日內，事業或污水下水道系統應檢具完成到職訓練之證明文件向直轄市、縣（市）主管機關報備。第三項規定未完成者應廢止核定設置並於十五日內重新申請；第四項並禁止再聘僱取得證書後連續三年以上未經核准設置者。",
 "After holding a certificate without appointment for how long is on-boarding training required, and by when must it be filed?",
 ["Three years or more; complete within six months from the day after taking office; file the certificate within fifteen days after six months","One year or more; complete within three months from the day after taking office; file the certificate within thirty days after three months","Five years or more; complete within one year from the day after taking office; file the certificate within sixty days after one year","Two years or more; complete within thirty days from the day after taking office; file the certificate within seven days after one year"],
 "Article 12, Paragraphs 1 and 2."),

(WP,"第13條",1,"廢水專責-刪除條文",
 "廢（污）水處理專責單位或人員設置及管理辦法第十三條之現行規定狀態為何？",
 ["業經刪除，不再有規範內容","仍規定到職訓練之期限","仍規定代理人之設置員額","仍規定專責人員應執行業務"],"a",
 "第13條：（刪除）。該條已刪除，現行條文無規範內容。到職訓練規定於第12條，代理人設置規定於第9條，專責人員應執行之業務則規定於第22條，包括協助釐定廢（污）水收集處理改善、許可申請及檢測申報、操作管理、管線及放流口管理與水質檢測管理等事項。",
 "What is the current status of Article 13 of these Regulations?",
 ["It has been deleted and has no content","It still governs on-boarding training","It still governs the number of deputies","It still governs the duties of personnel"],
 "Article 13 is deleted; compare Articles 9, 12 and 22."),

(WP,"第14條",2,"廢水專責-附表調整",
 "中央主管機關調整或變更附表一或附表二，致事業需提升專責人員設置級別或增加員額時，應於何期限內完成核定設置？",
 ["應於調整或變更後一年內向直轄市、縣（市）主管機關完成核定設置","應於調整或變更後三個月內向中央主管機關完成核定設置專責人員","應於調整或變更後六個月內向目的事業主管機關完成報備設置作業","應於調整或變更後三十日內向直轄市、縣（市）主管機關報備即可"],"a",
 "第14條：中央主管機關有調整或變更第3條第一項所列附表一或附表二之情形，致事業或污水下水道系統需提升廢（污）水處理專責人員設置級別或增加設置員額時，應於調整或變更後一年內向直轄市、縣（市）主管機關完成核定設置廢（污）水處理專責單位或人員。第24條第六款並規定未依第14條於一年內申請核定設置者，依本法第四十八條第三項處罰。",
 "When must staffing be upgraded after the central authority revises Appendix 1 or 2?",
 ["Within one year of the revision, completed with the municipal or county authority","Within three months of the revision, completed with the central competent authority","Within six months of the revision, filed with the industry competent authority","Within thirty days of the revision, merely filed with the municipal authority"],
 "Article 14; penalties under Article 24, Subparagraph 6."),

(WP,"第16條",3,"廢水專責-常駐紀錄",
 "廢（污）水處理專責人員因故未能常駐在場者應如何處理？何種情形不得繼續設置？",
 ["應備有請假紀錄或其他相關證明文件備查；半年內累積超過三十日未到職或一年內三次以上未符合規定者不得繼續設置","應於當日以電話向主管機關報告事由；半年內累積超過六十日未到職或一年內五次以上未符合規定者不得繼續設置","應立即停止廢（污）水處理設施操作；一年內累積超過三十日未到職或二年內三次以上未符合規定者不得繼續設置","應由事業負責人親自代理並免備文件；半年內累積超過九十日未到職或一年內二次以上未符合規定者不得繼續設置"],"a",
 "第16條：依本辦法設置之專責人員因故未能常駐在場者，應備有請假紀錄或其他相關證明文件以備查閱；專責人員於勞動基準法所定休息、休假規定之日數外，半年內累積超過三十日未到職，或經主管機關查獲一年內三次以上未符合前項規定者，不得再繼續設置為該事業或污水下水道系統之專責人員，事業並應於事實發生後三十日內重新申請核定設置。第24條第九款對未備請假紀錄簿或未保存三年者定有處罰。",
 "If the dedicated person cannot stay on site, what is required and when may the post no longer continue?",
 ["Keep leave records or documents for inspection; absence over thirty days in half a year or three failures in a year ends the post","Report by telephone the same day; absence over sixty days in half a year or five failures in a year ends the post","Stop operating the treatment facilities at once; absence over thirty days in a year or three failures in two years ends it","Have the responsible person deputise with no documents; absence over ninety days in half a year or two failures ends it"],
 "Article 16; see also Article 24."),

(WP,"第17條",2,"廢水專責-禁止行為",
 "依本辦法設置之廢（污）水處理專責人員或代理人，不得有下列何種行為？",
 ["明知或預見而不違背本意違反本法第十八條之一規定、同一時間設置於不同事業、使他人利用其名義虛偽設置、申報不實","於同一處所內兼任具備資格且級別相符之空氣污染防制專責人員、或兼任其他類環境保護專責及技術人員之職務","依事業委任之代操作營運機構派任而擔任該事業之專責人員、或於員工五十人以下事業由負責人兼任專責人員","於勞動基準法所定休息、休假日數內未到職、或依法共同設置而同時設置於二以上共同處理廢水之事業場所"],"a",
 "第17條：依本辦法設置之專責人員或代理人不得有下列行為：明知並有意或預見其發生而其發生並不違背其本意之情形下違反本法第十八條之一第一項或第二項規定；同一時間設置於不同之事業或污水下水道系統（依法共同設置者除外）；使他人利用其名義虛偽設置；明知為不實之事項而申報不實或於業務上作成之文書為虛偽記載。第25條並就違反各該款者依本法第四十八條第四項處罰。",
 "Which conduct is prohibited for dedicated wastewater personnel or deputies?",
 ["Intentionally breaching Article 18-1, being appointed at different enterprises at once, lending their name, and filing false reports","Concurrently serving as qualified air pollution control personnel of matching grade in the same premises, or as other environmental staff","Serving as dedicated personnel through a contracted operating firm, or the responsible person doubling in a firm of fifty or fewer staff","Being absent within the statutory rest and holiday days, or being appointed at two enterprises lawfully sharing treatment facilities"],
 "Article 17; penalties under Article 25."),

(WP,"第18條",3,"廢水專責-監督義務",
 "事業或污水下水道系統應令其設置之專責人員或代理人符合之規定為何？",
 ["監督常駐並專職負責第二十二條所定業務、備有請假紀錄簿並至少保存三年、監督執行業務且不得有第十七條所定行為","監督每月到場一次即可並得自由兼職、備有出勤紀錄並保存一年、僅須確認業務有人執行而無須監督其行為態樣","監督由代操作營運機構自行管理其派任人員、備有訓練紀錄並保存五年、由該機構承擔全部監督責任與法律效果","監督常駐並得兼任其他法規所定專責人員、備有請假紀錄並保存六個月、免除監督其執行第二十二條業務之責任"],"a",
 "第18條：事業或污水下水道系統應令所設置之專責人員或代理人符合下列規定：依第15條監督其於勞動基準法所定工作時間內常駐，並專職負責第22條所定業務；依第16條備有請假紀錄簿（單）供其未能常駐在場時填寫，該紀錄簿（單）應至少保存三年；監督其執行第22條所定業務，且不得有第17條所定之行為。第24條第八款至第十款對違反各該款者定有處罰。",
 "What must the enterprise ensure of its dedicated personnel or deputies?",
 ["Supervise full-time stationing and Article 22 duties, keep leave record books for at least three years, and supervise conduct under Article 17","Supervise a monthly site visit with free concurrent posts, keep attendance logs for one year, and merely confirm someone performs the duties","Let the contracted operating firm manage its own assigned staff, keep training records five years, and shift all supervision to that firm","Supervise stationing while allowing other statutory posts, keep leave records six months, and be relieved of supervising Article 22 duties"],
 "Article 18; penalties under Article 24."),

(WP,"第19條",3,"廢水專責-離職異動",
 "廢（污）水處理專責人員離職、異動時，事業應於幾日內報備？代理期間上限為何？專責人員本人應於幾日內報備？",
 ["事業應於事實發生後十五日內書面報備；代理期間不得超過三個月；專責人員應於離職或異動日起三十日內書面報備","事業應於事實發生後三十日內書面報備；代理期間不得超過六個月；專責人員應於離職或異動日起十五日內書面報備","事業應於事實發生後七日內書面報備；代理期間不得超過一個月；專責人員應於離職或異動日起六十日內書面報備","事業應於事實發生後六十日內書面報備；代理期間不得超過一年；專責人員應於離職或異動日起七日內書面報備"],"a",
 "第19條：專責人員離職、異動時，事業或污水下水道系統應由設置之代理人代理，並於事實發生後十五日內以書面報請直轄市、縣（市）主管機關備查；代理期間不得超過三個月，期滿前十五日內應完成同一級別以上合格專責人員之核定設置；專責人員應於離職或異動日起三十日內以書面報備。所稱異動，指調離原廠址或仍於原廠址惟未擔任專責人員職務。",
 "On departure or transfer, within how long must the enterprise report, how long may a deputy act, and when must the person report?",
 ["The enterprise reports in writing within fifteen days; deputising may not exceed three months; the person reports within thirty days","The enterprise reports in writing within thirty days; deputising may not exceed six months; the person reports within fifteen days","The enterprise reports in writing within seven days; deputising may not exceed one month; the person reports within sixty days","The enterprise reports in writing within sixty days; deputising may not exceed one year; the person reports within seven days"],
 "Article 19."),

(WP,"第20條",3,"廢水專責-非離職代理",
 "專責人員非因離職、異動而因故未能執行業務時，代理期間連續達多久應報備？代理期間上限及延長規定為何？",
 ["連續達十五日以上者應於事實發生後十五日內書面報備；代理不得超過三個月，報經主管機關核准者可延長至六個月","連續達七日以上者應於事實發生後三日內書面報備；代理不得超過一個月，報經主管機關核准者可延長至三個月","連續達三十日以上者應於事實發生後三十日內書面報備；代理不得超過六個月，且不得再報請主管機關核准延長","連續達六十日以上者應於事實發生後十日內書面報備；代理不得超過一年，報經主管機關核准者可延長至二年"],"a",
 "第20條：專責人員非因離職、異動而因故未能執行業務時，事業或污水下水道系統應由設置之代理人代理；代理期間連續達十五日以上者，應於事實發生後十五日內以書面報請直轄市、縣（市）主管機關備查。代理期間不得超過三個月，但報經該主管機關核准者可延長至六個月；代理期滿前十五日內應完成同一級別以上之合格專責人員核定設置。",
 "For absence other than departure, when must deputising be reported, and what are the limit and extension?",
 ["Fifteen consecutive days or more, reported within fifteen days; three months, extendable to six months with approval","Seven consecutive days or more, reported within three days; one month, extendable to three months with approval","Thirty consecutive days or more, reported within thirty days; six months, with no further extension permitted","Sixty consecutive days or more, reported within ten days; one year, extendable to two years with approval"],
 "Article 20; compare Article 19."),

(WP,"第21條",3,"廢水專責-過渡代理",
 "本辦法施行前已核定設置專責單位或人員者，應於何期限內完成代理人設置？期限內未完成而發生代理事由時應如何處理？",
 ["施行日起六個月內完成；應即指定具訓練資格或熟悉廢水處理操作管理之人員代理，十五日內報備並三十日內完成設置","施行日起三個月內完成；應即停止廢（污）水處理設施之操作並停工，於七日內函報中央主管機關核備後始得復工","施行日起一年內完成；得暫免指定任何人員代理，俟主管機關通知後再依規定補辦代理人之核定設置相關程序","施行日起三十日內完成；應由直轄市、縣（市）主管機關逕行指派轄內合格人員代理並向該事業收取代理費用"],"a",
 "第21條：本辦法施行前已核定設置專責單位或人員者，應於本辦法施行日起六個月內完成代理人之設置。於該期間內尚未完成者，發生第20條第一項及第19條第一項情形時，應即指定具參加同一級別以上專責人員訓練資格之人員，或熟悉廢（污）水處理操作管理之人員代理；並應於事實發生後十五日內以書面報請備查，三十日內完成代理人之設置。第9條並規定代理人之設置員額及更動申請期限。",
 "Enterprises approved before these Regulations must appoint deputies within, and if not yet done:",
 ["Six months from the effective date; immediately designate a qualified or experienced person, report in 15 days and appoint in 30 days","Three months from the effective date; immediately stop operating the treatment facilities and report to the central authority in 7 days","One year from the effective date; no deputy need be designated until the authority notifies and the procedure is completed later","Thirty days from the effective date; the municipal or county authority assigns a deputy and charges the enterprise a fee for it"],
 "Article 21; see also Article 9."),

(WP,"第23條",1,"廢水專責-在職訓練",
 "事業或污水下水道系統就專責人員參加中央主管機關指定之在職訓練，其義務為何？",
 ["不得以任何方式妨礙、禁止廢（污）水處理專責人員參加中央主管機關指定之在職訓練","得視廢（污）水處理設施操作需要，暫緩或禁止專責人員參加該項指定之在職訓練","僅須於專責人員受訓期間指派代理人代理，並得要求其自費參加該項在職訓練課程","得以書面同意權決定專責人員是否參加該項訓練，並報請主管機關核備後即為適法"],"a",
 "第23條：事業或污水下水道系統不得以任何方式妨礙、禁止廢（污）水處理專責人員參加中央主管機關指定之在職訓練。第24條第十二款規定有第23條情形妨礙、禁止專責人員參加在職訓練者，依本法第四十八條第三項處罰。第12條並規定連續三年以上未經核准設置者之到職訓練義務。",
 "What duty does the enterprise owe regarding designated on-the-job training?",
 ["It may not by any means obstruct or prohibit the dedicated person from attending the designated on-the-job training","It may postpone or bar attendance where the operation of the wastewater treatment facilities so requires","It need only appoint a deputy during the training and may require the person to pay the course fees","It may decide by written consent whether the person attends and merely file this with the authority"],
 "Article 23; penalties under Article 24, Subparagraph 12."),

(WP,"第24條",3,"廢水專責-事業罰則",
 "下列何種情形，事業或污水下水道系統應依水污染防治法第四十八條第三項規定處罰？",
 ["未依第三條第一項規定設置廢（污）水處理專責單位或專責人員，或未依第十四條規定於一年內完成核定設置","專責人員同一時間設置於不同之事業或污水下水道系統，且非屬依法共同設置之情形而經主管機關查獲","專責人員一年內二次以上未依規定常駐事業，且未備有請假紀錄或其他相關證明文件供主管機關查閱","專責人員要求委託之檢驗測定機構採樣人員違反採樣方法，採取定期檢測申報所需之放流水水樣"],"a",
 "第24條：事業或污水下水道系統未依第3條第一項設置專責單位或專責人員、負責人兼任而未依第7條第四項重新申請、未依第9條第四項於代理人更動十五日內申請、未依第12條第二項報備到職訓練、未依第12條第三項十五日內重新申請、未依第14條於一年內完成核定設置、未依第16條第二項三十日內重新申請、未依第18條各款監督、未依第19條至第21條執行代理報備、有第23條妨礙在職訓練情形者，依本法第四十八條第三項處罰。其餘選項屬第17條、第25條所定專責人員本身之責任。",
 "Which case subjects the enterprise to penalty under Article 48, Paragraph 3 of the Act?",
 ["Failing to set up the dedicated unit or personnel under Article 3, or to complete the upgrade within a year under Article 14","The dedicated person being appointed at different enterprises at the same time without a lawful joint arrangement","The dedicated person twice in a year not being stationed on site and keeping no leave records for inspection","The dedicated person asking sampling staff of the testing organisation to breach the prescribed sampling method"],
 "Article 24; the others fall under Articles 17 and 25."),

(WP,"第25條",3,"廢水專責-人員罰則",
 "廢（污）水處理專責人員有何情形應依水污染防治法第四十八條第四項處罰？其所稱一年內如何計算？",
 ["一年內二次以上未常駐且未備請假紀錄、使他人利用其名義虛偽設置、一年內二次以上未依規定簽章確認檢測申報等；自違規之日起往前回溯至第三百六十五日止","一年內一次未常駐但已備請假紀錄、於同一處所兼任空氣污染防制專責人員、由代操作營運機構派任擔任專責人員等；自查獲之日起往後推算三百六十五日","半年內三次以上未參加在職訓練、未於到職六個月內完成到職訓練、未依規定辦理代理人更動申請等；自處分之日起往前回溯至第一百八十日止","二年內一次以上未依規定執行第二十二條所定業務、未備有勞健保投保資料同意書等；自申請核定設置之日起往前回溯至第七百三十日止"],"a",
 "第25條：專責人員一年內二次以上未依第15條第一項常駐且未依第16條第一項備有請假紀錄、明知或預見而不違背本意違反本法第十八條之一第一項或第二項、違反第17條第二款或第三款、申報不實或業務文書虛偽記載、一年內二次以上未依第22條第二款第三目填具檢測申報並簽章確認、一年內二次以上未依第22條第三款第四目或第五目執行操作管理業務、違反第22條第五款第一目要求採樣人員違反採樣方法者，依本法第四十八條第四項處罰。所稱一年內，指本辦法施行後之違規行為，自違規之日起往前回溯至第三百六十五日止。",
 "When is the dedicated person penalised under Article 48, Paragraph 4, and how is one year counted?",
 ["Twice a year not stationed with no leave records, lending their name for a false appointment, or twice failing to sign declarations; counted back 365 days from the violation","Once a year not stationed but with leave records kept, serving as air control personnel in the same premises, or being assigned by an operating firm; counted forward 365 days","Three failures in half a year to attend training, missing on-boarding training within six months, or not filing a deputy change; counted back 180 days from the penalty","One failure in two years to perform Article 22 duties or to keep insurance consent forms; counted back 730 days from the date of the application for approval"],
 "Article 25."),

(WP,"第26條",2,"廢水專責-原設置書失效",
 "依本辦法規定應重新申請廢（污）水處理專責單位或人員核定設置者，其原申請核定設置書效力為何？",
 ["自應完成設置之期限屆滿之翌日起失其效力","自主管機關核准新申請案之日起失其效力","自重新申請書送達主管機關之日起失其效力","自原專責人員離職或異動之當日起失其效力"],"a",
 "第26條：依本辦法規定應重新申請廢（污）水處理專責單位或人員核定設置者，其原申請核定設置書自應完成設置之期限屆滿之翌日起，失其效力。第12條第三項、第16條第二項、第7條第四項及第14條均定有應重新申請核定設置之情形與期限，逾期依第24條處罰。",
 "When does the original approval application lose effect where re-application is required?",
 ["From the day after the deadline for completing the appointment expires","From the day the authority approves the newly filed application","From the day the re-application is delivered to the competent authority","From the day the former dedicated person leaves or is transferred"],
 "Article 26."),

(WP,"第27條",2,"廢水專責-舊法排除",
 "自本辦法施行之日起，環境保護專責單位或人員設置及管理辦法有關廢（污）水處理專責單位或人員之規定，其效力為何？",
 ["不再適用之","仍優先適用之","與本辦法併行適用","由主管機關逐案指定適用"],"a",
 "第27條：自本辦法施行之日起，環境保護專責單位或人員設置及管理辦法有關廢（污）水處理專責單位或人員之設置及管理規定，不再適用之。第28條並規定本辦法自發布日施行。第12條第一項所定到職訓練仍依環境保護專責及技術人員訓練管理辦法之規定辦理。",
 "From the effective date of these Regulations, the old general regulations on wastewater dedicated staffing:",
 ["No longer apply at all","Continue to apply first","Apply alongside these rules","Apply as designated case by case"],
 "Article 27; see also Articles 12 and 28."),

(WP,"第28條",1,"廢水專責-施行",
 "廢（污）水處理專責單位或人員設置及管理辦法之施行日期規定為何？",
 ["本辦法自發布日施行","本辦法自發布後一年施行","本辦法自公布後六個月施行","本辦法自中央主管機關指定日施行"],"a",
 "第28條：本辦法自發布日施行。第21條並規定本辦法施行前已核定設置專責單位或人員者，應於施行日起六個月內完成代理人之設置；第27條則排除環境保護專責單位或人員設置及管理辦法相關規定之適用。",
 "When do these Regulations take effect?",
 ["From the date of promulgation","One year after promulgation","Six months after promulgation","On a date designated centrally"],
 "Article 28."),
]
