# -*- coding: utf-8 -*-
# 第 5 批（A）：勞動檢查法、勞動檢查法施行細則、立即發生危險之虞認定標準、違反案件處理要點、重大災害通報要點、優良單位選拔要點
LI = "OSH-03"; LR = "OSH-04"; ID = "OSH-25"; VP = "OSH-27"; MA = "OSH-28"; EX = "OSH-26"
Q = [
# ---------- 勞動檢查法 ----------
(LI,"第3條",2,"勞檢法-定義",
 "勞動檢查法所稱「代行檢查機構」係指何者？",
 ["由中央主管機關指定辦理危險性機械或設備檢查之行政機關、學術機構或非營利法人","由地方主管機關委託辦理勞動條件檢查業務之工會、職業訓練機構或營利事業公司","由中央主管機關設置辦理勞動檢查業務之專責檢查機構、代行檢查員及勞動檢查員","由目的事業主管機關核准辦理危險性作業環境監測之財團法人或民間顧問公司"],"a",
 "第3條：勞動檢查機構指中央或直轄市主管機關或有關機關為辦理勞動檢查業務所設置之專責檢查機構；代行檢查機構指由中央主管機關指定為辦理危險性機械或設備檢查之行政機關、學術機構或非營利法人；勞動檢查員與代行檢查員分別領有勞動檢查證與代行檢查證。",
 "Under the Labor Inspection Act, a 'delegated inspection agency' is:",
 ["An administrative agency, academic institution or non-profit legal person designated by the central authority to inspect dangerous machinery or equipment","A trade union, vocational training institution or for-profit company commissioned by the local authority to inspect working conditions at enterprises","A dedicated inspection body, delegated inspector and labor inspector established by the central authority to carry out the labor inspection business","A foundation or private consulting firm approved by the competent industry authority to carry out the periodic monitoring of dangerous working environments"],
 "Article 3: labor inspection agencies are dedicated bodies of the central or municipal authorities; delegated inspection agencies are designated agencies, academic institutions or non-profits for dangerous machinery/equipment inspection."),

(LI,"第4條",1,"勞檢法-範圍",
 "下列何者屬勞動檢查事項範圍？",
 ["勞動基準法令、職業安全衛生法令及其他依勞動法令應辦理之事項","公司稅務申報法令、商業登記法令及其他依公司法令應辦理之事項","環境保護法令、建築管理法令及其他依都市計畫法令應辦理之事項","消防安全設備法令、食品衛生管理法令及其他依醫療法令應辦理之事項"],"a",
 "第4條：依本法規定應執行檢查之事項、勞動基準法令規定之事項、職業安全衛生法令規定之事項、其他依勞動法令應辦理之事項。細則第3條：勞動法令指勞工保險、勞工福利、就業服務及其他相關法令。",
 "Which falls within the scope of labor inspection?",
 ["Labor Standards laws, OSH laws and other matters required by labor laws","Tax laws, business registration laws and other matters required by company laws","Environmental laws, building laws and other matters required by planning laws","Fire safety laws, food hygiene laws and other matters required by medical laws"],
 "Article 4: matters under this Act, the Labor Standards Act, OSH laws and other labor laws; Enforcement Rules Article 3 defines other labor laws as labor insurance, welfare, employment services etc."),

(LI,"第6條",2,"勞檢法-方針",
 "中央主管機關應於年度開始前幾個月公告並宣導勞動檢查方針？勞動檢查機構應於公告後幾個月內擬定監督檢查計畫？",
 ["六個月；三個月","三個月；一個月","一年；六個月","一個月；一個月"],"a",
 "第6條：中央主管機關應參酌勞動條件、安全衛生條件、職業災害嚴重率及傷害頻率，於年度開始前六個月公告勞動檢查方針（優先受檢事業單位選擇原則、監督檢查重點、檢查及處理原則等）；勞動檢查機構應於公告後三個月內擬定勞動監督檢查計畫報請核備。",
 "The central authority must announce the labor inspection policy how many months before the year begins, and inspection agencies must draw up their plans within how long after?",
 ["6 months; 3 months","3 months; 1 month","1 year; 6 months","1 month; 1 month"],
 "Article 6: policy announced 6 months before the year starts (priority targets, focus, handling principles); agencies draft supervision and inspection plans within 3 months."),

(LI,"第7條",2,"勞檢法-年報",
 "中央主管機關應多久定期公布勞動檢查年報？依施行細則應於何時公布前一年之年報？",
 ["每年；每年第三季","每二年；每年年底","每半年；每年第一季","每季；每季次月底"],"a",
 "第7條第3項：中央主管機關應每年定期公布勞動檢查年報。細則第7條第2項：應於每年第三季公布前一年之勞動檢查年報。",
 "How often is the labor inspection annual report published, and when per the Enforcement Rules?",
 ["Yearly; in the third quarter each year","Every two years; at the end of each year","Every six months; in the first quarter each year","Quarterly; by the end of the following month"],
 "Article 7(3): published annually; Enforcement Rules Article 7(2): in the third quarter for the previous year."),

(LI,"第11條",2,"勞檢法-檢查員",
 "下列何者為勞動檢查員不得有之行為？",
 ["洩漏受檢查事業單位之生產技術、設備及經營財務等秘密（離職後亦同）","於檢查前告知檢查目的並請事業單位派員陪同檢查（依施行細則辦理）","進入事業單位檢查時主動出示勞動檢查證並告知雇主及工會（依第二十二條）","依規定通知事業單位提出必要之報告紀錄及工資清冊等文件（依第十五條）"],"a",
 "第11條：不得為變更隱匿或捏造事實之陳報；不得洩漏受檢事業單位之生產技術設備及經營財務等秘密，離職後亦同；處理秘密申訴案件不得洩漏申訴來源；不得與受檢事業單位發生不當財務關係。任何人得根據事實舉發違法失職。第12條：有利害關係者應自行迴避。",
 "Which is prohibited for labor inspectors?",
 ["Disclosing the inspected enterprise's technical, equipment or financial secrets, even after leaving office","Informing the enterprise of the purpose of the inspection and asking it to send staff to accompany them","Presenting the labor inspector's certificate and notifying the employer and the union on entering the site","Requiring the enterprise to produce necessary reports, records and wage ledgers for examination and copying"],
 "Article 11: no false reports, no disclosure of enterprise secrets (also after leaving), no revealing complaint sources, no improper financial relations; Article 12: recusal for conflicts of interest."),

(LI,"第13條",2,"勞檢法-程序",
 "勞動檢查員執行職務，原則上不得事先通知事業單位，但下列何者除外？",
 ["危險性工作場所審查或檢查、危險性機械或設備檢查、職業災害檢查及其他經核准者","一般安全衛生檢查、勞動條件檢查、勞工申訴案件檢查及其他經工會事先同意者","危險性工作場所定期檢查、機械設備型式驗證、職業病調查及其他經雇主同意者","營造工程開工檢查、鍋爐定期檢查、職業災害統計查核及其他經事先報備核備者"],"a",
 "第13條：勞動檢查員執行職務除第26條之審查或檢查、危險性機械或設備檢查、職業災害檢查及其他經勞動檢查機構或主管機關核准者外，不得事先通知事業單位。",
 "Labor inspectors generally must not give advance notice, except for:",
 ["Dangerous workplace review/inspection, dangerous machinery/equipment inspection, occupational accident inspection and other approved cases","General occupational safety inspections, labor condition inspections, worker complaint inspections and other cases agreed by the union","Periodic dangerous workplace checks, type verification of machinery and equipment, occupational disease surveys and cases agreed by the employer","Construction commencement checks, periodic boiler inspections, accident statistics audits and other cases reported to the agency in advance"],
 "Article 13: the exceptions are Article 26 reviews/inspections, dangerous machinery or equipment inspections, accident inspections and other approved cases."),

(LI,"第14條、第35條",2,"勞檢法-程序",
 "勞動檢查員為執行檢查職務得隨時進入事業單位，雇主或有關人員無故拒絕、規避或妨礙者，處罰為何？",
 ["新臺幣三萬元以上十五萬元以下罰鍰，並得按次處罰","新臺幣三萬元以上六萬元以下罰鍰，並得按次處罰","新臺幣六萬元以上三十萬元以下罰鍰，但不得按次處罰","新臺幣二萬元以上二十萬元以下罰鍰，並得停止其營業"],"a",
 "第14條：勞動檢查員得隨時進入事業單位，雇主、代理人、勞工及有關人員不得無故拒絕、規避或妨礙，非警察協助不足以排除時得要求警察協助。第35條：違反第14條第1項或第15條第2項者處三萬元以上十五萬元以下罰鍰，並得按次處罰。",
 "If an employer or related persons refuse, evade or obstruct a labor inspector's entry without cause, the penalty is:",
 ["A fine of NT$30,000 to NT$150,000, which may be imposed repeatedly","A fine of NT$30,000 to NT$60,000, which may be imposed repeatedly","A fine of NT$60,000 to NT$300,000, which may not be imposed repeatedly","A fine of NT$20,000 to NT$200,000, together with suspension of business"],
 "Article 14 grants entry at any time, with police assistance if needed; Article 35: NT$30,000–150,000 per instance for violating Article 14(1) or 15(2)."),

(LI,"第15條",2,"勞檢法-程序",
 "勞動檢查員執行職務時，得對事業單位有關人員為下列何種行為？",
 ["詢問並製作談話紀錄或錄音、通知提出報告紀錄工資清冊、檢查文件資料並影印拍照錄影測量、封存或掣給收據後抽取物料樣品","逮捕違規雇主並解送法院偵辦、命令事業單位停止營業、沒入違規之機械設備器材、逕行處分罰鍰並移送強制執行","扣押事業單位之帳冊及財產、查封廠房土地並公告拍賣、凍結其銀行存款帳戶、命令其負責人限期出境並接受訊問","解散事業單位之工會組織、撤銷公司登記營業證照、註銷勞工保險投保單位、命令雇主重新申請設立許可並補繳費用"],"a",
 "第15條：詢問有關人員（必要時製作談話紀錄或錄音）、通知提出必要報告紀錄工資清冊文件、檢查應備置之文件資料物品（得影印拍照錄影測量）、封存或掣給收據後抽取物料樣品器材工具以憑檢驗；事業單位不得拒絕；事業單位得申請檢視或複製錄影照片，勞檢機構不得拒絕。",
 "During inspection, labor inspectors may:",
 ["Question personnel (with records or recordings), require reports and wage ledgers, examine and copy/photograph documents, and seal or take samples against receipt","Arrest the offending employer and send him to court, order the business to close down, confiscate the offending machinery, and impose fines for compulsory enforcement","Seize the enterprise's account books and assets, attach and auction its plant and land, freeze its bank accounts, and order the responsible person not to leave the country","Dissolve the enterprise's trade union, revoke its company registration certificate, cancel its labor insurance unit, and order the employer to reapply for a set-up permit"],
 "Article 15: questioning, requiring documents, examining and copying/photographing/measuring, sealing or sampling against receipt; the enterprise may request to view or copy recordings and the agency must not refuse."),

(LI,"第16條",3,"勞檢法-程序",
 "勞動檢查員對違反勞動法律規定之犯罪嫌疑者，必要時得如何？",
 ["聲請檢察官簽發搜索票執行搜索、扣押","報請勞動檢查機構首長核發搜索票執行搜索、扣押","會同當地警察機關逕行執行搜索、扣押相關物件","由勞動檢查員自行簽發封存單執行搜索、扣押"],"a",
 "第16條：勞動檢查員對違反勞動法律規定之犯罪嫌疑者，必要時得聲請檢察官簽發搜索票，就其相關物件、處所執行搜索、扣押。細則第16條：應依刑事訴訟法相關規定。",
 "For suspected crimes under labor laws, labor inspectors may if necessary:",
 ["Apply to a prosecutor for a search warrant to search and seize related objects and premises","Ask the head of the inspection agency to issue a search warrant to search and seize the premises","Search and seize the related objects and premises directly together with the local police authority","Issue a sealing order on their own authority in order to search and seize the objects concerned"],
 "Article 16: apply to a prosecutor for a search warrant; Enforcement Rules Article 16: per the Code of Criminal Procedure."),

(LI,"第17條",2,"勞檢法-代行檢查",
 "危險性機械或設備之檢查，除由勞動檢查員實施外，必要時得由何者實施？",
 ["中央主管機關指定之代行檢查機構派代行檢查員","事業單位委託之檢驗機構派其僱用之技術人員","製造廠商登記之品管單位派其原設計之技師","產物保險公司指定之查勘機構派特約鑑定人"],"a",
 "第17條：危險性機械或設備之檢查除由勞動檢查機構派勞動檢查員實施外，必要時亦得指定代行檢查機構派代行檢查員實施。第19條：代行檢查業務為非營利性質，收費以收支平衡為原則。細則第17條：代行檢查指定期檢查及其他指定公告之檢查。",
 "Besides labor inspectors, inspections of dangerous machinery or equipment may be carried out by:",
 ["Delegated inspectors from agencies designated by the central authority","Testing technicians from laboratories commissioned by the enterprise itself","Licensed engineers from quality units registered by the original manufacturer","Loss adjusters from survey firms appointed by a property insurance company"],
 "Article 17: designated delegated inspection agencies; Article 19: non-profit, fees on a break-even basis; Enforcement Rules Article 17: periodic and other designated inspections."),

(LI,"第22條",2,"勞檢法-程序",
 "勞動檢查員進入事業單位檢查時應如何？事業單位對未持勞動檢查證者得如何？",
 ["主動出示勞動檢查證並告知雇主及工會；得拒絕檢查","僅出示國民身分證並告知當地主管機關；不得拒絕檢查","事先以書面通知雇主及工會到場；應報請主管機關核准","檢查後補行出示勞動檢查證並告知工會；不得拒絕檢查"],"a",
 "第22條：勞動檢查員進入事業單位進行檢查時應主動出示勞動檢查證並告知雇主及工會，事業單位對未持勞動檢查證者得拒絕檢查；檢查後應作成紀錄並告知違反事項及提供遵守法令意見。細則第19條：檢查前應告知檢查目的並請派員陪同。細則第20條：勞動檢查證每二年換發一次。",
 "On entering an enterprise, inspectors must do what, and what may the enterprise do if no certificate is shown?",
 ["Present the labor inspector's certificate and notify the employer and union; refuse the inspection","Show only a national identity card and notify the local competent authority; may not refuse","Notify the employer and the union in writing beforehand to attend; must report to the authority","Show the inspector's certificate only after the inspection ends; may not refuse the inspection"],
 "Article 22: present the certificate and notify employer and union; enterprises may refuse inspectors without a certificate; Enforcement Rules Article 20: certificates reissued every two years."),

(LI,"第25條",2,"勞檢法-結果",
 "勞動檢查機構對違反勞動法令事項應於幾日內書面通知事業單位改正或限期改善？事業單位應將檢查結果公告幾日以上？",
 ["十日內；七日以上","三日內；三日以上","三十日內；三十日以上","七日內；十四日以上"],"a",
 "第25條：有違反勞動法令規定事項者，勞動檢查機構應於十日內以書面通知事業單位立即改正或限期改善，並副知地方主管機關；公營事業另副知目的事業主管機關；事業單位應於違規場所顯明易見處公告七日以上。第36條：未公告者處三萬元以上六萬元以下罰鍰。",
 "The inspection agency must notify the enterprise in writing of violations within how many days, and the enterprise must post the results for at least how long?",
 ["10 days; 7 days","3 days; 3 days","30 days; 30 days","7 days; 14 days"],
 "Article 25: written notice within 10 days, copied to the local authority; results posted conspicuously for at least 7 days; Article 36: failure to post → NT$30,000–60,000."),

(LI,"第26條",2,"勞檢法-危工",
 "下列何種危險性工作場所非經勞動檢查機構審查或檢查合格，事業單位不得使勞工作業？",
 ["從事石油裂解之石化工業工作場所、農藥製造、爆竹煙火及火藥類製造、達規定壓力容量之鍋爐壓力容器、危險物有害物達規定數量、指定營造工程等","從事金屬表面處理之電鍍工廠、飼料製造、玻璃纖維及橡膠類製造、達規定噸數之堆高機吊車、易燃物品達規定重量、一般裝修工程等","從事食品加工之冷凍冷藏工作場所、造紙製造、印刷電路板及油墨類製造、達規定容量之空調冷卻水塔、清潔劑達規定數量、道路挖掘工程等","從事紡織染整之漂白工作場所、水泥製造、磁磚陶瓷及玻璃器皿類製造、達規定功率之發電機組、廢棄物達規定重量、室內裝潢工程等"],"a",
 "第26條：石油裂解之石化工業、農藥製造、爆竹煙火工廠及火藥類製造、設置達規定壓力或容量之高壓氣體類壓力容器或蒸汽鍋爐、製造處置使用危險物有害物達規定數量、中央主管機關會商指定之營造工程、其他指定之工作場所。第34條：違反者處三年以下有期徒刑、拘役或科或併科十五萬元以下罰金。",
 "Which dangerous workplaces may not be operated until reviewed or inspected and approved by the labor inspection agency?",
 ["Petroleum cracking, pesticide manufacturing, fireworks and explosives, boilers/pressure vessels above thresholds, dangerous/harmful substances above thresholds, designated construction works, etc.","Metal electroplating, animal feed manufacturing, glass fibre and rubber products, forklifts/cranes above tonnage thresholds, flammable goods above weight limits, general fit-out works, etc.","Frozen food processing, paper manufacturing, printed circuit boards and printing inks, cooling towers above capacity thresholds, detergents above quantity limits, road excavation works, etc.","Textile bleaching and dyeing, cement manufacturing, tiles, ceramics and glassware, generator sets above rated power thresholds, waste above weight thresholds, interior decoration works, etc."],
 "Article 26 lists seven categories; Article 34: violation → up to 3 years' imprisonment, detention and/or a fine up to NT$150,000."),

(LI,"第27條",2,"勞檢法-停工",
 "事業單位發生重大職業災害時，勞動檢查機構應如何？",
 ["立即指派勞動檢查員前往檢查，調查原因及責任；非立即停工不足以避免擴大者以書面通知部分或全部停工","先函請事業單位自行調查災害原因及責任；經審核其報告認有必要者再以書面通知部分或全部停工","通知地方主管機關派員前往檢查，認定災害等級；非撤銷登記不足以避免擴大者移送法院裁定歇業","於接獲通知三日內指派檢查員前往勘查，統計罹災人數；非全部停工不足以究責者以口頭通知停工"],"a",
 "第27條：勞動檢查機構對事業單位工作場所發生重大職業災害時應立即指派勞動檢查員前往實施檢查，調查職業災害原因及責任；發現非立即停工不足以避免職業災害擴大者，應就發生災害場所以書面通知事業單位部分或全部停工。",
 "When a major occupational accident occurs, the labor inspection agency shall:",
 ["Immediately dispatch inspectors to investigate causes and responsibility, and order partial or full stoppage in writing if needed to prevent escalation","Ask the enterprise to investigate the causes and responsibility itself, and order partial or full stoppage in writing only after reviewing its report","Notify the local competent authority to send staff to grade the accident, and apply to a court to close the business if that is needed to stop escalation","Dispatch inspectors within three days to survey the site and count the victims, and order a stoppage verbally where full stoppage is needed to fix liability"],
 "Article 27: immediate dispatch and investigation, with written stop-work orders where necessary to prevent the accident from spreading."),

(LI,"第28條",2,"勞檢法-停工",
 "勞動檢查員實施安全衛生檢查時發現勞工有立即發生危險之虞，勞動檢查機構得如何？",
 ["以書面通知事業單位逕予先行停工","以口頭警告事業單位限期改善後複查","報請中央主管機關核定後始得停工","先處以罰鍰並通知事業單位繼續作業"],"a",
 "第28條：發現勞工有立即發生危險之虞，得就該場所以書面通知事業單位逕予先行停工；有立即發生危險之虞之情事由中央主管機關定之（勞動檢查法第二十八條所定勞工有立即發生危險之虞認定標準）。第30條：停工原因消滅後得申請復工。",
 "If an inspection finds workers in imminent danger, the inspection agency may:",
 ["Order an immediate stoppage of that workplace in writing","Give a verbal warning and recheck after a set deadline","Order the stoppage only after the central authority approves","Impose a fine first and let the work at that place continue"],
 "Article 28: immediate written stop-work order; the criteria for imminent danger are set by the central authority; Article 30: resumption may be applied for once the cause is removed."),

(LI,"第29條",3,"勞檢法-停工",
 "事業單位未依勞動檢查機構通知限期改善事項辦理而有發生職業災害之虞時，勞動檢查機構得如何？",
 ["於認有必要時以書面通知部分或全部停工","應即移送地方法院檢察署偵辦並公布名稱","得逕行撤銷其工廠登記及營業許可證照","僅得再次通知限期改善而不得通知其停工"],"a",
 "第29條：勞動檢查員對事業單位未依通知限期改善事項辦理而有發生職業災害之虞時應陳報所屬勞動檢查機構；勞動檢查機構於認有必要時得以書面通知事業單位部分或全部停工。細則第33條：全部停工日數超過七日者應陳報中央主管機關核定。",
 "If an enterprise fails to make required improvements by the deadline and an accident is likely, the inspection agency may:",
 ["Order partial or full stoppage in writing when deemed necessary","Refer the case to the district prosecutor and publish the name","Revoke the factory registration and the business licence directly","Only set another improvement deadline and never order a stoppage"],
 "Article 29: written stop-work order when necessary; Enforcement Rules Article 33: full stoppages over 7 days require central approval."),

(LI,"第32條",2,"勞檢法-申訴",
 "事業單位應於顯明易見處公告哪些勞工申訴相關事項？",
 ["受理申訴之機構或人員、勞工得申訴之範圍、申訴書格式、申訴程序","受理檢舉之檢察機關、雇主得抗辯之範圍、答辯書格式、訴願程序","調解勞資爭議之委員會、工會得協商之事項、協議書格式、仲裁程序","辦理職災補償之保險機構、勞工得請領之給付、申請書格式、核定程序"],"a",
 "第32條：受理勞工申訴之機構或人員、勞工得申訴之範圍、勞工申訴書格式、申訴程序，公告書由中央主管機關定之。第36條：未公告者處三萬元以上六萬元以下罰鍰。",
 "Enterprises must conspicuously post which complaint-related items?",
 ["The body or person receiving complaints, the scope of complaints, the complaint form and the procedure","The prosecutor's office receiving reports, the scope of defence, the defence form and the appeal steps","The committee mediating labor disputes, the matters for bargaining, the agreement form and arbitration","The insurer paying accident compensation, the benefits claimable, the claim form and the approval steps"],
 "Article 32: the four items, using the format set by the central authority; Article 36: failure → NT$30,000–60,000."),

(LI,"第33條",2,"勞檢法-申訴",
 "勞動檢查機構受理勞工申訴後，應於幾日內將檢查結果通知申訴人？事業單位得否對申訴人不利處分？",
 ["十四日內；不得終止契約或為其他不利處分","七日內；得終止契約或為其他不利處分","三十日內；得調整職務或減發工資獎金","六十日內；應先報請主管機關核准後處分"],"a",
 "第33條：受理申訴後應儘速派員檢查並於十四日內將檢查結果通知申訴人；勞工向工會申訴者由工會查證後提出書面改善建議；事業單位不得對申訴人終止勞動契約或為其他不利處分；勞動檢查機構應保密不得洩漏申訴人身分。",
 "After receiving a worker's complaint, the agency must notify the complainant of results within how long, and may the enterprise penalize the complainant?",
 ["14 days; no termination or other adverse treatment allowed","7 days; termination and other adverse treatment are allowed","30 days; reassignment or a pay cut is allowed as a penalty","60 days; adverse treatment allowed with prior official approval"],
 "Article 33: results within 14 days; unions may propose improvements; no adverse treatment of complainants; complainant identity kept confidential."),

(LI,"第34條",2,"勞檢法-罰則",
 "違反停工通知或使勞工在未經審查檢查合格之危險性工作場所作業者，處罰為何？",
 ["三年以下有期徒刑、拘役或科或併科新臺幣十五萬元以下罰金","一年以下有期徒刑、拘役或科或併科新臺幣三萬元以下罰金","五年以下有期徒刑、拘役或科或併科新臺幣三十萬元以下罰金","新臺幣三萬元以上十五萬元以下罰鍰，並得按次連續處罰"],"a",
 "第34條：違反第26條使勞工在未經審查或檢查合格之工作場所作業者，或違反第27條至第29條停工通知者，處三年以下有期徒刑、拘役或科或併科十五萬元以下罰金；法人代表人代理人受僱人因執行業務犯者，對該法人或自然人亦科以罰金。",
 "Violating a stop-work order or operating an unapproved dangerous workplace is punishable by:",
 ["Up to 3 years' imprisonment, detention and/or a fine up to NT$150,000","Up to 1 year's imprisonment, detention and/or a fine up to NT$30,000","Up to 5 years' imprisonment, detention and/or a fine up to NT$300,000","A fine of NT$30,000 to NT$150,000, imposed repeatedly for each violation"],
 "Article 34: criminal penalty up to 3 years plus fine up to NT$150,000, also imposed on the legal person or natural person employer."),

# ---------- 勞動檢查法施行細則 ----------
(LR,"第6條",3,"勞檢細則-定義",
 "勞動檢查法施行細則所稱「職業災害嚴重率」及「傷害頻率」之定義為何？",
 ["每百萬工時之失能傷害總損失日數；每百萬工時之失能傷害次數","每千人之職業災害死亡人數；每千人之職業災害受傷人數","每年之職業災害總發生件數；每月之職業災害總發生件數","每萬工時之失能傷害總損失日數；每萬工時之失能傷害次數"],"a",
 "細則第6條：職業災害嚴重率指每百萬工時之失能傷害總損失日數；傷害頻率指每百萬工時之失能傷害次數。",
 "Under the Enforcement Rules, 'severity rate' and 'frequency rate' mean:",
 ["Total lost days from disabling injuries per million work hours; number of disabling injuries per million work hours","Total number of occupational fatalities per 1,000 workers; total number of occupational injuries per 1,000 workers","Total number of occupational accident cases each year; total number of occupational accident cases each month","Total lost days from disabling injuries per 10,000 work hours; number of disabling injuries per 10,000 work hours"],
 "Enforcement Rules Article 6: severity rate = disabling-injury lost days per million hours; frequency rate = disabling injuries per million hours."),

(LR,"第9條",2,"勞檢細則-檢查員",
 "新進勞動檢查員未經職前訓練合格前，勞動檢查機構得否指派其單獨執行檢查職務？",
 ["不得，但特殊情況經陳報中央主管機關核准者不在此限","得，但應由資深檢查員陪同並於三個月內完成訓練","得，但以一般安全衛生檢查及勞動條件檢查案件為限","不得，但經事業單位書面同意並報請工會備查者不在此限"],"a",
 "細則第8條：專業訓練指新進人員之職前訓練、現職人員之在職訓練及進修。第9條：新進勞動檢查員未經職前訓練合格前不得指派其單獨執行檢查職務，但特殊情況經敘明理由陳報中央主管機關核准者不在此限。",
 "May a new labor inspector be assigned to inspect alone before passing pre-service training?",
 ["No, except in special cases approved by the central authority","Yes, if accompanied by a senior inspector for three months","Yes, but only for general OSH and labor condition inspections","No, except with the written consent of the enterprise and union"],
 "Article 8 defines professional training; Article 9 bars solo assignments before pre-service training passes, except with central approval."),

(LR,"第13條",3,"勞檢細則-封存",
 "勞動檢查員實施封存，以下列何種情事為限？",
 ["違反職安法令所禁止使用者、違反勞動法令者、職災原因鑑定所必須者、其他經勞檢機構核准者","違反消防法令所禁止使用者、違反環保法令者、火災原因調查所必須者、其他經地方政府核准者","經雇主書面同意封存者、經勞工申訴指明者、經工會決議請求者、其他經檢查員認為適當者","違反建築法令所禁止使用者、違反稅務法令者、產品品質檢驗所必須者、其他經法院裁定者"],"a",
 "細則第13條：封存以有違反職業安全衛生法令所禁止使用者、有違反勞動法令者、有職業災害原因鑑定所必須者、其他經勞動檢查機構核准者為限；原因消滅或經許可得啟封。第14條：應開列封存物件清單及貼封條，封條加蓋印信並載明機構名稱、物件名稱、封存日期、法令依據。",
 "Sealing by labor inspectors is limited to:",
 ["Items banned under OSH laws, items violating labor laws, items needed for accident cause identification, and other cases approved by the agency","Items banned under fire laws, items violating environmental laws, items needed for fire cause investigation, and other cases approved by the government","Items sealed with the employer's consent, items named in a worker's complaint, items requested by union resolution, and other cases the inspector allows","Items banned under building laws, items violating tax laws, items needed for product quality testing, and other cases ordered by a court of law"],
 "Article 13: the four situations; unsealing when the cause ends or on approved application; Article 14: inventory list and stamped seal stating agency, item, date and legal basis."),

(LR,"第15條",3,"勞檢細則-程序",
 "事業單位向勞動檢查機構申請檢視或複製檢查時之錄影照片，應於受檢之次日起幾日內書面提出？機構應於接獲後幾日內提供？",
 ["三十日；三十日","七日；十四日","十日；二十日","六十日；三十日"],"a",
 "細則第15條：事業單位依本法第15條第3項申請檢視或複製時，應於受檢之次日起三十日內以書面提出；勞動檢查機構應於接獲申請書之次日起三十日內提供。",
 "An enterprise must request in writing to view or copy inspection recordings within how many days after inspection, and the agency must provide them within:",
 ["30 days; 30 days","7 days; 14 days","10 days; 20 days","60 days; 30 days"],
 "Article 15: request within 30 days of the day after inspection; provided within 30 days of receipt."),

(LR,"第21條",2,"勞檢細則-異議",
 "事業單位對檢查結果通知書有異議時，應於通知書送達之次日起幾日內書面提出？改善期限是否因異議而停止計算？",
 ["十日內；不停止","三十日內；停止計算","七日內；停止計算","十五日內；不停止"],"a",
 "細則第21條：有異議者應於通知書送達之次日起十日內以書面敘明理由向勞動檢查機構提出；通知書所定改善期限在機構另為適當處分前，不因異議而停止計算。",
 "An enterprise objecting to an inspection result notice must file within how many days, and is the improvement deadline suspended?",
 ["10 days; not suspended","30 days; time stops running","7 days; time stops running","15 days; not suspended"],
 "Article 21: written objection within 10 days; the improvement deadline keeps running unless the agency rules otherwise."),

(LR,"第23條",2,"勞檢細則-公告",
 "事業單位以檢查結果通知書全部內容公告者，應公告於何處？",
 ["管制勞工出勤之場所、餐廳宿舍及各作業場所之公告場所、或與工會或勞工代表協商同意之場所之一","事業單位之公司網站首頁、股東會及董事會之會議紀錄、或與主管機關協商指定之刊物之一","當地勞工主管機關之公布欄、工會辦公室及勞資會議之場所、或經檢查機構指定之報紙之一","事業單位大門外之圍牆、員工人事資料檔案及薪資袋內、或經雇主自行選定之內部公告欄之一"],"a",
 "細則第23條：以通知書全部內容公告者，公告於事業單位管制勞工出勤之場所、餐廳宿舍及各作業場所之公告場所、與工會或勞工代表協商同意之場所之一；以違反規定單項內容公告者，公告於違反規定之機具設備或場所。",
 "Where must the full inspection result notice be posted?",
 ["At the attendance-control area, the notice boards of canteens/dormitories/work areas, or a place agreed with the union or worker representatives","On the company website home page, the minutes of shareholder and board meetings, or a publication designated with the competent authority","On the local labor authority's notice board, the union office and labor-management meeting room, or a newspaper designated by the agency","On the outside wall by the main gate, in personnel files and pay envelopes, or on any internal notice board the employer chooses for itself"],
 "Article 23: one of the three listed places for full notices; single-item notices go on the offending machine, equipment or place."),

(LR,"第27-1條",3,"勞檢細則-危工",
 "勞檢法第26條所稱高壓氣體類壓力容器，不包括下列何者？",
 ["移動式製造設備、非有毒性可燃性之單座固定式製造設備、減壓設備、空調設備及氟氯烷冷媒冷凍機器","固定式製造設備、具有毒性或可燃性之多座移動式儲存容器、加壓設備、冷卻設備及液氧儲存槽車","供處理高壓氣體之盛裝容器、液化石油氣儲槽、氨冷凍設備、氧氣儲槽及蒸汽鍋爐等加熱裝置","移動式起重機、非屬有毒性之單座升降設備、通風設備、照明設備及以清水為冷媒之冷卻水塔"],"a",
 "細則第27條之1：高壓氣體類壓力容器指供處理及儲存高壓氣體之盛裝容器，但不包括移動式製造設備、非屬有毒性或可燃性高壓氣體之單座固定式製造設備、減壓設備、空調設備及以氟氯烷為冷媒之冷凍機器；蒸汽鍋爐指以火焰燃燒氣體或高溫氣體加熱於水或熱媒使發生超過大氣壓之壓力蒸汽供他用之裝置及附屬過熱器節煤器。",
 "High-pressure gas pressure vessels under Article 26 of the Act do NOT include:",
 ["Mobile production equipment, single fixed units for non-toxic non-flammable gas, pressure-reducing equipment, air conditioners and CFC-refrigerant refrigeration machines","Fixed production equipment, multiple mobile storage vessels for toxic or flammable gas, pressure-raising equipment, cooling units and large liquid-oxygen tank trucks","Containers for handling high-pressure gas, LPG storage tanks, ammonia refrigeration systems, oxygen storage tanks and steam boilers used as gas-fired heating devices","Mobile cranes, single non-toxic lifting units, ventilation equipment, lighting equipment and cooling water towers that use plain water as the circulating refrigerant"],
 "Enforcement Rules Article 27-1: the four exclusions; steam boilers are also defined there."),

(LR,"第31條",2,"勞檢細則-重大災害",
 "勞動檢查法第27條所稱重大職業災害，係指下列何者？",
 ["發生死亡災害、罹災人數三人以上、氨氯氟化氫光氣硫化氫二氧化硫等洩漏致一人以上需住院、其他指定公告之災害","發生財物損失災害、罹災人數十人以上、氧氣氮氣二氧化碳氬氣氦氣等外洩致三人以上請假、其他自行認定之災害","發生輕傷災害、罹災人數二人以上、汽油柴油甲醇乙醇丙酮甲苯等溢漏致一人以上就醫、其他經工會決議之災害","發生停工事故、罹災人數五人以上、粉塵噪音輻射高溫低溫振動等超標致一人以上不適、其他經雇主通報之災害"],"a",
 "細則第31條：發生死亡災害者；發生災害之罹災人數在三人以上者；氨、氯、氟化氫、光氣、硫化氫、二氧化硫等化學物質之洩漏發生一人以上罹災勞工需住院治療者；其他經中央主管機關指定公告之災害。",
 "'Major occupational accidents' under Article 27 of the Act are:",
 ["Fatal accidents, 3+ victims, leaks of ammonia/chlorine/HF/phosgene/H2S/SO2 with 1+ hospitalized, and other designated accidents","Property-loss accidents, 10+ victims, releases of oxygen/nitrogen/CO2/argon/helium with 3+ on leave, and other self-determined accidents","Minor-injury accidents, 2+ victims, spills of petrol/diesel/methanol/ethanol/acetone with 1+ treated, and accidents resolved by the union","Stoppage incidents, 5+ victims, dust/noise/radiation/heat/vibration above limits with 1+ unwell, and accidents reported by the employer"],
 "Enforcement Rules Article 31: the four categories."),

(LR,"第33條",3,"勞檢細則-停工",
 "勞動檢查機構通知事業單位全部停工之日數超過幾日者，應陳報中央主管機關核定？",
 ["七日","三日","十四日","三十日"],"a",
 "細則第33條：停工日數由勞動檢查機構視情節決定；全部停工日數超過七日者應陳報中央主管機關核定。第34條：停工通知書應記載事業單位名稱地址、法令依據、停工理由、停工日期、停工範圍、申請復工之條件及程序、執行機構。",
 "Full stop-work orders exceeding how many days must be reported to the central authority for approval?",
 ["7 days","3 days","14 days","30 days"],
 "Article 33: over 7 days; Article 34 lists the required contents of stop-work notices."),

(LR,"第36條",2,"勞檢細則-復工",
 "事業單位申請復工，勞動檢查機構應如何處理？",
 ["查證停工原因消滅後以書面通知復工，載明事業單位名稱地址、復工日期、復工範圍","於接獲申請當日先以口頭同意復工，事後補行通知，載明復工日期、復工範圍及罰鍰金額","報請中央主管機關核定後由其通知復工，載明事業單位負責人姓名、停工日期、罰鍰金額","由事業單位自行公告復工並副知檢查機構，載明工會同意日期、復工範圍及改善措施"],"a",
 "細則第36條：勞動檢查機構於查證停工原因消滅後，應以書面通知其復工；復工通知書應記載申請復工之事業單位雇主名稱地址、復工日期、復工範圍。",
 "When an enterprise applies to resume work, the agency shall:",
 ["Verify the cause has been removed and notify resumption in writing with the enterprise name, date and scope","Approve resumption verbally on the day of application and confirm later, stating the date, scope and fine","Report to the central authority, which notifies resumption stating the employer's name, date and fine","Let the enterprise announce resumption itself and copy the agency, stating the union's consent and scope"],
 "Article 36: written resumption notice after verification, stating enterprise, resumption date and scope."),

# ---------- 立即發生危險之虞認定標準 ----------
(ID,"第2條",1,"立即危險-類型",
 "勞動檢查法第28條所定勞工有立即發生危險之虞之類型有哪些？",
 ["墜落、感電、倒塌崩塌、火災爆炸、中毒缺氧","噪音振動、高溫低溫、粉塵飛散、輻射曝露、異常氣壓","跌倒滑倒、切割擦傷、燒燙傷害、被夾被捲、物體飛落","交通事故、溺水窒息、動物咬傷、感染疾病、精神壓力"],"a",
 "認定標準第2條：有立即發生危險之虞之類型為墜落、感電、倒塌崩塌、火災爆炸、中毒缺氧五類。第8條：中央主管機關得指定其他情事並公告。",
 "The types of imminent danger under Article 28 of the Labor Inspection Act are:",
 ["Falls, electrocution, collapse, fire/explosion, poisoning/oxygen deficiency","Noise and vibration, heat and cold, dust, radiation, abnormal air pressure","Slips and trips, cuts and abrasions, burns, being caught, falling objects","Traffic accidents, drowning, animal bites, infectious disease, mental stress"],
 "Article 2 of the Standards: five types; Article 8 allows the central authority to designate more."),

(ID,"第3條",2,"立即危險-墜落",
 "下列何者屬有立即發生墜落危險之虞之情事？",
 ["於高差二公尺以上之工作場所邊緣及開口部分，未設置護欄、護蓋、安全網或配掛安全帶之防墜設施","於高差零點五公尺以下之地面作業區域周邊，已設置護欄、護蓋、安全網及配掛安全帶之防墜設施","於室內平坦地面之一般作業場所走道及通路，未使勞工佩戴安全帽、耳塞或反光背心等個人防護具","於高度一點五公尺以下之移動梯及合梯作業，未設置扶手、腳墊、防滑板或指派監視人員之措施"],"a",
 "第3條：高差二公尺以上邊緣開口未設防墜設施；高差二公尺以上作業未用高空工作車或設工作臺且未張掛安全網配掛安全帶；易踏穿屋頂未設三十公分以上踏板安全網或安全帶；高差超過一點五公尺未設安全上下設備；超過二層樓或七點五公尺鋼構未張設安全網；移動式起重機吊掛平台載人未設圍欄安全母索等。",
 "Which is an imminent fall danger?",
 ["Edges or openings at a height difference of 2 m or more without guardrails, covers, safety nets or harness anchorages","Areas around ground level work with a height difference under 0.5 m already fitted with guardrails, covers and nets","Walkways and passages in ordinary indoor workplaces where the workers wear no helmets, ear plugs or reflective vests","Portable and step ladders under 1.5 m in height used without handrails, non-slip feet, boards or a watcher assigned"],
 "Article 3: unprotected edges/openings at 2 m+, work at 2 m+ without platforms/nets/harness, fragile roofs without 30 cm walkboards, no safe access above 1.5 m, steel structures over 2 floors or 7.5 m without nets, crane-suspended platforms without guards."),

(ID,"第3條",3,"立即危險-墜落",
 "於石綿板、鐵皮板、瓦、木板等易踏穿材料構築之屋頂作業，未設置寬度幾公分以上之踏板、安全網或安全帶者，屬立即發生危險之虞？",
 ["三十公分","二十公分","四十公分","五十公分"],"a",
 "第3條第3款：於易踏穿材料構築之屋頂從事作業時，未於屋架上設置防止踏穿及寬度三十公分以上之踏板、裝設安全網或配掛安全帶。",
 "Work on fragile roofs (asbestos sheet, metal sheet, tiles, wood) is an imminent danger when walkboards are narrower than, and no nets or harnesses are used:",
 ["30 cm","20 cm","40 cm","50 cm"],
 "Article 3(3): walkboards at least 30 cm wide, safety nets or harnesses required."),

(ID,"第4條",3,"立即危險-感電",
 "使用對地電壓在多少伏特以上之移動式或攜帶式電動機具，未設置漏電斷路器者，屬立即發生感電危險之虞？",
 ["一百五十伏特","一百一十伏特","二百二十伏特","三百八十伏特"],"a",
 "第4條第2款：使用對地電壓在一百五十伏特以上移動式或攜帶式電動機具，或於潮濕場所金屬板上鋼架上等導電性良好場所使用移動式或攜帶式電動機具，未設置高敏感度高速型漏電斷路器。第3款：狹小空間或鋼架場所之交流電焊機未裝自動電擊防止裝置。",
 "Portable or mobile electric tools with a voltage to ground of at least what, used without a residual-current device, constitute imminent electrocution danger?",
 ["150 V","110 V","220 V","380 V"],
 "Article 4(2): 150 V or more, or any portable tool in wet or conductive locations without a high-sensitivity fast RCD; Article 4(3): AC welders in confined conductive spaces without automatic voltage reducers."),

(ID,"第5條",3,"立即危險-倒塌",
 "施工架於垂直方向幾公尺、水平方向幾公尺內未與穩定構造物妥實連接者，屬立即發生倒塌危險之虞？",
 ["五點五公尺；七點五公尺","三點五公尺；五點五公尺","九點五公尺；八點五公尺","二點五公尺；四點五公尺"],"a",
 "第5條：施工架垂直方向五點五公尺、水平方向七點五公尺內未與穩定構造物妥實連接；露天開挖一點五公尺以上或有崩塌之虞未設擋土支撐等；隧道坑道有落磐之虞未設支撐岩栓噴凝土；模板支撐支柱基礎易積水地盤軟弱未強化。",
 "Scaffolds not tied to a stable structure within what vertical and horizontal spacing constitute imminent collapse danger?",
 ["5.5 m vertically; 7.5 m horizontally","3.5 m vertically; 5.5 m horizontally","9.5 m vertically; 8.5 m horizontally","2.5 m vertically; 4.5 m horizontally"],
 "Article 5: 5.5 m vertical and 7.5 m horizontal; also unsupported excavations 1.5 m+, tunnels without support, and formwork on soft or waterlogged ground."),

(ID,"第6條",3,"立即危險-火災爆炸",
 "存有易燃液體蒸氣或可燃性氣體之作業場所，濃度達爆炸下限值之百分之多少以上時，未使勞工退避並停止使用點火源者，屬立即發生火災爆炸危險之虞？",
 ["百分之三十","百分之十","百分之五十","百分之百"],"a",
 "第6條第2款：未於作業前測定濃度，或濃度達爆炸下限值之百分之三十以上時未即刻使勞工退避至安全場所並停止使用煙火及其他點火源之機具。第6款：局限空間作業場所使用純氧換氣亦屬之。",
 "In workplaces with flammable vapors or gases, failing to evacuate and stop ignition sources when concentration reaches what percentage of the LEL is an imminent fire/explosion danger?",
 ["30%","10%","50%","100%"],
 "Article 6(2): 30% of the lower explosive limit; Article 6(6): using pure oxygen for ventilation in confined spaces also qualifies."),

(ID,"第7條",3,"立即危險-缺氧",
 "在人孔、下水道、儲槽等自然換氣不充分之場所，空氣中氧氣濃度未滿百分之十八、硫化氫超過多少 ppm 或一氧化碳超過多少 ppm 而未確實配戴呼吸防護具者，屬立即發生危險之虞？",
 ["硫化氫十 ppm；一氧化碳三十五 ppm","硫化氫五 ppm；一氧化碳二十五 ppm","硫化氫二十 ppm；一氧化碳五十 ppm","硫化氫一 ppm；一氧化碳十 ppm"],"a",
 "第7條第5款：氧氣濃度未滿百分之十八、硫化氫濃度超過十 ppm 或一氧化碳濃度超過三十五 ppm 時未確實配戴空氣呼吸器等呼吸防護具、安全帶及安全索；或未置備通風設備換氣、未置備測定儀器隨時測定保持氧氣十八％以上、硫化氫十 ppm 以下、一氧化碳三十五 ppm 以下。",
 "In poorly ventilated spaces such as manholes, sewers or tanks, imminent danger exists when oxygen is below 18%, hydrogen sulfide exceeds, or carbon monoxide exceeds:",
 ["H2S 10 ppm; CO 35 ppm","H2S 5 ppm; CO 25 ppm","H2S 20 ppm; CO 50 ppm","H2S 1 ppm; CO 10 ppm"],
 "Article 7(5): O2 under 18%, H2S over 10 ppm or CO over 35 ppm without respirators, harness and lifeline, or without ventilation and continuous measurement."),

(ID,"第7條",3,"立即危險-中毒",
 "製造、處置或使用特定化學物質危害預防標準所稱丙類第一種或丁類物質之特定化學管理設備時，未設置何種裝置屬立即發生中毒危險之虞？",
 ["適當之溫度、壓力及流量計測裝置及發生異常之自動警報裝置","適當之照度、色溫及演色性照明裝置及發生停電之緊急照明裝置","適當之溫度、濕度及風速空調裝置及發生異味之自動除臭裝置","適當之角度、高度及位置監視攝影裝置及發生入侵之自動門禁裝置"],"a",
 "第7條第2至4款：特定化學管理設備未設溫度壓力流量計測裝置及異常自動警報裝置；未設遮斷原料供輸、卸放製品、冷卻用水或惰性氣體供輸裝置；未設洩漏時能立即警報之器具及除卻危害必要藥劑容器之設施。第1款：有機溶劑儲槽等作業未供給輸氣管面罩。",
 "For specified chemical management equipment handling Class C-1 or Class D substances, imminent poisoning danger exists when the equipment lacks:",
 ["Temperature, pressure and flow measuring devices and automatic abnormality alarms","Illuminance, colour temperature and rendering lighting and emergency lights for power failure","Temperature, humidity and wind speed air conditioning and automatic deodorising devices","Angle, height and position surveillance cameras and automatic access control doors"],
 "Article 7(2)–(4): missing measuring devices and alarms, missing shut-off/discharge/cooling/inert-gas devices, or missing leak alarms and neutralizing agents."),

# ---------- 違反案件處理要點 ----------
(VP,"第3點",2,"案件處理-繳納",
 "違反職安法或勞檢法之罰鍰處分，其繳納期限為送達處分書之次日起幾日內？逾期經催繳仍未繳納者如何處理？",
 ["三十日內；催繳通知送達次日起十五日內仍未繳納得移送行政執行","十日內；催繳通知送達次日起三日內仍未繳納即得逕行強制執行","六十日內；催繳通知送達次日起三十日內仍未繳納應撤銷原處分","七日內；催繳通知送達次日起七日內仍未繳納應加倍計算罰鍰金額"],"a",
 "要點第3點：罰鍰繳納期限為送達處分書之次日起三十日內，屆滿未繳納者原處分機關擬具罰鍰催繳通知書催繳；第4點：催繳通知送達次日起十五日內仍未繳納者，得移送法務部行政執行署所屬分署執行。",
 "Fines under the OSH Act or Labor Inspection Act must be paid within how many days of service, and what follows a reminder?",
 ["30 days; if unpaid 15 days after the reminder, the case may be referred for administrative enforcement","10 days; if unpaid 3 days after the reminder, compulsory enforcement follows without any further notice","60 days; if unpaid 30 days after the reminder, the original penalty must be revoked automatically","7 days; if unpaid 7 days after the reminder, the fine must be doubled before administrative enforcement"],
 "Points 3–4: 30 days from the day after service; a reminder notice; referral to the Administrative Enforcement Agency if still unpaid 15 days after the reminder."),

(VP,"第5點",3,"案件處理-分類",
 "依違反案件處理要點，非屬營造業之事業單位勞工總人數在三百人以上者，屬何類事業單位？",
 ["甲類","乙類","丙類","丁類"],"a",
 "第5點：甲類為上市上櫃公司、營造業承攬單一工程二億元以上、非營造業勞工三百人以上、依職安法第15條之1或第27條之1交付一定規模工程者；乙類為營造業五千萬元以上未達二億元、非營造業一百人以上未達三百人；丙類為營造業五百萬元以上未達五千萬元、非營造業六人以上未達一百人；丁類為未達前三類者。",
 "Under the case-handling directive, a non-construction enterprise with 300 or more workers is classified as:",
 ["Class A (甲)","Class B (乙)","Class C (丙)","Class D (丁)"],
 "Point 5: Class A = listed companies, construction contracts NT$200M+, non-construction 300+ workers; Class B = NT$50M–200M or 100–299 workers; Class C = NT$5M–50M or 6–99 workers; Class D = below."),

(VP,"第5點",3,"案件處理-分類",
 "營造業承攬單一工程之金額在新臺幣五千萬元以上未達二億元者，屬何類事業單位？",
 ["乙類","甲類","丙類","丁類"],"a",
 "第5點第2款：乙類指營造業承攬單一工程之金額在五千萬元以上未達二億元者，或非營造業勞工總人數一百人以上未達三百人者。",
 "A construction enterprise with a single contract of NT$50 million to under NT$200 million is:",
 ["Class B (乙)","Class A (甲)","Class C (丙)","Class D (丁)"],
 "Point 5(2): Class B for NT$50M–200M contracts or 100–299 workers in non-construction industries."),

(VP,"第8點",2,"案件處理-公布",
 "依職安法第49條，主管機關對違反職安法受罰鍰或刑罰處罰，或致發生第37條第2項職業災害之事業單位，應公布何事項？",
 ["事業單位雇主名稱及負責人姓名；處以罰鍰者並公布處分期日、違反條文及罰鍰金額；並公布職災發生日期地點及罹災人數","事業單位之統一編號及資本總額；處以罰鍰者並公布繳納期限、承辦人員姓名及催繳次數；並公布職災之保險給付金額","事業單位工會名稱及理事長姓名；處以刑罰者並公布起訴日期、承辦檢察官及求刑年數；並公布罹災勞工姓名及年齡","事業單位之營業地址及電話號碼；處以罰鍰者並公布申訴期限、救濟結果及繳納帳戶；並公布職災之調查報告全文"],"a",
 "第8點：應公布其事業單位、雇主之名稱及負責人姓名；處以罰鍰者應公布處分期日、違反條文及罰鍰金額；符合情形者並應公布職業災害之發生日期、發生地及罹災人數。",
 "Under OSH Act Article 49, for enterprises fined or criminally punished, or that caused a reportable accident, the authority must publish:",
 ["Enterprise and employer names and the responsible person; for fines, the date, violated provisions and amount; plus accident date, place and number of victims","The enterprise's tax number and capital; for fines, the payment deadline, the officer in charge and the number of reminders; plus the insurance benefits paid","The enterprise union's name and its chairperson; for criminal cases, the indictment date, the prosecutor and the sentence sought; plus victims' names and ages","The enterprise's business address and telephone; for fines, the appeal deadline, the remedy outcome and the payment account; plus the full investigation report"],
 "Point 8: names and responsible person; penalty date, provisions and amount; accident date, location and victim count."),

(VP,"第9點",3,"案件處理-加重",
 "處分機關依職安法第43條第1項或第45條第1項處以罰鍰時，得依事業規模性質或情節加重罰鍰至法定最高額之多少？",
 ["二分之一","四分之一","三分之一","十分之一"],"a",
 "第9點：得依事業規模、性質或違反情節，加重其罰鍰至法定罰鍰最高額二分之一。第6點：同一違法態樣違反多項法條得逐一累加至最高罰鍰；不同態樣分別處罰。第10點：違反次數自違反之日往前回溯三年內累計。",
 "When fining under OSH Act Articles 43(1) or 45(1), the authority may increase the fine by up to what share of the statutory maximum?",
 ["One half","One quarter","One third","One tenth"],
 "Point 9: up to half of the statutory maximum; Point 6: same-type violations accumulate to the maximum; Point 10: violation counts look back three years."),

# ---------- 重大災害通報及檢查處理要點 ----------
(MA,"第2點",2,"重大災害-定義",
 "依勞動部重大災害通報及檢查處理要點，行政院災害緊急通報作業規定所稱「甲級災害規模」之職業災害為何？",
 ["工作場所職災造成三人以上死亡、五人以上罹災（含失蹤）、或經媒體廣為報導之火災爆炸有害氣體外洩等","工作場所職災造成一人以上死亡、三人以上罹災（含輕傷）、或經工會提報之機械夾捲感電墜落事故等","工作場所職災造成十人以上死亡、二十人以上罹災（含失蹤）、或經檢察官起訴之工安刑事案件等","工作場所職災造成五人以上受傷、二人以上住院（含門診）、或經地方政府公布之食品中毒群聚事件等"],"a",
 "第2點：重大災害包括職安法第37條第2項之死亡、罹災三人以上、罹災一人以上需住院之職災；甲級災害為工作場所職災造成三人以上死亡、五人以上罹災（含失蹤）、經大眾傳播媒體廣為報導之火災爆炸有害氣體外洩等涉及勞工安全之災害；其他經認有必要者。",
 "Under the MOL directive, a 'Class A scale' occupational disaster is:",
 ["3+ deaths, 5+ victims (including missing), or widely reported fires, explosions or gas leaks involving worker safety","1+ deaths, 3+ victims (including minor injuries), or union-reported entanglement, electrocution or fall accidents","10+ deaths, 20+ victims (including missing), or prosecuted criminal cases concerning industrial safety at work","5+ injuries, 2+ hospitalised (including outpatients), or locally announced food poisoning clusters at the workplace"],
 "Point 2: reportable accidents under OSH Act 37(2) plus Class A disasters (3+ deaths, 5+ victims, widely reported fires/explosions/leaks)."),

(MA,"第4點",3,"重大災害-檢查",
 "勞動檢查機構接獲何種職業災害通報應儘速派員檢查？",
 ["死亡災害、肢體器官嚴重受損須住院連續二十四小時以上、氨氯氟化氫光氣硫化氫二氧化硫洩漏致一人以上住院、罹災人數三人以上","輕傷災害、皮膚表面輕微擦傷須門診連續四十八小時以上、汽油柴油甲苯二甲苯乙酸乙酯溢漏致二人以上休息、罹災人數十人以上","財損災害、機械設備嚴重毀壞須停工連續七十二小時以上、氧氣氮氣氬氣氦氣二氧化碳外洩致一人以上不適、罹災人數五人以上","虛驚事故、勞工受驚嚇須休養連續十二小時以上、粉塵噪音輻射高溫低溫振動等超標致三人以上請假、罹災人數二人以上"],"a",
 "第4點：發生死亡災害；罹災者肢體或器官嚴重受損危及生命或身體機能嚴重喪失且須住院治療連續達二十四小時以上；氨氯氟化氫光氣硫化氫二氧化硫等洩漏造成一人以上罹災勞工需住院；罹災人數三人以上。礦災空難海難震災輻射事故陸上交通事故及殺人刑事案件等他法已有機制者不在此限。",
 "Which accident reports require the inspection agency to dispatch inspectors promptly?",
 ["Deaths, severe limb/organ injuries needing 24+ hours of hospitalization, listed chemical leaks with 1+ hospitalized, and 3+ victims","Minor injuries, light skin abrasions needing 48+ hours of outpatient care, fuel or solvent spills with 2+ workers resting, and 10+ victims","Property damage, severe machinery damage needing 72+ hours of work stoppage, inert gas releases with 1+ feeling unwell, and 5+ victims","Near misses, frightened workers needing 12+ hours of rest at home, dust or noise limits exceeded with 3+ on sick leave, and 2+ victims"],
 "Point 4: the four categories; excluded where other laws cover mining, aviation, maritime, earthquake, radiation, road traffic or homicide investigations."),

(MA,"第5點",3,"重大災害-通報",
 "勞動檢查機構對事業單位之職業災害通報案件，應指派專人於幾日內於檢查資訊系統確認處理方式並輸入通報資料？",
 ["二日內","一日內","七日內","三十日內"],"a",
 "第5點：事業單位職災通報案件應指派專人於二日內於「勞動檢查機構檢查資訊管理系統」確認處理方式並輸入資料，屬職安法第37條第2項之職災應產出重大災害通報表傳真職安署及地方主管機關；媒體廣為報導之災害應填具即時處理情形表通報，結報時間災情單純不宜超過二天、複雜不超過三天；假日應再以電話通報。",
 "Inspection agencies must have a designated person confirm and enter accident reports in the inspection information system within:",
 ["2 days","1 day","7 days","30 days"],
 "Point 5: within 2 days, producing the major accident report form for reportable accidents; media-covered disasters get situation reports closed within 2–3 days; holiday accidents also phoned in."),

# ---------- 優良單位及人員選拔要點 ----------
(EX,"第3點",2,"優良單位-資格",
 "參選職業安全衛生優良單位，受選拔當年度及前幾年度工作場所不得發生重大災害？",
 ["前三年度","前一年度","前五年度","前十年度"],"a",
 "第3點：受選拔當年度及前三年度未發生重大災害通報要點第2點所稱之重大災害或失能程度一至九等級之職災；前三年度失能傷害頻率及嚴重率均低於同行業前三年平均值；前三年度未曾獲五星獎或國家職業安全衛生獎；前四年度未連續四年獲優良單位獎；應建置管理系統者已通過 TOSHMS 驗證或績效審查且有效。",
 "To be eligible as an outstanding OSH unit, no major accident may have occurred in the selection year and the preceding:",
 ["3 years","1 year","5 years","10 years"],
 "Point 3: no major accidents or grade 1–9 disability accidents in the current and previous 3 years; frequency and severity rates below the industry 3-year averages; no Five-Star or National OSH Award in the last 3 years; TOSHMS certification where required."),

(EX,"第8點",3,"優良單位-五星獎",
 "連續幾年榮獲優良獎，第幾年經決審為優良獎之事業單位，得參加五星獎評選？",
 ["連續二年，第三年","連續一年，第二年","連續三年，第四年","連續五年，第六年"],"a",
 "第8點：連續二年榮獲優良獎，第三年經決審為優良獎之事業單位，得於通知送達翌日起十日內檢具五星獎自評表及佐證資料參加五星獎評選。第10點：五星獎得主之災保行業別費率依規定調整，且得參選國家職業安全衛生獎；勞檢機構自獲獎翌年起二年內得以監督指導代替一般例行檢查。",
 "Enterprises that win the Outstanding Award for how many consecutive years and again in which year may compete for the Five-Star Award?",
 ["2 consecutive years, then the 3rd year","1 consecutive year, then the 2nd year","3 consecutive years, then the 4th year","5 consecutive years, then the 6th year"],
 "Point 8: two consecutive years plus a third-year award; Point 10: Five-Star winners get insurance rate adjustments, National OSH Award eligibility, and two years of supervision in lieu of routine inspection."),

(EX,"第11點",3,"優良單位-時程",
 "優良單位及人員之選拔，原則上於何時接受推薦或自薦？何時完成決審？",
 ["次年二月起；五月","次年一月起；三月","次年六月起；九月","次年十月起；十二月"],"a",
 "第11點：於次年二月起接受推薦或自薦，四月中旬完成初審，五月完成決審為原則；獲選者經查證與事實不符或填報不實者得撤銷得獎資格並追回獎勵。第7點：初審由當地勞工主管機關、科學園區管理局、產業園區管理局等辦理，決審由職安署組設小組決定。",
 "Nominations for outstanding OSH units and personnel open when, and final review is completed by when?",
 ["From February of the following year; May","From January of the following year; March","From June of the following year; September","From October of the following year; December"],
 "Point 11: nominations from February, preliminary review by mid-April, final review in May; awards may be revoked for false information."),
]
