# -*- coding: utf-8 -*-
# 第 12 批（C3）：乾洗作業空氣污染防制設施管制標準（ENV-124）、
#                 移動污染源空氣污染物排放標準（ENV-126）、
#                 移動污染源違反空氣污染防制法裁罰準則（ENV-127）、
#                 移動污染源燃料成分管制標準（ENV-128）、
#                 煉鋼及鑄造電爐粒狀污染物管制及排放標準（ENV-134）
# ※ 四個選項刻意寫成相近長度。
L1 = "ENV-124"
L2 = "ENV-126"
L3 = "ENV-127"
L4 = "ENV-128"
L5 = "ENV-134"
Q = [

# ===== ENV-124 乾洗作業空氣污染防制設施管制標準 =====
(L1,"第1條",1,"乾洗標準-法源",
 "乾洗作業空氣污染防制設施管制標準之訂定法源依據為何？",
 ["依空氣污染防制法第二十三條第二項規定訂定之","依空氣污染防制法第二十條第二項規定訂定之","依空氣污染防制法第三十一條第一項規定訂定","依水污染防治法第十八條第二項規定訂定之"],"a",
 "第1條：本標準依空氣污染防制法第二十三條第二項規定訂定之。第11條規定本標準自發布日起施行；第10條並定有既設業者自八十九年七月一日起符合本標準之緩衝期。",
 "What is the legal basis for the Control Standards for Air Pollution Control Facilities of Dry Cleaning Operations?",
 ["Adopted under Article 23, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 20, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 31, Paragraph 1 of the Air Pollution Control Act","Adopted under Article 18, Paragraph 2 of the Water Pollution Control Act"],
 "Article 1; see also Articles 10 and 11."),


(L1,"第2條",3,"乾洗標準-回收率公式",
 "乾洗溶劑重量回收率R及排放削減率E之計算公式為何？",
 ["R＝Wr／（W0－W）×100％；E＝（M0－M）／M×100％，M0及M分別為破壞性處理前後之質量流率","R＝（W0－W）／Wr×100％；E＝（M－M0）／M0×100％，M0及M分別為破壞性處理前後之質量流率","R＝Wr／W0×100％；E＝（M0－M）／M0×100％，M0及M分別為冷凝回收前後之乾洗溶劑質量流率","R＝W／（W0－Wr）×100％；E＝M0／（M0－M）×100％，M0及M分別為烘乾前後之乾洗衣物重量比"],"a",
 "第2條第9款、第10款：乾洗溶劑重量回收率 R＝Wr／（W0－W）×100％，W0為烘乾作業前衣物重量、W為烘乾後衣物重量、Wr為回收乾洗溶劑重量；排放削減率 E＝（M0－M）／M×100％，M0、M分別為破壞性處理前、後廢氣中乾洗溶劑之質量流率。",
 "What are the formulas for solvent weight recovery rate R and emission reduction rate E?",
 ["R = Wr / (W0 − W) × 100%; E = (M0 − M) / M × 100%, where M0 and M are mass flow rates before and after destructive treatment","R = (W0 − W) / Wr × 100%; E = (M − M0) / M0 × 100%, where M0 and M are mass flow rates before and after destructive treatment","R = Wr / W0 × 100%; E = (M0 − M) / M0 × 100%, where M0 and M are solvent mass flow rates before and after condensation recovery","R = W / (W0 − Wr) × 100%; E = M0 / (M0 − M) × 100%, where M0 and M are the clothing weights before and after the drying cycle"],
 "Article 2, Subparagraphs 9 and 10."),

(L1,"第3條",3,"乾洗標準-適用對象",
 "使用石油系乾洗溶劑者，於本標準發布前已設立時，其適用門檻為何？",
 ["同一場所所有石油系溶劑乾洗機總容量十八公斤以上，或石油系乾洗溶劑年使用量一千公升以上者","同一場所所有石油系溶劑乾洗機總容量三十公斤以上，或石油系乾洗溶劑年使用量五百公升以上者","同一場所所有石油系溶劑乾洗機總容量十公斤以上，或石油系乾洗溶劑年使用量二千公升以上者","同一場所所有石油系溶劑乾洗機總容量十八公斤以上，且石油系乾洗溶劑年使用量一萬公升以上者"],"a",
 "第3條第1項第1款第2目：本標準發布前已設立者，其同一公私場所所有石油系溶劑乾洗機總容量十八公斤以上（含十八公斤）或其石油系乾洗溶劑年使用量一千公升以上（含一千公升）者適用本標準；同款第3目並規定總容量未達十八公斤而因民眾陳情經主管機關認定有污染之虞者亦適用。同條第2項：實際容量與原廠標示容量不同時，以容量較大者為準。",
 "For petroleum solvent dry cleaners established before promulgation, what threshold makes the standards apply?",
 ["Total petroleum solvent machine capacity of 18 kilograms or more, or annual petroleum solvent use of 1000 litres or more","Total petroleum solvent machine capacity of 30 kilograms or more, or annual petroleum solvent use of 500 litres or more","Total petroleum solvent machine capacity of 10 kilograms or more, or annual petroleum solvent use of 2000 litres or more","Total petroleum solvent machine capacity of 18 kilograms or more, and annual petroleum solvent use of 10000 litres or more"],
 "Article 3."),

(L1,"第4條",3,"乾洗標準-石油系規定",
 "使用石油系乾洗溶劑從事乾洗作業者，其烘乾機回收率及溶劑洩漏之管制規定為何？",
 ["烘乾機乾洗溶劑重量回收率或削減率應達百分之八十五以上；任何單元不得有溶劑洩漏每分鐘三滴以上或目視可見蒸汽洩漏","烘乾機乾洗溶劑重量回收率或削減率應達百分之六十以上；任何單元不得有溶劑洩漏每分鐘十滴以上或目視可見蒸汽洩漏","烘乾機乾洗溶劑重量回收率或削減率應達百分之九十五以上；任何單元洩漏偵測濃度不得超過五十ppm並應立即停機","烘乾機乾洗溶劑重量回收率或削減率應達百分之七十五以上；任何單元不得有溶劑洩漏每小時三滴以上或蒸汽外洩情形"],"a",
 "第4條第3款、第6款：烘乾機之乾洗溶劑重量回收率或削減率應達百分之八十五以上；乾洗設備任何單元不得有乾洗溶劑洩漏每分鐘三滴以上或以目視可見溶劑蒸汽洩漏情事。同條第2款並規定溶劑脫除後烘乾前之堆置衣物及過濾殘渣應存放密封容器，曝露於空氣中時間不得超過五分鐘。",
 "For petroleum solvent dry cleaning, what recovery rate and leak limits apply?",
 ["Dryer solvent weight recovery or reduction must reach 85 percent or more; no unit may leak three or more drops per minute or show visible vapour","Dryer solvent weight recovery or reduction must reach 60 percent or more; no unit may leak ten or more drops per minute or show visible vapour","Dryer solvent weight recovery or reduction must reach 95 percent or more; no unit may show detected leak concentration over 50 ppm and must stop","Dryer solvent weight recovery or reduction must reach 75 percent or more; no unit may leak three or more drops per hour or let vapour escape"],
 "Article 4, Subparagraphs 2, 3 and 6."),


(L1,"第5條",3,"乾洗標準-委託代烘乾",
 "申請委託代烘乾作業之期限及委託受託家數限制為何？",
 ["應於乾洗溶劑回收設備設置期限屆滿之四個月前提出申請；委託對象以一家為限，受託家數不得超過三家","應於乾洗溶劑回收設備設置期限屆滿之六個月前提出申請；委託對象以三家為限，受託家數不得超過一家","應於乾洗溶劑回收設備設置期限屆滿之六十日前提出申請；委託對象不限家數，受託家數不得超過五家","應於主管機關指定日起六個月內提出申請；委託對象以二家為限，受託家數則由主管機關個案核定之"],"a",
 "第5條第1項：符合條件者得於乾洗溶劑回收設備設置期限屆滿之四個月前，檢具乾洗衣物烘乾委託計畫書及受託者之受託計畫書，向當地主管機關申請委託代烘乾作業，經審查核可者委託者得免設置回收烘乾機或尾氣處理設備。同條第2項第1款：委託對象應以一家為限；第3項第1款：受託之家數不得超過三家。",
 "What is the application deadline for contracted drying, and the limits on the number of parties?",
 ["Apply four months before the recovery equipment installation deadline expires; only one contractor may be used and a firm may accept at most three","Apply six months before the recovery equipment installation deadline expires; up to three contractors may be used and a firm may accept only one","Apply sixty days before the recovery equipment installation deadline expires; the number of contractors is unlimited and a firm may accept five","Apply within six months of the date designated by the authority; up to two contractors may be used and the authority decides acceptances"],
 "Article 5, Paragraphs 1 to 3."),

(L1,"第5條",3,"乾洗標準-代烘乾管理",
 "受託代烘乾者每日最大處理量之計算及主管機關核定作業時間之規定為何？",
 ["代烘乾最大量＝最大操作量－經常操作量；住宅區及商業區每日作業時間不得超過八小時，工業區則不限定時間","代烘乾最大量＝最大操作量＋經常操作量；住宅區及商業區每日作業時間不得超過十二小時，工業區不限時間","代烘乾最大量＝經常操作量－最大操作量；住宅區及商業區每日作業時間不得超過四小時，工業區不限時間","代烘乾最大量＝最大操作量×經常操作量；各分區每日作業時間一律不得超過八小時，不因分區而有差異"],"a",
 "第5條第3項第2款、第3款：代烘乾處理之最大量＝最大操作量－經常操作量；最大操作量＝烘乾機設計最大處理量×每小時最大烘乾批次×主管機關核定之每日作業時間；主管機關核定之每日作業時間，住宅區及商業區不得超過八小時，工業區不限定時間，其他區域由主管機關依實際需要核定。",
 "How is a contractor's maximum daily drying volume computed, and what daily hours are approved?",
 ["Max contracted volume = maximum operating volume minus routine operating volume; residential and commercial areas are capped at eight hours, industrial areas are not","Max contracted volume = maximum operating volume plus routine operating volume; residential and commercial areas are capped at twelve hours, industrial areas are not","Max contracted volume = routine operating volume minus maximum operating volume; residential and commercial areas are capped at four hours, industrial areas are not","Max contracted volume = maximum operating volume times routine operating volume; every zone is uniformly capped at eight hours a day without distinction"],
 "Article 5, Paragraph 3, Subparagraphs 2 and 3."),


(L1,"第6條",3,"乾洗標準-計畫書內容",
 "乾洗衣物烘乾委託計畫書應包括之內容，下列何者正確？",
 ["委託者名稱地址負責人資料、乾洗機總容量及過去一年平均每月乾洗衣物量、使用溶劑種類及過去三年平均每年用量、委託運送方式及合約書","委託者名稱地址負責人資料、乾洗機每批次處理量及過去三個月營業額、使用溶劑之購買發票影本、委託運送車輛之行車紀錄器影像紀錄","受託者名稱地址負責人資料、受託烘乾衣物每日最大量、現行及未來乾洗作業方式說明、烘乾作業操作條件之記錄方式及切結書資料","委託者及受託者之工廠登記證明、空氣污染防制費繳納證明、乾洗溶劑之物質安全資料表、以及最近一年之排放檢測報告書內容"],"a",
 "第6條第1項：委託計畫書內容應包括委託者公司行號名稱、地址及乾洗作業場所地址、負責人姓名及身分證字號；乾洗機總容量及過去一年平均每月乾洗衣物量、使用乾洗溶劑種類及過去三年平均每年用量；每日及每月委託烘乾衣物最大量、儲放與運送方式及路線、簽收方式、委託時間、委託合約書及切結書等。同條第2項另定受託計畫書之內容。",
 "Which correctly states what the drying entrustment plan must contain?",
 ["Client's name, address and responsible person; total machine capacity and last year's monthly average volume; solvent types and three-year average annual use; transport and contract","Client's name, address and responsible person; per-batch capacity and the last three months' turnover; copies of solvent purchase invoices; dashcam footage of the transport vehicles","Contractor's name, address and responsible person; maximum daily volume accepted; description of current and future dry cleaning practices; recording methods and affidavit","Factory registration of both parties; proof of air pollution control fee payment; safety data sheets of the dry cleaning solvent; and the past year's emission testing report"],
 "Article 6, Paragraph 1."),

(L1,"第7條",3,"乾洗標準-四氯乙烯",
 "使用四氯乙烯及其他非石油系乾洗溶劑者，其冷凝回收設備出口溫度及乾洗槽開門濃度規定為何？",
 ["冷凝液出口管壁溫度應小於或等於攝氏七．二度；新設立設備乾洗槽溶劑濃度須處理至三百ppm以下始得開啟槽門","冷凝液出口管壁溫度應小於或等於攝氏二十七度；新設立設備乾洗槽溶劑濃度須處理至五十ppm以下始得開啟槽門","冷凝液出口管壁溫度應小於或等於攝氏零下七度；新設立設備乾洗槽溶劑濃度須處理至一千ppm以下始得開啟槽門","冷凝液出口管壁溫度應大於或等於攝氏七．二度；新設立設備乾洗槽溶劑濃度須處理至三十ppm以下始得開啟槽門"],"a",
 "第7條第2款、第3款：應設置冷凍式冷凝回收設備或功能較佳之設施，冷凝液出口應裝設溫度計，冷凝液出口管壁溫度應小於或等於攝氏七．二度；本標準發布後新設立之乾洗設備，乾洗槽中應設置乾洗溶劑濃度偵測器，槽中濃度須經可再生使用之碳槽或其他溶劑吸附器處理至三百ppm以下始得開啟槽門。",
 "For perchloroethylene dry cleaning, what condenser outlet temperature and door-opening concentration apply?",
 ["Condensate outlet pipe wall temperature at or below 7.2 degrees Celsius; new equipment must reduce drum concentration below 300 ppm before opening","Condensate outlet pipe wall temperature at or below 27 degrees Celsius; new equipment must reduce drum concentration below 50 ppm before opening the door","Condensate outlet pipe wall temperature at or below minus 7 degrees Celsius; new equipment must reduce drum concentration below 1000 ppm before opening","Condensate outlet pipe wall temperature at or above 7.2 degrees Celsius; new equipment must reduce drum concentration below 30 ppm before opening the door"],
 "Article 7, Subparagraphs 2 and 3."),

(L1,"第7條",3,"乾洗標準-洩漏偵測",
 "使用四氯乙烯之乾洗設備，其洩漏管制及自行偵測頻率規定為何？",
 ["任何單元不得有溶劑滴漏或偵測濃度超過五十ppm；每週至少一次自行偵測設備管線，超過時應即止漏並停止乾洗作業","任何單元不得有溶劑滴漏或偵測濃度超過三百ppm；每月至少一次自行偵測設備管線，超過時應於三日內完成修復作業","任何單元不得有每分鐘三滴以上之滴漏情形；每季至少一次委託檢測機構偵測管線，超過時應報請主管機關同意後停機","任何單元不得有溶劑滴漏或偵測濃度超過五百ppm；每年至少一次自行偵測設備管線，超過時應於次年改善並記錄備查"],"a",
 "第7條第5款、第6款：乾洗設備任何單元不得有溶劑滴漏或溶劑洩漏偵測濃度超過五十ppm之情事；每週應至少一次自行使用四氯乙烯濃度偵測器偵測其設備管線，偵測濃度超過五十ppm時應即時採行止漏修復措施並停止乾洗作業，所用偵測器最低濃度偵測極限至少應為五十ppm。同條第7款並要求各項紀錄至少保存二年備查。",
 "What leak limits and self-inspection frequency apply to perchloroethylene dry cleaning equipment?",
 ["No unit may drip or show detected concentration over 50 ppm; lines are self-checked at least weekly, and exceedance requires immediate repair and stopping work","No unit may drip or show detected concentration over 300 ppm; lines are self-checked at least monthly, and exceedance must be repaired within three days","No unit may drip three or more drops a minute; lines are checked at least quarterly by a testing firm, and exceedance requires approval before shutdown","No unit may drip or show detected concentration over 500 ppm; lines are self-checked at least yearly, and exceedance is improved the next year with records"],
 "Article 7, Subparagraphs 5 to 7."),

(L1,"第8條",1,"乾洗標準-儲存",
 "乾洗溶劑之儲存應符合何項規定？",
 ["應儲存於密閉之容器內，不得造成溶劑逸散或洩漏於空氣中","應儲存於通風良好之開放式容器內並定期補充溶劑至滿載","應儲存於冷藏設備中並維持攝氏七．二度以下之低溫狀態","應儲存於室外遮陽處並於容器上標明購買日期及使用期限"],"a",
 "第8條：乾洗溶劑應儲存於密閉之容器內，不得造成溶劑逸散或洩漏於空氣中。第4條第2款並要求溶劑脫除後烘乾前之堆置衣物及過濾殘渣應存放於密封容器內，曝露於空氣中之時間不得超過五分鐘。",
 "How must dry cleaning solvent be stored?",
 ["It must be kept in sealed containers so that no solvent escapes or leaks into the air","It must be kept in well-ventilated open containers and regularly topped up to full","It must be kept refrigerated and maintained below 7.2 degrees Celsius at all times","It must be kept outdoors in shade with purchase date and expiry marked on the drum"],
 "Article 8; see also Article 4, Subparagraph 2."),

(L1,"第9條",3,"乾洗標準-回收率測試",
 "石油系乾洗溶劑冷凝回收設備之回收率測試，其測試衣物重量及測試次數規定為何？",
 ["測試衣物重量需為烘乾設備設計容量之百分之八十至九十，且至少測試三次以上，測試數據平均標準差須小於百分之三","測試衣物重量需為烘乾設備設計容量之百分之五十至六十，且至少測試五次以上，測試數據平均標準差須小於百分之十","測試衣物重量需為烘乾設備設計容量之百分之百，且至少測試二次以上，測試數據之平均標準差須小於百分之十五","測試衣物重量需為烘乾設備設計容量之百分之三十至四十，且至少測試一次即可，並免計算測試數據之平均標準差"],"a",
 "第9條附件第5點：測試衣物重量需為烘乾設備設計容量之百分之八十至百分之九十，且於同一烘乾設備相同操作條件下至少測試三次以上，其測試數據之平均標準差須小於百分之三。附件並規定磅秤秤重範圍為零至七十五公斤、誤差小於二十公克以內且經國家標準認可，測試衣物為棉質實驗衣。",
 "In the recovery rate test for petroleum solvent condensers, what test load and repetitions are required?",
 ["Test clothing weight must be 80 to 90 percent of the dryer's design capacity, with at least three runs and mean standard deviation under 3 percent","Test clothing weight must be 50 to 60 percent of the dryer's design capacity, with at least five runs and mean standard deviation under 10 percent","Test clothing weight must be 100 percent of the dryer's design capacity, with at least two runs and mean standard deviation under 15 percent","Test clothing weight must be 30 to 40 percent of the dryer's design capacity, with only one run needed and no standard deviation required"],
 "Article 9 and its appendix."),

(L1,"第10條",2,"乾洗標準-緩衝期",
 "本標準發布前已設立之乾洗業者，以及因民眾陳情經認定有污染之虞者，應何時起符合本標準？",
 ["發布前已設立者應自八十九年七月一日起符合；經陳情認定有污染之虞者應於主管機關指定日起六個月內符合","發布前已設立者應自發布日起立即符合；經陳情認定有污染之虞者應於主管機關指定日起三個月內符合規定","發布前已設立者應自九十年一月一日起符合；經陳情認定有污染之虞者應於主管機關指定日起一年內符合","發布前已設立者應自八十九年七月一日起符合；經陳情認定有污染之虞者得免適用本標準之各項管制規定"],"a",
 "第10條：本標準發布前已設立從事乾洗作業者，應自八十九年七月一日起符合本標準規定；石油系乾洗機總容量未達十八公斤，因民眾陳情經主管機關認定有污染之虞者，應於主管機關指定日起六個月內符合本標準規定。",
 "When must pre-existing dry cleaners, and those found polluting after complaints, comply?",
 ["Those established before promulgation comply from 1 July 2000; those found polluting after complaints comply within six months of the designated date","Those established before promulgation comply from the promulgation date at once; those found polluting after complaints comply within three months","Those established before promulgation comply from 1 January 2001; those found polluting after complaints comply within one year of the designated date","Those established before promulgation comply from 1 July 2000; those found polluting after complaints are exempt from all controls in these standards"],
 "Article 10."),

(L1,"第11條",1,"乾洗標準-施行",
 "乾洗作業空氣污染防制設施管制標準之施行日期為何？",
 ["本標準自發布日起施行","本標準自八十九年七月一日起施行","本標準自發布後六個月起施行","本標準自發布後屆滿一年起施行"],"a",
 "第11條：本標準自發布日起施行。第10條另定既設乾洗業者應自八十九年七月一日起符合本標準規定之緩衝期間，兩者規範對象與意義不同。",
 "When do the Dry Cleaning Air Pollution Control Standards take effect?",
 ["They take effect on the date of promulgation","They take effect from 1 July 2000 onwards","They take effect six months after promulgation","They take effect one year after promulgation"],
 "Article 11; see also Article 10."),


# ===== ENV-126 移動污染源空氣污染物排放標準 =====
(L2,"第1條",1,"移動源排放-法源",
 "移動污染源空氣污染物排放標準之訂定法源依據為何？",
 ["依空氣污染防制法第三十六條第二項規定訂定之","依空氣污染防制法第三十七條第二項規定訂定之","依空氣污染防制法第三十九條第三項規定訂定","依空氣污染防制法第四十四條第一項規定訂定"],"a",
 "第1條：本標準依空氣污染防制法第三十六條第二項規定訂定之。第10條規定本標準除另定施行日期者外，自中華民國一百十二年七月一日施行；第9條規定本標準未規定之測定方法，由中央主管機關會商有關機關認定之。",
 "What is the legal basis for the Mobile Source Air Pollutant Emission Standards?",
 ["Adopted under Article 36, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 37, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 39, Paragraph 3 of the Air Pollution Control Act","Adopted under Article 44, Paragraph 1 of the Air Pollution Control Act"],
 "Article 1; see also Articles 9 and 10."),

(L2,"第2條",3,"移動源排放-測定定義",
 "本標準所稱行車型態測定、惰轉狀態測定及目測判定，其定義各為何？",
 ["行車型態測定以車體動力計模擬特定行車型態測排放重量；惰轉狀態測定為保持惰轉時測排放濃度；目測判定由訓練合格領證人員以目測判定粒狀污染物濃度","行車型態測定以實際道路行駛方式測排放濃度；惰轉狀態測定為引擎熄火後測殘留濃度；目測判定由主管機關人員以儀器量測粒狀污染物之排放重量與濃度","行車型態測定以底盤動力計測定燃料消耗量；惰轉狀態測定為引擎高轉速時測排放重量；目測判定由車主自行以目視方式判定黑煙之不透光率百分比數值","行車型態測定以引擎台架模擬負荷測排放量；惰轉狀態測定為冷車啟動時測排放濃度；目測判定由檢驗站以林格曼煙氣濃度表比對判定粒狀污染物之濃度"],"a",
 "第2條第1至3款：行車型態測定指以車體動力計模擬特定行車型態，測定車輛在該行車型態時排氣管排放空氣污染物之重量；惰轉狀態測定指車輛於保持惰轉狀態時測定所排放空氣污染物之濃度；目測判定指由經中央主管機關排煙目測判煙人員訓練合格、領有合格證書之人員，以目測方法判定交通工具所排放粒狀污染物之濃度。",
 "How are driving cycle testing, idle testing and visual determination defined?",
 ["Driving cycle testing measures pollutant weight on a chassis dynamometer; idle testing measures concentration while idling; visual determination is by certified trained smoke readers","Driving cycle testing measures concentration on real roads; idle testing measures residual concentration after shutdown; visual determination is by officials using instruments to measure weight","Driving cycle testing measures fuel consumption on a chassis dynamometer; idle testing measures weight at high engine speed; visual determination is by owners judging smoke opacity themselves","Driving cycle testing measures emissions on an engine bench under load; idle testing measures concentration at cold start; visual determination is by stations using a Ringelmann chart comparison"],
 "Article 2, Subparagraphs 1 to 3."),

(L2,"第2條",3,"移動源排放-檢驗定義",
 "本標準所稱新車型審驗、新車檢驗及使用中車輛檢驗，其定義及範圍為何？",
 ["新車型審驗為製造進口後銷售使用前之審查檢驗；新車檢驗為審驗合格後製造進口達規定數量或期間時之檢驗；使用中車輛檢驗包括定期檢驗及不定期檢驗","新車型審驗為出廠前之品質管制查核；新車檢驗為領牌時之首次排氣檢驗；使用中車輛檢驗僅指依本法第四十四條規定辦理之定期檢驗，不包括路邊攔查之檢驗","新車型審驗為每年例行之車型抽驗作業；新車檢驗為銷售後三個月內之複驗；使用中車輛檢驗僅指依本法第四十五條規定於停靠處所或行駛途中所為之不定期檢驗","新車型審驗為原型車之設計審查；新車檢驗為量產車出廠前之逐車檢驗；使用中車輛檢驗指車輛達一定車齡後由製造廠召回進行之排放性能檢測與改善作業"],"a",
 "第2條第4至6款：新車型審驗指各車型車輛於製造或進口後、銷售或使用前，對該車型空氣污染物排放情形所為之審查檢驗；新車檢驗指車輛經新車型審驗合格，於其製造或進口達規定之數量或期間時所為之檢驗；使用中車輛檢驗包括依本法第四十四條之定期檢驗及依第四十五條於停靠處所或行駛途中之不定期檢驗。",
 "How are new model certification, new vehicle testing and in-use vehicle testing defined?",
 ["New model certification reviews a model after making or import and before sale; new vehicle testing applies once set volumes or periods are reached; in-use testing covers periodic and non-periodic tests","New model certification is a pre-shipment quality check; new vehicle testing is the first emission test at registration; in-use testing means only periodic tests under Article 44, not roadside checks","New model certification is a routine annual sampling of models; new vehicle testing is a re-test within three months of sale; in-use testing means only roadside or parking-lot tests under Article 45","New model certification reviews prototype design; new vehicle testing checks every mass-produced unit before shipment; in-use testing means recall-based performance testing after a certain vehicle age"],
 "Article 2, Subparagraphs 4 to 6."),

(L2,"第2條",3,"移動源排放-參考車重",
 "本標準所稱參考車重，其計算方式為何？特定之重量各為多少？",
 ["汽車空車重量加特定重量；以FTP-75測試型態者為一百三十六公斤，以NEDC或WLTC者為一百公斤","汽車空車重量加特定重量；以FTP-75測試型態者為一百公斤，以NEDC或WLTC者為一百三十六公斤","汽車總重量減特定重量；以FTP-75測試型態者為一百三十六公斤，以NEDC或WLTC者為二百公斤","汽車空車重量加乘客重量；以FTP-75測試型態者為五十四公斤，以NEDC或WLTC者為六十八公斤"],"a",
 "第2條第10款：參考車重指汽車空車重量加特定之重量；空車重量指未裝載人貨、引擎內有規定潤滑油、水箱有冷卻水、燃料箱有規定燃料並帶有原廠規定配件之重量；特定之重量，以FTP-75者為一百三十六公斤，以NEDC或WLTC者為一百公斤。",
 "How is reference vehicle weight calculated, and what are the specified add-on weights?",
 ["Curb weight plus a specified weight; 136 kilograms for the FTP-75 test cycle and 100 kilograms for NEDC or WLTC","Curb weight plus a specified weight; 100 kilograms for the FTP-75 test cycle and 136 kilograms for NEDC or WLTC","Gross weight minus a specified weight; 136 kilograms for the FTP-75 test cycle and 200 kilograms for NEDC or WLTC","Curb weight plus passenger weight; 54 kilograms for the FTP-75 test cycle and 68 kilograms for NEDC or WLTC"],
 "Article 2, Subparagraph 10."),

(L2,"第2條",2,"移動源排放-替代清潔燃料",
 "本標準所稱替代清潔燃料，包括下列何者？",
 ["新配方汽油、新配方柴油、天然氣、液化石油氣、氫氣、甲醇、乙醇及其他混合百分之八十五以上醇類之燃料","新配方汽油、新配方柴油、天然氣、液化石油氣、重油、煤油及其他混合百分之五十以上醇類之燃料","一般車用汽油、超級柴油、天然氣、液化石油氣、氫氣、甲醇及其他混合百分之三以上醇類之燃料","新配方汽油、生質柴油、船舶燃油、航空燃油、氫氣、乙醇及其他混合百分之二十以上醇類之燃料"],"a",
 "第2條第12款：替代清潔燃料指新配方汽油、新配方柴油、天然氣、液化石油氣、氫氣、甲醇、乙醇及其他混合百分之八十五以上醇類之燃料。第3條、第5條並分別就汽油及替代清潔燃料引擎汽車、柴油及替代清潔燃料引擎汽車訂有排放標準。",
 "What counts as alternative clean fuel under these standards?",
 ["Reformulated gasoline and diesel, natural gas, LPG, hydrogen, methanol, ethanol and other fuels blended with 85 percent or more alcohol","Reformulated gasoline and diesel, natural gas, LPG, heavy oil, kerosene and other fuels blended with 50 percent or more alcohol","Ordinary motor gasoline, super diesel, natural gas, LPG, hydrogen, methanol and other fuels blended with 3 percent or more alcohol","Reformulated gasoline, biodiesel, marine fuel oil, aviation fuel, hydrogen, ethanol and other fuels blended with 20 percent or more alcohol"],
 "Article 2, Subparagraph 12."),


(L2,"第3條",2,"移動源排放-汽油車",
 "汽油及替代清潔燃料引擎汽車排氣管排放標準，管制哪些污染物？以何種方式測定？",
 ["管制CO、HC、NOx、粒狀污染物及粒狀污染物數量，分行車型態測定與惰轉狀態測定二種方式","管制CO、HC、NOx、二氧化硫及戴奧辛，分行車型態測定與目測判定二種方式分別訂定其標準","管制CO、HC、NOx、甲醛及黑煙，分惰轉狀態測定與儀器測定二種方式分別訂定其排放標準","管制CO、NOx、鉛化合物及揮發性有機物，僅以行車型態測定一種方式訂定其排氣管排放標準"],"a",
 "第3條：汽油及替代清潔燃料引擎汽車排氣管排放一氧化碳（CO）、碳氫化合物（HC）、氮氧化物（NOx）、粒狀污染物（PM）及粒狀污染物數量（PN）之標準，分行車型態測定與惰轉狀態測定規定之。第4條另就曲軸箱、油箱及化油器排放碳氫化合物訂有標準。",
 "Which pollutants does the tailpipe standard for gasoline and alternative clean fuel cars cover, and how are they tested?",
 ["CO, HC, NOx, particulate matter and particle number, tested both by driving cycle testing and by idle testing","CO, HC, NOx, sulphur dioxide and dioxins, with standards set both by driving cycle testing and by visual determination","CO, HC, NOx, formaldehyde and black smoke, with standards set both by idle testing and by instrument measurement","CO, NOx, lead compounds and volatile organics, with standards set only by driving cycle testing of the tailpipe"],
 "Article 3; see also Article 4."),

(L2,"第4條",2,"移動源排放-蒸發排放",
 "汽油及替代清潔燃料引擎汽車之曲軸箱、油箱及化油器，本標準管制何種污染物？",
 ["管制碳氫化合物（HC）之排放，另以表定標準規範","管制一氧化碳（CO）之排放，另以表定標準規範","管制氮氧化物（NOx）之排放，另以表定標準規範","管制粒狀污染物（PM）之排放，另以表定標準規範"],"a",
 "第4條：汽油及替代清潔燃料引擎汽車曲軸箱、油箱及化油器排放碳氫化合物（HC）之標準，另以表定之。第7條並就機車曲軸箱、油箱及燃油供給系統排放碳氫化合物訂有標準。",
 "Which pollutant is controlled from the crankcase, fuel tank and carburettor of gasoline cars?",
 ["Hydrocarbons (HC), with limits set out in the accompanying table","Carbon monoxide (CO), with limits set out in the accompanying table","Nitrogen oxides (NOx), with limits set out in the accompanying table","Particulate matter (PM), with limits set out in the accompanying table"],
 "Article 4; see also Article 7."),

(L2,"第5條",3,"移動源排放-柴油車",
 "柴油及替代清潔燃料引擎汽車排氣管排放標準，管制之污染物及測定方式為何？",
 ["管制CO、HC、NMHC、NOx、甲醛、粒狀污染物、粒狀污染物數量與黑煙，分行車型態測定、目測判定及儀器測定","管制CO、HC、NOx與黑煙四項污染物，僅分行車型態測定及惰轉狀態測定二種方式訂定其排放標準","管制CO、HC、NOx、甲醛及二氧化硫，分惰轉狀態測定、目測判定及儀器測定三種方式訂定標準","管制黑煙與粒狀污染物二項，僅以目測判定一種方式訂定標準，其餘氣態污染物則不予管制之"],"a",
 "第5條：柴油及替代清潔燃料引擎汽車排氣管排放一氧化碳、碳氫化合物、非甲烷碳氫化合物、氮氧化物、甲醛、粒狀污染物、粒狀污染物數量與黑煙之標準，分行車型態測定、目測判定及儀器測定規定之。第2條第3款並定義目測判定須由訓練合格領證人員為之。",
 "Which pollutants and test methods apply to the tailpipe standard for diesel and alternative clean fuel cars?",
 ["CO, HC, NMHC, NOx, formaldehyde, PM, particle number and black smoke, by driving cycle testing, visual determination and instrument measurement","CO, HC, NOx and black smoke only, with standards set by driving cycle testing and by idle testing as the two applicable methods","CO, HC, NOx, formaldehyde and sulphur dioxide, with standards set by idle testing, visual determination and instrument measurement","Only black smoke and particulate matter, with standards set solely by visual determination, other gaseous pollutants being uncontrolled"],
 "Article 5; see also Article 2, Subparagraph 3."),

(L2,"第6條",2,"移動源排放-機車",
 "機車排氣管排放標準所管制之污染物及測定方式為何？",
 ["管制CO、HC、NOx與粒狀污染物，分行車型態測定、惰轉狀態測定、目測判定及儀器測定","管制CO、HC、NOx與黑煙，僅分行車型態測定及惰轉狀態測定二種方式訂定排放標準","管制CO、HC、甲醛與粒狀污染物數量，僅分目測判定及儀器測定二種方式訂定其標準","管制CO與HC二項污染物，僅以惰轉狀態測定一種方式訂定標準，其餘污染物均不管制"],"a",
 "第6條：機車排氣管排放一氧化碳（CO）、碳氫化合物（HC）、氮氧化物（NOx）與粒狀污染物（PM）之標準，分行車型態測定、惰轉狀態測定、目測判定及儀器測定規定之。第7條另就機車曲軸箱、油箱及燃油供給系統排放碳氫化合物訂有標準。",
 "Which pollutants and test methods apply to motorcycle tailpipe emission standards?",
 ["CO, HC, NOx and particulate matter, by driving cycle testing, idle testing, visual determination and instrument measurement","CO, HC, NOx and black smoke, with standards set only by driving cycle testing and idle testing as the two methods","CO, HC, formaldehyde and particle number, with standards set only by visual determination and instrument measurement","Only CO and HC, with standards set solely by idle testing, all other pollutants being left outside the controls"],
 "Article 6; see also Article 7."),

(L2,"第7條",1,"移動源排放-機車蒸發",
 "機車之曲軸箱、油箱及燃油供給系統，本標準管制何種污染物之排放？",
 ["管制碳氫化合物（HC）之排放並以表定標準規範","管制氮氧化物（NOx）之排放並以表定標準規範","管制一氧化碳（CO）之排放並以表定標準規範","管制粒狀污染物數量（PN）並以表定標準規範"],"a",
 "第7條：機車曲軸箱、油箱及燃油供給系統排放碳氫化合物（HC）之標準，另以表定之。第4條並就汽油及替代清潔燃料引擎汽車之曲軸箱、油箱及化油器排放碳氫化合物訂有相同性質之管制。",
 "Which pollutant is controlled from a motorcycle's crankcase, fuel tank and fuel supply system?",
 ["Hydrocarbons (HC), with limits prescribed in the accompanying table","Nitrogen oxides (NOx), with limits prescribed in the accompanying table","Carbon monoxide (CO), with limits prescribed in the accompanying table","Particle number (PN), with the limits prescribed in the accompanying table"],
 "Article 7; see also Article 4."),

(L2,"第8條",2,"移動源排放-火車船舶",
 "本標準對火車及船舶之排放，分別管制哪些空氣污染物？",
 ["火車管制CO、HC、NOx及粒狀污染物；船舶則管制粒狀污染物之排放標準","火車管制粒狀污染物及黑煙；船舶則管制CO、HC、NOx及硫氧化物排放","火車與船舶均管制CO、HC、NOx、粒狀污染物及粒狀污染物數量等五項","火車管制黑煙不透光率；船舶則管制甲醛及非甲烷碳氫化合物之排放量"],"a",
 "第8條：火車排放一氧化碳（CO）、碳氫化合物（HC）、氮氧化物（NOx）及粒狀污染物（PM）之標準，及船舶排放粒狀污染物之標準，另以表定之。第2條第12款所定替代清潔燃料及第9條之測定方法認定規定，亦與各類移動污染源之管制相關。",
 "Which pollutants are controlled for trains and for vessels under these standards?",
 ["Trains are controlled for CO, HC, NOx and particulate matter; vessels are controlled for particulate matter","Trains are controlled for particulate matter and black smoke; vessels are controlled for CO, HC, NOx and SOx","Both trains and vessels are controlled for CO, HC, NOx, particulate matter and particle number alike","Trains are controlled for black smoke opacity; vessels are controlled for formaldehyde and non-methane HC"],
 "Article 8."),

(L2,"第9條",1,"移動源排放-測定方法",
 "本標準未規定之測定方法，應如何處理？",
 ["由中央主管機關會商有關機關認定之","由各車輛製造廠依國際慣例自行認定","由直轄市、縣（市）主管機關逕行認定","由交通部公路主管機關公告後適用之"],"a",
 "第9條：本標準未規定之測定方法，由中央主管機關會商有關機關認定之。第2條第1至3款並就行車型態測定、惰轉狀態測定及目測判定分別定義，作為各條排放標準之測定基礎。",
 "How are test methods not prescribed in these standards handled?",
 ["They are determined by the central authority in consultation with relevant agencies","They are determined by each vehicle manufacturer following international practice","They are determined directly by the municipal or county competent authorities","They apply after being announced by the highway authority of the transport ministry"],
 "Article 9; see also Article 2."),

(L2,"第10條",1,"移動源排放-施行",
 "移動污染源空氣污染物排放標準之施行日期規定為何？",
 ["本標準除另定施行日期者外，自中華民國一百十二年七月一日施行","本標準除另定施行日期者外，自中華民國一百零九年七月一日施行","本標準一律自發布日施行，各條所定施行日期不影響其效力","本標準除另定施行日期者外，自中華民國一百十三年一月一日施行"],"a",
 "第10條：本標準除另定施行日期者外，自中華民國一百十二年七月一日施行。本標準修正日期為一百十二年六月三十日，各類車輛之排放標準另於第3條至第8條之附表中訂有分階段適用之施行日期。",
 "When do the Mobile Source Air Pollutant Emission Standards take effect?",
 ["Unless another date is set, they take effect on 1 July 2023","Unless another date is set, they take effect on 1 July 2020","They uniformly take effect on the promulgation date regardless","Unless another date is set, they take effect on 1 January 2024"],
 "Article 10."),

# ===== ENV-127 移動污染源違反空氣污染防制法裁罰準則 =====
(L3,"第1條",1,"移動源裁罰-法源",
 "移動污染源違反空氣污染防制法裁罰準則之訂定法源依據為何？",
 ["依空氣污染防制法第八十五條第二項規定訂定之","依空氣污染防制法第三十六條第二項規定訂定之","依行政罰法第十八條第三項規定授權訂定之標準","依空氣污染防制法第四十五條第三項規定訂定"],"a",
 "第1條：本準則依空氣污染防制法第八十五條第二項規定訂定之。第2條規定裁量罰鍰額度除依附表一及附表二辦理外，並應審酌違反本法上義務行為應受責難程度、所生影響，並得考量受處罰者之資力；第5條規定本準則自發布日施行。",
 "What is the legal basis for the Penalty Standards for Mobile Sources Violating the Air Pollution Control Act?",
 ["Adopted under Article 85, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 36, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 18, Paragraph 3 of the Administrative Penalty Act","Adopted under Article 45, Paragraph 3 of the Air Pollution Control Act"],
 "Article 1; see also Articles 2 and 5."),

(L3,"第2條",3,"移動源裁罰-裁量原則",
 "主管機關對違反本法之移動污染源裁量罰鍰額度時，除依附表規定外，尚應審酌哪些事項？",
 ["應審酌違反本法上義務行為應受責難程度、所生影響，並得考量受處罰者之資力","應審酌違規車輛之車齡、行駛里程數，並得考量該車輛之市場殘餘價值","應審酌受處罰者之前科紀錄與職業，並得考量其戶籍所在地之空氣品質","應審酌檢舉人所提供事證之完整程度，並得考量該地區之交通流量狀況"],"a",
 "第2條第1項：主管機關對違反本法之行為，其裁量罰鍰額度除依附表一及附表二規定辦理外，並應審酌違反本法上義務行為應受責難程度、所生影響，並得考量受處罰者之資力。同條第2項並定有罰鍰額度計算公式。",
 "Besides the tables, what must the authority weigh when setting fines on mobile source violations?",
 ["The blameworthiness of the breach of duty and its effects, and it may consider the offender's financial capacity","The age and mileage of the offending vehicle, and it may consider the vehicle's remaining market value","The offender's prior record and occupation, and it may consider the air quality of the offender's domicile","The completeness of the evidence provided by the informant, and it may consider local traffic volumes"],
 "Article 2, Paragraph 1."),

(L3,"第2條",3,"移動源裁罰-計算公式",
 "移動污染源違規罰鍰額度之計算公式及各符號意義為何？",
 ["罰鍰額度＝A×B×（1＋C）×罰鍰下限；A為移動污染源類型、B為違規情節、C為得加重或減輕裁罰事項","罰鍰額度＝A＋B＋（1－C）×罰鍰上限；A為移動污染源類型、B為違規情節、C為得加重或減輕裁罰事項","罰鍰額度＝A×B÷（1＋C）×罰鍰上限；A為違規次數、B為污染物濃度倍數、C為受處罰者之資力狀況","罰鍰額度＝（A＋B）×C×罰鍰下限；A為車齡年數、B為行駛里程、C為主管機關裁量之加減比例值"],"a",
 "第2條第2項、第3項：罰鍰額度＝A×B×（1＋C）×罰鍰下限；A指移動污染源類型，B指違規情節，C指得加重或減輕裁罰事項，屬加重者C為正值、屬減輕者C為負值。同條第4項：罰鍰額度之計算取至新臺幣元，小數點後無條件捨去。",
 "What is the formula for calculating fines on mobile source violations and what do its symbols mean?",
 ["Fine = A × B × (1 + C) × the statutory minimum; A is the mobile source type, B is the circumstances, C is the aggravating or mitigating factor","Fine = A + B + (1 − C) × the statutory maximum; A is the mobile source type, B is the circumstances, C is the aggravating or mitigating factor","Fine = A × B ÷ (1 + C) × the statutory maximum; A is the number of offences, B is the concentration multiple, C is the offender's financial capacity","Fine = (A + B) × C × the statutory minimum; A is the vehicle age in years, B is the mileage, C is the discretionary adjustment ratio of the authority"],
 "Article 2, Paragraphs 2 to 4."),


(L3,"第3條",2,"移動源裁罰-上下限",
 "依本準則計算之應處罰鍰額度逾法定上限或低於法定下限者，應如何裁處？",
 ["逾法定罰鍰額度上限者以該上限裁處；低於法定罰鍰額度下限者以該下限裁處","逾法定罰鍰額度上限者仍依計算結果裁處；低於下限者則免予裁處罰鍰","逾法定罰鍰額度上限者以上限之二倍裁處；低於下限者以下限之半數裁處","逾法定罰鍰額度上限者應報請中央主管機關核定；低於下限者改處以警告"],"a",
 "第3條：依前條規定計算應處罰鍰額度逾法定罰鍰額度上限者，以該法定罰鍰額度上限裁處之；低於該法定罰鍰額度下限者，以該法定罰鍰額度下限裁處之。第2條之計算公式即以罰鍰下限為基數乘算。",
 "How is a fine imposed when the computed amount exceeds the statutory maximum or falls below the minimum?",
 ["If it exceeds the statutory maximum the maximum is imposed; if it falls below the minimum the minimum is imposed","If it exceeds the statutory maximum the computed amount still stands; if below the minimum no fine is imposed","If it exceeds the statutory maximum twice that maximum is imposed; if below the minimum half the minimum applies","If it exceeds the statutory maximum central approval is required; if below the minimum a warning is issued instead"],
 "Article 3; see also Article 2."),

(L3,"第4條",1,"移動源裁罰-汽車類型",
 "本準則所稱汽車之類型，依何項規定認定？",
 ["依道路交通安全規則之規定認定","依空氣污染防制法施行細則規定認定","依移動污染源空氣污染物排放標準規定","依中央主管機關逐年公告之分類認定"],"a",
 "第4條：本準則汽車之類型，依道路交通安全規則之規定。第2條第3項第1款所定之A即指移動污染源類型，為罰鍰額度計算公式之重要參數之一。",
 "By what rules are vehicle types determined under these Penalty Standards?",
 ["They follow the Road Traffic Safety Rules","They follow the Enforcement Rules of the Act","They follow the Mobile Source Emission Standards","They follow annual classifications announced centrally"],
 "Article 4; see also Article 2."),

(L3,"第5條",1,"移動源裁罰-施行",
 "移動污染源違反空氣污染防制法裁罰準則之施行日期為何？",
 ["本準則自發布日施行","本準則自發布後三個月施行","本準則自次年一月一日施行","本準則自發布後一年施行之"],"a",
 "第5條：本準則自發布日施行。第2條並規定裁量罰鍰額度應依附表一及附表二辦理，並審酌應受責難程度、所生影響及受處罰者之資力。",
 "When do these Penalty Standards take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect on 1 January of the next year","They take effect one year after promulgation"],
 "Article 5; see also Article 2."),

# ===== ENV-128 移動污染源燃料成分管制標準 =====
(L4,"第1條",1,"燃料成分-法源",
 "移動污染源燃料成分管制標準之訂定法源依據為何？",
 ["依空氣污染防制法第三十九條第三項規定訂定之","依空氣污染防制法第三十六條第二項規定訂定之","依石油管理法第二十四條第二項規定訂定之標準","依空氣污染防制法第三十七條第二項規定訂定"],"a",
 "第1條：本標準依空氣污染防制法第三十九條第三項規定訂定之。第7條規定本標準除另定施行日期者外，自發布日施行；第3條至第6條分別就汽油、柴油、船舶燃油及航空燃油訂有成分管制標準。",
 "What is the legal basis for the Control Standards for Mobile Source Fuel Composition?",
 ["Adopted under Article 39, Paragraph 3 of the Air Pollution Control Act","Adopted under Article 36, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 24, Paragraph 2 of the Petroleum Administration Act","Adopted under Article 37, Paragraph 2 of the Air Pollution Control Act"],
 "Article 1; see also Articles 3 to 7."),

(L4,"第2條",3,"燃料成分-汽柴油成分",
 "本標準所稱汽油成分及柴油成分，各包括哪些項目？",
 ["汽油成分包括苯含量、芳香烴含量、烯烴含量、硫含量、氧含量及蒸氣壓；柴油成分包括硫含量、多環芳香烴含量及十六烷指數","汽油成分包括硫含量、多環芳香烴含量及十六烷指數；柴油成分包括苯含量、芳香烴含量、烯烴含量、氧含量及蒸氣壓","汽油成分包括苯含量、鉛含量、錳含量及辛烷值；柴油成分包括硫含量、氧含量、蒸氣壓及脂肪酸甲酯之摻配比例","汽油成分包括硫含量、氧含量及蒸氣壓三項；柴油成分包括硫含量、閃火點、傾點及黏度等物理化學性質項目"],"a",
 "第2條第1款、第2款：汽油成分指汽油之物理及化學性質足以影響汽油引擎移動污染源污染排放者，包括苯含量、芳香烴含量、烯烴含量、硫含量、氧含量及蒸氣壓；柴油成分包括硫含量、多環芳香烴含量及十六烷指數。",
 "What items are included in gasoline composition and in diesel composition?",
 ["Gasoline covers benzene, aromatics, olefins, sulphur, oxygen content and vapour pressure; diesel covers sulphur, polycyclic aromatics and cetane index","Gasoline covers sulphur, polycyclic aromatics and cetane index; diesel covers benzene, aromatics, olefins, oxygen content and vapour pressure","Gasoline covers benzene, lead, manganese and octane number; diesel covers sulphur, oxygen, vapour pressure and the blending ratio of fatty acid methyl esters","Gasoline covers only sulphur, oxygen content and vapour pressure; diesel covers sulphur, flash point, pour point and viscosity as physical properties"],
 "Article 2, Subparagraphs 1 and 2."),


(L4,"第2條",3,"燃料成分-十六烷指數",
 "本標準所稱十六烷指數及多環芳香烴含量，其定義為何？",
 ["十六烷指數為柴油著火性能表示方法，由密度及蒸餾溫度計算而得；多環芳香烴含量指柴油中除單環芳香烴以外之總芳香烴含量","十六烷指數為汽油抗爆震性能表示方法，由辛烷值換算而得；多環芳香烴含量指汽油中含苯、甲苯及二甲苯等之總量數值","十六烷指數為柴油揮發度表示方法，由蒸氣壓及黏度計算而得；多環芳香烴含量指柴油中單環芳香烴與烯烴含量之總和數值","十六烷指數為柴油含硫量表示方法，由硫含量及密度換算取得；多環芳香烴含量指柴油摻配之脂肪酸甲酯總量之重量百分比"],"a",
 "第2條第9款、第10款：十六烷指數指柴油著火性能表示方法之一種，由密度及蒸餾溫度計算而得，計算方法依中華民國國家標準（CNS）12016號或12761號規定；多環芳香烴含量指柴油中除單環芳香烴以外之總芳香烴含量。",
 "How are cetane index and polycyclic aromatic content defined?",
 ["Cetane index expresses diesel ignition quality and is computed from density and distillation temperature; polycyclic aromatics are total aromatics other than mono-aromatics","Cetane index expresses gasoline anti-knock quality and is converted from octane number; polycyclic aromatics are the total of benzene, toluene and xylene in gasoline","Cetane index expresses diesel volatility and is computed from vapour pressure and viscosity; polycyclic aromatics are the sum of mono-aromatics and olefins in diesel","Cetane index expresses diesel sulphur level and is converted from sulphur and density; polycyclic aromatics are the weight percentage of blended fatty acid methyl esters"],
 "Article 2, Subparagraphs 9 and 10."),

(L4,"第2條",2,"燃料成分-酒精汽油生質柴油",
 "本標準所稱酒精汽油、生質柴油、船舶燃油及航空燃油之定義，下列何者正確？",
 ["酒精汽油為摻配燃料乙醇或直接使用變性燃料乙醇者；生質柴油為摻配脂肪酸甲酯或直接使用脂肪酸甲酯者；船舶燃油含海運輕重柴油、漁業動力用油及燃料油","酒精汽油為摻配甲醇之汽油；生質柴油為以動植物油直接燃燒之燃料；船舶燃油僅指遠洋船舶使用之重質燃料油，不含漁業動力用油及海運輕柴油等油品","酒精汽油為含氧量達百分之八十五以上之汽油；生質柴油為以廢食用油煉製之柴油；航空燃油僅指軍用航空器所添加之航空煤油，不含商用航空汽油等油品","酒精汽油為添加乙基第三丁基醚之汽油；生質柴油為十六烷指數達五十以上之柴油；船舶燃油指船上發電機專用之柴油，航空燃油指地勤設備使用之各式油品"],"a",
 "第2條第11至14款：酒精汽油指以化石汽油摻配燃料乙醇或直接使用未經摻配化石汽油之變性燃料乙醇為燃料者；生質柴油指以化石柴油摻配脂肪酸甲酯或直接使用脂肪酸甲酯為燃料者；船舶燃油指任何船舶引擎、鍋爐或其他燃燒設備所使用之燃料，包括海運輕柴油、海運重柴油、漁業動力用油及燃料油；航空燃油指商用航空器所添加之航空煤油及航空汽油。",
 "Which correctly defines alcohol gasoline, biodiesel, marine fuel and aviation fuel?",
 ["Alcohol gasoline blends or uses denatured fuel ethanol; biodiesel blends or uses fatty acid methyl esters; marine fuel covers marine gas oil, marine diesel, fishery fuel and fuel oil","Alcohol gasoline is gasoline blended with methanol; biodiesel is animal or plant oil burned directly; marine fuel means only heavy fuel oil for ocean vessels, excluding fishery and marine gas oil","Alcohol gasoline is gasoline with oxygen content of 85 percent or more; biodiesel is refined from waste cooking oil; aviation fuel means only military jet kerosene, excluding commercial aviation gasoline","Alcohol gasoline is gasoline with ethyl tertiary butyl ether; biodiesel is diesel with a cetane index of 50 or more; marine fuel is generator diesel and aviation fuel is ground equipment fuel"],
 "Article 2, Subparagraphs 11 to 14."),

(L4,"第3條",2,"燃料成分-汽油管制",
 "汽油（含Ｅ３酒精汽油）成分管制標準，係以何種方式分階段規定？",
 ["分別訂有一百零一年一月一日、一百零九年七月一日及一百十三年一月一日起施行之三階段汽油成分標準","分別訂有一百年七月一日及一百零九年七月一日起施行之二階段汽油成分標準，並無第三階段之規定","僅訂有一百零九年七月一日起施行之單一階段汽油成分標準，其餘年度均沿用原有之管制數值規定","分別訂有九十五年、一百年及一百零五年一月一日起施行之三階段汽油成分標準並逐年加嚴其管制值"],"a",
 "第3條：汽油（含Ｅ３酒精汽油）成分管制標準分為中華民國一百零一年一月一日起、一百零九年七月一日起及一百十三年一月一日起施行之三階段標準，各以表定其苯含量、芳香烴含量、烯烴含量、硫含量、氧含量及蒸氣壓等項目之管制值。",
 "How are the gasoline composition control standards staged?",
 ["Three stages take effect on 1 January 2012, 1 July 2020 and 1 January 2024 respectively","Two stages take effect on 1 July 2011 and 1 July 2020, with no third stage prescribed","Only one stage takes effect on 1 July 2020, other years keeping the previous limits","Three stages take effect on 1 January 2006, 2011 and 2016, tightening year by year"],
 "Article 3; see also Article 2, Subparagraph 1."),

(L4,"第4條",2,"燃料成分-柴油管制",
 "柴油（含生質柴油）成分管制標準，其分階段施行日期為何？",
 ["分別訂有一百年七月一日及一百零九年七月一日起施行之二階段柴油成分標準","分別訂有一百零一年一月一日及一百十三年一月一日起施行之二階段柴油標準","分別訂有一百年七月一日、一百零九年七月一日及一百十三年一月一日之三階段","僅訂有一百十三年一月一日起施行之單一階段柴油成分標準並適用於全部油品"],"a",
 "第4條：柴油（含生質柴油）成分管制標準分為中華民國一百年七月一日起施行及一百零九年七月一日起施行之二階段標準。第2條第2款所定柴油成分包括硫含量、多環芳香烴含量及十六烷指數三項管制項目。",
 "What are the staged effective dates of the diesel composition control standards?",
 ["Two stages take effect on 1 July 2011 and on 1 July 2020 respectively","Two stages take effect on 1 January 2012 and on 1 January 2024 respectively","Three stages take effect on 1 July 2011, 1 July 2020 and 1 January 2024","Only one stage takes effect on 1 January 2024 and applies to all diesel fuels"],
 "Article 4; see also Article 2, Subparagraph 2."),

(L4,"第5條",2,"燃料成分-船舶燃油",
 "本標準對船舶燃油之管制，其適用範圍為何？",
 ["訂有船舶燃油成分管制標準，適用於船舶引擎、鍋爐或其他燃燒設備所使用之燃料","訂有船舶燃油成分管制標準，僅適用於外國籍船舶進入我國港區時所使用之燃料","訂有船舶燃油成分管制標準，僅適用於漁業動力用油，其餘船用油品不在管制內","未訂船舶燃油成分管制標準，船舶用油悉依國際海事組織公約規定辦理不另管制"],"a",
 "第5條：船舶燃油成分管制標準另以表定之。第2條第13款：船舶燃油指任何船舶引擎、鍋爐或其他燃燒設備所使用之燃料，包括海運輕柴油、海運重柴油、漁業動力用油及燃料油；第4款並定義硫含量指汽柴油、船舶燃油及航空燃油中含硫及其化合物之總量。",
 "What is the scope of the marine fuel composition control under these standards?",
 ["Marine fuel composition limits are set and apply to fuel used by any vessel engine, boiler or other combustion equipment","Marine fuel composition limits are set but apply only to foreign flagged vessels while they are within our port areas","Marine fuel composition limits are set but apply only to fishery power fuel, other marine oils being left uncontrolled","No marine fuel composition limits are set, marine fuels being governed solely by the conventions of the IMO instead"],
 "Article 5; see also Article 2, Subparagraphs 4 and 13."),

(L4,"第6條",2,"燃料成分-航空燃油",
 "本標準所稱航空燃油之範圍及其管制方式為何？",
 ["航空燃油指商用航空器所添加之航空煤油及航空汽油，並訂有航空燃油成分管制標準","航空燃油指軍民用航空器所使用之各式燃料，惟本標準並未訂定其成分管制標準值","航空燃油僅指商用航空器所添加之航空煤油，航空汽油另依石油管理法規定管制之","航空燃油指機場地勤設備及航空器所用油品，其成分由民航主管機關逐案核定認可"],"a",
 "第6條：航空燃油成分管制標準另以表定之。第2條第14款：航空燃油指商用航空器所添加之航空煤油及航空汽油；第4款並定義硫含量為汽柴油、船舶燃油及航空燃油中含硫及其化合物之總量，為航空燃油之主要管制項目。",
 "What is the scope of aviation fuel here and how is it controlled?",
 ["Aviation fuel means jet kerosene and aviation gasoline fuelled into commercial aircraft, and composition limits are prescribed","Aviation fuel means every fuel used by military and civil aircraft, but these standards prescribe no composition limits","Aviation fuel means only jet kerosene for commercial aircraft, aviation gasoline being controlled by petroleum law","Aviation fuel means fuels for airport ground equipment and aircraft, with composition approved case by case by CAA"],
 "Article 6; see also Article 2, Subparagraphs 4 and 14."),

(L4,"第7條",1,"燃料成分-施行",
 "移動污染源燃料成分管制標準之施行日期規定為何？",
 ["本標準除另定施行日期者外，自發布日施行","本標準一律自中華民國一百十三年一月一日施行","本標準除另定者外，自發布後屆滿六個月施行","本標準自中央主管機關另行公告之日起施行之"],"a",
 "第7條：本標準除另定施行日期者外，自發布日施行。第3條、第4條所定汽油及柴油成分標準則另訂有一百零一年一月一日、一百零九年七月一日、一百十三年一月一日及一百年七月一日等分階段施行日期。",
 "When do the Mobile Source Fuel Composition Control Standards take effect?",
 ["Unless another date is set, they take effect on the promulgation date","They uniformly take effect on 1 January 2024 for all the fuel types","Unless otherwise set, they take effect six months after promulgation","They take effect on a date separately announced by the central authority"],
 "Article 7; see also Articles 3 and 4."),

# ===== ENV-134 煉鋼及鑄造電爐粒狀污染物管制及排放標準 =====
(L5,"第1條",1,"煉鋼電爐-法源",
 "煉鋼及鑄造電爐粒狀污染物管制及排放標準之訂定法源依據為何？",
 ["依空氣污染防制法第二十條第二項及第二十三條第二項規定訂定之","依空氣污染防制法第二十條第二項及第二十四條第一項規定訂定之","依空氣污染防制法第二十三條第二項及第三十一條第二項規定訂定","依空氣污染防制法第十五條第二項及第二十條第二項規定訂定之"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項及第二十三條第二項規定訂定之。第3條規定本標準適用於煉鋼及鑄造電爐；第8條規定本標準除另定施行日期者外，自發布日施行。",
 "What is the legal basis for the Emission Standards for Particulates from Steelmaking and Foundry Electric Furnaces?",
 ["Adopted under Article 20, Paragraph 2 and Article 23, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 20, Paragraph 2 and Article 24, Paragraph 1 of the Air Pollution Control Act","Adopted under Article 23, Paragraph 2 and Article 31, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 15, Paragraph 2 and Article 20, Paragraph 2 of the Air Pollution Control Act"],
 "Article 1; see also Articles 3 and 8."),

(L5,"第2條",3,"煉鋼電爐-定義",
 "本標準所稱電爐、煉鋼電弧爐及鑄造電爐，其定義各為何？",
 ["電爐指以電為動力熔煉鋼鐵及其合金之電弧爐、感應爐及電阻爐；煉鋼電弧爐指利用電弧熱量冶煉廢鐵廢鋼或銑鐵之電弧爐；鑄造電爐指從事鋼鐵及其合金元件鑄造之電爐","電爐指以燃油為動力熔煉鋼鐵之各式熔解爐；煉鋼電弧爐指以感應加熱方式冶煉銑鐵之感應爐；鑄造電爐指從事鋼鐵及其合金元件表面處理及熱處理作業之各式加熱爐設備","電爐指設有集塵設備之各類熔融爐；煉鋼電弧爐指以電阻加熱方式熔煉廢鋼之電阻爐；鑄造電爐指以化石燃料燃燒加熱進行灰鐵鑄造程序之連續式或批次式加熱熔解設備","電爐指年產量達一萬公噸以上之熔煉設備；煉鋼電弧爐指以轉爐吹氧方式精煉鋼液之設備；鑄造電爐指從事鋁銅等非鐵金屬元件鑄造之電弧爐、感應爐及電阻爐等設備"],"a",
 "第2條第3至5款：電爐指以電為動力來源熔煉鋼、鐵及其合金之電弧爐、感應爐及電阻爐；煉鋼電弧爐指利用電弧產生的熱量進行廢鐵、廢鋼或銑鐵冶煉之電弧爐；鑄造電爐指從事鋼、鐵及其合金元件鑄造（含鋼鑄造程序或灰鐵鑄造程序等）之電爐，包含電弧爐、感應爐及電阻爐。",
 "How are electric furnace, steelmaking electric arc furnace and foundry electric furnace defined?",
 ["Electric furnaces melt steel, iron and alloys by electric power and include arc, induction and resistance furnaces; the steelmaking arc furnace smelts scrap or pig iron by arc heat; the foundry furnace casts steel and iron parts","Electric furnaces melt steel and iron using fuel oil in various melting units; the steelmaking arc furnace smelts pig iron by induction heating; the foundry furnace performs surface and heat treatment of steel and iron parts","Electric furnaces are any melting units fitted with dust collectors; the steelmaking arc furnace melts scrap by resistance heating; the foundry furnace uses fossil fuel firing for grey iron casting in batch or continuous units","Electric furnaces are melting units producing over ten thousand tonnes a year; the steelmaking arc furnace refines molten steel by oxygen blowing; the foundry furnace casts non-ferrous parts such as aluminium and copper"],
 "Article 2, Subparagraphs 3 to 5."),

(L5,"第2條",3,"煉鋼電爐-加料出鋼期",
 "本標準所稱加料期及出鋼期，其起訖時點及廠房逸散不透光率所容許之期限為何？",
 ["加料期自爐蓋開啟加料至爐蓋關閉後三分鐘；出鋼期自開始傾斜出鋼至恢復直立位置後三分鐘；廠房逸散不透光率所容許之期限均為六分鐘","加料期自爐蓋開啟加料至爐蓋關閉後六分鐘；出鋼期自開始傾斜出鋼至恢復直立位置後六分鐘；廠房逸散不透光率所容許之期限均為三分鐘","加料期自加料開始至熔解完成為止；出鋼期自出鋼開始至鋼液冷卻凝固為止；廠房逸散不透光率所容許之期限依實際作業時間認定不予限制","加料期自爐蓋開啟前三分鐘至關閉為止；出鋼期自傾斜出鋼前三分鐘至完成為止；廠房逸散不透光率所容許之期限由主管機關個案核定認可"],"a",
 "第2條第6款、第7款：加料期指自煉鋼電弧爐爐蓋開啟加料至爐蓋關閉後三分鐘，本標準附表粒狀污染物排放標準廠房逸散不透光率所容許之加料期限為六分鐘；出鋼期指自煉鋼電弧爐開始傾斜出鋼時至恢復直立位置後之三分鐘，所容許之出鋼期限為六分鐘。",
 "How are the charging period and the tapping period defined, and what time is allowed for building opacity?",
 ["Charging runs from opening the roof to three minutes after it closes; tapping runs from tilting to three minutes after returning upright; six minutes each is allowed for building opacity","Charging runs from opening the roof to six minutes after it closes; tapping runs from tilting to six minutes after returning upright; three minutes each is allowed for building opacity","Charging runs from the start of charging until melting is complete; tapping runs from the start of tapping until the steel solidifies; no time limit applies to building opacity","Charging runs from three minutes before the roof opens until it closes; tapping runs from three minutes before tilting until completion; the authority sets opacity time case by case"],
 "Article 2, Subparagraphs 6 and 7."),


(L5,"第3條",1,"煉鋼電爐-適用",
 "本標準之適用對象為何？",
 ["本標準適用於煉鋼及鑄造電爐","本標準適用於各類金屬冶煉之熔融爐","本標準適用於煉鋼電弧爐但不含鑄造電爐","本標準適用於使用化石燃料之各式熔解爐"],"a",
 "第3條：本標準適用於煉鋼及鑄造電爐。第2條第3款並定義電爐指以電為動力來源熔煉鋼、鐵及其合金之電弧爐、感應爐及電阻爐；第4條規定本標準規定值如附表。",
 "To what does this standard apply?",
 ["It applies to steelmaking and foundry electric furnaces","It applies to melting furnaces of all metal smelting industries","It applies to steelmaking arc furnaces but not foundry furnaces","It applies to all melting furnaces that burn fossil fuels for heat"],
 "Article 3; see also Articles 2 and 4."),

(L5,"第4條",1,"煉鋼電爐-規定值",
 "煉鋼及鑄造電爐粒狀污染物之排放標準規定值，係以何種方式訂定？",
 ["本標準規定值列於附表，依附表所定數值管制排放","本標準規定值由各地方主管機關按區域特性另訂","本標準規定值直接列於條文中逐項明定管制數值","本標準規定值依操作許可證所載內容個案認定之"],"a",
 "第4條：本標準規定值如附表。第2條第6款、第7款並說明附表粒狀污染物排放標準中，廠房逸散不透光率所容許之加料期限及出鋼期限均為六分鐘。",
 "How are the particulate emission limits for these furnaces prescribed?",
 ["The limit values are set out in the appended table and control emissions accordingly","The limit values are separately set by each local authority to suit its region","The limit values are listed item by item directly in the text of the articles","The limit values are determined case by case as stated in the operating permit"],
 "Article 4; see also Article 2."),

(L5,"第5條",2,"煉鋼電爐-爐蓋",
 "煉鋼電弧爐爐蓋之開啟管制規定為何？有何例外？",
 ["除加料期及出鋼期外均不得打開；但於維修保養、停爐及故障期間不適用之","除加料期及出鋼期外均不得打開；且於維修保養、停爐及故障期間亦不得打開","僅於出鋼期不得打開，加料期則不受限制；維修保養期間應報請主管機關同意","除每日作業結束後外均得打開；但廠房逸散不透光率超過標準時應立即關閉之"],"a",
 "第5條：煉鋼電弧爐爐蓋，除加料期及出鋼期外，均不得打開；但於維修保養、停爐及故障期間不適用之。第2條第6款、第7款並就加料期、出鋼期之起訖時點及附表所容許之六分鐘期限予以定義。",
 "When may the roof of a steelmaking arc furnace be opened, and what exceptions apply?",
 ["It may not be opened except during charging and tapping; this does not apply during maintenance, shutdown and breakdown","It may not be opened except during charging and tapping, and it may not be opened during maintenance or breakdown either","It may not be opened only during tapping while charging is unrestricted; maintenance periods need the authority's consent","It may be opened at any time except after daily work ends; but it must close at once if building opacity exceeds limits"],
 "Article 5; see also Article 2, Subparagraphs 6 and 7."),

(L5,"第6條",2,"煉鋼電爐-紀錄系統",
 "煉鋼電弧爐於進行加料期、出鋼期之不透光率及時間判定前，應先完成何項設施？",
 ["應先完成集塵覆罩流量及爐內自由空間壓力紀錄系統","應先完成連續自動監測設施及數據傳輸連線之設置","應先完成廠房周界不透光率自動監測攝影設備之設置","應先完成廢氣排放管道之採樣設施及檢測平臺之設置"],"a",
 "第6條：煉鋼電弧爐之集塵覆罩流量及爐內自由空間壓力紀錄系統完成後，始得進行加料期、出鋼期之不透光率及時間判定。第5條並規定爐蓋除加料期及出鋼期外均不得打開，惟維修保養、停爐及故障期間不適用。",
 "What must be completed before opacity and timing determinations for charging and tapping may be made?",
 ["The recording system for hood flow rate and furnace free space pressure must be completed first","The continuous automatic monitoring facility and its data transmission link must be completed first","The automatic opacity monitoring camera system at the plant boundary must be completed first","The stack sampling ports and the testing platform on the exhaust duct must be completed first"],
 "Article 6; see also Article 5."),

(L5,"第7條",3,"煉鋼電爐-濃度計算",
 "電爐有一個以上集塵設備時，其粒狀污染物濃度（C）應如何計算？計算基準為何？",
 ["C＝Σ（Cs·Qs）／Σ（Qs），即各排放口排放量總和除以排氣體積流量總和；以凱氏溫度二七三度及一大氣壓未稀釋乾燥排氣為基準","C＝Σ（Cs）／n，即各排放口粒狀污染物濃度之算術平均值；以攝氏二十五度及一大氣壓經稀釋後之濕排氣體積為計算基準","C＝Σ（Cs·Qs）×n，即各排放口排放量總和乘以排放口總數目；以凱氏溫度二七三度及二大氣壓未稀釋濕排氣為計算基準","C＝Σ（Qs）／Σ（Cs·Qs），即排氣體積流量總和除以排放量總和；以排氣含氧量百分之十五為參考基準並經校正計算"],"a",
 "第7條：本標準濃度值計算均以凱氏溫度二七三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準；電爐有一個以上集塵設備者，粒狀污染物濃度 C＝Σ（Cs·Qs）／Σ（Qs），其中Cs為各集塵設備廢氣排放口之粒狀污染物濃度（mg/Nm3），Qs為各排放口之排氣體積流量（Nm3/hr）。",
 "How is particulate concentration C computed when a furnace has more than one dust collector, and on what basis?",
 ["C = Σ(Cs·Qs) / Σ(Qs), the total emissions of all outlets divided by total flow; based on dry undiluted exhaust at 273 K and one atmosphere","C = Σ(Cs) / n, the arithmetic mean of the concentrations of all outlets; based on diluted wet exhaust volume at 25 degrees Celsius and one atmosphere","C = Σ(Cs·Qs) × n, the total emissions of all outlets times the number of outlets; based on wet undiluted exhaust at 273 K and two atmospheres","C = Σ(Qs) / Σ(Cs·Qs), the total flow divided by total emissions of all outlets; based on an exhaust oxygen reference of 15 percent after correction"],
 "Article 7."),

(L5,"第8條",1,"煉鋼電爐-施行",
 "煉鋼及鑄造電爐粒狀污染物管制及排放標準之施行日期規定為何？",
 ["本標準除另定施行日期者外，自發布日施行","本標準一律自發布後屆滿一年之日起施行","本標準除另定者外，自次年一月一日起施行","本標準自中央主管機關另行公告之日施行"],"a",
 "第8條：本標準除另定施行日期者外，自發布日施行。第2條第1款、第2款並以一百零二年十一月十九日作為新設污染源與既存污染源之區分基準日。",
 "When do the Steelmaking and Foundry Electric Furnace Particulate Standards take effect?",
 ["Unless another date is set, they take effect on the promulgation date","They uniformly take effect upon expiry of one year from promulgation","Unless otherwise set, they take effect on 1 January of the next year","They take effect on a date separately announced by the central authority"],
 "Article 8; see also Article 2."),
]
