# -*- coding: utf-8 -*-
# OSH-36 營造安全衛生設施標準 補題（一）：第1條～第67條未出題條文
Q = [
("OSH-36","第1條",1,"營造安全-法源",
 "營造安全衛生設施標準之訂定法源為何？本標準未規定之事項應如何處理？",
 ["依職業安全衛生法第六條第三項規定訂定；本標準未規定者，適用其他有關職業安全衛生法令之規定",
  "依職業安全衛生法第五條第二項規定訂定；本標準未規定者，由地方主管機關另行公告補充規定",
  "依勞動檢查法第八條第一項規定訂定；本標準未規定者，適用建築技術規則有關施工安全之規定",
  "依職業安全衛生設施規則第三條規定訂定；本標準未規定者，由事業單位自行訂定作業規範辦理"],"a",
 "第1條：本標準依職業安全衛生法第六條第三項規定訂定；本標準未規定者，適用其他有關職業安全衛生法令之規定。第2條並定明本標準適用於從事營造作業之有關事業。",
 "What is the legal basis of this Standard, and what applies to matters it does not cover?",
 ["Issued under Article 6(3) of the OSH Act; matters not covered follow other occupational safety and health laws",
  "Issued under Article 5(2) of the OSH Act; matters not covered are supplemented by local authority notices",
  "Issued under Article 8(1) of the Labor Inspection Act; matters not covered follow the building technical rules",
  "Issued under Article 3 of the OSH Facilities Rules; matters not covered are self-regulated by each enterprise"],
 "Article 1."),

("OSH-36","第2條",1,"營造安全-適用範圍",
 "營造安全衛生設施標準之適用對象範圍為何？",
 ["適用於從事營造作業之有關事業，凡從事營造作業者均應依本標準辦理",
  "僅適用於承攬公共工程且工程金額達一億元以上之營造業廠商",
  "僅適用於領有建築執照之建築工程，土木及管線工程不在適用範圍",
  "僅適用於僱用勞工人數三十人以上之營造業事業單位及其承攬人"],"a",
 "第2條：本標準適用於從事營造作業之有關事業，不以工程金額、工程種類或勞工人數設限。第1條並定明本標準未規定者適用其他職業安全衛生法令。",
 "What is the scope of application of this Standard?",
 ["It applies to all undertakings engaged in construction work, regardless of size or contract value",
  "It applies only to contractors of public works with a contract value of NT$100 million or more",
  "It applies only to building works holding a building permit, excluding civil and pipeline works",
  "It applies only to construction undertakings employing thirty or more workers and their contractors"],
 "Article 2."),

("OSH-36","第4條",2,"營造安全-勞工義務",
 "對於雇主依本標準設置之安全衛生設備及措施，雇主應規定勞工遵守哪些事項？",
 ["不得任意拆卸或使其失效以保持應有效能；發現被拆卸或失效時應即停止作業並報告雇主或直屬主管人員",
  "得視作業需要自行調整或暫時拆卸；發現被拆卸或失效時應於當日工作結束後填表送交安全衛生單位",
  "非經工作場所負責人同意不得使用；發現被拆卸或失效時應自行修復完成後再向雇主提出書面報告",
  "應於每日作業前實施檢點並簽名；發現被拆卸或失效時應通知承攬商於三日內完成補修並留存紀錄"],"a",
 "第4條：雇主應規定勞工不得任意拆卸安全衛生設備或使其失效，並於發現被拆卸或失效時，應即停止作業並報告雇主或直屬主管人員。第3條則課予雇主經常注意保養、異常時即補修之義務。",
 "What must employers require workers to observe regarding safety and health equipment?",
 ["Not to dismantle it or render it ineffective; on finding it removed or ineffective, stop work at once and report",
  "They may adjust or remove it as work requires; if found removed, file a form with the safety unit that day",
  "It may not be used without the site manager's consent; if found removed, repair it first and then report in writing",
  "Check and sign off daily before work; if found removed, tell the contractor to repair within three days and record"],
 "Article 4."),

("OSH-36","第6條",2,"營造安全-風險評估",
 "雇主使勞工於營造工程工作場所作業前，應由何人再實施風險評估？其結果應如何處理？",
 ["應指派所僱職業安全衛生人員、工作場所負責人或專任工程人員，或委託專業單位實施，並將防護設施列入施工計畫",
  "應由當地勞動檢查機構派員會同工地負責人實施，並將評估結果函報中央主管機關備查後始得開工",
  "應由監造單位之建築師或技師獨立實施，其防護設施得於施工中視實際狀況隨時調整不必列入計畫",
  "應由工地全體勞工以會議方式共同實施，評估紀錄僅須留存工地備查，無須納入施工計畫之內容"],"a",
 "第6條：作業前應指派所僱之職業安全衛生人員、工作場所負責人、專任工程人員等專業人員，或委託專業單位，依施工規劃階段之風險評估及施工計畫等資料再實施風險評估，並採適當防護設施；依營建法規應有施工計畫者，並應將防護設施列入施工計畫執行。",
 "Who must re-conduct the risk assessment before work at a construction site, and how is the result handled?",
 ["In-house OSH staff, site supervisors or full-time engineers, or a commissioned professional unit; protections go into the plan",
  "The local labor inspection agency must jointly conduct it, and the result must be filed with the central authority before work starts",
  "The supervising architect or engineer conducts it alone, and protections may be adjusted during work without entering any plan",
  "All site workers jointly conduct it in a meeting; keeping the record on site suffices and it need not enter the construction plan"],
 "Article 6."),

("OSH-36","第7條",1,"營造安全-工作場所",
 "營造工程用之模板、施工架等材料拆除後，對於凸出之鐵釘、鐵條，雇主應採何種防護措施？",
 ["應採取拔除或釘入之防護措施，避免凸出之鐵釘、鐵條刺傷勞工",
  "應以紅色噴漆標示位置並設置警告標示，提醒勞工通行時注意閃避",
  "應於拆除後七日內集中堆置於指定區域，並派人於周邊全時監視管制",
  "應以帆布或塑膠布覆蓋於材料表面，並於材料上標示禁止勞工攀爬字樣"],"a",
 "第7條：雇主對於營造工程用之模板、施工架等材料拆除後，應採取拔除或釘入凸出之鐵釘、鐵條等防護措施。第5條並要求對暴露之鋼筋、鋼材採彎曲尖端、加蓋或加裝護套等防護。",
 "What must be done with protruding nails and bars on formwork and scaffold materials after dismantling?",
 ["They must be pulled out or hammered flush so that they cannot injure workers","Positions must be marked in red paint with warning signs so workers avoid them","Materials must be stacked in a designated area within seven days and watched full time","Materials must be covered with canvas or plastic and marked with a no-climbing sign"],
 "Article 7."),

("OSH-36","第8條之1",2,"營造安全-車輛機械",
 "為避免車輛機械作業時翻落或表土崩塌，雇主應事先調查哪些事項？其中哪些應於作業前告知勞工？",
 ["應調查天候地質地形、機械種類性能、行經路線及作業方法；其中行經路線及作業方法應於作業前告知勞工",
  "應調查機械檢查合格證、操作人員證照及保養紀錄；其中操作人員證照應於作業前告知勞工週知",
  "應調查鄰近建物產權、施工噪音及交通流量；其中噪音及交通流量應於作業前告知勞工並公告",
  "應調查工程預算、工期及材料來源等資料；其中工期及材料來源應於作業前告知勞工並張貼公布"],"a",
 "第8條之1：雇主應就作業場所天候地質地形、車輛機械種類及性能、行經路線、作業方法等事先調查；調查有危害之虞者應整理工作場所，且行經路線與作業方法應於作業前告知勞工。",
 "What must be surveyed in advance for vehicle-type machinery, and which items must be told to workers beforehand?",
 ["Weather, geology and terrain, machine type and capacity, travel routes and work methods; routes and methods must be told beforehand",
  "Inspection certificates, operator licences and maintenance records; operator licences must be announced to workers beforehand",
  "Neighbouring property titles, construction noise and traffic volume; noise and traffic must be announced beforehand",
  "Project budget, schedule and material sources; the schedule and material sources must be posted for workers beforehand"],
 "Article 8-1."),

("OSH-36","第9條",2,"營造安全-管線防護",
 "工作場所中原有之電力、電信、給水、煤氣等管線如有安全之虞時，雇主應如何處理？",
 ["應確實掌握狀況妥善處理，非經管線權責單位同意，不得任意挖掘、剪接、移動或於其鄰近從事加熱工作",
  "得由工地負責人指派專人先行剪接移動，事後三日內以書面通知管線權責單位補辦同意手續",
  "應報請當地勞動檢查機構核准後始得挖掘或移動，管線權責單位之同意與否不影響施工進行",
  "應先以警示帶圍出管線位置即可施工，僅於管線破損致外洩時，方須通知管線權責單位處理"],"a",
 "第9條：對工作場所原有電線、電力配管、電信管線、給水管、石油產品管線、煤氣管線、危險物或有害物管線等妨礙施工安全者應妥善處理；有安全之虞者，非經管線權責單位同意，不得任意挖掘、剪接、移動或於其鄰近從事加熱工作。",
 "How must existing power, telecom, water and gas lines that pose a safety risk be handled?",
 ["Ascertain and properly handle them; no excavation, cutting, moving or nearby heating without the utility owner's consent",
  "The site manager may assign someone to cut or move them first and notify the utility owner in writing within three days",
  "Approval from the local labor inspection agency suffices for excavation or relocation; the utility owner's consent is not needed",
  "Marking the line position with warning tape suffices; the utility owner need be told only if a line is damaged and leaks"],
 "Article 9."),

("OSH-36","第10條",1,"營造安全-條文沿革",
 "營造安全衛生設施標準第十條之現行狀態，以及工作場所原有管線妨礙施工安全時之處理依據為何？",
 ["該條業經刪除；原有管線妨礙施工安全者，依現行第九條規定妥善處理並取得管線權責單位同意",
  "該條仍為現行有效條文；原有管線妨礙施工安全者，依該條規定報請中央主管機關核定處理方式",
  "該條業經刪除；原有管線妨礙施工安全者，改依職業安全衛生設施規則有關電氣安全章節辦理",
  "該條僅停止適用而未刪除；原有管線妨礙施工安全者，仍得依該條規定由工地負責人逕行處理"],"a",
 "第10條已刪除，不再有實質規範內容。工作場所原有電線、管線妨礙工程施工安全者，現行係依第9條規定妥善處理，且有安全之虞時非經管線權責單位同意不得挖掘、剪接或移動。",
 "What is the current status of Article 10, and which article governs existing utility lines that obstruct safe construction?",
 ["It has been deleted; obstructing utility lines are handled under the current Article 9 with the utility owner's consent",
  "It remains in force; obstructing utility lines are handled by reporting to the central competent authority for approval",
  "It has been deleted; obstructing utility lines are instead handled under the electrical safety chapter of the Facilities Rules",
  "It is merely suspended rather than deleted; the site manager may still handle obstructing lines directly under it"],
 "Article 10 (deleted)."),

("OSH-36","第10條之1",2,"營造安全-軌道作業",
 "於軌道上或鄰近軌道場所作業時，為防止軌道機械碰觸引起之危害，應依何規定辦理？",
 ["坑道隧道橋梁之通行軌道應於適當間隔處設避難處所，車輛有碰觸之虞者應設監視警報裝置或配置監視人員",
  "軌道兩側應各設置高度九十公分之固定式護欄，並於每五十公尺設置一處人員專用之地下穿越通道",
  "應於軌道全線設置自動遮斷機及紅色閃光號誌，作業期間並應請軌道經營機構全面停止列車運行",
  "應由作業勞工自行攜帶手持式警示旗與哨音器，於機械接近時互相通報，不必另設監視警報裝置"],"a",
 "第10條之1：設置於坑道、隧道、橋梁等供勞工通行之軌道，應於適當間隔處設置避難處所；軌道上車輛有碰觸勞工之虞時，應設置能於車輛接近前發出電鈴或蜂鳴器等監視警報裝置或配置監視人員；軌道維護、機械替換連結作業並應保持必要照明。",
 "What measures apply to work on or adjacent to rail tracks to prevent contact by rail machinery?",
 ["Refuges at suitable intervals on tracks in tunnels and bridges, plus alarm devices or a watchman where contact is possible",
  "Fixed 90 cm guardrails on both sides of the track and an underpass for workers every fifty metres of track",
  "Automatic barriers and red flashing signals along the whole line, with the operator suspending all train movements",
  "Workers carry hand flags and whistles to warn each other as machines approach, with no separate alarm device needed"],
 "Article 10-1."),

("OSH-36","第11條之1",1,"營造安全-防護具",
 "對於進入營繕工程工作場所之作業人員，雇主在頭部防護上應盡何種義務？",
 ["應提供適當之安全帽，並使作業人員正確戴用",
  "應提供適當之安全帽，但僅限於高處作業人員使用",
  "應要求作業人員自行準備安全帽並負擔購置費用",
  "應於工地入口設置安全帽借用箱供人員自由取用"],"a",
 "第11條之1：雇主對於進入營繕工程工作場所作業人員，應提供適當安全帽，並使其正確戴用。第11條之2另定明作業人員應事前接受中央主管機關指定之營造作業安全訓練。",
 "What is the employer's duty on head protection for persons entering a building works site?",
 ["Provide suitable safety helmets and ensure that they are worn correctly",
  "Provide suitable safety helmets, but only for those working at height",
  "Require workers to supply their own helmets and bear the purchase cost",
  "Place a helmet loan box at the site entrance for anyone to take freely"],
 "Article 11-1."),

("OSH-36","第12條",2,"營造安全-易燃物料",
 "工作場所儲存有易燃性物料時，雇主應辦理之事項為何？",
 ["應設防止太陽直接照射之遮蔽物，並隔離儲存、設置禁止煙火之警告標誌及適當之滅火器材",
  "應設置密閉式冷藏庫房存放，並於庫房內裝設自動撒水設備及二十四小時錄影監視系統",
  "應存放於工地辦公室相鄰之獨立房間，並指派專責保管人員於上下班時清點數量並登記",
  "應以防火毯覆蓋後堆置於工地角落，並於每週實施一次庫存盤點及容器外觀檢查並紀錄"],"a",
 "第12條：工作場所儲存易燃性物料時，除應有防止太陽直接照射之遮蔽物外，並應隔離儲存、設置禁止煙火之警告標誌及適當之滅火器材。",
 "What must be done where flammable materials are stored at the workplace?",
 ["Provide shading from direct sunlight, store them separately, post no-fire warning signs and provide suitable extinguishers",
  "Store them in a sealed refrigerated store fitted with automatic sprinklers and round-the-clock video surveillance",
  "Store them in a separate room next to the site office with a custodian counting and logging them each shift",
  "Cover them with fire blankets in a corner of the site and inventory and inspect the containers once each week"],
 "Article 12."),

("OSH-36","第13條",2,"營造安全-倒塌防止",
 "依規定，雇主使勞工於哪些有發生倒塌、崩塌之虞之場所作業時，應設置防止倒塌崩塌之設施？",
 ["邊坡上方或其周邊，以及構造物或其他物體之上方、內部或其周邊等場所",
  "僅限於開挖深度達一點五公尺以上之露天開挖區及其相鄰之作業場所",
  "僅限於擋土支撐已完成組立且尚未拆除之區域及其正下方之通行走道",
  "僅限於高度七公尺以上之施工架及模板支撐所在位置及其鄰近之區域"],"a",
 "第13條：雇主使勞工於邊坡上方或其周邊，及構造物或其他物體之上方、內部或其周邊等有發生倒塌、崩塌之虞之場所作業者，應有防止發生倒塌、崩塌之設施。",
 "At which places with a risk of collapse must the employer provide collapse-prevention facilities?",
 ["Above or around a slope, and above, inside or around a structure or other object",
  "Only in open excavation areas at least 1.5 metres deep and the adjacent work areas",
  "Only in areas where earth retaining shoring is erected and the walkways directly below",
  "Only at scaffolds and formwork supports 7 metres or more high and the areas nearby"],
 "Article 13."),

("OSH-36","第15條",3,"營造安全-水位暴漲",
 "使勞工於有發生水位暴漲或土石流之地區作業者，除落水防護外，尚應辦理哪些事項？",
 ["應建立含無線連絡器材、連絡信號及連絡人員之作業連絡系統，並選任專責警戒人員辦理監視及通知撤離",
  "應於作業區上游一公里處設置自動水位計，並委託氣象機構每小時提供一次降雨預報資料存查",
  "應投保營造綜合保險及僱主意外責任保險，並於工務所張貼保險證明與理賠申請流程供查閱",
  "應由工地負責人每日填寫水情紀錄表，於雨量達到警戒值時報請當地水利主管機關核備後撤離"],"a",
 "第15條：於水位暴漲或土石流地區作業者，應建立作業連絡系統（含無線連絡器材、連絡信號、連絡人員），並選任專責警戒人員，隨時與河川管理當局連絡了解降雨量、監視上游水位或土石流狀況、獲知暴漲時即通知勞工撤離、不及撤離時啟動緊急應變體系。",
 "Besides fall-into-water protection, what must be done for work in areas prone to flash floods or debris flows?",
 ["Set up a liaison system with radios, signals and liaison staff, and appoint dedicated sentries to monitor and order evacuation",
  "Install an automatic water gauge one kilometre upstream and obtain hourly rainfall forecasts from a weather agency",
  "Take out construction and employer's liability insurance and post the certificates and claim procedure at the site office",
  "Have the site manager log water conditions daily and report to the water authority for approval before evacuating"],
 "Article 15."),

("OSH-36","第16條",3,"營造安全-緊急應變",
 "使勞工於有遭受溺水或土石流淹沒危險地區作業，關於救生器材檢點及紀錄留存之規定為何？",
 ["救生衣、救生圈、救生船、警報系統等應維護保養，作業期間每日實施檢點；相關計畫與紀錄應留存至完工前備查",
  "救生器材應每月實施檢點一次，相關緊急應變計畫與訓練紀錄應於作業結束後三個月內銷毀不再留存",
  "救生器材應每季委託專業機構檢驗，檢驗報告應於次年度開工前函報當地勞動檢查機構核備始得使用",
  "救生器材應於每次颱風過後實施檢點，訓練紀錄與維護紀錄由承攬商自行保管，不必留存於工務所"],"a",
 "第16條：應擬訂含通報系統、撤離程序、救援程序之緊急應變計畫並訓練勞工；第14條、第15條之救生衣、救生圈、救生繩索、救生船、警報系統等應維護保養，作業期間每日實施檢點；通報與救援單位連絡人姓名電話應揭示於工務所；緊急應變計畫、訓練紀錄及檢點紀錄在完工前應留存備查。",
 "What are the inspection and record-keeping rules for lifesaving gear where drowning or debris-flow burial is possible?",
 ["Lifejackets, rings, boats and alarms must be maintained and checked daily during work; plans and records kept until completion",
  "Lifesaving gear must be checked monthly, and emergency plans and training records destroyed within three months after work ends",
  "Lifesaving gear must be tested quarterly by a professional body and the report filed with the labor inspection agency yearly",
  "Lifesaving gear must be checked after each typhoon, with training and maintenance records kept by the contractor off site"],
 "Article 16."),

("OSH-36","第18條之1",1,"營造安全-條文沿革",
 "營造安全衛生設施標準第十八條之一之現行狀態為何？屋頂作業之安全規定現應依何條辦理？",
 ["該條業經刪除；屋頂作業之指派專人督導、護欄踏板及屋頂作業主管等規定，依現行第十八條辦理",
  "該條仍為現行有效條文；屋頂作業之踏板寬度與安全網設置規定，全部依該條規定辦理不適用他條",
  "該條業經刪除；屋頂作業之安全規定改依高架作業勞工保護措施標準有關規定辦理，不適用本標準",
  "該條僅暫緩施行而非刪除；屋頂作業於該條施行前，得由雇主自行訂定作業標準取代法定防護措施"],"a",
 "第18條之1已刪除。現行屋頂作業之規定見第18條：應指派專人督導，斜度大於三十四度或滑溜屋頂應設護欄、寬度四十公分以上工作臺及梯子，易踏穿材料屋頂應設寬度三十公分以上踏板並於下方裝設格柵或安全網，且應指派屋頂作業主管於現場辦理法定事項。",
 "What is the status of Article 18-1, and which article now governs roof work safety?",
 ["It has been deleted; supervision, guardrails, treading boards and the roof work supervisor follow the current Article 18",
  "It remains in force; treading board width and safety net requirements for roof work are governed solely by that article",
  "It has been deleted; roof work is instead governed by the standards on protective measures for elevated work",
  "It is only deferred rather than deleted; until it starts, employers may set their own rules in place of legal protections"],
 "Article 18-1 (deleted)."),

("OSH-36","第19條",2,"營造安全-墜落防止",
 "高度二公尺以上之屋頂、鋼梁、開口部分、工作臺、橋梁墩柱等處作業有墜落之虞時，應設置何種防護設備？",
 ["應設置護欄、護蓋或安全網等防護設備；設置有困難或因作業需要臨時開啟拆除者，應使勞工使用安全帶",
  "應一律設置固定式鋼構護籠並全面張掛安全網，任何情形下均不得以使用安全帶之方式替代設置",
  "應設置警示線及管制通行區並派員監視，僅於開口面積超過二平方公尺時始須另設護欄或護蓋",
  "應由勞工佩掛安全帶並繫於就近之施工架杆件，不須另行設置護欄、護蓋或安全網等防護設備"],"a",
 "第19條：高度二公尺以上之屋頂、鋼梁、開口部分、階梯、樓梯、坡道、工作臺、擋土牆、擋土支撐、施工構臺、橋梁墩柱及上部結構、橋臺等處作業有墜落之虞者，應設置護欄、護蓋或安全網；設置困難或因作業需要臨時開啟、拆除者，應採取使勞工使用安全帶等防墜措施，困難原因消失後仍應回復設置。",
 "What fall protection is required for work 2 m or higher on roofs, steel beams, openings, platforms and bridge piers?",
 ["Guardrails, covers or safety nets; where these are impracticable or temporarily removed, workers must use safety harnesses",
  "Fixed steel cages and full safety netting are always required, and safety harnesses may never be used as a substitute",
  "Warning lines, controlled zones and a watchman suffice; guardrails are added only where an opening exceeds two square metres",
  "Workers need only hook a harness onto a nearby scaffold member; guardrails, covers or safety nets are not required at all"],
 "Article 19."),

("OSH-36","第19條",2,"營造安全-墜落防止",
 "因作業需要臨時將護欄、護蓋或安全網等防護設備開啟或拆除者，其後續處理義務為何？",
 ["應採取使勞工使用安全帶等防止墜落措施，且設置困難之原因消失後，應即回復依原規定設置防護設備",
  "得於該作業期間全面免除防墜設備，並於作業完成後由工地負責人填具紀錄表存查即可不再回復",
  "應改以警示線及管制通行區代替，該替代措施得於工程結束前持續使用而不必再回復原防護設備",
  "應報請當地勞動檢查機構核准後始得開啟或拆除，核准期間並得免除使用安全帶等防墜落措施"],"a",
 "第19條第2項：設置護欄、護蓋或安全網有困難，或因作業需要臨時開啟、拆除者，應採取使勞工使用安全帶等防止墜落措施；但其設置困難之原因消失後，應依第1項規定回復設置。第17條並要求先以設計工法、護欄護蓋、安全網等順序控制墜落風險。",
 "What follow-up duty applies when guardrails, covers or nets are temporarily opened or removed for work?",
 ["Workers must use safety harnesses etc., and once the obstacle to installation ends the protection must be reinstated",
  "Fall protection may be waived entirely for that period, and a record filed by the site manager ends the obligation",
  "Warning lines and controlled zones may replace them permanently until the project ends, with no need to reinstate",
  "Prior approval of the labor inspection agency is needed, and during approval harness use may also be dispensed with"],
 "Article 19(2)."),

("OSH-36","第25條",1,"營造安全-開口防護",
 "對於廢止使用之開口及暫不使用之開口，雇主應分別如何處理以防止勞工墜落？",
 ["廢止使用之開口應予封閉；暫不使用之開口應採取加蓋等設備以防止勞工墜落",
  "廢止使用之開口應加蓋；暫不使用之開口應設置警示帶並標示禁止跨越之字樣",
  "廢止使用之開口應張掛安全網；暫不使用之開口應派專人於作業時間全時監視",
  "廢止使用之開口應設置護欄；暫不使用之開口得於周邊噴漆標示後不另設防護"],"a",
 "第25條：雇主對廢止使用之開口應予封閉，對暫不使用之開口應採取加蓋等設備，以防止勞工墜落。第21條並定明護蓋應具足夠強度、防止滑溜掀出移動，臨時性開口之護蓋表面漆黃色並書警告訊息。",
 "How must openings that are abolished and openings temporarily out of use be dealt with?",
 ["Abolished openings must be sealed off; openings temporarily unused must be fitted with covers or the like",
  "Abolished openings must be covered; openings temporarily unused need warning tape and a no-crossing sign",
  "Abolished openings must be netted; openings temporarily unused need a watchman throughout working hours",
  "Abolished openings must be railed; openings temporarily unused need only paint marking around the edges"],
 "Article 25."),

("OSH-36","第27條",3,"營造安全-物體飛落",
 "設置覆網攔截位能小於十二公斤‧公尺之高處物件時，其網目與衝擊強度規定為何？",
 ["方形菱形網目任一邊長不得大於二公分，其餘形狀網目不得大於四平方公分，並能承受直徑四十五公分、重七十五公斤物體自一公尺落下之衝擊",
  "方形菱形網目任一邊長不得大於五公分，其餘形狀網目不得大於十平方公分，並能承受直徑三十公分、重五十公斤物體自二公尺落下之衝擊",
  "方形菱形網目任一邊長不得大於十公分，其餘形狀網目不得大於十五平方公分，並能承受直徑六十公分、重一百公斤物體自三公尺落下之衝擊",
  "方形菱形網目任一邊長不得大於一公分，其餘形狀網目不得大於二平方公分，並能承受直徑二十公分、重二十五公斤物體自五公尺落下之衝擊"],"a",
 "第27條：覆網之方形、菱形網目任一邊長不得大於二公分，其餘形狀之網目不得大於四平方公分，強度應能承受直徑四十五公分、重七十五公斤之物體自高度一公尺處落下之衝擊力，張掛方式比照第22條第1款之安全網規定。第26條並定明位能超過十二公斤‧公尺之高處物件應予固定。",
 "What are the mesh size and impact strength requirements for catch nets for objects under 12 kg·m of potential energy?",
 ["Square or diamond mesh sides not over 2 cm, other shapes not over 4 cm²; withstanding a 45 cm, 75 kg object dropped from 1 m",
  "Square or diamond mesh sides not over 5 cm, other shapes not over 10 cm²; withstanding a 30 cm, 50 kg object dropped from 2 m",
  "Square or diamond mesh sides not over 10 cm, other shapes not over 15 cm²; withstanding a 60 cm, 100 kg object dropped from 3 m",
  "Square or diamond mesh sides not over 1 cm, other shapes not over 2 cm²; withstanding a 20 cm, 25 kg object dropped from 5 m"],
 "Article 27."),

("OSH-36","第27條",2,"營造安全-物體飛落",
 "覆網下之最低點與作業勞工工作平面之距離規定為何？攔截之飛落物件應如何處理？",
 ["覆網下最低點應離作業勞工工作平面三公尺以上，距離不足時應改以其他設施防護；攔截之飛落物件應隨時清理",
  "覆網下最低點應離作業勞工工作平面一公尺以上，距離不足時得加掛第二層覆網；攔截物件應每週清理一次",
  "覆網下最低點應離作業勞工工作平面五公尺以上，距離不足時應停止上方作業；攔截物件應於工程完工後清理",
  "覆網下最低點應離作業勞工工作平面七公尺以上，距離不足時應加設警示線；攔截物件應每月清理並作成紀錄"],"a",
 "第27條：覆網下之最低點應離作業勞工工作平面三公尺以上，如距離不足三公尺應改以其他設施防護；覆網攔截之飛落物件應隨時清理；覆網有劣化、破損、腐蝕等情況應即更換。",
 "How far must the lowest point of a catch net be above the working surface, and how are caught objects handled?",
 ["At least 3 m above the working surface; if less, other protection must be used, and caught objects cleared at all times",
  "At least 1 m above the working surface; if less, a second net may be hung, and caught objects cleared once a week",
  "At least 5 m above the working surface; if less, work above must stop, and caught objects cleared after completion",
  "At least 7 m above the working surface; if less, warning lines are added, and caught objects cleared monthly with a record"],
 "Article 27."),

("OSH-36","第29條",2,"營造安全-物料儲存",
 "營造用各類物料之儲存堆積排列，關於儲存位置及倉庫設備之規定為何？",
 ["應井然有序，且不得儲存於距庫門或升降機二公尺範圍以內或妨礙交通之地點；倉庫內應設警告標示、護圍及防火設備",
  "應井然有序，且不得儲存於距庫門或升降機五公尺範圍以內之地點；倉庫內應設置自動撒水設備及排煙風機",
  "應井然有序，且不得儲存於距庫門或升降機十公尺範圍以內之地點；倉庫內應設置監視系統及門禁管制設備",
  "應井然有序，且不得儲存於距庫門或升降機一公尺範圍以內之地點；倉庫內應設置除濕設備及溫濕度紀錄器"],"a",
 "第29條：營造用各類物料之儲存、堆積及排列應井然有序，不得儲存於距庫門或升降機二公尺範圍以內或足以妨礙交通之地點；倉庫內應設必要之警告標示、護圍及防火設備。",
 "What are the location and warehouse equipment rules for storing construction materials?",
 ["Orderly storage, not within 2 m of a warehouse door or lift or obstructing traffic; warning signs, guards and fire equipment inside",
  "Orderly storage, not within 5 m of a warehouse door or lift; automatic sprinklers and smoke extraction fans inside the warehouse",
  "Orderly storage, not within 10 m of a warehouse door or lift; surveillance systems and access control equipment inside",
  "Orderly storage, not within 1 m of a warehouse door or lift; dehumidifiers and temperature-humidity recorders inside"],
 "Article 29."),

("OSH-36","第30條",1,"營造安全-物料儲存",
 "對於放置各類物料之構造物或平臺，本標準之基本要求為何？",
 ["應具安全之負荷強度，足以承受所放置物料之重量",
  "應每三個月委託技師實施一次結構安全鑑定並報備",
  "應於表面標示核准放置之物料種類與其製造廠商",
  "應以鋼板全面覆蓋並於四周設置高度一公尺護欄"],"a",
 "第30條：雇主對於放置各類物料之構造物或平臺，應具安全之負荷強度。第31條並要求物料儲存不得妨礙火警警報器、滅火器、急救設備、通道、電氣開關及保險絲盒等緊急設備之使用狀態。",
 "What is the basic requirement for structures or platforms used to place materials?",
 ["They must have a safe load-bearing strength for the materials placed on them",
  "They must be structurally appraised by an engineer every three months and filed",
  "They must be marked with the approved material types and their manufacturers",
  "They must be fully covered with steel plate and railed to one metre all around"],
 "Article 30."),

("OSH-36","第31條",2,"營造安全-物料儲存",
 "各類物料之儲存規劃，不得妨礙哪些緊急設備之使用狀態？",
 ["不得妨礙火警警報器、滅火器、急救設備、通道、電氣開關及保險絲盒等緊急設備之使用狀態",
  "不得妨礙工地大門、警衛室、車輛引導人員及施工電梯等進出設施之正常使用狀態",
  "不得妨礙測量儀器、放樣基準點、鋼筋加工區及混凝土泵浦等施工設備之運作狀態",
  "不得妨礙工務所、休息室、盥洗設備及飲用水設備等勞工福利設施之使用狀態"],"a",
 "第31條：雇主對於各類物料之儲存應妥為規劃，不得妨礙火警警報器、滅火器、急救設備、通道、電氣開關及保險絲盒等緊急設備之使用狀態。",
 "Which emergency facilities must material storage not obstruct?",
 ["Fire alarms, extinguishers, first-aid equipment, passageways, electrical switches and fuse boxes",
  "Site gates, guard posts, traffic marshals and construction lifts used for entry and exit",
  "Survey instruments, setting-out benchmarks, rebar yards and concrete pumps used in the works",
  "Site offices, rest rooms, washing facilities and drinking water facilities for worker welfare"],
 "Article 31."),

("OSH-36","第32條",2,"營造安全-鋼材儲存",
 "鋼材之儲存，依規定應辦理之事項為何？",
 ["應預防傾斜滾落必要時以纜索捆紮，場地應為堅固地面，各堆間應有適當距離，並避免置於電線上下方",
  "應每堆高度不得超過一點八公尺，場地應鋪設瀝青混凝土，並於每堆四周設置高度九十公分之護欄",
  "應以帆布全面覆蓋防止鏽蝕，場地應設置排水溝，各堆間距不得小於五公尺並派人全時看管",
  "應依鋼材規格分別存放於獨立倉庫，場地應鋪設木質棧板，並於每日下班前實施數量清點作業"],"a",
 "第32條：鋼材儲存應預防傾斜、滾落，必要時以纜索等適當捆紮；儲存場地應為堅固之地面；各堆鋼材之間應有適當距離；置放地點應避免在電線下方或上方；採起重機吊運時應顯明標示鋼材重量，並避免在電力線下操作。",
 "What are the requirements for storing steel materials?",
 ["Prevent tilting and rolling, lash with cables if needed, use firm ground, keep proper gaps between stacks, avoid power lines",
  "Keep each stack under 1.8 m high, pave the yard with asphalt concrete, and rail each stack to a height of 90 cm",
  "Cover fully with canvas against rust, provide drains, keep stacks at least 5 m apart and post a full-time watchman",
  "Store each steel grade in a separate warehouse, lay timber pallets, and count the stock before the end of each day"],
 "Article 32."),

("OSH-36","第33條",2,"營造安全-砂石堆積",
 "砂、石等之堆積，依規定應辦理之事項為何？",
 ["不得妨礙勞工出入並避免於電線下方，進退路處不得有懸垂物，清倉時應使勞工佩掛安全帶並設監視人員",
  "應堆積成金字塔形且高度不得超過三公尺，進退路處應鋪設鋼板，清倉時應由二人以上共同作業",
  "應以圍籬區隔並設置地磅，進退路處應設置洗車臺，清倉時應先報請當地環保機關同意後為之",
  "應分級存放於獨立料倉，進退路處應設置紅綠燈號誌，清倉時應停止工地其他一切作業並淨空"],"a",
 "第33條：砂、石堆積不得妨礙勞工出入，並避免於電線下方或接近電線之處；堆積場於勞工進退路處不得有任何懸垂物；砂、石清倉時應使勞工佩掛安全帶並設置監視人員；堆積場所應經常灑水或予以覆蓋，以避免塵土飛揚。",
 "What must be observed when stockpiling sand and stone?",
 ["Do not obstruct access or sit under power lines; no overhangs on access routes; use harnesses and a watchman when clearing",
  "Pile in a pyramid no higher than 3 m, lay steel plates on access routes, and have at least two people clear the pile",
  "Fence the area and install a weighbridge, provide a wheel wash on access routes, and get environmental approval to clear",
  "Store by grade in separate bins, install traffic lights on access routes, and stop all other site work when clearing"],
 "Article 33."),

("OSH-36","第34條",2,"營造安全-物料堆放",
 "樁、柱、鋼套管、鋼筋籠等易滑動、滾動物件之堆放，應如何辦理？",
 ["應置於堅實、平坦之處，並加以適當之墊襯、擋樁或其他防止滑動之必要措施",
  "應置於工地邊坡之下方，並以纜索懸吊固定於鄰近之施工架或構造物立柱上",
  "應置於鋪設鋼板之區域，並以堆高機每日搬動一次以避免長期壓陷地面沉陷",
  "應置於倉庫內部之棚架，並依規格分層排列且每層之間應加設金屬隔板固定"],"a",
 "第34條：雇主對於樁、柱、鋼套管、鋼筋籠等易滑動、滾動物件之堆放，應置於堅實、平坦之處，並加以適當之墊襯、擋樁或其他防止滑動之必要措施。第35條並定明磚瓦木塊管料鋼筋等堆放高度不得超過一點八公尺。",
 "How must piles, columns, casings and rebar cages that easily slide or roll be stacked?",
 ["On firm and level ground, with suitable packing, chocks or other necessary measures to prevent sliding",
  "Below the site slope, suspended and fixed by cables to a nearby scaffold or structural column",
  "On a steel-plated area, moved once a day by forklift so that the ground does not settle under load",
  "On racks inside a warehouse, layered by size with a metal divider fixed between each of the layers"],
 "Article 34."),

("OSH-36","第37條",2,"營造安全-管料儲存",
 "管料之儲存，依規定應辦理之事項為何？",
 ["應儲存於堅固平坦之臺架並預防尾端突出滾落，依規格大小長度分別排列，分層疊放每層置一隔板",
  "應儲存於地面之沙坑內以防滾動，依材質分別排列，堆放高度不得超過二公尺並以纜索捆紮固定",
  "應儲存於密閉倉庫並保持通風乾燥，依採購批次排列，每層之間應鋪設帆布以免管料互相碰撞",
  "應儲存於工地圍籬外側之空地，依施工順序排列，並於管料兩端加裝橡膠護套後以鐵鏈鎖固"],"a",
 "第37條：管料應儲存於堅固而平坦之臺架上，並預防尾端突出、伸展或滾落；依規格大小及長度分別排列以利取用；分層疊放，每層中置一隔板以均勻壓力並防止管料滑出；管料之置放應避免在電線上方或下方。",
 "What are the requirements for storing pipe materials?",
 ["On firm level racks preventing ends protruding or rolling, sorted by size and length, stacked in layers with a divider",
  "In a ground sand pit to stop rolling, sorted by material, stacked no higher than 2 m and lashed with cables",
  "In a sealed warehouse kept ventilated and dry, sorted by purchase batch, with canvas laid between the layers",
  "On open ground outside the site fence, sorted by work sequence, with rubber caps on both ends and chained"],
 "Article 37."),

("OSH-36","第38條",1,"營造安全-條文沿革",
 "營造安全衛生設施標準第三十八條之現行狀態為何？物料儲存章之現行規範重點為何？",
 ["該條業經刪除；物料之儲存章現行規範重點為儲存位置、負荷強度、緊急設備不受妨礙及各類材料堆放方式",
  "該條仍為現行有效條文；物料之儲存章現行規範重點僅為袋裝材料堆放層數與交錯方向之技術規定",
  "該條業經刪除；物料之儲存事項改依危害性化學品標示及通識規則有關貯存規定辦理不適用本標準",
  "該條僅暫停適用；物料之儲存於該條恢復適用前，得由事業單位依其內部管理規定自行決定辦理"],"a",
 "第38條已刪除。本標準第三章物料之儲存現行內容包括第29條儲存位置與倉庫設備、第30條平臺負荷強度、第31條不得妨礙緊急設備、第32條至第37條鋼材、砂石、易滾動物件、一般建材、袋裝材料及管料之堆放規定。",
 "What is the status of Article 38, and what does the materials storage chapter now cover?",
 ["It has been deleted; the chapter now covers storage location, load strength, unobstructed emergency gear and stacking rules",
  "It remains in force; the chapter now covers only the layer count and alternating direction rules for bagged materials",
  "It has been deleted; material storage is instead governed by the hazardous chemical labelling and communication rules",
  "It is merely suspended; until it revives, enterprises may decide material storage under their own internal rules"],
 "Article 38 (deleted)."),

("OSH-36","第39條",1,"營造安全-施工架",
 "何種情形下雇主應設置適當之施工架？",
 ["對於不能藉高空工作車或其他方法安全完成之二公尺以上高處營造作業，應設置適當之施工架",
  "對於不能藉高空工作車或其他方法安全完成之五公尺以上高處營造作業，應設置適當之施工架",
  "對於所有建築物外牆之粉刷、貼磚及油漆作業，不論高度一律應設置適當之鋼管施工架",
  "對於工期超過六個月且樓層數達五層以上之建築工程，應於開工前設置適當之施工架"],"a",
 "第39條：雇主對於不能藉高空工作車或其他方法安全完成之二公尺以上高處營造作業，應設置適當之施工架。第40條並定明特定施工架及施工構臺之構築拆除，應由專任工程人員或執業技師設計並簽章確認。",
 "When must the employer erect suitable scaffolding?",
 ["For construction work at 2 m or more that cannot be safely done by aerial work vehicle or other means",
  "For construction work at 5 m or more that cannot be safely done by aerial work vehicle or other means",
  "For all exterior wall plastering, tiling and painting work on buildings, regardless of the working height",
  "For building projects lasting over six months and reaching five storeys, before construction commences"],
 "Article 39."),

("OSH-36","第44條",1,"營造安全-施工架",
 "對於施工架及施工構臺之維護，本標準課予雇主之基本義務為何？",
 ["應經常予以適當之保養，並維持各部分之牢穩",
  "應每半年委託原設計技師實施一次整體結構檢測",
  "應於每次使用前後拆解檢查各構件並更換插銷",
  "應於架體外側懸掛保養責任人姓名及聯絡電話"],"a",
 "第44條：雇主對於施工架及施工構臺，應經常予以適當之保養並維持各部分之牢穩。第45條並列舉維持穩定之七款規定，包括不得與模板支撐連接、與構造物連接間隔垂直不超過五點五公尺、水平不超過七點五公尺等。",
 "What is the employer's basic duty for maintaining scaffolds and work platforms?",
 ["To maintain them properly at all times and keep every part firm and stable",
  "To have the original design engineer test the whole structure every six months",
  "To dismantle and inspect every member and replace pins before and after each use",
  "To hang the name and phone number of the maintenance officer on the outer frame"],
 "Article 44."),

("OSH-36","第46條",2,"營造安全-施工架",
 "施工架上物料之運送、儲存及荷重分配，依規定應如何辦理？",
 ["應避免施工架發生突然振動，不得放置或運轉動力機械設備或作為固定混凝土輸送管之用，載重限制應明顯標示",
  "應以人力搬運為原則並禁止使用吊索，動力機械設備得置於架上但須加設防震墊，載重限制得口頭告知",
  "應於架體中央集中堆置以維持平衡，動力機械設備得固定於架上使用，載重限制由工地負責人自行認定",
  "應於每日下班前將物料全部清空，動力機械設備得於白天置於架上，載重限制僅須記載於施工計畫內"],"a",
 "第46條：於施工架上放置或搬運物料時應避免施工架突然振動；施工架上不得放置或運轉動力機械及設備，或以施工架作為固定混凝土輸送管、垃圾管槽之用（無作業危險之虞者除外）；載重限制應於明顯易見處明確標示，不得超過荷重限制並避免不均衡。",
 "How must material handling, storage and load distribution on scaffolds be managed?",
 ["Avoid sudden vibration, do not place or run powered machinery or fix concrete delivery pipes on it, and post load limits clearly",
  "Handle by hand only and ban slings; powered machinery may sit on the scaffold on anti-vibration pads; limits may be told orally",
  "Stack centrally to keep balance; powered machinery may be fixed on the scaffold; the site manager decides the load limits",
  "Clear all materials before the end of each day; powered machinery may sit on it by day; limits appear only in the work plan"],
 "Article 46."),

("OSH-36","第48條、第49條",1,"營造安全-條文沿革",
 "營造安全衛生設施標準第四十九條之現行狀態為何？高度二公尺以上施工架上作業之工作臺規定現依何條？",
 ["該條業經刪除；施工架上工作臺寬度四十公分以上、踏板縫隙三公分以下等規定，現依第四十八條辦理",
  "該條仍為現行有效條文；施工架上工作臺之寬度與踏板規格全部依該條規定辦理，不適用其他條文",
  "該條業經刪除；施工架上工作臺之規定改依高空工作車安全檢查構造標準有關工作臺規定辦理",
  "該條僅停止適用而未刪除；施工架上工作臺於恢復適用前，由雇主參照國家標準自行決定其規格"],"a",
 "第49條已刪除。現行高度二公尺以上施工架上作業之工作臺規定見第48條：應供給足夠強度之工作臺，寬度在四十公分以上並舖滿密接踏板，支撐點二處以上並綁結固定，踏板間縫隙不得大於三公分，工作臺應低於施工架立柱頂點一公尺以上。",
 "What is the status of Article 49, and which article now governs work platforms on scaffolds above 2 m?",
 ["It has been deleted; platform width of 40 cm and board gaps under 3 cm are now governed by Article 48",
  "It remains in force; platform width and board specifications on scaffolds are governed solely by that article",
  "It has been deleted; scaffold work platforms are instead governed by the aerial work vehicle construction standards",
  "It is only suspended, not deleted; until it revives, employers set platform specifications by national standards"],
 "Article 49 (deleted)."),

("OSH-36","第50條、第51條",1,"營造安全-條文沿革",
 "營造安全衛生設施標準第五十條之現行狀態為何？施工架上人員上下設備之現行規定為何？",
 ["該條業經刪除；施工架上人員上下設備應檢查穩固性並補強，任一處步行至最近上下設備距離應在三十公尺以下",
  "該條仍為現行有效條文；施工架上人員上下設備之間距及檢查方式全部依該條規定辦理不適用他條",
  "該條業經刪除；施工架上人員上下設備改依固定式起重機安全檢查構造標準有關階梯規定辦理",
  "該條僅暫緩施行；施工架上人員上下設備於施行前，得由工地負責人依現場狀況自行決定其配置"],"a",
 "第50條已刪除。現行施工架上設置人員上下設備之規定見第51條：應確實檢查施工架各部分穩固性，必要時適當補強，並將上下設備架設處之立柱與建築物堅實部分牢固連接；施工架任一處步行至最近上下設備之距離應在三十公尺以下。",
 "What is the status of Article 50, and what now governs access equipment on scaffolds?",
 ["It has been deleted; stability must be checked and reinforced, and any point must be within 30 m of the nearest access",
  "It remains in force; the spacing and inspection of scaffold access equipment are governed solely by that article",
  "It has been deleted; scaffold access equipment is instead governed by the stationary crane construction standards",
  "It is merely deferred; until it starts, the site manager may decide access arrangements according to site conditions"],
 "Article 50 (deleted)."),

("OSH-36","第52條",2,"營造安全-施工架",
 "構築施工架時，有鄰近結構物之周遭或跨越工作走道者，應於其下方設置何種設施？",
 ["應於其下方設計斜籬及防護網等，以防止物體飛落引起災害",
  "應於其下方設置移動式圍籬及警示帶，以管制人員不得通行",
  "應於其下方設置臨時性構臺及扶手，以供勞工安全通行使用",
  "應於其下方設置排水溝及集水井，以防止雨水積聚影響通行"],"a",
 "第52條：雇主構築施工架時，有鄰近結構物之周遭或跨越工作走道者，應於其下方設計斜籬及防護網等，以防止物體飛落引起災害。第53條並定明鄰近或跨越車輛通道者，應於該通道設置護籠等安全設施。",
 "What must be provided below a scaffold that is near a structure or spans a walkway?",
 ["Inclined fans and protective nets designed below it, to prevent falling objects causing accidents",
  "Movable fencing and warning tape below it, so that people are barred from passing through",
  "A temporary platform and handrails below it, so that workers may pass through in safety",
  "Drainage channels and sumps below it, so that rainwater does not pond and hinder passage"],
 "Article 52."),

("OSH-36","第53條",1,"營造安全-施工架",
 "構築施工架時，有鄰近或跨越車輛通道者，應於該通道設置何種安全設施？",
 ["應於該通道設置護籠等安全設施，以防車輛之碰撞危險",
  "應於該通道設置減速丘及測速照相，以限制車輛之車速",
  "應於該通道設置洗車臺及沉砂池，以避免車輛帶泥上路",
  "應於該通道設置臨時號誌及枕木，以引導車輛依序通行"],"a",
 "第53條：雇主構築施工架時，有鄰近或跨越車輛通道者，應於該通道設置護籠等安全設施，以防車輛之碰撞危險。第52條則規範鄰近結構物或跨越工作走道時應於下方設置斜籬及防護網。",
 "What safety facility must be provided where a scaffold adjoins or spans a vehicle route?",
 ["Protective cages or the like on that route, to guard against vehicle collision",
  "Speed humps and speed cameras on that route, to restrict the speed of vehicles",
  "A wheel wash and settling pit on that route, to stop vehicles carrying mud out",
  "Temporary signals and sleepers on that route, to guide vehicles through in order"],
 "Article 53."),

("OSH-36","第54條",3,"營造安全-原木施工架",
 "原木施工架之立柱間距、接頭搭接長度及捆綁處數之規定為何？",
 ["立柱排列間距不大於二點五公尺；搭接式接頭搭接部分應有一公尺以上長度並捆綁二處以上；對接式應以一點八公尺以上補強材捆綁四處以上",
  "立柱排列間距不大於一點五公尺；搭接式接頭搭接部分應有二公尺以上長度並捆綁三處以上；對接式應以三公尺以上補強材捆綁六處以上",
  "立柱排列間距不大於三點五公尺；搭接式接頭搭接部分應有零點五公尺以上長度並捆綁一處以上；對接式應以一公尺以上補強材捆綁二處以上",
  "立柱排列間距不大於五公尺；搭接式接頭搭接部分應有三公尺以上長度並捆綁四處以上；對接式應以五公尺以上補強材捆綁八處以上"],"a",
 "第54條：原木施工架立柱應垂直或稍向構造物傾斜，排列間距不大於二點五公尺；立柱延伸接頭屬搭接式者搭接部分應有一公尺以上長度且捆綁二處以上，屬對接式者應以一點八公尺以上長度之補強材捆綁於二對接立柱並捆綁四處以上。",
 "What are the column spacing, joint lap length and lashing counts for timber scaffolds?",
 ["Columns spaced not over 2.5 m; lap joints lapped at least 1 m and lashed at 2 or more points; butt joints use a 1.8 m splice lashed at 4 or more points",
  "Columns spaced not over 1.5 m; lap joints lapped at least 2 m and lashed at 3 or more points; butt joints use a 3 m splice lashed at 6 or more points",
  "Columns spaced not over 3.5 m; lap joints lapped at least 0.5 m and lashed at 1 or more point; butt joints use a 1 m splice lashed at 2 or more points",
  "Columns spaced not over 5 m; lap joints lapped at least 3 m and lashed at 4 or more points; butt joints use a 5 m splice lashed at 8 or more points"],
 "Article 54."),

("OSH-36","第54條",3,"營造安全-原木施工架",
 "原木施工架支持工作臺之兩相鄰踏腳桁間距，依踏板厚度應如何限制？",
 ["以不及四公分厚之踏板構築者不得超過一公尺；四至五公分厚者不得超過一點五公尺；五公分厚以上者不得超過二公尺",
  "以不及四公分厚之踏板構築者不得超過二公尺；四至五公分厚者不得超過三公尺；五公分厚以上者不得超過四公尺",
  "以不及四公分厚之踏板構築者不得超過零點五公尺；四至五公分厚者不得超過一公尺；五公分厚以上者不得超過一點五公尺",
  "以不及四公分厚之踏板構築者不得超過一點五公尺；四至五公分厚者不得超過二公尺；五公分厚以上者不得超過二點五公尺"],"a",
 "第54條第7款第5目：支持工作臺之兩相鄰踏腳桁之間距，應視預期載重及工作臺舖板之材質厚度定之；以不及四公分厚之踏板構築者間距不得超過一公尺，以四至五公分厚之踏板構築者不得超過一點五公尺，以五公分厚以上之踏板構築者不得超過二公尺。",
 "How is the spacing of adjacent ledgers supporting a timber scaffold platform limited by board thickness?",
 ["Boards under 4 cm thick: not over 1 m; boards 4 to 5 cm thick: not over 1.5 m; boards 5 cm or thicker: not over 2 m",
  "Boards under 4 cm thick: not over 2 m; boards 4 to 5 cm thick: not over 3 m; boards 5 cm or thicker: not over 4 m",
  "Boards under 4 cm thick: not over 0.5 m; boards 4 to 5 cm thick: not over 1 m; boards 5 cm or thicker: not over 1.5 m",
  "Boards under 4 cm thick: not over 1.5 m; boards 4 to 5 cm thick: not over 2 m; boards 5 cm or thicker: not over 2.5 m"],
 "Article 54(7)(5)."),

("OSH-36","第55條",3,"營造安全-圓竹施工架",
 "使用圓竹構築之施工架，其型式限制、立柱間距及橫檔垂直間距規定為何？",
 ["以獨立直柱式施工架為限；立柱間距不得大於一點八公尺；橫檔垂直間距不得大於二公尺且最低位置不高於地面二公尺",
  "以懸吊式施工架為限；立柱間距不得大於二點五公尺；橫檔垂直間距不得大於四公尺且最低位置不高於地面三公尺",
  "以框式施工架為限；立柱間距不得大於三公尺；橫檔垂直間距不得大於五公尺且最低位置不高於地面五公尺",
  "以棧橋式施工架為限；立柱間距不得大於一公尺；橫檔垂直間距不得大於一公尺且最低位置不高於地面一公尺"],"a",
 "第55條：圓竹構築之施工架以獨立直柱式施工架為限；立柱間距不得大於一點八公尺；主柱橫檔延伸應於節點處搭接並以十號以下鍍鋅鐵線紮結牢固；橫檔垂直間距不得大於二公尺，最低位置不得高於地面二公尺以上。",
 "What type limit, column spacing and ledger vertical spacing apply to bamboo scaffolds?",
 ["Independent upright type only; columns not over 1.8 m apart; ledgers not over 2 m apart with the lowest not above 2 m",
  "Suspended type only; columns not over 2.5 m apart; ledgers not over 4 m apart with the lowest not above 3 m",
  "Frame type only; columns not over 3 m apart; ledgers not over 5 m apart with the lowest one not above 5 m",
  "Trestle type only; columns not over 1 m apart; ledgers not over 1 m apart with the lowest one not above 1 m"],
 "Article 55."),

("OSH-36","第58條",2,"營造安全-懸臂式施工架",
 "懸臂式施工架之設置，依規定應辦理之事項為何？",
 ["應依長度斷面設計足夠強度必要時以斜撐補強並與構造物錨定；各部分應以構造物堅固部分支持；托架應設斜撐並與牆壁紮牢",
  "應以鋼索懸吊於上層樓板並設安全係數十以上之吊纜；各部分得以施工架立柱支持；托架僅須以膨脹螺栓固定即可",
  "應設置於建築物室內側並以千斤頂頂撐固定；各部分得以模板支撐支持；托架應以鐵線捆綁於鄰近之鋼筋上",
  "應由工地負責人依經驗決定其斷面尺寸；各部分得以砂包壓重固定；托架應每週實施一次目視檢查並紀錄"],"a",
 "第58條：懸臂式施工架應依其長度及斷面設計足夠之強度，必要時以斜撐補強並與構造物妥為錨定；施工架各部分應以構造物之堅固部分支持之；工作臺置於嵌入牆內之托架上者，該托架應設斜撐並與牆壁紮牢。",
 "What requirements apply to cantilever scaffolds?",
 ["Design adequate strength by length and section, brace and anchor to the structure, support on solid parts, brace and tie brackets to the wall",
  "Suspend by wire ropes from the floor above with a safety factor of ten, support on scaffold columns, fix brackets with expansion bolts only",
  "Erect indoors and hold with jacks, support on formwork shoring, and lash brackets to nearby reinforcing bars with steel wire",
  "Let the site manager set the section size by experience, hold with sandbag ballast, and inspect brackets visually each week"],
 "Article 58."),

("OSH-36","第60條之1",3,"營造安全-系統式施工架",
 "系統式施工架之構築，關於連接方式與材質之規定為何？",
 ["立柱橫桿斜撐應以輪盤八角盤及插銷扣件連接成牢固系統，交叉處不得以活扣或鐵線代替；插銷扣件採SS400或同等以上材質",
  "立柱橫桿斜撐得以鐵線或活扣紮結成系統構架，交叉處應加設木楔補強；輪盤插銷扣件採鑄鐵或塑鋼等具耐蝕性之材質即可",
  "立柱橫桿斜撐應以焊接方式於現場一體成型，不得使用任何插銷或扣件；輪盤插銷扣件採鋁合金或不鏽鋼等輕質金屬材質",
  "立柱橫桿斜撐得以繩索捆綁後再加鋼夾固定，交叉處應以水泥砂漿包覆；輪盤插銷扣件採一般碳鋼且無須另作表面處理"],"a",
 "第60條之1：系統式施工架所有立柱、橫桿及斜撐等應以輪盤、八角盤或其他類似功能構件及插銷扣件等組配件連接成緊密牢固之系統構架，連接交叉處不得以各式活扣緊結或鐵線代替；金屬材料等應符合CNS4750；輪盤、插銷扣件及續連端之金屬材料應採SS400或具同等以上抗拉強度之材質。",
 "What are the connection and material rules for system scaffolds?",
 ["Columns, ledgers and braces join via rosettes and pin couplers into a tight system; no snap ties or wire at crossings; SS400 or better metal",
  "Columns, ledgers and braces may be tied with wire or snap ties, with wedges at crossings; cast iron or plastic-steel couplers suffice",
  "Columns, ledgers and braces must be welded into one piece on site with no pins or couplers; aluminium or stainless couplers are used",
  "Columns, ledgers and braces may be roped and clamped, with mortar wrapped at crossings; plain carbon steel couplers need no finish"],
 "Article 60-1."),

("OSH-36","第62條",1,"營造安全-鋼管識別",
 "同一作業場所使用之鋼管，其厚度、外徑及強度相異時，為防止混淆應如何處理？",
 ["應分別對該鋼管以顏色或其他方式標示等，使勞工易於識別",
  "應將不同規格之鋼管分別存放於不同工區並禁止交互使用",
  "應由工地負責人於每日作業前召集勞工說明規格差異事項",
  "應將不同規格之鋼管全數退回供應商換為同一規格之鋼管"],"a",
 "第62條：雇主對於同一作業場所使用之鋼管，其厚度、外徑及強度相異時，為防止鋼管之混淆，應分別對該鋼管以顏色或其他方式標示等，使勞工易於識別。",
 "How must steel tubes of differing thickness, diameter or strength at one site be handled?",
 ["Each must be marked by colour or another method so that workers can identify them easily",
  "Tubes of different specification must be stored in separate zones and never used together",
  "The site manager must brief workers on the specification differences before work each day",
  "All tubes of differing specification must be returned to the supplier and exchanged for one type"],
 "Article 62."),

("OSH-36","第62條之1",2,"營造安全-施工構臺",
 "施工構臺之設置，關於支柱、連結部分及覆工板間隙之規定為何？",
 ["支柱應埋入適當深度或襯以墊板座鈑防止滑動下沈；連結接觸安裝部分應以螺栓鉚釘固定；高度二公尺以上構臺覆工板間隙應在三公分以下",
  "支柱應以砂石回填夯實並加設混凝土基座；連結部分得以鐵線捆綁固定；高度二公尺以上構臺覆工板間隙應在十公分以下",
  "支柱應直接置於原地面不得埋入以利拆除；連結部分應全面焊接固定；高度五公尺以上構臺覆工板間隙應在五公分以下",
  "支柱應每三公尺設置一支且不得使用墊板；連結部分得以插銷鬆配合；高度十公尺以上構臺覆工板間隙應在一公分以下"],"a",
 "第62條之1：施工構臺支柱應依土壤性質埋入適當深度或於柱腳部襯以墊板、座鈑等防止滑動或下沈；支柱、水平繫材、斜撐材及構臺之梁等連結、接觸及安裝部分應以螺栓或鉚釘等金屬連結器材固定；高度二公尺以上構臺之覆工板等板料間隙應在三公分以下；構臺寬度應足供機具運轉通行並預留起重機外伸撐座場地。",
 "What rules govern posts, connections and decking gaps of construction work platforms?",
 ["Posts embedded deep enough or on base plates; connections fixed by bolts or rivets; decking gaps under 3 cm for platforms over 2 m",
  "Posts backfilled with compacted gravel on concrete pads; connections may be wire-tied; decking gaps under 10 cm above 2 m",
  "Posts set on existing ground without embedment for easy removal; connections fully welded; gaps under 5 cm above 5 m",
  "Posts every 3 m with no base plates allowed; connections loosely pinned; decking gaps under 1 cm for platforms over 10 m"],
 "Article 62-1."),

("OSH-36","第62條之1",2,"營造安全-施工構臺",
 "施工構臺之設置寬度，依規定應如何考量？",
 ["設置寬度應足供所需機具運轉通行之用，並依施工計畫預留起重機外伸撐座伸展及材料堆置之場地",
  "設置寬度一律應在四公尺以上，且不得於構臺上堆置任何材料或設置起重機具之外伸撐座",
  "設置寬度依構臺高度決定，高度每增加一公尺應加寬零點五公尺，並不得供車輛機械通行使用",
  "設置寬度由工地負責人依現場地形自行決定，僅須確保勞工得以側身通過即符合本標準規定"],"a",
 "第62條之1第4款：構臺設置寬度應足供所需機具運轉通行之用，並依施工計畫預留起重機外伸撐座伸展及材料堆置之場地。第62條之2並要求惡劣氣候、四級以上地震後或局部解體變更後，作業前應確認主要構材狀況。",
 "How must the width of a construction work platform be determined?",
 ["Wide enough for the machinery to travel and operate, with space reserved for crane outriggers and material stacking",
  "At least 4 m in all cases, with no materials stacked on it and no crane outriggers allowed to be deployed on it",
  "By platform height, adding 0.5 m of width per extra metre of height, and it may not be used by vehicle machinery",
  "By the site manager according to terrain, needing only enough room for a worker to pass through sideways"],
 "Article 62-1(4)."),

("OSH-36","第63條",3,"營造安全-露天開挖",
 "從事露天開挖作業前，為防止地面崩塌及損壞地下埋設物，應調查之內容為何？",
 ["地面形狀地層地質及鄰近建築物、地面龜裂與地下水位及地層凍結狀況、有無地下埋設物、地下有無危險或有害氣體",
  "工程預算及工期、承攬商之財務狀況、鄰近土地公告現值、開挖土方之處理場所及運輸路線之交通流量統計資料",
  "勞工人數及年齡分布、機械操作人員之證照、工地周邊住戶意見、開挖期間之氣象預報與空氣品質指標數值",
  "鄰近工地之施工進度、材料供應商之名冊、開挖機具購置年份、工地監視系統之攝影機配置與錄影保存時數"],"a",
 "第63條：露天開挖作業前應就作業地點及其附近施以鑽探、試挖或其他適當方法調查：一、地面形狀、地層、地質、鄰近建築物及交通影響情形；二、地面有否龜裂、地下水位狀況及地層凍結狀況；三、有無地下埋設物及其狀況；四、地下有無高溫、危險或有害之氣體、蒸氣及其狀況。",
 "What must be surveyed before open excavation to prevent ground collapse and damage to buried services?",
 ["Ground form, strata, geology and nearby buildings; cracking, groundwater and frozen ground; buried services; hazardous gases",
  "Project budget and schedule, contractor finances, land values nearby, and traffic counts on the spoil haulage routes",
  "Worker numbers and ages, operator licences, opinions of nearby residents, and weather forecasts and air quality indices",
  "Progress of nearby sites, the supplier list, the purchase year of the excavators, and the site CCTV layout and recording hours"],
 "Article 63."),

("OSH-36","第63條",2,"營造安全-露天開挖",
 "依露天開挖調查結果所擬訂之開挖計畫，其內容應包括哪些事項？",
 ["應包括開挖方法、順序、進度、使用機械種類、降低水位、穩定地層方法及土壓觀測系統等事項",
  "應包括工程契約金額、付款辦法、保固年限、爭議處理程序及承攬商保險理賠之申請流程等事項",
  "應包括勞工出勤紀錄、加班費計算方式、伙食安排、宿舍配置及每日朝會宣導主題等管理事項",
  "應包括土方外運車輛之車牌、司機姓名、每日趟次、過磅單編號及棄土場收容證明等文件資料"],"a",
 "第63條第2項：依調查結果擬訂之開挖計畫，其內容應包括開挖方法、順序、進度、使用機械種類、降低水位、穩定地層方法及土壓觀測系統等。第64條並規範人工開挖自由面之傾斜度與開挖面高度限制。",
 "What must the excavation plan drawn up from the survey results contain?",
 ["Excavation method, sequence, schedule, machine types, dewatering, ground stabilisation and earth pressure monitoring",
  "Contract value, payment terms, warranty period, dispute procedures and the contractor's insurance claim process forms",
  "Worker attendance records, overtime calculation, catering, dormitory layout and the daily toolbox meeting topics",
  "Spoil truck plate numbers, driver names, daily trips, weighbridge ticket numbers and disposal site receipt copies"],
 "Article 63(2)."),

("OSH-36","第67條",2,"營造安全-露天開挖",
 "於接近磚壁或水泥隔牆等構造物之場所從事開挖作業前，應採取何種預防設施？",
 ["應採取地盤改良及構造物保護等有效之預防設施，以防止構造物損壞變形或倒塌致危害勞工",
  "應先請鄰房所有權人簽署同意書並辦理鑑定，開挖期間得免除任何地盤改良或保護措施",
  "應於構造物外側噴塗警示漆並張貼裂縫觀測貼片，發現裂縫擴大時再行辦理補強作業",
  "應將開挖深度限制在一公尺以內並以人工方式施作，即可免除地盤改良及構造物保護"],"a",
 "第67條：雇主於接近磚壁或水泥隔牆等構造物之場所從事開挖作業前，為防止構造物損壞、變形或倒塌致危害勞工，應採取地盤改良及構造物保護等有效之預防設施。第68條並要求為防止損壞地下管線，應懸吊或支撐管線或予以移設，並指派專人現場指揮。",
 "What preventive measures are required before excavating near brick walls or cement partitions?",
 ["Effective measures such as ground improvement and structure protection, to stop damage, deformation or collapse harming workers",
  "A consent form signed by the neighbouring owner plus a survey, after which no ground or structure measures are needed",
  "Warning paint and crack monitoring patches on the outside, with reinforcement only once cracks are seen to widen",
  "Limiting the excavation depth to one metre and digging by hand, which exempts ground improvement and protection"],
 "Article 67."),
]
