# -*- coding: utf-8 -*-
# 第 7 批（E）：職業災害勞工職業重建補助辦法、職業災害預防補助辦法、直轄市及縣市政府協助職災勞工重返職場補助辦法、
#              財團法人職業災害預防及重建中心監督及管理辦法、危險性機械或設備代行檢查機構管理規則、勞動檢查員遴用及專業訓練辦法、勞動檢查員執行職務迴避辦法
RB = "OSH-81"; PV = "OSH-84"; RW = "OSH-86"; RC = "OSH-87"; AI = "OSH-88"; IR = "OSH-89"; IA = "OSH-90"
Q = [
# ---------- 職業災害勞工職業重建補助辦法（103/7/14） ----------
(RB,"第3條",2,"職業重建-事項",
 "職業災害勞工職業重建包括哪些事項？其對象為何？",
 ["心理輔導及社會適應、工作能力評估及強化、職務再設計、職業輔導評量、職業訓練、就業服務追蹤及輔導再就業、相關研究；經醫師診斷為職業傷病致工作能力降低或喪失者","僅職業訓練；所有勞工","僅就業媒合；失業者","僅心理輔導；身心障礙者"],"a",
 "第3條：心理輔導及社會適應、工作能力評估及強化、職務再設計、職業輔導評量、職業訓練、就業服務追蹤及輔導再就業、其他職業重建研究。第4條：對象為勞工發生職業災害後經醫師診斷為職業傷病致工作能力降低或喪失者。第6條：工作能力評估及強化指提供工作分析及功能性體能測驗並進行增進生心理功能之治療復健及訓練，單位應置職能或物理治療師一人以上，個案管理每四十人置個案管理員一人。第8條：職務再設計指協調改善工作環境機具設備調整職務內容方法條件或應用就業輔助器具，應置相關系所畢業有一年以上經驗者二人以上。第9條：職業輔導評量每七人置評量員一人並設專用評量室。",
 "Vocational rehabilitation for occupational accident workers covers, and targets:",
 ["Psychological counseling and social adaptation, work capacity assessment and strengthening, job redesign, vocational evaluation, vocational training, employment services and follow-up, and research; workers diagnosed with occupational injury or disease whose work capacity is reduced or lost","Vocational training only; all workers","Job matching only; the unemployed","Counseling only; persons with disabilities"],
 "Articles 3–9."),

(RB,"第11條",3,"職業重建-就業服務人力",
 "辦理職災勞工就業服務之單位，就業媒合服務每月服務量每幾人置就業服務員一人？支持性就業服務每幾人一人？",
 ["三十人；六人","五十人；十人","十人；三人","一百人；二十人"],"a",
 "第11條：依法設立之就業服務機構或身心障礙者就業服務機構或受委託辦理者；就業媒合服務每月服務量每三十人置就業服務員一人（網際網路求職不計入），支持性就業服務每六人置一人，不足者以該數計。第13條：辦理二款以上服務應以個案管理方式為之。第14條：個案管理員及就業服務員應具社工師職能治療師或特教教師證書、相關科系畢業、非相關科系畢業服務滿一年且訓練八十小時或訓練一百六十小時、高中職畢業服務滿二年且訓練二百四十小時或訓練四百小時之一；職業輔導評量員另應受評量訓練一百六十小時。",
 "Employment service units for occupational accident workers need one employment specialist per how many monthly job-matching clients, and per how many supported-employment clients?",
 ["30; 6","50; 10","10; 3","100; 20"],
 "Articles 11–14."),

(RB,"第15條",3,"職業重建-申請與核銷",
 "申請職業重建補助之單位應於每年何時前向職安署提出申請？計畫完成後幾日內送成果核銷？未確實執行者列為幾年內不予補助對象？",
 ["二月或七月底前；三十日；五年","一月底前；十日；三年","六月底前；六十日；一年","十二月底前；九十日；十年"],"a",
 "第15條：應訂定實施計畫書（單位名稱計畫名稱目標人力主持人資歷經費概算方法期間預期成效）並填申請書於每年二月或七月底前向職安署提出。第16條：延續性者首年提出總計畫分年申請。第17條：職安署審核後組職業災害預防及重建補助審查委員會審議，每年二月底前將前一年度補助情形報中央主管機關備查。第19條：得分期撥款並期中期末審查。第20條：完成後三十日內送成果核銷，剩餘款繳回。第21條：得實地查訪稽核及績效評估。第22條：未確實執行或無故拒絕查核者撤回補助追回款項並列為五年內不予補助對象。",
 "Vocational rehabilitation subsidy applications are due by, results for settlement within, and non-performers are barred for:",
 ["The end of February or July; 30 days; 5 years","End of January; 10 days; 3 years","End of June; 60 days; 1 year","End of December; 90 days; 10 years"],
 "Articles 15–22."),

# ---------- 職業災害預防補助辦法（103/7/14） ----------
(PV,"第2條",2,"職災預防補助-公告",
 "中央主管機關應於每年何時前公告下年度職業災害預防重點及優先補助事項？",
 ["十月底前（特殊需要得隨時公告）","一月底前","六月底前","三月底前"],"a",
 "第2條：申請職災勞工保護法第10條第1項第1至5款及第8款職業災害預防事項之補助依本辦法辦理；中央主管機關應於每年十月底前公告下年度職業災害預防重點及優先補助事項，特殊需要得隨時公告。第3條：研究及規劃補助單位為大專校院或職災研究機構，主持人具教授副教授或助理教授合計三年以上或相當專業人員三年以上並有主持研究能力。第4條：培訓職業疾病醫師為全國性醫學會或設醫學系所附設醫院開辦職業疾病門診者。第5條：培訓職業衛生護理人員為全國性護理學協會或設護理科系所。",
 "The central authority must announce next year's occupational accident prevention priorities by:",
 ["The end of October (or any time for special needs)","End of January","End of June","End of March"],
 "Articles 2–5."),

(PV,"第7條",3,"職災預防補助-教育訓練單位",
 "申請補助勞工安全衛生教育訓練之單位應符合何條件？每一計畫主持人一次以申請幾個計畫為限？",
 ["事業單位職訓機構及相關團體、訓練設施儀器完善師資健全、主持人具安全衛生教學經驗三年以上或訓練實務五年以上；一個","任何人；不限","僅大學；三個","僅政府機關；二個"],"a",
 "第6條：技術性專業性業務補助單位主持人應具安全衛生類科高考及格且實務三年以上或大專畢業實務五年以上。第7條：教育訓練補助單位為事業單位職業訓練機構及相關團體，訓練設施及儀器設備完善師資健全，主持人具安全衛生教學經驗三年以上或訓練實務五年以上。第8條：宣導單位主持人具宣導實務三年以上。第9條：每年二月或七月底前向職安署申請。第10條：每年各款以一個計畫且每一主持人一次以一個計畫為限。第14條：完成後三十日內核銷。第16條：未確實執行或拒絕查核者撤回補助追回款項並列五年內不予補助。",
 "Units applying for OSH training subsidies must, and each project leader may apply for how many projects at a time?",
 ["Be enterprises, training institutions or related groups with adequate facilities and faculty, led by someone with 3+ years of OSH teaching or 5+ years of training experience; one","Anyone; unlimited","Universities only; three","Government agencies only; two"],
 "Articles 6–10 and 14–16."),

# ---------- 直轄市及縣市政府辦理協助職業災害勞工重返職場補助辦法（115/6/29） ----------
(RW,"第2條",2,"重返職場補助-項目",
 "直轄市及縣市政府協助職災勞工重返職場之補助項目有哪三種？",
 ["輔助設施補助、職能復健津貼、僱用職業災害勞工補助","失業給付、退休金、資遣費","醫療費、喪葬費、撫卹金","訓練費、交通費、住宿費"],"a",
 "第2條：補助項目為輔助設施補助、職能復健津貼、僱用職業災害勞工補助。第3條：雇主依災保法第67條提供職災勞工從事工作必要之輔助設施得向地方主管機關申請補助，應於購置前或提供後九十日內備具申請書、僱用證明、認可職能復健專業機構開立之復工計畫或評估報告書、實地訪視同意書、改善前後照片、發票收據、未依身權法領取補助之聲明書。第4條：地方主管機關應於六十日內完成審核。第4條之1：購置前申請者應於核定送達之日起一百八十日內完成購置請領。",
 "The three local-government subsidies for returning occupational accident workers to work are:",
 ["Assistive facility subsidies, vocational rehabilitation allowances, and subsidies for employing occupational accident workers","Unemployment, pension, severance","Medical, funeral, condolence","Training, transport, lodging"],
 "Articles 2–4-1."),

(RW,"第5條",3,"重返職場補助-輔助設施限額",
 "輔助設施補助以每一職災勞工同一事故補助總金額多少為限？雇主受領補助後應繼續僱用該勞工幾個月？",
 ["新臺幣二十萬元；六個月","十萬元；三個月","五十萬元；一年","五萬元；一個月"],"a",
 "第5條：每一職業災害勞工同一職業災害事故補助總金額以二十萬元為限。第6條：雇主受領輔助設施補助之日起六個月內應繼續僱用該職災勞工（不可歸責事由經同意者除外）。第7條：不實申領、非因職災傷病造成之工作障礙、已依第79條請領之項目、屬身權法第57條公共建築物應改善事項、屬職安法所定必要安全衛生設備、非工作所需、同一事由已領相同補助、規避拒絕查核等不予發給。",
 "Assistive facility subsidies are capped per worker per accident at, and the employer must keep employing the worker for at least:",
 ["NT$200,000; 6 months","NT$100,000; 3 months","NT$500,000; 1 year","NT$50,000; 1 month"],
 "Articles 5–7."),

(RW,"第11條",3,"重返職場補助-職能復健津貼",
 "職能復健津貼之給付數額如何計算？發給日數以幾日為限？",
 ["依服務日數以投保薪資分級表第一等級百分之六十除以三十之日額發給；一百八十日","依平均工資全額；三百六十日","依基本工資百分之五十；九十日","定額每日一千二百元；三十日"],"a",
 "第8條：補助對象為於認可醫療機構或認可職能復健專業機構接受職能復健服務（復工計畫擬訂、工作分析、工作模擬評估、功能性能力評估、強化訓練評估及生理心理功能強化訓練）之被保險人。第9條：服務完成後備具申請書、服務完成證明、存摺影本申請。第10條：地方主管機關三十日內審核。第11條：依服務完成證明所載服務日數，以投保薪資分級表第一等級百分之六十除以三十之日額標準發給，以一百八十日為限。第12條：不實申領、規避拒絕查核者不予發給。",
 "The vocational rehabilitation allowance is calculated how, and limited to how many days?",
 ["Service days times a daily rate of 60% of the grade-1 insured salary divided by 30; 180 days","Full average wage; 360 days","50% of minimum wage; 90 days","Flat NT$1,200 per day; 30 days"],
 "Articles 8–12."),

(RW,"第18條",3,"重返職場補助-僱用補助基準",
 "原事業單位協助失能職災勞工復工並繼續僱用滿六個月，僱用第十至十五等級者每月補助平均月投保薪資百分之多少？第一至九等級？僱用其他事業單位之職災勞工者？",
 ["百分之三十；百分之五十；百分之五十及百分之七十","百分之十；百分之二十；百分之三十及四十","百分之五十；百分之七十；百分之七十及九十","百分之百；百分之百；百分之百"],"a",
 "第13條：勞工發生職災之事業單位協助符合第43條失能程度且有工作能力之職災勞工恢復原工作調整職務或安置適當工作並繼續僱用滿六個月得申請補助。第14條：僱用其他事業單位之失能職災勞工滿六個月亦得申請。第16條：每滿六個月之次日起備具僱用名冊薪資清冊出勤紀錄復工證明失能給付核發證明投保證明非負責人配偶或三親等內親屬聲明書等申請。第18條：原事業單位第十至十五等級按平均月投保薪資百分之三十、第一至九等級百分之五十；第19條：其他事業單位分別為百分之五十及百分之七十；部分工時者依平均月薪資總額計算。第20條：同一事故合計以十二個月為限。第21條：未申報災保、負責人配偶或三親等內親屬、庇護工場、重複領取等不予發給。第22條：核撥後二年內追蹤。",
 "Original employers keeping disabled occupational accident workers for six months receive monthly subsidies of what share of average insured salary for grades 10–15 and grades 1–9, and other employers hiring such workers:",
 ["30%; 50%; 50% and 70%","10%; 20%; 30% and 40%","50%; 70%; 70% and 90%","100% for all"],
 "Articles 13–22; combined limit 12 months per accident."),

# ---------- 財團法人職業災害預防及重建中心監督及管理辦法（111/3/23） ----------
(RC,"第3條",3,"重建中心-董監事",
 "財團法人職業災害預防及重建中心置董事幾人？其中幾分之幾以上應具職安職衛勞工健康職業傷病診治重建法律等專長？監察人幾人？",
 ["七人至十五人（單數）；三分之一以上；三人至五人","三人至五人；二分之一；一人","十五人至二十一人；全部；七人","五人；不限；二人"],"a",
 "第2條：中心就董監事遴聘比例資格、捐助章程變更、基金投資、財產管理運用、會計制度、預決算編審核轉、績效評估、兼職費、薪資獎金、重大措施受勞動部監督管理。第3條：董事七人至十五人（單數）由勞動部遴聘，任一性別不少於三分之一，三分之一以上應具職業安全職業衛生勞工健康職業傷病診治職災勞工重建及法律等專長。第4條：監察人三人至五人由勞動部遴聘，任一性別不少於三分之一，至少一人具會計專長。第5條：捐助章程變更應經全體董事三分之二以上出席出席過半數同意後報勞動部許可，會議十日前通知不得臨時動議。",
 "The Occupational Accident Prevention and Rehabilitation Center has how many directors, of whom at least what share must have OSH, health, medical, rehabilitation or legal expertise, and how many supervisors?",
 ["7 to 15 (odd number); at least one-third; 3 to 5","3 to 5; half; 1","15 to 21; all; 7","5; none; 2"],
 "Articles 2–5."),

(RC,"第9條",3,"重建中心-預決算",
 "職災預防及重建中心年度預算書應於每年何時前送勞動部核轉立法院審議？決算書及會計師查核報告應於何時前送？",
 ["七月十五日前；三月三十一日前","一月三十一日前；六月三十日前","十二月三十一日前；一月三十一日前","五月三十一日前；九月三十日前"],"a",
 "第6條：設立基金投資應符合財團法人法第19條第3項第2至6款並擬投資計畫經董事會通過報勞動部核准。第8條：應建立會計制度報核定。第9條：會計年度開始前訂定工作計畫編列預算書經董事會通過於每年七月十五日前送勞動部核轉立法院審議，秉持零基預算精神。第11條：前一年度工作成果及決算書提經董事會審定送監察人查核後連同會計師查核報告於每年三月三十一日前送核轉立法院審議。第12條：每年四月三十日前提報績效評估目標及前一年度績效評估結果，勞動部得組評鑑作業小組實地評鑑。第14條：專任董事長執行長薪資不超過部長待遇，副執行長及專業人員不超過政務次長待遇。第15條：獎金每人每年以平均二點五個月薪給為原則。第16條：受委託行使公權力事項應自行辦理。",
 "The Center's annual budget must be sent for legislative review by, and its final accounts with the CPA audit report by:",
 ["July 15; March 31","January 31; June 30","December 31; January 31","May 31; September 30"],
 "Articles 6–16."),

# ---------- 危險性機械或設備代行檢查機構管理規則（106/10/2） ----------
(AI,"第2條",3,"代檢機構-資格",
 "危險性機械或設備代行檢查機構應具備之資格，下列何者正確？",
 ["從事危險性機械設備研究設計檢查或訓練二年以上著有成績之行政機關學術機關公營事業或非由受檢單位人員擔任代表人之非營利法人、訂有專業團體標準或發行技術期刊之學術機關或非營利法人、中央主管機關設立之職安衛非營利法人","任何營利公司","受檢事業單位自設","保險公司"],"a",
 "第2條：曾從事危險性機械或設備之研究設計檢查或相關教育訓練二年以上著有成績之行政機關學術機關公營事業機構或非由受檢事業單位人員擔任代表人之非營利法人；訂有專業團體標準或發行專業技術期刊著有成績之學術機關或非營利法人；中央主管機關設立之職業安全衛生非營利法人。第3條：指定期間應具固定獨立辦事處所（檔案室設備存放室）、附表一檢查設備器具、代檢業務一級副主管及二級主管、足夠代檢員及事務人員。第4條：指定考量檢查區域機械設備數量項目種類勞檢機構人力及資格條件，必要時公開甄選。第5條：代檢業務應獨立運作，人員聘用資遣解聘變更應報核准。",
 "Which bodies qualify as agent inspection bodies for dangerous machinery and equipment?",
 ["Government agencies, academic institutions, public enterprises or non-profit legal persons (not represented by inspected enterprises' staff) with 2+ years of relevant research, design, inspection or training; academic or non-profit bodies issuing professional standards or journals; the ministry's OSH non-profit","Any for-profit company","The inspected enterprise itself","Insurance companies"],
 "Articles 2–5."),

(AI,"第7條",3,"代檢機構-代檢員資格",
 "代行檢查員應具備之資格，下列何者正確？代檢業務各級主管應具何資格？",
 ["專科以上相關科系畢業符合附表二資格經職前訓練合格、高考相關類科及格經職前訓練合格、曾任勞動檢查員經專業訓練合格、曾經職前訓練合格取得證書等；曾任勞檢員或代檢員並從事相關檢查工作五年以上","任何人；任何人","高中畢業即可；一年經驗","僅機械技師；三年"],"a",
 "第7條：專科以上學校有關科系畢業符合附表二資格經代檢員職前訓練合格、高等考試或相當考試相關類科及格經職前訓練合格、曾任勞動檢查員經相關專業訓練合格、曾經職前訓練合格取得證書、其他經認定具相當資格；職前訓練項目時數依附表三。第8條：未具或喪失國籍、內亂外患罪、貪污、有期徒刑未執行畢、停職休職、褫奪公權、監護輔助宣告、曾遭撤銷資格或因案離職者不得為代檢業務人員。第9條：各級主管應曾任勞檢員或代檢員並從事相關機械設備檢查五年以上。第10條：應接受指定在職訓練。",
 "Agent inspectors must, and agent inspection supervisors must:",
 ["Be relevant college graduates meeting listed qualifications with pre-service training, pass the senior civil exam with training, be former labor inspectors with professional training, or hold pre-service training certificates; have served as labor or agent inspectors with 5+ years of relevant inspection work","Anyone; anyone","High school graduates; 1 year","Mechanical engineers only; 3 years"],
 "Articles 7–10."),

(AI,"第14條",2,"代檢機構-受理檢查",
 "受檢單位於約定檢查日期因故不能配合，於檢查幾日前通知代檢機構延期者得不另行繳費？",
 ["三日前","一日前","七日前","當日"],"a",
 "第13條：應於指定資訊系統登載受檢單位名稱地址代表人電話、受檢機械設備型式容量、編號合格證號碼檢查日期有效期限等。第14條：受理申請應依約定日期指派代檢員檢查；受檢單位於檢查三日前通知延期者得不另行繳費另約期檢查，不可抗力者不受期限限制。第15條：應置足夠檢查設備安全器具，代檢員檢查前應充分瞭解受檢機械設備概況及以往檢查情形、熟悉法令、準備資料儀器工作服防護器具。第17條：主要原始發證資料保存至廢用止，其他檢查資料至少保存十年（微縮電子化者三年）。第18條：不得洩漏業務秘密，檔案室置專人管理。",
 "Inspected enterprises that cannot keep the appointment may reschedule without extra fees if they notify the agent body at least:",
 ["3 days before","1 day before","7 days before","On the day"],
 "Articles 13–18."),

(AI,"第22條",2,"代檢機構-檢查結果",
 "代檢員檢查合格應如何處理？不合格時？",
 ["作成紀錄，於機械設備打印漆印或張貼合格標章並報請核發檢查明細表或合格證，已持合格證者於原證簽署註明有效期限；告知不合格事項並由代檢機構報請勞檢機構依法處理，於原證記事欄記載並通知改善","口頭告知即可；口頭告知","僅拍照；僅拍照","不需紀錄；直接沒收"],"a",
 "第21條：代檢員應依排定日程親自執行不得委由他人代理或變更日程。第22條：檢查後應作成紀錄；應發合格證明者於合格後在機械設備打印漆印或張貼檢查合格標章並報請代檢機構核發檢查明細表或檢查合格證；已持有合格證者於原證或必要文件簽署註明有效期限。第23條：不合格者告知事業單位不合格事項並由代檢機構報請勞檢機構依法處理，已持合格證者於記事欄記載並通知改善。第24條：應使代檢員獨立行使不受不當干預，遇不當干預應向中央主管機關報告，有利害關係應迴避。第25條：依檢查費收費標準收費解繳國庫。第26條：經費獨立專戶。",
 "After a passing inspection the agent inspector must, and after a failing one:",
 ["Record it, mark or label the equipment and have the body issue the detail sheet or certificate (or endorse an existing certificate with its validity); inform the enterprise of deficiencies, have the body report to the labor inspection agency, note it on the certificate and order improvement","Verbal notice only; verbal notice","Photos only; photos only","No record; confiscate"],
 "Articles 21–26."),

(AI,"第28條",3,"代檢機構-考評與終止",
 "對代檢機構之考評區分為哪三種？何種情形中央主管機關得終止指定？",
 ["平時督導、檢查品質監督、年終考評；未依法令執行、利用職權推介訓練或技術服務、使專職人員從事無關事務、違反契約、主動申請廢止、情節重大","年度、季度、月度；僅虧損","內部、外部、第三方；僅遷址","口試、筆試、實作；僅換人"],"a",
 "第28條：考評區分為平時督導、檢查品質監督、年終考評。第29條：平時督導業務執行費用收支財產管理。第30條：不定期品質抽查、審核報告資料、判定結果有疑義、受檢單位申訴時實施品質監督。第31條：年終考評設備業務人員經費財產等。第32條：未依職安法令執行代檢業務、利用代行檢查職權推介教育訓練或技術服務、使專職人員從事無關事務、違反契約或未有效執行、主動申請廢止、其他情節重大者得終止指定。第6條：經廢止指定應於三十日內移交人員資料及委託費用購置之設備。第33、34條：成績優良自行研究有功效者得公開表揚，代檢員表現優良研究有貢獻主動協助消弭災害者得獎勵。",
 "Agent inspection bodies are evaluated by which three means, and designation may be terminated when:",
 ["Routine supervision, inspection quality monitoring and year-end evaluation; failing to follow OSH laws, using inspection authority to promote training or services, diverting dedicated staff, breaching contracts, voluntarily applying, or serious violations","Annual, quarterly, monthly; losses only","Internal, external, third-party; relocation only","Oral, written, practical; staff change only"],
 "Articles 6 and 28–34."),

# ---------- 勞動檢查員遴用及專業訓練辦法（108/2/23） ----------
(IR,"第2條",3,"勞檢員-遴用資格",
 "勞動檢查員之遴用應具有何資格之一？",
 ["高考或相當考試理工醫農教育管理勞工社會法律等類科及格、大學相關學系畢業具公務人員或技術人員任用資格、相關研究所畢業具聘用或派用資格","任何大學畢業","高中畢業","僅需勞檢證照"],"a",
 "第2條：公務人員高等考試或相當高等考試之理工醫農教育管理勞工社會法律等相當類科及格；國內外大學或獨立學院理工醫農勞工社會法律等相關學系畢業具公務人員或技術人員任用資格；相關研究所畢業具聘用人員聘用條例或派用人員派用條例聘用派用資格；曾依法任用擔任檢查員者不受限制。第3條：專業訓練分職前訓練、在職訓練及進修；職務分勞動條件檢查、一般安全衛生檢查、營造業安全衛生專業檢查、特殊有害作業環境專業檢查及危險性機械設備專業檢查；由中央主管機關統籌規劃。第10條：由所屬單位報請中央主管機關核發勞動檢查證。",
 "Labor inspectors must be recruited from those who:",
 ["Passed the senior civil service exam in science, engineering, medicine, labor, law, etc., graduated from relevant departments with civil service or technical appointment eligibility, or hold relevant graduate degrees with contract or assignment eligibility","Any university graduate","High school graduates","Only hold an inspection license"],
 "Articles 2–3 and 10."),

(IR,"第4條",3,"勞檢員-職前訓練",
 "勞動檢查員職前訓練之學科訓練時數不得少於幾小時？術科實習檢查不得少於幾場次？各項專業檢查訓練時數不得低於幾小時？",
 ["一百五十小時；六十場（座）次；六十小時","一百小時；三十場；三十小時","三百小時；一百場；一百小時","五十小時；十場；二十小時"],"a",
 "第4條：職前訓練學科不得少於一百五十小時（勞工行政勞動法令勞動條件與安全衛生知識檢查程序與技能），術科在指定檢查員指導下實習檢查不得少於六十場（座）次。第5條：在職訓練分專業檢查訓練（營造業安全衛生、特殊有害作業環境、危險性機械設備各不低於六十小時）、法規研討、檢查新知研討、工作專長研討、檢查專長研討、其他專題研討；指派受訓不得無正當理由拒絕。第6條：未完成專業檢查訓練者不得單獨執行各該專業檢查。第7條：成績優良者得選送進修或專題研究。",
 "Labor inspector pre-service training requires at least how many hours of coursework, how many practical inspections, and each professional inspection course at least:",
 ["150 hours; 60 sessions; 60 hours","100 hours; 30; 30 hours","300 hours; 100; 100 hours","50 hours; 10; 20 hours"],
 "Articles 4–7."),

(IR,"第8條",2,"勞檢員-在職訓練時數",
 "勞動檢查員每人每年接受在職訓練（法規研討、檢查新知等）時數不得低於幾小時？",
 ["二十小時","十二小時","六小時","四十小時"],"a",
 "第8條：每人每年接受第5條第1項第2至6款在職訓練時數不得低於二十小時，新進人員該年接受職前訓練者除外。第9條：受訓期間應遵守規定，曠課或時數不足者視情節處理；訓練應予記錄。第10條：勞檢機構之檢查員由所屬單位檢附資格證明派令報請中央主管機關核發勞動檢查證，上級主管機關督導人員亦得核發。",
 "Labor inspectors must receive at least how many hours of in-service training per year?",
 ["20 hours","12 hours","6 hours","40 hours"],
 "Articles 8–10."),

# ---------- 勞動檢查員執行職務迴避辦法（109/4/17） ----------
(IA,"第2條",3,"勞檢員迴避-自行迴避",
 "勞動檢查員有下列何種情形應自行迴避？",
 ["投資受檢事業單位達資本額百分之五以上、與事業主或負責人有非因檢查所致糾紛而為訴訟當事人足認有偏頗之虞、本人或配偶前配偶四親等內血親三親等內姻親等為受檢單位事業主或負責人","曾在該單位參觀","與該單位員工同鄉","曾檢查過該單位"],"a",
 "第2條：投資受檢事業單位達其資本額百分之五以上；現與或曾與受檢事業主或事業經營負責人發生非屬執行檢查職務所致之糾紛而為訴訟事件當事人足認執行職務有偏頗之虞；本人或其配偶前配偶四親等內血親三親等內血親之配偶配偶之三親等內血親或其配偶或曾有此關係者為受檢事業主或負責人。第4條：代行檢查員適用。",
 "A labor inspector must recuse when:",
 ["Holding 5% or more of the inspected enterprise's capital, being a litigation party with its owner over a non-inspection dispute suggesting bias, or the inspector or close relatives (spouse, ex-spouse, blood relatives within four degrees, in-laws within three) being the owner or manager","Having visited the enterprise","Being from the same hometown as staff","Having inspected it before"],
 "Article 2; Article 4 applies it to agent inspectors."),

(IA,"第3條",3,"勞檢員迴避-異議",
 "受檢事業單位之雇主工會或從業人員對應迴避而未迴避之勞檢員，得於檢查結果通知書送達翌日起幾日內提出異議？勞檢機構應於幾日內函復？異議有理由時？",
 ["三十日；十日；另行指派人員重新實施檢查","七日；三日；撤銷檢查","六十日；三十日；不需重檢","十日；十日；罰鍰"],"a",
 "第3條：有應自行迴避情形而不迴避或有具體事實足認執行職務有偏頗之虞者，受檢事業單位之雇主工會或其他從業人員得於檢查結果通知書送達翌日起三十日內舉其原因及事實以書面向勞動檢查機構提出異議，檢查員得提出意見書；勞檢機構應於十日內函復事業單位並副知上級主管機關中央主管機關及該檢查員；異議有理由時應另行指派人員重新實施檢查。第5條：代行檢查機構及代行檢查員適用。",
 "Objections to an inspector who failed to recuse may be filed within how many days of the inspection notice, the inspection agency replies within, and if justified:",
 ["30 days; 10 days; another inspector re-inspects","7 days; 3 days; the inspection is voided","60 days; 30 days; no re-inspection","10 days; 10 days; a fine"],
 "Articles 3 and 5."),
]
