# -*- coding: utf-8 -*-
# 第 10 批（G1）：野生動物保育法（114/02/18）第1條～第30條（含第21條之1）
# ※ 四個選項刻意寫成相近長度。
WL = "ENV-17"
Q = [
(WL,"第1條",1,"野保法-立法目的",
 "野生動物保育法之立法目的為何？本法未規定之事項應如何處理？",
 ["為保育野生動物、維護物種多樣性與自然生態之平衡而制定；本法未規定者，適用其他有關法律之規定",
  "為發展野生動物產業、維護畜牧經濟之穩定而制定；本法未規定者，一律優先適用本法之特別規定",
  "為管制動物之輸出入、維護國際貿易之秩序而制定；本法未規定者，由中央主管機關另以命令定之",
  "為保護農林作物、維護農業生產之收益而制定；本法未規定者，全部適用動物保護法之相關規定"],"a",
 "第1條：為保育野生動物，維護物種多樣性，與自然生態之平衡，特制定本法；本法未規定者，適用其他有關法律之規定。第2條並定明主管機關，第3條定明各項用辭定義。",
 "What is the legislative purpose of the Wildlife Conservation Act, and what applies to matters it does not cover?",
 ["To conserve wildlife and maintain species diversity and ecological balance; matters not provided for follow other relevant laws",
  "To develop the wildlife industry and maintain stable livestock economics; matters not provided for always follow this Act first",
  "To control imports and exports of animals and maintain trade order; matters not provided for are set by ministerial order",
  "To protect farm and forest crops and maintain farming income; matters not provided for all follow the Animal Protection Act"],
 "Article 1."),

(WL,"第2條",1,"野保法-主管機關",
 "依本法規定，各級主管機關分別為何？海域野生動物保育之中央主管機關為何？",
 ["中央為農業部，直轄市為直轄市政府，縣（市）為縣（市）政府；海域野生動物保育之中央主管機關為海洋委員會",
  "中央為環境部，直轄市為直轄市政府，縣（市）為縣（市）政府；海域野生動物保育之中央主管機關為交通部",
  "中央為內政部，直轄市為直轄市政府，縣（市）為縣（市）政府；海域野生動物保育之中央主管機關為農業部",
  "中央為農業部，直轄市為直轄市政府，縣（市）為鄉鎮公所；海域野生動物保育之中央主管機關為經濟部"],"a",
 "第2條：本法主管機關在中央為農業部，在直轄市為直轄市政府，在縣（市）為縣（市）政府；但海域野生動物保育之中央主管機關為海洋委員會。第4條保育類名錄亦由中央主管機關指定公告。",
 "Who are the competent authorities under this Act, and which agency is central authority for marine wildlife?",
 ["Ministry of Agriculture centrally, municipal and county/city governments locally; the Ocean Affairs Council for marine wildlife",
  "Ministry of Environment centrally, municipal and county/city governments locally; the Ministry of Transportation for marine wildlife",
  "Ministry of the Interior centrally, municipal and county/city governments locally; the Ministry of Agriculture for marine wildlife",
  "Ministry of Agriculture centrally, municipal governments and township offices locally; the Ministry of Economic Affairs for marine wildlife"],
 "Article 2."),

(WL,"第3條",2,"野保法-定義",
 "本法對瀕臨絕種、珍貴稀有及其他應予保育之野生動物，分別如何定義？",
 ["瀕臨絕種指族群量降至危險標準、生存已面臨危機者；珍貴稀有指各地特有或族群量稀少者；其他應予保育指族群量雖未達稀有程度但生存已面臨危機者",
  "瀕臨絕種指僅存於動物園內人工飼養者；珍貴稀有指經濟價值高而市場交易熱絡者；其他應予保育指族群量已超過環境容許量而須加以控制數量者",
  "瀕臨絕種指族群量已低於一千隻之物種；珍貴稀有指列入國際公約附錄二之物種；其他應予保育指非臺灣地區原產而逸失於野外之外來入侵物種之總稱",
  "瀕臨絕種指棲息環境已完全消失之物種；珍貴稀有指具觀賞或藥用價值之物種；其他應予保育指經地方主管機關認定有保護必要之一般類野生動物物種"],"a",
 "第3條第3至5款：瀕臨絕種野生動物指族群量降至危險標準、其生存已面臨危機者；珍貴稀有野生動物指各地特有或族群量稀少者；其他應予保育之野生動物指族群量雖未達稀有程度、但生存已面臨危機者。第4條規定此三者合稱保育類。",
 "How does the Act define endangered, rare and valuable, and other conservation-deserving wildlife?",
 ["Endangered: population fallen to a dangerous level with survival in crisis; rare and valuable: endemic or of scarce population; other conservation-deserving: not yet scarce but survival already in crisis",
  "Endangered: existing only in captivity in zoos; rare and valuable: of high economic value and actively traded; other conservation-deserving: species whose population exceeds environmental capacity and needs control",
  "Endangered: species with fewer than one thousand individuals; rare and valuable: species listed in Appendix II of an international convention; other conservation-deserving: non-native species escaped into the wild",
  "Endangered: species whose habitat has entirely disappeared; rare and valuable: species of ornamental or medicinal value; other conservation-deserving: general wildlife the local authority deems in need of protection"],
 "Article 3, subparagraphs 3–5."),

(WL,"第3條",2,"野保法-定義",
 "本法所稱騷擾、虐待、獵捕、加工，其定義分別為何？",
 ["騷擾指以藥品器物或其他方法干擾野生動物之行為；虐待指以暴力、不當使用藥品或其他方法致傷害或使其無法維持正常生理狀態；獵捕指以藥品獵具或其他器具方法捕取或捕殺；加工指以其屍體或器官等製成產品",
  "騷擾指以聲響驅趕野生動物離開農地之行為；虐待指以商業目的長期圈養野生動物之行為；獵捕指持有獵槍進入山林之準備行為；加工指將活體野生動物運送至屠宰場並予以宰殺後包裝販賣之行為",
  "騷擾指未經許可進入野生動物保護區之行為；虐待指未提供適當場所及設備飼養之行為；獵捕指在垂釣區內釣取魚類之行為；加工指以人工方式繁殖野生動物並將其幼體對外出售或交換之行為",
  "騷擾指於夜間使用照明設備觀察野生動物者；虐待指使野生動物與同種個體相互競爭者；獵捕指以陷阱捕捉家禽家畜之行為；加工指將野生動物產製品自國外輸入後重新標示並於公共場所陳列之行為"],"a",
 "第3條第10、11、12、13款：騷擾指以藥品、器物或其他方法干擾野生動物之行為；虐待指以暴力、不當使用藥品或其他方法，致傷害野生動物或使其無法維持正常生理狀態；獵捕指以藥品、獵具或其他器具或方法捕取或捕殺；加工指利用其屍體、骨、角、牙、皮、毛、卵或器官之全部或部分製成產品。第18條、第42條並對騷擾、虐待保育類野生動物設有刑責。",
 "How are harassment, abuse, hunting, and processing defined?",
 ["Harassment: disturbing wildlife with chemicals, objects or other means; abuse: violence or improper use of drugs injuring wildlife or preventing normal physiology; hunting: capturing or killing with drugs, gear or other means; processing: making products from carcasses or organs",
  "Harassment: using noise to drive wildlife off farmland; abuse: long-term captivity of wildlife for commercial purposes; hunting: entering forests carrying a shotgun in preparation; processing: transporting live wildlife to a slaughterhouse and packing the meat for sale",
  "Harassment: entering a wildlife refuge without permission; abuse: keeping wildlife without proper premises and facilities; hunting: angling for fish inside a designated angling zone; processing: artificially breeding wildlife and selling or exchanging the offspring",
  "Harassment: observing wildlife at night using lighting equipment; abuse: causing wildlife to compete with individuals of the same species; hunting: trapping poultry or livestock with snares; processing: importing wildlife products, relabelling them and displaying them in public"],
 "Article 3, subparagraphs 10–13."),

(WL,"第3條",2,"野保法-定義",
 "本法所稱野生動物產製品、棲息環境、保育及利用，其定義為何？",
 ["產製品指野生動物之屍體、骨、角、牙、皮、毛、卵或器官之全部、部分或其加工品；棲息環境指維持動植物生存之自然環境；保育指基於物種多樣性與生態平衡所為保護、復育、管理；利用指經科學實證無礙生態平衡之運用",
  "產製品指野生動物經人工繁殖後所生之幼體及其後代；棲息環境指經主管機關徵收後劃入保護區之土地；保育指將野生動物移入動物園加以圈養之行為；利用指以野生動物從事表演或競技以獲取門票收入之行為",
  "產製品指野生動物飼養過程所產生之排泄物及廢棄物；棲息環境指人工闢建供野生動物暫時停留之設施；保育指禁止任何人接近野生動物之管制措施；利用指將野生動物產製品輸出至國外以賺取外匯之貿易行為之總稱",
  "產製品指以塑膠或其他材料仿製野生動物外形之商品；棲息環境指野生動物遷徙途中所經過之行政區域；保育指對野生動物施打疫苗及投藥之防疫行為；利用指未經許可捕捉野生動物後供自己食用或轉售他人之行為"],"a",
 "第3條第6、7、8、9款：野生動物產製品指其屍體、骨、角、牙、皮、毛、卵或器官之全部、部分或加工品；棲息環境指維持動植物生存之自然環境；保育指基於物種多樣性與自然生態平衡原則所為保護、復育、管理之行為；利用指經科學實證、無礙自然生態平衡，運用野生動物以獲取文化、教育、學術、經濟等效益之行為。",
 "How are wildlife products, habitat, conservation, and utilization defined?",
 ["Products: all or part of carcasses, bones, horns, teeth, hides, fur, eggs or organs, or items processed from them; habitat: the natural environment sustaining flora and fauna; conservation: protection, restoration and management; utilization: scientifically verified use not harming ecological balance",
  "Products: the young and descendants produced by artificial breeding of wildlife; habitat: land expropriated by the authority and zoned into a refuge; conservation: moving wildlife into zoos for captive keeping; utilization: using wildlife in performances or contests to earn ticket revenue",
  "Products: excreta and waste generated during the keeping of wildlife; habitat: artificial facilities built for wildlife to stop over temporarily; conservation: control measures barring anyone from approaching wildlife; utilization: exporting wildlife products abroad to earn foreign exchange",
  "Products: goods imitating wildlife shapes made of plastic or other materials; habitat: the administrative districts wildlife passes through when migrating; conservation: vaccinating and medicating wildlife for disease prevention; utilization: catching wildlife without permit for food or resale"],
 "Article 3, subparagraphs 6–9."),

(WL,"第4條",1,"野保法-分類",
 "野生動物依本法區分為哪二類？保育類名錄如何產生？",
 ["分為保育類（瀕臨絕種、珍貴稀有及其他應予保育者）與一般類；保育類由野生動物保育諮詢委員會評估分類，中央主管機關指定公告並製作名錄",
  "分為經濟類（可供食用或商業利用者）與觀賞類；經濟類由地方主管機關評估分類，並由縣（市）主管機關逕行公告後報中央主管機關備查即可",
  "分為本土類（原產於臺灣地區者）與外來類；本土類由中央研究機構評估分類，經目的事業主管機關核定公告，地方主管機關製作名錄",
  "分為陸域類（棲息於陸地者）與海域類；陸域類由農業部與海洋委員會共同評估分類，報請行政院核定後由各級主管機關分別公告名錄"],"a",
 "第4條：野生動物區分為保育類與一般類；保育類指瀕臨絕種、珍貴稀有及其他應予保育之野生動物，由野生動物保育諮詢委員會評估分類，中央主管機關指定公告並製作名錄。第5條並規定該委員會之設置。",
 "Into which two categories is wildlife divided, and how is the protected list produced?",
 ["Protected species (endangered, rare and valuable, and other conservation-deserving) and general species; protected species are classified by the advisory committee and designated, announced and listed by the central authority",
  "Economic species (edible or commercially usable) and ornamental species; economic species are classified by local authorities and announced directly by county/city authorities, then merely reported to the central authority",
  "Native species (originating in Taiwan) and exotic species; native species are classified by central research institutes, approved and announced by the industry authority, and listed by local authorities",
  "Terrestrial species (living on land) and marine species; terrestrial species are jointly classified by the Ministry of Agriculture and Ocean Affairs Council and announced separately after Executive Yuan approval"],
 "Article 4."),

(WL,"第5條",2,"野保法-諮詢委員會",
 "中央主管機關設野生動物保育諮詢委員會，其委員之給職與組成比例有何規定？",
 ["委員為無給職，設置辦法由中央主管機關訂定；其中專家學者、民間保育團體及原住民等不具官方身分之代表，不得少於委員總人數三分之二",
  "委員為有給職，設置辦法由行政院訂定；其中專家學者、民間保育團體及原住民等不具官方身分之代表，不得少於委員總人數二分之一",
  "委員為無給職，設置辦法由立法院審定；其中專家學者、民間保育團體及原住民等不具官方身分之代表，不得多於委員總人數三分之一",
  "委員為無給職，設置辦法由地方主管機關訂定；其中專家學者、民間保育團體及原住民等不具官方身分之代表，應恰為委員總人數四分之三"],"a",
 "第5條：中央主管機關為保育野生動物設野生動物保育諮詢委員會；委員為無給職，設置辦法由中央主管機關訂定，其中專家學者、民間保育團體及原住民等不具官方身分之代表不得少於委員總人數三分之二。該委員會依第4條評估分類保育類、依第10條認可保護區之劃定。",
 "How are the members of the Wildlife Conservation Advisory Committee remunerated and composed?",
 ["Members serve without pay and the establishment rules are set by the central authority; non-official representatives such as scholars, NGOs and indigenous people must be no fewer than two-thirds of all members",
  "Members are salaried and the establishment rules are set by the Executive Yuan; non-official representatives such as scholars, NGOs and indigenous people must be no fewer than one-half of all members",
  "Members serve without pay and the establishment rules are approved by the Legislative Yuan; non-official representatives such as scholars, NGOs and indigenous people must not exceed one-third of all members",
  "Members serve without pay and the establishment rules are set by local authorities; non-official representatives such as scholars, NGOs and indigenous people must be exactly three-quarters of all members"],
 "Article 5."),

(WL,"第6條",1,"野保法-研究機構",
 "中央主管機關為加強野生動物保育，於研究機構之設立及委外事項有何規定？",
 ["應設立野生動物研究機構，並得委請學術研究機構或民間團體從事野生動物之調查、研究、保育、利用、教育、宣揚等事項",
  "應設立野生動物收容機構，並得委請動物用藥廠商或營利公司從事野生動物之繁殖、育種、買賣、輸出、加工等事項",
  "得設立野生動物執法機構，並應委請警察機關或保全公司從事野生動物之查緝、取締、扣押、沒入、銷毀等事項",
  "應設立野生動物疫病機構，並得委請醫療院所或檢疫公司從事野生動物之防疫、檢疫、解剖、標本、銷售等事項"],"a",
 "第6條：中央主管機關為加強野生動物保育，應設立野生動物研究機構，並得委請學術研究機構或民間團體從事調查、研究、保育、利用、教育、宣揚等事項。第22條另定保育警察及保育檢查人員，第23條定明對參與國際保育活動者之協助獎勵。",
 "What does the Act require of the central authority regarding research institutions and outsourcing?",
 ["It shall establish a wildlife research institute and may commission academic institutions or civil groups to conduct surveys, research, conservation, utilization, education and promotion",
  "It shall establish a wildlife shelter and may commission veterinary drug makers or profit-making companies to conduct breeding, stock improvement, trading, export and processing",
  "It may establish a wildlife enforcement agency and shall commission police or security firms to conduct investigation, crackdown, seizure, confiscation and destruction",
  "It shall establish a wildlife disease institute and may commission hospitals or quarantine companies to conduct disease control, quarantine, dissection, taxidermy and sales"],
 "Article 6."),

(WL,"第7條",2,"野保法-保育票",
 "為彙集社會資源保育野生動物，中央主管機關得採行哪些措施？其管理辦法由何機關訂定？",
 ["得設立保育捐助專戶接受私人或法人捐贈，並得發行野生動物保育票；專戶設置及保育票名稱、標章之使用及發行管理辦法由中央主管機關定之",
  "得設立保育捐助專戶接受私人或法人捐贈，並得發行野生動物保育票；專戶設置及保育票名稱、標章之使用及發行管理辦法由地方主管機關定之",
  "得課徵野生動物保育捐並強制業者認養保護區，並得發行野生動物保育債券；相關費率、標章之使用及發行管理辦法由財政主管機關會商定之",
  "得動用第二預備金並向公益彩券盈餘申請撥補，並得發行野生動物保育彩券；專戶設置及彩券名稱、標章之使用及發行辦法由行政院逕行定之"],"a",
 "第7條：中央主管機關得設立保育捐助專戶，接受私人或法人捐贈，及發行野生動物保育票；專戶設置及保育票名稱、標章之使用及發行管理辦法，由中央主管機關定之。違反第7條第2項擅自使用保育票名稱、標章或發行者，依第45條處新臺幣五十萬元以上二百五十萬元以下罰鍰。",
 "What measures may the central authority take to pool social resources, and who sets the rules?",
 ["It may set up a conservation donation account taking private or corporate donations and issue wildlife conservation stamps; the rules on the account, stamp names, emblems and issuance are set by the central authority",
  "It may set up a conservation donation account taking private or corporate donations and issue wildlife conservation stamps; the rules on the account, stamp names, emblems and issuance are set by local authorities",
  "It may levy a wildlife conservation surcharge, require firms to adopt refuges and issue conservation bonds; rates, emblem use and issuance rules are set jointly with the fiscal authority",
  "It may draw on the second reserve fund and public welfare lottery surplus and issue conservation lottery tickets; account and ticket name, emblem and issuance rules are set by the Executive Yuan"],
 "Article 7."),

(WL,"第8條",3,"野保法-重要棲息環境",
 "在野生動物重要棲息環境實施開發利用行為（如探採礦、修建道路、開發建築）者，應循何種程序？",
 ["應先向地方主管機關申請，經層報中央主管機關許可後，始得向目的事業主管機關申請為之",
  "應先向目的事業主管機關申請，經層報行政院環境部許可後，始得向中央主管機關申請為之",
  "應先向中央主管機關申請，經轉知地方主管機關備查後，即得逕行動工並於事後補行申請",
  "應先向鄉鎮市公所申請，經層報地方主管機關許可後，始得向野生動物研究機構申請為之"],"a",
 "第8條第2項：在野生動物重要棲息環境實施農林漁牧開發利用、探採礦、採取土石、修建鐵公路、開發建築、設置公園墳墓遊憩運動用地或森林遊樂區、處理廢棄物等行為，應先向地方主管機關申請，經層報中央主管機關許可後，始得向目的事業主管機關申請。違反者依第43條第1項處新臺幣三十萬元以上一百五十萬元以下罰鍰。",
 "What procedure applies to development in a major wildlife habitat, such as mining, road building or construction?",
 ["Apply first to the local authority, obtain permission from the central authority through the chain of report, and only then apply to the industry authority",
  "Apply first to the industry authority, obtain permission from the Ministry of Environment through the chain of report, and only then apply to the central authority",
  "Apply first to the central authority, have it notified to the local authority for record, and then start work at once with the application filed afterwards",
  "Apply first to the township office, obtain permission from the local authority through the chain of report, and only then apply to the wildlife research institute"],
 "Article 8, paragraph 2."),

(WL,"第8條",2,"野保法-重要棲息環境",
 "既有建設或開發行為對野生動物構成重大影響時如何處理？重要棲息環境之類別及範圍由誰公告？",
 ["中央主管機關得要求當事人或目的事業主管機關限期提出改善辦法；重要棲息環境之類別及範圍由中央主管機關公告，變更時亦同",
  "地方主管機關得要求當事人或土地所有權人立即停止使用；重要棲息環境之類別及範圍由目的事業主管機關公告，變更時亦同",
  "中央主管機關應逕行撤銷原核發之開發許可並命恢復原狀；重要棲息環境之類別及範圍由野生動物研究機構公告，變更時亦同",
  "目的事業主管機關得要求當事人繳交生態補償代金；重要棲息環境之類別及範圍由縣（市）主管機關公告，變更時報中央備查"],"a",
 "第8條第3項：既有之建設、土地利用或開發行為，如對野生動物構成重大影響，中央主管機關得要求當事人或目的事業主管機關限期提出改善辦法。第4項：重要棲息環境之類別及範圍由中央主管機關公告，變更時亦同。不依期限提出改善辦法者，依第43條第2項處新臺幣四十萬元以上二百萬元以下罰鍰。",
 "How are existing developments with major impacts handled, and who announces habitat categories and scope?",
 ["The central authority may order the party or the industry authority to submit improvement measures within a set period; it also announces the categories and scope, and likewise any change",
  "The local authority may require the party or the landowner to stop the use immediately; the industry competent authority announces the categories and scope, and likewise any change",
  "The central authority shall revoke the development permit outright and order full restoration; the wildlife research institute announces the categories and the scope, and likewise any change",
  "The industry authority may require the party to pay ecological compensation money; county/city authorities announce the categories and scope, reporting changes for the record"],
 "Article 8, paragraphs 3–4."),

(WL,"第9條",2,"野保法-停工補救",
 "未依規定實施環境影響評估而擅自經營利用野生動物重要棲息環境者，主管機關應如何處置？",
 ["應即通知或會同目的事業主管機關責令停工；已致生育環境遭破壞者，並應限期令當事人補提補救方案並監督實施，逾期未提或情況緊急時得以當事人費用為必要處理",
  "應即函請司法機關偵辦並移送強制執行；已致生育環境遭破壞者，並應限期令當事人繳納罰金並監督繳納，逾期未繳或情況緊急時得由國庫墊付必要費用",
  "應即撤銷開發許可並註銷營業執照；已致生育環境遭破壞者，並應限期令當事人辦理徵收並監督移轉，逾期未辦或情況緊急時得由目的事業主管機關代辦",
  "應即通知土地登記機關辦理禁止處分登記；已致生育環境遭破壞者，並應限期令當事人提出環評並監督審查，逾期未提時得由地方主管機關逕行核定"],"a",
 "第9條：未依第8條第1項規定實施環境影響評估而擅自經營利用者，主管機關應即通知或會同目的事業主管機關責令停工；已致野生動物生育環境遭受破壞者，並應限期令當事人補提補救方案，監督其實施；逾期未補提補救方案或遇情況緊急時，主管機關得以當事人之費用為必要之處理。不提補救方案者依第43條第2項處罰。",
 "How must the authority act when someone develops a major habitat without the required environmental impact assessment?",
 ["Notify or join the industry authority to order a work stoppage; where breeding environments are damaged, order a remedial plan within a deadline and supervise it, and if overdue or urgent take necessary action at the party's expense",
  "Refer the case to prosecutors and compulsory enforcement; where breeding environments are damaged, order payment of a fine within a deadline and supervise it, and if overdue or urgent advance the necessary costs from the treasury",
  "Revoke the development permit and cancel the business licence; where breeding environments are damaged, order expropriation within a deadline and supervise transfer, and if overdue or urgent let the industry authority act instead",
  "Notify the land registry to enter a disposition ban; where breeding environments are damaged, order an impact assessment within a deadline and supervise review, and if overdue let the local authority approve it directly"],
 "Article 9."),

(WL,"第10條",3,"野保法-保護區",
 "野生動物保護區之劃定、變更或廢止應踐行何種程序？中央主管機關於緊急必要時可否逕行劃定？",
 ["必要時應先於當地舉辦公聽會聽取居民意見後，層報中央主管機關經野生動物保育諮詢委員會認可後公告實施；中央主管機關認緊急或必要時，得經該委員會認可逕行劃定或變更",
  "必要時應先於當地舉辦聽證會取得居民同意後，層報行政院經環境影響評估委員會認可後公告實施；中央主管機關認緊急或必要時，仍應依一般程序報請行政院核定後辦理",
  "必要時應先辦理公開展覽三十日並函詢目的事業主管機關後，報請立法院同意後公告實施；中央主管機關認緊急或必要時，得授權鄉鎮市公所先行公告再補辦程序",
  "必要時應先完成土地徵收及地上物補償後，層報中央主管機關經內政部都市計畫委員會認可後公告實施；中央主管機關認緊急或必要時，應先取得土地所有人同意"],"a",
 "第10條第1至3項：地方主管機關得就有特別保護必要之重要棲息環境劃定野生動物保護區，擬訂保育計畫並執行；劃定、變更或廢止必要時應先於當地舉辦公聽會，充分聽取居民意見後層報中央主管機關，經野生動物保育諮詢委員會認可後公告實施；中央主管機關認為緊急或必要時，得經該委員會認可逕行劃定或變更。",
 "What procedure applies to designating, changing or abolishing a wildlife refuge, and may the central authority act directly?",
 ["Where necessary hold a local public hearing to gather residents' views, then report up for the advisory committee's endorsement and announce it; in urgent or necessary cases the central authority may designate or change it directly with that committee's endorsement",
  "Where necessary hold a formal hearing to obtain residents' consent, then report to the Executive Yuan for the EIA committee's endorsement and announce it; in urgent or necessary cases the central authority must still follow the ordinary procedure",
  "Where necessary hold a thirty-day public exhibition and consult the industry authority, then obtain the Legislative Yuan's consent and announce it; in urgent cases the central authority may let township offices announce first and complete formalities later",
  "Where necessary complete land expropriation and compensation first, then report up for the Interior Ministry urban planning committee's endorsement and announce it; in urgent cases the central authority must first obtain landowners' consent"],
 "Article 10, paragraphs 1–3."),

(WL,"第10條",2,"野保法-保護區管制",
 "主管機關得於野生動物保護區保育計畫中，就哪些事項予以公告管制？",
 ["騷擾、虐待、獵捕或宰殺一般類野生動物等行為；採集、砍伐植物等行為；污染、破壞環境等行為；其他禁止或許可行為",
  "民眾攝影及錄影等行為；車輛通行與臨時停放等行為；商業廣告與招牌設置行為；其他經目的事業主管機關指定之行為",
  "土地買賣及所有權移轉行為；建物之增建改建修繕行為；水權登記及用水申請行為；其他經內政部公告限制之處分行為",
  "宗教祭祀及放生活動行為；學術研究人員採樣行為；空拍機起降與航拍行為；其他經地方民意機關決議禁止之行為"],"a",
 "第10條第4項：主管機關得於保育計畫中就下列事項公告管制：一、騷擾、虐待、獵捕或宰殺一般類野生動物等行為；二、採集、砍伐植物等行為；三、污染、破壞環境等行為；四、其他禁止或許可行為。違反第1款獵捕宰殺者依第50條第1項處五萬元以上二十五萬元以下罰鍰，騷擾虐待者依第2項處二萬元以上十萬元以下罰鍰。",
 "Which matters may the authority announce as controlled in a refuge conservation plan?",
 ["Harassing, abusing, hunting or killing general wildlife; collecting or felling plants; polluting or damaging the environment; and other prohibited or permitted acts",
  "Public photography and video recording; vehicle passage and temporary parking; commercial advertising and signage; and other acts designated by the industry authority",
  "Land sales and title transfers; building extension, alteration and repair; water rights registration and water use applications; and other dispositions restricted by the Interior Ministry",
  "Religious rituals and animal release events; sampling by academic researchers; drone take-off and aerial filming; and other acts banned by local council resolution"],
 "Article 10, paragraph 4."),

(WL,"第11條",2,"野保法-保護區土地",
 "野生動物保護區之土地，其徵收撥用、未徵收土地之義務及損失處理為何？",
 ["必要時得依法徵收或撥用交主管機關管理；未經徵收撥用者，所有人使用人或占有人應以主管機關公告之方法提供棲息環境，所受損失主管機關應給予補償",
  "應一律辦理徵收並交由目的事業主管機關管理；未經徵收者，所有人使用人或占有人應無償提供全部土地供公眾使用，所受損失由開發行為人負責賠償",
  "必要時得依法徵收或撥用交主管機關管理；未經徵收撥用者，所有人使用人或占有人得自由使用收益不受限制，所受損失由地方民意機關編列預算補助",
  "應由主管機關以租用方式取得並委託民間經營管理；未經租用者，所有人使用人或占有人應繳交回饋金作為保育經費，所受損失得申請減免地價稅"],"a",
 "第11條：經劃定為野生動物保護區之土地，必要時得依法徵收或撥用，交由主管機關管理；未經徵收或撥用者，其所有人、使用人或占有人應以主管機關公告之方法提供野生動物棲息環境，公告前使用收益方法有害保育者主管機關得命變更或停止；但遇國家重大建設，在不影響野生動物生存原則下，經諮詢委員會認可及中央主管機關許可者不在此限。所受損失應予補償。違反第2項者依第50條第1項第3款處罰。",
 "How does the Act treat land in a wildlife refuge as to expropriation, duties on unexpropriated land, and losses?",
 ["It may be expropriated or appropriated and managed by the authority; on unexpropriated land the owner, user or possessor must provide habitat by the announced method, and the authority shall compensate losses suffered",
  "All such land must be expropriated and managed by the industry authority; where unexpropriated, the owner, user or possessor must provide all land free for public use, and losses are compensated by the developer",
  "It may be expropriated or appropriated and managed by the authority; on unexpropriated land the owner, user or possessor may use and profit freely without restriction, and losses are subsidized by the local council's budget",
  "It must be leased by the authority and entrusted to private management; where unleased, the owner, user or possessor must pay a feedback levy for conservation, and losses may be offset by land tax relief"],
 "Article 11."),

(WL,"第12條",2,"野保法-資源調查",
 "為執行野生動物資源調查或保育計畫進入公、私有土地，相關人員與土地權利人各有何義務？",
 ["主管機關或受託機關團體得派員攜帶證明文件進入；土地所有人使用人或管理人除涉及軍事機密應會同軍事機關外，不得規避、拒絕或妨礙",
  "主管機關或受託機關團體得派員免持證明文件進入；土地所有人使用人或管理人得於任何情形拒絕進入，但應另行提供書面資料供調查參考",
  "須由警察機關持法院核發之搜索票始得進入；土地所有人使用人或管理人除涉及營業秘密外，應全程陪同並負擔調查所需之全部費用",
  "須由目的事業主管機關會同檢察官始得進入；土地所有人使用人或管理人除涉及個人隱私外，應先簽署同意書並提供土地權利證明文件"],"a",
 "第12條第1項：為執行野生動物資源調查或保育計畫，主管機關或受託機關、團體得派員攜帶證明文件進入公、私有土地進行調查及實施保育措施；公、私有土地所有人、使用人或管理人，除涉及軍事機密者應會同軍事機關為之外，不得規避、拒絕或妨礙。第2項並規定遇設有圍障之土地或實施保育措施時應事先通知，第3項規定對工商軍事秘密應予保密。違反者依第51條第1項第1款處一萬元以上五萬元以下罰鍰。",
 "What duties apply when officials enter public or private land for wildlife surveys or conservation measures?",
 ["The authority or entrusted body may send staff carrying credentials to enter; the owner, user or manager may not evade, refuse or obstruct, save that military secrets require the military agency to attend",
  "The authority or entrusted body may send staff to enter without carrying credentials; the owner, user or manager may refuse entry in any case but must supply written material for reference instead",
  "Entry requires police officers holding a court search warrant; the owner, user or manager must accompany throughout and bear all survey costs, except where trade secrets are involved",
  "Entry requires the industry authority accompanied by a prosecutor; the owner, user or manager must first sign a consent form and produce title documents, except where personal privacy is involved"],
 "Article 12, paragraphs 1–3."),

(WL,"第12條",3,"野保法-調查補償",
 "因進行野生動物資源調查或實施保育措施致土地所有人或使用人受損失時，補償金額如何決定？",
 ["應予補償，補償金額依協議為之；協議不成時，報請上級主管機關核定之",
  "應予補償，補償金額由中央主管機關逕行核定；當事人不服時得提起民事訴訟",
  "得予補償，補償金額依公告土地現值計算；協議不成時，送請仲裁機構仲裁之",
  "應予補償，補償金額由受託調查機關團體自行決定；協議不成時，由法院逕為裁定"],"a",
 "第12條第4項：為進行第1項調查或實施各項保育措施，致公、私有土地所有人或使用人遭受損失者，應予補償；補償金額依協議為之，協議不成時，報請上級主管機關核定之。第5項並授權中央主管機關訂定調查及保育措施之辦法。",
 "How is the compensation amount determined when a survey or conservation measure causes loss to a landowner or user?",
 ["Compensation shall be paid and its amount agreed by negotiation; if no agreement is reached, it is reported to the superior authority for approval",
  "Compensation shall be paid and its amount set directly by the central authority; a dissatisfied party may bring a civil action",
  "Compensation may be paid and its amount computed on the announced land value; if no agreement is reached, the matter goes to arbitration",
  "Compensation shall be paid and its amount decided by the entrusted surveying body; if no agreement is reached, the court rules on it directly"],
 "Article 12, paragraph 4."),

(WL,"第13條",2,"野保法-補救方案",
 "經許可從事開發利用行為而破壞野生動物棲息環境時，主管機關應如何處理？未經許可者呢？",
 ["經許可者，主管機關應限期令行為人提補救方案並監督其實施；未經許可者，除依前述辦理外，主管機關並得緊急處理，其費用由行為人負擔",
  "經許可者，主管機關應逕行撤銷許可並命恢復原狀；未經許可者，除依前述辦理外，主管機關並得移送法辦，其費用由目的事業機關負擔",
  "經許可者，主管機關應命行為人繳交生態補償代金；未經許可者，除依前述辦理外，主管機關並得停止供水供電，其費用由土地所有人負擔",
  "經許可者，主管機關應報請中央主管機關廢止該開發案；未經許可者，除依前述辦理外，主管機關並得強制拆除，其費用由國庫先行墊付"],"a",
 "第13條：經許可從事第8條第2項開發利用行為而破壞野生動物棲息環境時，主管機關應限期令行為人提補救方案並監督其實施；前項開發利用行為未經許可者，除依前項規定辦理外，主管機關得緊急處理，其費用由行為人負擔。不提補救方案或不依方案實施者依第43條第2項處四十萬元以上二百萬元以下罰鍰。",
 "How is habitat damage handled when the development was permitted, and when it was not?",
 ["If permitted, the authority orders the actor to submit a remedial plan within a deadline and supervises it; if unpermitted, in addition to that the authority may take emergency action at the actor's expense",
  "If permitted, the authority revokes the permit outright and orders restoration; if unpermitted, in addition to that the authority may refer the case for prosecution at the industry authority's expense",
  "If permitted, the authority orders payment of ecological compensation money; if unpermitted, in addition to that the authority may cut off water and power at the landowner's expense",
  "If permitted, the authority reports to the central authority to abolish the project; if unpermitted, in addition to that the authority may demolish the works with costs advanced by the treasury"],
 "Article 13."),

(WL,"第14條",1,"野保法-外來種",
 "逸失或生存於野外之非臺灣地區原產動物，如有影響國內動植物棲息環境之虞時應如何處理？認定機關為何？",
 ["得由主管機關逕為必要之處置；該非臺灣地區原產動物由中央主管機關認定之",
  "應由土地所有人自行捕捉並送交收容；該非臺灣地區原產動物由地方主管機關認定之",
  "須經野生動物保育諮詢委員會決議後處理；該非臺灣地區原產動物由目的事業機關認定之",
  "應報請行政院核准後始得予以撲殺；該非臺灣地區原產動物由動植物防疫機關認定之"],"a",
 "第14條：逸失或生存於野外之非臺灣地區原產動物，如有影響國內動植物棲息環境之虞者，得由主管機關逕為必要之處置；該等非臺灣地區原產動物由中央主管機關認定之。第27條另規定首次輸入非臺灣地區原產物種須提出對國內動植物影響評估報告經核准。",
 "How are escaped or wild-living non-native animals handled when they may affect domestic habitats, and who identifies them?",
 ["The authority may take necessary action directly; such non-native animals are identified by the central authority",
  "The landowner must capture them and hand them over for shelter; such non-native animals are identified by the local authority",
  "Action requires a resolution of the conservation advisory committee; such non-native animals are identified by the industry authority",
  "They may be culled only after Executive Yuan approval; such non-native animals are identified by the plant and animal quarantine agency"],
 "Article 14."),

(WL,"第15條",1,"野保法-無主動物",
 "無主或流蕩之保育類野生動物及無主之保育類野生動物產製品，主管機關應如何處理？",
 ["主管機關應逕為處理，並得委託有關機關或團體收容、暫養、救護、保管或銷毀",
  "主管機關應公告招領六個月，逾期無人認領者始得委託有關機關或團體拍賣變價",
  "主管機關應移送警察機關處理，並得委託獸醫師公會辦理解剖、標本製作或販售",
  "主管機關應報請中央主管機關核准，並得委託民間業者飼養、繁殖、加工或出口"],"a",
 "第15條：無主或流蕩之保育類野生動物及無主之保育類野生動物產製品，主管機關應逕為處理，並得委託有關機關或團體收容、暫養、救護、保管或銷毀。第52條另定違法查獲物之沒收沒入及公開放生、遣返、典藏或銷毀。",
 "How must the authority deal with ownerless or stray protected wildlife and ownerless protected wildlife products?",
 ["The authority shall handle them directly and may entrust agencies or groups with shelter, temporary keeping, rescue, custody or destruction",
  "The authority shall advertise for claimants for six months and only then entrust agencies or groups to auction them off",
  "The authority shall refer them to the police and may entrust the veterinary association with dissection, taxidermy, storage or sale",
  "The authority shall seek central approval and may entrust private operators with keeping, breeding, processing or export"],
 "Article 15."),

(WL,"第16條",2,"野保法-保育類禁止",
 "除本法或其他法令另有規定外，對保育類野生動物及其產製品分別禁止哪些行為？",
 ["保育類野生動物不得騷擾、虐待、獵捕、宰殺、買賣、陳列、展示、持有、輸入、輸出或飼養、繁殖；其產製品不得買賣、陳列、展示、持有、輸入、輸出或加工",
  "保育類野生動物僅不得獵捕及宰殺，其餘買賣、陳列、展示、持有、輸出入均得自由為之；其產製品則僅禁止輸出，國內買賣、陳列、展示及加工不受限制",
  "保育類野生動物不得騷擾、虐待、獵捕、宰殺，但買賣、持有及飼養繁殖經地方民意機關同意即可；其產製品得自由買賣，僅輸出入須報請目的事業機關備查",
  "保育類野生動物與一般類野生動物同受相同管制，均僅禁止使用炸藥毒物獵捕；其產製品之買賣、陳列、展示、持有及加工，僅須於事後三十日內申報即可"],"a",
 "第16條：保育類野生動物，除本法或其他法令另有規定外，不得騷擾、虐待、獵捕、宰殺、買賣、陳列、展示、持有、輸入、輸出或飼養、繁殖；保育類野生動物產製品，除本法或其他法令另有規定外，不得買賣、陳列、展示、持有、輸入、輸出或加工。第18條、第24條、第35條分別就利用、輸出入及買賣陳列展示定有例外與許可規定。",
 "What acts are prohibited for protected wildlife and their products, absent other legal provision?",
 ["Protected wildlife may not be harassed, abused, hunted, killed, traded, displayed, exhibited, possessed, imported, exported, kept or bred; their products may not be traded, displayed, exhibited, possessed, imported, exported or processed",
  "Protected wildlife may only not be hunted or killed, while trading, display, exhibition, possession and trade are free; their products are barred only from export, with domestic trade, display and processing unrestricted",
  "Protected wildlife may not be harassed, abused, hunted or killed, but trading, possession and breeding need only local council consent; their products may be traded freely, with only trade reported to the industry authority",
  "Protected and general wildlife are subject to entirely identical controls barring only explosives and poisons; trading, display, exhibition, possession and processing of their products need only be declared within thirty days afterwards"],
 "Article 16."),

(WL,"第17條",2,"野保法-一般類獵捕",
 "非基於學術研究或教育目的，獵捕一般類之哺乳類、鳥類、爬蟲類、兩棲類野生動物，應遵守何規定？",
 ["應在地方主管機關所劃定之區域內為之，並應先向地方主管機關、受託機關或團體申請核發許可證",
  "應在中央主管機關所劃定之區域內為之，並應先向目的事業主管機關申請核發狩獵執照及保險",
  "應在野生動物保護區以外之任何區域為之，並應於獵捕後三十日內向警察機關報備獵獲數量",
  "應在自有或承租之私有土地範圍內為之，並應先向鄉鎮市公所申請核發臨時性之獵捕同意書"],"a",
 "第17條第1項：非基於學術研究或教育目的，獵捕一般類之哺乳類、鳥類、爬蟲類、兩棲類野生動物，應在地方主管機關所劃定之區域內為之，並應先向地方主管機關、受託機關或團體申請核發許可證。違反者依第49條第1項第1款處六萬元以上三十萬元以下罰鍰，並得撤銷其許可證。",
 "What applies to hunting general mammals, birds, reptiles and amphibians other than for research or education?",
 ["It must take place within an area designated by the local authority, and a permit must first be obtained from the local authority or an entrusted body",
  "It must take place within an area designated by the central authority, and a hunting licence and insurance must first be obtained from the industry authority",
  "It may take place anywhere outside a wildlife refuge, with the number taken reported to the police within thirty days after hunting",
  "It must take place on land the hunter owns or leases, and a temporary hunting consent must first be obtained from the township office"],
 "Article 17, paragraph 1."),

(WL,"第17條",2,"野保法-獵捕區劃定",
 "獵捕一般類野生動物之物種、區域劃定變更廢止及管制事項，其擬訂與核定程序為何？許可證得否收費？",
 ["由地方主管機關擬訂，層報中央主管機關核定後公告之；許可證得收取工本費，申請程序及其他有關事項由中央主管機關定之",
  "由中央主管機關擬訂，會商目的事業主管機關核定後公告之；許可證應免費核發，申請程序及其他有關事項由地方主管機關定之",
  "由野生動物研究機構擬訂，報請野生動物保育諮詢委員會核定後公告之；許可證得收取保育回饋金，收費標準由行政院統一定之",
  "由鄉鎮市公所擬訂，層報縣（市）主管機關核定後公告之；許可證得收取管理費及押金，申請程序由地方民意機關決議定之"],"a",
 "第17條第2、3項：獵捕一般類野生動物之物種、區域之劃定、變更、廢止及管制事項，由地方主管機關擬訂，層報中央主管機關核定後公告之；許可證得收取工本費，其申請程序及其他有關事項由中央主管機關定之。第20條並規定進入劃定區應登記及隨身攜帶許可證備查。",
 "Who drafts and approves the species, zones and control matters for hunting general wildlife, and may fees be charged?",
 ["The local authority drafts them and the central authority approves and announces them; a handling fee may be charged for permits, with procedures set by the central authority",
  "The central authority drafts them and approves and announces them after consulting the industry authority; permits must be free, with procedures set by local authorities",
  "The wildlife research institute drafts them and the conservation advisory committee approves and announces them; a conservation levy may be charged, with rates set uniformly by the Executive Yuan",
  "Township offices draft them and county/city authorities approve and announce them; management fees and deposits may be charged, with procedures set by local council resolution"],
 "Article 17, paragraphs 2–3."),

(WL,"第18條",3,"野保法-保育類利用",
 "保育類野生動物原則上不得騷擾、虐待、獵捕、宰殺或為其他利用，其例外情形為何？",
 ["一、族群量逾越環境容許量者；二、基於學術研究或教育目的，經中央主管機關許可者",
  "一、族群量低於環境容許量者；二、基於商業展演或營利目的，經地方主管機關許可者",
  "一、經飼養繁殖滿三年以上者；二、基於宗教祭祀或觀光目的，經目的事業機關許可者",
  "一、族群量逾越環境容許量者；二、基於私人收藏或飼養目的，經野生動物研究機構核備者"],"a",
 "第18條第1項：保育類野生動物應予保育，不得騷擾、虐待、獵捕、宰殺或為其他利用，但有下列情形之一不在此限：一、族群量逾越環境容許量者；二、基於學術研究或教育目的，經中央主管機關許可者。未具第1款條件而獵捕宰殺者依第41條處六月以上五年以下有期徒刑，騷擾虐待者依第42條處一年以下有期徒刑。",
 "What are the exceptions to the ban on harassing, abusing, hunting, killing or otherwise using protected wildlife?",
 ["(1) where the population exceeds environmental carrying capacity; (2) for academic research or education with the central authority's permission",
  "(1) where the population falls below environmental carrying capacity; (2) for commercial performance or profit with the local authority's permission",
  "(1) where the animals have been kept and bred for over three years; (2) for religious rites or tourism with the industry authority's permission",
  "(1) where the population exceeds environmental carrying capacity; (2) for private collection or keeping with the research institute's recording"],
 "Article 18, paragraph 1."),

(WL,"第18條",2,"野保法-利用許可",
 "因族群量逾越環境容許量而利用保育類野生動物者，應經何機關許可？可利用之種類地點範圍由誰公告？",
 ["應先經地方主管機關許可；其可利用之種類、地點、範圍及利用數量、期間與方式，由中央主管機關公告之",
  "應先經中央主管機關許可；其可利用之種類、地點、範圍及利用數量、期間與方式，由地方主管機關公告之",
  "應先經目的事業主管機關許可；其可利用之種類、地點、範圍及利用數量、期間與方式，由行政院公告之",
  "應先經野生動物保育諮詢委員會許可；其可利用之種類、地點、範圍及利用數量、期間與方式，由研究機構公告"],"a",
 "第18條第2項：第1項第1款保育類野生動物之利用，應先經地方主管機關許可；其可利用之種類、地點、範圍及利用數量、期間與方式，由中央主管機關公告之。第3項並授權中央主管機關訂定申請程序及費用。違反第18條第2項未申請許可者依第49條第1項第6款處六萬元以上三十萬元以下罰鍰。",
 "Whose permission is needed to use protected wildlife whose population exceeds carrying capacity, and who announces the allowed scope?",
 ["The local authority's prior permission is required; the species, sites, scope, quantity, period and manner allowed are announced by the central authority",
  "The central authority's prior permission is required; the species, sites, scope, quantity, period and manner allowed are announced by local authorities",
  "The industry authority's prior permission is required; the species, sites, scope, quantity, period and manner allowed are announced by the Executive Yuan",
  "The conservation advisory committee's permission is required; the species, sites, scope, quantity, period and manner allowed are announced by the research institute"],
 "Article 18, paragraph 2."),

(WL,"第19條",3,"野保法-禁止獵法",
 "獵捕野生動物時，本法列舉禁止使用之方法包括哪些？",
 ["使用炸藥或其他爆裂物、使用毒物、使用電氣麻醉物或麻痺方法、架設網具、使用獵槍以外之其他種類槍械、使用陷阱或特殊獵捕工具、使用獸鋏及其他經主管機關公告禁止之方法",
  "使用弓箭或彈弓、使用誘餌或飼料、使用犬隻協助追蹤、架設木製圍籬、使用鏡頭超過三百公釐之攝影器材、使用車輛照明、使用捕蟲網及其他經地方民意機關決議禁止之方法",
  "使用漁網或魚叉、使用哨音或錄音、使用無人機空中追逐、架設瞭望平臺、使用夜視鏡或熱顯像儀器、使用馬匹騎乘、使用手電筒及其他經目的事業主管機關核定之方法",
  "使用石塊或木棍、使用煙燻或火燒、使用麻繩綑綁固定、架設臨時工寮、使用非動力之小型船筏、使用竹製陷坑、使用鹽磚及其他經野生動物研究機構列管之方法"],"a",
 "第19條第1項：獵捕野生動物不得以下列方法為之：一、使用炸藥或其他爆裂物；二、使用毒物；三、使用電氣、麻醉物或麻痺之方法；四、架設網具；五、使用獵槍以外之其他種類槍械；六、使用陷阱或特殊獵捕工具；七、使用獸鋏；八、其他經主管機關公告禁止之方法。違反而獵捕宰殺保育類者依第41條第1項第3款處刑，獵捕一般類者依第49條第1項第2款處罰鍰。",
 "Which hunting methods does the Act expressly prohibit?",
 ["Explosives, poisons, electricity, anaesthetics or paralysing methods, setting nets, firearms other than hunting guns, traps or special capture devices, leg-hold traps, and other methods announced as prohibited",
  "Bows or slingshots, bait or feed, tracking dogs, wooden fencing, cameras with lenses over three hundred millimetres, vehicle headlights, insect nets, and other methods banned by local council resolution",
  "Fishing nets or spears, whistles or recordings, aerial pursuit by drone, observation platforms, night vision or thermal imagers, riding horses, flashlights, and other methods approved by the industry authority",
  "Stones or clubs, smoking or burning, binding with hemp rope, temporary huts, non-powered small boats, bamboo pitfalls, salt licks, and other methods listed by the wildlife research institute"],
 "Article 19, paragraph 1."),

(WL,"第19條",2,"野保法-排除拆除",
 "對於以禁止方法獵捕野生動物所使用之器具，主管機關有何權限？土地權利人有何義務？",
 ["主管機關得逕予排除或拆除並銷毀之；土地所有人、使用人或管理人不得規避、拒絕或妨礙",
  "主管機關應報請檢察官核發扣押命令後始得拆除；土地所有人、使用人或管理人得請求先行補償",
  "主管機關僅得命行為人自行拆除並限期回報；土地所有人、使用人或管理人得拒絕人員進入土地",
  "主管機關得逕予排除或拆除但不得銷毀應予保管；土地所有人、使用人或管理人應負擔保管費用"],"a",
 "第19條第2項：使用第1項各款所定方法獵捕野生動物者，主管機關得逕予排除或拆除並銷毀之；土地所有人、使用人或管理人不得規避、拒絕或妨礙。違反者依第49條第1項第3款處新臺幣六萬元以上三十萬元以下罰鍰。",
 "What powers does the authority have over gear used in prohibited hunting, and what duty falls on land holders?",
 ["The authority may remove or dismantle and destroy it directly; the owner, user or manager may not evade, refuse or obstruct",
  "The authority may dismantle it only after a prosecutor issues a seizure order; the owner, user or manager may demand compensation first",
  "The authority may only order the actor to dismantle it and report back; the owner, user or manager may refuse entry onto the land",
  "The authority may remove or dismantle it but must keep rather than destroy it; the owner, user or manager bears the storage costs"],
 "Article 19, paragraph 2."),

(WL,"第20條",2,"野保法-登記查驗",
 "進入劃定區獵捕一般類野生動物或主管機關劃定之垂釣區者，應履行哪些程序？",
 ["應向受託管理機關、團體登記，隨身攜帶許可證以備查驗；離開時應報明獲取野生動物之種類、數量並繳納費用",
  "應向當地警察機關報備，隨身攜帶身分證件以備查驗；離開時應報明停留時間及同行人數並繳納清潔費",
  "應向鄉鎮市公所投保責任險，隨身攜帶保單以備查驗；離開時應報明使用獵具種類及數量並繳交押金",
  "應向目的事業主管機關申報，隨身攜帶槍砲執照以備查驗；離開時應報明彈藥消耗數量並繳納規費"],"a",
 "第20條：進入第17條劃定區獵捕一般類野生動物或主管機關劃定之垂釣區者，應向受託管理機關、團體登記，隨身攜帶許可證以備查驗；離開時應向受託管理機關、團體報明獲取野生動物之種類、數量，並繳納費用；費用收取標準由中央主管機關定之。違反者依第51條第1項第2款處一萬元以上五萬元以下罰鍰。",
 "What must a person do when entering a designated hunting or angling zone?",
 ["Register with the entrusted managing body and carry the permit for inspection; on leaving, report the species and number taken and pay the fees",
  "Report to the local police and carry an identity card for inspection; on leaving, report the length of stay and party size and pay a cleaning fee",
  "Take out liability insurance at the township office and carry the policy for inspection; on leaving, report gear types and numbers and pay a deposit",
  "Declare to the industry authority and carry a firearms licence for inspection; on leaving, report ammunition used and pay the statutory charge"],
 "Article 20."),

(WL,"第21條",3,"野保法-緊急獵捕",
 "野生動物有哪些情形時得予以獵捕或宰殺，而不受獵捕許可等規定之限制？保育類另有何要求？",
 ["有危及公共安全或人類性命之虞、危害農林作物家禽家畜或水產養殖、傳播疾病或病蟲害、有妨礙航空安全之虞、其他經主管機關核准者；保育類除情況緊急外應先報請主管機關處理",
  "有影響觀光遊憩品質之虞、造成道路交通壅塞、於夜間發出噪音干擾住戶、有損害景觀樹木之虞、其他經地方民意機關決議者；保育類一律得逕行獵捕不必報請主管機關處理",
  "有危及公共安全或人類性命之虞、危害農林作物家禽家畜或水產養殖、傳播疾病或病蟲害、有妨礙航空安全之虞、其他經主管機關核准者；保育類須一律事先取得中央主管機關書面許可",
  "有進入私人住宅庭院之情形、於農地覓食踐踏作物、族群量逾越環境容許量、有妨礙鐵路運輸之虞、其他經目的事業機關認定者；保育類應先報請野生動物研究機構評估同意"],"a",
 "第21條第1項：野生動物有下列情形之一者得予以獵捕或宰殺，不受第17條第1項、第18條第1項及第19條第1項第2款至第6款規定之限制：一、有危及公共安全或人類性命之虞；二、危害農林作物、家禽、家畜或水產養殖；三、傳播疾病或病蟲害；四、有妨礙航空安全之虞；五、其他經主管機關核准之情形。但保育類野生動物除情況緊急外，應先報請主管機關處理。",
 "In which situations may wildlife be hunted or killed free of the ordinary permit rules, and what extra rule applies to protected species?",
 ["Threat to public safety or human life; harm to crops, poultry, livestock or aquaculture; spread of disease or pests; threat to aviation safety; other cases approved by the authority; for protected species the authority must be notified first unless urgent",
  "Harm to tourism quality; causing road congestion; making noise disturbing residents at night; risk of damaging landscape trees; other cases resolved by the local council; protected species may always be taken without notifying the authority",
  "Threat to public safety or human life; harm to crops, poultry, livestock or aquaculture; spread of disease or pests; threat to aviation safety; other cases approved by the authority; for protected species written central permission is always required in advance",
  "Entering private yards; foraging and trampling crops on farmland; population exceeding carrying capacity; risk of obstructing rail transport; other cases found by the industry authority; protected species need the research institute's prior assessment"],
 "Article 21, paragraph 1."),

(WL,"第21條",2,"野保法-緊急防治",
 "保育類野生動物危害農林作物、家禽、家畜或水產養殖，在緊急情況下未及報請主管機關處理時，得如何處理？",
 ["得以主管機關核定之人道方式予以獵捕或宰殺，以防治危害",
  "得以任何有效方式包括使用毒物予以獵捕或宰殺，以防治危害",
  "應待主管機關人員到場後始得予以驅離，不得自行獵捕或宰殺",
  "得委託民間獵人以商業方式大量獵捕或宰殺，以防治危害擴大"],"a",
 "第21條第2項：保育類野生動物有危害農林作物、家禽、家畜或水產養殖，在緊急情況下，未及報請主管機關處理者，得以主管機關核定之人道方式予以獵捕或宰殺以防治危害。此為第16條、第18條第1項禁止規定之例外。",
 "If protected wildlife urgently harms crops or livestock and there is no time to notify the authority, what may be done?",
 ["They may be hunted or killed by a humane method approved by the competent authority in order to prevent the harm",
  "They may be hunted or killed by any effective method, including the use of poisons, in order to prevent the harm",
  "They may only be driven away once the authority's staff arrive, and may not be hunted or killed on one's own",
  "Private hunters may be commissioned to take them commercially in bulk in order to stop the harm from spreading"],
 "Article 21, paragraph 2."),

(WL,"第21條之1",3,"野保法-原住民族",
 "原住民族基於傳統文化、祭儀或非營利自用獵捕野生動物者，其法律地位及辦法訂定機關為何？",
 ["不受第17條第1項、第18條第1項及第19條第1項第2款至第6款規定之限制，但應經主管機關核准或備查；辦法由中央主管機關會同中央原住民族主管機關定之",
  "不受任何獵捕管制規定之限制，亦無須經主管機關核准或備查；相關辦法由中央原住民族主管機關單獨訂定後報請行政院核定實施",
  "仍應完全適用第17條第1項及第18條第1項之獵捕許可規定，並須另經部落會議決議通過；辦法由中央主管機關會同內政部及各地方主管機關共同訂定之",
  "不受獵捕方法禁止規定之限制，但獵獲物不得攜出部落範圍；辦法由目的事業主管機關會同原住民族委員會分別訂定之"],"a",
 "第21條之1：原住民族基於其傳統文化、祭儀或非營利自用而有獵捕、宰殺或利用野生動物之必要者，不受第17條第1項、第18條第1項及第19條第1項第2款至第6款規定之限制；其行為應經主管機關核准或備查，相關辦法由中央主管機關會同中央原住民族主管機關定之。第51條之1並就違反情形定有專屬罰則，首次違反者不罰。",
 "What is the legal position of indigenous hunting for traditional culture, rites or non-profit personal use, and who sets the rules?",
 ["It is exempt from Article 17(1), Article 18(1) and Article 19(1) subparagraphs 2–6, but requires the authority's approval or recording; rules are set by the central authority jointly with the central indigenous peoples authority",
  "It is exempt from all hunting controls and needs no approval or recording by the authority; the rules are set by the central indigenous peoples authority alone and approved by the Executive Yuan",
  "It remains fully subject to the hunting permit rules of Article 17(1) and Article 18(1) and additionally needs a tribal assembly resolution; rules are set jointly by the central authority, the Interior Ministry and all local authorities",
  "It is exempt from the prohibited-method rules but the catch may not be taken outside the tribe; rules are set separately by the industry authority and the Council of Indigenous Peoples"],
 "Article 21-1."),

(WL,"第22條",2,"野保法-保育警察",
 "為保育野生動物，本法就執法人力及獎勵有何規定？",
 ["得設置保育警察；主管機關或受託機關團體得置野生動物保育或檢查人員於保護區內執行稽查取締，必要時得商請警察協助；對主動參與或協助取締舉發者得予以獎勵",
  "應設置專責檢察官；主管機關或受託機關團體應置野生動物司法警察於全國執行搜索扣押，必要時得商請憲兵協助；對主動參與或協助取締舉發者應處以行政罰",
  "得設置保育志工隊；主管機關或受託機關團體應置野生動物解說人員於保護區內執行導覽解說，必要時得商請消防隊協助；對主動參與或協助解說者得予以表揚",
  "應設置保育調查官；主管機關或受託機關團體得置野生動物鑑識人員於實驗室執行物種鑑定，必要時得商請海巡協助；對主動參與或協助鑑定者得核發獎狀"],"a",
 "第22條：為保育野生動物得設置保育警察；主管機關或受託機關、團體得置野生動物保育或檢查人員，並於野生動物保護區內執行稽查、取締及保育工作有關事項，必要時得商請轄區內之警察協助；執法人員、民眾或團體主動參與或協助取締、舉發違法事件者，主管機關得予以獎勵，獎勵辦法由主管機關定之。",
 "What does the Act provide on enforcement personnel and rewards?",
 ["Conservation police may be established; the authority or entrusted bodies may appoint conservation or inspection staff to inspect and enforce in refuges, may request police help, and may reward those who help crack down or report violations",
  "Dedicated prosecutors must be appointed; the authority or entrusted bodies must appoint wildlife judicial police to search and seize nationwide, may request military police assistance, and must fine those who help report violations",
  "Conservation volunteer teams may be formed; the authority or entrusted bodies must appoint interpretation staff to guide visitors in refuges, may request fire brigade help, and may commend those who help with interpretation",
  "Conservation investigators must be appointed; the authority or entrusted bodies may appoint forensic staff to identify species in laboratories, may request coast guard help, and may issue certificates to those who help"],
 "Article 22."),

(WL,"第23條",1,"野保法-國際參與",
 "民間團體或個人參與國際性野生動物保護會議或其他有關活動者，主管機關得如何處理？",
 ["主管機關得予協助或獎勵",
  "主管機關應予補助全部費用",
  "主管機關應先審查並得禁止",
  "主管機關得逕行指派代表出席"],"a",
 "第23條：民間團體或個人參與國際性野生動物保護會議或其他有關活動者，主管機關得予協助或獎勵。第22條第3項另定對協助取締舉發違法事件者之獎勵辦法。",
 "How may the authority treat groups or individuals taking part in international wildlife protection meetings or activities?",
 ["The competent authority may provide assistance or rewards",
  "The competent authority must subsidize all of their costs",
  "The competent authority must review and may prohibit it",
  "The competent authority may appoint delegates directly"],
 "Article 23."),

(WL,"第24條",2,"野保法-輸出入",
 "野生動物活體及保育類產製品之輸出入有何限制？保育類活體之輸出入以何者為限？",
 ["非經中央主管機關同意不得輸入或輸出；保育類活體之輸出入以學術研究機構、大專校院、公立或政府立案之私立動物園供教育、學術研究之用為限",
  "非經地方主管機關同意不得輸入或輸出；保育類活體之輸出入以合法登記之寵物業者、動物用藥廠商及進出口貿易商供商業販售之用為限",
  "非經目的事業主管機關同意不得輸入或輸出；保育類活體之輸出入以觀光遊樂業、馬戲團及動物表演團體供展演營利之用為限",
  "非經海關查驗同意不得輸入或輸出；保育類活體之輸出入以私人收藏家、宗教團體及民俗療法業者供個人持有之用為限"],"a",
 "第24條第1、2項：野生動物之活體及保育類野生動物之產製品，非經中央主管機關之同意不得輸入或輸出；保育類野生動物之活體，其輸入或輸出以學術研究機構、大專校院、公立或政府立案之私立動物園供教育、學術研究之用為限。違反第1項而輸出入保育類活體或產製品者依第40條第1款處六月以上五年以下有期徒刑；輸出入一般類活體者依第51條第1項第3款處罰鍰。",
 "What restricts import and export of live wildlife and protected wildlife products, and who may trade live protected animals?",
 ["No import or export without the central authority's consent; live protected animals may be traded only by academic institutions, colleges and public or registered private zoos for education or research",
  "No import or export without the local authority's consent; live protected animals may be traded only by licensed pet businesses, veterinary drug firms and import-export traders for commercial sale",
  "No import or export without the industry authority's consent; live protected animals may be traded only by tourism operators, circuses and animal performance troupes for profit-making shows",
  "No import or export without customs inspection consent; live protected animals may be traded only by private collectors, religious groups and folk remedy businesses for personal possession"],
 "Article 24, paragraphs 1–2."),

(WL,"第24條",3,"野保法-海洋哺乳類",
 "海洋哺乳類野生動物活體及產製品之輸出入，本法設有何種特別限制？未經同意者如何處理？",
 ["非經中央主管機關同意不得輸出入，且以產地國原住民族傳統領域內住民因生存所需獵捕者為限，輸入須提出證明文件；未經同意而輸出入買賣陳列展示一般類者，準用一般類管理與處罰規定並得沒入",
  "非經地方主管機關同意不得輸出入，且以產地國政府核發配額之商業捕鯨船所捕獲者為限，輸入須提出檢疫證明；未經同意而輸出入買賣陳列展示一般類者，一律免罰僅命限期補辦手續即可",
  "非經海洋委員會同意不得輸出入，且以我國籍漁船於公海合法作業所混獲者為限，輸入須提出漁獲證明；未經同意而輸出入買賣陳列展示一般類者，準用保育類規定處以有期徒刑並得沒收",
  "非經目的事業主管機關同意不得輸出入，且以經人工繁殖三代以上之個體為限，輸入須提出血統證明；未經同意而輸出入買賣陳列展示一般類者，由海關逕予退運不另處以罰鍰或沒入"],"a",
 "第24條第3至6項：海洋哺乳類野生動物活體及產製品非經中央主管機關同意不得輸入或輸出；其輸出入以產地國原住民族傳統領域內住民因生存所需獵捕者為限，輸入須提出證明文件；未經中央主管機關同意而輸入、輸出、買賣、陳列、展示一般類海洋哺乳類野生動物活體及產製品者，準用本法一般類野生動物之管理與處罰規定，並得沒入之。第2條並定海域野生動物保育之中央主管機關為海洋委員會。",
 "What special limits apply to trade in marine mammals and their products, and what if consent is lacking?",
 ["No trade without the central authority's consent, limited to takes by residents of indigenous traditional territories in the source country for subsistence, with documentation on import; unconsented trade or display of general species follows the general-species rules and items may be confiscated",
  "No trade without the local authority's consent, limited to catches by commercial whaling vessels holding source-country quotas, with quarantine certificates on import; unconsented trade or display of general species is never penalized, only a late filing is ordered",
  "No trade without the Ocean Affairs Council's consent, limited to bycatch by domestic fishing vessels lawfully operating on the high seas, with catch certificates required on import; unconsented trade or display of general species is punished as for protected species with imprisonment and confiscation",
  "No trade without the industry authority's consent, limited to individuals bred in captivity for three generations, with pedigree certificates on import; unconsented trade or display of general species is simply returned by customs with no fine or confiscation"],
 "Article 24, paragraphs 3–6."),

(WL,"第25條",2,"野保法-機構輸出入",
 "學術研究機構、大專校院、動物園、博物館或展示野生動物者，輸出入保育類野生動物或其產製品時應如何辦理？",
 ["應經中央主管機關同意，始得輸入或輸出保育類野生動物或其產製品",
  "應經地方主管機關備查，即得輸入或輸出保育類野生動物或其產製品",
  "應經目的事業主管機關核准，並報請立法院同意後始得輸入或輸出之",
  "應向海關辦理報關並繳納保證金後，即得自由輸入或輸出而不受限制"],"a",
 "第25條：學術研究機構、大專校院、公立或政府立案之私立動物園、博物館或展示野生動物者，輸入或輸出保育類野生動物或其產製品，應經中央主管機關同意。第28條並規定基於學術研究或教育目的與國外機構進行研究、交換、贈與或展示者，應自輸入輸出之日起一年內向中央主管機關提出相關報告。",
 "How must research institutions, colleges, zoos, museums or exhibitors import or export protected wildlife or their products?",
 ["They must obtain the central authority's consent before importing or exporting protected wildlife or their products",
  "They need only file with the local authority for record before importing or exporting protected wildlife or products",
  "They must obtain the industry authority's approval and the Legislative Yuan's consent before importing or exporting",
  "They may import or export freely without restriction once they clear customs and post a guarantee deposit"],
 "Article 25."),

(WL,"第26條",2,"野保法-禁止輸出入公告",
 "為文化、衛生、生態保護或政策需要而禁止野生動物或其產製品輸出入時，應依何程序辦理？違反之罰則為何？",
 ["中央主管機關得洽請貿易主管機關依貿易法之規定公告禁止輸入或輸出；違反者處新臺幣二十萬元以上一百萬元以下罰鍰",
  "中央主管機關得逕依本法之規定公告禁止輸入或輸出而無須洽請他機關；違反者處新臺幣六萬元以上三十萬元以下罰鍰",
  "地方主管機關得洽請海關依關稅法之規定公告禁止輸入或輸出；違反者處新臺幣三十萬元以上一百五十萬元以下罰鍰",
  "目的事業主管機關得洽請衛生機關依食品法規公告禁止輸入或輸出；違反者處六月以上五年以下有期徒刑得併科罰金"],"a",
 "第26條：為文化、衛生、生態保護或政策需要，中央主管機關得洽請貿易主管機關依貿易法之規定，公告禁止野生動物或其產製品輸入或輸出。第47條第2項：違反第26條規定者，處新臺幣二十萬元以上一百萬元以下罰鍰。",
 "How is an import/export ban on wildlife imposed for cultural, health, ecological or policy needs, and what is the penalty?",
 ["The central authority may ask the trade authority to announce the ban under the Foreign Trade Act; violators are fined NT$200,000 to NT$1,000,000",
  "The central authority may announce the ban directly under this Act without asking any other agency; violators are fined NT$60,000 to NT$300,000",
  "The local authority may ask customs to announce the ban under the Customs Act; violators are fined NT$300,000 to NT$1,500,000",
  "The industry authority may ask health agencies to announce the ban under food laws; violators face six months to five years imprisonment plus fines"],
 "Articles 26 and 47(2)."),

(WL,"第27條",2,"野保法-首次輸入",
 "申請首次輸入非臺灣地區原產之野生動物物種者，應辦理何種程序？",
 ["應檢附有關資料，並提出對國內動植物影響評估報告，經中央主管機關核准後始得輸入",
  "應檢附有關資料，並提出原產地合法出口證明，向地方主管機關報備後即得逕行輸入",
  "應檢附有關資料，並提出獸醫師開立之健康證明，經海關查驗相符後即得免經核准輸入",
  "應檢附有關資料，並提出國際貿易公約許可證，報請目的事業主管機關備查後始得輸入"],"a",
 "第27條第1項：申請首次輸入非臺灣地區原產之野生動物物種者，應檢附有關資料，並提出對國內動植物影響評估報告，經中央主管機關核准後始得輸入。違反者依第49條第1項第4款處新臺幣六萬元以上三十萬元以下罰鍰。第14條並規定逸失於野外之非臺灣地區原產動物得由主管機關逕為必要處置。",
 "What must be done to import a non-native wildlife species into Taiwan for the first time?",
 ["Submit the relevant materials plus an assessment report on impacts to domestic flora and fauna, and import only after the central authority approves",
  "Submit the relevant materials plus a lawful export certificate from the country of origin, and import directly after filing with the local authority",
  "Submit the relevant materials plus a veterinarian's health certificate, and import without approval once customs verifies the documents match",
  "Submit the relevant materials plus an international trade convention permit, and import only after filing with the industry authority for record"],
 "Article 27, paragraph 1."),

(WL,"第27條",2,"野保法-調查追蹤",
 "對於首次輸入之非臺灣地區原產野生動物，所在地直轄市、縣（市）主管機關有何義務？",
 ["應定期進行調查追蹤；發現有足以影響國內動植物棲息環境之虞時，應責令所有人或占有人限期提預防或補救方案並監督實施，並報請中央主管機關處理",
  "應每年辦理一次普查；發現有足以影響國內動植物棲息環境之虞時，應逕行撲殺該等野生動物並命所有人負擔費用，事後函報中央主管機關備查",
  "應委託民間團體代為管理；發現有足以影響國內動植物棲息環境之虞時，應轉知目的事業主管機關依其主管法規處理，不必再報請中央主管機關",
  "應要求所有人自行申報數量；發現有足以影響國內動植物棲息環境之虞時，應通知海關辦理退運出口並命所有人繳交保證金，報請行政院核定"],"a",
 "第27條第2項：所在地直轄市、縣（市）主管機關對首次輸入之野生動物應定期進行調查追蹤；於發現該野生動物足以影響國內動植物棲息環境之虞時，應責令所有人或占有人限期提預防或補救方案，監督其實施，並報請中央主管機關處理。不提方案或不依方案實施者，依第47條第1項處新臺幣三十萬元以上一百五十萬元以下罰鍰。",
 "What duties fall on the local authority regarding first-time imported non-native wildlife?",
 ["Conduct periodic tracking surveys; where the animals may affect domestic habitats, order the owner or possessor to submit a preventive or remedial plan within a deadline, supervise it, and report to the central authority",
  "Conduct a full census once a year; where the animals may affect domestic habitats, cull them directly at the owner's expense and report to the central authority for record afterwards",
  "Entrust management to civil groups; where the animals may affect domestic habitats, refer the matter to the industry authority to handle under its own laws without reporting to the central authority",
  "Require owners to declare the numbers themselves; where the animals may affect domestic habitats, have customs re-export them, require the owner to post a guarantee deposit, and report to the Executive Yuan for approval"],
 "Article 27, paragraph 2."),

(WL,"第28條",2,"野保法-研究報告",
 "基於學術研究或教育目的，以保育類野生動物或其產製品與國外學術研究機構進行研究、交換、贈與或展示者，應於何時向何機關提出報告？",
 ["應自輸入、輸出之日起一年內，向中央主管機關提出相關報告",
  "應自輸入、輸出之日起三十日內，向地方主管機關提出相關報告",
  "應自輸入、輸出之日起六個月內，向目的事業主管機關提出報告",
  "應自輸入、輸出之日起二年內，向野生動物研究機構提出相關報告"],"a",
 "第28條：基於學術研究或教育目的，以保育類野生動物或其產製品與國外學術研究機構進行研究、交換、贈與或展示者，應自輸入、輸出之日起一年內，向中央主管機關提出相關報告。未依限提出或報告內容不實者，依第51條第1項第4款處新臺幣一萬元以上五萬元以下罰鍰。",
 "When and to whom must a report be filed after research, exchange, donation or exhibition of protected wildlife with foreign institutions?",
 ["A report must be filed with the central competent authority within one year of the date of import or export",
  "A report must be filed with the local competent authority within thirty days of the date of import or export",
  "A report must be filed with the industry competent authority within six months of the date of import or export",
  "A report must be filed with the wildlife research institute within two years of the date of import or export"],
 "Article 28."),

(WL,"第29條",1,"野保法-海關查驗",
 "野生動物及其產製品輸入、輸出時，應由哪些機關辦理查驗與檢驗檢疫？",
 ["應由海關查驗物證相符，並由輸出入動植物檢驗、檢疫機關或其所委託之機構依相關法令辦理檢驗及檢疫",
  "應由警察機關查驗物證相符，並由地方衛生主管機關或其所委託之醫療院所依相關法令辦理檢驗及檢疫",
  "應由目的事業主管機關查驗，並由野生動物研究機構或其所委託之學術單位依相關法令辦理檢驗及檢疫",
  "應由航空港務單位查驗物證，並由環境檢驗機關或其所委託之民間實驗室依相關法令辦理檢驗及檢疫"],"a",
 "第29條：野生動物及其產製品輸入、輸出時，應由海關查驗物證相符，且由輸出入動植物檢驗、檢疫機關或其所委託之機構，依照檢驗及檢疫相關法令之規定辦理檢驗及檢疫。第30條並規定野生動物之防疫及追蹤檢疫由動植物防疫主管機關依相關法令辦理。",
 "Which agencies verify and carry out inspection and quarantine when wildlife or products are imported or exported?",
 ["Customs verifies that goods match the documents, and the import/export plant and animal inspection and quarantine agency or its commissioned body performs inspection and quarantine",
  "The police verify that goods match the documents, and the local health authority or its commissioned hospitals perform inspection and quarantine under the relevant laws",
  "The industry authority verifies the documents, and the wildlife research institute or its commissioned academic units perform inspection and quarantine under the relevant laws",
  "The airport or harbour authority verifies the documents, and environmental testing agencies or their commissioned private labs perform inspection and quarantine"],
 "Article 29."),

(WL,"第30條",1,"野保法-防疫檢疫",
 "野生動物之防疫及追蹤檢疫，應由何機關依何種法令辦理？",
 ["由動植物防疫主管機關依相關法令辦理",
  "由野生動物研究機構依本法規定辦理之",
  "由地方衛生主管機關依傳染病法令辦理",
  "由中央主管機關會同海關依關稅法辦理"],"a",
 "第30條：野生動物之防疫及追蹤檢疫，由動植物防疫主管機關依相關法令辦理。第29條規定輸出入時由海關查驗並由檢驗檢疫機關辦理檢驗及檢疫，二者分工不同。",
 "Which agency handles wildlife disease prevention and follow-up quarantine, and under which laws?",
 ["The plant and animal disease control authority handles them under the relevant laws",
  "The wildlife research institute handles them under the provisions of this Act",
  "The local health authority handles them under communicable disease laws",
  "The central authority with customs handles them under the Customs Act"],
 "Article 30."),
]
