# -*- coding: utf-8 -*-
# 第 11 批（K2）：職業安全衛生教育訓練規則、危害性化學品標示及通識規則、
#                勞工健康保護規則、女性勞工母性健康保護實施辦法、
#                妊娠與分娩後女性及未滿十八歲勞工禁止從事危險性或有害性工作認定標準（補題）
B = "OSH-11"
C = "OSH-12"
D = "OSH-10"
E = "OSH-22"
F = "OSH-20"
Q = [

# ===== OSH-11 職業安全衛生教育訓練規則 =====
(B,"第2條",2,"教育訓練規則-訓練分類",
 "本規則所定之安全衛生教育訓練共分為幾類？下列何者為其明列之類別？",
 ["共十二類；含業務主管、管理人員、作業環境監測人員、施工及製程安全評估人員等訓練","共八類；含業務主管、管理人員、作業環境監測人員及具危險性機械設備操作人員等訓練","共十五類；含業務主管、管理人員、勞動檢查員及職業安全衛生顧問服務人員等之訓練","共十類；含急救人員、一般安全衛生訓練及在職教育訓練，惟不包含特殊作業人員訓練"],"a",
 "第2條：安全衛生教育訓練分十二類，包括職業安全衛生業務主管、管理人員、作業環境監測人員、施工及製程安全評估人員、高壓氣體與營造及有害作業主管、危險性機械設備操作人員、特殊作業人員、勞工健康服務護理人員及相關人員、急救人員、一般安全衛生教育訓練、前十款之在職訓練及其他經指定者。",
 "How many categories of safety and health training does the rule set, and which are listed?",
 ["Twelve; including business supervisors, management personnel, monitoring staff and safety assessors","Eight; including business supervisors, management personnel, monitoring staff and crane operators","Fifteen; including business supervisors, management personnel, labor inspectors and consultants","Ten; including first aiders, general training and refresher training, but not special operations staff"],
 "Article 2 lists twelve categories."),

(B,"第4條",3,"教育訓練規則-營造業主管",
 "擔任營造業職業安全衛生業務主管之人員，於何種情形得免接受該項安全衛生教育訓練？",
 ["於九十八年一月八日前具勞工安全管理師等資格之一，且有一年以上營造工作經歷者","於九十八年一月八日前具勞工安全管理師等資格之一，且有三年以上營造工作經歷者","於一百零三年七月三日前具職業安全衛生管理員資格，且有二年以上營造工作經歷者","於任職前已接受一般安全衛生教育訓練六小時以上，且有五年以上營造工作經歷者"],"a",
 "第4條：雇主對擔任營造業職業安全衛生業務主管之勞工，應於事前使其接受該訓練，雇主或其代理人擔任者亦同，課程及時數依附表二。惟於中華民國九十八年一月八日前具勞工安全管理師、勞工衛生管理師、勞工安全衛生管理員或相關訓練結業證書等資格之一，且有一年以上營造工作經歷者，得免接受訓練。",
 "When may a construction industry safety and health business supervisor be exempt from the training?",
 ["Holding one of the listed qualifications before 8 Jan 2009 with over one year of construction experience","Holding one of the listed qualifications before 8 Jan 2009 with over three years of construction work","Holding a safety and health management staff qualification before 3 July 2014 with two years of work","Having taken six hours of general safety training before appointment with five years of construction work"],
 "Article 4, paragraph 3."),

(B,"第7條",2,"教育訓練規則-施工安全評估",
 "雇主對擔任施工安全評估之勞工，應於何時使其接受教育訓練？課程及時數之依據為何？",
 ["應於事前使其接受施工安全評估人員之安全衛生教育訓練；課程及時數依附表五之規定","應於到職後三個月內使其接受施工安全評估人員教育訓練；課程及時數依附表六之規定","應於事前使其接受製程安全評估人員之安全衛生教育訓練；課程及時數依附表六之規定","應於事前使其接受營造業職業安全衛生業務主管訓練；課程及時數依附表二之相關規定"],"a",
 "第7條：雇主對擔任施工安全評估之勞工，應於事前使其接受施工安全評估人員之安全衛生教育訓練，課程及時數依附表五之規定。第8條之製程安全評估人員訓練則依附表六辦理。",
 "When must workers doing construction safety assessment be trained, and under which table?",
 ["Beforehand, on the construction safety assessor training; courses and hours follow Table 5","Within three months of taking the post, on that training; courses and hours follow Table 6","Beforehand, on the process safety assessor training; courses and hours follow Table 6 rules","Beforehand, on construction industry supervisor training; courses and hours follow Table 2"],
 "Article 7 requires prior training under Table 5."),

(B,"第8條",2,"教育訓練規則-製程安全評估",
 "雇主對擔任製程安全評估之勞工，其教育訓練之時點及課程時數依據為何？",
 ["應於事前使其接受製程安全評估人員之安全衛生教育訓練；課程及時數依附表六之規定","應於事前使其接受施工安全評估人員之安全衛生教育訓練；課程及時數依附表五之規定","應於指派後六個月內接受製程安全評估人員教育訓練；課程及時數依附表五之相關規定","應每二年接受製程安全評估人員在職教育訓練一次；課程及時數依附表十五之相關規定"],"a",
 "第8條：雇主對擔任製程安全評估之勞工，應於事前使其接受製程安全評估人員之安全衛生教育訓練，課程及時數依附表六之規定。第7條施工安全評估人員訓練則依附表五。",
 "When must process safety assessors be trained, and under which table?",
 ["Beforehand, on the process safety assessor training; courses and hours follow Table 6","Beforehand, on the construction safety assessor training; courses and hours follow Table 5","Within six months after assignment, on that training; courses and hours follow Table 5","Every two years as refresher training; courses and hours follow Table 15 of the rules"],
 "Article 8 requires prior training under Table 6."),

(B,"第15條",2,"教育訓練規則-健康服務人員",
 "雇主對從事勞工健康服務之護理人員及相關人員之安全衛生教育訓練，其課程時數及講師資格依何規定？",
 ["應使其接受勞工健康服務之安全衛生教育訓練；課程時數及講師資格依勞工健康保護規則","應使其接受勞工健康服務之安全衛生教育訓練；課程時數及講師資格依本規則附表十五","應使其接受急救人員之安全衛生教育訓練；課程時數及講師資格依醫療機構管理辦法規定","應使其接受一般安全衛生教育訓練；課程時數及講師資格由訓練單位自行擬訂報請備查"],"a",
 "第15條：雇主對從事勞工健康服務之護理人員及勞工健康服務相關人員，應使其接受勞工健康服務之安全衛生教育訓練，其課程、時數及講師資格依勞工健康保護規則之規定。第35條所定附表十五之講師資格，適用範圍為第三條至第十四條及第十六條之訓練。",
 "Which rules govern courses, hours and instructor qualifications for occupational health service nurses?",
 ["They must take the health service training; courses, hours and instructors follow the Health Protection Rules","They must take the health service training; courses, hours and instructors follow Table 15 of these rules","They must take first aider training; courses, hours and instructors follow the medical institution rules","They must take general safety training; courses, hours and instructors are set by the training unit itself"],
 "Article 15 defers to the Labor Health Protection Rules."),

(B,"第20條之1",2,"教育訓練規則-認可申請",
 "訓練單位申請對外招訓之認可，應檢附哪些文件？文件未備齊時如何處理？",
 ["申請書、職業訓練機構設立證書影本、安全衛生推廣績效證明及其他規定文件；得限期補正","申請書、公司登記證明文件、資本額查核報告書及其他規定文件；未備齊者一律不予受理","評鑑自評表、人才發展品質管理系統評核證明及其他規定文件；未備齊者得逕予核准認可","教育訓練場所報備書、課程表、講師概況及學員名冊等；未備齊者由地方主管機關補正"],"a",
 "第20條之1：申請第二十條第二項認可者，應檢附申請書、職業訓練機構設立證書影本、安全衛生推廣績效證明文件及其他經中央主管機關規定之文件；文件未備齊者，中央主管機關得通知限期補正，屆期未補正或補正未完全者，不予受理。",
 "What documents must accompany an application for recognition, and what if they are incomplete?",
 ["Application, training institution certificate copy, publicity performance proof and other documents; correctable","Application, company registration, capital verification report and other documents; rejected outright","Self-assessment form, talent quality management certificate and others; approved without further review","Venue filing form, course list, instructor profiles and roster; the local authority completes them"],
 "Article 20-1, paragraphs 1 and 2."),

(B,"第20條之2",2,"教育訓練規則-自主管理",
 "經中央主管機關認可之訓練單位對外招訓時，應建立何種制度？其依據為何？",
 ["應參照中央主管機關公告之相關指引，建立安全衛生教育訓練自主管理制度後對外招訓","應參照地方主管機關公告之作業要點，建立教育訓練品質保證及退費爭議處理之制度","應報經勞動檢查機構核定後，建立學員資格查核及訓練期滿證明核發之內部稽核制度","應依國家標準CNS 45001規定建立職業安全衛生管理系統，並每三年接受外部驗證"],"a",
 "第20條之2：經中央主管機關依第二十條第二項規定認可之訓練單位（認可訓練單位）對外招訓時，應參照中央主管機關公告之相關指引，建立安全衛生教育訓練自主管理制度。",
 "What system must a recognized training unit build before recruiting externally?",
 ["A self-management system for safety and health training, following guidelines announced centrally","A quality assurance and refund dispute system, following operating points issued locally","An internal audit system for checking trainee eligibility, approved by the inspection agency","A CNS 45001 occupational safety management system, externally certified every three years"],
 "Article 20-2 requires a self-management system."),

(B,"第20條之4",2,"教育訓練規則-評鑑申請",
 "認可訓練單位申請職業安全衛生教育訓練單位評鑑，應檢附哪些文件？",
 ["評鑑自評表、符合第二十條之三第一項規定之資格文件及其他中央主管機關規定之文件","申請書、職業訓練機構設立證書影本、安全衛生推廣績效證明及其他規定之相關文件","教育訓練計畫報備書、課程表、講師概況、學員名冊及專責輔導員名單等五款之文件","學員簽到紀錄、受訓學員點名紀錄、成績冊及結業證書核發清冊等結訓後保存文件"],"a",
 "第20條之4：申請第二十條之三第一項評鑑者，應檢附評鑑自評表、符合該項規定之資格文件及其他經中央主管機關規定之文件；文件未備齊者得通知限期補正，屆期未補正或補正未完全者，不予受理。第20條之3並定評鑑結果分優等、甲等、乙等及丙等並公開之。",
 "What documents must accompany an application for training unit evaluation?",
 ["A self-assessment form, documents proving eligibility under Article 20-3, and other required papers","An application, training institution certificate copy, publicity performance proof and other papers","The training plan filing form, course list, instructor profiles, roster and dedicated counselor list","Trainee sign-in records, roll-call records, grade books and certificate issuance lists after training"],
 "Article 20-4, paragraph 1."),

(B,"第21條",2,"教育訓練規則-評鑑等級",
 "認可訓練單位辦理第五條、第十二條第一項第一款等指定之教育訓練前，須具備何種評鑑資格？",
 ["須依第二十條之三第一項規定經中央主管機關評鑑，並具甲等以上之資格始得辦理","須依第二十條之三第一項規定經中央主管機關評鑑，並具乙等以上之資格始得辦理","須經地方主管機關查核合格，並取得人才發展品質管理系統評核通過證明後辦理","須經勞動檢查機構評鑑列為優等，並報請中央主管機關核定招訓區域後始得辦理"],"a",
 "第21條：認可訓練單位辦理第五條、第十二條第一項第一款第二款、第十三條第一項第一款第二款及第十四條第一項第二款之教育訓練、第十八條第一項第二款之在職教育訓練及其他經中央主管機關指定者，應依第二十條之三第一項規定經評鑑並具甲等以上之資格。",
 "What evaluation grade must a recognized training unit hold to run the designated training?",
 ["It must be evaluated by the central authority under Article 20-3 and hold at least Grade A","It must be evaluated by the central authority under Article 20-3 and hold at least Grade B","It must pass a local authority audit and hold a talent quality management pass certificate","It must be rated excellent by the inspection agency and have its region approved centrally"],
 "Article 21 requires Grade A or above."),

(B,"第22條",3,"教育訓練規則-辦理範圍",
 "第二十條第一項第六款經核可之非營利急救訓練單位，得辦理何種安全衛生教育訓練？",
 ["以辦理急救人員安全衛生教育訓練為限；第五款者得辦理健康服務人員及急救人員訓練","以辦理勞工健康服務護理人員訓練為限；第五款者則僅得辦理急救人員之安全衛生訓練","得辦理第三條至第十六條之各類安全衛生教育訓練，不受訓練種類或對象之任何限制","以辦理事業單位自有勞工及其承攬人勞工之安全衛生教育訓練為限，不得對外招訓辦理"],"a",
 "第22條第1項：第二十條第一項第五款之訓練單位，以辦理勞工健康服務護理人員、勞工健康服務相關人員及急救人員訓練為限；第六款之訓練單位，以辦理急救人員安全衛生教育訓練為限。第2項、第3項並定第二款至第四款、第七款至第九款訓練單位辦理急救及健康服務人員訓練時之合辦要求。",
 "What training may a recognized non-profit first aid training unit (item 6) provide?",
 ["Only first aider safety and health training; item 5 units may train health service staff and first aiders","Only occupational health service nurse training; item 5 units may train first aiders only in that field","Any of the training under Articles 3 to 16, with no restriction on the type or target of the training","Only training for the entity's own workers and its contractors' workers, never external recruitment"],
 "Article 22, paragraph 1."),

(B,"第23條",3,"教育訓練規則-場所核定",
 "訓練單位辦理第三條至第十六條之教育訓練前，應向何機關辦理何種程序？應檢附之文件為何？",
 ["報請地方主管機關核定；含場所報備書、資格文件、量測設備及防護具、術科場地機具等","報請中央主管機關認可；含申請書、設立證書影本、推廣績效證明及其他規定之文件等","報請勞動檢查機構備查；含教育訓練計畫報備書、課程表、講師概況及學員名冊等文件","報請目的事業主管機關許可；含消防安全設備文件、建物用途證明及責任保險證明等"],"a",
 "第23條第1項：訓練單位辦理第三條至第十六條之教育訓練前，應檢附教育訓練場所報備書、符合資格之文件、置備之安全衛生量測設備及個人防護具、術科場地實習機具及設備、訓練場所設施、消防安全設備文件及建物用途證明，報請地方主管機關核定；變更時亦同。第2項並定量測設備及防護具應為申請訓練場所專用。",
 "To which authority, and with what documents, must a training venue be submitted before training?",
 ["To the local authority for approval; venue filing form, eligibility papers, measuring gear and venues","To the central authority for recognition; application, certificate copy, performance proof and papers","To the inspection agency for filing; training plan filing form, course list, instructors and roster","To the industry authority for a permit; fire safety documents, building use proof and insurance"],
 "Article 23, paragraph 1."),

(B,"第24條",2,"教育訓練規則-辦理區域",
 "經核定之訓練單位辦理安全衛生教育訓練，其辦理區域有何限制？何種情形不受限制？",
 ["應於地方主管機關核定之區域內辦理；但經中央主管機關評鑑職類優等者，不受此限","應於地方主管機關核定之區域內辦理；但經中央主管機關評鑑職類甲等者，不受此限","應於中央主管機關認可之區域內辦理；但經地方主管機關同意跨區辦理者，不受此限","得於全國各地自由辦理；但辦理急救人員訓練者，應於核定區域內辦理不得跨區域"],"a",
 "第24條：經第二十三條核定之訓練單位，應於地方主管機關核定之區域內辦理安全衛生教育訓練；但依第二十條之三第一項規定經中央主管機關評鑑職類優等者，不在此限。",
 "Where may an approved training unit hold training, and what is the exception?",
 ["Within the region approved by the local authority; unless rated excellent for that field centrally","Within the region approved by the local authority; unless rated Grade A for that field centrally","Within the region recognized by the central authority; unless the local authority allows crossing","Anywhere nationwide; except first aider training, which must stay within the approved region"],
 "Article 24 and its proviso."),

(B,"第26條",2,"教育訓練規則-在職訓練報備",
 "訓練單位辦理安全衛生在職教育訓練，應於何時報請何機關辦理何種程序？",
 ["應於十五日前檢附文件報請地方主管機關備查；文件變動至遲於開訓前一日報請備查","應於三十日前檢附文件報請地方主管機關核定；文件變動至遲於開訓前七日報請核定","應於十五日前檢附文件報請中央主管機關認可；文件變動至遲於開訓當日報請其認可","應於開訓後十日內檢附文件報請勞動檢查機構備查；文件變動無須另行報請其備查"],"a",
 "第26條：訓練單位辦理第十八條第一項第一款至第九款之在職教育訓練，應於十五日前檢附第二十五條第一項第一款至第四款文件報請地方主管機關備查；勞工主管機關或勞動檢查機構不適用之。文件內容有變動者，至遲於開訓前一日報請備查始可開訓。中央主管機關並得公告課程綱要供辦理。",
 "When and to whom must refresher safety training be reported?",
 ["Fifteen days beforehand, filed with the local authority; changes filed at latest the day before training","Thirty days beforehand, approved by the local authority; changes approved at latest seven days before","Fifteen days beforehand, recognized by the central authority; changes recognized on the training day","Within ten days after training starts, filed with the inspection agency; changes need no further filing"],
 "Article 26, paragraphs 1 and 4."),

(B,"第27條",2,"教育訓練規則-結訓證明",
 "中央主管機關公告以技術士技能檢定為測驗方式之職類，訓練單位對期滿學員應如何處理？",
 ["應於結訓後十五日內發給訓練期滿證明；該職類之測驗方式由中央主管機關公告之","應於結訓後三十日內發給結業證書；該職類之測驗方式由地方主管機關公告核定之","應於結訓後十五日內發給結業證書；該職類之測驗由訓練單位自行辦理並核發證書","應於結訓後七日內發給訓練期滿證明；該職類測驗方式由技能檢定機構自行公告之"],"a",
 "第27條：第三條至第十六條之教育訓練技術或管理職類，中央主管機關得就其一部或全部公告測驗方式為技術士技能檢定；訓練單位對於接受該職類訓練期滿者，應於結訓後十五日內發給訓練期滿證明（格式十）。",
 "For fields tested by skill certification, what must the training unit issue and when?",
 ["A training completion certificate within 15 days of the end; the authority announces the test mode","A graduation certificate within 30 days of the end; the local authority announces the test mode","A graduation certificate within 15 days; the training unit runs the test and issues the certificate","A training completion certificate within 7 days; the certification body announces the test mode"],
 "Article 27, paragraph 2."),

(B,"第30條",2,"教育訓練規則-停止業務",
 "訓練單位停止辦理安全衛生教育訓練業務時，應如何辦理？",
 ["應於十五日前報請地方主管機關備查，並將建置資料之電子檔移送中央主管機關","應於三十日前報請中央主管機關備查，並將建置資料之電子檔移送地方主管機關","應於停止後十日內報請勞動檢查機構備查，並將全部紙本資料移送地方主管機關","應於十五日前報請中央主管機關核准，並將建置資料之電子檔自行銷毀不得留存"],"a",
 "第30條：訓練單位對第二十三條、第二十五條、第二十六條及第二十九條規定之文件，應依中央主管機關公告之內容、期限及方式登錄；停止辦理教育訓練業務者，應於十五日前報請地方主管機關備查，並將第二十九條建置資料之電子檔移送中央主管機關。",
 "What must a training unit do when it stops providing safety and health training?",
 ["File with the local authority 15 days beforehand and send the electronic records to the central authority","File with the central authority 30 days beforehand and send the electronic records to the local authority","File with the inspection agency within 10 days after stopping and send all paper records to the local authority","Get the central authority's approval 15 days beforehand and destroy the electronic records itself"],
 "Article 30, paragraph 2."),

(B,"第32條",2,"教育訓練規則-查核",
 "對於訓練單位辦理本規則之教育訓練，主管機關之查核權限如何分配？",
 ["地方主管機關得予查核；中央主管機關於必要時得予抽查，並得向其索取相關資料","中央主管機關得予查核；地方主管機關於必要時得予抽查，但不得索取訓練相關資料","僅勞動檢查機構得予查核及抽查；地方主管機關與中央主管機關均無查核之權限者","由目的事業主管機關查核；中央主管機關僅得於接獲檢舉時派員抽查並索取其資料"],"a",
 "第32條：地方主管機關對於訓練單位辦理本規則之教育訓練，得予查核；中央主管機關於必要時，得予抽查。主管機關為查核及監督訓練成效，得向其索取教育訓練相關資料。第39條第10款並定拒絕、規避或阻撓查核或評鑑者，得處罰鍰並令限期改正。",
 "How is inspection authority over training units allocated?",
 ["The local authority may audit; the central authority may spot-check when necessary and request data","The central authority may audit; the local authority may spot-check but may not request any data","Only the inspection agency may audit or spot-check; neither local nor central authority may do so","The industry authority audits; the central authority spot-checks only when a complaint is received"],
 "Article 32, paragraphs 1 and 2."),

(B,"第34條",2,"教育訓練規則-費用用途",
 "訓練單位辦理安全衛生教育訓練所收取之費用，依規定應用於哪些用途？",
 ["講師授課酬勞、講師培訓、測驗費、證書費、職員薪津、辦公費、房租及必要教學支出","講師授課酬勞、學員交通住宿補助、廣告行銷費用、股東紅利分配及必要之教學支出","測驗費、證書費、罰鍰之繳納、營業稅款、機構盈餘分配及從事安全衛生活動之支出","職員薪津、辦公費、房租、設備採購、對外轉投資及捐贈政治團體等安全衛生支出"],"a",
 "第34條：訓練單位辦理安全衛生教育訓練所收取之費用，應用於講師授課酬勞、講師培訓、測驗費、證書費、職員薪津、辦公費、房租、必要教學支出及從事安全衛生活動之用。",
 "What may fees collected for safety and health training be spent on?",
 ["Instructor fees, instructor training, test and certificate fees, salaries, office costs, rent and teaching","Instructor fees, trainee travel and lodging subsidies, advertising, shareholder dividends and teaching","Test and certificate fees, payment of fines, business tax, profit distribution and safety activities","Salaries, office costs, rent, equipment, outside investment and donations to political groups"],
 "Article 34 lists the permitted uses."),

(B,"第35條",1,"教育訓練規則-講師資格",
 "訓練單位辦理第三條至第十四條及第十六條之教育訓練時，講師資格應符合何規定？",
 ["應符合本規則附表十五所定之講師資格規定，並於報備時檢附講師概況供查核","應符合本規則附表二所定之課程及時數規定，並由地方主管機關逐案審查資格","應具職業安全衛生管理員資格並接受講習每二年至少六小時，其餘資格不採認","應由中央主管機關統一遴聘並造冊公告，訓練單位不得自行聘任講師擔任授課"],"a",
 "第35條：訓練單位辦理第三條至第十四條及第十六條之教育訓練時，講師資格應符合附表十五之規定。第25條第1項第3款並定報備時應檢附講師概況（格式八）。第15條之勞工健康服務人員訓練講師資格則依勞工健康保護規則。",
 "What must instructor qualifications comply with for the training under Articles 3 to 14 and 16?",
 ["Table 15 of these rules, with instructor profiles submitted at filing for verification","Table 2 of these rules on courses and hours, reviewed case by case by the local authority","Holding a safety management staff qualification plus six hours of training every two years","Being appointed and listed by the central authority; units may not hire instructors themselves"],
 "Article 35 refers to Table 15."),

(B,"第36條",3,"教育訓練規則-教材編製",
 "訓練單位編製教育訓練教材應踐行何種程序？教材經中央主管機關指定或統一編製者應如何處理？",
 ["應設編輯及審查會依法定課程與公告課綱編輯，報中央主管機關備查；統一編製者不得自編","應設編輯及審查會依法定課程與公告課綱編輯，報地方主管機關核定；統一編製者仍得自編","得逕由授課講師自行編寫教材使用，僅需於開訓前一日報備；統一編製者得擇一使用之","應委託學術機構編製並報請勞動檢查機構審查，修正時免再報備；統一編製者僅供參考"],"a",
 "第36條：訓練單位對第三條至第十六條教育訓練教材之編製，應設編輯及審查會，並依法定課程名稱、時數及中央主管機關公告之課程綱要編輯，於審查完成後將相關資料連同教材報請中央主管機關備查，修正時亦同；教材經中央主管機關指定或統一編製者，訓練單位應以其為教材使用，不得自行編製。",
 "What procedure applies to preparing training materials, and to centrally issued materials?",
 ["Set an editing and review board, edit per the official outline, file centrally; no self-editing if issued","Set an editing and review board, edit per the official outline, get local approval; self-editing allowed","Instructors may write materials freely, filed the day before training; centrally issued ones optional","Commission an academic body and have the inspection agency review; centrally issued ones advisory"],
 "Article 36, paragraphs 1 and 2."),

(B,"第38條",3,"教育訓練規則-警告改正",
 "訓練單位有下列何種情事者，主管機關應依本法第四十八條規定予以警告並令其限期改正？",
 ["未依第三十三條規定辦理、訓練教材方式或目標違反勞動法令、未依訓練計畫內容實施等","招訓廣告或簡章內容虛偽不實、未於核備之訓練場所實施教育訓練、未依規定辦理測驗等","未經中央主管機關認可即對外招訓、未具評鑑甲等以上資格即辦理指定之教育訓練者等","拒絕規避或阻撓主管機關業務查核或評鑑、未核實登載結業證書核發清冊之資料等情事"],"a",
 "第38條列舉警告並令限期改正之五款情事：未依第三十三條規定辦理、訓練教材或訓練方式或訓練目標違反勞動法令、未依訓練計畫內容實施、經查核發現違反本規則、其他違反中央主管機關規定。至於選項所述之虛偽招訓廣告、未經認可即對外招訓、拒絕查核等，則屬第39條處以罰鍰之事由。",
 "Which conduct triggers a warning and an order to correct within a period?",
 ["Failing to comply with Article 33, materials or aims breaching labor law, not following the training plan","False recruitment advertising, training outside the filed venue, failing to hold the required tests","Recruiting externally without central recognition, running designated training without Grade A status","Refusing or obstructing audits or evaluation, and false entries in certificate issuance lists"],
 "Article 38 lists five grounds for a warning."),

(B,"第40條",3,"教育訓練規則-撤銷廢止",
 "訓練單位經撤銷或廢止認可後，於幾年內有何種情形者，中央主管機關應不予認可？",
 ["三年內以同一名稱或於同一地點申請認可，或其負責人以不同申請單位負責人申請者","五年內以同一名稱或於同一地點申請認可，或其負責人以不同申請單位負責人申請者","一年內以同一名稱申請認可者；惟變更負責人或遷移訓練場所後即得重新申請認可","十年內申請認可者一律不予受理，且其負責人終身不得再以任何名義申請訓練認可"],"a",
 "第40條：訓練單位有第三十八條、第三十九條情形而屆期未改正或情節重大者，主管機關得撤銷或廢止其認可，或定期停止其訓練業務之一部或全部；經撤銷或廢止認可者，於三年內以同一名稱或於同一地點申請認可，或其負責人以不同申請單位之負責人申請認可者，中央主管機關應不予認可。",
 "Within how many years, and in which situations, must recognition be refused after revocation?",
 ["Three years; applying under the same name or at the same site, or the same person as another unit's head","Five years; applying under the same name or at the same site, or the same person as another unit's head","One year and only under the same name; changing the head or moving the venue allows reapplication","Ten years for any application, and the responsible person is barred for life from any application"],
 "Article 40, paragraph 4."),

(B,"第41條",2,"教育訓練規則-罰則沿革",
 "關於本規則罰則章之現行規定，下列敘述何者正確？",
 ["第四十一條已刪除；訓練單位之警告、罰鍰及撤銷廢止認可分依第三十八條至第四十條辦理","第四十一條仍為現行條文；訓練單位之警告、罰鍰及撤銷廢止均統一依該條規定辦理處分","第三十八條至第四十條均已刪除；訓練單位之處分一律回歸職業安全衛生法第四十八條處理","第三十九條已刪除；訓練單位之罰鍰處分改依職業訓練法第三十九條規定移送地方機關辦理"],"a",
 "本規則第41條已刪除。現行罰則以第38條（警告並令限期改正）、第39條（處以罰鍰並令限期改正，列舉十五款情事）及第40條（屆期未改正或情節重大者撤銷、廢止認可或停止訓練業務）為主，均依本法第四十八條規定辦理。",
 "Which statement about the current penalty chapter of these rules is correct?",
 ["Article 41 is deleted; warnings, fines and revocation are handled under Articles 38 to 40 respectively","Article 41 remains in force; warnings, fines and revocation are all handled under that one article","Articles 38 to 40 are deleted; all sanctions revert directly to Article 48 of the parent Act instead","Article 39 is deleted; fines are now imposed under Article 39 of the Vocational Training Act instead"],
 "Article 41 has been deleted."),

(B,"第42條之1",3,"教育訓練規則-過渡規定",
 "本規則一百十四年九月四日修正施行前已對外招訓之非營利法人等訓練單位，應於何時前取得認可？",
 ["應於一百十六年十二月三十一日前經中央主管機關依第二十條第二項認可，始得對外招訓","應於一百十五年十二月三十一日前經中央主管機關依第二十條第二項認可，始得對外招訓","應於一百十六年十二月三十一日前報請地方主管機關核定，逾期仍得繼續招訓不受限制","應於一百十八年十二月三十一日前經勞動檢查機構評鑑甲等，始得繼續辦理其對外招訓"],"a",
 "第42條之1：本規則一百十四年九月四日修正施行前已對外招訓之原經認可非營利法人，及未經認可之非營利法人、雇主團體、勞工團體，應於一百十六年十二月三十一日前經中央主管機關依第二十條第二項認可，經認可後始得對外招訓；原經認可者屆期未重新認可，得廢止其原認可。",
 "By when must training units already recruiting externally obtain recognition?",
 ["By 31 December 2027, recognized by the central authority under Article 20-2, before recruiting again","By 31 December 2026, recognized by the central authority under Article 20-2, before recruiting again","By 31 December 2027, approved by the local authority; recruitment may continue even if they miss it","By 31 December 2029, rated Grade A by the inspection agency, before continuing to recruit externally"],
 "Article 42-1, paragraph 1."),

(B,"第42條之2",2,"教育訓練規則-過渡規定",
 "本規則修正施行前曾經評鑑且評鑑結果未明定效期之訓練單位，應如何處理？",
 ["應於本規則修正施行之日起五年內依第二十條之三申請評鑑；屆期未申請者得廢止其結果","應於本規則修正施行之日起三年內依第二十條之三申請評鑑；屆期未申請者得廢止其結果","其原評鑑結果永久有效無須重新申請評鑑，中央主管機關亦不得廢止其原評鑑之結果者","應於本規則修正施行之日起一年內重新申請認可；屆期未申請者由地方主管機關撤銷之"],"a",
 "第42條之2：本規則一百十四年九月四日修正施行前，訓練單位曾經評鑑且評鑑結果未明定效期者，應於本規則修正施行之日起五年內，依第二十條之三申請評鑑；屆期未申請評鑑者，中央主管機關得廢止其原經評鑑之結果。",
 "What must training units evaluated before the amendment, with no stated validity period, do?",
 ["Apply for evaluation under Article 20-3 within five years of the amendment, or the result may be revoked","Apply for evaluation under Article 20-3 within three years of the amendment, or the result may be revoked","Their old evaluation result is valid forever and the central authority may not revoke it at any time","Reapply for recognition within one year of the amendment, failing which the local authority revokes it"],
 "Article 42-2 sets a five-year window."),

(B,"第42條之3",1,"教育訓練規則-委託辦理",
 "本規則所定之認可、評鑑事項，中央主管機關得如何辦理？",
 ["得委託學術機構或相關專業團體辦理之，不以自行辦理為限","得委託地方主管機關或勞動檢查機構辦理，不得委託民間","應由中央主管機關自行辦理，不得委託任何機構團體辦理","得委由受評鑑之訓練單位相互辦理，並報中央主管機關備查"],"a",
 "第42條之3：本規則所定之認可、評鑑事項，中央主管機關得委託學術機構或相關專業團體辦理之。第20條之1、第20條之4分別定認可與評鑑之申請文件及補正規定。",
 "How may the central authority handle recognition and evaluation matters?",
 ["It may commission academic institutions or relevant professional bodies to handle them","It may commission the local authority or inspection agency, but never private bodies","It must handle them itself and may not commission any institution or body at all","It may let evaluated training units evaluate each other and file the results centrally"],
 "Article 42-3 allows commissioning."),

(B,"第43條",2,"教育訓練規則-施行日期",
 "關於職業安全衛生教育訓練規則之施行日期，下列敘述何者正確？",
 ["本規則自發布日施行；一百十四年九月四日修正發布之條文，自一百十五年一月一日施行","本規則自發布日施行；一百十四年九月四日修正發布之條文，自一百十六年一月一日施行","本規則自發布後六個月施行；一百十四年九月四日修正發布之條文自發布日起即施行","本規則自發布日施行；一百十五年六月二十五日修正之條文自一百十六年七月一日施行"],"a",
 "第43條：本規則自發布日施行；一百十四年九月四日修正發布之條文自一百十五年一月一日施行；一百十五年六月二十五日修正發布之條文，除第三條附表一、第四條附表二、第五條附表三自一百十六年一月一日施行外，自一百十五年七月一日施行。",
 "Which statement about the effective dates of these Rules is correct?",
 ["The Rules take effect on promulgation; the 4 Sept 2025 amendments take effect on 1 Jan 2026","The Rules take effect on promulgation; the 4 Sept 2025 amendments take effect on 1 Jan 2027","The Rules take effect six months after promulgation; the 2025 amendments on promulgation","The Rules take effect on promulgation; the 25 June 2026 amendments take effect 1 July 2027"],
 "Article 43."),

# ===== OSH-12 危害性化學品標示及通識規則 =====
(C,"第1條",1,"危害通識規則-授權依據",
 "危害性化學品標示及通識規則係依何規定訂定？",
 ["依職業安全衛生法第十條第三項規定訂定之","依職業安全衛生法第十一條第二項規定訂定","依職業安全衛生法第七條第四項規定訂定之","依毒性及關注化學物質管理法第十條訂定"],"a",
 "第1條：本規則依職業安全衛生法第十條第三項規定訂定。本法第10條第1項課雇主標示及製備安全資料表之義務，第12條、第13條並定安全資料表之提供與混合物危害性認定。",
 "Under which provision are these Regulations enacted?",
 ["Article 10, paragraph 3 of the Occupational Safety and Health Act","Article 11, paragraph 2 of the Occupational Safety and Health Act","Article 7, paragraph 4 of the Occupational Safety and Health Act","Article 10 of the Toxic and Concerned Chemical Substances Act"],
 "Article 1 cites Article 10-3 of the Act."),

(C,"第13條",3,"危害通識規則-安全資料表",
 "製造者、輸入者或供應者提供化學品前應提供何種文件？混合物之危害性如何認定？",
 ["應提供安全資料表；已作整體測試者依測試結果，未作者健康危害依CNS15030分類標準","應提供安全資料表；已作整體測試者依成分推估結果，未作者健康危害依濃度加權計算","應提供危害通識計畫；已作整體測試者依測試結果，未作者依供應商提供之資料認定","應提供危害性化學品清單；不論是否作整體測試，一律依CNS15030混合物分類標準"],"a",
 "第13條：製造者、輸入者或供應者提供化學品與事業單位或自營作業者前，應提供安全資料表；混合物已作整體測試者依整體測試結果，未作整體測試者其健康危害性除有科學資料佐證外，依國家標準CNS15030分類之混合物分類標準，物理性危害則使用有科學根據之資料評估。第15條並定至少每三年檢討一次。",
 "What must be provided before supplying a chemical, and how is a mixture's hazard determined?",
 ["A safety data sheet; whole-mixture test results if tested, otherwise CNS15030 mixture classification","A safety data sheet; component estimates if tested, otherwise a concentration-weighted calculation","A hazard communication plan; test results if tested, otherwise the supplier's own supplied data","A hazardous chemical inventory; CNS15030 mixture classification whether or not it was tested"],
 "Article 13, paragraphs 1 and 2."),

(C,"第16條",2,"危害通識規則-條文沿革",
 "關於安全資料表之更新及本規則現行條文，下列敘述何者正確？",
 ["第十六條已刪除；安全資料表應適時更新並至少每三年檢討一次，更新紀錄應保存三年","第十六條仍為現行條文；安全資料表應至少每五年檢討一次，其更新紀錄應保存五年","第十六條已刪除；安全資料表僅於危害成分變更時始須更新，且無保存更新紀錄義務","第十六條已刪除；安全資料表之檢討更新改依毒性及關注化學物質管理法規定辦理之"],"a",
 "本規則第16條已刪除。安全資料表之檢討更新依第15條規定：製造者、輸入者、供應者或雇主應依實際狀況檢討其內容正確性、適時更新，並至少每三年檢討一次；更新之內容、日期、版次等紀錄應保存三年。",
 "Which statement about updating safety data sheets and the current text is correct?",
 ["Article 16 is deleted; sheets must be updated and reviewed at least every three years, records kept three years","Article 16 is still in force; sheets must be reviewed at least every five years and records kept five years","Article 16 is deleted; sheets need updating only when components change and no records need keeping","Article 16 is deleted; review and updating now follow the Toxic and Concerned Chemical Substances Act"],
 "Article 16 is deleted; Article 15 governs updating."),

(C,"第22條",1,"危害通識規則-適用除外",
 "對農藥及環境用藥等危害性化學品之標示，應依何規定辦理？",
 ["應依農藥及環境用藥相關法規之規定辦理其標示事項","應依本規則附表一及附表二之規定辦理其標示事項","應依游離輻射及環境保護相關法規辦理其標示事項","應由中央主管機關逐案指定標示方式報環境部核定"],"a",
 "第22條：對農藥及環境用藥等危害性化學品之標示，應依農藥及環境用藥相關法規規定辦理。第21條並定放射性物質、CNS15030分類之環境危害性化學品標示，應依游離輻射及環境保護相關法規辦理。",
 "Which rules govern the labelling of pesticides and environmental agents?",
 ["The labelling follows the relevant pesticide and environmental agent legislation","The labelling follows Tables 1 and 2 of these Regulations on hazard labelling","The labelling follows the ionizing radiation and environmental protection laws","The central authority designates the method case by case with ministry approval"],
 "Article 22 defers to pesticide and environmental agent laws."),

# ===== OSH-10 勞工健康保護規則 =====
(D,"第1條",1,"勞工健康保護規則-授權依據",
 "勞工健康保護規則係依職業安全衛生法哪些規定訂定？",
 ["依本法第六條第三項、第二十條第三項、第二十一條第三項及第二十二條第三項訂定","依本法第六條第三項、第十條第三項、第二十條第三項及第三十一條第三項規定訂定","依本法第二十條第三項、第二十一條第三項、第二十九條第二項及第三十條第四項訂定","依本法第五條第二項、第十一條第二項、第二十三條第四項及第三十四條第二項訂定"],"a",
 "第1條：本規則依職業安全衛生法第六條第三項、第二十條第三項、第二十一條第三項及第二十二條第三項規定訂定。第29條並定本規則之分階段施行日期。",
 "Under which provisions of the Act are these Rules enacted?",
 ["Articles 6-3, 20-3, 21-3 and 22-3 of the Occupational Safety and Health Act","Articles 6-3, 10-3, 20-3 and 31-3 of the Occupational Safety and Health Act","Articles 20-3, 21-3, 29-2 and 30-4 of the Occupational Safety and Health Act","Articles 5-2, 11-2, 23-4 and 34-2 of the Occupational Safety and Health Act"],
 "Article 1 cites four provisions of the Act."),

(D,"第5條",2,"勞工健康保護規則-特約人員",
 "事業單位特約勞工健康服務人員辦理勞工健康服務時，應如何委託？",
 ["應依危害風險分類或特別危害健康作業，委託經認可之勞工健康服務專業機構指派人員","應依勞工人數之多寡，委託當地衛生主管機關指派符合資格之醫護人員到場提供服務","得逕行自行聘僱兼職之醫護人員辦理，無須委託經認可之勞工健康服務專業機構辦理","應委託醫院評鑑合格之醫療機構，由該機構指派任一名醫師擔任並免除其資格限制"],"a",
 "第5條：事業單位特約勞工健康服務人員辦理勞工健康服務，應依其事業之危害風險分類或特別危害健康作業，委託依勞工健康服務專業機構管理規則認可之機構，由該機構指派其符合第七條所定資格之人員為之。第6條並定僱用之健康服務人員不得兼任其他法令所定專責人員。",
 "How must an entity engage contracted occupational health service personnel?",
 ["By risk class or specially hazardous work, commissioning a recognized professional body to assign staff","By headcount, commissioning the local health authority to send qualified medical staff to the site","By simply hiring part-time medical staff directly, with no need to use a recognized professional body","By commissioning an accredited hospital, which may assign any physician regardless of qualifications"],
 "Article 5 requires a recognized professional body."),

(D,"第10條",2,"勞工健康保護規則-適用對象",
 "對其他受工作場所負責人指揮或監督從事勞動之人員，勞工健康服務應如何辦理？",
 ["應比照該事業單位勞工辦理；其不提供健康資料及書面同意者，仍應辦理第五款至第七款","應比照該事業單位勞工辦理；其不提供健康資料及書面同意者，即得完全免除辦理義務","無須比照該事業單位勞工辦理，該等人員健康服務由其原雇主或派遣事業單位負責之","應比照該事業單位勞工辦理；惟僅限於從事特別危害健康作業之人員始有適用之餘地"],"a",
 "第10條：事業單位對其他受工作場所負責人指揮或監督從事勞動之人員，應比照該事業單位勞工辦理第九條所定勞工健康服務事項；該等人員不提供個人健康資料及書面同意者，事業單位仍應辦理第九條第五款至第七款規定之事項。",
 "How must health services be provided to persons directed or supervised at the workplace?",
 ["Same as the entity's own workers; if they withhold data and consent, items 5 to 7 still apply","Same as the entity's own workers; if they withhold data and consent, the duty falls away entirely","No equal treatment is needed; their original employer or dispatching entity bears the whole duty","Same as the entity's own workers, but only for those engaged in specially hazardous work"],
 "Article 10, paragraphs 1 and 2."),

(D,"第18條",3,"勞工健康保護規則-健康檢查",
 "雇主對在職勞工有從事長期夜間工作之情形者，應實施何種健康檢查？該檢查紀錄保存年限為何？",
 ["應於當年度依附表十一實施長期夜間工作健康檢查，該檢查紀錄至少保存七年","應於當年度依附表十所定項目實施特殊健康檢查，該檢查紀錄至少保存十年","應於次年度依附表九所定項目實施一般健康檢查，該檢查紀錄至少保存三年","應每三年依附表十一實施長期夜間工作健康檢查，該檢查紀錄至少保存五年"],"a",
 "第18條：雇主對在職勞工有從事長期夜間工作之情形者，應於當年度依附表十一所定項目實施長期夜間工作健康檢查。第2條第4款定長期夜間工作指前一年度午後十時至翌晨六時工作三小時以上達當月工作日數二分之一且累計六個月以上，或該時段工作時數累計達七百小時以上。第20條定附表十一紀錄至少保存七年。",
 "What check applies to workers doing long-term night work, and how long are records kept?",
 ["A long-term night work health check under Table 11 that year, with records kept at least seven years","A special health check under Table 10 that year, with the records kept for at least ten years","A general health check under Table 9 the following year, with records kept at least three years","A long-term night work check under Table 11 every three years, with records kept five years"],
 "Articles 18 and 20."),

(D,"第23條",2,"勞工健康保護規則-特殊檢查",
 "特別危害健康作業場所之管理、監督人員及於該場所從事其他作業之人員，其健康檢查如何辦理？",
 ["有受健康危害之虞者適用第十九條特殊健康檢查之規定；但臨時性作業者不在此限","有受健康危害之虞者適用第十七條一般健康檢查之規定；但臨時性作業者不在此限","一律適用第十九條特殊健康檢查規定，臨時性作業者亦應每年實施特殊健康檢查者","均免適用特殊健康檢查之規定，僅需依第十七條規定定期實施一般健康檢查即可"],"a",
 "第23條：特別危害健康作業之管理、監督人員或相關人員及於各該場所從事其他作業之人員，有受健康危害之虞者，適用第十九條規定（每年或變更作業時依附表十實施特殊健康檢查）；但臨時性作業者不在此限。第2條第3款定臨時性作業指作業期間不超過三個月且一年內不再重複者。",
 "How are health checks handled for supervisors and others at specially hazardous workplaces?",
 ["Those at risk of health harm fall under Article 19 special checks; temporary work is excluded","Those at risk of health harm fall under Article 17 general checks; temporary work is excluded","All of them fall under Article 19 special checks, and temporary work is checked yearly too","None of them needs special checks; only the periodic general checks of Article 17 apply"],
 "Article 23 and its proviso."),

(D,"第29條",2,"勞工健康保護規則-施行日期",
 "關於勞工健康保護規則之施行日期，下列敘述何者正確？",
 ["原則自一百十五年七月一日施行，第五條等自一百十六年七月一日，第十七條等自一百十七年一月一日","原則自一百十五年一月一日施行，第五條等自一百十五年七月一日，第十七條等自一百十六年一月一日","原則自發布日起施行，第五條等自一百十六年七月一日施行，第十七條等自一百十八年一月一日施行","原則自一百十六年七月一日施行，第五條等自一百十七年一月一日，第十七條等自一百十八年七月施行"],"a",
 "第29條：本規則除第五條、第六條第二項至第四項、第十三條第三項自中華民國一百十六年七月一日施行，及第二條附表一、第十六條附表九、附表十、第十七條、第十八條、第二十條、第二十一條自一百十七年一月一日施行外，自一百十五年七月一日施行。",
 "Which statement about the effective dates of these Rules is correct?",
 ["Generally 1 July 2026; Article 5 and others 1 July 2027; Articles 17 and others 1 January 2028","Generally 1 January 2026; Article 5 and others 1 July 2026; Articles 17 and others 1 January 2027","Generally on promulgation; Article 5 and others 1 July 2027; Articles 17 and others 1 January 2029","Generally 1 July 2027; Article 5 and others 1 January 2028; Articles 17 and others July 2029"],
 "Article 29 sets staged effective dates."),

# ===== OSH-22 女性勞工母性健康保護實施辦法 =====
(E,"第1條",1,"母性健康保護-授權依據",
 "女性勞工母性健康保護實施辦法係依何規定訂定？",
 ["依職業安全衛生法第三十一條第三項規定訂定之","依職業安全衛生法第三十條第四項規定訂定之","依職業安全衛生法第二十九條第二項規定訂定","依性別平等工作法第十五條第五項規定訂定之"],"a",
 "第1條：本辦法依職業安全衛生法第三十一條第三項規定訂定。本法第31條第1項課雇主對妊娠中或分娩後未滿一年之女性勞工採取母性健康保護措施之義務；第2條並定保護期間為得知妊娠之日起至分娩後一年。",
 "Under which provision are these Regulations enacted?",
 ["Article 31, paragraph 3 of the Occupational Safety and Health Act","Article 30, paragraph 4 of the Occupational Safety and Health Act","Article 29, paragraph 2 of the Occupational Safety and Health Act","Article 15, paragraph 5 of the Act of Gender Equality in Employment"],
 "Article 1 cites Article 31-3 of the Act."),

(E,"第4條",3,"母性健康保護-鉛作業",
 "具有鉛作業之事業中，雇主使女性勞工從事何種工作應實施母性健康保護？其風險等級如何區分？",
 ["從事鉛及其化合物散布場所之工作者；依血中鉛濃度五及十μg/dl為界區分三級管理","從事鉛及其化合物散布場所之工作者；依血中鉛濃度十及二十μg/dl為界區分三級管理","僅妊娠中女性勞工從事鉛作業者；依作業場所空氣中鉛濃度是否超過容許標準區分","從事任何金屬粉塵作業之女性勞工；依尿中鉛濃度五及十μg/dl為界區分三級管理"],"a",
 "第4條：具有鉛作業之事業中，雇主使女性勞工從事鉛及其化合物散布場所之工作者，應實施母性健康保護。第10條並定風險分級：血中鉛濃度低於五μg/dl者為第一級管理，五以上未達十μg/dl者為第二級，十μg/dl以上者為第三級，但經醫師評估須調整者不在此限。",
 "Which lead work triggers maternal health protection, and how are risk levels divided?",
 ["Work where lead and its compounds are dispersed; three levels split at blood lead 5 and 10 µg/dl","Work where lead and its compounds are dispersed; three levels split at blood lead 10 and 20 µg/dl","Only pregnant workers in lead work; levels split by whether airborne lead exceeds the exposure limit","Any female worker in metal dust work; three levels split at urinary lead of 5 and 10 µg/dl"],
 "Articles 4 and 10."),

(E,"第5條",3,"母性健康保護-危害評估",
 "雇主使保護期間之勞工暴露於危險性或有害性工作之作業環境或型態時，應辦理何事項？何時須訂定母性健康保護計畫？",
 ["應實施危害評估；依勞工健康保護規則第三條或第四條應配置醫護人員者，另應訂定母性健康保護計畫","應實施作業環境監測；凡勞工人數在三十人以上之事業單位，均應訂定母性健康保護計畫並據以執行","應實施特殊健康檢查；經地方主管機關指定公告之事業單位，始應訂定母性健康保護計畫並執行","應實施危害評估；惟僅從事鉛及其化合物散布場所工作之事業單位，始須訂定母性健康保護計畫"],"a",
 "第5條：雇主使保護期間之勞工暴露於本法第三十條第一項或第二項之危險性或有害性工作之作業環境或型態，應實施危害評估；使其從事本法第三十條第一項第五款至第十四款及第二項第三款至第五款之工作，應實施母性健康保護。事業單位依勞工健康保護規則第三條或第四條應配置醫護人員者，雇主另應訂定母性健康保護計畫並據以執行。",
 "What must an employer do when a protected worker is exposed to dangerous or harmful work?",
 ["Carry out a hazard assessment; entities that must staff medical personnel must also draw up a protection plan","Carry out environmental monitoring; every entity with 30 or more workers must draw up a protection plan","Carry out special health checks; only entities designated by the local authority must draw up a plan","Carry out a hazard assessment; only entities with lead dispersal work need draw up a protection plan"],
 "Article 5, paragraphs 1 to 3."),

(E,"第7條",2,"母性健康保護-面談指導",
 "勞工於保護期間經醫護人員面談，發現健康狀況異常需進一步評估或追蹤檢查者，雇主應如何處理？",
 ["應轉介婦產科專科醫師或其他專科醫師，並請其註明臨床診斷與應處理及注意事項","應轉介職業醫學科專科醫師進行現場訪視，並由該醫師逕行決定調換工作之內容","應由事業單位護理人員自行追蹤三個月，其間無須轉介任何專科醫師進行評估者","應報請地方主管機關指定醫院複檢，並依複檢結果由主管機關命令雇主調整工作"],"a",
 "第7條：勞工於保護期間，雇主應使從事勞工健康服務醫護人員與其面談並提供健康指導及管理；面談發現健康狀況異常需進一步評估或追蹤檢查者，應轉介婦產科專科醫師或其他專科醫師，並請其註明臨床診斷與應處理及注意事項。勞工受面談時應依附表二填寫健康情形，並提供孕婦健康手冊予醫護人員。",
 "If an interview finds an abnormal health condition needing further assessment, what must be done?",
 ["Refer to an obstetrician or other specialist, who notes the diagnosis and matters to handle and watch","Refer to an occupational medicine specialist for a site visit, who alone decides the job reassignment","Have the in-house nurse follow up for three months, with no referral to any specialist during that time","Report to a hospital designated by the local authority, which then orders the employer to adjust work"],
 "Article 7, paragraph 2."),

(E,"第8條",2,"母性健康保護-重新辦理",
 "保護期間之勞工發生何種情形時，雇主應依規定重新辦理面談及風險分級等母性健康保護？",
 ["因工作條件改變、作業程序變更、健康異常或不適反應，經醫師診斷不適原有工作者","因請產假、育嬰留職停薪或調整工作地點，經事業單位主管認定確有必要重新辦理者","因勞工自行提出書面申請，或工會代表提出要求並經職業安全衛生委員會決議通過者","因作業環境監測結果超過容許暴露標準二分之一，並經地方主管機關通知辦理者等"],"a",
 "第8條：勞工於保護期間，因工作條件改變、作業程序變更、健康異常或有不適反應，經醫師診斷證明不適原有工作者，雇主應依第六條、第七條規定重新辦理（即重新辨識評估危害、區分風險等級並使醫護人員面談指導）。",
 "In what circumstances must the protection process be carried out again?",
 ["Changed work conditions or procedures, health abnormality or discomfort, with a doctor finding unfitness","Maternity leave, parental leave without pay or relocation, where the entity's supervisor thinks it needed","A written request by the worker, or a union request resolved by the safety and health committee","Monitoring results exceeding half the exposure limit, with notification from the local authority"],
 "Article 8."),

(E,"第12條",3,"母性健康保護-適性評估",
 "對保護期間之勞工為適性評估時，雇主應提供哪些資料予醫師？對醫師建議有疑慮時應如何處理？",
 ["提供評估結果、最近一次健康檢查、作業環境監測紀錄及危害暴露情形；有疑慮時請職業醫學科專科醫師現場訪視","提供評估結果、最近一次健康檢查、作業環境監測紀錄及危害暴露情形；有疑慮時逕報地方主管機關裁決處理","僅提供最近一次健康檢查結果即可；對醫師之建議有疑慮時，得不予採納並由雇主自行決定工作之安排","提供勞工個人病歷及家族病史等資料；有疑慮時應請婦產科專科醫師重新出具診斷證明書後辦理"],"a",
 "第12條：雇主應將第六條、第七條之評估結果與最近一次之健康檢查、作業環境監測紀錄及危害暴露情形等資料，提供予勞工健康服務之醫師或職業醫學科專科醫師，由醫師依附表三提供工作適性安排之建議；雇主應參照該建議採取必要之母性健康保護，對建議有疑慮時，應再請職業醫學科專科醫師現場訪視並提供綜合適性評估及建議。",
 "What data must be given to the physician for a fitness assessment, and what if there is doubt?",
 ["Assessment results, the latest health check, monitoring records and exposure data; doubts go to a site visit","Assessment results, the latest health check, monitoring records and exposure data; doubts go to the authority","Only the latest health check result; where there is doubt the employer may ignore it and decide the work","The worker's personal and family medical history; doubts require a fresh obstetrician's certificate first"],
 "Article 12, paragraphs 1 and 2."),

(E,"第13條",2,"母性健康保護-勞工意願",
 "雇主採取母性健康保護措施時，應遵守哪些原則？勞工對該措施有無配合義務？",
 ["應使醫師與勞工面談告知並聽取意見，尊重勞工意願並依勞基法性平法及游離輻射防護法辦理；勞工有配合義務","應使醫師與勞工面談告知並聽取意見，尊重勞工意願並依勞基法性平法及游離輻射防護法辦理；勞工無配合義務","得逕依醫師建議調整工作而不必與勞工面談，亦無須聽取單位主管之意見；惟勞工並有絕對之配合義務","應報請地方主管機關核定後始得調整工作，且僅需依勞動基準法辦理即可；勞工得拒絕配合不受處分"],"a",
 "第13條：雇主對於第十二條適性評估之建議，應使從事勞工健康服務之醫師與勞工面談，告知工作調整之建議，並聽取勞工及單位主管意見；所採取之母性健康保護應尊重勞工意願，並依勞動基準法、性別平等工作法及游離輻射防護法規定辦理；勞工對雇主所採取之母性健康管理措施有配合之義務。第14條並定相關文件及紀錄至少保存三年。",
 "What principles govern the protection measures, and must the worker cooperate?",
 ["Interview and inform the worker, hear both sides, respect her wishes and follow labor and radiation law; she must cooperate","Interview and inform the worker, hear both sides, respect her wishes and follow labor and radiation law; no duty to cooperate","Adjust the work straight from the doctor's advice without any interview or supervisor input; she must fully cooperate","Get the local authority's approval before adjusting work and follow only the Labor Standards Act; she may refuse"],
 "Article 13, paragraphs 1 to 3."),

(E,"第15條",2,"母性健康保護-哺乳期間",
 "女性勞工分娩滿一年後仍在哺乳者，關於母性健康保護之權利為何？",
 ["得請求雇主採取母性健康保護，不因法定保護期間屆滿而當然喪失其請求之權利","應由雇主主動實施母性健康保護，並強制延長保護期間至其分娩後滿二年為止","保護期間既已屆滿，雇主即不得再對其實施任何母性健康保護措施或工作調整","得請求地方主管機關命令雇主實施母性健康保護，雇主接獲命令後不得拒絕之"],"a",
 "第15條：女性勞工分娩滿一年後，仍在哺乳者，得請求雇主採取母性健康保護。第2條第2款所定母性健康保護期間為雇主得知女性勞工妊娠之日起至分娩後一年，第15條則賦予期間屆滿後仍在哺乳者之請求權。",
 "What right does a worker still breastfeeding more than a year after childbirth have?",
 ["She may request maternal health protection; the right does not lapse merely because the period ended","The employer must act on its own and the protection period is compulsorily extended to two years","The protection period has ended, so the employer may not take any protection measures at all","She may ask the local authority to order protection, and the employer may not refuse the order"],
 "Article 15 gives a right to request."),

(E,"第16條",2,"母性健康保護-施行日期",
 "關於女性勞工母性健康保護實施辦法之施行日期，下列敘述何者正確？",
 ["本辦法自一百零四年一月一日施行；一百十三年五月三十一日修正之第三條及第五條自一百十三年七月一日施行","本辦法自一百零三年七月三日施行；一百十三年五月三十一日修正之第三條及第五條自一百十四年一月一日施行","本辦法自一百零四年一月一日施行；一百零九年九月十六日修正之第三條及第五條自一百十年九月一日施行","本辦法自發布日起施行；其後所有修正條文一律自發布日施行，並無另定施行日期之特別規定者"],"a",
 "第16條：本辦法自中華民國一百零四年一月一日施行；修正條文除一百零九年九月十六日修正發布之第三條及第五條自一百十年三月一日施行、一百十三年五月三十一日修正發布之第三條及第五條自一百十三年七月一日施行外，自發布日施行。",
 "Which statement about the effective dates of these Regulations is correct?",
 ["Effective 1 January 2015; Articles 3 and 5 as amended 31 May 2024 take effect on 1 July 2024","Effective 3 July 2014; Articles 3 and 5 as amended 31 May 2024 take effect on 1 January 2025","Effective 1 January 2015; Articles 3 and 5 as amended 16 Sept 2020 take effect on 1 Sept 2021","Effective on promulgation; every later amendment also takes effect on promulgation with no exception"],
 "Article 16."),

# ===== OSH-20 妊娠與分娩後女性及未滿十八歲勞工禁止從事危險性或有害性工作認定標準 =====
(F,"第1條",2,"母性禁止工作標準-授權依據",
 "妊娠與分娩後女性及未滿十八歲勞工禁止從事危險性或有害性工作認定標準，係依何規定訂定？",
 ["依職業安全衛生法第二十九條第二項及第三十條第四項規定訂定之","依職業安全衛生法第三十條第一項及第三十一條第三項規定訂定之","依職業安全衛生法第二十九條第一項及第三十二條第二項規定訂定","依勞動基準法第四十九條及性別平等工作法第十五條規定所訂定"],"a",
 "第1條：本標準依職業安全衛生法第二十九條第二項及第三十條第四項規定訂定。第2條定本法第29條第1項（未滿十八歲者）禁止從事工作之認定標準如附表一，並明定未滿十五歲者不得從事該等工作；第3條、第4條則分別以附表二、附表三認定本法第30條第1項（妊娠中）及第2項（分娩後未滿一年）之禁止工作。",
 "Under which provisions is this Standard enacted?",
 ["Article 29, paragraph 2 and Article 30, paragraph 4 of the Occupational Safety and Health Act","Article 30, paragraph 1 and Article 31, paragraph 3 of the Occupational Safety and Health Act","Article 29, paragraph 1 and Article 32, paragraph 2 of the Occupational Safety and Health Act","Article 49 of the Labor Standards Act and Article 15 of the Gender Equality in Employment Act"],
 "Article 1 cites Articles 29-2 and 30-4 of the Act."),

]
