# -*- coding: utf-8 -*-
# 第 12 批（E1）：鋼鐵業集塵灰高溫冶煉設施戴奧辛管制及排放標準（ENV-149）、
#                 鋼鐵業燒結工場空氣污染物排放標準（ENV-150）、
#                 鋼鐵業燒結工場戴奧辛管制及排放標準（ENV-151）、
#                 餐飲業空氣污染防制設施管理辦法（ENV-152）、
#                 瀝青拌合業粒狀污染物排放標準（ENV-153）
# ※ 四個選項刻意寫成相近長度。
Q = [

# ── ENV-149 鋼鐵業集塵灰高溫冶煉設施戴奧辛管制及排放標準（9 條）───────────
("ENV-149","第1條",1,"集塵灰冶煉戴奧辛-法源",
 "鋼鐵業集塵灰高溫冶煉設施戴奧辛管制及排放標準係依據哪些條文訂定？",
 ["空氣污染防制法第二十條第二項、第二十二條第二項、第三項及第二十三條第二項",
  "空氣污染防制法第十四條第二項、第二十四條第三項及第二十八條第二項訂定",
  "廢棄物清理法第二十條第二項、第二十二條第三項及第二十三條第二項規定訂定",
  "毒性化學物質管理法第二十條第二項及空氣污染防制法第二十三條第一項訂定"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項、第二十二條第二項、第三項及第二十三條第二項規定訂定。第3條並規定本標準未規定事項適用其他相關法規之規定。第4條則界定其適用於集塵灰高溫冶煉設施之排氣，管制污染物項目為戴奧辛。",
 "Under which provisions was this dioxin control and emission standard for steel dust high-temperature smelting facilities adopted?",
 ["Article 20(2), Article 22(2) and (3), and Article 23(2) of the Air Pollution Control Act",
  "Article 14(2), Article 24(3), and Article 28(2) of the Air Pollution Control Act of Taiwan",
  "Article 20(2), Article 22(3), and Article 23(2) of the Waste Disposal Act of Taiwan",
  "Article 20(2) of the Toxic Chemical Substances Control Act and Article 23(1) of the Air Act"],
 "Article 1; see also Articles 3 and 4."),

("ENV-149","第2條",2,"集塵灰冶煉戴奧辛-定義",
 "既存高溫冶煉設施之認定基準日為何？其在何種情形下應以新設高溫冶煉設施論？",
 ["九十四年十月十二日前已完成建造或建造中等；更換或擴增設備致戴奧辛排放增量達年許可排放量百分之十",
  "九十四年十月十二日前已取得設置許可證或操作許可證者；更換或擴增設備致戴奧辛排放增量達年許可排放量百分之三十",
  "九十五年九月一日前已完成建造或建造中等；擴增設備致戴奧辛排放增量達年許可排放量百分之二十",
  "九十三年六月十六日前已完成工程發包簽約者；更換設備致粒狀污染物排放增量達百分之十者"],"a",
 "第2條第五款：既存高溫冶煉設施指中華民國九十四年十月十二日前已完成建造、建造中、完成工程招標程序或未經招標程序已完成工程發包簽約者；但更換或擴增設備致戴奧辛排放增量達操作許可證年許可排放量百分之十者，以新設高溫冶煉設施論。第四款則定義新設高溫冶煉設施為九十四年十月十二日起設立者。兩者適用之排放標準值不同，詳見第5條。",
 "What is the cut-off date for an existing high-temperature smelting facility, and when is it treated as a new facility?",
 ["Built or under construction before 12 Oct 2005; treated as new if replacement or expansion raises dioxin emissions by 10% of the permitted annual amount",
  "Holding a setup or operating permit before 12 Oct 2005; treated as new if replacement or expansion raises dioxin emissions by 30% of the permitted annual amount",
  "Built or under construction before 1 Sep 2006; treated as new if expansion raises dioxin emissions by 20% of the permitted annual amount",
  "Contract signed before 16 Jun 2004; treated as new if replacement raises particulate emissions by 10% of the permitted amount"],
 "Article 2, subparagraphs 4 and 5."),

("ENV-149","第3條",1,"集塵灰冶煉戴奧辛-適用",
 "本標準未規定之事項，應如何處理？",
 ["適用其他相關法規之規定",
  "由業者自行訂定內部規範",
  "一律報請中央主管機關核定",
  "視為不受任何規範之事項"],"a",
 "第3條：本標準未規定事項適用其他相關法規之規定。例如採樣測定方法、許可證管理等，即回歸空氣污染防制法及其相關子法辦理。第4條另界定本標準之適用對象與管制污染物項目。",
 "How are matters not provided for in this standard handled?",
 ["Other relevant laws and regulations apply",
  "Operators may set their own internal rules",
  "They must all be approved by the central authority",
  "They are treated as entirely unregulated matters"],
 "Article 3."),

("ENV-149","第4條",1,"集塵灰冶煉戴奧辛-範圍",
 "本標準之適用範圍及管制污染物項目為何？",
 ["適用於高溫冶煉鋼鐵業集塵灰設施之排氣，管制污染物項目為戴奧辛",
  "適用於高溫冶煉鋼鐵業集塵灰設施之廢水，管制污染物項目為重金屬",
  "適用於鋼鐵業燒結工場之排氣，管制污染物項目為硫氧化物與粒狀物",
  "適用於鋼鐵業電弧爐煉鋼設施之排氣，管制污染物項目為揮發性有機物"],"a",
 "第4條：本標準適用於高溫冶煉鋼鐵業集塵灰設施之排氣，管制污染物項目為戴奧辛。至於燒結工場之戴奧辛管制另有鋼鐵業燒結工場戴奧辛管制及排放標準；電弧爐則另有煉鋼業電弧爐戴奧辛管制及排放標準。",
 "What is the scope of this standard and the pollutant it controls?",
 ["Exhaust gas from high-temperature smelting facilities for steel dust; the controlled pollutant is dioxin",
  "Wastewater from high-temperature smelting facilities for steel dust; the controlled pollutants are heavy metals",
  "Exhaust gas from steel sintering plants; the controlled pollutants are sulfur oxides and particulates",
  "Exhaust gas from electric arc furnace steelmaking; the controlled pollutant is volatile organic compounds"],
 "Article 4."),

("ENV-149","第5條",3,"集塵灰冶煉戴奧辛-標準值",
 "既存高溫冶煉設施之戴奧辛排放標準值及其施行日期為何？",
 ["自九十四年十月十二日為 9 ng-TEQ/Nm3，自九十五年九月一日起加嚴為 1 ng-TEQ/Nm3",
  "自九十四年十月十二日為 5 ng-TEQ/Nm3，自九十五年九月一日起加嚴為 2 ng-TEQ/Nm3",
  "自九十四年十月十二日為 9 ng-TEQ/Nm3，自九十七年一月一日起加嚴為 0.4 ng-TEQ/Nm3",
  "自九十五年九月一日為 1 ng-TEQ/Nm3，自九十七年一月一日起加嚴為 0.1 ng-TEQ/Nm3"],"a",
 "第5條附表：既存高溫冶煉設施自中華民國九十四年十月十二日起適用 9 ng-TEQ/Nm3，自九十五年九月一日起適用 1 ng-TEQ/Nm3；新設高溫冶煉設施自九十四年十月十二日起即適用 0.4 ng-TEQ/Nm3。第6條規定濃度以毒性當量（TEQ）表示。",
 "What are the dioxin emission limits for existing high-temperature smelting facilities and their effective dates?",
 ["9 ng-TEQ/Nm3 from 12 Oct 2005, tightened to 1 ng-TEQ/Nm3 from 1 Sep 2006",
  "5 ng-TEQ/Nm3 from 12 Oct 2005, tightened to 2 ng-TEQ/Nm3 from 1 Sep 2006",
  "9 ng-TEQ/Nm3 from 12 Oct 2005, tightened to 0.4 ng-TEQ/Nm3 from 1 Jan 2008",
  "1 ng-TEQ/Nm3 from 1 Sep 2006, tightened to 0.1 ng-TEQ/Nm3 from 1 Jan 2008"],
 "Article 5, table."),

("ENV-149","第5條",2,"集塵灰冶煉戴奧辛-新設標準",
 "新設高溫冶煉設施之戴奧辛排放標準值及施行日期為何？",
 ["排放標準值 0.4 ng-TEQ/Nm3，自中華民國九十四年十月十二日施行",
  "排放標準值 1.0 ng-TEQ/Nm3，自中華民國九十五年九月一日施行",
  "排放標準值 0.1 ng-TEQ/Nm3，自中華民國九十四年十月十二日施行",
  "排放標準值 0.5 ng-TEQ/Nm3，自中華民國九十七年一月一日施行"],"a",
 "第5條附表：新設高溫冶煉設施排放標準值為 0.4 ng-TEQ/Nm3，施行日期為中華民國九十四年十月十二日，較既存設施最終值 1 ng-TEQ/Nm3 更嚴格。第2條第四款定義新設高溫冶煉設施即九十四年十月十二日起設立者。",
 "What is the dioxin limit for a new high-temperature smelting facility and its effective date?",
 ["A limit of 0.4 ng-TEQ/Nm3, effective from 12 October 2005",
  "A limit of 1.0 ng-TEQ/Nm3, effective from 1 September 2006",
  "A limit of 0.1 ng-TEQ/Nm3, effective from 12 October 2005",
  "A limit of 0.5 ng-TEQ/Nm3, effective from 1 January 2008"],
 "Article 5, table."),

("ENV-149","第6條",3,"集塵灰冶煉戴奧辛-計算基準",
 "集塵灰高溫冶煉設施煙道排氣戴奧辛濃度之計算基準及採樣規定為何？",
 ["以凱氏溫度二七三度、一大氣壓下未經稀釋之乾燥排氣體積為基準；採樣測定應達三次以上取算術平均值，每次採樣間隔一小時以上",
  "以凱氏溫度二九八度、一大氣壓下已經稀釋之濕潤排氣體積為基準；採樣測定應達二次以上取算術平均值，每次採樣間隔二小時以上",
  "以凱氏溫度二七三度、二大氣壓下未經稀釋之濕潤排氣體積為基準；採樣測定應達三次以上取幾何平均值，每次採樣間隔三十分鐘以上",
  "以凱氏溫度二七三度、一大氣壓下未經稀釋之乾燥排氣體積為基準；採樣測定僅需一次即可，並取單次最低值申報"],"a",
 "第6條：濃度計算以凱氏溫度二七三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，標準值濃度以毒性當量（TEQ）表示，由測得附表各項戴奧辛濃度乘以其國際毒性當量因子（I-TEF）之總和計算；採樣及測定應達三次以上並取算術平均值，每次採樣時間應間隔一小時以上。第2條第二、三款則定義 I-TEF 與 TEQ。",
 "What is the calculation basis for stack dioxin concentration and the sampling requirement?",
 ["Undiluted dry exhaust volume at 273 K and 1 atm; at least three samplings averaged arithmetically, each at least one hour apart",
  "Diluted wet exhaust volume at 298 K and 1 atm; at least two samplings averaged arithmetically, each at least two hours apart",
  "Undiluted wet exhaust volume at 273 K and 2 atm; at least three samplings averaged geometrically, each at least thirty minutes apart",
  "Undiluted dry exhaust volume at 273 K and 1 atm; only a single sampling is needed and the lowest value is reported"],
 "Article 6."),

("ENV-149","第7條",3,"集塵灰冶煉戴奧辛-操作管制",
 "集塵灰高溫冶煉設施之集塵設備入口廢氣溫度應如何管制？未能達成時如何處理？",
 ["應在攝氏二○○度以下並具備即時顯示之廢氣溫度監測設施；未能低於者得經當地主管機關認可後以其他操作條件替代",
  "應在攝氏三○○度以下並具備每月抄錄之廢氣溫度紀錄表；未能低於者得逕行停止監測並於年度報告中敘明原因",
  "應在攝氏二○○度以下並具備即時顯示之廢氣壓力監測設施；未能低於者得由業者自行選定其他操作條件替代",
  "應在攝氏一五○度以下並具備即時顯示之廢氣溫度監測設施；未能低於者應立即停止操作並拆除該集塵設備"],"a",
 "第7條第一項：集塵設備入口廢氣溫度應在攝氏二○○度以下，並應具備即時顯示之廢氣溫度監測設施；未能低於攝氏二○○度者，得經當地主管機關認可後，以其他操作條件替代。第二項並要求戴奧辛污染防制設備維持最近一次採樣分析符合第5條標準下之操作條件，操作條件變更者應重新採樣分析。",
 "How is the inlet gas temperature of the dust collector controlled, and what if it cannot be met?",
 ["It must be below 200 degrees Celsius with real-time temperature monitoring; if not, other operating conditions may substitute with local authority approval",
  "It must be below 300 degrees Celsius with monthly recorded temperature logs; if not, monitoring may simply stop with reasons noted in the annual report",
  "It must be below 200 degrees Celsius with real-time exhaust pressure monitoring; if not, the operator may choose substitute operating conditions itself",
  "It must be below 150 degrees Celsius with real-time temperature monitoring; if not, operation must stop at once and the dust collector be dismantled"],
 "Article 7."),

("ENV-149","第8條",3,"集塵灰冶煉戴奧辛-檢測申報",
 "集塵灰高溫冶煉設施排氣中戴奧辛之定期檢測頻率與申報期限規定為何？",
 ["每年定期檢測二次，二次間隔不得少於三個月或超過九個月；檢測七日前送檢測計畫書，檢測後六十日內申報報告書",
  "每年定期檢測二次，二次間隔不得少於一個月或超過六個月；檢測十日前送檢測計畫書，檢測後三十日內申報報告書",
  "每年定期檢測四次，二次間隔不得少於三個月或超過九個月；檢測七日前送檢測計畫書，檢測後九十日內申報報告書",
  "每年定期檢測一次，並於檢測後三個月內申報；檢測十四日前送檢測計畫書至中央主管機關備查後始得執行"],"a",
 "第8條第一款：每年定期檢測二次，分別於一月至六月及七月至十二月各執行一次，二次間隔不得少於三個月或超過九個月；定期檢測七日前應檢送檢測計畫書至直轄市、縣（市）主管機關，檢測結果應於檢測後六十日內申報檢測報告書。第二款規定連續二次定期檢測均符合第5條標準者，得申請調整為每年一次，但違反第5條規定者應回復每年二次。",
 "What is the periodic dioxin testing frequency and reporting deadline for these facilities?",
 ["Twice a year, with the two tests at least three and at most nine months apart; a test plan seven days before and a report within sixty days after",
  "Twice a year, with the two tests at least one and at most six months apart; a test plan ten days before and a report within thirty days after",
  "Four times a year, with tests at least three and at most nine months apart; a test plan seven days before and a report within ninety days after",
  "Once a year, reported within three months of testing; a test plan must be filed with the central authority fourteen days beforehand"],
 "Article 8, subparagraph 1."),

("ENV-149","第9條",1,"集塵灰冶煉戴奧辛-施行",
 "本標準之施行日期如何規定？",
 ["除另定施行日期者外，自發布日施行",
  "一律自發布後六個月起開始施行",
  "應由中央主管機關另行公告施行",
  "自發布日後之次年一月一日施行"],"a",
 "第9條：本標準除另定施行日期者外，自發布日施行。所稱另定施行日期者，即指第5條附表中既存設施 1 ng-TEQ/Nm3 之九十五年九月一日等分階段加嚴日期。",
 "How does this standard specify its effective date?",
 ["It takes effect on promulgation unless otherwise specified",
  "It uniformly takes effect six months after promulgation",
  "It takes effect only upon separate central announcement",
  "It takes effect on 1 January of the following year"],
 "Article 9."),

# ── ENV-150 鋼鐵業燒結工場空氣污染物排放標準（7 條）───────────────────
("ENV-150","第1條",1,"燒結工場排放標準-法源",
 "鋼鐵業燒結工場空氣污染物排放標準之訂定法源為何？",
 ["依空氣污染防制法第二十條第二項規定訂定",
  "依空氣污染防制法第二十三條第二項規定訂定",
  "依空氣污染防制法第十四條第三項規定訂定",
  "依固定污染源空氣污染物排放標準第三條訂定"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項規定訂定。第2條並規定本標準用詞未規定者，依固定污染源空氣污染物排放標準之規定。第3條界定適用對象為鋼鐵業燒結工場。",
 "What is the legal basis of the emission standard for steel sintering plants?",
 ["Adopted under Article 20, Paragraph 2 of the Air Pollution Control Act",
  "Adopted under Article 23, Paragraph 2 of the Air Pollution Control Act",
  "Adopted under Article 14, Paragraph 3 of the Air Pollution Control Act",
  "Adopted under Article 3 of the Stationary Source Emission Standards"],
 "Article 1."),

("ENV-150","第2條",2,"燒結工場排放標準-定義",
 "本標準所稱起機運作期及防制設備維修期，其定義為何？",
 ["起機運作期指燒結機停止運轉後重新啟動製程設備之三小時內；維修期指硫氧化物或氮氧化物防制設備檢修更換而停止操作之期間",
  "起機運作期指燒結機停止運轉後重新啟動製程設備之八小時內；維修期指粒狀污染物防制設備檢修更換而停止操作之期間",
  "起機運作期指燒結機每日開始生產後之三小時內；維修期指全廠因歲修而停止所有燒結機生產作業之全部期間",
  "起機運作期指燒結機停止運轉前之三小時內；維修期指硫氧化物或氮氧化物監測設施校正或維護而暫停之期間"],"a",
 "第2條第三款：起機運作期指燒結工場燒結機停止運轉後，重新啟動製程設備之三小時內操作期間。第四款：防制設備維修期指既存燒結工場燒結機裝設之硫氧化物或氮氧化物空氣污染防制設備，進行檢修或設備更換過程而停止操作該污染防制設備之期間。此二期間之排放標準值另依第4條附表適用，並須依第5條事先報備。",
 "How are the start-up period and the control equipment maintenance period defined?",
 ["Start-up means the three hours after restarting process equipment following a sinter machine shutdown; maintenance means the period the SOx or NOx control equipment is out of service for repair or replacement",
  "Start-up means the eight hours after restarting process equipment following a sinter machine shutdown; maintenance means the period the particulate control equipment is out of service for repair or replacement",
  "Start-up means the first three hours of daily production of the sinter machine; maintenance means the entire period all sinter machines stop for a plant-wide overhaul",
  "Start-up means the three hours before a sinter machine shuts down; maintenance means the period SOx or NOx monitoring equipment is paused for calibration or servicing"],
 "Article 2, subparagraphs 3 and 4."),

("ENV-150","第3條",1,"燒結工場排放標準-適用",
 "本標準之適用對象為何？",
 ["鋼鐵業中藉由高溫將鐵礦砂、焦炭與其他礦石混合燒結成塊之燒結工場",
  "鋼鐵業中以電弧爐熔煉廢鋼並鑄造成型之煉鋼及鑄造電爐工場",
  "鋼鐵業中將集塵灰以高溫冶煉回收金屬氧化物之高溫冶煉設施",
  "鋼鐵業中以焦炭爐乾餾煤炭製造焦炭並回收副產品之焦化工場"],"a",
 "第3條：本標準適用對象為鋼鐵業中藉由高溫將鐵礦砂、焦炭與其他礦石混合燒結成塊之燒結工場。其戴奧辛管制另依鋼鐵業燒結工場戴奧辛管制及排放標準辦理；電弧爐與集塵灰冶煉設施則各有專屬標準。",
 "To what does this standard apply?",
 ["Sintering plants in the steel industry that fuse iron ore, coke and other minerals into lumps at high temperature",
  "Electric arc furnace steelmaking and casting plants in the steel industry that melt scrap steel and cast it into shape",
  "High-temperature smelting facilities in the steel industry that recover metal oxides from collected furnace dust",
  "Coking plants in the steel industry that carbonize coal in coke ovens to make coke and recover by-products"],
 "Article 3."),

("ENV-150","第4條",1,"燒結工場排放標準-規定值",
 "燒結工場空氣污染物之排放標準規定值以何種方式規定？",
 ["於本標準第四條所定之附表中規定",
  "由中央主管機關逐案以公告方式核定",
  "依各縣市主管機關自訂之標準辦理",
  "準用移動污染源排放標準之規定值"],"a",
 "第4條：燒結工場空氣污染物排放標準規定值如附表。附表中並就既存燒結工場之起機運作期與防制設備維修期另訂硫氧化物、氮氧化物標準值，其適用須依第5條規定事先報備。",
 "How are the emission limits for sintering plants prescribed?",
 ["They are set out in the table attached to Article 4",
  "They are approved case by case by the central authority",
  "They follow standards set by each local authority",
  "They apply the mobile source emission standards"],
 "Article 4 and its attached table."),

("ENV-150","第5條",3,"燒結工場排放標準-報備",
 "既存燒結工場欲適用起機運作期及防制設備維修期之硫氧化物、氮氧化物標準值，應如何辦理？",
 ["應於每次起機運作或防制設備維修前二十四小時內，向直轄市、縣（市）主管機關報備",
  "應於每次起機運作或防制設備維修後二十四小時內，向直轄市、縣（市）主管機關報備",
  "應於每次起機運作或防制設備維修前七日內，向中央主管機關提出書面申請並取得核可",
  "應於每年一月底前將全年預定之起機及維修時程一次報請中央主管機關備查後實施"],"a",
 "第5條第一項：既存燒結工場於燒結機每次起機運作或防制設備維修前二十四小時內，應向直轄市、縣（市）主管機關報備，始得適用第4條附表所定起機運作期及防制設備維修期之硫氧化物及氮氧化物排放標準值。第二項並就維修期天數設有上限。",
 "How must an existing sintering plant proceed to use the start-up and maintenance period SOx/NOx limits?",
 ["It must report to the municipal or county authority within 24 hours before each start-up or equipment maintenance",
  "It must report to the municipal or county authority within 24 hours after each start-up or equipment maintenance",
  "It must apply in writing to the central authority seven days before each start-up or maintenance and obtain approval",
  "It must file the whole year's planned start-up and maintenance schedule with the central authority by the end of January"],
 "Article 5, Paragraph 1."),

("ENV-150","第5條",3,"燒結工場排放標準-維修天數",
 "各燒結機之防制設備維修期每年天數上限為何？",
 ["硫氧化物防制設備每年不得超過三十五日，氮氧化物防制設備每年不得超過二十一日",
  "硫氧化物防制設備每年不得超過二十一日，氮氧化物防制設備每年不得超過三十五日",
  "硫氧化物防制設備每年不得超過三十日，氮氧化物防制設備每年不得超過三十日整",
  "硫氧化物防制設備每年不得超過六十日，氮氧化物防制設備每年不得超過四十五日"],"a",
 "第5條第二項：各燒結機之硫氧化物防制設備維修期每年不得超過三十五日，氮氧化物防制設備維修期每年不得超過二十一日。逾此天數即不得再適用第4條附表之維修期放寬標準值，須符合一般排放標準。",
 "What is the annual cap on control equipment maintenance days for each sinter machine?",
 ["Not more than 35 days a year for SOx control equipment and 21 days a year for NOx control equipment",
  "Not more than 21 days a year for SOx control equipment and 35 days a year for NOx control equipment",
  "Not more than 30 days a year for SOx control equipment and 30 days a year for NOx control equipment",
  "Not more than 60 days a year for SOx control equipment and 45 days a year for NOx control equipment"],
 "Article 5, Paragraph 2."),

("ENV-150","第6條",3,"燒結工場排放標準-含氧量校正",
 "本標準污染物濃度之計算基準及含氧量參考基準為何？",
 ["以凱氏溫度二七三度、一大氣壓下未經稀釋之乾燥排氣為基準，含氧量參考基準為百分之十五，實測氧氣大於二十者以二十計",
  "以凱氏溫度二九八度、一大氣壓下未經稀釋之濕潤排氣為基準，含氧量參考基準為百分之十五，實測氧氣大於十八者以十八計",
  "以凱氏溫度二七三度、一大氣壓下未經稀釋之乾燥排氣為基準，含氧量參考基準為百分之六，實測氧氣大於二十一者以二十一計",
  "以凱氏溫度二七三度、二大氣壓下已經稀釋之乾燥排氣為基準，含氧量參考基準為百分之十六，實測氧氣大於二十者以二十計"],"a",
 "第6條：本標準各種污染物之濃度計算均以凱氏溫度二七三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，並以排氣含氧量百分之十五為參考基準，校正式為 C＝(21－15)/(21－Os)×Cs；排氣中氧氣百分率大於二十者，以百分之二十計。",
 "What is the calculation basis and the reference oxygen content under this standard?",
 ["Undiluted dry exhaust at 273 K and 1 atm, with a 15% reference oxygen content; measured oxygen above 20% counts as 20%",
  "Undiluted wet exhaust at 298 K and 1 atm, with a 15% reference oxygen content; measured oxygen above 18% counts as 18%",
  "Undiluted dry exhaust at 273 K and 1 atm, with a 6% reference oxygen content; measured oxygen above 21% counts as 21%",
  "Diluted dry exhaust at 273 K and 2 atm, with a 16% reference oxygen content; measured oxygen above 20% counts as 20%"],
 "Article 6."),

("ENV-150","第7條",1,"燒結工場排放標準-施行",
 "本標準之施行日期如何規定？",
 ["除另定施行日期者外，自發布日施行",
  "統一自發布後一年之次日開始施行",
  "應報請行政院核定後始得公布施行",
  "自發布日後第三個月之首日施行"],"a",
 "第7條：本標準除另定施行日期者外，自發布日施行。本標準最近一次修正日期為民國一百零一年六月十四日，此日期亦為第2條新設燒結工場之認定基準日。",
 "How does this standard specify its effective date?",
 ["It takes effect on promulgation unless otherwise specified",
  "It uniformly takes effect the day after one year of promulgation",
  "It may be promulgated only after Executive Yuan approval",
  "It takes effect on the first day of the third month after promulgation"],
 "Article 7."),

# ── ENV-151 鋼鐵業燒結工場戴奧辛管制及排放標準（9 條）───────────────
("ENV-151","第1條",1,"燒結戴奧辛-法源",
 "鋼鐵業燒結工場戴奧辛管制及排放標準之訂定法源為何？",
 ["空氣污染防制法第二十條第二項、第二十二條第二項、第三項及第二十三條第二項",
  "空氣污染防制法第二十條第一項、第二十二條第一項及第二十三條第一項規定",
  "空氣污染防制法第二十四條第二項、第二十八條第三項及第三十條第二項規定",
  "廢棄物清理法第二十條第二項及空氣污染防制法第二十三條第二項規定訂定"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項、第二十二條第二項、第三項及第二十三條第二項規定訂定。同一法源亦為鋼鐵業集塵灰高溫冶煉設施戴奧辛管制及排放標準之依據，兩者分別管制不同製程設施。",
 "What is the legal basis of the dioxin control and emission standard for steel sintering plants?",
 ["Article 20(2), Article 22(2) and (3), and Article 23(2) of the Air Pollution Control Act",
  "Article 20(1), Article 22(1) and Article 23(1) of the Air Pollution Control Act of Taiwan",
  "Article 24(2), Article 28(3) and Article 30(2) of the Air Pollution Control Act of Taiwan",
  "Article 20(2) of the Waste Disposal Act and Article 23(2) of the Air Pollution Control Act"],
 "Article 1."),

("ENV-151","第2條",2,"燒結戴奧辛-定義",
 "本標準所稱新設燒結工場與既存燒結工場如何區分？既存工場何時視為新設？",
 ["以本標準發布日為界；既存工場因設備更換或擴增致戴奧辛排放量增加達年許可排放量百分之十以上者以新設論",
  "以本標準發布日為界；既存工場因設備更換或擴增致戴奧辛排放量增加達年許可排放量百分之三十以上者以新設論",
  "以民國一百零一年六月十四日為界；既存工場因擴增致戴奧辛排放量增加達年許可排放量百分之十以上者以新設論",
  "以取得操作許可證之日為界；既存工場因產能提高致粒狀污染物排放量增加達百分之十以上者以新設燒結工場論"],"a",
 "第2條第四、五款：新設燒結工場指本標準發布日起設立者；既存燒結工場指發布日前已完成建造、建造中、完成工程招標程序或已完成工程發包簽約者，但因設備更換或擴增致戴奧辛排放量增加達操作許可證記載年許可排放量百分之十以上者，以新設燒結工場論。二者標準值差異見第5條。",
 "How are new and existing sintering plants distinguished, and when is an existing plant treated as new?",
 ["By the promulgation date of this standard; an existing plant counts as new if equipment change or expansion raises dioxin emissions by 10% or more of the permitted annual amount",
  "By the promulgation date of this standard; an existing plant counts as new if equipment change or expansion raises dioxin emissions by 30% or more of the permitted annual amount",
  "By 14 June 2012; an existing plant counts as new if expansion raises dioxin emissions by 10% or more of the permitted annual amount",
  "By the date the operating permit is issued; an existing plant counts as new if higher output raises particulate emissions by 10% or more"],
 "Article 2, subparagraphs 4 and 5."),

("ENV-151","第3條",1,"燒結戴奧辛-適用",
 "本標準未規定之事項應如何適用法規？",
 ["適用其他相關法規之規定",
  "由主管機關個案裁量認定",
  "適用國際公約之相關規定",
  "由業者於許可證中自行載明"],"a",
 "第3條：本標準未規定事項適用其他相關法規之規定。例如檢測方法、許可證申請及罰則等，均回歸空氣污染防制法及其相關子法。第4條另界定適用範圍與管制污染物。",
 "How are matters not covered by this standard dealt with?",
 ["Other relevant laws and regulations apply",
  "The competent authority decides case by case",
  "The relevant international conventions apply",
  "The operator states them in its own permit"],
 "Article 3."),

("ENV-151","第4條",1,"燒結戴奧辛-範圍",
 "本標準適用之排氣來源及管制污染物項目為何？",
 ["鋼鐵業中將鐵礦砂、焦炭與其他礦石混合燒結成塊之工場燒結機冶煉過程排氣，管制污染物為戴奧辛",
  "鋼鐵業中將鐵礦砂、焦炭與其他礦石混合燒結成塊之工場燒結機冶煉過程排氣，管制污染物為重金屬",
  "鋼鐵業中以電弧爐熔煉廢鋼之煉鋼設施冶煉過程排氣，管制污染物為戴奧辛及粒狀污染物二項",
  "鋼鐵業中將集塵灰以高溫冶煉回收金屬之設施排氣，管制污染物為戴奧辛及揮發性有機物二項"],"a",
 "第4條：本標準適用於鋼鐵業中藉由高溫將鐵礦砂、焦炭與其他礦石混合燒結成塊之工場燒結機冶煉過程之排氣，管制污染物項目為戴奧辛。同一燒結工場之粒狀物、硫氧化物、氮氧化物則依鋼鐵業燒結工場空氣污染物排放標準管制。",
 "Which exhaust and which pollutant does this standard cover?",
 ["Exhaust from the sinter machine smelting process fusing iron ore, coke and other minerals; the pollutant controlled is dioxin",
  "Exhaust from the sinter machine smelting process fusing iron ore, coke and other minerals; the pollutants controlled are heavy metals",
  "Exhaust from electric arc furnace steelmaking melting scrap steel; the pollutants controlled are dioxin and particulates",
  "Exhaust from facilities smelting steel dust to recover metals; the pollutants controlled are dioxin and volatile organics"],
 "Article 4."),

("ENV-151","第5條",3,"燒結戴奧辛-標準值",
 "燒結工場戴奧辛排放標準值及其施行日期為何？",
 ["既存工場九十五年一月一日起 2.0、九十七年一月一日起 1.0 ng-TEQ/Nm3；新設工場自發布日起 0.5 ng-TEQ/Nm3",
  "既存工場九十五年一月一日起 5.0、九十七年一月一日起 2.0 ng-TEQ/Nm3；新設工場自發布日起 1.0 ng-TEQ/Nm3",
  "既存工場九十五年九月一日起 2.0、九十七年一月一日起 0.5 ng-TEQ/Nm3；新設工場自發布日起 0.1 ng-TEQ/Nm3",
  "既存工場九十四年一月一日起 1.0、九十六年一月一日起 0.5 ng-TEQ/Nm3；新設工場自發布日起 0.4 ng-TEQ/Nm3"],"a",
 "第5條第一項表：既存燒結工場自九十五年一月一日起適用 2.0 ng-TEQ/Nm3、自九十七年一月一日起適用 1.0 ng-TEQ/Nm3；新設燒結工場自發布日起適用 0.5 ng-TEQ/Nm3。第二項：標準值濃度以毒性當量（TEQ）表示，由測得附表各項戴奧辛濃度乘以國際毒性當量因子（I-TEF）總和計算，採樣測定應達三次以上取算術平均值，每次採樣間隔一小時以上。",
 "What are the dioxin emission limits for sintering plants and their effective dates?",
 ["Existing plants 2.0 from 1 Jan 2006 and 1.0 ng-TEQ/Nm3 from 1 Jan 2008; new plants 0.5 ng-TEQ/Nm3 from promulgation",
  "Existing plants 5.0 from 1 Jan 2006 and 2.0 ng-TEQ/Nm3 from 1 Jan 2008; new plants 1.0 ng-TEQ/Nm3 from promulgation",
  "Existing plants 2.0 from 1 Sep 2006 and 0.5 ng-TEQ/Nm3 from 1 Jan 2008; new plants 0.1 ng-TEQ/Nm3 from promulgation",
  "Existing plants 1.0 from 1 Jan 2005 and 0.5 ng-TEQ/Nm3 from 1 Jan 2007; new plants 0.4 ng-TEQ/Nm3 from promulgation"],
 "Article 5."),

("ENV-151","第6條",3,"燒結戴奧辛-校正公式",
 "燒結工場排氣煙道戴奧辛濃度之含氧量校正基準為何？實測含氧量過高時如何處理？",
 ["以排氣含氧量百分之十五為參考基準，依 C＝(21－15)/(21－Os)×Cs 校正；Os 大於百分之二十者以百分之二十計算",
  "以排氣含氧量百分之六為參考基準，依 C＝(21－6)/(21－Os)×Cs 校正；Os 大於百分之二十者以百分之二十一計算",
  "以排氣含氧量百分之十五為參考基準，依 C＝(21－Os)/(21－15)×Cs 校正；Os 大於百分之十五者以百分之十五計算",
  "以排氣含氧量百分之十六為參考基準，依 C＝(21－16)/(21－Os)×Cs 校正；Os 大於百分之十八者以百分之十八計算"],"a",
 "第6條：燒結工場排氣煙道中戴奧辛濃度以凱氏溫度二七三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，並以排氣含氧量十五％為參考基準，校正公式 C＝(21－15)/(21－Os)×Cs；Os 為排氣中含氧量實測值，其大於二○％者，以二○％計算。此與第5條之標準值搭配適用。",
 "What is the oxygen correction basis for stack dioxin concentration, and what if measured oxygen is too high?",
 ["A 15% reference oxygen content, corrected as C = (21-15)/(21-Os) x Cs; an Os above 20% is counted as 20%",
  "A 6% reference oxygen content, corrected as C = (21-6)/(21-Os) x Cs; an Os above 20% is counted as 21%",
  "A 15% reference oxygen content, corrected as C = (21-Os)/(21-15) x Cs; an Os above 15% is counted as 15%",
  "A 16% reference oxygen content, corrected as C = (21-16)/(21-Os) x Cs; an Os above 18% is counted as 18%"],
 "Article 6."),

("ENV-151","第7條",2,"燒結戴奧辛-操作條件",
 "燒結工場冶煉過程集塵設備入口廢氣溫度及防制設備操作條件應如何維持？",
 ["入口廢氣溫度應在攝氏二○○度以下並具即時顯示監測設施；防制設備應維持最近一次採樣分析符合排放標準期間之操作條件",
  "入口廢氣溫度應在攝氏三○○度以下並具每日人工抄錄紀錄；防制設備應維持設置許可證所載之原始設計操作條件不得變動",
  "入口廢氣溫度應在攝氏二○○度以下並具即時顯示監測設施；防制設備操作條件得由業者視生產需要隨時調整無須再檢測",
  "入口廢氣溫度應在攝氏一五○度以下並具即時顯示監測設施；防制設備應維持最近一次年度稽查檢測當日之進料條件"],"a",
 "第7條第一項：燒結工場冶煉過程中集塵設備入口廢氣溫度應在攝氏二○○度以下，並應具備即時顯示之廢氣溫度監測設施。第二項：正常運作時之戴奧辛污染防制設備應維持最近一次採樣分析符合戴奧辛排放標準期間之操作條件，操作條件有變更時，應重新進行戴奧辛採樣分析以調整其操作條件。",
 "How must the dust collector inlet temperature and control equipment operating conditions be maintained?",
 ["Inlet gas below 200 degrees Celsius with real-time monitoring; control equipment must keep the operating conditions of the last compliant sampling analysis",
  "Inlet gas below 300 degrees Celsius with daily manual logging; control equipment must keep the original design conditions in the setup permit unchanged",
  "Inlet gas below 200 degrees Celsius with real-time monitoring; operating conditions may be adjusted freely as production requires without re-testing",
  "Inlet gas below 150 degrees Celsius with real-time monitoring; control equipment must keep the feed conditions of the last annual inspection day"],
 "Article 7."),

("ENV-151","第8條",3,"燒結戴奧辛-檢測頻率調整",
 "燒結工場在何種條件下得申請調整戴奧辛檢測頻率為每年一次？其後如違規應如何處理？",
 ["連續二次定期檢測濃度均符合第五條標準值者得檢具文件申請調整；嗣後稽查或定期檢測違反者應回復每年二次之頻率",
  "連續一次定期檢測濃度符合第五條標準值者即得逕行調整；嗣後稽查或定期檢測違反者仍得維持每年一次之檢測頻率",
  "連續三次定期檢測濃度均符合第五條標準值者得檢具文件申請調整；嗣後違反者應改為每半年檢測一次並加倍申報",
  "連續二次定期檢測濃度均低於標準值一半者得逕行免除檢測；嗣後違反者應由主管機關另行公告其檢測頻率規定"],"a",
 "第8條第二款：連續二次定期檢測排氣中戴奧辛濃度均符合第5條排放標準值者，得檢具相關證明文件向直轄市、縣（市）主管機關申請調整檢測頻率為每年一次；但經主管機關稽查檢測或已調整為每年一次者，其檢測結果違反第5條規定時，應依第一款所定每年二次之頻率辦理。第一款並定有間隔三至九個月、檢測前七日送計畫書、檢測後六十日內申報之規定。",
 "On what condition may a sintering plant reduce dioxin testing to once a year, and what if it later violates?",
 ["Two consecutive periodic tests meeting the Article 5 limits allow an application to reduce; a later violation restores the twice-a-year frequency",
  "One periodic test meeting the Article 5 limits allows an immediate reduction; a later violation still permits the once-a-year frequency to continue",
  "Three consecutive periodic tests meeting the Article 5 limits allow an application to reduce; a later violation requires semi-annual testing and double reporting",
  "Two consecutive tests below half the limit allow testing to be waived entirely; a later violation lets the authority announce a new frequency"],
 "Article 8, subparagraph 2."),

("ENV-151","第9條",1,"燒結戴奧辛-施行",
 "本標準之施行日期如何規定？",
 ["除已另訂施行日期者外，自發布日施行",
  "一律自發布日起滿一年之翌日施行",
  "須俟中央主管機關另定日期後施行",
  "自發布當年度之十二月三十一日施行"],"a",
 "第9條：本標準除已另訂施行日期者外，自發布日施行。所謂另訂施行日期者，係指第5條表列既存燒結工場九十五年一月一日、九十七年一月一日之分階段加嚴日期。",
 "How does this standard specify its effective date?",
 ["It takes effect on promulgation unless a date is otherwise set",
  "It uniformly takes effect the day after one full year from promulgation",
  "It takes effect only after the central authority sets a date",
  "It takes effect on 31 December of the year of promulgation"],
 "Article 9."),

# ── ENV-152 餐飲業空氣污染防制設施管理辦法（8 條）─────────────────
("ENV-152","第1條",1,"餐飲業防制設施-法源",
 "餐飲業空氣污染防制設施管理辦法之訂定法源為何？",
 ["依空氣污染防制法第二十三條第二項規定訂定",
  "依空氣污染防制法第二十條第二項規定訂定之",
  "依空氣污染防制法第三十一條第三項規定訂定",
  "依食品安全衛生管理法第八條第四項規定訂定"],"a",
 "第1條：本辦法依空氣污染防制法第二十三條第二項規定訂定。空污法第二十三條係關於公私場所應設置防制設施或監測設施並維持正常運作之規定，故本辦法之重點在於集氣系統與油煙處理設備之設置及操作維護。",
 "What is the legal basis of these regulations on air pollution control facilities for the food and beverage industry?",
 ["Adopted under Article 23, Paragraph 2 of the Air Pollution Control Act",
  "Adopted under Article 20, Paragraph 2 of the Air Pollution Control Act",
  "Adopted under Article 31, Paragraph 3 of the Air Pollution Control Act",
  "Adopted under Article 8, Paragraph 4 of the Food Safety and Sanitation Act"],
 "Article 1."),

("ENV-152","第2條",2,"餐飲業防制設施-定義",
 "本辦法所稱污染防制設施包含哪些？營業面積之範圍為何？",
 ["污染防制設施包含集氣系統、油煙處理設備、監測設施及排氣管線；營業面積指經營所使用之樓地板面積含烹飪作業區及座位區",
  "污染防制設施包含集氣系統、油煙處理設備及消防排煙設備；營業面積指經營所使用之樓地板面積但不含座位區及走道區",
  "污染防制設施僅包含油煙處理設備及排氣管線二項；營業面積指烹飪作業區之地板面積並扣除座位區與廚房儲藏空間",
  "污染防制設施包含集氣系統、油煙處理設備及廢水處理設備；營業面積指建築物登記之總樓地板面積含停車空間在內"],"a",
 "第2條第五款：污染防制設施包含集氣系統、油煙處理設備、監測設施、排氣管線。第二款：營業面積指餐飲業經營所使用之樓地板面積，包括烹飪作業區及座位區等。第六至八款並分別定義集氣系統、油煙處理設備及排氣管線；第十一款定義集氣風量為集氣流速與面積之乘積。",
 "What does a pollution control facility include, and what counts as business floor area?",
 ["It includes the gas collection system, fume treatment equipment, monitoring facilities and exhaust ducts; business area is the floor area used, including cooking and seating areas",
  "It includes the gas collection system, fume treatment equipment and fire smoke exhaust equipment; business area is the floor area used, excluding seating areas and aisles",
  "It includes only the fume treatment equipment and exhaust ducts; business area is the cooking zone floor area minus seating areas and kitchen storage space",
  "It includes the gas collection system, fume treatment equipment and wastewater treatment units; business area is the registered total floor area including parking space"],
 "Article 2, subparagraphs 2 and 5."),

("ENV-152","第3條",1,"餐飲業防制設施-列管對象",
 "本辦法所稱列管對象如何界定？",
 ["指依附表所列行政區域內，達適用條件及規模之餐飲業",
  "指全國各行政區域內從事餐食調理或餐飲承包之所有餐飲業者",
  "指經中央主管機關逐家指定並公告列管之連鎖餐飲業者",
  "指營業面積達五百平方公尺以上之各類餐廳及食品工廠"],"a",
 "第3條：本辦法所稱列管對象，指依附表所列行政區域內，達適用條件及規模之餐飲業。第2條第三、四款並依本辦法發布日區分新設列管餐飲業與既存列管餐飲業，二者依第7條適用不同之符合期限。",
 "How are regulated entities defined under these regulations?",
 ["Food and beverage businesses meeting the applicable conditions and scale within the administrative areas listed in the attached table",
  "All food and beverage businesses engaged in meal preparation or catering anywhere in the administrative areas of the country",
  "Chain food and beverage operators designated and publicly announced one by one by the central competent authority",
  "All kinds of restaurants and food factories with a business floor area of five hundred square meters or more"],
 "Article 3 and its attached table."),

("ENV-152","第4條",3,"餐飲業防制設施-氣罩設置",
 "列管餐飲業採上吸式或側吸式氣罩者，其收集面之設置距離規定為何？",
 ["上吸式應自烹飪設施垂直投影面向外延伸十五公分且與鍋具上緣垂直距離不得大於一百二十公分；側吸式收集面前緣與烹飪區域中心點水平距離不得大於四十五公分",
  "上吸式應自烹飪設施垂直投影面向外延伸四十五公分且與鍋具上緣垂直距離不得大於一百五十公分；側吸式收集面前緣與烹飪區域中心點水平距離不得大於十五公分",
  "上吸式應自烹飪設施垂直投影面向外延伸十五公分且與鍋具上緣垂直距離不得小於一百二十公分；側吸式收集面前緣與烹飪區域中心點水平距離不得小於四十五公分",
  "上吸式應自烹飪設施垂直投影面向內縮減十五公分且與鍋具上緣垂直距離不得大於六十公分；側吸式收集面前緣與烹飪區域中心點水平距離不得大於九十公分"],"a",
 "第4條第二項：採上吸式氣罩者，氣罩收集面應自烹飪設施垂直投影面向外延伸十五公分，且與烹飪鍋具上緣之垂直距離不得大於一百二十公分；採側吸式氣罩者，氣罩收集面前緣與烹飪設施實際烹飪區域中心點或對角線交叉點之水平距離不得大於四十五公分，且氣罩面積應為實際烹飪區域面積之百分之三十以上。第一項並要求集氣系統應與排氣管線連接並維持正常運作。",
 "What are the positioning requirements for an up-draft or side-draft hood collection surface?",
 ["Up-draft hoods must extend 15 cm beyond the vertical projection of the cooking facility and be no more than 120 cm above the pot rim; side-draft hood front edges must be within 45 cm horizontally of the cooking zone center",
  "Up-draft hoods must extend 45 cm beyond the vertical projection of the cooking facility and be no more than 150 cm above the pot rim; side-draft hood front edges must be within 15 cm horizontally of the cooking zone center",
  "Up-draft hoods must extend 15 cm beyond the vertical projection of the cooking facility and be no less than 120 cm above the pot rim; side-draft hood front edges must be no less than 45 cm horizontally from the cooking zone center",
  "Up-draft hoods must be set 15 cm inside the vertical projection of the cooking facility and no more than 60 cm above the pot rim; side-draft hood front edges must be within 90 cm horizontally of the cooking zone center"],
 "Article 4, Paragraph 2."),

("ENV-152","第4條",3,"餐飲業防制設施-面速度",
 "集氣系統氣罩面集氣流速之最低要求及既存業者未達標準時之改善期限為何？",
 ["上吸式應達每秒零點五公尺以上、側吸式應達每秒三公尺以上；既存業者應於主管機關通知改善期限內完成，改善期限以三十日為上限",
  "上吸式應達每秒三公尺以上、側吸式應達每秒零點五公尺以上；既存業者應於主管機關通知改善期限內完成，改善期限以三十日為上限",
  "上吸式應達每秒零點五公尺以上、側吸式應達每秒三公尺以上；既存業者應於主管機關通知改善期限內完成，改善期限以九十日為上限",
  "上吸式應達每秒一點五公尺以上、側吸式應達每秒五公尺以上；既存業者應於主管機關通知改善期限內完成，改善期限以六十日為上限"],"a",
 "第4條第三項：採上吸式氣罩者其氣罩面集氣流速應達每秒零點五公尺以上，採側吸式者其收集面集氣流速應達每秒三公尺以上；屬既存列管餐飲業未能達成者，應於直轄市、縣（市）主管機關通知改善之期限內完成改善，改善期限以三十日為上限。第四項並規定集氣系統之操作條件或數值得有百分之十之容許差值；第五項則允許情形特殊者提出替代方案報請同意。",
 "What is the minimum hood face velocity, and how long may an existing operator take to improve?",
 ["At least 0.5 m/s for up-draft hoods and 3 m/s for side-draft hoods; existing operators must improve within the notified period, capped at 30 days",
  "At least 3 m/s for up-draft hoods and 0.5 m/s for side-draft hoods; existing operators must improve within the notified period, capped at 30 days",
  "At least 0.5 m/s for up-draft hoods and 3 m/s for side-draft hoods; existing operators must improve within the notified period, capped at 90 days",
  "At least 1.5 m/s for up-draft hoods and 5 m/s for side-draft hoods; existing operators must improve within the notified period, capped at 60 days"],
 "Article 4, Paragraph 3; see also Paragraphs 4 and 5."),

("ENV-152","第5條",2,"餐飲業防制設施-處理風量",
 "列管餐飲業所設油煙處理設備之設計處理風量有何要求？",
 ["設計處理風量不得小於集氣系統實際集氣風量，並應維持設備正常運作",
  "設計處理風量不得大於集氣系統實際集氣風量，並應維持設備正常運作",
  "設計處理風量應為集氣系統實際集氣風量之二分之一以上即為合格",
  "設計處理風量由業者依營業面積自行認定，無須與集氣風量相關聯"],"a",
 "第5條第一項：列管餐飲業應設置油煙處理設備，其設計處理風量不得小於集氣系統實際集氣風量，並應維持設備正常運作。第2條第十一款定義集氣風量為集氣流速與面積之乘積，上吸式以氣罩面積計、側吸式以氣罩集氣面積計。",
 "What is required of the design treatment airflow of the fume treatment equipment?",
 ["The design treatment airflow must be no less than the actual airflow of the collection system, kept in normal operation",
  "The design treatment airflow must be no greater than the actual airflow of the collection system, kept in normal operation",
  "The design treatment airflow qualifies as long as it is at least half the actual collection system airflow",
  "The design treatment airflow is decided by the operator from business area, unrelated to collection airflow"],
 "Article 5, Paragraph 1."),

("ENV-152","第5條",3,"餐飲業防制設施-紀錄保存",
 "油煙處理設備之清潔保養頻率及相關紀錄之保存年限為何？",
 ["每月至少清潔或保養一次並記錄執行項目及方式；操作參數與清潔保養紀錄及憑證應保存二年備查",
  "每季至少清潔或保養一次並記錄執行項目及方式；操作參數與清潔保養紀錄及憑證應保存二年備查",
  "每月至少清潔或保養一次並記錄執行項目及方式；操作參數與清潔保養紀錄及憑證應保存六個月備查",
  "每半年至少清潔或保養一次並記錄執行項目及方式；操作參數與清潔保養紀錄及憑證應保存五年備查"],"a",
 "第5條第二項第二款：每月至少清潔或保養一次，並記錄執行項目及執行方式。第三項：第二項第一款操作參數與第二款清潔保養之紀錄及其相關憑證資料應保存二年備查。第二項第一款並就靜電集塵器、濕式洗滌器、活性碳吸附裝置、臭氧處理設備分別規定應記錄之主要操作參數。",
 "How often must fume treatment equipment be cleaned or serviced, and how long are records kept?",
 ["Cleaned or serviced at least once a month with items and methods recorded; parameter and maintenance records and vouchers kept two years",
  "Cleaned or serviced at least once a quarter with items and methods recorded; parameter and maintenance records and vouchers kept two years",
  "Cleaned or serviced at least once a month with items and methods recorded; parameter and maintenance records and vouchers kept six months",
  "Cleaned or serviced at least every six months with items and methods recorded; parameter and maintenance records and vouchers kept five years"],
 "Article 5, Paragraphs 2 and 3."),

("ENV-152","第6條",2,"餐飲業防制設施-監測查核",
 "列管餐飲業所設污染防制設施之監控儀表及水電表紀錄有何規定？",
 ["應具備可顯示主要操作參數之監控儀表或監測設施並設於可供查核處；主管機關得命設置獨立電表或水表並記錄每日用量保存二年",
  "應具備可顯示主要操作參數之監控儀表或監測設施並設於廠區辦公室內；主管機關得命設置獨立電表或水表並記錄每月用量保存一年",
  "應具備可顯示主要操作參數之監控儀表或監測設施並設於可供查核處；主管機關得命設置獨立電表或水表並記錄每日用量保存六個月",
  "得免設監控儀表而以人工每日目視檢查替代並登載於日誌；主管機關不得要求業者另行設置獨立之電表或水表設備裝置"],"a",
 "第6條第一項：列管餐飲業設置之污染防制設施，應具備可顯示第5條第一項第一款各目主要操作參數之監控儀表或監測設施，並設置於可供直轄市、縣（市）主管機關查核之處。第二項：主管機關得命設置獨立電表或水表，並記錄每日用電量或用水量資訊，紀錄應保存二年備查。此與第5條第三項之二年保存期一致。",
 "What are the rules on monitoring instruments and utility meter records for the control facilities?",
 ["Instruments showing the main operating parameters must be installed where the authority can inspect them; the authority may order separate meters with daily readings kept two years",
  "Instruments showing the main operating parameters must be installed in the plant office; the authority may order separate meters with monthly readings kept one year",
  "Instruments showing the main operating parameters must be installed where the authority can inspect them; the authority may order separate meters with daily readings kept six months",
  "Monitoring instruments may be omitted and replaced by daily visual checks logged by staff; the authority may not require separate electricity or water meters"],
 "Article 6."),

("ENV-152","第7條",3,"餐飲業防制設施-符合期限",
 "新設與既存列管餐飲業應自何時起符合本辦法？展延之申請期限及最後期限為何？",
 ["新設自一百十一年一月一日、既存自一百十一年二月一日起符合；得於期限屆滿前二個月申請展延，展延不得逾一百十一年七月一日",
  "新設自一百十一年二月一日、既存自一百十一年一月一日起符合；得於期限屆滿前二個月申請展延，展延不得逾一百十一年七月一日",
  "新設自一百十一年一月一日、既存自一百十一年二月一日起符合；得於期限屆滿前一個月申請展延，展延不得逾一百十二年一月一日",
  "新設自一百十年七月一日、既存自一百十一年七月一日起符合；得於期限屆滿前三個月申請展延，展延不得逾一百十二年七月一日"],"a",
 "第7條第一項：新設列管餐飲業應自中華民國一百十一年一月一日起符合本辦法規定；既存列管餐飲業應自一百十一年二月一日起符合。第二項：因不可歸責於既存列管餐飲業之事由致無法如期符合者，得於期限屆滿前二個月檢具證明文件及相關資料，向直轄市、縣（市）主管機關申請展延，展延期限不得逾一百十一年七月一日。",
 "From when must new and existing regulated food businesses comply, and what are the extension deadlines?",
 ["New from 1 Jan 2022 and existing from 1 Feb 2022; extension may be sought two months before the deadline and may not go beyond 1 Jul 2022",
  "New from 1 Feb 2022 and existing from 1 Jan 2022; extension may be sought two months before the deadline and may not go beyond 1 Jul 2022",
  "New from 1 Jan 2022 and existing from 1 Feb 2022; extension may be sought one month before the deadline and may not go beyond 1 Jan 2023",
  "New from 1 Jul 2021 and existing from 1 Jul 2022; extension may be sought three months before the deadline and may not go beyond 1 Jul 2023"],
 "Article 7."),

("ENV-152","第8條",1,"餐飲業防制設施-施行",
 "本辦法之施行日期如何規定？",
 ["本辦法自發布日起施行","本辦法自發布後一年施行","本辦法自公告核定日施行","本辦法自次年元旦起施行"],"a",
 "第8條：本辦法自發布日施行。惟列管餐飲業實際應符合本辦法各項設施規定之期限，另依第7條規定分別為一百十一年一月一日（新設）及一百十一年二月一日（既存）。",
 "How does this regulation specify its effective date?",
 ["It takes effect on the date of promulgation",
  "It takes effect one year after promulgation",
  "It takes effect on the date of approval notice",
  "It takes effect on 1 January of the next year"],
 "Article 8; see also Article 7."),

# ── ENV-153 瀝青拌合業粒狀污染物排放標準（8 條）───────────────────
("ENV-153","第1條",1,"瀝青拌合-法源",
 "瀝青拌合業粒狀污染物排放標準之訂定法源為何？",
 ["依空氣污染防制法第二十條第二項規定訂定",
  "依空氣污染防制法第二十三條第二項規定訂定",
  "依空氣污染防制法第二十八條第三項規定訂定",
  "依公路法第七十八條第二項規定授權訂定之"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項規定訂定。第2條規定本標準未規定事項適用其他相關之規定；第3條界定適用對象為瀝青拌合業工廠。",
 "What is the legal basis of the particulate emission standard for asphalt mixing plants?",
 ["Adopted under Article 20, Paragraph 2 of the Air Pollution Control Act",
  "Adopted under Article 23, Paragraph 2 of the Air Pollution Control Act",
  "Adopted under Article 28, Paragraph 3 of the Air Pollution Control Act",
  "Adopted under the authority of Article 78, Paragraph 2 of the Highway Act"],
 "Article 1."),

("ENV-153","第2條",1,"瀝青拌合-適用",
 "本標準未規定之事項如何處理？",
 ["適用其他相關之規定",
  "由業者自行決定辦理",
  "一律免除相關之義務",
  "報請中央機關另定之"],"a",
 "第2條：本標準未規定事項適用其他相關之規定。例如一般性之粒狀污染物排放限值、周界標準、許可證管理等，即回歸固定污染源空氣污染物排放標準與空氣污染防制法相關子法辦理。",
 "How are matters not covered by this standard handled?",
 ["Other relevant provisions apply to them",
  "Operators decide how to handle them",
  "All related obligations are waived",
  "The central authority sets them later"],
 "Article 2."),

("ENV-153","第3條",1,"瀝青拌合-對象",
 "本標準之適用對象為何？",
 ["瀝青拌合業藉由加熱乾燥砂石粒料與加熱呈液態之瀝青膠泥混拌生產瀝青混合料之工廠",
  "瀝青拌合業藉由常溫拌合砂石粒料與乳化瀝青生產透水性鋪面材料之預拌加工廠場",
  "營建工程中從事道路刨除、鋪築瀝青混凝土及路面壓實作業之施工機具與工地",
  "水泥業中藉由旋窯高溫煅燒石灰石與黏土生產水泥熟料及水泥製品之工廠"],"a",
 "第3條：本標準之適用對象指瀝青拌合業藉由加熱乾燥砂石粒料與加熱呈液態之瀝青膠泥混拌生產瀝青混合料之工廠。第5條並就非經集塵設備處理而排放之逸散源（其他污染源）加以列舉。",
 "To what does this standard apply?",
 ["Asphalt mixing plants that heat and dry aggregates and mix them with heated liquid asphalt cement to produce asphalt mixtures",
  "Asphalt plants that mix aggregates with emulsified asphalt at ambient temperature to produce permeable paving materials",
  "Construction machinery and sites engaged in road milling, asphalt concrete paving and pavement compaction work",
  "Cement plants that calcine limestone and clay in rotary kilns at high temperature to produce clinker and cement products"],
 "Article 3."),

("ENV-153","第4條",1,"瀝青拌合-規定值",
 "本標準之粒狀污染物排放規定值以何種形式呈現？",
 ["以本標準所附之附表規定其排放標準值",
  "以條文文字逐項列出各污染源限值數字",
  "由地方主管機關依個案許可證中載明",
  "準用水泥業空氣污染物排放標準規定值"],"a",
 "第4條：本標準規定值如附表。第7條並規定本標準污染物之測定依附表及中央主管機關增修訂公告之方法；第6條則規定濃度值之計算基準及含氧量參考基準。",
 "In what form are the particulate emission limits under this standard set out?",
 ["They are set out in the table attached to this standard",
  "They are listed item by item in the text of the articles",
  "They are stated in each permit by the local authority",
  "They follow the cement industry emission standards"],
 "Article 4."),

("ENV-153","第5條",2,"瀝青拌合-其他污染源",
 "本標準所稱其他污染源指非經集塵設備處理而排放之逸散源，包括下列何者？",
 ["粒料乾燥機、砂石粒料儲運及秤重系統、砂石瀝青之拌合系統、礦物填充料下料及儲運系統",
  "粒料乾燥機、瀝青膠泥加熱鍋爐排放管道、成品瀝青混合料出料煙道、廠內道路灑水區域",
  "廠區周界圍籬、成品堆置場、員工停車場區域、進出廠區之砂石運輸車輛與其行駛路徑",
  "集塵設備排放管道、廢氣旁通管線、緊急發電機排氣管、鍋爐燃燒後之煙囪排放口位置"],"a",
 "第5條：本標準所稱其他污染源指非經集塵設備處理而排放之逸散源，包括粒料乾燥機、砂石粒料儲運及秤重系統、砂石瀝青之拌合系統、礦物填充料下料及儲運系統四款。此等逸散源之排放限值另依第4條附表規定。",
 "Which of the following are the other pollution sources, that is, fugitive sources not treated by dust collectors?",
 ["The aggregate dryer, aggregate storage and weighing systems, the aggregate-asphalt mixing system, and mineral filler discharge and storage systems",
  "The aggregate dryer, the asphalt cement heating boiler stack, the finished mixture discharge stack, and the plant road watering area",
  "The site boundary fence, the product stockpile yard, the staff parking area, and aggregate trucks entering the plant with their routes",
  "The dust collector stack, the exhaust bypass duct, the emergency generator exhaust pipe, and the boiler chimney outlet after combustion"],
 "Article 5."),

("ENV-153","第6條",2,"瀝青拌合-計算基準",
 "本標準濃度值之計算基準及排放管道排氣含氧量參考基準為何？",
 ["以凱氏溫度二七三度、一大氣壓下未經稀釋之乾燥排氣體積為計算基準，排放管道含氧量以百分之十六為參考基準",
  "以凱氏溫度二九八度、一大氣壓下未經稀釋之乾燥排氣體積為計算基準，排放管道含氧量以百分之十五為參考基準",
  "以凱氏溫度二七三度、一大氣壓下已經稀釋之濕潤排氣體積為計算基準，排放管道含氧量以百分之六為參考基準",
  "以凱氏溫度二七三度、二大氣壓下未經稀釋之乾燥排氣體積為計算基準，排放管道含氧量以百分之十二為參考基準"],"a",
 "第6條：本標準濃度值計算均以凱氏溫度二七三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，排放管道排氣含氧量以百分之十六為參考基準。此與鋼鐵業燒結工場之百分之十五、廢棄物焚化爐之百分之十一等參考基準不同，應予區辨。",
 "What are the calculation basis and the reference oxygen content for stacks under this standard?",
 ["Undiluted dry exhaust volume at 273 K and 1 atm, with a stack reference oxygen content of 16 percent",
  "Undiluted dry exhaust volume at 298 K and 1 atm, with a stack reference oxygen content of 15 percent",
  "Diluted wet exhaust volume at 273 K and 1 atm, with a stack reference oxygen content of 6 percent",
  "Undiluted dry exhaust volume at 273 K and 2 atm, with a stack reference oxygen content of 12 percent"],
 "Article 6."),

("ENV-153","第7條",1,"瀝青拌合-測定方法",
 "本標準污染物之測定應依何種方法辦理？",
 ["依附表及中央主管機關增修訂公告之方法",
  "依業者委託之檢測機構自訂之作業方法",
  "依國際標準組織公告之最新版測定方法",
  "依地方主管機關於許可證載明之方法"],"a",
 "第7條：本標準污染物之測定依附表及中央主管機關增修訂公告之方法。此與第4條規定值如附表相呼應，故附表兼具限值與測定方法之功能。",
 "By what methods must pollutants be measured under this standard?",
 ["By the attached table and methods announced or revised by the central authority",
  "By methods drawn up by the testing organization the operator retains",
  "By the latest measurement methods announced by the ISO organization",
  "By the methods specified in the permit by the local competent authority"],
 "Article 7."),

("ENV-153","第8條",1,"瀝青拌合-施行",
 "本標準規定事項之施行日期如何規定？",
 ["除另定施行日期者外，自發布日施行",
  "須經行政院核定後三個月始得施行",
  "一律自發布日起屆滿一年後始施行",
  "由中央主管機關另行公告日期施行"],"a",
 "第8條：本標準規定事項除另定施行日期者外，自發布日施行。本標準最近一次修正日期為民國八十八年四月七日，其附表所列各污染源之粒狀物限值即自該時起適用。",
 "How does this standard specify its effective date?",
 ["It takes effect on promulgation unless otherwise specified",
  "It may take effect three months after Executive Yuan approval",
  "It uniformly takes effect one full year after promulgation",
  "The central authority announces the effective date separately"],
 "Article 8."),
]
