# -*- coding: utf-8 -*-
# 第 11 批（A2）：職業安全衛生設施規則 補題（第61條～第125條）
L = "OSH-07"
Q = [
(L,"第61條",1,"設施規則-一般工作機械",
 "對於金屬、塑膠等加工用之圓盤鋸，雇主應設置何種安全裝置？",
 ["鋸齒接觸預防裝置","反撥預防之楔子裝置","雙手操作式安全裝置","感應式光電安全裝置"],"a",
 "第61條：雇主對於金屬、塑膠等加工用之圓盤鋸，應設置鋸齒接觸預防裝置。木材加工用圓盤鋸另依機械設備器具安全標準辦理（第41條）。",
 "What device must be fitted to circular saws for metal or plastics?",
 ["A saw blade contact prevention device","An anti kickback riving knife device","A two hand control safety device","A photoelectric sensing safety device"],
 "Article 61 requires a blade contact prevention device."),

(L,"第63條",2,"設施規則-一般工作機械",
 "對於棉紡機、絲紡機等機械之高速迴轉部分易發生危險者，應如何辦理？",
 ["應裝置護罩、護蓋或其他適當之安全裝置","應每三個月測定其迴轉數並作成紀錄備查","應限制其最高迴轉數不得超過每分鐘百轉","應由作業管理人員於運轉中全程在旁監視"],"a",
 "第63條：雇主對於棉紡機、絲紡機、手紡式或其他各種機械之高速迴轉部分易發生危險者，應裝置護罩、護蓋或其他適當之安全裝置。",
 "What is required for dangerous high speed rotating parts of spinning machines?",
 ["Guards, covers or other suitable safety devices must be installed","Their speed must be measured quarterly and recorded for inspection","Their maximum speed must be capped at one hundred revolutions a minute","A designated manager must watch beside them throughout operation"],
 "Article 63 requires guards, covers or other suitable safety devices."),

(L,"第64條",2,"設施規則-木材加工機械",
 "對於木材加工用帶鋸之鋸齒及帶輪，本規則規定應如何處理？",
 ["除鋸切所需部分及鋸床外，應設置護罩或護圍等設備","除鋸切所需部分外，應以透明壓克力板完全密閉包覆","應於帶鋸兩側設置警告標示，並由專人於作業中監看","應每日作業前試轉三分鐘以上並確認鋸齒無裂痕情形"],"a",
 "第64條：雇主對於木材加工用帶鋸鋸齒（鋸切所需之部分及鋸床除外）及帶輪，應設置護罩或護圍等設備。第65條另規定導送滾輪之接觸預防裝置。",
 "How must the teeth and wheels of a woodworking band saw be handled?",
 ["Guards or fences are required, except the cutting part and the saw bed","The whole saw must be fully enclosed in transparent acrylic panels","Warning signs on both sides plus a dedicated watcher during the work","A three minute trial run each day to check the teeth for cracks"],
 "Article 64 exempts only the cutting portion and the saw bed."),

(L,"第65條",2,"設施規則-木材加工機械",
 "木材加工用帶鋸之突釘型或鋸齒型導送滾輪，應如何防護？",
 ["除導送面外應設接觸預防裝置或護蓋，設緊急制動裝置能停止轉動者除外","除導送面外應設接觸預防裝置或護蓋，且不得有任何例外之情形","應於滾輪外部包覆橡膠並降低轉速至每分鐘二十轉以下使用","應由勞工佩戴防割手套後操作，並於作業前實施口頭告知"],"a",
 "第65條：突釘型導送滾輪或鋸齒型導送滾輪，除導送面外，應設接觸預防裝置或護蓋；但設有緊急制動裝置，使勞工能停止該滾輪轉動者，不在此限。",
 "How must spiked or toothed feed rollers of a band saw be protected?",
 ["Contact prevention devices or covers except the feed face, unless an e stop exists","Contact prevention devices or covers except the feed face, with no exception","The rollers must be rubber wrapped and run below twenty revolutions a minute","Workers wear cut resistant gloves and receive a verbal briefing beforehand"],
 "Article 65 exempts rollers with an emergency stop that halts rotation."),

(L,"第66條",2,"設施規則-木材加工機械",
 "對於有自動輸送裝置以外之截角機，本規則規定應如何辦理？",
 ["應裝置刃部接觸預防裝置，但妨礙工作且勞工使用送料工具者除外","應裝置刃部接觸預防裝置，於任何情形下均不得免除其設置","應設置雙手操作式安全裝置，並禁止使用任何送料之工具","應由作業管理人員逐次啟動，勞工不得自行操作該機械"],"a",
 "第66條：雇主對於有自動輸送裝置以外之截角機，應裝置刃部接觸預防裝置；但設置接觸預防裝置有阻礙工作，且勞工使用送料工具時，不在此限。",
 "What applies to mitre saws without an automatic feed device?",
 ["A blade contact prevention device, unless it hinders work and feed tools are used","A blade contact prevention device that may never be omitted in any case","A two hand control device, with the use of any feeding tool prohibited","Only the designated manager may start it; workers may not operate it"],
 "Article 66 allows the exemption only where the device hinders work and feed tools are used."),

(L,"第67條",1,"設施規則-木材加工機械",
 "對於自動輸材台或帶鋸輸材台與鋸齒之間，雇主應如何辦理？",
 ["應禁止勞工進入，並加以標示","應設置監視器並保存影像三年","應鋪設止滑踏板供勞工站立作業","應設置高度九十公分以上之扶手"],"a",
 "第67條：雇主應禁止勞工進入自動輸材台或帶鋸輸材台與鋸齒之間，並加以標示。第68條另規定木材加工機械合計五台以上應指定作業管理人員。",
 "What applies to the space between a saw carriage and the saw teeth?",
 ["Workers must be barred from entering, and a notice must be posted","A camera must be installed and the footage kept for three years","Anti slip treads must be laid so workers can stand and work there","A handrail at least ninety centimetres high must be installed"],
 "Article 67 forbids entry and requires marking."),

(L,"第70條",3,"設施規則-衝剪機械",
 "調整衝剪機械之金屬模使滑塊等動作時，本規則規定之作法為何？",
 ["具寸動機構者應採用寸動；未具者應切斷動力電源，待飛輪停止後以手旋動調整","具寸動機構者應採連續運轉；未具者得於飛輪旋轉中直接以手調整之","一律應切斷動力電源，並於飛輪停止前即可開始進行金屬模之調整","一律應採用連續行程，並由二名勞工同時按壓雙手操作開關進行"],"a",
 "第70條：對具有寸動機構或滑塊調整裝置者，應採用寸動；未具寸動機構者，應切斷衝剪機械之動力電源，於飛輪等之旋轉停止後，用手旋動飛輪調整之。",
 "How must the slide be moved when adjusting dies on a press?",
 ["Use inching if available; otherwise cut power and turn the flywheel by hand when stopped","Use continuous running if inching exists; otherwise adjust by hand while spinning","Always cut the power, and adjustment may begin before the flywheel stops","Always use a continuous stroke with two workers pressing the two hand controls"],
 "Article 70: inching where available, otherwise power off and hand turning after the flywheel stops."),

(L,"第71條",2,"設施規則-衝剪機械",
 "下列何者屬本規則第71條規定衝剪機械應保持應有性能之機件或機構？",
 ["一行程一停止機構、連動停止機構或緊急停止機構","進料用之輸送帶及其張力調整用之惰輪組件","機台照明用之防眩燈具及其固定支架與配線","冷卻潤滑油之循環泵浦及其過濾器等零組件"],"a",
 "第71條列舉應保持性能之機件：離合器及制動裝置、附屬於離合器與制動之螺絲彈簧及梢、連結機構部分、滑塊機構、一行程一停止機構與連動停止機械或緊急停止機構。",
 "Which is listed in Article 71 as a part whose function must be maintained?",
 ["The single stroke stop, interlocked stop or emergency stop mechanism","The feeding conveyor belt and the idler set adjusting its tension","Anti glare lamps for the machine table with brackets and wiring","Coolant circulation pumps together with their filters and fittings"],
 "Article 71 lists clutch, brake, linkage, slide and stop mechanisms."),

(L,"第72條",2,"設施規則-衝剪機械",
 "雇主設置衝剪機械達幾台以上時，應指定作業管理人員負責法定職務？",
 ["五台","三台","八台","十台"],"a",
 "第72條：設置衝剪機械五台以上時，應指定作業管理人員負責檢查機械及安全裝置、發現異狀採必要措施、保管鎖式換回開關鎖匙、直接指揮金屬模之裝置拆卸及調整作業。第68條木材加工機械亦為五台。",
 "From how many press machines must a designated operations manager be assigned?",
 ["Five units","Three units","Eight units","Ten units"],
 "Article 72: five or more press machines."),

(L,"第74條",1,"設施規則-離心機械",
 "自離心機械取出內裝物時，除置有自動取出機械外，本規則規定為何？",
 ["應規定勞工於操作前使該機械停止運轉","應規定勞工使用長柄工具於運轉中取出","應規定由二名以上勞工共同操作始得取出","應規定將回轉數降至半數以下後再取出"],"a",
 "第74條：雇主對於自離心機械取出內裝物時，除置有自動取出內裝物之機械外，應規定勞工操作前，應使該機械停止運轉。第73條另要求裝置覆蓋及連鎖裝置。",
 "How must contents be removed from a centrifugal machine?",
 ["Workers must stop the machine before starting the operation","Workers must use long handled tools while it is still running","At least two workers must carry out the removal together","The speed must first be reduced to less than half the rated"],
 "Article 74 requires stopping the machine unless automatic removal is provided."),

(L,"第75條",1,"設施規則-離心機械",
 "對於離心機械之使用，本規則就轉速有何規定？",
 ["應規定不得超越該機械之最高使用回轉數","應規定不得超越該機械額定回轉數之八成","應規定每日作業前試轉一分鐘以上再使用","應規定每半年委外檢測回轉數一次並紀錄"],"a",
 "第75條：雇主對於離心機械之使用，應規定不得超越該機械之最高使用回轉數。研磨輪之最高使用周速度限制則見第62條。",
 "What speed limit applies to the use of centrifugal machines?",
 ["Use must never exceed the machines maximum permitted speed","Use must not exceed eighty percent of the rated speed","A one minute trial run is required before work each day","Speed must be measured by an outside body twice a year"],
 "Article 75 bars exceeding the maximum permitted rotational speed."),

(L,"第77條",2,"設施規則-粉碎機混合機",
 "自粉碎機或混合機取出內裝物時，本規則之規定為何？",
 ["應使機械停止運轉，但作業需要不能停止且以工具取出不致危及安全者除外","應使機械停止運轉，且不得有任何得於運轉中取出之例外情形","得於運轉中直接以手取出，惟應由監視人員在旁全程戒護","應先將開口部以護蓋封閉，再由勞工自側面之檢修門取出"],"a",
 "第77條：除置有自動取出內裝物之機械外，應規定勞工操作前使機械停止運轉；但基於作業需要該機械不能停止運轉，且使勞工使用工具取出內裝物時不致危及安全者，不在此限。",
 "How must contents be taken from a crusher or mixer?",
 ["Stop the machine, unless work needs prevent it and tools make removal safe","Stop the machine, with no exception permitting removal while running","Contents may be taken by hand while running if a watcher stands by","Close the opening with a cover and remove through the side access door"],
 "Article 77 allows the exception only where tools make the removal safe."),

(L,"第78條",2,"設施規則-滾軋機",
 "對於滾輾紙、布、金屬箔等具有捲入點之滾軋機，有危害之虞時應如何辦理？",
 ["應設護圍、導輪或具有連鎖性能之安全防護裝置等設備","應設置防塵罩並於機台旁張貼禁止伸手之警告標示","應指派勞工二人一組作業，其中一人專責緊急按鈕","應將滾輪轉速調降至每分鐘十公尺以下始得以操作"],"a",
 "第78條：雇主對於滾輾紙、布、金屬箔等或其他具有捲入點之滾軋機，有危害勞工之虞時，應設護圍、導輪或具有連鎖性能之安全防護裝置等設備。",
 "What is required for rolling machines with in running nip points?",
 ["Fences, guide rollers or interlocked safety guarding devices must be fitted","A dust cover and a warning sign forbidding reaching in must be posted","Workers must work in pairs, one taking charge of the emergency button","The roller speed must be cut to under ten metres a minute before use"],
 "Article 78 requires fences, guide rollers or interlocked guards."),

(L,"第79條",2,"設施規則-滾軋機",
 "對於滾輾橡膠、合成樹脂之滾輾機，本規則要求設置何種裝置？",
 ["於災害發生時被害者能自己易於操縱之緊急制動裝置","於災害發生時由現場作業主管遠端操作之停止按鈕","可自動偵測異物並反向退出之感應式安全防護裝置","可於超載時自動卸除動力之過負荷防止與警報裝置"],"a",
 "第79條：雇主對於滾輾橡膠、橡膠化合物、合成樹脂之滾輾機或其他具有危害之滾輾機，應設置於災害發生時，被害者能自己易於操縱之緊急制動裝置。",
 "What device must rubber or resin rolling machines have?",
 ["An emergency brake the victim can easily operate when an accident happens","A stop button the site supervisor operates remotely when an accident happens","A sensing guard that detects foreign objects and reverses the rollers","An overload prevention device that cuts power and alarms when overloaded"],
 "Article 79 stresses that the victim can operate it easily."),

(L,"第80條",1,"設施規則-滾軋機",
 "對於置有紗梭之織機，雇主應裝置何種設備？",
 ["導梭","護網","跨橋","制動器"],"a",
 "第80條：雇主對於置有紗梭之織機，應裝置導梭，以防止紗梭飛出傷害勞工。",
 "What must be fitted to looms equipped with a shuttle?",
 ["A shuttle guard","A protective net","A crossing bridge","A braking device"],
 "Article 80 requires a shuttle guard."),

(L,"第81條",1,"設施規則-滾軋機",
 "對於引線機之引線滑車或撚線機之籠車，有危害勞工之虞者應如何辦理？",
 ["應設護罩、護圍等設備","應設接地與漏電斷路器","應設自動注油潤滑裝置","應設轉速與張力顯示器"],"a",
 "第81條：雇主對於引線機之引線滑車或撚線機之籠車，有危害勞工之虞者，應設護罩、護圍等設備。",
 "What is required for wire drawing sheaves or stranding machine cages?",
 ["Guards or protective fences must be provided","Earthing and an earth leakage breaker","An automatic lubricating oiler device","A speed and tension indicating meter"],
 "Article 81 requires guards or fences."),

(L,"第82條",3,"設施規則-成型機械",
 "對於射出成型機、打模機、輪胎成型機等加壓成型機械之安全門，本規則有何要求？",
 ["應具有非關閉狀態即無法起動機械之性能","應具有於開啟時自動噴灑冷卻液之性能","應以透明材質製造並標示最大成型壓力","應於每次開啟後由專人簽名確認並紀錄"],"a",
 "第82條：射出成型機、鑄鋼造形機、打模機、橡膠加硫成型機、輪胎成型機等，應設安全門、雙手操作式安全裝置、感應式安全裝置或其他安全裝置；前項安全門應具有非關閉狀態即無法起動機械之性能。",
 "What must the safety door of a moulding press provide?",
 ["The machine cannot start unless the door is in the closed state","Coolant must be sprayed automatically whenever the door opens","It must be transparent and marked with the maximum forming pressure","A designated person must sign a record after each opening of the door"],
 "Article 82: the machine must be unable to start while the door is open."),

(L,"第83條",1,"設施規則-機械一般",
 "對於扇風機之葉片有危害勞工之虞者，雇主應設置何種設備？",
 ["護網或護圍等設備","接地與漏電斷路器","風速指示及警報器","定時自動停止裝置"],"a",
 "第83條：雇主對於扇風機之葉片，有危害勞工之虞者，應設護網或護圍等設備。",
 "What must be fitted where fan blades may endanger workers?",
 ["Protective nets or guarding fences","Earthing and a leakage breaker","A wind speed gauge with alarm","A timer that stops it automatically"],
 "Article 83 requires nets or fences."),

(L,"第85條",3,"設施規則-高速回轉體",
 "施行高速回轉體試驗前應先實施非破壞檢查者，其轉軸條件為何？",
 ["重量超越一公噸，且週邊速率在每秒一百二十公尺以上","重量超越五公噸，且週邊速率在每秒二十五公尺以上","重量超越一公噸，且週邊速率在每秒六十公尺以上者","重量超越十公噸，且週邊速率在每秒一百公尺以上者"],"a",
 "第85條：轉軸之重量超越一公噸，且轉軸之週邊速率在每秒一百二十公尺以上之高速回轉體試驗，應事先就該軸材質、形狀等施行非破壞檢查，確認無破壞原因存在時始得為之。第84條之隔離規定門檻則為每秒二十五公尺。",
 "Which rotor requires non destructive testing before a spin test?",
 ["Shaft weight over one tonne with peripheral speed of 120 m/s or more","Shaft weight over five tonnes with peripheral speed of 25 m/s or more","Shaft weight over one tonne with peripheral speed of 60 m/s or more","Shaft weight over ten tonnes with peripheral speed of 100 m/s or more"],
 "Article 85: over one tonne and 120 metres per second."),

(L,"第86條",2,"設施規則-高速回轉體",
 "施行第85條所定高速回轉體試驗時，本規則要求之操作方式為何？",
 ["應以遙控操作等方法控制，使破壞時不致傷及勞工","應由二名以上勞工於現場共同操作並相互監督之","應於試驗中全程錄影並保存紀錄三年以上備查用","應先以額定轉速之半數試轉十分鐘後再逐步加速"],"a",
 "第86條：雇主於施行前條規定高速回轉試驗時，應以遙控操作等方法控制；使試驗中即使該高速回轉體破壞時，亦不致傷及勞工。",
 "How must the spin test under Article 85 be operated?",
 ["By remote control or similar means so a burst cannot injure workers","By two or more workers operating together on site and watching each other","By recording the whole test on video and keeping it for three years","By first running at half rated speed for ten minutes and then speeding up"],
 "Article 86 requires remote control operation."),

(L,"第87條",1,"設施規則-起重升降機具",
 "起重升降機具之設備及有關措施，本規則規定應依何者辦理？",
 ["起重升降機具有關安全規則","鍋爐及壓力容器安全規則","高壓氣體設備安全規則","機械設備器具安全標準"],"a",
 "第87條：雇主對於起重升降機具之設備及有關措施，應依起重升降機具有關安全規則辦理。第103條並規定除本節外並應依其他相關職業安全衛生法規辦理。",
 "Which rules govern lifting appliance equipment and measures?",
 ["The safety rules on lifting appliances","The boiler and pressure vessel rules","The high pressure gas equipment rules","The safety standards for machinery"],
 "Article 87 refers to the safety rules for lifting appliances."),

(L,"第89條",1,"設施規則-起重升降機具",
 "對於各種起重機具，本規則就負荷標示有何規定？",
 ["應標示最高負荷，並規定使用時不得超過該項限制","應標示自重與空重，使用時得超過最高負荷一成","應標示製造年份與廠牌，並每年重新噴漆一次以上","應標示操作人員姓名，並由該人員負責保管鑰匙"],"a",
 "第89條：雇主對於各種起重機具，應標示最高負荷，並規定使用時不得超過此項限制。第94條就升降機另規定標示積載荷重或乘載最高人數。",
 "What marking is required on lifting appliances?",
 ["The maximum load must be marked and use must never exceed it","The dead weight must be marked and the load may exceed it by ten percent","The year and brand must be marked and repainted at least once a year","The operators name must be marked and that person keeps the key"],
 "Article 89 requires marking of the maximum load."),

(L,"第90條",1,"設施規則-起重升降機具",
 "對於起重機具之吊鉤或吊具，本規則要求應有何種裝置？",
 ["防止吊舉中所吊物體脫落之裝置","顯示實際吊掛重量之荷重計裝置","自動調整吊掛角度之平衡裝置者","於超載時自動釋放吊物之洩壓閥"],"a",
 "第90條：雇主對於起重機具之吊鉤或吊具，應有防止吊舉中所吊物體脫落之裝置。第91條另規定過捲預防裝置之距離要求。",
 "What device must hooks or lifting gear have?",
 ["A device preventing the load from slipping off while being lifted","A load meter showing the actual weight of the hanging load","A balancing device that adjusts the sling angle automatically","A relief valve that releases the load automatically when overloaded"],
 "Article 90 requires a device preventing the load dropping off the hook."),

(L,"第92條",2,"設施規則-起重升降機具",
 "起重機具運轉時為防止吊掛物掉落，下列規定何者正確？",
 ["吊耳設置位置及數量應能確保吊掛物之平衡，並能承受整體重量","吊耳數量由操作人員視現場情況決定，不必考慮平衡之問題","吊索、吊籃等吊掛用具之強度得低於吊掛物重量之二分之一","吊掛物通過人員上方時，僅需鳴笛示警即可繼續進行吊運"],"a",
 "第92條：應採取防止吊掛物通過人員上方及人員進入吊掛物下方之設備或措施；使用吊耳時，其設置位置及數量應確保吊掛物之平衡，結合方式應能承受整體重量，吊索吊籃等應有足夠強度。",
 "Which rule prevents suspended loads from falling during crane operation?",
 ["Lifting lug position and number must ensure balance and bear the whole weight","The operator alone decides the number of lugs without regard to balance","Slings and baskets may have strength below half the weight of the load","Loads may pass over persons provided a warning horn is first sounded"],
 "Article 92 also bars loads passing above people or people going under loads."),

(L,"第93條",2,"設施規則-起重升降機具",
 "對於升降機之升降路各樓出入口，本規則規定應具備何種安全裝置？",
 ["任一門開啟時升降機不能開動，開動中任一門開啟能停止上下","任一門開啟時升降機得低速開動，並由管理員在旁監視操作","各樓出入口門得以布簾或活動柵欄替代，但應標示警告文字","出入口門應於營業時間內全部開啟，以利勞工進出及避難用"],"a",
 "第93條：升降路各樓出入口應裝置構造堅固平滑之門，並應有安全裝置，使升降搬器及升降路出入口之任一門開啟時，升降機不能開動；及升降機在開動中任一門開啟時，能停止上下。",
 "What safety device is required at each landing door of an elevator?",
 ["The lift cannot start with any door open, and stops if a door opens in motion","The lift may run slowly with a door open while an attendant watches it","Curtains or movable gates may replace doors if a warning sign is posted","All landing doors must stay open during business hours for easy escape"],
 "Article 93 requires interlocking of all landing and car doors."),

(L,"第94條",1,"設施規則-起重升降機具",
 "對於升降機各樓出入口及搬器內，本規則規定應明顯標示何者？",
 ["積載荷重或乘載之最高人數，並規定不得超過限制","製造廠商名稱與出廠年份，並每三年重新標示一次","最近一次定期檢查日期，並由檢查人員簽名確認之","緊急聯絡電話與管理員姓名，供故障時聯繫使用之"],"a",
 "第94條：雇主對於升降機各樓出入口及搬器內，應明顯標示其積載荷重或乘載之最高人數，並規定使用時不得超過限制。第89條就起重機具標示最高負荷亦同旨。",
 "What must be clearly marked at elevator landings and inside the car?",
 ["The load capacity or maximum number of persons, which must not be exceeded","The makers name and year of manufacture, re marked every three years","The date of the most recent periodic inspection, signed by the inspector","An emergency phone number and the name of the building administrator"],
 "Article 94 requires marking of capacity and bars exceeding it."),

(L,"第96條",1,"設施規則-起重升降機具",
 "對於升降機，本規則規定應設置下列何種安全裝置？",
 ["終點極限開關、緊急剎車及其他安全裝置","過負荷防止裝置及吊掛物平衡指示裝置","逸走防止裝置及軌道夾鉗等固定用裝置","警報式風速計及自動收捲之防風纜索"],"a",
 "第96條：雇主對於升降機，應設置終點極限開關、緊急剎車及其他安全裝置。第93條、第95條並就出入口門之連鎖裝置有規定。",
 "Which safety devices must an elevator have?",
 ["Terminal limit switches, an emergency brake and other safety devices","An overload prevention device and a load balance indicator","A runaway prevention device with rail clamps for anchoring","An alarming anemometer with automatically retracting guy ropes"],
 "Article 96 requires limit switches and an emergency brake."),

(L,"第100條",1,"設施規則-起重升降機具",
 "下列何種吊鉤、鉤環或鏈環，不得作為起重升降機具之吊掛用具？",
 ["已變形或已龜裂者","表面有輕微鏽斑者","未標示製造廠商者","使用逾三年未換新者"],"a",
 "第100條：雇主不得使用已變形或已龜裂之吊鉤、鉤環、鏈環，作為起重升降機具之吊掛用具。第98條、第99條另就吊鏈與鋼索之汰換基準規定。",
 "Which hooks, shackles or links may not be used as lifting gear?",
 ["Those that are deformed or cracked","Those with slight surface rust spots","Those without a makers name marked","Those used for more than three years"],
 "Article 100 bars deformed or cracked hooks, shackles and links."),

(L,"第102條",2,"設施規則-起重升降機具",
 "吊鏈或未設環結之鋼索，須具備何種端末處理始得作為吊掛用具？",
 ["兩端設有吊鉤、鉤環、鏈環或編結環首、壓縮環首","兩端以鐵絲纏繞十圈以上並塗覆防鏽油脂處理者","兩端以電焊直接熔接成閉合環狀並經目視確認者","兩端以塑膠套管包覆並加註使用荷重標籤標示者"],"a",
 "第102條：吊鏈或未設環結之鋼索，其兩端非設有吊鉤、鉤環、鏈環或編結環首、壓縮環首者，不能作為起重機具之吊掛用具。",
 "What end fittings must chains or unlooped wire ropes have to be used as slings?",
 ["Hooks, shackles, links, spliced eyes or compressed eyes at both ends","At least ten turns of iron wire at both ends coated with rust proof grease","Both ends welded directly into a closed loop and checked by eye","Both ends sleeved in plastic tubing with a working load label attached"],
 "Article 102 lists the acceptable end terminations."),

(L,"第103條",1,"設施規則-起重升降機具",
 "起重升降機具設備及有關措施，除本節規定外，尚應依何者辦理？",
 ["其他相關職業安全衛生法規之規定","事業單位自訂之內部作業標準規定","製造廠商所附使用說明書之建議值","勞動檢查機構個案核定之替代方案"],"a",
 "第103條：起重升降機具設備及有關措施，除依本節之規定外，並應依其他相關職業安全衛生法規規定辦理。第113條就高壓氣體設備亦有相同體例之規定。",
 "Besides this section, what else governs lifting appliances?",
 ["Other relevant occupational safety and health regulations","Internal operating standards set by the enterprise itself","Recommended values in the makers instruction manual","Alternatives approved case by case by the inspection agency"],
 "Article 103 preserves the application of other OSH regulations."),

(L,"第104條",1,"設施規則-鍋爐壓力容器",
 "鍋爐及壓力容器之設備及有關措施，應依何種規則辦理？",
 ["鍋爐及壓力容器有關安全規則","起重升降機具有關安全規則","高壓氣體設備及容器安全規則","缺氧症預防規則之相關規定"],"a",
 "第104條：雇主對於鍋爐及壓力容器設備及有關措施，應依鍋爐及壓力容器有關安全規則之規定辦理。",
 "Which rules govern boilers and pressure vessels?",
 ["The safety rules on boilers and pressure vessels","The safety rules on lifting appliances and hoists","The safety rules on high pressure gas equipment","The rules on the prevention of oxygen deficiency"],
 "Article 104 refers to the boiler and pressure vessel safety rules."),

(L,"第105條",1,"設施規則-高壓氣體",
 "高壓氣體之製造、儲存、消費等，本規則規定應依何者辦理？",
 ["高壓氣體設備及容器有關安全規則","鍋爐及壓力容器有關安全規則","起重升降機具有關之安全規則","特定化學物質危害預防標準"],"a",
 "第105條：雇主對於高壓氣體之製造、儲存、消費等，應依高壓氣體設備及容器有關安全規則之規定辦理。",
 "Which rules govern the making, storage and use of high pressure gas?",
 ["The safety rules on high pressure gas equipment and containers","The safety rules on boilers and on pressure vessels in use","The safety rules on lifting appliances and hoisting gear","The standards on the prevention of specified chemical hazards"],
 "Article 105 refers to the high pressure gas equipment and container rules."),

(L,"第106條",2,"設施規則-高壓氣體",
 "使用儲存高壓氣體之容器，不論盛裝或空容器，下列辦理方式何者正確？",
 ["容器應標明所裝氣體品名，不得任意灌裝或轉裝，外表顏色不得擅自變更","容器外表顏色得由事業單位自行統一變更，以利現場辨識與管理","空容器因無殘壓之虞，得不予固定並任意橫置堆疊於通道旁邊","容器焊接前應先於容器本體上試焊，確認電流適當後再行施作"],"a",
 "第106條：確知容器用途無誤方得使用；應標明所裝氣體品名，不得任意灌裝或轉裝；外表顏色不得擅自變更或擦掉；使用時應加固定；搬動不得粗莽或衝擊；焊接時不得在容器上試焊。",
 "Which practice for high pressure gas containers is correct?",
 ["Mark the gas name, never refill or transfer freely, and never change the colour","The enterprise may repaint containers in its own colours for easier handling","Empty containers need no securing and may be stacked flat beside passages","Test welding may be done on the container body to check the current first"],
 "Article 106 forbids arbitrary refilling, colour changes and test welding on containers."),

(L,"第109條",2,"設施規則-高壓氣體",
 "高壓可燃性氣體之貯存，除一般貯存規定外，另有何特別要求？",
 ["電氣設備應採防爆型，不得帶用防爆型攜帶式電筒以外之燈火","電氣設備得採一般型，惟應加裝漏電斷路器並每月檢點一次","貯存處應置備吸收劑、中和劑及適用之防毒面罩或呼吸防護具","貯存處周圍五公尺內應設置圍籬，並由警衛人員全日看守之"],"a",
 "第109條：高壓可燃性氣體之貯存，除第108條規定外，電氣設備應採用防爆型，不得帶用防爆型攜帶式電筒以外之其他燈火，並應有適當之滅火機具。吸收劑、中和劑係第110條毒性高壓氣體之規定。",
 "What extra rule applies to storing flammable high pressure gas?",
 ["Explosion proof electrical equipment; no lamps except explosion proof torches","Ordinary electrical equipment with a leakage breaker checked once a month","Absorbents, neutralisers and suitable respirators must be kept at the store","A fence within five metres of the store guarded around the clock by security"],
 "Article 109 requires explosion proof equipment and suitable fire extinguishers."),

(L,"第110條",2,"設施規則-高壓氣體",
 "對於毒性高壓氣體之儲存，下列辦理方式何者符合本規則規定？",
 ["貯存處應置備吸收劑、中和劑及適用之防毒面罩或呼吸用防護具","貯存處得設於腐蝕性化學藥品或煙囪附近，以集中管理危險物","具腐蝕性之毒性氣體應密閉存放，並儘量減少換氣以避免擴散","容器溫度得保持在攝氏六十度以下，並每週測定溫度一次以上"],"a",
 "第110條：毒性高壓氣體之儲存，應於貯存處置備吸收劑、中和劑及適用之防毒面罩或呼吸用防護具；具腐蝕性之毒性氣體應充分換氣保持通風良好；不得在腐蝕化學藥品或煙囪附近貯藏；並預防異物混入。",
 "Which practice complies with the rule on storing toxic high pressure gas?",
 ["Absorbents, neutralisers and suitable respirators must be kept at the store","The store may sit near corrosive chemicals or chimneys to centralise risk","Corrosive toxic gases must be sealed with ventilation kept to a minimum","Containers may be kept below 60 degrees Celsius with weekly temperature checks"],
 "Article 110 requires absorbents, neutralisers and respiratory protection at the store."),

(L,"第111條",2,"設施規則-高壓氣體",
 "對於毒性高壓氣體之使用，下列規定何者正確？",
 ["非對該氣體有實地瞭解之人員不准進入，空氣中濃度不得超過容許濃度","經現場作業主管同意者，未受訓練人員亦得單獨進入使用場所","工作場所空氣中毒性氣體濃度得為容許濃度之二倍以下使用","使用場所得採密閉方式操作，不必保持通風良好之作業環境"],"a",
 "第111條：非對該氣體有實地瞭解之人員不准進入；工作場所空氣中之毒性氣體濃度不得超過容許濃度；應置備充分及適用之防護具；並保持通風良好。",
 "Which rule governs the use of toxic high pressure gas?",
 ["Only persons with practical knowledge may enter; concentration must stay below the limit","With the site supervisors consent, untrained persons may enter the area alone","Airborne concentration may reach up to twice the permissible exposure limit","The area may be operated fully closed without maintaining good ventilation"],
 "Article 111 restricts entry and caps airborne concentration at the permissible limit."),

(L,"第112條",1,"設施規則-高壓氣體",
 "對於高壓氣體之廢棄，本規則規定雇主應防止何種危害？",
 ["火災爆炸或中毒之危害","感電及被夾捲之危害","墜落及倒塌之危害者","高溫灼燙及凍傷危害"],"a",
 "第112條：雇主對於高壓氣體之廢棄，應防止火災爆炸或中毒之危害。第109條至第111條並就可燃性與毒性高壓氣體之貯存使用另有規定。",
 "What hazards must be prevented when disposing of high pressure gas?",
 ["Fire, explosion or poisoning hazards","Electric shock and entanglement hazards","Falling and structural collapse hazards","High temperature burn and frostbite risks"],
 "Article 112 targets fire, explosion and poisoning."),

(L,"第113條",1,"設施規則-高壓氣體",
 "有關高壓氣體設備及必要措施，除本節規定外尚應依何者辦理？",
 ["其他相關職業安全衛生法規之規定","高壓氣體容器製造廠商建議事項","事業單位報請備查之內部作業標準","當地消防機關核定之防火管理計畫"],"a",
 "第113條：有關高壓氣體設備及必要措施，除本節之規定外，並應依其他相關職業安全衛生法規規定辦理，與第103條起重升降機具之規定體例相同。",
 "Besides this section, what else applies to high pressure gas equipment?",
 ["Other relevant occupational safety and health regulations","Recommendations given by the container manufacturer","Internal standards filed by the enterprise for the record","A fire management plan approved by the local fire agency"],
 "Article 113 preserves other OSH regulations."),

(L,"第114條",1,"設施規則-車輛機械",
 "職業安全衛生設施規則第114條之現行條文內容為何？",
 ["本條業經刪除，現行規則並無規定內容","規定車輛機械應裝置名牌指出額定荷重","規定自設道路應能承受車輛機械之荷重","規定堆高機非置備後扶架者不得使用之"],"a",
 "第114條業經刪除。車輛機械之名牌標示規定見第115條，自設道路規定見第118條，堆高機後扶架規定見第124條。",
 "What does Article 114 of the Rules currently provide?",
 ["The article has been deleted and states no requirement","It requires vehicles to carry a plate showing rated load","It requires site roads to bear the load of the vehicles","It bars use of forklifts without a load backrest fitted"],
 "Article 114 has been deleted."),

(L,"第115條",2,"設施規則-車輛機械",
 "對於車輛機械，本規則就馬力、強度及標示有何規定？",
 ["應有足夠馬力及強度承受規定荷重，並裝置名牌指出空重、載重、額定荷重","應有足夠馬力及強度承受規定荷重，惟得免標示空重與額定荷重","應由製造廠商出具強度計算書，並免於機體上為任何之標示","應每半年測定其馬力一次，並將測定紀錄保存一年以上備查"],"a",
 "第115條：雇主對於車輛機械應有足夠之馬力及強度，承受其規定之荷重；並應裝置名牌或相等之標示指出空重、載重、額定荷重等。",
 "What does the rule require of vehicle type machines?",
 ["Enough power and strength for the load, plus a plate showing dead and rated loads","Enough power and strength for the load, but dead and rated loads need no marking","A strength calculation from the maker, with no marking required on the machine","Power output measured twice a year with records kept for at least one year"],
 "Article 115 requires a name plate showing dead weight, load and rated load."),

(L,"第118條",2,"設施規則-車輛機械",
 "對於勞工工作場所之自設道路，下列辦理方式何者符合本規則規定？",
 ["道路之邊緣及開口部分，應設置足以防止車輛機械翻落之設施","道路坡度得依現地條件放寬，縱有滑下可能亦得先行使用之","橋梁及涵洞非屬道路範圍，得免納入定期檢查之項目辦理","危險區域僅需於地面漆設標線，不必設標誌杆或防禦物者"],"a",
 "第118條：自設道路應能承受車輛機械之荷重；危險區應設標誌杆或防禦物；道路包括橋梁及涵洞應定期檢查；坡度須適當不得有滑下可能之斜度；應設行車安全設備；邊緣及開口部分應設防止翻落設施。",
 "Which practice complies with the rule on employer built site roads?",
 ["Road edges and openings must have facilities preventing vehicles from falling off","Gradients may be relaxed on site even where machines might slide down them","Bridges and culverts are outside the road and need no periodic inspection","Danger zones need only painted floor lines, not posts or protective barriers"],
 "Article 118 lists six requirements including fall prevention at edges and openings."),

(L,"第121條",2,"設施規則-車輛機械",
 "車輛系營建機械之修理或附屬裝置安裝、拆卸作業，應指定專人負責何事項？",
 ["決定作業順序並指揮作業，監視安全支柱、絞車等之使用狀況","決定作業順序並指揮作業，惟安全支柱之使用由勞工自行判斷","申請勞動檢查機構派員到場監督，並於作業後函報檢查結果","代為保管機械鑰匙，並於作業完成後填具自動檢查紀錄表件"],"a",
 "第121條：雇主對於車輛系營建機械之修理或附屬裝置之安裝、拆卸等作業時，應就該作業指定專人負責決定作業順序並指揮作業，及監視於機臂、突樑下作業之勞工所使用安全支柱、絞車等之狀況。",
 "What must the designated person do during repair of construction vehicles?",
 ["Decide the work sequence, direct the work, and watch safety props and winches","Decide the sequence and direct work, leaving prop use to the workers judgement","Ask the inspection agency to send an officer and report the result afterwards","Keep the machine key and fill in the self inspection form once work is done"],
 "Article 121 requires sequencing, direction and monitoring of safety props."),

(L,"第122條",2,"設施規則-車輛機械",
 "以自行行駛或牽引拖曳方式將車輛系營建機械裝卸於貨車時，應採何措施？",
 ["應於平坦堅固地點為之，道板須具足夠長寬強度並穩固固定於適當斜度","應於任何空地為之，道板僅需具足夠長度，斜度由駕駛人自行斟酌","應先卸除機械之制動裝置以利滑行，並由二人於兩側徒手扶持之","應以起重機吊掛方式裝卸，不得使用道板、填土或臨時架台方式"],"a",
 "第122條：裝卸時應選擇平坦堅固地點；使用道板應具足夠長度、寬度及強度，並穩固固定於適當之斜度；使用填土或臨時架台時，應確認具足夠寬度、強度並保持適當斜度。",
 "What measures apply when loading construction vehicles onto a truck?",
 ["Choose flat firm ground; ramps must be long, wide, strong and firmly fixed","Any open ground will do; only ramp length matters and the driver judges slope","Release the brakes first to help it slide, with two people steadying by hand","Loading must use a crane; ramps, earth fill and temporary stands are barred"],
 "Article 122 requires flat firm ground and properly fixed ramps."),

(L,"第123條",1,"設施規則-車輛機械",
 "職業安全衛生設施規則第123條之現行條文內容為何？",
 ["本條已刪除，目前並無任何規定之內容","規定堆高機托板應無顯著損傷或腐蝕者","規定荷重一公噸以上堆高機應由受訓者操作","規定車輛系營建機械應裝置前照燈具設備"],"a",
 "第123條業經刪除。堆高機托板規定見第125條，一公噸以上堆高機操作人員資格見第126條，前照燈具規定見第119條。",
 "What does Article 123 of the Rules currently provide?",
 ["The article is deleted and holds no provision at present","It requires forklift pallets to be free of damage or decay","It requires trained operators for forklifts of one tonne or more","It requires construction vehicles to be fitted with headlights"],
 "Article 123 has been deleted."),

(L,"第125條",2,"設施規則-堆高機",
 "雇主使用堆高機之托板或撬板時，本規則規定應符合何種條件？",
 ["具有充分能承受積載貨物重量之強度，且無顯著損傷、變形或腐蝕","具有承受積載貨物重量二分之一之強度，輕微變形者仍得使用","應為金屬材質製造，木質托板一律不得使用於任何堆高作業","應標示製造日期並於使用滿三年後一律汰換，不得繼續使用"],"a",
 "第125條：雇主使用堆高機之托板或撬板時，應具有充分能承受積載之貨物重量之強度，且無顯著之損傷、變形或腐蝕者。第126條並規定一公噸以上堆高機應由受特殊作業安全衛生教育訓練人員操作。",
 "What conditions must forklift pallets or skids meet?",
 ["Strength enough to bear the loaded goods, with no marked damage or decay","Strength of half the loaded weight, and slight deformation is acceptable","They must be metal; wooden pallets may never be used for stacking work","They must show a date of manufacture and be scrapped after three years"],
 "Article 125 requires adequate strength and freedom from notable damage."),
]
