# -*- coding: utf-8 -*-
# 第 12 批（H2）：應回收廢棄物回收處理業管理辦法（ENV-186）
#                毒性及關注化學物質災害事故應變車輛管理辦法（ENV-188）
A = "ENV-186"
B = "ENV-188"
Q = [

# ===== ENV-186 應回收廢棄物回收處理業管理辦法 =====
(A,"第1條",1,"回收處理業管理-授權依據",
 "應回收廢棄物回收處理業管理辦法係依據何項規定訂定？",
 ["依廢棄物清理法第十八條第三項及第四項規定訂定之",
  "依廢棄物清理法第十八條第六項及第七項規定訂定之",
  "依廢棄物清理法第十六條第四項及第五項規定訂定之",
  "依資源回收再利用法第十五條第三項及第四項訂定之"],"a",
 "第1條：本辦法依廢棄物清理法第十八條第三項及第四項規定訂定之。第5條並定回收業、處理業應向登記機關完成登記，始得從事應回收廢棄物回收、處理業務；第27條定本辦法自發布日施行。",
 "Which statutory provisions are the legal basis of these Regulations?",
 ["Article 18, paragraphs 3 and 4 of the Waste Disposal Act",
  "Article 18, paragraphs 6 and 7 of the Waste Disposal Act",
  "Article 16, paragraphs 4 and 5 of the Waste Disposal Act",
  "Article 15, paragraphs 3 and 4 of the Resource Recycling Act"],
 "Article 1."),

(A,"第2條",2,"回收處理業管理-適用對象",
 "本辦法之適用對象及其規模如何規定？",
 ["廢機動車輛回收業；前款以外其他應回收廢棄物回收業回收貯存廠（場）土地面積達一千平方公尺以上；應回收廢棄物處理業",
  "廢機動車輛回收業；前款以外其他應回收廢棄物回收業回收貯存廠土地面積達五百平方公尺以上；應回收廢棄物清除業",
  "廢電子電器回收業；前款以外其他應回收廢棄物回收業回收貯存廠土地面積達三千平方公尺以上；一般廢棄物處理業",
  "廢照明光源回收業；前款以外其他應回收廢棄物回收業回收貯存廠土地面積達一萬平方公尺以上；事業廢棄物處理業"],"a",
 "第2條：本辦法適用對象及規模為廢機動車輛回收業、前款以外其他應回收廢棄物回收業回收貯存廠（場）土地面積達一千平方公尺以上者，及應回收廢棄物處理業。第25條並定未達第2條規模之回收業得依其申請適用本辦法辦理登記及申報。",
 "Who is covered by these Regulations, and at what scale?",
 ["Scrap vehicle recovery operators; other recovery operators with a storage yard of 1,000 square metres or more; and recyclable waste treatment operators",
  "Scrap vehicle recovery operators; other recovery operators with a storage yard of 500 square metres or more; and recyclable waste clearance operators",
  "Waste appliance recovery operators; other recovery operators with a storage yard of 3,000 square metres or more; and general waste treatment operators",
  "Waste lighting recovery operators; other recovery operators with a storage yard of 10,000 square metres or more; and industrial waste treatment operators"],
 "Article 2."),

(A,"第3條",2,"回收處理業管理-回收業處理業定義",
 "本辦法所稱回收業與處理業之定義分別為何？",
 ["回收業指從事回收、清運、分類、壓縮、打包或貯存且無拆解行為者，但廢機動車輛回收業得從事拆解；處理業指以物理化學等方法達純化、精煉、分離、無害化或資源化，或輸出處理者",
  "回收業指從事收集、運輸並得自行拆解及破碎之業者，但廢機動車輛回收業不得拆解；處理業指僅從事分類、壓縮及打包，或將應回收廢棄物委託他人代為輸出國外處理之業者",
  "回收業指從事應回收廢棄物之稽核認證及補貼申請業務者，並得兼營拆解；處理業指從事再生料銷售及市場開發，或將應回收廢棄物運送至掩埋場最終處置之業者",
  "回收業指受地方主管機關委託辦理資源回收車清運之業者，不得拆解；處理業指設置焚化爐從事應回收廢棄物之熱處理，或將其轉為衍生燃料販售之業者"],"a",
 "第3條第1款：回收業指從事應回收廢棄物之回收、清運、分類、壓縮、打包或貯存業務，且無拆解行為者；但廢機動車輛回收業得從事拆解行為。第2款：處理業指以物理、化學或其他處理方法改變其物理化學特性，達純化、精煉、分離、無害化或資源化處理之行為，或輸出處理應回收廢棄物之業務者。",
 "How are recovery operators and treatment operators defined?",
 ["Recovery covers collection, haulage, sorting, compaction, baling or storage without dismantling, except scrap vehicle operators; treatment covers purifying, refining, separating, detoxifying or recycling, or export treatment",
  "Recovery covers collection and transport with dismantling and shredding allowed, except for scrap vehicle operators; treatment covers only sorting, compaction and baling, or contracting others to export the waste abroad",
  "Recovery covers audit certification and subsidy claim work and may include dismantling; treatment covers recycled material sales and market development, or hauling recyclable waste to landfill for disposal",
  "Recovery covers collection rounds contracted by local authorities without dismantling; treatment covers incineration of recyclable waste, or converting it into derived fuel for sale on the market"],
 "Article 3, subparagraphs 1 and 2."),

(A,"第3條",2,"回收處理業管理-處理效能定義",
 "本辦法所稱資源回收再利用比率與有害物質回收或去除比率之定義為何？",
 ["資源回收再利用比率指處理後產出再生料重量占處理總量之重量百分比；有害物質回收或去除比率指回收或去除之有害物質重量占所含有害物質總量之重量百分比",
  "資源回收再利用比率指處理後產出再生料售價占處理總成本之金額百分比；有害物質回收或去除比率指有害物質檢測合格件數占全年抽驗件數之數量百分比",
  "資源回收再利用比率指實際處理量占登記最大處理量之重量百分比；有害物質回收或去除比率指去除之有害物質體積占廠內廢水排放總量之容積百分比",
  "資源回收再利用比率指稽核認證量占年度目標回收量之數量百分比；有害物質回收或去除比率指有害物質貯存容器數量占全廠容器總數之數量百分比"],"a",
 "第3條第6款：資源回收再利用比率指應回收廢棄物經處理後產出之再生料重量，占處理應回收廢棄物總量之重量百分比。第7款：有害物質回收或去除比率指經處理後所回收或去除之有害物質重量，占處理應回收廢棄物所含有害物質總量之重量百分比。第5款並定處理效能即此二比率。",
 "How are the recycling ratio and the hazardous substance recovery or removal ratio defined?",
 ["Recycled material weight as a percentage of total waste treated; hazardous weight recovered or removed as a percentage of the hazardous content of the waste treated",
  "Recycled material sales value as a percentage of total treatment cost; test items passing as a percentage of all hazardous substance items sampled during the year",
  "Actual throughput as a percentage of the registered maximum capacity; hazardous volume removed as a percentage of total wastewater discharged from the plant",
  "Audited certified volume as a percentage of the annual target volume; hazardous storage containers as a percentage of all containers held across the whole plant"],
 "Article 3, subparagraphs 6 and 7."),

(A,"第4條",1,"回收處理業管理-登記機關",
 "本辦法所稱登記機關，就回收業與處理業分別為何？",
 ["回收業為貯存廠（場）所在地直轄市、縣（市）主管機關；處理業為處理廠（場）所在地直轄市、縣（市）主管機關",
  "回收業為機構登記所在地之中央主管機關；處理業為處理廠（場）所在地之直轄市、縣（市）主管機關轉陳中央核定",
  "回收業與處理業均為中央主管機關；地方主管機關僅負責受理申報及現場稽查，不得核發或撤銷其登記證",
  "回收業為負責人戶籍所在地主管機關；處理業為其主要再生料銷售對象所在地直轄市、縣（市）主管機關"],"a",
 "第4條：登記機關就回收業為貯存廠（場）所在地直轄市、縣（市）主管機關；就處理業為處理廠（場）所在地直轄市、縣（市）主管機關。第21條並定登記機關核准申請、變更、展延或撤銷、廢止登記時應副知中央主管機關。",
 "Which authority is the registration authority for recovery and for treatment operators?",
 ["For recovery operators, the municipal or county authority where the storage yard lies; for treatment operators, the authority where the treatment plant lies",
  "For recovery operators, the central authority where the entity is registered; for treatment operators, the local authority which refers the case to the centre",
  "For both recovery and treatment operators, the central authority; local authorities only receive filings and inspect, and cannot issue or revoke licences",
  "For recovery operators, the authority where the responsible person is domiciled; for treatment operators, where its main recycled material buyer is located"],
 "Article 4."),

(A,"第5條",1,"回收處理業管理-登記義務",
 "回收業、處理業從事應回收廢棄物回收、處理業務前，應完成何項程序？",
 ["應向登記機關完成登記，始得從事應回收廢棄物回收、處理業務",
  "應向中央主管機關報備營運計畫，即得從事回收、處理業務",
  "應向同業公會取得會員資格，始得從事回收、處理之業務",
  "應向目的事業主管機關取得許可，即可從事回收處理業務"],"a",
 "第5條：回收業、處理業應向登記機關完成登記，始得從事應回收廢棄物回收、處理業務。第4條並定登記機關為廠（場）所在地直轄市、縣（市）主管機關；第6條定申請、變更、展延登記及申報應以網路傳輸方式辦理。",
 "What must recovery and treatment operators complete before starting business?",
 ["They must complete registration with the registration authority before operating",
  "They must file an operating plan with the central authority before operating",
  "They must obtain membership of the relevant trade association before operating",
  "They must obtain a permit from the industry regulator before starting business"],
 "Article 5."),

(A,"第6條",1,"回收處理業管理-網路傳輸",
 "回收業、處理業辦理申請、變更、展延登記及申報作業之方式為何？",
 ["應依規定之格式、內容、頻率以網路傳輸方式辦理，但經中央主管機關同意以書面辦理及申報者不在此限",
  "應依規定之格式、內容以書面遞送方式辦理，但經地方主管機關同意以網路辦理及申報者不在此限",
  "應依同業公會規定之格式以電子郵件方式辦理，但經登記機關同意以掛號郵寄辦理者不在此限",
  "應依目的事業主管機關格式以傳真方式辦理，但經中央主管機關同意以口頭報備者不在此限"],"a",
 "第6條：回收業、處理業應依規定之格式、內容、頻率，以網路傳輸方式辦理申請、變更、展延登記及申報作業；但經中央主管機關同意以書面辦理及申報者，不在此限。第23條第2項並定應於每月十五日前依第6條規定申報前一個月營運情形。",
 "How must applications, changes, renewals and reporting be filed?",
 ["Online transmission in the prescribed format, content and frequency, unless the central authority consents to paper filing and reporting",
  "Paper delivery in the prescribed format and content, unless the local authority consents to online filing and reporting instead",
  "Email in the format set by the trade association, unless the registration authority consents to filing by registered mail",
  "Fax in the format set by the industry regulator, unless the central authority consents to reporting verbally"],
 "Article 6."),

(A,"第7條",2,"回收處理業管理-回收業申請文件",
 "回收業申請登記時，應檢具之文件包括下列何者？",
 ["土地合法使用證明文件、回收項目及最大貯存量說明、分類壓縮打包方法及設施說明、緊急應變措施計畫、廠（場）區周圍二公里範圍內之相關位置圖",
  "土地合法使用證明文件、處理流程及處理設備說明、處理效能及質量平衡說明、試運轉計畫書、廠（場）區周圍五公里範圍內之相關位置圖",
  "工廠登記證及水權狀、資本額查核簽證報告、勞工安全衛生管理計畫、公共意外責任保險單、廠區周圍一公里範圍內之空氣品質檢測報告",
  "環境影響評估審查結論、土壤及地下水品質背景調查報告、專責人員合格證書、廠區周圍十公里範圍內之地下水監測井分布位置圖"],"a",
 "第7條各款：回收業申請登記應檢具申請表、政府機關核准設立證明、土地合法使用證明、回收項目及最大貯存量說明、分類壓縮打包方法及設施說明、貯存方法及設施說明、廢機動車輛拆解作業流程（如從事拆解）、污染防制（治）措施說明、廠（場）區配置圖、緊急應變措施計畫、清理計畫及廠（場）區周圍二公里範圍內相關位置圖。",
 "Which documents must a recovery operator file when applying for registration?",
 ["Lawful land use proof, recovery items and maximum storage capacity, sorting and baling methods and facilities, an emergency response plan, and a site map covering 2 km around",
  "Lawful land use proof, treatment flow and equipment documents, treatment performance and mass balance, a trial run plan, and a site map covering 5 km around the plant site",
  "Factory registration and water rights, capital verification reports, an occupational safety plan, liability insurance, and an air quality report for 1 km around",
  "EIA review conclusions, soil and groundwater background survey reports, certificates for dedicated personnel, and a monitoring well map covering 10 km around"],
 "Article 7."),

(A,"第8條",2,"回收處理業管理-處理業設置",
 "處理業申請登記分為哪二階段？其設置階段之審查與效果為何？",
 ["分為設置及試運轉二階段；應先檢具申請表、核准設立證明、土地合法使用證明、設置計畫書及周圍二公里位置圖送登記機關審查核准設置後，始得進行處理設施建造、裝置",
  "分為試運轉及正式營運二階段；應先檢具申請表、環評結論、消防查驗證明及營運計畫書送中央主管機關審查核准後，始得進行處理設施之建造與裝置作業",
  "分為登記及展延二階段；應先檢具申請表、稽核認證量證明、財務報表及再生料銷售合約送登記機關審查核准後，始得進行處理設施之建造與裝置",
  "分為勘查及認證二階段；應先檢具申請表、技師簽證報告、專責人員名冊及保險單送目的事業主管機關核准後，始得進行處理設施建造、裝置"],"a",
 "第8條：處理業申請登記分為設置及試運轉二階段；其應先檢具申請表及政府機關核准設立證明文件、土地合法使用證明文件、設置計畫書（含處理項目及最大處理量、處理流程及設備、產出物種類及去化方式、貯存方法及設施、處理效能及質量平衡、污染防制措施、廠區配置圖、緊急應變計畫、清理計畫）、廠（場）區周圍二公里範圍內相關位置圖等，送登記機關審查核准設置後，始得進行處理設施建造、裝置。",
 "What two stages apply to treatment operator registration, and what does the setup stage require?",
 ["Setup and trial run; an application, establishment proof, lawful land use proof, a setup plan and a 2 km site map must be approved by the registration authority before construction begins",
  "Trial run and formal operation; an application, EIA conclusions, fire inspection certificates and an operating plan must be approved by the central authority before construction begins",
  "Registration and renewal; an application, audited volume proof, financial statements and material sales contracts must be approved by the registration authority before construction",
  "Inspection and certification; an application, engineer certification reports, personnel rosters and insurance policies must be approved by the industry regulator before construction"],
 "Article 8."),

(A,"第9條",2,"回收處理業管理-設置有效期限",
 "處理業核准設置之有效期限為何？得否申請展延？",
 ["核准設置之有效期限為三年；期限屆滿前得檢具展延原因說明文件申請展延設置，以一次為限，核准之有效期限以一年為限",
  "核准設置之有效期限為五年；期限屆滿前得檢具展延原因說明文件申請展延設置，以二次為限，每次核准之有效期限為三年",
  "核准設置之有效期限為一年；期限屆滿前得檢具展延原因說明文件申請展延設置，不限次數，每次核准期限均為六個月",
  "核准設置之有效期限為十年；期限屆滿前得檢具展延原因說明文件申請展延設置，以三次為限，每次核准期限為五年"],"a",
 "第9條：處理業核准設置之有效期限為三年；有效期限屆滿前，得檢具展延原因說明文件申請展延設置，以一次為限，其核准之有效期限以一年為限。第10條第4項並定試運轉期間以三個月為限，得申請展延一次三個月。",
 "How long is the approval for a treatment plant's setup valid, and may it be extended?",
 ["Valid for three years; one extension may be sought before expiry, and the extended period is limited to one year",
  "Valid for five years; up to two extensions may be sought before expiry, each extended period being three years",
  "Valid for one year; extensions may be sought without limit before expiry, each extended period being six months",
  "Valid for ten years; up to three extensions may be sought before expiry, each extended period being five years"],
 "Article 9."),

(A,"第10條",2,"回收處理業管理-試運轉申請",
 "處理業於設置完成後進行試運轉前，應檢具之試運轉計畫書應包括哪些內容？",
 ["試運轉期間、方式、程序、步驟；試運轉之應回收廢棄物項目、數量；產出再生料及其他廢棄物種類、最大產出量及去化方式與合約；採樣、檢測計畫",
  "試運轉期間之營業額預估；試運轉之再生料銷售對象及單價；產出廢棄物之掩埋場地點、掩埋量及費用；員工訓練與勞工保險投保計畫",
  "試運轉期間之用電度數及水量；試運轉之補貼費請領金額；產出再生料之外銷國家、報關文件及運費；廠區消防演練與疏散計畫",
  "試運轉期間之董事會決議紀錄；試運轉之土地租賃契約；產出廢棄物之保險理賠條款、賠償額度及責任分擔；公司財務簽證報告"],"a",
 "第10條第1項第2款：試運轉計畫書應包括試運轉期間、方式、程序、步驟；試運轉之應回收廢棄物項目、數量；試運轉後產出之再生料及其他廢棄物之種類及最大產出量說明，與其再利用、再生利用或處理方式及委託之合約或證明文件；採樣、檢測計畫。第3項並定試運轉計畫執行結果應做成試運轉報告，於登記機關准駁登記前提送。",
 "What must a treatment operator's trial run plan contain?",
 ["The trial period, methods, procedures and steps; the waste items and volumes used; the types, maximum output and disposal routes of products with contracts; and a sampling and testing plan",
  "The projected turnover for the trial period; buyers and unit prices of recycled material; the landfill site, volume and fees for residues; and staff training and insurance plans",
  "Electricity and water use during the trial; the subsidy amount to be claimed; export destinations, customs papers and freight for material; and fire drill and evacuation plans",
  "Board resolutions covering the trial period; the land lease contract; insurance clauses, indemnity limits and liability sharing for residues; and audited financial statements"],
 "Article 10, paragraph 1, subparagraph 2, and paragraph 3."),

(A,"第10條",2,"回收處理業管理-試運轉期限",
 "非經登記機關同意，處理業之試運轉期間以多久為限？得否展延？",
 ["試運轉期間以三個月為限；期限屆滿前得檢具原因說明文件申請展延，以一次為限，其期限以三個月為限",
  "試運轉期間以六個月為限；期限屆滿前得檢具原因說明文件申請展延，以二次為限，每次期限為六個月",
  "試運轉期間以一年為限；期限屆滿前得檢具原因說明文件申請展延，不限次數，每次期限均為三個月",
  "試運轉期間以一個月為限；期限屆滿前得檢具原因說明文件申請展延，以三次為限，每次期限為一個月"],"a",
 "第10條第4項：非經登記機關同意，試運轉期間以三個月為限；處理業於試運轉期限屆滿前，得檢具原因說明文件申請展延，以一次為限，其期限以三個月為限。第3項並定試運轉報告應於登記機關准駁登記前提送。",
 "Unless the authority consents otherwise, how long may a trial run last, and may it be extended?",
 ["The trial run is limited to three months; one extension may be sought before expiry, limited to a further three months",
  "The trial run is limited to six months; up to two extensions may be sought before expiry, each of a further six months",
  "The trial run is limited to one year; extensions may be sought without limit before expiry, each of a further three months",
  "The trial run is limited to one month; up to three extensions may be sought before expiry, each of a further one month"],
 "Article 10, paragraph 4."),

(A,"第11條",2,"回收處理業管理-輸出處理登記",
 "處理業採輸出國外處理者，申請登記時應檢具之文件與一般處理業有何不同？",
 ["應檢具輸出處理項目及其最大貯存量說明、分類作業說明文件、貯存方法及設施說明，而非處理流程、處理設備及處理效能質量平衡等文件",
  "應檢具處理流程及處理設備說明、處理效能及質量平衡說明，並另加附輸出目的國之處理廠許可文件及國際貿易主管機關核准函",
  "應檢具設置計畫書及試運轉計畫書，並免附土地合法使用證明、緊急應變措施計畫及廠（場）區周圍二公里範圍內相關位置圖",
  "應檢具稽核認證設施說明及實廠運轉報告，並免附政府機關核准設立證明文件、污染防制措施說明及廠（場）區配置圖"],"a",
 "第11條：處理業採輸出國外處理者，申請登記應檢具申請表、政府機關核准設立證明、土地合法使用證明、輸出處理項目及其最大貯存量說明、分類作業說明、貯存方法及設施說明、污染防制（治）措施說明、廠（場）區配置圖、緊急應變措施計畫、清理計畫及廠（場）區周圍二公里範圍內相關位置圖，並無處理流程、設備及處理效能質量平衡等文件。",
 "How do the registration documents differ for operators exporting waste for treatment?",
 ["They file export items and maximum storage capacity, sorting operation documents and storage methods, rather than treatment flow, equipment and performance and mass balance documents",
  "They file treatment flow and equipment plus performance and mass balance documents, and additionally the destination country's plant permit and trade authority approval",
  "They file a setup plan and a trial run plan instead, and are exempt from lawful land use proof, emergency response plans and the 2 km surrounding site location map",
  "They file audit facility descriptions and full-scale run reports, and are exempt from government establishment certificates, pollution control statements and plant layout drawings"],
 "Article 11."),

(A,"第12條",1,"回收處理業管理-登記證記載",
 "回收業、處理業登記證應記載之事項包括下列何者？",
 ["登記證字號、機構名稱及地址、廠（場）名稱及地址、負責人姓名、核准登記日期及有效日期、業別及回收處理項目、廠（場）地號",
  "登記證字號、機構資本額及股東名冊、廠（場）建物樓層數、專責人員姓名、投保金額及保險期間、稽核認證量、廠區用電契約容量",
  "登記證字號、機構統一編號及稅籍編號、廠（場）土地公告現值、會計師姓名、財務報表年度、再生料銷售額、廠區周圍地籍圖",
  "登記證字號、機構員工人數及薪資總額、廠（場）消防設備清冊、技師姓名、環評審查文號、補貼費率、廠區污水排放許可號"],"a",
 "第12條：回收業、處理業登記證應記載登記證字號、機構名稱及地址、廠（場）名稱及地址、負責人姓名、核准登記日期及有效日期、回收業或處理業業別及回收、處理項目、回收貯存廠（場）或處理廠（場）地號。第20條第1項第1款並定登記證應記載事項有虛偽不實者得撤銷、註銷或廢止其登記證。",
 "What must be recorded on a recovery or treatment operator's registration certificate?",
 ["Certificate number, entity name and address, plant name and address, responsible person, approval and expiry dates, category and items, and the plant land parcel number",
  "Certificate number, capital and shareholder roster, number of storeys, dedicated personnel, insured amount and period, audited volume, and the contracted electricity capacity",
  "Certificate number, tax ID and tax file number, land announced value, accountant's name, financial statement year, recycled material sales, and the cadastral map around",
  "Certificate number, headcount and total payroll, fire equipment inventory, engineer's name, EIA reference number, subsidy rate, and the wastewater discharge permit number"],
 "Article 12."),

(A,"第13條",2,"回收處理業管理-回收業變更",
 "回收業申請變更登記，各款應於何時辦理？",
 ["機構名稱地址、負責人姓名及廠（場）地址地號變更者，於變更後十五日內辦理；土地面積、回收項目、分類貯存方法設施、新增拆解及污染防制措施變更者，應於變更前辦理",
  "機構名稱地址、負責人姓名及廠（場）地址地號變更者，於變更前十五日辦理；土地面積、回收項目、分類貯存方法設施、新增拆解及污染防制措施變更者，於變更後三十日內辦理",
  "機構名稱地址、負責人姓名及廠（場）地址地號變更者，於變更後六十日內辦理；土地面積、回收項目、分類貯存方法設施、新增拆解及污染防制措施變更者，於次年度一併辦理",
  "機構名稱地址、負責人姓名及廠（場）地址地號變更者，於年度終了時辦理；土地面積、回收項目、分類貯存方法設施、新增拆解及污染防制措施變更者，於變更後六個月內辦理"],"a",
 "第13條第2項：第1項第1款（機構名稱及地址、負責人姓名）及第2款（回收貯存廠場地址或地號）變更者，應於變更後十五日內檢具證明文件向登記機關辦理；第3款至第8款（土地面積、回收項目及最大貯存量、分類壓縮打包方法及設施、貯存方法及設施、新增從事廢機動車輛拆解、污染防制措施）變更者，應於變更前檢具相關文件辦理。",
 "When must a recovery operator apply for change registration for each item?",
 ["Entity name and address, responsible person, and plant address or parcel changes within 15 days after; land area, items, sorting and storage methods, new dismantling and pollution control changes before the change",
  "Entity name and address, responsible person, and plant address or parcel changes 15 days before; land area, items, sorting and storage methods, new dismantling and pollution control changes within 30 days after",
  "Entity name and address, responsible person, and plant address or parcel changes within 60 days after; land area, items, sorting and storage methods, new dismantling and pollution control changes in the following year",
  "Entity name and address, responsible person, and plant address or parcel changes at the year end; land area, items, sorting and storage methods, new dismantling and pollution control changes within six months after"],
 "Article 13, paragraphs 1 and 2."),

(A,"第14條",2,"回收處理業管理-處理業變更",
 "處理業應申請變更登記之情形及辦理時點為何？",
 ["處理廠土地面積、處理項目最大處理量、處理流程設備、污染防制措施、產出物種類及去化方式、貯存方法設施、廠區配置變更者，均應於變更前檢具相關文件向登記機關辦理",
  "處理廠土地面積、處理項目最大處理量、處理流程設備、污染防制措施、產出物種類及去化方式、貯存方法設施、廠區配置變更者，均應於變更後三十日內向中央主管機關辦理",
  "處理廠土地面積、處理項目最大處理量、處理流程設備、污染防制措施、產出物種類及去化方式、貯存方法設施、廠區配置變更者，均免辦理變更而僅需併入季報表申報",
  "處理廠土地面積、處理項目最大處理量、處理流程設備、污染防制措施、產出物種類及去化方式、貯存方法設施、廠區配置變更者，均應於變更後六個月內向目的事業主管機關辦理"],"a",
 "第14條第2項：第1項第1款（機構名稱及地址、負責人姓名）及第2款（處理廠場地址或地號）變更者，應於變更後十五日內辦理；第3款至第9款（處理廠土地面積、處理項目及最大處理量或輸出項目最大貯存量、處理流程及設備、污染防制措施、產出物種類最大產出量及去化方式、貯存方法及設施、廠場區配置）變更者，應於變更前檢具相關文件向登記機關辦理。",
 "Which treatment operator changes need registration, and when must they be filed?",
 ["Changes to plant land area, items and maximum capacity, treatment flow and equipment, pollution control, output types and routes, storage methods and plant layout must all be filed before the change",
  "Changes to plant land area, items and maximum capacity, treatment flow and equipment, pollution control, output types and routes, storage methods and plant layout must be filed centrally within 30 days",
  "Changes to plant land area, items and maximum capacity, treatment flow and equipment, pollution control, output types and routes, storage methods and plant layout need no filing, only quarterly reporting",
  "Changes to plant land area, items and maximum capacity, treatment flow and equipment, pollution control, output types and routes, storage methods and plant layout must be filed within six months"],
 "Article 14, paragraphs 1 and 2."),

(A,"第15條",2,"回收處理業管理-登記證展延",
 "回收業、處理業登記證之有效期限為何？應於何時申請展延？",
 ["登記證有效期限為五年；有效期限屆滿後仍繼續從事原登記項目業務者，應於屆滿前三個月至六個月內申請展延，每次展延之有效期限為五年",
  "登記證有效期限為三年；有效期限屆滿後仍繼續從事原登記項目業務者，應於屆滿前一個月至三個月內申請展延，每次展延之有效期限為三年",
  "登記證有效期限為十年；有效期限屆滿後仍繼續從事原登記項目業務者，應於屆滿前六個月至一年內申請展延，每次展延之有效期限為十年",
  "登記證有效期限為二年；有效期限屆滿後仍繼續從事原登記項目業務者，應於屆滿後三個月內補行申請展延，每次展延有效期限為二年"],"a",
 "第15條第1項：回收業、處理業登記證有效期限為五年；有效期限屆滿後仍繼續從事原登記項目之業務者，應於屆滿前三個月至六個月內申請展延，每次展延之有效期限為五年。第19條第6項並定登記機關受理展延應審酌其營運期間環保稽查取締紀錄及環境品質變異情形。",
 "How long is a registration certificate valid, and when must renewal be sought?",
 ["Valid for five years; those continuing the registered business must apply between three and six months before expiry, and each renewal runs for five years",
  "Valid for three years; those continuing the registered business must apply between one and three months before expiry, and each renewal runs for three years",
  "Valid for ten years; those continuing the registered business must apply between six and twelve months before expiry, and each renewal runs for ten years",
  "Valid for two years; those continuing the registered business may apply within three months after expiry, and each renewal runs for two years thereafter"],
 "Article 15, paragraph 1."),

(A,"第15條",3,"回收處理業管理-未展延效果",
 "回收業、處理業展延文件不符規定或未依期間申請展延者，其效果為何？",
 ["文件不符或補正逾期者，登記機關應於有效期限屆滿前駁回；未依規定期間申請而尚未准駁者，應於期限屆滿日起停止營運；未於屆滿前申請展延者，登記證自屆滿日起失其效力",
  "文件不符或補正逾期者，登記機關應通知限期改善並得延長效期；未依規定期間申請而尚未准駁者，得繼續營運至准駁作成日止；未於屆滿前申請者，登記證自動延展一年",
  "文件不符或補正逾期者，登記機關應移請中央主管機關核定；未依規定期間申請而尚未准駁者，應於准駁後三個月停止營運；未於屆滿前申請者，登記證得於屆滿後補辦展延",
  "文件不符或補正逾期者，登記機關得逕行縮短其有效期限；未依規定期間申請而尚未准駁者，應暫停收受應回收廢棄物；未於屆滿前申請者，登記證由中央主管機關註銷"],"a",
 "第15條第2項：申請展延文件不符規定或補正資料未能於登記機關規定期限內補正者，登記機關應於登記證有效期限屆滿前駁回其申請；未依前項規定期間申請展延者，登記機關尚未作成准駁之決定時，應於登記證有效期限屆滿日起停止營運；未於登記證有效期限屆滿前申請展延者，於有效期限屆滿日起，其登記證失其效力。",
 "What follows if renewal documents are deficient or renewal is not sought in time?",
 ["Deficient or uncorrected filings are rejected before expiry; where a late application is undecided, operations must stop from the expiry date; certificates not renewed before expiry lose effect from that date",
  "Deficient or uncorrected filings trigger an improvement notice and an extended term; where a late application is undecided, operations may continue until a decision; unrenewed certificates run on for one year",
  "Deficient or uncorrected filings are referred to the central authority; where a late application is undecided, operations must stop three months after a decision; renewal may be sought after expiry",
  "Deficient or uncorrected filings let the authority shorten the term directly; where a late application is undecided, waste intake must pause; unrenewed certificates are cancelled by the central authority"],
 "Article 15, paragraph 2."),

(A,"第16條",1,"回收處理業管理-回收業展延文件",
 "回收業申請展延登記時，應檢具之文件包括下列何者？",
 ["回收項目及其最大貯存量說明、分類壓縮打包方法及設施說明、貯存方法及設施說明、污染防制（治）措施說明、廠（場）區配置圖、緊急應變措施計畫及清理計畫",
  "設置計畫書及試運轉計畫書、採樣檢測計畫、實廠運轉報告、稽核認證設施運作方式說明、廠（場）區周圍二公里範圍內相關位置圖及土地合法使用證明",
  "近三年財務報表及納稅證明、股東名冊、董事會議事錄、員工在職證明、公共意外責任保險單、消防安全設備檢修申報表及建築物使用執照",
  "環境影響評估審查結論、水污染防治許可證、空氣污染防制設備操作許可證、廢棄物清理計畫書、土壤及地下水品質檢測報告及專責人員名冊"],"a",
 "第16條各款：回收業申請展延登記應檢具申請表及政府機關核准設立證明、回收項目及其最大貯存量說明、分類壓縮打包方法及設施說明、貯存方法及設施說明、廢機動車輛回收業從事拆解者之拆解作業流程說明、污染防制（治）措施說明、廠（場）區配置圖及說明、緊急應變措施計畫、清理計畫及其他經中央主管機關規定之文件。",
 "Which documents must a recovery operator file when seeking renewal of registration?",
 ["Recovery items and maximum storage capacity, sorting and baling methods and facilities, storage methods and facilities, pollution control measures, layout drawings, an emergency plan and a clearance plan",
  "A setup plan and a trial run plan, sampling and testing plans, full-scale run reports, audit facility operation documents, a 2 km surrounding location map and lawful land use proof papers",
  "Three years of financial statements and tax payment certificates, shareholder rosters, board minutes, employment certificates, liability insurance policies, fire inspection filings and building use permits",
  "EIA review conclusions, water pollution control permits, air pollution control equipment operating permits, waste clearance plans, soil and groundwater test reports and dedicated personnel rosters"],
 "Article 16."),

(A,"第17條",2,"回收處理業管理-處理業展延文件",
 "處理業申請展延登記時，應檢具之文件包括下列何者？",
 ["處理項目及最大處理量說明、處理流程及處理設備說明、產出再生料及其他廢棄物種類最大產出量與去化合約、貯存方法及設施說明、處理效能及質量平衡說明",
  "回收項目及最大貯存量說明、分類壓縮打包方法及設施說明、廢機動車輛拆解作業流程說明、貯存方法及設施說明、稽核認證作業區域配置圖及說明文件",
  "設置計畫書及核准設置文件、試運轉期間用電紀錄、試運轉採樣檢測報告、輸出目的國處理廠許可文件、國際貿易主管機關核准函及報關文件",
  "近五年營運統計季報表、補貼費請領明細、再生料銷售發票、廠區土地公告現值證明、地價稅完納證明及建築物公共安全檢查簽證申報書"],"a",
 "第17條各款：處理業申請展延登記應檢具申請表及政府機關核准設立證明、處理項目及最大處理量說明、處理流程及處理設備說明、產出再生料及其他廢棄物之種類及最大產出量說明與委託再利用、再生利用或處理之合約或證明文件、貯存方法及設施說明、處理效能及質量平衡說明、污染防制措施說明、廠（場）區配置圖、緊急應變措施計畫及清理計畫等。",
 "Which documents must a treatment operator file when seeking renewal of registration?",
 ["Treatment items and maximum capacity, treatment flow and equipment, output types and maximum output with disposal contracts, storage methods and facilities, and performance and mass balance documents",
  "Recovery items and maximum storage capacity, sorting and baling methods and facilities, scrap vehicle dismantling flow documents, storage methods and facilities, and audit area layout drawings",
  "The setup plan and setup approval, electricity records during the trial run, trial sampling and test reports, the destination plant permit, trade authority approval and customs papers",
  "Five years of quarterly operating statistics, subsidy claim details, recycled material sales invoices, land value certificates, land tax receipts and building safety inspection filings"],
 "Article 17."),

(A,"第18條",2,"回收處理業管理-輸出展延文件",
 "處理業採輸出國外處理者，申請展延登記時應檢具之文件包括下列何者？",
 ["輸出處理項目及其最大貯存量說明、分類作業說明文件、貯存方法及設施說明、污染防制（治）措施說明、廠（場）區配置圖、緊急應變措施計畫及清理計畫",
  "處理流程及處理設備說明、處理效能及質量平衡說明、實廠運轉計畫及報告、採樣檢測計畫、稽核認證設施運作方式說明及廠區配置圖說明文件",
  "土地合法使用證明及地籍圖謄本、建築物使用執照、消防安全設備檢查表、公共意外責任保險單、勞工安全衛生管理計畫及員工訓練紀錄表",
  "輸出目的國之環保主管機關核准函、國際運輸業者契約、海關報單影本、再生料買賣合約、外匯結匯水單及貿易主管機關輸出許可證明"],"a",
 "第18條各款：處理業採輸出國外處理者申請展延登記，應檢具申請表及政府機關核准設立證明、輸出處理項目及其最大貯存量說明、分類作業說明文件、貯存方法及設施說明、污染防制（治）措施說明、廠（場）區配置圖及說明、緊急應變措施計畫、清理計畫及其他經中央主管機關規定之文件。",
 "Which documents must an exporting treatment operator file when seeking renewal?",
 ["Export items and maximum storage capacity, sorting operation documents, storage methods and facilities, pollution control measures, layout drawings, an emergency plan and a clearance plan",
  "Treatment flow and equipment documents, performance and mass balance documents, full-scale run plans and reports, sampling and testing plans, audit facility documents and layout drawings",
  "Lawful land use proof and cadastral transcripts, building use permits, fire equipment checklists, public liability insurance, occupational safety plans and staff training records",
  "The destination country's environmental approval letter, international carrier contracts, customs declarations, sales contracts, foreign exchange slips and trade export licences"],
 "Article 18."),

(A,"第19條",2,"回收處理業管理-審查期限",
 "登記機關受理回收業、處理業申請登記、變更登記及展延登記，其審查期限為何？",
 ["應辦理現場勘查者於六十日內完成審查，未辦理現場勘查者於三十日內完成審查並作成准駁決定；必要時或因業者正當事由得延長，延長期間以三十日為限",
  "應辦理現場勘查者於九十日內完成審查，未辦理現場勘查者於六十日內完成審查並作成准駁決定；必要時或因業者正當事由得延長，延長期間以六十日為限",
  "應辦理現場勘查者於三十日內完成審查，未辦理現場勘查者於十五日內完成審查並作成准駁決定；必要時或因業者正當事由得延長，延長期間以十五日為限",
  "應辦理現場勘查者於一百二十日內完成審查，未辦理現場勘查者於九十日內完成審查並作成准駁決定；不得因任何事由延長其法定之審查期限"],"a",
 "第19條第1項：應辦理現場勘查者應於六十日內完成審查，未辦理現場勘查者應於三十日內完成審查並做成准駁之決定。第2項：登記機關認為必要時或因業者提出正當事由，得延長審查期限，延長期間以三十日為限。第3、4項並定內容欠缺或現勘不符者應通知限期補正，屆期未補正者駁回，補正日數不算入審查期限。",
 "What review deadlines apply to registration, change and renewal applications?",
 ["60 days where a site inspection is required and 30 days where it is not, with a decision made; an extension of up to 30 days is allowed where needed or on justified grounds",
  "90 days where a site inspection is required and 60 days where it is not, with a decision made; an extension of up to 60 days is allowed where needed or on justified grounds",
  "30 days where a site inspection is required and 15 days where it is not, with a decision made; an extension of up to 15 days is allowed where needed or on justified grounds",
  "120 days where a site inspection is required and 90 days where it is not, with a decision made; no extension of the statutory review period is permitted on any ground"],
 "Article 19, paragraphs 1 to 4."),

(A,"第19條",3,"回收處理業管理-現場勘查",
 "登記機關辦理現場勘查之規定為何？",
 ["受理回收業登記、變更、展延及處理業變更登記，必要時得辦理現場勘查；受理處理業登記及展延登記應辦理現場勘查，受補貼機構之處理業展延得免辦，但處理含有害物質者展延仍應辦理",
  "受理回收業登記、變更、展延及處理業變更登記，一律應辦理現場勘查；受理處理業登記及展延登記則採書面審查，受補貼機構之處理業展延必要時得辦理現場勘查即可",
  "受理回收業登記、變更、展延及處理業變更登記，均免辦理現場勘查；受理處理業登記及展延登記由中央主管機關統一辦理現場勘查，地方機關不得自行辦理",
  "受理回收業登記、變更、展延及處理業變更登記，得委託同業公會辦理現場勘查；受理處理業登記及展延登記應由技師簽證代替現場勘查，不再另行辦理勘查"],"a",
 "第19條第5項：登記機關受理回收業申請登記、變更登記、展延登記及處理業之變更登記，必要時得辦理現場勘查；受理處理業登記及展延登記，應辦理現場勘查，受理受補貼機構之處理業展延登記，得免辦理現場勘查；但受理處理含有害物質成分之應回收廢棄物處理業展延登記，應辦理現場勘查。第6項並定展延應審酌環保稽查取締紀錄。",
 "When must the registration authority carry out an on-site inspection?",
 ["Recovery registrations, changes and renewals and treatment changes may be inspected if needed; treatment registrations and renewals must be inspected, subsidised operators' renewals may be exempt, but hazardous ones must be inspected",
  "Recovery registrations, changes and renewals and treatment changes must always be inspected on site; treatment registrations and renewals are reviewed on paper, and subsidised operators' renewals may be inspected where needed",
  "Recovery registrations, changes and renewals and treatment changes need no inspection at all; treatment registrations and renewals are inspected only by the central authority and never by local ones",
  "Recovery registrations, changes and renewals and treatment changes may be inspected by trade associations; treatment registrations and renewals use engineer certification in place of any on-site inspection"],
 "Article 19, paragraphs 5 and 6."),

(A,"第20條",3,"回收處理業管理-撤銷廢止",
 "登記機關得依職權撤銷、註銷或廢止其登記證或回收、處理項目之情形，包括下列何者？",
 ["登記證應記載事項虛偽不實、營業行為受勒令歇業處分、未依規定辦理變更經通知限期辦理屆期未辦、廠（場）址遷移、連續二季未申報營運統計季報表經通知限期申報屆期未報",
  "登記證污損毀壞未申請換發、營業額連續二年下滑逾三成、未依規定辦理變更經通知即予撤銷、廠（場）址擴建、連續二年未申報營運統計年報表經通知限期申報屆期未報",
  "登記證有效期限即將屆滿、未參加中央主管機關講習訓練、未依規定投保公共意外責任保險、廠（場）址設於工業區外、連續二月未提送再生料銷售明細表及發票影本",
  "登記證持有人變更負責人姓名、未設置環保專責人員、未依規定辦理員工健康檢查、廠（場）址面積縮減、連續二年未達中央主管機關公告之年度回收量目標值者"],"a",
 "第20條第1項：登記證記載虛偽不實、營業行為違法受勒令歇業處分、登記文件不實、未依本辦法辦理變更經通知限期辦理屆期仍未辦理、廠（場）址遷移、登記後連續二季未申報營運統計季報表經通知限期申報屆期仍未申報、登記後滿六個月尚未開始營業或開始營業後自行停業六個月以上、項目經廢止公告、自行申請廢止、依土污法認定為污染行為人、未依第24條辦理、其他違反情節重大者，得撤銷、註銷或廢止登記證或項目。",
 "Which grounds allow the authority to revoke or cancel a registration certificate or items?",
 ["False particulars on the certificate, an order to cease business, failure to file changes after a deadline notice, relocation of the plant, and two straight quarters without statistics filings after notice",
  "A damaged certificate not replaced, turnover falling over 30 per cent in two years, revocation immediately upon a change notice, plant expansion, and two years without annual statistics filings after notice",
  "A certificate nearing expiry, failure to attend central authority training, lack of public liability insurance, a plant sited outside an industrial zone, and two months without sales schedules and invoices",
  "A change in the responsible person's name, no dedicated environmental personnel, no staff health checks, a reduction in plant area, and two years below the announced annual recovery volume target"],
 "Article 20, paragraph 1."),

(A,"第21條",1,"回收處理業管理-副知中央",
 "登記機關核准或撤銷、廢止登記，或註銷登記證時，應辦理何項程序？",
 ["應副知中央主管機關",
  "應副知目的事業主管機關",
  "應公告於機關網站三十日",
  "應報請行政院核定後實施"],"a",
 "第21條：登記機關於核准回收業、處理業之申請、變更、展延登記及撤銷、廢止登記，或註銷登記證時，應副知中央主管機關。第20條並列舉得撤銷、註銷或廢止登記證之各款事由。",
 "What must the registration authority do when approving or revoking a registration?",
 ["Send a copy to the central competent authority",
  "Send a copy to the relevant industry regulator",
  "Publish it on its website for thirty days",
  "Report it to the Executive Yuan for approval"],
 "Article 21."),

(A,"第22條",2,"回收處理業管理-停歇業清理",
 "回收業、處理業遷廠（場）、停業、歇業、宣告破產或經撤銷、廢止登記後，其尚未清除處理完竣之廢棄物應如何辦理？費用由誰負擔？",
 ["應依登記機關之指示辦理；所需清除、處理費用由回收業、處理業自行負擔",
  "應依中央主管機關之指示辦理；所需清除、處理費用由資源回收管理基金支應",
  "應依同業公會之指示辦理；所需清除、處理費用由公會共同基金分攤負擔",
  "應依破產管理人之指示辦理；所需清除、處理費用由地方政府編列預算支應"],"a",
 "第22條第1項：回收業、處理業遷廠（場）、停業、歇業、宣告破產時，或經撤銷、廢止登記後，對其廠（場）區尚未清除、處理完竣之廢棄物，應依登記機關之指示辦理。第2項：前項清除、處理所需費用由回收業、處理業自行負擔。第7條第10款並要求申請登記時即應檢具此類清理計畫。",
 "How must waste left on site be handled on relocation, closure or revocation, and who pays?",
 ["It must be handled as directed by the registration authority, and the operator bears the clearance and treatment costs itself",
  "It must be handled as directed by the central authority, and the costs are met from the Recycling Management Fund",
  "It must be handled as directed by the trade association, and the costs are shared from the association's joint fund",
  "It must be handled as directed by the bankruptcy trustee, and the costs are met from the local government budget"],
 "Article 22, paragraphs 1 and 2."),

(A,"第23條",2,"回收處理業管理-紀錄申報",
 "回收業、處理業對廢電線電纜、鐵門、水溝蓋等指定項目應如何作成紀錄？營運情形應於何時申報？",
 ["應逐日依項目、數量、日期、來源及流向作成紀錄並保存五年以供查核；並應於每月十五日前申報前一個月之營運情形",
  "應逐月依項目、數量、日期、來源及流向作成紀錄並保存三年以供查核；並應於每季結束後十五日內申報前一季營運情形",
  "應逐季依項目、數量、日期、來源及流向作成紀錄並保存一年以供查核；並應於每年一月底前申報前一年度之營運情形",
  "應逐日依項目、數量、日期、來源及流向作成紀錄並保存十年以供查核；並應於每月月底前申報當月份之營運情形"],"a",
 "第23條第1項：回收業、處理業應將回收、清除、處理之廢電線電纜、鐵門、水溝蓋及其他經中央主管機關指定項目，逐日依項目、數量、日期、來源及流向等作成紀錄，並保存五年以供查核。第2項：應於每月十五日前依第6條規定向登記機關申報前一個月之營運情形。第27條第2項並定本條自一百十六年一月一日施行。",
 "How must records of designated items be kept, and when must operations be reported?",
 ["Daily records of item, quantity, date, source and destination kept five years for inspection; and the previous month's operations reported by the 15th of each month",
  "Monthly records of item, quantity, date, source and destination kept three years for inspection; and the previous quarter's operations reported within 15 days of quarter end",
  "Quarterly records of item, quantity, date, source and destination kept one year for inspection; and the previous year's operations reported by the end of January each year",
  "Daily records of item, quantity, date, source and destination kept ten years for inspection; and the current month's operations reported by the last day of that month"],
 "Article 23, paragraphs 1 and 2."),

(A,"第24條",2,"回收處理業管理-有害物質處理業",
 "處理含中央主管機關指定公告有害物質成分之應回收廢棄物處理業，應符合何項規定始得營業？",
 ["應依本法第十八條第六項所定辦法成為受補貼機構，並納入稽核認證管制，始得營業",
  "應依本法第四十一條規定取得公民營廢棄物處理機構許可文件，始得開始營業",
  "應依本法第三十一條規定設置環境保護專責單位或人員，始得開始其營業",
  "應依本法第二十八條規定與清除機構簽訂共同清理契約，始得開始營業"],"a",
 "第24條：處理含中央主管機關指定公告有害物質成分之應回收廢棄物處理業，應依本法第十八條第六項所定辦法成為受補貼機構，並納入稽核認證管制，始得營業。第20條第1項第11款並定未依第24條辦理者，登記機關得撤銷、註銷或廢止其登記證或處理項目。",
 "What must operators treating designated hazardous recyclable waste satisfy before operating?",
 ["They must become a subsidised institution under the Article 18-6 regulations and be brought under audit certification control",
  "They must obtain a public or private waste treatment institution permit under Article 41 of the Act before operating",
  "They must establish a dedicated environmental protection unit or personnel under Article 31 of the Act",
  "They must sign a joint clearance contract with a clearance institution under Article 28 of the Act"],
 "Article 24."),

(A,"第25條",1,"回收處理業管理-未達規模者",
 "未達第二條所定規模之回收業，得否適用本辦法？",
 ["得依其申請適用本辦法之規定辦理登記及申報等事項，並受本辦法之規範",
  "一律不得適用本辦法，應改依事業廢棄物貯存清除處理標準辦理",
  "應強制適用本辦法之全部規定，不得以規模未達為由申請免除",
  "須經中央主管機關公告指定後，始得適用本辦法之部分規定"],"a",
 "第25條：未達第2條規模之回收業，得依其申請，適用本辦法之規定辦理登記及申報等相關事項，並受本辦法之規範。第2條並定廢機動車輛回收業以外之其他回收業，以回收貯存廠（場）土地面積達一千平方公尺以上者為適用規模。",
 "May recovery operators below the Article 2 scale threshold apply these Regulations?",
 ["Yes, on their own application they may register and report under these Regulations and be governed by them",
  "No, they must instead follow the industrial waste storage, clearance and treatment facility standard",
  "They are compulsorily subject to all of the provisions and cannot claim exemption for small scale",
  "Only after the central authority announces a designation may they apply parts of these rules"],
 "Article 25."),

(A,"第26條",1,"回收處理業管理-條文刪除",
 "本辦法原第二十六條規定之現行狀態為何？相關事項現應如何辦理？",
 ["該條業已刪除，回收業、處理業之管理悉依現行本辦法其他各條規定辦理",
  "該條仍屬有效，訂有本辦法施行前既有業者三年過渡適用期間之規定",
  "該條業經修正，改定回收業登記證有效期限得延長至十年之特別規定",
  "該條業經移列附表，另定應回收廢棄物項目與補貼費率之對照規定"],"a",
 "第26條：（刪除）。該條經刪除後，回收業、處理業之登記、變更、展延、撤銷廢止及申報等事項，均依本辦法其餘各條規定辦理；第27條並定本辦法自發布日施行，其中一百十五年七月十三日修正發布之第二十三條自一百十六年一月一日施行。",
 "What is the current status of the former Article 26 of these Regulations?",
 ["It has been deleted, and the management of operators follows the remaining articles of these Regulations",
  "It remains in force and provides a three-year transitional period for operators existing before",
  "It has been amended to allow recovery registration certificates to be extended up to ten years",
  "It has been moved into an appendix listing recyclable waste items against their subsidy rates"],
 "Article 26 (deleted)."),

(A,"第27條",2,"回收處理業管理-施行日",
 "本辦法之施行日期規定為何？一百十五年七月十三日修正發布之第二十三條自何時施行？",
 ["本辦法自發布日施行；一百十五年七月十三日修正發布之第二十三條，自一百十六年一月一日施行",
  "本辦法自發布後六個月施行；一百十五年七月十三日修正發布之第二十三條，自發布日起即行施行",
  "本辦法自發布日施行；一百十五年七月十三日修正發布之第二十三條，自一百十七年七月一日施行",
  "本辦法自一百十五年一月一日施行；一百十五年七月十三日修正發布之第二十三條，自公布後三年施行"],"a",
 "第27條第1項：本辦法自發布日施行。第2項：本辦法中華民國一百十五年七月十三日修正發布之第二十三條，自一百十六年一月一日施行。第23條係關於廢電線電纜、鐵門、水溝蓋等指定項目之逐日紀錄與每月十五日前申報之規定。",
 "When do these Regulations take effect, and when does the amended Article 23 apply?",
 ["The Regulations take effect on promulgation; Article 23 as amended on 13 July 2026 takes effect on 1 January 2027",
  "The Regulations take effect six months after promulgation; Article 23 as amended on 13 July 2026 takes effect at once",
  "The Regulations take effect on promulgation; Article 23 as amended on 13 July 2026 takes effect on 1 July 2028",
  "The Regulations take effect on 1 January 2026; Article 23 as amended on 13 July 2026 takes effect three years later"],
 "Article 27."),

# ===== ENV-188 毒性及關注化學物質災害事故應變車輛管理辦法 =====
(B,"第1條",1,"應變車輛管理-授權依據",
 "毒性及關注化學物質災害事故應變車輛管理辦法之授權依據為何？",
 ["依毒性及關注化學物質管理法第四十三條第二項規定訂定之",
  "依毒性及關注化學物質管理法第三十五條第三項規定訂定之",
  "依毒性及關注化學物質管理法第二十四條第一項規定訂定之",
  "依災害防救法第六十三條及消防法第十三條規定合併訂定之"],"a",
 "第1條：本辦法依毒性及關注化學物質管理法第四十三條第二項規定訂定之。第9條並定事故應變車輛依本法第四十三條第一項規定執行任務時，應開啟警示燈；第13條定本辦法自發布日施行。",
 "What is the legal basis of these Regulations on emergency response vehicles?",
 ["Article 43, paragraph 2 of the Toxic and Concerned Chemical Substances Control Act",
  "Article 35, paragraph 3 of the Toxic and Concerned Chemical Substances Control Act",
  "Article 24, paragraph 1 of the Toxic and Concerned Chemical Substances Control Act",
  "Article 63 of the Disaster Prevention Act together with Article 13 of the Fire Services Act"],
 "Article 1."),

(B,"第2條",2,"應變車輛管理-車輛種類",
 "事故應變車輛之種類及用途為何？其車身標識有何限制？",
 ["環境事故器材車為配置應變、偵檢設備之應變車輛，環境事故勤務車為執行勘查、支援任務之應變車輛；非依交通管理法令或經中央主管機關核准外，不得為其他標識",
  "環境事故指揮車為載運指揮官及幕僚之車輛，環境事故救護車為運送傷患就醫之車輛；非依消防法令或經地方主管機關核准外，不得為其他之標識",
  "環境事故採樣車為執行水質土壤採樣之車輛，環境事故除污車為執行人員除污之車輛；非依環評法令或經目的事業主管機關核准外，不得標識",
  "環境事故通信車為架設無線電基地台之車輛，環境事故照明車為提供夜間照明之車輛；非依道路交通標誌規則或經公路監理機關核准外，不得標識"],"a",
 "第2條第1項：事故應變車輛種類及用途為一、環境事故器材車：配置應變、偵檢設備之應變車輛；二、環境事故勤務車：執行勘查、支援任務之應變車輛。第2項：車身顏色、車身標示字體尺度、基本配備及使用之車輛種類應符合附表規定；非依交通管理法令規定或經中央主管機關核准外，不得為其他標識。",
 "What types of incident response vehicles are there, and what limits apply to markings?",
 ["Environmental incident equipment vehicles carry response and detection gear, and duty vehicles carry out survey and support tasks; other markings need traffic law authority or central approval",
  "Environmental incident command vehicles carry commanders and staff, and ambulances transport casualties to hospital; other markings need fire services authority or local approval",
  "Environmental incident sampling vehicles take water and soil samples, and decontamination vehicles clean personnel; other markings need EIA authority or industry regulator approval",
  "Environmental incident communication vehicles set up radio base stations, and lighting vehicles provide night lighting; other markings need road sign rules or highway office approval"],
 "Article 2, paragraphs 1 and 2."),

(B,"第3條",1,"應變車輛管理-駕駛資格",
 "事故應變車輛之駕駛人應具備何種資格？",
 ["應領有該種車輛之職業駕駛執照",
  "應領有該種車輛之普通駕駛執照",
  "應領有毒災應變專業技術證照",
  "應領有危險物品運送人員證明"],"a",
 "第3條：事故應變車輛駕駛人，應領有該種車輛職業駕駛執照。第12條並定違反第3條規定經直轄市、縣（市）主管機關令限期改善屆期未完成改善者，得變更或廢止登記並通知公路監理機關辦理異動或註銷車輛牌照。",
 "What qualification must the driver of an incident response vehicle hold?",
 ["A professional driving licence for that class of vehicle",
  "An ordinary driving licence for that class of vehicle",
  "A professional technician certificate for toxic incidents",
  "A dangerous goods transport personnel certificate"],
 "Article 3."),

(B,"第4條",3,"應變車輛管理-設置登記",
 "事故應變車輛之設置登記程序、陳報期限及登記有效期間為何？",
 ["由所有人向所在地直轄市、縣（市）主管機關申請登記，核准後向公路監理機關申請牌照，並於取得牌照之日起十五日內陳報備查；登記有效期間五年，期滿前三至六個月內申請展延",
  "由所有人向中央主管機關申請登記，核准後向公路監理機關申請牌照，並於取得牌照之日起三十日內陳報備查；登記有效期間三年，期滿前一至三個月內申請展延",
  "由所有人向公路監理機關申請牌照後，再向直轄市、縣（市）主管機關登記，並於登記之日起七日內陳報備查；登記有效期間十年，期滿後三個月內補行展延",
  "由所有人向目的事業主管機關申請登記，核准後向消防機關申請牌照，並於取得牌照之日起六十日內陳報備查；登記有效期間二年，期滿前一個月內申請展延"],"a",
 "第4條第1項：事故應變車輛之設置，由所有人向所在地直轄市、縣（市）主管機關申請登記，經核准登記並發給登記文件後，向所在地公路監理機關申請車輛牌照；所有人應於取得車輛牌照之日起十五日內陳報直轄市、縣（市）主管機關備查。第2項：登記有效期間為五年，期滿仍須繼續設置者，應於期滿前三個月至六個月之期間內申請展延，每次展延不得超過五年。",
 "What is the registration process, reporting deadline and validity period for such vehicles?",
 ["The owner applies to the local municipal or county authority, then applies for plates at the highway office, and reports within 15 days of receiving plates; registration lasts five years, renewable three to six months before expiry",
  "The owner applies to the central authority, then applies for plates at the highway office, and reports within 30 days of receiving plates; registration lasts three years, renewable one to three months before expiry",
  "The owner obtains plates from the highway office first, then registers with the local competent authority, and reports within 7 days of registering; registration lasts ten years, renewable within three months after expiry",
  "The owner applies to the industry regulator, then applies for plates at the fire agency, and reports within 60 days of receiving plates; registration lasts two years, renewable one month before expiry"],
 "Article 4, paragraphs 1 and 2."),

(B,"第5條",2,"應變車輛管理-登記文件記載",
 "事故應變車輛登記文件應記載之事項包括下列何者？",
 ["車輛所有人名稱地址及負責人與車輛管理人姓名、身分證統一編號；發證日期及有效期間；車輛種類；牌照號碼、廠牌、型式、引擎及車身號碼、出廠年月、購入日期、行車執照指定檢驗日期",
  "車輛所有人資本額及股東名冊；投保強制汽車責任保險金額及期間；車輛顏色；牌照號碼、車體長寬高、載重噸數、輪胎規格、燃油種類、加油卡號及維修廠商聯絡資料等事項",
  "車輛所有人之營利事業登記證號；駕駛人職業駕照號碼及有效期間；車輛用途；牌照號碼、行駛里程、每年耗油量、平均時速、保養週期及歷次維修紀錄與費用明細等事項",
  "車輛所有人之工廠登記編號；應變器材清冊及有效期限；車輛停放地點；牌照號碼、無線電呼號、定位系統帳號、出勤區域範圍、支援協定對象及緊急聯絡電話號碼等相關事項"],"a",
 "第5條：登記文件應記載車輛所有人名稱、地址（所有人為公司行號者，其負責人及車輛管理人之姓名、國民身分證統一編號）、發證日期及有效期間、車輛種類、車輛牌照號碼、廠牌、型式、引擎號碼、車身號碼、出廠年月、購入日期、行車執照指定檢驗日期等事項。",
 "What must the vehicle registration document record?",
 ["Owner name and address with the responsible person and vehicle manager's names and ID numbers; issue date and validity; vehicle type; plate number, make, model, engine and chassis numbers, build date, purchase date and inspection date",
  "Owner capital and its shareholder roster; compulsory insurance sum and period; vehicle colour; plate number, body dimensions, load tonnage, tyre specifications, fuel type, fuel card number and repair shop contact details",
  "Owner business registration number; the driver's professional licence number and its validity; vehicle use; plate number, mileage, annual fuel use, average speed, service intervals and the full repair history with cost details",
  "Owner factory registration number; response equipment inventory and expiry dates; parking location; plate number, radio call sign, positioning account, response area, mutual aid partners and emergency contact numbers"],
 "Article 5."),

(B,"第6條",3,"應變車輛管理-變更廢止",
 "設置事故應變車輛有變更情形者，應於何時申請變更或廢止登記？申請廢止登記應檢具何文件？",
 ["應於事實發生之日起三十日內向原核准登記之直轄市、縣（市）主管機關申請；申請廢止登記者應檢具完成除去車身標示、拆除警示燈及警鳴器之證明文件",
  "應於事實發生之日起十五日內向中央主管機關申請；申請廢止登記者應檢具車輛報廢證明、牌照繳銷收據及原登記文件正本等相關之證明文件",
  "應於事實發生之日起六十日內向公路監理機關申請；申請廢止登記者應檢具車輛過戶契約、稅費完納證明及保險解約證明等文件",
  "應於事實發生之日起九十日內向目的事業主管機關申請；申請廢止登記者應檢具董事會決議、財產處分清冊及會計師簽證報告"],"a",
 "第6條第1項：車輛所有人或負責人名稱地址變更、車輛過戶或車種變更、車輛停駛或恢復使用、車輛報廢或繳銷牌照、所有人停業歇業解散或裁撤者，應於事實發生之日起三十日內，向原核准登記之直轄市、縣（市）主管機關申請變更或廢止登記。第3項：申請廢止登記者，應檢具完成除去車身依第2條第2項所定車輛標示、拆除警示燈及警鳴器之證明文件。",
 "When must changes or deregistration be applied for, and what proof is needed for deregistration?",
 ["Within 30 days of the event, to the municipal or county authority that granted registration; deregistration requires proof that markings, warning lights and sirens have been removed",
  "Within 15 days of the event, to the central competent authority; deregistration requires a scrapping certificate, plate surrender receipt and the original registration document",
  "Within 60 days of the event, to the highway supervision office; deregistration requires the transfer contract, tax clearance proof and insurance cancellation certificates",
  "Within 90 days of the event, to the relevant industry regulator; deregistration requires board resolutions, an asset disposal schedule and an accountant's certification report"],
 "Article 6, paragraphs 1 and 3."),

(B,"第7條",2,"應變車輛管理-註銷牌照",
 "事故應變車輛經廢止登記或登記有效期間屆滿未申請展延者，主管機關應如何處理？",
 ["直轄市、縣（市）主管機關應通知公路監理機關註銷車輛牌照",
  "直轄市、縣（市）主管機關應逕行沒入該車輛並公開拍賣",
  "中央主管機關應通知警察機關扣留該車輛之行車執照",
  "公路監理機關應通知主管機關逕予撤銷其登記之文件"],"a",
 "第7條：事故應變車輛經直轄市、縣（市）主管機關廢止登記，或登記有效期間屆滿未申請展延，或經申請展延未獲核准者，直轄市、縣（市）主管機關應通知公路監理機關註銷車輛牌照。第4條第2項並定登記有效期間為五年，應於期滿前三個月至六個月申請展延。",
 "What happens when registration is revoked or lapses without renewal?",
 ["The municipal or county authority notifies the highway office to cancel the vehicle plates",
  "The municipal or county authority confiscates the vehicle and sells it at public auction",
  "The central authority notifies the police to seize the vehicle licence of that vehicle",
  "The highway office notifies the authority to revoke the registration document directly"],
 "Article 7."),

(B,"第8條",1,"應變車輛管理-網路傳輸",
 "申請事故應變車輛登記、展延、變更及登記文件之核（換、補）發，得以何種方式為之？",
 ["中央主管機關得公告以網路傳輸方式為之",
  "地方主管機關得公告以書面郵寄方式為之",
  "公路監理機關得公告以臨櫃辦理方式為之",
  "目的事業主管機關得公告以傳真方式為之"],"a",
 "第8條：申請事故應變車輛登記、展延、變更及登記文件之核（換、補）發，中央主管機關得公告以網路傳輸方式為之。第4條並定登記由所有人向所在地直轄市、縣（市）主管機關申請。",
 "How may registration, renewal, change and certificate issuance be filed?",
 ["The central authority may announce that they be filed by online transmission",
  "The local authority may announce that they be filed by postal paper delivery",
  "The highway office may announce that they be filed over the service counter",
  "The industry regulator may announce that they be filed by fax transmission"],
 "Article 8."),

(B,"第9條",2,"應變車輛管理-警示燈警鳴器",
 "事故應變車輛執行任務時，對警示燈及警鳴器之使用有何規定？未執行任務時應如何處理？",
 ["執行任務應開啟警示燈，非因情況緊急不得使用警鳴器；未執行任務時應妥善停放",
  "執行任務應開啟警鳴器，非因情況緊急不得使用警示燈；未執行任務時得任意停放",
  "執行任務應同時開啟警示燈及警鳴器；未執行任務時應停放於公路監理機關指定處",
  "執行任務得視需要開啟警示燈與警鳴器；未執行任務時應繳回牌照並停止使用車輛"],"a",
 "第9條第1項：事故應變車輛依本法第四十三條第一項規定執行任務，應開啟警示燈；非因情況緊急，不得使用警鳴器。第2項：事故應變車輛未執行任務時應妥善停放。第12條並定違反第9條規定經令限期改善屆期未改善者，得變更或廢止登記。",
 "What rules govern warning lights and sirens on duty, and parking when off duty?",
 ["Warning lights must be on when on duty, and sirens only in urgent situations; vehicles must be properly parked when off duty",
  "Sirens must be on when on duty, and warning lights only in urgent situations; vehicles may be parked anywhere when off duty",
  "Both warning lights and sirens must be on when on duty; vehicles must be parked at a site designated by the highway office",
  "Warning lights and sirens may be used as needed when on duty; when off duty the plates must be surrendered and use ceased"],
 "Article 9, paragraphs 1 and 2."),

(B,"第10條",2,"應變車輛管理-定位與紀錄",
 "事故應變車輛執行任務時應回傳何項資訊？出勤紀錄應由誰保存多久？",
 ["應即時回傳定位資訊予中央主管機關指定之網路系統；出勤人員應填具出勤紀錄，由所有人保存三年備查",
  "應即時回傳影像資訊予地方主管機關指定之監控系統；出勤人員應填具出勤紀錄，由駕駛人保存一年備查",
  "應每日回傳耗油資訊予公路監理機關指定之管理系統；出勤人員應填具出勤紀錄，由所有人保存五年備查",
  "應每月回傳里程資訊予目的事業主管機關指定平台；出勤人員應填具出勤紀錄，由公會保存十年備查"],"a",
 "第10條：事故應變車輛執行任務應即時回傳定位資訊予中央主管機關指定之網路系統；出勤人員應填具出勤紀錄，由所有人保存三年備查。第11條第1項並定直轄市、縣（市）主管機關就所轄車輛之配備、車身標識及出勤紀錄應定期檢查。",
 "What information must be transmitted on duty, and who keeps duty records for how long?",
 ["Real-time positioning data to the network system designated by the central authority; duty records are filed by crew and kept by the owner for three years",
  "Real-time video data to the monitoring system designated by the local authority; duty records are filed by crew and kept by the driver for one year",
  "Daily fuel consumption data to the system designated by the highway office; duty records are filed by crew and kept by the owner for five years",
  "Monthly mileage data to the platform designated by the industry regulator; duty records are filed by crew and kept by the association for ten years"],
 "Article 10."),

(B,"第11條",2,"應變車輛管理-定期檢查",
 "直轄市、縣（市）主管機關對所轄事故應變車輛應檢查哪些項目？所有人有何義務？",
 ["應就車輛之配備、車身標識及出勤紀錄定期檢查，必要時得不定期為之；所有人對於檢查不得規避、妨礙或拒絕",
  "應就車輛之排放污染、噪音及耗油量定期檢查，必要時得不定期為之；所有人對於檢查得申請延期或改期辦理",
  "應就駕駛人體檢、酒測及工時紀錄定期檢查，必要時得委託公會為之；所有人對於檢查得要求事前七日通知",
  "應就車輛之保險、稅費及牌照定期檢查，必要時得由公路監理機關為之；所有人對於檢查得拒絕提供出勤紀錄"],"a",
 "第11條第1項：直轄市、縣（市）主管機關就所轄事故應變車輛之配備、車身標識及出勤紀錄應定期檢查，必要時得不定期為之。第2項：事故應變車輛之所有人對於前項檢查，不得規避、妨礙或拒絕。第12條並定違反第11條第2項規定經令限期改善屆期未改善者，得變更或廢止登記。",
 "What must the local authority inspect, and what duty does the owner have?",
 ["Vehicle equipment, body markings and duty records must be inspected regularly and may be inspected at any time; owners must not evade, obstruct or refuse inspection",
  "Vehicle emissions, noise and fuel use must be inspected regularly and may be inspected at any time; owners may apply to postpone or reschedule the inspection",
  "Driver health checks, breath tests and hours records must be inspected regularly, possibly by associations; owners may demand seven days' advance notice",
  "Vehicle insurance, taxes and plates must be inspected regularly, possibly by the highway office; owners may refuse to hand over their duty records"],
 "Article 11, paragraphs 1 and 2."),

(B,"第12條",3,"應變車輛管理-違規處理",
 "違反車身標識、駕駛資格、登記、變更、警示燈使用、定位回傳或拒絕檢查等規定者，主管機關應如何處理？",
 ["經直轄市、縣（市）主管機關令其限期改善，屆期未完成改善者，得變更或廢止登記，並通知公路監理機關辦理異動登記或註銷其車輛牌照",
  "經直轄市、縣（市）主管機關逕處罰鍰並沒入車輛，改善完成後始得發還，並通知公路監理機關恢復其車輛牌照之使用權利",
  "經中央主管機關令其限期改善，屆期未完成改善者，應移送司法機關偵辦，並通知公路監理機關暫時扣留其行車執照",
  "經公路監理機關令其限期改善，屆期未完成改善者，應停止其出勤三個月，並通知直轄市、縣（市）主管機關列管追蹤"],"a",
 "第12條：違反第2條第2項、第3條、第4條、第6條、第9條、第10條或第11條第2項規定，經直轄市、縣（市）主管機關令其限期改善，屆期未完成改善者，直轄市、縣（市）主管機關得變更或廢止登記，並通知公路監理機關辦理異動登記或註銷其車輛牌照。第7條並定廢止登記或未展延者應通知註銷牌照。",
 "How are breaches of marking, driver, registration, light, positioning or inspection rules handled?",
 ["The local authority orders improvement within a period; if not completed, it may change or revoke registration and notify the highway office to amend or cancel the plates",
  "The local authority imposes a fine and confiscates the vehicle, returning it after improvement, and notifies the highway office to restore the use of the plates",
  "The central authority orders improvement within a period; if not completed, the case goes to prosecutors and the highway office is told to seize the vehicle licence",
  "The highway office orders improvement within a period; if not completed, duty is suspended for three months and the local authority is told to keep the case under watch"],
 "Article 12."),

(B,"第13條",1,"應變車輛管理-施行日",
 "本辦法之施行日期規定為何？",
 ["本辦法自發布日施行，未另定分階段施行之日期",
  "本辦法自發布後六個月施行，並分階段適用之",
  "本辦法自發布後一年施行，並溯及既往而適用",
  "本辦法自中華民國一百十二年一月一日起施行"],"a",
 "第13條：本辦法自發布日施行。第1條並定本辦法依毒性及關注化學物質管理法第四十三條第二項規定訂定；第12條則定違反相關規定經令限期改善屆期未改善者得變更或廢止登記。",
 "When do these Regulations take effect?",
 ["On the date of promulgation, with no phased effective dates",
  "Six months after promulgation, applying in phases over time",
  "One year after promulgation, applying retroactively as well",
  "On 1 January 2023 under a separately designated date"],
 "Article 13."),
]
