# -*- coding: utf-8 -*-
# 第 9 批（B3）：補齊條文覆蓋──公民營廢棄物清除處理機構許可管理辦法
WC = "ENV-54"
Q = [
(WC,"第1條",1,"清處機構-授權依據",
 "公民營廢棄物清除處理機構許可管理辦法係依何法條授權訂定？",
 ["依廢棄物清理法第四十二條規定訂定","依廢棄物清理法第四十四條規定訂定",
  "依廢棄物清理法第二十八條規定訂定","依資源回收再利用法第十八條規定訂定"],"a",
 "第1條：本辦法依廢棄物清理法（本法）第四十二條規定訂定之。廢棄物清理法第42條授權中央主管機關就公民營廢棄物清除處理機構之設施、設備、專業技術人員、許可及管理等事項訂定管理辦法；至於廢棄物清理專業技術人員管理辦法則係依本法第44條訂定。",
 "Under which provision were these Regulations for Public and Private Waste Disposal Organizations issued?",
 ["Article 42 of the Waste Disposal Act","Article 44 of the Waste Disposal Act",
  "Article 28 of the Waste Disposal Act","Article 18 of the Resource Recycling Act"],
 "Article 1."),

(WC,"第3條",2,"清處機構-同意設置文件",
 "申請處理許可證者於設置廢棄物處理場（廠）前應先取得何種文件？有無例外？",
 ["應先申請核發機關之同意設置文件；但既有之工廠或廢棄物處理設施得於進行試運轉後逕行申請處理許可證",
  "應先申請目的事業主管機關之工廠設立許可；但既有之工廠或廢棄物處理設施得於完工後逕行申請處理許可證",
  "應先取得中央主管機關之同意設置文件；但屬移動式廢棄物處理設施者得於試運轉前逕行申請處理許可證",
  "應先取得環境影響評估審查通過之定稿本；但既有之工廠或廢棄物處理設施得免辦理試運轉而逕行申請"],"a",
 "第3條第3項：申請處理許可證者，於設置廢棄物處理場（廠）前，應申請核發機關之同意設置文件；但既有之工廠或廢棄物處理設施得於進行試運轉後逕行申請處理許可證。第3條第4項：所稱既有之工廠，除依法免辦工廠設立登記者外，指於申請處理許可證前已依相關規定取得工廠登記且有相同產品並實際運作之工廠。",
 "Before establishing a waste treatment site, an applicant for a treatment permit must first obtain what, and with what exception?",
 ["The issuing authority's consent-to-establish document; existing factories or treatment facilities may instead apply for the treatment permit directly after a trial run",
  "The industry authority's factory establishment approval; existing factories or treatment facilities may instead apply for the permit directly after completion",
  "The central authority's consent-to-establish document; mobile waste treatment facilities may instead apply for the permit directly before any trial run",
  "A final approved environmental impact assessment report; existing factories or treatment facilities may skip the trial run and apply directly"],
 "Article 3, paragraphs 3-4."),

(WC,"第4條",1,"清處機構-受理機關",
 "申請清除許可證及申請同意設置文件或處理許可證，應分別向何核發機關提出？",
 ["申請清除許可證者向所在地之核發機關申請；申請同意設置文件或處理許可證者，向處理場（廠）所在地之核發機關申請",
  "申請清除許可證者向處理場（廠）所在地核發機關申請；申請同意設置文件或處理許可證者，向機構登記所在地之核發機關申請",
  "申請清除許可證者向中央主管機關申請核發；申請同意設置文件或處理許可證者，向處理場（廠）所在地之核發機關申請",
  "申請清除許可證者向所在地之核發機關申請；申請同意設置文件或處理許可證者，一律向中央主管機關委託之機關申請"],"a",
 "第4條：申請清除許可證者，應向所在地之核發機關申請；申請同意設置文件或處理許可證者，應向處理場（廠）所在地之核發機關申請。第2條第3項並定核發機關指本法第41條第1項核發許可文件之直轄市、縣（市）主管機關或中央主管機關委託之機關。",
 "Where must applications for removal permits and for consent-to-establish or treatment permits be filed?",
 ["Removal permits with the issuing authority of the applicant's location; consent-to-establish and treatment permits with the issuing authority where the treatment site is located",
  "Removal permits with the issuing authority where the treatment site is located; consent-to-establish and treatment permits with the authority of the registered address",
  "Removal permits with the central competent authority; consent-to-establish and treatment permits with the issuing authority where the treatment site is located",
  "Removal permits with the issuing authority of the applicant's location; consent-to-establish and treatment permits always with an agency commissioned by the central authority"],
 "Article 4 (see Article 2, paragraph 3)."),

(WC,"第7條",2,"清處機構-技術員設置核定",
 "清除、處理機構設置專業技術人員時，應如何辦理申請？",
 ["應檢具專業技術人員合格證書及設置申請書，向直轄市、縣（市）主管機關申請核定，並應採網路傳輸方式辦理，經同意者得以書面申請",
  "應檢具專業技術人員合格證書及勞保投保資料，向中央主管機關申請核定，並應採網路傳輸方式辦理，不得以書面方式提出申請",
  "應檢具專業技術人員合格證書及在職訓練紀錄，向目的事業主管機關報請備查，並得由機構自行決定採網路或書面方式辦理",
  "應檢具專業技術人員學經歷證明及體格檢查報告，向直轄市、縣（市）主管機關申請核定，並一律應以書面掛號方式提出申請"],"a",
 "第7條：清除、處理機構設置專業技術人員時，應檢具專業技術人員合格證書及設置申請書，向直轄市、縣（市）主管機關申請核定；其申請除經直轄市、縣（市）主管機關同意得以書面方式申請者外，應採網路傳輸方式辦理。第6條並定各級機構應置之技術員類別與人數。",
 "How must removal or treatment organizations apply to appoint professional technical personnel?",
 ["Submit the personnel's qualification certificate and an appointment application to the municipal or county authority for approval, filed online unless that authority consents to paper filing",
  "Submit the personnel's qualification certificate and labor insurance data to the central competent authority for approval, filed online with paper filing never permitted in any case",
  "Submit the qualification certificate and in-service training records to the industry authority for the record, choosing freely between online and paper filing",
  "Submit the personnel's academic credentials and a medical examination report to the municipal or county authority for approval, always filed by registered mail"],
 "Article 7."),

(WC,"第9條",3,"清處機構-同意設置文件檢附",
 "申請處理機構同意設置文件時，應檢具下列何項文件？",
 ["工程計畫說明書、污染防治計畫書、廢棄物處理流程設備及操作說明、車輛進出口廢棄物磅秤設備設置規劃、閉路電視錄影系統配置計畫及自律切結聲明",
  "營運概況與違法事實改善情形、最近一次固定污染源檢測報告、處理後衍生廢棄物每六個月檢測紀錄、同業公會會員證明文件及自律切結聲明",
  "試運轉方法程序步驟、質量平衡計算方式、採樣監測及品質管理計畫、緊急應變措施、收受廢棄物之允收標準及封場復育計畫書等文件",
  "工程計畫說明書、勞工安全衛生管理計畫、消防安全設備竣工查驗報告、員工在職訓練計畫、產品銷售契約書及土地使用分區證明文件"],"a",
 "第9條：申請處理機構同意設置文件應檢具申請表、政府機關核准登記證明文件、負責人身分證明文件、處理場（廠）土地所有權狀地籍資料及土地清冊（非自有土地並附使用同意書）、工程計畫說明書、污染防治計畫書、廢棄物處理流程（含所產生污染物處理與排放）設備及操作說明、車輛進出口廢棄物磅秤設備設置規劃、閉路電視錄影系統配置計畫（設置要求如附件二）、環評定稿本相關內容及審查結論、自律切結聲明（附件一）等文件。",
 "Which documents must accompany an application for a treatment organization's consent-to-establish?",
 ["An engineering plan statement, a pollution control plan, the treatment flow, equipment and operating description, weighing equipment layout for vehicles, a CCTV system layout plan and a self-discipline affidavit",
  "An operations summary with violation remedies, the latest stationary source test report, six-monthly testing records for derived hazardous waste, trade association membership proof and a self-discipline affidavit",
  "Trial run methods and steps, mass balance calculations, a sampling, monitoring and quality management plan, emergency response measures, waste acceptance criteria and a site closure restoration plan",
  "An engineering plan statement, an occupational safety plan, a fire safety inspection report, an employee training plan, product sales contracts and a land use zoning certificate"],
 "Article 9."),

(WC,"第11條",3,"清處機構-處理許可證檢附",
 "申請核發處理許可證時，應檢具下列何項文件？",
 ["含廢棄物種類來源、操作、紀錄與統計及質量平衡之試運轉報告、收受廢棄物之允收標準、品管規劃、運作管理紀錄規劃、建築執照或使用執照及封場復育計畫",
  "含試運轉方法程序步驟及清運計畫之試運轉計畫書、工程計畫說明書、污染防治計畫書、閉路電視錄影系統配置計畫、環評定稿本內容及土地清冊",
  "含營運概況及違法事實改善情形之營運報告、原核發許可證、同業公會會員證明文件、有害事業廢棄物衍生廢棄物檢測紀錄及展延原因說明書",
  "含員工名冊及勞保投保資料之人事文件、公司章程與股東名簿、最近三年財務報表、營利事業所得稅結算申報書及銀行存款餘額證明文件"],"a",
 "第11條：申請核發處理許可證者應檢具申請表、登記證明文件、負責人身分證明、處理技術員合格證書與勞保投保資料及任職證明、同意設置文件、建廠期間環境管理及定期監測報告、含廢棄物種類來源與操作紀錄統計及質量平衡之試運轉報告、收受廢棄物之允收標準、含檢測項目方法頻率數量之品管規劃、運作管理紀錄規劃、他場（廠）同意處理其所產生廢棄物之證明、建築執照或使用執照、無法執行業務時之廢棄物處置計畫、自律切結聲明，以最終處置方式處理者並應檢附封場復育計畫。",
 "Which documents must accompany an application for a treatment permit?",
 ["A trial run report covering waste types, sources, operation, records, statistics and mass balance; waste acceptance criteria; a quality control plan; an operations record plan; building or use permits; and a closure restoration plan",
  "A trial run plan with methods, steps and haulage arrangements; an engineering plan statement; a pollution control plan; a CCTV system layout plan; the final EIA report contents; and a land inventory with cadastral data and title deeds",
  "An operations report with violation remedies; the original permit; trade association membership proof; testing records for waste derived from hazardous waste; and a statement of reasons for renewal",
  "Personnel files with a staff roster and labor insurance data; the articles of incorporation and shareholder register; three years of financial statements; tax returns; and bank balance certificates"],
 "Article 11."),

(WC,"第12條",2,"清處機構-環評併同審查",
 "申請案經依規定通過環境影響評估審查者，核發機關應如何審查？",
 ["得僅就申請同意設置文件或許可證中未經環境影響評估審查之部分進行審查，並應將環評中廢棄物處理及相關污染防治審查結論併入許可條件",
  "應就申請同意設置文件或許可證之全部內容重新完整審查一次，並得不受環評中廢棄物處理及相關污染防治審查結論之任何拘束",
  "得僅就申請同意設置文件或許可證中已經環境影響評估審查之部分進行審查，未經環評審查之部分則由目的事業主管機關逕行核定",
  "應俟環境影響評估主管機關同意後始得受理其申請，並應將環評中廢棄物處理及相關污染防治審查結論全部排除於許可條件之外"],"a",
 "第12條：申請案經依規定通過環境影響評估審查，核發機關得僅就其申請同意設置文件或許可證中，未經環境影響評估審查部分進行審查，並應將環境影響評估中廢棄物處理及相關污染防治審查結論併入許可條件。第9條第10款並要求檢具環評定稿本中與廢棄物處理及相關污染防治之內容及審查結論。",
 "Where an application has passed environmental impact assessment review, the issuing authority:",
 ["May review only the parts of the consent or permit application not covered by the EIA, and must incorporate the EIA's waste treatment and pollution control conclusions into the permit conditions",
  "Must review the entire consent or permit application afresh from the start, and is not bound in any way by the EIA's waste treatment and pollution control conclusions in any respect whatsoever",
  "May review only the parts already covered by the EIA, while parts not covered by the EIA are approved directly by the industry competent authority",
  "May accept the application only after the EIA authority consents, and must exclude all of the EIA's waste treatment and pollution control conclusions from the final permit conditions"],
 "Article 12."),

(WC,"第13條",1,"清處機構-許可證記載事項",
 "清除許可證及處理許可證應記載事項分別規定於何處？",
 ["清除許可證應記載事項如附件三；處理許可證應記載事項如附件四",
  "清除許可證應記載事項如附件一；處理許可證應記載事項如附件二",
  "清除許可證應記載事項如附件四；處理許可證應記載事項如附件五",
  "清除及處理許可證應記載事項均規定於同一附件三之表格內"],"a",
 "第13條：清除許可證應記載事項如附件三；處理許可證應記載事項如附件四。另附件一為自律切結聲明，附件二為不同管制類別之錄影系統設置要求，附件五為特定工程用途資源化產品之使用地點、銷售對象及品質標準。",
 "Where are the required entries for removal permits and treatment permits specified?",
 ["Removal permit entries in Annex 3; treatment permit entries in Annex 4",
  "Removal permit entries in Annex 1; treatment permit entries in Annex 2",
  "Removal permit entries in Annex 4; treatment permit entries in Annex 5",
  "Entries for both removal and treatment permits are in a single Annex 3"],
 "Article 13."),

(WC,"第15條",3,"清處機構-展延檢附文件",
 "申請清除、處理許可證期限之展延時，應檢具下列何項文件？",
 ["原核發許可證、許可期間內營運概況及違法事實改善情形、最近一次固定污染源檢測或水污染防治措施功能測試結果、有害事業廢棄物處理後衍生廢棄物之每六個月檢測紀錄及同業公會會員證明文件",
  "原核發同意設置文件、展延原因說明書、工程計畫說明書及污染防治計畫書、閉路電視錄影系統配置計畫、環境影響評估定稿本審查結論及最終處置場之封場復育計畫書等文件",
  "試運轉計畫書及其質量平衡計算方式、採樣監測及品質管理計畫、緊急應變措施、收受廢棄物之允收標準、資源化產品品管規劃及運作管理紀錄規劃等相關文件",
  "最近三年財務報表及營利事業所得稅結算申報書、股東名簿與公司章程、員工勞工保險投保資料明細、建築執照或使用執照及土地使用分區證明文件等文件"],"a",
 "第15條第2項：申請清除、處理許可證期限之展延，應檢具申請表、登記證明文件、負責人身分證明、原核發許可證、清除或處理技術員合格證書與勞保投保資料及任職證明、原許可文件許可事項、許可期間內營運概況及違法事實改善情形、最近一次固定污染源檢測或水污染防治措施功能測試結果及品管與運作管理紀錄（清除機構及採掩埋法者免附）、他場（廠）同意處理證明（清除機構免）、有害事業廢棄物處理後衍生廢棄物之每六個月檢測紀錄、同業公會會員證明文件及自律切結聲明。",
 "Which documents must accompany an application to renew a removal or treatment permit?",
 ["The original permit; an operations summary and record of remedying violations during the term; the latest stationary source test or water control performance test results; six-monthly testing records for waste derived from hazardous waste; and trade association membership proof",
  "The original consent-to-establish document; a statement of renewal reasons; an engineering plan statement and a pollution control plan; a CCTV system layout plan; the EIA review conclusions; a site closure restoration plan for final disposal sites; and a land ownership inventory",
  "The trial run plan and its mass balance calculations; a sampling, monitoring and quality management plan; emergency response measures; waste acceptance criteria; a recycled product quality plan; and an operations record plan",
  "Three years of financial statements and tax returns; the shareholder register and articles of incorporation; employees' labor insurance data; building or use permits; and a land use zoning certificate"],
 "Article 15, paragraph 2."),

(WC,"第16條",3,"清處機構-變更辦理",
 "同意設置文件或許可文件之變更應如何辦理？變更級別者應如何處理？",
 ["機構名稱、地址、負責人姓名及身分證明文件字號變更者應於變更後三十日內辦理變更；其他審查通過內容之變更應於變更前提出申請；清除、處理機構變更級別應重新提出申請",
  "機構名稱、地址、負責人姓名及身分證明文件字號變更者應於變更前六十日內辦理變更；其他審查通過內容之變更得於變更後補行申請；清除、處理機構變更級別僅需報請備查",
  "機構名稱、地址、負責人姓名及身分證明文件字號變更者應於變更後九十日內辦理變更；其他審查通過內容之變更應於變更前提出申請；清除、處理機構變更級別應辦理註銷登記",
  "機構名稱、地址、負責人姓名及身分證明文件字號變更者免辦理任何變更程序；其他審查通過內容之變更應於變更後三十日內辦理；清除、處理機構變更級別應重新提出申請"],"a",
 "第16條第1項：機構名稱、地址、負責人姓名、住址及身分證明文件字號變更時，應於變更後三十日內填具變更申請表連同證明文件辦理變更；更新處理設備或增加必要輔助機具且未涉及原許可製程、種類、數量及主要機具者應報核發機關備查；其他審查通過內容之變更應於變更前依原核准內容辦理並檢具變更申請表提出申請。第16條第3項：變更期限應以原核准之期限為限。第16條第4項：清除、處理機構變更級別，應重新提出申請。",
 "How must changes to a consent or permit be handled, and what if the grade changes?",
 ["Changes to name, address, responsible person's name and ID number are filed within 30 days after the change; other approved contents must be applied for before the change; a change of grade requires a fresh application",
  "Changes to name, address, responsible person's name and ID number must be filed 60 days before the change; other approved contents may be applied for after the change; a change of grade only needs filing for the record",
  "Those changes are filed within 90 days after the change; other approved contents must be applied for before the change; a change of grade requires deregistration",
  "Those changes need no filing at all; other approved contents are filed within 30 days after the change; a change of grade requires a fresh application"],
 "Article 16."),

(WC,"第16-1條",1,"清處機構-網路傳輸",
 "清除、處理許可及同意設置文件之申請、變更及展延，應以何種方式辦理？",
 ["應採網路傳輸方式辦理；但經核發機關同意者，得以書面方式為之",
  "應採書面掛號方式辦理；但經核發機關同意者，得以網路傳輸為之",
  "應採網路傳輸方式辦理；且不論任何情形均不得以書面方式提出",
  "得由申請者自行選擇採網路傳輸或書面方式辦理，無任何限制"],"a",
 "第16-1條：清除、處理許可及同意設置文件之申請、變更及展延，應採網路傳輸方式辦理；但經核發機關同意者，得以書面方式為之。第7條之專業技術人員設置核定申請亦採相同之網路傳輸原則。",
 "How must applications, changes and renewals of permits and consent documents be filed?",
 ["By online transmission; paper filing is allowed only where the issuing authority consents",
  "By registered paper mail; online transmission is allowed only where the authority consents",
  "By online transmission only, with paper filing never permitted under any circumstances",
  "By whichever of online or paper filing the applicant chooses, with no restriction at all"],
 "Article 16-1."),

(WC,"第16-2條",3,"清處機構-審查範圍限制",
 "核發機關受理清除、處理許可等案件之審查範圍與補正通知有何限制？",
 ["審查範圍不得及於申請、提報、變更或展延內容以外之事項，不得增加法規未明定之義務；審查意見應以一次性提供為原則，後續補正通知不宜有前次未列明之審查意見",
  "審查範圍得及於申請內容以外之相關環保法規遵循事項，並得增加必要之管理義務；審查意見得分次提供，後續補正通知得隨時新增前次未列明之審查意見",
  "審查範圍不得及於申請內容以外之事項，但得增加法規未明定之義務；審查意見應於受理後七日內一次提供，逾期未提供者視為准予核發其許可證",
  "審查範圍限於文件完整性之程序審查而不及於實體審查；審查意見應以書面一次性提供，且核發機關不得就已核發之許可證更正任何顯然錯誤"],"a",
 "第16-2條第1項：核發機關受理清除許可證、同意設置文件、試運轉計畫、處理許可證之申請、提報、變更或展延案件時，其審查範圍不得及於申請、提報、變更或展延內容以外之事項，並不得以任何形式之處分增加法規所未明定之義務。第16-2條第2項：發現誤寫、誤算或其他類此顯然錯誤者，得隨時更正並通知受更正者。第16-2條第3項：審查意見應分別以一次性提供為原則，後續通知限期補正時不宜有前次未列明之審查意見。",
 "What limits apply to the scope of review and to correction notices?",
 ["Review may not extend beyond the matters applied for and may not impose duties not prescribed by law; review comments should be given once, and later correction notices should not raise comments omitted earlier",
  "Review may extend to compliance with other environmental laws and may impose any necessary management duties; comments may be given in stages, and new comments may be added in later notices at any time",
  "Review may not extend beyond the matters applied for but may impose duties not prescribed by law; comments must be given within seven days or the permit is deemed granted",
  "Review is limited to the procedural completeness of documents and excludes substantive review; comments are given once and obvious errors in issued permits may never be corrected"],
 "Article 16-2."),

(WC,"第16-3條",2,"清處機構-污染流向示意圖",
 "申請核發、變更或展延處理許可證及設貯存場或轉運站之清除許可證前，申請者應先辦理何事項？",
 ["須先繪製全廠（場）空氣、水、廢棄物、毒性及關注化學物質污染流向示意圖，檢視污染在不同介質間之流向及在各類環保許可證（文件）間之關連",
  "須先委託環境工程技師完成全廠（場）環境風險評估報告書，檢視污染物對周界居民健康之影響及其與各類環保許可證（文件）之關連",
  "須先取得目的事業主管機關核發之工廠登記證及使用執照，檢視其產能與各類環保許可證（文件）所登記之處理量是否相互一致",
  "須先繪製全廠（場）廢棄物貯存及處理設施配置平面圖，檢視各設施單元之相對位置及其與周界圍牆間之最小防護距離是否足夠"],"a",
 "第16-3條第1項：申請核發、變更或展延處理許可證及設貯存場或轉運站之清除許可證前，申請者須先繪製全廠（場）空氣、水、廢棄物、毒性及關注化學物質污染流向示意圖，檢視污染在不同介質間之流向及在各類環保許可證（文件）間之關連。第16-3條第2項：如涉及其他類環保許可證之申請、變更、異動或展延者，須同時依各該環保法規提出。此與水污染防治措施計畫及許可申請審查管理辦法第49-1條規定相同。",
 "Before applying for, changing or renewing a treatment permit (or a removal permit with storage or transfer stations), the applicant must first:",
 ["Draw a plant-wide flow diagram of air, water, waste, toxic and concerned chemical pollution, reviewing flows across media and links among the various environmental permits",
  "Commission an environmental engineer to complete a plant-wide risk assessment report, reviewing health effects on nearby residents and links among the various environmental permits",
  "Obtain the industry authority's factory registration and use permit, reviewing whether its capacity matches the treatment volumes registered in the various environmental permits",
  "Draw a plant-wide layout of waste storage and treatment facilities, reviewing the relative positions of units and whether buffer distances to the boundary wall suffice"],
 "Article 16-3 (compare Article 49-1 of the water control permit regulations)."),

(WC,"第16-4條",1,"清處機構-製證期限",
 "核發機關受理清除、處理許可證申請核發、換發或補發，經審查符合規定者，應於何時完成製證？",
 ["應於審查核准後十四日內完成許可證製作，並通知申請者繳納證書費及領取許可證",
  "應於審查核准後三十日內完成許可證製作，並通知申請者繳納證書費及領取許可證",
  "應於審查核准後七日內完成許可證製作，並由申請者自行至資訊系統下載列印",
  "應於審查核准後六十日內完成許可證製作，並以雙掛號郵寄方式逕送申請者收執"],"a",
 "第16-4條：核發機關受理清除許可證、處理許可證申請核發、換發或補發許可證，經審查符合規定者，應於審查核准後十四日內完成許可證製作，並通知申請者繳納證書費及領取許可證。第5條並定審查期限為受理後六十日內，必要時得再延長六十日。",
 "After approving an application to issue, reissue or replace a permit, the authority must complete the permit within:",
 ["Fourteen days of approval, then notify the applicant to pay the certificate fee and collect the permit",
  "Thirty days of approval, then notify the applicant to pay the certificate fee and collect the permit",
  "Seven days of approval, with the applicant downloading and printing it from the information system",
  "Sixty days of approval, then send it directly to the applicant by double-registered mail"],
 "Article 16-4."),

(WC,"第17條",2,"清處機構-移動式設施",
 "設置移動式廢棄物處理設施之處理機構，於處理設施移動前應如何辦理？",
 ["應檢具審查通過之申請文件及污染防治計畫書，函請移動前、後處理設施所在地直轄市、縣（市）主管機關許可後，始得移動",
  "應檢具審查通過之申請文件及污染防治計畫書，函請移動後處理設施所在地直轄市、縣（市）主管機關備查後，即得移動",
  "應檢具移動路線規劃及車輛清冊資料，函請移動前、後處理設施所在地直轄市、縣（市）主管機關備查後，始得移動",
  "應檢具審查通過之申請文件及試運轉報告，函請中央主管機關委託之機關核准後，並副知所在地主管機關始得移動"],"a",
 "第17條：設置移動式廢棄物處理設施之處理機構，應於處理設施移動前，檢具審查通過之申請文件及污染防治計畫書，函請移動前、後處理設施所在地直轄市、縣（市）主管機關許可後，始得移動。第11條第6款並定移動式廢棄物處理設施免附建廠期間定期監測報告。",
 "Before moving a mobile waste treatment facility, the treatment organization must:",
 ["Submit the approved application documents and pollution control plan and obtain permission from the municipal or county authorities of both the origin and destination locations",
  "Submit the approved application documents and pollution control plan for the record with the municipal or county authority of the destination location, after which it may move",
  "Submit a route plan and vehicle inventory for the record with the authorities of both the origin and destination locations before moving",
  "Submit the approved application documents and trial run report for approval by an agency commissioned by the central authority, copying the local authority"],
 "Article 17."),

(WC,"第18條",2,"清處機構-自行清除與容許差值",
 "清除、處理機構從事業務時，關於自行清除處理、容許差值及清除車輛之規定為何？",
 ["除報經核發機關同意外應自行清除、處理；每月實際清除、處理量總額得有許可量上限百分之十之容許差值；應以經核准之車輛清除，調度不及經同意得以其他清除機構核准車輛清除",
  "得自由委託其他機構代為清除、處理而無須報經同意；每月實際清除、處理量總額得有許可量上限百分之三十之容許差值；應以經核准之車輛清除，且任何情形均不得使用他機構車輛",
  "除報經核發機關同意外應自行清除、處理；每月實際清除、處理量總額不得有任何容許差值；應以經核准之車輛清除，調度不及時得逕行使用其他清除機構之車輛清除",
  "應由核發機關指定之機構共同清除、處理；每月實際清除、處理量總額得有許可量上限百分之二十之容許差值；應以經核准之車輛清除，其他機構車輛須報中央核准"],"a",
 "第18條：清除、處理機構應依本法及其相關規定及審查通過之申請文件內容辦理；除報經核發機關同意外，應自行清除、處理；每月實際清除、處理量總額得有許可該項廢棄物清除、處理量上限百分之十之容許差值；清除機構受託清除廢棄物應以其經核發機關核准之車輛進行清除，但因清除車輛調度不及經核發機關同意者，得以其他清除機構經核准之清除車輛進行清除。",
 "What rules govern self-performance, tolerance and vehicles for removal and treatment organizations?",
 ["They must perform the work themselves unless the authority consents; monthly actual volume may vary within 10% of the permitted ceiling; approved vehicles must be used, with another organization's approved vehicles allowed by consent when dispatch falls short",
  "They may freely subcontract the work to others without any consent; monthly actual volume may vary within 30% of the permitted ceiling; approved vehicles must be used, and another organization's approved vehicles are never allowed under any circumstances",
  "They must perform the work themselves unless the authority consents; no tolerance applies to monthly volume; approved vehicles must be used, and others' vehicles may be used freely when dispatch falls short",
  "They must work jointly with organizations designated by the authority; monthly volume may vary within 20% of the ceiling; other organizations' vehicles require central approval"],
 "Article 18."),

(WC,"第19條",2,"清處機構-暫停收受",
 "處理機構產出之資源化產品及衍生廢棄物貯存量達何程度時，應暫時停止收受廢棄物？",
 ["其貯存量超出前六個月之累積產出量時，應暫時停止收受廢棄物；但經核發機關同意者，不在此限",
  "其貯存量超出前三個月之累積產出量時，應暫時停止收受廢棄物；但經核發機關備查者，不在此限",
  "其貯存量超出前十二個月之累積產出量時，應暫時停止收受廢棄物，且無任何例外情形之規定",
  "其貯存量超出當月之累積產出量時，應暫時停止收受廢棄物；但經目的事業主管機關同意者除外"],"a",
 "第19條：處理機構產出資源化產品及衍生廢棄物，如其貯存量超出前六個月之累積產出量時，應暫時停止收受廢棄物；但經核發機關同意者，不在此限。第24條並定資源化產品應標示用途範圍、逐項逐筆記錄銷售流向並符合品質標準。",
 "When must a treatment organization suspend accepting waste due to stored products and derived waste?",
 ["When the stored volume exceeds the cumulative output of the previous six months, unless the issuing authority consents otherwise",
  "When the stored volume exceeds the cumulative output of the previous three months, unless filed with the issuing authority",
  "When the stored volume exceeds the cumulative output of the previous twelve months, with no exception provided at all",
  "When the stored volume exceeds the current month's cumulative output, unless the industry authority consents"],
 "Article 19."),

(WC,"第20條",2,"清處機構-契約書",
 "清除、處理機構從事業務前應與委託人訂定契約書，其保存及記載規定為何？",
 ["應事先訂定契約書並保存三年以備查驗，契約書應附有效許可證影本並記載廢棄物種類代碼性質數量、清除處理之工具設備方法頻率場所、委託期間及最終處置地點與數量等事項",
  "應事先訂定契約書並保存一年以備查驗，契約書應附有效許可證正本並記載廢棄物種類代碼性質數量、清除處理之工具設備方法頻率場所、委託期間及最終處置地點與數量等事項",
  "得於業務開始後補訂契約書並保存五年以備查驗，契約書僅需記載廢棄物之種類與數量及委託期間，其餘事項得由雙方自行約定而不受法規之限制拘束",
  "應事先訂定契約書並送核發機關核准後保存七年，契約書應附有效許可證影本並記載委託人之財務狀況、履約保證金金額、違約金計算方式及爭議處理程序等事項"],"a",
 "第20條第1項：清除、處理機構從事廢棄物清除、處理業務，應事先與委託人訂定契約書，並保存三年以備主管機關查驗；但受託清除、處理因天然災害或緊急事故產生之廢棄物者不在此限。第20條第2項：契約書應附有效許可證之影本並記載廢棄物之種類、代碼、性質及數量；清除或處理之工具、設備、方法、頻率、相關場所；委託期間；處理機構廢棄物之最終處置地點及數量；因故無法執行契約或突發事件之應變措施等事項。",
 "What are the rules on the contract with the entrusting party, its retention and its contents?",
 ["A contract must be made in advance and kept three years for inspection; it must attach a copy of the valid permit and state waste types, codes, properties and quantities, tools, equipment, methods, frequency and sites, the term, and final disposal sites and quantities",
  "A contract must be made in advance and kept one year for inspection; it must attach the original valid permit and state waste types, codes, properties and quantities, tools, equipment, methods, frequency and sites, the term, and final disposal sites and quantities",
  "A contract may be made after work begins and kept five years; it need only state waste types, quantities and the term, with all other matters left to the parties free of any legal requirement",
  "A contract must be approved by the issuing authority and kept seven years; it must attach a permit copy and state the client's finances, performance bond, liquidated damages and dispute procedures"],
 "Article 20."),

(WC,"第21-1條",1,"清處機構-收費登載",
 "處理機構經核准營運者，關於處理費用之收費範圍應如何辦理？",
 ["應將處理費用收費範圍於中央主管機關清除處理機構服務管理資訊系統登載，調整時亦同",
  "應將處理費用收費範圍報請直轄市、縣（市）主管機關核准後始得收取，調整時亦同",
  "應將處理費用收費範圍於機構網站及場（廠）門口公告揭示，調整時免再重新公告",
  "應將處理費用收費範圍列入與委託人之契約書即可，無須向任何主管機關辦理登載"],"a",
 "第21-1條：處理機構經核准營運者，應將處理費用收費範圍於中央主管機關清除處理機構服務管理資訊系統登載；調整時亦同。第23條並定應於設備、機具、設施或處理場（廠）明顯處標示機構名稱、聯絡電話及許可證字號。",
 "How must an approved treatment organization handle its fee scale?",
 ["Post the scope of treatment fees on the central authority's service management information system, and do the same whenever it is adjusted",
  "Obtain the municipal or county authority's approval of the scope of treatment fees before charging, and do the same whenever it is adjusted",
  "Publish the fee scope on its website and at the plant gate, with no need to republish when it is adjusted",
  "Simply include the fee scope in the contract with the entrusting party, with no filing to any competent authority"],
 "Article 21-1 (see also Article 23)."),

(WC,"第22條",1,"清處機構-條文刪除",
 "本辦法第22條之現況為何？",
 ["第22條業經刪除，現行辦法已無該條之規定","第22條規定清除機構之貯存場設置管理標準",
  "第22條規定處理機構之緊急應變計畫書內容","第22條規定清除車輛之即時追蹤系統設置"],"a",
 "第22條：（刪除）。現行辦法第三章管理之相關規定分別見於第17條移動式設施、第18條自行清除處理與容許差值、第19條暫停收受、第20條契約書、第21條申報與紀錄保存、第21-1條收費登載、第23條標示、第24條資源化產品、第25條技術員異動、第26條註銷與暫停營運、第27條撤銷廢止等條文。",
 "What is the current status of Article 22 of these Regulations?",
 ["Article 22 has been deleted and no longer appears in the Regulations","Article 22 prescribes storage yard standards for removal organizations",
  "Article 22 prescribes the contents of emergency response plans","Article 22 prescribes real-time tracking systems for removal vehicles"],
 "Article 22 (deleted)."),

(WC,"第23條",1,"清處機構-標示義務",
 "清除、處理機構應於何處標示何種資訊？",
 ["應於設備、機具、設施或處理場（廠）明顯處標示機構名稱、聯絡電話及許可證字號",
  "應於設備、機具、設施或處理場（廠）明顯處標示負責人姓名、統一編號及資本額",
  "應於清除車輛之車門兩側標示機構名稱、聯絡電話及專業技術人員之姓名與級別",
  "應於處理場（廠）大門及圍牆四周標示廢棄物種類代碼、每月許可量及收費標準"],"a",
 "第23條：清除、處理機構應於設備、機具、設施或處理場（廠）明顯處標示機構名稱、聯絡電話及許可證字號。此一標示義務便於主管機關及民眾辨識合法機構，與第21-1條收費範圍登載義務同屬透明化管理措施。",
 "What information must removal and treatment organizations display, and where?",
 ["The organization's name, contact phone number and permit number, in a conspicuous place on equipment, machinery, facilities or the treatment site",
  "The responsible person's name, tax ID number and paid-in capital, in a conspicuous place on equipment, machinery, facilities or the site",
  "The organization's name, contact phone number and the technicians' names and grades, on both doors of every removal vehicle",
  "Waste type codes, monthly permitted volumes and the fee schedule, on the site's main gate and around the perimeter wall"],
 "Article 23."),

(WC,"第24條",3,"清處機構-資源化產品",
 "處理機構產出資源化產品者，其記錄保存與網路申報規定為何？",
 ["銷售流向、對象、數量及用途應逐項逐筆記錄，相關紀錄及憑證應存放於許可證登記之場（廠）並妥善保存三年；並應於每月十日前主動連線至中央主管機關事業廢棄物申報及管理資訊系統申報",
  "銷售流向、對象、數量及用途應按季彙總記錄，相關紀錄及憑證應存放於機構登記之營業所並妥善保存一年；並應於每季首月十五日前主動連線至中央主管機關資訊系統辦理申報",
  "銷售流向、對象、數量及用途應逐項逐筆記錄，相關紀錄及憑證應送交核發機關集中保管並保存五年；並應於每年一月三十一日前主動連線至中央主管機關資訊系統辦理申報",
  "銷售流向、對象、數量及用途得由買受人自行記錄，相關紀錄及憑證應存放於負責人住所並妥善保存七年；並應於每月月底前主動連線至地方主管機關資訊系統辦理申報"],"a",
 "第24條第1項第2款：應逐項逐筆記錄資源化產品之銷售流向、對象、數量及用途；未直接售予最終使用者者，主管機關得要求記錄轉售流向及數量；相關紀錄及憑證應存放於許可證登記之場（廠）並妥善保存三年。第24條第1項第5款：應於每月十日前主動連線至中央主管機關事業廢棄物申報及管理資訊系統申報；因軟硬體故障無法於每月十日前完成申報者，應於一日內以傳真向直轄市、縣（市）主管機關報備並於修復完成一日內補行申報。第24條第1項第1款並定資源化產品應標示用途範圍。",
 "What are the record-keeping and online reporting rules for recycled products?",
 ["Sales flows, buyers, quantities and uses must be recorded item by item; records and vouchers kept at the permitted site for three years; and online reporting to the central authority's industrial waste system by the 10th of each month",
  "Sales flows, buyers, quantities and uses must be summarized quarterly; records and vouchers kept at the registered business office for one year; and online reporting to the central authority's system by the 15th of the first month of each quarter",
  "Sales flows, buyers, quantities and uses must be recorded item by item; records and vouchers submitted to the issuing authority for central custody for five years; and online reporting by 31 January each year",
  "Sales flows, buyers, quantities and uses may be recorded by the purchasers; records kept at the responsible person's residence for seven years; and online reporting to the local authority by month end"],
 "Article 24, paragraph 1, subparagraphs 1, 2 and 5."),

(WC,"第26條",2,"清處機構-註銷與暫停營運",
 "清除、處理機構自行終止業務或暫停營業時，應如何辦理？",
 ["自行終止業務或未於許可期限屆滿前申請展延者，應向核發機關申報註銷許可證；暫停營業在一個月以上者，應於滿一個月後十五日內向核發機關申報暫停營運",
  "自行終止業務或未於許可期限屆滿前申請展延者，應向核發機關申報註銷許可證；暫停營業在三個月以上者，應於滿三個月後三十日內向核發機關申報暫停營運",
  "自行終止業務或未於許可期限屆滿前申請展延者，其許可證自動失效而免辦理申報；暫停營業在一個月以上者，應於復業後十五日內向核發機關補行申報營運",
  "自行終止業務或未於許可期限屆滿前申請展延者，應向中央主管機關申報註銷許可證；暫停營業在六個月以上者，應於滿六個月後十五日內申報暫停營運"],"a",
 "第26條：清除、處理機構自行終止廢棄物清除、處理業務，或未於許可期限屆滿前申請展延者，應向核發機關申報註銷許可證；其暫停營業在一個月以上者，應於滿一個月後十五日內，向核發機關申報暫停營運。第14條第6項並定未於許可期限屆滿前申請展延者，其許可證於屆滿日起失其效力。",
 "How must an organization handle voluntary termination or suspension of business?",
 ["On terminating business or failing to seek renewal before expiry, it must file to cancel the permit; if business is suspended for a month or more, it must file a suspension within 15 days after that month",
  "On terminating business or failing to seek renewal before expiry, it must file to cancel the permit; if business is suspended for three months or more, it must file a suspension within 30 days after those three months",
  "On terminating business or failing to seek renewal, the permit lapses automatically with no filing needed; if suspended for a month or more, it files within 15 days after resuming",
  "On terminating business or failing to seek renewal, it must file cancellation with the central authority; if suspended for six months or more, it files within 15 days after those six months"],
 "Article 26."),

(WC,"第28條",1,"清處機構-條文刪除",
 "本辦法第28條之現況為何？",
 ["第28條業經刪除，現行辦法已無該條之規定","第28條規定清除處理機構之保證金繳納標準",
  "第28條規定許可證撤銷廢止後之複查作業","第28條規定機構評鑑分級與獎勵措施內容"],"a",
 "第28條：（刪除）。現行第四章附則自第29條起，分別規定外文文件之中文譯本（第29條）、中央委託機關核發之副知與分送（第30條）、封場復育計畫及資源化產品過渡規定（第31-2條）及施行日期（第32條）；第31條及第31-1條亦均已刪除。",
 "What is the current status of Article 28 of these Regulations?",
 ["Article 28 has been deleted and no longer appears in the Regulations","Article 28 prescribes deposit requirements for these organizations",
  "Article 28 prescribes re-inspection after a permit is revoked","Article 28 prescribes performance grading and incentive measures"],
 "Article 28 (deleted)."),

(WC,"第29條",1,"清處機構-外文文件",
 "本辦法所定之相關文件為外文者，應如何處理？",
 ["應檢附經駐外館處驗證或國內公證人認證之中文譯本；但提供之文件為英文者，得免附中文譯本",
  "應檢附經駐外館處驗證或國內公證人認證之中文譯本；不論該文件為何種語文均不得免附譯本",
  "應檢附由申請者自行翻譯並蓋章確認之中文譯本；但提供之文件為英文者，得免附中文譯本",
  "應檢附經目的事業主管機關核可之翻譯社中文譯本；但提供之文件為日文者，得免附中文譯本"],"a",
 "第29條：本辦法所定之相關文件為外文者，應檢附經駐外館處驗證或國內公證人認證之中文譯本；但提供之文件為英文者，得免附中文譯本。此規定使英文文件之申請成本降低，其他語文則須經驗證或認證。",
 "How must documents required under these Regulations that are in a foreign language be handled?",
 ["A Chinese translation authenticated by an overseas mission or a domestic notary must be attached; documents in English are exempt from the translation requirement",
  "A Chinese translation authenticated by an overseas mission or a domestic notary must be attached; no language is exempt from the translation requirement",
  "A Chinese translation prepared and stamped by the applicant must be attached; documents in English are exempt from the translation requirement",
  "A Chinese translation from a translation agency approved by the industry authority must be attached; documents in Japanese are exempt"],
 "Article 29."),

(WC,"第30條",2,"清處機構-副知與分送",
 "核發機關為中央主管機關委託之機關者，其核發許可證或同意設置文件應如何辦理？",
 ["應副知該清除機構或處理場（廠）所在地直轄市、縣（市）主管機關；該機構對第三章應許可、核准、備查、副知、檢具文件之規定，應分送核發機關及所在地主管機關",
  "應副知中央主管機關及目的事業主管機關；該機構對第三章應許可、核准、備查、副知、檢具文件之規定，僅需送交原核發機關而無須分送所在地主管機關",
  "應報請中央主管機關核准後始得核發許可證；該機構對第三章應許可、核准、備查、副知、檢具文件之規定，應一律逕送中央主管機關辦理後轉知地方",
  "應公告於中央主管機關指定之資訊網站；該機構對第三章應許可、核准、備查、副知、檢具文件之規定，得選擇送交核發機關或所在地主管機關其一"],"a",
 "第30條第1項：核發機關為中央主管機關委託之機關者，核發許可證或同意設置文件時，應副知該清除機構或處理場（廠）所在地直轄市、縣（市）主管機關。第30條第2項：經中央主管機關委託之機關核發許可證或同意設置文件之清除、處理機構，對於第三章有關應許可、核准、備查、副知、檢具文件之規定，應分送核發機關及該清除機構或處理場（廠）所在地直轄市、縣（市）主管機關。",
 "Where the issuing authority is an agency commissioned by the central authority, issuance of permits requires:",
 ["Copying the municipal or county authority where the organization or treatment site is located; and the organization must send Chapter III filings to both the issuing authority and that local authority",
  "Copying the central competent authority and the industry competent authority; and the organization need send its Chapter III filings only to the issuing authority, not to the local authority",
  "Obtaining the central authority's approval before issuing; and the organization must send all Chapter III filings to the central authority for onward notification",
  "Publishing on a website designated by the central authority; and the organization may send Chapter III filings to either the issuing authority or the local authority"],
 "Article 30."),

(WC,"第31條",1,"清處機構-條文刪除",
 "本辦法第31條之現況為何？",
 ["第31條業經刪除，現行辦法已無該條之規定","第31條規定許可證展延之過渡適用期間",
  "第31條規定清除處理機構之年度稽查頻率","第31條規定資源化產品之進出口管理事項"],"a",
 "第31條：（刪除）。第31-1條亦已刪除；現行附則中僅第31-2條保留過渡規定，即應檢具封場復育計畫者之期限，及一百十年九月十三日前已取得處理許可證之機構其資源化產品應於一百十二年一月一日前檢具符合附件五之文件。",
 "What is the current status of Article 31 of these Regulations?",
 ["Article 31 has been deleted and no longer appears in the Regulations","Article 31 prescribes a transitional period for permit renewals",
  "Article 31 prescribes the annual inspection frequency for organizations","Article 31 prescribes import and export control of recycled products"],
 "Article 31 (deleted)."),

(WC,"第31-1條",1,"清處機構-條文刪除",
 "本辦法第31-1條之現況為何？",
 ["第31-1條業經刪除，現行辦法已無該條規定","第31-1條規定機構負責人之消極資格限制",
  "第31-1條規定處理費用之上限與調整機制","第31-1條規定清除車輛 GPS 之資料保存期"],"a",
 "第31-1條：（刪除）。與第22條、第28條及第31條同屬已刪除之條文；現行辦法之附則實質規定為第29條外文文件、第30條副知分送、第31-2條過渡規定及第32條施行日期。",
 "What is the current status of Article 31-1 of these Regulations?",
 ["Article 31-1 has been deleted and no longer appears in the Regulations","Article 31-1 prescribes disqualifications for a responsible person",
  "Article 31-1 prescribes ceilings and adjustment of treatment fees","Article 31-1 prescribes the retention period for vehicle GPS data"],
 "Article 31-1 (deleted)."),

(WC,"第31-2條",2,"清處機構-過渡規定",
 "關於封場復育計畫及既有處理機構資源化產品之過渡規定為何？",
 ["應檢具封場復育計畫之處理機構，應依規定期限檢具送核發機關核准並納入許可文件；一百十年九月十三日前已取得處理許可證者，其資源化產品應於一百十二年一月一日前檢具符合附件五之文件送核准",
  "應檢具封場復育計畫之處理機構，應於營運終止後三年內檢具送核發機關備查即可；一百十年九月十三日前已取得處理許可證者，其資源化產品應於一百十五年一月一日前檢具符合附件五之文件送核准",
  "應檢具封場復育計畫之處理機構，應報請中央主管機關核定後公告於資訊網路；一百十年九月十三日前已取得處理許可證者，其資源化產品免再檢具符合附件五之文件而逕依原許可辦理",
  "應檢具封場復育計畫之處理機構，應於申請展延時一併提出並經專家學者審查；一百零一年十二月七日前已取得處理許可證者，其資源化產品應於一百十二年一月一日前檢具附件五文件"],"a",
 "第31-2條第1項：符合事業廢棄物貯存清除處理方法及設施標準第41條之3第2項規定，應檢具封場復育計畫之處理機構，應依其規定期限檢具封場復育計畫送核發機關核准，並納入許可文件。第31-2條第2項：本辦法中華民國一百十年九月十三日發布施行之日前已取得處理許可證之處理機構，產出之資源化產品符合第24條第1項第3款用途者，應於一百十二年一月一日前檢具符合附件五之文件送核發機關核准後納入許可文件。",
 "What are the transitional rules on closure restoration plans and existing organizations' recycled products?",
 ["Organizations required to file a closure restoration plan must submit it within the prescribed period for approval and inclusion in the permit; those permitted before 13 September 2021 had to file Annex 5 documents for their recycled products before 1 January 2023",
  "Organizations required to file a closure restoration plan may submit it for the record within three years after operations end; those permitted before 13 September 2021 must file Annex 5 documents for their recycled products before 1 January 2026 without any exception",
  "Such organizations must have the plan approved by the central authority and published online; those permitted before 13 September 2021 need not file Annex 5 documents at all",
  "Such organizations must submit the plan with their renewal application for expert review; those permitted before 7 December 2012 had to file Annex 5 documents before 1 January 2023"],
 "Article 31-2."),

(WC,"第32條",1,"清處機構-施行日",
 "公民營廢棄物清除處理機構許可管理辦法之施行日期規定為何？",
 ["本辦法自發布日施行，並未另定其他施行日期","本辦法自發布後六個月施行，另定有過渡條款",
  "本辦法自發布後一年施行，並溯及既往而適用","本辦法自中央主管機關另行公告之日起施行之"],"a",
 "第32條：本辦法自發布日施行。本辦法最近一次修正日期為民國一百十三年五月十七日；第14條第7項及第31-2條就修正施行前已取得同意設置文件或處理許可證者另定有個別期限，屬過渡條款而非施行日期之另定。",
 "The effective date rule of these Regulations is:",
 ["They take effect on the date of promulgation, with no separate date set","They take effect six months after promulgation, with transitional clauses",
  "They take effect one year after promulgation and apply retroactively","They take effect on a date separately announced by the central authority"],
 "Article 32."),
]
