# -*- coding: utf-8 -*-
# 第 10 批（E4）：資源循環推動法 第1條～第52條
C = "ENV-24"
Q = [

(C,"第1條",1,"資循法-立法目的",
 "資源循環推動法之立法目的為何？",
 ["為節約自然資源使用，促進資源循環，減少廢棄物產生，減輕環境負荷，建立永續發展之循環型社會","為有效清除處理廢棄物，改善環境衛生，維護國民健康，健全清除處理機構之管理制度","為管制污染物之排放，提升環境品質，保障農漁生產，確保產業永續經營之發展環境","為促進產業技術升級，擴大出口貿易金額，健全綠色金融體系，提高國家整體競爭力"],"a",
 "第1條：為節約自然資源使用，促進資源循環，減少廢棄物產生，減輕環境負荷，建立永續發展之循環型社會，特制定本法。第4條並定物質使用之優先順序原則；第5條課予事業於事業活動時應循之減量及資源循環原則；第6條則規定國民應減少資源消耗、延長產品使用年限。",
 "What is the legislative purpose of the Resource Circulation Promotion Act?",
 ["To save natural resources, promote resource circulation, reduce waste generation, ease environmental burden and build a sustainable circular society","To effectively clear and treat waste, improve environmental sanitation, safeguard public health and strengthen management of clearance institutions","To control pollutant emissions, raise environmental quality, protect farming and fishing and secure a sustainable business environment","To upgrade industrial technology, expand export value, strengthen green finance and raise overall national competitiveness"],
 "Article 1, read with Articles 4 to 6."),

(C,"第2條",1,"資循法-主管機關",
 "本法所稱主管機關，在中央、直轄市及縣（市）分別為何機關？",
 ["在中央為環境部；在直轄市為直轄市政府；在縣（市）為縣（市）政府","在中央為經濟部；在直轄市為直轄市環境保護局；在縣（市）為縣（市）環保局","在中央為國家科學及技術委員會；在直轄市為直轄市經發局；在縣（市）為工商科","在中央為行政院；在直轄市為直轄市建設局；在縣（市）為鄉（鎮、市）公所"],"a",
 "第2條：本法所稱主管機關，在中央為環境部，在直轄市為直轄市政府，在縣（市）為縣（市）政府。第47條並規定本法所定之處罰除另有規定外，由直轄市或縣（市）主管機關為之。第9條則就中央有關機關推動資源循環之權責事項分列十一款分工。",
 "Who are the competent authorities at central, special municipality and county or city level?",
 ["The Ministry of Environment centrally; the special municipality government; the county or city government","The Ministry of Economic Affairs centrally; the municipal environmental bureau; the county environmental bureau","The National Science and Technology Council centrally; the municipal economic bureau; the county commerce section","The Executive Yuan centrally; the municipal construction bureau; the township or city office"],
 "Article 2, read with Articles 9 and 47."),

(C,"第3條",2,"資循法-用詞定義",
 "本法所稱再生資源、再使用及再生利用之定義分別為何？",
 ["再生資源指原效用減失而具經濟及循環技術可行性並經公告核准者；再使用指未改變原形態直接重複使用或恢復功用後使用；再生利用指改變原形態或與其他物質結合供作材料燃料","再生資源指尚未失去原效用之庫存物料；再使用指將物質送回原製程當作原料使用；再生利用指將物質委託清除機構運至掩埋場或焚化廠進行最終處置之行為","再生資源指經檢驗合格之進口原料；再使用指將產品拆解後取出可用零件販售；再生利用指將廢棄物經中間處理後送往海洋棄置之處理行為","再生資源指經環保標章認證之綠色產品；再使用指延長產品保固年限之服務；再生利用指提供維修服務及設置維修站點之營業行為"],"a",
 "第3條列六款定義：再生資源指原效用減失之物質，具經濟及循環利用技術可行性，並依本法公告或核准再使用或再生利用者；循環利用指再生資源再使用或再生利用之行為；再使用指未改變原物質形態，將再生資源直接重複使用或經過適當程序恢復原功用或部分功用後使用之行為；再生利用指改變原物質形態或與其他物質結合，供作為材料、燃料、肥料、飼料、填料、土壤改良等用途；事業及再生產品亦分別定義。",
 "How does the Act define renewable resources, re-use and recycling?",
 ["Renewable resources lost their utility but are economically and technically circulable and duly announced; re-use keeps the original form for repeated or restored use; recycling changes the form for use as material","Renewable resources are stock materials that retain their utility; re-use means returning material to the original process as feedstock; recycling means sending material to landfill or incineration for final disposal","Renewable resources are imported materials that passed inspection; re-use means dismantling products and selling usable parts; recycling means ocean dumping after intermediate treatment","Renewable resources are eco-labelled green products; re-use means extending the product warranty period; recycling means offering repair services and repair station networks"],
 "Article 3, subparagraphs 1 to 6."),

(C,"第4條",2,"資循法-優先順序",
 "為達成資源永續利用，對於物質之使用應依何種順序考量？有何例外？",
 ["應優先考量減少產生廢棄物，失去原效用後依序考量再使用、再生利用、能源回收及妥善處理；但經生命週期考量可得最佳環境效益者不在此限","應優先考量能源回收，其次再生利用、再使用及減少產生廢棄物，最後始考量妥善處理；但經目的事業主管機關核准者不在此限","應優先考量妥善處理，其次減少產生廢棄物、能源回收及再使用，最後始考量再生利用；但經地方議會決議同意者不在此限","應優先考量再生利用，其次能源回收、妥善處理及再使用，最後始考量減少產生廢棄物；但經環境影響評估通過者不在此限"],"a",
 "第4條：為達成資源永續利用，在可行之技術及經濟為基礎下，對於物質之使用，應優先考量減少產生廢棄物，失去原效用後應依序考量再使用，其次物質再生利用、能源回收及妥善處理；但經生命週期考量，可得最佳整體環境效益者，不在此限。第5條並就事業訂有五款應循之原則；第30條規定再生資源未依規定循環利用者視為廢棄物，應依廢棄物清理法回收清除處理。",
 "In what order must materials be considered for sustainable resource use, and what exception applies?",
 ["Waste reduction first, then re-use, recycling, energy recovery and proper treatment; unless a life cycle assessment shows a better overall benefit","Energy recovery first, then recycling, re-use and waste reduction, and proper treatment last; unless the industry authority approves otherwise","Proper treatment first, then waste reduction, energy recovery and re-use, and recycling last; unless the local council resolves otherwise","Recycling first, then energy recovery, proper treatment and re-use, and waste reduction last; unless an environmental impact assessment is passed"],
 "Article 4, read with Articles 5 and 30."),

(C,"第5條",3,"資循法-事業義務",
 "事業於進行事業活動時，應循哪些原則以減少資源消耗、抑制廢棄物產生及促進資源循環？",
 ["選用清潔生產技術；對原料使用採取減少廢棄物產生之必要措施；原材料失去原效用後應自行或供循環利用；製造販賣物品容器之事業有責任提升產品耐用年限及落實修繕服務；網路交易平台服務提供者應訂定並執行相關管理機制","選用最低成本之生產技術；對原料使用採取增加庫存周轉之措施；原材料失去原效用後應一律委外掩埋；製造販賣物品容器之事業僅須依約履行保固；網路交易平台服務提供者無須訂定任何管理機制","選用經認證之進口製程設備；對原料使用採取分散採購來源之措施；原材料失去原效用後應報請主管機關指定去向；製造販賣物品容器之事業應加倍收取押金；網路交易平台服務提供者應代收回收清除處理費","選用符合國家標準之原料；對原料使用採取提高單位產出之措施；原材料失去原效用後應優先辦理出口；製造販賣物品容器之事業應設置專責單位；網路交易平台服務提供者應公開全部交易紀錄"],"a",
 "第5條列五款：選用清潔生產技術；對於原料之使用應採取減少廢棄物產生之必要措施；原材料失去原效用後應自行或供循環利用，無法循環利用者應進行能源回收或妥善處理；從事物品、容器之製造、販賣之事業，有責任提升產品耐用年限及落實修繕服務，並應朝促使產品利於資源循環之方向進行研發、設計及標示材質種類；從事網路交易平台服務提供者應訂定並執行相關管理機制，促使並引導利用其平台交易之事業或個人落實包裝減量及促進資源循環。",
 "Which principles must enterprises follow to cut resource use and promote circulation?",
 ["Adopt cleaner production technology; take measures to cut waste from raw material use; circulate materials that lose utility; makers and sellers must extend durability and offer repairs; platform providers must run management mechanisms","Adopt the lowest cost production technology; take measures to increase inventory turnover; landfill materials that lose utility; makers and sellers need only honour warranties; online platform providers need no management mechanism","Adopt certified imported process equipment; diversify raw material sourcing; report materials that lose utility for the authority to direct; makers and sellers must double deposits; online platform providers must collect recycling fees","Adopt raw materials meeting national standards; raise output per unit of material; export materials that lose utility first; makers and sellers must set up dedicated units; online platform providers must publish all transaction records"],
 "Article 5, subparagraphs 1 to 5."),

(C,"第6條",1,"資循法-國民義務",
 "本法就國民於資源循環方面之義務，定有何種規定？",
 ["國民應減少資源之消耗，抑制廢棄物之產生，儘可能延長產品使用年限，使用促進資源循環之產品或服務","國民應每月申報家戶垃圾產生量，並將回收物送交指定地點，違者由主管機關處以罰鍰","國民應優先購買本國製造之產品，並拒絕使用一切進口包裝材料，以扶植國內循環產業","國民應參與主管機關辦理之資源循環教育訓練每年四小時，並取得結業證書後始得申請補助"],"a",
 "第6條：國民應減少資源之消耗，抑制廢棄物之產生，儘可能延長產品使用年限，使用促進資源循環之產品或服務。本條屬宣示性規定，未定有罰則。第32條第3項並規定主管機關及各目的事業主管機關應辦理促進產品回收及延長使用技術、優先採購綠色產品或服務相關之教育推廣活動。",
 "What duty does the Act place on citizens regarding resource circulation?",
 ["Citizens should reduce resource use, curb waste, extend product life as far as possible and use products or services that promote circulation","Citizens must report household waste volumes monthly and deliver recyclables to designated points, with fines for failure to do so","Citizens should buy domestically made products first and refuse all imported packaging so as to foster the domestic circular industry","Citizens must attend four hours of resource circulation training each year and hold a certificate before applying for any subsidy"],
 "Article 6, read with Article 32, paragraph 3."),

(C,"第7條",1,"資循法-委任委託",
 "主管機關及目的事業主管機關就本法規定之查核、審查、宣導、訓練、輔導、評鑑、獎勵、補助及研究相關事宜，得為何種處置？",
 ["得委任所屬機關（構）、委託或委辦其他機關（構）、法人或團體辦理","得逕行成立行政法人並移撥全部預算及人員專責辦理各該事宜","得要求受查核之事業自行僱用第三方機構辦理並負擔全部費用","得指定各級學校及研究機構無償代為執行查核及裁處相關事宜"],"a",
 "第7條：主管機關及目的事業主管機關得委任所屬機關（構）、委託或委辦其他機關（構）、法人或團體，辦理本法規定之查核、審查、宣導、訓練、輔導、評鑑、獎勵、補助及研究相關事宜。第8條並規定主管機關或目的事業主管機關得派員攜帶證明文件進入公私場所實施檢查或令其提供有關資料，受檢查者不得規避、妨礙或拒絕。",
 "What may the authorities do about inspection, review, training, guidance, appraisal, incentives, subsidies and research under the Act?",
 ["They may delegate to subordinate agencies, or commission other agencies, juridical persons or organizations","They may set up an administrative juridical person and transfer all budget and staff to it for these matters","They may require the inspected enterprise to hire a third party itself and bear all the costs","They may designate schools and research institutes to carry out inspection and penalty work free of charge"],
 "Article 7, read with Article 8."),

(C,"第8條",2,"資循法-檢查權",
 "主管機關或目的事業主管機關得進入公私場所實施何種檢查？受檢查者及有關機關團體之義務為何？",
 ["得實施資源循環相關產品、服務、營建工程、包裝容器製造輸入販賣及再生資源、創新實驗之檢查，或令其提供資料；受檢查者不得規避拒絕，並得請求有關機關團體協助","得實施勞工作業環境監測及健康檢查紀錄之查核，或令其提供員工個人資料；受檢查者得以營業秘密為由拒絕提供，主管機關不得請求任何機關協助提供資料","得實施財務報表及關係人交易之查核，或令其提供銀行往來明細；受檢查者僅於取得法院搜索票時始負配合義務，其餘情形均得拒絕檢查","得實施空氣污染物排放濃度及放流水水質之採樣檢測，或令其提供操作許可證；受檢查者得要求主管機關先行預約時間，未預約者得拒絕受檢"],"a",
 "第8條第1項：主管機關或目的事業主管機關得派員攜帶證明文件，進入公私場所，實施本法所定資源循環相關產品、服務、營建工程、物品、包裝、容器製造、輸入、販賣、使用情形及再生資源、創新實驗運作或執行之檢查，或令其提供有關資料，受檢查者不得規避、妨礙或拒絕。第2項：主管機關或目的事業主管機關為實施前項之檢查，得請求有關機關（構）、法人、團體協助或提供必要之資料。第40條第1款規定規避妨礙或拒絕檢查者處新臺幣一萬二千元以上十五萬元以下罰鍰。",
 "What inspections may the authorities carry out, and what duties do those inspected bear?",
 ["Inspection of circulation-related products, services, works, packaging, renewable resources and innovation experiments, or demands for data; those inspected may not refuse, and agencies may assist","Inspection of workplace monitoring and health check records, or demands for employee personal data; those inspected may refuse citing trade secrets, and no agency may be asked to assist","Inspection of financial statements and related party transactions, or demands for bank records; those inspected must cooperate only under a court search warrant and may otherwise refuse","Sampling of air pollutant concentrations and effluent quality, or demands for operating permits; those inspected may require an appointment and refuse unannounced inspections"],
 "Article 8, paragraphs 1 and 2, with Article 40."),

(C,"第9條",3,"資循法-機關分工",
 "中央有關機關推動資源循環之權責分工，下列何者正確？",
 ["能源、製造及商業部門由經濟部主辦；科學園區由國家科學及技術委員會主辦；運輸部門由交通部主辦；農業部門由農業部主辦；建築部門由內政部主辦","能源、製造及商業部門由環境部主辦；科學園區由經濟部主辦；運輸部門由內政部主辦；農業部門由衛生福利部主辦；建築部門由交通部主辦","能源、製造及商業部門由金融監督管理委員會主辦；科學園區由農業部主辦；運輸部門由經濟部主辦；農業部門由內政部主辦；建築部門由環境部主辦","能源、製造及商業部門由國家科學及技術委員會主辦；科學園區由交通部主辦；運輸部門由農業部主辦；農業部門由經濟部主辦；建築部門由衛生福利部主辦"],"a",
 "第9條列十一款分工：能源、製造及商業部門由經濟部主辦；科學園區由國家科學及技術委員會主辦；運輸部門由交通部主辦；農業部門由農業部主辦；建築部門由內政部主辦；工程部門由各工程中央目的事業主管機關主辦；環境部門由環境部主辦；綠色金融由金融監督管理委員會及環境部主辦；科技研發及推動由國家科學及技術委員會及環境部主辦；衛生福利部門由衛生福利部主辦；其他資源循環事項由中央主管機關報請行政院指定。各款均由各中央目的事業主管機關協辦。",
 "Which division of central agency responsibilities for resource circulation is correct?",
 ["Energy, manufacturing and commerce led by Economic Affairs; science parks by the National Science and Technology Council; transport by Transportation; agriculture by Agriculture; building by the Interior","Energy, manufacturing and commerce led by the Ministry of Environment; science parks by Economic Affairs; transport by the Interior; agriculture by Health and Welfare; building by Transportation","Energy, manufacturing and commerce led by the Financial Supervisory Commission; science parks by Agriculture; transport by Economic Affairs; agriculture by the Interior; building by Environment","Energy, manufacturing and commerce led by the National Science and Technology Council; science parks by Transportation; transport by Agriculture; agriculture by Economic Affairs; building by Health and Welfare"],
 "Article 9, subparagraphs 1 to 11."),

(C,"第10條",1,"資循法-輔導培育",
 "目的事業主管機關就源頭減量及資源循環推動機制，負有何種義務？",
 ["應輔導事業規劃導入源頭減量及資源循環推動機制，並培育資源循環技術研發人才及推廣教育","應逕行代事業規劃設置全部循環利用設施，並負擔其設置及營運所需之全部費用","應每年對事業實施強制性技術檢定，未通過者即命其停工並廢止其工廠登記","應統一採購循環設備配發各事業使用，並指派公務人員常駐事業內部監督營運"],"a",
 "第10條：目的事業主管機關應輔導事業規劃導入源頭減量及資源循環推動機制，並培育資源循環技術研發人才及推廣教育。第13條第3項並規定中央目的事業主管機關應依綠色設計原則檢討所主管之相關法令並輔導事業遵行；第34條第1項則就事業或個人辦理相關技術開發、人才培訓、實際運用執行與管理績效優良者定有獎勵或補助規定。",
 "What duty does the industry authority bear regarding source reduction and circulation mechanisms?",
 ["It must guide enterprises in adopting source reduction and circulation mechanisms, and cultivate talent and promote education","It must plan and build all circulation facilities for enterprises itself and bear all construction and operating costs","It must run compulsory annual technical assessments and shut down and deregister enterprises that fail","It must centrally procure circulation equipment for enterprises and station civil servants inside them to supervise"],
 "Article 10, read with Articles 13 and 34."),

(C,"第11條",3,"資循法-資源循環計畫",
 "國家整體資源循環計畫應由何機關擬訂、報請何機關核定？其檢討頻率為何？地方應擬訂何種計畫？",
 ["由中央主管機關會商中央目的事業主管機關擬訂，報請行政院核定後實施並公開，至少每五年檢討一次；地方主管機關應依該計畫擬訂行動計畫，報請中央主管機關核定","由中央目的事業主管機關擬訂，報請立法院審議通過後實施，至少每十年檢討一次；直轄市、縣（市）主管機關應依該計畫擬訂年度預算書，報請地方議會審議通過後實施","由行政院逕行擬訂並公告實施，無須報請任何機關核定，至少每三年檢討一次；直轄市、縣（市）主管機關應依該計畫擬訂環境影響評估報告，報請中央主管機關備查","由資源循環推動會擬訂並自行核定實施，無須對外公開，至少每二年檢討一次；直轄市、縣（市）主管機關應依該計畫擬訂自治條例，報請行政院核定後施行"],"a",
 "第11條第1項：中央主管機關應依我國環境狀況、資源循環目標，參酌國際現況與國內情勢變化及第9條分工事項，會商中央目的事業主管機關擬訂國家整體資源循環計畫，報請行政院核定後實施，並對外公開，且至少每五年檢討一次。第2項：中央主管機關應綜整各中央目的事業主管機關推動情形，每年編寫資源循環推動成果報告，報請行政院核定後對外公開。第3項：直轄市、縣（市）主管機關應擬訂行動計畫，報請中央主管機關核定後實施並對外公開，且至少每五年檢討一次。第4項：地方應每年編寫行動計畫成果報告並對外公開。",
 "Who drafts the national resource circulation plan, who approves it, how often is it reviewed, and what must local authorities prepare?",
 ["The central authority drafts it with the industry authorities and the Executive Yuan approves it, reviewed every five years; local authorities prepare action plans approved centrally","The central industry authority drafts it and the Legislative Yuan approves it, reviewed at least every ten years; local authorities prepare annual budgets approved by the local council","The Executive Yuan drafts and announces it without any other approval, reviewed at least every three years; local authorities prepare environmental impact reports filed centrally","The promotion committee drafts and approves it itself without publication, reviewed at least every two years; local authorities enact self-government ordinances approved by the Executive Yuan"],
 "Article 11, paragraphs 1 to 4."),

(C,"第12條",3,"資循法-推動會",
 "資源循環推動會之召集人由何人擔任？其委員任期及組成比例規定為何？",
 ["召集人一人由環境部部長擔任；委員任期二年，政府代表應由副首長以上擔任，學者專家及環保團體代表不得少於二分之一，環保團體代表不得少於整體四分之一","召集人一人由行政院院長擔任；委員任期三年，政府機關代表應由首長親自擔任，學者專家及環境保護團體代表不得少於三分之一，環境保護團體代表不得少於整體之五分之一","召集人一人由經濟部部長擔任；委員任期四年，政府機關代表得由科長級以上人員擔任，學者專家代表不得少於四分之一，環境保護團體代表不得少於整體之三分之一","召集人一人由中央主管機關指派之次長擔任；委員任期一年，政府機關代表不受職級限制，學者專家及環境保護團體代表合計不得多於二分之一"],"a",
 "第12條第1項：中央主管機關為執行第11條第1項至第3項職權，應組成資源循環推動會，負責召集、督導相關部會研議、協商、評估、整合、制定及推動資源循環政策、措施。第2項：推動會置召集人一人，由環境部部長擔任；委員任期二年，由相關政府機關、學者、專家及環境保護團體代表組成，其中政府機關代表應由副首長以上主管擔任，學者、專家及環境保護團體代表不得少於二分之一，環境保護團體代表不得少於推動會整體之四分之一。第3項：推動會之會議紀錄應對外公開，但涉及國家機密或營業秘密者不在此限。",
 "Who convenes the resource circulation promotion committee, and what are the member terms and composition ratios?",
 ["The Minister of Environment convenes it; members serve two years, government representatives must be deputy heads or above, scholars and environmental groups at least half, and the latter at least a quarter","The Premier convenes it; members serve three years, government representatives must be agency heads in person, scholars and environmental groups at least a third, and environmental groups at least a fifth","The Minister of Economic Affairs convenes it; members serve four years, government representatives may be section chiefs or above, scholars at least a quarter, and environmental groups at least a third","A deputy minister designated centrally convenes it; members serve one year, government representatives face no rank limit, and scholars and environmental groups together no more than half"],
 "Article 12, paragraphs 1 to 3."),

(C,"第13條",3,"資循法-綠色設計原則",
 "中央主管機關規劃之產品及營建工程綠色設計原則，應包括哪些項目？",
 ["使用單一、易於分解或資源循環之材質；使用一定比率之再生粒（材）料；易維修、可升級或提升耐用性；禁止或限制使用有害環境物質；營建工程現場分類減量","使用進口高單價材質；使用一定比率之天然原生材料；提高產品更換頻率以刺激消費；鼓勵使用具揮發性之有機溶劑；營建工程集中委外處理全部廢棄物","使用複合多層之防護材質；使用一定比率之石化衍生材料；縮短產品保固年限；限制產品維修管道以維護品牌；營建工程一律採全面拆除重建方式","使用符合國際標準之包裝材質；使用一定數量之進口再生料；增加產品功能複雜度；強制回收全部舊品；營建工程應優先採用海洋棄置方式處理"],"a",
 "第13條第1項列六款綠色設計原則：使用單一、易於分解、拆解或資源循環之材質；使用一定比率或數量之再生粒（材）料；易維修、可升級或提升耐用性；禁止或限制使用有害環境物質；營建工程源頭現場分類減少廢棄物；其他於生命週期節約能資源使用及減少廢棄物之設計。第2項：中央主管機關應就綠色設計原則之內容、項目及其他相關事項訂定綠色設計準則。第3項：中央目的事業主管機關應依綠色設計原則檢討所主管之相關法令並輔導事業遵行。",
 "What items must the green design principles for products and construction works cover?",
 ["Single materials easy to break down or circulate; a set ratio of recycled granules or materials; easy repair, upgradability or durability; banning environmentally harmful substances; on-site sorting to cut construction waste","Imported high value materials; a set ratio of natural virgin materials; more frequent product replacement to stimulate demand; use of volatile organic solvents; centralised outsourcing of all construction waste","Multi-layer composite protective materials; a set ratio of petrochemical derived materials; shorter warranty periods; restricted repair channels to protect the brand; full demolition and rebuilding for construction works","Packaging meeting international standards; a set quantity of imported recycled material; greater functional complexity; compulsory take-back of all old goods; ocean dumping as the preferred construction route"],
 "Article 13, paragraphs 1 to 3."),

(C,"第14條",3,"資循法-循環標誌核定",
 "中央主管機關指定公告一定種類、規模之產品應遵行綠色設計準則者，其製造、輸入業者應如何辦理？",
 ["應於公告所定期限檢具產品綠色設計文件向中央主管機關申請核定符合綠色設計準則及發給循環標誌；非屬指定公告之產品，其業者得自願遵行並申請核定及發給標誌","應於公告所定期限向中央目的事業主管機關報備並繳納規費即可，無須申請任何核定；非屬指定公告之產品，其業者不得自願申請遵行綠色設計準則","應於產品上市前逐批送請認證機構檢驗並取得合格報告；非屬指定公告之產品，其業者應由地方主管機關逐案指定是否須遵行綠色設計準則","應於每年度終了後三個月內提報綠色設計執行成果送地方主管機關備查；非屬指定公告之產品，其業者應一律比照指定產品辦理申請核定"],"a",
 "第14條第1項：中央主管機關得指定公告一定種類、規模之產品應遵行綠色設計準則指定項目，其製造、輸入業者應於公告所定期限檢具產品綠色設計文件向中央主管機關申請核定符合綠色設計準則及發給循環標誌。第2項：非屬指定公告之產品，其製造、輸入業者得自願遵行並申請核定及發給循環標誌。第3項：應使用一定比率或數量再生粒（材）料者，應提送來源、使用總量、產品產量及銷量等資料，經認可之驗證方式或機構查驗後報中央主管機關備查。第38條第1項第1款定有罰則；第52條並定第14條自公布後二年施行。",
 "What must makers and importers of designated products do under the green design rules?",
 ["File green design documents centrally within the announced period for approval and a circulation mark; makers of non-designated products may do so voluntarily","File with the central industry authority and pay fees within the announced period without any approval; makers of non-designated products may not volunteer to follow the rules","Send each batch to a certification body for testing before launch; for non-designated products the local authority decides case by case whether the rules apply","File annual green design results with the local authority within three months of each year end; makers of non-designated products must apply exactly as designated ones do"],
 "Article 14, paragraphs 1 to 3, with Articles 38 and 52."),

(C,"第15條",2,"資循法-營建工程設計",
 "中央主管機關得指定公告一定規模之營建工程遵行綠色設計準則者，其義務主體及配合機關之義務為何？",
 ["工程主辦機關或起造人應於規劃設計及施工階段遵行綠色設計準則指定項目；各工程中央目的事業主管機關應依該指定項目檢討設計施工技術及作業規範","承包廠商及分包廠商應於投標階段承諾遵行綠色設計準則；各工程中央目的事業主管機關應逕行修訂契約範本並要求全面適用於既有工程","監造建築師及技師應於竣工階段查核綠色設計準則之落實；各工程中央目的事業主管機關應委託公會辦理查核並收取查核費用","材料供應商及設備製造商應於供料階段檢附綠色設計證明；各工程中央目的事業主管機關應建立供應商黑名單並公告於指定網站"],"a",
 "第15條第1項：中央主管機關得指定公告一定規模之營建工程，其工程主辦機關或起造人應於規劃設計及施工階段遵行綠色設計準則指定項目。第2項：各工程中央目的事業主管機關應依前項指定項目，檢討營建工程設計施工技術及作業規範相關規定。第38條第2項規定營建工程之工程主辦機關或起造人違反第15條第1項所定公告者，處新臺幣六萬元以上三十萬元以下罰鍰；尚未施工者並通知限期提出改善計畫，屆期未依核定期程內容執行者按次處罰，必要時得令其停工。",
 "Who must follow the green design rules for designated construction works, and what must the works authority do?",
 ["The works agency or building owner must follow the designated items at the planning and construction stages; each central works authority must review its operating specifications","Contractors and subcontractors must undertake compliance at the tender stage; each central works authority must revise contract templates and apply them to all existing works","Supervising architects and engineers must verify compliance at completion; each central works authority must have trade associations carry out checks and charge fees","Material and equipment suppliers must furnish green design certificates on delivery; each central works authority must maintain and publish a supplier blacklist"],
 "Article 15, paragraphs 1 and 2, with Article 38, paragraph 2."),

(C,"第16條",2,"資循法-重複使用計畫",
 "中央主管機關指定公告物品或其包裝、容器重複使用目標及方式者，其業者應如何辦理？",
 ["其製造、輸入或販賣業者應於公告所定期限檢具重複使用計畫申請中央主管機關核准，並應提送執行成果報中央主管機關備查","其製造、輸入或販賣業者應於公告所定期限向地方主管機關報備並繳納保證金，執行成果無須提報任何機關備查","其製造、輸入或販賣業者應於每次販售時向消費者收取押金，並將押金全數解繳資源循環基金專戶保管運用","其製造、輸入或販賣業者應於公告後一年內全面停止生產該類物品，並將既有庫存全數退運出口或銷毀"],"a",
 "第16條第1項：中央主管機關得指定公告物品或其包裝、容器重複使用目標及方式，其製造、輸入或販賣業者應於公告所定期限檢具重複使用計畫申請中央主管機關核准，並應提送執行成果報中央主管機關備查。第2項：非屬指定公告者得自願檢具重複使用計畫送核准並提送執行成果備查。第3項：重複使用計畫應記載事項、申請應備文件、審查、核准事項、管理、變更、廢止、執行成果備查等辦法由中央主管機關定之。第42條第1款及第44條第1款分別就製造輸入業者及販賣業者定有罰則。",
 "What must businesses do where reuse targets and methods are announced for goods, packaging or containers?",
 ["Makers, importers or sellers must file a reuse plan for central authority approval within the announced period and submit implementation results for the record","Makers, importers or sellers must file with the local authority and post a bond within the announced period, with no need to report results to any authority","Makers, importers or sellers must collect a deposit at each sale and remit all deposits to a resource circulation fund account for custody","Makers, importers or sellers must stop producing such goods within one year of the announcement and re-export or destroy all existing stock"],
 "Article 16, paragraphs 1 to 3, with Articles 42 and 44."),

(C,"第17條",2,"資循法-減量計畫",
 "中央主管機關指定公告物品或其包裝、容器減量目標及方式者，指定事業應如何辦理？",
 ["指定事業應於公告所定期限檢具減量計畫申請中央主管機關核准，並應提送執行成果報中央主管機關備查","指定事業應於公告所定期限檢具減量計畫送地方議會決議通過，並將執行成果登載於公司網站即可","指定事業應於公告所定期限完成減量目標並自行留存紀錄，無須申請核准亦無須提送任何執行成果","指定事業應於公告所定期限委託會計師查核減量成果並出具簽證報告，送中央目的事業主管機關核定"],"a",
 "第17條第1項：中央主管機關得指定公告物品或其包裝、容器減量目標及方式，指定事業應於公告所定期限檢具減量計畫申請中央主管機關核准，並應提送執行成果報中央主管機關備查。第2項：非屬指定公告者，其製造、輸入或販賣業者得自願檢具減量計畫送核准並提送執行成果備查。第3項：減量計畫應記載事項、申請應備文件、審查、核准事項、管理、變更、廢止及執行成果備查等辦法由中央主管機關定之。第42條第2款定有新臺幣六千元以上十五萬元以下罰鍰。",
 "What must designated enterprises do where reduction targets and methods are announced?",
 ["They must file a reduction plan for central authority approval within the announced period and submit implementation results for the record","They must have the reduction plan passed by the local council within the announced period and merely post results on the company website","They must meet the reduction target within the announced period and keep records themselves, without approval or any results reporting","They must have accountants audit the reduction results and file an attested report with the central industry authority for approval"],
 "Article 17, paragraphs 1 to 3, with Article 42."),

(C,"第18條",3,"資循法-禁限制使用",
 "物品或其包裝、容器有何種情形，中央主管機關得禁止或限制製造、輸入、販賣、使用？地方得否加嚴？",
 ["過度耗用能資源、含長期不易腐化成分、含有害物質、有回收困難之虞、有嚴重污染環境之虞；地方主管機關得視環境治理條件訂定較中央更嚴格之自治法規，報請中央核定","價格低於同類進口產品、含高比例再生材料、經消費者投訴達一定件數、市場占有率超過一定比例、業者資本額未達一定金額；地方主管機關不得訂定任何較中央更嚴格之管制措施","製造流程耗用人力過多、包裝色彩過於鮮豔、標示文字未使用中文、未取得環保標章使用權、未加入生產者責任組織；地方主管機關僅得建議中央加嚴而不得自行訂定","經檢驗不符國家標準、產地標示不明、未投保產品責任險、未設置維修站點、未提供一定保固年限；地方主管機關得逕行公告加嚴而無須報請中央核定"],"a",
 "第18條第1項列五款情形。第2項：禁止、限制之方式與範圍、各款情形之認定、資料備查等由中央主管機關公告之。第3項：直轄市、縣（市）主管機關得視環境治理條件差異，就限制製造、輸入、販賣、使用之管制對象、項目、期限、減量、限制使用方式，訂定較前項公告更加嚴格之自治法規或管制措施，報請中央主管機關核定。第4項：不符公告或自治法規者，地方主管機關得令業者將產品下架、銷毀、退運或為其他適當處置。第39條定有罰則。",
 "On what grounds may the central authority ban or restrict goods, packaging or containers, and may local rules be stricter?",
 ["Excessive energy or resource use, slow-decaying components, hazardous components, difficult recovery, or serious pollution risk; local authorities may set stricter ordinances for local conditions, approved centrally","Prices below comparable imports, a high recycled content, a set number of consumer complaints, market share above a threshold, or capital below a threshold; local authorities may never set stricter measures","Labour-intensive processes, overly bright packaging colours, labels not in Chinese, no eco-label right, or no producer responsibility membership; local authorities may only recommend stricter central rules","Failing national standards, unclear origin labelling, no product liability insurance, no repair stations, or no minimum warranty; local authorities may announce stricter rules without central approval"],
 "Article 18, paragraphs 1 to 4, with Article 39."),

(C,"第19條",2,"資循法-包裝減量",
 "中央主管機關得就物品之運輸或販賣包裝指定公告哪些事項？輸入業者有何義務？",
 ["得指定公告減量目標、空間比例、層數、材質種類及數量，其製造、運輸、販賣業者應依公告辦理；輸入業者銷售該物品時之包裝應符合該公告規定","得指定公告包裝之圖樣設計、色彩配比及字體大小，其製造業者應依公告事項辦理；輸入業者僅須於報關時申報包裝重量而無須符合任何包裝規定","得指定公告包裝之售價上限及利潤率，其販賣業者應依公告事項辦理；輸入業者應於輸入前取得中央主管機關個案核准始得銷售該物品","得指定公告包裝之保固年限及維修據點數量，其運輸業者應依公告事項辦理；輸入業者應將全部包裝材料退運回原輸出國處理"],"a",
 "第19條第1項：中央主管機關得指定公告物品之運輸或販賣包裝之減量目標、空間比例、層數、使用材質之種類及數量，其製造、運輸、販賣業者應依公告事項辦理。第2項：前項業者應將辦理減量成果報告報中央主管機關備查；其備查程序、提報方式、期限、應記載事項等由中央主管機關公告之。第3項：輸入業者輸入第1項指定公告物品者，其於銷售該物品時之包裝應符合該項公告之規定。第42條第3款及第44條第2款分別定有罰則。",
 "What may the central authority announce about transport or sales packaging, and what duty falls on importers?",
 ["Reduction targets, space ratios, layer counts and material types, which makers, hauliers and sellers must follow; importers must sell such goods in compliant packaging","Packaging artwork, colour ratios and font sizes, which makers must follow; importers need only declare packaging weight at customs and face no packaging rules","Packaging price caps and profit margins, which sellers must follow; importers need case-by-case central approval before selling such goods","Packaging warranty periods and repair point numbers, which hauliers must follow; importers must re-export all packaging to the country of origin"],
 "Article 19, paragraphs 1 to 3, with Articles 42 and 44."),

(C,"第20條",3,"資循法-延長使用",
 "中央主管機關指定公告物品之延長使用目標及方式者，業者應以哪些指定方式辦理？",
 ["提供使用過之物品回收服務；重複填充；提供租賃、押金回收或回購服務；提供維修服務及設置維修站點；提供一定保固年限；其他經中央主管機關認可之方式","提供舊品折價換購新品服務；縮短產品改版週期；提供分期付款及信用貸款服務；設置直營門市據點；提供一定期間之免費配送；其他經公會認可之方式","提供產品保險理賠服務；提高產品售價以反映成本；提供會員積點兌換服務；設置客服電話專線；提供一定金額之購物金；其他經地方主管機關認可之方式","提供產品說明書電子化服務；限制產品銷售地區；提供代客保管服務；設置產品展示中心；提供一定次數之清潔保養；其他經目的事業主管機關認可之方式"],"a",
 "第20條第1項列六款指定方式：提供使用過之物品回收服務；重複填充；提供租賃、押金回收或回購服務；提供維修服務及設置維修站點；提供一定保固年限；其他經中央主管機關認可之方式。業者並應設置必要設施，其執行成果應報中央主管機關備查。第2項：必要設施設置方式、物品延長使用執行成果備查等辦法由中央主管機關定之。第42條第4款及第44條第3款分別就製造輸入業者及販賣業者定有罰則。",
 "Which designated methods must businesses use where extended-use targets are announced for goods?",
 ["Take-back services for used goods; refilling; leasing, deposit return or buy-back services; repair services and repair stations; a minimum warranty period; other methods the central authority recognizes","Trade-in discounts on new purchases; shorter product revision cycles; instalment and credit services; directly operated stores; free delivery for a period; other methods the trade association recognizes","Product insurance claim services; higher prices reflecting cost; membership point redemption; a customer service hotline; store credit of a set amount; other methods the local authority recognizes","Digital user manuals; restricted sales territories; storage services for customers; product showrooms; a set number of cleaning services; other methods the industry authority recognizes"],
 "Article 20, paragraphs 1 and 2, with Articles 42 and 44."),

(C,"第21條",2,"資循法-循環標誌",
 "得向中央主管機關申請核准使用循環標誌之產品及服務範圍為何？未經核准者有何禁止規定？",
 ["循環產品指使用易於循環材質、一定比率再生材料或符合綠色設計準則之產品；循環服務指提供物品或包裝容器重複或延長使用之服務；未經核准者不得擅自使用或變造循環標誌","循環產品指全部使用天然原生材料製成之產品；循環服務指提供產品保險及理賠之服務；未經核准者仍得於自有網站或型錄上使用循環標誌，僅不得用於產品包裝","循環產品指取得國家標準認證之進口產品；循環服務指提供產品運輸及倉儲之服務；未經核准者得於申請期間先行使用循環標誌，俟核准後補辦登記即可","循環產品指售價低於同類新品之二手商品；循環服務指提供二手商品交易媒合之服務；未經核准者由中央目的事業主管機關逐案認定得否使用循環標誌"],"a",
 "第21條第1項列二款：循環產品指使用易於資源循環材質、一定比率再生材料或符合綠色設計準則等促進資源循環特性之產品；循環服務指提供物品或其包裝、容器重複或延長使用等促進資源循環方式之服務。業者得申請核准使用循環標誌，並應依核准事項使用於產品、包裝或服務場所。第2項：申請條件、應備文件、審查、核准事項、使用與標示之管理、變更、查核、抽樣檢驗、廢止等辦法由中央主管機關定之。第3項：未經核准者不得擅自使用、變造或不當使用循環標誌。第41條第1款、第2款定有罰則。",
 "Which products and services may apply to use the circulation mark, and what is prohibited without approval?",
 ["Circular products use easily circulated materials, a set recycled content or meet the green design rules; circular services give reuse or extended use of goods; without approval no one may use or alter the mark","Circular products are made wholly of natural virgin materials; circular services provide product insurance and claims; without approval the mark may still be used on websites and catalogues but not on packaging","Circular products are imports certified to national standards; circular services provide transport and warehousing; without approval the mark may be used while an application is pending and registered later","Circular products are second-hand goods priced below comparable new ones; circular services match second-hand trades; without approval the industry authority decides case by case"],
 "Article 21, paragraphs 1 to 3, with Article 41."),

(C,"第22條",3,"資循法-資訊揭露",
 "中央主管機關指定公告物品或其包裝、容器者，其業者應揭露及標示哪些資訊？",
 ["使用之材質及再生粒（材）料比率；包裝材質及重量；可維修性、耐用性及維修方式；回收拆解及再利用方式；分類回收標誌；使用唯一識別碼者應更新流向及驗證資訊","製造成本及毛利率；原料進口來源國別；員工人數及平均薪資；主要客戶名單及銷售金額；股東持股比例；使用具唯一產品識別碼者應公開全部客戶個人資料","產品專利號碼及授權範圍；研發經費占營收比率；生產設備廠牌型號；廠房面積及產能利用率；環境影響評估結論；使用具唯一產品識別碼者應公開製程參數","碳排放總量及減量目標；用水量及節水措施；勞工職業災害統計；供應商稽核結果；董事會決議事項；使用具唯一產品識別碼者應公開內部稽核報告"],"a",
 "第22條第1項列七款應揭露及標示之資訊：使用之材質及再生粒（材）料比率；包裝材質及重量；可維修性、耐用性及維修方式；回收、拆解及再利用方式；分類回收標誌；使用具唯一產品識別碼者應動態更新流向追溯及品質驗證資訊；其他經中央主管機關指定之事項。第2項：非屬指定公告者得自願揭露及標示。第3項：資訊之計算方式、可維修性耐用性評估方式、標誌圖樣、揭露及標示內容與方式等辦法由中央主管機關定之。第41條第3款及第45條分別定有罰則。",
 "What information must businesses disclose and label for designated goods, packaging or containers?",
 ["Materials used and recycled content ratio; packaging material and weight; repairability, durability and repair methods; recovery and reuse methods; sorting marks; flow tracing and verification data where a unique identifier is used","Production cost and gross margin; country of origin of raw materials; headcount and average pay; major customer names and sales; shareholding ratios; all customer personal data where a unique identifier is used","Patent numbers and licence scope; research spending as a share of revenue; equipment brands and models; plant area and capacity use; environmental assessment conclusions; process parameters where a unique identifier is used","Total carbon emissions and reduction targets; water use and saving measures; occupational accident statistics; supplier audit results; board resolutions; internal audit reports where a unique identifier is used"],
 "Article 22, paragraphs 1 to 3, with Articles 41 and 45."),

(C,"第23條",2,"資循法-環保標章",
 "製造、輸入、販賣產品或提供服務業者取得環保標章使用權之程序及後續義務為何？",
 ["得向中央主管機關申請環保標章使用權，審查通過發給證書者應標示於產品、包裝或服務場所；取得者應提送使用情形、產量及銷售量報備查，必要時得抽樣檢驗產品","得向中央目的事業主管機關申請環保標章使用權，經備查後即得標示於產品；取得使用權者無須提送任何資料，中央主管機關亦不得對其產品進行抽樣檢驗","得向地方主管機關申請環保標章使用權，經地方議會決議通過後發給證書；取得使用權者應每月公告銷售明細於指定網站供民眾查閱比對","得向認證機構申請環保標章使用權，經認證合格即取得永久使用權；取得使用權者僅須於證書屆期前重新認證，無須提送產量或銷售資料"],"a",
 "第23條第1項：製造、輸入、販賣產品或提供服務業者得向中央主管機關申請環保標章使用權；經中央主管機關審查通過並發給證書者，應將環保標章標示於產品、包裝或服務場所。第2項：取得環保標章使用權之業者，應提送環保標章使用情形、產品產量、銷售量等資料報中央主管機關備查；必要時，中央主管機關得抽樣檢驗產品。第3項：申請條件、應備文件、審查、分類、標示、使用、管理、變更、查核、抽樣檢驗、廢止、資料提報等辦法由中央主管機關定之。第41條第4款定有罰則。",
 "How is the right to use the eco-label obtained, and what follow-up duties apply?",
 ["Apply to the central authority; on passing review the label must be shown on the product or service premises; holders report use, output and sales, and the authority may sample-test","Apply to the central industry authority; the label may be used once filed; holders need report nothing and the central authority may not sample-test their products","Apply to the local authority; a certificate issues after a local council resolution; holders must publish monthly sales details on a designated website for public comparison","Apply to a certification body; passing certification confers a permanent right; holders need only recertify before expiry and report no output or sales data"],
 "Article 23, paragraphs 1 to 3, with Article 41."),

(C,"第24條",2,"資循法-環保標章禁止",
 "未取得環保標章使用權之業者，不得有下列何種行為？",
 ["擅自使用環保標章於產品、包裝或消費者能取得之文件資訊；擅自使用標章、證書、證號或文字進行標示、宣傳或廣告；變造環保標章使用證書或標章圖示","於產品標示回收相關標誌及材質種類；於廣告中說明產品使用再生材料之比率；於包裝上標示可維修性及耐用性資訊；於服務場所標示循環服務之內容","向中央主管機關申請環保標章使用權並檢具相關文件；於審查期間先行研發符合標章規格之產品；於取得證書後將標章標示於服務場所","依第二十二條規定自願揭露及標示物品資訊；提送產品產量及銷售量資料報中央主管機關備查；接受中央主管機關之抽樣檢驗"],"a",
 "第24條列四款：擅自使用環保標章於產品、包裝或其他消費者能取得之文件或資訊；擅自使用環保標章、證書、證號或文字進行標示、宣傳、廣告或其他對外之表示；變造環保標章使用證書或標章圖示；其他經中央主管機關認定不當使用環保標章之情形。第41條第5款規定有第24條各款所定行為之一者，由中央主管機關處新臺幣一萬元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰。",
 "Which acts are prohibited for those without the right to use the eco-label?",
 ["Using the eco-label on products, packaging or documents available to consumers; using the label, certificate, number or wording in labelling, promotion or advertising; altering the certificate or label design","Marking recovery symbols and material types on products; stating the recycled content ratio in advertising; labelling repairability and durability on packaging; describing circular services at service premises","Applying to the central authority for the right and filing the documents; developing products meeting the label specification while under review; showing the label at service premises after certification","Voluntarily disclosing and labelling goods information under Article 22; reporting output and sales for the record; submitting to the central authority's sample testing"],
 "Article 24, subparagraphs 1 to 4, with Article 41."),

(C,"第25條",3,"資循法-再生資源項目",
 "得再使用及得再生利用之再生資源項目，分別由何機關公告？未經公告者事業應如何辦理？",
 ["得再使用之項目由中央主管機關公告；得再生利用之項目由中央目的事業主管機關公告；未經公告者事業得檢具計畫，分別向各該機關申請核准為再生資源項目","得再使用及得再生利用之項目均由中央主管機關公告；未經公告者事業不得申請，須俟中央主管機關主動公告後始得循環利用該項物質","得再使用之項目由地方主管機關公告；得再生利用之項目由地方議會決議公告；未經公告者事業得逕行循環利用，僅須於事後報請備查即可","得再使用之項目由中央目的事業主管機關公告；得再生利用之項目由中央主管機關公告；未經公告者事業應報請行政院核定後始得申請成為再生資源項目"],"a",
 "第25條第1項：得再使用之再生資源項目，由中央主管機關公告之。第2項：再使用之清運、貯存方法、設施規範、再使用規範、紀錄、管理等辦法由中央主管機關定之。第3項：得再生利用之再生資源項目，由中央目的事業主管機關公告之。第4項：再生利用之清運、貯存方法、設施規範、再生利用規範、紀錄、管理等辦法由中央目的事業主管機關定之。第5項：未經公告為再生資源項目者，事業得檢具再使用、再生利用計畫，分別向中央主管機關或中央目的事業主管機關申請核准為再生資源項目。第6項：計畫書應載明事項分別由各該機關公告。第40條第2款定有罰則。",
 "Who announces items eligible for re-use and for recycling, and what may enterprises do for unannounced items?",
 ["The central authority announces re-use items and the industry authority recycling items; for unannounced items an enterprise may file a plan with the respective authority for approval","The central authority announces both; for unannounced items enterprises may not apply and must wait for the central authority to announce them","The local authority announces re-use items and the local council announces recycling items; unannounced items may be circulated directly and merely filed afterwards","The central industry authority announces re-use items and the central authority announces recycling items; unannounced items need Executive Yuan approval before any application"],
 "Article 25, paragraphs 1 to 6, with Article 40."),

(C,"第26條",3,"資循法-生產者責任組織",
 "再生資源為廢棄物品、包裝或容器者，中央主管機關得指定業者為何種作為？該組織負有何種責任及義務？",
 ["得指定其製造、輸入、販賣或使用業者共同成立或加入生產者責任組織，負擔回收清除及循環利用之財務與執行責任；該組織應規劃循環利用計畫送核准並定期申報","得指定其製造、輸入、販賣或使用業者共同繳納回收清除處理費予資源回收管理基金；該組織僅負財務責任而不負實際執行責任，亦無須提送任何循環利用計畫或申報","得指定其製造、輸入、販賣或使用業者共同委託單一清除機構處理；該組織應由中央主管機關指派公務人員擔任負責人，並由政府編列預算支應全部費用","得指定其製造、輸入、販賣或使用業者共同設立信託基金專戶；該組織應每年將基金收支報地方議會審議，並由議會決定循環利用之方式及目標"],"a",
 "第26條第1項：中央主管機關得指定其製造、輸入、販賣或使用業者，共同成立或加入既有生產者責任組織，負擔再生資源之回收、清除及循環利用之財務與實際執行責任。第2項：中央主管機關得指定生產者責任組織依指定之目標、循環利用方式及必要設施規劃循環利用計畫，並於公告期限內檢具該計畫送請中央主管機關審查，並依核准之計畫辦理。第3項：生產者責任組織應依中央主管機關指定之資料傳輸方式定期申報循環利用情形。第5項：再生資源為事業活動產生之物品、包裝或容器者，循環利用計畫之審查核准及執行情形之監督考核由中央目的事業主管機關為之。",
 "What may the central authority require of businesses for waste goods, packaging or containers, and what duties follow?",
 ["It may require makers, importers, sellers or users to join a producer responsibility organization bearing financial and operational duties; that body needs an approved plan and reports","It may require them to jointly pay recycling fees into the recycling management fund; the body bears only financial responsibility, not operational, and files no plan or report","It may require them to jointly commission a single clearance operator; the body must be headed by a civil servant appointed centrally and funded wholly by government budget","It may require them to jointly set up a trust fund account; the body must submit fund accounts annually to the local council, which decides the circulation methods and targets"],
 "Article 26, paragraphs 1 to 3 and 5."),

(C,"第27條",1,"資循法-再生產品標準",
 "再生產品應符合何種標準？不符合者有何效果？",
 ["應符合國家標準；無國家標準者得由中央目的事業主管機關公告其標準；不符合者不適用第五章輔導獎勵措施之規定","應符合國際標準；無國際標準者得由認證機構自行訂定；不符合者應由中央主管機關逕行命其停止生產並銷毀全部庫存","應符合企業內部規格；無內部規格者由同業公會協議訂定；不符合者仍得適用輔導獎勵措施，僅須加註警語即可","應符合地方自治法規；無自治法規者由地方議會決議訂定；不符合者應退運出口或移交執行機關依廢棄物清理法處理"],"a",
 "第27條第1項：再生產品應符合國家標準；無國家標準者，得由中央目的事業主管機關公告其標準。第2項：再生產品不符合前項標準者，不適用第五章輔導獎勵措施之規定。第五章（第32條至第37條）就優先採購、獎勵補助、租稅減免、融資信用保證、專用區設置及創新實驗等定有規定。第3條第6款並定義再生產品指以一定比例以上之再生資源為原料所製成之產品。",
 "What standards must recycled products meet, and what follows if they do not?",
 ["National standards; where none exist the industry authority may announce one; products that fail do not qualify for the Chapter 5 incentive measures","International standards; where none exist certification bodies may set their own; products that fail must stop production and have all stock destroyed","Internal company specifications; where none exist the trade association agrees them; products that fail still qualify for incentives if a warning is added","Local self-government ordinances; where none exist the local council resolves them; products that fail must be re-exported or handed to the executing agency"],
 "Article 27, paragraphs 1 and 2, read with Article 3 and Chapter 5."),

(C,"第28條",2,"資循法-輸出入限制",
 "為有效循環利用國內再生資源，中央主管機關得為何種處置？經限制者應如何辦理？",
 ["得限制或禁止再生資源之輸入或輸出；經限制輸入或輸出者，應申請直轄市、縣（市）主管機關許可後始得輸入或輸出","得逕行沒入輸出入之全部再生資源；經限制輸入或輸出者，應向海關報備並繳納關稅後即得輸入或輸出","得指定再生資源之輸出入價格區間；經限制輸入或輸出者，應取得中央目的事業主管機關同意函後始得輸入或輸出","得要求輸出入業者繳納履約保證金；經限制輸入或輸出者，應報請行政院專案核准後始得輸入或輸出"],"a",
 "第28條第1項：為有效循環利用國內再生資源，中央主管機關得限制或禁止再生資源之輸入或輸出；經限制輸入或輸出者，應申請直轄市、縣（市）主管機關許可後，始得輸入或輸出。第2項：再生資源輸入或輸出之限制、禁止、申請許可之資格、應備文件、審查、許可事項、許可期限、廢止等辦法由中央主管機關定之。第40條第3款規定違反該辦法有關限制、禁止、許可事項或許可期限之規定者，處新臺幣一萬二千元以上十五萬元以下罰鍰。",
 "What may the central authority do about cross-border movement of renewable resources, and what applies once restricted?",
 ["It may restrict or ban import or export of renewable resources; once restricted, a municipal or county permit is needed before moving them","It may confiscate all renewable resources moved across borders; once restricted, filing with customs and paying duty suffices to import or export","It may set price ranges for such trade; once restricted, a letter of consent from the central industry authority is needed before importing or exporting","It may require traders to post performance bonds; once restricted, case-by-case Executive Yuan approval is needed before importing or exporting"],
 "Article 28, paragraphs 1 and 2, with Article 40."),

(C,"第29條",1,"資循法-申報義務",
 "經中央主管機關指定公告之事業，就再生資源之運作情形負有何種申報義務？",
 ["應依中央主管機關規定之格式、項目及頻率，以網路傳輸方式向中央主管機關申報再生資源之產出、貯存、清運、再使用、再生利用及輸出入情形","應依中央目的事業主管機關規定之格式，以書面方式向地方主管機關按季申報其再生資源之產量及銷售金額，網路傳輸方式一律不予受理","應依同業公會規定之格式，以電子郵件方式向公會申報其再生資源之流向，並由公會彙整後轉送中央主管機關參考","應依地方議會決議之格式，以公告方式於公司網站揭露其再生資源之全部運作情形，無須向任何主管機關申報"],"a",
 "第29條：經中央主管機關指定公告之事業，應依中央主管機關規定之格式、項目、內容、頻率，以網路傳輸方式，向中央主管機關申報其再生資源之產出、貯存、清運、再使用、再生利用、輸入、輸出、過境或轉口情形；但經中央主管機關同意者，得以網路傳輸以外之方式申報。第40條第4款規定違反第29條申報規定者，處新臺幣一萬二千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰；情節重大者得處停工或停業處分。",
 "What reporting duty falls on enterprises designated by the central authority?",
 ["They must report online to the central authority, in the prescribed form and frequency, the generation, storage, haulage, re-use and recycling of renewable resources","They must report quarterly in writing to the local authority in the central industry authority's form on output and sales value, with online filing never accepted","They must report resource flows by email to the trade association in its form, which compiles and forwards them to the central authority for reference","They must publish all their operations on the company website in a form resolved by the local council, without reporting to any authority"],
 "Article 29, with the penalty in Article 40."),

(C,"第30條",1,"資循法-視為廢棄物",
 "再生資源未依規定循環利用，或無法再使用、再生利用時，應如何處理？",
 ["未依規定循環利用者，視為廢棄物，應依廢棄物清理法規定回收、清除、處理；無法再使用、再生利用時，應依廢棄物清理法規定清除、處理","未依規定循環利用者，仍視為再生資源，得繼續貯存至找到循環利用管道為止；無法再使用、再生利用時，得逕行掩埋而不受任何法律拘束","未依規定循環利用者，應退運回原產出事業重新處理；無法再使用、再生利用時，應由中央主管機關指定公營事業無償收受並處理","未依規定循環利用者，應由主管機關逕行沒入並拍賣；無法再使用、再生利用時，應報請行政院指定處理場所後始得清除處理"],"a",
 "第30條第1項：再生資源未依規定循環利用者，視為廢棄物，應依廢棄物清理法規定回收、清除、處理。第2項：再生資源無法再使用、再生利用時，應依廢棄物清理法規定清除、處理。第31條並規定再生資源屬依廢棄物清理法公告之應回收廢棄物者，其回收、貯存及回收清除處理費用之繳納依廢棄物清理法之規定辦理。",
 "How are renewable resources handled when not circulated as required or when re-use and recycling are impossible?",
 ["Those not circulated as required are deemed waste and must be recovered and treated under the Waste Disposal Act; those that cannot be re-used or recycled must be cleared under that Act","Those not circulated as required remain renewable resources and may be stored until an outlet is found; those that cannot be re-used may be landfilled free of any legal constraint","Those not circulated as required must be returned to the generating enterprise for reprocessing; those that cannot be re-used must be taken free of charge by a designated state enterprise","Those not circulated as required are confiscated and auctioned by the authority; those that cannot be re-used need an Executive Yuan designated site before clearance"],
 "Article 30, paragraphs 1 and 2, with Article 31."),

(C,"第31條",1,"資循法-應回收廢棄物",
 "再生資源屬依廢棄物清理法公告之應回收廢棄物者，其回收、貯存及回收清除處理費用之繳納應依何規定辦理？",
 ["依廢棄物清理法之規定辦理","依本法第二十六條生產者責任組織之規定辦理","依中央目的事業主管機關另訂之管理辦法辦理","依直轄市、縣（市）主管機關所定自治法規辦理"],"a",
 "第31條：再生資源屬依廢棄物清理法公告之應回收廢棄物者，其回收、貯存及回收清除處理費用之繳納，依廢棄物清理法之規定辦理。廢棄物清理法第15條至第18條就應回收廢棄物之範圍、責任業者登記與繳費、資源回收管理基金用途及稽核認證補貼等定有規定。第30條並規定再生資源未依規定循環利用者視為廢棄物，應依廢棄物清理法回收清除處理。",
 "Which rules govern recovery, storage and fee payment where a renewable resource is announced mandatory recycling waste?",
 ["The provisions of the Waste Disposal Act","The producer responsibility organization rules in Article 26","Separate regulations issued by the central industry authority","Self-government ordinances set by the municipal or county authority"],
 "Article 31, read with Article 30 and Articles 15 to 18 of the Waste Disposal Act."),

(C,"第32條",3,"資循法-優先採購",
 "政府機關、公立學校、公營事業、軍事機關及行政法人應優先採購哪些產品或服務？績效評核由何機關辦理？",
 ["應優先採購環保標章產品、依第二十一條核准使用循環標誌之循環產品或服務、其他環保及具綠色意涵之產品；由中央主管機關辦理績效評核","應優先採購國產品、取得國家標準認證之產品、價格最低之產品；由行政院公共工程委員會辦理績效評核並公告採購金額排名","應優先採購取得國際認證之進口產品、由中小企業製造之產品、具專利技術之產品；由經濟部辦理績效評核並核發獎勵金","應優先採購由生產者責任組織成員製造之產品、經地方議會推薦之產品；由直轄市、縣（市）主管機關分別辦理績效評核"],"a",
 "第32條第1項列三款應優先採購之標的：環保標章產品；依第21條核准使用循環標誌之循環產品或循環服務；其他環境保護產品及具綠色意涵之產品或服務。並由中央主管機關辦理績效評核。第2項：應優先採購之產品或服務種類、績效評核作業等辦法由中央主管機關定之。第3項：主管機關及各目的事業主管機關應辦理促進產品回收及延長使用技術、優先採購相關之教育推廣活動。第4項：民間企業或團體優先採購績效優良者，中央主管機關得予獎勵。",
 "What must government bodies, schools, state enterprises and administrative juridical persons buy first, and who appraises performance?",
 ["Eco-labelled products, circular products or services approved to use the circulation mark, and other environmental or green products; the central authority appraises performance","Domestic products, products certified to national standards and the lowest priced products; the Public Construction Commission appraises performance and ranks procurement values","Internationally certified imports, products made by small and medium enterprises and patented products; the Ministry of Economic Affairs appraises performance and pays incentives","Products made by producer responsibility organization members and products recommended by the local council; each municipal or county authority appraises performance separately"],
 "Article 32, paragraphs 1 to 4."),

(C,"第33條",1,"資循法-自願服務獎勵",
 "事業自願提供物品或其包裝、容器之源頭減量、重複使用、延長使用或其他有利資源循環服務且績效優良者，得受何種待遇？",
 ["中央主管機關得予獎勵或補助","中央主管機關應逕予免除全部稅捐及規費","直轄市、縣（市）主管機關應發給定額獎勵金","中央目的事業主管機關應優先核發各項許可"],"a",
 "第33條：為促進資源循環，事業自願提供物品或其包裝、容器之源頭減量、重複使用、延長使用或其他有利資源循環服務，績效優良者，中央主管機關得予獎勵或補助。第34條第4項並規定第33條獎勵或補助之條件、方式、審查程序、廢止及其他有關事項之辦法，由中央主管機關定之。第32條第4項則就民間企業或團體優先採購績效優良者定有獎勵規定。",
 "How may enterprises voluntarily providing source reduction, reuse or extended use services with strong results be treated?",
 ["The central authority may give them incentives or subsidies","The central authority must exempt them from all taxes and fees","The municipal or county authority must pay them a fixed incentive","The central industry authority must give their permits priority"],
 "Article 33, read with Articles 32 and 34."),

(C,"第34條",3,"資循法-獎勵補助租稅",
 "事業或個人辦理綠色設計、源頭減量、永續消費、再使用、再生利用相關事項績效優良者，及事業投資於循環利用之支出，分別有何優惠？",
 ["績效優良者中央主管機關得予獎勵或補助；事業投資於循環利用之研究發展、人才培育及設備購置支出，得依稅法、產業創新條例或其他法律減免稅捐","績效優良者由行政院頒發獎狀並公開表揚；事業投資於循環利用之支出得全額由政府補助，並免除當年度營利事業所得稅之全部稅額","績效優良者得優先取得政府採購標案之議價權；事業投資於循環利用之支出得列為當年度營業費用並加倍認列於財務報表","績效優良者得申請延長各項許可證之有效期限；事業投資於循環利用之支出得抵繳違反本法所受之罰鍰及滯納金"],"a",
 "第34條第1項：事業或個人辦理綠色設計、源頭減量、永續消費、再使用、再生利用之相關技術開發、人才培訓、實際運用執行與管理，績效優良者，中央主管機關得予獎勵或補助。第2項：為促進資源循環產業發展，事業投資於循環利用及循環永續管理之研究發展、人才培育及設備購置支出金額，得依有關稅法、產業創新條例或其他法律規定減免稅捐。第3項：主管機關得考量偏遠、原住民族地區及離島地區之需要，訂定輔導、補助計畫。第4項：獎勵或補助之條件、方式、審查程序、廢止等辦法由中央主管機關定之。",
 "What benefits apply to strong performers in green design and circulation, and to investment in circulation?",
 ["The central authority may give incentives or subsidies to strong performers; investment in research, talent and equipment for circulation may receive tax relief under other statutes","The Executive Yuan issues certificates and public commendation; such investment is fully government funded and the whole year's profit-seeking enterprise income tax is waived","Strong performers gain priority negotiating rights in government tenders; such investment counts as current operating expense and is double recognized in the accounts","Strong performers may extend the validity of their permits; such investment may offset fines and late surcharges incurred under this Act"],
 "Article 34, paragraphs 1 to 4."),

(C,"第35條",1,"資循法-融資信保",
 "中央主管機關就事業投資於本法資源循環各項措施，得協調哪些機構給予何種協助？",
 ["得協調有關機關、金融機構及信用保證機構，對事業投資於本法各項措施優先給予融資及信用保證","得協調證券交易所及櫃檯買賣中心，針對該等事業優先核准其股票上市櫃並免除財務門檻之限制","得協調稅捐稽徵機關及海關，針對該等事業全面免除營業稅、關稅及貨物稅之課徵","得協調勞動主管機關及移民機關，針對該等事業優先核配外籍移工名額並放寬聘僱比例"],"a",
 "第35條：中央主管機關得協調有關機關、金融機構及信用保證機構，針對事業投資於本法資源循環各項措施，優先給予融資管道及信用保證。第34條第2項並就事業投資於循環利用及循環永續管理之研究發展、人才培育及設備購置支出，定有依有關稅法、產業創新條例或其他法律規定減免稅捐之規定；第9條第8款則將綠色金融資源循環事項列由金融監督管理委員會及環境部主辦。",
 "Which bodies may the central authority coordinate, and what help may they give to circulation investment?",
 ["Relevant agencies, financial and credit guarantee institutions, to give priority financing and credit guarantees for such investment","The stock exchange and over-the-counter centre, to give priority listing approval and waive financial thresholds for such enterprises","Tax collection agencies and customs, to waive business tax, customs duty and commodity tax entirely for such enterprises","The labour and immigration authorities, to give priority migrant worker quotas and relax hiring ratios for such enterprises"],
 "Article 35, read with Articles 9 and 34."),

(C,"第36條",3,"資循法-專用區設置",
 "主管機關或目的事業主管機關為促進資源循環，得就土地需求為何種規劃？涉及都市計畫變更時如何辦理？",
 ["得依各地區產業土地需求規劃設置環保科技或資源循環專用區；涉都市計畫變更者，得擬具可行性規劃報告會同都市計畫主管機關依都市計畫法第二十七條辦理","得逕行徵收私有土地作為專用區使用而無須辦理任何補償；涉及都市計畫變更者，由主管機關逕行公告變更並自公告日起生效，無須會同任何機關辦理","得指定既有工業區全部改編為資源循環專用區；涉及都市計畫變更者，應報請立法院審議通過後始得辦理變更編定相關程序","得要求產業園區開發單位無償提供二分之一土地作為專用區；涉及都市計畫變更者，應由地方議會決議並報行政院核定後辦理"],"a",
 "第36條第1項：為促進資源循環，引進技術及人才，激勵國內環保產業技術之研究創新與發展，主管機關或目的事業主管機關得依各地區資源循環產業之土地需求，規劃設置環保科技或資源循環專用區。第2項：涉及都市計畫變更者，主管機關得擬具可行性規劃報告，會同都市計畫主管機關依都市計畫法第27條辦理變更；涉及非都市土地使用者，應依國土計畫法、區域計畫法相關規定辦理。第3項：專用區及用地經同意變更或使用後，屬公有土地者得辦理撥用或出租予興辦人，不受土地法第25條規定之限制。第5項：產業園區規劃開發時，主管機關得要求開發單位預留資源循環用地。",
 "How may authorities plan land for resource circulation, and how are urban plan changes handled?",
 ["They may plan environmental technology or circulation zones by regional land needs; for an urban plan change they may act with the planning authority under Article 27","They may expropriate private land for such zones without any compensation; urban plan changes take effect on the authority's own announcement without involving any other agency","They may convert entire existing industrial parks into circulation zones; urban plan changes require Legislative Yuan approval before any re-designation","They may require park developers to donate half their land for such zones; urban plan changes require a local council resolution and Executive Yuan approval"],
 "Article 36, paragraphs 1 to 3 and 5."),

(C,"第37條",3,"資循法-創新實驗",
 "事業申請辦理資源循環創新實驗者，中央主管機關審查時應審酌哪些事項？得排除哪些法律之適用？",
 ["應審酌其創新性、必要性、可行性、風險控管及環境影響；得會商有關機關後核准排除本法及廢棄物清理法相關條文之全部或一部適用","應審酌其投資金額、預期營收、就業人數及股東結構；得排除公司法、證券交易法及勞動基準法之全部或一部適用，以利實驗順利進行","應審酌其專利數量、研發人員比例及國際合作對象；得排除環境影響評估法、水污染防治法及空氣污染防制法之全部規定而無任何限制","應審酌其資本額、營業年資及過往違規紀錄；得排除刑法、行政罰法及行政執行法有關責任與強制執行之全部規定"],"a",
 "第37條第1項：事業得檢具資源循環創新實驗計畫，向中央主管機關申請核准辦理，並應提送執行成果報中央主管機關備查。第2項：中央主管機關審查時應審酌其創新性、必要性、可行性、風險控管、環境影響；核准得附加實驗期間、範圍、規模、方法、監測、通報、返還獎勵或補助、限期改善或停止實驗、廢止核准及其他附款。第3項：得會商中央及地方有關機關後核准排除第25條、第27條及廢棄物清理法第12條、第14條、第18條第1項、第31條第1項第1款、第36條、第39條第1項、第41條第1項之全部或一部適用；但排除範圍應以達成實驗目的為必要且相當者為限，且不得排除涉及人體健康、公共安全或其他重大環境風險之強制規定與民事、刑事責任。第43條定有罰則。",
 "What must the central authority consider when reviewing a circulation innovation experiment, and which laws may be disapplied?",
 ["Innovativeness, necessity, feasibility, risk control and environmental impact; after consulting central and local agencies it may disapply all or part of Articles 25 and 27 and named Waste Disposal Act provisions","Investment amount, expected revenue, headcount and shareholder structure; it may disapply all or part of the Company Act, Securities and Exchange Act and Labor Standards Act","Patent counts, the share of research staff and international partners; it may disapply the entire Environmental Impact Assessment Act, Water Pollution Control Act and Air Pollution Control Act without limit","Capital, years in business and past violations; it may disapply all provisions of the Criminal Code, Administrative Penalty Act and Administrative Execution Act on liability and enforcement"],
 "Article 37, paragraphs 1 to 3, with Article 43."),

(C,"第38條",2,"資循法-綠色設計罰則",
 "未依第十四條第一項公告所定期限申請核定產品符合綠色設計準則者，及營建工程違反第十五條第一項公告者，其罰鍰額度分別為何？",
 ["前者由中央主管機關處新臺幣六千元以上三十萬元以下罰鍰；後者處新臺幣六萬元以上三十萬元以下罰鍰，尚未施工者並通知限期提出改善計畫","前者由中央主管機關處新臺幣一萬元以上十五萬元以下罰鍰；後者處新臺幣一千二百元以上六萬元以下罰鍰，並得逕行撤銷其建造執照及使用執照","前者由地方主管機關處新臺幣一萬二千元以上十五萬元以下罰鍰；後者處新臺幣六千元以上十五萬元以下罰鍰，並得沒入其全部施工機具設備","前者由中央目的事業主管機關處新臺幣三萬元以上五百萬元以下罰鍰；後者處新臺幣六萬元以上一千萬元以下罰鍰，並得移送司法機關偵辦"],"a",
 "第38條第1項列二款情形，由中央主管機關處新臺幣六千元以上三十萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰：未依第14條第1項公告所定期限申請核定產品符合綠色設計準則；指定產品之製造、輸入業者違反第14條第4項所定辦法有關核定事項、變更、查核、抽樣檢驗或資料備查之規定。第2項：營建工程之工程主辦機關或起造人違反第15條第1項所定公告有關綠色設計準則指定項目者，處新臺幣六萬元以上三十萬元以下罰鍰；尚未施工者並通知限期提出改善計畫，屆期未依核定期程內容執行者按次處罰，必要時得令其停工。第52條並定第38條第1項自公布後二年施行。",
 "What fines apply for missing the Article 14 green design approval deadline and for construction works breaching Article 15?",
 ["The central authority fines the former NT$6,000 to NT$300,000; the latter is fined NT$60,000 to NT$300,000, with an improvement plan required before construction","The central authority fines the former NT$10,000 to NT$150,000; the latter is fined NT$1,200 to NT$60,000, with possible revocation of building and occupancy permits","The local authority fines the former NT$12,000 to NT$150,000; the latter is fined NT$6,000 to NT$150,000, with possible confiscation of all construction equipment","The central industry authority fines the former NT$30,000 to NT$5 million; the latter is fined NT$60,000 to NT$10 million, with possible referral for prosecution"],
 "Article 38, paragraphs 1 and 2, with Article 52."),

(C,"第39條",2,"資循法-禁限制罰則",
 "違反第十八條第二項所定公告有關禁止或限制方式、範圍或資料備查之規定者，其罰鍰額度為何？",
 ["處製造、輸入業者新臺幣六萬元以上三十萬元以下罰鍰，處販賣、使用業者新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善","處製造、輸入業者新臺幣一萬元以上十五萬元以下罰鍰，處販賣、使用業者新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善","處製造、輸入業者新臺幣一萬二千元以上十五萬元以下罰鍰，處販賣、使用業者新臺幣三千元以上三萬元以下罰鍰，並通知限期改善","處製造、輸入業者新臺幣三十萬元以上三百萬元以下罰鍰，處販賣、使用業者新臺幣六萬元以上六十萬元以下罰鍰，並通知限期改善"],"a",
 "第39條列三款情形，處製造、輸入業者新臺幣六萬元以上三十萬元以下罰鍰，處販賣、使用業者新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰：違反依第18條第2項所定公告有關禁止或限制方式、範圍或資料備查之規定；違反第18條第3項有關地方主管機關所定加嚴自治法規或管制措施規定；不遵行地方主管機關依第18條第4項規定所為之處置（下架、銷毀、退運等）。",
 "What fines apply for breaching the Article 18 announcement on bans, restrictions or data filing?",
 ["Makers and importers are fined NT$60,000 to NT$300,000 and sellers and users NT$1,200 to NT$60,000, with notice to improve by a deadline","Makers and importers are fined NT$10,000 to NT$150,000 and sellers and users NT$6,000 to NT$150,000, with notice to improve by a deadline","Makers and importers are fined NT$12,000 to NT$150,000 and sellers and users NT$3,000 to NT$30,000, with notice to improve by a deadline","Makers and importers are fined NT$300,000 to NT$3 million and sellers and users NT$60,000 to NT$600,000, with notice to improve by a deadline"],
 "Article 39, subparagraphs 1 to 3, with Article 18."),

(C,"第40條",2,"資循法-檢查申報罰則",
 "規避、妨礙或拒絕依第八條第一項所為之檢查，或違反第二十九條申報規定者，其罰鍰額度及情節重大之效果為何？",
 ["由主管機關或目的事業主管機關處新臺幣一萬二千元以上十五萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰；情節重大者得處停工或停業","由中央主管機關處新臺幣六千元以上三十萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰；情節重大者得逕予廢止其公司登記及工廠登記","由地方主管機關處新臺幣六萬元以上三十萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰；情節重大者得沒入其全部再生資源及設備","由中央目的事業主管機關處新臺幣一萬元以上十五萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰；情節重大者得移送司法機關偵辦"],"a",
 "第40條列四款情形，由主管機關或目的事業主管機關處新臺幣一萬二千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰，情節重大者得處一個月以上一年以下停工或停業處分：規避、妨礙或拒絕依第8條第1項所為之檢查或要求提供資料之命令；違反依第25條第2項或第4項所定辦法有關清運、貯存方法、設施規範、再使用或再生利用規範、紀錄或管理之規定；違反依第28條第2項所定辦法有關限制、禁止、許可事項或許可期限之規定；違反第29條申報規定。第46條並定義情節重大之四款情形。",
 "What fine applies to obstructing Article 8 inspections or breaching Article 29 reporting, and what follows in serious cases?",
 ["The authority or industry authority fines NT$12,000 to NT$150,000, with notice to improve and recurring fines; in serious cases work or business may be suspended","The central authority fines NT$6,000 to NT$300,000, with notice to improve and recurring fines; in serious cases company and factory registration may be revoked","The local authority fines NT$60,000 to NT$300,000, with notice to improve and recurring fines; in serious cases all renewable resources and equipment may be confiscated","The central industry authority fines NT$10,000 to NT$150,000, with notice to improve and recurring fines; in serious cases the matter may be referred for prosecution"],
 "Article 40, subparagraphs 1 to 4, with Article 46."),

(C,"第41條",2,"資循法-標誌標示罰則",
 "擅自使用、變造或不當使用循環標誌，或有第二十四條各款所定不當使用環保標章行為之一者，其罰鍰額度為何？",
 ["由中央主管機關處新臺幣一萬元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","由中央主管機關處新臺幣六萬元以上三十萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","由地方主管機關處新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","由中央目的事業主管機關處新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰"],"a",
 "第41條列五款情形，由中央主管機關處新臺幣一萬元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰：違反依第21條第2項所定辦法有關循環標誌之核准事項、使用與標示之管理、變更、查核、抽樣檢驗之規定；違反第21條第3項規定擅自使用、變造或不當使用循環標誌；指定物品或其包裝、容器之製造、輸入或販賣業者未依第22條第1項所定期限揭露或標示資訊，或違反同條第3項所定辦法之規定；違反依第23條第3項所定辦法有關環保標章之標示、使用、管理、變更、查核、抽樣檢驗、資料提報之規定；有第24條各款所定行為之一。",
 "What fine applies to misusing the circulation mark or committing an act listed in Article 24 on eco-label misuse?",
 ["The central authority fines NT$10,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected","The central authority fines NT$60,000 to NT$300,000, with notice to improve by a deadline and recurring fines if not corrected","The local authority fines NT$1,200 to NT$60,000, with notice to improve by a deadline and recurring fines if not corrected","The central industry authority fines NT$6,000 to NT$150,000, with notice to improve and recurring fines if not corrected"],
 "Article 41, subparagraphs 1 to 5."),

(C,"第42條",2,"資循法-計畫違反罰則",
 "指定物品或其包裝、容器之製造、輸入業者違反第十六條第一項重複使用公告，或違反第十七條第一項減量公告者，其罰鍰額度為何？",
 ["處新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","處新臺幣一萬二千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","處新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","處新臺幣六萬元以上三十萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰"],"a",
 "第42條列四款情形，處新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰：指定物品或其包裝、容器之製造、輸入業者違反第16條第1項所定公告有關重複使用目標、方式、期限之規定，或違反同條第3項所定辦法之規定；違反第17條第1項所定公告有關減量目標、方式、期限之規定，或違反同條第3項所定辦法之規定；製造、運輸業者違反第19條第1項所定包裝減量公告或第2項成果報告規定，輸入業者違反同條第3項規定；製造、輸入業者違反第20條第1項延長使用公告或第2項所定辦法之規定。第44條則就販賣業者定有較低額之罰鍰。",
 "What fine applies where designated makers or importers breach the Article 16 reuse or Article 17 reduction announcements?",
 ["A fine of NT$6,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected in time","A fine of NT$12,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected in time","A fine of NT$1,200 to NT$60,000, with notice to improve by a deadline and recurring fines if not corrected in time","A fine of NT$60,000 to NT$300,000, with notice to improve by a deadline and recurring fines if not corrected in time"],
 "Article 42, subparagraphs 1 to 4, with Article 44."),

(C,"第43條",1,"資循法-創新實驗罰則",
 "違反依第三十七條第五項所定辦法有關核准事項、變更、管理、執行成果提送期限或備查之規定者，其罰鍰額度為何？",
 ["由中央主管機關處新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","由中央主管機關處新臺幣一萬元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","由地方主管機關處新臺幣一萬二千元以上十五萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰","由中央目的事業主管機關處新臺幣六萬元以上三十萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰"],"a",
 "第43條：違反依第37條第5項所定辦法有關核准事項、變更、管理、執行成果提送期限或備查之規定，由中央主管機關處新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰。第37條第5項規定資源循環創新實驗計畫之申請、審查、核准、管理、變更、展延、執行成果提送與備查、資訊公開、風險控管、監測、通報、返還獎勵或補助、限期改善或停止實驗、撤銷或廢止核准等辦法由中央主管機關定之。",
 "What fine applies for breaching the Article 37 innovation experiment regulations on approval, change, management or results?",
 ["The central authority fines NT$6,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected","The central authority fines NT$10,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected","The local authority fines NT$12,000 to NT$150,000, with notice to improve and recurring fines if not corrected","The central industry authority fines NT$60,000 to NT$300,000, with notice to improve and recurring fines if not corrected"],
 "Article 43, read with Article 37, paragraph 5."),

(C,"第44條",2,"資循法-販賣業者罰則",
 "指定物品或其包裝、容器之販賣業者違反第十六條、第十九條或第二十條所定公告者，其罰鍰額度為何？",
 ["處新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","處新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","處新臺幣一萬元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","處新臺幣六萬元以上三十萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰"],"a",
 "第44條列三款情形，處新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰：指定物品或其包裝、容器之販賣業者違反第16條第1項重複使用公告或第3項所定辦法；販賣業者違反第19條第1項包裝減量公告或第2項成果報告規定；販賣業者違反第20條第1項延長使用公告或第2項所定辦法。第42條則就製造、輸入業者之相同違規態樣定有新臺幣六千元以上十五萬元以下之較高罰鍰。",
 "What fine applies where designated sellers breach the announcements under Articles 16, 19 or 20?",
 ["A fine of NT$1,200 to NT$60,000, with notice to improve by a deadline and recurring fines if not corrected in time","A fine of NT$6,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected in time","A fine of NT$10,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected in time","A fine of NT$60,000 to NT$300,000, with notice to improve by a deadline and recurring fines if not corrected in time"],
 "Article 44, subparagraphs 1 to 3, contrasted with Article 42."),

(C,"第45條",1,"資循法-自願揭露罰則",
 "依第二十二條第二項規定自願揭露及標示資訊之業者，違反同條第三項所定辦法有關揭露或標示內容、方式之規定者，其罰鍰額度為何？",
 ["由中央主管機關處新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","由中央主管機關處新臺幣一萬元以上十五萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰","由地方主管機關處新臺幣六千元以上十五萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰","由中央目的事業主管機關處新臺幣六萬元以上三十萬元以下罰鍰，並通知限期改善，屆期未改善者按次處罰"],"a",
 "第45條：依第22條第2項規定自願揭露及標示物品或其包裝、容器資訊之業者，違反依同條第3項所定辦法有關揭露或標示內容、方式之規定，由中央主管機關處新臺幣一千二百元以上六萬元以下罰鍰，並通知限期改善，屆期仍未完成改善者按次處罰。第41條第3款則就指定物品之業者未依第22條第1項所定期限揭露或標示資訊者，定有新臺幣一萬元以上十五萬元以下之較高罰鍰。",
 "What fine applies where a voluntary discloser under Article 22 breaches the disclosure or labelling regulations?",
 ["The central authority fines NT$1,200 to NT$60,000, with notice to improve by a deadline and recurring fines if not corrected","The central authority fines NT$10,000 to NT$150,000, with notice to improve by a deadline and recurring fines if not corrected","The local authority fines NT$6,000 to NT$150,000, with notice to improve and recurring fines if not corrected","The central industry authority fines NT$60,000 to NT$300,000, with notice to improve and recurring fines if not corrected"],
 "Article 45, contrasted with Article 41, subparagraph 3."),

(C,"第46條",2,"資循法-情節重大",
 "第四十條所稱情節重大，指下列何種情形？",
 ["違反第八條、第二十五條、第二十八條或第二十九條規定，一年內經二次限期改善仍繼續違反同一規定；未依第二十五條循環利用再生資源致嚴重污染環境；申報或記錄文件虛偽不實","違反本法任一規定三年內經五次限期改善仍繼續違反；再生資源貯存量超過核准量二倍以上；未於期限內繳納罰鍰達六個月；未依規定設置專責人員達三個月","經地方議會決議認定影響公共利益重大；經媒體大幅報導引起社會關注；經民眾檢舉達十件以上；經目的事業主管機關建議應從重處罰之情形","違反本法致其負責人遭起訴或判刑確定；事業資本額達一定金額以上；違規期間持續超過一年；違規所得利益超過法定罰鍰最高額"],"a",
 "第46條列四款情節重大之情形：違反第8條第1項、第25條第2項、第4項、第28條第2項或第29條規定，一年內經二次限期改善，仍繼續違反同一規定；未依第25條第2項或第4項規定循環利用再生資源，嚴重污染環境；申請、申報或記錄之文件虛偽不實；其他經主管機關或目的事業主管機關認定情形。第40條規定情節重大者得處一個月以上一年以下停工或停業處分。",
 "What counts as a serious case under Article 40?",
 ["Continuing to breach the same provision of Articles 8, 25, 28 or 29 after two improvement deadlines in a year; seriously polluting by failing to circulate resources; filing false reports or records","Breaching any provision after five improvement deadlines within three years; storing more than twice the approved volume; leaving fines unpaid for six months; lacking dedicated personnel for three months","Being found by local council resolution to seriously affect public interest; drawing wide media coverage; attracting ten or more public complaints; being recommended for heavier penalty by the industry authority","Having its responsible person indicted or convicted; having capital above a set amount; violating continuously for over a year; gaining benefits exceeding the maximum statutory fine"],
 "Article 46, subparagraphs 1 to 4, with Article 40."),

(C,"第47條",1,"資循法-處罰機關",
 "本法所定之處罰，除另有規定外，由何機關為之？",
 ["由直轄市或縣（市）主管機關為之","由中央主管機關統一為之","由中央目的事業主管機關為之","由執行機關或鄉（鎮、市）公所為之"],"a",
 "第47條：本法所定之處罰，除另有規定外，由直轄市或縣（市）主管機關為之。惟第38條、第41條、第43條及第45條明定由中央主管機關處罰，第40條則規定由主管機關或目的事業主管機關處罰，均屬本條所稱另有規定之情形。第48條並規定依本法所定罰鍰裁罰基準等相關事項之準則，由中央主管機關定之。",
 "Who imposes penalties under the Act unless otherwise provided?",
 ["The municipal or county competent authority","The central competent authority alone","The central industry competent authority","The executing agency or township office"],
 "Article 47, read with Articles 38, 40, 41, 43, 45 and 48."),

(C,"第48條",1,"資循法-裁罰準則",
 "依本法所定罰鍰裁罰基準等相關事項之準則，由何機關訂定？",
 ["由中央主管機關定之","由行政院會同中央主管機關定之","由直轄市、縣（市）主管機關分別定之","由中央目的事業主管機關會商公會定之"],"a",
 "第48條：依本法所定罰鍰裁罰基準等相關事項之準則，由中央主管機關定之。第47條並規定本法所定之處罰除另有規定外由直轄市或縣（市）主管機關為之；第50條則規定有第38條至第42條、第44條等所定情形之一者，主管機關得於中央主管機關指定之網站公開違規業者之名稱、地址及違法情形。",
 "Who prescribes the guidelines on fining criteria under the Act?",
 ["The central competent authority","The Executive Yuan together with the central authority","Each municipal or county authority separately","The central industry authority with the trade association"],
 "Article 48, read with Articles 47 and 50."),

(C,"第49條",1,"資循法-規費收取",
 "主管機關或目的事業主管機關依本法規定受理各項申請之審查，應收取何種費用？其收費標準由何機關訂定？",
 ["應收取審查費或證書費等規費；其收費標準由中央主管機關或中央目的事業主管機關定之","應收取保證金及履約保證費；其收費標準由直轄市、縣（市）主管機關分別訂定公告","應收取管理費及回饋金；其收費標準由地方議會以自治條例定之並報行政院備查","應收取工本費及人事費；其收費標準由受理申請之機關依實際支出逐案核定"],"a",
 "第49條第1項：主管機關或目的事業主管機關依本法規定受理各項申請之審查，應收取審查費或證書費等規費。第2項：前項收費標準，由中央主管機關或中央目的事業主管機關定之。本法所定各項申請包括第14條綠色設計核定及循環標誌、第16條重複使用計畫、第17條減量計畫、第21條循環標誌使用、第23條環保標章使用權、第25條再生資源項目核准、第28條輸出入許可及第37條創新實驗計畫等。",
 "What fees are charged for reviewing applications under the Act, and who sets the schedule?",
 ["Review fees or certificate fees; the central authority or the central industry authority sets the schedule","Deposits and performance guarantee fees; each municipal or county authority sets and announces the schedule","Management fees and compensation payments; the local council sets the schedule by ordinance filed with the Executive Yuan","Document and personnel fees; the receiving agency approves each case by actual expenditure"],
 "Article 49, paragraphs 1 and 2."),

(C,"第50條",2,"資循法-資訊公開",
 "有第三十八條、第三十九條、第四十二條、第四十四條等所定情形之一者，主管機關得為何種處置？",
 ["得於中央主管機關指定之網站，公開違規業者之名稱、地址及違法情形","得逕行廢止違規業者之公司登記，並禁止其負責人五年內再擔任負責人","得將違規業者移送司法機關偵辦，並沒入其違規產品之全部銷售所得","得命違規業者於全國性報紙頭版刊登道歉啟事，並負擔全部刊登費用"],"a",
 "第50條：有第38條、第39條、第40條第2款、第4款、第41條第1款至第3款、第5款、第42條、第44條所定情形之一者，主管機關得於中央主管機關指定之網站，公開違規業者之名稱、地址及違法情形。第48條並規定罰鍰裁罰基準等相關事項之準則由中央主管機關定之；第47條規定處罰除另有規定外由直轄市或縣（市）主管機關為之。",
 "What may the authority do where violations under Articles 38, 39, 42 or 44 occur?",
 ["It may publish the violator's name, address and violation details on a website designated by the central authority","It may revoke the violator's company registration and bar its responsible person from office for five years","It may refer the violator for prosecution and confiscate all sales proceeds from the offending products","It may order the violator to publish an apology on the front page of a national newspaper at its own cost"],
 "Article 50, read with Articles 47 and 48."),

(C,"第51條",1,"資循法-施行細則",
 "本法施行細則由何機關訂定？",
 ["由中央主管機關定之","由行政院會同中央主管機關定之","由中央目的事業主管機關定之","由直轄市、縣（市）主管機關分別定之"],"a",
 "第51條：本法施行細則，由中央主管機關定之。第2條規定中央主管機關為環境部。本法多數授權辦法亦由中央主管機關訂定，例如第14條綠色設計準則相關辦法、第16條重複使用計畫辦法、第17條減量計畫辦法、第21條循環標誌辦法、第23條環保標章辦法及第37條創新實驗辦法等。",
 "Who prescribes the enforcement rules of the Act?",
 ["The central competent authority","The Executive Yuan together with the central authority","The central industry competent authority","Each municipal or county competent authority separately"],
 "Article 51, read with Articles 2, 14, 16, 17, 21, 23 and 37."),

(C,"第52條",2,"資循法-施行日期",
 "本法之施行日期為何？何條文另定自公布後二年施行？",
 ["本法除第十四條及第三十八條第一項規定自公布後二年施行外，自公布日施行","本法除第二十一條及第四十一條規定自公布後三年施行外，自公布日施行","本法除第二十五條及第四十條規定自公布後一年施行外，自公布後六個月施行","本法除第三十七條及第四十三條規定自公布後五年施行外，自行政院公告日施行"],"a",
 "第52條：本法除第14條及第38條第1項規定自公布後二年施行外，自公布日施行。第14條規範指定公告產品應遵行綠色設計準則並申請核定及發給循環標誌；第38條第1項則為未依第14條第1項公告期限申請核定，或違反第14條第4項所定辦法者之罰鍰規定，二者均延後二年施行，以利業者準備。",
 "When does the Act take effect, and which provisions take effect two years after promulgation?",
 ["The Act takes effect on promulgation, except Article 14 and Article 38, paragraph 1, which take effect two years after promulgation","The Act takes effect on promulgation, except Articles 21 and 41, which take effect three years after promulgation","The Act takes effect six months after promulgation, except Articles 25 and 40, which take effect one year after promulgation","The Act takes effect on the date the Executive Yuan announces, except Articles 37 and 43, which take effect five years after promulgation"],
 "Article 52, read with Articles 14 and 38."),
]
