# -*- coding: utf-8 -*-
# 第 10 批（I-1）：氣候變遷因應法 第1條–第31條
# 欄位：law_id, article, difficulty, category, q_zh, opts_zh(a,b,c,d), answer, explain_zh, q_en, opts_en, explain_en
L = "ENV-22"
Q = [
(L,"第1條",1,"氣候法-總則",
 "《氣候變遷因應法》第1條所揭示之立法目的，下列敘述何者正確？",
 ["因應全球氣候變遷，制定調適策略，降低與管理溫室氣體排放，落實世代正義、環境正義及公正轉型",
  "促進電業自由化與市場競爭，降低民生電價成本，確保發電業者合理利潤及穩定供應電力",
  "管制固定與移動污染源之空氣污染物排放，維護國民健康與生活環境，提升整體空氣品質",
  "推動資源回收與再利用，減少事業廢棄物產生量，建立循環經濟產業鏈及再生料交易市場"],"a",
 "第1條：為因應全球氣候變遷，制定氣候變遷調適策略，降低與管理溫室氣體排放，落實世代正義、環境正義及公正轉型，善盡共同保護地球環境之責任，並確保國家永續發展，特制定本法。第4條進一步將此目的具體化為一百三十九年淨零排放之長期減量目標。",
 "What is the legislative purpose stated in Article 1 of the Climate Change Response Act?",
 ["To respond to global climate change, set adaptation strategies, reduce greenhouse gas emissions, and realize intergenerational justice and just transition",
  "To liberalize the electricity industry and market competition, lower household electricity prices, and secure reasonable profits and stable supply for generators",
  "To control air pollutant emissions from stationary and mobile sources, safeguard public health and the living environment, and improve overall air quality",
  "To promote recycling and reuse, reduce industrial waste generation, and build a circular economy chain and a recycled materials trading market"],
 "Article 1 sets out climate response, GHG reduction and just transition as the Act's purposes."),

(L,"第2條",1,"氣候法-主管機關",
 "依本法規定，中央、直轄市及縣（市）之主管機關分別為何？",
 ["中央為行政院環境保護署；直轄市為直轄市政府；縣（市）為縣（市）政府",
  "中央為經濟部能源局；直轄市為直轄市環保局；縣（市）為縣（市）環保局",
  "中央為國家發展委員會；直轄市為直轄市政府；縣（市）為縣（市）建設處",
  "中央為行政院永續會；直轄市為直轄市議會；縣（市）為縣（市）政府環保單位"],"a",
 "第2條第1項：本法所稱主管機關，在中央為行政院環境保護署，在直轄市為直轄市政府，在縣（市）為縣（市）政府。同條第2項並規定，涉及中央目的事業主管機關職掌者，由中央目的事業主管機關辦理，與第8條之權責分工相呼應。",
 "Which authorities are the competent authorities under the Act?",
 ["Central: the Environmental Protection Administration, Executive Yuan; municipality: the municipal government; county/city: the county/city government",
  "Central: the Bureau of Energy, MOEA; municipality: the municipal EPB; county/city: the county/city EPB",
  "Central: the National Development Council; municipality: the municipal government; county/city: the county/city construction department",
  "Central: the Executive Yuan sustainable development council; municipality: the municipal council; county/city: the county/city environmental unit"],
 "Article 2 designates the EPA as the central competent authority and local governments locally."),

(L,"第2條",2,"氣候法-主管機關",
 "本法所定事項如涉及中央目的事業主管機關職掌者，應如何辦理？",
 ["由該中央目的事業主管機關辦理，中央主管機關不因此取代其職掌",
  "一律由中央主管機關統一辦理，中央目的事業主管機關僅負責備查",
  "由行政院國家永續發展委員會逕行辦理，其他機關均不得介入",
  "由直轄市、縣（市）主管機關代為辦理，並定期函報中央核備"],"a",
 "第2條第2項：本法所定事項，涉及中央目的事業主管機關職掌者，由中央目的事業主管機關辦理。第8條第2項並逐款列出各部會之主辦與協辦事項，第11條、第19條亦分別課予中央目的事業主管機關訂修部門行動方案及調適行動方案之義務。",
 "Who handles matters under the Act that fall within another central authority's competence?",
 ["That central authority in charge of the relevant industry handles them, and its competence is not displaced",
  "The central competent authority handles all of them, while the industry authority only keeps records",
  "The Executive Yuan sustainable development council handles them directly and no other agency may intervene",
  "Municipal and county/city authorities handle them on its behalf and report periodically to the center"],
 "Article 2(2): matters within an industry authority's competence are handled by that authority."),

(L,"第3條",2,"氣候法-定義",
 "依本法第3條，下列何者屬於本法明文列舉之溫室氣體？",
 ["二氧化碳、甲烷、氧化亞氮、氫氟碳化物、全氟碳化物、六氟化硫及三氟化氮",
  "二氧化碳、一氧化碳、二氧化硫、氮氧化物、臭氧、揮發性有機物及甲烷",
  "甲烷、氧化亞氮、氨氣、硫化氫、細懸浮微粒、六氟化硫及氫氟碳化物",
  "二氧化碳、甲烷、氯氟碳化物、鉛塵、戴奧辛、全氟碳化物及三氟化氮"],"a",
 "第3條第1款列舉溫室氣體為二氧化碳、甲烷、氧化亞氮、氫氟碳化物、全氟碳化物、六氟化硫、三氟化氮及其他經中央主管機關公告者。第3條第7款並規定排放量係各種溫室氣體量乘以溫暖化潛勢後之合計量，以二氧化碳當量表示。",
 "Which set lists the greenhouse gases expressly enumerated in Article 3?",
 ["Carbon dioxide, methane, nitrous oxide, HFCs, PFCs, sulfur hexafluoride and nitrogen trifluoride",
  "Carbon dioxide, carbon monoxide, sulfur dioxide, nitrogen oxides, ozone, volatile organics and methane",
  "Methane, nitrous oxide, ammonia, hydrogen sulfide, fine particulates, sulfur hexafluoride and HFCs",
  "Carbon dioxide, methane, CFCs, lead dust, dioxins, PFCs and nitrogen trifluoride"],
 "Article 3(1) enumerates seven gases plus any others announced by the central authority."),

(L,"第3條",2,"氣候法-定義",
 "依本法用詞定義，「淨零排放」與「碳匯」分別指何者？",
 ["淨零排放指排放量與碳匯量達成平衡；碳匯指持續移除後吸收或儲存溫室氣體之樹木、森林、土壤、海洋、地層、設施或場所",
  "淨零排放指全國排放量降為零；碳匯指政府核發給事業之免費排放額度與自願減量專案取得之減量額度總和",
  "淨零排放指排放量較基準年減少五成；碳匯指以人為方式捕捉並封存二氧化碳之設備及其附屬管線設施",
  "淨零排放指排放量與能源消費量達成平衡；碳匯指產品生命週期各階段所產生碳排放量換算之二氧化碳當量"],"a",
 "第3條第10款：淨零排放指溫室氣體排放量與碳匯量達成平衡；第9款：碳匯指自排放源或大氣中持續移除後吸收或儲存之樹木、森林、土壤、海洋、地層、設施或場所。第4條並以一百三十九年淨零排放為國家長期減量目標。",
 "How does the Act define net zero emissions and carbon sink?",
 ["Net zero means emissions balance carbon sinks; a sink is trees, forests, soil, ocean, strata, facilities or sites that absorb or store removed GHGs",
  "Net zero means national emissions fall to zero; a sink is the total of free allocated allowances plus credits from voluntary reduction projects",
  "Net zero means emissions fall by half from the base year; a sink is the equipment and pipelines that artificially capture and store carbon dioxide",
  "Net zero means emissions balance energy consumption; a sink is the CO2 equivalent of emissions across a product's life cycle stages"],
 "Article 3(9)-(10) define carbon sink and net zero emissions."),

(L,"第3條",3,"氣候法-定義",
 "依本法用詞定義，「碳洩漏」及「碳足跡」之意涵為何？",
 ["碳洩漏指管制導致產業外移至碳管制寬鬆國家反增全球排碳；碳足跡指產品生命週期各階段碳排放換算二氧化碳當量之總和",
  "碳洩漏指封存之二氧化碳自地層逸散至大氣；碳足跡指事業各廠場年度直接與間接排放量經查驗後登錄之合計數量",
  "碳洩漏指盤查時漏未申報之排放量；碳足跡指個人日常生活食衣住行所消耗能源折算之二氧化碳當量排放總量",
  "碳洩漏指免費核配額度未使用而失效；碳足跡指產品製造階段所使用電力乘以電力排放係數所得之二氧化碳當量"],"a",
 "第3條第17款：碳洩漏指實施溫室氣體管制，可能導致產業外移至其他碳管制較為寬鬆國家，反而增加全球排碳量之情況；第18款：碳足跡指產品由原料取得、製造、配送銷售、使用及廢棄處理等生命週期各階段之碳排放量換算為二氧化碳當量之總和。第31條之進口產品排碳差額制度及第37條之碳足跡標示均由此而來。",
 "What do carbon leakage and carbon footprint mean under the Act?",
 ["Leakage is regulation pushing industry to laxer countries and raising global emissions; footprint is total life-cycle CO2e of a product",
  "Leakage is captured carbon dioxide escaping from strata; footprint is a firm's verified annual direct and indirect emissions on record",
  "Leakage is emissions omitted from an inventory report; footprint is the CO2e of an individual's daily food, clothing, housing and travel",
  "Leakage is free allowances expiring unused; footprint is manufacturing electricity use multiplied by the power emission factor"],
 "Article 3(17)-(18) define carbon leakage and carbon footprint."),

(L,"第4條",1,"氣候法-減量目標",
 "本法所定國家溫室氣體長期減量目標為何？",
 ["中華民國一百三十九年溫室氣體淨零排放",
  "中華民國一百三十九年溫室氣體排放量減半",
  "中華民國一百二十九年溫室氣體淨零排放",
  "中華民國一百四十九年溫室氣體排放量減半"],"a",
 "第4條第1項：國家溫室氣體長期減量目標為中華民國一百三十九年溫室氣體淨零排放。第2項並要求各級政府與國民、事業、團體共同推動溫室氣體減量、發展負排放技術及促進國際合作；第10條則以五年為一期訂定階段管制目標以達成之。",
 "What is the national long-term GHG reduction goal under the Act?",
 ["Net zero greenhouse gas emissions by 2050 (ROC year 139)",
  "Halving greenhouse gas emissions by 2050 (ROC year 139)",
  "Net zero greenhouse gas emissions by 2040 (ROC year 129)",
  "Halving greenhouse gas emissions by 2060 (ROC year 149)"],
 "Article 4(1) sets net zero emissions in ROC year 139 as the long-term goal."),

(L,"第5條",2,"氣候法-基本方針",
 "依第5條第3項，政府因應氣候變遷之法律及政策規劃管理原則，下列何者正確？",
 ["應擬定逐步降低化石燃料依賴之中長期策略，訂定再生能源中長期目標，逐步落實非核家園願景",
  "應優先擴大核能發電占比，凍結再生能源躉購費率，以維持電價穩定及國家能源安全需要",
  "應全面禁止使用化石燃料發電，並於三年內完成所有燃煤機組之除役與拆除作業程序",
  "應由電業自行決定能源配比，政府不介入燃料選擇，僅就排放結果課徵稅費並公開資訊"],"a",
 "第5條第3項第2款：為確保國家能源安全，應擬定逐步降低化石燃料依賴之中長期策略，訂定再生能源中長期目標，逐步落實非核家園願景。同項第3款並規定排放額度核配應逐步從免費核配到拍賣或配售方式規劃，與第35條第1項之核配方式相呼應。",
 "Which principle for climate-related laws and policies is correct under Article 5(3)?",
 ["A mid- and long-term strategy to reduce fossil fuel dependence, renewable energy targets, and gradual realization of a nuclear-free homeland",
  "Priority expansion of nuclear generation and a freeze on renewable feed-in tariffs to keep prices stable and secure national energy supply",
  "A complete ban on fossil-fuel generation with all coal-fired units decommissioned and dismantled within three years",
  "Utilities decide their own energy mix without government involvement in fuel choice, with only fees on emissions and disclosure"],
 "Article 5(3)(2) requires reducing fossil fuel dependence and setting renewable targets."),

(L,"第5條",3,"氣候法-原住民族權益",
 "依第5條第3項第8款，政府推動自然碳匯涉及原住民族土地之開發、利用或限制時，應如何處理？",
 ["應與當地原住民族諮商並取得其同意，且新增碳匯之相關權益應與原住民族共享",
  "應報請原住民族委員會核定即可，無須另與當地原住民族進行諮商或取得同意",
  "應由中央主管機關逕行公告實施，事後將碳匯收益之半數撥入原住民族發展基金",
  "應徵詢地方民意代表意見後辦理，並將碳匯權益全數歸屬於土地登記所有權人"],"a",
 "第5條第3項第8款：為推動自然碳匯，政府應與原住民族共同推動及管理原住民族地區內之自然碳匯，該區域內新增碳匯之相關權益應與原住民族共享，涉及原住民族土地開發、利用或限制，應與當地原住民族諮商，並取得其同意。第8條第2項第19款並將原住民族氣候變遷調適及減量事項列由原住民族委員會主辦。",
 "What is required when natural carbon sink work involves indigenous land?",
 ["Consultation with and consent from the local indigenous peoples, and sharing of the rights and interests in newly added sinks",
  "Approval from the Council of Indigenous Peoples alone, without consultation with or consent from the local indigenous peoples",
  "Direct announcement by the central competent authority, with half of the sink revenue later paid into an indigenous development fund",
  "Consultation with local elected representatives, with all sink rights vested in the registered landowner"],
 "Article 5(3)(8) requires consultation with and consent of indigenous peoples."),

(L,"第6條",2,"氣候法-基本原則",
 "依第6條，因應氣候變遷相關計畫或方案之基本原則，下列何者正確？",
 ["部門階段管制目標之訂定應考量成本效益，確保儘可能以最低成本達到溫室氣體減量成效",
  "部門階段管制目標之訂定應以最大減量幅度為唯一考量，不得因成本因素而有所調整",
  "國家減量目標之訂定應完全比照工業先進國家之期程，不考量我國經濟及社會之發展",
  "減量技術之研究發展應委由民間企業自行負擔，政府不得編列預算補助或投入資源"],"a",
 "第6條第2款：部門階段管制目標之訂定，應考量成本效益，並確保儘可能以最低成本達到溫室氣體減量成效。第1款並要求履行聯合國氣候變化綱要公約共同但有差異之國際責任，同時兼顧我國環境、經濟及社會之永續發展；第10條第3項規定階段管制目標應依第5條第3項及第6條之原則訂定。",
 "Which is a basic principle for climate-related plans under Article 6?",
 ["Sectoral phased control targets shall consider cost-effectiveness and achieve reductions at the lowest possible cost",
  "Sectoral phased control targets shall pursue the largest possible cut only, with no adjustment on cost grounds",
  "National reduction targets shall copy the timetables of advanced industrial nations regardless of domestic conditions",
  "Research on reduction technology shall be funded solely by private firms, with no public budget or resources"],
 "Article 6(2) requires cost-effective sectoral targets."),

(L,"第7條",1,"氣候法-權限委任",
 "主管機關及目的事業主管機關就氣候變遷調適與溫室氣體減量事宜，得為下列何種處置？",
 ["得委任所屬機關（構）、委託或委辦其他機關（構），辦理調查、查核、輔導、訓練及研究事宜",
  "得將裁處罰鍰及廢止許可等處分權限，全部移轉由民間查驗機構代為行使並負最終責任",
  "得委由事業自行辦理其排放源之查核與認證，主管機關不再進行任何形式之檢查或複核",
  "得將本法所定所有職權委由行政院國家永續發展委員會統籌行使，不受法定分工之限制"],"a",
 "第7條：主管機關及目的事業主管機關得委任所屬機關（構）、委託或委辦其他機關（構），辦理有關氣候變遷調適與溫室氣體減量之調查、查核、輔導、訓練及研究事宜。至於罰鍰之裁處，依第58條原則上由中央主管機關為之。",
 "What may competent authorities do under Article 7?",
 ["Delegate or commission subordinate or other agencies to conduct surveys, audits, guidance, training and research",
  "Transfer powers to impose fines and revoke permits entirely to private verification bodies bearing final responsibility",
  "Let enterprises audit and certify their own emission sources, with the authority conducting no further checks",
  "Transfer all powers under the Act to the Executive Yuan sustainable development council regardless of statutory division"],
 "Article 7 allows delegation of surveys, audits, guidance, training and research."),

(L,"第8條",2,"氣候法-政府權責",
 "為推動氣候變遷因應及強化跨域治理，何機關應協調、分工、整合國家因應氣候變遷基本方針及重大政策之跨部會事務？",
 ["行政院國家永續發展委員會（永續會）",
  "行政院環境保護署所設之費率審議會",
  "直轄市、縣（市）氣候變遷因應推動會",
  "中央主管機關所設學者專家技術諮詢小組"],"a",
 "第8條第1項：為推動氣候變遷因應及強化跨域治理，行政院國家永續發展委員會（永續會）應協調、分工、整合國家因應氣候變遷基本方針及重大政策之跨部會氣候變遷因應事務。同條第2項第20款並規定其他氣候變遷調適及減量事項由永續會協調指定之。",
 "Which body coordinates cross-ministry climate response policy under Article 8?",
 ["The National Council for Sustainable Development, Executive Yuan",
  "The rate review committee established under the EPA",
  "The municipal or county/city climate change response promotion committee",
  "The technical advisory panel of scholars and experts under the central authority"],
 "Article 8(1) assigns cross-ministry coordination to the sustainable development council."),

(L,"第8條",3,"氣候法-政府權責",
 "依第8條第2項之權責分工，下列配對何者正確？",
 ["運輸管理及運輸部門減量由交通部主辦；建築溫室氣體減量管理由內政部主辦",
  "運輸管理及運輸部門減量由經濟部主辦；建築溫室氣體減量管理由交通部主辦",
  "運輸管理及運輸部門減量由內政部主辦；建築溫室氣體減量管理由經濟部主辦",
  "運輸管理及運輸部門減量由環保署主辦；建築溫室氣體減量管理由國科會主辦"],"a",
 "第8條第2項第4款：運輸管理、大眾運輸系統發展及其他運輸部門溫室氣體減量事項由交通部主辦、經濟部協辦；第6款：建築溫室氣體減量管理事項由內政部主辦、各中央目的事業主管機關協辦。第3款製造部門減量則由經濟部主辦。",
 "Which pairing of lead agencies under Article 8(2) is correct?",
 ["Transport management and transport-sector reduction: MOTC; building GHG reduction management: Ministry of the Interior",
  "Transport management and transport-sector reduction: MOEA; building GHG reduction management: MOTC",
  "Transport management and transport-sector reduction: Ministry of the Interior; building GHG reduction management: MOEA",
  "Transport management and transport-sector reduction: EPA; building GHG reduction management: the science and technology council"],
 "Article 8(2)(4) and (6) assign transport to MOTC and buildings to the Interior Ministry."),

(L,"第8條",3,"氣候法-政府權責",
 "依第8條第2項，「公正轉型之推動事項」及「溫室氣體減量對整體經濟影響評估」之主辦機關為何？",
 ["二者均由國家發展委員會主辦，並由各中央目的事業主管機關或經濟部協辦",
  "二者均由行政院環境保護署主辦，並由國家發展委員會及財政部共同協辦",
  "公正轉型由勞動部主辦；經濟影響評估由財政部主辦，經濟部負責協辦事宜",
  "公正轉型由原住民族委員會主辦；經濟影響評估由金融監督管理委員會主辦"],"a",
 "第8條第2項第18款：公正轉型之推動事項由國家發展委員會主辦、各中央目的事業主管機關協辦；第12款：溫室氣體減量對整體經濟影響評估及因應規劃事項由國家發展委員會主辦、經濟部協辦。第46條第2項所稱公正轉型主辦機關即指國發會。",
 "Which agency leads just transition and the economic impact assessment of GHG reduction?",
 ["The National Development Council leads both, assisted by industry authorities or the MOEA",
  "The Environmental Protection Administration leads both, assisted by the NDC and the Ministry of Finance",
  "The Ministry of Labor leads just transition; the Ministry of Finance leads the impact assessment with MOEA support",
  "The Council of Indigenous Peoples leads just transition; the Financial Supervisory Commission leads the assessment"],
 "Article 8(2)(12) and (18) place both with the National Development Council."),

(L,"第9條",2,"氣候法-行動綱領",
 "國家因應氣候變遷行動綱領由何機關擬訂？其檢討頻率為何？",
 ["由中央主管機關擬訂，會商中央目的事業主管機關報行政院核定；至少每四年檢討一次",
  "由行政院國家永續發展委員會擬訂並逕行發布；至少每二年檢討一次並對外公開",
  "由各中央目的事業主管機關分別擬訂後彙整發布；至少每五年檢討一次並送立法院",
  "由中央主管機關會同直轄市政府擬訂並公告實施；至少每十年檢討一次並公開周知"],"a",
 "第9條第1項：中央主管機關應依我國經濟、能源、環境狀況、參酌國際現況及第8條第1項分工事宜擬訂行動綱領，會商中央目的事業主管機關，報請行政院核定後實施並對外公開。第2項：應參酌聯合國氣候變化綱要公約與其協議或相關國際公約決議事項及國內情勢變化，至少每四年檢討一次。",
 "Who drafts the national climate action guidelines and how often are they reviewed?",
 ["The central competent authority drafts them, consults industry authorities, submits to the Executive Yuan; reviewed at least every four years",
  "The Executive Yuan sustainable development council drafts and issues them directly; reviewed at least every two years and made public",
  "Each central industry authority drafts its own part for consolidation; reviewed at least every five years and sent to the Legislative Yuan",
  "The central authority drafts them with municipal governments and announces them; reviewed at least every ten years and publicized"],
 "Article 9 requires review of the action guidelines at least every four years."),

(L,"第10條",2,"氣候法-階段管制目標",
 "階段管制目標之期程及提出時點，下列敘述何者正確？",
 ["以五年為一期，各期除第一期外，中央主管機關應於下一期開始前二年提出",
  "以四年為一期，各期除第一期外，中央主管機關應於下一期開始前一年提出",
  "以十年為一期，各期除第一期外，中央主管機關應於下一期開始前三年提出",
  "以三年為一期，各期除第一期外，中央主管機關應於當期結束前六個月提出"],"a",
 "第10條第1項：中央主管機關經召開公聽會程序後，訂定五年為一期之階段管制目標，報請行政院核定後實施並對外公開。第4項：各期階段管制目標，除第一期外，中央主管機關應於下一期開始前二年提出。第5項並要求每年彙整各部門執行狀況向行政院報告。",
 "What is the cycle and timing for phased control targets?",
 ["Five-year periods; except for the first, targets must be proposed two years before the next period begins",
  "Four-year periods; except for the first, targets must be proposed one year before the next period begins",
  "Ten-year periods; except for the first, targets must be proposed three years before the next period begins",
  "Three-year periods; except for the first, targets must be proposed six months before the period ends"],
 "Article 10(1) and (4): five-year periods, proposed two years in advance."),

(L,"第10條",3,"氣候法-階段管制目標",
 "中央主管機關為研擬階段管制目標召開公聽會前，應於何時以何方式公開周知？",
 ["應於舉行之日前三十日，以網際網路方式公開周知公聽會日期、地點及方式等事項",
  "應於舉行之日前七日，以刊登政府公報方式公開周知公聽會日期、地點及方式等事項",
  "應於舉行之日前六十日，以新聞紙頭版方式公開周知公聽會日期、地點及方式等事項",
  "應於舉行之日前十五日，以公文函知各地方主管機關轉知轄內人民及相關民間團體"],"a",
 "第10條第2項：於召開公聽會前，應將舉行公聽會之日期、地點及方式等事項，於舉行之日前三十日，以網際網路方式公開周知，並得登載於政府公報、新聞紙或其他適當方法廣泛周知；人民或團體得於公開周知期間內以書面或網際網路提出意見，由中央主管機關併同階段管制目標報行政院。",
 "How far ahead and by what means must the hearing on phased targets be publicized?",
 ["At least thirty days before, publicized online with the date, place and format of the hearing",
  "At least seven days before, publicized in the government gazette with the date, place and format",
  "At least sixty days before, publicized on newspaper front pages with the date, place and format",
  "At least fifteen days before, notified by official letter to local authorities for onward notice"],
 "Article 10(2) requires online publication thirty days before the hearing."),

(L,"第11條",2,"氣候法-部門行動方案",
 "所屬部門溫室氣體減量行動方案應由何機關訂修？其程序為何？",
 ["由中央目的事業主管機關依行動綱領及階段管制目標，經公聽會程序後訂修並送中央主管機關報行政院核定",
  "由中央主管機關逕行訂定後函知各中央目的事業主管機關配合辦理，無須辦理公聽會程序",
  "由直轄市、縣（市）主管機關訂修後，送氣候變遷因應推動會決議並報請中央主管機關備查",
  "由行政院國家永續發展委員會統一訂定，各中央目的事業主管機關僅依其內容編列預算執行"],"a",
 "第11條：中央目的事業主管機關應依行動綱領及階段管制目標，邀集中央及地方有關機關、學者、專家、民間團體經召開公聽會程序後，訂修所屬部門溫室氣體減量行動方案，送中央主管機關報請行政院核定後實施並對外公開。第15條之地方減量執行方案則依行動綱領及部門行動方案訂修。",
 "Who formulates the sectoral GHG reduction action programs and how?",
 ["Central industry authorities, following the guidelines and phased targets, after a public hearing and Executive Yuan approval",
  "The central competent authority alone, notifying industry authorities to implement, with no public hearing required",
  "Municipal and county/city authorities, after their promotion committee resolves, submitted to the central authority for record",
  "The Executive Yuan sustainable development council uniformly, with industry authorities only budgeting for implementation"],
 "Article 11 assigns sectoral action programs to central industry authorities after a hearing."),

(L,"第12條",2,"氣候法-成果報告",
 "中央目的事業主管機關執行所屬部門行動方案後，未能達成部門階段管制目標時，應如何處理？",
 ["應提出改善措施，連同每年編寫之成果報告送中央主管機關報請行政院核定後對外公開",
  "應由中央主管機關逕予處以罰鍰，並限期命其重新訂定該部門之階段管制目標及期程",
  "應停止該部門所有溫室氣體排放源之操作，俟達成目標後始得申請恢復營運及排放",
  "得逕行調降該部門下一期階段管制目標，無須提出改善措施或編寫年度成果報告"],"a",
 "第12條第1項至第3項：中央目的事業主管機關應每年編寫所屬部門行動方案成果報告；未能達成所屬部門階段管制目標時，應提出改善措施；前二項成果報告及改善措施應送中央主管機關報請行政院核定後對外公開。第10條第5項並要求中央主管機關每年彙整執行狀況向行政院報告。",
 "What must an industry authority do if its sectoral phased target is not met?",
 ["Propose improvement measures and submit them with the annual report to the Executive Yuan for approval and public disclosure",
  "Be fined by the central competent authority and ordered to set new sectoral phased targets and timetables within a deadline",
  "Suspend operation of all emission sources in that sector until the target is met and resumption is approved",
  "Lower the next-period sectoral target directly, without improvement measures or an annual results report"],
 "Article 12 requires improvement measures plus annual reporting and public disclosure."),

(L,"第13條",2,"氣候法-排放清冊",
 "中央主管機關就全國排放量統計及國家報告之編撰，其法定義務為何？",
 ["應定期統計全國排放量並建立國家溫室氣體排放清冊，每三年編撰溫室氣體國家報告報行政院核定後公開",
  "應每年統計全國排放量並建立國家溫室氣體排放清冊，每五年編撰溫室氣體國家報告送立法院備查",
  "應每二年統計全國排放量並建立排放交易資料庫，每四年編撰溫室氣體國家報告逕行對外公開",
  "應每半年統計全國排放量並建立碳足跡資料庫，每三年編撰能源政策白皮書報行政院核定公開"],"a",
 "第13條第2項：中央主管機關應定期統計全國排放量，建立國家溫室氣體排放清冊；並每三年編撰溫室氣體國家報告，報請行政院核定後對外公開。第1項並規定中央目的事業主管機關應進行排放量之調查及統計之研議，將成果每年定期提送中央主管機關。",
 "What are the central authority's duties on national emissions statistics?",
 ["Compile national emissions periodically, maintain the national GHG inventory, and produce a national report every three years for approval and disclosure",
  "Compile national emissions yearly, maintain the national GHG inventory, and produce a national report every five years for the Legislative Yuan",
  "Compile national emissions every two years, maintain a trading database, and publish a national report every four years directly",
  "Compile national emissions every six months, maintain a carbon footprint database, and issue an energy white paper every three years"],
 "Article 13(2): periodic national inventory and a national report every three years."),

(L,"第13條",1,"氣候法-排放清冊",
 "中央目的事業主管機關就排放量之調查及統計，應如何辦理？",
 ["應進行排放量之調查及統計之研議，並將調查及統計成果每年定期提送中央主管機關",
  "應進行排放量之調查及統計之研議，並將調查及統計成果每三年提送行政院核定公開",
  "應委託查驗機構進行排放量調查，並將查驗結果每半年提送直轄市、縣（市）主管機關",
  "應由所轄事業自行調查統計後逕送中央主管機關，目的事業主管機關無須另行辦理研議"],"a",
 "第13條第1項：中央目的事業主管機關應進行排放量之調查及統計之研議，並將調查及統計成果每年定期提送中央主管機關。中央主管機關再依第2項建立國家溫室氣體排放清冊並每三年編撰國家報告。",
 "What must central industry authorities do about emissions surveys and statistics?",
 ["Study and conduct emissions surveys and statistics, and submit the results to the central authority periodically each year",
  "Study and conduct emissions surveys and statistics, and submit the results every three years to the Executive Yuan for disclosure",
  "Commission verification bodies to survey emissions and submit results every six months to local competent authorities",
  "Let regulated enterprises survey and report directly to the central authority, with no study duty for industry authorities"],
 "Article 13(1) requires annual submission of survey and statistical results."),

(L,"第14條",1,"氣候法-地方推動會",
 "直轄市、縣（市）氣候變遷因應推動會之召集人及委員如何產生？",
 ["由直轄市、縣（市）主管機關首長擔任召集人，委員由召集人就有關機關單位首長及專家學者派兼或聘兼",
  "由中央主管機關指派副首長擔任召集人，委員由中央主管機關遴聘之學者專家及民間團體代表擔任",
  "由地方議會議長擔任召集人，委員由議會各黨團依席次比例推薦地方公正人士擔任並報中央備查",
  "由環保局局長擔任召集人，委員由轄內排放量前十大事業之負責人及所屬查驗機構代表擔任"],"a",
 "第14條第1項：直轄市、縣（市）主管機關設氣候變遷因應推動會，由直轄市、縣（市）主管機關首長擔任召集人，職司跨局處因應氣候變遷事務之協調整合及推動；第2項：委員由召集人就有關機關、單位首長及氣候變遷因應學識經驗之專家、學者派兼或聘兼之。第15條、第20條之地方方案均須送該推動會。",
 "How are the convener and members of the local climate response promotion committee appointed?",
 ["The head of the local competent authority convenes it, and the convener appoints agency heads and experts as members",
  "The central authority designates a deputy head as convener, and appoints scholars, experts and NGO representatives as members",
  "The local council speaker convenes it, with members recommended by party caucuses in proportion to seats and reported to the center",
  "The environmental bureau director convenes it, with members from the ten largest emitters and their verification bodies"],
 "Article 14 makes the local authority head the convener, who appoints the members."),

(L,"第15條",2,"氣候法-地方減量方案",
 "直轄市、縣（市）主管機關訂修溫室氣體減量執行方案，應依何者為據並經何種程序？",
 ["應依行動綱領及部門行動方案廣詢意見後訂修，送推動會並報中央主管機關會商中央目的事業主管機關核定",
  "應依國家調適計畫及碳費費率廣詢意見後訂修，送地方議會決議通過後逕行公告實施並對外公開",
  "應依中央主管機關公告之效能標準訂修，送中央目的事業主管機關核定後報行政院備查並對外公開",
  "應依轄內事業自行提報之自願減量專案彙整訂定，送推動會備查後即生效，無須報中央機關核定"],"a",
 "第15條第1項：直轄市、縣（市）主管機關應依行動綱領及部門行動方案，邀集有關機關、學者、專家、民間團體舉辦座談會或以其他適當方法廣詢意見，訂修減量執行方案，送直轄市、縣（市）氣候變遷因應推動會，報請中央主管機關會商中央目的事業主管機關核定後實施並對外公開。第2項並要求每年編寫成果報告。",
 "On what basis and by what procedure do local authorities adopt reduction implementation programs?",
 ["Based on the action guidelines and sectoral programs, sent to the promotion committee and approved by the central authority",
  "Based on the national adaptation plan and carbon fee rates, resolved by the local council and then announced directly to the public",
  "Based on efficiency standards announced by the central authority, approved by industry authorities and filed with the Executive Yuan",
  "Compiled from voluntary reduction projects submitted by local enterprises, effective once filed with the promotion committee"],
 "Article 15 requires local programs to follow the guidelines and be centrally approved."),

(L,"第16條",1,"氣候法-輔導",
 "依第16條，目的事業主管機關對事業應提供何種輔導？",
 ["應輔導事業進行排放源排放量之盤查、查驗、登錄、減量及參與國內或國際合作採行減量措施",
  "應輔導事業辦理碳費之申報繳納、滯納金計算及裁罰基準之適用，並代為向中央主管機關陳報",
  "應輔導事業辦理排放額度之免費核配、拍賣底價訂定及碳市場價格之公告等交易相關事宜",
  "應輔導事業辦理環境影響評估、水污染防治許可及廢棄物清理計畫書之審查與變更程序"],"a",
 "第16條：目的事業主管機關應輔導事業進行排放源排放量之盤查、查驗、登錄、減量及參與國內或國際合作採行溫室氣體減量措施。事業之盤查登錄義務規定於第21條，查驗機構之許可則規定於第22條。",
 "What guidance must industry authorities give enterprises under Article 16?",
 ["Guidance on inventorying, verifying, registering and reducing emissions and joining domestic or international reduction measures",
  "Guidance on filing and paying carbon fees, calculating late fees and applying penalty criteria, and reporting on their behalf",
  "Guidance on free allocation of allowances, setting auction floor prices and announcing carbon market prices and related trading",
  "Guidance on environmental impact assessment, water pollution permits and review of waste disposal plans and their changes"],
 "Article 16 requires guidance on inventory, verification, registration and reduction."),

(L,"第17條",2,"氣候法-調適",
 "依第17條，政府應推動之氣候變遷調適能力建構事項，下列何者正確？",
 ["以科學為基礎檢視現有資料、推估未來氣候變遷並評估氣候變遷風險，藉以強化風險治理及調適能力",
  "以事業自主揭露為基礎彙整排放資料，據以核算碳費費率並公告各行業之免費核配比例及期程",
  "以地方政府財政能力為基礎分配調適預算，並由中央主管機關統一興建各縣市之防災工程設施",
  "以歷史災害統計為唯一依據訂定調適目標，不納入未來氣候情境推估及跨領域協商機制之考量"],"a",
 "第17條第1項第1款：以科學為基礎，檢視現有資料、推估未來可能之氣候變遷，並評估氣候變遷風險，藉以強化風險治理及氣候變遷調適能力。第18條並要求中央主管機關與中央科技主管機關定期公開氣候變遷科學報告，作為各級政府風險評估之依據。",
 "Which adaptation capacity-building item is required by Article 17?",
 ["Science-based review of existing data, projection of future climate change and risk assessment to strengthen risk governance and adaptation",
  "Compiling emissions data from voluntary disclosure to set carbon fee rates and announce free allocation ratios by sector",
  "Allocating adaptation budgets by local fiscal capacity, with the central authority building all local disaster works",
  "Setting adaptation targets solely on historical disaster statistics, excluding future climate scenarios and cross-domain coordination"],
 "Article 17(1)(1) requires science-based risk assessment for adaptation capacity."),

(L,"第17條",2,"氣候法-調適",
 "依第17條規定，國民、事業及團體對氣候變遷調適能力建構事項負有何種責任？",
 ["應致力參與政府所推動之各項氣候變遷調適能力建構事項",
  "應每年提報調適成果報告送直轄市、縣（市）主管機關核定",
  "應繳納調適基金分擔金，作為地方推動調適工作之財源",
  "並無任何法定責任，調適能力建構事項專屬政府機關職掌"],"a",
 "第17條第2項：國民、事業、團體應致力參與前項氣候變遷調適能力建構事項。同條第1項第8款、第9款並要求強化脆弱群體因應衝擊之能力，及融入以社區及原住民族為本之調適政策及措施。",
 "What responsibility do citizens, enterprises and groups bear for adaptation capacity building?",
 ["They shall endeavor to participate in the adaptation capacity-building items promoted by the government",
  "They shall submit annual adaptation results reports to the local competent authority for approval",
  "They shall pay adaptation fund contributions to finance local adaptation work",
  "They bear no legal responsibility, as adaptation is exclusively a government matter"],
 "Article 17(2) requires citizens, enterprises and groups to participate."),

(L,"第18條",3,"氣候法-調適",
 "氣候變遷科學報告之研提及氣候變遷風險評估作業準則之訂定，分別由何者辦理？",
 ["科學報告由中央主管機關與中央科技主管機關並與氣象主管機關共同研析定期公開；風險評估作業準則由中央主管機關會商有關機關定之",
  "科學報告由氣象主管機關單獨編製並每年公開；風險評估作業準則由中央科技主管機關會商地方主管機關訂定並公告實施",
  "科學報告由永續會邀集學者專家編製並公開；風險評估作業準則由各中央目的事業主管機關就其權責領域分別訂定發布",
  "科學報告由各直轄市主管機關分別編製彙整；風險評估作業準則由行政院統一訂定後函頒各機關遵照辦理"],"a",
 "第18條第1項：中央主管機關與中央科技主管機關應進行氣候變遷科學及衝擊調適研究發展，並與氣象主管機關共同研析及掌握氣候變遷趨勢，定期公開氣候變遷科學報告。第2項要求輔導各級政府據以進行風險評估；第3項規定風險評估之作業準則由中央主管機關會商有關機關定之。",
 "Who produces the climate science report and who sets the risk assessment guidelines?",
 ["The competent and science authorities publish the report with the meteorological authority; the central authority sets the guidelines",
  "The meteorological authority alone compiles and publishes the report yearly; the science authority sets the guidelines with local authorities",
  "The sustainable development council compiles the report with experts; each industry authority sets its own risk assessment guidelines",
  "Municipal authorities compile and consolidate the report; the Executive Yuan sets uniform guidelines and circulates them to agencies"],
 "Article 18 assigns the report jointly and the guidelines to the central authority."),

(L,"第19條",2,"氣候法-調適行動方案",
 "中央目的事業主管機關就易受氣候變遷衝擊之權責領域，應訂定幾年為一期之調適行動方案？",
 ["四年為一期，並依第五條第三項、第六條及第十七條訂定調適目標",
  "五年為一期，並依第四條之國家長期減量目標訂定該領域調適目標",
  "三年為一期，並依中央主管機關公告之效能標準訂定調適目標數值",
  "十年為一期，並依直轄市、縣（市）調適執行方案訂定調適目標"],"a",
 "第19條第1項：中央目的事業主管機關應就易受氣候變遷衝擊之權責領域，訂定四年為一期之該領域調適行動方案，並依第5條第3項、第6條及第17條訂定調適目標。第3項並規定中央主管機關應整合各領域調適行動方案，擬訂國家氣候變遷調適行動計畫報行政院核定。",
 "What is the cycle for sectoral climate adaptation action programs?",
 ["Four-year periods, with adaptation goals set under Articles 5(3), 6 and 17",
  "Five-year periods, with adaptation goals set under the long-term reduction goal in Article 4",
  "Three-year periods, with adaptation goals set by the efficiency standards announced centrally",
  "Ten-year periods, with adaptation goals set by local adaptation implementation programs"],
 "Article 19(1) requires four-year sectoral adaptation action programs."),

(L,"第19條",2,"氣候法-調適行動方案",
 "國家氣候變遷調適行動計畫之擬訂及調適行動方案成果報告之編寫，下列敘述何者正確？",
 ["國家調適計畫由中央主管機關整合各領域方案擬訂報行政院核定；成果報告由中央目的事業主管機關每年編寫送中央主管機關",
  "國家調適計畫由永續會整合各領域方案逕行公告實施；成果報告由中央主管機關每二年彙編後送立法院審議並公開",
  "國家調適計畫由各中央目的事業主管機關聯合發布實施；成果報告由地方主管機關每年編寫送推動會後對外公開",
  "國家調適計畫由行政院逕行核定並交中央主管機關執行；成果報告由查驗機構每年查驗後送中央主管機關備查"],"a",
 "第19條第3項：中央主管機關應依行動綱領，整合第1項調適行動方案，擬訂國家氣候變遷調適行動計畫，報請行政院核定後實施並對外公開。第4項：中央目的事業主管機關應每年編寫調適行動方案成果報告，送中央主管機關報請行政院核定後對外公開。",
 "Who prepares the national adaptation action plan and the annual results reports?",
 ["The central authority consolidates sectoral programs into the national plan for Executive Yuan approval; industry authorities write annual results reports for it",
  "The sustainable development council consolidates and announces the national plan; the central authority compiles reports biennially for the Legislative Yuan",
  "Central industry authorities jointly issue the national plan; local authorities write annual reports for their promotion committees",
  "The Executive Yuan adopts the plan directly for the central authority to execute; verification bodies file annual reports"],
 "Article 19(3)-(4) assign the national plan centrally and annual reports to industry authorities."),

(L,"第20條",2,"氣候法-地方調適",
 "直轄市、縣（市）氣候變遷調適執行方案之訂修及成果報告，下列敘述何者正確？",
 ["應依行動綱領、國家調適計畫及調適行動方案訂修，送推動會並報中央主管機關會商中央目的事業主管機關核定",
  "應依碳費費率及排放額度核配情形訂修，送地方議會審議通過後即實施，無須報請中央主管機關核定",
  "應依中央主管機關公告之查驗規範訂修，送查驗機構查驗合格後對外公開，並每三年編寫成果報告",
  "應依轄內事業之自願減量專案訂修，送中央目的事業主管機關逕行核定後實施，每半年編寫成果報告"],"a",
 "第20條第1項：直轄市、縣（市）主管機關應依行動綱領、國家調適計畫及調適行動方案，廣詢意見訂修調適執行方案，送直轄市、縣（市）氣候變遷因應推動會，報請中央主管機關會商中央目的事業主管機關核定後實施並對外公開。第2項：應每年編寫成果報告，送推動會後對外公開。",
 "How are local climate adaptation implementation programs adopted?",
 ["Based on the guidelines, national plan and sectoral programs, sent to the promotion committee and approved by the central authority",
  "Based on carbon fee rates and allowance allocation, effective once the local council approves, with no central approval needed",
  "Based on centrally announced verification rules, disclosed after a verification body certifies them, with reports every three years",
  "Based on local enterprises' voluntary reduction projects, approved directly by industry authorities, with semi-annual reports"],
 "Article 20 requires local adaptation programs to be centrally approved."),

(L,"第21條",2,"氣候法-盤查登錄",
 "事業具有經中央主管機關公告之排放源者，依第21條負有何種義務？",
 ["應進行排放量盤查並於規定期限前登錄於中央主管機關指定資訊平台；經公告指定應查驗者並應經查驗機構查驗",
  "應進行排放量盤查並自行保存紀錄五年備查，除主管機關派員檢查外無須登錄於任何資訊平台",
  "應委由目的事業主管機關代為盤查登錄，事業僅需配合提供原始能源使用及產品產量之資料",
  "應於每年底前將排放量申報至地方主管機關，由地方主管機關彙整後轉送中央主管機關公開"],"a",
 "第21條第1項：事業具有經中央主管機關公告之排放源，應進行排放量盤查，並於規定期限前登錄於中央主管機關指定資訊平台；其經中央主管機關公告指定應查驗者，盤查相關資料並應經查驗機構查驗。第2項授權中央主管機關訂定盤查、登錄之頻率、紀錄、期限及查驗方式等辦法，違反者依第49條第1項處罰。",
 "What duty does Article 21 impose on enterprises with announced emission sources?",
 ["Conduct an emissions inventory and register it on the designated platform by the deadline; verification by a body if so designated",
  "Conduct an inventory and keep records for five years for inspection, with no duty to register on any information platform",
  "Have the industry authority do the inventory and registration, with the enterprise only supplying energy use and output data",
  "Report emissions to the local authority by year end, which compiles and forwards them to the central authority"],
 "Article 21(1) requires inventory, registration and, where designated, verification."),

(L,"第21條",3,"氣候法-盤查登錄",
 "事業違反依第21條第2項所定辦法中有關盤查、登錄頻率、紀錄、期限或管理之規定，經通知限期補正或改善屆期未完成者，應如何處罰？",
 ["處新臺幣十萬元以上一百萬元以下罰鍰，並通知限期補正或改善；屆期仍未完成者，按次處罰",
  "處新臺幣二十萬元以上二百萬元以下罰鍰，並得逕行令其停工或停業，不再通知限期改善",
  "處新臺幣一萬元以上十萬元以下罰鍰，並註銷其於中央主管機關指定平台開立之交易帳戶",
  "處新臺幣三十萬元以上三百萬元以下罰鍰，並追繳最近五年內應繳納之碳費及滯納金"],"a",
 "第49條第1項：事業違反依第21條第2項所定辦法中有關排放量盤查、登錄之頻率、紀錄、應登錄事項、期限或管理之規定，經通知限期補正或改善屆期未完成者，處新臺幣十萬元以上一百萬元以下罰鍰，並通知限期補正或改善，屆期仍未完成者按次處罰。若係明知不實而盤查、登錄，則依第47條處二十萬元以上二百萬元以下罰鍰。",
 "What penalty applies for breaching the inventory and registration regulations under Article 21(2)?",
 ["A fine of NT$100,000 to NT$1,000,000, with notice to correct within a deadline and repeated fines if not completed",
  "A fine of NT$200,000 to NT$2,000,000, with an immediate order to halt work or business and no correction period",
  "A fine of NT$10,000 to NT$100,000, with cancellation of the trading account opened on the designated platform",
  "A fine of NT$300,000 to NT$3,000,000, with recovery of carbon fees and late charges for the past five years"],
 "Article 49(1) sets a fine of NT$100,000 to NT$1,000,000 with repeated penalties."),

(L,"第22條",2,"氣候法-查驗機構",
 "查驗機構須具備何種要件，始得辦理本法所定查驗事宜？",
 ["應先向中央主管機關或其委託（任）之認證機關（構）申請認證，並取得中央主管機關許可",
  "應先取得直轄市、縣（市）主管機關核發之許可證，並向中央主管機關辦理登記備查即可",
  "應先取得目的事業主管機關之委辦，並與受查驗事業簽訂契約報中央主管機關核備即可",
  "應先由查驗人員個別取得合格證書，機構本身無須認證或許可，即得逕行辦理查驗事宜"],"a",
 "第22條第1項：查驗機構應先向中央主管機關或其委託（任）之認證機關（構）申請認證後，並取得中央主管機關許可，始得辦理本法所定查驗事宜。第2項、第3項分別授權訂定查驗機構許可及認證機構資格之辦法；未取得許可逕行查驗者，依第49條第2項處十萬元以上一百萬元以下罰鍰。",
 "What must a verification body obtain before performing verification under the Act?",
 ["Accreditation from the central authority or its commissioned accreditation body, and then a permit from the central authority",
  "A permit issued by the municipal or county/city competent authority, plus registration with the central authority for record",
  "A commission from the industry authority and a contract with the verified enterprise filed with the central authority",
  "Only individual certificates for its verification personnel, with no accreditation or permit needed for the body itself"],
 "Article 22(1) requires accreditation followed by a central permit."),

(L,"第23條",2,"氣候法-效能標準",
 "依第23條，下列何者應符合效能標準或減緩溫室氣體排放之規定？",
 ["中央主管機關公告產品之生產過程排放、指定車輛之排放，及新建築之構造與設備",
  "中央主管機關公告產品之運輸過程排放、既有廠房之空調設備，及既有建築之外牆材料",
  "地方主管機關公告之營建工地機具排放、農業機械之排放，及新設加油站之儲槽設備",
  "目的事業主管機關指定之船舶排放、航空器排放，及新設變電所之輸配電設備規格"],"a",
 "第23條第1項至第3項：中央主管機關公告之產品，其生產過程排放溫室氣體應符合效能標準；事業製造或輸入中央主管機關指定之車輛供國內使用者，其車輛排放溫室氣體應符合效能標準；新建築之構造、設備應符合減緩溫室氣體排放之規定。第3條第14款並定義效能標準為單位產品、原（物）料、里程或其他單位用料容許之排放量。",
 "Which items must meet efficiency standards or emission mitigation rules under Article 23?",
 ["Production-process emissions of announced products, emissions of designated vehicles, and the structure and equipment of new buildings",
  "Transport-stage emissions of announced products, air conditioning in existing plants, and exterior wall materials of existing buildings",
  "Construction site machinery announced locally, agricultural machinery emissions, and storage tanks at new gas stations",
  "Ship and aircraft emissions designated by industry authorities, and transmission equipment specifications at new substations"],
 "Article 23(1)-(3) cover announced products, designated vehicles and new buildings."),

(L,"第23條",2,"氣候法-效能標準",
 "第23條所定效能標準及新建築減緩溫室氣體排放與查核之規定，其訂定程序為何？",
 ["由中央主管機關會商中央目的事業主管機關擬訂，報請行政院核定後發布",
  "由中央目的事業主管機關逕行擬訂並發布，僅須事後函送中央主管機關備查",
  "由中央主管機關邀集查驗機構共同擬訂，經公聽會程序後由中央主管機關公告",
  "由直轄市、縣（市）主管機關分別擬訂，報請中央主管機關核定後分區實施"],"a",
 "第23條第4項：第1項、第2項效能標準及第3項減緩溫室氣體排放及查核之規定，由中央主管機關會商中央目的事業主管機關擬訂，報請行政院核定後發布。此與第9條行動綱領、第10條階段管制目標同採報請行政院核定之程序。",
 "How are the efficiency standards under Article 23 established?",
 ["Drafted by the central authority in consultation with industry authorities and issued after Executive Yuan approval",
  "Drafted and issued by industry authorities directly, with only a later filing to the central authority for record",
  "Drafted by the central authority together with verification bodies and announced after a public hearing",
  "Drafted separately by municipal and county/city authorities and implemented regionally after central approval"],
 "Article 23(4): drafted with industry authorities and issued upon Executive Yuan approval."),

(L,"第24條",2,"氣候法-增量抵換",
 "事業新設或變更排放源達一定規模者，依第24條負有何種義務？有無替代方式？",
 ["應依溫室氣體增量之一定比率進行抵換；抵換確有困難經申請核可者，得繳納代金專作減量工作之用",
  "應依溫室氣體增量之全額進行抵換；抵換困難者得申請展延三年，期滿仍應全額完成抵換義務",
  "應向中央主管機關繳納增量保證金；於營運三年後排放量未增加者，得申請無息退還全部保證金",
  "應停止該新設或變更排放源之操作；經完成環境影響評估並取得地方主管機關同意後始得營運"],"a",
 "第24條第1項：事業新設或變更排放源達一定規模者，應依溫室氣體增量之一定比率進行抵換；但進行增量抵換確有困難，向主管機關提出申請經核可者，得繳納代金，專作溫室氣體減量工作之用。第26條第1款規定減量額度得用於本條之增量抵換；未依規定抵換者，依第52條第1款處十萬元以上一百萬元以下罰鍰。",
 "What must an enterprise do when a new or modified emission source reaches a certain scale?",
 ["Offset a set ratio of the GHG increment; if offsetting is genuinely difficult, pay an approved fee dedicated to reduction work",
  "Offset the full amount of the GHG increment; if difficult, apply for a three-year extension but still offset in full afterwards",
  "Pay an increment deposit to the central authority, refundable without interest after three years if emissions did not rise",
  "Halt operation of the new or modified source until an impact assessment is completed and local consent is obtained"],
 "Article 24(1) requires increment offsetting, with an approved fee as the alternative."),

(L,"第24條",2,"氣候法-增量抵換",
 "第24條第1項所稱一定規模、增量抵換一定比率、期程及代金之計算與繳納期限等事項，由何機關以何種方式定之？",
 ["由中央主管機關訂定辦法規範之",
  "由行政院會同立法院訂定準則規範之",
  "由中央目的事業主管機關逕行公告之",
  "由直轄市、縣（市）主管機關自訂之"],"a",
 "第24條第2項：前項一定規模、增量抵換一定比率、期程、抵換來源、繳納代金之申請程序、代金之計算、繳納期限、繳納方式及其他應遵行事項之辦法，由中央主管機關定之。未依該辦法期限繳納代金者，依第60條每逾一日加徵百分之零點五滯納金。",
 "Who prescribes the scale, offset ratio and fee rules under Article 24(2)?",
 ["The central competent authority prescribes them by regulations",
  "The Executive Yuan and Legislative Yuan jointly prescribe them",
  "Central industry authorities announce them directly",
  "Municipal and county/city authorities set their own rules"],
 "Article 24(2) authorizes the central competent authority to issue the regulations."),

(L,"第25條",2,"氣候法-自願減量",
 "事業或各級政府執行自願減量專案取得減量額度，依第25條應如何辦理？",
 ["得自行或聯合提出專案向中央主管機關申請核准取得額度，並依規定條件及期限使用",
  "得逕行執行減量措施後自行計算額度，於指定平台登錄公開即完成取得程序無須核准",
  "應委由查驗機構核發減量額度，事業僅須將查驗結果報中央主管機關備查即可使用",
  "應由中央目的事業主管機關統一提出專案，個別事業不得單獨或聯合提出減量專案"],"a",
 "第25條第1項：事業或各級政府得自行或聯合共同提出自願減量專案，據以執行溫室氣體減量措施，向中央主管機關申請核准取得減量額度，並應依中央主管機關規定之條件及期限使用。第2項並規定中央主管機關得依專案類型指定查驗方式。",
 "How are credits obtained from voluntary reduction projects under Article 25?",
 ["Enterprises or governments may propose projects alone or jointly for central approval, using credits under prescribed conditions and deadlines",
  "They may implement measures and calculate credits themselves, completing acquisition by registering on the platform without approval",
  "Verification bodies issue the credits, and the enterprise need only file the verification result with the central authority",
  "Only central industry authorities may propose projects; individual enterprises may not propose them alone or jointly"],
 "Article 25(1) requires central approval of voluntary reduction projects."),

(L,"第25條",3,"氣候法-減量額度帳戶",
 "取得減量額度之事業及各級政府，就額度之帳戶及處分，依第25條第3項應如何辦理？",
 ["應向中央主管機關申請開立帳戶，將額度資訊公開於指定平台，並得移轉、交易或拍賣之",
  "應向中央金融主管機關申請開立帳戶，將額度資訊公開於證券交易所，並得質押或信託之",
  "應向目的事業主管機關申請開立帳戶，額度資訊列為營業秘密，並僅得於關係企業間移轉",
  "應向地方主管機關申請開立帳戶，額度資訊每年公告一次，且不得移轉、交易或拍賣之"],"a",
 "第25條第3項：執行抵換專案、先期專案及自願減量專案取得減量額度之事業及各級政府，應向中央主管機關申請開立帳戶，將減量額度之資訊公開於中央主管機關指定平台，並得移轉、交易或拍賣之。違反依第5項所定辦法中有關移轉、交易、拍賣對象或方式之規定者，依第51條第1款處罰並限制或停止交易。",
 "What must credit holders do about accounts and disposal of credits under Article 25(3)?",
 ["Apply to the central authority to open an account, disclose credit data on the designated platform, and may transfer, trade or auction them",
  "Apply to the central financial authority to open an account, disclose on the stock exchange, and may pledge or place them in trust",
  "Apply to the industry authority to open an account, treat credit data as trade secrets, and transfer only among affiliates",
  "Apply to the local authority to open an account, disclose annually, and may not transfer, trade or auction the credits"],
 "Article 25(3) requires a central account, platform disclosure, and permits transfer or trade."),

(L,"第26條",2,"氣候法-減量額度用途",
 "依第26條，減量額度之用途不包括下列何者？",
 ["折抵事業依本法應繳納之罰鍰金額及其滯納金",
  "進行第二十四條第一項新設或變更排放源之增量抵換",
  "扣除第二十八條第一項各款所定碳費之收費排放量",
  "抵銷第三十六條第二項超過核配額度之超額量"],"a",
 "第26條列舉減量額度用途為：增量抵換、扣除第28條第1項各款之排放量、扣除第31條第1項之排碳差額、抵銷第36條第2項之超額量及其他經中央主管機關認可之用途。罰鍰及滯納金非屬法定用途，滯納金依第60條每逾一日按滯納金額加徵百分之零點五。",
 "Which is NOT a permitted use of reduction credits under Article 26?",
 ["Offsetting fines payable under the Act and the late payment charges arising from them",
  "Offsetting greenhouse gas increments for new or modified sources under Article 24(1)",
  "Deducting from the chargeable carbon fee emissions specified in Article 28(1)",
  "Offsetting the excess emissions above allocated allowances under Article 36(2)"],
 "Article 26 lists four uses plus others approved centrally; fines are not among them."),

(L,"第27條",2,"氣候法-國外額度",
 "事業取得國外減量額度者，依第27條應經何種程序始得使用？其比率如何決定？",
 ["應經中央主管機關認可後始得扣除排放量或抵銷超額量；比率由中央主管機關會商中央目的事業主管機關定之",
  "應經查驗機構查驗合格後即得扣除排放量或抵銷超額量；比率由查驗機構依國際慣例逐案認定之",
  "應經外交部及財政部會銜同意後始得扣除排放量；比率由行政院逐年公告並送立法院審議通過",
  "應經地方主管機關備查後即得抵銷超額量；比率由事業依其減量成本自行決定並於平台公開"],"a",
 "第27條第1項：事業取得國外減量額度者，應經中央主管機關認可後，始得扣除第28條第1項各款之排放量或抵銷第36條第2項之超額量。第2項：認可及扣除比率等事項，由中央主管機關參酌聯合國氣候變化綱要公約與其協議或相關國際公約決議事項、能源效率提升、國內減量額度取得及長期減量目標達成等要素，會商中央目的事業主管機關定之。",
 "What procedure applies to foreign reduction credits under Article 27?",
 ["Central authority recognition is required before deducting emissions or offsetting excess; the ratio is set with industry authorities",
  "Verification body certification suffices before deduction or offsetting; the ratio is decided case by case under international practice",
  "Joint consent of the foreign affairs and finance ministries is required; the ratio is announced yearly and approved by the Legislative Yuan",
  "Local authority filing suffices for offsetting; the enterprise sets the ratio by its own reduction cost and discloses it"],
 "Article 27 requires central recognition of foreign credits before use."),

(L,"第28條",2,"氣候法-碳費",
 "依第28條第1項，中央主管機關得分階段對何種排放源徵收碳費？向何人徵收？",
 ["直接排放源及間接排放源，向排放源之所有人徵收；所有人非使用人或管理人者，向實際使用人或管理人徵收",
  "僅直接排放源，向排放源所在土地之所有權人徵收；土地為公有者，向管理機關之上級機關徵收",
  "僅間接排放源，向售電之電業徵收；電業得於電費帳單中列項向其用電之終端使用者轉嫁收取",
  "直接排放源及間接排放源，一律向事業之代表人徵收；代表人變更時由新任代表人補繳全額"],"a",
 "第28條第1項第1款、第2款：直接排放源依其排放量、間接排放源依其使用電力間接排放之排放量，均向排放源之所有人徵收；其所有人非使用人或管理人者，向實際使用人或管理人徵收。第2項並規定生產電力之直接排放源，得檢具提供電力消費之排放量證明文件，申請扣除第1款之排放量。",
 "Which sources are subject to the carbon fee and from whom is it collected?",
 ["Direct and indirect sources; collected from the owner, or from the actual user or manager if the owner is neither",
  "Direct sources only; collected from the landowner where the source sits, or the supervising agency if publicly owned",
  "Indirect sources only; collected from the electricity retailer, which may pass it to end users on their bills",
  "Direct and indirect sources; always collected from the enterprise's representative, with successors paying in full"],
 "Article 28(1) covers direct and indirect sources, charged to owners or actual users."),

(L,"第28條",2,"氣候法-碳費",
 "碳費之徵收費率如何審議及核定？",
 ["由中央主管機關所設費率審議會依減量現況、排放源類型、排放量規模、自主減量情形等審議，送中央主管機關核定公告並定期檢討",
  "由行政院所設碳定價委員會依國際碳價及匯率審議，送立法院決議後由中央主管機關公告實施並每十年檢討",
  "由中央目的事業主管機關依各行業產值及貿易強度分別訂定，報中央主管機關備查後公告，不定期檢討調整",
  "由中央金融主管機關依碳市場交易均價按月計算後公告，中央主管機關僅負責徵收作業及欠費之追繳"],"a",
 "第28條第3項：第1項碳費之徵收費率，由中央主管機關所設之費率審議會依我國溫室氣體減量現況、排放源類型、溫室氣體排放種類、排放量規模、自主減量情形及減量效果及其他相關因素審議，送中央主管機關核定公告，並定期檢討之。第29條並規定達指定目標之自主減量計畫得申請核定優惠費率。",
 "How is the carbon fee rate reviewed and approved?",
 ["A rate review committee under the central authority reviews it against reduction status, source types, scale and self-reduction; the authority approves and announces it",
  "A carbon pricing committee under the Executive Yuan reviews it against international prices and exchange rates, subject to Legislative Yuan resolution and decennial review",
  "Industry authorities set rates by sector output and trade intensity, file them centrally for record and announce them, reviewing them irregularly",
  "The central financial authority calculates and announces it monthly from average market prices, with the central authority only collecting arrears"],
 "Article 28(3) assigns rate review to a committee under the central authority."),

(L,"第28條",3,"氣候法-碳費",
 "生產電力之直接排放源，就其提供電力消費所產生之排放量，得如何處理？",
 ["得檢具提供電力消費之排放量證明文件，向中央主管機關申請扣除直接排放源之排放量",
  "得檢具電費收據及售電契約，向中央目的事業主管機關申請退還已繳納碳費之半數金額",
  "得將該部分排放量移轉登錄至用電事業之帳戶，並由用電事業依間接排放源費率繳納碳費",
  "得免予申報該部分排放量，逕以年度總發電量乘以電力排放係數計算應繳納之碳費金額"],"a",
 "第28條第2項：生產電力之直接排放源，得檢具提供電力消費之排放量證明文件，向中央主管機關申請扣除前項第1款之排放量。此係為避免與第1項第2款間接排放源（用電者）之碳費重複課徵。第35條第3項亦有公用事業核配額應扣除間接排放額度之類似設計。",
 "How may a power-generating direct source treat emissions from electricity supplied to consumers?",
 ["Submit documentation of the emissions from electricity supplied and apply to deduct them from its direct source emissions",
  "Submit electricity receipts and sales contracts to the industry authority and apply for a refund of half the carbon fee paid",
  "Transfer and register those emissions to the electricity user's account, which then pays at the indirect source rate",
  "Omit reporting those emissions and instead compute the fee from total generation times the power emission factor"],
 "Article 28(2) allows deduction on proof of emissions from electricity supplied."),

(L,"第29條",2,"氣候法-優惠費率",
 "碳費徵收對象採行何種措施並達成何種要件，始得申請核定優惠費率？",
 ["因轉換低碳燃料、採行負排放技術、提升能源效率、使用再生能源或製程改善等措施，有效減量並達中央主管機關指定目標",
  "因擴大生產規模、增加僱用員工人數、提高研發支出比率或取得國際認證等措施，並經目的事業主管機關推薦",
  "因參與國際碳市場交易、購買足額國外減量額度或投資海外減碳專案，並經中央金融主管機關同意",
  "因設籍於偏遠地區、屬中小企業規模或年營業額未達一定金額，並經地方主管機關查核屬實"],"a",
 "第29條第1項：碳費徵收對象因轉換低碳燃料、採行負排放技術、提升能源效率、使用再生能源或製程改善等溫室氣體減量措施，能有效減少溫室氣體排放量並達中央主管機關指定目標者，得提出自主減量計畫向中央主管機關申請核定優惠費率。第2項規定指定目標由中央主管機關會商有關機關定之。",
 "What qualifies a carbon fee payer to apply for a preferential rate?",
 ["Switching to low-carbon fuels, negative emission technology, energy efficiency, renewables or process improvement that cuts emissions to the designated target",
  "Expanding production, hiring more employees, raising R&D spending or obtaining international certification, with a recommendation from the industry authority",
  "Joining international carbon markets, buying sufficient foreign credits or investing in overseas reduction projects with financial authority consent",
  "Being located in a remote area, qualifying as an SME or having turnover below a set amount, as verified by the local authority"],
 "Article 29(1) grants preferential rates for self-reduction plans meeting designated targets."),

(L,"第30條",2,"氣候法-額度扣除",
 "碳費徵收對象欲以減量額度扣除第28條第1項各款之排放量者，應如何辦理？",
 ["應向中央主管機關申請核准，其扣減比率、上限及審查程序等事項依中央主管機關所定辦法辦理",
  "應向中央目的事業主管機關申報後即得扣除，扣減比率由事業依其自主減量計畫內容自行決定",
  "應向查驗機構申請查驗合格後逕行扣除，扣減上限為當年度應繳碳費金額之半數並報備查",
  "應向地方主管機關申請並經推動會決議通過，扣減比率由地方主管機關視轄內減量情形決定"],"a",
 "第30條第1項：碳費徵收對象得向中央主管機關申請核准以減量額度扣除第28條第1項各款之排放量。第2項：適用對象、應檢具文件、減量額度扣減比率、上限、審查程序、廢止、補足額度及其他應遵行事項之辦法，由中央主管機關定之。減量額度之來源見第25條，國外額度另須依第27條經認可。",
 "How may a carbon fee payer use credits to deduct chargeable emissions?",
 ["Apply to the central authority for approval, with deduction ratios, caps and review procedures set by its regulations",
  "Report to the industry authority and deduct directly, with the ratio decided by the enterprise in its self-reduction plan",
  "Deduct after a verification body certifies it, capped at half of the annual fee payable, and file it for record",
  "Apply to the local authority with promotion committee approval, with the ratio set locally by reduction conditions"],
 "Article 30 requires central approval for using credits to deduct chargeable emissions."),

(L,"第31條",3,"氣候法-碳邊境",
 "事業進口經中央主管機關公告之產品，依第31條第1項負有何種義務？",
 ["應向中央主管機關申報產品碳排放量，並依審查核定之排碳差額，於第二十五條之平台取得減量額度",
  "應向財政部關務署申報產品碳排放量，並依核定之排碳差額，於進口時按差額繳納碳關稅及規費",
  "應向中央目的事業主管機關申報產品產地證明，並依該國碳價水準補繳相當金額之碳費及利息",
  "應向查驗機構申報產品碳足跡，並依查驗結果於產品外包裝分級標示後始得於國內販賣使用"],"a",
 "第31條第1項：為避免碳洩漏，事業進口經中央主管機關公告之產品，應向中央主管機關申報產品碳排放量，並依中央主管機關審查核定之排碳差額，於第25條之平台取得減量額度；但於出口國已實施排放交易、繳納碳稅或碳費且未於出口時退費者，得檢附證明文件申請核定減免。第2項規定未取得足夠額度者應繳納代金。",
 "What duty does Article 31(1) impose on importers of announced products?",
 ["Report the product's carbon emissions to the central authority and obtain credits on the Article 25 platform for the approved carbon differential",
  "Report the product's carbon emissions to Customs and pay a carbon border tariff and fees on the approved differential at import",
  "Report the product's origin certificate to the industry authority and pay carbon fees plus interest matching that country's carbon price",
  "Report the product's carbon footprint to a verification body and apply graded labeling before domestic sale or use"],
 "Article 31(1) requires reporting emissions and obtaining credits for the carbon differential."),

(L,"第31條",3,"氣候法-碳邊境",
 "進口產品於出口國已實施排放交易、繳納碳稅或碳費之情形，及未取得足夠減量額度時，應如何處理？",
 ["出口時未退費者得檢附證明文件申請核定減免應取得之額度；未取得足夠額度者，應向中央主管機關繳納代金",
  "出口時已退費者仍得檢附證明文件申請全額免除；未取得足夠額度者，應退運該批產品並限期辦理出口",
  "凡出口國有碳定價制度者一律免除取得額度義務；未取得足夠額度者，處以貨價三倍之罰鍰並沒入產品",
  "出口國稅費得全額抵充應繳之碳費；未取得足夠額度者，由中央主管機關逕行自其排放額度帳戶扣減"],"a",
 "第31條第1項但書：於出口國已實施排放交易、繳納碳稅或碳費且未於出口時退費者，得檢附相關證明文件，向中央主管機關申請核定減免應取得之減量額度。第2項：事業未依前項規定取得足夠減量額度，應向中央主管機關繳納代金；逾期未繳納者依第60條加徵滯納金。",
 "How are foreign carbon costs and insufficient credits handled under Article 31?",
 ["If not refunded on export, documents may support approved relief from credits required; insufficient credits require paying a fee centrally",
  "Even if refunded on export, documents support full exemption; insufficient credits require the goods to be returned and re-exported",
  "Any exporting country carbon pricing exempts the duty entirely; insufficient credits bring a fine of triple the goods value and confiscation",
  "Foreign taxes fully offset the carbon fee payable; insufficient credits are deducted directly from the firm's allowance account"],
 "Article 31 allows relief for non-refunded foreign carbon costs and requires a fee otherwise."),
]
