# -*- coding: utf-8 -*-
# 第 10 批（D1）：水污染防治措施及檢測申報管理辦法 第1條～第43條之1
W = "ENV-09"
Q = [

(W,"第1條",1,"水措-授權依據",
 "本辦法係依據哪一部法律及其哪些條文規定訂定？",
 ["依水污染防治法第十八條、第十九條準用第十八條、第二十條第三項、第二十二條、第三十一條第二項及第三十二條第四項規定訂定","依水污染防治法第八條、第九條準用第八條、第十條第三項、第十二條、第二十一條第二項及第二十三條第四項規定訂定","依環境基本法第十八條、第十九條準用第十八條、第二十條第三項、第二十二條、第三十一條第二項及第三十二條第四項規定訂定","依下水道法第十八條、第十九條準用第十八條、第二十條第一項、第二十二條、第三十一條第四項及第三十二條第二項規定訂定"],"a",
 "第1條：本辦法依水污染防治法第十八條、第十九條準用第十八條、第二十條第三項、第二十二條、第三十一條第二項及第三十二條第四項規定訂定之。第4條並要求事業或污水下水道系統應採行核發機關核准之水污染防治措施，並依核准內容運作。",
 "This regulation is promulgated under which act and which provisions?",
 ["Water Pollution Control Act Articles 18, 19 (applying 18), 20-III, 22, 31-II and 32-IV","Water Pollution Control Act Articles 8, 9 (applying 8), 10-III, 12, 21-II and 23-IV","Basic Environment Act Articles 18, 19 (applying 18), 20-III, 22, 31-II and 32-IV","Sewerage Act Articles 18, 19 (applying 18), 20-I, 22, 31-IV and 32-II"],
 "Article 1 lists the enabling provisions of the Water Pollution Control Act."),

(W,"第2條",2,"水措-定義",
 "本辦法所稱最初稀釋率之意義為何？以海洋放流管線排放於海洋者，其最初稀釋率應達多少？",
 ["指廢水自管線排入海洋後上升達平衡狀態時，水柱中心與周遭海水混合所得之稀釋倍數；應達一百倍以上","指廢水自管線排入海洋前於岸上加水稀釋時，貯留槽中心與補充清水混合所得之稀釋倍數；應達五十倍以上","指廢水自管線排入海洋後沉降達靜止狀態時，海床表面與底層海水混合所得之稀釋倍數；應達二百倍以上","指廢水自管線排入海洋後上升達平衡狀態時，水柱邊緣與河川淡水混合所得之稀釋倍數；應達一千倍以上"],"a",
 "第2條第7款：最初稀釋率指廢（污）水自管線排入海洋後，上升達平衡狀態時，廢水水柱中心與周遭海水混合所得之稀釋倍數。第8款：以海放管排放於海洋者，其最初稀釋率須達一百倍以上。第35條要求每年定期檢視海放管結構，確認稀釋率達一百倍以上之功能。",
 "What is the initial dilution ratio, and what value must sea outfall discharge reach?",
 ["Dilution when the rising plume reaches equilibrium, mixing the plume core with surrounding seawater; at least 100 times","Dilution on shore before piping, mixing the storage tank core with make-up fresh water; at least 50 times","Dilution when the plume settles to rest, mixing the seabed surface with bottom seawater; at least 200 times","Dilution when the rising plume reaches equilibrium, mixing the plume edge with river fresh water; at least 1,000 times"],
 "Article 2 subparagraphs 7 and 8."),

(W,"第2條",2,"水措-定義",
 "本辦法對非連續性排放及 TUa 之定義為何？",
 ["非連續性排放指放流水非每日二十四小時持續排放至承受水體或核准排放口；TUa 為生物急毒性半數致死濃度之倒數","非連續性排放指放流水每日二十四小時持續排放至承受水體或核准排放口；TUa 為生物急毒性半數致死濃度之對數","非連續性排放指放流水非每週七日持續排放至承受水體或核准排放口；TUa 為生物慢毒性無觀察效應濃度之倒數","非連續性排放指放流水非每月三十日持續排放至承受水體或核准排放口；TUa 為生物急毒性半數抑制濃度之平方"],"a",
 "第2條第11款：非連續性排放指放流水非每日二十四小時持續自放流口排放至承受水體，或自下水道管理機關（構）核准之排放口排入污水下水道。第14款：TUa 為生物急毒性檢測時半數致死濃度 LC50 之倒數。第84條之1並以 TUa 值一．四三作為調整檢測申報頻率之判準。",
 "How are non-continuous discharge and TUa defined?",
 ["Effluent not discharged 24 hours a day to receiving water or an approved outlet; TUa is the reciprocal of the acute LC50","Effluent discharged 24 hours a day to receiving water or an approved outlet; TUa is the logarithm of the acute LC50","Effluent not discharged 7 days a week to receiving water or an approved outlet; TUa is the reciprocal of the chronic NOEC","Effluent not discharged 30 days a month to receiving water or an approved outlet; TUa is the square of the acute IC50"],
 "Article 2 subparagraphs 11 and 14."),

(W,"第3條",2,"水措-廢水類別",
 "本辦法所定事業廢水類別包括哪四類？",
 ["作業廢水、洩放廢水、未接觸冷卻水、逕流廢水","作業廢水、洩放廢水、接觸冷卻水、生活污水","製程廢水、貯留廢水、未接觸冷卻水、逕流廢水","作業廢水、稀釋廢水、未接觸冷卻水、滲出廢水"],"a",
 "第3條：事業廢水類別為作業廢水、洩放廢水、未接觸冷卻水及逕流廢水。作業廢水指製造、加工、冷卻、沖洗、畜殖等作業時與人或物直接接觸之廢水；未接觸冷卻水指於熱交換管線內專供溫度交換之水；逕流廢水指雨水沖刷戶外設施、地面、原料而產生之廢水。",
 "Which four categories of industrial wastewater does the regulation define?",
 ["Process wastewater, blowdown wastewater, non-contact cooling water, runoff wastewater","Process wastewater, blowdown wastewater, contact cooling water, domestic sewage","Manufacturing wastewater, stored wastewater, non-contact cooling water, runoff wastewater","Process wastewater, dilution wastewater, non-contact cooling water, leachate wastewater"],
 "Article 3."),

(W,"第4條",1,"水措-核准運作",
 "事業或污水下水道系統採行水污染防治措施時，應如何辦理？",
 ["應採行經核發機關核准之水污染防治措施，並依核准之水措內容運作","應採行經目的事業主管機關備查之水措，並得自行調整水措內容運作","應採行經環境檢驗測定機構認可之水措，並依同業慣例之內容運作","應採行經公會或技師公會審查之水措，並依技師簽證之內容自行運作"],"a",
 "第4條：事業或污水下水道系統應採行經直轄市、縣（市）主管機關或中央主管機關委託之機關（核發機關）核准之水污染防治措施，並依核准之水措內容運作。第62條並規定未經許可之排放、貯留、稀釋、繞流排放或未符規定之管線設施，應依限期改善命令封閉、拆移。",
 "How must an enterprise adopt water pollution control measures?",
 ["Adopt measures approved by the issuing authority and operate per the approved content","Adopt measures recorded by the industry competent authority and adjust the content freely","Adopt measures accredited by an environmental testing organization and follow industry practice","Adopt measures reviewed by a professional engineers association and follow certified content"],
 "Article 4."),

(W,"第5條",2,"水措-防範措施",
 "事業有疏漏污染物或廢水至水體、土壤之虞者，應採行何種措施？相關紀錄應保存多久？",
 ["應採取維護及防範措施，疏漏至作業環境之污染物應收集處理，並記錄日期、原因、水量及處理情形，保存三年","應採取維護及防範措施，疏漏至作業環境之污染物得逕行排放，並記錄日期、原因、水量及處理情形，保存一年","應採取停工及歇業措施，疏漏至作業環境之污染物應委外清除，並記錄日期、原因、水量及處理情形，保存五年","應採取維護及防範措施，疏漏至作業環境之污染物應稀釋處理，並記錄日期、原因、水量及處理情形，保存十年"],"a",
 "第5條第1項：有疏漏之虞者，應採取維護及防範措施，其疏漏至作業環境之污染物或廢（污）水應收集處理，並記錄疏漏日期、時間、原因、水量及收集處理情形，保存三年。第2條第1款並將維護防範措施及緊急應變措施列為水污染防治措施項目之一。",
 "What must be done when there is a risk of leakage, and how long are records kept?",
 ["Take maintenance and preventive measures, collect and treat the spilled pollutants, and keep records for three years","Take maintenance and preventive measures, discharge the spilled pollutants directly, and keep records for one year","Suspend operations and close down, contract out removal of the pollutants, and keep records for five years","Take maintenance and preventive measures, dilute the spilled pollutants, and keep records for ten years"],
 "Article 5 paragraph 1."),

(W,"第5條",3,"水措-緊急應變",
 "事業疏漏污染物致污染水體、土壤者，應於多久內通知主管機關？應變後應於多久內提報處理報告？",
 ["應立即採取緊急應變措施，於事件發生後三小時內通知直轄市、縣（市）主管機關，應變後十日內提報紀錄及報告","應立即採取緊急應變措施，於事件發生後二十四小時內通知直轄市、縣（市）主管機關，應變後三日內提報報告","應先行完成改善措施，於事件發生後七日內通知直轄市、縣（市）主管機關，應變後三十日內提報紀錄及報告","應立即採取緊急應變措施，於事件發生後一小時內通知中央主管機關，應變後六個月內提報紀錄及處理報告"],"a",
 "第5條第2項：致污染水體、土壤者，應立即採取緊急應變措施，於事件發生後三小時內通知直轄市、縣（市）主管機關，應變後十日內提報緊急應變紀錄及處理報告報備查，並保存三年。第3項規定報告應載明應變內容與排除清理方法、參與人員及任務、水體土壤監測計畫等。",
 "Within what time must contamination be notified, and when is the report submitted?",
 ["Respond at once, notify the municipal or county authority within 3 hours, and report within 10 days after response","Respond at once, notify the municipal or county authority within 24 hours, and report within 3 days after response","Complete remediation first, notify the municipal or county authority within 7 days, and report within 30 days","Respond at once, notify the central competent authority within 1 hour, and report within 6 months after response"],
 "Article 5 paragraphs 2 and 3."),

(W,"第6條",1,"水措-天然災害",
 "天然災害或緊急事故發生時，事業或污水下水道系統應如何處理廢水？",
 ["應依主管機關之命令處理廢（污）水","應依目的事業主管機關之命令停止營運","應依自訂應變計畫逕行排放廢（污）水","應依保險公司評估結果決定處理方式"],"a",
 "第6條：天然災害或緊急事故發生時，事業或污水下水道系統應依主管機關之命令處理廢（污）水。第47條另就自來水廠於豪雨特報或天然災害致原水濁度過高時，訂有得採緊急應變措施直接排放之特別規定。",
 "During a natural disaster or emergency, how must wastewater be handled?",
 ["In accordance with the competent authority's order","In accordance with the industry authority's shutdown order","By direct discharge under a self-drafted response plan","In accordance with the insurer's assessment result"],
 "Article 6."),

(W,"第7條",2,"水措-雨污分流",
 "事業所產生之廢水於作業環境內收集時，有何限制？既設事業技術上難以達成時如何處理？",
 ["應以溝渠、管線或容器收集，不得與雨水合流收集，但逕流廢水除外；既設者得提出證明並設防止直接排放設施，經主管機關同意","應以溝渠、管線或容器收集，一律不得與雨水合流收集且無例外；既設者得提出證明並設防止直接排放設施，逕行合流收集","應以溝渠、管線或容器收集，得與雨水合流收集，但作業廢水除外；既設者應提出證明並設防止直接排放設施，報請備查","應以密閉容器收集，不得與雨水合流收集，但未接觸冷卻水除外；既設者得提出證明並設防止直接排放設施，免經同意"],"a",
 "第7條第1項：所產生之廢（污）水應於作業環境內以溝渠、管線或容器收集，不得與雨水合流收集，但逕流廢水不在此限。第2項：既設者於工程技術上難以達成，得提出證明並有防止合流後廢水直接排放之設施，經主管機關同意後始得合流收集。",
 "How must wastewater be collected on site, and what applies to existing facilities?",
 ["By channel, pipe or container, not combined with rainwater except runoff wastewater; existing ones need authority consent","By channel, pipe or container, never combined with rainwater with no exception; existing ones may combine on their own","By channel, pipe or container, may be combined with rainwater except process wastewater; existing ones just file a record","By closed container, not combined with rainwater except non-contact cooling water; existing ones need no consent at all"],
 "Article 7."),

(W,"第8條",2,"水措-逕流廢水",
 "事業貯存或堆置下列何種物質，其逕流廢水含該物質成分時應收集處理？",
 ["廢水處理產生之污泥、煤渣煤灰飛灰爐石底渣、經雨水沖刷會溶出有害健康物質之原料、有害事業廢棄物等","一般辦公用紙類文具、包裝紙箱棧板、經雨水沖刷不會溶出有害健康物質之成品、一般事業廢棄物等","員工宿舍生活垃圾、廚餘回收桶、經雨水沖刷會揮發之揮發性有機物、資源回收之玻璃與鋁罐容器等","綠美化景觀植栽土壤、堆肥腐植質、經雨水沖刷會產生濁度之砂石、營建剩餘土石方及廢棄土方等"],"a",
 "第8條：貯存或堆置廢（污）水處理產生之污泥，煤渣、煤灰、飛灰、爐石、底渣，經雨水沖刷後會溶出或產生本法公告有害健康物質之原料物料下腳料產品或副產品，有害事業廢棄物，以及廢照明光源、廢乾電池、農藥廢容器、廢鉛蓄電池、廢潤滑油、廢機動車輛等物質者，應收集處理其逕流廢水。",
 "Storing which materials requires the resulting runoff wastewater to be collected and treated?",
 ["Wastewater treatment sludge, coal cinder, fly ash, slag, bottom ash, raw materials leaching hazardous substances, hazardous waste","Office paper and stationery, cartons and pallets, finished goods not leaching hazardous substances, general industrial waste","Dormitory household refuse, kitchen waste bins, volatile organics released by rain, recycled glass and aluminium containers","Landscaping planting soil, compost humus, gravel producing turbidity when washed, construction surplus soil and rock"],
 "Article 8 subparagraphs 1 to 5."),

(W,"第9條",3,"水措-沉砂池",
 "採礦業、營建工地等應設置之沉砂池，其總設計容量及液面高度規定為何？",
 ["總設計容量應為工地或作業場所總面積乘以○．○二五公尺以上，非下雨期間最高液面距池頂應大於池深二分之一","總設計容量應為工地或作業場所總面積乘以○．二五公尺以上，非下雨期間最高液面距池頂應大於池深三分之一","總設計容量應為工地或作業場所總面積乘以○．○○五公尺以上，非下雨期間最高液面距池頂應大於池深四分之一","總設計容量應為工地或作業場所總面積乘以○．一二五公尺以上，非下雨期間最高液面距池頂應大於池深五分之四"],"a",
 "第9條第3項：沉砂池總設計容量應為工地或作業場所範圍總面積乘以○．○二五公尺以上；非下雨期間最高液面距池頂高度應大於池深之二分之一；並應採不透水材質。第6項：雨量大於沉砂池總設計容量時，超過部分之逕流廢水量得以繞流排放。",
 "What are the sedimentation basin's design capacity and liquid level requirements?",
 ["Total design capacity is site area times at least 0.025 m; in dry periods the freeboard exceeds one half of basin depth","Total design capacity is site area times at least 0.25 m; in dry periods the freeboard exceeds one third of basin depth","Total design capacity is site area times at least 0.005 m; in dry periods the freeboard exceeds one quarter of basin depth","Total design capacity is site area times at least 0.125 m; in dry periods the freeboard exceeds four fifths of basin depth"],
 "Article 9 paragraph 3."),

(W,"第9條",2,"水措-遮雨設施",
 "採礦業、土石採取業、水泥業及營建工地就開挖面或堆置場所應如何辦理？相關維護紀錄保存多久？",
 ["應舖設足以防止雨水進入之遮雨、擋雨及導雨設施，並定期維護清理淤砂及記錄，紀錄保存三年以備查閱","應舖設足以防止雨水進入之遮雨、擋雨及導雨設施，並於每次降雨後全部拆除重設及記錄，紀錄保存一年","應舖設足以加速雨水滲透之透水、導滲及集滲設施，並定期維護清理淤砂及記錄，紀錄保存三年以備查閱","應舖設足以防止雨水進入之遮雨、擋雨及導雨設施，並委由公會統一維護清理及記錄，紀錄保存十年備查"],"a",
 "第9條第1項：應於開挖面或堆置場所舖設足以防止雨水進入之遮雨、擋雨及導雨設施，但設置有困難並經主管機關同意者不在此限。第4項：擋雨、遮雨、導雨設施及沉砂池應定期維護、清理淤砂並記錄清理維護時間及方法，紀錄保存三年。第7項：辦公場所、員工宿舍之生活污水應妥善收集處理。",
 "What must mining sites and construction sites install, and how long are records kept?",
 ["Rain shielding, blocking and diversion facilities preventing rain ingress, maintained and recorded, records kept three years","Rain shielding, blocking and diversion facilities fully dismantled and rebuilt after each rainfall, records kept one year","Permeable, infiltration and seepage collection facilities speeding rain infiltration, maintained, records kept three years","Rain shielding, blocking and diversion facilities maintained collectively by the trade association, records kept ten years"],
 "Article 9 paragraphs 1 and 4."),

(W,"第10條",2,"水措-削減計畫",
 "營建工地之逕流廢水污染削減計畫應於何時、向何機關辦理？計畫應記載哪些事項？",
 ["應於施工前報請直轄市、縣（市）主管機關核准並據以實施；應記載基本資料、污染削減措施及工程圖說、目的事業主管機關證明文件","應於完工後報請直轄市、縣（市）主管機關備查並據以實施；應記載基本資料、污染削減措施及工程圖說、目的事業主管機關證明文件","應於施工前報請中央主管機關核准並據以實施；應記載基本資料、放流水標準檢測報告、環境影響評估審查結論及水權狀影本","應於開工後三十日內報請下水道管理機關核准並實施；應記載基本資料、污染削減措施及工程圖說、建築師簽證之結構安全證明"],"a",
 "第10條第1項：營建工地應於施工前檢具逕流廢水污染削減計畫，報請直轄市、縣（市）主管機關核准並據以實施。第2項：削減計畫應記載基本資料、第9條規定之污染削減措施及其工程圖說、目的事業主管機關核發之證明文件影本。第4項：應於中央主管機關指定之日起採網路傳輸方式辦理。",
 "When and to whom is the runoff reduction plan submitted, and what must it contain?",
 ["Before construction to the municipal or county authority for approval; basic data, reduction measures with drawings, agency certificate","After completion to the municipal or county authority for the record; basic data, reduction measures with drawings, agency certificate","Before construction to the central competent authority for approval; basic data, effluent test report, EIA conclusion, water rights copy","Within 30 days after start to the sewerage authority for approval; basic data, reduction measures with drawings, architect's safety certificate"],
 "Article 10 paragraphs 1, 2 and 4."),

(W,"第10條",3,"水措-計畫變更",
 "營建工地削減計畫記載事項變更時，應於何時辦理變更？",
 ["變更基本資料或證明文件應自事實發生翌日起三十日內辦理，須經目的事業主管機關核准者自核准後三十日內；變更削減措施應於變更前辦理","變更基本資料或證明文件應自事實發生翌日起七日內辦理，須經目的事業主管機關核准者自核准後七日內；變更削減措施應於變更後辦理","變更基本資料或證明文件應自事實發生翌日起九十日內辦理，須經目的事業主管機關核准者自核准後九十日內；變更削減措施免辦理","變更基本資料或證明文件應於變更前辦理，須經目的事業主管機關核准者自核准後六個月內；變更削減措施應自事實發生後一年內辦理"],"a",
 "第10條第3項：變更基本資料或目的事業主管機關證明文件者，應自事實發生之翌日起三十日內辦理，須經目的事業主管機關核准者自核准後三十日內為之；變更污染削減措施及工程圖說者，應於變更前辦理；經主管機關查核發現內容不足以維護水體水質而有污染之虞經限期改善者，應於改善期限內辦理。",
 "When must a construction site amend its runoff reduction plan?",
 ["Basic data or certificates within 30 days of the event, or 30 days after agency approval; measures must be amended beforehand","Basic data or certificates within 7 days of the event, or 7 days after agency approval; measures may be amended afterwards","Basic data or certificates within 90 days of the event, or 90 days after agency approval; measures need no amendment at all","Basic data or certificates before the change, or 6 months after agency approval; measures within one year after the event"],
 "Article 10 paragraph 3."),

(W,"第11條",3,"水措-削減措施",
 "非屬第九條及第十條之事業應採取削減措施，其逕流廢水收集設施之可收集量於降雨停止後多久應達許可核准量？",
 ["應依污染特性採取削減措施，其收集設施之可收集量於降雨停止五日後應達許可核准之應收集處理量","應依污染特性採取削減措施，其收集設施之可收集量於降雨停止三十日後應達許可核准之應收集處理量","應依業別統一採取削減措施，其收集設施之可收集量於降雨停止十二小時後應達許可核准之收集處理量","應依污染特性採取削減措施，其收集設施之可收集量於降雨開始五日後應達許可核准之應收集處理量"],"a",
 "第11條第1項：非屬第9條及第10條之事業及污水下水道系統應依其污染特性採取逕流廢水污染削減措施。第3項：應收集處理逕流廢水量依個案許可審查核准，雨量大於應收集處理量時始得繞流排放。第4項：收集設施之可收集量於降雨停止五日後，應達許可核准之應收集處理量。",
 "After rainfall stops, by when must the runoff collection capacity reach the permitted volume?",
 ["Measures follow pollution characteristics; capacity must reach the permitted volume five days after rainfall stops","Measures follow pollution characteristics; capacity must reach the permitted volume thirty days after rainfall stops","Measures are uniform by industry; capacity must reach the permitted volume twelve hours after rainfall stops","Measures follow pollution characteristics; capacity must reach the permitted volume five days after rainfall starts"],
 "Article 11 paragraphs 1, 3 and 4."),

(W,"第12條",2,"水措-計測設施",
 "哪些情形應於廢水處理設施前設置進流水獨立專用累計型水量計測設施？共同設置處理設施者其輸送方式為何？",
 ["廢水回收使用、稀釋、受託處理或經主管機關指定者；共同設置者其廢水輸送應以管線或溝渠為之","僅廢水回收使用及貯留者；共同設置者其廢水輸送應以桶裝、槽車等非管線方式為之較為妥適","廢水納管、土壤處理或海放者；共同設置者其廢水輸送得以任何方式為之，無須報經主管機關同意","廢水回收使用、稀釋、受託處理或經主管機關指定者；共同設置者其廢水輸送應以槽車或桶裝為之"],"a",
 "第12條第1項：廢（污）水回收使用、稀釋、受託處理或經主管機關指定者，應於廢（污）水處理設施前設置進流水獨立專用累計型水量計測設施。第2項：共同設置廢（污）水（前）處理設施處理廢水者，其輸送方式應以管線或溝渠為之。第2條第2款並定義共同設置為二以上事業合資共同興建並使用。",
 "Which cases require an inflow cumulative flow meter, and how is jointly treated wastewater conveyed?",
 ["Recycling, dilution, entrusted treatment or cases designated by the authority; conveyance by pipe or channel","Only recycling and storage of wastewater; conveyance by drum or tank truck rather than by pipe or channel","Sewer connection, soil treatment or sea outfall; conveyance by any means without needing authority consent","Recycling, dilution, entrusted treatment or cases designated by the authority; conveyance by tank truck or drum"],
 "Article 12."),

(W,"第13條",1,"水措-備用電力",
 "事業產生廢水之生產設施具有備用電力者，其廢水處理設施應如何配置？",
 ["其廢（污）水（前）處理設施亦應具備足供運轉之備用電力","其廢（污）水（前）處理設施得於停電期間暫停運轉並排放","其廢（污）水（前）處理設施應改以人工方式加藥維持運轉","其廢（污）水（前）處理設施應於停電時通報並繞流至水體"],"a",
 "第13條：事業或污水下水道系統產生廢（污）水之生產設施具有備用電力者，其廢（污）水（前）處理設施亦應具備足供運轉之備用電力。第18條並規定處理設施故障超過二十四小時，應將無法處理之廢水妥善貯存，不得排放。",
 "If production facilities have backup power, what applies to treatment facilities?",
 ["The wastewater treatment facilities must also have backup power sufficient to operate","The wastewater treatment facilities may suspend operation and discharge during outages","The wastewater treatment facilities must switch to manual chemical dosing to keep running","The wastewater treatment facilities must report and bypass to receiving water on outage"],
 "Article 13."),

(W,"第14條",2,"水措-保養紀錄",
 "廢水處理設施產生之污泥應如何處理？處理設施之保養維修紀錄應保存多久？",
 ["污泥應採行減量措施；處理設施應定期實施保養及適時維修並作成紀錄，保存五年以備查閱","污泥應採行減量措施；處理設施應定期實施保養及適時維修並作成紀錄，保存一年以備查閱","污泥應委外全量清運；處理設施應於故障時實施保養及維修並作成紀錄，保存三年以備查閱","污泥應回流至製程；處理設施應定期實施保養及適時維修並作成紀錄，保存十年以備主管機關查閱"],"a",
 "第14條第1項：廢（污）水（前）處理設施產生之污泥，應採行減量措施。第2項：廢（污）水（前）處理設施應定期實施保養及適時維修，並作成紀錄，保存五年以備查閱。第16條第3項亦規定用電度數、操作參數等紀錄及單據影本應保存五年。",
 "How must treatment sludge be handled, and how long are maintenance records kept?",
 ["Sludge must be subject to reduction measures; facilities regularly maintained with records kept for five years","Sludge must be subject to reduction measures; facilities regularly maintained with records kept for one year","Sludge must be fully contracted out; facilities maintained only on breakdown with records kept for three years","Sludge must be returned to the process; facilities regularly maintained with records kept for ten years"],
 "Article 14."),

(W,"第15條",3,"水措-限期改善",
 "廢水處理設施未維持正常操作經命限期改善者，於改善期間應如何辦理？拆除既有設施應辦何種程序？",
 ["應維持既有設施正常操作並採減少或停止生產等措施，不得超過據以通知之操作參數，違反者按次處罰；拆除前應辦變更登記","應停止既有設施操作並採加倍生產以稀釋污染等措施，不得超過據以通知之操作參數，違反者處以停工；拆除前應辦變更登記","應維持既有設施正常操作並採減少或停止生產等措施，得暫時超過據以通知之操作參數，免予處罰；拆除後三十日內補辦登記","應委託代操作者接手操作並採增加加藥量等措施，不得超過據以通知之操作參數，違反者按日處罰；拆除免辦任何登記程序"],"a",
 "第15條第1項：於限期改善期間內應維持既有設施正常操作，採行減少、停止生產或服務作業量，或改善處理設施等措施，且不得超過主管機關據以通知限期改善之操作參數，其他操作參數亦應符合正常範圍，違反者按次處罰。第2項：改善措施必須拆除既有設施方能施工者，應向核發機關辦理變更登記後始得為之。",
 "During an ordered improvement period, what applies, and what if existing units must be dismantled?",
 ["Keep existing units operating normally, cut or halt output, not exceed the notified parameters; register the change before dismantling","Halt existing units, double output to dilute pollution, not exceed the notified parameters; register the change before dismantling","Keep existing units operating normally, cut or halt output, temporarily exceed the notified parameters; register within 30 days after","Entrust a contract operator, increase chemical dosing, not exceed the notified parameters; dismantling needs no registration at all"],
 "Article 15."),

(W,"第16條",2,"水措-操作紀錄",
 "廢水處理設施之電度表及操作參數量測設施，非屬連續自動紀錄者應如何記錄？相關紀錄保存多久？",
 ["應每日記錄累計用電度數及操作參數值一次；藥品量與污泥產生貯存清運量按次記錄每月統計，紀錄保存五年","應每月記錄累計用電度數及操作參數值一次；藥品量與污泥產生貯存清運量按年記錄每年統計，紀錄保存五年","應每日記錄累計用電度數及操作參數值三次；藥品量與污泥產生貯存清運量按次記錄每週統計，紀錄保存一年","應每季記錄累計用電度數及操作參數值一次；藥品量與污泥產生貯存清運量按次記錄每月統計，紀錄保存三年"],"a",
 "第16條第1項：屬連續自動紀錄者應依計測、量測設施之設計規格及頻率記錄；非屬連續自動紀錄者，應每日記錄其累計用電度數及操作參數值一次；藥品量及污泥之產生、貯存、清運量應按次記錄，每月統計。第3項：前二項紀錄及單據或發票影本應保存五年以備查閱。",
 "For non-continuous recording, how often are power and parameters logged, and records kept?",
 ["Log cumulative power use and parameters once daily; chemicals and sludge logged per event, monthly totals; records five years","Log cumulative power use and parameters once monthly; chemicals and sludge logged yearly, annual totals; records five years","Log cumulative power use and parameters three times daily; chemicals and sludge logged per event, weekly totals; records one year","Log cumulative power use and parameters once quarterly; chemicals and sludge logged per event, monthly totals; records three years"],
 "Article 16."),

(W,"第17條",3,"水措-電度表",
 "廢水處理設施之獨立專用電度表應符合哪些規定？維護更換後應於多久內報備？",
 ["規格符合度量衡法規並能量測全部用電量、應有透明視窗、由主管機關或電力業者鉛封、進出電路標明來源去處；更換後一週內報備","規格符合度量衡法規並能量測全部用電量、應有透明視窗、由事業自行加封條、進出電路標明來源去處；更換後六個月內報備","規格符合電業法規並能量測部分用電量、應有防窺遮罩、由主管機關或電力業者鉛封、進出電路免標明；更換後一年內報備","規格符合度量衡法規並能量測全部用電量、應有透明視窗、由檢驗測定機構鉛封、進出電路標明來源去處；更換後即日報備"],"a",
 "第17條第1項：電度表規格應符合度量衡法規並能量測處理設施之全部用電量、應有透明視窗、應由主管機關或電力業者鉛封經主管機關確認不得任意破壞、進出電路應標明來源及去處。第2項：維護更換前應向主管機關報備始得拆封，期間用電度數仍應記錄，維護更換後一週內應向主管機關報備。",
 "What must the dedicated electricity meter satisfy, and when is replacement reported?",
 ["Metrology-compliant, measures all power use, transparent window, sealed by the authority or utility, circuits labelled; report within a week","Metrology-compliant, measures all power use, transparent window, self-sealed by the enterprise, circuits labelled; report within six months","Electricity-act compliant, measures part of power use, privacy shield, sealed by the authority or utility, no labels; report within a year","Metrology-compliant, measures all power use, transparent window, sealed by a testing organization, circuits labelled; report the same day"],
 "Article 17 paragraphs 1 and 2."),

(W,"第18條",3,"水措-設施故障",
 "廢水處理設施發生故障超過多久應妥善貯存不得排放？修復時間超過多久應暫時停止產生廢水？",
 ["故障超過二十四小時應將無法處理之廢水妥善貯存不得排放；修復時間超過三十日者應暫時停止產生廢（污）水","故障超過七十二小時應將無法處理之廢水妥善貯存不得排放；修復時間超過九十日者應暫時停止產生廢（污）水","故障超過二十四小時應將無法處理之廢水稀釋後排放於水體；修復時間超過三十日者應加倍收費並繼續生產作業","故障超過一週應將無法處理之廢水妥善貯存不得排放；修復時間超過六個月者應暫時停止產生廢（污）水並歇業"],"a",
 "第18條第1項：處理設施發生故障超過二十四小時，應將無法處理之廢（污）水妥善貯存，不得排放；修復時間超過三十日者，應暫時停止產生廢（污）水。第2項：應記錄故障時間、設施名稱、發生原因、廢水產生量及收集情形、修復方法及進度，保存三年以備查閱。",
 "After how long a breakdown must wastewater be stored, and when must generation stop?",
 ["Breakdown over 24 hours: store untreated wastewater and do not discharge; repair over 30 days: temporarily stop generating","Breakdown over 72 hours: store untreated wastewater and do not discharge; repair over 90 days: temporarily stop generating","Breakdown over 24 hours: dilute untreated wastewater and discharge to water; repair over 30 days: pay double and keep operating","Breakdown over one week: store untreated wastewater and do not discharge; repair over 6 months: stop generating and close down"],
 "Article 18."),

(W,"第19條",3,"水措-代操作",
 "代操作者於代操作期間致該事業最近一年內有何情形時，事業不得委託其代為操作？",
 ["經查獲繞流排放、大量排放污染物嚴重影響附近水體水質、排放含有害健康物質有危害公眾健康之虞、受裁處停工（業）","經查獲逾期申報、偶發排放污染物輕微影響附近水體水質、排放含一般有機物無危害公眾健康之虞、受裁處罰鍰處分","經查獲未設告示牌、未依規定校正水量計測設施、未於期限內提報操作紀錄、未參加主管機關舉辦之教育訓練課程","經查獲繞流排放、負責人變更未辦理登記、代操作人員請假未通報、代操作契約金額低於同業之平均行情價格"],"a",
 "第19條第2項：代操作者代其他事業操作期間，致該事業最近一年內有經查獲繞流排放、大量排放污染物經認定嚴重影響附近水體水質、排放含本法公告有害健康物質經認定有危害公眾健康之虞、受主管機關裁處停工（業）等情形之一者，不得委託其代為操作。第1項並定明得委託代操作者代為操作處理設施。",
 "Which situations in the past year bar entrusting a contract operator?",
 ["Bypass discharge found, mass discharge seriously affecting nearby water, hazardous substances risking public health, ordered shutdown","Late reporting found, occasional discharge slightly affecting nearby water, ordinary organics with no public health risk, a fine imposed","No signboard found, flow meters not calibrated as required, operating records filed late, failure to attend official training courses","Bypass discharge found, unregistered change of responsible person, unreported operator leave, contract price below the market average"],
 "Article 19 paragraph 2."),

(W,"第19條",2,"水措-代操作資格",
 "應設置廢水處理專責單位之事業，其委託之代操作人員應具何種資格？現場紀錄應保存多久？",
 ["應具甲級廢水處理專責人員資格；現場應置放到達離開時間及操作維護情形紀錄並簽名確認，保存三年","應具乙級廢水處理專責人員資格；現場應置放到達離開時間及操作維護情形紀錄並簽名確認，保存三年","應具環境工程技師執業資格；現場應置放到達離開時間及操作維護情形紀錄並簽名確認，保存一年","應具甲級廢水處理專責人員資格；現場僅需置放代操作契約影本並由負責人簽名確認，保存十年備查"],"a",
 "第19條第3項：應置廢水處理專責人員者，其委託之代操作人員應具同一等級廢水處理專責人員資格；應設廢（污）水處理專責單位者，其委託之代操作人員應具甲級廢水處理專責人員資格。第4項：現場應置放代操作人員到達、離開之時間及操作維護情形之紀錄並簽名確認，紀錄保存三年以備查閱。",
 "What qualification is required for contract operators, and how long are site records kept?",
 ["Class A wastewater treatment personnel; site records of arrival, departure and maintenance signed, kept three years","Class B wastewater treatment personnel; site records of arrival, departure and maintenance signed, kept three years","Licensed environmental engineer; site records of arrival, departure and maintenance signed, kept for one year","Class A wastewater treatment personnel; only a copy of the contract signed by the head, kept for ten years"],
 "Article 19 paragraphs 3 and 4."),

(W,"第20條",2,"水措-納管",
 "污水下水道系統區域內之事業未將廢水納管者，應完成哪些程序始得排放於地面水體？",
 ["應經下水道管理機關（構）同意，並取得廢（污）水排放地面水體許可證或簡易排放許可文件後始得排放","應經下水道管理機關（構）同意即可排放，無須另行取得廢（污）水排放地面水體許可證或許可文件","應取得廢（污）水排放地面水體許可證或簡易排放許可文件即可，無須經下水道管理機關（構）同意","應經目的事業主管機關同意，並取得工廠登記證及水權狀等文件影本後，始得排放廢水於地面水體"],"a",
 "第20條：污水下水道系統區域內之事業未納管者，應經下水道管理機關（構）同意，並於取得廢（污）水排放地面水體許可證或簡易排放許可文件後，始得排放於地面水體。第21條並規定此等事業之廢水不得排放於該排水區域內之專用雨水下水道。",
 "What must a non-connected enterprise complete before discharging to surface water?",
 ["Consent of the sewerage authority plus a surface water discharge permit or simplified discharge document","Consent of the sewerage authority alone, with no surface water discharge permit or document needed","A surface water discharge permit or simplified discharge document alone, with no sewerage consent","Consent of the industry competent authority plus copies of a factory registration and water rights"],
 "Article 20."),

(W,"第21條",1,"水措-雨水下水道",
 "前條事業所產生之廢水得否排放於該排水區域內之專用雨水下水道？",
 ["原則不得排放，但經下水道管理機關（構）與主管機關同意者，不在此限","原則不得排放，且無任何例外情形，一律禁止排入專用雨水下水道","原則得排放，但經下水道管理機關（構）反對者，即不得排入其中","原則得排放，惟應於排放前二十四小時通知下水道管理機關（構）"],"a",
 "第21條：第20條之事業所產生之廢（污）水，不得排放於該排水區域內之專用雨水下水道，但經下水道管理機關（構）與主管機關同意者，不在此限。此與第7條雨污分流收集之要求相互呼應。",
 "May such wastewater be discharged into the dedicated stormwater sewer?",
 ["In principle no, unless both the sewerage authority and the competent authority consent","In principle no, with no exception whatsoever, discharge is prohibited in all cases","In principle yes, unless the sewerage authority raises an objection to the discharge","In principle yes, provided the sewerage authority is notified 24 hours in advance"],
 "Article 21."),

(W,"第22條",3,"水措-納管改善",
 "納管事業未符下水道水質標準經通知限期改善，且無法於期限內完成改善並遭拒絕納入者，應如何辦理？",
 ["採納管以外水措應向核發機關申請許可證（文件）；於未取得核准之許可證（文件）前，應停止產生廢（污）水","採納管以外水措應向下水道管理機關申請許可證；於未取得核准之許可證（文件）前，仍得繼續產生廢（污）水","採納管以外水措應向目的事業主管機關報請備查；於未取得核准之許可證（文件）前，得先行排放於地面水體","採納管以外水措應向核發機關申請許可證（文件）；於未取得核准之許可證（文件）前，得將廢水稀釋後排放"],"a",
 "第22條第1項：納管事業經通知限期改善時，如採取納管以外之水措，應向核發機關提出許可證（文件）之申請。第2項：無法於規定期間內完成改善，經下水道管理機關（構）依下水道法拒絕納入或通知停止使用者，於未取得核發機關核准之許可證（文件）前，應停止產生廢（污）水。第3項：下水道管理機關（構）通知限期改善及拒絕納入時，應同時通知主管機關。",
 "If an unconnected user cannot improve in time and connection is refused, what applies?",
 ["Apply to the issuing authority for a permit; until an approved permit is obtained, wastewater generation must stop","Apply to the sewerage authority for a permit; until an approved permit is obtained, generation may still continue","File with the industry competent authority; until an approved permit is obtained, discharge to surface water is allowed","Apply to the issuing authority for a permit; until an approved permit is obtained, diluted discharge is permitted"],
 "Article 22."),

(W,"第23條",2,"水措-土壤處理",
 "事業採土壤處理者，應併同採行何種措施？何種情形不在此限？",
 ["應併同採行其他經主管機關核准之水措，作為暫停土壤處理時之替代措施；已依廢清法得以槽車清除者除外","應併同採行其他經主管機關核准之水措，作為暫停土壤處理時之替代措施；經技師簽證認為無必要者除外","應併同設置海洋放流管線，作為暫停土壤處理時之替代措施；已依廢清法得以槽車清除廢水者不在此限","應併同投保環境責任保險，作為暫停土壤處理時之替代措施；已依廢清法得以槽車清除廢水者不在此限"],"a",
 "第23條：採土壤處理者，應併同採行其他經主管機關核准之水措，作為暫停土壤處理時之替代措施；但已依廢棄物清理法規定辦理，得以桶裝、槽車或其他非管線、溝渠清除未符合放流水標準之廢水至作業環境外者，不在此限。第27條並列有應暫停排放廢水於土壤之四種情形。",
 "What must accompany soil treatment, and what is excepted?",
 ["Another approved water measure as a substitute when soil treatment is suspended; unless removal by tank truck under the Waste Act","Another approved water measure as a substitute when soil treatment is suspended; unless an engineer certifies it unnecessary","A sea outfall pipeline as a substitute when soil treatment is suspended; unless removal by tank truck under the Waste Act","Environmental liability insurance as a substitute when soil treatment is suspended; unless removal by tank truck under the Waste Act"],
 "Article 23."),

(W,"第24條",1,"水措-土壤處理",
 "事業產生之廢水於採行土壤處理前，應處理至何種程度？",
 ["應經前處理至符合土壤處理標準，始得採行土壤處理","應經前處理至符合放流水標準，始得採行土壤處理","應經前處理至符合飲用水水質標準，始得土壤處理","應經前處理至符合地下水污染管制標準始得處理"],"a",
 "第24條：事業或污水下水道系統產生之廢（污）水，應經前處理至符合土壤處理標準，始得採行土壤處理。第27條另規定土壤飽和萃取液導電度、土壤及地下水監測結果達標準限值時，應暫停排放廢水於土壤。",
 "To what level must wastewater be pre-treated before soil treatment?",
 ["Pre-treated to meet the soil treatment standard before soil treatment","Pre-treated to meet the effluent standard before soil treatment applies","Pre-treated to meet the drinking water quality standard before treatment","Pre-treated to meet the groundwater pollution control standard first"],
 "Article 24."),

(W,"第25條",2,"水措-適用除外",
 "下列何種情形之事業或污水下水道系統，不適用土壤處理章之規定？",
 ["取得畜牧糞尿水施灌農作個案再利用許可、經核准沼液沼渣作為農地肥分使用、設置不透水材質設施隔絕廢水與土壤接觸等","取得工廠登記證及水權狀、經核准設置海洋放流管線排放、設置透水材質設施加速廢水與土壤接觸滲透等情形之一者","取得環境影響評估審查結論、經核准繞流排放於地面水體、設置不透水材質設施隔絕廢水與土壤接觸等情形之一者","取得畜牧場登記證書及飼養登記證、經核准委託代操作處理設施、設置沉砂池收集初期降雨廢水等情形之一者"],"a",
 "第25條：依農業事業廢棄物再利用管理辦法取得畜牧糞尿水施灌農作個案再利用許可、依本辦法取得農業主管機關核准畜牧業沼液沼渣作為農地肥分使用計畫、經核准輸送符合放流水標準之畜牧廢水作為植物澆灌、經核准輸送符合放流水標準之廢水作為花木澆灌、設置不透水材質設施隔絕廢水與土壤接觸者，不適用土壤處理章規定。",
 "Which circumstances exempt an enterprise from the soil treatment chapter?",
 ["Individual reuse permit for livestock manure irrigation, approved biogas slurry land application, impermeable isolation facilities","Factory registration and water rights, approved sea outfall discharge, permeable facilities speeding infiltration into soil","EIA review conclusion obtained, approved bypass discharge to surface water, impermeable facilities isolating wastewater","Livestock farm registration certificates, approved contract operation of facilities, sedimentation basins for first flush"],
 "Article 25."),

(W,"第26條",1,"水措-攔水渠",
 "採土壤處理者，應於何處設置攔水渠？何種情形不在此限？",
 ["應於土壤處理適用土地區段下坡處設置攔水渠，妥善收集處理溢流之廢水；土壤處理後無溢流水者除外","應於土壤處理適用土地區段上坡處設置攔水渠，妥善收集處理溢流之廢水；土壤處理後無溢流水者除外","應於土壤處理適用土地區段四周設置攔水渠，妥善收集處理入滲之雨水；土壤處理面積未達一公頃者除外","應於土壤處理適用土地區段下坡處設置抽水井，妥善抽取處理入滲之廢水；土壤監測合格者不在此限內"],"a",
 "第26條：事業或污水下水道系統應於土壤處理之適用土地區段下坡處設置攔水渠，妥善收集處理溢流之廢（污）水；但土壤處理後無溢流水者，不在此限。第28條並要求於排放廢水於土壤前設置採樣口及告示牌。",
 "Where must an interception channel be built for soil treatment, and what is excepted?",
 ["Downslope of the soil treatment land, collecting and treating overflow wastewater; unless there is no overflow after treatment","Upslope of the soil treatment land, collecting and treating overflow wastewater; unless there is no overflow after treatment","Around the soil treatment land, collecting and treating infiltrating rainwater; unless the area is under one hectare","Downslope of the soil treatment land, a pumping well drawing infiltrated wastewater; unless soil monitoring passes"],
 "Article 26."),

(W,"第27條",3,"水措-暫停排放",
 "採土壤處理者於哪些情形應暫停排放廢水於土壤？",
 ["中央氣象署發布大雨豪雨特報日起至解除日後三日、土壤飽和萃取液導電度達標準、土壤或地下水監測結果達監測標準限值","中央氣象署發布陸上颱風警報日起至解除當日、土壤飽和萃取液酸鹼值達標準、土壤或地下水監測結果達管制標準限值","中央氣象署發布大雨豪雨特報日起至解除日後十日、土壤含水量達百分之三十、土壤或地下水監測結果達整治標準限值","中央氣象署發布高溫資訊日起至解除日後三日、土壤飽和萃取液濁度達標準、土壤或地下水監測結果達背景值之限度"],"a",
 "第27條第1項：應依許可證登記之排放期間排放廢水，但自中央氣象署發布大雨、豪雨特報日起至解除日後三日之期間、土壤飽和萃取液導電度於二十五攝氏度達每公分四毫西門、土壤監測結果達土壤污染監測標準限值、地下水監測結果達地下水污染監測標準限值者，應暫停排放廢（污）水。",
 "When must discharge to soil be suspended?",
 ["From a heavy rain advisory until three days after it is lifted; soil saturation extract conductivity, soil or groundwater at monitoring limits","From a land typhoon warning until the day it is lifted; soil saturation extract pH, soil or groundwater at pollution control limits","From a heavy rain advisory until ten days after it is lifted; soil moisture at 30 percent, soil or groundwater at remediation limits","From a high temperature advisory until three days after; soil saturation extract turbidity, soil or groundwater at background limits"],
 "Article 27 paragraph 1."),

(W,"第27條",3,"水措-導電度",
 "土壤飽和萃取液導電度達何數值時應暫停排放？依該款暫停後應完成何種程序始得繼續排放？",
 ["於二十五攝氏度達每公分四毫西門；應檢具檢測合格報告送直轄市、縣（市）主管機關核准後始得繼續排放","於二十攝氏度達每公分四十毫西門；應檢具檢測合格報告送直轄市、縣（市）主管機關核准後始得繼續排放","於二十五攝氏度達每公分零點四毫西門；應檢具檢測合格報告向直轄市、縣（市）主管機關報備即得排放","於二十五攝氏度達每公分四毫西門；應檢具檢測合格報告送中央主管機關核准並公告後，始得繼續排放廢水"],"a",
 "第27條第1項第2款：土壤飽和萃取液導電度於二十五攝氏度達每公分四毫西門者，應暫停排放廢（污）水。第2項：依第1項第2款至第4款規定暫停排放者，應檢具檢測合格報告送直轄市、縣（市）主管機關核准後，始得繼續排放廢（污）水於土壤。",
 "At what conductivity must discharge stop, and how may it resume?",
 ["4 mS/cm at 25 degrees Celsius; submit a passing test report for municipal or county authority approval before resuming","40 mS/cm at 20 degrees Celsius; submit a passing test report for municipal or county authority approval before resuming","0.4 mS/cm at 25 degrees Celsius; submit a passing test report to the municipal or county authority for the record only","4 mS/cm at 25 degrees Celsius; submit a passing test report for central competent authority approval and publication"],
 "Article 27 paragraphs 1 and 2."),

(W,"第28條",2,"水措-採樣口",
 "採土壤處理者所設之採樣口應符合哪些規定？",
 ["應有可供人員進出之道路、設置獨立專用累計型水量計測設施、設置告示牌並標示座標、可供直接採樣不得設置規避設施","應有可供人員進出之道路、設置獨立專用累計型水量計測設施、設置圍籬並上鎖管制、僅得於事業陪同時始開放採樣","應有可供車輛進出之產業道路、設置流速計及水位計、設置告示牌並標示地號、可供直接採樣不得設置規避之設施","應有可供人員進出之道路、設置獨立專用瞬間型水量計測設施、設置告示牌並標示座標、僅供間接採樣或委託採樣"],"a",
 "第28條第2項：採樣口應有可供主管機關人員進出至採樣口之道路、設置獨立專用累計型水量計測設施量測排放於土壤之水量、設置告示牌並標示座標、可供直接採樣且未經核准不得設置規避妨礙或拒絕主管機關直接採樣之設施。第3項：經查獲繞流排放或經指定之非連續性排放者，其採樣口應設置於主管機關指定之位置。",
 "What must a soil treatment sampling port satisfy?",
 ["Access road for inspectors, dedicated cumulative flow meter, signboard with coordinates, direct sampling with no evasive devices","Access road for inspectors, dedicated cumulative flow meter, locked fencing, sampling opened only when the enterprise attends","Vehicle access road, flow velocity and level gauges, signboard with the land number, direct sampling with no evasive devices","Access road for inspectors, dedicated instantaneous flow meter, signboard with coordinates, indirect or contracted sampling only"],
 "Article 28 paragraphs 2 and 3."),

(W,"第28條",3,"水措-告示牌",
 "採樣口告示牌之規格及設置高度規定為何？",
 ["長度三十二公分以上、寬度十五公分以上，白底黑字，文字一．五公分見方以上；設置高度介於地面上五十公分至二公尺之間","長度十五公分以上、寬度三十二公分以上，黑底白字，文字一．五公分見方以上；設置高度介於地面上五十公分至二公尺之間","長度三十二公分以上、寬度十五公分以上，白底紅字，文字三公分見方以上；設置高度介於地面上一公尺至三公尺之間","長度三公分以上、寬度一．五公分以上，白底黑字，文字十五公分見方以上；設置高度介於地面上二公尺至五公尺之間"],"a",
 "第28條第4項：告示牌應依核准內容記載名稱、管制編號、採樣口編號、座標、最大日排放水量；規格長度應為三十二公分以上、寬度十五公分以上，牌面底色白色、標示文字黑色、字體一．五公分見方以上；應固定於採樣口旁明顯處，設置高度介於地面上五十公分至二公尺之間；材質須堅固耐用、安裝穩固。第55條規定放流口告示牌準用本項。",
 "What are the signboard dimensions and mounting height?",
 ["At least 32 cm long and 15 cm wide, black on white, characters at least 1.5 cm square; mounted 50 cm to 2 m above ground","At least 15 cm long and 32 cm wide, white on black, characters at least 1.5 cm square; mounted 50 cm to 2 m above ground","At least 32 cm long and 15 cm wide, red on white, characters at least 3 cm square; mounted 1 m to 3 m above the ground","At least 3 cm long and 1.5 cm wide, black on white, characters at least 15 cm square; mounted 2 m to 5 m above ground"],
 "Article 28 paragraph 4; Article 55 applies it to outfall signboards."),

(W,"第29條",3,"水措-受託資格",
 "事業申請受託處理變更登記，應符合哪些不良紀錄之限制？",
 ["申請日前一年內未因違反本法第七條受裁處超過二次，且前三年內未經認定排放有害健康物質危害公眾健康、未受裁處停工、未經查獲繞流排放","申請日前三年內未因違反本法第七條受裁處超過二次，且前一年內未經認定排放有害健康物質危害公眾健康、未受裁處停工、未經查獲繞流排放","申請日前一年內未因違反本法第七條受裁處超過五次，且前三年內未經認定排放一般有機物影響水質、未受裁處罰鍰、未經查獲逾期申報","申請日前六個月內未因違反本法第七條受裁處超過二次，且前十年內未經認定排放有害健康物質危害公眾健康、未受裁處停工、未查獲繞流"],"a",
 "第29條：取得之水措計畫核准文件或許可證有餘裕量之登記事項，且申請日前一年內未因違反本法第七條規定受裁處超過二次（納管事業則為前一年內未受下水道管理機關拒絕納入或通知停止使用）、申請日前三年內未經認定排放含有害健康物質危害公眾健康、未因違反本法受裁處停工（業）、未經查獲繞流排放者，得申請並完成受託處理變更登記。",
 "What compliance record is required to register for entrusted treatment?",
 ["No more than two Article 7 penalties in the past year, and in the past three years no health hazard finding, no shutdown, no bypass","No more than two Article 7 penalties in the past three years, and in the past year no health hazard finding, no shutdown, no bypass","No more than five Article 7 penalties in the past year, and in the past three years no organics finding, no fine, no late reporting","No more than two Article 7 penalties in the past six months, and in the past ten years no health hazard finding, no shutdown, no bypass"],
 "Article 29."),

(W,"第30條",2,"水措-受託處理",
 "受託處理廢水之受託者應符合哪些規定？",
 ["以受託處理同業別或同類型廢水為限、每日受託水量不得超過核准每日最大餘裕量、收受後應於二十四小時內處理","以受託處理不同業別或不同類型廢水為限、每日受託水量不得超過核准每日最大餘裕量、收受後應於七日內處理","以受託處理同業別或同類型廢水為限、每日受託水量不得超過核准每日最大排放量、收受後應於七十二小時內處理","以受託處理同業別或同類型廢水為限、每日受託水量得超過核准每日最大餘裕量、收受後應於三十日內完成處理"],"a",
 "第30條：受託者應以受託處理同業別或同類型之廢（污）水為限（經核發機關同意者除外）、每日受託處理之廢水量不得超過核准每日最大餘裕量、收受廢水後應於二十四小時內處理。第29條並就受託處理變更登記訂有不良紀錄之限制。",
 "What rules apply to an entrusted treatment provider?",
 ["Only same or similar industry wastewater; daily volume not over the approved maximum spare capacity; treat within 24 hours","Only different industry or type wastewater; daily volume not over the approved maximum spare capacity; treat within 7 days","Only same or similar industry wastewater; daily volume not over the approved maximum discharge; treat within 72 hours","Only same or similar industry wastewater; daily volume may exceed the approved spare capacity; treat within 30 days"],
 "Article 30."),

(W,"第31條",2,"水措-委託處理",
 "委託他人處理廢水之委託者應設置何種設施？委託者及受託者應於何處設置水量計測設施？",
 ["應設置廢（污）水（前）處理設施或貯留設施貯存廢水；雙方均應於管線或溝渠之進流水、出流水端設置獨立專用累計型水量計測設施","應設置廢（污）水（前）處理設施或貯留設施貯存廢水；僅受託者需於管線或溝渠之進流水端設置獨立專用累計型水量計測設施","應設置沉砂池或調勻設施貯存待運送之廢水；雙方均應於管線或溝渠之進流水、出流水端設置獨立專用瞬間型水量計測設施","應設置緊急應變放流口以備溢流時排放廢水；雙方均應於管線或溝渠之進流水、出流水端設置共用之累計型水量計測設施"],"a",
 "第31條第1項：委託者應設置廢（污）水（前）處理設施或貯留設施，貯存廢（污）水。第2項：委託者及受託者應於管線或溝渠之進流水、出流水端，設置獨立專用累計型水量計測設施。第33條並規定接獲停止委託通知時應收集貯留，貯留超過三十日且未取得其他水措應停止產生廢水。",
 "What facility must the entrusting party install, and where are flow meters required?",
 ["Treatment or storage facilities to store wastewater; both parties install dedicated cumulative meters at pipe inflow and outflow ends","Treatment or storage facilities to store wastewater; only the provider installs a dedicated cumulative meter at the inflow end","Sedimentation or equalization facilities to store wastewater; both parties install dedicated instantaneous meters at both ends","An emergency outfall for overflow discharge; both parties install a shared cumulative meter at the inflow and outflow ends"],
 "Article 31."),

(W,"第32條",3,"水措-受託故障",
 "受託者因處理設施故障無法處理受委託廢水時應如何辦理？無法受託處理期間超過多久應停止受託？",
 ["應告知委託者停止輸送並進行改善；無法受託處理期間超過三十日者，應停止受託處理並向核發機關辦理變更","應告知委託者停止輸送並進行改善；無法受託處理期間超過一百八十日者，應停止受託處理並向核發機關辦理變更","應告知委託者加倍輸送以稀釋污染並改善；無法受託處理期間超過三十日者，得繼續受託處理但應加強紀錄","應告知主管機關並自行停工歇業；無法受託處理期間超過二十四小時者，應停止受託處理並辦理許可證註銷"],"a",
 "第32條第1項：受託者因處理設施故障致無法處理受委託之廢水時，應告知委託者停止輸送並進行改善；無法受託處理廢水期間超過三十日者，應停止受託處理並向核發機關辦理水措計畫核准文件或許可證（文件）變更。第2項：受託者未辦理變更，核發機關得逕行變更許可登記項目。第3項：紀錄應保存三年。",
 "What must a provider do on breakdown, and after how long must it stop accepting wastewater?",
 ["Tell the client to stop conveying and improve; if unable to treat for over 30 days, stop and register the change with the issuer","Tell the client to stop conveying and improve; if unable to treat for over 180 days, stop and register the change with the issuer","Tell the client to double conveyance to dilute and improve; if unable to treat for over 30 days, keep accepting but log more","Notify the authority and shut down; if unable to treat for over 24 hours, stop accepting and cancel the permit entirely"],
 "Article 32."),

(W,"第33條",2,"水措-委託貯留",
 "委託者接獲受託者通知停止委託處理時應如何辦理？貯留超過多久且未取得其他水措應停止產生廢水？",
 ["應收集貯留其廢（污）水；廢水貯留超過三十日且未取得經核發機關核准之其他水措者，應停止產生廢（污）水","應收集貯留其廢（污）水；廢水貯留超過九十日且未取得經核發機關核准之其他水措者，應停止產生廢（污）水","應立即繞流排放其廢（污）水；廢水貯留超過三十日且未取得經核發機關核准之其他水措者，得繼續產生廢水","應收集貯留其廢（污）水；廢水貯留超過二十四小時且未取得目的事業主管機關同意者，應立即歇業並停工"],"a",
 "第33條第1項：委託者接獲受託者通知停止委託處理時，應收集貯留其廢（污）水；廢水貯留超過三十日且未取得經核發機關核准之其他水措，應停止產生廢（污）水；但已依廢棄物清理法辦理得以桶裝、槽車清除未符合放流水標準之廢水至作業環境外者不在此限。第2項：相關紀錄應保存三年。",
 "On notice to stop, what must the entrusting party do and when must generation stop?",
 ["Collect and store its wastewater; if stored over 30 days without another approved water measure, stop generating wastewater","Collect and store its wastewater; if stored over 90 days without another approved water measure, stop generating wastewater","Immediately bypass discharge its wastewater; if stored over 30 days without another approved measure, generation may continue","Collect and store its wastewater; if stored over 24 hours without industry authority consent, close down and stop work at once"],
 "Article 33."),

(W,"第34條",3,"水措-受託限制",
 "受託者於受託處理期間一年內違反本法規定二次以上者，有何限制？",
 ["自第二次違反日起一年內，不得增加受託處理水量及對象","自第二次違反日起三年內，不得增加受託處理水量及對象","自第一次違反日起一年內，應立即停止全部受託處理業務","自第二次違反日起六個月內，得增加受託水量但不得增加對象"],"a",
 "第34條第1項：受託者於受託處理期間，一年內違反本法相關規定二次以上者，於第二次違反日起一年內，不得增加受託處理水量及對象。第2項：有違反本法第七條受裁處超過二次、排放含有害健康物質經認定危害公眾健康、受裁處停工（業）、經查獲繞流排放等情形之一者，應停止受託處理。",
 "If a provider breaches the Act twice within a year, what restriction applies?",
 ["For one year from the second breach, it may not increase entrusted volume or clients","For three years from the second breach, it may not increase entrusted volume or clients","For one year from the first breach, it must immediately halt all entrusted treatment","For six months from the second breach, volume may rise but clients may not be added"],
 "Article 34."),

(W,"第35條",3,"水措-海放管",
 "以海放管排放廢水於海洋者，其施工報備、結構檢視及故障通知期限各為何？",
 ["設置或變更施工應於完工後三十日內報請備查；每年應定期檢視結構確認稀釋率達一百倍；故障後三小時內通知主管機關","設置或變更施工應於開工前三十日內報請核准；每半年應定期檢視結構確認稀釋率達五十倍；故障後三日內通知主管機關","設置或變更施工應於完工後九十日內報請備查；每三年應定期檢視結構確認稀釋率達一百倍；故障後二十四小時內通知","設置或變更施工應於完工後三十日內報請核准；每年應定期檢視結構確認稀釋率達一千倍；故障後一個月內通知主管機關"],"a",
 "第35條：海放管設置或變更施工應於完工後三十日內報請主管機關備查；每年應定期檢視海放管結構，確認最初稀釋率達一百倍以上之功能，作成紀錄保存三年；海放管因故障、損壞有影響排放或船舶航行安全之虞者，應立即修復或清除，並於發現後三小時內通知主管機關。",
 "What are the reporting, inspection and notification deadlines for a sea outfall?",
 ["Report construction within 30 days of completion; inspect yearly confirming 100-fold dilution; notify within 3 hours of failure","Report construction 30 days before start for approval; inspect half-yearly confirming 50-fold dilution; notify within 3 days","Report construction within 90 days of completion; inspect every 3 years confirming 100-fold dilution; notify within 24 hours","Report construction within 30 days of completion for approval; inspect yearly confirming 1,000-fold dilution; notify within a month"],
 "Article 35."),

(W,"第36條",2,"水措-稀釋率不足",
 "海放管故障致最初稀釋率無法達一百倍以上時，應如何辦理？",
 ["排放之廢水應符合放流水標準；無法排放於海洋時得由主管機關許可之放流口排放地面水體，排放期間超過九十日應辦變更","排放之廢水應符合放流水標準；無法排放於海洋時得逕由原海放管排放地面水體，排放期間超過九十日應辦許可證註銷","排放之廢水應符合土壤處理標準；無法排放於海洋時得由主管機關許可之放流口排放地面水體，排放期間超過三日應變更","排放之廢水應符合放流水標準；無法排放於海洋時得由主管機關許可之放流口排放地面水體，排放期間超過十年應變更"],"a",
 "第36條第1項：海放管因故障或損壞致最初稀釋率無法達一百倍以上時，排放之廢（污）水應符合放流水標準；無法排放於海洋時得由主管機關許可之放流口排放於地面水體，但排放期間超過九十日者，應向核發機關辦理許可證（文件）之變更。第2項：故障或損壞之發生時間、通知時間、原因、修復狀況應記錄並保存三年。",
 "If a sea outfall fails to reach 100-fold dilution, what applies?",
 ["Discharge must meet the effluent standard; if sea discharge is impossible use a permitted outfall, and amend the permit after 90 days","Discharge must meet the effluent standard; if sea discharge is impossible use the same outfall pipe, and cancel the permit after 90 days","Discharge must meet the soil treatment standard; if sea discharge is impossible use a permitted outfall, and amend after 3 days","Discharge must meet the effluent standard; if sea discharge is impossible use a permitted outfall, and amend the permit after 10 years"],
 "Article 36."),

(W,"第37條",3,"水措-稀釋",
 "經許可採行稀釋者應於何處混合稀釋？因情況急迫而稀釋時應於多久內提出書面報告？",
 ["應於廢（污）水（前）處理設施單元之調勻設施混合稀釋；並於二十日內向直轄市、縣（市）主管機關及核發機關提出書面報告","應於放流池或放流口末端混合稀釋；並於二十日內向直轄市、縣（市）主管機關及核發機關提出稀釋期間因應作為書面報告","應於廢（污）水（前）處理設施單元之調勻設施混合稀釋；並於六個月內向中央主管機關及目的事業主管機關提出書面報告","應於廠外承受水體之混合區內混合稀釋；並於二十四小時內向直轄市、縣（市）主管機關及核發機關提出書面報告說明"],"a",
 "第37條第1項：經許可採行稀釋者，應於廢（污）水（前）處理設施單元之調勻設施混合稀釋。第2項：調勻設施應設置獨立專用進流水累計型水量計測設施。第3項：有本法第十八條之一第三項所定情形，因情況急迫為搶救人員或重大處理設施而稀釋時，應記錄起訖時間、原因、水量及通報時間，並於二十日內提出稀釋期間因應作為書面報告。",
 "Where must approved dilution occur, and when is the written report due?",
 ["In the equalization unit of the treatment facility; a written report within 20 days to the municipal or county and issuing authorities","At the effluent pond or the outfall end; a written report within 20 days to the municipal or county and issuing authorities","In the equalization unit of the treatment facility; a written report within 6 months to the central and industry authorities","In the mixing zone of the receiving water off site; a written report within 24 hours to the municipal and issuing authorities"],
 "Article 37 paragraphs 1 to 3."),

(W,"第38條",2,"水措-貯留設施",
 "以槽車清除運送廢水至作業環境外者，及廢棄物掩埋場返送滲出水者，應分別設置何種設施？",
 ["前者應於作業環境內設置貯留設施貯存尚未清除運送前之廢水；後者應設置收集滲出水之貯留設施、抽水設施及逕流廢水截流溝","前者應於作業環境外設置轉運站暫存尚未清除運送前之廢水；後者應設置收集滲出水之貯留設施、抽水設施及逕流廢水截流溝","前者應於作業環境內設置貯留設施貯存尚未清除運送前之廢水；後者僅需設置收集滲出水之抽水設施，免設貯留設施及截流溝","前者應於作業環境內設置沉砂池沉澱尚未清除運送前之廢水；後者應設置收集滲出水之調勻設施、加藥設施及地下水監測井"],"a",
 "第38條第1項：以桶裝、槽車或其他非管線、溝渠清除、運送廢（污）水至作業環境外者，應於作業環境內設置貯留設施，貯存尚未清除、運送前之廢（污）水。第2項：廢棄物掩埋場將滲出水返送至掩埋面者，應設置收集滲出水之貯留設施、抽水設施及逕流廢水之截流溝。第40條並規定貯留設施容量應可容納緊急應變之需。",
 "What facilities are required for tank truck removal and for landfill leachate recirculation?",
 ["On-site storage for wastewater awaiting removal; leachate storage, pumping facilities and a runoff interception ditch","Off-site transfer station for wastewater awaiting removal; leachate storage, pumping facilities and a runoff interception ditch","On-site storage for wastewater awaiting removal; only leachate pumping facilities, with no storage or interception ditch","On-site sedimentation basin for wastewater awaiting removal; leachate equalization, dosing facilities and monitoring wells"],
 "Article 38."),

(W,"第39條",3,"水措-貯留紀錄",
 "採貯留者應設置何種計測設施？其貯留紀錄應如何作成並保存多久？",
 ["應設進出流獨立專用累計型水量計測設施或自動記錄液位並顯示貯留水量之計測設施；應逐日逐批記錄並保存三年","應設進出流獨立專用瞬間型水量計測設施或人工目視估算液位之計量方式；應逐月彙總記錄並保存三年以備查閱","應設進出流獨立專用累計型水量計測設施或自動記錄液位並顯示貯留水量之計測設施；應逐年彙整記錄並保存一年","應設進出流共用之累計型水量計測設施或自動記錄水溫並顯示貯留水質之計測設施；應逐日逐批記錄並保存十年"],"a",
 "第39條第1項：貯留設施應設置進流水及出流水之獨立專用累計型水量計測設施，或自動記錄液位及顯示貯留水量之計測設施。第2項：應逐日逐批記錄廢水貯留時間、輸（運）送方式、水量及處理水量，並保存三年。第4項：以槽車清除未符合放流水標準之廢水，貯留期間超過三十日以上且未取得其他水措者，應停止產生廢水。",
 "What metering and records does storage of wastewater require?",
 ["Dedicated cumulative meters at inflow and outflow or automatic level recording showing volume; log daily and per batch, keep three years","Dedicated instantaneous meters at inflow and outflow or visual level estimation; log monthly summaries, keep three years","Dedicated cumulative meters at inflow and outflow or automatic level recording showing volume; log yearly summaries, keep one year","Shared cumulative meters at inflow and outflow or automatic temperature recording; log daily and per batch, keep ten years"],
 "Article 39 paragraphs 1, 2 and 4."),

(W,"第40條",1,"水措-貯留容量",
 "事業或污水下水道系統貯留設施之容量應如何設計？",
 ["其容量應可容納緊急應變之需","其容量以每日平均水量之半數為限","其容量應可容納全年產生之廢水量","其容量由代操作者依經驗自行決定"],"a",
 "第40條：事業或污水下水道系統貯留設施之容量應可容納緊急應變之需。第39條並要求貯留設施設置累計型水量計測設施或自動液位記錄設施，且應逐日逐批記錄貯留時間、輸送方式及水量。",
 "How must storage facility capacity be designed?",
 ["Capacity must accommodate emergency response needs","Capacity is capped at half of the average daily flow","Capacity must hold a full year of wastewater generated","Capacity is decided by the contract operator's experience"],
 "Article 40."),

(W,"第41條",3,"水措-回收使用",
 "廢水回收使用之原則為何？哪些情形不受該原則限制？",
 ["應處理至符合放流水標準始得回收使用並於回收前設採樣口；廢水作為製程之用、回收作為洗滌塔等防治設備且回收後之水經處理者除外","應處理至符合飲用水標準始得回收使用並於回收前設採樣口；廢水作為製程之用、回收作為洗滌塔等防治設備且回收後之水經處理者除外","應處理至符合放流水標準始得回收使用並於回收前設採樣口；廢水作為員工宿舍飲用、回收作為魚池補注且回收後之水未經處理者除外","應處理至符合土壤處理標準始得回收使用並於回收後設採樣口；廢水作為製程之用、回收作為冷卻水塔補水且回收後之水經稀釋者除外"],"a",
 "第41條第1項：產生之廢（污）水應處理至符合放流水標準始得回收使用，並於回收使用前設置採樣口；但產生之廢水作為製程之用，或回收作為洗滌塔或其他污染防治設備之用且回收使用後之水經設置之處理設施處理者，不在此限。第43條並要求於廢水產生及處理後、回收前分別設置獨立專用累計型水量計測設施。",
 "What is the rule for recycling wastewater, and which cases are excepted?",
 ["Treat to the effluent standard and install a sampling port before reuse; process use, or scrubber use with the returned water treated","Treat to the drinking water standard and install a sampling port before reuse; process use, or scrubber use with the returned water treated","Treat to the effluent standard and install a sampling port before reuse; dormitory drinking use, or fish pond top-up left untreated","Treat to the soil treatment standard and install a sampling port after reuse; process use, or cooling tower top-up with water diluted"],
 "Article 41 paragraph 1."),

(W,"第41條",3,"水措-補充水",
 "回收使用未符合放流水標準之廢水，以無須處理即能符合放流水標準之水源作為補充混合使用者，應如何辦理？",
 ["應提出補充必要性、水源、每日最大補充水量及計算量測方式等資料，經直轄市、縣（市）主管機關核准，並按日記錄補充水量保存三年","應提出補充必要性、水源、每日最大補充水量及計算量測方式等資料，向直轄市、縣（市）主管機關報備即可，並按月記錄水量保存一年","應提出補充必要性、水源、每年最大補充水量及計算量測方式等資料，經中央主管機關核准並公告，並按季記錄補充水量保存十年","應提出補充必要性、水源、每日最大補充水量及計算量測方式等資料，經目的事業主管機關同意，免記錄補充水量亦免保存文件"],"a",
 "第41條第2項第2款：以無須處理即能符合放流水標準之水源作為補充混合使用者，應提出補充之必要性、補充水來源、每日最大補充水量及其計算量測方式，並於未設處理設施處理回收水或經認定有必要時另提出質量平衡說明，經直轄市、縣（市）主管機關核准始得為之，並應按日記錄補充之水量保存三年。第3項：查核不符者應通知不得採行並限期辦理變更。",
 "How is make-up water that already meets the effluent standard approved for blending?",
 ["Submit necessity, source, maximum daily volume and measurement method for municipal or county approval; log daily, keep three years","Submit necessity, source, maximum daily volume and measurement method to the municipal or county authority for record; log monthly","Submit necessity, source, maximum yearly volume and measurement method for central approval and publication; log quarterly, keep ten years","Submit necessity, source, maximum daily volume and measurement method for industry authority consent; no logging or retention needed"],
 "Article 41 paragraph 2 subparagraph 2."),

(W,"第42條",2,"水措-回收排放",
 "回收使用後之水排放於地面水體及作為室內用水時，應分別符合何種標準？",
 ["排放地面水體應符合放流水標準；作為沖洗辦公場所、員工宿舍等室內用水應符合建築物污水處理設施之放流水標準","排放地面水體應符合放流水標準；作為沖洗辦公場所、員工宿舍等室內用水應符合飲用水水質標準及自來水水質規定","排放地面水體應符合土壤處理標準；作為沖洗辦公場所、員工宿舍等室內用水應符合建築物污水處理設施之放流水標準","排放地面水體應符合放流水標準；作為沖洗辦公場所、員工宿舍等室內用水無須符合任何標準，惟應避免與人體接觸"],"a",
 "第42條第1項：回收使用後之水應符合放流水標準始得排放於地面水體；但回收使用作為沖洗作業環境內辦公場所、員工宿舍及其他活動場所之室內用水，應符合建築物污水處理設施之放流水標準。第2項：回收使用之廢水應避免與人體接觸影響健康。",
 "Which standards apply to recycled water discharged to surface water and used indoors?",
 ["Effluent standard for surface water discharge; building sewage treatment effluent standard for indoor flushing use","Effluent standard for surface water discharge; drinking water quality and tap water standards for indoor flushing use","Soil treatment standard for surface water discharge; building sewage treatment effluent standard for indoor flushing","Effluent standard for surface water discharge; no standard at all for indoor flushing, only avoiding human contact"],
 "Article 42."),

(W,"第43條",2,"水措-回收計測",
 "回收使用廢水者應於哪些位置設置獨立專用累計型水量計測設施？回收使用前應設置何種設施？",
 ["應於廢水產生及處理後設置，回收前另設置回收使用之計測設施；回收使用前應設置廢（污）水（前）處理設施或貯留設施","應僅於廢水產生前設置一處計測設施即可，回收前免設置回收使用之計測設施；回收使用前應設置沉砂池或攔水渠設施","應於廢水產生及處理後設置，回收前另設置回收使用之計測設施；回收使用前應設置緊急應變放流口及自動監測設施","應於放流口及採樣口各設置一處計測設施，回收前免另設計測設施；回收使用前應設置海洋放流管線或土壤處理區"],"a",
 "第43條第1項：回收使用廢（污）水者，應於廢水產生及處理後設置獨立專用累計型水量計測設施；回收前，設置回收使用之獨立專用累計型水量計測設施。第2項：廢水回收使用者應於回收使用前，設置廢（污）水（前）處理設施或貯留設施，貯存廢（污）水。",
 "Where must cumulative flow meters be installed for recycling, and what facility precedes reuse?",
 ["After generation and after treatment, plus a reuse meter before recycling; treatment or storage facilities before reuse","Only one meter before generation, with no reuse meter before recycling; a sedimentation basin or interception channel","After generation and after treatment, plus a reuse meter before recycling; an emergency outfall and automatic monitors","One meter each at the outfall and sampling port, with no reuse meter; a sea outfall pipeline or soil treatment area"],
 "Article 43."),

(W,"第43條之1",3,"水措-回收除外",
 "哪些情形不適用回收使用章之規定？",
 ["廢水尚未進入處理設施僅於製程循環、於放流池前各處理單元間迴流返送、設置可獨立分割且無直接排放之淨化原廢水回收系統","廢水已進入處理設施並於放流後回收、於放流池後各處理單元間迴流返送、設置無法獨立分割且有直接排放之原廢水回收系統","廢水尚未進入處理設施僅於製程循環、於放流池前各處理單元間迴流返送、設置由代操作者操作且經技師簽證之回收系統","廢水尚未進入處理設施僅於廠外循環、於放流口後各處理單元間迴流返送、設置可獨立分割但有直接排放至土壤之系統"],"a",
 "第43條之1第1項：廢（污）水尚未進入處理設施僅於製程循環、於放流池（槽、口）前之處理設施各單元間迴流返送、設置淨化原廢水回收系統且淨化系統與後續處理設施可獨立分割並無廢水直接排放至地面水體或土壤者，不適用回收使用章規定。第2項：經認定無淨化功能之虞者應提出說明資料，屆期未提出或認定未具功能者應依本章辦理並限期變更。",
 "Which situations fall outside the wastewater recycling chapter?",
 ["Process-loop water before treatment; return flow between units ahead of the effluent pond; a separable purification system with no direct discharge","Water recycled after treatment and discharge; return flow between units after the effluent pond; an inseparable system with direct discharge","Process-loop water before treatment; return flow between units ahead of the effluent pond; a system run by a contractor and engineer-certified","Off-site loop water before treatment; return flow between units after the outfall; a separable system that discharges directly to soil"],
 "Article 43-1."),
]
