# -*- coding: utf-8 -*-
# 第 9 批（D9）：環境用藥管理法（ENV-76）逐條題（第1～30條）
EA = "ENV-76"
Q = [
(EA,"第1條",1,"環境用藥-立法目的",
 "環境用藥管理法之立法目的為何？",
 ["為防止環境用藥之危害，維護人體健康，保護環境","為促進環境用藥產業發展，提升外銷競爭力及產值","為統一環境用藥之市場價格，穩定供需及物價水準","為健全環境用藥業者財務，保障從業人員工作權益"],"a",
 "第1條：為防止環境用藥之危害，維護人體健康，保護環境，特制定本法。第2條並規定本法所稱主管機關在中央為行政院環境保護署，在直轄市為直轄市政府，在縣（市）為縣（市）政府。",
 "What is the legislative purpose of the Environmental Agents Control Act?",
 ["To prevent harm from environmental agents, safeguard human health and protect the environment","To promote the environmental agents industry and raise its export competitiveness and output","To unify the market prices of environmental agents and stabilise supply, demand and prices","To strengthen the finances of agent businesses and protect employees' working rights"],
 "Articles 1 and 2."),

(EA,"第2條",1,"環境用藥-主管機關",
 "環境用藥管理法所稱主管機關，在中央、直轄市及縣（市）分別為何？",
 ["中央為行政院環境保護署；直轄市為直轄市政府；縣（市）為縣（市）政府","中央為衛生福利部；直轄市為直轄市衛生局；縣（市）為縣（市）衛生局","中央為經濟部；直轄市為直轄市經濟發展局；縣（市）為縣（市）建設局","中央為行政院農業委員會；直轄市為直轄市農業局；縣（市）為縣（市）農業處"],"a",
 "第2條：本法所稱主管機關：在中央為行政院環境保護署；在直轄市為直轄市政府；在縣（市）為縣（市）政府。第3條、第4條並分別列舉中央主管機關及直轄市、縣（市）主管機關之主管事項。",
 "Which agencies are the competent authorities under this Act?",
 ["The Environmental Protection Administration centrally; the municipal government in special municipalities; the county or city government locally","The Ministry of Health and Welfare centrally; the municipal health bureau in special municipalities; the county health bureau locally","The Ministry of Economic Affairs centrally; the municipal economic development bureau; the county construction bureau locally","The Council of Agriculture centrally; the municipal agriculture bureau; the county agriculture department locally"],
 "Articles 2 to 4."),

(EA,"第3條",2,"環境用藥-中央權責",
 "中央主管機關之主管事項包括下列何者？",
 ["全國性環境用藥管理政策方案與計畫之策劃訂定及督導執行、全國性管理法規之執行訂定研議及釋示、管理之研究發展及宣導、全國性管理人員之訓練及管理、國際合作及科技交流",
  "轄內環境用藥管理實施方案與計畫之規劃及執行、轄內管理自治法規之訂定釋示及執行、轄內管理之研究發展及宣導、轄內管理之資料統計及彙報、其他有關轄內管理事項",
  "全國性環境用藥價格之審議及核定、業者財務狀況之查核及輔導、產業投資獎勵措施之研擬、外銷市場之開拓及推廣、同業公會之設立許可及監督管理等各項事項",
  "全國性環境用藥使用者之登記及發證、施藥人員之健康檢查及追蹤、藥害救濟基金之設立及運用、消費爭議之調處及仲裁、廣告內容之事前審查及核准等各項事項"],"a",
 "第3條：中央主管機關之主管事項如下：全國性環境用藥管理政策、方案與計畫之策劃、訂定及督導執行；全國性環境用藥管理法規之執行、訂定、研議及釋示；環境用藥管理之研究發展及宣導；全國性環境用藥管理人員之訓練及管理；全國性環境用藥管理業務之督導；全國性環境用藥管理之協調或執行；環境用藥管理之國際合作及科技交流；其他有關全國性環境用藥管理事項。",
 "Which matters fall to the central competent authority?",
 ["Planning, setting and supervising national policies, programmes and plans; enforcing, drafting and interpreting national regulations; research, development and promotion; training and managing national personnel; and international cooperation and scientific exchange",
  "Planning and implementing the programmes and plans within its own jurisdiction; drafting, interpreting and enforcing local self-government rules; local research, development and promotion work; local data statistics and reporting; and other local management matters",
  "Reviewing and approving national prices for environmental agents; auditing and guiding business finances; drafting investment incentives; developing and promoting export markets; and licensing and supervising trade associations",
  "Registering and licensing national users of environmental agents; health checks and follow-up for applicators; establishing a drug injury relief fund; mediating consumer disputes; and pre-approving advertising content"],
 "Article 3."),

(EA,"第4條",2,"環境用藥-地方權責",
 "直轄市、縣（市）主管機關之主管事項包括下列何者？",
 ["轄內環境用藥管理之實施方案與計畫之規劃及執行、管理法規之執行與轄內管理自治法規之訂定釋示及執行、轄內管理之研究發展及宣導、轄內管理之資料統計及彙報",
  "全國性環境用藥管理政策方案與計畫之策劃訂定及督導執行、全國性管理法規之訂定研議及釋示、全國性管理人員之訓練及管理、環境用藥管理之國際合作及科技交流事項",
  "轄內環境用藥售價之核定及公告、轄內業者營業額之統計及課稅、轄內從業人員勞健保之查核、轄內工廠用地之變更編定及都市計畫審議等有關轄內經濟發展之事項",
  "轄內環境用藥許可證之查驗登記及核發、原體轉讓之審查及核准、委託製造之審查及核准、專供輸出環境用藥之核准及其他依本法應由中央主管機關辦理之各項事項"],"a",
 "第4條：直轄市、縣（市）主管機關之主管事項如下：轄內環境用藥管理之實施方案與計畫之規劃及執行；環境用藥管理法規之執行與轄內環境用藥管理自治法規之訂定、釋示及執行；轄內環境用藥管理之研究發展及宣導；轄內環境用藥管理之資料統計及彙報；其他有關轄內環境用藥管理事項。",
 "Which matters fall to the special municipality, county or city competent authority?",
 ["Planning and implementing local programmes and plans; enforcing regulations and drafting, interpreting and enforcing local self-government rules; local research, development and promotion; and local statistics and reporting",
  "Planning, setting and supervising national policies, programmes and plans; drafting and interpreting national regulations; training and managing national personnel; and international cooperation and scientific exchange",
  "Approving and announcing local prices for environmental agents; compiling local turnover statistics and taxation; auditing employees' labour and health insurance; and rezoning factory land and urban planning review",
  "Registering and issuing local product permits; reviewing and approving transfers of active ingredients; approving contract manufacture; approving export-only agents; and other matters the Act assigns to the central authority"],
 "Article 4."),

(EA,"第5條",3,"環境用藥-用詞定義",
 "本法所稱環境用藥原體、一般環境用藥及特殊環境用藥，其定義為何？",
 ["原體指用以製造加工一般及特殊環境用藥所需之有效成分原料；一般環境用藥指以原體經製造加工所含有效成分符合中央主管機關所規定限量且使用簡便之藥品；特殊環境用藥指須在安全防護措施下使用或其他經中央主管機關認定之藥品",
  "原體指已完成包裝並得直接販售予一般消費者之成品藥劑；一般環境用藥指僅得由領照病媒防治業使用之高濃度藥品；特殊環境用藥指得由一般民眾自由購買使用且無須任何安全防護措施之低濃度藥品或微生物製劑等藥劑",
  "原體指經中央主管機關公告禁止製造輸入之成分；一般環境用藥指經直轄市縣市主管機關核准販賣之藥品；特殊環境用藥指經目的事業主管機關認定屬工業用途之藥品，三者依其用途及販售通路分別加以區分",
  "原體指自國外輸入而尚未經查驗登記之藥品；一般環境用藥指國內自行研發並取得專利之藥品；特殊環境用藥指專供輸出而不得在國內販賣之藥品，三者依其來源地及流通方向不同而分別為不同之定義"],"a",
 "第5條第1項第2款：環境用藥原體指用以製造、加工一般環境用藥、特殊環境用藥所需之有效成分原料。第3款：一般環境用藥指以環境用藥原體經製造、加工，所含有效成分符合中央主管機關所規定限量，使用簡便之藥品。第4款：特殊環境用藥指以環境用藥原體經製造、加工，須在安全防護措施下使用或其他經中央主管機關認定之藥品。第1款並定義環境用藥包括環境衛生用殺蟲劑、殺鼠劑、殺菌劑，及防治空氣水土壤污染或處理廢棄物之化學合成藥品與微生物製劑。",
 "How are active ingredients, general and special environmental agents defined?",
 ["Active ingredients are the raw materials used to make general and special agents; general agents are made from them, contain active ingredients within the limits prescribed centrally and are simple to use; special agents must be used under safety protection measures or are so designated centrally",
  "Active ingredients are finished packaged products sold directly to ordinary consumers; general agents are high-concentration products usable only by licensed pest control businesses; special agents are low-concentration products the public may buy and use freely with no protection measures at all",
  "Active ingredients are components the central authority has banned from manufacture or import; general agents are products the local authority has approved for sale; special agents are products the industry authority classifies as industrial, distinguished by use and sales channel",
  "Active ingredients are products imported from abroad not yet registered; general agents are domestically developed and patented products; special agents are products made only for export and not sold domestically, distinguished by origin and direction of trade"],
 "Article 5."),

(EA,"第6條",3,"環境用藥-偽造環境用藥",
 "本法所稱偽造環境用藥，指環境用藥有何情形者？",
 ["未經中央主管機關核准而製造加工輸入；摻雜或抽換國內外產品；塗改或變更有效期間標示；所含有效成分種類與核准不符",
  "未經中央主管機關核准而添加變更著色劑防腐劑；有效成分含量與容許誤差範圍不符；超過有效期限；標示文字有誤植情形",
  "含有經中央主管機關公告禁止製造加工輸入輸出販賣或使用之成分；未依核准事項辦理；未置專業技術人員；未按月記錄",
  "未依規定申請查驗登記展延；未於期滿前三個月至六個月申請展延；許可證經廢止後仍繼續製造；未辦理工廠登記者"],"a",
 "第6條第1項：本法所稱偽造環境用藥，指環境用藥有下列情形之一者：未經中央主管機關核准而製造、加工、輸入；摻雜或抽換國內外產品；塗改或變更有效期間標示；所含有效成分種類與核准不符。第2項：前項第三款所稱有效期間標示，指環境用藥標示上登載之製造日期、批號及有效期限。第7條則規定禁用環境用藥指含有經中央主管機關公告禁止之成分者。",
 "What constitutes a counterfeit environmental agent?",
 ["Manufacture, processing or import without central approval; adulteration or substitution of domestic or foreign products; alteration of the validity period marking; or active ingredient types differing from those approved",
  "Adding or changing colourants or preservatives without central authority approval; active ingredient content outside the permitted tolerance range; being past the stated expiry date; or misprinted wording appearing on the product label",
  "Containing an ingredient the central authority has banned from manufacture, import, export, sale or use; not following approved terms; not appointing technical staff; or not keeping monthly records",
  "Not applying for registration or extension as required; not applying three to six months before expiry; continuing manufacture after the permit is annulled; or not obtaining factory registration"],
 "Articles 6 and 7."),

(EA,"第7條",1,"環境用藥-禁用環境用藥",
 "本法所稱禁用環境用藥，其定義為何？",
 ["指環境用藥含有經中央主管機關公告禁止製造、加工、輸入、輸出、販賣或使用之成分者",
  "指環境用藥含有經直轄市、縣（市）主管機關認定不適合於轄內販賣或使用之成分者",
  "指環境用藥含有經目的事業主管機關認定屬工業用途而不宜供環境衛生使用之成分者",
  "指環境用藥含有未經中央主管機關公告列入正面表列而尚待審查認定之新開發成分者"],"a",
 "第7條：本法所稱禁用環境用藥，指環境用藥含有經中央主管機關公告禁止製造、加工、輸入、輸出、販賣或使用之成分者。第38條並規定主管機關查獲偽造或禁用之環境用藥，應通知業者自通知書到達翌日起七日內將庫存品列冊，十五日內將市售品收回列冊。",
 "How is a banned environmental agent defined?",
 ["An agent containing an ingredient the central authority has announced as banned from manufacture, processing, import, export, sale or use",
  "An agent containing an ingredient the local authority considers unsuitable for sale or use within its own jurisdiction",
  "An agent containing an ingredient the industry authority regards as industrial and unsuitable for environmental sanitation use",
  "An agent containing a newly developed ingredient not yet on a central positive list and still awaiting review and determination"],
 "Articles 7 and 38."),

(EA,"第8條",2,"環境用藥-劣質環境用藥",
 "本法所稱劣質環境用藥，指環境用藥有何情形者？",
 ["未經中央主管機關核准而添加或變更著色劑、防腐劑、香料、溶劑或賦形劑；有效成分含量與容許誤差範圍不符；超過有效期限",
  "未經中央主管機關核准而製造、加工或輸入；摻雜或抽換國內外之產品；塗改或變更其有效期間之標示；有效成分種類與核准不符",
  "含有經中央主管機關公告禁止使用之成分；未依核准事項辦理製造；未置專業技術人員；未依規定按月記錄製造加工輸出輸入數量",
  "未於期滿前申請展延許可證；未辦理工廠登記；未符合環境用藥工廠設廠標準；未依規定申請調配或分裝之核准即逕行分裝者"],"a",
 "第8條：本法所稱劣質環境用藥，指環境用藥有下列情形之一者：未經中央主管機關核准而添加或變更著色劑、防腐劑、香料、溶劑或賦形劑；有效成分含量與容許誤差範圍不符；超過有效期限。第39條並規定主管機關查獲劣質環境用藥，應通知業者自通知書到達翌日起七日內將庫存品列冊，一個月內將市售品收回列冊。",
 "What constitutes a substandard environmental agent?",
 ["Adding or changing colourants, preservatives, fragrances, solvents or excipients without central approval; active ingredient content outside the permitted tolerance; or being past the expiry date",
  "Manufacture, processing or import without central approval; adulteration or substitution of domestic or foreign products; alteration of the validity period marking; or active ingredient types differing from those approved",
  "Containing an ingredient the central authority has banned from use; not manufacturing under the approved terms; not appointing technical staff; or not keeping monthly records of quantities",
  "Not applying to extend the permit before expiry; not obtaining factory registration; not meeting the plant standards; or repackaging without first obtaining approval for blending or repackaging"],
 "Articles 8 and 39."),

(EA,"第9條",3,"環境用藥-查驗登記",
 "製造、加工或輸入環境用藥，應如何辦理？旅客攜帶少量自用者如何？",
 ["應將名稱成分性能製法要旨分析方法毒理報告藥效報告及有關資料證件連同標示及樣品向中央主管機關申請查驗登記，經核發許可證後始得製造加工或輸入；旅客攜帶少量自用者不受限制但限供自用不得販售",
  "應將名稱成分性能製法要旨分析方法毒理報告藥效報告及有關資料證件連同標示及樣品向直轄市縣市主管機關申請登記，經核發執照後始得製造加工或輸入；旅客攜帶少量自用者仍應申請查驗登記後始得攜入",
  "應向目的事業主管機關申請工廠登記並取得同意函後即得製造加工或輸入而無須辦理查驗登記；旅客攜帶少量自用者應向海關申報並繳納關稅後始得攜入，且得於國內自由轉售予他人使用",
  "應向中央主管機關報備其產品名稱及成分即可，無須提交毒理報告或藥效報告等資料；旅客攜帶少量自用者一律禁止攜入，海關查獲時應責令納稅義務人限期辦理退運或逕予沒入銷毀"],"a",
 "第9條第1項：製造、加工或輸入環境用藥，應將其名稱、成分、性能、製法之要旨、分析方法、毒理報告、藥效（效力）報告及有關資料或證件，連同標示及樣品，向中央主管機關申請查驗登記，經核發許可證後，始得製造、加工或輸入。第2項：屬一般環境用藥者，主管機關應於網際網路上公告其廠商、產品名稱、許可證字號、成分、性能及產品標示。第3項：輸入未經許可者，海關應責令納稅義務人限期辦理退運。第4項、第5項：旅客或交通工具服務人員攜帶少量自用者不受第1項限制，但限供自用不得販售。",
 "How must manufacture, processing or import be handled, and what about travellers' personal use?",
 ["Submit the name, ingredients, performance, process summary, analytical methods, toxicology and efficacy reports and related documents with labels and samples to the central authority for registration, and manufacture only after a permit issues; travellers carrying small amounts for personal use are exempt but may not sell them",
  "Submit the name, ingredients, performance, process summary, analytical methods, toxicology and efficacy reports and related documents together with labels and samples to the local competent authority, and manufacture only after a licence issues; travellers must still apply for registration before bringing any in at all",
  "Apply to the industry authority for factory registration and a consent letter, after which manufacture or import may proceed without any product registration; travellers must declare to customs and pay duty, and may then resell freely within the country",
  "Merely file the product name and ingredients with the central authority, with no toxicology or efficacy reports needed; travellers are wholly barred from bringing any in, and customs must order return shipment or confiscate and destroy them"],
 "Article 9."),

(EA,"第10條",3,"環境用藥-許可證期限",
 "環境用藥許可證之有效期間及展延規定為何？",
 ["有效期間為五年，期滿仍須繼續製造加工或輸入者，應於期滿前三個月至六個月之期間內向中央主管機關申請展延，每次展延不得超過五年",
  "有效期間為十年，期滿仍須繼續製造加工或輸入者，應於期滿前六個月至一年之期間內向中央主管機關申請展延，每次展延不得超過十年",
  "有效期間為三年，期滿仍須繼續製造加工或輸入者，應於期滿後三十日內向直轄市縣市主管機關申請展延，每次展延不得超過三年",
  "有效期間為永久而無須展延，惟應每五年向中央主管機關報備一次其製造加工或輸入之情形，未報備者其許可證即自動失其效力"],"a",
 "第10條第1項：環境用藥許可證有效期間為五年，期滿仍須繼續製造、加工或輸入者，應於期滿前三個月至六個月之期間內，向中央主管機關申請展延。每次展延，不得超過五年；其申請條件、准駁、撤銷、廢止、展延、變更、核（換、補）發及其他應遵行事項之準則，由中央主管機關定之。第2項：為維護國民健康或保護環境生態所必要，中央主管機關得廢止前項許可證。第3項：廢止原因消失時，原申請者得提出科學技術或實地調查結果之證實，向中央主管機關重行申請。",
 "How long is an environmental agent permit valid and how is it extended?",
 ["Valid for five years; to continue manufacture, processing or import, apply to the central authority in the window from six to three months before expiry, with each extension not exceeding five years",
  "Valid for ten years; to continue manufacture, processing or import, apply to the central authority in the window from one year to six months before expiry, with each extension not exceeding ten years",
  "Valid for three years; to continue manufacture, processing or import, apply to the local authority within 30 days after expiry, with each extension not exceeding three years",
  "Valid indefinitely with no extension needed, though manufacture or import must be reported to the central authority every five years or the permit lapses automatically"],
 "Article 10."),

(EA,"第11條",2,"環境用藥-許可執照",
 "環境用藥販賣業及病媒防治業應如何取得營業資格？何種情形免申領販賣業許可執照？",
 ["應向當地主管機關申請經審查核准登記領得許可執照後始得營業；環境用藥製造業者於製造許可證登記之廠商或製造廠址兼營自製產品之輸出批發零售及自用原體輸入者，免申領販賣業許可執照",
  "應向中央主管機關申請經審查核准登記領得許可執照後始得營業；環境用藥製造業者兼營任何他廠產品之批發零售者，亦免申領環境用藥販賣業許可執照而得逕行從事販賣業務",
  "應向目的事業主管機關辦理公司登記後即得營業而無須另申請許可執照；環境用藥製造業者及販賣業者均免申領任何許可執照，僅病媒防治業者始須申領許可執照後營業",
  "應向當地主管機關報備後即得先行營業並於六個月內補辦許可執照；環境用藥製造業者兼營自製產品輸出批發零售者，應另申領販賣業許可執照始得從事該等業務"],"a",
 "第11條第1項：環境用藥販賣業及病媒防治業，應向當地主管機關申請，經審查核准登記，領得許可執照後，始得營業。但環境用藥製造業者於環境用藥製造許可證登記之廠商或製造廠址兼營自製產品之輸出、批發、零售及自用原體輸入者，免申領環境用藥販賣業許可執照。第2項：領有許可執照之販賣業與病媒防治業者，主管機關應於網際網路上公告公司名稱與負責人、許可證字號等資訊。第50條並規定未依第11條取得許可執照而從事業務者，處三萬元以上十五萬元以下罰鍰。",
 "How do sellers and pest control businesses qualify, and who is exempt from a seller's licence?",
 ["Apply to the local authority, obtain approved registration and a licence before trading; manufacturers who at the firm or plant address on their manufacturing permit also export, wholesale or retail their own products and import their own active ingredients are exempt from the seller's licence",
  "Apply to the central competent authority, obtain approved registration and a licence before trading; manufacturers who also wholesale or retail any other firm's products at any location are likewise exempt from the environmental agent seller's licence and may trade directly without one",
  "Simply register the company with the industry authority and trade without any licence; both manufacturers and sellers are exempt from all licences, and only pest control businesses need a licence before trading",
  "File with the local authority and begin trading at once, obtaining the licence within six months; manufacturers who export, wholesale or retail their own products must additionally hold a seller's licence for that business"],
 "Articles 11 and 50."),

(EA,"第12條",1,"環境用藥-依核准辦理",
 "持有環境用藥製造、輸入許可證、環境用藥販賣業或病媒防治業許可執照者，負何義務？",
 ["應依核准事項辦理","得視市場需要自行調整","應每年重新申請核准","應報請目的事業主管機關備查"],"a",
 "第12條：持有環境用藥製造、輸入許可證、環境用藥販賣業或病媒防治業許可執照者，應依核准事項辦理。第49條第1款並規定違反第12條規定者，處新臺幣三萬元以上十五萬元以下罰鍰，並得令其限期改善；屆期未改善或情節重大者，撤銷、廢止其許可證或許可執照。",
 "What duty falls on holders of permits or licences under this Act?",
 ["They must act in accordance with the approved terms","They may adjust matters themselves as the market requires","They must re-apply for approval every year","They must file the matter with the industry authority"],
 "Articles 12 and 49."),

(EA,"第13條",2,"環境用藥-設廠標準",
 "環境用藥製造業者就工廠登記及設廠標準，負何義務？該標準由何機關訂定？",
 ["應依有關法規規定辦理工廠登記，其設備及安全衛生條件應符合環境用藥工廠設廠標準；該標準由中央主管機關會同相關目的事業主管機關定之",
  "應依有關法規規定辦理商業登記，其設備及安全衛生條件應符合勞工安全衛生設施規則；該標準由勞動主管機關會同中央主管機關共同定之",
  "得免辦理工廠登記而僅需辦理公司登記，其設備條件由業者依實際需要自行決定；主管機關不得就設廠條件另訂任何標準加以限制業者",
  "應依有關法規辦理工廠登記，其設備及安全衛生條件應符合國際標準組織之規範；該標準由同業公會會同認證機構共同研議後公告"],"a",
 "第13條：環境用藥製造業者，應依有關法規規定辦理工廠登記，其設備及安全衛生條件，應符合環境用藥工廠設廠標準；其標準，由中央主管機關會同相關目的事業主管機關定之。第49條第3款並規定違反依第13條所定設廠標準中有關工廠環境、製程設備、檢驗設備之管理規定者，處三萬元以上十五萬元以下罰鍰。",
 "What factory registration and plant standard duties fall on manufacturers?",
 ["They must obtain factory registration under the relevant laws, and their equipment and health and safety conditions must meet the environmental agent plant standards, set by the central authority with the relevant industry authorities",
  "They must obtain business registration under the relevant laws, and their equipment and health and safety conditions must meet the occupational safety facility rules, jointly set by the labour authority and the central authority",
  "They need only company registration rather than factory registration, and may decide equipment conditions themselves; the authorities may not set any plant conditions restricting them",
  "They must obtain factory registration under the relevant laws, and their equipment and health and safety conditions must meet ISO norms, drawn up and announced by the trade association with accreditation bodies"],
 "Articles 13 and 49."),

(EA,"第14條",1,"環境用藥-原體限制",
 "環境用藥製造業者就製造、加工環境用藥所用之原體，有何限制？",
 ["不得以未經查驗登記之環境用藥原體製造、加工環境用藥","得以未經查驗登記之原體製造，惟應於事後補辦查驗登記","得以任何原體製造，僅於輸出時始須使用經查驗登記之原體","不得以經查驗登記之原體製造，應一律使用自行合成之原體"],"a",
 "第14條：環境用藥製造業者，不得以未經查驗登記之環境用藥原體製造、加工環境用藥。第48條第1款並規定違反第14條規定者，處新臺幣六萬元以上三十萬元以下罰鍰，並得限期令其改善；屆期未改善或情節重大者，撤銷、廢止其許可證或許可執照，必要時並得勒令停工、停業或歇業。",
 "What limit applies to the active ingredients manufacturers may use?",
 ["They may not use unregistered active ingredients to manufacture or process environmental agents","They may use unregistered active ingredients provided registration is completed afterwards","They may use any active ingredient, and registered ones are required only for exports","They may not use registered active ingredients and must synthesise their own instead"],
 "Articles 14 and 48."),

(EA,"第15條",1,"環境用藥-原體轉讓",
 "環境用藥原體之轉讓，應如何辦理？其準則由何機關訂定？",
 ["環境用藥原體經中央主管機關核准者得轉讓之；其申請條件、審查及核准之準則，由中央主管機關定之",
  "環境用藥原體經直轄市縣市主管機關備查者得轉讓之；其申請條件及審查準則，由地方主管機關定之",
  "環境用藥原體一律不得轉讓予任何人，縱經中央主管機關核准亦同，違者應撤銷其製造許可證",
  "環境用藥原體得自由轉讓而無須經任何機關核准；惟受讓人應於受讓後三十日內向海關報備"],"a",
 "第15條第1項：環境用藥原體經中央主管機關核准者，得轉讓之。第2項：前項轉讓之申請條件、審查及核准之準則，由中央主管機關定之。第48條第1款並規定違反第15條第1項規定者，處新臺幣六萬元以上三十萬元以下罰鍰，並得限期令其改善。",
 "How may active ingredients be transferred, and who sets the rules?",
 ["Active ingredients may be transferred once approved by the central authority; the application conditions, review and approval rules are set by the central authority",
  "Active ingredients may be transferred once filed with the local authority; the application conditions and review rules are set by the local competent authority",
  "Active ingredients may never be transferred to anyone, even with central approval, and breach means revocation of the manufacturing permit",
  "Active ingredients may be transferred freely with no approval from any authority; the transferee need only notify customs within 30 days"],
 "Articles 15 and 48."),

(EA,"第16條",2,"環境用藥-專供輸出",
 "環境用藥製造業者依國外買方訂購要求製造專供輸出之環境用藥，應如何辦理？其限制為何？",
 ["經中央主管機關核准後得製造加工專供輸出之環境用藥，不受第九條第一項查驗登記規定之限制；該等環境用藥不得在國內販賣或移作他用",
  "經直轄市縣市主管機關核准後得製造加工專供輸出之環境用藥，仍應依第九條第一項辦理查驗登記；該等環境用藥得在國內販賣但不得移作他用",
  "無須經任何機關核准即得製造加工專供輸出之環境用藥；該等環境用藥並得在國內自由販賣或移作他用而不受本法任何規定之限制",
  "經目的事業主管機關核准後得製造加工專供輸出之環境用藥，並免辦理工廠登記；該等環境用藥於輸出前得在國內先行試銷六個月"],"a",
 "第16條第1項：環境用藥製造業者，得依國外買方訂購要求，經中央主管機關核准後，製造、加工專供輸出之環境用藥，不受第九條第一項規定之限制；其申請條件、審查、核准及其他應遵行事項之準則，由中央主管機關定之。第2項：前項經中央主管機關核准之環境用藥，不得在國內販賣或移作他用。第47條並規定違反第16條第2項規定者，處新臺幣九萬元以上四十五萬元以下罰鍰。",
 "How may export-only environmental agents be made, and what limits apply?",
 ["With central approval they may be manufactured or processed for export only, free from the Article 9(1) registration requirement; such agents may not be sold domestically or diverted to other uses",
  "With local competent authority approval they may be manufactured for export, but Article 9(1) registration still applies; such agents may be sold domestically but may not be diverted to other uses",
  "No approval from any authority is needed to make agents for export; such agents may also be sold freely domestically or diverted to other uses without restriction under this Act",
  "With industry authority approval they may be manufactured for export and are exempt from factory registration; such agents may be trial-sold domestically for six months before export"],
 "Articles 16 and 47."),

(EA,"第17條",1,"環境用藥-委託製造",
 "環境用藥製造業者就委託或接受委託製造環境用藥，有何規定？",
 ["非經中央主管機關核准，不得委託或接受委託製造環境用藥；其申請條件、審查、核准及其他應遵行事項之準則，由中央主管機關定之",
  "非經直轄市縣市主管機關備查，不得委託或接受委託製造環境用藥；其申請條件及審查準則，由地方主管機關依轄內情形分別訂定",
  "得自由委託或接受委託製造環境用藥而無須經任何機關核准；惟應於製造完成後三十日內報請中央主管機關備查其製造數量",
  "一律不得委託或接受委託製造環境用藥；縱經中央主管機關核准亦同，違者應撤銷其環境用藥製造許可證並勒令停工歇業"],"a",
 "第17條第1項：環境用藥製造業者，非經中央主管機關核准，不得委託或接受委託製造環境用藥。第2項：前項委託或接受委託之申請條件、審查、核准及其他應遵行事項之準則，由中央主管機關定之。第48條第1款並規定違反第17條第1項規定者，處新臺幣六萬元以上三十萬元以下罰鍰。",
 "What applies to contract manufacture of environmental agents?",
 ["Without central approval a manufacturer may not commission or accept contract manufacture; the application conditions, review, approval and other requirements are prescribed by the central authority",
  "Without a filing to the local competent authority a manufacturer may not commission or accept contract manufacture; the application conditions and review rules are set locally by each such authority",
  "Contract manufacture may be commissioned or accepted freely with no approval; the quantities made need only be filed with the central authority within 30 days of completion",
  "Contract manufacture is entirely prohibited even with central approval, and breach means revocation of the manufacturing permit and an order to halt work and close the business"],
 "Articles 17 and 48."),

(EA,"第18條",3,"環境用藥-調配分裝",
 "環境用藥之調配或分裝，其核准要求、定義及設備限制為何？",
 ["應經中央主管機關核准後始得為之；調配指以販賣為目的將不同成分或產品調合配藥，分裝指以販賣為目的將已核發許可證之環境用藥改變包裝內容量；分裝以具有同一劑型設備之環境用藥工廠始得為之",
  "應經直轄市縣市主管機關核准後始得為之；調配指以自用為目的將相同成分產品混合稀釋，分裝指以自用為目的將未核發許可證之環境用藥改變其包裝；分裝得由任何領有工廠登記之工廠為之",
  "無須經任何機關核准即得為之；調配及分裝均得由販賣業者於營業場所逕行辦理，亦得由病媒防治業者於施作現場依實際需要自行調配分裝而不受任何設備條件之限制",
  "應經目的事業主管機關核准後始得為之；調配指以研究為目的所為之試驗性配製，分裝指以展示為目的所為之樣品包裝；分裝以領有販賣業許可執照之營業場所始得為之而不限工廠"],"a",
 "第18條第1項：環境用藥之調配或分裝，應經中央主管機關核准後，始得為之。第2項：申請條件、審查、核准及其他應遵行事項之準則，由中央主管機關定之。第3項：所稱調配，指以販賣為目的，將不同成分或環境用藥產品調合配藥；所稱分裝，指以販賣為目的，將已核發許可證之環境用藥改變包裝內容量。第4項：環境用藥之分裝以具有同一劑型設備之環境用藥工廠，始得為之。第48條第1款並規定違反第18條第1項者處六萬元以上三十萬元以下罰鍰。",
 "What approval, definitions and equipment limits apply to blending and repackaging?",
 ["Central approval is required first; blending means combining different ingredients or products for sale, and repackaging means changing the pack size of a permitted agent for sale; repackaging may be done only at a plant with equipment for the same dosage form",
  "Local competent authority approval is required first; blending means mixing and diluting the same ingredients for one's own use, and repackaging means changing the pack of an unpermitted agent for one's own use; repackaging may be done at any registered factory",
  "No approval from any authority is needed; both blending and repackaging may be done by sellers at their premises or by pest control businesses on site as needed, with no equipment conditions at all",
  "Industry authority approval is required first; blending means experimental formulation for research and repackaging means sample packaging for display; repackaging may be done only at licensed sales premises rather than plants"],
 "Articles 18 and 48."),

(EA,"第19條",2,"環境用藥-專業技術人員",
 "環境用藥製造業、販賣業及病媒防治業者，就專業技術人員負何義務？相關辦法由何機關訂定？",
 ["應置專業技術人員；其所置人數、聘僱、訓練、資格、執行業務、證照取得與撤銷廢止、在職訓練、再訓練、出缺報備或代理等事項之辦法，由中央主管機關定之",
  "得視營業規模自行決定是否置專業技術人員；其人數及資格由業者依實際需要自行認定，主管機關不得另訂辦法加以限制業者之人事任用自由",
  "應置專業技術人員；其所置人數、聘僱、訓練及資格等事項之辦法，由各直轄市縣市主管機關分別依轄內產業情形訂定並報中央主管機關備查",
  "僅環境用藥製造業者應置專業技術人員，販賣業及病媒防治業者免置；其人數及資格之辦法，由同業公會會商認證機構後共同研議公告實施"],"a",
 "第19條第1項：環境用藥製造業、環境用藥販賣業及病媒防治業者，應置專業技術人員。第2項：前項專業技術人員之所置人數、聘僱、訓練、資格、執行業務、證照取得與撤銷、廢止、在職訓練、再訓練、出缺報備或代理及其他應遵行事項之辦法，由中央主管機關定之。第51條並規定專業技術人員違反該辦法中有關再訓練、執行業務、離職報備之規定者，處新臺幣四千元以上二萬元以下罰鍰，必要時得撤銷或廢止其合格證書。",
 "What duty applies regarding professional technical personnel, and who sets the rules?",
 ["Such personnel must be appointed; the rules on numbers, employment, training, qualifications, practice, certification and its revocation, in-service and refresher training, and vacancy reporting or substitution are set by the central authority",
  "Businesses may decide by their own operating scale whether to appoint any such personnel; the numbers and qualifications are for each business to judge for itself according to need, and the authorities may not restrict their freedom of appointment",
  "Such personnel must be appointed; the rules on numbers, employment, training and qualifications are set by each local authority for its own area and filed with the central authority",
  "Only manufacturers must appoint such personnel, with sellers and pest control businesses exempt; the rules on numbers and qualifications are drawn up by the trade association with accreditation bodies"],
 "Articles 19 and 51."),

(EA,"第20條",1,"環境用藥-標示販賣限制",
 "環境用藥販賣業及一般環境用藥批發、零售業者，有何販賣限制？",
 ["不得貯存、販賣未加標示之環境用藥或將環境用藥原包裝拆封販賣",
  "得貯存販賣未加標示之環境用藥，惟不得將原包裝拆封後販賣",
  "得將環境用藥原包裝拆封分裝後販賣，惟應於拆封後標示成分",
  "不得販賣任何環境用藥予未領有許可執照之病媒防治業者使用"],"a",
 "第20條：環境用藥販賣業及一般環境用藥批發、零售業者，不得貯存、販賣未加標示之環境用藥或將環境用藥原包裝拆封販賣。第48條第1款並規定違反第20條規定者，處新臺幣六萬元以上三十萬元以下罰鍰，並得限期令其改善；屆期未改善或情節重大者，撤銷、廢止其許可證或許可執照。",
 "What sales restriction applies to sellers and general agent wholesalers and retailers?",
 ["They may not store or sell unlabelled environmental agents, nor open the original packaging and sell from it",
  "They may store and sell unlabelled environmental agents, but may not open the original packaging to sell",
  "They may open the original packaging, repackage and sell, provided the ingredients are labelled after opening",
  "They may not sell any environmental agent to a pest control business that does not hold a licence"],
 "Articles 20 and 48."),

(EA,"第21條",3,"環境用藥-特殊環境用藥",
 "特殊環境用藥之銷售對象及使用者，各以何者為限？",
 ["銷售對象以衛生、環境保護主管機關或其所屬機關及持有許可執照之環境用藥販賣業、病媒防治業或其他經當地主管機關核准者為限；使用者以衛生、環境保護主管機關或其所屬機關及持有許可執照之病媒防治業或其他經當地主管機關核准者為限",
  "銷售對象以一般民眾及各類零售販賣通路為限而不包含任何衛生環境保護主管機關或其所屬機關；使用者以領有工廠登記證明文件之環境用藥製造業者或經同業公會推薦之從業人員為限，其餘任何人均不得購買或使用特殊環境用藥",
  "銷售對象以領有環境用藥製造許可證之業者為限；使用者以農民、林業經營者及漁業養殖業者為限，並應於使用前向當地農業主管機關報備其使用之數量、地點及施藥之方式",
  "銷售對象及使用者均無任何限制，任何人均得自由購買及使用；惟購買數量逾一定金額者應憑身分證明文件登記，並由販賣業者按月將購買人名冊報請主管機關備查"],"a",
 "第21條第1項：特殊環境用藥之銷售對象，以衛生、環境保護主管機關或其所屬機關及持有許可執照之環境用藥販賣業、病媒防治業或其他經當地直轄市、縣（市）主管機關核准者為限。第2項：特殊環境用藥之使用者，以衛生、環境保護主管機關或其所屬機關及持有許可執照之病媒防治業或其他經當地直轄市、縣（市）主管機關核准者為限。第49條第1款並規定違反第21條第1項或第2項規定者，處新臺幣三萬元以上十五萬元以下罰鍰。",
 "To whom may special environmental agents be sold, and who may use them?",
 ["Sales are limited to health and environmental authorities and their subordinate agencies, licensed sellers and pest control businesses, and others approved by the local authority; use is limited to those authorities and agencies, licensed pest control businesses, and others approved by the local authority",
  "Sales are limited to the general public and all kinds of retail sales channels with no health or environmental protection authorities or their subordinate agencies included; use is limited to registered manufacturers or personnel recommended by the trade association, with all others barred from buying or using them at all",
  "Sales are limited to holders of a manufacturing permit; use is limited to farmers, forestry operators and aquaculture businesses, who must notify the local agriculture authority of quantities, places and methods before use",
  "There is no restriction at all on buyers or users and anyone may buy and use them; buyers above a certain value must show identity documents, and sellers file a monthly buyer list with the authority"],
 "Articles 21 and 49."),

(EA,"第22條",2,"環境用藥-病媒防治業",
 "病媒防治業執行業務，應符合何規定？其相關辦法由何機關訂定？",
 ["應符合中央主管機關之規定；其環境用藥安全使用、操作與防護、施藥人員訓練、用藥、施作紀錄提報與保存、施作計畫及其他應遵行事項之辦法，由中央主管機關定之",
  "應符合當地直轄市縣市主管機關之規定；其安全使用、施藥人員訓練及施作紀錄等事項之辦法，由各地方主管機關依轄內情形分別訂定後報請中央主管機關核定",
  "應符合同業公會自律規範之規定；其安全使用、操作與防護及施藥人員訓練等事項，由同業公會自行訂定並報請目的事業主管機關備查後對會員發生拘束效力",
  "應符合委託客戶所要求之規定；其用藥種類、施作方式及紀錄保存年限均由客戶與業者於契約中自行約定，主管機關不得就執行業務事項另訂任何管理辦法"],"a",
 "第22條：病媒防治業執行業務，應符合中央主管機關之規定；其環境用藥安全使用、操作與防護、施藥人員訓練、用藥、施作紀錄提報與保存、施作計畫及其他應遵行事項之辦法，由中央主管機關定之。第49條第5款並規定違反依第22條所定辦法中有關施藥人員訓練、用藥、安全防護設備、施作計畫書告知客戶、施作紀錄提報、紀錄保存之管理規定者，處新臺幣三萬元以上十五萬元以下罰鍰。",
 "What must pest control businesses comply with, and who sets the rules?",
 ["The central authority's requirements; the rules on safe use, operation and protection, applicator training, agent use, reporting and retention of work records, work plans and other requirements are set by the central authority",
  "The local competent authority's own requirements; the rules on safe use, applicator training and the keeping of work records are drafted by each local authority for its own area and submitted to the central authority for approval",
  "The trade association's self-regulatory code; the rules on safe use, operation, protection and applicator training are drawn up by the association and bind members once filed with the industry authority",
  "The requirements of the client who commissioned the work; the agents used, methods and record retention are agreed between client and business in contract, and no authority may set management rules"],
 "Articles 22 and 49."),

(EA,"第23條",3,"環境用藥-試驗研究",
 "專供試驗研究、教育示範、專案防治或申請登記用之環境用藥，經核准者有何效果及限制？",
 ["經中央主管機關核准者不受第九條第一項及第十五條規定之限制；該等環境用藥不得販賣或移作他用；經核准試驗研究或教育示範者，基於國民健康之維護或環境生態之保護，中央主管機關得廢止其核准",
  "經直轄市縣市主管機關核准者不受第九條第一項及第十五條規定之限制；該等環境用藥得於試驗完成後販賣或移作他用；經核准者中央主管機關不得以任何理由廢止其原核准之處分",
  "無須經任何機關核准即不受本法規定之限制；該等環境用藥並得自由販賣或移作他用，主管機關不得加以限制，亦不得廢止任何試驗研究或教育示範之核准",
  "經目的事業主管機關核准者仍應依第九條第一項辦理查驗登記；該等環境用藥於取得許可證後即得販賣；經核准者僅於業者自行申請時始得廢止其核准之處分"],"a",
 "第23條第1項：專供試驗研究、教育示範、專案防治或申請登記用之環境用藥，經中央主管機關核准者，不受第九條第一項及第十五條規定之限制；其申請條件、審查、核准及其他應遵行事項之準則，由中央主管機關定之。第2項：前項經核准之環境用藥，不得販賣或移作他用。第3項：經核准試驗研究或教育示範之環境用藥，基於國民健康之維護或環境生態之保護，中央主管機關得廢止其核准。第47條並規定違反第23條第2項規定者，處九萬元以上四十五萬元以下罰鍰。",
 "What effect and limits apply to agents approved for research, education, special control or registration?",
 ["With central approval they are exempt from Articles 9(1) and 15; they may not be sold or diverted to other uses; and approvals for research or educational demonstration may be annulled by the central authority to protect public health or the environment",
  "With local competent authority approval they are exempt from Articles 9(1) and 15; they may be sold or diverted to other uses once the trial has ended; and the central competent authority may not annul such an approval on any ground whatsoever at all",
  "No approval from any authority is needed and this Act does not restrict them; they may be sold or diverted freely, the authorities may not restrict them, and no research or demonstration approval may be annulled",
  "With industry authority approval Article 9(1) registration still applies; they may be sold once a permit issues; and approvals may be annulled only where the business itself applies for annulment"],
 "Articles 23 and 47."),

(EA,"第24條",2,"環境用藥-紀錄保存",
 "環境用藥製造業、販賣業及病媒防治業者，就數量紀錄負何義務？其紀錄應保存多久？",
 ["應按月記錄環境用藥之製造、加工、輸出、輸入、販賣及使用數量；紀錄資料應保存三年，必要時主管機關得令業者提報之",
  "應按年記錄環境用藥之製造、加工、輸出、輸入、販賣及使用數量；紀錄資料應保存一年，主管機關不得令業者提報該等紀錄",
  "應按日記錄環境用藥之製造及販賣數量而免記錄輸出輸入及使用數量；紀錄資料應保存十年並應主動每月報請主管機關備查",
  "得視實際需要自行決定是否記錄各項數量；如有記錄者應保存六個月，主管機關僅得於發生事故時始得令業者提報該紀錄"],"a",
 "第24條第1項：環境用藥製造業、環境用藥販賣業及病媒防治業者，應按月記錄環境用藥之製造、加工、輸出、輸入、販賣及使用數量。第2項：前項紀錄資料應保存三年；必要時，主管機關得令業者提報之。第48條第1款並規定違反第24條第1項、第2項規定者，處新臺幣六萬元以上三十萬元以下罰鍰，並得限期令其改善。",
 "What record-keeping duty applies, and how long must records be kept?",
 ["Monthly records of manufacture, processing, export, import, sale and use quantities; the records must be kept for three years and produced to the authority on demand",
  "Annual records of manufacture, processing, export, import, sale and use quantities; the records must be kept for one year and the authority may not require their production",
  "Daily records of manufacture and sale quantities only, excluding export, import and use; the records must be kept for ten years and filed monthly with the authority",
  "Businesses may decide for themselves whether to keep records; any kept must be held for six months, and the authority may require them only after an incident"],
 "Articles 24 and 48."),

(EA,"第25條",2,"環境用藥-容許誤差",
 "環境用藥有效成分含量容許誤差範圍由何機關公告？其變更應於何時公告？",
 ["由中央主管機關公告之；容許誤差範圍如有變更，應於施行之日起六個月前公告","由中央主管機關公告之；容許誤差範圍如有變更，應於施行之日起三十日前公告","由直轄市縣市主管機關公告之；容許誤差範圍如有變更，應於施行當日公告即可","由同業公會研議後公告之；容許誤差範圍如有變更，應於施行之日起一年前公告"],"a",
 "第25條第1項：環境用藥有效成分含量容許誤差範圍，由中央主管機關公告之。第2項：前項容許誤差範圍如有變更，應於施行之日起六個月前公告。第8條第2款並規定有效成分含量與容許誤差範圍不符者，屬劣質環境用藥；第46條第3項則規定製造、加工或輸入該等劣質環境用藥者，處負責人六萬元以上三十萬元以下罰鍰。",
 "Who announces the tolerance range for active ingredient content, and when must changes be announced?",
 ["The central competent authority announces it; any change must be announced six months before the date it takes effect","The central competent authority announces it; any change must be announced thirty days before the date it takes effect","The local competent authority announces it; any change may simply be announced on the day it takes effect","The trade association announces it after deliberation; any change must be announced one year before it takes effect"],
 "Articles 8, 25 and 46."),

(EA,"第26條",1,"環境用藥-貯存管理",
 "環境用藥之貯存、置放、數量、地點、使用藥劑種類、人員安全防護設備及污染防治措施等事項之辦法，由何機關訂定？",
 ["由中央主管機關定之","由地方主管機關定之","由目的事業主管機關定之","由業者自行訂定報備"],"a",
 "第26條：環境用藥之貯存、置放、數量、地點、使用藥劑種類、人員安全防護設備、污染防治措施及其他應遵行事項之辦法，由中央主管機關定之。第48條第2款並規定違反依第26條所定辦法中有關環境用藥貯存或置放之數量、地點、使用藥劑種類、人員安全防護設備、污染防治措施之管理規定者，處新臺幣六萬元以上三十萬元以下罰鍰。",
 "Who prescribes the rules on storage, placement, quantities, locations, protective equipment and pollution control?",
 ["The central competent authority","The local competent authority","The industry competent authority","The businesses themselves, for record"],
 "Articles 26 and 48."),

(EA,"第27條",1,"環境用藥-標示核准",
 "環境用藥之標示，其使用或變更應如何辦理？其準則由何機關訂定？",
 ["應先經中央主管機關核准；標示之內容、方式及其他應遵行事項之準則，由中央主管機關定之",
  "應先報請直轄市縣市主管機關備查；標示之內容及方式，由地方主管機關分別訂定實施",
  "得由業者自行決定其標示內容及方式而無須經任何機關核准或備查即得逕行使用變更",
  "應先經同業公會審查通過；標示之內容、方式及應遵行事項，由同業公會研議後公告"],"a",
 "第27條第1項：環境用藥之標示，其使用或變更，應先經中央主管機關核准。第2項：前項標示之內容、方式及其他應遵行事項之準則，由中央主管機關定之。第49條第1款並規定違反第27條第1項規定者，處新臺幣三萬元以上十五萬元以下罰鍰，並得令其限期改善；屆期未改善或情節重大者，撤銷、廢止其許可證或許可執照。",
 "How must the use or change of an environmental agent label be handled?",
 ["Central competent authority approval must be obtained first; the rules on label content, format and other requirements are prescribed by the central authority",
  "A filing must first be made with the local competent authority; the label content and format are prescribed separately by each local competent authority",
  "Businesses may decide the label content and format themselves and use or change it without any approval or filing",
  "Trade association review must be passed first; the label content, format and requirements are drawn up and announced by the association"],
 "Articles 27 and 49."),

(EA,"第28條",1,"環境用藥-廢棄清除",
 "廢棄環境用藥及環境用藥容器之清除處理，應依何規定辦理？",
 ["依廢棄物清理有關法規規定辦理","依毒性化學物質管理有關法規辦理","依水污染防治有關法規規定辦理","由業者自行決定其清除處理方式"],"a",
 "第28條：廢棄環境用藥及環境用藥容器之清除處理，依廢棄物清理有關法規規定辦理。第35條第1款並規定經封存之環境用藥、物品經主管機關認定為廢棄物者，應依廢棄物清理有關法規之規定處理；第41條並規定依本法查扣或沒入之環境用藥需為適當處理時，其費用由原製造、加工、輸入或販賣者負擔。",
 "Under which rules are waste environmental agents and their containers cleared and treated?",
 ["Under the waste disposal laws and regulations","Under the toxic chemical substances control laws","Under the water pollution control laws and regulations","At the business's own discretion as to method"],
 "Articles 28, 35 and 41."),

(EA,"第29條",2,"環境用藥-微生物製劑",
 "環境用藥微生物製劑得使用於何處？其運作申請、紀錄等事項之辦法由何機關訂定？",
 ["得使用於各生態、水源等保育或保護區；其運作申請、紀錄及其他應遵行事項之辦法，由中央主管機關定之",
  "一律不得使用於各生態、水源等保育或保護區；縱經中央主管機關核准亦同，違者應撤銷其許可證",
  "得使用於各生態、水源等保育或保護區；其運作申請及紀錄等事項，由當地保護區管理機關逕行核定",
  "僅得使用於已開發之都市計畫地區；其運作申請及紀錄等事項之辦法，由目的事業主管機關訂定之"],"a",
 "第29條：環境用藥微生物製劑得使用於各生態、水源等保育或保護區；其運作申請、紀錄及其他應遵行事項之辦法，由中央主管機關定之。第48條第3款並規定違反依第29條所定辦法中有關環境用藥微生物製劑運作申請、使用數量限制、紀錄及紀錄保存之管理規定者，處新臺幣六萬元以上三十萬元以下罰鍰。",
 "Where may microbial environmental agent preparations be used, and who sets the rules?",
 ["They may be used in ecological, water source and other conservation or protection areas; the rules on operation applications, records and other requirements are set by the central authority",
  "They may never be used in ecological, water source or other conservation or protection areas, even with central approval, and breach means revocation of the permit",
  "They may be used in ecological, water source and other conservation or protection areas; the operation application and record rules are settled by the local protected area authority",
  "They may be used only in developed urban planning areas; the rules on operation applications and records are prescribed by the industry authority"],
 "Articles 29 and 48."),

(EA,"第30條",2,"環境用藥-遺傳工程",
 "以遺傳工程或其他技術改造微生物個體從事環境用藥微生物製劑開發試驗研究，應如何辦理？",
 ["應向中央主管機關提出申請；其申請條件、程序、緊急應變、紀錄及其他應遵行事項之辦法，由中央主管機關定之",
  "應向目的事業主管機關提出申請；其申請條件、程序及紀錄等事項之辦法，由該目的事業主管機關定之",
  "應向直轄市縣市主管機關報備即可；其申請條件及程序，由各地方主管機關依轄內情形分別訂定之",
  "無須向任何機關提出申請或報備；惟應於試驗研究完成後將結果送請中央主管機關備查並公開發表"],"a",
 "第30條：以遺傳工程或其他技術改造微生物個體或其新陳代謝產物，從事環境用藥微生物製劑開發試驗研究，應向中央主管機關提出申請；其申請條件、程序、緊急應變、紀錄及其他應遵行事項之辦法，由中央主管機關定之。第48條第4款並規定違反依第30條所定辦法有關申請、試驗場所物理性及生物性防護緊急應變、紀錄及紀錄保存、紀錄提報之管理規定者，處新臺幣六萬元以上三十萬元以下罰鍰。",
 "How must research on genetically modified microbial preparations be handled?",
 ["An application must be made to the central competent authority; the rules on application conditions, procedures, emergency response, records and other requirements are set by the central authority",
  "An application must be made to the relevant industry authority; the rules on application conditions, procedures, records and other requirements are prescribed by that industry authority itself",
  "A filing with the local competent authority suffices; the application conditions and procedures are prescribed separately by each local authority for its area",
  "No application or filing to any authority is needed; the results need only be filed with the central authority and published after the research is completed"],
 "Articles 30 and 48."),
# ---END---
]
