# -*- coding: utf-8 -*-
# 第 11 批（F1）：壓力容器安全檢查構造標準 第1條～第32條（補題）
PV = "OSH-72"
Q = [
(PV,"第1條",1,"壓力容器標準-授權依據",
 "壓力容器安全檢查構造標準之訂定依據為何？",
 ["依職業安全衛生法第六條第三項及第十六條第四項規定訂定","依職業安全衛生法第五條第二項及第十五條第三項規定訂定","依勞動檢查法第八條第一項及第二十條第二項規定訂定之","依職業安全衛生設施規則第四條及第十八條第二項規定訂定"],"a",
 "第1條：本標準依據職業安全衛生法第六條第三項及第十六條第四項訂定之。前者為必要安全衛生設備及措施之授權，後者為危險性設備檢查之授權。第76條並定明本標準自發布日施行，修正條文自一百零三年七月三日施行。",
 "Which provisions are cited as the legal basis of this Standard?",
 ["Article 6-3 and Article 16-4 of the Occupational Safety and Health Act","Article 5-2 and Article 15-3 of the Occupational Safety and Health Act","Article 8-1 and Article 20-2 of the Labor Inspection Act and its rules","Article 4 and Article 18-2 of the OSH Facilities Rules issued under it"],
 "Article 1 cites Articles 6-3 and 16-4 of the OSH Act as enabling provisions."),

(PV,"第2條",2,"壓力容器標準-定義",
 "本標準所稱第一種壓力容器及第二種壓力容器，係如何界定？",
 ["指鍋爐及壓力容器安全規則第四條第一項第一款、第二款規定者；第一種不包括小型壓力容器","指鍋爐及壓力容器安全規則第五條第二項第一款、第三款規定者；第二種不包括小型壓力容器","指危險性機械及設備安全檢查規則第三條第一款、第二款規定者；第一種包括小型壓力容器","指鍋爐及壓力容器安全規則第六條第一項第二款、第四款規定者；二者均包括小型壓力容器"],"a",
 "第2條第1款、第2款：第一種壓力容器指鍋爐及壓力容器安全規則第四條第一項第一款規定者，但不包括小型壓力容器；第二種壓力容器指同條項第二款規定者。第二章規範第一種壓力容器，第三章第75條則定明第二章規定於第二種壓力容器準用之。",
 "How are Class 1 and Class 2 pressure vessels defined in this Standard?",
 ["By Article 4-1 subparagraphs 1 and 2 of the Boiler and Pressure Vessel Rules; Class 1 excludes small vessels","By Article 5-2 subparagraphs 1 and 3 of the Boiler and Pressure Vessel Rules; Class 2 excludes small vessels","By Article 3 subparagraphs 1 and 2 of the Dangerous Machinery Inspection Rules; Class 1 includes small ones","By Article 6-1 subparagraphs 2 and 4 of the Boiler and Pressure Vessel Rules; both of them include small ones"],
 "Article 2, subparagraphs 1 and 2."),

(PV,"第2條",1,"壓力容器標準-定義",
 "本標準用詞中，MPa 及最小厚度分別代表何意義？",
 ["MPa 為壓力單位百萬帕斯卡；最小厚度指依本標準算得之安全強度所必要之材料厚度","MPa 為壓力單位千帕斯卡；最小厚度指扣除腐蝕裕度後實際量測所得之材料厚度值","MPa 為應力單位每平方公尺牛頓；最小厚度指材料出廠時標稱厚度之百分之九十","MPa 為壓力單位百萬巴斯卡；最小厚度指水壓試驗後量得之受壓部最薄處之厚度"],"a",
 "第2條第3款、第4款：MPa 為壓力單位百萬帕斯卡；最小厚度指依本標準規定算得之安全強度所必要之材料厚度。第11條並規定管之厚度應在最小厚度以上，管以外部分得減零點二五毫米或減標稱厚度百分之六中較小之值。",
 "What do MPa and minimum thickness mean under this Standard?",
 ["MPa is the pressure unit megapascal; minimum thickness is that needed for the strength computed hereunder","MPa is the pressure unit kilopascal; minimum thickness is the measured value after deducting corrosion","MPa is a stress unit of newton per square metre; minimum thickness is ninety percent of the nominal one","MPa is the pressure unit megabar; minimum thickness is the thinnest measured value after the water test"],
 "Article 2, subparagraphs 3 and 4."),

(PV,"第3條",2,"壓力容器標準-材料",
 "第一種壓力容器之主要材料，應具備何種條件？",
 ["應為鋼鐵材料或非鐵系金屬材料，並具對應最高使用壓力及溫度之安全化學成分及機械性質","應為鋼鐵材料或高分子複合材料，並具對應最低使用壓力及溫度之安全化學成分及物理性質","應為非鐵系金屬材料或陶瓷材料，並具對應水壓試驗壓力及溫度之安全成分及機械性質","應為鑄鐵材料或非金屬襯裡材料，並具對應常用操作壓力及溫度之安全成分及機械性質"],"a",
 "第3條：第一種壓力容器之主要材料應為鋼鐵材料或非鐵系金屬材料，且各該材料對應最高使用壓力及最高使用溫度所引起之化學性、物理性影響，應具有安全上之化學成分及機械性質。第4條並定明不得使用附表一規定之材料。",
 "What must the main material of a Class 1 pressure vessel satisfy?",
 ["Steel or non-ferrous metal, with safe chemical composition and mechanical properties for max pressure and temperature","Steel or polymer composite, with safe chemical composition and physical properties for min pressure and temperature","Non-ferrous metal or ceramic, with safe composition and mechanical properties for the hydrostatic test pressure","Cast iron or non-metallic lining, with safe composition and mechanical properties for normal operating pressure"],
 "Article 3; see also Article 4 on prohibited materials."),

(PV,"第4條",1,"壓力容器標準-材料",
 "關於第一種壓力容器受壓部分之材料使用限制，本標準如何規定？",
 ["第一種壓力容器或其受壓部分，不得使用附表一所規定之材料","第一種壓力容器或其受壓部分，得經檢查機構同意使用附表一材料","第一種壓力容器之受壓部分，僅限使用附表一所列舉之各項材料","第一種壓力容器之非受壓部分，不得使用附表一所規定之各項材料"],"a",
 "第4條：第一種壓力容器或第一種壓力容器之受壓部分，不得使用附表一規定之材料。第75條規定第二章於第二種壓力容器準用，但不包括第四條附表一第二款至第四款之規定。",
 "How does the Standard restrict materials for Class 1 pressure vessels?",
 ["A Class 1 vessel or its pressure part may not use the materials listed in Table 1","A Class 1 vessel or its pressure part may use Table 1 materials if the agency agrees","The pressure part of a Class 1 vessel may only use materials enumerated in Table 1","The non-pressure part of a Class 1 vessel may not use materials listed in Table 1"],
 "Article 4; Article 75 partially excludes Table 1 for Class 2 vessels."),

(PV,"第6條",3,"壓力容器標準-鑄造件",
 "鑄鐵件之容許抗拉應力應如何取值？",
 ["FCD四○○、FCD四五○等取使用溫度抗拉強度之六點二五分之一；其他鑄鐵件取十分之一","FCD四○○、FCD四五○等取使用溫度抗拉強度之四分之一；其他鑄鐵件取六點二五分之一","FCD四○○、FCD四五○等取使用溫度抗拉強度之十分之一；其他鑄鐵件取六點二五分之一","FCD四○○、FCD四五○等取常溫降伏點之一點五分之一；其他鑄鐵件取一點二五分之一"],"a",
 "第6條第1款：黑心展性鑄鐵件、球狀石墨鑄鐵件之 FCD四○○、FCD四五○及同等以上者，取材料於使用溫度時抗拉強度之六點二五分之一；其他鑄鐵件取十分之一。同條第2款、第3款另定鑄鋼件及非鐵系金屬鑄造件之鑄造係數。",
 "How is the allowable tensile stress of cast iron parts determined?",
 ["FCD400 and FCD450 take one sixth-point-two-five of tensile strength at service temperature; others one tenth","FCD400 and FCD450 take one quarter of tensile strength at service temperature; others one sixth-point-two-five","FCD400 and FCD450 take one tenth of tensile strength at service temperature; others one sixth-point-two-five","FCD400 and FCD450 take one one-point-five of the yield point at normal temperature; others one one-point-two-five"],
 "Article 6, subparagraph 1."),

(PV,"第6條",3,"壓力容器標準-鑄造件",
 "鑄鋼件容許抗拉應力所應乘之鑄造係數，依規定分別為多少？",
 ["符合 CNS 二九○六等規定者零點八；經附表三檢查合格者零點九或一；其他鑄鋼件零點六七","符合 CNS 二九○六等規定者零點六七；經附表三檢查合格者零點八；其他鑄鋼件零點五○","符合 CNS 二九○六等規定者零點九；經附表三檢查合格者一點二五；其他鑄鋼件零點八○","符合 CNS 二九○六等規定者一點○○；經附表三檢查合格者零點八；其他鑄鋼件零點九○"],"a",
 "第6條第2款：碳鋼鑄鋼件化學成分在附表二規定值以下者及熔接結構用、不銹鋼、高溫高壓用、低溫高壓用鑄鋼件之鑄造係數為零點八；經依附表三檢查合格者依檢查種類及方法取零點九或一；其他鑄鋼件為零點六七。",
 "What casting factors apply to the allowable tensile stress of cast steel?",
 ["0.8 for parts meeting CNS 2906 and similar; 0.9 or 1 if inspected per Table 3; 0.67 for other cast steel","0.67 for parts meeting CNS 2906 and similar; 0.8 if inspected per Table 3; 0.50 for other cast steel parts","0.9 for parts meeting CNS 2906 and similar; 1.25 if inspected per Table 3; 0.80 for other cast steel parts","1.00 for parts meeting CNS 2906 and similar; 0.8 if inspected per Table 3; 0.90 for other cast steel parts"],
 "Article 6, subparagraph 2."),

(PV,"第6條",2,"壓力容器標準-鑄造件",
 "非鐵系金屬鑄造件之容許抗拉應力如何計算？",
 ["取一般材料規定算得之值，再乘以鑄造係數零點八所得之值","取一般材料規定算得之值，再乘以鑄造係數零點六七所得之值","取一般材料規定算得之值，再除以鑄造係數零點八所得之值","取一般材料規定算得之值之半，再乘以鑄造係數一點○所得之值"],"a",
 "第6條第3款：非鐵系金屬鑄造件之容許抗拉應力，取第五條第一項第一款算得之值乘以鑄造係數零點八所得之值。鑄鋼件則視標準別分取零點八、零點九、一或零點六七之鑄造係數。",
 "How is allowable tensile stress of non-ferrous metal castings computed?",
 ["Take the value computed under the general rule and multiply it by a casting factor of 0.8","Take the value computed under the general rule and multiply it by a casting factor of 0.67","Take the value computed under the general rule and divide it by a casting factor of 0.8","Take half the value computed under the general rule and multiply it by a factor of 1.0"],
 "Article 6, subparagraph 3."),

(PV,"第7條",3,"壓力容器標準-材料",
 "護面鋼之容許抗拉應力應如何計算？",
 ["以母材與合併材之容許抗拉應力各乘其厚度後相加，再除以兩者厚度之和","以母材與合併材之容許抗拉應力相加後，再除以兩者厚度相乘所得之值","以母材與合併材之容許抗拉應力取較大者，再乘以兩者厚度之比值計算","以母材容許抗拉應力乘以母材厚度，再減去合併材厚度所得之比值計算"],"a",
 "第7條：護面鋼之容許抗拉應力σa＝（σa1t1＋σa2t2）／（t1＋t2），即以母材與合併材之容許抗拉應力依其厚度加權平均。式中σa1、t1為母材之容許抗拉應力與厚度，σa2、t2為合併材之容許抗拉應力與厚度。",
 "How is the allowable tensile stress of clad steel calculated?",
 ["Multiply each stress by its own thickness, add them, then divide by the sum of the two thicknesses","Add the two allowable tensile stresses, then divide the sum by the product of the two thicknesses","Take the larger of the two allowable tensile stresses and multiply it by the ratio of thicknesses","Multiply the base metal stress by its thickness and subtract the thickness of the cladding metal"],
 "Article 7 gives a thickness-weighted average formula."),

(PV,"第8條",2,"壓力容器標準-容許應力",
 "材料之容許壓縮應力應如何取值？",
 ["鑄鐵以外材料取與容許抗拉應力相等之值；鑄鐵取容許抗拉應力二倍之值","鑄鐵以外材料取容許抗拉應力二倍之值；鑄鐵取與容許抗拉應力相等之值","鑄鐵以外材料取容許抗拉應力百分之八十之值；鑄鐵取其一點五倍之值","鑄鐵以外材料取容許抗拉應力一點五倍之值；鑄鐵取其百分之八十之值"],"a",
 "第8條：鑄鐵以外之材料，其容許壓縮應力取與容許抗拉應力相等之值；鑄鐵之容許壓縮應力則取容許抗拉應力二倍之值。第9條、第10條另定容許彎曲應力為一點五倍、容許剪應力為百分之八十。",
 "How is the allowable compressive stress of materials determined?",
 ["For materials other than cast iron it equals the allowable tensile stress; for cast iron it is twice that","For materials other than cast iron it is twice the allowable tensile stress; for cast iron it equals that","For materials other than cast iron it is eighty percent of the tensile value; for cast iron 1.5 times it","For materials other than cast iron it is 1.5 times the tensile value; for cast iron eighty percent of it"],
 "Article 8."),

(PV,"第9條",1,"壓力容器標準-容許應力",
 "材料之容許彎曲應力，原則上如何取值？",
 ["取容許抗拉應力之一點五倍之值","取容許抗拉應力之零點八倍之值","取容許壓縮應力之二點○倍之值","取容許剪應力之一點二五倍之值"],"a",
 "第9條第1項：材料之容許彎曲應力，取容許抗拉應力之一點五倍之值。同條第2項另規定使用溫度在潛變領域時，取與容許抗拉應力相等之值。",
 "How is the allowable bending stress of a material normally taken?",
 ["It is taken as 1.5 times the allowable tensile stress of the material","It is taken as 0.8 times the allowable tensile stress of the material","It is taken as 2.0 times the allowable compressive stress of material","It is taken as 1.25 times the allowable shear stress of the material"],
 "Article 9, paragraph 1."),

(PV,"第9條",3,"壓力容器標準-容許應力",
 "鋼鐵材料使用溫度在該材料潛變領域時，其容許彎曲應力如何處理？",
 ["取與容許抗拉應力相等之值，不適用一點五倍之原則規定","仍取容許抗拉應力之一點五倍，不因潛變領域而有差別","取容許抗拉應力之二倍之值，以確保潛變下之安全裕度","取容許剪應力之一點五倍之值，並另加一毫米腐蝕裕度"],"a",
 "第9條第2項：鋼鐵材料及非鐵系金屬材料之使用溫度在該材料潛變領域時之容許彎曲應力，取與容許抗拉應力相等之值，不受第一項一點五倍規定之限制。第5條第2項並定潛變領域之容許抗拉應力取法。",
 "In the creep range, how is allowable bending stress of steel taken?",
 ["It equals the allowable tensile stress, so the 1.5 times rule does not apply","It is still 1.5 times the allowable tensile stress, with no change in the rule","It is twice the allowable tensile stress to add margin under creep conditions","It is 1.5 times the allowable shear stress plus one millimetre of corrosion"],
 "Article 9, paragraph 2."),

(PV,"第10條",1,"壓力容器標準-容許應力",
 "材料之容許剪應力應如何取值？",
 ["取容許抗拉應力之百分之八十之值","取容許抗拉應力之百分之五十之值","取容許彎曲應力之百分之八十之值","取容許壓縮應力之百分之六十之值"],"a",
 "第10條：材料之容許剪應力，取容許抗拉應力之百分之八十之值。第28條並以容許彎曲應力及容許剪應力二者計算平型管板之最小厚度，取其較大值。",
 "How is the allowable shear stress of a material determined?",
 ["It is taken as eighty percent of the allowable tensile stress","It is taken as fifty percent of the allowable tensile stress","It is taken as eighty percent of the allowable bending stress","It is taken as sixty percent of allowable compressive stress"],
 "Article 10."),

(PV,"第11條",2,"壓力容器標準-構造",
 "管及管以外之部分，其厚度分別應符合何種規定？",
 ["管應在最小厚度以上；管以外部分應在最小厚度減零點二五毫米或減標稱厚度百分之六中較小之值以上","管應在最小厚度以上；管以外部分應在最小厚度減零點五毫米或減標稱厚度百分之十中較大之值以上","管應在最小厚度減零點二五毫米以上；管以外部分應在最小厚度減標稱厚度百分之六中較大之值以上","管應在最小厚度加零點二五毫米以上；管以外部分應在最小厚度加標稱厚度百分之六所得之值以上"],"a",
 "第11條：管之厚度應在最小厚度以上；管以外之部分，其厚度應在最小厚度減去零點二五毫米或減去標稱厚度百分之六之值中較小之值以上。第12條另定板厚下限，碳鋼及低合金鋼鋼板為二點五毫米以上。",
 "What thickness rules apply to pipes and to parts other than pipes?",
 ["Pipes at least the minimum thickness; other parts at least the minimum less 0.25 mm or 6% of nominal, whichever smaller","Pipes at least the minimum thickness; other parts at least the minimum less 0.5 mm or 10% of nominal, whichever larger","Pipes at least the minimum less 0.25 mm; other parts at least the minimum less 6% of nominal, whichever is larger","Pipes at least the minimum plus 0.25 mm; other parts at least the minimum plus 6% of the nominal thickness value"],
 "Article 11."),

(PV,"第13條",2,"壓力容器標準-構造",
 "胴體或其他承受壓力部分所使用板之腐蝕裕度，應為多少？有無例外？",
 ["應在一毫米以上；碳鋼及低合金鋼以外材料經驗實績認無腐蝕之虞者除外","應在二毫米以上；碳鋼及低合金鋼材料經驗實績認無腐蝕之虞者始除外","應在零點五毫米以上；非鐵系金屬材料經檢查機構認可者不受此限制","應在三毫米以上；高合金鋼鋼板經放射線透射試驗合格者不受此限制"],"a",
 "第13條：胴體或其他承受壓力部分所使用板之腐蝕裕度，應在一毫米以上；但碳鋼鋼料及低合金鋼鋼料以外之材料，依經驗實績認無腐蝕或磨耗之虞者，不在此限。第14條等計算最小厚度時均應加計腐蝕裕度。",
 "What corrosion allowance is required for plates of pressure parts?",
 ["At least one millimetre; materials other than carbon and low alloy steel with no corrosion risk are exempt","At least two millimetres; carbon and low alloy steel with proven no corrosion risk are the only exemption","At least half a millimetre; non-ferrous metal materials approved by the inspection agency are exempted","At least three millimetres; high alloy steel plates passing radiographic testing are exempt from this rule"],
 "Article 13."),

(PV,"第14條",2,"壓力容器標準-最小厚度",
 "內面承受壓力之圓筒胴體或球形胴體，其板之最小厚度如何決定？",
 ["取承受最高使用壓力時所生應力與容許抗拉應力相等之板厚，再加腐蝕裕度","取承受水壓試驗壓力時所生應力與容許彎曲應力相等之板厚，再加腐蝕裕度","取承受最高使用壓力三倍時所生應力與挫曲應力相等之板厚，再加腐蝕裕度","取承受最高使用壓力時所生應力與容許剪應力相等之板厚，再減去腐蝕裕度"],"a",
 "第14條：內面承受壓力之圓筒胴體或球形胴體之板，其最小厚度應取於承受最高使用壓力時，發生於該板之應力與該板之容許抗拉應力相等時之板厚加腐蝕裕度之厚度。第16條、第18條、第21條等均準用本條。",
 "How is the minimum plate thickness of an internally pressurised shell set?",
 ["The thickness at which stress under maximum working pressure equals allowable tensile stress, plus corrosion allowance","The thickness at which stress under hydrostatic test pressure equals allowable bending stress, plus corrosion allowance","The thickness at which stress under three times working pressure equals buckling stress, plus corrosion allowance","The thickness at which stress under maximum working pressure equals allowable shear stress, less corrosion allowance"],
 "Article 14, applied by reference in several later articles."),

(PV,"第15條",3,"壓力容器標準-最小厚度",
 "外面承受壓力之圓筒胴體與球形胴體，其板之最小厚度分別以最高使用壓力之幾倍計算？",
 ["圓筒胴體以三倍之壓力計算，球形胴體以四倍之壓力計算，均再加腐蝕裕度","圓筒胴體以四倍之壓力計算，球形胴體以三倍之壓力計算，均再加腐蝕裕度","圓筒胴體以一點五倍壓力計算，球形胴體以二倍之壓力計算，均再加腐蝕裕度","圓筒胴體以二倍之壓力計算，球形胴體以二點五倍壓力計算，均再減腐蝕裕度"],"a",
 "第15條：外面承受壓力之圓筒胴體之板，取承受最高使用壓力三倍之壓力時所生應力與挫曲應力相等之板厚加腐蝕裕度；球形胴體則以最高使用壓力四倍之壓力計算。第17條、第26條之圓錐體並準用第一項規定。",
 "What pressure multiples apply to externally pressurised cylindrical and spherical shells?",
 ["Three times working pressure for cylindrical and four times for spherical shells, plus corrosion allowance","Four times working pressure for cylindrical and three times for spherical shells, plus corrosion allowance","One-and-a-half times for cylindrical and two times for spherical shells, plus the corrosion allowance too","Two times for cylindrical and two-and-a-half times for spherical shells, less the corrosion allowance value"],
 "Article 15, paragraphs 1 and 2."),

(PV,"第15條",2,"壓力容器標準-最小厚度",
 "外面承受壓力之板，其最小厚度所比較之應力為何？",
 ["為該板發生挫曲時之應力，與所生應力相等時之板厚再加腐蝕裕度","為該板之容許抗拉應力，與所生應力相等時之板厚再加腐蝕裕度","為該板之容許彎曲應力，與所生應力相等時之板厚再減腐蝕裕度","為該板容許剪應力之半，與所生應力相等時之板厚再加腐蝕裕度"],"a",
 "第15條：外面承受壓力者係以該板發生挫曲時之應力為比較基準，與內面承受壓力以容許抗拉應力為基準（第14條）不同，並均應加腐蝕裕度。",
 "Which stress is compared for externally pressurised plates?",
 ["The buckling stress of the plate; thickness at equality plus the corrosion allowance","The allowable tensile stress of the plate; thickness at equality plus corrosion allowance","The allowable bending stress of the plate; thickness at equality less corrosion allowance","Half the allowable shear stress of the plate; thickness at equality plus that allowance"],
 "Article 15 uses buckling stress, unlike Article 14."),

(PV,"第16條",2,"壓力容器標準-最小厚度",
 "內面承受壓力之圓錐胴體，其板之最小厚度及與圓筒胴體之裝接應如何辦理？",
 ["最小厚度準用內面承壓圓筒胴體規定；裝接方法應使裝接部具安全所必要之強度","最小厚度準用外面承壓圓筒胴體規定；裝接方法應使裝接部具安全所必要之強度","最小厚度準用平型端板之相關規定；裝接部並應全部實施放射線透射試驗合格","最小厚度準用牽條支撐板之相關規定；裝接部並應加厚至八毫米以上以為補強"],"a",
 "第16條：內面承受壓力之圓錐胴體之板之最小厚度，準用第十四條規定；圓錐胴體裝接於圓筒胴體者，其裝接方法應使裝接部具有安全所必要之強度。第17條另定外面承壓者準用第十五條第一項。",
 "How are thickness and attachment handled for internally pressurised conical shells?",
 ["Thickness follows the internally pressurised cylindrical rule; the joint must have the strength needed for safety","Thickness follows the externally pressurised cylindrical rule; the joint must have the strength needed for safety","Thickness follows the flat end plate rule; the whole joint must also pass full radiographic testing before use","Thickness follows the stayed plate rule; the joint must also be thickened to at least eight millimetres for it"],
 "Article 16."),

(PV,"第17條",1,"壓力容器標準-最小厚度",
 "外面承受壓力之圓錐胴體，其板之最小厚度依何規定辦理？",
 ["準用外面承受壓力之圓筒胴體板最小厚度規定","準用內面承受壓力之圓筒胴體板最小厚度規定","準用外面承受壓力之球形胴體板最小厚度規定","準用未以牽條支撐平板之最小厚度相關規定"],"a",
 "第17條：外面承受壓力之圓錐胴體之板之最小厚度，準用第十五條第一項規定，即以最高使用壓力三倍之壓力計算挫曲並加腐蝕裕度。第26條之圓錐體型端板亦同。",
 "Which rule governs externally pressurised conical shell thickness?",
 ["The rule for externally pressurised cylindrical shell plates applies","The rule for internally pressurised cylindrical shell plates applies","The rule for externally pressurised spherical shell plates applies","The rule for unstayed flat plate minimum thickness applies instead"],
 "Article 17 applies Article 15, paragraph 1."),

(PV,"第18條",2,"壓力容器標準-最小厚度",
 "內面及外面承受壓力之管，其最小厚度分別準用何項規定？",
 ["內面承壓者準用內面承壓圓筒胴體規定；外面承壓者準用外面承壓圓筒胴體規定","內面承壓者準用外面承壓圓筒胴體規定；外面承壓者準用內面承壓圓筒胴體規定","內面承壓者準用球形胴體之相關規定；外面承壓者準用平型端板最小厚度規定","內面及外面承壓者均準用外面承壓球形胴體以四倍壓力計算最小厚度之規定"],"a",
 "第18條第1項、第2項：內面承受壓力之管之最小厚度準用第十四條規定；外面承受壓力之管之最小厚度準用第十五條第一項規定。同條第3項至第5項另定 U 字型管彎曲半徑及螺紋部管厚。",
 "Which rules apply to the minimum thickness of internally and externally pressurised pipes?",
 ["Internally pressurised follows the internal cylindrical shell rule; externally pressurised the external one","Internally pressurised follows the external cylindrical shell rule; externally pressurised the internal one","Internally pressurised follows the spherical shell rule; externally pressurised the flat end plate rule","Both internally and externally pressurised pipes follow the four times pressure spherical shell rule only"],
 "Article 18, paragraphs 1 and 2."),

(PV,"第18條",2,"壓力容器標準-最小厚度",
 "U 字型管之中心線應符合何項要求？",
 ["應有不致使該 U 字型管發生過剩應力集中之彎曲半徑","應有不致使該 U 字型管發生振動共振之最小直線長度","應有使該 U 字型管腐蝕裕度增為二毫米以上之厚度","應有使該 U 字型管彎曲半徑小於管外徑一半之設計"],"a",
 "第18條第3項：U 字型管之中心線，應有不致使該 U 字型管發生過剩應力集中之彎曲半徑。第20條就端板、第27條就夾套封閉部亦有避免過剩應力集中形狀之要求。",
 "What is required of the centre line of a U-shaped tube?",
 ["A bend radius that avoids excessive stress concentration in the tube","A minimum straight length that avoids vibration resonance in the tube","A thickness that raises the corrosion allowance to two millimetres or more","A bend radius smaller than half of the outside diameter of the tube itself"],
 "Article 18, paragraph 3."),

(PV,"第18條",3,"壓力容器標準-最小厚度",
 "於管之端部切削螺紋時，該螺紋部之管厚應如何計算？",
 ["應取依規定所得之管最小厚度，再加上螺紋高度之值","應取依規定所得之管最小厚度，再減去螺紋高度之值","應取依規定所得之管最小厚度，再加上腐蝕裕度一毫米","應取依規定所得之管最小厚度之一點五倍所得之數值"],"a",
 "第18條第4項、第5項：於管之端部切削螺紋時，內面承受壓力者，螺紋部之管厚應取第一項所定管最小厚度加螺紋高度之值；外面承受壓力者，則取第二項所定最小厚度加螺紋高度之值。",
 "How is pipe thickness at a threaded end calculated?",
 ["Take the minimum pipe thickness required and add the height of the thread","Take the minimum pipe thickness required and subtract the height of thread","Take the minimum pipe thickness required and add one millimetre for corrosion","Take one-and-a-half times the minimum pipe thickness otherwise required here"],
 "Article 18, paragraphs 4 and 5."),

(PV,"第19條",1,"壓力容器標準-端板",
 "全半球型端板以外之端板，其厚度應符合何項規定？",
 ["應在無縫胴體板之最小厚度以上","應在無縫胴體板最小厚度之半以上","應在熔接胴體板最小厚度之八成以上","應在管之最小厚度加螺紋高度以上"],"a",
 "第19條：全半球型端板以外之端板之厚度，應在無縫胴體板之最小厚度以上。第20條並要求端板應有不致發生過剩應力集中之形狀。",
 "What thickness must end plates other than hemispherical ones have?",
 ["At least the minimum thickness of a seamless shell plate","At least half the minimum thickness of a seamless shell","At least eighty percent of a welded shell plate minimum","At least the pipe minimum thickness plus the thread height"],
 "Article 19."),

(PV,"第20條",1,"壓力容器標準-端板",
 "端板之形狀應符合何項要求？",
 ["應有不致使其發生過剩應力集中之形狀","應有便於裝設安全閥及壓力表之平面形狀","應為全半球型或碟型，不得採用平型端板","應有可供設置人孔及清掃孔之凹面形狀"],"a",
 "第20條：端板應有不致使其發生過剩應力集中之形狀。第22條並要求未補強之孔設置於端板時，不得使人孔周圍及端板彎緣部發生過剩應力集中。",
 "What shape requirement applies to end plates?",
 ["A shape that does not cause excessive stress concentration","A flat shape convenient for fitting safety valves and gauges","A hemispherical or dished shape only, flat plates being barred","A concave shape allowing manholes and cleaning holes to be set"],
 "Article 20."),

(PV,"第21條",2,"壓力容器標準-端板",
 "中低面承受壓力且形成球面部分未以牽條支撐之端板，其最小厚度如何決定？",
 ["準用內面承受壓力圓筒或球形胴體板最小厚度之規定辦理","準用外面承受壓力圓筒胴體板最小厚度之規定辦理即可","取該端板凸緣部內徑百分之一與八毫米中之較大值辦理","準用以牽條支撐之板應在八毫米以上之厚度規定辦理即可"],"a",
 "第21條：中低面承受壓力之端板，且形成球面之部分未以牽條支撐者，其最小厚度準用第十四條規定，即以容許抗拉應力為基準加腐蝕裕度。中高面承受壓力者則依第24條、鑄鐵製者依第25條辦理。",
 "How is thickness set for a concave-pressurised unstayed spherical end plate?",
 ["It follows the rule for internally pressurised cylindrical or spherical shell plates","It follows the rule for externally pressurised cylindrical shell plates without change","It takes the larger of one percent of the flange inside diameter and eight millimetres","It follows the rule requiring stayed plates to be at least eight millimetres in thickness"],
 "Article 21 applies Article 14."),

(PV,"第22條",2,"壓力容器標準-端板",
 "將未補強之孔設置於端板時，應以何種方法設置？",
 ["以不致使人孔周圍及端板彎緣部發生過剩應力集中之方法設置","以使人孔周圍加厚至一點五倍並實施止漏熔接之方法設置之","以將孔徑限制在九十毫米以下並以螺紋旋裝之方法設置之","以在孔周邊全部實施磁粉探傷試驗合格後再開孔之方法設置"],"a",
 "第22條：將第三十五條但書規定之未補強之孔設置於端板時，應以不致使人孔周圍及端板彎緣部發生過剩應力集中之方法設置。第35條原則要求孔應以具充分強度之補強材補強。",
 "How must an unreinforced hole in an end plate be provided?",
 ["In a way that avoids excessive stress concentration around the manhole and knuckle","In a way that thickens the manhole area 1.5 times and adds seal welding around it","In a way that limits hole diameter to ninety millimetres and uses a screwed joint","In a way that magnetic particle tests the whole hole edge before it is cut open"],
 "Article 22, read with the proviso in Article 35."),

(PV,"第23條",3,"壓力容器標準-端板",
 "內面承受壓力之圓錐體型端板設有鎖緊螺栓用凸緣者，其最小厚度及與胴體之接合應如何辦理？",
 ["最小厚度準用內面承壓胴體板規定；接合應以使裝接部具安全必要強度之方法為之","最小厚度準用外面承壓胴體板規定；接合應以使裝接部具安全必要強度之方法為之","最小厚度準用平型管板之相關規定；接合部並應全長實施放射線透射試驗合格","最小厚度取凸緣部內徑百分之一計算；接合部並應實施熔接後熱處理始得裝接"],"a",
 "第23條：內面承受壓力之圓錐體型端板及中低面承受壓力之碟型蓋板設有鎖緊螺栓用之凸緣者，該端板部分之最小厚度準用第十四條規定；圓錐體型端板接合於胴體時，應以能使其裝接部具有安全所必要強度之方法裝接。",
 "What rules govern a bolted-flange conical end plate under internal pressure?",
 ["Thickness follows the internally pressurised shell rule; the joint must have the strength needed for safety","Thickness follows the externally pressurised shell rule; the joint must have the strength needed for safety","Thickness follows the flat tube sheet rule; the whole joint must also pass full radiographic testing first","Thickness is one percent of the flange inside diameter; the joint must be post-weld heat treated as well"],
 "Article 23."),

(PV,"第24條",3,"壓力容器標準-端板",
 "構成球面之一部且未以牽條支撐之端板，中高面承受壓力時之最小厚度如何決定？",
 ["取視同中低面承壓所得厚度乘一點六七加腐蝕裕度，與四倍壓力挫曲厚度加腐蝕裕度中較大者","取視同中低面承壓所得厚度乘一點二五加腐蝕裕度，與三倍壓力挫曲厚度加腐蝕裕度中較小者","取視同中低面承壓所得厚度乘二點○○加腐蝕裕度，與二倍壓力挫曲厚度加腐蝕裕度中較大者","取視同中低面承壓所得厚度乘一點五○加腐蝕裕度，與四倍壓力挫曲厚度減腐蝕裕度中較小者"],"a",
 "第24條：構成球面之一部且未以牽條支撐之端板，中高面承受壓力時之最小厚度，取下列較大值：一、視同中低面承受最高使用壓力時應力與容許抗拉應力相等之端板厚度乘一點六七加腐蝕裕度；二、以中高面承受最高使用壓力四倍壓力時挫曲厚度加腐蝕裕度。但鑄鐵製端板依第25條辦理。",
 "How is thickness set for a convex-pressurised unstayed spherical end plate?",
 ["The larger of 1.67 times the concave-side thickness plus allowance, and the four times pressure buckling value","The smaller of 1.25 times the concave-side thickness plus allowance, and the three times pressure buckling value","The larger of 2.00 times the concave-side thickness plus allowance, and the two times pressure buckling value","The smaller of 1.50 times the concave-side thickness plus allowance, and four times pressure buckling less it"],
 "Article 24, subparagraphs 1 and 2."),

(PV,"第24條",2,"壓力容器標準-端板",
 "構成球面一部之端板中高面承壓最小厚度之計算規定，對何種材質之端板不適用？",
 ["鑄鐵製端板不適用，另依其凸緣部內徑百分之一等規定計算","鑄鋼製端板不適用，另依其凸緣部內徑百分之五等規定計算","沃斯田鐵系不銹鋼端板不適用，另依熔接接頭效率規定計算","非鐵系金屬製端板不適用，另依鑄造係數零點八之規定計算"],"a",
 "第24條但書：鑄鐵製端板不適用該條計算方式。第25條另定鑄鐵製端板取視同中低面承壓時之最小厚度與端板凸緣部內徑百分之一之較大值。",
 "Which end plates are excluded from the Article 24 convex-side calculation?",
 ["Cast iron end plates are excluded and use the one percent flange diameter rule","Cast steel end plates are excluded and use the five percent flange diameter rule","Austenitic stainless end plates are excluded and use the joint efficiency rule","Non-ferrous metal end plates are excluded and use the 0.8 casting factor rule"],
 "Article 24 proviso, with Article 25."),

(PV,"第25條",2,"壓力容器標準-端板",
 "鑄鐵製且未以牽條支撐、構成球面一部之端板，中高面承受壓力時之最小厚度如何取？",
 ["取視同中低面承壓時之最小厚度與端板凸緣部內徑百分之一，二者中之較大值","取視同中低面承壓時之最小厚度與端板凸緣部內徑百分之一，二者中之較小值","取視同中低面承壓時之最小厚度與端板凸緣部外徑百分之五，二者中之較大值","取視同中低面承壓時最小厚度乘一點六七與凸緣部內徑百分之十中之較大值"],"a",
 "第25條：構成球面之一部且未以牽條支撐之鑄鐵製端板，其中高面承受壓力時之最小厚度，就該端板視同中低面承受壓力時之最小厚度與該端板凸緣部內徑之百分之一之值，取二者中較大之值。",
 "How is a cast iron convex-pressurised spherical end plate thickness taken?",
 ["The larger of the concave-side minimum thickness and one percent of the flange inside diameter","The smaller of the concave-side minimum thickness and one percent of the flange inside diameter","The larger of the concave-side minimum thickness and five percent of the flange outside diameter","The larger of 1.67 times that thickness and ten percent of the flange inside diameter of the plate"],
 "Article 25."),

(PV,"第26條",1,"壓力容器標準-端板",
 "外面承受壓力之圓錐體型端板，其最小厚度依何規定辦理？",
 ["準用外面承受壓力圓筒胴體以三倍壓力計算之規定","準用外面承受壓力球形胴體以四倍壓力計算之規定","準用內面承受壓力圓筒胴體以最高使用壓力之規定","準用中高面承受壓力端板乘一點六七倍之厚度規定"],"a",
 "第26條：外面承受壓力之圓錐體型端板之最小厚度，準用第十五條第一項規定，即以最高使用壓力三倍之壓力計算挫曲並加腐蝕裕度。",
 "Which rule sets the thickness of an externally pressurised conical end plate?",
 ["The externally pressurised cylindrical shell rule using three times pressure","The externally pressurised spherical shell rule using four times the pressure","The internally pressurised cylindrical shell rule using the working pressure","The convex-side end plate rule multiplying the thickness by 1.67 times over it"],
 "Article 26 applies Article 15, paragraph 1."),

(PV,"第27條",2,"壓力容器標準-平板",
 "平型端板、平型蓋板及未以牽條支撐之平板，其最小厚度準用何規定？夾套封閉部另有何要求？",
 ["準用內面承壓胴體板最小厚度規定；夾套封閉部應有不致過剩應力集中之形狀","準用外面承壓胴體板最小厚度規定；夾套封閉部應有不致過剩應力集中之形狀","準用以牽條支撐板八毫米以上之規定；夾套封閉部應全長實施超音波探傷試驗","準用平型管板容許剪應力之相關規定；夾套封閉部應加設伸縮接頭以吸收應力"],"a",
 "第27條：平型端板、平型蓋板、平型底板等未以牽條支撐之平板及將夾套熔接於胴體時之夾套封閉部，其最小厚度準用第十四條規定；該夾套封閉部並應有不致使其發生過剩應力集中之形狀。",
 "Which rules govern flat unstayed plates and jacket closures?",
 ["Thickness follows the internally pressurised shell rule; the jacket closure must avoid stress concentration","Thickness follows the externally pressurised shell rule; the jacket closure must avoid stress concentration","Thickness follows the eight millimetre stayed plate rule; the jacket closure needs full ultrasonic testing","Thickness follows the flat tube sheet shear rule; the jacket closure needs an expansion joint to absorb it"],
 "Article 27."),

(PV,"第28條",3,"壓力容器標準-管板",
 "熱交換器未以管牽條支撐之平型管板，其最小厚度如何決定？",
 ["取應力與容許彎曲應力相等及與容許剪應力相等所得二厚度加腐蝕裕度中較大者","取應力與容許抗拉應力相等及與容許壓縮應力相等所得二厚度加腐蝕裕度中較小者","取應力與容許彎曲應力相等所得厚度乘一點六七，再加腐蝕裕度一毫米之數值","取應力與容許剪應力相等所得厚度之半，再加標稱厚度百分之六所得之數值計"],"a",
 "第28條第1項：熱交換器及其類似設備之未以管牽條支撐之平型管板及具有平型蓋板功能之平型管板，其最小厚度取承受最高使用壓力時應力與容許彎曲應力相等之厚度加腐蝕裕度，及與容許剪應力相等之厚度加腐蝕裕度，二者中之較大值。",
 "How is the minimum thickness of an unstayed flat tube sheet determined?",
 ["The larger of the thicknesses where stress equals allowable bending and allowable shear stress, plus allowance","The smaller of the thicknesses where stress equals allowable tensile and compressive stress, plus allowance","The thickness where stress equals allowable bending stress times 1.67, plus one millimetre of allowance too","Half the thickness where stress equals allowable shear stress, plus six percent of the nominal thickness"],
 "Article 28, paragraph 1."),

(PV,"第28條",1,"壓力容器標準-管板",
 "將管裝設於平型管板時，應如何實施？",
 ["應採取使其接合部具有安全所必要強度之方法實施","應採取以螺紋旋裝並加設止漏熔接之方法實施之","應採取使其接合部厚度達八毫米以上之方法實施","應採取先實施熔接後熱處理再裝設管之方法實施"],"a",
 "第28條第2項：將管裝設於平型管板時，應採取使其接合部具有安全所必要強度之方法實施。第16條、第23條、第30條就圓錐胴體、端板及牽條之裝接亦有相同意旨之規定。",
 "How must tubes be fitted into a flat tube sheet?",
 ["By a method giving the joint the strength necessary for safety","By a screwed connection together with seal welding at the joint","By a method making the joint at least eight millimetres thick","By post-weld heat treating the sheet before the tubes are fitted"],
 "Article 28, paragraph 2."),

(PV,"第29條",3,"壓力容器標準-熱交換器",
 "二管板固定式熱交換器於何種情形應設置伸縮接頭？該接頭並應確認何事項？",
 ["胴體及管之伸縮致所生應力分別超過各該容許應力時；應確認具疲勞強度之安全性","胴體及管之伸縮致所生應力達各該容許應力之半時；應確認具抗腐蝕性能之安全性","最高使用壓力超過一 MPa 且管板厚度不足時；應確認具放射線透射試驗之合格性","管板未以管牽條支撐且管數超過一百支時；應確認其熔接接頭效率達百分之八十五"],"a",
 "第29條：二管板固定式熱交換器因其胴體及管之伸縮狀態，致在胴體及管所生之應力值分別超過各該容許應力者，應在其胴體設置伸縮接頭；伸縮接頭並應確認具有疲勞強度之安全性。",
 "When must a fixed double tube sheet exchanger have an expansion joint?",
 ["When shell and tube expansion makes the stresses exceed their allowable values; fatigue safety must be confirmed","When shell and tube expansion makes the stresses reach half the allowable values; corrosion safety is confirmed","When working pressure exceeds one MPa and the tube sheet is too thin; radiographic acceptance is confirmed","When the sheet is unstayed and there are over one hundred tubes; joint efficiency of 85 percent is confirmed"],
 "Article 29."),

(PV,"第30條",3,"壓力容器標準-牽條",
 "牽條之斷面積應達何種標準？",
 ["應在所生應力與容許抗拉應力除以一點一所得值相等時之斷面積以上","應在所生應力與容許抗拉應力乘以一點一所得值相等時之斷面積以上","應在所生應力與容許彎曲應力除以一點五所得值相等時之斷面積以上","應在所生應力與容許剪應力除以零點八所得值相等時之斷面積以上"],"a",
 "第30條第1項：牽條之斷面積，應在承受最高使用壓力時，於該斷面所生之應力與該斷面之容許抗拉應力除以一點一所得之值相等時之該斷面之面積以上。以熔接連接者，依第2項尚須再除以零點六。",
 "What cross-sectional area must a stay have?",
 ["At least the area where stress equals the allowable tensile stress divided by 1.1","At least the area where stress equals the allowable tensile stress multiplied by 1.1","At least the area where stress equals the allowable bending stress divided by 1.5","At least the area where stress equals the allowable shear stress divided by 0.8 too"],
 "Article 30, paragraph 1."),

(PV,"第30條",3,"壓力容器標準-牽條",
 "牽條以熔接連接者，其斷面積之計算另有何要求？",
 ["應將原規定所得之斷面積再除以零點六所得之值以上","應將原規定所得之斷面積再乘以零點六所得之值以上","應將原規定所得之斷面積再除以一點一所得之值以上","應將原規定所得之斷面積再乘以一點六七所得之值以上"],"a",
 "第30條第2項：牽條以熔接連接者，其斷面積應在依第一項算得之面積再除以零點六所得之值以上，不受第一項規定之限制。第3項並要求裝設牽條時使接合部具安全所必要之強度。",
 "What extra rule applies to the area of a welded stay?",
 ["The area required under the general rule must be divided by 0.6","The area required under the general rule must be multiplied by 0.6","The area required under the general rule must be divided by 1.1","The area required under the general rule must be multiplied by 1.67"],
 "Article 30, paragraph 2."),

(PV,"第30條",1,"壓力容器標準-牽條",
 "裝設牽條時，應採取何種方法實施？",
 ["應採取使其接合部具有安全所必要強度之方法實施","應採取以螺紋旋裝並加設補強材之方法實施裝設","應採取使接合部厚度達八毫米以上之方法為裝設","應採取先行實施磁粉探傷試驗合格後裝設之方法"],"a",
 "第30條第3項：裝設牽條時，應採取使其接合部具有安全所必要強度之方法實施。第31條並要求以牽條支撐之板厚度在八毫米以上，棒牽條以熔接裝設者除外。",
 "How must stays be installed?",
 ["By a method giving the joint the strength necessary for safety","By a screwed connection with an added reinforcing pad at joint","By a method making the joint at least eight millimetres thick","By carrying out magnetic particle testing before installing it"],
 "Article 30, paragraph 3."),

(PV,"第31條",2,"壓力容器標準-牽條",
 "以牽條支撐之板，其厚度應在多少以上？有何例外？",
 ["應在八毫米以上；但棒牽條以熔接方法裝設者不在此限","應在五毫米以上；但棒牽條以螺紋旋裝裝設者不在此限","應在十毫米以上；但棒牽條以鉚接方法裝設者不在此限","應在二點五毫米以上；但棒牽條以熔接裝設者不在此限"],"a",
 "第31條第1項：以牽條支撐之板之厚度，應在八毫米以上；但棒牽條以熔接方法裝設者，不在此限。同條第2項並要求該棒牽條應有不致使其熔接部發生過剩應力集中之節距。",
 "How thick must a stayed plate be, and what is the exception?",
 ["At least eight millimetres, unless bar stays are attached by welding","At least five millimetres, unless bar stays are attached by screwing","At least ten millimetres, unless the bar stays are attached by riveting","At least two-point-five millimetres, unless bar stays are welded on"],
 "Article 31, paragraph 1."),

(PV,"第31條",2,"壓力容器標準-牽條",
 "以熔接方法裝設之棒牽條，應具備何種條件？",
 ["應有不致使其熔接部發生過剩應力集中之節距","應有不致使其熔接部產生腐蝕之防蝕塗裝措施","應有使其熔接部厚度達板厚一點五倍之補強材","應有使其熔接部全長實施磁粉探傷試驗之紀錄"],"a",
 "第31條第2項：以熔接方法裝設之棒牽條，應有不致使其熔接部發生過剩應力集中之節距。此為第1項板厚八毫米以上規定之但書配套要求。",
 "What must a welded bar stay provide?",
 ["A pitch that avoids excessive stress concentration at the weld","An anti-corrosion coating that prevents corrosion at the weld","A reinforcing pad making the weld 1.5 times the plate thickness","A record of magnetic particle testing over the whole weld line"],
 "Article 31, paragraph 2."),

(PV,"第32條",2,"壓力容器標準-牽條",
 "以牽條支撐之平板及熱交換器平型管板，其最小厚度準用何規定？",
 ["準用內面承壓圓筒或球形胴體板最小厚度之規定","準用外面承壓圓筒胴體板最小厚度之相關規定","準用中高面承壓端板乘一點六七倍之厚度規定","準用未以管牽條支撐平型管板取較大值之規定"],"a",
 "第32條：以牽條支撐之平板、熱交換器及其類似設備之平型管板之最小厚度，準用第十四條規定。未以管牽條支撐之平型管板則依第28條以彎曲及剪應力二者取較大值。",
 "Which rule sets thickness for stayed flat plates and tube sheets?",
 ["The internally pressurised cylindrical or spherical shell plate rule","The externally pressurised cylindrical shell plate rule is applied","The convex end plate rule multiplying the thickness by 1.67 times","The unstayed flat tube sheet rule taking the larger of two values"],
 "Article 32 applies Article 14."),
]
