# -*- coding: utf-8 -*-
# 第 12 批（C2）：特殊性工業區緩衝地帶及空氣品質監測設施設置標準（ENV-123）、
#                 移動污染源空氣污染防制設備管理辦法（ENV-125）
# ※ 四個選項刻意寫成相近長度。
L1 = "ENV-123"
L3 = "ENV-125"
Q = [

# ===== ENV-123 特殊性工業區緩衝地帶及空氣品質監測設施設置標準 =====
(L1,"第1條",1,"特工區標準-法源",
 "特殊性工業區緩衝地帶及空氣品質監測設施設置標準之訂定法源依據為何？",
 ["依空氣污染防制法第十五條第二項規定訂定之","依空氣污染防制法第二十條第二項規定訂定之","依環境影響評估法第六條第二項規定訂定之","依空氣污染防制法第二十三條第二項規定訂定"],"a",
 "第1條：本標準依空氣污染防制法第十五條第二項規定訂定之。第2條並定義本法第十五條所稱特殊性工業區；第21條規定本標準除已另定施行日期者外，自發布日施行。",
 "What is the legal basis for the Standards for Buffer Zones and Air Quality Monitoring Facilities of Special Industrial Parks?",
 ["Adopted under Article 15, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 20, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 6, Paragraph 2 of the Environmental Impact Assessment Act","Adopted under Article 23, Paragraph 2 of the Air Pollution Control Act"],
 "Article 1; see also Articles 2 and 21."),

(L1,"第2條",3,"特工區標準-定義",
 "本法第十五條所稱特殊性工業區，其認定要件為何？",
 ["工業區內容納所列類別之特殊性工業，且其合計基地面積超過總基地面積四分之一者","工業區內容納所列類別之特殊性工業，且其合計基地面積超過總基地面積二分之一者","工業區內容納所列類別之特殊性工業，且其員工人數合計超過全區從業人員半數者","工業區內容納任一所列類別之特殊性工業，不論其基地面積比例一律認定為特殊性"],"a",
 "第2條第1項：本法第十五條所稱特殊性工業區，指工業區內容納金屬冶煉業、煉油工業、石油化學基本原料工業、紙漿工業、水泥製造工業等類別之特殊性工業，且其合計基地面積超過總基地面積四分之一者。",
 "What is the criterion for a park to be a special industrial park under Article 15 of the Act?",
 ["The park houses the listed special industries whose combined site area exceeds one quarter of the total site area","The park houses the listed special industries whose combined site area exceeds one half of the total site area","The park houses the listed special industries whose employees together exceed half of all workers in the park","The park houses any one of the listed special industries, regardless of what share of the site area it occupies"],
 "Article 2, Paragraph 1."),

(L1,"第2條",3,"特工區標準-擴大變更",
 "本法施行細則所稱特殊性工業區之擴大與變更，其區別為何？",
 ["擴大指總基地面積變大且特殊性工業類別面積增加並逾四分之一；變更指總基地面積未變化但特殊性工業類別面積增加","擴大指總基地面積未變化但特殊性工業類別面積增加；變更指總基地面積變大且特殊性工業類別面積亦同步增加","擴大指工業區增加新的特殊性工業類別種類；變更指原有特殊性工業改變其產品項目或製程設備之類型內容","擴大指緩衝地帶面積增加逾四分之一者；變更指空氣品質監測站數量增加或監測項目種類有所調整之情形"],"a",
 "第2條第2項：所稱特殊性工業區擴大，指一般性工業區及特殊性工業區總基地面積變大，其容納之特殊性工業類別面積增加，且合計基地面積超過總基地面積四分之一者；所稱變更，指總基地面積未變化，但容納特殊性工業類別面積增加者。",
 "How do expansion and alteration of a special industrial park differ?",
 ["Expansion means the total site grows and special industry area rises past one quarter; alteration means the total site is unchanged but that area rises","Expansion means the total site is unchanged but special industry area rises; alteration means the total site grows and that area rises as well","Expansion means the park adds new categories of special industry; alteration means existing special industries change their products or processes","Expansion means the buffer zone area grows by more than one quarter; alteration means monitoring stations or monitored items are adjusted"],
 "Article 2, Paragraph 2."),

(L1,"第2條",2,"特工區標準-區位",
 "新設特殊性工業區及擴大區域內之特殊性工業，其坐落區位有何限制？",
 ["應集中坐落於不直接與區界外其他土地使用分區相鄰之區位","應分散坐落於工業區四周並直接緊鄰區界以利廢氣稀釋擴散","應集中坐落於工業區之盛行風上風處並緊鄰緩衝地帶之邊界","應集中坐落於監測站所在鄉鎮市區內並與住宅區相隔六十公尺"],"a",
 "第2條第3項：新設特殊性工業區及擴大特殊性工業區內擴大區域之特殊性工業，應集中坐落於不直接與區界外其他土地使用分區相鄰之區位。第7條並規定與區外住宅區、學校、醫院或生態保護區毗鄰者，緩衝地帶寬度不得小於六十公尺。",
 "Where must special industries in a new or expanded special industrial park be located?",
 ["They must be concentrated where they do not directly adjoin other land use zones outside the park boundary","They must be spread around the park periphery and directly adjoin the boundary so exhaust disperses better","They must be concentrated upwind of the prevailing wind of the park and directly adjoin the buffer zone edge","They must be concentrated in the township where the monitoring station lies and be 60 metres from housing"],
 "Article 2, Paragraph 3; see also Article 7."),

(L1,"第3條",2,"特工區標準-設置計畫",
 "開發特殊性工業區者，就緩衝地帶及空氣品質監測設施設置計畫應如何辦理？",
 ["應於開發前提出設置計畫，報請直轄市、縣（市）主管機關審查通過後始得開發","應於開發後六個月內提出設置計畫，報請直轄市、縣（市）主管機關備查即可","應於開發前提出設置計畫，報請中央主管機關核定並轉送目的事業主管機關備查","應於固定污染源正式運轉後一年內提出設置計畫，報請當地主管機關審查通過"],"a",
 "第3條第1項：開發特殊性工業區者，應於開發前提出緩衝地帶及空氣品質監測設施設置計畫，報請直轄市、縣（市）主管機關審查通過後，始得開發。同條第4項並規定設置內容變更時，應於變更前提出修正計畫報請審查通過後始得變更。",
 "How must a developer of a special industrial park handle the buffer zone and monitoring facility plan?",
 ["The plan must be submitted before development and approved by the municipal or county authority first","The plan must be submitted within six months after development and merely filed with the local authority","The plan must be submitted before development to the central authority for approval and then forwarded","The plan must be submitted within one year after the source starts operating and be approved locally"],
 "Article 3, Paragraphs 1 and 4."),

(L1,"第3條",3,"特工區標準-計畫內容",
 "緩衝地帶及空氣品質監測設施設置計畫應載明之特殊性工業區基本資料，包括下列何者？",
 ["開發單位、總基地面積、容納之特殊性工業類別及面積與占比，並附區外五公里範圍內土地利用配置圖說","開發單位、資本額、員工人數及產品年產值，並附區外十公里範圍內之人口分布及戶籍統計資料表","開發單位、總基地面積及廢水排放量，並附區外一公里範圍內之地質鑽探報告與地下水位觀測紀錄","開發單位、營運計畫與財務預測，並附全國空氣品質監測站分布圖說及最近三年之空氣品質年報"],"a",
 "第3條第2項第1款：設置計畫應載明特殊性工業區基本資料，包括開發單位、總基地面積、容納之特殊性工業類別及面積、其占總基地面積比例、區內特殊性工業類別土地利用配置圖說，以及特殊性工業區外五公里範圍內土地利用配置圖說。",
 "What basic park information must the buffer zone and monitoring facility plan contain?",
 ["Developer, total site area, categories and areas of special industries and their share, plus land use maps within five kilometres outside","Developer, capital, staff numbers and annual output value, plus population and household statistics within ten kilometres outside","Developer, total site area and wastewater discharge, plus geological drilling reports and groundwater records within one kilometre","Developer, business plan and financial forecast, plus a national monitoring station map and three years of air quality reports"],
 "Article 3, Paragraph 2, Subparagraph 1."),

(L1,"第3條",2,"特工區標準-既有工業區",
 "中華民國一百零一年九月二十二日（含）前已開發之特殊性工業區，其空氣品質監測設施設置計畫應於何時提出？",
 ["應於中華民國一百零三年三月三十一日前提出，報請直轄市、縣（市）主管機關審查","應於中華民國一百零三年十二月三十一日前提出，報請中央主管機關核定並公告","應於中華民國一百零五年三月三十一日前提出，報請目的事業主管機關轉送審查","應於本標準發布後六個月內提出，報請所在地鄉鎮市區公所核轉主管機關備查"],"a",
 "第3條第3項：中華民國一百零一年九月二十二日（含）前已開發之特殊性工業區，開發單位應於一百零三年三月三十一日前提出空氣品質監測設施設置計畫，報請直轄市、縣（市）主管機關審查。第14條第1項第4款並定於審查通過通知之日起一年內提報設置完成資料。",
 "By when must special industrial parks developed on or before 22 September 2012 submit their monitoring facility plan?",
 ["By 31 March 2014, submitted to the municipal or county competent authority for review","By 31 December 2014, submitted to the central competent authority for approval and announcement","By 31 March 2016, submitted through the industry regulator to be forwarded for review","Within six months of promulgation, filed through the township office with the competent authority"],
 "Article 3, Paragraph 3; see also Article 14."),

(L1,"第4條",3,"特工區標準-審查期限",
 "直轄市、縣（市）主管機關受理設置計畫後之審查期限及補正規定為何？",
 ["應於四十五日內完成審查；補正日數不算入審查期限，補正總日數不得超過九十日","應於六十日內完成審查；補正日數應算入審查期限，補正總日數不得超過三十日","應於九十日內完成審查；補正僅得通知一次，逾期未補正即駁回並不得再申請","應於三十日內完成審查；補正日數不算入審查期限，補正總日數不得超過一百八十日"],"a",
 "第4條第1項、第2項：主管機關受理設置計畫後應於四十五日內完成審查；經審查不合規定者應通知限期補正，屆期未補正者駁回，已補正仍不合規定者得再通知限期補正；各次補正日數不算入審查期限內，且補正總日數不得超過九十日。",
 "What is the review period and the rule on corrections after a plan is accepted?",
 ["Review is completed within 45 days; correction days are excluded from that period and total no more than 90 days","Review is completed within 60 days; correction days count toward that period and total no more than 30 days","Review is completed within 90 days; only one correction notice is allowed and late correction bars reapplying","Review is completed within 30 days; correction days are excluded from that period and total no more than 180 days"],
 "Article 4, Paragraphs 1 and 2."),

(L1,"第4條",2,"特工區標準-跨轄審查",
 "特殊性工業區緩衝地帶及空氣品質監測設施位於不同直轄市、縣（市）者，其審查應如何辦理？",
 ["受理之主管機關應會商緩衝地帶及監測設施所在地之直轄市、縣（市）主管機關辦理審查作業","受理之主管機關應報請中央主管機關指定單一機關統籌辦理全部審查作業並作成審查結論","應由各該設施所在地之主管機關分別受理並各自作成審查結果，互不拘束亦不須相互會商","應由工業區目的事業主管機關逕行審查後，函知各相關直轄市、縣（市）主管機關備查"],"a",
 "第4條第3項：特殊性工業區緩衝地帶及空氣品質監測設施位於不同直轄市、縣（市）者，直轄市、縣（市）主管機關受理其設置計畫後，應會商緩衝地帶及空氣品質監測設施所在地之直轄市、縣（市）主管機關辦理審查作業。",
 "How is review handled when the buffer zone or monitoring facilities lie in different municipalities or counties?",
 ["The receiving authority must consult the authorities where the buffer zone and monitoring facilities are located","The receiving authority must ask the central authority to designate one agency to handle all the review work","Each authority where the facilities are located reviews separately, reaching results that do not bind each other","The industry regulator of the park reviews it directly and then notifies each relevant local authority for record"],
 "Article 4, Paragraph 3."),

(L1,"第5條",2,"特工區標準-緩衝地帶",
 "本法第十五條所稱緩衝地帶之範圍為何？何種情形之鄰接面不須設置緩衝地帶？",
 ["指區界內四周之綠帶、隔離水道、行政管理設施或其他非生產製程設施；毗鄰海域、寬六十公尺以上河川或陡峭山坡地者免設","指區界外四周之綠帶、隔離水道、行政管理設施或其他非生產製程設施；毗鄰海域、寬三十公尺以上河川或平坦農地者免設","指區界內四周之全部空地及道路用地，並包含廠房間之防火間隔；毗鄰其他工業區或商業區之鄰接面得免設置緩衝地帶","指工業區外五公里範圍內之公有林地及公園綠地；毗鄰住宅區、學校或醫院之鄰接面得免設置緩衝地帶及監測設施"],"a",
 "第5條第1項：本法第十五條所稱緩衝地帶，指設置於特殊性工業區區界內四周之綠帶、隔離水道、行政管理設施或其他非屬生產製程之設施。同條第2項：毗鄰海域或寬度六十公尺以上之河川或坡度陡峭不適開發利用之山坡地者，其鄰接面不須設置緩衝地帶。",
 "What counts as the buffer zone, and when is one not required on an adjoining side?",
 ["Green belts, isolating waterways, administrative or non-production facilities inside the boundary; sides facing sea, rivers over 60 m wide or steep slopes are exempt","Green belts, isolating waterways, administrative or non-production facilities outside the boundary; sides facing sea, rivers over 30 m wide or flat farmland are exempt","All open space and roads inside the boundary including fire gaps between plants; sides facing other industrial or commercial zones are exempt","Public forest and parkland within five kilometres of the park; sides facing housing, schools or hospitals are exempt from buffer and monitoring"],
 "Article 5."),

(L1,"第6條",3,"特工區標準-綠帶",
 "本標準所稱綠帶之定義及樹木栽種密度規定為何？",
 ["指短草或地被植物覆蓋且面積超過三十平方公尺之土地；每十平方公尺應有一株以上高四公尺以上成木","指短草或地被植物覆蓋且面積超過三百平方公尺之土地；每十平方公尺應有三株以上高二公尺以上成木","指喬木林相完整且面積超過三十平方公尺之土地；每一百平方公尺應有一株以上高四公尺以上成木","指人工鋪面以外之所有透水土地面積；每二十平方公尺應有五株以上高度六公尺以上之成木為限"],"a",
 "第6條：綠帶指短草或地被植物所覆蓋，且面積超過三十平方公尺之土地；其樹木栽種密度應符合下列規定之一：每十平方公尺應有一株以上高度四公尺以上之成木；或每二十平方公尺應有一株以上高度四公尺以上之成木，並有二十株以上高度低於四公尺之矮樹。",
 "How is a green belt defined and what planting density is required?",
 ["Land covered by short grass or ground cover exceeding 30 square metres; one mature tree over 4 m tall per 10 square metres","Land covered by short grass or ground cover exceeding 300 square metres; three mature trees over 2 m tall per 10 square metres","Land with complete tree canopy exceeding 30 square metres; one mature tree over 4 m tall per 100 square metres of area","All pervious land other than paved surfaces; at least five mature trees over 6 m tall for every 20 square metres of land"],
 "Article 6."),

(L1,"第6條",2,"特工區標準-綠帶密度",
 "綠帶樹木栽種密度之第二種替代規定為何？",
 ["每二十平方公尺應有一株以上高四公尺以上之成木，及二十株以上高度低於四公尺之矮樹","每二十平方公尺應有二株以上高四公尺以上之成木，及十株以上高度低於二公尺之矮樹","每三十平方公尺應有一株以上高六公尺以上之成木，及三十株以上高度低於四公尺之矮樹","每十平方公尺應有一株以上高二公尺以上之成木，及五株以上高度低於一公尺之地被植物"],"a",
 "第6條第2款：每二十平方公尺應有一株以上高度為四公尺以上之成木，二十株以上高度低於四公尺之矮樹。第1款則為每十平方公尺應有一株以上高度四公尺以上之成木，二者符合其一即可。",
 "What is the alternative planting density requirement for green belts?",
 ["Per 20 square metres, one or more mature trees over 4 m tall plus 20 or more shrubs under 4 m tall","Per 20 square metres, two or more mature trees over 4 m tall plus 10 or more shrubs under 2 m tall","Per 30 square metres, one or more mature trees over 6 m tall plus 30 or more shrubs under 4 m tall","Per 10 square metres, one or more trees over 2 m tall plus five or more ground cover plants under 1 m"],
 "Article 6, Subparagraph 2."),

(L1,"第7條",3,"特工區標準-緩衝地帶面積",
 "新設特殊性工業區緩衝地帶之設置應符合何項規定？",
 ["面積不得少於工業區總面積百分之十二，或最小寬度Ｗ＝３√Ａ且不得小於六十公尺，二者符合其一","面積不得少於工業區總面積百分之二十五，或最小寬度Ｗ＝３√Ａ且不得小於三十公尺，二者均須符合","面積不得少於工業區總面積百分之十二，且最小寬度Ｗ＝５√Ａ並不得小於一百公尺，二者均須符合","面積不得少於工業區總面積百分之七十，或最小寬度Ｗ＝３√Ａ且不得小於六十公尺，由業者自行擇定"],"a",
 "第7條第1項：新設特殊性工業區緩衝地帶之設置應符合下列規定之一：緩衝地帶面積不得少於該工業區總面積百分之十二；或緩衝地帶最小寬度依Ｗ＝３√Ａ（Ａ為工業區總面積、公頃；Ｗ為最小寬度、公尺），且不得小於六十公尺。",
 "What must the buffer zone of a new special industrial park satisfy?",
 ["Either area of at least 12 percent of total park area, or minimum width W = 3√A and never less than 60 metres","Either area of at least 25 percent of total park area, or minimum width W = 3√A and never less than 30 metres; both apply","Area of at least 12 percent of total park area, and also minimum width W = 5√A never less than 100 metres; both apply","Either area of at least 70 percent of total park area, or minimum width W = 3√A and never less than 60 metres, at will"],
 "Article 7, Paragraph 1."),

(L1,"第7條",3,"特工區標準-緩衝地帶要求",
 "新設特殊性工業區毗鄰住宅區、學校、醫院或生態保護區者，其緩衝地帶寬度及綠帶隔離水道面積要求為何？",
 ["緩衝地帶寬度不得小於六十公尺；綠帶及隔離水道面積不得少於緩衝地帶面積百分之七十","緩衝地帶寬度不得小於三十公尺；綠帶及隔離水道面積不得少於緩衝地帶面積百分之五十","緩衝地帶寬度不得小於一百公尺；綠帶及隔離水道面積不得少於工業區總面積百分之十二","緩衝地帶寬度不得小於六十公尺；綠帶及隔離水道面積不得少於緩衝地帶面積百分之三十"],"a",
 "第7條第2項：新設特殊性工業區與工業區外之住宅區、學校、醫院或生態保護區毗鄰者，其緩衝地帶寬度不得小於六十公尺。同條第3項：綠帶及隔離水道之面積，不得少於緩衝地帶面積百分之七十。同條第4項並要求於區內任一特殊性工業固定污染源正式運轉日前完成緩衝地帶設置。",
 "For a new park adjoining housing, schools, hospitals or ecological reserves, what width and green area apply?",
 ["The buffer zone must be at least 60 metres wide; green belts and waterways must be at least 70 percent of the buffer area","The buffer zone must be at least 30 metres wide; green belts and waterways must be at least 50 percent of the buffer area","The buffer zone must be at least 100 metres wide; green belts and waterways must be at least 12 percent of the park area","The buffer zone must be at least 60 metres wide; green belts and waterways must be at least 30 percent of the buffer area"],
 "Article 7, Paragraphs 2 to 4."),

(L1,"第8條",2,"特工區標準-擴大變更緩衝",
 "擴大或變更之特殊性工業區，其緩衝地帶設置應如何辦理？",
 ["新設時已實施環評者依審查通過之環說書、評估報告書內容及審查結論辦理；未實施環評者提出原設置內容報請同意後依原規定設置","新設時已實施環評者一律改依本標準第七條規定重新設置；未實施環評者應補辦環境影響評估後依審查結論設置緩衝地帶","不論新設時是否實施環評，均應依本標準第七條規定辦理，緩衝地帶面積不得少於工業區總面積百分之十二並另加計綠帶","不論新設時是否實施環評，均得免設置緩衝地帶，僅需依第九條至第十三條規定設置空氣品質監測設施並定期申報監測紀錄"],"a",
 "第8條：擴大或變更之特殊性工業區及一般性工業區經擴大或變更為特殊性工業區者，於新設時已實施環境影響評估者，其緩衝地帶設置應依審查通過之環境影響說明書、環境影響評估報告書所載內容及審查結論辦理；未實施環評者，應提出擴大或變更前依相關法令設置之緩衝地帶內容，報請直轄市、縣（市）主管機關同意後依原規定設置。",
 "How must buffer zones be provided for expanded or altered special industrial parks?",
 ["If EIA was done at establishment, follow the approved EIA documents and conclusions; if not, submit the existing buffer content for consent","If EIA was done at establishment, they must all be rebuilt under Article 7; if not, a supplementary EIA must be made and followed","Regardless of any earlier EIA, Article 7 applies, with buffer area at least 12 percent of park area plus additional green belts","Regardless of any earlier EIA, no buffer zone is needed and only the monitoring facilities of Articles 9 to 13 must be provided"],
 "Article 8."),

(L1,"第9條",3,"特工區標準-監測項目",
 "特殊性工業區空氣品質監測設施之氣象監測項目及一般空氣污染物監測項目為何？",
 ["氣象為風向、風速、溫度、相對濕度、降雨量；一般污染物含PM10、PM2.5、SO2、NOx、CO、O3及總碳氫化合物","氣象為風向、風速、氣壓、日照量、蒸發量；一般污染物含PM10、PM2.5、SO2、NOx、CO、O3及戴奧辛類物質","氣象為風向、風速、溫度、相對濕度、能見度；一般污染物僅含PM10、SO2及NOx等三項基本空氣污染物指標","氣象為溫度、相對濕度、降雨量、紫外線量；一般污染物含PM2.5、CO、O3、氨氣、氯氣及揮發性有機物等項"],"a",
 "第9條第1款、第2款：氣象監測項目為風向、風速、溫度、相對濕度、降雨量；一般空氣污染物監測項目為懸浮微粒（PM10）、細懸浮微粒（PM2.5）、二氧化硫、氮氧化物（含NO及NO2）、一氧化碳、臭氧及總碳氫化合物。",
 "What meteorological and general air pollutant items must be monitored?",
 ["Meteorology: wind direction, speed, temperature, humidity, rainfall; pollutants: PM10, PM2.5, SO2, NOx, CO, O3 and THC","Meteorology: wind direction, speed, pressure, sunshine, evaporation; pollutants: PM10, PM2.5, SO2, NOx, CO, O3 and dioxins","Meteorology: wind direction, speed, temperature, humidity, visibility; pollutants: only PM10, SO2 and NOx as basic indicators","Meteorology: temperature, humidity, rainfall, ultraviolet level; pollutants: PM2.5, CO, O3, ammonia, chlorine and VOCs"],
 "Article 9, Subparagraphs 1 and 2."),

(L1,"第9條",3,"特工區標準-其他監測項目",
 "容納半導體製造工業或光電材料及元件製造業之特殊性工業區，應加測哪些空氣污染物？",
 ["應監測無機酸（含氫氟酸、鹽酸、硝酸、磷酸及硫酸）、醋酸、氨氣及氯氣等項目","應監測硫化氫、甲硫醇、二硫化碳、硫化甲基、二硫化甲基及甲基胺類等項目","應監測戴奧辛及附表一所列有機光化前驅物、甲醛及乙醛等多項有害空氣污染物","應監測懸浮微粒中之鎳、砷、鎘、錳、鈹、鉛化合物，並免測其他一般空氣污染物"],"a",
 "第9條第3款第3目：容納之特殊性工業類別含半導體製造工業或光電材料及元件製造業之一者，應監測無機酸（包含氫氟酸、鹽酸、硝酸、磷酸及硫酸）、醋酸、氨氣及氯氣。同款第2目並要求監測PM10中之鎳、砷、鎘、錳、鈹、鉛化合物及TSP中之六價鉻。",
 "What extra pollutants must be monitored where semiconductor or optoelectronic manufacturing is present?",
 ["Inorganic acids including hydrofluoric, hydrochloric, nitric, phosphoric and sulphuric acid, plus acetic acid, ammonia and chlorine","Hydrogen sulphide, methyl mercaptan, carbon disulphide, dimethyl sulphide, dimethyl disulphide and methylamine compounds","Dioxins together with the photochemical precursors listed in Table 1, plus formaldehyde and acetaldehyde as hazardous pollutants","Nickel, arsenic, cadmium, manganese, beryllium and lead compounds in PM10, with all general air pollutants then exempted"],
 "Article 9, Subparagraph 3."),

(L1,"第10條",2,"特工區標準-監測方法",
 "空氣品質監測方法之規定，以及原以人工操作監測者之轉換義務為何？",
 ["應符合中央主管機關公告或認可之檢測方法，已公告認可自動檢測方法者應以自動檢測方法為之；人工操作者應於公告後三年內提修正計畫改為自動","應符合中央主管機關公告或認可之檢測方法，得由業者自行選擇人工或自動檢測方法為之；人工操作者應於公告後一年內提修正計畫改為自動","應符合國際標準組織所定之檢測方法，並優先採行人工操作監測以確保數據品質；自動檢測方法僅於主管機關指定時始得採用之","應符合中央主管機關公告或認可之檢測方法，並一律採人工操作監測設施進行；自動監測設施僅得作為輔助性之參考數據來源"],"a",
 "第10條：空氣品質監測方法應符合中央主管機關公告或認可檢測方法之規定，且中央主管機關已公告或認可自動檢測方法者，應以自動檢測方法為之；依規定以人工操作監測設施進行者，應於自動檢測方法公告後三年內提出設置修正計畫，報請主管機關審查通過後改以自動檢測方法為之。",
 "What are the rules on monitoring methods and on switching from manual monitoring?",
 ["Methods must follow those announced or approved centrally, automatic methods must be used where announced, and manual users must switch within three years","Methods must follow those announced or approved centrally, operators may choose manual or automatic, and manual users must switch within one year","Methods must follow ISO standards and manual monitoring is preferred for data quality, with automatic methods used only if designated","Methods must follow those announced or approved centrally but manual facilities must always be used, automatic data serving only as reference"],
 "Article 10."),

(L1,"第11條",3,"特工區標準-站址選定",
 "特殊性工業區空氣品質監測站之站址選定原則，下列何者正確？",
 ["應用一年以上具代表性氣象資料及擴散模擬選址、設於盛行風下風處、設於敏感受體聚集處、設於最易發生最大濃度值區域","應用三個月以上氣象資料及擴散模擬選址、設於盛行風上風處、設於人口稀少處、設於歷年濃度最低之背景值區域範圍","應用一年以上氣象資料及擴散模擬選址、設於工業區中心點、設於廠區大門出入口、設於距離污染源五百公尺內之位置","應由主管機關逕行指定站址、設於行政區界線上、設於既有測站相鄰處、設於交通流量最大之主要幹道路口旁側位置"],"a",
 "第11條第1項：監測站站址選定原則為：應用一年以上具代表性之氣象資料及適當之空氣品質擴散模擬選擇位置；設置於工業區之盛行風下風處；設置於敏感受體聚集處；考慮污染源分布，設置於最易發生空氣污染物最大濃度值（長期及短期）之區域。同條第2項並要求設置監測中心管理監測事宜。",
 "Which correctly states the siting principles for air quality monitoring stations of a special industrial park?",
 ["Use one year or more of meteorological data and dispersion modelling; site downwind, at sensitive receptor clusters, and where peak concentrations occur","Use three months or more of meteorological data and dispersion modelling; site upwind, in sparsely populated areas, and where background values are lowest","Use one year or more of meteorological data and dispersion modelling; site at the park centre, at the plant gate, and within 500 metres of the source","Have the competent authority designate the site directly; place it on the district boundary, beside existing stations, and at the busiest road junction"],
 "Article 11."),

(L1,"第12條",3,"特工區標準-監測站數量",
 "容納金屬冶煉業、煉油工業、水泥製造工業或煉焦工業等之特殊性工業區，應設置多少空氣品質監測站？",
 ["應於所在鄉鎮市區及其周界緊鄰之鄉鎮市區各設至少一個，並另於適當地區設置至少四個監測站","應於所在鄉鎮市區及其周界緊鄰之鄉鎮市區各設至少二個，並另於適當地區設置至少二個監測站","應於所在鄉鎮市區設置至少一個監測站即可，其周界緊鄰之鄉鎮市區得免另行設置任何監測站","應於所在直轄市或縣市轄區內設置至少四個監測站，並得與鄰近縣市之既有監測站合併計算"],"a",
 "第12條第1項：容納之特殊性工業類別含金屬冶煉業、煉油工業、石油化學基本原料工業、紙漿工業、水泥製造工業、煉焦工業及以煤、油或氣體為燃料之電力業之一者，應於所在鄉（鎮、市、區）及其周界緊鄰之鄉（鎮、市、區）各設置至少一個監測站，並另於適當地區設置至少四個監測站。同條第2項：其餘特殊性工業區應於適當地區設置至少四個監測站。",
 "How many monitoring stations must a park housing smelting, refining, cement or coking industries provide?",
 ["At least one in its own township and in each directly adjoining township, plus at least four more in suitable areas","At least two in its own township and in each directly adjoining township, plus at least two more in suitable areas","At least one in its own township is enough, and the directly adjoining townships need no station of their own","At least four stations within its own municipality or county, which may be merged with neighbouring counties' stations"],
 "Article 12, Paragraphs 1 and 2."),

(L1,"第12條",2,"特工區標準-合併設置",
 "特殊性工業區應設之空氣品質監測站，於何種情形得合併設置？",
 ["其他特殊性工業區已依規定於同一鄉鎮市區設置者，得報請直轄市、縣（市）主管機關同意後合併設置","其他特殊性工業區已於同一直轄市或縣市內設置者，即得逕行合併設置，免報請主管機關同意","經開發單位與鄰近工業區達成協議並簽訂契約者，即得合併設置並按比例分攤設置及維護費用","經環境影響評估審查結論同意者，得將應設之監測站數量減半並免設監測中心管理監測事宜"],"a",
 "第12條第3項：特殊性工業區依前二項規定應設置之空氣品質監測站，其他特殊性工業區已依規定於同一鄉（鎮、市、區）設置者，得報請直轄市、縣（市）主管機關同意後，合併設置。",
 "When may required monitoring stations be jointly established?",
 ["Where another special industrial park already has one in the same township, joint use is allowed with the local authority's consent","Where another special industrial park already has one in the same municipality or county, joint use is allowed without any consent","Where the developer and a neighbouring park sign an agreement, joint use is allowed with costs shared in proportion between them","Where the EIA conclusion so agrees, the required number of stations may be halved and no monitoring centre need be established"],
 "Article 12, Paragraph 3."),

(L1,"第13條",2,"特工區標準-採樣口",
 "空氣品質監測設施採樣口之設置原則如何規範？無法適用時應如何辦理？",
 ["採樣口設置原則依附錄之規定；經指定監測項目而無法適用者，依本法施行細則第十二條第四項規定辦理","採樣口設置原則依附錄之規定；無法適用者得由開發單位自行決定位置，於設置完成後報請主管機關備查","採樣口設置原則由中央主管機關逐案核定；無法適用者應改設於鄰近鄉鎮市區之既有空氣品質監測站內","採樣口設置原則依環境影響評估審查結論辦理；無法適用者得免設置採樣口並改以模式模擬結果替代之"],"a",
 "第13條：空氣品質監測設施採樣口之設置原則，依附錄之規定；經主管機關指定監測項目之空氣品質監測設施，其採樣口無法適用前項設置原則者，應依本法施行細則第十二條第四項規定辦理。",
 "How are sampling port siting principles prescribed, and what if they cannot be applied?",
 ["Ports follow the appendix; where designated items cannot meet it, Article 12, Paragraph 4 of the Enforcement Rules applies","Ports follow the appendix; where it cannot be met, the developer decides the location and files it for record afterwards","Ports are approved case by case by the central authority; where it cannot be met, an existing nearby station must be used","Ports follow the EIA review conclusion; where it cannot be met, no port is needed and modelling results are used instead"],
 "Article 13."),

(L1,"第14條",3,"特工區標準-提報期限",
 "特殊性工業區提報空氣品質監測設施設置完成資料之期限，下列何者正確？",
 ["新設者於區內任一特殊性工業固定污染源正式運轉日前；變更者於任一增設固定污染源正式運轉日起一年內","新設者於區內任一特殊性工業固定污染源正式運轉日起一年內；變更者於任一增設固定污染源正式運轉日前","新設者於設置計畫審查通過之日起一年內；變更者於區內任一增設固定污染源正式運轉日起三年內提報","新設者於開發完成後六個月內提報；變更者於變更計畫報請主管機關備查之日起三個月內提報完成資料"],"a",
 "第14條第1項：新設之特殊性工業區應於區內任一屬特殊性工業之固定污染源設置完成正式運轉日前提報；擴大者於任一增設固定污染源正式運轉日前；變更者於任一增設固定污染源正式運轉日起一年內；一百零一年九月二十二日前已開發者，自設置計畫審查通過通知之日起一年內。同條第2項：正式運轉日指該固定污染源所屬製程操作許可證登載之有效起始日。",
 "Which correctly states the deadlines for reporting completion of monitoring facilities?",
 ["New parks report before any special industry source formally operates; altered parks within one year after any added source formally operates","New parks report within one year after any special industry source formally operates; altered parks before any added source operates","New parks report within one year after plan approval; altered parks within three years after any added source formally operates","New parks report within six months after development is finished; altered parks within three months after the change is filed"],
 "Article 14."),

(L1,"第15條",3,"特工區標準-監測頻率",
 "以人工操作監測設施進行監測者，其戴奧辛及有害空氣污染物之監測頻率原則為何？",
 ["戴奧辛每年應監測一次；附表二所列有害空氣污染物每六日應進行一次連續二十四小時樣品採集及分析","戴奧辛每季應監測一次；附表二所列有害空氣污染物每三日應進行一次連續十二小時樣品採集及分析","戴奧辛每半年應監測一次；附表二所列有害空氣污染物每月應進行一次連續四十八小時樣品採集分析","戴奧辛每月應監測一次；附表二所列有害空氣污染物每十二日應進行一次連續八小時樣品採集及分析"],"a",
 "第15條第1項第1款第2目：以人工操作監測設施進行者，戴奧辛每年應監測一次；附表二所列有害空氣污染物每六日應進行一次連續二十四小時樣品採集及分析；其餘監測項目每六日依中央主管機關公告或認可檢測方法監測一次。以自動監測設施進行者應連續進行監測。",
 "For manual monitoring, what is the basic frequency for dioxins and hazardous air pollutants?",
 ["Dioxins once a year; Table 2 hazardous pollutants sampled and analysed for 24 consecutive hours once every six days","Dioxins once a quarter; Table 2 hazardous pollutants sampled and analysed for 12 consecutive hours once every three days","Dioxins twice a year; Table 2 hazardous pollutants sampled and analysed for 48 consecutive hours once every month","Dioxins once a month; Table 2 hazardous pollutants sampled and analysed for eight consecutive hours every twelve days"],
 "Article 15, Paragraph 1, Subparagraph 1."),

(L1,"第15條",3,"特工區標準-變更頻率",
 "變更之特殊性工業區於增設固定污染源正式運轉日後第二年，其自動監測及人工監測頻率為何？第三年起如何辦理？",
 ["自動監測每月應進行一次連續二十四小時監測；人工監測有害空氣污染物每月一次連續二十四小時採樣，第三年起依新設者規定辦理","自動監測應連續進行監測不得中斷；人工監測有害空氣污染物每六日一次連續二十四小時採樣，第三年起得減半為每十二日一次","自動監測每季應進行一次連續二十四小時監測；人工監測有害空氣污染物每季一次連續八小時採樣，第三年起即可免再進行監測","自動監測每週應進行一次連續十二小時監測；人工監測有害空氣污染物每週一次連續十二小時採樣，第三年起改為每年監測一次"],"a",
 "第15條第1項第2款：變更之特殊性工業區於任一增設特殊性工業固定污染源正式運轉日後第二年，自動監測設施每月應進行一次連續二十四小時監測；人工操作者戴奧辛每年監測一次，附表二有害空氣污染物每月一次連續二十四小時採樣分析，其餘項目每月監測一次；第三年起依第1款（即新設者）規定辦理。",
 "In the second year after an added source operates in an altered park, what monitoring frequency applies, and from year three?",
 ["Automatic monitoring runs 24 consecutive hours once a month; manual hazardous pollutant sampling is 24 hours monthly; from year three the new-park rules apply","Automatic monitoring must run continuously without interruption; manual hazardous pollutant sampling is 24 hours every six days; from year three it may halve to every twelve days","Automatic monitoring runs 24 consecutive hours once a quarter; manual hazardous pollutant sampling is eight hours quarterly; from year three monitoring may cease altogether","Automatic monitoring runs 12 consecutive hours once a week; manual hazardous pollutant sampling is 12 hours weekly; from year three it changes to once every year"],
 "Article 15, Paragraph 1, Subparagraph 2."),

(L1,"第16條",3,"特工區標準-頻率調整",
 "人工操作監測設施之監測頻率，於何種情形得調整或免測？",
 ["連續二年最高與最低監測值差異在百分之十以內者得調整為每十二日一次；連續三年最高監測值均低於偵測極限者得免測該項目","連續二年最高與最低監測值差異在百分之二十以內者得調整為每三日一次；連續三年監測值低於管制標準者得免測該項目","連續三年最高與最低監測值差異在百分之十以內者得調整為每六日一次；連續五年最高監測值均低於偵測極限者得免測該項","連續一年最高與最低監測值差異在百分之五以內者得調整為每二十四日一次；連續二年未超標者即得免測該項空氣污染物"],"a",
 "第16條第1項：人工操作監測者除戴奧辛外，連續二年之最高及最低監測值差異在百分之十以內者，得報請主管機關同意後調整附表二有害空氣污染物監測頻率為每十二日一次連續二十四小時採樣分析，其餘項目每十二日監測一次。同條第2項：連續三年最高監測值均低於偵測極限者，得報請同意後免進行該項監測。",
 "When may the frequency of manual monitoring be relaxed or the item exempted?",
 ["If two years' highest and lowest values differ by no more than 10 percent, frequency may become every twelve days; three years all below detection limit allows exemption","If two years' highest and lowest values differ by no more than 20 percent, frequency may become every three days; three years below the standard allows exemption","If three years' highest and lowest values differ by no more than 10 percent, frequency may become every six days; five years all below detection limit allows exemption","If one year's highest and lowest values differ by no more than 5 percent, frequency may become every 24 days; two years without exceedance allows exemption"],
 "Article 16."),

(L1,"第16條",3,"特工區標準-恢復監測",
 "經同意免測之空氣污染物項目，於何種情形應恢復監測？其恢復後之頻率為何？",
 ["區內任一屬特殊性工業之固定污染源涉及本法第二十四條所稱之變更者，自操作許可證有效起始日起恢復為每六日監測一次","區內任一屬特殊性工業之固定污染源發生違規遭裁罰者，自裁處書送達之日起恢復為每十二日監測一次並持續二年","區內新增任一非屬特殊性工業之固定污染源者，自其設置完成日起恢復為每月監測一次並報請主管機關核備","經民眾陳情或主管機關稽查發現異味者，自陳情之日起恢復為每三日監測一次並應連續監測滿一年以上"],"a",
 "第16條第2項但書：特殊性工業區內屬特殊性工業之固定污染源，其任一固定污染源涉及本法第二十四條所稱之變更者，該項空氣污染物監測頻率自該固定污染源操作許可證登載之有效起始日起，恢復為每六日依中央主管機關公告或認可檢測方法監測一次。",
 "When must an exempted pollutant item resume monitoring, and at what frequency?",
 ["When any special industry stationary source in the park undergoes a change under Article 24 of the Act, monitoring resumes every six days from the permit start date","When any special industry stationary source in the park is fined for a violation, monitoring resumes every twelve days from service of the penalty for two years","When any non-special-industry stationary source is added in the park, monitoring resumes monthly from its completion date subject to authority approval","When residents complain or inspectors detect odour, monitoring resumes every three days from the complaint date and continues for at least one year"],
 "Article 16, Paragraph 2 proviso; see also Article 24 of the Act."),

(L1,"第17條",3,"特工區標準-數據品質",
 "空氣品質自動監測設施之取樣分析循環時間、數據紀錄值及有效紀錄值比例規定為何？",
 ["取樣及分析應於六分鐘內完成一次循環並以一分鐘平均值為紀錄值；每月有效紀錄值不得少於應監測時數百分之七十五","取樣及分析應於十五分鐘內完成一次循環並以五分鐘平均值為紀錄值；每月有效紀錄值不得少於應監測時數百分之九十","取樣及分析應於六十分鐘內完成一次循環並以小時平均值為紀錄值；每年有效紀錄值不得少於應監測時數百分之八十","取樣及分析應於三分鐘內完成一次循環並以三十秒平均值為紀錄值；每季有效紀錄值不得少於應監測時數百分之五十"],"a",
 "第17條第1項：氣象之風向、風速、溫度、相對濕度與SO2、NOx、CO、O3及THC以自動監測設施進行者，取樣及分析應於六分鐘內完成一次循環，並以一分鐘平均值作為數據紀錄值。同條第2項：自動監測設施每月之有效紀錄值不得少於應監測時數百分之七十五。",
 "What cycle time, record value and valid record ratio apply to automatic monitoring facilities?",
 ["Sampling and analysis complete one cycle within six minutes with one-minute averages recorded; monthly valid records at least 75 percent of required hours","Sampling and analysis complete one cycle within fifteen minutes with five-minute averages recorded; monthly valid records at least 90 percent of required hours","Sampling and analysis complete one cycle within sixty minutes with hourly averages recorded; yearly valid records at least 80 percent of the required hours","Sampling and analysis complete one cycle within three minutes with 30-second averages recorded; quarterly valid records at least 50 percent of hours"],
 "Article 17, Paragraphs 1 and 2."),

(L1,"第17條",2,"特工區標準-人工有效值",
 "除戴奧辛外，空氣品質人工操作監測設施之有效樣品紀錄值比例規定為何？",
 ["每年不得少於應監測樣品數百分之七十五，每月亦不得少於應監測樣品數百分之七十五","每年不得少於應監測樣品數百分之九十，每月亦不得少於應監測樣品數百分之九十","每年不得少於應監測樣品數百分之五十，每季亦不得少於應監測樣品數百分之六十","每年不得少於應監測樣品數百分之七十五，每月則不受有效樣品紀錄值比例之限制"],"a",
 "第17條第3項：除戴奧辛外，空氣品質人工操作監測設施每年之有效樣品紀錄值不得少於應監測樣品數百分之七十五；每月之有效樣品紀錄值，亦不得少於應監測樣品數百分之七十五。自動監測設施則規定每月有效紀錄值不得少於應監測時數百分之七十五。",
 "Apart from dioxins, what valid sample ratio applies to manual monitoring facilities?",
 ["At least 75 percent of required samples each year, and also at least 75 percent of required samples each month","At least 90 percent of required samples each year, and also at least 90 percent of required samples each month","At least 50 percent of required samples each year, and also at least 60 percent of required samples each quarter","At least 75 percent of required samples each year, with no monthly valid sample ratio requirement imposed"],
 "Article 17, Paragraph 3."),

(L1,"第18條",3,"特工區標準-紀錄項目",
 "空氣品質自動監測設施應記錄之項目及紀錄保存年限為何？",
 ["應記錄濃度小時、日、月平均值、零點及全幅偏移值、校正紀錄、超過空氣品質標準次數百分比等；紀錄應保存五年備查","應記錄濃度小時、日、月平均值、零點及全幅偏移值、校正紀錄、超過空氣品質標準次數百分比等；紀錄應保存二年備查","僅需記錄各監測項目之月平均值及年平均值，並註明超標次數；紀錄應保存三年，供主管機關隨時查核使用","僅需記錄零點及全幅偏移值與例行保養維修時間；濃度數據因已連線傳輸主管機關，故免另行製作保存紀錄"],"a",
 "第18條第1項：自動監測設施應記錄監測項目及量測濃度值（含小時、日、月平均值、每日最高最低小時平均值、每月最高最低日平均值、每月有效小時紀錄值百分比）、氣象項目及小時平均值、零點及全幅偏移值、例行保養維修、標準品檢查、校正、精密度準確度測試、超過空氣品質標準之次數及百分比等。同條第3項：紀錄應保存五年，以備主管機關查核。",
 "What must automatic monitoring facilities record, and how long are records kept?",
 ["Hourly, daily and monthly averages, zero and span drift, calibration records, and exceedance counts and percentages; records kept five years","Hourly, daily and monthly averages, zero and span drift, calibration records, and exceedance counts and percentages; records kept two years","Only monthly and annual averages of each item with exceedance counts noted; records kept three years for inspection at any time","Only zero and span drift and routine maintenance times; concentration data need no records because they are transmitted online"],
 "Article 18, Paragraphs 1 and 3."),

(L1,"第18條",2,"特工區標準-人工紀錄",
 "空氣品質人工操作監測設施應記錄之項目為何？",
 ["監測項目、採樣地點、採樣開始及結束時間、流量及體積、樣品分析時間、量測濃度值","監測項目、採樣人員姓名證號、採樣車輛車牌、氣象條件、樣品運送溫度及保存期限","監測項目、零點及全幅偏移值、例行保養維修時間、標準品檢查紀錄及精密度測試紀錄","監測項目、超過空氣品質標準之次數與百分比、每月有效小時紀錄值百分比及改善方式"],"a",
 "第18條第2項：空氣品質人工操作監測設施應記錄之項目為監測項目、採樣地點、採樣開始及結束時間、流量及體積、樣品分析時間、量測濃度值。同條第3項規定前二項紀錄應保存五年，以備主管機關查核。",
 "What items must manual air quality monitoring facilities record?",
 ["Monitored items, sampling location, start and end times, flow and volume, analysis time, and measured concentrations","Monitored items, sampler names and ID numbers, vehicle plates, weather conditions, transport temperature and holding time","Monitored items, zero and span drift values, routine maintenance times, standard checks and precision test records","Monitored items, exceedance counts and percentages, monthly valid hour percentages and the improvement measures taken"],
 "Article 18, Paragraphs 2 and 3."),

(L1,"第19條",3,"特工區標準-連線申報",
 "特殊性工業區監測中心之數據連線對象，及人工操作監測結果之申報期限為何？",
 ["應與工業區所在地及監測站所在地之直轄市、縣（市）主管機關連線；人工監測按季於二月、五月、八月及十一月底前申報前一季紀錄","應與中央主管機關及所在地鄉鎮市區公所連線；人工監測按季於一月、四月、七月及十月底前申報前一季之監測紀錄資料","應與工業區所在地之直轄市、縣（市）主管機關連線即可；人工監測於每年一月底前申報前一年度全年之監測紀錄資料","應與各該工業區之目的事業主管機關連線；人工監測按月於次月十日前申報前一個月之全部監測紀錄與品保紀錄資料"],"a",
 "第19條第2項：監測中心之監測數據應與特殊性工業區所在地及空氣品質監測站所在地之直轄市、縣（市）主管機關連線，輸出訊號及電訊傳輸設施應符合中央主管機關規定。同條第3項：以人工操作監測者，應按季於每年二月、五月、八月及十一月底前向前述主管機關申報前一季之紀錄。第1項並要求自動監測設施應有連續自動記錄輸出訊號之設備。",
 "With whom must the monitoring centre link its data, and when must manual results be reported?",
 ["Link with the local authorities where the park and the stations lie; manual results are reported by the end of February, May, August and November","Link with the central authority and the township office where the park lies; manual results are reported by the end of January, April, July and October","Link only with the local authority where the park lies; manual results are reported by the end of January each year for the whole previous year","Link with the industry regulator of the park; manual results are reported monthly by the tenth day of the following month with QA records"],
 "Article 19."),

(L1,"第20條",1,"特工區標準-品保",
 "空氣品質監測設施之品質保證作業程序應符合何項規定？",
 ["應符合中央主管機關之規定辦理","應符合各該工業區自訂之作業規範","應符合國際標準組織所定作業程序","應符合開發單位環評承諾書之內容"],"a",
 "第20條：空氣品質監測設施之品質保證作業程序，應符合中央主管機關之規定。第18條第1項並要求記錄標準品檢查、校正及精密度準確度測試等品保品管相關紀錄，保存五年備查。",
 "Whose rules must the quality assurance procedures for monitoring facilities follow?",
 ["They must follow the rules of the central competent authority","They must follow the park's own self-prescribed procedures","They must follow the procedures of the ISO standards body","They must follow the developer's EIA commitment documents"],
 "Article 20; see also Article 18."),

(L1,"第21條",1,"特工區標準-施行",
 "本標準之施行日期規定為何？",
 ["本標準除已另定施行日期者外，自發布日施行","本標準一律自發布後屆滿一年之日起開始施行","本標準除已另定者外，自次年七月一日起施行","本標準自中央主管機關另以公告指定之日施行"],"a",
 "第21條：本標準除已另定施行日期者外，自發布日施行。第3條第3項另就一百零一年九月二十二日前已開發之特殊性工業區，定有一百零三年三月三十一日前提出設置計畫之特別期限。",
 "When do these Standards take effect?",
 ["They take effect on the date of promulgation unless another date is set","They uniformly take effect upon expiry of one year from promulgation","Unless otherwise set they take effect on 1 July of the following year","They take effect on a date separately designated by public notice"],
 "Article 21; see also Article 3."),

# ===== ENV-125 移動污染源空氣污染防制設備管理辦法 =====
(L3,"第1條",1,"移動源設備-法源",
 "移動污染源空氣污染防制設備管理辦法之訂定法源依據為何？",
 ["依空氣污染防制法第三十七條第二項規定訂定之","依空氣污染防制法第三十六條第三項規定訂定之","依空氣污染防制法第二十三條第二項規定訂定","依道路交通管理處罰條例第九十二條規定訂定"],"a",
 "第1條：本辦法依空氣污染防制法第三十七條第二項規定訂定之。第2條並列舉機動車輛空氣污染防制設備之種類；第7條規定本辦法自發布日施行。",
 "What is the legal basis for the Regulations for Management of Mobile Source Air Pollution Control Equipment?",
 ["Adopted under Article 37, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 36, Paragraph 3 of the Air Pollution Control Act","Adopted under Article 23, Paragraph 2 of the Air Pollution Control Act","Adopted under Article 92 of the Road Traffic Management Penalty Act"],
 "Article 1; see also Articles 2 and 7."),

(L3,"第2條",2,"移動源設備-種類",
 "本辦法所列機動車輛空氣污染防制設備之種類，包括下列何者？",
 ["觸媒轉化器、排氣再循環系統、蒸發排放活性碳罐、曲軸箱通氣閥、含氧量感知器及濾煙器等設備","觸媒轉化器、渦輪增壓器、燃油噴射泵、水箱冷卻風扇、汽車電瓶及輪胎氣壓偵測系統等設備","消音器、避震器、排氣管尾段、隔熱護板、進氣濾清器及冷氣壓縮機等與排氣相關之各項裝置","行車紀錄器、衛星定位裝置、胎壓偵測器、防鎖死煞車系統及車道偏離警示系統等車用電子設備"],"a",
 "第2條第1款：機動車輛空氣污染防制設備包括觸媒轉化器、排氣再循環系統、蒸發排放活性碳罐、曲軸箱通氣閥、熱反應器、二次空氣供給泵、二次空氣控制閥、含氧量感知器、減速控制裝置、濾煙器、濾煙器再生裝置、車上診斷系統、電子控制單元及其他經中央主管機關指定公告之設備。",
 "Which of the following are listed as motor vehicle air pollution control equipment?",
 ["Catalytic converter, exhaust gas recirculation, evaporative canister, PCV valve, oxygen sensor and particulate filter","Catalytic converter, turbocharger, fuel injection pump, radiator cooling fan, vehicle battery and tyre pressure sensing system","Muffler, shock absorber, tailpipe section, heat shield, intake air cleaner and air conditioning compressor related to exhaust","Dashcam, satellite positioning unit, tyre pressure monitor, anti-lock braking system and lane departure warning electronics"],
 "Article 2, Subparagraph 1."),

(L3,"第2條",2,"移動源設備-其他移動源",
 "火車、船舶、航空器及其他水上動力機具之空氣污染防制設備種類，應如何規範？",
 ["中央主管機關得另行公告其設備之種類","由各該目的事業主管機關逐案核定認可","準用本辦法所列機動車輛設備種類規定","由製造者或進口商自行申報並公開登載"],"a",
 "第2條第2款：火車、船舶、航空器及其他水上動力機具空氣污染防制設備之種類，中央主管機關得另行公告之。第3條並規定移動污染源製造者或進口商所使用之空氣污染防制設備，應經中央主管機關核准。",
 "How are the equipment categories for trains, vessels, aircraft and other watercraft prescribed?",
 ["The central competent authority may separately announce their categories","Each relevant industry regulator approves and recognizes them case by case","The motor vehicle equipment categories in these Regulations apply mutatis mutandis","Manufacturers or importers declare and publicly register them by themselves"],
 "Article 2, Subparagraph 2; see also Article 3."),

(L3,"第3條",2,"移動源設備-核准",
 "移動污染源製造者或進口商所使用之空氣污染防制設備，其核准規定為何？",
 ["應經中央主管機關核准；其種類、規格或標識變更時，亦需經中央主管機關核准","應經中央主管機關核准；其種類、規格或標識變更時，僅需報請地方主管機關備查","應向當地主管機關申請登記；其種類、規格或標識變更時，得逕行變更免另申請","應經交通主管機關檢驗合格；其種類、規格或標識變更時，應重新辦理車輛登檢"],"a",
 "第3條第1項、第2項：移動污染源製造者或進口商於移動污染源上所使用之空氣污染防制設備，應經中央主管機關核准；前項空氣污染防制設備之種類、規格或標識變更時，需經中央主管機關核准。第5條並規定使用人或所有人更換設備時，應更換經核准之空氣污染防制設備。",
 "What approval applies to air pollution control equipment used by mobile source makers or importers?",
 ["It must be approved by the central competent authority, and changes of type, specification or marking also need approval","It must be approved by the central competent authority, but changes of type, specification or marking only need local filing","It must be registered with the local competent authority, and changes of type, specification or marking need no new application","It must pass inspection by the transport authority, and changes of type, specification or marking require re-registration"],
 "Article 3; see also Article 5."),

(L3,"第4條",2,"移動源設備-標示",
 "經中央主管機關指定公告之移動污染源空氣污染防制設備，其標示義務為何？",
 ["製造者或進口商應於該設備或設備總成上標示明顯可見不易毀損之辨識號碼或型號","製造者或進口商應於車輛行照及出廠證明文件上載明該設備之辨識號碼或型號","使用人或所有人應於每次定期檢驗時自行標示該設備之辨識號碼或製造年份","銷售商應於銷售發票及保固書上標示該設備之辨識號碼、型號及有效使用年限"],"a",
 "第4條：經中央主管機關指定公告之移動污染源空氣污染防制設備，製造者或進口商應於該設備或設備總成上標示明顯可見不易毀損之辨識號碼或型號。第6條並要求於移動污染源上標明設備相關位置圖及標識。",
 "What labelling duty applies to designated mobile source air pollution control equipment?",
 ["Makers or importers must mark a clearly visible and durable identification number or model on the equipment or assembly","Makers or importers must state the identification number or model on the vehicle licence and factory certificate","Users or owners must mark the identification number or year of manufacture themselves at each periodic inspection","Sellers must state the identification number, model and service life on the sales invoice and the warranty card"],
 "Article 4; see also Article 6."),

(L3,"第5條",2,"移動源設備-更換",
 "移動污染源使用人或所有人需更換空氣污染防制設備時，應如何辦理？",
 ["應更換經中央主管機關核准之空氣污染防制設備","應更換原廠出廠時所配置之同型號設備始為合法","應先報請當地主管機關同意後始得更換該項設備","應於更換後三十日內向公路監理機關辦理變更登記"],"a",
 "第5條：經中央主管機關核准使用於移動污染源上之空氣污染防制設備，移動污染源使用人或所有人需更換其空氣污染防制設備時，應更換核准之空氣污染防制設備。第6條並要求加註使用人或所有人不得拆除或改裝非經中央主管機關認證之空氣污染防制設備。",
 "What must a user or owner do when replacing mobile source air pollution control equipment?",
 ["The replacement must be equipment approved by the central competent authority","The replacement must be the identical model originally fitted by the manufacturer","Consent of the local competent authority must be obtained before replacement","Registration of the change must be made with the motor vehicle office in 30 days"],
 "Article 5; see also Article 6."),

(L3,"第6條",2,"移動源設備-位置圖標識",
 "製造者或進口商就移動污染源上之空氣污染防制設備標示義務為何？機車有何特別規定？",
 ["應標明設備相關位置圖及標識並加註不得拆除或改裝非經認證之設備；機車得僅標明其標識","應標明設備相關位置圖及標識並加註設備之保固年限與里程數；機車得免標明任何標識","應標明設備出廠序號及檢驗合格證號並加註更換週期；機車應另標明排氣量與車重","應標明設備之製造商名稱與產地並加註建議售價；機車得僅標明位置圖免標示標識"],"a",
 "第6條：製造者或進口商應於移動污染源上標明空氣污染防制設備相關位置圖及標識，並加註使用人或所有人不得拆除或不得改裝非經中央主管機關認證之空氣污染防制設備；但機車得僅標明其標識。第4條並要求於設備或設備總成上標示辨識號碼或型號。",
 "What must makers or importers mark on the mobile source, and what special rule applies to motorcycles?",
 ["A position diagram and marking of the equipment plus a note barring removal or uncertified modification; motorcycles may show only the marking","A position diagram and marking of the equipment plus the warranty period and mileage; motorcycles need not show any marking at all","The equipment serial number and inspection certificate number plus the replacement interval; motorcycles must also show displacement and weight","The maker's name and country of origin plus a suggested retail price; motorcycles may show only the position diagram without marking"],
 "Article 6; see also Article 4."),

(L3,"第7條",1,"移動源設備-施行",
 "移動污染源空氣污染防制設備管理辦法之施行日期為何？",
 ["本辦法自發布日起施行","本辦法自發布後三個月施行","本辦法自次年一月一日施行","本辦法自發布後一年施行之"],"a",
 "第7條：本辦法自發布日施行。第2條並規定火車、船舶、航空器及其他水上動力機具之空氣污染防制設備種類，中央主管機關得另行公告之。",
 "When do the Regulations for Mobile Source Air Pollution Control Equipment take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect on 1 January of the next year","They take effect one year after promulgation"],
 "Article 7; see also Article 2."),
]
