# -*- coding: utf-8 -*-
# 第 13 批（A1）：補題──空污專責辦法、固定污染源排放標準、空氣品質標準、室內空氣品質標準、環境音量標準
AP = "ENV-26"; ES = "ENV-27"; AQ = "ENV-28"; IQ = "ENV-31"; EN = "ENV-40"
Q = [
# ---------- 空氣污染防制專責單位或專責人員設置及管理辦法（ENV-26） ----------
(AP,"第1條",1,"空污專責-法源",
 "空氣污染防制專責單位或專責人員設置及管理辦法係依何規定訂定？",
 ["依空氣污染防制法第三十四條第四項規定訂定","依空氣污染防制法第二十條第二項規定訂定","依空氣污染防制法第六十九條第一項規定訂定","依空氣污染防制法第五條第三項規定訂定"],"a",
 "第1條：本辦法依空氣污染防制法第三十四條第四項規定訂定之。第2條：專責人員分空氣污染防制專責人員及健康風險評估專責人員，應由經中央主管機關訓練合格並取得合格證書者擔任。空污法第二十條第二項為固定污染源空氣污染物排放標準之授權依據，第五條第三項則為空氣品質標準之授權依據。",
 "The Regulations for dedicated air pollution control units or personnel are enacted under which provision?",
 ["Article 34, Paragraph 4 of the Air Pollution Control Act","Article 20, Paragraph 2 of the Air Pollution Control Act","Article 69, Paragraph 1 of the Air Pollution Control Act","Article 5, Paragraph 3 of the Air Pollution Control Act"],
 "Article 1; Article 20(2) authorizes emission standards and Article 5(3) the ambient air quality standards."),

(AP,"第3條",2,"空污專責-員額",
 "公私場所設置之空氣污染防制專責單位，至少應包括之員額為何？",
 ["甲級空氣污染防制專責人員二人及乙級空氣污染防制專責人員一人","甲級空氣污染防制專責人員一人及乙級空氣污染防制專責人員二人","甲級空氣污染防制專責人員三人及乙級空氣污染防制專責人員二人","甲級空氣污染防制專責人員一人及乙級空氣污染防制專責人員三人"],"a",
 "第3條：空氣污染防制專責人員分甲級及乙級；公私場所設置之專責單位至少應包括甲級專責人員二人、乙級專責人員一人。第7條：應設置專責單位者，代理人至少應設二名。第4條：同一處所內專責單位得與依法設置之廢（污）水處理專責單位合併設置。",
 "A dedicated air pollution control unit must include at least which staffing?",
 ["Two Class A air pollution control personnel and one Class B person","One Class A air pollution control person and two Class B personnel","Three Class A air pollution control personnel and two Class B staff","One Class A air pollution control person and three Class B personnel"],
 "Article 3; see also Articles 4 and 7."),

(AP,"第3條",2,"空污專責-設置等級",
 "空氣污染防制專責單位或專責人員之設置等級，應依下列何者辦理？",
 ["依空氣污染防制法第三十四條第一項及第二項所定公告事項辦理","依直轄市、縣（市）主管機關個案審查核定之等級辦理","依公私場所自行評估污染潛勢之分級結果自主辦理","依固定污染源操作許可證所載排放量級距辦理"],"a",
 "第3條第二項：空氣污染防制專責單位或專責人員之設置等級，應依本法第三十四條第一項及第二項所定公告事項辦理。同條第一項規定空氣污染防制專責人員分甲級及乙級。第2條：專責人員應由經中央主管機關訓練合格並取得合格證書者擔任。",
 "The required grade of a dedicated air pollution control unit or person is determined by:",
 ["The matters published under Article 34, Paragraphs 1 and 2 of the Act","The grade approved case by case by the municipal or county authority","The premises own self-assessed pollution potential grading result","The emission tier written on the stationary source operating permit"],
 "Article 3, Paragraph 2."),

(AP,"第4條",2,"空污專責-合併兼任",
 "同一處所內，空氣污染防制專責單位之合併設置及專責人員之兼任，規定為何？",
 ["得與依法設置之廢（污）水處理專責單位合併設置，人員具資格且級別符合者得互兼","僅得與依法設置之廢棄物清理專責單位合併設置，惟人員一律不得互相兼任","一律不得與其他類專責單位合併設置，人員亦不得兼任其他類專責技術人員","得與任何目的事業主管機關所定專責單位合併，人員無須具備資格即可互兼"],"a",
 "第4條：同一處所內，空氣污染防制專責單位得與其依法設置之廢（污）水處理專責單位合併設置；空污專責人員如具備廢（污）水處理專責人員資格且設置級別均符合規定，得互兼之。同條第二項並允許具健康風險評估專責人員或其他類環境保護專責及技術人員資格者，於同一處所內同時兼任。第5條：專責人員仍應常駐並專職，不得兼任環保法規以外其他法規所定專責（任）人員。",
 "Within the same premises, may the dedicated air unit be merged and may personnel hold concurrent posts?",
 ["Yes, it may merge with the lawful wastewater treatment unit and qualified personnel of matching grade may cross-serve","Only merger with a lawful waste disposal unit is allowed and personnel may never hold concurrent posts","Merger with any other dedicated unit is prohibited and personnel may not serve as other environmental staff","Merger with any unit set by any competent authority is allowed and personnel need no qualification to cross-serve"],
 "Article 4; concurrent service is limited by Article 5."),

(AP,"第6條",2,"空污專責-共同設置",
 "二以上公私場所共同設置空氣污染防制設備共同處理空氣污染物者，共同設置專責單位或人員之要件及級別為何？",
 ["經直轄市、縣（市）主管機關核准者得共同設置；原定級別不一致時應以最高級別設置","經中央主管機關核准者始得共同設置；原定級別不一致時應以最低級別設置","報請直轄市、縣（市）主管機關備查即可；原定級別不一致時由各場所自行協議","經目的事業主管機關同意者得共同設置；原定級別不一致時應以平均級別設置"],"a",
 "第6條：二以上公私場所共同設置空氣污染防制設備共同處理空氣污染物，經直轄市、縣（市）主管機關核准者，得共同設置專責單位或專責人員；原定級別不一致時，應以最高級別設置。第18條第二款規定專責人員不得同一時間設置於不同公私場所，但依法共同設置者不在此限。",
 "When two or more premises jointly install control equipment, joint dedicated staffing requires:",
 ["Approval by the municipal or county authority; where grades differ the highest grade applies","Approval by the central competent authority; where grades differ the lowest grade applies","Only a filing with the municipal or county authority; differing grades are settled by agreement","Consent of the industry competent authority; where grades differ the average grade applies"],
 "Article 6; see also Article 18, Subparagraph 2."),

(AP,"第8條",2,"空污專責-申請設置",
 "公私場所申請核定設置空氣污染防制專責單位或專責人員時，應檢具之文件及申請方式為何？",
 ["檢具合格證書、設置申請書及勞健保查詢同意書等，向直轄市、縣（市）主管機關申請核定","檢具在職訓練證明及環境影響評估報告書，向中央主管機關申請許可並公告周知","檢具固定污染源操作許可證及排放量申報書，向目的事業主管機關報備後即生效","檢具公司登記證明及專責人員身分證影本，向鄉（鎮、市、區）公所辦理登記"],"a",
 "第8條：應檢具專責人員合格證書、設置申請書及同意查詢勞健保資料同意書、代理人具參加同一類別及級別以上專責人員訓練資格之學（經）歷證明及其勞健保查詢同意書，向直轄市、縣（市）主管機關申請核定設置；除經該機關同意得以書面為之外，自中央主管機關指定之日起應採網路傳輸方式辦理。第7條：代理人更動應於十五日內重新申請核定設置。",
 "To obtain approval of dedicated air pollution staffing, the premises must submit what and to whom?",
 ["Certificates, the application form and labor and health insurance consent forms, to the municipal or county authority","On-the-job training records and an environmental impact statement, to the central authority for public notice","The stationary source operating permit and emission reports, filed with the industry competent authority","Company registration papers and copies of ID cards, registered with the township or district office"],
 "Article 8; online filing is required from the date designated by the central authority."),

(AP,"第10條",3,"空污專責-代理期間",
 "空污專責人員非因離職或異動而因故未能執行業務時，代理期間連續達多久應報備查？代理期間最長為何？",
 ["連續達十五日以上者應於事實發生後十五日內報備；代理不得逾三個月，核准得延長至六個月","連續達七日以上者應於事實發生後三日內報備；代理不得逾一個月，核准得延長至三個月","連續達三十日以上者應於事實發生後三十日內報備；代理不得逾六個月，不得再行延長","連續達六十日以上者應於事實發生後十日內報備；代理不得逾一年，核准得延長至二年"],"a",
 "第10條：專責人員非因離職、異動而因故未能執行業務時，應由設置之代理人代理；代理期間連續達十五日以上者，應於事實發生後十五日內以書面報請直轄市、縣（市）主管機關備查。代理期間不得超過三個月，報經核准者得延長至六個月；代理期滿前十五日內應完成同一類別及級別以上之合格專責人員核定設置。第9條之離職、異動代理期間則不得超過三個月且無延長規定。",
 "For absence other than departure or transfer, deputising must be reported when it lasts how long, and the deputy period limit is:",
 ["Fifteen consecutive days or more, reported within fifteen days; three months, extendable to six months if approved","Seven consecutive days or more, reported within three days; one month, extendable to three months if approved","Thirty consecutive days or more, reported within thirty days; six months, with no extension permitted at all","Sixty consecutive days or more, reported within ten days; one year, extendable to two years if approved"],
 "Article 10; compare Article 9."),

(AP,"第11條",3,"空污專責-過渡代理人",
 "本辦法修正施行前已核定設置專責單位或人員者，應於何期限內完成代理人設置？期限內尚未完成者發生代理事由應如何處理？",
 ["修正施行日起六個月內完成；應即指定具訓練資格之人員代理，十五日內報備並三十日內完成設置","修正施行日起三個月內完成；應即停止操作固定污染源，並於七日內函報中央主管機關核備","修正施行日起一年內完成；得暫免指定人員代理，俟主管機關通知後再行補辦相關設置程序","修正施行日起三十日內完成；應由目的事業主管機關逕行指派人員代理並副知公私場所"],"a",
 "第11條：本辦法修正施行前已核定設置專責單位或專責人員者，應於修正施行日起六個月內完成代理人之設置。於該期間內尚未完成者，發生第10條第一項或第9條第一項情形時，應即指定具參加同一類別及級別以上專責人員訓練資格之人員代理；並於事實發生後十五日內書面報請備查，三十日內完成代理人之設置。",
 "Premises approved before this amendment must complete deputy appointment within, and if not yet done:",
 ["Six months from the amendment; immediately designate a qualified person, report in 15 days and appoint in 30 days","Three months from the amendment; immediately shut down the stationary source and report to the central authority","One year from the amendment; no deputy need be designated until the authority issues a further notification","Thirty days from the amendment; the industry competent authority appoints the deputy on the premises behalf"],
 "Article 11."),

(AP,"第12條",2,"空污專責-代操作營運",
 "公私場所之空氣污染防制專責人員或代理人，得否由其委任之代操作營運機構派任？管理責任歸屬為何？",
 ["得由代操作營運機構派任具資格人員申請設置，惟公私場所仍應負本辦法所定管理之責","得由代操作營運機構派任具資格人員申請設置，管理責任隨之移轉由該機構全部承擔","不得由代操作營運機構派任，專責人員限由公私場所正式僱用之員工擔任並負全責","得由代操作營運機構派任而免經主管機關核定，公私場所與該機構均不負管理之責"],"a",
 "第12條：公私場所得以其委任之代操作營運機構派任具資格之人員，依本辦法規定向直轄市、縣（市）主管機關申請設置為該公私場所之專責人員或代理人；除派任外，公私場所仍應負本辦法所定管理之責。第19條並課予公私場所監督專責人員常駐、專職及執行業務之義務。",
 "May a contracted operation and maintenance firm supply the dedicated person, and who bears management duty?",
 ["Yes, it may assign qualified staff for approval, but the premises still bears the management duty under these rules","Yes, it may assign qualified staff for approval, and the management duty transfers wholly to that firm","No, the dedicated person must be a formally hired employee of the premises, which bears full responsibility","Yes, and no approval by the authority is needed; neither the premises nor the firm bears management duty"],
 "Article 12; see also Article 19."),

(AP,"第14條",2,"空污專責-風險評估業務",
 "健康風險評估專責人員或其代理人應執行之業務為何？",
 ["評估公私場所排放有害空氣污染物之健康風險，並執行健康風險管理及降低風險工作","核發固定污染源設置及操作許可證，並辦理排放量申報之審查及空污費費額核算","擬定排放管道及周界檢測作業計畫，並負責採樣孔與安全採樣平台之設置維護","受理民眾陳情案件並派員稽查取締，辦理環境影響評估書件之審查及公告作業"],"a",
 "第14條：健康風險評估專責人員或依規定設置之代理人，應執行評估公私場所排放有害空氣污染物之健康風險，以及執行空氣污染之健康風險管理及降低健康風險之相關工作。第13條則規定空氣污染防制專責人員之業務，包括擬定防制及改善計畫、監督防制與監測設施運作、緊急應變、許可證申請與申報、檢測作業及採樣設施監督等。",
 "What duties must health risk assessment dedicated personnel perform?",
 ["Assess health risks of hazardous air pollutants emitted by the premises and carry out risk management and reduction","Issue stationary source installation and operating permits and review emission declarations and fee calculations","Draft stack and boundary monitoring plans and maintain sampling ports and safety sampling platforms","Handle public complaints and inspections and review and publish environmental impact assessment documents"],
 "Article 14; compare Article 13."),

(AP,"第15條",3,"空污專責-到職訓練",
 "專責人員取得合格證書後連續多久未經依法設置者，應完成到職訓練？期限為何？公私場所應於何時備查？",
 ["連續三年以上；應於到職之翌日起六個月內完成；設置屆滿六個月後十五日內檢具證明備查","連續一年以上；應於到職之翌日起三個月內完成；設置屆滿三個月後三十日內檢具證明備查","連續五年以上；應於到職之翌日起一年內完成；設置屆滿一年後六十日內檢具證明備查","連續二年以上；應於到職之翌日起三十日內完成；設置屆滿一年後七日內檢具證明備查"],"a",
 "第15條第一項、第二項：專責人員取得合格證書後連續三年以上未經依法設置為專責人員者，應於到職之翌日起六個月內依中央主管機關規定完成到職訓練；設置屆滿六個月後十五日內，公私場所應檢具完成到職訓練之證明文件報請直轄市、縣（市）主管機關備查。第20條第四款規定未備查者依本法第69條第1項第1款處罰。",
 "After holding a certificate without appointment for how long is refresher on-boarding training required, by when, and when must it be filed?",
 ["Three years or more; within six months from the day after taking office; filed within fifteen days after six months","One year or more; within three months from the day after taking office; filed within thirty days after three months","Five years or more; within one year from the day after taking office; filed within sixty days after one year","Two years or more; within thirty days from the day after taking office; filed within seven days after one year"],
 "Article 15, Paragraphs 1 and 2."),

(AP,"第15條",3,"空污專責-廢止核定",
 "專責人員未依規定期限完成到職訓練，或公私場所未依限完成備查者，法律效果為何？",
 ["主管機關應廢止專責人員之設置核定，公私場所並應於十五日內重新申請核定設置","主管機關應廢止專責人員之合格證書，公私場所並應於三十日內重新申請訓練資格","主管機關應命公私場所限期改善，屆期未改善始得廢止其固定污染源操作許可證","主管機關應逕予處以罰鍰並命停工，公私場所毋須重新申請專責人員核定設置"],"a",
 "第15條第三項：專責人員未於規定期限內完成到職訓練，或公私場所未於規定期限內完成備查者，直轄市、縣（市）主管機關應廢止公私場所專責人員之設置核定，公私場所並應於十五日內重新申請專責人員核定設置。第22條：重新申請者，原申請設置書自應完成設置之期限屆滿翌日起失其效力。第20條第五款對逾期未重新申請者定有處罰。",
 "If on-boarding training or its filing is not completed on time, the consequence is:",
 ["The authority shall revoke the approval and the premises must re-apply for approval within fifteen days","The authority shall revoke the qualification certificate and the premises must re-apply for training in thirty days","The authority shall order improvement within a time limit and only then revoke the operating permit","The authority shall impose a fine and order shutdown, with no need to re-apply for approval of personnel"],
 "Article 15, Paragraph 3; see also Articles 20 and 22."),

(AP,"第16條",2,"空污專責-請假紀錄",
 "依本辦法設置之專責人員因故未能常駐在廠（場）者，應如何處理？",
 ["應備有請假紀錄或其他相關證明文件，以備主管機關查閱","應於當日以電話向直轄市、縣（市）主管機關口頭報告事由","應立即停止固定污染源之操作，直至專責人員返回廠場為止","應由公私場所負責人親自代理，並免除備置任何證明文件"],"a",
 "第16條第一項：依本辦法規定設置之專責人員，因故未能常駐在廠（場）者，應備有請假紀錄或其他相關證明文件，以備查閱。第19條第二款：公私場所應備有請假紀錄簿（單）供填寫，且該紀錄或證明文件應至少保存三年。第20條第九款：未備置或未保存三年者，依本法第69條第1項第1款處罰。",
 "If a dedicated person cannot stay stationed at the plant, what must be done?",
 ["Keep leave records or other supporting documents available for inspection","Report the reason orally by telephone to the municipal or county authority","Immediately stop operating the stationary source until the person returns","Have the responsible person deputise, with no documentation required at all"],
 "Article 16, Paragraph 1; see also Articles 19 and 20."),

(AP,"第16條",3,"空污專責-不得續任",
 "專責人員於勞基法所定休息、休假日數外，發生何種情形即不得再繼續設置為該場所之專責人員？公私場所應於何時重新申請？",
 ["半年內累積超過三十日未到職，或一年內三次以上未備請假紀錄；三十日內重新申請核定","一年內累積超過三十日未到職，或半年內二次以上未備請假紀錄；十五日內重新申請核定","半年內累積超過六十日未到職，或一年內五次以上未備請假紀錄；六個月內重新申請核定","一年內累積超過九十日未到職，或二年內三次以上未備請假紀錄；七日內重新申請核定"],"a",
 "第16條第二項：專責人員於勞動基準法所定休息、休假規定之日數外，半年內累積超過三十日未到職，或經主管機關查獲一年內三次以上未依第一項備有請假紀錄或證明文件者，不得再繼續設置為該公私場所之專責人員；公私場所應於該事實發生後三十日內重新申請核定設置。第20條第六款對逾期未申請者定有處罰。",
 "Apart from statutory rest days, when may a person no longer continue as the dedicated person, and when must re-application be made?",
 ["Over thirty days absent within half a year, or three failures to keep leave records in a year; re-apply in thirty days","Over thirty days absent within a year, or two failures to keep leave records in half a year; re-apply in fifteen days","Over sixty days absent within half a year, or five failures to keep leave records in a year; re-apply in six months","Over ninety days absent within a year, or three failures to keep leave records in two years; re-apply in seven days"],
 "Article 16, Paragraph 2."),

(AP,"第17條",1,"空污專責-在職訓練",
 "關於專責人員參加中央主管機關指定之在職訓練，公私場所之義務為何？",
 ["不得以任何方式妨礙或禁止專責人員參加中央主管機關指定之在職訓練","得視固定污染源操作需要，暫緩或禁止專責人員參加該項在職訓練","僅須於專責人員受訓期間指派代理人，並得要求其自費參加該訓練","得以書面同意權決定專責人員是否參加，並報請主管機關核備即可"],"a",
 "第17條：公私場所不得以任何方式妨礙、禁止專責人員參加中央主管機關指定之在職訓練。第20條第七款：有第17條情形者，依本法第69條第1項第1款規定處罰。第19條並要求公私場所監督專責人員常駐、專職及執行第13條或第14條所定業務。",
 "Regarding designated on-the-job training, the premises duty is:",
 ["It may not by any means obstruct or prohibit the dedicated person from attending the designated training","It may postpone or bar attendance where the operation of the stationary source so requires","It need only appoint a deputy during training and may require the person to pay the fees","It may decide by written consent whether the person attends and merely file this with the authority"],
 "Article 17; penalties under Article 20, Subparagraph 7."),

(AP,"第19條",3,"空污專責-監督義務",
 "公私場所應令其設置之專責人員或代理人符合之規定，下列何者正確？",
 ["監督常駐並專職負責法定業務、備有請假紀錄簿並至少保存三年、監督執行業務且不得有禁止行為","監督每月到場一次並得兼職、備有出勤紀錄並保存一年、僅須監督執行業務而無其他限制","監督常駐並得兼任其他法規所定專責人員、備有請假紀錄並保存六個月、免除監督業務執行","監督由代操作營運機構自行管理、備有訓練紀錄並保存五年、由該機構承擔全部監督責任"],"a",
 "第19條：公私場所應令所設置之專責人員或代理人符合下列規定：依第5條監督其於勞動基準法所定工作時間內常駐並專職負責第13條或第14條所定業務；依第16條第一項備有請假紀錄簿（單）供填寫，該紀錄或證明文件至少保存三年；監督其執行第13條或第14條業務，且不得有第18條所定之行為。第20條第八款至第十款對違反者定有處罰。",
 "Which correctly states what the premises must ensure of its dedicated personnel or deputies?",
 ["Supervise full-time stationing and statutory duties, keep leave logs for at least three years, and supervise conduct","Supervise a monthly site visit with concurrent posts allowed, keep attendance logs one year, no other limits","Supervise stationing while allowing other statutory posts, keep leave logs six months, no duty supervision","Let the contracted operating firm self-manage, keep training logs five years, and shift all supervision to it"],
 "Article 19; penalties under Article 20."),

(AP,"第20條",3,"空污專責-場所罰則",
 "下列何種情形，公私場所應依空氣污染防制法第六十九條第一項第一款規定處罰？",
 ["未依本法第三十四條第一項及第二項規定設置專責單位或專責人員者","專責人員一年內二次以上未常駐且未備請假紀錄或其他證明文件者","專責人員同一時間設置於不同之公私場所且非屬依法共同設置者","專責人員明知為不實事項而申報不實或於業務文書為虛偽記載者"],"a",
 "第20條第一款：公私場所未依本法第三十四條第一項及第二項規定設置專責單位或專責人員者，依本法第69條第1項第1款規定處罰。其餘選項所述均屬第18條所定專責人員本身之禁止行為，依第21條規定係對專責人員依本法第69條第2項處罰，處罰對象不同。",
 "Which situation subjects the premises to penalty under Article 69(1)(1) of the Air Pollution Control Act?",
 ["Failing to set up a dedicated unit or personnel as required by Article 34, Paragraphs 1 and 2 of the Act","The dedicated person twice in a year not being stationed on site and keeping no leave records at all","The dedicated person being appointed at different premises at the same time without lawful joint setup","The dedicated person knowingly filing false declarations or making false entries in business documents"],
 "Article 20, Subparagraph 1; the others fall under Articles 18 and 21."),

(AP,"第20條",3,"空污專責-場所罰則二",
 "依第20條規定，公私場所有下列何種違失亦依本法第六十九條第一項第一款處罰？",
 ["未備有請假紀錄簿（單），或該請假紀錄簿（單）未依規定保存三年","專責人員一年內二次以上未依規定常駐公私場所執行其法定業務","專責人員使他人利用其名義虛偽設置為該場所之專責人員或代理人","專責人員預見違法發生而不違背本意，違反本法且有第九十六條情事"],"a",
 "第20條第九款：公私場所未依第19條第二款規定備有請假紀錄簿（單），或該請假紀錄簿（單）未保存三年者，依本法第69條第1項第1款處罰。第20條並列有妨礙專責人員參加在職訓練、使專責人員兼任無關工作、未執行監督致專責人員違規等情形。其餘選項為第18條所定行為，依第21條對專責人員處罰。",
 "Which further failing of the premises is penalised under Article 69(1)(1)?",
 ["Not keeping a leave record book, or not retaining that leave record book for three years","The dedicated person failing twice in a year to be stationed on site to perform statutory duties","The dedicated person letting another party falsely use his or her name for the appointment","The dedicated person foreseeing and accepting a violation of the Act under Article 96"],
 "Article 20, Subparagraph 9; the others are Article 18 conduct penalised under Article 21."),

(AP,"第21條",3,"空污專責-人員罰則",
 "專責人員有何情形應依本法第六十九條第二項處罰？其所稱一年內如何計算？",
 ["一年內二次以上未常駐且未備請假紀錄，或違反第十八條各款之一；自違規日往前回溯至第三百六十五日止","一年內三次以上未常駐且未備請假紀錄，或違反第十九條各款之一；自違規日往後推算至第三百六十五日止","半年內二次以上未常駐且未備出勤紀錄，或違反第二十條各款之一；自查獲日往前回溯至第一百八十日止","二年內一次以上未常駐且未備請假紀錄，或違反第十七條各款之一；自處分日往前回溯至第七百三十日止"],"a",
 "第21條：專責人員一年內二次以上未依第5條第一項規定常駐公私場所，且未依第16條第一項備有請假紀錄或其他證明文件，或違反第18條各款情形之一者，依本法第69條第2項規定處罰。所稱一年內，指本辦法修正施行後之違規行為，自違規之日起往前回溯至第三百六十五日止。第18條所列包括同時設置於不同場所、使他人虛偽設置、申報不實等。",
 "When is the dedicated person penalised under Article 69, Paragraph 2, and how is the one-year period counted?",
 ["Twice in a year not stationed with no leave records, or breach of Article 18; counted back 365 days from the violation","Three times in a year not stationed with no leave records, or breach of Article 19; counted forward 365 days","Twice in half a year not stationed with no attendance records, or breach of Article 20; back 180 days from detection","Once in two years not stationed with no leave records, or breach of Article 17; back 730 days from the disposition"],
 "Article 21; conduct listed in Article 18."),

(AP,"第22條",2,"空污專責-原設置書失效",
 "依本辦法規定重新申請專責單位或專責人員核定設置者，其原申請設置書效力為何？",
 ["自應完成設置之期限屆滿之翌日起失其效力","自主管機關核准新設置申請之日起失其效力","自重新申請書送達主管機關之日起失其效力","自原專責人員離職或異動之當日起失其效力"],"a",
 "第22條：依本辦法規定重新申請空氣污染防制專責單位或專責人員核定設置者，其原申請設置書自應完成設置之期限屆滿之翌日起，失其效力。第15條第三項、第16條第二項及第20條第五款、第六款均定有應重新申請核定設置之期限，逾期並有處罰。",
 "When does the original application document lose effect where re-application is required?",
 ["From the day after the deadline for completing the appointment expires","From the day the authority approves the new application for appointment","From the day the re-application is delivered to the competent authority","From the day the former dedicated person leaves or is transferred away"],
 "Article 22."),

(AP,"第23條",1,"空污專責-施行",
 "空氣污染防制專責單位或專責人員設置及管理辦法之施行日期規定為何？",
 ["本辦法自發布日施行","本辦法自公布後一年施行","本辦法自發布後六個月施行","本辦法自中央主管機關指定日施行"],"a",
 "第23條：本辦法自發布日施行。相對而言，室內空氣品質管理法第24條規定自公布後一年施行，室內空氣品質標準第5條則明定自中華民國一百零一年十一月二十三日起施行，立法體例不同。",
 "When do these Regulations take effect?",
 ["From the date of promulgation","One year after promulgation","Six months after promulgation","On a date designated centrally"],
 "Article 23."),

# ---------- 固定污染源空氣污染物排放標準（ENV-27） ----------
(ES,"第1條",1,"固污排放-法源",
 "固定污染源空氣污染物排放標準係依何規定訂定？",
 ["依空氣污染防制法第二十條第二項規定訂定","依空氣污染防制法第三十四條第四項規定訂定","依空氣污染防制法第五條第三項規定訂定","依空氣污染防制法第十四條第二項規定訂定"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項規定訂定之。空污法第三十四條第四項為空氣污染防制專責單位或專責人員設置及管理辦法之授權依據，第五條第三項則為空氣品質標準之授權依據，三者不同。",
 "The Stationary Pollution Source Air Pollutant Emission Standards are enacted under:",
 ["Article 20, Paragraph 2 of the Air Pollution Control Act","Article 34, Paragraph 4 of the Air Pollution Control Act","Article 5, Paragraph 3 of the Air Pollution Control Act","Article 14, Paragraph 2 of the Air Pollution Control Act"],
 "Article 1."),

(ES,"第2條",2,"固污排放-適用範圍",
 "本標準之適用對象為何？特定業別、區域或設施另訂有排放標準時應如何適用？",
 ["適用於新設立或變更、或既存之固定污染源；特定業別、區域或設施另訂者應優先適用該標準","僅適用於新設立或變更之固定污染源；特定業別另訂標準者仍應優先適用本標準之規定","適用於固定污染源及移動污染源；特定區域另訂標準者由公私場所自行選擇適用之標準","僅適用於既存之固定污染源；特定設施另訂標準者應由中央主管機關個案指定其適用"],"a",
 "第2條：本標準適用於新設立或變更、或既存之固定污染源（分別簡稱新污染源、既存污染源），其標準如附表；但特定業別、區域或設施另訂有排放標準者，應優先適用該標準。第4條並就既存污染源與新污染源之認定訂有以八十一年四月十一日、十二日為分界之原則。",
 "Whom does this Standard apply to, and what if a sector, area or facility has its own standard?",
 ["It applies to new, modified and existing stationary sources; a sector, area or facility standard prevails","It applies only to new or modified stationary sources; this Standard still prevails over sector standards","It applies to stationary and mobile sources; where an area standard exists the source may choose either","It applies only to existing stationary sources; facility standards apply only if designated case by case"],
 "Article 2; see also Article 4."),

(ES,"第3條",2,"固污排放-名詞定義",
 "依本標準之專用名詞定義，周界、K 及 Nm³ 之意義分別為何？",
 ["周界指公私場所所使用或管理之界線；K 為凱氏絕對溫度 K＝273＋℃；Nm³ 指凱氏溫度二百七十三度及一大氣壓下每立方公尺體積","周界指距離廠房外牆十公尺之範圍線；K 為攝氏溫度 K＝℃－273；Nm³ 指凱氏溫度二百度及一大氣壓下每立方公尺體積","周界指工業區編定使用之土地界線；K 為華氏絕對溫度 K＝459＋℉；Nm³ 指常溫二十五度及一大氣壓下每立方公尺體積","周界指排放管道中心向外十二度俯角線；K 為排氣密度係數 K＝273－℃；Nm³ 指標準狀態下每分鐘立方公尺排氣量"],"a",
 "第3條：周界指公私場所所使用或管理之界線；K 為凱氏絕對溫度，K＝273＋℃；Nm³ 指凱氏溫度二百七十三度及一大氣壓下每立方公尺體積；mg 為毫克（○‧○○一公克）、μg 為微克（○‧○○一毫克）、ppm 為百萬分之一。第5條並規定周界測定應在周界外任何能判定污染物由該場所排放之地點為之。",
 "Under the definitions, what do boundary, K and Nm3 mean?",
 ["Boundary is the line used or managed by the premises; K is absolute Kelvin K=273+C; Nm3 is cubic metres at 273 K and one atmosphere","Boundary is a line ten metres outside the plant wall; K is Celsius K=C-273; Nm3 is cubic metres at 200 K and one atmosphere","Boundary is the zoned land line of the industrial park; K is Rankine K=459+F; Nm3 is cubic metres at 25 C and one atmosphere","Boundary is the twelve degree depression line from the stack; K is a gas density factor K=273-C; Nm3 is cubic metres per minute"],
 "Article 3; see also Article 5."),

(ES,"第3條",3,"固污排放-符號基準",
 "依本標準定義，排氣含氧百分率實測值 Os 超過二十％時如何計算？地面十公尺高度平均風速 u0 之計算參考基準為何？",
 ["Os 超過二十％則以二十％計算之；u0 以年平均風速三‧五公尺／秒為計算之參考基準","Os 超過二十％則以二十一％計算之；u0 以年平均風速五‧○公尺／秒為計算之參考基準","Os 超過十五％則以十五％計算之；u0 以年平均風速二‧五公尺／秒為計算之參考基準","Os 超過二十％則維持實測值計算；u0 以年平均風速十‧○公尺／秒為計算之參考基準"],"a",
 "第3條第二十七款：Os 為排氣中含氧百分率之實測值，如超過二十％，則以二十％計算之。第二十一款：u0 為地面十公尺高度之平均風速，本標準以年平均風速三‧五公尺／秒為計算之參考基準。第二十八款另定影像判煙，指依中央主管機關規定方法以數位影像拍攝設備及辨識軟體判定排放口廢氣不透光率。第11條規定濃度校正公式 C＝[（21－On）／（21－Os）]×Cs。",
 "If measured oxygen percentage Os exceeds twenty percent, how is it counted, and what reference wind speed applies to u0?",
 ["Os above twenty percent is counted as twenty percent; u0 uses an annual mean wind speed of 3.5 m/s","Os above twenty percent is counted as twenty-one percent; u0 uses an annual mean wind speed of 5.0 m/s","Os above fifteen percent is counted as fifteen percent; u0 uses an annual mean wind speed of 2.5 m/s","Os above twenty percent keeps the measured value; u0 uses an annual mean wind speed of 10.0 m/s"],
 "Article 3, Subparagraphs 21, 27 and 28; see also Article 11."),

(ES,"第6條",2,"固污排放-取樣時間",
 "周界測定之取樣時間規定為何？",
 ["粒狀污染物為一小時；硫氧化物為一小時；其餘表列氣體污染物以三十分鐘為原則","粒狀污染物為三十分鐘；硫氧化物為三十分鐘；其餘表列氣體污染物以一小時為原則","粒狀污染物為二十四小時；硫氧化物為八小時；其餘表列氣體污染物以四小時為原則","粒狀污染物為十分鐘；硫氧化物為十五分鐘；其餘表列氣體污染物以六分鐘為原則"],"a",
 "第6條：周界測定之取樣時間，粒狀污染物為一小時；氣體污染物中硫氧化物取樣時間為一小時，其餘表列之氣體污染物採樣時間以三十分鐘為原則；但測定方法已明訂採樣時間者，依該測定方法為之。第5條規定周界測定地點，無法於周界外選點時得於廠界內三公尺處測定，並得於第一次被告發之次日起三十日內申請周界再認定。",
 "What sampling times apply to boundary measurement?",
 ["One hour for particulates; one hour for sulphur oxides; thirty minutes in principle for other listed gases","Thirty minutes for particulates; thirty minutes for sulphur oxides; one hour in principle for other gases","Twenty-four hours for particulates; eight hours for sulphur oxides; four hours in principle for other gases","Ten minutes for particulates; fifteen minutes for sulphur oxides; six minutes in principle for other gases"],
 "Article 6; see also Article 5."),

(ES,"第8條",2,"固污排放-管道高度",
 "排放標準中列有排放管道排放標準之空氣污染物，新污染源之排放管道高度應如何決定？",
 ["應依本標準第八條所定公式計算之，以求得該新污染源應有之排放管道高度","由公私場所依廠區地形及建物高度自行決定，並報請主管機關備查即可","一律以三十公尺為最低高度，不需另行計算亦不受其他條文規定之限制","由目的事業主管機關於核發工廠登記時逕行指定，主管機關不得再變更"],"a",
 "第8條：排放標準中列有排放管道排放標準之空氣污染物，新污染源之排放管道高度應依所定公式計算之。第7條則規定未列排放管道排放標準之氣體污染物，依低排放管道（h≦6m）及較高排放管道（h>6m）分別以 q＝a2‧b2 等公式計算。第9條並規定附表列有換算常數值者，應依第七條至第八條分別計算取較高者為其管道高度。",
 "For pollutants with a stack emission standard, how is the stack height of a new source set?",
 ["It must be calculated by the formula prescribed in Article 8 of this Standard for the new source","The premises decides it from terrain and building height and merely files this with the authority","A uniform minimum of thirty metres applies with no calculation and no other article limiting it","The industry competent authority fixes it when issuing factory registration and it cannot change"],
 "Article 8; see also Articles 7 and 9."),

(ES,"第9條",3,"固污排放-換算常數",
 "新污染源排放之污染物於附表中列有換算常數值者，其排放管道高度如何認定？主管機關處理既存污染源陳情案件時有何權限？",
 ["應依第七條至第八條計算方法分別計算取較高者；得命既存污染源改善排放濃度或準用規定變更管道高度","應依第七條至第八條計算方法分別計算取較低者；僅得命既存污染源限期改善排放濃度而不得變更管道","應由公私場所自行擇一計算方法計算即可；僅得命既存污染源停工停業而不得要求變更其管道高度","應以附表所列固定高度為準毋須計算；得逕行廢止既存污染源之操作許可證並命其拆除排放管道"],"a",
 "第9條：新污染源排放之污染物於附表中列有換算常數值者，應依第七條至第八條所定計算方法分別計算排放管道高度之較高者，為其排放管道高度；主管機關於處理對既存污染源之陳情案件時，得命該既存污染源改善其排放濃度或準用前項規定變更其排放管道高度。第10條並規定採多重污染防制措施者，經核准始得建築低於第九條高度之排放管道。",
 "Where a conversion constant is listed, how is the new source stack height determined, and what may the authority do about complaints against existing sources?",
 ["Calculate under Articles 7 and 8 and take the higher; it may order concentration improvement or a height change","Calculate under Articles 7 and 8 and take the lower; it may only order improvement, never a height change","The premises may choose either method freely; the authority may only order shutdown of the source","Use the fixed height in the appendix without calculation; the authority may revoke the permit and order removal"],
 "Article 9; see also Article 10."),

(ES,"第10條",3,"固污排放-多重防制",
 "公私場所對污染源採多重污染防制措施，欲建築低於第九條所規定高度之排放管道者，應如何辦理？其排放標準如何認定？",
 ["應檢具書面資料報請當地主管機關核准後始得建築；以實際管道高度計算之最高許可排放量為排放標準","應報請中央主管機關備查後即得逕行建築；仍以第九條計算之管道高度所對應之排放量為排放標準","應取得目的事業主管機關同意後始得建築；以附表所列周界標準值之二倍為其最高許可排放量","應於完工後三十日內函報主管機關備查；以實際測得之排放濃度作為其最高許可排放量之上限"],"a",
 "第10條：公私場所對污染源採多重污染防制措施者，應檢具書面資料報請當地主管機關核准後，始得建築低於第九條所規定高度之排放管道；並應以實際排放管道高度依第九條或中央主管機關認可之計算公式計算之最高許可排放量為排放標準，且其最高許可排放量不得超過本標準之排放管道排放標準。",
 "To build a stack lower than Article 9 requires when multiple control measures are used, the source must:",
 ["Submit documents and obtain local authority approval first; the permitted rate is computed from the actual height","File with the central authority and build at once; the rate stays that of the Article 9 calculated height","Obtain the industry authority consent first; the permitted rate is twice the listed boundary standard value","File within thirty days after completion; the measured concentration becomes the maximum permitted rate"],
 "Article 10; the rate may not exceed the stack emission standard."),

(ES,"第12條",1,"固污排放-檢測方法",
 "本標準相關之檢測方法及品質管制事項，依何者之規定辦理？",
 ["依中央主管機關之規定辦理","依直轄市、縣（市）主管機關之規定辦理","依目的事業主管機關之規定辦理","依公私場所自訂之品保計畫辦理"],"a",
 "第12條：本標準相關之檢測方法及品質管制事項，依中央主管機關之規定。第13條並規定設置連續自動監測設施者，粒狀污染物不透光率六分鐘紀錄值高於標準值之累積時間不得超過四小時，氣狀污染物一小時紀錄值高於標準值之累積時間不得超過二小時。",
 "Testing methods and quality control matters under this Standard follow whose rules?",
 ["Those prescribed by the central competent authority","Those prescribed by the municipal or county authority","Those prescribed by the industry competent authority","Those in the premises own self-written QA plan"],
 "Article 12; see also Article 13."),

(ES,"第14條",1,"固污排放-施行",
 "固定污染源空氣污染物排放標準之施行日期規定為何？",
 ["本標準自發布日施行","本標準自發布後一年施行","本標準自公布後六個月施行","本標準自中央主管機關公告日施行"],"a",
 "第14條：本標準自發布日施行。第2條規定本標準適用於新污染源及既存污染源，特定業別、區域或設施另訂有排放標準者優先適用；第4條以八十一年四月十一日、十二日區分既存污染源與新污染源。",
 "When does this emission Standard take effect?",
 ["From the date of promulgation","One year after promulgation","Six months after promulgation","On the date publicly announced"],
 "Article 14."),

# ---------- 空氣品質標準（ENV-28） ----------
(AQ,"第1條",1,"空品標準-法源",
 "空氣品質標準係依何規定訂定？",
 ["依空氣污染防制法第五條第三項規定訂定","依空氣污染防制法第二十條第二項規定訂定","依空氣污染防制法第三十四條第四項規定訂定","依空氣污染防制法第十四條第一項規定訂定"],"a",
 "第1條：本標準依空氣污染防制法第五條第三項規定訂定之。第2條並定義小時平均值、八小時平均值、日平均值、二十四小時值、年平均值及三個月移動平均值等用詞。空污法第二十條第二項則為固定污染源空氣污染物排放標準之授權依據。",
 "The Ambient Air Quality Standards are enacted under:",
 ["Article 5, Paragraph 3 of the Air Pollution Control Act","Article 20, Paragraph 2 of the Air Pollution Control Act","Article 34, Paragraph 4 of the Air Pollution Control Act","Article 14, Paragraph 1 of the Air Pollution Control Act"],
 "Article 1; see also Article 2."),

(AQ,"第3條",3,"空品標準-判定基準",
 "依本標準所定各項空氣污染物之空氣品質標準，懸浮微粒、細懸浮微粒及臭氧分別以何種平均值型態設定標準值？",
 ["懸浮微粒為日平均值及年平均值；細懸浮微粒為二十四小時值及年平均值；臭氧為小時平均值及八小時平均值","懸浮微粒為二十四小時值及年平均值；細懸浮微粒為日平均值及月平均值；臭氧為日平均值及年平均值","懸浮微粒為小時平均值及八小時平均值；細懸浮微粒為小時平均值及日平均值；臭氧為年平均值及日平均值","懸浮微粒為三個月移動平均值；細懸浮微粒為八小時平均值及日平均值；臭氧為二十四小時值及年平均值"],"a",
 "第3條就各項空氣污染物分別訂定空氣品質標準值，其平均值型態可由第4條之判定方法對應：懸浮微粒以日平均值及年平均值判定，細懸浮微粒以二十四小時值及年平均值判定，臭氧以小時平均值及八小時平均值判定，二氧化硫及二氧化氮以小時平均值及年平均值判定，一氧化碳以小時平均值及八小時平均值判定。第2條並定義各該平均值之計算方式。",
 "For PM10, PM2.5 and ozone, what averaging forms does the Standard use?",
 ["PM10 daily and annual averages; PM2.5 the 24-hour value and annual average; ozone hourly and 8-hour averages","PM10 the 24-hour value and annual average; PM2.5 daily and monthly averages; ozone daily and annual averages","PM10 hourly and 8-hour averages; PM2.5 hourly and daily averages; ozone annual and daily averages","PM10 a three-month moving average; PM2.5 8-hour and daily averages; ozone the 24-hour value and annual average"],
 "Articles 2 to 4."),

(AQ,"第5條",2,"空品標準-監測方法",
 "細懸浮微粒（PM2.5）濃度監測之標準方法為何？中央主管機關得如何替代？",
 ["以中央主管機關公告之空氣中細懸浮微粒手動檢測方法為之；得評估後以自動監測數據轉換計算替代","以直轄市主管機關指定之連續自動監測方法為之；得評估後以手動監測數據直接取代自動數據","以國際電工協會標準一型監測儀器測定為之；得由公私場所自行選擇手動或自動方法擇一辦理","以檢驗測定機構自訂之標準作業程序為之；得於數據不足時逕以模式推估值替代實際監測數據"],"a",
 "第5條：細懸浮微粒（PM2.5）濃度監測之標準方法，以中央主管機關公告之空氣中細懸浮微粒手動檢測方法為之；其他各項空氣污染物依中央主管機關公告之標準方法監測。中央主管機關得經評估，以自動監測數據經由與手動監測數據轉換計算後替代之。第4條並規定經中央主管機關認可之特殊事件，其當日監測數值不予採計。",
 "What is the standard method for PM2.5 monitoring, and how may it be substituted?",
 ["The manual method announced by the central authority; automated data may substitute after conversion","A continuous automated method designated by the municipal authority; manual data may replace it directly","IEC Class 1 instruments; the premises may freely choose either the manual or the automated method","A testing organisation in-house procedure; modelled estimates may replace monitoring data if data is short"],
 "Article 5; see also Article 4."),

(AQ,"第6條",1,"空品標準-施行",
 "空氣品質標準之施行日期規定為何？",
 ["本標準自發布日施行","本標準自發布後一年施行","本標準自公布後六個月施行","本標準自中央主管機關指定日施行"],"a",
 "第6條：本標準自發布日施行。第4條規定空氣污染防制區及總量管制區符合空氣品質標準之判定方法，需以區內一般空氣品質監測站連續三年之統計值與標準值比較，經中央主管機關認可之特殊事件當日數值不予採計。",
 "When do the Ambient Air Quality Standards take effect?",
 ["From the date of promulgation","One year after promulgation","Six months after promulgation","On a date designated centrally"],
 "Article 6."),

# ---------- 室內空氣品質標準（ENV-31） ----------
(IQ,"第1條",1,"室內空品標準-法源",
 "室內空氣品質標準係依何規定訂定？",
 ["依室內空氣品質管理法第七條第二項規定訂定","依室內空氣品質管理法第十條第三項規定訂定","依室內空氣品質管理法第九條第三項規定訂定","依室內空氣品質管理法第十一條第二項規定訂定"],"a",
 "第1條：本標準依室內空氣品質管理法第七條第二項規定訂定之。該法第7條第一項要求公告場所室內空氣品質應符合室內空氣品質標準，第二項則授權中央主管機關會商中央目的事業主管機關依公告場所之類別及使用特性訂定標準。該法第10條第三項授權者為檢驗測定管理辦法，第9條第三項授權者為專責人員設置管理辦法。",
 "The Indoor Air Quality Standards are enacted under:",
 ["Article 7, Paragraph 2 of the Indoor Air Quality Management Act","Article 10, Paragraph 3 of the Indoor Air Quality Management Act","Article 9, Paragraph 3 of the Indoor Air Quality Management Act","Article 11, Paragraph 2 of the Indoor Air Quality Management Act"],
 "Article 1."),

(IQ,"第4條",2,"室內空品標準-符合判定",
 "公告場所應如何判定其室內空氣品質符合本標準？",
 ["依場所公告類別所列各項污染物項目及濃度測值，經分別判定未超過標準者，始認定符合","將各項污染物濃度測值加總平均後，其平均值未超過標準值總和者，即認定符合標準","僅須二氧化碳及一氧化碳兩項未超過標準值，其餘項目得由場所自行選擇是否檢測","由檢驗測定機構就任選三項污染物判定，其中二項未超過標準值者即認定符合標準"],"a",
 "第4條：公告場所應依其場所公告類別所列各項室內空氣污染物項目及濃度測值，經分別判定未超過第2條規定標準者，始認定符合本標準。第2條所列標準值包括二氧化碳八小時值一○○○ppm、一氧化碳八小時值九ppm、甲醛一小時值○‧○八ppm、TVOC 一小時值○‧五六ppm、細菌最高值一五○○CFU/m³、真菌最高值一○○○CFU/m³、PM10 二十四小時值七五μg/m³、PM2.5 二十四小時值三五μg/m³、臭氧八小時值○‧○六ppm。",
 "How is compliance with the Indoor Air Quality Standards judged for an announced site?",
 ["Each listed pollutant for that site category is judged separately and none may exceed the standard value","All pollutant readings are averaged and compliance holds if the average is below the sum of the values","Only carbon dioxide and carbon monoxide must comply; other items are tested at the site discretion","A testing body picks any three pollutants and compliance holds if two of them are within the values"],
 "Article 4; the values are in Article 2."),

(IQ,"第5條",1,"室內空品標準-施行",
 "室內空氣品質標準之施行日期規定為何？",
 ["自中華民國一百零一年十一月二十三日起施行","自中華民國一百年十一月二十三日起施行","自中華民國一百零二年一月一日起施行","自本標準發布後滿一年之日起施行"],"a",
 "第5條：本標準自中華民國一百零一年十一月二十三日起施行。室內空氣品質管理法第24條規定該法自公布後一年施行，該法公布日為一百年十一月二十三日，故本標準之施行日與母法施行日一致。",
 "When do the Indoor Air Quality Standards take effect?",
 ["From 23 November 2012 of the Republic of China calendar year 101","From 23 November 2011 of the Republic of China calendar year 100","From 1 January 2013 of the Republic of China calendar year 102","From one year after the promulgation of this Standard"],
 "Article 5."),

# ---------- 環境音量標準（ENV-40） ----------
(EN,"第1條",1,"環境音量-法源",
 "環境音量標準係依何規定訂定？",
 ["依噪音管制法第十五條第三項規定訂定","依噪音管制法第九條第二項規定訂定","依噪音管制法第三十六條規定訂定","依噪音管制法第十一條第一項規定訂定"],"a",
 "第1條：本標準依噪音管制法第十五條第三項規定訂定之。噪音管制法第三十六條為噪音管制法施行細則之授權依據，第十一條第一項則授權訂定噪音管制標準，三者授權對象不同。第2條並定義管制區、道路、道路邊地區、航空噪音防制區及時段區分等用詞。",
 "The Ambient Noise Standards are enacted under:",
 ["Article 15, Paragraph 3 of the Noise Control Act","Article 9, Paragraph 2 of the Noise Control Act","Article 36 of the Noise Control Act as amended","Article 11, Paragraph 1 of the Noise Control Act"],
 "Article 1; Article 36 authorizes the Enforcement Rules."),

(EN,"第5條",2,"環境音量-航空噪音",
 "非屬各級航空噪音防制區之區域，其全年航空噪音日夜音量之環境音量標準為何？",
 ["噴射飛機及螺旋槳飛機起降之航空站為六十；供直昇機起降之航空站為五十二","噴射飛機及螺旋槳飛機起降之航空站為五十二；供直昇機起降之航空站為六十","噴射飛機及螺旋槳飛機起降之航空站為六十五；供直昇機起降之航空站為五十","噴射飛機及螺旋槳飛機起降之航空站為七十；供直昇機起降之航空站為六十五"],"a",
 "第5條：非屬各級航空噪音防制區之區域，噴射飛機及螺旋槳飛機起降之航空站，全年航空噪音日夜音量標準為六十；供直昇機起降之航空站為五十二。第2條第九款定義全年航空噪音日夜音量之計算公式；第3條規定機場周圍固定式航空噪音監測站應蒐集全年之航空噪音日夜音量，非固定式者應蒐集連續十日以上。",
 "Outside any aircraft noise control zone, the annual day-night aircraft noise level standards are:",
 ["Sixty for airports serving jet and propeller aircraft; fifty-two for heliports serving helicopters","Fifty-two for airports serving jet and propeller aircraft; sixty for heliports serving helicopters","Sixty-five for airports serving jet and propeller aircraft; fifty for heliports serving helicopters","Seventy for airports serving jet and propeller aircraft; sixty-five for heliports serving helicopters"],
 "Article 5; see also Articles 2 and 3."),

(EN,"第6條",1,"環境音量-施行",
 "環境音量標準之施行日期規定為何？",
 ["本標準自發布日施行","本標準自發布後一年施行","本標準自公布後六個月施行","本標準自中央主管機關指定日施行"],"a",
 "第6條：本標準自發布日施行。第4條所定道路交通噪音環境音量標準，依管制區類別及緊鄰道路寬度分為四種情形，並區分日間、晚間、夜間三個時段訂定均能音量（Leq）標準值。",
 "When does the Ambient Noise Standard take effect?",
 ["From the date of promulgation","One year after promulgation","Six months after promulgation","On a date designated centrally"],
 "Article 6."),
]
