# -*- coding: utf-8 -*-
# 第 12 批（F3）：共通性事業廢棄物作為固體再生燃料原料再利用管理辦法（ENV-167，23條）
#                再生資源再使用管理辦法（ENV-168，19條）
S = "ENV-167"
U = "ENV-168"

Q = [

# ===== ENV-167 共通性事業廢棄物作為固體再生燃料原料再利用管理辦法 =====
(S,"第1條",1,"SRF再利用-法源",
 "共通性事業廢棄物作為固體再生燃料原料再利用管理辦法係依廢棄物清理法何條規定訂定？",
 ["依廢棄物清理法第三十九條第二項規定訂定","依廢棄物清理法第二十八條第二項規定訂定","依廢棄物清理法第三十七條第二項規定訂定","依廢棄物清理法第三十一條第一項規定訂定"],"a",
 "第1條：本辦法依廢棄物清理法第三十九條第二項規定訂定之。第2條定義固體再生燃料及再利用機構，第6條規定品質標準與檢測，第23條定明本辦法除另定施行日期者外自發布日施行。",
 "Under which article of the Waste Disposal Act are these SRF Regulations enacted?",
 ["Enacted under Article 39, paragraph 2 of the Waste Disposal Act","Enacted under Article 28, paragraph 2 of the Waste Disposal Act","Enacted under Article 37, paragraph 2 of the Waste Disposal Act","Enacted under Article 31, paragraph 1 of the Waste Disposal Act"],
 "Article 1 states the statutory authority."),

(S,"第2條",2,"SRF再利用-用詞定義",
 "本辦法所稱固體再生燃料（SRF）及再利用機構，其定義分別為何？",
 ["固體再生燃料指以附表具適燃性之事業廢棄物再利用種類混合作為燃料且品質符合附件一者；再利用機構指經政府登記有案收受該廢棄物再利用之工廠","固體再生燃料指以生質物及廢塑膠混合造粒而成之顆粒狀燃料；再利用機構指經目的事業主管機關核准設立並取得工廠登記之發電業或汽電共生廠","固體再生燃料指經高溫熱裂解產生之固態碳材與灰渣之混合物；再利用機構指領有廢棄物處理許可證並附設焚化設施之公民營廢棄物處理機構","固體再生燃料指以廢棄物直接壓縮成型而未經檢測之替代燃料；再利用機構指取得固定污染源操作許可證並使用該燃料之公私場所或事業"],"a",
 "第2條：固體再生燃料指以附表具適燃性之事業廢棄物再利用種類混合作為燃料，且品質符合附件一所定品質標準者；再利用指事業將其事業廢棄物自行或送往再利用機構作為固體再生燃料原料用途之行為；再利用機構指經政府登記有案，收受事業廢棄物再利用為固體再生燃料之工廠。第13條並規定使用者之資格。",
 "How are Solid Recovered Fuel and a reuse organization defined?",
 ["SRF is a fuel blended from combustible waste types in the table meeting the Annex 1 quality standard; a reuse organization is a registered plant receiving such waste","SRF is a pelletized fuel made from biomass mixed with waste plastics; a reuse organization is a power or cogeneration plant licensed by the industry authority","SRF is the mixture of solid carbon and ash produced by high temperature pyrolysis; a reuse organization is a licensed waste treatment firm with an incinerator","SRF is an alternative fuel compressed directly from waste without any testing; a reuse organization is a site holding a stationary source operating permit"],
 "Article 2."),

(S,"第3條",2,"SRF再利用-自行再利用",
 "屬本法第三十一條第一項第一款公告之事業，其自行再利用應先完成何種程序？",
 ["應於其事業廢棄物清理計畫書經審核機關審查核准後，始得自行再利用其事業廢棄物","應向中央主管機關申請再利用許可證並經公告後，始得自行再利用其事業廢棄物","應取得固定污染源設置許可證及操作許可證後，始得自行再利用其事業廢棄物","應與領有清除許可證之清除機構簽訂契約書後，始得自行再利用其事業廢棄物"],"a",
 "第3條：屬本法第三十一條第一項第一款公告之事業，於其事業廢棄物清理計畫書經直轄市、縣（市）主管機關或中央主管機關委託之機關（審核機關）審查核准後，始得自行再利用；其依本辦法及附表規定再利用所屬同一法人之其他分廠（場）所產生之事業廢棄物者，視為自行再利用。",
 "What must a designated enterprise complete before reusing its own waste as SRF feedstock?",
 ["Its waste disposal plan must first be reviewed and approved by the reviewing authority before self-reuse may begin","It must first obtain a reuse permit from the central authority and have it publicly announced before self-reuse","It must first obtain both installation and operating permits for a stationary pollution source before self-reuse","It must first sign a contract with a licensed waste clearance organization before it may reuse its own waste"],
 "Article 3."),

(S,"第4條",2,"SRF再利用-適用範圍",
 "非屬本辦法附表規定之再利用行為，應依何規定辦理？附表所列種類用途有污染之虞時如何處理？",
 ["應依共通性事業廢棄物再利用管理辦法或各中央目的事業主管機關所定辦法辦理；有污染之虞者中央主管機關得暫停其再利用，原因消失應即解除","應依廢棄物清理法第二十八條規定委託處理機構處理；有污染之虞者由直轄市、縣（市）主管機關逕行公告廢止該再利用種類及用途之規定","應由事業自行提報再利用計畫書經核准後辦理；有污染之虞者應由再利用者自行停止運作並於三十日內向審核機關報備後始得恢復辦理","應依資源回收再利用法所定再使用管理辦法辦理；有污染之虞者由中央目的事業主管機關會商後修正附表所列之再利用種類及其用途"],"a",
 "第4條：事業及再利用機構應依本辦法及附表規定進行事業廢棄物再利用；非屬附表規定之再利用行為，應依共通性事業廢棄物再利用管理辦法或各中央目的事業主管機關所定之事業廢棄物再利用管理辦法規定辦理。附表所列再利用種類及用途有污染環境之虞者，中央主管機關得暫停其再利用；其原因消失時應即解除之。",
 "What governs reuse not listed in the attached table, and what if a listed use risks pollution?",
 ["The general industrial waste reuse regulations or the industry authority's own regulations apply; risky uses may be suspended and reinstated when the cause ends","Article 28 of the Waste Disposal Act applies and treatment must be commissioned; risky uses are abolished by public notice of the local competent authority","The enterprise files its own reuse plan for approval; for risky uses the operator halts work itself and files a report within thirty days before resuming","The reuse regulations under the Resource Recycling Act apply; risky uses are addressed by the industry authority amending the reuse types in the table"],
 "Article 4."),

(S,"第5條",2,"SRF再利用-三階段審查",
 "再利用機構從事再利用前應檢具何種文件送審？其審查應以何種程序辦理？",
 ["應檢具事業廢棄物清理計畫書併同載明再利用方式、資格及檢核文件送審核機關核准；審查應以書面審查、現場勘查及試運轉三階段程序辦理","應檢具工廠登記證及環境影響說明書送中央主管機關核准；審查應以書面審查及專家學者現場會勘二階段程序辦理即可開始從事再利用","應檢具固定污染源操作許可證及燃料使用許可證送地方主管機關備查；審查應以文件備查及一年後追蹤查核二階段程序辦理即為已足","應檢具品質管理系統第三方驗證報告送中央主管機關認可；審查應以驗證機構初審及促進委員會複審二階段程序辦理後即可營運"],"a",
 "第5條：再利用機構應檢具事業廢棄物清理計畫書，併同載明再利用方式、再利用資格及再利用檢核相關文件，送審核機關審查核准後，始得依本辦法及附表規定從事再利用；第3條及本項之事業廢棄物清理計畫書審查應以書面審查、現場勘查及試運轉之三階段程序辦理。",
 "What must a reuse organization submit before operating, and by what review procedure?",
 ["A waste disposal plan with the reuse method, qualifications and checklist documents, approved by the reviewing authority after a three stage review","A factory registration and an environmental impact statement approved by the central authority, after a two stage documentary and site review procedure","A stationary source operating permit and a fuel use permit filed with the local authority, after a two stage filing and one year follow-up procedure","A third party quality management verification report recognized by the central authority, after a verifier initial review and committee second review"],
 "Article 5."),

(S,"第6條",3,"SRF再利用-品質標準",
 "再利用者生產之固體再生燃料，其品質及不可燃廢棄物含量之規定為何？",
 ["須符合附件一品質標準，所含自然夾雜之不可燃廢棄物溼基重量比依人工分撿檢視不得超過百分之一，並應依附件二品質分級表區分等級","須符合附件三檢測方法規範，所含自然夾雜之不可燃廢棄物乾基重量比依機械篩分檢視不得超過百分之五，並應依附件一品質標準區分等級","須符合附件六設備規定標準，所含自然夾雜之不可燃廢棄物體積比依目視方式檢視不得超過百分之十，並應依附件四標示表區分等級","須符合附表管理方式規定，所含自然夾雜之不可燃廢棄物溼基重量比依人工分撿檢視不得超過百分之三，並應依附件七規定區分等級"],"a",
 "第6條第1項：自行再利用之事業及再利用機構生產之固體再生燃料須符合附件一品質標準，其所含自然夾雜之不可燃廢棄物之溼基重量比，依人工分撿方式檢視，不得超過百分之一；並應依附件二品質分級表區分等級。第8條並規定經檢測未符合品質標準者應依本法第二十八條或第三十九條規定處理或再利用。",
 "What quality and non-combustible content requirements apply to the SRF produced?",
 ["It must meet the Annex 1 quality standard, naturally mixed non-combustibles may not exceed one percent by wet weight on manual sorting, and Annex 2 grading applies","It must meet the Annex 3 test method specification, non-combustibles may not exceed five percent by dry weight on mechanical screening, and Annex 1 grading applies","It must meet the Annex 6 equipment standard, non-combustibles may not exceed ten percent by volume on visual inspection, and Annex 4 labels set the grade","It must meet the management rules in the table, non-combustibles may not exceed three percent by wet weight on manual sorting, and Annex 7 sets the grade"],
 "Article 6, paragraph 1."),

(S,"第6條",3,"SRF再利用-採樣檢測",
 "再利用者辦理固體再生燃料定期檢測分析，其採樣批量及樣次規定為何？檢測報告應保存多久？",
 ["營運期間生產相同組成者應每月逐批採樣檢測，每批次批量小於或等於一千五百公噸，每批次最少採樣二十四樣次進行等量混樣分析，報告應保存三年","營運期間生產相同組成者應每季逐批採樣檢測，每批次批量小於或等於三千公噸，每批次最少採樣十二樣次進行等量混樣分析，報告應保存五年","營運期間生產相同組成者應每半年採樣檢測一次，每批次批量小於或等於五百公噸，每批次最少採樣六樣次進行等量混樣分析，報告應保存一年","營運期間生產相同組成者應每年採樣檢測一次，每批次批量小於或等於一萬公噸，每批次最少採樣四十八樣次進行等量混樣分析，報告應保存七年"],"a",
 "第6條第2項第2款：營運期間生產相同組成之固體再生燃料，應每月逐批採樣檢測，每批次批量小於或等於一千五百公噸，且每批次最少採樣二十四樣次進行等量混樣分析。第3項規定檢測報告應於銷售時提供使用者並妥善保存三年。採樣方法應依公告之NIEA M195或ISO 21645辦理。",
 "What batch size and sampling frequency apply to periodic SRF testing, and how long are reports kept?",
 ["Monthly batch sampling during operation, each batch at most 1,500 tonnes with at least 24 increments composited equally, and reports kept three years","Quarterly batch sampling during operation, each batch at most 3,000 tonnes with at least 12 increments composited equally, and reports kept five years","Semiannual sampling during operation, each batch at most 500 tonnes with at least 6 increments composited equally, and reports kept for one year","Annual sampling during operation, each batch at most 10,000 tonnes with at least 48 increments composited equally, and reports kept seven years"],
 "Article 6, paragraphs 2 and 3."),

(S,"第7條",3,"SRF再利用-第三方驗證",
 "固體再生燃料品質管理系統之第三方驗證，得委託何種機構辦理？通過驗證之效果為何？",
 ["得委託全國認證基金會認可名錄內之驗證機構或經中央主管機關認可之學術機構或財團法人；通過驗證者於證明文件有效期間內產出者得先行銷售及使用","得委託中央主管機關許可之環境檢驗測定機構或目的事業主管機關指定之公會辦理；通過驗證者於證明文件有效期間內得免除逐批採樣檢測之義務","得委託設有環境工程系所之大專校院或經濟部標準檢驗局辦理；通過驗證者得於三年內免受主管機關查核並免提報檢測報告予使用者確認","得委託任何取得國際標準化組織認證之顧問公司辦理；通過驗證者得逕行銷售予任何國內外使用者而不受使用者資格條件之限制拘束"],"a",
 "第7條第1項、第4項：再利用者得委託財團法人全國認證基金會認可之品質管理系統認證名錄內之驗證機構，或經中央主管機關認可之學術機構或財團法人辦理第三方驗證；通過驗證者應提出證明文件送直轄市、縣（市）主管機關及使用者備查，其於驗證證明文件有效期間內所生產之固體再生燃料得先行銷售及使用，但仍應依第6條第2項規定進行採樣檢測確認符合品質標準。",
 "Who may carry out third party verification of the SRF quality management system, and what does passing it allow?",
 ["Verifiers on the TAF accredited list or academic bodies or foundations recognized centrally; fuel made during validity may be sold and used in advance","Testing organizations licensed by the central authority or guilds designated by the industry authority; passing exempts the producer from batch sampling","Universities with environmental engineering departments or the Bureau of Standards; passing exempts it from inspection and from giving users reports","Any consultancy holding an International Organization for Standardization accreditation; passing lifts all restrictions on who may be sold the fuel"],
 "Article 7, paragraphs 1 and 4."),

(S,"第8條",2,"SRF再利用-不符標準處理",
 "再利用者生產之固體再生燃料經檢測未符合附件一品質標準，及再利用後之衍生廢棄物，應如何處理？",
 ["應依廢棄物清理法第二十八條或第三十九條規定處理或再利用","應逕行退運予原產生事業並由該事業自行貯存至改善完成為止","應由直轄市、縣（市）主管機關代為清除處理並向再利用者求償","應降級後仍得銷售予使用者，但應於契約書中載明其品質等級"],"a",
 "第8條：再利用者生產固體再生燃料經檢測未符合附件一品質標準，及再利用後之衍生廢棄物，應依本法第二十八條或第三十九條規定處理或再利用。第19條第1款並規定固體再生燃料不符合品質標準者，直轄市、縣（市）主管機關得要求限期改善並停止其銷售或運送。",
 "How must off-spec SRF and residues from the reuse process be handled?",
 ["They must be treated or reused under Article 28 or Article 39 of the Waste Disposal Act","They must be returned to the generating enterprise for storage until correction is done","The local competent authority disposes of them and recovers the costs from the operator","They may still be sold after downgrading provided the grade is stated in the contract"],
 "Article 8."),

(S,"第9條",2,"SRF再利用-清除方式",
 "事業廢棄物送往再利用機構再利用前之清除，得由事業或再利用機構以何種方式為之？",
 ["得自行清除，或委託領有廢棄物清除許可證之公民營廢棄物清除機構清除","得委託任何領有營業車輛牌照之運輸業者清除，無須具備清除許可證者","得由再利用機構之使用者代為清除，並於事後補行申報清運聯單即可","得委託當地執行機關之清潔隊代為清除，並依規定繳納清除處理費用"],"a",
 "第9條：事業廢棄物送往再利用機構再利用前之清除，由事業或再利用機構自行清除，或委託領有廢棄物清除許可證之公民營廢棄物清除機構清除，且受託清除機構應依公民營廢棄物清除處理機構許可管理辦法第十八條第四項規定辦理；清運機具裝置即時追蹤系統應依本法第三十一條第一項第三款規定辦理。",
 "How may waste be cleared before delivery to a reuse organization?",
 ["Either by self-clearance, or by commissioning a public or private clearance organization holding a clearance permit","By commissioning any transport operator holding commercial vehicle plates, with no clearance permit being required","By having the SRF user clear it on their behalf, with the manifest filed after the fact to complete the record","By commissioning the local executing agency's cleaning squad and paying the prescribed clearance and treatment fees"],
 "Article 9."),

(S,"第10條",3,"SRF再利用-契約書",
 "事業於委託清除或再利用前，及再利用者銷售固體再生燃料前，其契約書之規定為何？",
 ["均應事先簽訂契約書，委託清除再利用契約應保存三年留供查核；買賣契約應載明品質等級數量、雙方固定污染源操作許可證號及銷售後應直接使用等事項","均得於運作後三十日內補簽契約書，契約書應保存一年；買賣契約僅需載明數量及價格，其餘事項得由雙方於出貨單上另行約定後辦理即可","委託清除再利用契約應報請主管機關核准後始生效力；買賣契約則免予簽訂，僅需於每次出貨時填具附件五產品填報資料表交付使用者即可","委託清除再利用契約應由清除機構單方作成並保存五年；買賣契約應載明售價結構及運費負擔方式，並於契約期滿後函報主管機關備查"],"a",
 "第10條第1項、第3項、第4項：事業於委託清除或再利用前應先與再利用機構及清除機構簽訂契約書並妥善保存三年留供查核，未簽約者不得受託；再利用者於銷售前應先與使用者簽訂買賣契約書，應記載品質等級及數量、雙方固定污染源操作許可證號、雙方設置閉路電視錄影監視系統、銷售後應直接使用、逐批提供品質檢測報告等事項；並應於首次銷售前連線至指定申報系統提報契約書供備查。",
 "What rules govern contracts before commissioning clearance or reuse and before selling SRF?",
 ["Contracts must be signed first, the clearance and reuse contract kept three years; sales contracts must state grade and quantity, both permit numbers and direct use","Contracts may be signed within thirty days after operations begin and kept one year; sales contracts need only state quantity and price, with the rest on the delivery note","The clearance and reuse contract takes effect only after the authority approves it; no sales contract is needed, only the Annex 5 data sheet given at each shipment","The clearance and reuse contract is drawn up by the clearance firm alone and kept five years; sales contracts must state pricing and freight and be filed after expiry"],
 "Article 10, paragraphs 1, 3 and 4."),

(S,"第11條",3,"SRF再利用-設備",
 "再利用者依附件六規定應設置何種設備？其設備運作紀錄應記錄哪些事項並保存多久？",
 ["應設置純化設備與均質化設備，並視廢棄物性質得擇定乾燥、壓縮、光學分選等設備；應記錄設備使用情況、維修情況、操作人員及處理量，保存三年","應設置焚化設備與空氣污染防制設備，並視廢棄物性質得擇定破碎、篩分等設備；應記錄進料量、排放濃度、燃燒溫度及操作時數，並保存五年備查","應設置貯存槽與滲出水收集設備，並視廢棄物性質得擇定中和、固化等設備；應記錄貯存量、滲出水量、清運日期及承受水體，並保存一年備查","應設置計量設備與閉路電視監視系統，並視廢棄物性質得擇定除臭、消毒等設備；應記錄過磅重量、車號、駕駛人及進出時間，並保存七年備查"],"a",
 "第11條：再利用者應依附件六規定設置純化設備與均質化設備，並視廢棄物性質得擇定設置乾燥設備、壓縮設備、光學分選設備或醱酵、乾化、除臭等生物處理方式；依規定設置之設備應記錄設備使用情況、設備維修情況、操作設備人員及設備處理量，紀錄應妥善保存三年。本辦法施行前已核准而未能設置者，得提出替代方法報經審核機關同意。",
 "What equipment must a reuse operator install under Annex 6, and what operating records are kept and for how long?",
 ["Purification and homogenization units, optionally drying, compression or optical sorting; records of use, maintenance, operators and throughput kept three years","Incineration and air pollution control units, optionally crushing or screening; records of feed rate, emission levels, temperature and hours kept five years","Storage tanks and leachate collection units, optionally neutralization or solidification; records of volume, leachate, haul dates and waters kept one year","Weighing equipment and closed circuit television, optionally deodorizing or disinfection; records of weight, plate number, driver and times kept seven years"],
 "Article 11."),

(S,"第12條",2,"SRF再利用-監視系統",
 "再利用者設置閉路電視錄影監視系統，其設置地點、畫面涵蓋範圍及紀錄保存等應依何規定辦理？",
 ["應依附件七規定辦理其設置地點、畫面應涵蓋範圍、攝錄監視畫面與系統規格、攝錄紀錄保存及故障排除","應依附件二品質分級表規定辦理其設置地點、畫面涵蓋範圍、系統規格、紀錄保存及故障排除等事項","應依附件四製造方法及設備標示表規定辦理設置地點、畫面範圍、系統規格、紀錄保存與故障排除","應由再利用者於事業廢棄物清理計畫書中自行訂定設置地點、畫面範圍、系統規格及紀錄保存年限"],"a",
 "第12條：再利用者應設置閉路電視錄影監視系統，其設置地點、畫面應涵蓋範圍、攝錄監視畫面與系統規格、攝錄紀錄保存及故障排除，應依附件七規定辦理。第18條第4款、第5款並規定監視系統七日內故障達二次以上且未能於一個工作日內修復，或未能提供遠端查看者，主管機關得令其停止再利用運作。",
 "What governs the location, coverage and record keeping of the required closed circuit television system?",
 ["Annex 7 governs the installation site, required field of coverage, image and system specifications, record retention and fault clearing","Annex 2, the quality grading table, governs the installation site, coverage, system specifications, record retention and fault clearing","Annex 4, the production method and equipment label sheet, governs the site, coverage, specifications, retention and fault clearing","The operator sets the site, coverage, system specifications and record retention period itself in its own waste disposal plan"],
 "Article 12."),

(S,"第13條",3,"SRF再利用-使用者資格",
 "再利用者生產之固體再生燃料應銷售或提供予何人？其使用者應符合何種資格？",
 ["應直接銷售予國內使用者或供自廠及同一法人其他分廠使用；使用者須為本法第三十一條第一項第二款公告之事業，且取得操作許可證並於燃料使用許可證記載使用固體再生燃料","得銷售予國內外任何燃煤鍋爐之使用者；使用者僅須取得工廠登記證及經目的事業主管機關同意使用替代燃料之文件，無須另行取得固定污染源之設置或操作許可證明","應透過中央主管機關指定之交易平台銷售；使用者須為領有廢棄物處理許可證之公民營處理機構，並於其許可證中登載得使用固體再生燃料作為輔助燃料者","得銷售予經直轄市、縣（市）主管機關備查之任何事業；使用者僅須設置閉路電視錄影監視系統並按月申報使用量，無須具備空氣污染防制法之相關許可"],"a",
 "第13條：再利用者生產之固體再生燃料應直接銷售予國內使用者，或提供自廠或所屬同一法人之其他分廠（場）使用；其使用者應符合本法第三十一條第一項第二款公告之事業，及依空氣污染防制法相關規定取得固定污染源操作許可證，且燃料使用許可證記載使用固體再生燃料。第19條第2款並規定銷售對象不符規定者得令其停止銷售。",
 "To whom may SRF be sold, and what qualifications must the user meet?",
 ["Directly to domestic users or the producer's own or affiliated plants; users must be designated enterprises holding a stationary source operating permit that records SRF use","To any coal boiler user at home or abroad; users need only a factory registration and the industry authority's consent to burn alternative fuel, with no source permit needed","Only through a trading platform designated by the central authority; users must be licensed waste treatment firms whose permit records SRF as an auxiliary fuel for use","To any enterprise filed with the local competent authority; users need only install closed circuit television and report usage monthly, with no air pollution permit"],
 "Article 13."),

(S,"第14條",2,"SRF再利用-運作紀錄",
 "事業及再利用機構對於事業廢棄物再利用之運作，應如何作成紀錄及保存？",
 ["均應逐筆作成紀錄，紀錄及相關憑證應妥善保存三年留供查核，並應依本法第三十一條第一項第二款相關規定申報再利用情形","均應按月彙總作成紀錄，紀錄及相關憑證應妥善保存一年留供查核，並得免依本法規定申報其事業廢棄物之再利用運作情形","均應按季彙總作成紀錄，紀錄及相關憑證應妥善保存五年留供查核，並應於每年年終函報中央主管機關備查其再利用之情形","僅再利用機構應逐筆作成紀錄並保存七年，事業免作紀錄；再利用情形由再利用機構代事業統一申報予直轄市、縣（市）主管機關"],"a",
 "第14條：事業對於事業廢棄物送往再利用機構之日期、種類、名稱、數量、再利用用途及再利用機構名稱應逐筆作成紀錄；再利用機構對於再利用之日期、種類、名稱、數量、用途、事業名稱、衍生廢棄物之處置及再利用期程應逐筆作成紀錄；前二項紀錄及相關憑證應妥善保存三年留供查核，並應依本法第三十一條第一項第二款相關規定申報再利用情形。",
 "How must enterprises and reuse organizations record and keep reuse operation data?",
 ["Both must record each transaction, keep the records and vouchers three years for inspection, and report reuse under Article 31, paragraph 1, subparagraph 2","Both must compile monthly summaries, keep the records and vouchers one year for inspection, and are exempt from reporting reuse operations under the Act","Both must compile quarterly summaries, keep the records and vouchers five years for inspection, and report to the central authority at each year end","Only the reuse organization records each transaction and keeps it seven years; it also reports on behalf of the enterprises to the local competent authority"],
 "Article 14."),

(S,"第15條",3,"SRF再利用-每日紀錄申報",
 "再利用者對固體再生燃料之產銷資料應多久作成紀錄？其申報期限為何？",
 ["應每日作成紀錄並妥善保存三年，並應按月於每月十日前主動連線至指定申報系統向直轄市、縣（市）主管機關申報前月資料","應每週作成紀錄並妥善保存一年，並應按季於每季首月十五日前主動連線至指定申報系統向直轄市、縣（市）主管機關申報資料","應每月作成紀錄並妥善保存五年，並應按年於次年一月底前主動連線至指定申報系統向中央主管機關申報前一年度之全部資料","應每批次作成紀錄並妥善保存七年，並應於每次銷售後三日內主動連線至指定申報系統向中央主管機關申報該批次銷售資料"],"a",
 "第15條：再利用者對於不同品質之固體再生燃料產生量、銷售對象、證號、地址、產品代碼及名稱、銷售量、事業廢棄物代碼名稱與使用量及庫存量等資料，應每日作成紀錄並妥善保存三年，無銷售時亦應記錄庫存量；應按月申報前項每日紀錄，並於每月十日前主動連線至指定申報系統向直轄市、縣（市）主管機關申報前月資料，發現申報內容與實際不一致應立即上網補正並說明原因。",
 "How often must SRF production and sales data be recorded, and when must they be reported?",
 ["Records must be made daily and kept three years, and reported monthly online to the local competent authority by the tenth of each month for the prior month","Records must be made weekly and kept one year, and reported quarterly online to the local competent authority by the fifteenth of each quarter's first month","Records must be made monthly and kept five years, and reported annually online to the central competent authority by the end of January for the prior year","Records must be made per batch and kept seven years, and reported online to the central competent authority within three days after each sale of a batch"],
 "Article 15."),

(S,"第16條",2,"SRF再利用-申報故障",
 "事業及再利用者連線申報時，因軟硬體設施故障無法完成申報者，應如何辦理？",
 ["應於一日內以傳真方式向直轄市、縣（市）主管機關報備並作成紀錄，並於修復完成一日內補行連線申報","應於七日內以書面方式向直轄市、縣（市）主管機關報備並作成紀錄，並於修復完成七日內補行申報","應於三十日內以電子郵件向中央主管機關報備並作成紀錄，並於修復完成三十日內補行連線申報","應立即停止收受事業廢棄物進廠，俟系統修復完成並補行申報後始得恢復其再利用運作行為"],"a",
 "第16條：事業及再利用者依第14條、第15條規定連線申報時，因相關軟硬體設施發生故障無法完成申報，應於一日內以傳真方式向直轄市、縣（市）主管機關報備並作成紀錄；並於修復完成一日內補行連線申報。",
 "What must be done when hardware or software failure prevents online reporting?",
 ["Notify the local competent authority by fax within one day and record it, then complete the online report within one day of repair","Notify the local competent authority in writing within seven days and record it, then complete the report within seven days of repair","Notify the central competent authority by email within thirty days and record it, then complete the report within thirty days of repair","Stop receiving industrial waste immediately, and resume reuse operations only after the system is repaired and the report is filed"],
 "Article 16."),

(S,"第17條",3,"SRF再利用-停止收受",
 "再利用者有何情形時，直轄市、縣（市）主管機關得令其停止收受事業廢棄物進廠（場）並限期改善？",
 ["未於收受廢棄物三十日內完成再利用作業、固體再生燃料庫存量超出前三個月累積產出量、再利用設施故障未於三十日內修復或喪失從事業務能力者","未於收受廢棄物七日內完成再利用作業、庫存量超出前一個月累積產出量、設施故障未於七日內修復或未於期限內繳納廢棄物清除處理費用者","未依規定設置磅秤及計量設備、未取得工廠登記證、未加入同業公會或未依規定投保公共意外責任保險及環境污染責任保險等情形之一者","未於每年年終提報營運報告書、未辦理員工在職教育訓練、未設置專責單位或未依規定聘僱廢棄物處理技術員達三個月以上等情形者"],"a",
 "第17條：再利用者有下列情形之一者，直轄市、縣（市）主管機關得令其停止收受事業廢棄物進廠（場）並要求限期改善：未於收受廢棄物三十日內完成再利用作業；固體再生燃料未依附表管理方式貯存或庫存量超出前三個月累積產出量；再利用設施故障或異常未能於三十日內或核准期限內完成修復；未依規定申報；未提供有效之第三方驗證證明文件且未檢具符合品質標準之檢測報告；提供不實驗證文件；喪失從事業務能力或一年內無從事廢棄物再利用業務。",
 "In which cases may the local authority order a reuse operator to stop receiving waste and correct within a deadline?",
 ["Not completing reuse within thirty days of receipt, stock exceeding the prior three months' output, equipment unrepaired for thirty days, or loss of capability","Not completing reuse within seven days of receipt, stock exceeding the prior month's output, equipment unrepaired for seven days, or unpaid disposal fees","Failing to install weighing and metering equipment, lacking factory registration, not joining the trade guild, or lacking liability insurance cover","Failing to file an annual operating report, not training staff, not setting up a dedicated unit, or lacking a licensed technician for three months"],
 "Article 17."),

(S,"第18條",3,"SRF再利用-停止運作",
 "再利用者有何情形時，直轄市、縣（市）主管機關得令其停止再利用運作並限期改善？",
 ["再利用來源用途或產品未符清理計畫書檢核文件、廠內無應有設備或未正常運作、燃料未依規定採樣檢測或檢測報告不實、監視系統七日內故障二次以上未於一個工作日內修復","再利用機構之負責人變更未辦理登記、員工人數不足、營業額低於前一年度、或未於指定期限內參加主管機關舉辦之法規說明會等與運作管理有關之情形","再利用機構所在建築物未取得使用執照、消防安全設備檢查不合格、未設置員工休息室、或未依規定辦理勞工健康檢查等職業安全衛生方面之情形","再利用機構未於廠區設置地磅、未鋪設柏油路面、未種植綠籬、或未於出入口設置洗車設備等環境維護方面經主管機關認定應改善之情形"],"a",
 "第18條：再利用者有下列情形之一者，直轄市、縣（市）主管機關得令其停止再利用運作並要求限期改善：廢棄物來源、再利用用途、作業期程或產品項目未符合事業廢棄物清理計畫書之再利用檢核文件；廠內無應有設備或營運期間設備未運作或未正常運作；固體再生燃料未依規定採樣檢測分析、不符品質標準或檢測報告不實；閉路電視監視系統七日內故障達二次以上且未能於一個工作日內修復；未能提供遠端查看或不符附件七清晰辨識規定；銷售對象不符規定；規避妨礙拒絕查核等。",
 "In which cases may the local authority order a reuse operator to halt reuse operations and correct within a deadline?",
 ["Source, use, schedule or products not matching the approved plan, missing or malfunctioning equipment, improper testing or false reports, or repeated camera faults unrepaired in one working day","A change of the operator's responsible person left unregistered, insufficient staff, turnover below the previous year, or failing to attend a regulatory briefing held by the authority","The plant building lacking a use permit, failing fire safety inspection, having no staff rest room, or failing to arrange the statutory worker health examinations","The plant lacking a weighbridge, unpaved roads, no green hedge, or no wheel washing facility at the entrance as the authority considers should be improved"],
 "Article 18."),

(S,"第19條",3,"SRF再利用-停止銷售",
 "再利用者銷售、運送固體再生燃料有何情形時，主管機關得要求限期改善，未改善者得令其停止銷售或運送？",
 ["燃料未依規定採樣檢測或不符品質標準、銷售對象不符規定、提供不實驗證文件、送達數量超過買賣契約書所載數量、或使用者庫存量超過前三個月累積使用量","運送車輛未依規定噴漆標示、駕駛人未受專業訓練、未隨車攜帶運送聯單、或未於夜間行駛時裝設警示燈等交通運輸管理方面之相關違規情形之一者","銷售價格低於同業平均價格、未開立統一發票、未依規定申報營業稅、或未與使用者約定運費負擔方式等交易與稅務管理方面之相關違規情形之一者","未於銷售前公告產品規格、未建置產品官方網站、未提供使用者教育訓練、或未設置客戶服務專線等產品行銷與售後服務方面之相關情形之一者"],"a",
 "第19條：再利用者銷售、運送固體再生燃料有下列情形之一者，直轄市、縣（市）主管機關得要求限期改善，未改善者得令其停止銷售或運送至使用者：燃料未依規定採樣檢測分析、不符品質標準或檢測報告不實；銷售對象不符規定；未提供有效之第三方驗證證明文件且未檢具符合品質標準之檢測報告；提供不實之第三方驗證證明文件；送達數量超過買賣契約書所載數量；規避妨礙拒絕查核；使用者未依附表規定設施使用、設置監視系統、記錄、申報及確認品質；使用者庫存量超過前三個月累積使用量。",
 "In which cases may the authority order correction and, failing that, halt sale or delivery of SRF?",
 ["Improper testing or off-spec fuel, unqualified buyers, false verification documents, delivery exceeding the contract quantity, or user stock above three months of use","Delivery vehicles not painted with markings, untrained drivers, manifests not carried on board, or no warning lights fitted for night driving of the vehicles","Selling below the industry average price, not issuing uniform invoices, failing to file business tax, or not agreeing with the user on who bears freight","Not announcing product specifications before sale, having no product website, giving users no training, or providing no customer service hotline"],
 "Article 19."),

(S,"第20條",3,"SRF再利用-恢復與限制",
 "經令停止收受、停止再利用運作或停止銷售之再利用者，應如何恢復？其清理計畫書遭撤銷廢止者有何限制？",
 ["應檢具改善後證明文件或說明資料報主管機關核准後始得恢復；清理計畫書遭撤銷或廢止者，三年內不得以相同或類似機構名稱申請再利用檢核，其負責人三年內亦不得重新申請","應於改善完成後函報主管機關備查即得恢復；清理計畫書遭撤銷或廢止者，一年內不得以相同機構名稱申請再利用檢核，惟其負責人不受任何申請資格之限制","應俟停止處分屆滿六個月後自動恢復運作；清理計畫書遭撤銷或廢止者，五年內不得於同一直轄市、縣（市）轄區內申請再利用檢核，負責人並應永久除名","應向中央主管機關申請複審並經促進委員會決議後恢復；清理計畫書遭撤銷或廢止者，二年內不得申請再利用檢核，其負責人並得於改善後隨時重新申請"],"a",
 "第20條：經令停止收受事業廢棄物進廠（場）、停止再利用運作、停止銷售或運送之再利用者，應檢具改善後證明文件或說明資料報直轄市、縣（市）主管機關核准後，始得恢復；再利用者違反本辦法及同時違反事業廢棄物清理計畫書審查管理辦法，並經審核機關撤銷或廢止其清理計畫書者，於三年內不得以相同或類似機構名稱申請再利用檢核，其負責人於三年內亦不得重新申請為再利用者之負責人。",
 "How may a suspended reuse operator resume, and what restriction follows revocation of its waste disposal plan?",
 ["It must file proof of correction and obtain the authority's approval to resume; after revocation, no application under the same or similar name for three years, nor by its principal","It may resume simply by filing a report after correction; after revocation, no application under the same name for one year, while its principal faces no restriction at all","Operations resume automatically six months after the suspension order; after revocation, no application in the same municipality for five years and the principal is barred","It must apply to the central authority for re-review by the promotion committee; after revocation, no application for two years, though its principal may reapply anytime"],
 "Article 20."),

(S,"第21條",2,"SRF再利用-追蹤查核",
 "主管機關就事業廢棄物再利用之追蹤查核，其權限及相對人之義務為何？",
 ["主管機關得派員或委託相關機構進行追蹤查核，或要求提供廠內運作有關資料及說明，事業、再利用者及使用者應予配合","主管機關僅得於接獲檢舉時派員查核，且不得委託其他機構辦理；受查核者得以營業秘密為由拒絕提供廠內運作相關資料","主管機關應於查核前七日以書面通知受查核者，未通知者受查核者得拒絕查核；使用者不屬本辦法規範對象而免予配合查核","主管機關得委託同業公會辦理查核，查核結果應先送受查核者確認後始得作成紀錄；再利用者得就查核項目自行選擇提供資料"],"a",
 "第21條：主管機關得派員或委託相關機構進行事業廢棄物再利用之追蹤查核，或要求提供廠內運作有關資料及說明，事業、再利用者及使用者應予配合。第18條第7款、第19條第6款並將規避、妨礙、拒絕配合查核或拒絕提供資料列為得令停止運作或停止銷售之事由。",
 "What are the authority's tracking powers and the duties of those inspected?",
 ["The authority may send staff or commission bodies to track and inspect, or demand operating data and explanations, with enterprises, operators and users all cooperating","The authority may inspect only upon a complaint and may not commission others; those inspected may refuse operating data by invoking commercial secrecy","The authority must give seven days' written notice or inspection may be refused; users fall outside these Regulations and need not cooperate with inspections","The authority may commission the trade guild to inspect, results must be confirmed by the inspected party first, and operators may choose what data to supply"],
 "Article 21."),

(S,"第22條",3,"SRF再利用-過渡規定",
 "本辦法施行前經審查機關核准之事業廢棄物清理計畫書，其有關固體再生燃料原料用途部分應如何處理？",
 ["仍屬有效，但事業及再利用者應於本辦法施行後一年內辦理清理計畫書變更，經審核機關審查核准後始得依本辦法及附表規定從事再利用","自本辦法施行日起立即失其效力，事業及再利用者應於施行後三十日內停止再利用運作並重新提送事業廢棄物清理計畫書申請審查核准","仍屬有效且無須辦理任何變更，惟應自本辦法施行後三年內完成純化設備與均質化設備之設置並報請直轄市、縣（市）主管機關備查","仍屬有效，但事業及再利用者應於本辦法施行後六個月內取得第三方驗證證明文件，未取得者由審核機關逕行廢止其清理計畫書"],"a",
 "第22條：自本辦法施行日起，共通性事業廢棄物再利用管理辦法附表有關固體再生燃料原料用途之規定不再適用；事業及再利用者於本辦法施行前經審查機關核准之事業廢棄物清理計畫書，其有關該附表固體再生燃料原料用途部分仍屬有效，但應於本辦法施行後一年內辦理清理計畫書變更，經審核機關審查核准後，始得依本辦法及附表規定從事再利用。",
 "How are waste disposal plans approved before these Regulations treated as to SRF feedstock use?",
 ["They remain valid, but the plan must be amended within one year after these Regulations take effect and approved before reuse may continue under them","They lapse immediately on the effective date, and operations must stop within thirty days while a new waste disposal plan is submitted for approval","They remain valid with no amendment needed, provided purification and homogenization equipment is installed and filed within three years of effect","They remain valid, but third party verification must be obtained within six months, failing which the reviewing authority revokes the disposal plan"],
 "Article 22."),

(S,"第23條",1,"SRF再利用-施行日",
 "共通性事業廢棄物作為固體再生燃料原料再利用管理辦法之施行日期規定為何？",
 ["除另定施行日期者外，自發布日施行","一律自發布日施行，不得另定日期","自發布後六個月施行，不得另定日期","自發布後滿一年施行，不得另定日期"],"a",
 "第23條：本辦法除另定施行日期者外，自發布日施行。本辦法修正日期為民國114年1月17日；第22條並就施行前已核准之事業廢棄物清理計畫書定有一年內辦理變更之過渡規定。",
 "When do these SRF Regulations take effect?",
 ["They take effect on promulgation unless another effective date is set","They always take effect on promulgation and no other date may be set","They take effect six months after promulgation with no other date set","They take effect one year after promulgation with no other date set"],
 "Article 23."),

# ===== ENV-168 再生資源再使用管理辦法 =====
(U,"第1條",1,"再使用辦法-法源",
 "再生資源再使用管理辦法係依資源回收再利用法何條規定訂定？",
 ["依資源回收再利用法第十五條第二項規定訂定","依資源回收再利用法第十七條第二項規定訂定","依資源回收再利用法第十九條第一項規定訂定","依資源回收再利用法第二十六條第二項規定訂定"],"a",
 "第1條：本辦法依資源回收再利用法第十五條第二項規定訂定之。第2條規定本辦法適用之再生資源項目，第6條規定達一定規模之再使用業者應辦理登記，第19條定明本辦法自發布日施行。",
 "Under which article of the Resource Recycling Act are these Reuse Regulations enacted?",
 ["Enacted under Article 15, paragraph 2 of the Resource Recycling Act","Enacted under Article 17, paragraph 2 of the Resource Recycling Act","Enacted under Article 19, paragraph 1 of the Resource Recycling Act","Enacted under Article 26, paragraph 2 of the Resource Recycling Act"],
 "Article 1 states the statutory authority."),

(U,"第2條",2,"再使用辦法-適用項目",
 "本辦法適用之再生資源項目為何？",
 ["依本法第十五條第一項經環境部公告之再使用再生資源項目，及依同條第五項向環境部申請核准之項目","僅限依本法第十五條第一項經環境部公告之再使用再生資源項目，申請核准之項目不在本辦法適用範圍","僅限經中央目的事業主管機關指定之再生資源項目，環境部公告之項目應另依廢棄物清理法規定辦理","僅限經直轄市、縣（市）主管機關核准登記之再生資源項目，其餘項目均應依廢棄物清理法規定辦理"],"a",
 "第2條：本辦法適用之再生資源項目包括依本法第十五條第一項經環境部公告之再使用再生資源項目，及依本法第十五條第五項規定向環境部申請核准之再使用再生資源項目。第3條至第5條並規定公告項目之評估報告與審議程序。",
 "Which recycled resource items do these Regulations apply to?",
 ["Reuse items announced by the Ministry under Article 15, paragraph 1, and items approved on application under Article 15, paragraph 5","Only reuse items announced by the Ministry under Article 15, paragraph 1; items approved on application fall outside these Regulations","Only items designated by the central industry competent authority; items announced by the Ministry are governed by the Waste Disposal Act","Only items registered and approved by the municipal or county authority; all other items are governed by the Waste Disposal Act instead"],
 "Article 2."),

(U,"第3條",2,"再使用辦法-公告研擬",
 "環境部研擬再使用再生資源項目之公告時，得參酌何人所提之評估報告？",
 ["得參酌中央目的事業主管機關、再使用用途目的事業主管機關、地方主管機關、團體、事業或個人所提之經濟及技術可行性評估報告","僅得參酌中央目的事業主管機關所提之經濟及技術可行性評估報告，其他機關團體或個人所提報告不得作為研擬公告之參考依據","僅得參酌再生資源回收再利用促進委員會委員所提出之書面意見，並不得接受事業或個人所提出之任何經濟技術可行性評估報告","僅得參酌經環境部認可之學術機構所提出之研究報告，地方主管機關與相關團體所提之評估報告僅供備查而不作為研擬之依據"],"a",
 "第3條：環境部得參酌中央目的事業主管機關、再使用用途目的事業主管機關、地方主管機關、團體、事業或個人（申請人）所提再生資源再使用之經濟及技術可行性評估報告，研擬再使用再生資源項目之公告。第4條並列舉該評估報告應包括之內容。",
 "Whose assessment reports may the Ministry consider when drafting an announcement of reuse items?",
 ["Reports on economic and technical feasibility filed by the industry authority, the use-purpose authority, local authorities, groups, enterprises or individuals","Only reports on economic and technical feasibility filed by the central industry competent authority; reports from other bodies or individuals may not be used","Only written opinions submitted by members of the recycling and reuse promotion committee; reports from enterprises or individuals may not be accepted","Only research reports from academic institutions recognized by the Ministry; reports from local authorities and groups are for reference filing only"],
 "Article 3."),

(U,"第4條",3,"再使用辦法-評估報告內容",
 "再生資源再使用之經濟及技術可行性評估報告，應包括哪些內容？",
 ["相關法令標準、國內再使用再生資源產出現況與特性、國內外回收再利用現況、技術可行性評析、經濟可行性評析、回收再利用影響因子分析及結論與建議","申請人之公司登記資料、資本額、員工人數、廠房面積、機具設備清冊、近三年財務報表、股東名冊、營業稅繳納證明及同業公會會員證明等文件","再使用場所之土地登記謄本、地籍圖、都市計畫土地使用分區證明、建築物使用執照、消防安全設備竣工查驗合格證明及鄰地所有權人同意書等","再生資源之採樣計畫書、檢測報告、品質分級表、貯存設施設計圖、清運車輛清冊、駕駛人名冊及緊急應變計畫書等作業執行面之相關文件資料"],"a",
 "第4條：評估報告應包括相關法令標準（含環保與產品法規、品質規範）、國內再使用再生資源產出現況與特性、國內外回收再利用現況、技術可行性評析、經濟可行性評析、回收再利用影響因子分析及結論與建議。第5條並規定環境部得邀請申請人、有關機關、業者公會代表及專家學者進行初審。",
 "What must the economic and technical feasibility assessment report contain?",
 ["Applicable laws and standards, domestic output and characteristics, recycling practice at home and abroad, technical and economic feasibility, influence factors, and conclusions","The applicant's registration data, capital, headcount, plant area, equipment list, three years of financial statements, shareholder roster, tax receipts and guild membership","Land registration transcripts, cadastral maps, zoning certificates, building use permits, fire safety completion inspection certificates and consent of adjoining landowners","Sampling plans, test reports, quality grading tables, storage facility drawings, vehicle and driver rosters and emergency response plans for the operational side"],
 "Article 4."),

(U,"第5條",3,"再使用辦法-審議程序",
 "環境部接獲評估報告後之審議程序為何？公告後應如何檢討？",
 ["得邀請申請人、有關機關、業者公會代表及專家學者初審，申請人依初審意見修正後提再生資源回收再利用促進委員會審議通過後公告；公告後應定期檢討","應逕送再生資源回收再利用促進委員會審議，通過後即行公告；公告後除有重大變動外，原則上不再進行任何形式之定期檢討或修正作業","應先送中央目的事業主管機關核轉行政院核定後公告；公告後每五年由直轄市、縣（市）主管機關辦理一次檢討並函報環境部備查辦理","應由環境部委託學術機構完成複審後逕行公告；公告後由申請人自行檢討執行情形，並於每年年終函報環境部備查其執行成效與建議"],"a",
 "第5條：環境部接獲評估報告後，得邀請申請人、有關機關、相關業者及其公會代表、專家學者進行初審；申請人應依初審意見修正報告後送環境部提交再生資源回收再利用促進委員會審議，經審議通過後依本法第十五條第一項規定公告；公告後環境部應依實際執行情形、經濟及技術可行性及回收再利用影響因子變動情形定期檢討。",
 "What review procedure follows receipt of the report, and how is an announced item reviewed later?",
 ["A preliminary review with the applicant, agencies, industry and experts; the revised report goes to the promotion committee, and announced items are reviewed periodically","The report goes straight to the promotion committee and is announced once passed; after announcement no periodic review is made absent a major change of circumstances","The report goes through the industry authority to the Executive Yuan for approval and announcement; local authorities then review it every five years and file the result","The Ministry commissions an academic body to complete a second review and then announces it; the applicant reviews performance and files a report each year end"],
 "Article 5."),

(U,"第6條",3,"再使用辦法-登記申請",
 "從事再使用再生資源達一定規模之再使用業者，應向何機關申請登記？其登記內容有何拘束力？",
 ["應向再使用場（廠）所在地直轄市、縣（市）主管機關申請登記，並應依登記之項目技術方法量能及衍生廢棄物處置方式辦理，不得為未經登記之事項","應向環境部申請登記並取得再使用許可證，登記內容僅供主管機關統計參考，實際運作項目及方法得由業者視市場需求隨時自行調整而無須變更","應向中央目的事業主管機關申請登記並副知環境部，登記後三年內不得變更登記事項，逾三年始得申請變更其再使用項目與技術方法等內容","應向再使用場（廠）所在地鄉鎮市區公所申請登記，登記內容如與實際運作不符者，僅需於年度營運統計報表中敘明差異原因即可免受處罰"],"a",
 "第6條：從事再使用再生資源達一定規模之再使用業者應填具申請表，連同公司商業登記文件、負責人身分證明、再使用場（廠）之土地權利文件、再使用再生資源項目技術方法量能及衍生廢棄物處置方式等文件，向再使用場（廠）所在地直轄市、縣（市）主管機關申請登記；再使用業者應依第1項第4款之登記內容辦理，不得為未經登記之事項；業者規模由環境部另定之。",
 "To which authority must a reuse operator of a certain scale apply to register, and how binding is the registered content?",
 ["To the municipal or county authority where the site is located; the operator must follow the registered items, methods, capacity and residue handling and do nothing unregistered","To the Ministry for a reuse licence; the registered content is only for statistical reference and actual items and methods may be adjusted anytime as the market requires","To the central industry competent authority with a copy to the Ministry; registered particulars may not be changed for three years after the registration is granted","To the township or district office where the site is located; any mismatch with actual operations need only be explained in the annual operating statistics report"],
 "Article 6."),

(U,"第7條",2,"再使用辦法-補正期限",
 "主管機關受理再使用業者申請登記文件後，認有應行補正事項者，應於何時通知？",
 ["應於收文後十日內通知限期補正；必要時並得要求提示申請登記之文件正本供查核","應於收文後三十日內通知限期補正；必要時得要求申請人重新檢送全部文件正本","應於收文後六十日內通知限期補正；補正次數以三次為限，逾次數者應予駁回","應於收文後三日內通知限期補正；補正期間不得超過七日，逾期即視為撤回申請"],"a",
 "第7條：主管機關受理再使用業者申請登記之文件後，認有應行補正事項，應於收文後十日內通知限期補正；必要時，並得要求提示申請登記之文件正本供查核。第6條第3項並規定申請登記文件除申請表應為正本外，其餘得檢送影本供審查。",
 "When must the authority give notice of required corrections after receiving a registration application?",
 ["Within ten days of receipt, and it may require the originals of the application documents for checking","Within thirty days of receipt, and it may require the applicant to resubmit all originals afresh","Within sixty days of receipt, with corrections limited to three rounds before rejection follows","Within three days of receipt, with the correction period capped at seven days before withdrawal"],
 "Article 7."),

(U,"第8條",3,"再使用辦法-變更",
 "再使用業者之機構名稱地址、負責人資料變更，與其他登記文件內容變更，分別應如何辦理？",
 ["名稱地址及負責人資料變更應於變更後十五日內檢具證明文件辦理變更；其他登記文件內容變更應於變更前依申請登記之規定辦理","名稱地址及負責人資料變更應於變更前先報准始得變更；其他登記文件內容變更應於變更後三十日內檢具證明文件向主管機關辦理","名稱地址及負責人資料變更應於變更後九十日內辦理變更登記；其他登記文件內容變更得於次年度申請換發登記文件時一併辦理","名稱地址及負責人資料變更僅需於營運統計報表中載明；其他登記文件內容變更應向中央目的事業主管機關申請核准後辦理"],"a",
 "第8條：再使用業者之機構名稱及地址、負責人姓名住址及身分證明文件字號變更時，應於變更後十五日內檢具變更事項相關證明文件向主管機關辦理變更；其他申請登記文件內容變更時，應於變更前依本辦法申請登記之規定辦理。因辦理變更致主管機關不同時，應向原登記之主管機關申請，由其受理後轉請變更後之主管機關辦理。",
 "How are changes of name, address and principal handled, versus changes to other registered contents?",
 ["Name, address and principal changes are filed within fifteen days after the change; other registered contents must go through the registration procedure before changing","Name, address and principal changes need prior approval before taking effect; other registered contents are filed within thirty days after the change is made","Name, address and principal changes are registered within ninety days; other registered contents may be handled together at the next annual reissue of documents","Name, address and principal changes need only be noted in the operating report; other registered contents need approval from the central industry authority"],
 "Article 8."),

(U,"第9條",2,"再使用辦法-彙送",
 "主管機關辦理再使用業者之登記、變更，應如何彙送資料？",
 ["應於每月五日前將前一月辦理資料彙送環境部，留供查核之用","應於每季首月十日前將前一季辦理資料彙送環境部留供查核","應於每年一月底前將前一年度辦理資料彙送環境部留供查核","應於辦理完成後三日內將個案資料逐案函送環境部核備查驗"],"a",
 "第9條：主管機關辦理再使用業者之登記、變更，應於每月五日前將前一月辦理資料彙送環境部，留供查核。第12條第3項並規定主管機關應於每年一月、四月、七月及十月底前彙整業者申報資料及執行機關辦理情形，彙送環境部備查。",
 "How must the competent authority forward its registration and change records?",
 ["The previous month's records must be sent to the Ministry by the fifth of each month for inspection","The previous quarter's records must be sent to the Ministry by the tenth of each quarter's first month","The previous year's records must be sent to the Ministry by the end of January each year for inspection","Each case must be sent individually to the Ministry within three days after it has been processed"],
 "Article 9."),

(U,"第10條",2,"再使用辦法-終止暫停",
 "再使用業者終止或暫停營業六個月以上者，其尚未完成再使用之再生資源應如何處理？",
 ["應依主管機關之指示辦理，所需費用由再使用業者自行負擔；該再生資源無法再使用時，應依本法第十九條規定辦理","應由主管機關逕行代為清除處理，所需費用由主管機關編列預算支應；無法再使用者得逕行掩埋而免依本法辦理","應由原產生者無償取回並自行處理，所需費用由產生者負擔；無法再使用者應報請中央目的事業主管機關核准後銷毀","應由承接之其他再使用業者概括承受，所需費用由雙方自行約定；無法再使用者得暫存於原場所至有再使用需求為止"],"a",
 "第10條：再使用業者終止或暫停營業六個月以上者，其尚未完成再使用之再生資源，應依主管機關之指示辦理，所需費用由再使用業者自行負擔；前項再生資源無法再使用時，應依本法第十九條規定辦理。第17條並規定違反第10條者，主管機關應依本法第二十六條第一項第四款規定辦理。",
 "How must unreused resources be handled when an operator terminates or suspends business for over six months?",
 ["They must be handled as the competent authority directs at the operator's own cost; where reuse is impossible, Article 19 of the Act applies","The competent authority disposes of them directly at public expense; where reuse is impossible they may simply be landfilled outside the Act","The original generator must take them back free of charge at its own cost; where reuse is impossible destruction needs the industry authority's approval","A successor operator assumes them with costs agreed between the parties; where reuse is impossible they may stay stored until demand arises"],
 "Article 10."),

(U,"第11條",3,"再使用辦法-執行主體",
 "由家戶或其他非事業所產生之再生資源，及由事業所產生之再生資源，其再使用分別由何人為之？",
 ["家戶等非事業所產生者由產生地執行機關為之，執行機關得報經上級主管機關核准後委託合法登記之再使用業者；事業所產生者應自行或委託合法登記之再使用業者為之","家戶等非事業所產生者由中央主管機關統一委託再使用業者辦理；事業所產生者一律應委託執行機關辦理，不得自行再使用或委託民間再使用業者辦理","家戶等非事業所產生者由各該鄉鎮市區公所自行辦理且不得委外；事業所產生者應委託取得廢棄物處理許可證之公民營處理機構辦理再使用作業","家戶等非事業所產生者由回收商自行收購後辦理再使用；事業所產生者應由中央目的事業主管機關指定之再使用業者辦理而不得自行選擇對象"],"a",
 "第11條：由家戶或其他非事業所產生再生資源之再使用，由產生地之直轄市、縣（市）環境保護局（執行機關）為之，但執行機關得報經上級主管機關核准後，委託合法登記之再使用業者辦理；由事業所產生再生資源之再使用，應自行或委託合法登記之再使用業者為之，但經執行機關同意者，得委託其為之。",
 "Who carries out reuse of resources from households and from enterprises respectively?",
 ["Household resources are handled by the local executing agency, which may commission a registered operator with approval; enterprise resources go to themselves or a registered operator","Household resources are commissioned centrally to operators by the Ministry; enterprise resources must all be given to the executing agency and may not be self-handled at all","Household resources are handled by township offices with no outsourcing allowed; enterprise resources must go to firms holding waste treatment permits for the reuse work","Household resources are bought and reused by collectors themselves; enterprise resources must go to operators designated by the central industry authority without choice"],
 "Article 11."),

(U,"第12條",2,"再使用辦法-紀錄保存",
 "再使用業者對於再生資源再使用之運作，應作成何種紀錄並保存多久？",
 ["應就日期、種類、名稱、數量、用途、產生者名稱、再使用途徑、產銷情形及衍生廢棄物處置證明作成紀錄，妥善保存三年留供查核","應就日期、數量及用途作成簡要紀錄，妥善保存一年留供查核，其餘產生者名稱與產銷情形等資料得免予記錄而由主管機關逕行調查","應就進出場車輛之車號、駕駛人、過磅重量及時間作成紀錄，妥善保存五年留供查核，再生資源之種類用途等資料則免予作成紀錄","應就再生資源之採樣檢測結果及品質分級作成紀錄，妥善保存七年留供查核，日期數量與產銷情形等營運資料則得以口頭說明代之"],"a",
 "第12條第1項：再使用業者對於再生資源再使用之日期、種類、名稱、數量、用途、產生者名稱、再使用途徑、產銷情形及衍生廢棄物處置證明，應作成紀錄，妥善保存三年，留供查核。第17條並規定違反第12條第1項者，主管機關應依本法第二十六條第一項第四款規定辦理。",
 "What records must a reuse operator make, and for how long must they be kept?",
 ["Records of date, type, name, quantity, use, generator, reuse route, production and sales, and residue disposal proof, kept three years for inspection","Brief records of date, quantity and use kept one year for inspection; generator names and production and sales data need not be recorded by the operator","Records of vehicle plates, drivers, weighed loads and times kept five years for inspection; resource types and uses need not be recorded by the operator","Records of sampling test results and quality grades kept seven years for inspection; dates, quantities and sales data may be explained orally instead"],
 "Article 12, paragraph 1."),

(U,"第12條",3,"再使用辦法-季報申報",
 "再使用業者應於何時檢具營運統計報表向主管機關申報？主管機關又應於何時彙送環境部？",
 ["業者應於每年一月、四月、七月及十月十五日前檢具前一季報表申報；主管機關應於每年一月、四月、七月及十月底前彙送環境部備查","業者應於每年一月及七月十五日前檢具前半年報表申報；主管機關應於每年二月及八月底前彙整資料函送中央目的事業主管機關備查","業者應於每月十日前檢具前一月報表申報；主管機關應於每月二十日前彙整資料以網路傳輸方式傳送環境部及執行機關共同備查使用","業者應於每年十二月底前檢具當年度報表申報；主管機關應於次年三月底前彙整資料連同稽查紀錄一併函報環境部審查後公告周知"],"a",
 "第12條第2項、第3項：再使用業者應於每年一月、四月、七月及十月十五日前，檢具前一季營運統計報表向主管機關以書面申報，屬本法公告應以網路傳輸方式申報者依其規定；主管機關應於每年一月、四月、七月及十月底前，彙整再使用業者所申報資料及執行機關辦理再生資源再使用情形，彙送環境部備查。",
 "When must operators file quarterly operating statistics, and when must the authority forward them?",
 ["Operators file the previous quarter by the fifteenth of January, April, July and October; the authority forwards to the Ministry by the end of those months","Operators file each half year by the fifteenth of January and July; the authority compiles and sends the data to the central industry authority by end February and August","Operators file the previous month by the tenth of each month; the authority transmits the compiled data online to the Ministry and executing agency by the twentieth","Operators file the year's report by the end of December; the authority compiles it with inspection records and reports to the Ministry by the end of March next year"],
 "Article 12, paragraphs 2 and 3."),

(U,"第13條",3,"再使用辦法-清運規定",
 "清運再使用再生資源之車輛機具，其清運過程應遵守哪些規定？",
 ["應防止飛散濺落溢漏惡臭擴散爆炸等污染環境或危害人體健康情事，應隨車攜帶清運證明文件，不同項目原則應分類清運，發生污染應立即採取緊急應變措施","僅需依道路交通管理處罰條例規定加蓋帆布並限制載重，清運證明文件得於送達目的地後補行製作，不同項目得混合清運而無須辦理分類清運作業","應於清運前三日向主管機關報備清運路線與時間，並全程開啟即時追蹤系統，清運車輛應噴印統一識別標誌，不同項目應以專用車輛個別清運","應由取得廢棄物清除許可證之清除機構清運並填具遞送聯單，清運車輛應設置密閉式車廂及秤重設備，清運過程發生污染者應於七日內報備處理"],"a",
 "第13條：清運再使用再生資源之車輛機具於清運過程中，應防止再使用再生資源飛散、濺落、溢漏、惡臭擴散、爆炸等污染環境或危害人體健康之情事發生；清運應隨車攜帶清運證明文件，但公告及核准之項目另有規定者從其規定；不同項目除另有規定外應分類清運；清運過程發生污染環境或危害人體健康情事時，清運者應立即採取緊急應變措施。",
 "What rules govern vehicles transporting recycled resources for reuse?",
 ["Prevent scattering, spillage, leakage, odor spread and explosion; carry transport documents on board; separate different items; and take immediate emergency measures on pollution","Simply cover the load with a tarpaulin and observe weight limits; transport documents may be made after arrival; different items may be mixed without separate transport","Report the route and time to the authority three days ahead and run real time tracking throughout; mark vehicles with a uniform logo; carry each item on a dedicated vehicle","Use a licensed clearance organization with manifests; fit enclosed compartments and weighing equipment; and report any pollution during transport within seven days"],
 "Article 13."),

(U,"第14條",3,"再使用辦法-貯存方法",
 "再使用再生資源之貯存方法，關於堆置之高度與分隔走道有何規定？",
 ["有堆置必要者應分區堆置，堆置高度不得超過五公尺，各區域間應有一公尺以上之分隔走道，並應採必要措施防止掉落或崩塌","有堆置必要者應集中堆置，堆置高度不得超過十公尺，各區域間應有三公尺以上之分隔走道，並應採必要措施防止掉落或崩塌","有堆置必要者應分區堆置，堆置高度不得超過三公尺，各區域間應有二公尺以上之分隔走道，並應設置擋土牆以防止崩塌情事","有堆置必要者應分層堆置，堆置高度不得超過八公尺，各區域間應有零點五公尺以上之走道，並應覆蓋防塵網以防止飛散情事"],"a",
 "第14條第1項第3款：再使用再生資源有堆置之必要者，應分區堆置，其堆置高度不得超過五公尺，各區域間應有一公尺以上之分隔走道，並應採行必要措施以防止堆置之再使用再生資源發生掉落或崩塌等情事。同項並要求貯存地點容器設施保持清潔完整、不得飛揚逸散滲出污染地面或散發惡臭，且容器設施應與所存放者具有相容性並分類貯存。",
 "What rules apply to stacking height and separation aisles when storing recycled resources for reuse?",
 ["Stacks must be zoned, not exceed five meters high, with aisles of at least one meter between zones, and measures to prevent falling or collapse","Stacks must be concentrated, not exceed ten meters high, with aisles of at least three meters between zones, and measures to prevent falling or collapse","Stacks must be zoned, not exceed three meters high, with aisles of at least two meters between zones, and retaining walls to prevent any collapse","Stacks must be layered, not exceed eight meters high, with aisles of at least half a meter between zones, and dust nets to prevent any scattering"],
 "Article 14, paragraph 1, subparagraph 3."),

(U,"第15條",2,"再使用辦法-貯存設施",
 "再使用再生資源之貯存設施，應符合哪些規定？",
 ["應有防止污染地面水體地下水體空氣土壤之設備或措施、以中文標示名稱、具防止掉落溢散洩漏惡臭之設備、四周設置圍籬並設置消防設施","應有防止污染之設備、以中英文雙語標示名稱、設置二十四小時警衛人員、四周設置三公尺圍牆並裝設紅外線感應之防盜與監視系統設備","應有防止污染之設備、設置地磅與計量設備、鋪設不透水混凝土地坪、設置滲出水收集池並委託合格檢測機構每季檢測地下水水質一次","應有防止污染之設備、設置排水溝與沉砂池、屋頂加蓋以防雨水侵入、設置獨立電表與水表並每月向主管機關申報用水用電之數量資料"],"a",
 "第15條：再使用再生資源之貯存設施應有防止污染地面水體、地下水體、空氣、土壤之設備或措施；貯存地點容器設施應於明顯處以中文標示再使用再生資源之名稱；具有防止掉落、溢散、洩漏、散發惡臭及影響四周環境品質之必要設備或措施；貯存場（廠）區四周應設置圍籬；貯存場（廠）區應設置消防設施；並應符合公告項目及管理方式或核准計畫書內容之相關規定。",
 "What must storage facilities for recycled resources meet?",
 ["Equipment against pollution of water, air and soil; Chinese labelling of the name; devices against falling, spillage, leakage and odor; a perimeter fence; and fire equipment","Equipment against pollution; bilingual Chinese and English labelling; round the clock security guards; a three meter wall; and infrared intrusion detection and monitoring","Equipment against pollution; a weighbridge and metering devices; impermeable concrete flooring; a leachate collection pond; and quarterly groundwater testing by a laboratory","Equipment against pollution; drainage ditches and sedimentation basins; roofing against rain ingress; separate meters; and monthly reporting of water and power consumption"],
 "Article 15."),

(U,"第16條",2,"再使用辦法-再使用設施",
 "再使用業者進行再生資源再使用所設置之設施，應符合哪些規定？",
 ["應具堅固之基礎結構、與再生資源接觸表面採不透水材料構築（必要時另採抗蝕材料）、具污染防治設施及防止與警示火災爆炸之功能","應具堅固之基礎結構、設置獨立之進出通道與停車空間、具備自動化控制系統及設置員工休息室與盥洗設備等勞工安全衛生設施","應取得建築物使用執照及工廠登記證、設置符合規定之消防安全設備、通過職業安全衛生管理系統驗證並每年辦理一次設施安全檢查","應委由技師設計簽證並經公會審查、使用符合國家標準之材料構築、設置備援電力系統並每半年辦理一次設施功能測試及紀錄保存"],"a",
 "第16條：再使用業者進行再生資源再使用所設置之設施，應具堅固之基礎結構；設施與再使用再生資源接觸之表面採不透水材料構築，必要時應另採抗蝕材料構築；具污染防治設施；具防止及警示火災、爆炸之功能；並應符合公告之再使用再生資源項目及管理方式或核准計畫書內容之再使用設施規範相關規定。",
 "What must facilities used for reusing recycled resources comply with?",
 ["A solid foundation structure; impermeable material where the resource contacts it, corrosion resistant if needed; pollution control equipment; and fire and explosion prevention and warning","A solid foundation structure; a separate access road and parking area; an automated control system; and staff rest rooms and washing facilities for occupational safety and health","A building use permit and factory registration; compliant fire safety equipment; certification of an occupational safety management system; and an annual facility safety inspection","Design certified by a licensed engineer and reviewed by the guild; construction in materials meeting national standards; backup power; and semiannual function tests with records"],
 "Article 16."),

(U,"第17條",2,"再使用辦法-違反處理",
 "違反本辦法有關終止暫停營業、紀錄保存、清運、貯存及設施等規定者，主管機關應如何辦理？",
 ["應依資源回收再利用法第二十六條第一項第四款規定辦理其處分事宜","應依廢棄物清理法第五十二條規定按次處罰並命其限期改善其違規","應依水污染防治法第四十六條規定裁處罰鍰並命其停工停業之處分","應逕行廢止其登記文件並於三年內不受理該業者重新申請登記案件"],"a",
 "第17條：違反第10條、第12條第1項、第13條至第16條規定者，主管機關應依本法第二十六條第一項第四款規定辦理。上開條文分別規範終止暫停營業之再生資源處理、運作紀錄保存三年、清運、貯存方法、貯存設施及再使用設施等義務。",
 "How must the authority act against breaches of the termination, record, transport, storage and facility rules?",
 ["It must proceed under Article 26, paragraph 1, subparagraph 4 of the Resource Recycling Act","It must impose repeat penalties and order correction under Article 52 of the Waste Disposal Act","It must impose a fine and order shutdown under Article 46 of the Water Pollution Control Act","It must revoke the registration outright and refuse any new application for three years"],
 "Article 17."),

(U,"第18條",1,"再使用辦法-文書格式",
 "再生資源再使用管理辦法所定之相關文書及證明文件格式，由何機關訂定？",
 ["由中央主管機關（環境部）定之","由中央目的事業主管機關定之","由直轄市、縣（市）主管機關定之","由回收再利用促進委員會定之"],"a",
 "第18條：本辦法所定之相關文書及證明文件格式，由環境部定之。第6條第4項並規定應辦理登記之再使用業者規模，由環境部另定之。",
 "Which authority prescribes the document and certificate formats under these Regulations?",
 ["They are prescribed by the Ministry of Environment","They are prescribed by the central industry authority","They are prescribed by the municipal or county authority","They are prescribed by the recycling promotion committee"],
 "Article 18."),

(U,"第19條",1,"再使用辦法-施行日",
 "再生資源再使用管理辦法之施行日期為何？",
 ["本辦法自發布日起施行","本辦法自發布後三個月施行","本辦法自發布後六個月施行","本辦法自發布後滿一年施行"],"a",
 "第19條：本辦法自發布日施行。本辦法修正日期為民國114年11月21日，授權依據為資源回收再利用法第十五條第二項；第17條並定明違反特定條文者應依本法第二十六條第一項第四款辦理。",
 "When do these Reuse Regulations take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect six months after promulgation","They take effect one full year after promulgation"],
 "Article 19."),
]
