# -*- coding: utf-8 -*-
Q = [
# ===================== ENV-212 飲用水水源水質或淨水處理改善計畫審核準則 =====================
("ENV-212","第1條",1,"改善計畫審核-法源",
 "飲用水水源水質或淨水處理改善計畫審核準則係依據哪一條文授權訂定？",
 ["依飲用水管理條例第六條第一項規定訂定之","依飲用水管理條例第十三條第二項規定訂定之","依飲用水管理條例第十一條第三項規定訂定之","依飲用水管理條例第二十二條第一項規定訂定之"],"a",
 "第1條：本準則依飲用水管理條例第六條第一項規定訂定，規範水源水質不合格時提出改善計畫並經審核後始得繼續作為飲用水水源之程序。",
 "Under which provision are these Regulations for reviewing drinking water source or treatment improvement plans adopted?",
 ["Adopted under Article 6, Paragraph 1 of the Drinking Water Management Act","Adopted under Article 13, Paragraph 2 of the Drinking Water Management Act","Adopted under Article 11, Paragraph 3 of the Drinking Water Management Act","Adopted under Article 22, Paragraph 1 of the Drinking Water Management Act"],
 "Article 1: adopted under Article 6(1) of the Drinking Water Management Act."),

("ENV-212","第2條",1,"改善計畫審核-申請資格",
 "申請提出飲用水水源水質或淨水處理改善計畫者，應具備何種資格？",
 ["應為自來水事業、社區自設公共給水設備之管理單位或簡易自來水之管理單位其中之一","應為環境檢驗測定機構、水利技師事務所或工程顧問公司等專業機構其中之一","應為直轄市、縣（市）主管機關、鄉鎮市公所或流域管理委員會其中之一","應為自來水事業、飲用水設備販賣業者或包裝水製造業者其中之一"],"a",
 "第2條：提出改善計畫者應具備自來水事業、社區自設公共給水設備之管理單位或簡易自來水之管理單位資格之一，與飲用水水質處理藥劑申請公告作業準則第2條之資格規定相同。",
 "Who may submit a drinking water source or treatment improvement plan?",
 ["A water supply enterprise, the manager of a community self-built public water supply facility, or the manager of a simplified tap water system","An environmental testing organization, a hydraulic engineering consultancy, or an engineering consulting company as a professional body","A municipal or county competent authority, a township or city office, or a river basin management committee","A water supply enterprise, a drinking water equipment vendor, or a packaged water manufacturing business"],
 "Article 2: water supply enterprise, community facility manager, or simplified tap water manager."),

("ENV-212","第3條",2,"改善計畫審核-送件程序",
 "提出改善計畫者，應檢具資料幾份、循何種程序報送？",
 ["應檢具資料一式十份，報該目的事業主管機關轉中央主管機關審核，並副知轄區直轄市、縣（市）主管機關","應檢具資料一式十五份，逕送中央主管機關審核，並副知該目的事業主管機關及轄區鄉鎮市公所","應檢具資料一式五份，報轄區直轄市、縣（市）主管機關審核，並副知該目的事業主管機關備查","應檢具資料一式二十份，報該目的事業主管機關逕行核定，並副知中央主管機關及水利主管機關"],"a",
 "第3條第1項：提出改善計畫者應檢具基本資料表、水源水質現況及檢驗報告等資料一式十份，報該目的事業主管機關轉中央主管機關審核，並副知轄區直轄市、縣（市）主管機關。",
 "How many copies are required and through what channel is the plan filed?",
 ["Ten copies, filed with the industry competent authority for transfer to the central authority, copying the municipal or county authority","Fifteen copies, filed directly with the central competent authority, copying the industry competent authority and the township office","Five copies, filed with the municipal or county competent authority for review, copying the industry competent authority for record","Twenty copies, filed with the industry competent authority for direct approval, copying the central authority and the water resources authority"],
 "Article 3(1): ten copies via the industry competent authority to the central authority."),

("ENV-212","第3條",3,"改善計畫審核-應附資料",
 "改善計畫應檢具之資料內容，以及本準則所稱目的事業主管機關為何？",
 ["內容含水源水質現況及檢驗報告、改善工作內容、計畫期程經費、改善後水質預測、水質監測計畫及應變措施；自來水為中央水利主管機關，簡易自來水及社區自設公共給水為直轄市、縣（市）政府","內容含水源水質現況及檢驗報告、改善工作內容、計畫期程經費、改善後水質預測、水質監測計畫及應變措施；自來水為中央主管機關，簡易自來水及社區自設公共給水為鄉鎮市公所","內容含用水人口統計、售水費率結構、財務計畫、管線汰換進度、用戶抱怨處理紀錄及設備採購清冊；自來水為中央水利主管機關，簡易自來水及社區自設公共給水為經濟部","內容含水源水質現況及檢驗報告、改善工作內容、計畫經費、環境影響評估書件及土地取得證明；自來水為直轄市、縣（市）政府，簡易自來水及社區自設公共給水為中央水利主管機關"],"a",
 "第3條第1項各款：應檢具基本資料表、水源水質現況及檢驗報告、改善工作內容、計畫期程、計畫經費、改善後水質預測、水質監測計畫、改善期間應變措施、預定進度表及需其他機關配合事項。第2項：目的事業主管機關在自來水為中央水利主管機關，在簡易自來水及社區自設公共給水為直轄市、縣（市）政府。",
 "What must the plan contain, and who is the industry competent authority?",
 ["Source water quality status and test reports, improvement work, schedule and budget, predicted water quality, monitoring plan and contingency measures; the central water authority for tap water, the municipal or county government for the others","Source water quality status and test reports, improvement work, schedule and budget, predicted water quality, monitoring plan and contingency measures; the central competent authority for tap water, the township office for the others","Water use population statistics, tariff structure, financial plan, pipeline replacement progress, customer complaint records and equipment purchase lists; the central water authority for tap water, the Ministry of Economic Affairs for the others","Source water quality status and test reports, improvement work, budget, environmental impact assessment documents and land acquisition proof; the municipal or county government for tap water, the central water authority for the others"],
 "Article 3: ten listed items; central water authority for tap water, local government for the rest."),

("ENV-212","第4條",1,"改善計畫審核-審核組成",
 "中央主管機關審核飲用水水源水質或淨水處理改善計畫時，得如何進行？",
 ["得邀集專家、學者、相關機關（構）等審核改善計畫","應委由該目的事業主管機關邀集業者代表審核計畫","應交由轄區直轄市、縣（市）主管機關代為審核計畫","應由行政院成立跨部會審查小組專責審核改善計畫"],"a",
 "第4條：中央主管機關得邀集專家、學者、相關機關（構）等審核改善計畫；審核期限依第5條、審核結果依第6條辦理。",
 "How may the central authority conduct the review of an improvement plan?",
 ["It may convene experts, scholars and relevant agencies or institutions to review the plan","It must let the industry competent authority convene industry representatives to review","It must have the municipal or county competent authority review the plan on its behalf","It must have the Executive Yuan form an interministerial task force to review plans"],
 "Article 4: experts, scholars and relevant agencies may be convened."),

("ENV-212","第5條",2,"改善計畫審核-審核期限",
 "中央主管機關審核改善計畫申請時，其補正與審核期限規定為何？",
 ["文件欠缺者通知限期補正，屆期未補正予以退件，但期限屆至前有正當理由報經核准得展延；文件齊備者應於六十日內完成審核，補正日數不計入","文件欠缺者通知限期補正，屆期未補正予以退件，且不得申請展延補正期限；文件齊備者應於三十日內完成審核，補正日數應計入審核期間","文件欠缺者應逕予退件不另通知補正，申請人得重新提出申請；文件齊備者應於九十日內完成審核，補正日數不計入審核期間內","文件欠缺者通知限期補正，屆期未補正視為撤回申請案；文件齊備者應於五十工作日內完成審核，並得延長一次五十工作日"],"a",
 "第5條：文件或資料有欠缺或不合規定者通知限期補正，屆期未補正者予以退件，但期限屆至前有正當理由報經中央主管機關核准展延者不在此限；文件齊備者應於六十日內完成審核，各項補正日數不計入審核期間內。",
 "What are the supplementation and review time limits?",
 ["Incomplete filings get a correction deadline and are returned if missed, though an extension may be approved for good cause; complete filings are reviewed within 60 days, excluding supplementation days","Incomplete filings get a correction deadline and are returned if missed, with no extension allowed; complete filings are reviewed within 30 days, and supplementation days are counted in full","Incomplete filings are returned directly without a correction notice and may be refiled; complete filings are reviewed within 90 days, excluding supplementation days","Incomplete filings get a correction deadline and are deemed withdrawn if missed; complete filings are reviewed within 50 working days, extendable once by 50 working days"],
 "Article 5: 60 days for review; correction deadline with possible extension for good cause."),

("ENV-212","第6條",2,"改善計畫審核-審核結果",
 "中央主管機關審查改善計畫相關資料後，其准駁效果為何？",
 ["認其水質可改善者，始得繼續作為飲用水之水源；經審查未能改善者，駁回其申請","認其水質可改善者，得免依飲用水水質標準辦理檢驗；未能改善者，通知補正","認其水質可改善者，由中央主管機關公告該水源名稱；未能改善者，移送裁罰","認其水質可改善者，核發水源使用許可證三年；未能改善者，得附條件核准"],"a",
 "第6條第1項：經審查改善工作內容、期程、水質監測計畫、改善後水質預測、應變措施、預定進度及其他資料後，認其水質可改善者始得繼續作為飲用水之水源；審查未能改善者駁回其申請。",
 "What follows from the central authority's substantive review of the plan?",
 ["If the water quality can be improved, the source may continue to be used for drinking water; if not, the application is rejected","If the water quality can be improved, testing under the water quality standards may be waived; if not, correction is required","If the water quality can be improved, the central authority announces the name of the source; if not, the case goes to penalty","If the water quality can be improved, a three-year source use licence is issued; if not, conditional approval may be given"],
 "Article 6(1): continued use as a drinking water source if improvable, otherwise rejection."),

("ENV-212","第6條",2,"改善計畫審核-執行進度",
 "改善計畫經審查核可者，於執行期間應如何辦理進度回報？",
 ["應依改善計畫執行，並每三個月填報計畫執行進度表送中央主管機關備查，並副知轄區直轄市、縣（市）主管機關","應依改善計畫執行，並每六個月填報計畫執行進度表送目的事業主管機關備查，並副知中央主管機關查核","應依改善計畫執行，並每一個月填報計畫執行進度表送轄區直轄市、縣（市）主管機關核定後公告","應依改善計畫執行，並於計畫完成後一次填報執行成果報告送中央主管機關核備，無須期中回報"],"a",
 "第6條第2項：經審查核可者應依改善計畫執行，並每三個月填報計畫執行進度表，送中央主管機關備查，並副知轄區直轄市、縣（市）主管機關。",
 "How must progress be reported once the plan is approved?",
 ["Implement the plan and file a progress report every three months with the central authority for record, copying the municipal or county authority","Implement the plan and file a progress report every six months with the industry competent authority for record, copying the central authority","Implement the plan and file a progress report every month with the municipal or county authority for approval and public announcement","Implement the plan and file a single completion report with the central authority afterwards, with no interim progress reporting required"],
 "Article 6(2): quarterly progress reports to the central authority, copying the local authority."),

("ENV-212","第7條",1,"改善計畫審核-施行",
 "飲用水水源水質或淨水處理改善計畫審核準則之施行日期為何？",
 ["本準則自發布日施行","本準則自發布後三個月施行","本準則自發布後一年施行","本準則自九十六年一月一日施行"],"a",
 "第7條：本準則自發布日施行，無另定緩衝期間。",
 "When do these Regulations take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect one year after promulgation","They take effect on January 1 of Year 96 (2007)"],
 "Article 7: effective upon promulgation."),

# ===================== ENV-213 氣候變遷風險評估作業準則 =====================
("ENV-213","第1條",1,"氣候風險評估-法源",
 "氣候變遷風險評估作業準則係依據哪一條文授權訂定？",
 ["依氣候變遷因應法第十八條第三項規定訂定之","依氣候變遷因應法第二十八條第二項規定訂定之","依氣候變遷因應法第十二條第四項規定訂定之","依氣候變遷因應法第二十二條第一項規定訂定之"],"a",
 "第1條：本準則依氣候變遷因應法第十八條第三項規定訂定。氣候法第十八條課予各級政府進行氣候變遷風險評估並據以研擬調適方案之義務，本準則規範其作業程序。",
 "Under which provision are the Climate Change Risk Assessment Regulations adopted?",
 ["Adopted under Article 18, Paragraph 3 of the Climate Change Response Act","Adopted under Article 28, Paragraph 2 of the Climate Change Response Act","Adopted under Article 12, Paragraph 4 of the Climate Change Response Act","Adopted under Article 22, Paragraph 1 of the Climate Change Response Act"],
 "Article 1: adopted under Article 18(3) of the Climate Change Response Act."),

("ENV-213","第2條",2,"氣候風險評估-定義",
 "本準則所稱氣候變遷風險評估及衝擊，定義分別為何？",
 ["氣候變遷風險評估指對氣候變遷風險進行量化或質化之科學評估，並考量危害度、暴露度及脆弱度等風險要素之關聯影響；衝擊指極端天氣、氣候事件及氣候變遷趨勢對自然、人類系統之影響","氣候變遷風險評估指以溫室氣體排放清冊推估未來排放趨勢，並考量減量成本、技術可行性及產業競爭力等要素；衝擊指極端天氣、氣候事件對於溫室氣體排放總量所產生之變化","氣候變遷風險評估指對氣候變遷風險進行量化之財務評估，並考量保險費率、資產價值及市場波動等要素之關聯；衝擊指自然人為氣候危害事件之嚴重度或其長期之變化趨勢","氣候變遷風險評估指針對高風險地區進行地質與水文之工程調查，並考量降雨強度、地層下陷及土地利用等因素；衝擊指暴露對象於現況與未來風險評估結果間之落差"],"a",
 "第2條第1、2款：氣候變遷風險評估指對氣候變遷風險進行量化或質化之科學評估，並考量危害度、暴露度及脆弱度等風險要素之關聯影響；衝擊指極端天氣、氣候事件及氣候變遷趨勢對於自然、人類系統之影響，即氣候危害及暴露對象交互作用後所衍生之後果。",
 "How are climate change risk assessment and impact defined?",
 ["Risk assessment is a quantitative or qualitative scientific assessment of climate risk considering the linked effects of hazard, exposure and vulnerability; impact is the effect of extreme weather, climate events and trends on natural and human systems","Risk assessment projects future emission trends from the greenhouse gas inventory considering abatement cost, technical feasibility and industrial competitiveness; impact is the change in total greenhouse gas emissions caused by extreme weather","Risk assessment is a quantitative financial assessment of climate risk considering insurance rates, asset values and market volatility; impact is the severity or long-term trend of natural or human-induced climate hazard events","Risk assessment is a geological and hydrological engineering survey of high risk areas considering rainfall intensity, land subsidence and land use; impact is the gap between current and future risk assessment results for exposed objects"],
 "Article 2(1)-(2): scientific assessment of hazard, exposure and vulnerability; impact on natural and human systems."),

("ENV-213","第2條",2,"氣候風險評估-定義",
 "本準則所稱危害度、暴露度及脆弱度之定義分別為何？",
 ["危害度指自然或人為導致之氣候危害事件嚴重度或變化趨勢；暴露度指實際或可能受衝擊之暴露對象存在之規模或程度；脆弱度指暴露對象易受負面影響之程度，含敏感、易致受損及缺乏調適能力","危害度指暴露對象易受負面影響之敏感程度與易致受損程度；暴露度指氣候危害事件發生之頻率與強度變化趨勢；脆弱度指實際或可能受到氣候衝擊之暴露對象存在之規模或其程度","危害度指自然或人為導致之氣候危害事件嚴重度或變化趨勢；暴露度指暴露對象缺乏應對與調適之能力程度；脆弱度指設定一致氣候情境後所進行之衝擊模擬與風險評估結果之落差","危害度指極端天氣對於自然及人類系統所衍生之後果；暴露度指高暴露度、高脆弱度且易受氣候危害影響之地理空間範圍；脆弱度指阻礙調適行動規劃或實施成效之各項因素"],"a",
 "第2條第3至5款：危害度指自然或人為導致之氣候危害事件嚴重度或變化趨勢，可能加劇暴露對象之不利影響；暴露度指實際或可能受衝擊之暴露對象存在之規模或程度；脆弱度指暴露對象易受負面影響之程度，包括敏感程度、易致受損程度及缺乏應對、調適之能力。",
 "How are hazard, exposure and vulnerability defined?",
 ["Hazard is the severity or trend of natural or human-induced climate hazard events; exposure is the scale or extent of objects actually or potentially affected; vulnerability is the degree of susceptibility, including sensitivity, damage propensity and lack of adaptive capacity","Hazard is the sensitivity and damage propensity of exposed objects to negative effects; exposure is the frequency and intensity trend of climate hazard events; vulnerability is the scale or extent of objects actually or potentially affected by climate impacts","Hazard is the severity or trend of natural or human-induced climate hazard events; exposure is the degree to which objects lack response and adaptive capacity; vulnerability is the gap between impact simulation and risk assessment results under a set scenario","Hazard is the consequence of extreme weather for natural and human systems; exposure is the geographic area with high exposure, high vulnerability and susceptibility to hazards; vulnerability is the set of factors obstructing adaptation planning or its effectiveness"],
 "Article 2(3)-(5): hazard severity, scale of exposed objects, and degree of susceptibility."),

("ENV-213","第2條",3,"氣候風險評估-定義",
 "本準則所稱調適應用情境、調適差距及高風險地區之定義分別為何？",
 ["調適應用情境指為助各級政府執行風險評估而設定一致之氣候情境；調適差距指評估暴露對象於現況與未來風險評估結果之落差；高風險地區指高暴露度、高脆弱度及易受氣候危害影響之地理空間範圍","調適應用情境指可應用於降低調適差距且具氣候調適之策略措施及行動；調適差距指阻礙調適行動規劃或實施之因素；高風險地區指實際或可能受衝擊之暴露對象存在之規模或程度所及範圍","調適應用情境指依當期氣候變遷科學報告所推估之溫升幅度區間；調適差距指各級政府調適預算編列與實際支出之差額；高風險地區指經中央主管機關公告應優先辦理環境影響評估之地區","調適應用情境指極端天氣及氣候事件對自然與人類系統之後果；調適差距指暴露對象敏感程度與易致受損程度之差異；高風險地區指氣候危害事件嚴重度或變化趨勢達一定門檻之行政區域"],"a",
 "第2條第6至8款：調適應用情境指為有助各級政府執行氣候變遷風險評估，設定一致之氣候情境，就各易受氣候變遷衝擊領域進行衝擊模擬、風險評估及調適規劃；調適差距指評估暴露對象於現況與未來氣候變遷風險評估結果之落差；高風險地區指高暴露度、高脆弱度及易受氣候危害影響之地理空間範圍。",
 "How are adaptation application scenario, adaptation gap and high risk area defined?",
 ["The scenario is a consistent climate scenario set to help governments assess risk; the gap is the difference between current and future risk assessment results for exposed objects; a high risk area is an area of high exposure, high vulnerability and hazard susceptibility","The scenario is the set of strategies, measures and actions usable to reduce the adaptation gap; the gap is the set of factors obstructing adaptation planning or implementation; a high risk area is the scale or extent of objects actually or potentially affected","The scenario is the warming range projected in the current climate change science report; the gap is the difference between budgeted and actual adaptation spending by governments; a high risk area is an area announced by the central authority as requiring priority EIA","The scenario is the consequence of extreme weather and climate events for natural and human systems; the gap is the difference between sensitivity and damage propensity of exposed objects; a high risk area is a district whose hazard severity exceeds a set threshold"],
 "Article 2(6)-(8): consistent climate scenario, gap between current and future results, and high exposure and vulnerability areas."),

("ENV-213","第2條",2,"氣候風險評估-定義",
 "本準則所稱調適選項與調適障礙之定義分別為何？",
 ["調適選項指可應用於降低調適差距且具氣候調適之策略、措施及行動；調適障礙指阻礙調適行動規劃、實施或降低其成效之因素，可能涉及物理、生態、技術、經濟、社會、文化、制度、治理或資訊等面向","調適選項指為助各級政府執行風險評估而設定之一致氣候情境；調適障礙指評估暴露對象於現況與未來氣候變遷風險評估結果之落差，並涉及物理、生態、技術、經濟或治理等各項面向","調適選項指高暴露度、高脆弱度且易受氣候危害影響之地理空間範圍；調適障礙指自然或人為導致之氣候危害事件嚴重度或其變化趨勢，可能加劇暴露對象所承受之各種不利影響","調適選項指政府依當期氣候變遷科學報告所編列之調適預算項目；調適障礙指暴露對象易受負面影響之程度，包括敏感程度、易致受損程度及缺乏應對與調適能力等各面向之情形"],"a",
 "第2條第9、10款：調適選項指可應用於降低調適差距且具氣候調適之策略、措施及行動；調適障礙指阻礙調適行動規劃、實施或降低其成效之因素，可能涉及物理、生態、技術、經濟、社會、文化、制度、治理或資訊等面向。第11條第3款要求彙整執行過程之調適障礙並提出解決方案。",
 "How are adaptation option and adaptation barrier defined?",
 ["An adaptation option is a strategy, measure or action usable to reduce the adaptation gap; a barrier is a factor obstructing adaptation planning or implementation or reducing its effectiveness, spanning physical, ecological, technical, economic, social, cultural, institutional, governance or information aspects","An adaptation option is the consistent climate scenario set to help governments perform risk assessment; a barrier is the difference between current and future climate risk assessment results for exposed objects, spanning physical, ecological, technical, economic, social, cultural and governance aspects","An adaptation option is the geographic area with high exposure, high vulnerability and susceptibility to climate hazards; a barrier is the severity or trend of natural or human-induced climate hazard events that may aggravate the adverse effects on exposed objects","An adaptation option is a budget item compiled by government under the current climate change science report; a barrier is the degree of susceptibility of exposed objects, including sensitivity, damage propensity and lack of response and adaptive capacity"],
 "Article 2(9)-(10): options reduce the adaptation gap; barriers obstruct planning, implementation or effectiveness."),

("ENV-213","第3條",1,"氣候風險評估-科學報告",
 "各級政府規劃、執行調適方案時，應依本準則使用何種資料進行氣候變遷風險評估？",
 ["應使用氣候變遷科學報告進行氣候變遷風險評估","應使用國家溫室氣體排放清冊進行風險評估作業","應使用環境影響評估審查結論進行風險評估作業","應使用災害潛勢地圖及保險理賠統計進行評估"],"a",
 "第3條：各級政府規劃、執行調適方案時，應依本準則規定使用氣候變遷科學報告進行氣候變遷風險評估；第7條第1款及第11條第4款並要求使用當期科學報告並參採最新國內外研究。",
 "What material must governments use when performing climate change risk assessment?",
 ["They must use the climate change science report for the risk assessment","They must use the national greenhouse gas emission inventory for the assessment","They must use environmental impact assessment review conclusions for the assessment","They must use disaster potential maps and insurance claim statistics for the assessment"],
 "Article 3: the climate change science report must be used."),

("ENV-213","第4條",1,"氣候風險評估-辦理事項",
 "各級政府辦理氣候變遷風險評估，應包括哪些事項？",
 ["應包括界定範疇、檢視資源及氣候衝擊現況、評估未來氣候變遷風險三項","應包括盤點溫室氣體排放源、訂定減量目標、查核減量執行成效三項","應包括界定範疇、辦理環境影響評估、公告高風險地區禁建範圍三項","應包括編列調適預算、辦理民眾意見調查、公布年度調適白皮書三項"],"a",
 "第4條：各級政府辦理氣候變遷風險評估，應包括界定範疇、檢視資源及氣候衝擊現況、評估未來氣候變遷風險三事項，其具體作法分別規定於第5條至第7條。",
 "What must a government's climate change risk assessment cover?",
 ["Defining the scope, reviewing resources and current climate impacts, and assessing future climate risk","Inventorying greenhouse gas sources, setting reduction targets, and auditing reduction performance","Defining the scope, conducting environmental impact assessment, and announcing building bans in high risk areas","Budgeting for adaptation, surveying public opinion, and publishing an annual adaptation white paper"],
 "Article 4: scope definition, review of resources and current impacts, and future risk assessment."),

("ENV-213","第5條",2,"氣候風險評估-界定範疇",
 "各級政府執行界定範疇時，應辦理哪些事項？",
 ["確認易受氣候變遷影響對象、對應業務範疇及權責機關；評估其氣候危害類型與可能受影響之時間、空間尺度及範圍；邀集有關機關、學者、專家、民間團體共同界定評估範疇","確認轄區內溫室氣體排放大戶名單及其排放量；評估各該事業之減量潛力與成本；邀集有關機關、學者、專家、民間團體共同核定各事業之排放額度上限","確認易受氣候變遷影響對象、對應業務範疇及權責機關；評估其保險投保比率與資產價值；由權責機關首長逕行核定評估範疇並函報中央主管機關備查後公告","確認高風險地區之地理界線及土地使用現況；評估其開發強度與人口密度變化；邀集有關機關、學者、專家、民間團體共同檢討土地使用分區管制計畫"],"a",
 "第5條：界定範疇應辦理確認易受氣候變遷影響對象、對應之業務範疇及權責機關；評估該對象之氣候危害類型、可能受影響之時間、空間尺度及範圍；並邀集有關機關、學者、專家、民間團體共同界定評估範疇。",
 "What must be done when defining the assessment scope?",
 ["Identify climate-sensitive objects, their business scope and responsible agencies; assess hazard types and the time and spatial scale affected; convene agencies, scholars, experts and civil groups to define the scope","Identify major greenhouse gas emitters and their emissions; assess their reduction potential and cost; convene agencies, scholars, experts and civil groups to set emission caps for each","Identify climate-sensitive objects, their business scope and responsible agencies; assess their insurance coverage and asset values; have the agency head approve the scope and file it with the central authority for record","Identify the boundaries and land use of high risk areas; assess development intensity and population density change; convene agencies, scholars, experts and civil groups to review zoning controls"],
 "Article 5: identify objects and agencies, assess hazard types and scales, and convene stakeholders."),

("ENV-213","第6條",2,"氣候風險評估-資源盤點",
 "各級政府執行檢視資源及氣候衝擊現況時，就資源盤點應辦理何事項？",
 ["盤點權責機關及易受氣候變遷影響對象之可掌握資源，包括知識、技術、人力、財務等能力建構情形，及可投入風險評估及調適計畫等調適管理機制之資源","盤點權責機關轄下所有公有建築物及公共設施之耐震能力、使用年限與維護費用，並據以編列未來十年之公共工程改建與補強預算及施工期程","盤點易受氣候變遷影響對象之營業額、就業人數及產值占比，並依產業別排序，作為調適資源分配與租稅減免優惠核給之唯一衡量依據","盤點權責機關已完成之溫室氣體減量措施及其減量績效，並與國際同級城市進行標竿比較，作為調適選項優先順序與經費核撥之依據"],"a",
 "第6條第1款：應盤點權責機關及易受氣候變遷影響對象之可掌握資源，包括權責機關之知識、技術、人力、財務等能力建構情形，及可投入有關氣候變遷風險評估及調適計畫等調適管理機制之資源。",
 "What does the resource inventory step require?",
 ["Inventory the resources of responsible agencies and climate-sensitive objects, including knowledge, technology, manpower and financial capacity building, and resources for adaptation management","Inventory the seismic capacity, service life and maintenance cost of all public buildings and facilities, and budget public works reconstruction and reinforcement for the coming decade","Inventory the turnover, employment and output share of climate-sensitive objects and rank them by industry as the sole basis for allocating adaptation resources and tax relief","Inventory the greenhouse gas reduction measures already completed and benchmark them against peer cities as the basis for prioritizing adaptation options and funding"],
 "Article 6(1): inventory capacity building and resources for adaptation management."),

("ENV-213","第6條",2,"氣候風險評估-衝擊現況",
 "檢視氣候衝擊現況之評估項目與方法規劃，依本準則應如何辦理？",
 ["評估項目包括危害度、暴露度及脆弱度，評估結果應含易受影響對象之影響程度或空間分布；並規劃權責機關及影響對象屬性之質化、量化或綜合之衝擊評估方法","評估項目包括排放量、減量率及碳費負擔，評估結果應含各排放源之減量潛力排序；並規劃由中央主管機關統一指定之量化衝擊評估方法供各級政府適用","評估項目包括危害度、暴露度及調適差距，評估結果應含高風險地區之禁限建範圍；並規劃委由民間顧問公司採用國際通用模式辦理質化衝擊評估作業","評估項目包括降雨量、氣溫及海平面高度，評估結果應含未來百年之推估數值區間；並規劃以問卷調查方式取代質化與量化之衝擊評估方法並公開結果"],"a",
 "第6條第2、3款：評估氣候衝擊現況之評估項目包括危害度、暴露度及脆弱度，評估結果應含易受氣候變遷影響對象之影響程度或其空間分布情形；並應規劃權責機關及易受影響對象屬性之質化、量化或綜合之衝擊評估方法。",
 "What items and methods apply when reviewing current climate impacts?",
 ["Assessment items are hazard, exposure and vulnerability, with results showing the degree of effect or spatial distribution; qualitative, quantitative or combined impact methods are planned by attribute","Assessment items are emissions, reduction rates and carbon fee burden, with results ranking reduction potential; a uniform quantitative method designated by the central authority applies","Assessment items are hazard, exposure and the adaptation gap, with results showing building bans in high risk areas; qualitative assessment is outsourced to consultants using international models","Assessment items are rainfall, temperature and sea level, with results giving projected ranges for the coming century; questionnaires replace qualitative and quantitative impact methods"],
 "Article 6(2)-(3): hazard, exposure and vulnerability, plus qualitative or quantitative methods."),

("ENV-213","第7條",3,"氣候風險評估-未來風險",
 "各級政府執行評估未來氣候變遷風險時，應如何使用科學資訊並進行評估？",
 ["應使用當期氣候變遷科學報告並參採最新國內外科學研究機構及政府報告，以調適應用情境評估未來衝擊或風險；並依前條評估結果及方法辨識調適差距或指認高風險地區","應使用發布逾五年之氣候變遷科學報告並參採產業公會意見，以歷史災害紀錄評估未來衝擊或風險；並依環境影響評估審查結論辨識調適差距或指認高風險地區","應使用當期氣候變遷科學報告並參採最新國內外科學研究機構及政府報告，以歷史平均氣候值評估過去衝擊；並依中央主管機關公告之名單指認高風險地區範圍","應使用中央主管機關指定之單一氣候模式並排除國外研究成果，以調適應用情境評估未來衝擊；並由權責機關逕行公告調適差距與高風險地區之範圍"],"a",
 "第7條第1、2款：應使用當期氣候變遷科學報告，並參採最新國內外科學研究機構及政府單位之氣候變遷科學資訊與知識相關報告及建議，以調適應用情境評估未來衝擊或風險；並依第6條第2款評估結果及第3款評估方法進行未來風險評估，辨識調適差距或指認高風險地區。",
 "How must future climate risk be assessed?",
 ["Use the current climate science report and the latest domestic and foreign research and government reports, assess future impacts under adaptation scenarios, then identify the adaptation gap or high risk areas from the prior results and methods","Use a climate science report over five years old and industry association views, assess future impacts from historical disaster records, then identify the gap or high risk areas from EIA review conclusions","Use the current climate science report and the latest domestic and foreign research and government reports, assess past impacts using historical climate averages, then designate high risk areas from a list announced by the central authority","Use a single climate model designated by the central authority and exclude foreign research, assess future impacts under adaptation scenarios, then have the responsible agency announce the gap and high risk areas"],
 "Article 7(1)-(2): current science report, adaptation scenarios, identification of gaps and high risk areas."),

("ENV-213","第7條",2,"氣候風險評估-合理性檢視",
 "調適差距之辨識或高風險地區之指認，其合理性應如何檢視？",
 ["應邀集有關機關、學者、專家、民間團體，共同檢視調適差距或指認高風險地區之合理性","應報請中央主管機關委託之學術機構，逐案覆核調適差距及高風險地區指認之合理性","應由權責機關首長召開內部會議自行核定，並於核定後函送中央主管機關備查即可","應委由地方民意機關審議通過後公告，並得排除有關機關與民間團體之意見參與"],"a",
 "第7條第3款：應邀集有關機關、學者、專家、民間團體，共同檢視調適差距或指認高風險地區之合理性；此與第5條第3款共同界定評估範疇之外部參與要求相呼應。",
 "How is the reasonableness of the identified gap or high risk areas reviewed?",
 ["Relevant agencies, scholars, experts and civil groups are convened to jointly review the reasonableness","An academic institution commissioned by the central authority reviews each identification case by case","The agency head approves it at an internal meeting and merely files it with the central authority","The local council must approve and announce it, excluding input from agencies and civil groups"],
 "Article 7(3): joint review by agencies, scholars, experts and civil groups."),

("ENV-213","第8條",1,"氣候風險評估-調適推動",
 "各級政府進行氣候變遷風險評估後，研擬、推動調適方案及策略時應辦理哪些事項？",
 ["應辦理調適選項規劃及綜整決策、推動或執行調適選項、檢討或修正調適選項三項","應辦理溫室氣體盤查登錄、排放額度核配、碳費徵收與稽核等三項配套管制作業","應辦理高風險地區土地徵收、建築物拆除補償、居民安置與遷村作業等三項工作","應辦理氣候變遷科學報告編撰、氣象觀測站設置及災害預警系統維運等三項工作"],"a",
 "第8條：各級政府進行風險評估後，於研擬、推動調適方案及策略時，應辦理調適選項規劃及綜整決策、推動或執行調適選項、檢討或修正調適選項；其原則分別規定於第9條至第11條。",
 "What must governments do when formulating and promoting adaptation programs after the assessment?",
 ["Plan and integrate decisions on adaptation options, promote or implement the options, and review or revise the options","Conduct greenhouse gas inventory registration, allocate emission allowances, and levy and audit carbon fees","Expropriate land in high risk areas, compensate for building demolition, and resettle or relocate residents","Compile the climate change science report, install weather stations, and operate disaster warning systems"],
 "Article 8: planning and integration, implementation, and review or revision of adaptation options."),

("ENV-213","第9條",2,"氣候風險評估-調適選項規劃",
 "各級政府執行調適選項規劃及綜整決策之原則為何？",
 ["以降低調適差距為目標擬訂調適選項及推動期程；評估選項之有效性、可行性及可能負面影響；評估優先執行之調適選項；並得評估附加效益及參考各界意見","以降低溫室氣體排放量為目標擬訂減量選項及期程；評估選項之減量成本效益與技術成熟度；評估優先執行之減量選項；並應報請中央主管機關逐案核定","以維持地方財政平衡為目標擬訂調適選項及期程；評估選項之預算需求與人力配置；評估優先執行之調適選項；並得排除民間團體與專家學者之參與","以達成國際承諾指標為目標擬訂調適選項及期程；評估選項之國際評比效果與宣傳價值；評估優先執行之選項；並應由行政院統一核定推動順序"],"a",
 "第9條第1項：調適選項規劃及綜整決策之原則為以降低調適差距為目標擬訂調適選項及推動期程、評估調適選項之有效性、可行性及可能之負面影響、評估優先執行之調適選項。第2、3項另定得評估附加效益及參考有關機關、學者、專家及民間團體意見。",
 "What principles govern the planning and integrated decision-making on adaptation options?",
 ["Set options and schedules aimed at reducing the adaptation gap; assess effectiveness, feasibility and possible adverse effects; assess priority options; co-benefits and stakeholder views may also be considered","Set reduction options and schedules aimed at cutting greenhouse gases; assess abatement cost-effectiveness and technical maturity; assess priority options; each must be approved by the central authority","Set options and schedules aimed at keeping local finances balanced; assess budget needs and staffing; assess priority options; participation by civil groups and experts may be excluded","Set options and schedules aimed at meeting international pledges; assess international ranking effects and publicity value; assess priority options; the Executive Yuan sets the order"],
 "Article 9: reduce the adaptation gap, assess effectiveness and feasibility, and prioritize options."),

("ENV-213","第10條",2,"氣候風險評估-推動執行",
 "各級政府推動或執行調適選項之原則為何？",
 ["調適選項推動期程之符合程度；建立量化評估指標作為執行成效依據；無法建立指標者得透過訪談相關團體、諮詢專家等方式協助檢視執行成效","調適選項推動經費之執行率高低；建立質化描述作為執行成效之唯一依據；無法完成者得逕行展延期程並免報請權責機關核定或對外說明","調適選項與國際標準之接軌程度；建立碳排放減量指標作為執行成效依據；無法建立指標者應停止執行該調適選項並重新辦理風險評估","調適選項所涉土地取得之完成比率；建立民意支持度調查作為執行成效依據；無法建立指標者應由中央主管機關逕行代為執行該調適選項"],"a",
 "第10條：推動或執行調適選項之原則包括調適選項推動期程之符合程度、建立量化評估指標作為評估調適選項或計畫執行成效之依據；無法建立指標者，得透過訪談相關團體、諮詢專家等方式協助檢視調適執行成效。",
 "What principles govern promoting or implementing adaptation options?",
 ["Conformity with the option's schedule; quantitative indicators as the basis for evaluating results; where indicators cannot be set, interviews with groups and expert consultation help review performance","The budget execution rate of the option; qualitative description as the sole basis for performance; where it cannot be completed, the schedule may be extended without approval or explanation","Alignment of the option with international standards; carbon reduction indicators as the basis for performance; where indicators cannot be set, the option stops and reassessment is required","The completion rate of land acquisition for the option; public support surveys as the basis for performance; where indicators cannot be set, the central authority implements the option instead"],
 "Article 10: schedule conformity, quantitative indicators, and interviews or expert consultation as a fallback."),

("ENV-213","第11條",3,"氣候風險評估-檢討修正",
 "各級政府檢討或修正調適選項之原則包括哪些？",
 ["降低調適差距之執行情形；評估跨領域調適策略、政策或計畫之潛在正負面影響；彙整調適障礙並提出未來解決方案；使用當期科學報告滾動進行風險評估作為修正依據","降低溫室氣體排放量之執行情形；評估各排放源減量措施之成本效益；彙整減量障礙並提出補助方案；使用歷史排放清冊滾動檢討排放額度作為修正之依據","降低調適經費支出之執行情形；評估跨部門預算排擠之潛在影響；彙整財務缺口並提出增稅方案；使用前期決算數據滾動編列預算作為調適選項修正之依據","降低災害發生頻率之執行情形；評估工程設施耐災標準之提升幅度；彙整施工障礙並提出加速方案；使用工程驗收報告滾動檢討設計標準作為修正之依據"],"a",
 "第11條：檢討或修正調適選項之原則包括降低調適差距之執行情形、評估跨領域調適策略政策或計畫之潛在正負面影響、彙整執行過程之調適障礙並提出未來解決方案，以及使用當期氣候變遷科學報告並參採最新國內外研究，滾動進行氣候變遷風險評估作為修正依據。",
 "What principles govern reviewing or revising adaptation options?",
 ["Progress in closing the adaptation gap; potential positive and negative effects of cross-sector strategies, policies or plans; compiled barriers with future solutions; rolling reassessment using the current science report","Progress in cutting greenhouse gases; cost-effectiveness of reduction measures at each source; compiled reduction barriers with subsidy schemes; rolling review of allowances using historical inventories","Progress in cutting adaptation spending; potential crowding-out effects across departments; compiled funding gaps with tax increase proposals; rolling budgeting using previous final accounts data","Progress in cutting disaster frequency; the extent to which structural resilience standards rise; compiled construction barriers with acceleration plans; rolling review of design standards using acceptance reports"],
 "Article 11: gap-closing progress, cross-sector effects, barriers and solutions, and rolling reassessment."),

("ENV-213","第12條",1,"氣候風險評估-施行",
 "氣候變遷風險評估作業準則之施行日期為何？",
 ["本準則自發布日施行","本準則自發布後三個月施行","本準則自發布後一年施行","本準則自一百十五年一月一日施行"],"a",
 "第12條：本準則自發布日施行，無另定緩衝期間。",
 "When do these Regulations take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect one year after promulgation","They take effect on January 1 of Year 115 (2026)"],
 "Article 12: effective upon promulgation."),

# ===================== ENV-214 環境用藥原體轉讓申請作業準則 =====================
("ENV-214","第1條",1,"原體轉讓-法源",
 "環境用藥原體轉讓申請作業準則係依據哪一條文授權訂定？",
 ["依環境用藥管理法第十五條第二項規定訂定之","依環境用藥管理法第十六條第一項規定訂定之","依環境用藥管理法第二十四條第三項規定訂定之","依環境用藥管理法第十一條第二項規定訂定之"],"a",
 "第1條：本準則依環境用藥管理法第十五條第二項規定訂定，規範環境用藥原體轉讓之受讓人資格、申請方式與期限。",
 "Under which provision are the Regulations on applications for transferring environmental agent active ingredients adopted?",
 ["Adopted under Article 15, Paragraph 2 of the Environmental Agents Control Act","Adopted under Article 16, Paragraph 1 of the Environmental Agents Control Act","Adopted under Article 24, Paragraph 3 of the Environmental Agents Control Act","Adopted under Article 11, Paragraph 2 of the Environmental Agents Control Act"],
 "Article 1: adopted under Article 15(2) of the Environmental Agents Control Act."),

("ENV-214","第2條",2,"原體轉讓-受讓人資格",
 "環境用藥原體轉讓之受讓人，以何者為限？",
 ["以環境用藥販賣業或領有與該原體相同有效成分之環境用藥製造許可證之環境用藥製造業者為限","以環境用藥病媒防治業或領有任一環境用藥販賣許可執照之環境用藥販賣業者為限","以領有工廠登記證之化學品製造業或經公會推薦之環境用藥輸入業者為限","以環境用藥製造業或領有與該原體相同劑型之環境用藥輸入許可證之輸入業者為限"],"a",
 "第2條：原體轉讓之受讓人以環境用藥販賣業，或領有與該原體相同有效成分之環境用藥製造許可證之環境用藥製造業者為限，以確保受讓人具備合法使用該原體之資格。",
 "Who may receive a transferred environmental agent active ingredient?",
 ["Only an environmental agent vendor, or a manufacturer holding a manufacturing licence for the same active ingredient","Only a vector control business, or a vendor holding any environmental agent sales licence","Only a chemical manufacturer with a factory registration, or an importer recommended by the trade association","Only a manufacturer, or an importer holding an import licence for an agent of the same dosage form"],
 "Article 2: an environmental agent vendor or a manufacturer licensed for the same active ingredient."),

("ENV-214","第3條",2,"原體轉讓-申請方式",
 "環境用藥原體之轉讓，得以哪兩種方式向中央主管機關申請？",
 ["許可申請與個案申請兩種方式，均向中央主管機關提出","備查申請與核備申請兩種方式，均向地方主管機關提出","許可申請與展延申請兩種方式，均向目的事業主管機關提出","登記申請與報備申請兩種方式，向中央或地方主管機關提出"],"a",
 "第3條：原體之轉讓以許可申請及個案申請兩種方式向中央主管機關申請；許可申請係併同環境用藥許可證申請或展延辦理，個案申請則於每次轉讓或受讓原體前申請核准。",
 "By which two routes may a transfer be applied for to the central competent authority?",
 ["A licence-based application and a case-by-case application, both filed with the central authority","A recordation application and an approval-for-record application, both filed with the local authority","A licence-based application and a renewal application, both filed with the industry authority","A registration application and a notification application, filed with the central or local authority"],
 "Article 3: licence-based application and case-by-case application, both to the central authority."),

("ENV-214","第3條",3,"原體轉讓-許可申請",
 "未領有原體製造或輸入許可證之環境用藥製造業者，應如何辦理原體轉讓之許可申請？個案申請之時點為何？",
 ["於申請環境用藥許可證或展延時，檢具經原體許可證持有者加蓋公司及負責人印章之該許可證影本併同辦理；個案申請則於每次轉讓或受讓原體前申請核准","於取得環境用藥許可證後三個月內，檢具經原體許可證持有者加蓋公司印章之該許可證正本併案報備；個案申請則於每次轉讓或受讓原體後三個月內補行申請","於每年度開始前，檢具經地方主管機關核章之原體許可證影本併同年度製造計畫辦理；個案申請則由原體持有者於每季結束後彙總申報轉讓數量即可","於申請工廠登記或變更登記時，檢具經目的事業主管機關驗證之許可證影本併同辦理；個案申請則於原體實際交付並完成入庫後始得補申請核准"],"a",
 "第3條第1款：未領有原體製造或輸入許可證之環境用藥製造業者，於申請環境用藥許可證或展延時，檢具經原體製造或輸入許可證持有者加蓋公司及負責人印章之該許可證影本，併同辦理。第2款：個案申請係製造業或販賣業者於每次轉讓或受讓原體前申請核准。",
 "How does a manufacturer without its own active ingredient licence apply, and when is a case-by-case application made?",
 ["When applying for or renewing an environmental agent licence, submit a copy of the holder's licence stamped with company and responsible person seals; case-by-case applications are made before each transfer","Within three months of obtaining the licence, submit the original holder's licence stamped with the company seal for record; case-by-case applications are filed within three months after each transfer","Before each year begins, submit a copy of the licence certified by the local authority with the annual production plan; the holder reports transfer volumes quarterly in aggregate instead","When applying for or changing factory registration, submit a copy verified by the industry authority; case-by-case applications may only follow actual delivery and warehousing of the ingredient"],
 "Article 3(1)-(2): licence copy with seals filed with the agent licence application; case applications precede each transfer."),

("ENV-214","第4條",2,"原體轉讓-應檢資料",
 "個案申請原體轉讓者，應檢具哪些資料？",
 ["受讓人之環境用藥製造許可證字號、品名、有效成分及含量、原體需求量；原體持有者之許可證字號、品名、有效成分及含量、原體轉讓數量及原體製造日期","受讓人之工廠登記證號、資本額、員工人數、年產能；原體持有者之營利事業登記證號、負責人姓名、聯絡地址、倉儲位置及原體採購單價","受讓人之環境用藥製造許可證字號、品名、原體需求量、預定售價；原體持有者之進口報單號碼、關稅完稅證明、運送車輛車號及交付地點與時間","受讓人之病媒防治業許可執照字號、專業技術人員名冊；原體持有者之許可證字號、品名、有效成分及含量、原體轉讓數量及使用地點"],"a",
 "第4條：個案申請應檢具環境用藥製造業受讓人之環境用藥製造許可證字號、品名、有效成分及含量、原體需求量，以及原體持有者所持有原體之許可證字號、品名、有效成分及含量、原體轉讓數量及原體製造日期。",
 "What data must a case-by-case transfer application contain?",
 ["The transferee's manufacturing licence number, product name, active ingredient and content, and required quantity; the holder's licence number, product name, active ingredient and content, transfer quantity and manufacturing date","The transferee's factory registration number, capital, headcount and annual capacity; the holder's business registration number, responsible person, address, warehouse location and the unit purchase price of the ingredient","The transferee's manufacturing licence number, product name, required quantity and planned price; the holder's import declaration number, duty certificate, delivery vehicle plate, place and time","The transferee's vector control licence number and roster of technicians; the holder's licence number, product name, active ingredient and content, transfer quantity and place of use"],
 "Article 4: licence numbers, product names, active ingredients, quantities and manufacturing date."),

("ENV-214","第5條",2,"原體轉讓-完成期限",
 "依第四條規定申請核准轉讓之原體，應於何時完成轉讓？",
 ["應於核准日起三個月內完成轉讓","應於核准日起六個月內完成轉讓","應於核准日起一年內完成該項轉讓","應於申請日起三十日內完成該轉讓"],"a",
 "第5條：依第4條規定申請核准轉讓之原體，應於核准日起三個月內完成轉讓，逾期即不得再依該次核准辦理轉讓。",
 "By when must an approved transfer be completed?",
 ["Within three months from the date of approval","Within six months from the date of approval","Within one year from the date of the approval","Within thirty days from the date of application"],
 "Article 5: within three months of approval."),

("ENV-214","第6條",2,"原體轉讓-補正",
 "未依第四條規定檢具申請資料者，應如何處理？補正期限為何？",
 ["應通知限期補正，補正期限以一個月為限，屆期未補正者逕予退件","應通知限期補正，補正期限以三個月為限，屆期未補正者逕予退件","應逕予退件不另通知補正，申請人得於一個月內重新提出申請","應通知限期補正，補正期限以六個月為限，屆期未補正者處以罰鍰"],"a",
 "第6條：未依第4條規定檢具申請資料者，應通知限期補正；補正期限以一個月為限，屆期未補正者逕予退件。此與環境用藥專供輸出申請作業準則第4條第2項之補正規定相同。",
 "How are incomplete case-by-case applications handled, and what is the correction period?",
 ["A correction deadline is given, capped at one month, and the case is returned if missed","A correction deadline is given, capped at three months, and the case is returned if missed","The case is returned directly without notice, and may be refiled within one month","A correction deadline is given, capped at six months, and a fine follows if missed"],
 "Article 6: one-month correction period, otherwise return of the application."),

("ENV-214","第7條",1,"原體轉讓-施行",
 "環境用藥原體轉讓申請作業準則之施行日期為何？",
 ["本準則自發布日施行","本準則自發布後三個月施行","本準則自發布後一年施行","本準則自九十六年一月一日施行"],"a",
 "第7條：本準則自發布日施行，無另定緩衝期間。",
 "When do these Regulations take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect one year after promulgation","They take effect on January 1 of Year 96 (2007)"],
 "Article 7: effective upon promulgation."),

# ===================== ENV-215 環境用藥專供輸出申請作業準則 =====================
("ENV-215","第1條",1,"專供輸出-法源",
 "環境用藥專供輸出申請作業準則係依據哪一條文授權訂定？",
 ["依環境用藥管理法第十六條第一項規定訂定之","依環境用藥管理法第十五條第二項規定訂定之","依環境用藥管理法第二十四條第一項規定訂定之","依環境用藥管理法第十三條第三項規定訂定之"],"a",
 "第1條：本準則依環境用藥管理法第十六條第一項規定訂定，規範製造、加工專供輸出環境用藥之申請資格與應檢文件。",
 "Under which provision are the Regulations on applications for environmental agents made solely for export adopted?",
 ["Adopted under Article 16, Paragraph 1 of the Environmental Agents Control Act","Adopted under Article 15, Paragraph 2 of the Environmental Agents Control Act","Adopted under Article 24, Paragraph 1 of the Environmental Agents Control Act","Adopted under Article 13, Paragraph 3 of the Environmental Agents Control Act"],
 "Article 1: adopted under Article 16(1) of the Environmental Agents Control Act."),

("ENV-215","第2條",2,"專供輸出-申請資格",
 "申請製造、加工專供輸出環境用藥者，以何者為限？",
 ["以持有與該專供輸出藥劑相同劑型之環境用藥製造許可證之環境用藥製造業者為限","以持有與該專供輸出藥劑相同有效成分之環境用藥輸入許可證之輸入業者為限","以領有環境用藥販賣業許可執照且登記營業項目含輸出業務之販賣業者為限","以持有任一環境用藥製造許可證且工廠登記證未逾三年之環境用藥製造業者為限"],"a",
 "第2條：申請製造、加工專供輸出環境用藥，以持有與該專供輸出藥劑相同劑型之環境用藥製造許可證之環境用藥製造業者為限。第4條並要求檢具製造許可證影本。",
 "Who may apply to manufacture or process environmental agents solely for export?",
 ["Only a manufacturer holding an environmental agent manufacturing licence for the same dosage form as the exported agent","Only an importer holding an environmental agent import licence for the same active ingredient as the exported agent","Only a vendor holding an environmental agent sales licence whose registered scope includes export business","Only a manufacturer holding any environmental agent manufacturing licence with a factory registration under three years old"],
 "Article 2: a manufacturer licensed for the same dosage form."),

("ENV-215","第3條",1,"專供輸出-成分限制",
 "申請製造、加工專供輸出之環境用藥，於成分上有何限制？",
 ["不得含有環境用藥管理法公告禁用之成分","不得含有環境用藥管理法公告列管之成分","不得含有輸入國政府尚未核准登記之成分","不得含有國內未取得許可證登記之任何成分"],"a",
 "第3條：申請製造、加工專供輸出之環境用藥，不得含有本法公告禁用之成分；即使產品專供輸出而不於國內販售，仍受禁用成分之限制。",
 "What ingredient restriction applies to agents made solely for export?",
 ["They may not contain ingredients banned by announcement under the Environmental Agents Control Act","They may not contain ingredients listed for control by announcement under the Environmental Agents Control Act","They may not contain ingredients not yet approved and registered by the importing country's government","They may not contain any ingredient without a domestically registered licence in this country"],
 "Article 3: no ingredients banned under the Act."),

("ENV-215","第4條",3,"專供輸出-應檢文件",
 "環境用藥製造業申請製造、加工專供輸出之環境用藥，應檢具哪些文件或資料？",
 ["環境用藥製造許可證影本、登載主要產品之工廠登記文件影本、國外買方訂購文件正本、專供輸出藥劑之外文品名各成分及含量劑型內容量及數量","環境用藥販賣業許可執照影本、營利事業登記證影本、國外買方訂購文件影本、專供輸出藥劑之中文品名各成分及含量劑型內容量及售價","環境用藥製造許可證正本、環保專責人員設置證明文件、國內經銷商合約書、專供輸出藥劑之外文品名各成分及含量與國內市場售價一覽表","環境用藥製造許可證影本、工廠登記文件影本、輸入國政府核發之准許輸入證明正本、專供輸出藥劑之運輸方式包裝材質及倉儲地點說明"],"a",
 "第4條第1項：應檢具環境用藥製造許可證影本、登載主要產品之工廠登記文件影本、國外買方訂購文件正本（含外國廠商名稱及地址、藥劑外文品名、有效成分、數量、劑型、內容量），以及專供輸出環境用藥之外文品名、各成分及含量、劑型、內容量、數量。",
 "What documents must accompany an application to make agents solely for export?",
 ["A copy of the manufacturing licence, a copy of the factory registration listing the main products, the original foreign buyer order, and the agent's foreign name, ingredients, contents, dosage form, volume and quantity","A copy of the sales licence, a copy of the business registration, a copy of the foreign buyer order, and the agent's Chinese name, ingredients, contents, dosage form, volume and price","The original manufacturing licence, proof of appointing environmental staff, the domestic distributor contract, and the agent's foreign name, ingredients, contents and domestic price list","A copy of the manufacturing licence, a copy of the factory registration, the original import permit from the importing government, and a description of the transport method, packaging material and storage location"],
 "Article 4(1): manufacturing licence copy, factory registration copy, original buyer order, and product particulars."),

("ENV-215","第4條",2,"專供輸出-補正",
 "未依規定檢具專供輸出申請之文件或資料者，應如何處理？補正期限為何？",
 ["應通知限期補正，補正期限以一個月為限，屆期未補正者逕予退件","應通知限期補正，補正期限以三個月為限，屆期未補正者逕予退件","應逕予退件不另通知補正，申請人得於三十日內重新提出申請","應通知限期補正，補正期限以六個月為限，屆期未補正者廢止許可"],"a",
 "第4條第2項：未依前項規定檢具申請文件或資料者，應通知限期補正；補正期限以一個月為限，屆期未補正者逕予退件，與環境用藥原體轉讓申請作業準則第6條之規定一致。",
 "How are incomplete export applications handled, and what is the correction period?",
 ["A correction deadline is given, capped at one month, and the case is returned if missed","A correction deadline is given, capped at three months, and the case is returned if missed","The case is returned directly without notice, and may be refiled within thirty days","A correction deadline is given, capped at six months, and the licence is annulled if missed"],
 "Article 4(2): one-month correction period, otherwise return of the application."),

("ENV-215","第5條",2,"專供輸出-紀錄保存",
 "經核准製造、加工專供輸出環境用藥者，其紀錄義務為何？",
 ["應按月記錄製造、加工、輸出量，其記錄及紀錄保存準用環境用藥管理法第二十四條之規定","應按季記錄製造、加工、輸出量，其記錄及紀錄保存準用環境用藥管理法第十五條之規定","應按年記錄製造、加工、輸出量，其記錄及紀錄保存依國外買方訂購文件所載期限辦理","應按批記錄製造、加工、輸出量，其記錄及紀錄保存由中央主管機關逐案指定其年限"],"a",
 "第5條：經核准製造、加工專供輸出環境用藥者，應按月記錄製造、加工、輸出量；其記錄及紀錄保存準用本法第二十四條之規定。",
 "What record-keeping duty applies to approved export-only production?",
 ["Monthly records of manufacture, processing and export volumes, kept in accordance with Article 24 of the Act by analogy","Quarterly records of manufacture, processing and export volumes, kept in accordance with Article 15 of the Act by analogy","Annual records of manufacture, processing and export volumes, kept for the period stated in the foreign buyer's order","Batch-by-batch records of manufacture, processing and export volumes, with retention set case by case by the authority"],
 "Article 5: monthly records, retained under Article 24 of the Act by analogy."),

("ENV-215","第6條",1,"專供輸出-施行",
 "環境用藥專供輸出申請作業準則之施行日期為何？",
 ["本準則自發布日施行","本準則自發布後三個月施行","本準則自發布後一年施行","本準則自九十六年七月一日施行"],"a",
 "第6條：本準則自發布日施行，無另定緩衝期間。",
 "When do these Regulations take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect one year after promulgation","They take effect on July 1 of Year 96 (2007)"],
 "Article 6: effective upon promulgation."),
]
