# -*- coding: utf-8 -*-
# 第 13 批（B2）：廢棄物清理法施行細則（ENV-52）、有害事業廢棄物認定標準（ENV-53）、事業廢棄物清理計畫書審查管理辦法（ENV-55）補題
W = "ENV-52"
H = "ENV-53"
P = "ENV-55"
Q = [
(W,"第1條",1,"廢清細則-授權依據",
 "廢棄物清理法施行細則係依據母法何條規定訂定？",
 ["依廢棄物清理法第七十六條規定訂定之施行細則","依廢棄物清理法第三十一條第二項規定訂定之細則","依廢棄物清理法第六十三條規定授權訂定之細則","依行政程序法第一百五十條授權所訂定之法規命令"],"a",
 "第1條：本細則依廢棄物清理法第七十六條規定訂定之。本細則就中央、直轄市縣（市）主管機關及執行機關之權責分工（第2條至第4條）、自行清除處理之定義（第11條）、清理計畫書變更範圍（第12條）等作補充規定。",
 "Under which article of the parent act are these Enforcement Rules issued?",
 ["Article 76 of the Waste Disposal Act authorizes these Enforcement Rules","Article 31, Paragraph 2 of the Waste Disposal Act authorizes these Rules","Article 63 of the Waste Disposal Act provides the authorization for the Rules","Article 150 of the Administrative Procedure Act provides the authorization"],
 "Article 1."),

(W,"第2條",2,"廢清細則-中央權責",
 "下列何者屬廢棄物清理法所定中央主管機關之主管事項？",
 ["有害事業廢棄物輸入、輸出、過境及轉口之同意，以及廢棄物檢驗測定機構之許可及管理","應回收廢棄物回收處理業之登記及管理，以及一般廢棄物清除機具之統籌調度及調派","一般廢棄物清除處理費徵收之規劃、訂定及公告，以及清除地區之公告指定及調整","公民營廢棄物清除處理機構許可文件之核發，以及占用道路廢棄車輛之查報及移置"],"a",
 "第2條第6款、第10款：廢棄物檢驗測定機構之許可及管理、有害事業廢棄物輸入輸出過境及轉口之同意，均屬中央主管機關主管事項；另包括全國性清理政策方案計畫之策劃訂定督導、資源回收管理基金之管理及運作等。第3條所列則為直轄市或縣（市）主管機關之主管事項。",
 "Which item falls within the central competent authority responsibilities under the Waste Disposal Act?",
 ["Consent to import, export, transit and transhipment of hazardous industrial waste, and permitting of waste testing organizations","Registration and management of recycling and treatment enterprises, and pooling and dispatch of general waste collection machinery","Planning, setting and announcing the collection of general waste clearance and disposal fees, and designating clearance districts","Issuing permits to public and private waste clearance and disposal organizations, and reporting and removing abandoned vehicles"],
 "Article 2, Subparagraphs 6 and 10."),

(W,"第3條",2,"廢清細則-地方權責",
 "下列何者屬直轄市或縣（市）主管機關之主管事項？",
 ["應回收廢棄物回收處理業之登記及管理，與公民營廢棄物清除處理機構許可文件之核發","有害事業廢棄物輸入、輸出、過境及轉口之同意，與資源回收管理基金之管理及運作","全國性廢棄物清理法規之訂定及釋示，與廢棄物清理之國際合作及科技交流事項","公告指定清除地區及一般廢棄物回收清除處理用地之規劃取得等執行機關執行事項"],"a",
 "第3條第6款、第12款：直轄市或縣（市）主管機關主管公民營廢棄物清除處理機構許可文件之核發與督導查核管理、應回收廢棄物回收處理業之登記及管理；另含廢棄物輸入輸出過境轉口許可文件之核發（第11款）。第2條所列則屬中央主管機關，第4條所列屬執行機關。",
 "Which item falls within the responsibilities of a municipal or county competent authority?",
 ["Registration and management of recycling and treatment enterprises, and issuing permits to waste clearance organizations","Consent to import, export, transit and transhipment of hazardous industrial waste, and managing the recycling fund","Formulating and interpreting nationwide waste clearance laws, and international cooperation and technical exchange","Announcing clearance districts and planning and acquiring land for general waste recovery, clearance and disposal"],
 "Article 3, Subparagraphs 6, 11 and 12."),

(W,"第4條",3,"廢清細則-執行機關",
 "就占用道路廢棄車輛之處理，鄉（鎮、市）公所與直轄市政府環境保護局之執行事項有何差異？",
 ["鄉（鎮、市）公所執行查報、認定及張貼；直轄市環保局則執行查報、認定、張貼、移置及公告","鄉（鎮、市）公所執行查報、認定、張貼及移置；直轄市環保局僅負責最後之公告作業程序","鄉（鎮、市）公所僅負責車輛之拖吊移置作業；直轄市環保局則負責查報、認定及張貼公告","二者執行事項完全相同，均包括查報、認定、張貼、移置及公告等五項法定執行工作事項"],"a",
 "第4條第1款第9目：直轄市政府環境保護局執行占用道路廢棄車輛之查報、認定、張貼、移置及公告；第4款第8目：鄉（鎮、市）公所執行占用道路廢棄車輛之查報、認定及張貼，不含移置及公告。另鄉（鎮、市）公所受託事項限於清除，縣環保局則受託處理一般事業廢棄物。",
 "How do township offices and municipal EPBs differ in handling abandoned vehicles occupying roads?",
 ["Township offices report, identify and post notices; municipal EPBs also carry out removal and announcement","Township offices report, identify, post notices and remove; municipal EPBs only handle the final announcement","Township offices only tow and remove the vehicles; municipal EPBs report, identify and post the announcements","Their duties are identical, both covering reporting, identification, posting, removal and public announcement"],
 "Article 4, Subparagraphs 1(9) and 4(8)."),

(W,"第5條",2,"廢清細則-鄉鎮處理",
 "縣環境保護局完成一般廢棄物工作調整前，鄉（鎮、市）就一般廢棄物處理應如何辦理？",
 ["應自行設置處理設施，並將處理方法及地點報縣環境保護局核准後自行處理","應一律將一般廢棄物運至縣環境保護局所轄之焚化廠處理，不得自行設置設施","應委託合格之公民營廢棄物清除處理機構代為處理，並報中央主管機關備查","應由縣環境保護局統一設置處理設施並代為處理，鄉（鎮、市）僅負責清除"],"a",
 "第5條：縣環境保護局依本法第5條第5項規定完成一般廢棄物工作調整前，鄉（鎮、市）應自行設置一般廢棄物處理設施，並將處理方法及地點報縣環境保護局核准後，自行處理所轄之一般廢棄物；但經縣環境保護局指定處理場所者，鄉（鎮、市）公所應備置適當之清除車輛，清除至指定場所處理。",
 "Before the county EPB completes work adjustment, how must townships handle general waste?",
 ["Set up their own disposal facilities and report the method and site to the county EPB for approval","Transport all general waste to the incineration plant run by the county EPB, with no own facilities","Commission licensed public or private clearance and disposal organizations and file with the central authority","Have the county EPB set up facilities and dispose of the waste, with townships handling clearance only"],
 "Article 5."),

(W,"第6條",2,"廢清細則-工作調整計畫",
 "縣環境保護局辦理一般廢棄物工作調整之計畫，應於何時報請何機關備查？其內容為何？",
 ["應於中華民國九十二年七月十四日前報請中央主管機關備查；內容含調整時程、人員機具設施調整及財務計畫","應於中華民國九十五年一月一日前報請所屬縣政府核定備查；內容僅需載明調整時程與經費來源即可辦理","應於中華民國九十二年七月十四日前報請目的事業主管機關核定；內容含環境影響評估及用地取得計畫書件","應於工作調整完成後六個月內報請中央主管機關核准；內容含人員編制、預算編列及設施操作維護管理計畫"],"a",
 "第6條：縣環境保護局依本法第5條第5項規定辦理一般廢棄物工作調整，應於中華民國九十二年七月十四日前，檢具工作調整計畫報請中央主管機關備查；計畫內容包括調整之時程、人員機具設施之調整、財務計畫及其他事項。調整完成前之處理方式依第5條辦理。",
 "When and to whom must a county EPB file its general waste work adjustment plan, and what must it contain?",
 ["File with the central competent authority before 14 July 2003; it covers the schedule, staff, machinery and facility adjustment, and finances","File with the county government for approval before 1 January 2006; it need only state the adjustment schedule and funding sources","File with the industry competent authority for approval before 14 July 2003; it covers environmental impact assessment and land acquisition","File with the central competent authority within six months after completion; it covers staffing, budgeting and facility operation plans"],
 "Article 6."),

(W,"第7條",2,"廢清細則-申報期限",
 "執行機關就一般廢棄物之清除、處理及回收量，應於何時向何機關報送？",
 ["應於每月十五日前將前一個月之數量，報送各該上級主管機關彙總層報中央主管機關備查","應於每季結束後三十日內將該季之數量，逕行報送中央主管機關審核後公告於網站上","應於每月月底前將當月之預估數量，報送直轄市、縣（市）主管機關核定後據以執行","應於每年一月三十一日前將前一年度數量，報送目的事業主管機關彙整後函送備查"],"a",
 "第7條第1項：執行機關應公告一般廢棄物與依本法第5條第6項所定一般廢棄物回收項目之清除時間、作業及回收方式，並於每月十五日前將前一個月之一般廢棄物清除、處理及回收量，報送各該上級主管機關彙總層報中央主管機關備查。第2項：受託清除處理一般事業廢棄物時亦同。",
 "By when and to whom must an executing agency report general waste clearance, disposal and recovery volumes?",
 ["By the fifteenth of each month for the previous month, to the superior authority for consolidated filing with the central authority","Within thirty days after each quarter for that quarter, directly to the central competent authority for review and publication","By the end of each month for estimated volumes of that month, to the municipal or county authority for approval","By 31 January each year for the previous year, to the industry competent authority for consolidation and filing"],
 "Article 7."),

(W,"第8條",2,"廢清細則-資源回收",
 "執行機關收集之廢棄物經分類後之廢塑膠、廢鋁、廢鐵、廢玻璃、廢紙等物質，得如何處理？",
 ["得交付回收業、處理業或依中央主管機關指定之方式進行回收、再利用","應一律交由執行機關自設之資源回收場處理，不得交付民間業者處理","應報請中央主管機關逐案核准後，始得交付合格之處理業者進行處理","應優先交付當地公有焚化廠焚化，剩餘者始得交付回收業回收再利用"],"a",
 "第8條：執行機關依前條規定收集之廢棄物，經分類後之廢塑膠、廢鋁、廢鐵、廢玻璃、廢紙等物質，得交付回收業、處理業或依中央主管機關指定之方式進行回收、再利用。第7條並要求執行機關公告回收項目之清除時間、作業及回收方式並按月申報數量。",
 "How may an executing agency handle sorted waste plastics, aluminium, iron, glass and paper it has collected?",
 ["Hand them to recycling or treatment enterprises, or recycle and reuse them as the central authority directs","Send them all to a resource recovery yard run by the agency itself, never to private operators","Obtain case-by-case approval from the central competent authority before handing them to operators","Send them first to the local public incinerator, with only the remainder going to recyclers"],
 "Article 8."),

(W,"第9條",3,"廢清細則-證明文件",
 "本法第九條第一項所定廢棄物產生源及處理地點之證明文件，分別為何？",
 ["產生源為申報廢棄物情形所列印之遞送聯單等；處理地點為產生源與處理者簽訂之合約文件影本","產生源為事業之工廠登記證影本；處理地點為處理機構之處理許可證及操作紀錄之影本文件","產生源為主管機關核發之事業廢棄物清理計畫書；處理地點為當地主管機關出具之同意函件","產生源為運輸業者出具之載運證明；處理地點為土地所有權人出具之土地使用同意書影本"],"a",
 "第9條第1項：廢棄物產生源之證明文件為依本法第31條第1項第2款申報廢棄物情形所列印之遞送聯單、依事業廢棄物貯存清除處理方法及設施標準所填具有害事業廢棄物之遞送聯單，或其他主管機關所定或認定之格式文件。第2項：處理地點證明文件為產生源與處理者所簽訂之合約文件影本；處理者為執行機關者，得為其出具之同意處理文件影本。",
 "What documents prove the source and disposal site of waste under Article 9, Paragraph 1 of the Act?",
 ["The source is proven by printed manifest forms from waste reporting; the site by a copy of the contract with the disposer","The source is proven by a copy of the factory registration; the site by the disposal permit and operating records","The source is proven by the approved industrial waste disposal plan; the site by a consent letter from the local authority","The source is proven by a carriage certificate from the transporter; the site by a landowner consent letter copy"],
 "Article 9."),

(W,"第10條",2,"廢清細則-基金收入",
 "依本法第二十六條第三項成立之一般廢棄物清除處理基金，其收入來源為何？",
 ["向指定清除地區內家戶及其他產生源徵收之清除處理費收入，及代清除處理一般事業廢棄物等收入","中央主管機關循預算程序撥付之補助款，及向回收業者收取之資源回收管理基金分配款項收入","事業依法繳納之空氣污染防制費、水污染防治費及土壤及地下水污染整治費之一定比例撥入款","違反本法之罰鍰收入全數撥入，以及執行機關出售回收物質所得價款與利息孳息等各項收入"],"a",
 "第10條：一般廢棄物清除處理基金收入來源，為下列收入中屬本法第26條第1項、第2項規定之成本：一、向指定清除地區內家戶及其他產生源所徵收一般廢棄物清除、處理費用之收入；二、代清除、處理一般事業廢棄物及其他收入。",
 "What are the revenue sources of the general waste clearance and disposal fund?",
 ["Clearance and disposal fees collected from households and other sources in the designated district, and fees for handling industrial waste","Subsidies appropriated by the central competent authority through the budget process, and allocations from the recycling management fund","A fixed share of the air pollution, water pollution and soil and groundwater remediation fees paid by enterprises under law","All fine revenue from violations of the Act, plus proceeds from selling recovered materials and interest earned on them"],
 "Article 10."),

(W,"第13條",3,"廢清細則-產業用料需求",
 "申請公告本法第三十八條第一項但書所定產業用料需求者，應檢具下列何種文件？",
 ["產生源、主要成分及有害成分說明、國內使用現況、過去三年進口量統計及未來三年需求量評估等","申請人之公司登記證明、負責人身分證明、工廠配置圖及最近三年之財務報表與納稅證明文件","輸出國政府出具之同意輸出文件、國際運輸契約、保險單證及輸入後之污染防治設施操作紀錄","中央主管機關核發之輸入許可證影本、海關進口報單、商品檢驗合格證明及原產地證明文件"],"a",
 "第13條：本法第38條第1項但書所定之產業用料需求，得由用料需求之事業或公會，檢具產生源、主要成分及有害成分說明，國內使用現況（含相關事業、料源、用途及使用量），過去三年進口量之統計，未來三年需求量之評估，替代用料及其料源之評估，污染防治設施，及其他經指定之文件或資料，分送中央主管機關及中央目的事業主管機關會商後公告之。",
 "What documents must be submitted to have an industrial raw material need announced under the Act?",
 ["Descriptions of source and main and hazardous components, domestic use status, three-year import statistics and three-year demand forecasts","Company registration, identity documents of the responsible person, plant layout drawings, and three years of financial and tax records","Export consent documents from the exporting government, international carriage contracts, insurance policies and facility operating records","A copy of the import permit issued by the central authority, customs declarations, commodity inspection certificates and origin certificates"],
 "Article 13."),

(W,"第14條",2,"廢清細則-目的事業主管機關",
 "本法第三十九條所定中央目的事業主管機關及再利用用途目的事業主管機關應如何認定？認定爭議如何解決？",
 ["前者依廢棄物產生源所屬業別或屬性認定，後者依再利用機構所屬業別或屬性認定；爭議由中央主管機關報請行政院指定","二者均依廢棄物產生源所屬業別或屬性認定之；認定發生爭議時由中央主管機關逕行指定並函知相關目的事業主管機關","前者依再利用機構所屬業別認定，後者依產生源所屬業別認定；爭議時由雙方目的事業主管機關協商決定並報請備查","二者均由中央主管機關依廢棄物之種類與危害特性逐案認定；認定發生爭議時由申請人自行選定其一機關提出申請"],"a",
 "第14條第1項：本法第39條所定中央目的事業主管機關，應依事業廢棄物產生源所屬業別或屬性認定之；所定再利用用途目的事業主管機關，應依事業廢棄物再利用機構所屬業別或屬性認定之。第2項：目的事業主管機關之認定產生爭議時，由中央主管機關報請行政院指定之。",
 "How are the central industry authority and the reuse-purpose industry authority determined, and how are disputes resolved?",
 ["The former follows the industry of the waste source, the latter that of the reuse facility; disputes go to the Executive Yuan via the central authority","Both follow the industry or attributes of the waste source; where a dispute arises the central authority designates one and notifies the agencies","The former follows the reuse facility industry and the latter the source industry; disputes are settled by negotiation between the two agencies","Both are determined case by case by the central authority based on waste type and hazard; in a dispute the applicant chooses one agency"],
 "Article 14."),

(W,"第15條",2,"廢清細則-復工復業",
 "事業經處分機關依本法命其停工或停業者，應如何辦理始得復工、復業？",
 ["應於復工、復業前檢具完成改善證明文件、清理計畫書或指定文件向處分機關申請，經審查核准後始得為之","應於停工、停業處分屆滿之日起自動恢復營運，僅需將改善結果函報處分機關備查即完成法定程序","應向所在地目的事業主管機關申請核准，並由該機關會同處分機關現場勘查合格後即可逕行復工","應繳清全部罰鍰並提出改善承諾書向處分機關報備，於報備滿三十日未經駁回者視為已獲核准"],"a",
 "第15條：事業經執行機關或主管機關（處分機關）依本法規定命其停工或停業者，應於復工、復業前，檢具完成改善證明文件、事業廢棄物清理計畫書或經處分機關指定之文件向處分機關申請；經處分機關審查核准後，始得復工、復業。第16條並就涉及製程改變或處理設施新置變更者定有試車程序。",
 "How may an enterprise ordered to suspend operations resume work or business?",
 ["Before resuming, submit improvement certificates, the disposal plan or designated documents and obtain approval from the sanctioning authority","Resume automatically once the suspension period expires, merely filing the improvement results with the sanctioning authority afterwards","Apply to the local industry competent authority, which conducts a joint site inspection with the sanctioning authority before resumption","Pay all fines and file an improvement undertaking; if not rejected within thirty days of filing it is deemed approved"],
 "Article 15."),

(W,"第16條",3,"廢清細則-試車期限",
 "復工、復業之申請涉及製程改變或處理設施新置變更者，其試車期限及審查期限規定為何？",
 ["試車期間以三十日為限，必要時得申請延長，展延期限不得超過六十日；試車報告應於三十日內審查完成","試車期間以六十日為限，必要時得申請延長，展延期限不得超過三十日；試車報告應於六十日內審查完成","試車期間以九十日為限，且不得申請任何展延；試車報告應於申請後十五日內由處分機關審查完成核定","試車期間以三十日為限，得申請展延二次，每次三十日；試車報告應於四十五日內審查完成並副知備查"],"a",
 "第16條第1項：試車期間以三十日為限，但必要時得申請延長之，展延期限不得超過六十日。第2項：經核定試車之事業，應於試車期限屆滿前檢具試車報告及指定文件申請復工、復業。第3項：處分機關除審查要求補正資料之期間外，應於三十日內審查完成試車報告，併第15條規定審查。",
 "What are the trial run and review periods where resumption involves process or facility changes?",
 ["The trial run is limited to thirty days, extendable by no more than sixty days; the report is reviewed within thirty days","The trial run is limited to sixty days, extendable by no more than thirty days; the report is reviewed within sixty days","The trial run is limited to ninety days with no extension allowed; the report is reviewed within fifteen days of filing","The trial run is limited to thirty days with two extensions of thirty days each; the report is reviewed within forty-five days"],
 "Article 16."),

(W,"第17條",1,"廢清細則-許可文件",
 "本法第四十六條第四款所稱廢棄物清除、處理許可文件係指何者？",
 ["依公民營廢棄物清除處理機構許可管理辦法核發之清除許可證、處理許可證","依事業廢棄物貯存清除處理方法及設施標準核備之貯存設施設置同意文件","經目的事業主管機關核發之工廠登記證及公司登記證明等營業許可之文件","經直轄市、縣（市）主管機關審查核准之事業廢棄物清理計畫書核准函件"],"a",
 "第17條：本法第46條第4款所稱廢棄物清除、處理許可文件，指依公民營廢棄物清除處理機構許可管理辦法核發之清除許可證、處理許可證。本法第46條第4款係未依廢棄物清除處理許可文件內容貯存、清除、處理廢棄物之刑責規定。",
 "What are the waste clearance and disposal permit documents referred to in Article 46, Subparagraph 4 of the Act?",
 ["The clearance permit and disposal permit issued under the regulations governing public and private waste organizations","The consent document for establishing storage facilities filed under the industrial waste storage and disposal standards","The factory registration and company registration certificates issued by the industry competent authority","The approval letter for an industrial waste disposal plan reviewed by the municipal or county authority"],
 "Article 17."),

(W,"第18條",2,"廢清細則-處分書送達",
 "處分機關依本法所作成之處分書，涉及跨區違法者應如何處理？",
 ["除將處分書送達受處分人外，應將副本知會當地主管機關及違法行為者所在地主管機關","僅需將處分書送達受處分人即可，其他轄區主管機關得自行向處分機關調閱相關卷證","應先報請中央主管機關核定後再行送達，並由中央主管機關統一副知各相關主管機關","應將處分書公告於處分機關網站三十日，即視為對各相關轄區主管機關完成通知程序"],"a",
 "第18條：處分機關依本法所作成之處分書，其涉及跨區違法者，除將處分書送達受處分人外，應將處分書副知當地主管機關及違法行為者所在地主管機關。第19條並規定告發單、處分書、移送書等書表格式除另有規定外由中央主管機關定之。",
 "How must a sanction decision involving cross-jurisdiction violations be handled?",
 ["Besides serving it on the party, copy it to the local competent authority and the authority where the violator is located","Serving it on the party suffices; other authorities may request the case files from the sanctioning authority themselves","Submit it for central authority approval before service, and let the central authority copy all relevant authorities","Post it on the sanctioning authority website for thirty days, which is deemed notice to all relevant authorities"],
 "Article 18."),

(W,"第19條",1,"廢清細則-書表格式",
 "本法及本細則所定之告發單、處分書及移送書或其他書表格式，除另有規定外由何機關訂定？",
 ["由中央主管機關統一訂定其格式，以利各級機關一致適用","由各直轄市、縣（市）主管機關依其實際需要分別訂定","由執行機關依個案性質自行設計並報上級主管機關備查","由行政院訂定共通格式後函送各級主管機關遵照辦理"],"a",
 "第19條：本法及本細則所定之告發單、處分書及移送書或其他書表之格式，除另有規定者外，由中央主管機關定之。第18條並規定跨區違法之處分書應副知當地主管機關及違法行為者所在地主管機關。",
 "Who prescribes the formats of citation slips, sanction decisions and referral documents under the Act and Rules?",
 ["The central competent authority prescribes uniform formats for consistent use by all agencies","Each municipal or county competent authority prescribes its own formats as locally needed","Executing agencies design their own by case and file them with the superior authority","The Executive Yuan sets common formats and circulates them to all competent authorities"],
 "Article 19."),

(W,"第20條",1,"廢清細則-施行日期",
 "廢棄物清理法施行細則之施行日期如何規定？",
 ["本細則自發布日施行，並未另定特定之施行日期","本細則自發布後六個月施行，以利事業預作準備","本細則自發布後一年施行，並得溯及既往而適用","本細則自中華民國一百零八年一月一日起施行之"],"a",
 "第20條：本細則自發布日施行。本細則修正日期為民國108年11月6日，依本法第76條授權訂定，內容涵蓋各級主管機關與執行機關權責、自行清除處理定義、餘裕處理能量計算、清理計畫書變更範圍及復工復業試車程序等共二十條。",
 "How is the effective date of the Enforcement Rules prescribed?",
 ["The Rules take effect on the date of promulgation, with no separate date set","The Rules take effect six months after promulgation to allow preparation","The Rules take effect one year after promulgation and may apply retroactively","The Rules take effect from the first day of January in the year 2019"],
 "Article 20."),

(H,"第1條",1,"有害認定-授權依據",
 "有害事業廢棄物認定標準係依據廢棄物清理法何項規定訂定？",
 ["依廢棄物清理法第二條第三項規定訂定之認定標準","依廢棄物清理法第三十六條第二項規定訂定之標準","依廢棄物清理法第三十九條第二項規定授權訂定之","依廢棄物清理法施行細則第十七條規定授權訂定之"],"a",
 "第1條：本標準依廢棄物清理法第二條第三項規定訂定之。第2條規定有害事業廢棄物依序以列表之有害事業廢棄物、有害特性認定之有害事業廢棄物、其他經中央主管機關公告者三種方式判定。",
 "Under which provision of the Waste Disposal Act are the Hazardous Industrial Waste Criteria issued?",
 ["Article 2, Paragraph 3 of the Waste Disposal Act authorizes these Criteria","Article 36, Paragraph 2 of the Waste Disposal Act authorizes these Criteria","Article 39, Paragraph 2 of the Waste Disposal Act provides the authorization","Article 17 of the Enforcement Rules of the Act provides the authorization"],
 "Article 1."),

(H,"第3條",3,"有害認定-列表廢棄物",
 "列表之有害事業廢棄物包括哪三種種類？",
 ["製程有害事業廢棄物、混合五金廢料及生物醫療廢棄物三類，分別依附表一至附表三認定","毒性有害事業廢棄物、溶出毒性事業廢棄物及戴奧辛有害事業廢棄物三類，依附表四認定","腐蝕性事業廢棄物、易燃性事業廢棄物及反應性事業廢棄物三類，依其物理化學性質認定","多氯聯苯有害事業廢棄物、石綿及其製品廢棄物及混合五金廢料三類，依含量比例認定之"],"a",
 "第3條：列表之有害事業廢棄物種類為製程有害事業廢棄物（附表一所列製程產生之廢棄物）、混合五金廢料（依貯存清除處理及輸出入等清理階段危害特性判定，認定方式如附表二）、生物醫療廢棄物（醫療機構、生物安全等級第二級以上實驗室等產生附表三所列之廢棄物）。第4條所列者則為有害特性認定之有害事業廢棄物。",
 "Which three categories make up the listed hazardous industrial wastes?",
 ["Process hazardous waste, mixed metal scrap and biomedical waste, identified under Appendices One to Three respectively","Toxic hazardous waste, leaching toxic waste and dioxin hazardous waste, all identified under Appendix Four criteria","Corrosive waste, ignitable waste and reactive waste, identified according to their physical and chemical properties","PCB hazardous waste, asbestos and asbestos product waste and mixed metal scrap, identified by content proportions"],
 "Article 3."),

(H,"第5條",3,"有害認定-表列排除",
 "製程有害事業廢棄物申請表列排除改列為一般事業廢棄物者，應向何機關申請並檢具何種文件？",
 ["向所在地主管機關申請核准，檢具公司或商業登記證明、表列排除申請書、廢棄物採樣計畫書及檢測報告","向中央主管機關申請核准，僅需檢具廢棄物特性組成及成分分析之檢測報告與委託檢測機構之許可證影本","向目的事業主管機關申請備查，檢具工廠登記證、製程說明書、原物料清單及廢棄物產生量之統計資料","向所在地主管機關申請備查，檢具事業廢棄物清理計畫書、遞送聯單影本及再利用機構出具之同意文件"],"a",
 "第5條第1款：第3條第1款附表一所列之有害事業廢棄物，事業得檢具公司登記證明文件或商業登記證明文件、有害事業廢棄物表列排除申請書、廢棄物採樣計畫書、廢棄物特性組成及成分分析之檢測報告及其他經指定文件，向所在地主管機關申請表列排除核准後，得改列為一般事業廢棄物；表列排除判定程序與排除標準值由中央主管機關公告之。",
 "Where and with what documents does one apply to delist a process hazardous waste as general industrial waste?",
 ["To the local competent authority, with company or business registration, a delisting application, a sampling plan and test reports","To the central competent authority, with only the composition and constituent analysis reports and a copy of the testing body permit","To the industry competent authority for filing, with factory registration, process descriptions, raw material lists and volume statistics","To the local competent authority for filing, with the waste disposal plan, copies of manifests and a consent letter from a reuse facility"],
 "Article 5, Subparagraph 1."),

(H,"第5條",3,"有害認定-改列一般",
 "有害事業廢棄物經中間處理後或屬易燃性廢液者，在何種條件下得認定為一般事業廢棄物？",
 ["依中間處理方式處理而有害性質消失者；易燃性廢液不具製程、毒性、溶出毒性等性質且採焚化或熱處理者","經稀釋至有害成分濃度低於附表四標準之二分之一者；易燃性廢液貯存滿六個月未發生自燃現象者即可","經委託合格清除機構運至專用掩埋場掩埋者；易燃性廢液閃火點經檢測高於攝氏四十度者即得改列之","經事業自行檢測認定有害成分未檢出者；易燃性廢液以水稀釋後乙醇體積濃度低於百分之二十四者"],"a",
 "第5條第2款、第3款：第3條及第4條之有害事業廢棄物依事業廢棄物貯存清除處理方法及設施標準之中間處理方式處理，其有害性質消失者，得認定為一般事業廢棄物；第4條第6款第1目之廢液不具製程、毒性、溶出毒性、戴奧辛、多氯聯苯、腐蝕性、反應性等性質且採焚化或熱處理者亦同，但處理前之貯存、清除仍應符合有害事業廢棄物相關規定。",
 "When may a hazardous industrial waste after intermediate treatment, or an ignitable waste liquid, be treated as general waste?",
 ["When intermediate treatment removes the hazardous property; and when an ignitable liquid lacks the listed properties and is incinerated or heat treated","When diluted so hazardous concentrations fall below half the Appendix Four limits; and when an ignitable liquid stores six months without self-ignition","When sent by a licensed clearer to a dedicated landfill; and when an ignitable waste liquid tests with a flash point above forty degrees Celsius","When the enterprise itself tests and finds no hazardous constituents; and when dilution brings ethanol below twenty-four percent by volume"],
 "Article 5, Subparagraphs 2 and 3."),

(H,"第6條",2,"有害認定-過渡期限",
 "本標準修正後，既有清理計畫書或許可內容應辦理變更異動者及須增設之設施，其期限為何？",
 ["應於本標準發布施行後一年內完成變更或異動；須增設之相關設施亦應於發布後一年內完成設置","應於本標準發布施行後六個月內完成變更或異動；須增設之相關設施應於發布後二年內完成設置","應於本標準發布施行後二年內完成變更或異動；須增設之相關設施應於發布後三年內完成其設置","應於本標準發布施行後三個月內完成變更或異動；須增設之相關設施應於發布後六個月內設置完成"],"a",
 "第6條：本標準修正前已審查核准之事業廢棄物清理計畫書或依本法取得之清除、處理、清理或再利用相關許可，其審查核准或許可內容於本標準修正施行後應辦理變更或異動者，應於本標準發布施行後一年內完成變更或異動；因本標準修正而須增設之相關設施，於本標準發布後一年內應完成設置。",
 "What deadlines apply for amending approvals and installing new facilities after the Criteria are amended?",
 ["Amendments must be completed within one year of promulgation; required new facilities must also be installed within one year","Amendments must be completed within six months of promulgation; required new facilities must be installed within two years","Amendments must be completed within two years of promulgation; required new facilities must be installed within three years","Amendments must be completed within three months of promulgation; required new facilities must be installed within six months"],
 "Article 6."),

(H,"第7條",1,"有害認定-施行日期",
 "有害事業廢棄物認定標準之施行日期如何規定？",
 ["本標準自發布日施行，並未另定特定之施行日期","本標準自發布後一年施行，以利事業預作準備","本標準自發布後二年施行，並得溯及既往適用","本標準自中華民國一百零九年七月一日起施行"],"a",
 "第7條：本標準自發布日施行。本標準修正日期為民國109年2月21日，共七條，包括判定順序（第2條）、列表之有害事業廢棄物（第3條）、有害特性認定之八類廢棄物（第4條）、改列一般事業廢棄物之要件（第5條）及過渡期間規定（第6條）。",
 "How is the effective date of the Hazardous Industrial Waste Criteria prescribed?",
 ["The Criteria take effect on the date of promulgation, with no separate date set","The Criteria take effect one year after promulgation to allow preparation","The Criteria take effect two years after promulgation and apply retroactively","The Criteria take effect from the first day of July in the year 2020"],
 "Article 7."),

(P,"第1條",1,"清理計畫書-授權依據",
 "事業廢棄物清理計畫書審查管理辦法係依據廢棄物清理法何項規定訂定？",
 ["依廢棄物清理法第三十一條第二項及第三項規定訂定","依廢棄物清理法第二十八條第一項及第二項規定訂定","依廢棄物清理法第三十九條第二項及第三項規定訂定","依廢棄物清理法第四十一條第一項及第四項規定訂定"],"a",
 "第1條：本辦法依廢棄物清理法第三十一條第二項及第三項規定訂定之。本法第31條第1項規定指定公告事業應檢具事業廢棄物清理計畫書送審查核准後始得營運，並於變更時事先申請變更；第2條並界定本辦法適用對象為指定公告事業。",
 "Under which provisions of the Waste Disposal Act are these Regulations issued?",
 ["Article 31, Paragraphs 2 and 3 of the Waste Disposal Act","Article 28, Paragraphs 1 and 2 of the Waste Disposal Act","Article 39, Paragraphs 2 and 3 of the Waste Disposal Act","Article 41, Paragraphs 1 and 4 of the Waste Disposal Act"],
 "Article 1."),

(P,"第2條",2,"清理計畫書-適用對象",
 "本辦法之適用對象及所稱審核機關分別為何？",
 ["適用對象為依本法第三十一條第一項指定公告一定規模之事業；審核機關為直轄市、縣（市）主管機關或中央主管機關委託之機關","適用對象為所有產生事業廢棄物之事業及再利用機構；審核機關一律為中央主管機關，地方主管機關僅負責事後之稽查工作","適用對象為領有公民營廢棄物清除處理機構許可證者；審核機關為目的事業主管機關會同直轄市、縣（市）主管機關共同審查","適用對象為經環境影響評估審查通過之開發單位；審核機關為中央主管機關委託之財團法人環境檢驗測定機構代為受理審查"],"a",
 "第2條第1項、第2項：本辦法適用對象為依本法第31條第1項指定公告一定規模之事業（指定公告事業）；所稱審核機關指依本法規定審查核准事業廢棄物清理計畫書之直轄市、縣（市）主管機關或中央主管機關委託之機關。第12條並規定中央主管機關委託之機關受理審查時，應將審查結果副知事業所在地直轄市、縣（市）主管機關。",
 "Who do these Regulations apply to, and what is the reviewing authority?",
 ["They apply to enterprises of a designated scale announced under Article 31, Paragraph 1; the reviewing authority is the municipal or county authority or an agency commissioned by the central authority","They apply to all enterprises generating industrial waste and to reuse facilities; the reviewing authority is always the central authority, with local authorities only inspecting afterwards","They apply to holders of public or private waste clearance and disposal permits; review is conducted jointly by the industry authority and the municipal or county authority","They apply to development units that have passed environmental impact assessment; review is handled by a foundation testing organization commissioned by the central authority"],
 "Article 2."),

(P,"第3條",3,"清理計畫書-提送時機",
 "指定公告事業提送事業廢棄物清理計畫書之時機共有哪幾種？另有何營運限制？",
 ["新設、新提、重提、變更、異動及展延六種；且應於清理計畫書審查核准後，始得進行產生廢棄物之營運行為","新設、變更及展延三種；事業於提出清理計畫書申請之次日起即得先行營運，俟審查核准後再補正相關文件","新提、重提、異動及廢止四種；事業僅需於營運前向所在地主管機關報備，無須經審查核准即可開始營運","新設、新提、重提及展延四種；事業於取得工廠登記證後即得營運，清理計畫書得於營運後六個月內補送"],"a",
 "第3條第1項：提送時機為新設（新設事業屬指定公告事業時）、新提（既設事業未曾檢具經核准而依修正後公告規定需檢具時）、重提（清理計畫書經撤銷或廢止後仍需檢具時）、變更（符合第6條）、異動（符合第7條）、展延（符合第9條）。第2項：應於審查核准後，始得進行事業實質運作產生廢棄物之貯存、清除、處理、再利用、輸出及輸入之營運行為。",
 "What are the occasions for submitting an industrial waste disposal plan, and what operating restriction applies?",
 ["New establishment, first filing, refiling, amendment, minor change and renewal; operations generating waste may begin only after approval","New establishment, amendment and renewal; the enterprise may operate from the day after filing and supplement documents after approval","First filing, refiling, minor change and revocation; the enterprise need only file with the local authority and may operate without approval","New establishment, first filing, refiling and renewal; operations may begin on factory registration with the plan filed within six months"],
 "Article 3."),

(P,"第5條",3,"清理計畫書-應附文件",
 "指定公告事業辦理新設、新提或重提事業廢棄物清理計畫書，應併同檢具哪些文件？",
 ["相關許可登記執照或證明文件影本、負責人身分證明文件影本、設置專業技術人員之證明文件及環評相關書件","公司章程、股東名冊、最近三年財務報表、營利事業所得稅結算申報書及全體員工之勞工保險投保證明文件","土地及建物所有權狀影本、鄰近土地使用分區證明、地質鑽探報告及當地居民同意設廠之連署書等文件","清除機構之清除許可證影本、處理機構之處理許可證影本、運輸車輛行照影本及三年內之遞送聯單全部影本"],"a",
 "第5條第1項：應依中央主管機關網路傳輸申報系統所定格式填具清理計畫書，以電子簽章簽署之電子文件或書面併同下列文件一式二份提出：一、主管機關或目的事業主管機關核發之相關許可、登記、執照或其他證明文件影本（新設尚未取得者免附）；二、負責人身分證明文件影本；三、設置專業技術人員之相關證明文件（新設尚未完成設置者免附）；四、環境影響評估書件所載與廢棄物有關之內容及審查結論；五、其他經審核機關指定者。",
 "Which documents accompany a new, first-time or refiled industrial waste disposal plan?",
 ["Copies of relevant permits, registrations or licences, the responsible person identity document, professional technician certificates and EIA documents","Company articles, shareholder rosters, three years of financial statements, income tax filings and labour insurance certificates for all employees","Copies of land and building title deeds, zoning certificates, geological drilling reports and a petition of consent from nearby residents","Copies of clearance and disposal permits of the contractors, vehicle licence copies and all manifests from the preceding three years"],
 "Article 5."),

(P,"第6條",3,"清理計畫書-變更",
 "指定公告事業取得核准之清理計畫書後，有下列何種情形應事先辦理變更？",
 ["新增或改變製造過程、作業流程或處理流程致廢棄物性質改變或數量增加逾百分之十，或回收貯存清除處理再利用方法設施改變","新增或改變製造過程致廢棄物數量增加逾百分之三者，或事業之負責人、聯絡人、聯絡電話等基本資料發生任何異動情形者","事業之營業額較前一年度增加逾百分之十者，或所委託之清除機構、處理機構發生更換而未影響廢棄物之種類及數量者","事業廢棄物之貯存區位置微幅調整者，或事業因季節性因素致某月份廢棄物產生量較其他月份增加逾百分之二十之情形"],"a",
 "第6條第1項：取得核准後有下列情形之一者應事先辦理變更：一、新增或改變產品製造過程、作業流程或處理流程，致廢棄物性質改變或數量增加逾百分之十；二、廢棄物回收、貯存、清除、處理、再利用方法或設施改變；三、原物料使用量及產品產量或營運擴增及其他改變，致廢棄物性質改變或數量增加逾百分之十。第2項：非經常性廢棄物提出處置計畫書經核准者免辦理變更。",
 "Which situation requires an approved industrial waste disposal plan to be amended in advance?",
 ["New or changed manufacturing or operating processes altering waste properties or raising volume over ten percent, or changed handling methods or facilities","New or changed manufacturing processes raising waste volume by over three percent, or any change in the responsible person, contact person or phone number","The enterprise turnover rising more than ten percent over the previous year, or a change of clearance or disposal contractor without change in waste type","A slight relocation of the waste storage area, or seasonal factors making one month waste volume more than twenty percent higher than other months"],
 "Article 6."),

(P,"第7條",2,"清理計畫書-異動",
 "事業廢棄物清理計畫書所載資料變動而未致廢棄物性質改變或數量增加逾百分之十者，應如何辦理？",
 ["應於事實發生後十五日內辦理事業廢棄物清理計畫書異動，無須事先申請變更程序","應於事實發生後三十日內辦理清理計畫書變更，並經審核機關核准後始得繼續營運","應於事實發生後七日內報請目的事業主管機關備查，並副知所在地主管機關查核","應於次年度展延申請時一併敘明即可，事實發生當時無須辦理任何申報備查程序"],"a",
 "第7條第1項：清理計畫書所載基本資料、專業技術人員、原物料、產品或營運資料異動或製造過程、作業流程、處理流程新增或改變，而未致廢棄物性質改變或數量增加逾百分之十者，應於事實發生後十五日內辦理異動。第2項：新設事業申請時尚未完成專業技術人員設置者，應於完成設置後十五日內辦理異動。",
 "How must changes that do not alter waste properties or raise volume over ten percent be handled?",
 ["Apply for a minor change to the disposal plan within fifteen days of the event, with no prior amendment needed","Apply for an amendment to the disposal plan within thirty days and obtain approval before continuing operations","Report to the industry competent authority within seven days and copy the local competent authority","Simply state it when applying for renewal the following year, with no reporting at the time of the event"],
 "Article 7."),

(P,"第8條",2,"清理計畫書-變更異動程序",
 "指定公告事業辦理清理計畫書之變更或異動，應以何種方式向審核機關提出？",
 ["依中央主管機關網路傳輸申報系統格式填具申請表，以電子簽章電子文件或書面併同證明文件一式二份提出","以掛號郵寄書面申請表一式五份向中央主管機關提出，並副知所在地直轄市、縣（市）主管機關查核備案","由事業之專業技術人員親自送件至審核機關並當場口頭說明，經審核機關人員登記後即完成變更異動程序","僅需於中央主管機關網路申報系統線上勾選變更異動項目即可，無須檢附任何格式化申請表或證明文件"],"a",
 "第8條：指定公告事業辦理變更或異動事業廢棄物清理計畫書，應依中央主管機關網路傳輸申報系統所定格式，填具變更或異動申請表，以經電子簽章簽署之電子文件方式，或以書面方式併同變更或異動證明文件一式二份，向審核機關申請變更或異動。變更之事由見第6條，異動之事由見第7條。",
 "How must an enterprise submit an amendment or minor change of its waste disposal plan?",
 ["Complete the form in the central authority online reporting system, filed as a signed electronic document or in duplicate paper with supporting documents","Send five paper copies of the application by registered mail to the central competent authority and copy the municipal or county authority for filing","Have the professional technician deliver the documents in person and explain orally, the change taking effect once staff record it on the spot","Simply tick the changed items online in the central authority reporting system, with no formatted application form or supporting documents needed"],
 "Article 8."),

(P,"第10條",2,"清理計畫書-展延程序",
 "指定公告事業辦理事業廢棄物清理計畫書展延，應以何種方式提出申請？",
 ["依網路傳輸申報系統格式填具展延申請表，以電子簽章電子文件或書面併同第五條第一項文件一式二份申請","僅需於有效期限屆滿前以書面敘明繼續營運之意願函報審核機關，無須檢附第五條第一項所定之各項文件","應重新依新設程序全部重提事業廢棄物清理計畫書，並繳納與新設案件相同之審查費用後始得受理審查","應向中央主管機關申請展延並經核准後，再由中央主管機關函轉所在地直轄市、縣（市）主管機關備查"],"a",
 "第10條：指定公告事業辦理展延事業廢棄物清理計畫書，應依中央主管機關網路傳輸申報系統所定格式，填具展延申請表，以經電子簽章簽署之電子文件方式，或以書面方式併同第5條第1項規定之文件一式二份，向審核機關申請。依第9條第2項，展延應於有效期限屆滿前四個月至六個月提出。",
 "How must an enterprise apply to renew its industrial waste disposal plan?",
 ["Complete the renewal form in the online reporting system, filed as a signed electronic document or in duplicate paper with the Article 5 documents","Simply send a written statement of intent to continue operating before the validity period expires, without attaching the Article 5 documents","Refile the entire disposal plan under the new establishment procedure and pay the same review fee as a new case before it is accepted","Apply to the central competent authority for renewal and, once approved, have it forwarded to the municipal or county authority for filing"],
 "Article 10."),

(P,"第11條",3,"清理計畫書-審查期限",
 "審核機關受理新設、新提、重提、變更及展延案件，與受理異動案件之審查期限分別為何？",
 ["前者通知七日內繳納審查費並於四十五日內完成審查，必要時得再延長四十五日；後者應於二十五日內完成，必要時得延長二十五日","前者應於三十日內完成審查，必要時得延長三十日；後者應於十五日內完成審查，必要時得延長十五日並函知申請人辦理","前者應於六十日內完成審查且不得延長；後者應於三十日內完成審查，必要時得延長三十日並副知目的事業主管機關","前者應於九十日內完成審查，必要時得延長九十日；後者應於四十五日內完成審查，必要時得再延長四十五日辦理"],"a",
 "第11條第1項：審核機關受理新設、新提、重提、變更及展延後，應通知申請者於七日內繳納審查費，並應於四十五日內完成審查；必要時得再延長審查期限，以四十五日為限；審查符合規定者應於完成審查後七日內通知。第2項：受理異動後應於二十五日內完成審查，必要時得延長二十五日。",
 "What are the review periods for new, first-time, refiled, amendment and renewal cases versus minor change cases?",
 ["The former need the fee within seven days and review within forty-five days, extendable by forty-five; the latter within twenty-five days, extendable by twenty-five","The former must be reviewed within thirty days, extendable by thirty; the latter within fifteen days, extendable by fifteen with notice to the applicant","The former must be reviewed within sixty days with no extension; the latter within thirty days, extendable by thirty with a copy to the industry authority","The former must be reviewed within ninety days, extendable by ninety; the latter within forty-five days, extendable by a further forty-five days"],
 "Article 11, Paragraphs 1 and 2."),

(P,"第11條",3,"清理計畫書-補正限制",
 "審核機關通知申請者補正資料時，關於補正次數、日數及審查意見有何限制？",
 ["補正次數以三次為限、補正總日數不得超過三十日且不計入審查期限；審查意見應以一次性提供為原則","補正次數以五次為限、補正總日數不得超過六十日且計入審查期限；審查意見得於各次通知中隨時增列","補正次數並無限制、補正總日數不得超過九十日；審查意見得就申請項目以外之事項一併要求補正說明","補正次數以一次為限、補正日數不得超過十五日；審查意見應由審核機關會同目的事業主管機關提出"],"a",
 "第11條第4項、第5項：經認定應補正資料時，審查意見應以一次性提供為原則，並與申請項目或內容有關，後續通知不宜有前次未列明之審查意見；申請者未於期限內補正或未繳納審查費者得駁回申請，已補正而仍不合規定者得再通知限期補正，各次補正日數不計入審查期限，補正次數以三次為限，補正總日數不得超過三十日。",
 "What limits apply to requests for supplementary materials in terms of times, days and review comments?",
 ["At most three rounds, a total of thirty days excluded from the review period, and comments should in principle be given all at once","At most five rounds, a total of sixty days counted in the review period, and comments may be added freely in each notice","No limit on rounds and a total of ninety days, and comments may cover matters beyond the items applied for","At most one round of no more than fifteen days, and comments must be issued jointly with the industry authority"],
 "Article 11, Paragraphs 4 and 5."),

(P,"第11條之1",3,"清理計畫書-污染流向圖",
 "指定公告事業辦理清理計畫書各項申請前，應先完成何種檢視作業？",
 ["須先繪製全廠（場）空氣、水、廢棄物、毒性及關注化學物質污染流向示意圖，檢視污染在不同介質間之流向","須先委託環境檢驗測定機構完成全廠放流水及排放管道之採樣檢測，並取得符合標準之檢驗報告始得申請","須先辦理環境影響評估差異分析並取得目的事業主管機關核准，再據以向審核機關提出清理計畫書申請","須先取得所在地鄉（鎮、市）公所及鄰近居民之書面同意，並將同意文件併同清理計畫書送審核機關審查"],"a",
 "第11條之1第1項：指定公告事業辦理清理計畫書之新設、新提、重提、變更、異動或展延申請前，須先繪製全廠（場）空氣、水、廢棄物、毒性及關注化學物質污染流向示意圖，檢視污染在不同介質間之流向及在各類環保許可證（文件）間之關連。第2項並要求涉及其他類環保許可者須同時提出申請、變更、異動或展延。",
 "What review must an enterprise complete before filing any waste disposal plan application?",
 ["Draw a plant-wide flow diagram of air, water, waste, toxic and concerned chemical pollution to review flows across media","Commission an accredited testing body to sample plant effluent and stacks and obtain reports meeting the standards","Complete an environmental impact difference analysis approved by the industry authority before filing the plan","Obtain written consent from the township office and nearby residents and submit it together with the disposal plan"],
 "Article 11-1."),

(P,"第11條之2",3,"清理計畫書-固體再生燃料",
 "指定公告事業將事業廢棄物作為固體再生燃料原料用途，其新設、新提、重提申請應經何種審查程序？",
 ["應經書面審查、現場勘查及試運轉之三階段審查程序；涉及主要設備、廢棄物項目或數量之變更異動亦同","應僅經書面審查程序即可，惟審核機關認有必要時得於核准後一年內派員前往現場進行不定期抽查作業","應經書面審查及現場勘查之二階段程序，試運轉則由事業自行辦理並於完成後將結果函報審核機關備查","應先取得中央主管機關核發之固體再生燃料製造許可證，再向審核機關辦理清理計畫書之書面審查程序"],"a",
 "第11條之2第1項：指定公告事業採自行處理、自行再利用、依附表或公告管理方式，將事業廢棄物作為固體再生燃料原料用途，辦理清理計畫書之新設、新提、重提申請，應經書面審查、現場勘查及試運轉之三階段審查程序；清理計畫書之變更、異動申請涉及固體再生燃料製造技術相關之主要設備、廢棄物項目或數量時亦同。",
 "What review procedure applies when industrial waste is used as feedstock for solid recovered fuel?",
 ["A three-stage procedure of documentary review, site inspection and trial run; the same applies to changes in key equipment, items or volumes","Documentary review alone, though the reviewing authority may send staff for random on-site checks within one year after approval","A two-stage procedure of documentary review and site inspection; the trial run is run by the enterprise and its results merely filed","A solid recovered fuel manufacturing permit must first be obtained centrally, followed by documentary review of the disposal plan"],
 "Article 11-2, Paragraph 1."),

(P,"第11條之2",3,"清理計畫書-試運轉期限",
 "固體再生燃料相關案件之試運轉期限、展延及報告檢送期限規定為何？",
 ["試運轉期限不得超過二個月，展延以一次為限且不得超過一個月，應於屆滿十五日前申請；報告應於屆滿次日起三十日內檢送","試運轉期限不得超過六個月，展延以二次為限每次三個月，應於屆滿三十日前申請；報告應於屆滿次日起六十日內檢送審查","試運轉期限不得超過一個月，且不得申請任何展延；試運轉報告應於試運轉期限屆滿之次日起十五日內檢送審核機關審查","試運轉期限不得超過三個月，展延以一次為限且不得超過三個月，應於屆滿七日前申請；報告應於屆滿後九十日內檢送"],"a",
 "第11條之2第3項：試運轉期限不得超過二個月，屆期未完成者得於核准期限屆滿前申請展延，展延申請次數以一次為限，展延期限不得超過一個月，試運轉期間不計入第11條第1項及第2項之審查期限；應於試運轉期限屆滿十五日前申請展延。第5項：至遲應於試運轉期限屆滿之次日起三十日內，檢具試運轉報告及符合固體再生燃料品質標準之檢測報告送審，屆期未檢送者駁回申請。",
 "What are the trial run period, extension and report submission deadlines for solid recovered fuel cases?",
 ["The trial run may not exceed two months, extendable once by up to one month applied for fifteen days ahead; the report is due within thirty days after expiry","The trial run may not exceed six months, extendable twice by three months each applied for thirty days ahead; the report is due within sixty days after expiry","The trial run may not exceed one month and no extension is allowed; the trial run report is due within fifteen days after the period expires","The trial run may not exceed three months, extendable once by up to three months applied for seven days ahead; the report is due within ninety days"],
 "Article 11-2, Paragraphs 3 and 5."),

(P,"第12條",2,"清理計畫書-審查結果",
 "中央主管機關委託之機關受理審查清理計畫書時，及發現核准內容有顯然錯誤時，應如何處理？",
 ["應將審查結果副知事業所在地直轄市、縣（市）主管機關；發現誤寫誤算等顯然錯誤者得隨時更正並通知事業","應將審查結果報請中央主管機關核備後公告於網站；發現顯然錯誤者應撤銷原核准處分並命事業重新提送","應將審查結果逕行函知事業即可無須副知他機關；發現顯然錯誤者應俟事業申請變更時一併更正並通知之","應將審查結果送目的事業主管機關會核後始生效力；發現顯然錯誤者應報請中央主管機關核准後始得更正"],"a",
 "第12條第1項：中央主管機關委託之機關受理審查事業廢棄物清理計畫書時，應將審查結果副知指定公告事業所在地直轄市、縣（市）主管機關。第2項：審核機關發現審核通過之清理計畫書有誤寫、誤算或其他類此未符合本法及相關規定之顯然錯誤者，得隨時更正之，並通知指定公告事業。",
 "How must a commissioned agency handle review results and obvious errors in an approved plan?",
 ["Copy the review result to the municipal or county authority where the enterprise is located; obvious clerical errors may be corrected at any time with notice","Report the review result to the central authority for filing and publish it online; on obvious errors revoke the approval and require refiling","Notify only the enterprise of the review result; obvious errors are corrected together with the next amendment application and notified then","Send the review result to the industry authority for countersignature before it takes effect; obvious errors need central approval before correction"],
 "Article 12."),

(P,"第13條",1,"清理計畫書-遵行義務",
 "指定公告事業就其事業廢棄物之貯存、清除、處理、再利用、輸出及輸入行為應如何辦理？",
 ["應依審核機關核准之事業廢棄物清理計畫書內容進行各該行為","得依實際營運需要彈性調整，事後再併入年度申報一併說明","應依所委託清除處理機構之許可證內容辦理即為已足並免申報","應依目的事業主管機關另行核定之作業手冊辦理而非清理計畫書"],"a",
 "第13條：指定公告事業應依核准之事業廢棄物清理計畫書進行事業廢棄物貯存、清除、處理、再利用、輸出及輸入之行為。違反本條同一規定一年內經二次限期改善仍繼續違反者，依第16條第1項第1款得移請審核機關撤銷或廢止其清理計畫書。",
 "How must a designated enterprise conduct storage, clearance, disposal, reuse, export and import of its waste?",
 ["In accordance with the industrial waste disposal plan approved by the reviewing authority","Flexibly as operations require, explaining the differences later in the annual report","In accordance with the permits of the contracted clearance and disposal organizations only","In accordance with an operating manual separately approved by the industry competent authority"],
 "Article 13."),

(P,"第14條",2,"清理計畫書-產出物認定",
 "審核機關對清理計畫書中製程產出物之認定，應依何種原則辦理？",
 ["應謹慎審查並得要求提供產品種類成分規格形態用途或流向等資料，確認說明合理技術可行且流向無虞","應以事業自行提出之產品說明書為準即可，無須另行要求提供成分規格或流向等佐證資料以簡化程序","應一律認定製程產出物為事業廢棄物，除非事業取得中央目的事業主管機關核發之產品認定證明文件","應委請學者專家組成審查小組逐案表決認定，並將認定結果公告於審核機關網站供各界查閱及陳述意見"],"a",
 "第14條：清理計畫書中製程產出物之認定，審核機關應謹慎審查，必要時應請指定公告事業提供產品種類、成分、規格、形態、顏色、數量、照片、用途或流向等資料以供審查，並應確認產品之說明屬合理、技術可行且流向無虞；審核機關與工商登記單位應加強橫向聯繫，避免發生廢棄物登記為產品情事。",
 "What principles guide the reviewing authority in identifying process outputs in a disposal plan?",
 ["Review carefully and where needed request product type, composition, specification, form, use or flow data to confirm the account is reasonable and feasible","Accept the product description supplied by the enterprise as sufficient, without requesting composition, specification or flow evidence, to simplify the process","Treat all process outputs as industrial waste unless the enterprise holds a product identification certificate issued by the central industry authority","Convene a panel of scholars and experts to vote case by case and publish the outcome on the authority website for public inspection and comment"],
 "Article 14."),

(P,"第15條",2,"清理計畫書-解除列管",
 "指定公告事業遷廠、停（歇）業或宣告破產且已清理廠內廢棄物者，應如何辦理？",
 ["應向所在地直轄市、縣（市）主管機關申請解除列管","應逕向中央主管機關申請廢止其事業廢棄物清理計畫書","應向原審核機關申請暫停列管，俟三年後始得解除列管","應向目的事業主管機關辦理歇業登記即當然解除其列管"],"a",
 "第15條：指定公告事業遷廠、停（歇）業或宣告破產，且依核准之事業廢棄物清理計畫書清理廠內廢棄物後，應向所在地直轄市、縣（市）主管機關申請解除列管。第4條第6款並要求清理計畫書應載明遷廠、停（歇）業、宣告破產時之事業廢棄物清理計畫。",
 "What must an enterprise do after relocating, ceasing business or declaring bankruptcy and clearing its waste?",
 ["Apply to the municipal or county competent authority where it is located to be removed from the control list","Apply directly to the central competent authority to revoke its industrial waste disposal plan","Apply to the original reviewing authority to suspend control status, with removal only after three years","Register the closure with the industry competent authority, which removes control status automatically"],
 "Article 15."),

(P,"第17條",2,"清理計畫書-外文文件",
 "本辦法所定相關文件為外文者，及應檢附之文件於國外或大陸地區製作者，應如何辦理？",
 ["外文者應附經駐外機構驗證或國內公證人認證之中文譯本；國外製作者應經駐外機構驗證，大陸地區製作者應經指定機構驗證","外文者由事業自行翻譯後由負責人簽名切結即可；國外及大陸地區製作之文件均僅需檢附影本並加蓋公司大小章","外文者應附經審核機關指定翻譯社翻譯之譯本；國外製作者應經外交部驗證，大陸地區製作者應經內政部驗證","外文者得逕以原文提送而免附中文譯本；國外及大陸地區製作之文件均應經中央主管機關委託之機構複驗確認"],"a",
 "第17條第1項：本辦法所定之相關文件為外文者，應檢附經駐外機構驗證或國內公證人認證之中文譯本。第2項：依規定應檢附之文件於國外製作者，應經駐外機構驗證；在國內由外國駐我國使領館或其授權代表機構製作者，應經外交部複驗；在大陸地區或香港、澳門製作者，應經行政院設立或指定機構或委託之民間團體驗證。",
 "How must foreign-language documents and documents made abroad or in mainland China be handled?",
 ["Foreign-language ones need a Chinese translation verified by an overseas mission or notarized locally; documents made abroad need mission verification and mainland ones designated-agency verification","The enterprise may translate them itself with a declaration signed by the responsible person; documents made abroad or in the mainland need only copies stamped with company seals","They need a translation by a translation agency designated by the reviewing authority; documents made abroad need foreign ministry verification and mainland ones interior ministry verification","They may be submitted in the original language without a Chinese translation; documents made abroad or in the mainland must be re-verified by a commissioned organization"],
 "Article 17."),

(P,"第18條",2,"清理計畫書-過渡規定",
 "本辦法施行前經審核機關核准之事業廢棄物清理計畫書，其效力及期限規定為何？",
 ["原核准之清理計畫書仍屬有效，但應於中華民國一百十一年十二月三十一日前取得核准期限，屆期未取得者失其效力","原核准之清理計畫書於本辦法施行之日起即當然失其效力，指定公告事業應依新設程序重新提送清理計畫書送審","原核准之清理計畫書永久有效且無須辦理展延，僅於有第六條所定變更事由發生時始須向審核機關申請辦理變更","原核准之清理計畫書自本辦法施行日起算五年內有效，期滿後應依第九條第二項規定於屆滿前四至六個月申請展延"],"a",
 "第18條：指定公告事業於本辦法施行前，經審核機關核准之事業廢棄物清理計畫書仍屬有效；但指定公告事業應於中華民國一百十一年十二月三十一日前，取得事業廢棄物清理計畫書之核准期限，屆期未取得者，原核准之事業廢棄物清理計畫書失其效力。第9條並定有效期限原則為五年。",
 "What is the status and deadline of disposal plans approved before these Regulations took effect?",
 ["They remain valid, but the enterprise must obtain an approved validity period before 31 December 2022, failing which they lapse","They lapse automatically when the Regulations take effect, and the enterprise must refile under the new establishment procedure","They remain valid indefinitely without renewal, and amendment is needed only when an Article 6 change occurs","They remain valid for five years from the effective date, after which renewal must be sought four to six months before expiry"],
 "Article 18."),

(P,"第19條",1,"清理計畫書-施行日期",
 "事業廢棄物清理計畫書審查管理辦法之施行日期如何規定？",
 ["本辦法自中華民國一百零七年七月一日施行；修正條文則自發布日施行","本辦法自中華民國一百零七年一月一日施行；修正條文自發布後一年施行","本辦法自發布日施行；修正條文則自中華民國一百十四年七月十日起施行","本辦法自中華民國一百十一年十二月三十一日施行；修正條文亦自同日施行"],"a",
 "第19條：本辦法自中華民國一百零七年七月一日施行；本辦法修正條文自發布日施行。本辦法最新修正日期為民國114年7月10日，依本法第31條第2項及第3項授權訂定，內容包括提送時機、應載明事項、變更異動展延、審查期限與補正限制、固體再生燃料三階段審查及撤銷廢止事由等。",
 "How is the effective date of these Regulations prescribed?",
 ["The Regulations took effect on 1 July 2018; amendments take effect on their promulgation date","The Regulations took effect on 1 January 2018; amendments take effect one year after promulgation","The Regulations take effect on promulgation; the amendments take effect from 10 July 2025","The Regulations took effect on 31 December 2022; the amendments take effect on that same date"],
 "Article 19."),
]
