# -*- coding: utf-8 -*-
# 第 7 批（A）：職場霸凌防治措施準則、最高負責人霸凌申訴辦法、工程安全設計及整體工程統合管理辦法、
#              勞工作業場所容許暴露標準、勞工作業環境監測實施辦法（依全國法規資料庫「職業安全衛生目」總表補齊）
WB = "OSH-55"; WT = "OSH-56"; ED = "OSH-57"; PEL = "OSH-51"; EM = "OSH-52"
Q = [
# ---------- 職場霸凌防治措施準則（115/6/23，115/7/1 施行） ----------
(WB,"第2條",2,"霸凌-認定",
 "職場霸凌防治措施準則列舉之職場霸凌審酌情形，下列何者正確？",
 ["對特定人刻意排擠冷落不讓參與必要會議、破壞或阻礙其工作隱瞞資訊、以權力分配不合理工作目標、散布謠言或揭露隱私","主管依規定考核","同事意見不合一次","要求依工作規則出勤"],"a",
 "第2條：職場霸凌之認定應符合職安法第22條之1第1項定義，並綜合審酌事件背景頻率場所行為人動機目的及：對特定人刻意排擠忽視冷落不讓參與必要之重要會議事務或活動；破壞或刻意阻礙其工作、利用職務刁難、隱瞞或提供不實資訊；以權力欺壓刻意分配不合理工作目標或與能力明顯不符之工作；刻意散布謠言或揭露隱私。",
 "Which are listed as circumstances for identifying workplace bullying under the Guidelines?",
 ["Deliberately excluding someone from necessary meetings, sabotaging their work or withholding information, abusing power to assign unreasonable targets, spreading rumors or exposing privacy","Conducting performance reviews per rules","A single disagreement","Requiring attendance per work rules"],
 "Article 2 lists four patterns, weighed with background, frequency, place, motive and purpose."),

(WB,"第5條",2,"霸凌-申訴管道",
 "僱用勞工人數在幾人以上之雇主，應設置處理職場霸凌之申訴管道（電子信箱、專線電話等）並公開揭示？",
 ["十人以上","三十人以上","五人以上","一百人以上"],"a",
 "第5條：僱用勞工人數十人以上之雇主應設置處理職場霸凌之電子信箱專用信箱專線電話傳真或其他指定通訊軟體等申訴管道，並於工作場所顯著處公開揭示（得以書面電子資料傳輸或其他可隨時查知方式）。第4條：雇主應提供免於職場霸凌之工作環境並維護隱私。",
 "Employers with at least how many workers must set up and post a bullying complaint channel?",
 ["10","30","5","100"],
 "Article 5; Article 4 sets the general duty."),

(WB,"第6條",2,"霸凌-防治規範",
 "僱用勞工人數在幾人以上之雇主，應訂定職場霸凌防治措施、申訴與懲處規範並指定專責單位統籌辦理？",
 ["三十人以上","十人以上","五十人以上","一百人以上"],"a",
 "第6條：僱用勞工三十人以上之雇主除設申訴管道外，應訂定職場霸凌防治措施申訴與懲處規範、指定專責單位統籌並公開揭示；內容應包括行為樣態及預防措施、教育訓練、申訴處理單位與程序、調查人員資格及迴避、不公開處理及免於報復、屬實行為人之懲戒、惡意虛構事實之懲戒、被申訴人為最高負責人時得逕向地方主管機關申訴；各級主管及調查處理人員另應實施溝通技巧管理及申訴處理教育訓練；未達三十人者得參照辦理。",
 "Employers with at least how many workers must adopt written bullying prevention, complaint and disciplinary rules with a dedicated unit?",
 ["30","10","50","100"],
 "Article 6 lists eight required contents and training obligations."),

(WB,"第7條",2,"霸凌-立即措施",
 "雇主因接獲被霸凌勞工申訴而知悉職場霸凌時，應採取之立即有效措施，下列何者正確？",
 ["考量申訴人意願採取隔離措施且不得不利對待、提供或轉介法律諮詢醫療心理諮商等協助、啟動調查（申訴人有意願得先協調）、依調查結果懲戒行為人","要求申訴人自行處理","先懲戒申訴人","不需調查"],"a",
 "第7條：因申訴知悉時應考量申訴人意願採取適當隔離等措施避免再發生且不得不利對待、依需求提供或轉介法律諮詢醫療心理諮商社會福利資源等協助、啟動調查（有意願者得協調，協調不成立續行調查）、依調查結果懲戒或處理；非因申訴知悉時應訪談釐清、告知權益及救濟途徑、調整工作內容或場所、依意願提供協助；被霸凌勞工無申訴意願者仍應採取措施。",
 "When an employer learns of bullying through a complaint, immediate measures include:",
 ["Separation measures respecting the complainant's wishes with no adverse treatment, referral to legal, medical or counseling support, launching an investigation (with optional mediation), and disciplining the perpetrator based on findings","Telling the complainant to handle it","Disciplining the complainant first","No investigation"],
 "Article 7 also sets duties when bullying is learned of by other means."),

(WB,"第8條",3,"霸凌-申訴期限",
 "職場霸凌申訴自行為終了時起逾幾年者不予受理？被申訴人屬利用權勢者，得於離職之日起幾年內申訴？",
 ["三年；一年","一年；六個月","五年；二年","二年；一年"],"a",
 "第8條：申訴得以言詞電子郵件或書面提出，言詞或電子郵件者應作成紀錄朗讀或使閱覽確認；紀錄應由申訴人簽名或蓋章並載明姓名服務單位職稱住居所聯絡電話申訴日期、代理人資料、事實內容及證據；自職場霸凌行為終了時起逾三年者不予受理；被申訴人屬利用權勢者得於離職之日起一年內申訴（有較長期限者從其規定）；處理應以不公開方式為之。",
 "Bullying complaints are not accepted more than how many years after the conduct ended, and when the accused abused a position of power, complaints may be filed within how long after leaving employment?",
 ["3 years; 1 year","1 year; 6 months","5 years; 2 years","2 years; 1 year"],
 "Article 8."),

(WB,"第9條",3,"霸凌-申訴處理單位",
 "僱用勞工三十人以上之雇主設置之申訴處理單位，成員至少幾位？任一性別比例不得少於多少？",
 ["三位；三分之一","二位；二分之一","五位；四分之一","三位；二分之一"],"a",
 "第9條：申訴處理單位成員至少三位且任一性別比例不得少於三分之一；負責受理申訴、通知是否受理、登錄系統、辦理協調、調查或審議調查報告作成申訴成立與否之決定、提供懲戒建議、召開申復審議會議、通知當事人決定等。",
 "The complaint-handling unit for employers with 30+ workers must have at least how many members, with each gender making up at least:",
 ["3; one-third","2; one-half","5; one-quarter","3; one-half"],
 "Article 9 lists the unit's nine functions."),

(WB,"第10條",2,"霸凌-受理",
 "雇主應於接獲職場霸凌申訴之日起幾個工作日內決定是否受理並以書面通知申訴人？受理後應於幾個工作日內登錄系統？",
 ["十個工作日；受理翌日起七個工作日","三個工作日；三個工作日","三十日；十日","五個工作日；十個工作日"],"a",
 "第10條：應於接獲申訴之日起十個工作日內決定是否受理並書面通知，不受理者敘明理由；得不受理情形：非屬職場霸凌事項、無具體內容、未具真實姓名、同一事件已不受理或已終局處理、已撤回、已逾期限。第11條：應於受理翌日起七個工作日內依中央主管機關公告之內容及方式登錄系統並通知申訴人。",
 "Employers must decide whether to accept a bullying complaint within how many working days, and log accepted cases in the system within:",
 ["10 working days; 7 working days from the day after acceptance","3; 3","30 days; 10 days","5; 10"],
 "Articles 10–11."),

(WB,"第13條",3,"霸凌-協調",
 "職場霸凌申訴之協調程序，自協調之日起逾多久仍未有共識時應停止協調？協調不成立時雇主應如何？",
 ["一個月；續行調查並採取其他立即有效之適當措施","三個月；結案","七日；不需調查","六個月；再協調一次"],"a",
 "第13條：申訴人有意願協調者，應安排經當事人同意之適當協調人員本於客觀公正公平立場促進溝通；任一方無意願或自協調之日起逾一個月仍未有共識應停止協調；達成共識應作成紀錄載明事實及合意事項；協調不成立者雇主應續行調查並採取其他立即有效之適當措施；非因申訴知悉但有意願協調者亦同。",
 "Mediation of a bullying complaint must stop if no consensus is reached within, and if mediation fails the employer must:",
 ["1 month; continue the investigation and take other immediate effective measures","3 months; close the case","7 days; no investigation needed","6 months; mediate once more"],
 "Article 13."),

(WB,"第14條",3,"霸凌-調查小組",
 "僱用勞工一百人以上之雇主調查職場霸凌申訴時，應於受理之日起幾個工作日內組成調查小組？調查小組外部專業人士比例？事業單位成員應受幾小時防治教育訓練？",
 ["十五個工作日；不得少於二分之一；至少三小時","七個工作日；三分之一；六小時","三十日；全部；一小時","十個工作日；四分之一；三小時"],"a",
 "第14條：一百人以上之雇主應於受理申訴之日起十五個工作日內由申訴處理單位選任調查成員組成調查小組；成員至少三人、外部專業人士不得少於二分之一、任一性別比例不得少於三分之一；事業單位成員應參加主管機關或勞檢機構課程或中央主管機關網站數位課程至少三小時；外部專業人士應具勞動權益或相關事務處理經驗，得自職場霸凌調查專業人才資料庫遴選。第15條：與當事人有配偶前配偶四親等內血親三親等內姻親或家長家屬關係者應自行迴避。",
 "Employers with 100+ workers must form an investigation team within how many working days of acceptance, with what share of external experts, and how many hours of training for internal members?",
 ["15 working days; at least one-half; at least 3 hours","7 working days; one-third; 6 hours","30 days; all; 1 hour","10 working days; one-quarter; 3 hours"],
 "Article 14; Article 15 on recusal."),

(WB,"第16條",2,"霸凌-調查方式",
 "職場霸凌調查訪談當事人及相關人員時，下列何者正確？",
 ["以錄音或錄影輔助並作成紀錄，受訪談者不得自行錄音錄影；不得令當事人間對質；應保密姓名及身分資料","可令當事人對質","受訪談者可自行錄音","不需紀錄"],"a",
 "第16條：以書面通知當事人記載調查目的時間地點及不到場之影響；訪談以錄音或錄影輔助並作成紀錄，受訪談者不得自行錄音或錄影；調查過程或會議不得令當事人間或協助調查之人對質；當事人及相關人員應配合調查提供資料；得諮詢專業機關團體；保全證據；姓名及足以辨識身分之資料應保密（調查必要或公共安全考量除外）；所有參與人員負保密義務。",
 "During bullying investigation interviews:",
 ["Audio or video recording assists the record, interviewees may not record on their own; parties may not be made to confront each other; identities are kept confidential","Parties may be confronted with each other","Interviewees may record themselves","No records needed"],
 "Article 16."),

(WB,"第17條",3,"霸凌-調查期限",
 "雇主應自調查小組成立後翌日起多久內完成調查報告？必要時得延長多久？申訴處理單位至遲於調查報告完成之日起多久內作成成立與否之決定？",
 ["二個月；一個月；一個月","一個月；一個月；十日","三個月；三個月；二個月","十五日；十五日；七日"],"a",
 "第17條：應自調查小組成立後翌日起二個月內完成調查報告，必要時得延長一個月並通知當事人，協調期間不計入；報告應包括案由、訪談過程、陳述重點、事實認定與理由、處理建議；當事人無正當理由拒絕配合經通知限期仍未配合者得逕行作成報告。第18條：申訴處理單位至遲於調查報告完成之日起一個月內作成申訴成立與否之決定（成員二分之一以上出席、出席者過半數同意）；雇主應於決定之日起十個工作日內書面通知當事人並提供申復方法及期限。",
 "The investigation report is due within what period after the team is formed, extendable by, and the handling unit must decide within what period after the report:",
 ["2 months; 1 month; 1 month","1 month; 1 month; 10 days","3 months; 3 months; 2 months","15 days; 15 days; 7 days"],
 "Articles 17–18."),

(WB,"第19條",2,"霸凌-懲戒與登錄",
 "職場霸凌行為經調查屬實，雇主應如何？處理結果應於決定作成之日起幾個工作日內登錄系統？",
 ["視情節輕重對行為人適當懲戒或處理（已離職者除外）；十個工作日","一律解僱；三十日","口頭警告即可；不需登錄","調職申訴人；七日"],"a",
 "第19條：經調查屬實者應視情節輕重對行為人為適當懲戒或處理（已離職者不在此限）；情節輕重審酌對申訴人身心侵害程度、次數頻率手段重複違反、與申訴人關係違反後態度及過往行為、對事業單位危害程度範圍；處理結果應於決定作成之日起十個工作日內登錄系統。第20條：不得對申訴或協助申訴之工作者為解僱降調減薪等不利處分（惡意虛構事實者除外）。第26條：執行紀錄留存三年。",
 "When bullying is substantiated the employer must, and log the outcome within:",
 ["Impose appropriate discipline on the perpetrator based on severity (unless already departed); 10 working days","Always dismiss; 30 days","Verbal warning only; no logging","Transfer the complainant; 7 days"],
 "Article 19; Article 20 bars retaliation; Article 26: records kept 3 years."),

(WB,"第21條",3,"霸凌-小型事業處理期限",
 "僱用勞工未達三十人之雇主，職場霸凌申訴應自接獲申訴翌日起多久內作成決定？三十人以上未達一百人者？",
 ["三個月內（得延長一個月）；四個月內（得延長一個月）","一個月；二個月","六個月；六個月","十日；三十日"],"a",
 "第21條：未達三十人之雇主應自接獲申訴翌日起三個月內作成決定，必要時得延長一個月並通知當事人，申訴處理單位及調查小組規定得參照辦理；三十人以上未達一百人者四個月內作成決定，必要時延長一個月，調查小組規定得參照辦理。",
 "Employers with fewer than 30 workers must decide bullying complaints within, and those with 30 to under 100 workers within:",
 ["3 months (extendable 1 month); 4 months (extendable 1 month)","1 month; 2 months","6 months; 6 months","10 days; 30 days"],
 "Article 21."),

(WB,"第22條",3,"霸凌-申復",
 "當事人不服職場霸凌申訴決定，得於收到書面通知翌日起幾日內向雇主提出申復？雇主應於接獲申復後幾個工作日內召開申復審議會議？",
 ["三十日；十個工作日","十日；五個工作日","六十日；三十日","七日；三日"],"a",
 "第22條：得於收到書面通知翌日起三十日內書面具明理由提出申復，同一事件以一次為限；雇主應於接獲申復後十個工作日內由申訴處理單位成員推舉召集人召開申復審議會議並給予申復人陳述機會；發現調查程序有重大瑕疵或足以影響認定之新事證應組成申復調查小組再行調查（一百人以上外部專業人士不得少於三分之二，三十人以上未達一百人至少一人，任一性別不少於三分之一）。第23條：申訴處理單位應自申復審議會議召開日起三十日內作成決定，雇主於十個工作日內書面通知；再行調查者得展延三十日。",
 "A party may appeal a bullying decision within how many days of notice, and the employer must convene an appeal review within:",
 ["30 days; 10 working days","10 days; 5 working days","60 days; 30 days","7 days; 3 days"],
 "Articles 22–23; Article 24: authorities may order re-investigation for serious procedural defects."),

# ---------- 地方主管機關受理最高負責人職場霸凌事件申訴處理辦法（115/6/23） ----------
(WT,"第2條",2,"霸凌申訴-最高負責人",
 "勞工遭受事業單位最高負責人職場霸凌時，得向何機關提起申訴？所稱最高負責人包括？",
 ["直轄市或縣市主管機關；機關首長、學校校長、公營事業董事長、法人合夥或非法人團體之對外代表人或與該等職務相當之人","勞動部；僅董事長","法院；僅總經理","警察機關；僅負責人"],"a",
 "第2條：勞工遭受最高負責人職場霸凌得向直轄市或縣市主管機關申訴；最高負責人指機關（構）首長學校校長行政法人董（理）事長公營事業董事長理事主席或相當之人、法人合夥設有代表人或管理人之非法人團體及其他組織之對外代表人或相當之人。第3條：與代表人職務相當之人指實質執行代表人業務或實質控制人事財務業務經營且現任或曾任董監事、持股百分之二十以上、經工會股東廠商或申訴人指認有具體事證、代表人之配偶四親等內血親等、改選未登記、位居特殊重要職位者。",
 "Workers bullied by the enterprise's top executive may complain to whom, and who counts as the top executive?",
 ["The municipal or county government; agency heads, school principals, chairpersons of public enterprises, legal representatives of companies or organizations, and persons in equivalent positions","The Ministry of Labor; chairpersons only","Courts; general managers only","Police; owners only"],
 "Articles 2–3 (e.g., persons holding 20%+ shares or spouses/relatives of the representative may be deemed equivalent)."),

(WT,"第9條",3,"霸凌申訴-受理與調查",
 "地方主管機關應於接獲最高負責人霸凌申訴之日起幾個工作日內書面通知是否受理？受理後應於幾個工作日內開始調查並於多久內完成？",
 ["十個工作日；十個工作日；二個月（得延長一個月）","三日；三日；一個月","三十日；三十日；六個月","七日；七日；三個月"],"a",
 "第7條：申訴應以書面為之並載明申訴人資料代理人資料事實內容證據及日期，不符者通知文到十個工作日內補正。第9條：不予受理情形包括非屬最高負責人、無具體內容、未具真實姓名、逾期限、未補正、同一事件已調查完成或已處分、撤回後再提起；應於接獲申訴之日起十個工作日內書面通知是否受理。第10條：受理日起十個工作日內開始調查並於二個月內完成，必要時延長一個月。第11條：調查成員至少二人任一性別不少於三分之一。第16條：至遲於調查報告完成日起一個月內為成立與否之決定，成立者依法裁處。",
 "Local authorities must notify acceptance of a top-executive bullying complaint within, start investigating within, and complete it within:",
 ["10 working days; 10 working days; 2 months (extendable 1 month)","3 days; 3 days; 1 month","30 days; 30 days; 6 months","7 days; 7 days; 3 months"],
 "Articles 7–11 and 16."),

# ---------- 工程安全設計及整體工程統合管理辦法（115/6/30，115/7/1 施行） ----------
(ED,"第2條",2,"工程安全設計-定義",
 "工程安全設計及整體工程統合管理辦法所稱「安全設計」係指？",
 ["於工程規劃設計階段分析潛在施工危害，優先透過設計措施消除或降低風險，就剩餘風險實施風險評估規劃預防設備措施，編製安全衛生圖說及規範並量化編列安全衛生費用之設計","施工中之安全管理","完工後之安全檢查","保險規劃"],"a",
 "第2條：工程指新建增建改建修建拆除構造物與改變自然環境之行為；工程規劃指設計前之可行性與整體配置方案分析；工程設計指依規劃成果編製圖說規範預算技術文件；安全設計指於規劃設計階段依工程特性分析潛在施工危害，優先透過設計措施消除或降低職災風險，就剩餘風險實施風險評估規劃必要預防設備措施，編製安全衛生圖說及規範並量化編列安全衛生費用；統合管理指同一工程二個以上施工者共同作業時由主施工者統一規劃協調指揮連繫管制；工程業主指職安法第15條之1及第27條之1所定將工程交付規劃設計或施工之事業單位。",
 "'Safety design' under the Regulations means:",
 ["Analyzing construction hazards at the planning and design stage, eliminating or reducing risk through design first, assessing residual risk, preparing safety and health drawings and specifications, and quantifying safety costs","Safety management during construction","Post-completion inspection","Insurance planning"],
 "Article 2 also defines integrated management by the principal contractor and the project owner."),

(ED,"第3條",3,"工程安全設計-適用範圍",
 "職安法第15條之1所稱一定規模以上之工程，新建建築工程之門檻為何？其他工程之門檻？",
 ["高度八十公尺以上、開挖深度十八公尺且面積五百平方公尺以上、或造價二億元以上；預算或契約價金二億元以上","高度五十公尺；一億元","高度一百公尺；五億元","任何規模；一千萬元"],"a",
 "第3條：應申請建造執照之新建建築工程高度達八十公尺以上、開挖深度達十八公尺以上且開挖面積達五百平方公尺以上、或工程造價達新臺幣二億元以上；前款以外之工程預算金額或契約價金達二億元以上；其他經中央主管機關指定公告者；分開招標者金額合併計算。第4條：二個以上工程業主應互推代表人，未互推者共同負責。",
 "'Projects of a certain scale' under Article 15-1 of the OSH Act are new buildings meeting what thresholds, or other projects of:",
 ["Height 80 m+, excavation 18 m deep and 500 m²+, or cost NT$200 million+; budget or contract NT$200 million+","Height 50 m; NT$100 million","Height 100 m; NT$500 million","Any size; NT$10 million"],
 "Article 3; Article 4 on multiple owners."),

(ED,"第5條",3,"工程安全設計-規劃階段",
 "工程業主將工程交付規劃時應提出「工程規劃安全分析」，其內容包括？",
 ["工址環境潛在危害及風險對策、工程需求之安全設計注意事項、建議之安全施工方法、其他潛在危害需再評估事項","僅預算","僅工期","僅承商名單"],"a",
 "第5條：交付規劃時應參照規劃階段事前調查資訊就各方案辨識潛在施工危害，並就選定方案提出工程規劃安全分析：工址環境之潛在危害及風險對策、工程需求之安全設計應注意事項、建議之安全施工方法、其他潛在危害需再評估事項；應納入設計階段事前調查資訊。第6條：交付設計時應研訂安全設計方案、實施風險評估及對策、編製安全衛生圖說及規範、量化編列安全衛生費用並製作工程規劃設計安全分析報告（工程概要、潛在施工危害、安全設計方案、風險評估及對策、圖說及規範、費用），提供施工者作為施工計畫書參考。",
 "The 'project planning safety analysis' required when commissioning planning must include:",
 ["Site hazards and risk countermeasures, safety design considerations for project requirements, recommended safe construction methods, and other hazards needing reassessment","Budget only","Schedule only","Contractor list only"],
 "Article 5; Article 6 details the design-stage safety analysis report."),

(ED,"第7條",3,"工程安全設計-圖說規範",
 "安全衛生圖說之內容應包括？安全衛生規範之內容應包括？",
 ["安全衛生設施配置圖、構造型式說明、構件規格及尺寸大樣；法令依據、設施組立及拆除方式、管理注意事項、計量及計價方式","僅平面圖；僅工期","僅照片；僅價格","僅承商資料；僅罰則"],"a",
 "第7條：安全衛生圖說包括安全衛生設施之配置圖、構造型式說明、構件之規格及尺寸大樣；安全衛生規範包括職業安全衛生法令依據、設施之組立及拆除作業方式、安全衛生管理注意事項、設施與管理之計量及計價方式；種類例示如附表一。第8條：應依安全分析報告量化編列安全衛生費用納入招標文件或契約。第9條：應將施工者之職安管理績效（職災裁罰獲獎等履歷）作為選擇施工者參考。",
 "Safety and health drawings must include, and safety and health specifications must include:",
 ["Layout of safety facilities, structural type descriptions, component specifications and details; legal basis, erection and dismantling methods, management notes, measurement and pricing","Floor plans only; schedule only","Photos only; prices only","Contractor data only; penalties only"],
 "Article 7; Article 8: costs into tender documents; Article 9: contractor OSH track record as selection criterion."),

(ED,"第10條",2,"工程安全設計-施工計畫",
 "工程業主交付施工時，招標文件或契約應明定施工者辦理事項，施工計畫書應包括？",
 ["工程概要、職業安全衛生管理計畫、分項工程作業計畫","僅工期表","僅人力表","僅材料清單"],"a",
 "第10條：招標文件或契約應明定依施工階段事前調查資訊、工程規劃設計安全分析報告及契約圖說進行施工規劃，實施風險評估並將施工風險評估報告所提必要安全衛生設備措施納入施工計畫書確實執行；施工計畫書應包括工程概要、職業安全衛生管理計畫、分項工程作業計畫。第11條：分析評估方法得參照中央主管機關公告指引或附表二方法。",
 "Construction plans required by the contract must include:",
 ["Project overview, OSH management plan, and work plans for each sub-project","Schedule only","Manpower table only","Materials list only"],
 "Article 10; Article 11 on analysis methods."),

(ED,"第12條",3,"工程安全設計-監督查證",
 "工程業主指派於施工現場監督查證之人員應具何資格？委託之專業機構應置何人員？",
 ["施工安全評估人員或職業安全衛生管理員以上資格且一年以上工程實務經驗；工業安全技師或施工安全評估人員或管理員以上一人及建築師土木結構大地水利水保技師一人","任何員工；任何人","主任即可；一人","不需資格；不需"],"a",
 "第12條：工程業主應指派人員或委託專業機構於施工現場監督並查證施工者依施工計畫書確實採取安全衛生設備措施；指派之人員應具施工安全評估人員或職業安全衛生管理員以上資格並具一年以上工程相關實務經驗；專業機構應置具工業安全技師施工安全評估人員或管理員以上資格者一人及具建築師土木結構大地水利或水保技師資格者一人（同一人具各款資格者得僅置一人）。第13條：應訂定安全衛生監督與查證計畫，包括組織人力、監督查證項目判定基準停留點、假設工程組拆、墜落感電倒塌崩塌局限空間作業、立即危險認定標準情事。第14條：報告紀錄自完工之日起保存三年。",
 "Owner-appointed site supervision and verification personnel must hold, and a commissioned professional agency must staff:",
 ["Construction safety assessor or OSH administrator qualification or higher plus 1 year of project experience; one industrial safety technician/assessor/administrator and one architect or civil, structural, geotechnical, hydraulic or soil-conservation engineer","Any employee; anyone","A foreman; one person","No qualification; none"],
 "Articles 12–14."),

(ED,"第15條",2,"工程安全設計-主施工者",
 "工程業主將工程交付二個以上施工者施工時，應如何指定統合管理者？主施工者應採取何措施？",
 ["以書面或電子文件指定施工者之一為主施工者並要求其他施工者配合；設置統合管理組織指定整體工程場所負責人、連繫調整各施工者設施、巡視督促改善、機械設備人員進場管制、建立緊急應變機制並演練","口頭指定；不需","由勞檢機構指定；巡視即可","不需指定；不需"],"a",
 "第15條：應以書面或電子文件指定施工者之一為主施工者負責整體工程安全衛生統合管理並要求其他施工者配合。第16條：主施工者應依各施工者施工計畫調查工作介面辨識危害評估風險並告知相關施工者。第17條：設置安全衛生統合管理組織並指定整體工程工作場所負責人、連繫與調整各施工者之安全衛生設施及管理、實施巡視並督促改善、執行機械設備器具及人員進場安全管制、建立緊急應變機制並定期演練。第18條：工程業主應編列主施工者統合管理費用納入契約。",
 "When work is awarded to two or more contractors, the owner must designate a principal contractor how, and the principal contractor must:",
 ["In writing or electronically, requiring others to cooperate; set up an integrated management organization with a site manager, coordinate facilities, patrol and enforce corrections, control entry of equipment and personnel, and establish and drill emergency response","Verbally; nothing","Via the inspection agency; patrol only","No designation; nothing"],
 "Articles 15–18."),

(ED,"第19條",3,"工程安全設計-通報",
 "工程業主應於何時依中央主管機關公告方式辦理通報？所稱重大變更係指？",
 ["工程開工前或發生重大變更時；工程金額建築高度開挖深度基地面積橋梁隧道長度變更達原規模百分之五十以上","完工後；任何變更","每月；金額變更百分之十","每年；不需"],"a",
 "第19條：工程業主於工程開工前或工程發生重大變更時應依中央主管機關公告之內容及方式辦理通報；重大變更指工程金額建築高度開挖深度基地面積橋梁或隧道長度變更達原規模百分之五十以上者及其他指定公告之變更。第20條：適用範圍及施行日期如附表三；116年7月1日前已報核符合都更條例規定之都更事業計畫不適用。第21條：自115年7月1日施行。",
 "Project owners must notify the authority when, and a 'major change' means:",
 ["Before commencement or upon a major change; changes of 50% or more in project value, building height, excavation depth, site area, or bridge/tunnel length","After completion; any change","Monthly; 10% value change","Yearly; none"],
 "Article 19; Articles 20–21 on phased application from July 1, 2026."),

# ---------- 勞工作業場所容許暴露標準（114/4/11） ----------
(PEL,"第3條",2,"容許暴露-三種容許濃度",
 "勞工作業場所容許暴露標準所稱「八小時日時量平均容許濃度」係指？",
 ["勞工每天工作八小時，一般勞工重複暴露此濃度以下不致有不良反應之濃度","任何十五分鐘不致有不可忍受刺激之濃度","任何時間均不得超過之濃度","一週平均濃度"],"a",
 "第3條：八小時日時量平均容許濃度指附表一符號欄未註「高」字之濃度，勞工每天工作八小時重複暴露此濃度以下不致有不良反應者；短時間時量平均容許濃度指容許濃度乘以變量係數（未滿1為3、1以上未滿10為2、10以上未滿100為1.5、100以上未滿1000為1.25、1000以上為1）所得，連續暴露任何十五分鐘不致有不可忍受之刺激慢性或不可逆組織病變麻醉昏暈事故增加或效率降低者；最高容許濃度指符號欄註「高」字之濃度，不得使勞工有任何時間超過此濃度之暴露。第2條：附表一未列容許濃度之有害物經測出者視為超過標準。",
 "The '8-hour time-weighted average permissible concentration' means:",
 ["The concentration below which a typical worker repeatedly exposed 8 hours a day suffers no adverse effect","The 15-minute concentration without intolerable irritation","The ceiling never to be exceeded","A weekly average"],
 "Article 3 defines TWA, STEL (TWA × excursion factor from 3 down to 1) and ceiling values; Article 2: listed substances without a limit that are detected count as exceedances."),

(PEL,"第3條",3,"容許暴露-變量係數",
 "容許濃度為 1 以上未滿 10（ppm 或 mg/m³）之有害物，其短時間時量平均容許濃度之變量係數為多少？未滿 1 者？",
 ["2；3","1.5；2","1.25；1.5","1；1"],"a",
 "第3條變量係數表：容許濃度未滿1者係數3、1以上未滿10者2、10以上未滿100者1.5、100以上未滿1000者1.25、1000以上者1；氣狀物以 ppm、粒狀物以 mg/m³、石綿以 f/cc 為單位。",
 "The excursion factor for a substance whose permissible concentration is from 1 to under 10 is, and for under 1:",
 ["2; 3","1.5; 2","1.25; 1.5","1; 1"],
 "Article 3 table: 3, 2, 1.5, 1.25 and 1 by concentration band."),

(PEL,"第5條",2,"容許暴露-單位",
 "容許暴露標準所稱 ppm 係指攝氏幾度、幾大氣壓下每立方公尺空氣中氣狀有害物之立方公分數？f/cc 係指？",
 ["二十五度、一大氣壓；每立方公分纖維根數","零度、一大氣壓；每立方公尺纖維根數","二十度、一大氣壓；每公升根數","三十五度、一大氣壓；每毫升毫克數"],"a",
 "第5條：ppm 為百萬分之一單位，指溫度攝氏二十五度一大氣壓下每立方公尺空氣中氣狀有害物之立方公分數。第6條：mg/m³ 指同條件下每立方公尺空氣中粒狀或氣狀有害物之毫克數。第7條：f/cc 指同條件下每立方公分纖維根數。第4條：時量平均濃度＝各次濃度×工作時間之總和÷總工作時間。",
 "'ppm' in the standards refers to cm³ of gaseous contaminant per m³ of air at what temperature and pressure, and 'f/cc' means:",
 ["25°C, 1 atm; fibers per cubic centimeter","0°C, 1 atm; fibers per cubic meter","20°C, 1 atm; fibers per liter","35°C, 1 atm; mg per mL"],
 "Articles 4–7."),

(PEL,"第8條",2,"容許暴露-三項規定",
 "勞工作業環境空氣中有害物之濃度應符合之規定，下列何者正確？",
 ["全程工作日時量平均不超過八小時日時量平均容許濃度、任何連續十五分鐘時量平均不超過短時間時量平均容許濃度、任何時間不超過最高容許濃度","僅日平均不超過即可","僅最高不超過即可","一週平均不超過即可"],"a",
 "第8條：全程工作日之時量平均濃度不得超過相當八小時日時量平均容許濃度；任何一次連續十五分鐘內之時量平均濃度不得超過短時間時量平均容許濃度；任何時間均不得超過最高容許濃度。",
 "Airborne contaminant concentrations in workplaces must satisfy:",
 ["Full-shift TWA within the 8-hour PEL, any 15-minute TWA within the STEL, and never above the ceiling","Daily average only","Ceiling only","Weekly average only"],
 "Article 8."),

(PEL,"第9條",3,"容許暴露-相加效應",
 "作業環境空氣中有二種以上有害物存在，且其相互效應非屬相乘或獨立效應時，應視為何種效應？如何判定超出容許濃度？",
 ["相加效應；各有害物濃度除以其容許濃度之總和大於一即屬超出","相乘效應；乘積大於一","獨立效應；任一超過","無效應；不需計算"],"a",
 "第9條：二種以上有害物存在而相互間效應非屬相乘效應或獨立效應時應視為相加效應，總和＝甲濃度/甲容許濃度＋乙濃度/乙容許濃度＋……，總和大於一即屬超出容許濃度。第10條：本標準不適用於以二種有害物容許濃度比作為毒性指標、工作場所以外之空氣污染指標、職業疾病鑑定之唯一依據。",
 "When two or more contaminants coexist without synergistic or independent effects, they are treated as, and exceedance is determined by:",
 ["Additive; the sum of each concentration divided by its limit exceeding 1","Synergistic; the product exceeding 1","Independent; any single exceedance","No effect; no calculation"],
 "Article 9; Article 10 lists three uses the standard is not meant for."),

(PEL,"第11條",3,"容許暴露-施行",
 "勞工作業場所容許暴露標準 114 年 4 月 11 日修正之附表一編號十五、二百十一、四百四十五及附表二，自何時施行？",
 ["116 年 1 月 1 日","114 年 4 月 11 日","115 年 1 月 1 日","114 年 7 月 1 日"],"a",
 "第11條：本標準自103年7月3日施行；107年3月14日修正之附表一編號四、四十三、二百三十一、四百七十七自107年7月1日施行；114年4月11日修正發布之附表一編號十五、二百十一、四百四十五及附表二自116年1月1日施行，其餘自發布日施行。",
 "The April 11, 2025 amendments to specified entries of Table 1 and to Table 2 take effect on:",
 ["January 1, 2027","April 11, 2025","January 1, 2026","July 1, 2025"],
 "Article 11."),

# ---------- 勞工作業環境監測實施辦法（115/6/12） ----------
(EM,"第2條",2,"環測-用詞",
 "勞工作業環境監測實施辦法所稱「臨時性作業」「作業時間短暫」「作業期間短暫」各指？",
 ["正常作業以外期間不超過三個月且一年內不再重複；每日作業一小時以內；作業期間不超過一個月且終了後六個月內不再實施","一週內；半小時；一週","一年內；二小時；三個月","不定義；不定義；不定義"],"a",
 "第2條：監測機構指經中央主管機關認可辦理採樣測定分析之機構；臨時性作業指正常作業以外期間不超過三個月且一年內不再重複者；作業時間短暫指每日作業時間在一小時以內；作業期間短暫指作業期間不超過一個月且確知終了日起六個月不再實施；暴露評估指運用採樣策略及統計方法分析監測數據並與容許暴露標準比較；第三者認證機構指取得國際實驗室認證聯盟相互認可協議並經公告者；認證實驗室指經認證合格於有效期間內辦理化驗分析之機構。",
 "'Temporary work', 'short working time' and 'short work period' mean:",
 ["Non-routine work not over 3 months and not repeated within a year; daily work of 1 hour or less; work not over 1 month and not repeated within 6 months after ending","Within a week; half an hour; a week","Within a year; 2 hours; 3 months","Undefined"],
 "Article 2."),

(EM,"第4條",3,"環測-監測人員",
 "甲級化學性因子作業環境監測人員應領有下列何種文件之一？",
 ["職業衛生技師證書、化學性因子作業環境監測甲級技術士證照、或中央主管機關發給之作業環境測定服務人員證明並接受講習","乙級技術士證照","職業安全衛生管理員證","急救人員證"],"a",
 "第4條：甲級化學性因子監測人員為領有職業衛生技師證書、化學性因子作業環境監測甲級技術士證照、或中央主管機關發給之作業環境測定服務人員證明並接受講習者之一；甲級物理性因子監測人員類似（物理性甲級技術士）；乙級化學性或物理性監測人員為領有乙級技術士證照者。第3條：化學性因子監測指第5條第1項第1、2款第6條等，物理性因子指噪音及綜合溫度熱指數等。",
 "Class A chemical-factor monitoring personnel must hold one of:",
 ["An occupational hygienist license, a Class A chemical-factor monitoring technician certificate, or a ministry-issued monitoring service certificate with training","A Class B technician certificate","An OSH administrator certificate","A first-aid certificate"],
 "Article 4."),

(EM,"第5條",2,"環測-基本監測",
 "設有中央管理方式空氣調節設備之建築物室內作業場所，應每幾個月監測二氧化碳濃度一次以上？噪音暴露八小時日時量平均音壓級達幾分貝以上之作業場所應每幾個月監測噪音一次？",
 ["六個月；八十五分貝；六個月","三個月；九十分貝；三個月","一年；八十分貝；一年","一個月；八十五分貝；一個月"],"a",
 "第5條：設有中央管理方式空調之建築物室內作業場所每六個月監測二氧化碳一次以上（已依室內空氣品質管理法檢測者得免）；礦場地下試掘採掘、隧道掘削及已完工可通行之地下通道等坑內作業場所每六個月監測粉塵二氧化碳一次以上；噪音暴露工作日八小時日時量平均音壓級八十五分貝以上之作業場所每六個月監測噪音一次以上；臨時性作業作業時間短暫或作業期間短暫者除外。",
 "Indoor workplaces with central air conditioning must monitor CO₂ at least every, and workplaces with 8-hour TWA noise of at least what level must monitor noise every:",
 ["6 months; 85 dB; 6 months","3 months; 90 dB; 3 months","1 year; 80 dB; 1 year","1 month; 85 dB; 1 month"],
 "Article 5, with exemptions for temporary or short work."),

(EM,"第6條",3,"環測-化學性因子頻率",
 "高溫作業場所應每幾個月監測綜合溫度熱指數一次以上？有機溶劑、特定化學物質、鉛、粉塵等作業場所原則每幾個月監測一次？勞工暴露濃度高於或等於容許濃度者？",
 ["三個月；六個月；每三個月","一個月；三個月；每月","六個月；一年；每六個月","每週；每月；每週"],"a",
 "第6條：高溫作業場所每三個月監測綜合溫度熱指數一次以上；特定粉塵作業場所粉塵濃度、有機溶劑作業場所附表一項目、特定化學物質作業場所附表二項目、煉焦爐生成物、鉛作業場所鉛濃度、四烷基鉛作業場所濃度，每六個月監測一次以上，但勞工暴露濃度高於或等於容許暴露標準所定容許濃度者應每三個月一次以上；指定業別之特定粉塵作業場所應增列結晶型游離二氧化矽；監測對象採樣數量頻率依中央主管機關公告方式辦理。",
 "Hot-work sites must monitor WBGT at least every, chemical-factor sites (solvents, specified chemicals, lead, dust) every, and every how often when exposure meets or exceeds the PEL:",
 ["3 months; 6 months; 3 months","1 month; 3 months; monthly","6 months; 1 year; 6 months","Weekly; monthly; weekly"],
 "Article 6."),

(EM,"第7條",3,"環測-免監測與評估",
 "下列何種情形雇主得不依第6條實施作業環境監測？引進或修改製程材料設備時應如何？評估紀錄保存幾年？",
 ["臨時性作業作業時間或期間短暫且經評估不致超過短時間或最高容許濃度、化學品僅作貯存且無暴露之虞；應評估暴露風險，有增加之虞即實施監測；三年","所有情形；不需；一年","從無例外；不需；十年","勞工少於五人；不需；五年"],"a",
 "第7條：屬臨時性作業作業時間短暫或作業期間短暫且經評估不致暴露超出短時間時量平均或最高容許濃度、或化學品僅作貯存用途且無暴露危害之虞者得不實施；引進或修改製程作業程序材料設備時應評估暴露風險，有增加之虞者應即實施監測；評估應運用採樣分析定量推估模式直讀式儀器或其他科學方法並作成紀錄保存三年。第8條：採樣分析方法參照勞研所等建議方法，評估短時間或最高暴露確有困難者得以直讀式儀器監測。",
 "Which situations exempt an employer from Article 6 monitoring, what is required when processes or materials change, and how long are assessment records kept?",
 ["Temporary/short work assessed not to exceed the STEL or ceiling, or chemicals only stored with no exposure risk; assess exposure risk and monitor immediately if it may rise; 3 years","All situations; nothing; 1 year","No exemption; nothing; 10 years","Fewer than 5 workers; nothing; 5 years"],
 "Articles 7–8."),

(EM,"第9條",2,"環測-監測計畫",
 "作業環境監測計畫應包括哪些事項？應於實施監測幾日前通報中央主管機關？",
 ["監測目的、危害辨識及資料收集、相似暴露族群之建立、採樣策略之規劃及執行、樣本分析、數據分析及暴露評估；十日前","僅採樣點；當日","僅監測機構名稱；三十日前","僅費用；不需通報"],"a",
 "第9條：雇主應就作業環境危害特性監測目的及公告指引規劃採樣策略並訂定含採樣策略之監測計畫確實執行並檢討更新；計畫應包括監測目的、危害辨識及資料收集、相似暴露族群之建立、採樣策略之規劃及執行、樣本分析、數據分析及暴露評估；應於作業勞工顯而易見處公告或公開揭示，必要時向勞工代表說明；應於實施監測十日前通報中央主管機關（依第7條第2項辦理者得於監測後七日內通報）。",
 "The monitoring plan must include, and be reported to the central authority how many days before monitoring?",
 ["Purpose, hazard identification and data collection, similar exposure groups, sampling strategy, sample analysis, data analysis and exposure assessment; 10 days","Sampling points only; same day","Agency name only; 30 days","Cost only; no report"],
 "Article 9."),

(EM,"第10條",3,"環測-監測評估小組",
 "從事特別危害健康作業勞工人數在幾人以上，或應實施化學性因子監測且勞工人數幾人以上之事業單位，其監測計畫應由監測評估小組研訂？小組成員包括？",
 ["一百人以上；三百人以上；工作場所負責人、職安衛人員、受委託之執業職業衛生技師、作業主管及其他必要人員","五十人；一百人；僅雇主","三百人；五百人；僅技師","十人；三十人；僅勞工代表"],"a",
 "第10條：從事特別危害健康作業勞工一百人以上或依第6條應實施化學性因子監測且勞工三百人以上者，監測計畫應由工作場所負責人、職業安全衛生人員、受委託之執業職業衛生技師、工作場所作業主管及其他必要人員組成之監測評估小組研訂；技師應會同職安衛人員協助完成暴露評估報告並提供相似暴露族群劃分採樣策略等建議；執行情形應由成員共同簽名依附表三記錄保存三年；技師不得為監測機構人員且須經附表五課程訓練合格。",
 "Enterprises with at least how many workers in specially hazardous work, or requiring chemical monitoring with at least how many workers, need a monitoring assessment team, composed of:",
 ["100; 300; the workplace head, OSH personnel, a commissioned occupational hygienist, work supervisors and others as needed","50; 100; the employer only","300; 500; the hygienist only","10; 30; labor representatives only"],
 "Article 10."),

(EM,"第11條",3,"環測-自行監測",
 "雇主實施作業環境監測原則應設置或委託監測機構辦理，但下列何種項目得僱用乙級以上監測人員或委託執業職業衛生技師辦理？",
 ["物理性因子，或得以直讀式儀器有效監測之二氧化碳、二硫化碳、二氯聯苯胺及其鹽類、次乙亞胺、二異氰酸甲苯、硫化氫、汞及其無機化合物等","所有化學性因子","石綿","結晶型游離二氧化矽"],"a",
 "第11條：監測項目屬物理性因子或得以直讀式儀器有效監測之二氧化碳、二硫化碳、二氯聯苯胺及其鹽類、次乙亞胺、二異氰酸甲苯、硫化氫、汞及其無機化合物及其他指定者，得僱用乙級以上監測人員或委託執業職業衛生技師辦理；測定儀器設備應符合附表七。第14條：以直讀式儀器監測二氧化碳者免通報計畫及結果。",
 "Employers may use their own Class B+ monitoring staff or a commissioned hygienist instead of an accredited agency for:",
 ["Physical factors, or direct-reading-instrument measurable chemicals such as CO₂, CS₂, dichlorobenzidine, ethyleneimine, TDI, H₂S, mercury and inorganic compounds","All chemical factors","Asbestos","Crystalline silica"],
 "Article 11; Article 14 exempts CO₂ direct-reading monitoring from reporting."),

(EM,"第12條",2,"環測-結果通報",
 "雇主實施作業環境監測應會同何人實施？監測結果應於採樣或測定後幾日內通報中央主管機關？",
 ["職業安全衛生人員及勞工代表；四十五日內","監測機構；三十日內","勞檢機構；七日內","醫師；九十日內"],"a",
 "第12條：訂定監測計畫及實施監測時應會同職業安全衛生人員及勞工代表實施；監測結果應依附表五記錄並於作業勞工顯而易見處公告或公開揭示，必要時向勞工代表說明；應於採樣或測定後四十五日內將監測結果通報中央主管機關；計畫及結果依公告方法登錄於指定資訊網站。第15條：得以書面委託監測機構辦理通報。",
 "Monitoring must be carried out together with whom, and results reported to the central authority within how many days of sampling?",
 ["OSH personnel and labor representatives; 45 days","The monitoring agency; 30 days","The inspection agency; 7 days","A physician; 90 days"],
 "Article 12; Article 15 allows written delegation of reporting."),

(EM,"第13條",3,"環測-暴露評估報告",
 "雇主應於採樣或測定後幾日內完成暴露評估報告？監測結果及暴露評估報告應保存幾年？附表六所列化學物質者？",
 ["九十日；十年；三十年","四十五日；三年；十年","三十日；五年；二十年","六十日；十年；十年"],"a",
 "第13條：應依監測計畫各事項之執行情形及評估改善建議於採樣或測定後九十日內完成暴露評估報告；監測結果及暴露評估報告應保存十年，屬附表六所列化學物質者保存三十年。",
 "Exposure assessment reports are due within how many days of sampling, and results and reports are kept for, or for listed chemicals:",
 ["90 days; 10 years; 30 years","45 days; 3 years; 10 years","30 days; 5 years; 20 years","60 days; 10 years; 10 years"],
 "Article 13."),

(EM,"第16條",3,"環測-頻率放寬",
 "雇主實施化學性因子監測，符合何條件且經中央主管機關審查通過者，得不受監測頻率限制？審查通過有效期間最長幾年？",
 ["連續二年以上整體暴露評估結果低於容許濃度二分之一且半數以上相似暴露族群低於十分之一，或製程特殊採密閉設備無法反映實際暴露者；三年","一年低於容許濃度；一年","從未超標；五年","勞工同意；十年"],"a",
 "第16條：連續二年以上整體暴露評估結果低於容許濃度二分之一且半數以上相似暴露族群暴露評估結果低於容許濃度十分之一、或作業場所因製程特殊採密閉設備依現行方式無法反映實際暴露者，其監測管理成效經中央主管機關審查通過得不受頻率限制；仍應每年採必要措施確認自主管理有效性；有效期間最長三年，期滿前三十日至九十日間申請展延。第17條：規劃及暴露評估得委託執業職業衛生技師或具暴露評估技術服務類別之顧問機構辦理。",
 "Employers may be released from chemical monitoring frequency requirements when, with approval valid for at most:",
 ["Two consecutive years of overall exposure below half the PEL with over half of SEGs below one-tenth, or enclosed special processes that monitoring cannot reflect; 3 years","One year below the PEL; 1 year","Never exceeded; 5 years","Workers agree; 10 years"],
 "Article 16; Article 17 on outsourcing planning and assessment."),

(EM,"第18條",3,"環測-監測機構資格",
 "作業環境監測機構應具備之資格條件為何？",
 ["必要之採樣測定儀器設備、甲級監測人員三人以上或執業職業衛生技師一人以上、專屬之認證實驗室（符合 CNS 17025 或 ISO/IEC 17025）","一名乙級人員即可","任何實驗室","僅需公司登記"],"a",
 "第18條：監測機構應具備附表七之必要採樣及測定儀器設備、甲級監測人員三人以上或執業職業衛生技師一人以上、專屬之認證實驗室（符合 CNS17025 或 ISO/IEC17025 及公告之實驗室認證規範）。第19條：化驗分析類別為有機化合物、無機化合物、石綿等礦物性纖維、結晶型游離二氧化矽等礦物性粉塵、粉塵重量分析等。第22條：認可有效期間最長三年，屆滿前三十日至六十日間重新申請。",
 "An accredited monitoring agency must have:",
 ["Required sampling and measuring equipment, at least three Class A monitoring personnel or one licensed occupational hygienist, and a dedicated accredited laboratory (CNS 17025 / ISO/IEC 17025)","One Class B technician","Any laboratory","Only a business registration"],
 "Articles 18–19; Article 22: accreditation valid up to 3 years."),

(EM,"第25條",3,"環測-行程通報",
 "監測機構於執行作業環境監測幾日前，應將預定行程向中央主管機關通報？有特殊原因變更者至遲幾小時前？監測人員每年講習訓練不得低於幾小時？",
 ["五日前；二十四小時前；十二小時","一日前；一小時前；六小時","十日前；四十八小時前；二十四小時","三十日前；七日前；三小時"],"a",
 "第25條：監測人員應親自執行監測業務；監測機構應於執行監測五日前將預定行程向中央主管機關通報，特殊原因須變更者至遲於執行前二十四小時通報。第26條：應訂定管理手冊並依內容記載，紀錄文件保存三年。第27條：監測人員及第10條之技師每年參加認可講習訓練不得低於十二小時。第24條：負責人地址聯絡方式監測人員儀器設備認證實驗室有效期間及類別變更應於十五日內通知（監測人員得三十日內）。",
 "Monitoring agencies must report scheduled monitoring itineraries at least how many days ahead, changes at least how many hours ahead, and staff need at least how many hours of annual training?",
 ["5 days; 24 hours; 12 hours","1 day; 1 hour; 6 hours","10 days; 48 hours; 24 hours","30 days; 7 days; 3 hours"],
 "Articles 24–27."),

(EM,"第31條",3,"環測-機構處罰",
 "作業環境監測機構有下列何種情形，依職安法第48條處以罰鍰並得限期改正？",
 ["指派未具資格人員監測、申請文件或監測紀錄虛偽不實、實施監測時規避正常作業情形或高暴露場所、未依監測計畫實施情節重大等","僅未貼公告","僅遲交報告一天","僅名片格式錯誤"],"a",
 "第31條：指派未具第4條資格之監測人員、申請認可文件或監測紀錄虛偽不實、監測計畫或結果未依第15條第3項通報、未依認可類別辦理、未依第23條申請停止業務、查核應改善事項未改正、實施監測時規避正常作業情形或高暴露場所、未依監測計畫內容實施情節重大、未依第30條改正者，處以罰鍰並得限期改正。第30條：採樣分析方法未依規定、結果未依附表五記錄、變更未通知、行程未通報、未訂管理手冊等予以警告。第32條：屆期未改正或情節重大者得撤銷廢止認可或停止業務，二年內不得以同一名稱地點或負責人申請。第29條：雇主資料顯然錯誤、監測計畫未依第10條、未會同、報告未依第13條、儀器不符者，經限期改正未改正處罰鍰。",
 "Which agency conduct is fined under Article 48 of the OSH Act with an order to correct?",
 ["Assigning unqualified personnel, falsifying application documents or records, avoiding normal operating conditions or high-exposure areas during monitoring, or seriously departing from the monitoring plan","Missing a poster only","A report one day late only","A wrong business card format"],
 "Article 31; Article 30 warnings; Article 32 revocation; Article 29 employer penalties."),
]
