# -*- coding: utf-8 -*-
# 第 11 批（M1）：鉛中毒預防規則（補題，涵蓋全部未出題條文）
A = "OSH-39"
Q = [

(A,"第1條",1,"鉛中毒-授權依據",
 "鉛中毒預防規則係依據下列何項法律規定訂定之？",
 ["依職業安全衛生法第六條第三項規定訂定之","依職業安全衛生法第五條第二項規定訂定之","依職業安全衛生法第十九條第二項規定訂定","依勞工健康保護規則第六條第三項規定訂定"],"a",
 "第1條：本規則依職業安全衛生法第六條第三項規定訂定之。第2條並定明本規則適用於從事鉛作業之有關事業，並列舉十八款鉛作業。第50條則定明施行日期。",
 "Which statutory provision is the legal basis of the Lead Poisoning Prevention Rules?",
 ["Article 6, paragraph 3 of the Occupational Safety and Health Act","Article 5, paragraph 2 of the Occupational Safety and Health Act","Article 19, paragraph 2 of the Occupational Safety and Health Act","Article 6, paragraph 3 of the Labor Health Protection Rules"],
 "Article 1 cites Article 6, paragraph 3 of the Act."),

(A,"第4條",1,"鉛中毒-條文沿革",
 "鉛中毒預防規則第四條之現行狀態及其原規範事項現由何規定承接？",
 ["該條已刪除，相關事項改依其後條文指引之勞工健康保護規則等法規辦理","該條仍屬有效，明定雇主應每年實施特殊健康檢查一次以上並記錄","該條仍屬有效，明定雇主應每三個月實施作業環境監測一次以上","該條已移列於附則章，明定本規則自發布後滿六個月之日起施行"],"a",
 "第4條已刪除。健康管理、作業環境監測、妊娠與分娩後女性勞工及未滿十八歲勞工保護與入槽安全等事項，改由第4條之1指引依勞工健康保護規則、勞工作業環境監測實施辦法、缺氧症預防規則及職業安全衛生設施規則等辦理。",
 "What is the current status of Article 4 and where are its former matters now governed?",
 ["It has been deleted; those matters now follow the health protection and monitoring regulations cited later","It remains in force and requires a special health examination at least once every year","It remains in force and requires workplace environmental monitoring once every three months","It was moved to the supplementary chapter setting an effective date six months after promulgation"],
 "Article 4 was deleted; Article 4-1 now points to other regulations."),

(A,"第4條之1",2,"鉛中毒-準用法規",
 "雇主使勞工從事鉛作業，對於健康管理、作業環境監測、妊娠與分娩後女性勞工保護及入槽安全等事項，應依何規定辦理？",
 ["應依勞工健康保護規則、勞工作業環境監測實施辦法、缺氧症預防規則及職業安全衛生設施規則局限空間等規定","應依職業安全衛生管理辦法、危害性化學品標示及通識規則及高溫作業勞工作息時間標準等相關法令之規定","應依特定化學物質危害預防標準及粉塵危害預防標準所定之健康檢查與入槽作業等相關規定辦理即為已足","應由雇主自行訂定鉛作業管理計畫，報請當地勞動檢查機構核備後辦理，不受其他相關法規規定之限制"],"a",
 "第4條之1：健康管理、作業環境監測、妊娠與分娩後女性勞工及未滿十八歲勞工保護與入槽安全等事項，應依勞工健康保護規則、勞工作業環境監測實施辦法、妊娠與分娩後女性及未滿十八歲勞工禁止從事危險性或有害性工作認定標準、缺氧症預防規則及職業安全衛生設施規則所定局限空間作業等規定辦理。",
 "Which regulations govern health management, monitoring, protection of women and tank entry safety?",
 ["The Labor Health Protection Rules, monitoring regulations, oxygen deficiency rules and confined space provisions","The safety and health management regulations, hazard communication rules and high temperature work hour standards","Only the specified chemicals standard and the dust hazard prevention standard on examinations and tank entry","The employer sets its own plan, files it with the inspection agency, and is exempt from other regulations"],
 "Article 4-1 refers to five other sets of regulations."),

(A,"第5條",2,"鉛中毒-冶煉設施",
 "鉛之冶煉、精煉過程中，從事焙燒、燒結、熔融、鑄造、烘燒之作業場所，與非以濕式作業從事軋碎、研磨、混合或篩選之室內作業場所，應分別設置何種設備？",
 ["前者應設置局部排氣裝置；後者應設置密閉設備或局部排氣裝置","前者應設置整體換氣裝置；後者應設置局部排氣裝置或水霧設備","前者應設置密閉設備即可；後者僅需設置整體換氣裝置或噴水設備","前者應設置吹吸型換氣裝置；後者應設置整體換氣裝置及承受容器"],"a",
 "第5條第1款：鉛之冶煉、精煉過程中之焙燒、燒結、熔融、鑄造、烘燒等作業場所應設置局部排氣裝置。第2款：非以濕式作業從事軋碎、研磨、混合或篩選之室內作業場所，應設置密閉設備或局部排氣裝置。第20條並要求第2款、第3款之氣罩原則採包圍型。",
 "What controls are required for roasting and melting sites, and for non wet crushing or screening indoors?",
 ["The former needs local exhaust ventilation; the latter needs an enclosure or local exhaust ventilation","The former needs dilution ventilation; the latter needs local exhaust ventilation or a water mist","The former only needs an enclosure; the latter only needs dilution ventilation or a water spray","The former needs push pull ventilation; the latter needs dilution ventilation and a receiving vessel"],
 "Article 5, subparagraphs 1 and 2."),

(A,"第5條",3,"鉛中毒-冶煉設施",
 "鉛之冶煉、精煉作業中，臨時儲存燒結礦混存物、熔融鑄造作業場所及非以濕式將粉狀物倒入漏斗時，應分別設置何者？",
 ["臨時儲存應設儲存場所或容器；熔融鑄造場所應設儲存浮渣容器；倒入漏斗應設局部排氣裝置及承受溢流設備","臨時儲存應設密閉設備或水槽；熔融鑄造場所應設整體換氣裝置；倒入漏斗應設吹吸型換氣裝置及集塵設備","臨時儲存應設專用隔離倉庫；熔融鑄造場所應設儲存切屑容器；倒入漏斗應設密閉設備並一律採濕式作業","臨時儲存應加蓋防水帆布覆蓋；熔融鑄造場所應設置淋浴設備；倒入漏斗應設整體換氣裝置及承受溢流設備"],"a",
 "第5條第3款至第5款：非以濕式將粉狀之鉛、鉛混存物、燒結礦混存物倒入漏斗、容器、軋碎機或自其取出時，應設局部排氣裝置及承受溢流之設備；臨時儲存燒結礦混存物應設儲存場所或容器；熔融、鑄造作業場所應設儲存浮渣之容器。",
 "What must be provided for temporary storage, for melting and casting sites, and when pouring powder into hoppers?",
 ["A storage place or container; a vessel for dross; local exhaust ventilation plus an overflow receiving device","An enclosure or water tank; dilution ventilation; push pull ventilation plus a dust collecting device","A dedicated isolated warehouse; a vessel for scrap chips; an enclosure with mandatory wet working","A waterproof tarpaulin cover; shower facilities; dilution ventilation plus an overflow receiving device"],
 "Article 5, subparagraphs 3 to 5."),

(A,"第6條",2,"鉛中毒-銅鋅冶煉設施",
 "含鉛重量百分之三以上之銅或鋅冶煉、精煉作業中，以鼓風爐或電解漿泥熔融爐從事冶煉、熔融或煙灰段燒之作業場所，應設置何種設備？",
 ["應設置局部排氣裝置，以強制吸引並排出已發散之鉛塵","應設置整體換氣裝置，以動力稀釋已發散之鉛塵即可","應設置密閉設備並輔以水霧噴灑，抑制鉛塵向外發散","應設置吹吸型換氣裝置，並於爐口加設承受溢流設備"],"a",
 "第6條第1款：以鼓風爐或電解漿泥熔融爐從事冶煉、熔融或煙灰之段燒作業場所，應設置局部排氣裝置。第2條第2項第2款所定作業，係指含鉛重量在百分之三以上之銅或鋅冶煉、精煉過程中，轉爐連續熔融時處理煙灰或電解漿泥之作業。",
 "What control is required where a blast furnace or electrolytic sludge furnace is used for smelting or fume roasting?",
 ["Local exhaust ventilation that forcibly draws in and discharges the dispersed lead dust","Dilution ventilation that uses power to dilute the lead dust already dispersed","An enclosure supplemented by water mist spraying to suppress dust dispersion","Push pull ventilation with an overflow receiving device added at the furnace mouth"],
 "Article 6, subparagraph 1."),

(A,"第6條",3,"鉛中毒-銅鋅冶煉設施",
 "含鉛之銅或鋅冶煉作業中，非以濕式方式將煙灰、電解漿泥倒入漏斗或自其取出、臨時儲存煙灰電解漿泥、以電解漿泥熔融爐熔融，應分別如何處置？",
 ["倒入取出應設局部排氣裝置及承受溢流設備；臨時儲存應設儲存場所或容器；熔融場所應有儲存浮渣容器","倒入取出應設密閉設備及水霧噴灑設備；臨時儲存應設冷卻水槽；熔融場所應有儲存切屑之專用容器","倒入取出應設整體換氣裝置及集塵設備；臨時儲存應設露天堆置區；熔融場所應有防止飛散之隔離牆","倒入取出應設吹吸型換氣裝置及淋浴設備；臨時儲存應加以覆蓋；熔融場所應有承受溢流之專用設備"],"a",
 "第6條第3款至第5款：非以濕式作業方式將煙灰、電解漿泥倒入漏斗、容器、軋碎機等或自其中取出之室內作業場所，應設局部排氣裝置及承受溢流之設備；臨時儲存煙灰、電解漿泥時應設儲存場所或容器；以電解漿泥熔融爐從事熔融之作業場所，應有儲存浮渣之容器。",
 "What is required when pouring fume or sludge, for temporary storage, and at electrolytic sludge melting sites?",
 ["Local exhaust plus an overflow receiving device; a storage place or container; a vessel for dross","An enclosure plus water mist spraying; a cooling water tank; a dedicated vessel for scrap chips","Dilution ventilation plus dust collection; an open air stacking yard; an isolating wall against scatter","Push pull ventilation plus showers; a simple cover; a dedicated overflow receiving device"],
 "Article 6, subparagraphs 3 to 5."),

(A,"第8條",2,"鉛中毒-鉛合金製品設施",
 "從事鉛合金製造或鉛快削鋼注鉛作業時，對於室內熔融、被覆、鑄造、熔鉛噴布等作業場所及切屑之暫時儲存，應如何辦理？",
 ["室內作業場所應設局部排氣裝置；暫時儲存切屑應設置儲存切屑之容器","室內作業場所應設整體換氣裝置；暫時儲存切屑應以防水帆布加以覆蓋","室內作業場所應設密閉設備即可；暫時儲存切屑應設置儲存浮渣之容器","室內作業場所應設吹吸型換氣裝置；暫時儲存切屑應堆置於室外指定區"],"a",
 "第8條第1款：從事鉛或鉛合金之熔融、被覆、鑄造、熔鉛噴布、熔接、熔斷及以動力切斷、加工或鉛快削鋼注鉛之室內作業場所，應設置局部排氣裝置。第2款：暫時儲存鉛或鉛合金之切屑時，應設置儲存切屑之容器；第3款另定熔融、鑄造作業場所應設儲存浮渣之容器。",
 "For indoor melting and casting of lead alloys and for temporary storage of chips, what is required?",
 ["Local exhaust ventilation indoors; a container provided for storing the chips","Dilution ventilation indoors; a waterproof tarpaulin covering over the chips","Only an enclosure indoors; a vessel for storing dross provided for the chips","Push pull ventilation indoors; outdoor stacking of the chips at a set area"],
 "Article 8, subparagraphs 1 and 2."),

(A,"第9條",2,"鉛中毒-電線電纜設施",
 "電線、電纜製造過程中從事鉛之熔融、被覆、剝除等作業，其室內熔融作業場所及地面構造應如何設置？",
 ["應設局部排氣裝置及儲存浮渣之容器；地面應為易於使用真空除塵機或以水清除之構造","應設整體換氣裝置及儲存切屑之容器；地面應為易於使用掃帚乾式清掃作業之構造","應設密閉設備及承受溢流之設備；地面應鋪設吸油棉並以有機溶劑定期擦拭之構造","應設吹吸型換氣裝置及淋浴設備；地面應為具有排水坡度且鋪設木質格柵板之構造"],"a",
 "第9條：雇主使勞工從事第2條第2項第5款之作業時，從事鉛之熔融室內作業場所應設置局部排氣裝置及儲存浮渣之容器；室內作業場所之地面，應為易於使用真空除塵機或以水清除之構造。第36條並要求每日以水沖洗或真空除塵清潔作業場所一次以上。",
 "For indoor lead melting in cable manufacture, what equipment and floor construction are required?",
 ["Local exhaust ventilation and a vessel for dross; floors easily cleaned by vacuum cleaner or water","Dilution ventilation and a vessel for scrap chips; floors suited to dry sweeping with a broom","An enclosure and an overflow receiving device; floors covered with pads wiped by organic solvent","Push pull ventilation and shower facilities; sloped floors laid with wooden grating panels"],
 "Article 9, subparagraphs 1 and 2."),

(A,"第10條",2,"鉛中毒-鉛化合物製造",
 "鉛化合物、鉛混合物製造過程中，從事熔融、鑄造段燒及烘燒之室內作業場所，與從事冷卻攪拌之室內作業場所，應分別設置何種設備？",
 ["前者應設局部排氣裝置；後者應設密閉設備或局部排氣裝置","前者應設整體換氣裝置；後者應設吹吸型換氣裝置或水簾","前者應設密閉設備即可；後者應設整體換氣裝置或噴霧設備","前者應設吹吸型換氣裝置；後者應設承受溢流設備或水槽"],"a",
 "第10條第1款：從事鉛、鉛混存物之熔融、鑄造段燒及烘燒之室內作業場所，應設置局部排氣裝置。第2款：從事鉛或鉛混存物冷卻攪拌之室內作業場所，應設置密閉設備或局部排氣裝置。第3款另定熔融、鑄造作業場所應設儲存浮渣之容器。",
 "What controls apply to indoor melting and roasting sites, and to indoor cooling and stirring sites?",
 ["The former needs local exhaust ventilation; the latter needs an enclosure or local exhaust","The former needs dilution ventilation; the latter needs push pull ventilation or a water curtain","The former only needs an enclosure; the latter needs dilution ventilation or spray equipment","The former needs push pull ventilation; the latter needs an overflow device or a water tank"],
 "Article 10, subparagraphs 1 and 2."),

(A,"第10條",3,"鉛中毒-鉛化合物製造",
 "鉛化合物製造過程中，以人工搬運裝有粉狀鉛之容器時，為避免搬運勞工遭受污染，應採取何種措施？室內地面構造有何要求？",
 ["容器上應裝設把手或車輪，或置備專門運送該容器之車輛；地面應易於使用真空除塵機或以水清除","容器上應加設雙層密封蓋並張貼危害標示，且限二人共同搬運；地面應鋪設具吸附功能之地毯材質","容器應先以塑膠布包覆並置於推車上由主管全程陪同搬運；地面應設置排水溝並保持經常濕潤狀態","容器應以堆高機吊掛移動且禁止人力接觸容器外壁；地面應以環氧樹脂塗布並每週打蠟保養一次"],"a",
 "第10條第6款：以人工搬運裝有粉狀之鉛、鉛混存物之容器，為避免搬運勞工被污染，應於該容器上裝設把手或車輪，或置備有專門運送該容器之車輛。第7款：室內作業場所之地面，應為易於使用真空除塵機或以水清除之構造。",
 "How must containers of powdered lead be handled when carried manually, and what floor construction is required?",
 ["Fit handles or wheels to the container, or provide a dedicated cart; floors cleanable by vacuum or water","Add a double sealed lid and hazard labels and require two carriers; floors laid with absorbent carpet","Wrap the container in plastic on a trolley escorted by a supervisor; floors with drains kept always wet","Move containers only by forklift with no hand contact; floors coated with epoxy and waxed weekly"],
 "Article 10, subparagraphs 6 and 7."),

(A,"第11條",2,"鉛中毒-襯墊上光作業",
 "從事鉛之襯墊及表面上光作業時，對於室內熔融、熔接、熔斷、熔鉛噴布或真空作業等塗布及表面上光作業場所，應如何設置？",
 ["應設置局部排氣裝置；熔融作業場所並應設置儲存浮渣之容器","應設置整體換氣裝置；熔融作業場所並應設置儲存切屑容器","應設置密閉設備即可；熔融作業場所並應設置承受溢流之設備","應設置吹吸型換氣裝置；熔融作業場所並應設置淋浴盥洗設備"],"a",
 "第11條：雇主使勞工從事第2條第2項第8款之作業時，從事鉛、鉛混存物之熔融、熔接、熔斷、熔鉛噴布或真空作業等塗布及表面上光之室內作業場所，應設置局部排氣裝置；從事熔融作業場所應設置儲存浮渣之容器。",
 "What is required at indoor lining and surface glazing sites involving lead melting and spraying?",
 ["Local exhaust ventilation, plus a vessel for storing dross at the melting site","Dilution ventilation, plus a vessel for storing scrap chips at the melting site","Only an enclosure, plus an overflow receiving device at the melting site","Push pull ventilation, plus shower and washing facilities at the melting site"],
 "Article 11, subparagraphs 1 and 2."),

(A,"第12條",3,"鉛中毒-塗料釉藥製造",
 "含鉛塗料、釉藥、農藥、玻璃等製造過程中，從事鉛之熔融或鑄注、軋碎、非以濕式研磨混合篩選之作業，應分別如何辦理？",
 ["熔融鑄注應設局部排氣裝置及浮渣容器；軋碎應與其他作業場所隔離；研磨混合篩選應設密閉設備或局排","熔融鑄注應設整體換氣裝置及切屑容器；軋碎應採密閉設備隔離；研磨混合篩選應設吹吸型換氣裝置","熔融鑄注應設密閉設備及承受容器；軋碎應設整體換氣裝置；研磨混合篩選應與休息室隔離並設淋浴","熔融鑄注應設吹吸型換氣裝置及水槽；軋碎應設局部排氣裝置；研磨混合篩選應一律改採濕式作業方法"],"a",
 "第12條：從事鉛、鉛混存物熔融或鑄注之室內作業場所，應設局部排氣裝置及儲存浮渣之容器；從事軋碎之作業場所，應與其他作業場所隔離；非以濕式作業從事研磨、混合、篩選之室內作業場所，應設密閉設備或局部排氣裝置。第20條並要求第3款氣罩原則採包圍型。",
 "How must melting, crushing, and non wet grinding or screening be handled in paint and glaze manufacture?",
 ["Local exhaust and a dross vessel; crushing isolated from other sites; enclosure or local exhaust for grinding","Dilution ventilation and a chip vessel; crushing isolated by enclosure; push pull ventilation for grinding","An enclosure and a receiving vessel; dilution ventilation for crushing; grinding isolated with showers","Push pull ventilation and a tank; local exhaust for crushing; grinding switched entirely to wet methods"],
 "Article 12, subparagraphs 1 to 3."),

(A,"第13條",1,"鉛中毒-軟焊作業",
 "雇主使勞工於通風不充分之場所從事鉛合金軟焊之作業時，應於該作業場所設置何種設備？",
 ["應設置局部排氣裝置或整體換氣裝置","應設置密閉設備或吹吸型換氣裝置","應設置局部排氣裝置及承受溢流設備","應設置整體換氣裝置及儲存浮渣容器"],"a",
 "第13條：雇主使勞工從事第2條第2項第10款（於通風不充分之場所從事鉛合金軟焊）之作業時，應於該作業場所設置局部排氣裝置或整體換氣裝置。第32條並定該作業設置整體換氣裝置之換氣量，應為每一勞工平均每分鐘一‧六七立方公尺以上。",
 "What must be installed where lead alloy soft soldering is done in poorly ventilated places?",
 ["Local exhaust ventilation or dilution ventilation","An enclosure or push pull ventilation equipment","Local exhaust ventilation and an overflow device","Dilution ventilation and a vessel for storing dross"],
 "Article 13 allows either local exhaust or dilution ventilation."),

(A,"第14條",2,"鉛中毒-施釉作業",
 "雇主使勞工於室內作業場所以散布或噴布方式，使用含鉛化合物之釉藥從事施釉作業時，應設置何種設備？",
 ["應於該作業場所設置局部排氣裝置","應於該作業場所設置整體換氣裝置","應於該作業場所設置吹吸型換氣裝置","應於該作業場所設置移動式集塵裝置"],"a",
 "第14條：雇主使勞工於室內作業場所以散布或噴布方式從事第2條第2項第11款之施釉作業時，應於該作業場所設置局部排氣裝置。第2條第2項第11款所稱作業，指使用含鉛化合物之釉藥從事施釉或該施釉物之烘燒作業。",
 "What equipment is required for indoor glazing by scattering or spraying lead compound glazes?",
 ["Local exhaust ventilation at that workplace","Dilution ventilation installed at that workplace","Push pull ventilation installed at that workplace","A movable dust collector placed at that workplace"],
 "Article 14 requires local exhaust ventilation."),

(A,"第15條",2,"鉛中毒-繪畫作業",
 "雇主使勞工於室內作業場所，以噴布方式使用含鉛化合物之繪料從事繪畫作業時，應設置何種設備？",
 ["應於該作業場所設置局部排氣裝置","應於該作業場所設置整體換氣裝置","應於該作業場所設置密閉噴漆房","應於該作業場所設置吹吸型換氣裝置"],"a",
 "第15條：雇主使勞工於室內作業場所，以噴布從事第2條第2項第12款之繪畫作業時，應於該作業場所設置局部排氣裝置。第14條對施釉作業亦有相同要求；第49條則定臨時從事第10款至第13款作業者適用範圍限縮。",
 "What equipment is required for indoor painting by spraying with lead compound pigments?",
 ["Local exhaust ventilation at that workplace","Dilution ventilation installed at that workplace","A closed spray booth built at that workplace","Push pull ventilation installed at that workplace"],
 "Article 15 requires local exhaust ventilation."),

(A,"第16條",2,"鉛中毒-淬火退火",
 "雇主使勞工使用熔融之鉛從事金屬之淬火、退火作業時，應設置何種設備？",
 ["應設置局部排氣裝置及儲存浮渣之容器","應設置整體換氣裝置及儲存切屑之容器","應設置密閉設備及承受溢流之專用設備","應設置吹吸型換氣裝置及淋浴盥洗設備"],"a",
 "第16條：雇主使勞工從事第2條第2項第13款規定之淬火或退火作業時，應設置局部排氣裝置及儲存浮渣之容器。第45條並定砂浴作業之攪砂或換砂應置備適當之呼吸防護具。",
 "What must be provided where molten lead is used for quenching or annealing metals?",
 ["Local exhaust ventilation and a vessel for storing dross","Dilution ventilation and a vessel for storing scrap chips","An enclosure and a dedicated overflow receiving device","Push pull ventilation and shower and washing facilities"],
 "Article 16 requires local exhaust and a dross vessel."),

(A,"第17條",2,"鉛中毒-含鉛設備加工",
 "從事含鉛襯墊或已塗布含鉛塗料物品之壓延、熔接、熔斷、加熱、熱鉚接，與非以濕式方式軋碎之室內作業場所，應分別設置何種設備？",
 ["前者應設置局部排氣裝置；後者應設置密閉設備或局部排氣裝置","前者應設置整體換氣裝置；後者應設置吹吸型換氣裝置或水簾","前者應設置密閉設備即可；後者應設置整體換氣裝置或噴霧設備","前者應設置承受溢流設備；後者應設置局部排氣裝置及儲存容器"],"a",
 "第17條：從事鉛之襯墊或已塗布含鉛塗料物品之壓延、熔接、熔斷、加熱、熱鉚接之室內作業場所，應設置局部排氣裝置；非以濕式作業方式從事軋碎之室內作業場所，應設置密閉設備或局部排氣裝置。第18條另定剝除含鉛塗料之作業規定。",
 "What controls apply to rolling and welding of leaded items, and to non wet crushing indoors?",
 ["The former needs local exhaust ventilation; the latter needs an enclosure or local exhaust","The former needs dilution ventilation; the latter needs push pull ventilation or a water curtain","The former only needs an enclosure; the latter needs dilution ventilation or spray equipment","The former needs an overflow device; the latter needs local exhaust and storage containers"],
 "Article 17, subparagraphs 1 and 2."),

(A,"第18條",2,"鉛中毒-剝除含鉛塗料",
 "雇主使勞工從事剝除含鉛塗料之作業時，依規定應如何辦理？",
 ["應採取濕式作業，但有顯著困難者不在此限；並應將剝除之含鉛塗料立即清除","應採取密閉作業，且無例外規定；並應將剝除之含鉛塗料於每週末清除","應採取濕式作業，且不得有任何例外；並應將剝除之含鉛塗料就地掩埋","應採取乾式作業並輔以吹風，但應將剝除之含鉛塗料於當班結束前清除"],"a",
 "第18條：雇主使勞工從事第2條第2項第14款之剝除含鉛塗料時，應採取濕式作業，但有顯著困難者不在此限；並應將剝除之含鉛塗料立即清除。第45條第1項第3款另定非以濕式作業方法剝除含鉛塗料者，應置備適當之呼吸防護具。",
 "How must the stripping of lead based paint be carried out?",
 ["Use wet methods unless markedly difficult, and remove the stripped paint immediately","Use closed methods with no exception, and remove the stripped paint each weekend","Use wet methods with absolutely no exception, and bury the stripped paint on site","Use dry methods with blowing air, but remove the stripped paint before shift end"],
 "Article 18, subparagraphs 1 and 2."),

(A,"第19條",1,"鉛中毒-轉印紙製造",
 "轉印紙之製造過程中，從事粉狀鉛、鉛混存物之散布、上粉作業時，應於該作業場所設置何種設備？",
 ["應設置局部排氣裝置","應設置整體換氣裝置","應設置吹吸型換氣裝置","應設置移動式集塵裝置"],"a",
 "第19條：雇主使勞工從事第2條第2項第16款（轉印紙製造過程中粉狀鉛、鉛混存物之散布、上粉）之作業時，應於該作業場所設置局部排氣裝置。第45條並定粉狀鉛相關作業之呼吸防護具置備義務。",
 "What equipment is required for scattering and powdering of lead in transfer paper manufacture?",
 ["Local exhaust ventilation must be installed","Dilution ventilation must be installed there","Push pull ventilation must be installed there","A movable dust collector must be installed"],
 "Article 19 requires local exhaust ventilation."),

(A,"第20條",2,"鉛中毒-氣罩型式",
 "依第五條第二款及第三款、第六條第二款及第三款、第七條第二款及第三款等規定設置之局部排氣裝置，其氣罩應採何種型式？有無例外？",
 ["應採用包圍型；但作業方法上設置此種型式之氣罩有困難時，不在此限","應採用外裝型；但作業方法上設置此種型式之氣罩有困難時，不在此限","應採用接受型；且不論作業方法如何困難，均不得採用其他之型式","應採用吹吸型；但經勞動檢查機構認定確有困難者，得改採外裝型式"],"a",
 "第20條：第5條第2款及第3款、第6條第2款及第3款、第7條第2款及第3款、第10條第2款、第4款、第5款及第12條第3款規定設置之局部排氣裝置之氣罩，應採用包圍型；但作業方法上設置此種型式之氣罩困難時，不在此限。第25條另定氣罩之一般設置原則。",
 "What hood type is required for the local exhaust systems designated in those provisions, and is there an exception?",
 ["An enclosing type hood, unless such a hood is difficult to install given the work method","An exterior type hood, unless such a hood is difficult to install given the work method","A receiving type hood, with no alternative allowed however difficult the work method is","A push pull type hood, though an exterior hood is allowed if the inspection agency agrees"],
 "Article 20 requires enclosing hoods with a difficulty exception."),

(A,"第21條",2,"鉛中毒-輸送機",
 "雇主使勞工於室內作業場所以輸送機搬運粉狀之鉛、鉛混存物、燒結礦混存物時，應如何設置？",
 ["供料場所及轉運場所應設密閉設備或局部排氣裝置；斗式輸送機應設有效防止鉛塵飛揚之設備","供料場所及轉運場所應設整體換氣裝置或水霧設備；斗式輸送機應設自動停機與警報之裝置","供料場所及轉運場所應設承受溢流設備及儲存容器；斗式輸送機應設防止物料倒流之閘門","供料場所及轉運場所應設吹吸型換氣裝置及護欄；斗式輸送機應設定期潤滑與檢點之紀錄"],"a",
 "第21條：室內作業場所搬運粉狀之鉛、鉛混存物、燒結礦混存物之輸送機，其供料場所及轉運場所應設置密閉設備或局部排氣裝置；斗式輸送機應設置有效防止鉛塵飛揚之設備。第22條另定乾燥粉狀鉛作業場所之防塵規定。",
 "What must be provided for conveyors carrying powdered lead materials indoors?",
 ["Enclosures or local exhaust at feeding and transfer points; bucket conveyors need effective dust scatter prevention","Dilution ventilation or water mist at feeding and transfer points; bucket conveyors need auto stop and alarms","Overflow receiving devices and containers at those points; bucket conveyors need backflow prevention gates","Push pull ventilation and guardrails at those points; bucket conveyors need lubrication and check records"],
 "Article 21, subparagraphs 1 and 2."),

(A,"第22條",2,"鉛中毒-乾燥作業",
 "雇主使勞工從事乾燥粉狀之鉛、鉛混存物作業之場所，依規定應如何辦理？",
 ["應防止鉛塵溢出於室內；乾燥室之地面、牆壁或棚架應易於使用真空除塵機或以水清除","應防止鉛塵溢出於室外；乾燥室之地面、牆壁或棚架應鋪設吸音材質並每月更換一次","應維持室內正壓以隔絕外氣；乾燥室之地面、牆壁或棚架應採用木質材料並定期上漆","應設置整體換氣裝置稀釋鉛塵；乾燥室之地面應保持濕潤且牆壁應張貼危害告示牌"],"a",
 "第22條：雇主使勞工從事乾燥粉狀之鉛、鉛混存物作業之場所，應防止鉛、鉛混存物之鉛塵溢出於室內；乾燥室之地面、牆壁或棚架之構造，應易於使用真空除塵機或以水清除。第45條第1項第5款並定該乾燥作業應置備適當之呼吸防護具。",
 "What requirements apply to sites drying powdered lead materials?",
 ["Prevent lead dust escaping indoors; drying room floors, walls and racks cleanable by vacuum or water","Prevent lead dust escaping outdoors; floors, walls and racks lined with sound absorbing material monthly","Keep the room under positive pressure; floors, walls and racks made of wood and repainted regularly","Install dilution ventilation to dilute dust; keep floors wet and post hazard notices on the walls"],
 "Article 22, subparagraphs 1 and 2."),

(A,"第23條",2,"鉛中毒-集塵裝置",
 "雇主使用粉狀之鉛、鉛混存物、燒結礦混存物等之過濾式集塵裝置，對於濾布及固定式排氣口有何規定？",
 ["濾布應設有護圍；固定式排氣口應設於室外，並應避免迴流至室內作業場所","濾布應每月更換一次；固定式排氣口得設於室內，但應加裝防止迴流閘板","濾布應以水霧保持濕潤；固定式排氣口應設於室內高處，以利熱氣流上升","濾布應採可燃性材質；固定式排氣口應設於室外，並得任其自然迴流室內"],"a",
 "第23條第1款、第2款：過濾式集塵裝置之濾布應設有護圍；固定式排氣口應設於室外，並應避免迴流至室內作業場所。第29條並定局部排氣裝置或整體換氣裝置之排氣口應設於室外，但設有移動式集塵裝置者不在此限。",
 "What rules apply to the filter cloth and the fixed exhaust outlet of a filtering dust collector?",
 ["The filter cloth needs a guard; the fixed outlet must be outdoors and must avoid backflow indoors","The filter cloth is replaced monthly; the outlet may be indoors with a backflow prevention damper","The filter cloth is kept wet by mist; the outlet must be high indoors to let hot air rise","The filter cloth must be combustible; the outlet is outdoors and backflow indoors is acceptable"],
 "Article 23, subparagraphs 1 and 2."),

(A,"第23條",3,"鉛中毒-集塵裝置",
 "過濾式集塵裝置對於濾材上附著鉛塵之處理及裝置設置位置，另有何規定？更換濾布時勞工應如何防護？",
 ["應易於將附著於濾材上之鉛塵移除，並與勞工經常作業場所適當隔離；更換濾布應置備呼吸防護具","應每季委外清洗濾材一次，並儘量設於勞工經常作業場所旁；更換濾布時僅需配戴一般防塵口罩","應以壓縮空氣直接向室內吹除濾材，並設於休息室上方；更換濾布時由作業主管代為執行即可","應將濾材連同鉛塵一併掩埋處理，並設於餐廳附近以便管理；更換濾布時應先實施作業環境監測"],"a",
 "第23條第3款、第4款：集塵裝置應易於將附著於濾材上之鉛塵移除，並應與勞工經常作業場所適當隔離。第45條第1項第6款：從事集塵裝置濾布之更換作業，應置備適當之呼吸防護具並訂定計畫，使勞工確實遵守。",
 "What further rules apply to removing dust from the filter media and siting the collector, and to filter replacement?",
 ["Dust must be easy to remove and the collector kept apart from regular work areas; respirators for replacement","Media are sent out for cleaning quarterly and sited beside work areas; only a plain dust mask is needed","Compressed air blows the media clean indoors and it sits above the rest room; the supervisor does the work","The media are buried with the dust and the unit sits near the canteen; monitoring precedes replacement"],
 "Article 23, subparagraphs 3 and 4, and Article 45."),

(A,"第25條",2,"鉛中毒-氣罩設置",
 "雇主設置之局部排氣裝置氣罩，依規定應如何設置？",
 ["應設於每一鉛塵發生源，視作業方法及散布狀況選擇型式大小，外裝型或接受型開口應儘量接近發生源","應每一作業場所設置一具即可，型式大小由供應商決定，外裝型或接受型開口應遠離鉛塵之發生源","應設於作業場所之出入口處，型式大小依廠房面積決定，包圍型氣罩開口應朝向勞工呼吸帶方向","應設於屋頂排氣口下方位置，型式大小依風機容量決定，接受型氣罩開口應朝向室外新鮮空氣側"],"a",
 "第25條：局部排氣裝置之氣罩應設置於每一鉛、鉛混存物、燒結礦混存物等之鉛塵發生源；應視作業方法及鉛塵散布之狀況，選擇適於吸引該鉛塵之型式及大小；外裝型或接受型氣罩之開口，應儘量接近於鉛塵發生源。第20條另定特定作業之氣罩應採包圍型。",
 "How must hoods of a local exhaust system be arranged?",
 ["One at every dust source, of a type and size suited to the work, with exterior or receiving openings close to it","One per workplace is enough, type and size chosen by the supplier, with openings kept far from the source","At the entrance of the workplace, sized by floor area, with enclosing openings facing the breathing zone","Below the roof outlet, sized by fan capacity, with receiving openings facing the fresh outdoor air side"],
 "Article 25, subparagraphs 1 to 3."),

(A,"第26條",3,"鉛中毒-導管及監測",
 "局部排氣裝置之導管內部構造有何要求？依第三十一條第二項設置之局部排氣裝置另應設置何種裝置？",
 ["導管內部應易於清掃及測定，並開設清潔口及測定孔；另應設置監測靜壓、流速等顯示正常運轉之裝置","導管內部應保持絕對氣密而不得開孔，以免洩漏；另應設置自動滅火及溫度過高時之緊急遮斷裝置","導管內部應塗布防蝕塗料並每年更換管材一次；另應設置粉塵濃度連續自動監測及告警之顯示裝置","導管內部應維持負壓並設置消音棉以降低噪音；另應設置可顯示每日累計運轉時數之計時器裝置"],"a",
 "第26條第1項：局部排氣裝置之導管內部構造應易於清掃及測定，並於適當位置開設清潔口及測定孔。第2項：依第31條第2項規定設置之局部排氣裝置，應於氣罩連接導管適當處所，設置監測靜壓、流速或其他足以顯示該設備正常運轉之裝置；本項自一百十四年七月一日施行。",
 "What is required of duct interiors, and what extra device applies to systems installed under Article 31, paragraph 2?",
 ["Ducts easy to clean and measure with cleaning and measuring ports; plus a static pressure or velocity monitor","Ducts kept absolutely airtight with no openings; plus automatic fire suppression and heat cut off devices","Ducts coated against corrosion and replaced yearly; plus continuous dust concentration monitoring alarms","Ducts kept under negative pressure with sound absorbing wool; plus a daily cumulative run time counter"],
 "Article 26, paragraphs 1 and 2."),

(A,"第28條",2,"鉛中毒-排氣機位置",
 "局部排氣裝置之排氣機應設於何處？整體換氣裝置之排氣機或導管開口部又應如何設置？",
 ["排氣機應置於空氣清淨裝置後之位置，無累積鉛塵之虞者除外；整體換氣者應接近鉛塵發生源","排氣機應置於空氣清淨裝置前之位置，且無任何例外；整體換氣者應接近作業場所之出入口","排氣機應置於氣罩與導管之間的位置，以提高吸引力；整體換氣者應設於屋頂之最高處所","排氣機應置於室外地面並加設防雨遮蔽；整體換氣者應遠離鉛塵發生源以免造成擾流現象"],"a",
 "第28條第1項：設置局部排氣裝置之排氣機，應置於空氣清淨裝置後之位置，但無累積鉛塵之虞者，不在此限。第2項：設置整體換氣裝置之排氣機或設置導管之開口部，應接近鉛塵發生源，務使污染空氣有效換氣。",
 "Where must the exhaust fan of a local exhaust system be placed, and how is dilution ventilation arranged?",
 ["After the air cleaner, unless no dust can accumulate; dilution fans or duct openings near the dust source","Before the air cleaner in all cases with no exception; dilution fans placed near the workplace entrance","Between the hood and the duct to increase suction; dilution fans placed at the highest point of the roof","Outdoors at ground level under a rain cover; dilution fans kept far from the source to avoid turbulence"],
 "Article 28, paragraphs 1 and 2."),

(A,"第29條",1,"鉛中毒-排氣口",
 "雇主設置局部排氣裝置或整體換氣裝置之排氣口，應設置於何處？有何例外？",
 ["應設置於室外；但設有移動式集塵裝置者，不在此限","應設置於室內高處；但設有固定式集塵裝置者除外","應設置於室外；且不論有無集塵裝置均無任何例外","應設置於地面附近；但設有空氣清淨裝置者不在此限"],"a",
 "第29條：雇主設置局部排氣裝置或整體換氣裝置之排氣口，應設置於室外；但設有移動式集塵裝置者，不在此限。第23條第2款並定過濾式集塵裝置之固定式排氣口應設於室外並避免迴流。",
 "Where must the exhaust outlet of local exhaust or dilution ventilation be located, and what is the exception?",
 ["Outdoors, except where a movable dust collector is installed","High indoors, except where a fixed dust collector is installed","Outdoors, with no exception whether or not a collector exists","Near the floor, except where an air cleaning device is installed"],
 "Article 29 sets an outdoor outlet with one exception."),

(A,"第30條",2,"鉛中毒-有效運轉",
 "雇主設置之局部排氣裝置，於鉛作業期間應維持何種運轉狀態及績效？",
 ["應於鉛作業時間內有效運轉，並降低空氣中鉛塵濃度至勞工作業場所容許暴露標準以下","應於鉛作業開始前後各運轉三十分鐘，並降低鉛塵濃度至容許暴露標準之二倍以下","應於每日上下班時各運轉一小時，並使空氣中鉛塵濃度維持在可偵測極限值以下","應由作業主管視鉛塵狀況決定運轉時機，並將濃度降至容許暴露標準之五倍以下"],"a",
 "第30條：雇主設置之局部排氣裝置，應於鉛作業時間內有效運轉，並降低空氣中鉛塵濃度至勞工作業場所容許暴露標準以下。第33條並定局部排氣裝置或整體換氣裝置於鉛作業時不得停止運轉，但裝置內部清掃作業不在此限。",
 "How must a local exhaust system operate during lead work and to what performance?",
 ["Operate effectively throughout the lead work and cut airborne lead below the permissible exposure standard","Operate for thirty minutes before and after the work and keep lead below twice the permissible standard","Operate one hour at the start and end of each day and keep lead below the limit of detection","Operate whenever the supervisor decides and keep lead below five times the permissible standard"],
 "Article 30 requires effective operation below the exposure standard."),

(A,"第31條之1",3,"鉛中毒-專業人員準用",
 "從事局部排氣裝置設計之專業人員應具備之資格、訓練課程與時數、訓練單位，及設計報告書、原始性能測試報告書之內容，應準用何規定？",
 ["準用特定化學物質危害預防標準第三十八條及第三十八條之一之規定辦理","準用粉塵危害預防標準第二十三條及第二十四條所定之相關規定辦理","準用職業安全衛生教育訓練規則第十九條及第二十條所定之規定辦理","準用勞工作業環境監測實施辦法第十條及第十一條所定之規定辦理"],"a",
 "第31條之1：第31條第2項及第3項所定從事局部排氣裝置設計專業人員應具備之資格、訓練課程與時數、訓練單位，及局部排氣裝置設計報告書、原始性能測試報告書之內容，準用特定化學物質危害預防標準第38條及第38條之一之規定。本條自一百十四年七月一日施行。",
 "Which provisions are applied by reference for the designer qualifications and report contents?",
 ["Articles 38 and 38-1 of the Specified Chemical Substances Hazard Prevention Standards","Articles 23 and 24 of the Dust Hazard Prevention Standards are applied by reference","Articles 19 and 20 of the Occupational Safety and Health Education Rules apply","Articles 10 and 11 of the Regulations for Workplace Environmental Monitoring apply"],
 "Article 31-1 refers to the specified chemical substances standards."),

(A,"第33條",2,"鉛中毒-運轉禁止停止",
 "局部排氣裝置或整體換氣裝置於鉛作業時得否停止運轉？其設置處所另有何限制？",
 ["鉛作業時不得停止運轉，但裝置內部清掃作業不在此限；設置處所不得阻礙其排氣或換氣功能","鉛作業時得由作業主管視需要暫停運轉；設置處所僅須保持走道淨寬八十公分以上即可","鉛作業時不得停止運轉，且內部清掃時亦不得停止；設置處所應加設圍籬禁止勞工接近","鉛作業時得於休息時間全部停止運轉；設置處所得堆置原料，但應每週清點整理一次"],"a",
 "第33條第1項：局部排氣裝置或整體換氣裝置，於鉛作業時不得停止運轉，但裝置內部清掃作業不在此限。第2項：設置局部排氣裝置或整體換氣裝置之處所，不得阻礙其排氣或換氣功能。第30條並要求有效運轉至容許暴露標準以下。",
 "May the ventilation be stopped during lead work, and what limit applies to its location?",
 ["It may not stop during lead work except for internal cleaning; its location must not obstruct its function","The supervisor may pause it as needed; the location need only keep an aisle eighty centimetres wide","It may not stop at all, not even for internal cleaning; the location must be fenced off from workers","It may stop entirely during rest breaks; materials may be stacked there if tidied up once a week"],
 "Article 33, paragraphs 1 and 2."),

(A,"第35條",1,"鉛中毒-淋浴設備",
 "雇主使勞工從事粉狀之鉛、鉛混存物或燒結礦混存物之處理作業者，應設置何種設備？",
 ["應設置淋浴設備供勞工使用","應設置專用洗衣設備供使用","應設置獨立之更衣休息隔間","應設置盥洗用之漱口消毒台"],"a",
 "第35條：雇主使勞工從事粉狀之鉛、鉛混存物或燒結礦混存物之處理作業者，應設置淋浴設備。第38條另定從事含鉛、鉛塵設備內部作業者應設置淋浴及更衣設備；第39條並定應設置專用洗衣設備。",
 "What facility must be provided for workers handling powdered lead materials?",
 ["Shower facilities must be provided for workers","A dedicated laundry facility must be provided","A separate changing and rest cubicle is needed","A mouth rinsing and disinfecting stand is needed"],
 "Article 35 requires shower facilities."),

(A,"第36條",2,"鉛中毒-清潔頻率",
 "為防止鉛塵污染，雇主對作業場所、休息室、餐廳等之清潔，應以何種方式、多久實施一次？",
 ["應每日以水沖洗或以真空除塵機、適當溶液清潔一次以上；無鉛塵污染之虞者不在此限","應每週以水沖洗或以真空除塵機、適當溶液清潔一次以上；且無任何例外情形之規定","應每日以壓縮空氣吹除鉛塵並以掃帚乾式清掃一次以上；無鉛塵污染之虞者不在此限","應每月委託專業清潔業者以真空除塵機清潔一次以上；經作業主管同意者得免辦理"],"a",
 "第36條：雇主為防止鉛、鉛混存物或燒結礦混存物等之鉛塵污染，應每日以水沖洗，或以真空除塵機、適當溶液清潔作業場所、休息室、餐廳等一次以上；但無鉛塵污染之虞者，不在此限。第34條並定休息室之出入口及地面構造要求。",
 "How and how often must workplaces, rest rooms and canteens be cleaned to prevent lead dust?",
 ["Daily at least once by water flushing, vacuum cleaner or a suitable solution, unless no dust risk exists","Weekly at least once by water flushing, vacuum cleaner or a suitable solution, with no exception at all","Daily at least once by blowing with compressed air and dry sweeping, unless no dust risk exists","Monthly at least once by an outside cleaning contractor, waivable with the supervisor's consent"],
 "Article 36 requires daily cleaning with an exception."),

(A,"第37條",1,"鉛中毒-盥洗設備",
 "雇主使勞工從事鉛作業時，應於作業場所備置何種用品供勞工洗滌，以避免鉛塵污染？",
 ["應備置指甲刷、肥皂或適當溶液等洗手、漱口用之盥洗設備","應備置乾洗手酒精與拋棄式紙巾等簡易清潔用品即為已足","應備置有機溶劑與棉布等擦拭用品供勞工清除皮膚上鉛塵","應備置洗眼液、吸附劑及整補材料等急救與防止擴散材料"],"a",
 "第37條：雇主使勞工從事鉛作業時，應於作業場所備置指甲刷、肥皂或適當溶液等洗手、漱口用之盥洗設備，供給作業勞工洗滌，以避免鉛塵之污染。第35條並定粉狀鉛處理作業應設置淋浴設備。",
 "What washing supplies must be kept at the workplace for lead workers?",
 ["Nail brushes, soap or a suitable solution for hand washing and mouth rinsing","Alcohol hand rub and disposable paper towels as simple cleaning items suffice","Organic solvents and cotton cloths for workers to wipe lead dust off the skin","Eye wash, adsorbents and patching materials for first aid and spread control"],
 "Article 37 requires nail brushes, soap and washing facilities."),

(A,"第38條",2,"鉛中毒-設備內部作業",
 "雇主使勞工從事含鉛、鉛塵設備內部之作業時，依規定應如何辦理？",
 ["應設置淋浴及更衣設備供勞工使用；並使勞工將污染之衣服置於密閉容器內","應設置盥洗及休息設備供勞工使用；並使勞工將污染之衣服帶回自行清洗","應設置淋浴及更衣設備供勞工使用；並使勞工將污染之衣服懸掛於通風處","應設置專用洗衣設備供勞工使用；並使勞工將污染之衣服直接焚化處理之"],"a",
 "第38條：雇主使勞工從事第2條第2項第15款（含鉛、鉛塵設備內部）之作業時，應設置淋浴及更衣設備以供勞工使用，並使勞工將污染之衣服置於密閉容器內。第43條另定該作業應先隔離設備連結部分並充分換氣、濕潤鉛塵；第45條並定應置備呼吸防護具及防護衣著。",
 "What must be provided for work inside equipment containing lead or lead dust?",
 ["Shower and changing facilities, and contaminated clothing placed in a sealed container","Washing and rest facilities, and contaminated clothing taken home to be washed","Shower and changing facilities, and contaminated clothing hung in a ventilated spot","A dedicated laundry facility, and contaminated clothing incinerated straight away"],
 "Article 38, subparagraphs 1 and 2."),

(A,"第39條",1,"鉛中毒-洗衣設備",
 "雇主使勞工從事鉛作業時，對於附著於工作衣上之鉛塵，應提供何種設備供勞工於必要時洗滌？",
 ["應設置專用洗衣設備，供勞工洗滌工作衣上之鉛塵","應設置專用烘乾設備，供勞工烘乾工作衣上之鉛塵","應設置專用消毒設備，供勞工消毒工作衣上之鉛塵","應設置專用保管設備，供勞工存放已污染之工作衣"],"a",
 "第39條：雇主使勞工從事鉛作業時，應設置專用洗衣設備，供勞工於必要時，洗滌附著於工作衣上之鉛塵。第34條第2項並定應使勞工於進入休息室前，將附著於工作衣上之鉛塵適當清除。",
 "What facility must be provided for washing lead dust off work clothes?",
 ["A dedicated laundry facility for washing lead dust from work clothes","A dedicated drying facility for drying lead dust off work clothes","A dedicated disinfection unit for sterilising the soiled work clothes","A dedicated storage cabinet for keeping the contaminated work clothes"],
 "Article 39 requires a dedicated laundry facility."),

(A,"第41條",2,"鉛中毒-鉛塵溢漏",
 "雇主使勞工將粉狀之鉛、鉛混存物或燒結礦混存物倒入漏斗時，如有鉛塵溢漏情形，應如何處理？有何例外？",
 ["應令勞工立即停止作業；但係臨時性作業且勞工確實已戴用有效呼吸防護具者不在此限","應令勞工於當班結束前停止作業；但經作業主管同意者得延長至次日再行處理","應令勞工立即停止作業；且不論是否為臨時性作業或有無防護具均無例外規定","應令勞工加快作業速度儘速完成；但應同時開啟整體換氣裝置稀釋鉛塵濃度"],"a",
 "第41條：雇主使勞工將粉狀之鉛、鉛混存物或燒結礦混存物等倒入漏斗時，如有鉛塵溢漏情形，應令勞工立即停止作業；但如係臨時性作業，且勞工確實已戴用有效呼吸防護具者，不在此限。第47條並定佩戴輸氣管面罩時入氣口應置於新鮮空氣位置。",
 "What must be done if lead dust escapes while pouring powdered lead into a hopper?",
 ["Workers must stop at once, unless the task is temporary and they wear effective respirators","Workers must stop before the shift ends, though the supervisor may defer it to the next day","Workers must stop at once, with no exception for temporary work or protective equipment","Workers must speed up and finish quickly, while dilution ventilation is switched on"],
 "Article 41 with its temporary work exception."),

(A,"第42條",2,"鉛中毒-焙燒爐取出",
 "自焙燒爐中取出鉛混存物、燒結礦混存物之作業，應如何辦理？相關設備之使用有何要求？",
 ["應於烘燒爐口設承接容器儲存，並設長柄工具或採機械取出方式；設備之使用應公告使勞工周知","應於烘燒爐口設淋浴設備降溫，並由二人以上共同以人力取出；設備之使用僅需口頭告知即可","應於烘燒爐口設整體換氣裝置，並以壓縮空氣吹出爐內殘留物；設備之使用應報請檢查機構備查","應於烘燒爐口設防火帷幕阻隔，並待爐體完全冷卻後徒手取出；設備之使用應記載於交接班紀錄"],"a",
 "第42條第1項：自焙燒爐中取出鉛混存物、燒結礦混存物之作業，應於烘燒爐口設置承接容器以儲存，並應設置長柄工具或採取機械取出方式。第2項：前項設備之使用，應公告使作業勞工周知。第45條並定該等作業應置備適當之呼吸防護具。",
 "How must materials be taken out of a roasting furnace, and what applies to the equipment used?",
 ["Provide a receiving vessel at the furnace mouth and long handled tools or mechanical removal; post a notice","Provide showers at the furnace mouth for cooling and use two workers by hand; a verbal briefing suffices","Provide dilution ventilation at the mouth and blow residues out with compressed air; file with the agency","Provide a fire curtain at the mouth and remove by hand after full cooling; record it in the shift handover"],
 "Article 42, paragraphs 1 and 2."),

(A,"第43條",2,"鉛中毒-入槽前措施",
 "雇主使勞工從事含鉛、鉛塵設備內部之作業前及作業中，對該設備應採取何種措施？",
 ["作業開始前應確實隔離該設備與其他設備間之連結部分並充分換氣；並將內部鉛塵充分濕潤防止飛揚","作業開始前應將該設備加壓試漏並保持正壓狀態；並將內部鉛塵以壓縮空氣吹出後始得進入設備內","作業開始前應通知勞動檢查機構到場監督並取得許可；並將內部鉛塵以掃帚清掃集中後裝袋運出","作業開始前應由作業主管量測設備內溫度及濕度；並將內部鉛塵噴灑有機溶劑溶解後排放至污水池"],"a",
 "第43條：雇主使勞工從事第2條第2項第15款之作業時，作業開始前應確實隔離該設備與其他設備間之連結部分，並將該設備給予充分換氣；應將附著或堆積該設備內部之鉛、鉛混存物或燒結礦混存物等之鉛塵充分濕潤，以防止其飛揚。第4條之1並定入槽安全應依局限空間相關規定辦理。",
 "What must be done to equipment before and during work inside it?",
 ["Isolate its connections from other equipment and ventilate it fully; wet the internal lead dust to stop scatter","Pressure test it and keep it under positive pressure; blow the internal dust out with compressed air first","Notify the inspection agency to supervise and permit entry; sweep the dust together and bag it out","Have the supervisor measure inside temperature and humidity; dissolve the dust with solvent into a sump"],
 "Article 43, subparagraphs 1 and 2."),

(A,"第44條",1,"鉛中毒-禁止飲食",
 "雇主對於鉛作業場所之飲食及吸菸，依規定應如何處理？",
 ["應公告禁止飲食或吸菸，並揭示於明顯易見之處所","應公告禁止吸菸，但於指定時段內得飲用瓶裝飲料","應設置專用飲食區供勞工於作業場所內用餐及吸菸","應由作業主管於每日作業前口頭提醒勞工不得飲食"],"a",
 "第44條：雇主應公告鉛作業場所禁止飲食或吸菸，並揭示於明顯易見之處所。第34條並定應於作業場所外設置休息室，且進入休息室前應清除工作衣上鉛塵；第37條另定應備置洗手、漱口之盥洗設備。",
 "How must eating and smoking at lead work sites be handled?",
 ["Post a notice banning eating and smoking in a conspicuous place","Post a notice banning smoking, but allow bottled drinks at set times","Set up a dedicated eating area inside the workplace for meals and smoking","Have the supervisor remind workers verbally before work each day"],
 "Article 44 requires a posted ban on eating and smoking."),

(A,"第46條",1,"鉛中毒-輸氣管面罩",
 "雇主使勞工戴用輸氣管面罩從事連續作業時，每次連續作業時間有何限制？",
 ["每次不得超過一小時","每次不得超過二小時","每次不得超過三十分鐘","每次不得超過四小時"],"a",
 "第46條：雇主使勞工戴用輸氣管面罩之連續作業時間，每次不得超過一小時。第47條並定依第41條、第45條規定佩戴輸氣管面罩時，其面罩之入氣口應置於新鮮空氣之位置，並保持有效運轉。",
 "What limit applies to each continuous period of wearing an air line respirator?",
 ["Not more than one hour each time","Not more than two hours each time","Not more than thirty minutes each time","Not more than four hours each time"],
 "Article 46 sets a one hour limit."),

(A,"第47條",2,"鉛中毒-面罩入氣口",
 "雇主依第四十一條、第四十五條規定使勞工佩戴輸氣管面罩時，對面罩之入氣口有何要求？",
 ["入氣口應置於新鮮空氣之位置，並保持有效運轉","入氣口應置於局部排氣裝置氣罩旁，以利即時補氣","入氣口應置於作業場所內較高處，以避免鉛塵吸入","入氣口應置於集塵裝置排氣口後方，並每月清洗一次"],"a",
 "第47條：雇主依第41條、第45條規定使勞工佩戴輸氣管面罩時，其面罩之入氣口，應置於新鮮空氣之位置，並保持有效運轉。第46條並定戴用輸氣管面罩之連續作業時間每次不得超過一小時。",
 "What is required of the air intake of an air line respirator?",
 ["The intake must be placed in fresh air and kept effectively operating","The intake must sit beside the local exhaust hood for quick make up air","The intake must be placed high inside the workplace to avoid lead dust","The intake must sit behind the collector outlet and be washed monthly"],
 "Article 47 requires a fresh air intake."),

(A,"第49條",3,"鉛中毒-適用範圍限縮",
 "下列何種鉛作業僅適用本規則第一章及第四十一條、第四十五條、第四十七條及第四十八條之規定？",
 ["坩堝爐等總容量不滿五十公升且於攝氏四百五十度以下之熔融鑄造、臨時從事第十款至第十三款作業、隔離室遙控作業","坩堝爐等總容量不滿一百公升且於攝氏六百度以下之熔融鑄造、臨時從事第一款至第三款作業、以人工搬運粉狀鉛作業","坩堝爐等總容量不滿五十公升且於攝氏二百度以下之熔融鑄造、經常從事第十四款作業、於通風不充分場所軟焊作業","坩堝爐等總容量不滿三十公升且於攝氏四百五十度以下之熔融鑄造、臨時從事第十五款設備內部作業及其清掃作業"],"a",
 "第49條：作業場所熔融鉛或鉛合金之坩堝、爐等容量總計不滿五十公升，且於攝氏四百五十度以下之溫度從事熔融或鑄造；臨時從事第2條第2項第10款至第13款規定之作業或該作業場所清掃；於隔離室以遙控方式從事鉛作業者，僅適用第一章及第41條、第45條、第47條、第48條之規定。第27條第2項並定熔爐總容量未滿五十公升者得免設集塵裝置。",
 "Which lead work is subject only to Chapter One and Articles 41, 45, 47 and 48?",
 ["Crucibles under fifty litres in total at or below 450 degrees, temporary work under items 10 to 13, remote isolated work","Crucibles under one hundred litres at or below 600 degrees, temporary work under items 1 to 3, manual powder carrying","Crucibles under fifty litres at or below 200 degrees, regular work under item 14, soldering in poorly ventilated places","Crucibles under thirty litres at or below 450 degrees, temporary work inside equipment under item 15 and its cleaning"],
 "Article 49, subparagraphs 1 to 3."),

(A,"第50條",2,"鉛中毒-施行日期",
 "鉛中毒預防規則一百十三年六月十三日修正發布之第二十六條第二項、第三十一條第二項至第五項及第三十一條之一，自何時施行？",
 ["自一百十四年七月一日施行，其餘修正條文則自發布日施行","自一百十三年七月三日施行，其餘修正條文則自發布日施行","自一百十五年七月一日施行，其餘修正條文則自發布日施行","自一百十六年一月一日施行，其餘修正條文則自發布日施行"],"a",
 "第50條第2項：本規則中華民國一百零三年六月三十日修正發布之條文，自一百零三年七月三日施行；一百十三年六月十三日修正發布之第26條第2項、第31條第2項至第5項、第31條之一，自一百十四年七月一日施行。第1項並定本規則自發布日施行。",
 "When do the 2024 amendments to Article 26-2, Article 31-2 to 31-5 and Article 31-1 take effect?",
 ["On 1 July 2025, while the other amended provisions took effect on promulgation","On 3 July 2014, while the other amended provisions took effect on promulgation","On 1 July 2026, while the other amended provisions took effect on promulgation","On 1 January 2027, while the other amended provisions took effect on promulgation"],
 "Article 50, paragraph 2."),

]
