# -*- coding: utf-8 -*-
# 第 12 批（I1）：毒性及關注化學物質專業應變人員管理辦法（ENV-190）、
#                毒性及關注化學物質環境事故專業應變諮詢機關（構）認證及管理辦法（ENV-191）
A = "ENV-190"
B = "ENV-191"
Q = [

# ===== ENV-190 毒性及關注化學物質專業應變人員管理辦法 =====
(A,"第1條",1,"專業應變人員-授權依據",
 "毒性及關注化學物質專業應變人員管理辦法係依何項法律規定訂定？",
 ["依毒性及關注化學物質管理法第三十七條第三項規定訂定之","依毒性及關注化學物質管理法第三十六條第二項規定訂定之","依毒性及關注化學物質管理法第六條第二項規定所訂定之","依環境用藥管理法第三十七條第三項授權規定所訂定之"],"a",
 "第1條：本辦法依毒性及關注化學物質管理法第三十七條第三項規定訂定。第2條並定義專業應變人員分通識級、操作級、技術級、指揮級及專家級五級；第20條另依本法第三十七條第二項要求保存訓練紀錄三年。",
 "Which statutory provision authorizes these Regulations on professional responders?",
 ["Article 37, paragraph 3 of the Toxic and Concerned Chemical Substances Control Act","Article 36, paragraph 2 of the Toxic and Concerned Chemical Substances Control Act","Article 6, paragraph 2 of the Toxic and Concerned Chemical Substances Control Act","Article 37, paragraph 3 of the Environmental Agents Control Act instead of that Act"],
 "Article 1 cites Article 37, paragraph 3 of the Act."),

(A,"第2條",2,"專業應變人員-等級能力",
 "專業應變人員各等級所應具備之能力，下列敘述何者正確？",
 ["操作級具備操作緊急除污程序能力；指揮級具備執行整體事故應變程序指揮之能力","通識級具備操作緊急除污程序能力；專家級具備執行整體事故應變程序指揮之能力","技術級具備操作緊急除污程序能力；操作級具備執行整體事故應變程序指揮之能力","指揮級具備操作緊急除污程序能力；技術級具備執行整體事故應變程序指揮之能力"],"a",
 "第2條第1款：通識級具危害辨識及事故通報能力；操作級具危害辨識及操作緊急除污程序能力；技術級可執行削減場內外化學物質逸散、洩漏之程序與技術；指揮級具執行整體事故應變程序指揮能力；專家級能掌握風險與危害技術、導入應變資源並制定區域安全與控制計畫。第16條並定各級得由較高等級代之。",
 "Which statement correctly matches responder levels with their required abilities?",
 ["Operational level handles emergency decontamination; command level directs the overall incident response","Awareness level handles emergency decontamination; specialist level directs the overall incident response","Technician level handles emergency decontamination; operational level directs the overall response work","Command level handles emergency decontamination; technician level directs the overall incident response"],
 "Article 2, subparagraph 1 defines the five levels."),

(A,"第2條",2,"專業應變人員-用詞定義",
 "本辦法所稱相關運作人，其範圍為何？",
 ["指製造、使用、貯存及運送毒性及具危害性關注化學物質之運作人及所有人","指製造、輸入、輸出及販賣毒性及具危害性關注化學物質之運作人及所有人","指製造、使用、貯存及運送任何列管化學物質之承攬人及受託運送業者","指僅從事運送毒性及具危害性關注化學物質之運送業者及其僱用駕駛人"],"a",
 "第2條第3款：相關運作人指製造、使用、貯存及運送毒性化學物質及中央主管機關依本法第三十七條第一項指定公告具危害性關注化學物質之運作人及所有人。同條第2款並定義應變、諮詢機構係依認證及管理辦法取得認證者。相關運作人依第13條至第17條負登載專業應變人員之義務。",
 "What is the scope of the term related operators under these Regulations?",
 ["Operators and owners that manufacture, use, store or transport toxic and hazardous concerned chemicals","Operators and owners that manufacture, import, export or sell toxic and hazardous concerned chemicals","Contractors and carriers that manufacture, use, store or transport any listed controlled chemical","Only carriers transporting toxic and hazardous concerned chemicals and the drivers they employ"],
 "Article 2, subparagraph 3."),

(A,"第3條",2,"專業應變人員-參訓資格",
 "參加通識級、操作級或技術級專業應變人員證照訓練者，應具備何種資格？",
 ["年滿十八歲且領有國民中學以上學校畢業證書或同等學力證明，或其他經中央主管機關認可之資格","年滿二十歲且領有高級中等學校以上畢業證書或同等學力證明，或其他經中央主管機關認可之資格","年滿十八歲且領有專科以上學校理工農醫相關副學士學位證書，或其他經目的事業主管機關認可者","年滿十六歲且領有國民小學以上學校畢業證書或同等學力證明，或其他經直轄市主管機關認可之資格"],"a",
 "第3條第1項：參加通識級、操作級或技術級證照訓練者，應年滿十八歲且領有公立或立案私立國民中學以上學校畢業證書或同等學力證明，或其他經中央主管機關認可之資格。第4條並規定報名時應檢具符合資格之證明文件始得參訓。",
 "What qualification is required to take awareness, operational or technician level training?",
 ["At least 18 years old with a junior high diploma or equivalent, or another qualification recognized by the central authority","At least 20 years old with a senior high diploma or equivalent, or another qualification recognized by the central authority","At least 18 years old with an associate degree in science, engineering, agriculture or medicine recognized by the sector authority","At least 16 years old with an elementary school diploma or equivalent, or another qualification recognized by the local authority"],
 "Article 3, paragraph 1."),

(A,"第3條",3,"專業應變人員-高階參訓資格",
 "參加指揮級與專家級專業應變人員證照訓練，各應具備何種資格？",
 ["指揮級須有操作級、技術級或專家級合格證書或高級中等學校以上學歷；專家級須有技術級合格證書或專科以上理工農醫副學士學位","指揮級須有技術級或專家級合格證書或專科以上學歷；專家級須有指揮級合格證書或大學以上理工農醫學士學位始得報名參訓","指揮級須有通識級或操作級合格證書或國民中學以上學歷；專家級須有操作級合格證書或高級中等學校以上畢業證書即可參訓","指揮級須有專家級合格證書或碩士以上學歷；專家級須有指揮級合格證書或專科以上理工農醫副學士學位證明始得報名"],"a",
 "第3條第2項：參加指揮級訓練者，須領有操作級、技術級或專家級合格證書，或高級中等學校以上畢業證書或同等學力證明。第3項：參加專家級訓練者，須領有技術級合格證書，或專科以上學校理、工、農、醫等相關學科副學士以上學位證明。二者亦均得以其他經中央主管機關認可之資格參訓。",
 "What qualifications are required for command level and specialist level training?",
 ["Command needs an operational, technician or specialist certificate or senior high schooling; specialist needs a technician certificate or an associate degree in science or engineering","Command needs a technician or specialist certificate or junior college schooling; specialist needs a command certificate or a bachelor degree in science or engineering related fields","Command needs an awareness or operational certificate or junior high schooling; specialist needs an operational certificate or a senior high school graduation diploma to enroll","Command needs a specialist certificate or a master degree; specialist needs a command certificate or an associate degree in science or engineering related disciplines"],
 "Article 3, paragraphs 2 and 3."),

(A,"第4條",1,"專業應變人員-報名程序",
 "報名參加專業應變人員證照訓練者，於參訓前應完成何項程序？",
 ["應依規定檢具符合各該等級參訓資格之證明文件，始得參加訓練","應先繳納全額訓練費用並通過中央主管機關舉辦之資格預試","應由所屬運作人先向直轄市主管機關報備後方得報名參加訓練","應檢具最近三個月內之健康檢查合格證明文件始得報名參訓"],"a",
 "第4條：報名參加專業應變人員證照訓練者，應依第3條規定檢具符合資格之證明文件，始得參訓。第6條並定缺課時數逾總訓練時數四分之一以上者應予退訓且已繳費用不退還。",
 "What must an applicant complete before taking the certification training?",
 ["Documents proving the applicant meets the qualification for that level must be filed first","The full training fee must be paid and a qualifying pretest held by the central authority passed","The employing operator must first report to the municipal competent authority before enrollment","A health examination certificate issued within the past three months must be filed on enrollment"],
 "Article 4."),

(A,"第5條",1,"專業應變人員-訓練時數",
 "各級專業應變人員證照訓練之訓練時數及課程大綱，本辦法如何規定？",
 ["由附件一定之，訓練機關（構）並得依附件一之時數及課程大綱擬定教材","由各訓練機關（構）自行訂定後報中央主管機關核定並公告實施","由直轄市、縣（市）主管機關按轄區需要分別公告時數及課程","由本辦法條文逐級明定時數，課程大綱則授權訓練機構自行安排"],"a",
 "第5條：各級專業應變人員證照訓練之訓練時數及課程大綱如附件一。第22條第2項並定受託訓練機關（構）應使用中央主管機關指定之教材，或依附件一及附件二之時數及課程大綱擬定教材。",
 "How are the training hours and course outline for certification training prescribed?",
 ["Annex 1 prescribes them, and training bodies may prepare materials following its hours and outline","Each training body sets them itself and files them with the central authority for approval and notice","Municipal and county competent authorities announce the hours and courses according to local needs","The Regulations set the hours level by level and leave the course outline to the training bodies"],
 "Article 5 refers to Annex 1."),

(A,"第6條",2,"專業應變人員-退訓規定",
 "參加專業應變人員證照訓練及再訓練，缺課達何種程度應予退訓？已繳費用如何處理？",
 ["缺課時數逾總訓練時數四分之一以上者應予退訓，已繳納之訓練費用不予退還","缺課時數逾總訓練時數三分之一以上者應予退訓，已繳納之訓練費用應予退還","缺課時數逾總訓練時數五分之一以上者應予退訓，已繳納之訓練費用退還半數","缺課時數逾總訓練時數四分之一以上者得補課，補課後仍缺課者退還全部費用"],"a",
 "第6條：缺課時數逾總訓練時數四分之一以上者應予退訓，其已繳納之訓練費用不予退還。第8條另定測驗以一百分為滿分、七十分為及格，各科均及格者為訓練合格。",
 "What absence leads to dismissal from the training, and are fees refunded?",
 ["Absence over one fourth of total hours means dismissal, and fees already paid are not refunded","Absence over one third of total hours means dismissal, and fees already paid must be refunded","Absence over one fifth of total hours means dismissal, and half of the fees paid is refunded","Absence over one fourth of total hours allows make-up classes with a full refund if repeated"],
 "Article 6."),

(A,"第7條",3,"專業應變人員-資格認可",
 "本辦法施行前已參加符合附件一專業訓練者，如何取得同等級資格？何種情形得免測驗？",
 ["得於施行後六個月內檢具申請書及佐證資料向中央主管機關申請認可，經測驗合格核發證書；具十年以上事故應變實務經驗且有證明文件者免測驗","得於施行後三個月內檢具申請書及佐證資料向直轄市主管機關申請認可，經測驗合格核發證書；具五年以上事故應變實務經驗者一律免測驗","得於施行後一年內檢具申請書及佐證資料向原訓練機構申請認可，免測驗即核發證書；具十年以上實務經驗者尚須參加補正訓練後始得核發","得於施行後六個月內檢具申請書向中央主管機關申請認可，須重新參加全程訓練並經測驗合格；具三年以上實務經驗者得免參加該項訓練"],"a",
 "第7條：本辦法施行前參加各級主管機關、目的事業主管機關、法人或團體符合附件一之專業訓練者，得於施行後六個月內檢具申請書及佐證資料向中央主管機關申請同等級資格認可，經測驗合格核發合格證書；但具十年以上事故應變實務工作經驗且有證明文件者，得免測驗。第8條第2項並定該同等級認可測驗補考以一次為限。",
 "How may earlier trainees obtain equivalent level status, and who is exempt from the test?",
 ["Apply to the central authority within six months with supporting papers and pass a test; those with over ten years of response experience are exempt from the test","Apply to the municipal authority within three months with supporting papers and pass a test; those with over five years of response experience are all exempt from it","Apply to the original training body within one year with supporting papers and get the certificate without a test; ten years of experience requires remedial training","Apply to the central authority within six months and repeat the whole training course and test; those with over three years of experience are exempt from training"],
 "Article 7."),

(A,"第8條",3,"專業應變人員-測驗及格",
 "專業應變人員證照訓練之測驗成績如何評定？科目不及格者得如何補救？",
 ["以一百分為滿分七十分為及格，各科均及格為訓練合格；不及格科目得於結訓之日起一年內申請補考二次","以一百分為滿分六十分為及格，各科均及格為訓練合格；不及格科目得於結訓之日起二年內申請補考三次","以一百分為滿分八十分為及格，總平均及格即為合格；不及格科目得於結訓之日起六個月內申請補考一次","以一百分為滿分七十分為及格，總平均及格即為合格；不及格科目應重新參加全程訓練後再行辦理測驗"],"a",
 "第8條第1項：測驗以一百分為滿分、七十分為及格，各科目成績均達及格標準者為訓練合格。第2項：不及格者自結訓之日起一年內得申請該科目補考二次，屆期未補考者該科目為不及格。第3項並定補考後仍不及格者，得於最後一次補考結束之日起三個月內申請補訓練一次。",
 "How are test scores graded and what remedy exists for a failed subject?",
 ["Out of 100 with 70 as pass and every subject must pass; failed subjects may be retaken twice within one year of completion","Out of 100 with 60 as pass and every subject must pass; failed subjects may be retaken three times within two years of completion","Out of 100 with 80 as pass and only the average must pass; failed subjects may be retaken once within six months of completion","Out of 100 with 70 as pass and only the average must pass; failed subjects require repeating the entire training course again"],
 "Article 8, paragraphs 1 to 3."),

(A,"第9條",2,"專業應變人員-成績複查",
 "參訓者對測驗成績有異議時，應於何時、以何方式申請複查？次數有無限制？",
 ["於成績通知單送達之翌日起三十日內以書面向中央主管機關申請複查，申請複查以一次為限","於成績通知單送達之翌日起十五日內以書面向直轄市主管機關申請複查，複查次數以二次為限","於成績通知單送達之翌日起六十日內以口頭向原訓練機構申請複查，複查次數則無任何限制","於成績通知單送達之翌日起三十日內以書面向原訓練機構申請複查，並得同時申請重新測驗"],"a",
 "第9條：參加證照訓練及再訓練者對測驗成績有異議，得於成績通知單送達之翌日起三十日內以書面向中央主管機關申請複查，申請複查以一次為限。第10條並定訓練合格者應於接獲通知之翌日起三個月內申請核發合格證書。",
 "When, how and how often may a trainee ask for a score review?",
 ["In writing to the central competent authority within 30 days after the score notice is served, only once","In writing to the municipal competent authority within 15 days after the notice is served, up to twice","Orally to the original training body within 60 days after the score notice is served, with no limit","In writing to the original training body within 30 days after the notice, with a retest also possible"],
 "Article 9."),

(A,"第10條",2,"專業應變人員-證書核發",
 "訓練合格者應於何時申請核發合格證書？逾期未申請且訓練課程或內容有變更者，應如何處理？",
 ["應於接獲通知之翌日起三個月內申請核發；逾期未申請而課程或內容有變更者，應就變更部分參加補正訓練合格後始得申請","應於接獲通知之翌日起六個月內申請核發；逾期未申請而課程或內容有變更者，應重新參加全部課程訓練合格後始得申請","應於接獲通知之翌日起一個月內申請核發；逾期未申請者其訓練成績即行失效，須重新報名參加該等級之證照訓練","應於結訓之日起三個月內申請核發；逾期未申請而課程有變更者，仍得逕行申請核發證書並於次年度補正其訓練"],"a",
 "第10條第1項：訓練合格者應於接獲通知之翌日起三個月內向中央主管機關申請核發合格證書。第2項：未於期限內申請者，其所參加之訓練課程或內容有變更時，應就變更部分參加補正訓練合格後始得申請。",
 "When must a qualified trainee apply for the certificate, and what if courses changed meanwhile?",
 ["Within three months after the notice is received; if courses changed, remedial training on the changed part must be passed first","Within six months after the notice is received; if courses changed, the whole training course must be taken and passed again","Within one month after the notice is received; otherwise the results lapse and the level training must be enrolled in again","Within three months after completion; if courses changed the certificate still issues and training is made up next year"],
 "Article 10."),

(A,"第11條",3,"專業應變人員-再訓練",
 "自一百十三年一月一日起，取得合格證書並登載為專業應變人員者，其再訓練義務為何？",
 ["登載者應每年度完成再訓練；一年內未登載者應於到職翌日起六個月內完成再訓練，因故未能參加者應於報到日前書面申請延訓","登載者應每二年度完成再訓練；一年內未登載者應於到職翌日起三個月內完成再訓練，因故未能參加者得於事後補行申請延訓","登載者應每三年度完成再訓練；二年內未登載者應於到職翌日起一年內完成再訓練，因故未能參加者免申請延訓即可展延","登載者應每年度完成再訓練；一年內未登載者應於到職當日起十五日內完成再訓練，因故未能參加者應向原訓練機構申請延訓"],"a",
 "第11條第1項：自一百十三年一月一日起，取得合格證書並登載為相關運作人或應變、諮詢機構之專業應變人員者，應每年度完成再訓練。第2項：一年內未登載者，應於到職之翌日起六個月內完成再訓練；因故未能參加者，應於報到日前以書面敘明原因向直轄市、縣（市）或原認證主管機關申請延訓。第23條並定連續二年度未再訓練且未申請延訓者廢止其證書。",
 "From 2024, what retraining duty applies to certificate holders who are listed as responders?",
 ["Retraining every year once listed; if not listed within a year, retraining within six months of taking the post, with written deferral sought before reporting","Retraining every two years once listed; if not listed within a year, retraining within three months of taking the post, with deferral applied for afterwards","Retraining every three years once listed; if not listed within two years, retraining within one year of the post, with deferral granted without application","Retraining every year once listed; if not listed within a year, retraining within fifteen days of the post, with deferral sought from the training body"],
 "Article 11, paragraphs 1 and 2."),

(A,"第12條",1,"專業應變人員-再訓練課程",
 "各級專業應變人員再訓練之訓練時數及課程大綱，本辦法如何規定？",
 ["明定於附件二，訓練機關（構）應使用中央主管機關指定之教材或依其擬定教材","明定於附件一，與證照訓練之時數及課程大綱完全相同並適用相同教材","由中央主管機關每年公告，訓練機關（構）得視需要自行增減訓練時數","由直轄市、縣（市）主管機關依轄區事故類型分別訂定並報中央備查"],"a",
 "第12條：各級專業應變人員再訓練之訓練時數及課程大綱如附件二。第22條第2項並定受託訓練機關（構）應使用中央主管機關指定之教材，或依附件一及附件二之訓練時數及課程大綱擬定教材。",
 "How are the hours and outline for responder retraining prescribed?",
 ["Set in Annex 2, with training bodies using materials designated by the central authority or drawn from it","Set in Annex 1, identical in hours and outline to certification training and using the same materials","Announced yearly by the central authority, with training bodies free to raise or cut the hours as needed","Set separately by municipal and county authorities by local incident types and filed with the center"],
 "Article 12 refers to Annex 2."),

(A,"第13條",3,"專業應變人員-登載人數",
 "製造、使用、貯存毒性及具危害性關注化學物質之運作人，任一日運作量逾附件三高階運作總量者，運作場所應登載之專業應變人員為何？",
 ["應登載五人以上，其中指揮級、專家級、操作級各一人以上及技術級二人以上","應登載五人以上，其中指揮級、專家級各二人以上及技術級一人以上即為足夠","應登載三人以上，其中技術級二人以上及操作級一人以上，無須登載指揮級","應登載八人以上，其中指揮級二人、專家級二人及技術級四人以上並設主管"],"a",
 "第13條第1款：逾附件三高階運作總量者，運作場所應登載五人以上，其中指揮級、專家級、操作級各一人以上及技術級二人以上。第2款逾低階未逾高階者登載三人以上（技術級二人以上、操作級一人以上）；第3款逾分級運作量或第四類逾五百公斤者二人以上；第4款未逾者通識級一人以上。",
 "For sites exceeding the high tier total operating volume in Annex 3, what responders must be listed?",
 ["At least five persons, including one each at command, specialist and operational level plus two technicians","At least five persons, including two each at command and specialist level plus one technician is enough","At least three persons, including two technicians and one operational level, with no command level needed","At least eight persons, including two command, two specialist and four technicians with a supervisor"],
 "Article 13, subparagraph 1."),

(A,"第14條",3,"專業應變人員-運送登載",
 "應組設全國性聯防組織之相關運作人，單一物質單次運送跨直轄市、縣（市）而氣體數量逾八百公斤者，依責任區範圍應登載之人員為何？",
 ["應登載五人以上，其中指揮級及專家級各二人以上、技術級一人以上","應登載五人以上，其中指揮級及技術級各二人以上、專家級一人以上","應登載三人以上，其中專家級二人以上、技術級一人以上即為已足","應登載二人以上，其中技術級及操作級各一人以上另置通識級一人"],"a",
 "第14條第1款：氣體數量逾八百公斤者，應登載五人以上，其中指揮級及專家級各二人以上、技術級一人以上；液體逾十公噸、固體逾二十公噸者亦登載五人以上，惟為指揮級及技術級各二人以上、專家級一人以上。第2款中量者三人以上（專家級二人以上、技術級一人以上），第3款小量者通識級一人以上。",
 "For a single cross-jurisdiction shipment of gas over 800 kg, what responders must be listed?",
 ["At least five persons, including two at command level, two at specialist level and one technician","At least five persons, including two at command level, two technicians and one specialist level","At least three persons, including two at specialist level and one technician, which suffices","At least two persons, one technician and one operational level, plus one awareness level person"],
 "Article 14, subparagraph 1."),

(A,"第15條",3,"專業應變人員-委託應變",
 "相關運作人委託應變機構執行應變時，其自主應變量能之登載規定為何？",
 ["符合第十三條第一款或第十四條第一款者，應登載技術級二人以上；符合第十三條第三款者，應登載操作級一人以上","符合第十三條第一款或第十四條第一款者，應登載指揮級二人以上；符合第十三條第三款者，應登載技術級二人以上","既已委託應變機構執行應變，即免除登載專業應變人員之義務，僅須留存委託契約及費用單據備查","一律應登載通識級一人以上即可，並得由受託之應變機構代為登載於中央主管機關指定網站"],"a",
 "第15條：委託應變機構執行應變者仍應有一定自主應變量能，符合第13條第1款或第14條第1款者技術級二人以上；符合第13條第2款或第14條第2款者技術級及操作級各一人以上；符合第13條第3款者操作級一人以上。第16條第1項並定同時符合數款者應依最高等級登載。",
 "Where an operator commissions a response body, what self-response capacity must still be listed?",
 ["Those under Article 13(1) or 14(1) list two technicians; those under Article 13(3) list one operational level person","Those under Article 13(1) or 14(1) list two command level staff; those under Article 13(3) list two technicians","Commissioning a response body removes the listing duty entirely, and only the contract and invoices are kept","Only one awareness level person need be listed, and the commissioned body may do the listing on the website"],
 "Article 15."),

(A,"第16條",2,"專業應變人員-等級代替",
 "登載之專業應變人員等級同時符合第十三條至第十五條各款規定時應如何登載？各級別得否以其他級別代之？",
 ["應依各款規定之最高等級登載；通識級得由操作級以上代之，操作級得由技術級以上代之，技術級得由專家級代之","應依各款規定之最低等級登載；通識級得由操作級以上代之，操作級得由技術級以上代之，技術級得由指揮級代之","應依各款規定分別重複登載；各級別均不得以其他級別代之，須依各該等級分別派訓合格人員擔任","應由運作人自行擇一款登載；通識級得由技術級代之，操作級得由通識級代之，技術級得由操作級代之"],"a",
 "第16條第1項：同時符合第13條至第15條各款規定者，應依各款規定之最高等級登載專業應變人員。第2項：通識級得由操作級、技術級、指揮級或專家級為之；操作級得由技術級、指揮級或專家級為之；技術級得由專家級為之。",
 "How to list when several subparagraphs apply, and may levels be substituted?",
 ["List at the highest level required; awareness may be met by operational or above, operational by technician or above, technician by specialist","List at the lowest level required; awareness may be met by operational or above, operational by technician or above, technician by command level","List separately under every applicable subparagraph; no level may be substituted and each needs its own separately trained qualified staff","The operator picks any one subparagraph; awareness may be met by technician, operational by awareness, and technician by operational level"],
 "Article 16."),

(A,"第17條",2,"專業應變人員-登載期日",
 "相關運作人自何時起應將符合規定之專業應變人員訓練合格人數及等級登載於何處？",
 ["自中華民國一百十二年七月一日起，登載於中央主管機關指定之網站","自中華民國一百十三年一月一日起，登載於中央主管機關指定之網站","自中華民國一百十年七月一日起，登載於直轄市主管機關指定之網站","自中華民國一百十二年七月一日起，以書面報請當地主管機關備查"],"a",
 "第17條：相關運作人應於一百十二年七月一日起，將符合第13條、第14條或第15條規定之專業應變人員訓練合格人數及等級，登載於中央主管機關指定之網站。第24條第1項第1款並定一年內二次未依規定等級人數登載者，依本法第五十九條第十三款處罰。",
 "From when and where must operators list the number and levels of qualified responders?",
 ["From 1 July 2023, on the website designated by the central competent authority","From 1 January 2024, on the website designated by the central competent authority","From 1 July 2021, on the website designated by the municipal competent authority","From 1 July 2023, by written filing with the local authority for record keeping"],
 "Article 17."),

(A,"第18條",2,"專業應變人員-常駐要求",
 "相關運作人登載通識級、操作級或技術級之專業應變人員，對其僱用及駐點有何要求？",
 ["該等人員應受僱於該運作人，且應常駐於運作場所執行專業應變人員業務","該等人員得由承攬廠商員工兼任，且僅須於事故發生時到場執行應變業務","該等人員得受僱於應變機構，並以每週到場二日以上駐點方式執行業務","該等人員應受僱於該運作人，惟得常駐於總公司並以遠端方式指揮應變"],"a",
 "第18條：相關運作人登載通識級、操作級或技術級之專業應變人員，應受僱且常駐於運作場所執行業務。第24條第1項第2款並定登載之上開人員未常駐運作場所者，依本法第五十九條第十三款規定處罰。",
 "What employment and stationing rules apply to listed awareness, operational or technician staff?",
 ["They must be employed by that operator and stationed at the operation site performing their duties","They may be contractor employees serving concurrently and need only attend the site when an incident occurs","They may be employed by a response body and station on site at least two days a week to perform duties","They must be employed by that operator but may stay at headquarters and direct the response remotely"],
 "Article 18."),

(A,"第19條",2,"專業應變人員-再訓練備查",
 "相關運作人或應變、諮詢機構對其專業應變人員之再訓練負有何種義務？完成後應於幾日內報請備查？",
 ["不得規避、妨礙或拒絕其參加再訓練；並應於再訓練完成後十五日內檢具證明文件報請主管機關備查","不得規避、妨礙或拒絕其參加再訓練；並應於再訓練完成後三十日內檢具證明文件報請主管機關備查","得視營運需要暫緩其參加再訓練；並應於再訓練完成後十五日內檢具證明文件報請主管機關核定","不得規避、妨礙或拒絕其參加再訓練；惟證明文件僅須自行保存三年，無須報請主管機關備查"],"a",
 "第19條第1項：相關運作人或應變、諮詢機構不得規避、妨礙或拒絕其專業應變人員參加第11條之再訓練。第2項：應於第11條第2項再訓練完成後十五日內，檢具證明文件報請直轄市、縣（市）或原認證主管機關備查。違反者依第24條第1項第3款、第4款處罰。",
 "What duty applies to retraining of responders, and when must proof be filed?",
 ["It may not evade, obstruct or refuse their retraining, and files proof with the authority within 15 days","It may not evade, obstruct or refuse their retraining, and files proof with the authority within 30 days","It may postpone their retraining for business needs, and files proof for approval within 15 days","It may not evade, obstruct or refuse their retraining, but keeps proof in house for three years only"],
 "Article 19."),

(A,"第20條",1,"專業應變人員-紀錄保存",
 "相關運作人依本法第三十七條第二項規定，應保存專業應變人員訓練紀錄多久？未保存有何後果？",
 ["應保存訓練紀錄三年，未依規定保存者依本法第五十九條第十三款規定處罰","應保存訓練紀錄五年，未依規定保存者依本法第五十九條第十三款規定處罰","應保存訓練紀錄一年，未依規定保存者僅由主管機關限期命其改善即可","應保存訓練紀錄十年，未依規定保存者依本法第五十一條規定處以停工"],"a",
 "第20條：相關運作人應依本法第三十七條第二項規定，保存訓練紀錄三年。第24條第1項第5款並定未依第20條保存訓練紀錄者，依本法第五十九條第十三款規定處罰。",
 "How long must responder training records be kept, and what if they are not?",
 ["Three years, and failure to keep them is punished under Article 59, subparagraph 13 of the Act","Five years, and failure to keep them is punished under Article 59, subparagraph 13 of the Act","One year, and failure to keep them only leads to an order to correct within a set period","Ten years, and failure to keep them draws suspension of operations under Article 51 of the Act"],
 "Article 20."),

(A,"第21條",2,"專業應變人員-國外訓練認可",
 "本辦法施行前已取得符合美國聯邦法規29 CFR 1910.120（q）標準訓練合格證明者，如何取得我國合格證書？",
 ["得於本辦法施行後六個月內向中央主管機關申請核發同等級專業應變人員合格證書","得於本辦法施行後六個月內向直轄市主管機關申請核發指揮級應變人員合格證書","應重新參加我國各級專業應變人員證照訓練並經測驗合格後始得核發合格證書","得於本辦法施行後二年內向原認證主管機關申請換發同等級應變人員合格證書"],"a",
 "第21條第1項：取得符合美國聯邦法規29 CFR 1910.120（q）標準訓練合格證明、其他國家訓練合格證明經中央主管機關認可，或中央主管機關辦理訓練之合格證明者，得於本辦法施行後六個月內向中央主管機關申請核發同等級合格證書。第2項並定道路危險物品運送人員訓練證明書持有人得申請核發通識級合格證書，有效期限與該證明書一致。",
 "How may a holder of a 29 CFR 1910.120(q) training certificate obtain a domestic certificate?",
 ["Apply to the central authority within six months of promulgation for an equivalent level certificate","Apply to the municipal authority within six months of promulgation for a command level certificate","Take the domestic level certification training again and pass the test before a certificate is issued","Apply to the original certifying authority within two years to exchange it for an equivalent one"],
 "Article 21, paragraph 1."),

(A,"第22條",2,"專業應變人員-委託辦理",
 "中央主管機關辦理專業應變人員訓練、測驗及證書核發業務得如何為之？受託機構之教材有何要求？",
 ["得委託經指定之訓練機關（構）辦理；該機構應使用中央主管機關指定之教材或依附件一及附件二擬定教材","得委託經指定之訓練機關（構）辦理；該機構得自行編纂教材，並僅須於開訓後報中央主管機關備查","應由中央主管機關自行辦理不得委託；教材一律由中央主管機關統一編訂並無償提供各運作人使用","得委由直轄市、縣（市）主管機關辦理；教材應由各該地方主管機關依轄區產業特性分別訂定公告"],"a",
 "第22條第1項：中央主管機關得委託經指定之訓練機關（構）辦理訓練、測驗及證書核發相關業務。第2項：該訓練機關（構）應使用中央主管機關指定之教材，或依附件一及附件二之訓練時數及課程大綱擬定教材。",
 "How may the central authority carry out training, testing and certification, and what of materials?",
 ["It may commission designated training bodies, which use materials designated by the center or drawn from Annexes 1 and 2","It may commission designated training bodies, which may compile their own materials and merely file them after training starts","It must do everything itself without commissioning, and materials are compiled solely by the center and given out free","It may commission municipal and county authorities, whose materials are set locally by the industries in each area"],
 "Article 22."),

(A,"第23條",3,"專業應變人員-撤銷廢止",
 "專業應變人員有何情形，中央主管機關應撤銷或應廢止其合格證書？",
 ["以詐欺或違法方法取得證書、學經歷證明虛偽不實者撤銷；使他人利用其名義虛偽登載、連續二年度未再訓練且未申請延訓者廢止","以詐欺或違法方法取得證書、學經歷證明虛偽不實者廢止；使他人利用其名義虛偽登載、連續二年度未再訓練且未申請延訓者撤銷","以詐欺或違法方法取得證書者撤銷；連續一年度未參加再訓練者廢止，並得於繳納罰鍰後申請恢復其專業應變人員資格","學經歷證明文件虛偽不實者廢止；連續三年度未參加再訓練且未申請延訓者撤銷，其餘情形僅令其限期補正即為已足"],"a",
 "第23條第1項：以詐欺、脅迫或違法方法取得合格證書，或檢具之學經歷證明文件虛偽不實者，中央主管機關應撤銷其合格證書。第2項：使他人利用其名義虛偽委託或登載為專業應變人員，或經登載後連續二年度未參加再訓練且未依第11條第2項申請延訓者，應廢止其合格證書。",
 "When must a responder certificate be revoked, and when annulled?",
 ["Revoked for a certificate got by fraud or false credentials; annulled for lending one's name or two straight years without retraining or deferral","Annulled for a certificate got by fraud or false credentials; revoked for lending one's name or two straight years without retraining or deferral","Revoked for a certificate got by fraud; annulled after one year without retraining, with reinstatement possible once a fine has been duly paid","Annulled for false credentials; revoked after three straight years without retraining or deferral, other cases needing only timely correction"],
 "Article 23."),

(A,"第24條",3,"專業應變人員-罰則",
 "相關運作人有何情事依本法第五十九條第十三款規定處罰？其中所稱一年內如何計算？",
 ["一年內二次未依規定等級人數登載、登載人員未常駐、規避再訓練、未報備查或未保存紀錄；一年內指自違規之日往前回溯至第三百六十五日止","一年內三次未依規定等級人數登載、登載人員未常駐、規避再訓練、未報備查或未保存紀錄；一年內指自違規之日往前回溯至第一百八十日止","首次未依規定等級人數登載即予處罰、登載人員未常駐或未保存紀錄；一年內指以曆年一月一日起至十二月三十一日止為計算期間","一年內二次未依規定等級人數登載或未保存訓練紀錄；一年內指自本辦法施行之日起算至次年同日止，施行前之違規行為併計"],"a",
 "第24條第1項列舉五款依本法第五十九條第十三款處罰之情形：一年內二次未依第13條至第15條等級人數登載、依第18條登載之人員未常駐、違反第19條第1項規避妨礙拒絕再訓練、未依第19條第2項報請備查、未依第20條保存訓練紀錄。第2項：所稱一年內指本辦法施行後之違規行為，自違規之日往前回溯至第三百六十五日止。",
 "Which acts of an operator are punished under Article 59(13) of the Act, and how is the year counted?",
 ["Twice a year failing the level and headcount listing, non-resident staff, evading retraining, no filing or no records; the year counts back 365 days from the violation","Three times a year failing the level and headcount listing, non-resident staff, evading retraining, no filing or no records; the year counts back 180 days from it","A first failure of the level and headcount listing, non-resident staff or missing records is punished; the year means the calendar year from January to December","Twice a year failing the listing or keeping no records; the year runs from the day these Regulations took effect, and earlier violations are counted in as well"],
 "Article 24."),

(A,"第25條",1,"專業應變人員-施行日期",
 "毒性及關注化學物質專業應變人員管理辦法之施行日期為何？",
 ["本辦法自中華民國一百十年七月一日施行，並無另定過渡條款以延後適用","本辦法自中華民國一百零九年一月十六日施行，修正條文自發布日施行","本辦法自中華民國一百十二年七月一日施行，登載義務同日開始適用","本辦法自發布日施行，惟再訓練規定自一百十三年一月一日起適用之"],"a",
 "第25條：本辦法自中華民國一百十年七月一日施行。惟第11條再訓練義務自一百十三年一月一日起適用，第17條登載義務自一百十二年七月一日起適用，屬條文本身之適用日期規定。",
 "When did these Regulations on professional responders take effect?",
 ["They took effect on 1 July 2021, with no transitional clause deferring their application","They took effect on 16 January 2020, with amendments effective on the day of promulgation","They took effect on 1 July 2023, and the listing duty applies from that very same date","They took effect upon promulgation, with retraining rules applying from 1 January 2024"],
 "Article 25."),

# ===== ENV-191 毒性及關注化學物質環境事故專業應變諮詢機關（構）認證及管理辦法 =====
(B,"第1條",1,"應變諮詢機構-授權依據",
 "毒性及關注化學物質環境事故專業應變諮詢機關（構）認證及管理辦法之訂定依據為何？",
 ["依毒性及關注化學物質管理法第六條第二項及第三十七條第三項規定訂定","依毒性及關注化學物質管理法第六條第一項及第三十六條第二項規定訂定","依毒性及關注化學物質管理法第三十七條第一項及第四十條規定所訂定","依災害防救法第六條第二項及環境保護基本法第三十七條規定所訂定"],"a",
 "第1條：本辦法依毒性及關注化學物質管理法第六條第二項及第三十七條第三項規定訂定。第2條並定應變、諮詢人員限依專業應變人員管理辦法取得指揮級、專家級、技術級合格證書並常任於機構者。",
 "Which provisions authorize these Regulations on response and consulting bodies?",
 ["Article 6, paragraph 2 and Article 37, paragraph 3 of the Toxic and Concerned Chemical Substances Act","Article 6, paragraph 1 and Article 36, paragraph 2 of the Toxic and Concerned Chemical Substances Act","Article 37, paragraph 1 and Article 40 of the Toxic and Concerned Chemical Substances Act as amended","Article 6, paragraph 2 of the Disaster Prevention Act with Article 37 of the Basic Environment Act"],
 "Article 1."),

(B,"第2條",2,"應變諮詢機構-定義",
 "本辦法所稱應變機構與諮詢機構業務範圍有何區別？應變、諮詢人員限於何種等級？",
 ["應變機構於事故現場進行安全防護、緊急應變、偵檢、復原；諮詢機構提供安全資料表及危害防護資訊；人員限指揮級、專家級、技術級","應變機構提供安全資料表及危害防護資訊；諮詢機構於事故現場進行安全防護及緊急應變；人員限指揮級、專家級、操作級三種等級","應變機構於事故現場進行緊急應變及復原；諮詢機構負責事故調查及裁罰建議；人員限專家級及技術級，並得由通識級人員代理","應變機構與諮詢機構業務範圍相同並得互相支援；人員限取得任一等級專業應變人員合格證書者，不以常任於機構者為限"],"a",
 "第2條第1項：應變機構係於事故現場進行安全防護、緊急應變、偵檢、復原等作業之法人、機關（構）或團體；諮詢機構係提供安全資料表、化學物質危害、安全防護資訊等諮詢者。第2項：應變、諮詢人員指取得指揮級、專家級、技術級合格證書並常任於機構從事應變或諮詢之人員。",
 "How do response and consulting bodies differ, and which responder levels may staff them?",
 ["Response bodies do on-site protection, emergency response, detection and restoration; consulting bodies supply safety data sheets and hazard information; staff hold command, specialist or technician certificates","Response bodies supply safety data sheets and hazard information; consulting bodies do on-site protection and emergency response; staff hold command, specialist or operational level certificates","Response bodies do emergency response and restoration; consulting bodies handle accident investigation and penalty advice; staff hold specialist or technician certificates and awareness staff may stand in","Response and consulting bodies have identical scopes and may back each other up; staff may hold any level certificate and need not be permanently based at the body concerned"],
 "Article 2."),

(B,"第3條",2,"應變諮詢機構-資本額",
 "應變、諮詢機構之資格中，非公營事業之公司其實收資本額應達多少？",
 ["應變機構實收資本額新臺幣三千萬元以上；諮詢機構實收資本額新臺幣一千萬元以上","應變機構實收資本額新臺幣一千萬元以上；諮詢機構實收資本額新臺幣三千萬元以上","應變機構實收資本額新臺幣五千萬元以上；諮詢機構實收資本額新臺幣二千萬元以上","應變及諮詢機構之實收資本額均應達新臺幣一億元以上並另提存保證金備償"],"a",
 "第3條第1款：非公營事業之公司，其實收資本額應變機構新臺幣三千萬元以上、諮詢機構新臺幣一千萬元以上。同條並列財團法人或社團法人、公營事業或政府機關（構）、公私立大專以上校院及其他經主管機關認定者，均得為應變、諮詢機構。",
 "What paid-in capital must a private company have to be a response or consulting body?",
 ["Response bodies need paid-in capital of NTD 30 million or more, consulting bodies NTD 10 million or more","Response bodies need paid-in capital of NTD 10 million or more, consulting bodies NTD 30 million or more","Response bodies need paid-in capital of NTD 50 million or more, consulting bodies NTD 20 million or more","Both response and consulting bodies need NTD 100 million in capital and a deposited guarantee bond"],
 "Article 3, subparagraph 1."),

(B,"第4條",3,"應變諮詢機構-人員配置",
 "應變機構及諮詢機構應置之人員人數及等級為何？",
 ["應變機構應置應變人員十二人以上，含指揮級二人、專家級二人、技術級八人以上；諮詢機構應置八人以上，含專家級二人、技術級六人以上","應變機構應置應變人員十人以上，含指揮級一人、專家級三人、技術級六人以上；諮詢機構應置六人以上，含專家級一人、技術級五人以上","應變機構應置應變人員十二人以上，含指揮級四人、專家級四人、技術級四人以上；諮詢機構應置十人以上，含指揮級二人、技術級八人以上","應變機構應置應變人員八人以上，含專家級二人、技術級六人以上；諮詢機構應置十二人以上，含指揮級二人、專家級二人、技術級八人以上"],"a",
 "第4條第1項：應變機構應置應變人員十二人以上，含指揮級二人以上、專家級二人以上、技術級八人以上，其中以指揮級或專家級一人為主管。第2項：諮詢機構應置諮詢人員八人以上，含專家級二人以上、技術級六人以上，其中以專家級一人為主管。第13條並定人員異動應於三十日內補實。",
 "How many staff of what levels must response and consulting bodies employ?",
 ["Response bodies need at least 12 responders, with 2 command, 2 specialist and 8 technicians; consulting bodies need at least 8, with 2 specialist and 6 technicians","Response bodies need at least 10 responders, with 1 command, 3 specialist and 6 technicians; consulting bodies need at least 6, with 1 specialist and 5 technicians","Response bodies need at least 12 responders, with 4 command, 4 specialist and 4 technicians; consulting bodies need at least 10, with 2 command and 8 technicians","Response bodies need at least 8 responders, with 2 specialist and 6 technicians; consulting bodies need at least 12, with 2 command, 2 specialist and 8 technicians"],
 "Article 4."),

(B,"第5條",2,"應變諮詢機構-認證文件",
 "申請應變機構認證者，除申請書外應檢具之文件包括下列何者？",
 ["應變人員合格證書及勞保投保資料影本、任務編組及組織架構圖、個人防護與偵檢應變設備及車輛清冊、機構位置圖及配置圖","應變人員合格證書及勞保投保資料影本、任務編組及組織架構圖、通訊或資訊軟硬體設備清冊、機構位置圖及配置圖與所在位置","應變人員在職證明及最近三年財務報表、董監事名冊、應變績效統計表、主管機關前次評鑑結果及改善計畫書等文件影本","應變人員之體格檢查紀錄及保險單影本、與各級消防機關簽訂之支援協定、事故通報演練紀錄及責任區劃分說明等文件"],"a",
 "第5條列舉應變機構認證應檢具八款文件，包括申請書、符合第3條資格之證明、負責人身分證明、應變人員合格證書及勞保投保資料表與同意查詢同意書、經驗證明、任務編組及組織架構圖、依服務項目及區域配置之個人防護偵檢應變復原善後通訊軟硬體設備與車輛清冊，以及機構位置圖、配置圖及所在位置。",
 "Besides the application form, what must accompany an application for response body accreditation?",
 ["Copies of responder certificates and labor insurance data, task organization and chart, an inventory of protection, detection, response gear and vehicles, and site maps","Copies of responder certificates and labor insurance data, task organization and chart, an inventory of communication or information hardware and software, and site maps","Responder employment proof and three years of financial statements, a director roster, performance statistics, and the last review result with an improvement plan","Responder physical examination records and insurance policies, support agreements with fire agencies, notification drill records, and a service area description"],
 "Article 5."),

(B,"第6條",2,"應變諮詢機構-諮詢文件",
 "申請諮詢機構認證者，其應檢具之設備清冊與應變機構有何不同？",
 ["諮詢機構僅須依申請服務項目及區域配置通訊或資訊等軟體、硬體設備並製成清冊，無須配置偵檢、復原及車輛等設備","諮詢機構須配置個人防護、偵檢、應變、復原、善後及通訊等軟硬體設備與車輛，其範圍與應變機構完全相同並無不同","諮詢機構僅須檢具負責人身分證明及機構位置圖，無須檢具任何設備清冊，亦免附相關證明文件影本供主管機關審查","諮詢機構須另行配置移動式實驗室及氣體偵測車，並檢附各項設備之校正報告與保養紀錄以供現勘及實測時查核"],"a",
 "第6條第7款：諮詢機構應依申請服務項目及區域配置通訊或資訊等軟體、硬體設備，其名稱、規格、數量、放置地點、照片應製成清冊併附證明文件影本；相對於第5條第7款應變機構尚須配置個人防護、偵檢、應變、復原、善後等設備與車輛。其餘應檢具文件二者大致相同。",
 "How does the equipment inventory for a consulting body differ from that of a response body?",
 ["A consulting body lists only communication or information hardware and software for its service items and area, with no detection, restoration gear or vehicles","A consulting body must provide personal protection, detection, response, restoration, cleanup and communication gear and vehicles, exactly as a response body does","A consulting body files only the responsible person identification and a site map, with no equipment inventory and no supporting documents at all for review","A consulting body must also provide a mobile laboratory and a gas detection vehicle, with calibration reports and maintenance records for the site inspection"],
 "Article 6, subparagraph 7."),

(B,"第7條",2,"應變諮詢機構-受理機關",
 "應變、諮詢機構之認證，應向何機關提出申請？",
 ["應向機構所在地直轄市、縣（市）主管機關申請；服務區域涉及二直轄市、縣（市）以上者應向中央主管機關申請","應向機構所在地直轄市、縣（市）主管機關申請；服務區域涉及三直轄市、縣（市）以上者應向中央主管機關申請","一律應向中央主管機關申請認證；服務區域僅涉及單一直轄市、縣（市）者，得委由該地方主管機關代為審查","應向服務區域內任一直轄市、縣（市）主管機關申請；跨區服務者由各該地方主管機關會同辦理聯合審查作業"],"a",
 "第7條：應變、諮詢機構之認證應向機構所在地直轄市、縣（市）主管機關申請；服務區域涉及二直轄市、縣（市）以上者，應向中央主管機關申請。第8條並定書面審查與現勘、實測之審查期限。",
 "To which authority is an accreditation application for a response or consulting body made?",
 ["To the municipal or county authority where the body sits; to the central authority if the service area covers two or more municipalities or counties","To the municipal or county authority where the body sits; to the central authority if the service area covers three or more municipalities or counties","Always to the central competent authority; where the service area covers only one municipality or county, that local authority may review it on commission","To any municipal or county authority inside the service area; cross-area services are jointly reviewed by all the local authorities concerned together"],
 "Article 7."),

(B,"第8條",3,"應變諮詢機構-審查程序",
 "主管機關受理應變、諮詢機構認證申請之審查程序及期限為何？",
 ["書面審查應通知七日內繳費，繳費翌日起三十日內完成；現勘應通知七日內繳費，繳費翌日起九十日內完成，再自現勘通過翌日起九十日內完成實測","書面審查應通知十四日內繳費，繳費翌日起六十日內完成；現勘應通知十四日內繳費，繳費翌日起三十日內完成，再自現勘通過翌日起三十日內完成實測","書面審查應通知七日內繳費，繳費翌日起九十日內完成；現勘與實測應於書面審查通過翌日起三十日內一併完成，且不得再行延長審查期限","書面審查與現勘實測應於受理申請之日起一百八十日內全部完成；申請人並得於審查結果送達後始一次繳納全部審查費及證書費用"],"a",
 "第8條第1項第1款：主管機關應於收到申請資料後通知申請人七日內繳納審查費，並於繳費翌日起三十日內完成書面完整性審查。第2款：書面審查通過後通知七日內繳費，繳費翌日起九十日內完成現勘審查，並自現勘通過翌日起九十日內完成實測審查，必要時得延長三十日。第2項：未依期限繳費者駁回申請。",
 "What is the review procedure and time limit for accreditation applications?",
 ["Fee notice within 7 days and paper review within 30 days of payment; site visit fee notice within 7 days, visit within 90 days of payment, and field testing within 90 days after the visit passes","Fee notice within 14 days and paper review within 60 days of payment; site visit fee notice within 14 days, visit within 30 days of payment, and field testing within 30 days after the visit","Fee notice within 7 days and paper review within 90 days of payment; the site visit and field testing are both finished within 30 days after paper review passes, with no extension","Paper review, site visit and field testing are all completed within 180 days of acceptance, and all review and certificate fees are paid only after the result has been served"],
 "Article 8."),

(B,"第9條",3,"應變諮詢機構-補正限制",
 "書面審查文件不符規定或現勘、實測未通過者，補正次數及日數限制為何？證書於何時製作？",
 ["補正次數均以二次為限，書面審查補正總日數不得超過三十日，現勘實測補正總日數不得超過九十日；審查完成後十四日內製作證書","補正次數均以三次為限，書面審查補正總日數不得超過六十日，現勘實測補正總日數不得超過三十日；審查完成後三十日內製作證書","補正次數均以一次為限，書面審查與現勘實測補正總日數均不得超過九十日；審查完成後七日內製作證書並通知繳納證書費用","補正次數並無限制，惟補正日數應計入審查期限且總計不得超過一百二十日；審查完成後六十日內製作並逕行寄發認證證書"],"a",
 "第9條第1項：書面審查文件不符規定者應通知限期補正，補正以二次為限，補正日數不算入審查期限且總日數不得超過三十日。第2項：現勘或實測未通過者補正亦以二次為限，總日數不得超過九十日；屆期未補正或補正不完全者駁回。第3項：主管機關應於完成第8條、第12條審查後十四日內製作證書。",
 "What limits apply to corrections, and when is the certificate produced?",
 ["Corrections are capped at two rounds each, totaling no more than 30 days for paper review and 90 days for site visit and testing; the certificate is made within 14 days","Corrections are capped at three rounds each, totaling no more than 60 days for paper review and 30 days for site visit and testing; the certificate is made within 30 days","Corrections are capped at one round each, totaling no more than 90 days for both paper review and site testing; the certificate is made within 7 days and the fee noticed","Corrections are unlimited but their days count toward the review period, up to 120 days in all; the certificate is made and mailed within 60 days after the review ends"],
 "Article 9."),

(B,"第10條",2,"應變諮詢機構-證書記載",
 "應變、諮詢機構之認證證書，依規定應載明哪些事項？",
 ["機構名稱、負責人姓名、主管人員姓名、認證類別、服務項目、服務區域、主要裝備或設備、所在位置及有效期限","機構名稱、負責人姓名、應變人員全體名冊、實收資本額、營業額、服務區域、主要裝備或設備及機構所在位置","機構名稱、統一編號、董監事名單、認證類別、服務項目、收費標準、車輛牌照號碼、所在位置及證書有效期限","機構名稱、負責人姓名、主管人員學經歷、認證費用金額、服務項目、服務區域、投保金額及認證證書之編號"],"a",
 "第10條列舉認證證書應載明十款事項：機構名稱、負責人姓名、主管人員姓名、認證類別、服務項目、服務區域、主要裝備或設備、所在位置、有效期限及其他經主管機關指定事項。第12條並定其中部分事項變更時應於三十日內辦理變更。",
 "What must the accreditation certificate state?",
 ["Body name, responsible person, supervisor, certification category, service items, service area, main equipment, location and validity period","Body name, responsible person, a full roster of responders, paid-in capital, turnover, service area, main equipment and the location of the body","Body name, tax number, list of directors, certification category, service items, fee schedule, vehicle plate numbers, location and validity term","Body name, responsible person, supervisor credentials, certification fee amount, service items, service area, insured sum and certificate number"],
 "Article 10."),

(B,"第11條",1,"應變諮詢機構-有效期限",
 "應變、諮詢機構認證之有效期限為何？期滿仍繼續運作者應如何辦理？",
 ["認證有效期限為五年；期滿仍繼續運作者，應向主管機關重新申請認證","認證有效期限為三年；期滿仍繼續運作者，應向主管機關申請展延二年","認證有效期限為十年；期滿仍繼續運作者，僅須報請主管機關備查即可","認證有效期限為五年；期滿仍繼續運作者，得自動展延一次無須再申請"],"a",
 "第11條：應變、諮詢機構之認證有效期限為五年；期滿仍繼續運作者，應向主管機關重新申請認證。第14條並定變更認證類別或人員異動累計達申請時二分之一以上者，亦應重新辦理認證。",
 "How long is accreditation valid and what must a body do when it expires?",
 ["Five years, and a body that keeps operating must apply to the authority for accreditation anew","Three years, and a body that keeps operating must apply to the authority for a two year extension","Ten years, and a body that keeps operating need only file a record with the competent authority","Five years, and a body that keeps operating is extended once automatically without any application"],
 "Article 11."),

(B,"第12條",2,"應變諮詢機構-證書變更",
 "應變、諮詢機構認證證書之變更應於何時辦理？主管人員或服務項目變更者如何審查？",
 ["應於事實發生後三十日內辦理；主管人員或服務項目變更者應報請審查，惟得免辦理現勘","應於事實發生後十五日內辦理；主管人員或服務項目變更者應報請審查，並應一併辦理現勘","應於事實發生後六十日內辦理；主管人員或服務項目變更者僅須填具變更申請表送件即可","應於事實發生後三十日內辦理；主管人員或服務項目變更者應重新申請認證並辦理實測"],"a",
 "第12條第1項：認證證書之變更應於事實發生後三十日內辦理；機構名稱、負責人姓名等變更者填具變更申請表辦理；主管人員或服務項目變更者應報請審查，得免辦理現勘；服務區域、主要裝備設備或所在位置變更者應報請審查，得免辦理實測。第2項：未辦理者主管機關應限期命其辦理。",
 "When must certificate changes be filed, and how is a change of supervisor or service items reviewed?",
 ["Within 30 days of the event; a change of supervisor or service items goes for review but the site visit may be waived","Within 15 days of the event; a change of supervisor or service items goes for review and a site visit is required too","Within 60 days of the event; a change of supervisor or service items needs only a change application form filed","Within 30 days of the event; a change of supervisor or service items requires fresh accreditation and field testing"],
 "Article 12."),

(B,"第13條",3,"應變諮詢機構-人員異動",
 "應變、諮詢人員異動時機構應於何時聘請符合資格者並報備查？何種異動應辦理審查？",
 ["應於事實發生後三十日內聘請並檢具證明文件報請備查；專家級、指揮級異動或人員異動累計達申請時三分之一以上者應辦理審查","應於事實發生後十五日內聘請並檢具證明文件報請備查；專家級、指揮級異動或人員異動累計達申請時二分之一以上者應辦理審查","應於事實發生後六十日內聘請並檢具證明文件報請核定；技術級人員異動累計達申請時四分之一以上者應辦理審查並實測","應於事實發生後三十日內聘請並自行留存證明文件；任何等級人員異動均無須報請主管機關辦理審查或現勘作業"],"a",
 "第13條第1項：應變、諮詢人員異動，機構應於事實發生後三十日內聘請符合資格者並檢具證明文件報請主管機關備查；但專家級、指揮級人員異動，或人員異動累計達申請時三分之一以上者，應辦理審查，得免辦理現勘。第2項未辦理者主管機關應限期命其辦理。第14條並定異動累計達二分之一以上者應重新認證。",
 "When must staff turnover be filled and filed, and which turnover triggers a review?",
 ["Hire a qualified person within 30 days and file proof for the record; a change of specialist or command staff, or cumulative turnover of one third, needs review","Hire a qualified person within 15 days and file proof for the record; a change of specialist or command staff, or cumulative turnover of one half, needs review","Hire a qualified person within 60 days and file proof for approval; cumulative turnover of one quarter of technician staff needs review and field testing","Hire a qualified person within 30 days and keep the proof in house; no level of staff turnover requires any review or site visit by the authority at all"],
 "Article 13."),

(B,"第14條",2,"應變諮詢機構-重新認證",
 "應變、諮詢機構有何情形應重新辦理認證？",
 ["變更認證類別，或應變、諮詢人員異動人數累計達申請時二分之一以上者，應重新辦理認證","變更認證類別，或應變、諮詢人員異動人數累計達申請時三分之一以上者，應重新辦理認證","變更服務區域，或應變、諮詢人員異動人數累計達申請時四分之一以上者，應重新辦理認證","變更負責人姓名，或機構所在位置遷移至其他直轄市、縣（市）者，應重新辦理認證程序"],"a",
 "第14條：變更認證類別，或應變、諮詢人員異動人數累計達申請時二分之一以上者，應重新辦理認證。相對於第13條第1項，異動累計達三分之一以上者僅須辦理審查、得免現勘；第12條所定變更事項則僅須辦理變更登記。",
 "In which cases must a response or consulting body seek accreditation afresh?",
 ["Changing the accreditation category, or cumulative staff turnover reaching one half of the number at application","Changing the accreditation category, or cumulative staff turnover reaching one third of the number at application","Changing the service area, or cumulative staff turnover reaching one quarter of the number at application time","Changing the responsible person, or moving the premises into another municipality or county jurisdiction"],
 "Article 14."),

(B,"第15條",3,"應變諮詢機構-應變紀錄",
 "應變機構應按月記錄並保存三年之事項包括哪些？",
 ["環境事故應變件數；每一事故之廠場名稱、時間地點、類型、傷亡人數、肇事化學物質、發生狀況、應變狀況及善後復原；裝備設備及車輛異動情形","環境事故諮詢件數；每一諮詢項目名稱、諮詢方式、問題類別及其內容；諮詢所需之資訊及通訊設備種類異動情形等三款事項並保存五年備查","環境事故應變件數；每一事故之肇事者姓名、罰鍰金額、訴願結果；應變人員出勤時數統計及加班費核發紀錄等三款事項並保存三年","環境事故應變件數；每一事故之保險理賠金額、求償對象、和解內容；應變裝備採購金額與折舊攤提之明細帳冊等事項並保存十年"],"a",
 "第15條：應變機構應按月記錄環境事故應變件數，每一事故之廠（場）名稱、事故時間地點、類型、傷亡人數、肇事化學物質、發生狀況、應變狀況及善後復原，以及個人防護、偵檢、應變、復原、通訊等裝備設備及車輛之異動情形，並保存三年。第16條則為諮詢機構之按月記錄事項。",
 "What must a response body record monthly and keep for three years?",
 ["Number of response cases; for each incident the plant name, time, place, type, casualties, chemical involved, circumstances, response and restoration; and equipment and vehicle changes","Number of consulting cases; for each item the name, mode of consultation, question category and content; and changes in information and communication equipment, kept for five years","Number of response cases; for each incident the offender name, fine amount and appeal outcome; plus responder duty hour statistics and overtime payment records kept three years","Number of response cases; for each incident the insurance payout, party pursued and settlement terms; plus a ledger of equipment purchase cost and depreciation kept ten years"],
 "Article 15."),

(B,"第16條",2,"應變諮詢機構-諮詢紀錄",
 "諮詢機構應按月記錄並保存三年之事項為何？",
 ["環境事故諮詢件數；每一諮詢項目、名稱、諮詢方式、問題類別及其內容；諮詢所需之資訊及通訊設備種類之異動情形","環境事故應變件數；每一事故之廠場名稱、事故時間地點及類型；個人防護、偵檢、應變、復原、通訊裝備之異動情形","環境事故諮詢件數；每一諮詢對象之營利事業統一編號及收費金額；諮詢人員之出勤紀錄與教育訓練時數統計表","環境事故諮詢件數；每一諮詢案件之錄音檔案及通聯紀錄；機構每月營業收入、成本費用及損益之會計報表"],"a",
 "第16條：諮詢機構應按月記錄環境事故諮詢件數，每一諮詢項目、名稱、諮詢方式、問題類別及其內容，以及諮詢所需之資訊及通訊設備種類之異動情形，並保存三年。此與第15條應變機構之紀錄事項並列，二者保存期間均為三年。",
 "What must a consulting body record monthly and keep for three years?",
 ["Number of consulting cases; for each item the name, mode of consultation, question category and content; and changes in information and communication equipment types","Number of response cases; for each incident the plant name, time, place and type; and changes in personal protection, detection, response and communication equipment","Number of consulting cases; the tax number and fee charged for each client; and duty records plus training hour statistics for the consulting staff members employed","Number of consulting cases; audio files and call logs for every case; and monthly accounting statements of revenue, costs and profit or loss of the body itself"],
 "Article 16."),

(B,"第17條",3,"應變諮詢機構-撤銷廢止",
 "應變、諮詢機構在何種情形下，主管機關得撤銷或廢止其認證？",
 ["申請文件經撤銷或虛偽不實者得撤銷認證；資格文件經目的事業主管機關廢止、可歸責造成人員傷亡或環境污染、二次限期改善仍未辦理變更異動者得廢止","申請文件經撤銷或虛偽不實者得廢止認證；資格文件經目的事業主管機關廢止、可歸責造成人員傷亡或環境污染、一次限期改善仍未辦理變更異動者得撤銷","申請文件有誤寫誤算者即得撤銷其認證；未依限申報月報表、未參加主管機關講習或年度考評未達八十分者，主管機關均得逕予廢止其認證","僅於機構自行申請歇業時得廢止其認證；縱有造成人員傷亡或環境污染之情事，主管機關亦僅得命其限期改善而不得撤銷或廢止認證"],"a",
 "第17條第1項：檢送之申請文件經撤銷或有虛偽不實者，主管機關得撤銷其認證。第2項：第3條資格文件經目的事業主管機關廢止、經調查認定可歸責於機構而造成人員傷亡或環境污染事件、未依第12條第1項或第13條第1項辦理變更或異動經二次限期改善屆期未改善者，得廢止其認證。",
 "When may accreditation of a response or consulting body be revoked or annulled?",
 ["Revoked where filed documents are annulled or false; annulled where the qualification document is revoked by the sector authority, where casualties or pollution are attributable to it, or where two correction orders on changes go unheeded","Annulled where filed documents are annulled or false; revoked where the qualification document is revoked by the sector authority, where casualties or pollution are attributable to it, or where one correction order on changes goes unheeded","Revoked for mere clerical or arithmetic errors in the filings; annulled for late monthly reports, for missing an authority briefing, or for an annual performance rating below eighty points in any year","Annulled only when the body itself applies to close down; even where casualties or pollution occur the authority may only order correction within a period and may not revoke or annul the accreditation"],
 "Article 17."),

(B,"第18條",1,"應變諮詢機構-施行日期",
 "毒性及關注化學物質環境事故專業應變諮詢機關（構）認證及管理辦法之施行日期為何？",
 ["本辦法自發布日施行，並未另定延後生效之日期或過渡適用期間","本辦法自中華民國一百零九年三月三日起施行並回溯適用一年","本辦法自中華民國一百十年七月一日施行，與應變人員辦法同日","本辦法自發布後六個月施行，既有機構得於施行後一年內補正"],"a",
 "第18條：本辦法自發布日施行。相對之下，毒性及關注化學物質專業應變人員管理辦法第25條係定自中華民國一百十年七月一日施行，二者施行方式不同。",
 "When did these accreditation Regulations take effect?",
 ["They take effect on the day of promulgation, with no deferred date or transitional period set","They take effect on 3 March 2020 and apply retroactively for one year before that date","They take effect on 1 July 2021, the same day as the responder qualification regulations","They take effect six months after promulgation, existing bodies having one year to comply"],
 "Article 18."),
]
