# -*- coding: utf-8 -*-
Q = [
("OSH-42","第1條",1,"起重升降-總則",
 "起重升降機具安全規則之訂定法源依據為何？",
 ["職業安全衛生法第六條第三項","職業安全衛生法第十六條第四項","職業安全衛生法第二十三條第二項","職業安全衛生法第五條第三項"],"a",
 "第1條：本規則依職業安全衛生法第六條第三項規定訂定之。該項為雇主安全衛生設備及措施標準之授權依據。至於固定式起重機等機具之安全檢查構造標準，則另依同法第十六條第四項訂定。",
 "What is the statutory basis for the Safety Rules for Lifting Appliances?",
 ["Article 6, paragraph 3 of the Occupational Safety and Health Act","Article 16, paragraph 4 of the Occupational Safety and Health Act","Article 23, paragraph 2 of the Occupational Safety and Health Act","Article 5, paragraph 3 of the Occupational Safety and Health Act"],
 "Article 1: issued under Article 6(3) of the OSH Act."),

("OSH-42","第4條",2,"起重升降-適用範圍",
 "下列何種起重升降機具不適用本規則，而應依職業安全衛生設施規則辦理？",
 ["吊升荷重未滿零點五公噸之固定式起重機、移動式起重機及人字臂起重桿","吊升荷重未滿三公噸之固定式起重機、移動式起重機及人字臂起重桿","積載荷重未滿一公噸之升降機、營建用提升機及簡易提升機","升降路或導軌高度未滿二十公尺之營建用提升機及簡易提升機"],"a",
 "第4條：吊升荷重未滿零點五公噸之固定式起重機、移動式起重機及人字臂起重桿，積載荷重未滿零點二五公噸之升降機、營建用提升機及簡易提升機，及升降路或導軌高度未滿十公尺之營建用提升機，不適用本規則，改依職業安全衛生設施規則辦理。",
 "Which lifting appliance is excluded from these Rules and governed by the OSH Facilities Rules?",
 ["Fixed cranes, mobile cranes and derricks with a lifting load under 0.5 tonne","Fixed cranes, mobile cranes and derricks with a lifting load under 3 tonnes","Elevators, construction hoists and simple hoists with rated load under 1 tonne","Construction hoists and simple hoists with a guide rail height under 20 metres"],
 "Article 4 lists the appliances excluded from these Rules."),

("OSH-42","第6條",2,"起重升降-定義",
 "未具伸臂之固定式起重機，其額定荷重應如何認定？",
 ["自吊升荷重扣除吊鉤、抓斗等吊具之重量所得之荷重","自吊升荷重加計吊鉤、抓斗等吊具之重量所得之荷重","自積載荷重扣除吊鉤、抓斗等吊具之重量所得之荷重","自吊升荷重扣除鋼索及捲胴等機械部分之重量所得者"],"a",
 "第6條：未具伸臂之固定式起重機或未具吊桿之人字臂起重桿，額定荷重指自吊升荷重扣除吊鉤、抓斗等吊具之重量所得之荷重。具伸臂者則須再依構造材質、傾斜角、長度及吊運車位置決定最大荷重後扣除吊具重量。",
 "How is the rated load of a fixed crane without a jib determined?",
 ["The lifting load minus the weight of hooks, grabs and other lifting gear","The lifting load plus the weight of hooks, grabs and other lifting gear","The rated carrying load minus the weight of hooks, grabs and lifting gear","The lifting load minus the weight of ropes, drums and mechanical parts"],
 "Article 6: rated load equals lifting load less the lifting gear weight."),

("OSH-42","第7條",2,"起重升降-定義",
 "具有吊臂之吊籠，其積載荷重應以何種狀態計算？",
 ["於最小傾斜角狀態下，依構造材質於工作台上乘載人員或荷物上升之最大荷重","於最大傾斜角狀態下，依構造材質於工作台上乘載人員或荷物上升之最大荷重","於水平狀態下，依構造材質於工作台上乘載人員或荷物下降之最大荷重","於最小傾斜角狀態下，依構造材質於搬器上乘載人員之平均容許荷重"],"a",
 "第7條：具有吊臂之吊籠之積載荷重，指於其最小傾斜角狀態下，依其構造、材質，於其工作台上乘載人員或荷物上升之最大荷重。僅供下降使用之吊籠，則指工作台上所能承受之最大荷重。",
 "Under what condition is the rated carrying load of a jib-type suspended cage determined?",
 ["At the minimum inclination angle, the maximum load raised on the working platform","At the maximum inclination angle, the maximum load raised on the working platform","In the horizontal position, the maximum load lowered on the working platform","At the minimum inclination angle, the average permitted load carried in the car"],
 "Article 7 defines rated carrying load for jib-type cages."),

("OSH-42","第8條",2,"起重升降-定義",
 "升降機、簡易提升機、營建用提升機或吊籠之額定速率，係指何者？",
 ["搬器在積載荷重下，使其上升之最高速率","搬器在積載荷重下，使其下降之最高速率","搬器在無荷重狀態下，使其上升之平均速率","搬器在吊升荷重下，使其上升之最高速率"],"a",
 "第8條：升降機、簡易提升機、營建用提升機或吊籠之額定速率，指搬器在積載荷重下使其上升之最高速率；固定式起重機、移動式起重機或人字臂起重桿則指額定荷重下上升、直行、迴轉或橫行之各該最高速率。",
 "What is the rated speed for an elevator, hoist or suspended cage?",
 ["The maximum ascending speed of the car under the rated carrying load","The maximum descending speed of the car under the rated carrying load","The average ascending speed of the car under a no-load condition","The maximum ascending speed of the car under the crane lifting load"],
 "Article 8: rated speed is the maximum ascending speed at rated carrying load."),

("OSH-42","第9條",1,"起重升降-定義",
 "本規則所稱容許下降速率之定義為何？",
 ["於吊籠工作台上加予相當於積載荷重之重量，使其下降之最高容許速率","於吊籠工作台上加予相當於吊升荷重之重量，使其下降之最高容許速率","於升降機搬器上加予相當於積載荷重之重量，使其上升之最高容許速率","於吊籠工作台上加予相當於自重之重量，使其下降之平均容許速率"],"a",
 "第9條：容許下降速率，指於吊籠工作台上加予相當於積載荷重之重量，使其下降之最高容許速率。吊籠安全檢查構造標準第33條並要求設置在超過容許下降速度一點三倍前能自動控制速度之裝置。",
 "How is the permissible descending speed defined?",
 ["Maximum permitted descending speed with the rated carrying load on the platform","Maximum permitted descending speed with the crane lifting load on the platform","Maximum permitted ascending speed with the rated carrying load in the car","Average permitted descending speed with only the dead weight on the platform"],
 "Article 9 defines permissible descending speed for suspended cages."),

("OSH-42","第10條",3,"起重升降-固定式起重機",
 "固定式起重機經報經檢查機構放寬至荷重試驗之值時，該荷重試驗值如何計算？紀錄應保存幾年？",
 ["額定荷重一點二五倍；額定荷重超過二百公噸者為額定荷重加五十公噸；紀錄保存三年","額定荷重一點二七倍；額定荷重超過一百公噸者為額定荷重加五十公噸；紀錄保存三年","額定荷重一點二倍；額定荷重超過二百公噸者為額定荷重加二十公噸；紀錄保存一年","額定荷重一點五倍；額定荷重超過三百公噸者為額定荷重加五十公噸；紀錄保存五年"],"a",
 "第10條：固定式起重機不得超過額定荷重，必要時經事先實施荷重試驗並指定作業監督人員後，得報經檢查機構放寬至荷重試驗之值。該值為額定荷重一點二五倍之荷重（額定荷重超過二百公噸者為額定荷重加上五十公噸），荷重試驗紀錄應保存三年。",
 "How is the load-test value calculated when a fixed crane is permitted to exceed its rated load, and how long are records kept?",
 ["1.25 times rated load; over 200 tonnes, rated load plus 50 tonnes; records kept 3 years","1.27 times rated load; over 100 tonnes, rated load plus 50 tonnes; records kept 3 years","1.2 times rated load; over 200 tonnes, rated load plus 20 tonnes; records kept 1 year","1.5 times rated load; over 300 tonnes, rated load plus 50 tonnes; records kept 5 years"],
 "Article 10: load test value is 1.25 times rated load; records kept three years."),

("OSH-42","第13條",1,"起重升降-固定式起重機",
 "雇主對於固定式起重機之構造，應符合何項規定？",
 ["固定式起重機安全檢查構造標準","移動式起重機安全檢查構造標準","國家標準CNS 13628營建用提升機規定","升降機安全檢查構造標準之規定"],"a",
 "第13條：雇主對於固定式起重機之構造，應符合固定式起重機安全檢查構造標準。第25條則規定移動式起重機應符合移動式起重機安全檢查構造標準，第98條規定吊籠應符合吊籠安全檢查構造標準。",
 "Which standard must the construction of a fixed crane comply with?",
 ["The Safety Inspection and Construction Standards for Fixed Cranes","The Safety Inspection and Construction Standards for Mobile Cranes","National standard CNS 13628 governing construction site hoists","The Safety Inspection and Construction Standards for Elevators"],
 "Article 13 requires compliance with the fixed crane construction standards."),

("OSH-42","第14條",2,"起重升降-固定式起重機",
 "雇主對於固定式起重機之使用，就負荷條件應注意何事項？",
 ["負荷次數及吊升荷物重量不得超過設計時之負荷條件，並防止鋼材、接合處或銲接處變形折損","負荷次數不受限制，僅吊升荷物重量不得超過設計時之負荷條件，並防止鋼索斷裂","吊升荷物重量得超過設計負荷條件百分之十，但應防止接合處或銲接處變形折損","負荷次數及吊升荷物重量得由操作人員自行判斷，僅須每年檢查鋼材有無破斷"],"a",
 "第14條：雇主應注意固定式起重機之使用，其負荷次數及吊升荷物之重量，不得超過該起重機設計時之負荷條件，並應防止構造部分之鋼材、接合處或銲接處等發生變形、折損或破斷。第26條對移動式起重機有相同要求。",
 "What must be observed regarding the loading conditions of a fixed crane?",
 ["Load cycles and load weight must not exceed design conditions, and deformation prevented","Load cycles are unlimited; only load weight must stay within design conditions","Load weight may exceed design conditions by ten per cent if welds are checked","Operators may judge load cycles and weight, with steel checked once each year"],
 "Article 14: load cycles and weights must stay within design conditions."),

("OSH-42","第15條",2,"起重升降-固定式起重機",
 "固定式起重機之過捲預防裝置，雇主應調整何處之間距使其符合法定值？",
 ["吊具或其捲揚用槽輪上方與捲胴、槽輪及桁架等有碰撞之虞物體下方間","吊具或其捲揚用槽輪下方與地面及軌道等有碰撞之虞物體上方間","駕駛室頂部與建築物水平支撐、樑、橫樑等有碰撞之虞物體下方間","吊具最低位置與捲胴上所留置鋼索捲數之對應位置間之垂直距離"],"a",
 "第15條：固定式起重機之過捲預防裝置，其吊鉤、抓斗等吊具或該吊具之捲揚用槽輪上方，與捲胴、槽輪及桁架等（傾斜伸臂除外）有碰撞之虞物體下方間，應調整間距使符合法定值。構造標準第34條定為零點二五公尺以上，直動式為零點零五公尺以上。",
 "For an over-hoisting prevention device on a fixed crane, which clearance is adjusted?",
 ["Between the top of the lifting gear or its sheave and the underside of drums or girders","Between the bottom of the lifting gear or its sheave and the top of rails or ground","Between the top of the driver cabin and the underside of building beams or supports","Between the lowest hook position and the rope turns remaining on the winding drum"],
 "Article 15 concerns the clearance for over-hoisting prevention devices."),

("OSH-42","第16條",3,"起重升降-固定式起重機",
 "使用液壓為動力之固定式起重機所裝設之安全閥，應調整在何種壓力即能作用？",
 ["額定荷重以下之壓力，伸臂起重機為額定荷重最大值以下之壓力","吊升荷重以下之壓力，伸臂起重機為吊升荷重最大值以下之壓力","額定荷重一點二五倍以下之壓力，伸臂起重機為額定荷重以下者","積載荷重以下之壓力，伸臂起重機為額定荷重最小值以下之壓力"],"a",
 "第16條：使用液壓為動力之固定式起重機，應裝置防止液壓過度升高之安全閥，並調整在額定荷重（伸臂起重機為額定荷重之最大值）以下之壓力即能作用；但實施荷重試驗及安定性試驗時不在此限。第28條對移動式起重機規定為額定荷重之最大值以下。",
 "At what pressure must the relief valve of a hydraulic fixed crane operate?",
 ["At or below the pressure corresponding to the rated load, or its maximum for jib cranes","At or below the pressure corresponding to the lifting load, or its maximum for jib cranes","At or below 1.25 times the rated load pressure, or the rated load for jib cranes","At or below the rated carrying load pressure, or the minimum rated load for jib cranes"],
 "Article 16: the relief valve must act at or below rated load pressure."),

("OSH-42","第17條",2,"起重升降-固定式起重機",
 "伸臂固定式起重機之伸臂傾斜角有何限制？吊升荷重未滿三公噸者依何標準？",
 ["不得超過明細表內記載之範圍；未滿三公噸者以製造者指定之伸臂傾斜角為準","不得超過明細表內記載之範圍；未滿三公噸者以檢查機構指定之傾斜角為準","不得超過設計傾斜角之一點二五倍；未滿五公噸者以製造者指定之角度為準","不得超過明細表內記載範圍之百分之八十；未滿三公噸者由操作人員決定"],"a",
 "第17條：伸臂固定式起重機之使用，伸臂之傾斜角不得超過該起重機明細表內記載之範圍；但吊升荷重未滿三公噸者，以製造者指定之伸臂傾斜角為準。第33條對移動式起重機、第45條對人字臂起重桿有相同規定。",
 "What limits apply to the jib inclination angle of a jib-type fixed crane?",
 ["It may not exceed the range in the crane specification sheet; under 3 t, the maker sets it","It may not exceed the range in the specification sheet; under 3 t, the inspection body sets it","It may not exceed 1.25 times the design angle; under 5 t, the maker sets the angle","It may not exceed eighty per cent of the sheet range; under 3 t, the operator decides"],
 "Article 17 limits jib inclination to the specification sheet range."),

("OSH-42","第18條",1,"起重升降-固定式起重機",
 "雇主對於固定式起重機之額定荷重標示，應如何辦理？",
 ["於機身明顯易見處標示額定荷重，並使操作人員及吊掛作業者周知","於駕駛室內側標示吊升荷重，並僅使操作人員一人知悉即可","於吊鉤上標示積載荷重，並使廠內所有勞工均簽名確認知悉","於機身明顯易見處標示製造年月，並使檢查機構人員周知即可"],"a",
 "第18條：雇主對於固定式起重機，應於其機身明顯易見處標示其額定荷重，並使操作人員及吊掛作業者周知。額定荷重隨作業半徑改變之伸臂起重機，得標示最大作業半徑之額定荷重，並於操作室張貼荷重表及置備攜帶式荷重表。",
 "How must the rated load of a fixed crane be displayed?",
 ["Marked conspicuously on the crane body and made known to operators and slingers","Marked inside the cabin as lifting load and made known only to the single operator","Marked on the hook as rated carrying load and signed for by all plant workers","Marked conspicuously as the date of manufacture and made known to inspectors"],
 "Article 18 requires conspicuous marking of the rated load."),

("OSH-42","第21條",2,"起重升降-固定式起重機",
 "纜索固定式起重機作業時，為防止鋼索破損飛落或震脫彈出，應禁止人員進入何處？",
 ["有發生危害之虞之鋼索內角側","有發生危害之虞之鋼索外角側","駕駛室後方之機械室通道側","起重機軌道兩端之緩衝裝置處"],"a",
 "第21條：雇主於固定式起重機作業時，應採取防止人員進入吊舉物下方及吊舉物通過人員上方之設備或措施；於纜索固定式起重機作業時，為防止捲上用、橫行用鋼索通過槽輪或安裝部分發生破損飛落或震脫彈出，應禁止人員進入有發生危害之虞之鋼索內角側。",
 "During cable crane work, which area must personnel be kept out of?",
 ["The inner angle side of the wire ropes where hazards may occur","The outer angle side of the wire ropes where hazards may occur","The machine room passage behind the operator driving cabin","The buffer device area at both ends of the crane travel rails"],
 "Article 21 prohibits entry to the inner angle side of the ropes."),

("OSH-42","第23條",1,"起重升降-移動式起重機",
 "雇主對於移動式起重機之使用，關於荷重之基本限制為何？",
 ["不得超過額定荷重，本條並未設放寬規定","不得超過吊升荷重，但得經檢查機構放寬","不得超過積載荷重，但得經雇主同意放寬","不得超過額定荷重一點二五倍之荷重試驗值"],"a",
 "第23條：雇主對於移動式起重機之使用，不得超過額定荷重。與第10條固定式起重機及第41條人字臂起重桿不同，移動式起重機並無報經檢查機構放寬至荷重試驗值之例外規定。",
 "What is the basic load limit for using a mobile crane?",
 ["It must not exceed the rated load; no relaxation is provided here","It must not exceed the lifting load, but inspection bodies may relax it","It must not exceed the rated carrying load unless the employer agrees","It must not exceed the load-test value of 1.25 times the rated load"],
 "Article 23: mobile cranes must never exceed the rated load."),

("OSH-42","第24條",3,"起重升降-移動式起重機",
 "中型移動式起重機設置完成時應實施之荷重試驗及安定性試驗，其荷重倍數各為何？",
 ["荷重試驗為額定荷重一點二五倍，安定性試驗為額定荷重一點二七倍","荷重試驗為額定荷重一點二七倍，安定性試驗為額定荷重一點二五倍","荷重試驗為額定荷重一點二倍，安定性試驗為額定荷重一點五倍","荷重試驗為吊升荷重一點二五倍，安定性試驗為吊升荷重一點三倍"],"a",
 "第24條：中型移動式起重機設置完成時，應實施荷重試驗及安定性試驗。荷重試驗為額定荷重一點二五倍之荷重置於吊具上實施吊升、直行、旋轉或必要之走行等動作；安定性試驗為最不利安定條件下置於吊具上之額定荷重一點二七倍荷重。試驗紀錄應保存三年。",
 "What load multiples apply to the load test and stability test of a medium mobile crane?",
 ["Load test at 1.25 times rated load and stability test at 1.27 times rated load","Load test at 1.27 times rated load and stability test at 1.25 times rated load","Load test at 1.2 times rated load and stability test at 1.5 times rated load","Load test at 1.25 times lifting load and stability test at 1.3 times lifting load"],
 "Article 24 sets 1.25 and 1.27 multiples respectively."),

("OSH-42","第25條",1,"起重升降-移動式起重機",
 "雇主對於移動式起重機之構造，應符合何項規定？",
 ["移動式起重機安全檢查構造標準","固定式起重機安全檢查構造標準","國家標準CNS 13627升降機相關規定","吊籠安全檢查構造標準之相關規定"],"a",
 "第25條：雇主對於移動式起重機之構造，應符合移動式起重機安全檢查構造標準。相對地第13條規定固定式起重機應符合固定式起重機安全檢查構造標準。",
 "Which standard must a mobile crane comply with in construction?",
 ["The Safety Inspection and Construction Standards for Mobile Cranes","The Safety Inspection and Construction Standards for Fixed Cranes","National standard CNS 13627 relating to passenger elevators","The Safety Inspection and Construction Standards for Suspended Cages"],
 "Article 25 requires compliance with the mobile crane standards."),

("OSH-42","第26條",2,"起重升降-移動式起重機",
 "移動式起重機使用時，雇主對其設計負荷條件應注意何者？",
 ["負荷次數及吊升荷物重量不得超過設計時之負荷條件，並防止鋼材及銲接處變形破斷","僅吊升荷物重量不得超過設計時之負荷條件，負荷次數不列入管制範圍","負荷次數及吊升荷物重量得超過設計負荷條件，但應加強鋼材防蝕塗裝措施","負荷次數由製造者決定，吊升荷物重量則以檢查機構核定之值為上限"],"a",
 "第26條：雇主應注意移動式起重機使用時，其負荷次數及吊升荷物之重量，不得超過該起重機設計時之負荷條件，並應防止起重機構造部分之鋼材、接合處或銲接處等發生變形、折損或破斷。",
 "What must be observed about a mobile crane design loading condition?",
 ["Load cycles and load weight must stay within design conditions, preventing deformation","Only the load weight must stay within design conditions; cycles are not controlled","Cycles and weight may exceed design conditions if anti-corrosion coating is applied","The maker sets the load cycles and the inspection body caps the load weight"],
 "Article 26 mirrors Article 14 for mobile cranes."),

("OSH-42","第27條",2,"起重升降-移動式起重機",
 "移動式起重機之過捲預防裝置及過捲警報裝置，應調整何處之間距？",
 ["吊具或其捲揚用槽輪上方與伸臂前端槽輪及其他有碰撞之虞物體下方間","吊具或其捲揚用槽輪下方與外伸撐座及其他有碰撞之虞物體上方間","伸臂前端槽輪上方與駕駛室頂蓋及其他有碰撞之虞物體下方間","吊具最低位置與起伏裝置捲胴上留置鋼索捲數之對應位置間"],"a",
 "第27條：移動式起重機之過捲預防裝置及過捲警報裝置，其吊鉤、抓斗等吊具或該吊具之捲揚用槽輪上方，與伸臂前端槽輪及其他有碰撞之虞物體（傾斜之伸臂除外）下方間，應調整間距使符合法定值。",
 "Which clearance must be adjusted for a mobile crane over-hoisting device?",
 ["Between the top of the lifting gear or its sheave and the underside of the jib head sheave","Between the bottom of the lifting gear or its sheave and the top of the outriggers","Between the top of the jib head sheave and the underside of the operator cabin roof","Between the lowest hook position and the rope turns left on the luffing device drum"],
 "Article 27 concerns the over-hoisting clearance on mobile cranes."),

("OSH-42","第28條",2,"起重升降-移動式起重機",
 "使用液壓為動力之移動式起重機，其安全閥應調整在何種壓力即能作用？",
 ["額定荷重之最大值以下之壓力","額定荷重之最小值以下之壓力","吊升荷重之最大值以下之壓力","積載荷重之最大值以下之壓力"],"a",
 "第28條：使用液壓為動力之移動式起重機，應裝置防止液壓過度升高用之安全閥，此安全閥應調整在額定荷重之最大值以下之壓力即能作用；但實施荷重試驗及安定性試驗時，不在此限。",
 "At what pressure must a hydraulic mobile crane relief valve operate?",
 ["At or below the pressure corresponding to the maximum rated load","At or below the pressure corresponding to the minimum rated load","At or below the pressure corresponding to the maximum lifting load","At or below the pressure corresponding to the maximum carrying load"],
 "Article 28: the valve acts at or below the maximum rated load pressure."),

("OSH-42","第30條",2,"起重升降-移動式起重機",
 "移動式起重機作業範圍有地盤軟弱致有翻倒之虞時，雇主應如何處理？",
 ["不得使用該起重機作業，但鋪設具充分強度及足夠面積之鐵板或墊料可防止翻倒者除外","得繼續作業，但應將吊掛荷重降為額定荷重之二分之一並指派監視人員","得繼續作業，但應將外伸撐座縮回至最小寬度以降低翻倒力矩之影響","不得使用該起重機作業，且任何補強措施均不得作為繼續作業之依據"],"a",
 "第30條：移動式起重機在其作業範圍有地盤軟弱、埋設脆弱地下物或路肩崩塌等情形致有翻倒之虞者，不得使用該起重機從事作業；但在其下方鋪設具有充分強度及足夠面積之鐵板或墊料等可防止翻倒者，不在此限。第31條並要求確認外伸撐座支撐已置於鐵板中央範圍。",
 "What must be done when soft ground makes a mobile crane liable to overturn?",
 ["Work is prohibited unless steel plates or mats of adequate strength prevent overturning","Work may continue if the load is halved and a watch person is assigned to the job","Work may continue if the outriggers are retracted to their narrowest span setting","Work is prohibited absolutely and no reinforcement measure can permit continuing"],
 "Article 30 prohibits work on unstable ground unless reinforced."),

("OSH-42","第31條",2,"起重升降-移動式起重機",
 "使用外伸撐座之移動式起重機，其下方鋪有鐵板或墊料時，雇主應先確認何事項？",
 ["外伸撐座之支撐已置放於鐵板或墊料之中央範圍或不致翻倒之位置","外伸撐座之支撐已置放於鐵板或墊料之邊緣以增加接觸摩擦效果","鐵板或墊料之厚度已達五公分以上並經檢查機構人員簽認合格","鐵板或墊料已與地面以錨栓固定並由作業監督人員填寫檢點表"],"a",
 "第31條：使用外伸撐座之移動式起重機，其下方鋪有鐵板或墊料時，應先確認該外伸撐座之支撐已置放於鐵板或墊料之中央範圍，或位於不致造成該起重機有翻倒之虞之位置。",
 "What must be confirmed when steel plates are laid under crane outriggers?",
 ["That the outrigger pads rest within the central area of the plates or a safe position","That the outrigger pads rest on the plate edges to increase contact friction","That the plates are at least five centimetres thick and certified by an inspector","That the plates are anchored to the ground and a checklist has been completed"],
 "Article 31 requires outrigger pads to sit centrally on the plates."),

("OSH-42","第33條",2,"起重升降-移動式起重機",
 "具有伸臂之移動式起重機，其伸臂傾斜角之限制為何？",
 ["不得超過該起重機明細表內記載之範圍；吊升荷重未滿三公噸者以製造者指定者為準","不得超過該起重機明細表內記載之範圍；吊升荷重未滿五公噸者由操作人員決定","不得超過設計最大傾斜角之百分之九十；吊升荷重未滿三公噸者不受任何限制","不得超過檢查機構核定之傾斜角範圍；吊升荷重未滿一公噸者以雇主指定者為準"],"a",
 "第33條：具有伸臂之移動式起重機之使用，伸臂之傾斜角不得超過該起重機明細表內記載之範圍；但吊升荷重未滿三公噸者，以製造者指定之伸臂傾斜角為準。移動式起重機安全檢查構造標準第32條並要求設置傾斜角指示裝置。",
 "What limits the jib inclination angle of a mobile crane?",
 ["The range stated in the specification sheet; below 3 tonnes the maker sets the angle","The range stated in the specification sheet; below 5 tonnes the operator decides","Ninety per cent of the design maximum angle; below 3 tonnes there is no limit","The range approved by the inspection body; below 1 tonne the employer sets it"],
 "Article 33 mirrors Article 17 for mobile cranes."),

("OSH-42","第34條",1,"起重升降-移動式起重機",
 "移動式起重機之額定荷重隨作業半徑改變者，雇主得採取何種標示方式？",
 ["標示最大作業半徑之額定荷重，並於操作室張貼荷重表及置備攜帶式荷重表","標示最小作業半徑之額定荷重，並僅於機身外側噴漆註記吊升荷重數值","標示平均作業半徑之積載荷重，並於吊鉤上懸掛標示牌供吊掛者查閱","免予標示額定荷重，改由操作人員每次作業前口頭告知吊掛作業者"],"a",
 "第34條：雇主對於移動式起重機，應於其機身明顯易見處標示其額定荷重，並使操作人員及吊掛作業者周知；額定荷重隨作業半徑而改變者，得標示最大作業半徑之額定荷重，並採取於操作室張貼荷重表及置備攜帶式荷重表等措施。",
 "How may rated load be shown when it varies with the working radius?",
 ["Show the rated load at maximum radius and post a load chart in the operating cabin","Show the rated load at minimum radius and spray the lifting load on the body","Show the average radius carrying load and hang a plate on the crane hook","Omit the marking and have the operator tell the slinger before each lift"],
 "Article 34 allows marking at the maximum working radius plus load charts."),

("OSH-42","第35條",3,"起重升降-移動式起重機",
 "移動式起重機例外以搭乘設備吊升勞工時，搭乘設備連同人員之最大荷重上限及高處作業之限制為何？",
 ["不得超過作業半徑所對應額定荷重之百分五十；垂直高度超過二十公尺禁用直結式搭乘設備","不得超過作業半徑所對應額定荷重之百分之八十；垂直高度超過十公尺禁用直結式搭乘設備","不得超過作業半徑所對應吊升荷重之百分五十；垂直高度超過三十公尺禁用直結式搭乘設備","不得超過作業半徑所對應額定荷重之百分之三十；垂直高度超過二十公尺應加派監視人員"],"a",
 "第35條：移動式起重機以吊物為限，例外採防止墜落措施者，搭乘設備自重加上搭乘者、積載物之最大荷重不得超過該起重機作業半徑所對應額定荷重之百分五十，且垂直高度超過二十公尺之高處作業禁止使用直結式搭乘設備，但設有無線電通訊聯絡及作業監視或預防碰撞警報裝置者不在此限。",
 "What limits apply when a mobile crane exceptionally lifts workers in a carrier?",
 ["Max 50 per cent of the rated load at that radius; no direct-coupled carrier above 20 m","Max 80 per cent of the rated load at that radius; no direct-coupled carrier above 10 m","Max 50 per cent of the lifting load at that radius; no direct-coupled carrier above 30 m","Max 30 per cent of the rated load at that radius; a watch person is added above 20 m"],
 "Article 35 caps the carrier load at 50 per cent of the rated load."),

("OSH-42","第36條",3,"起重升降-移動式起重機",
 "移動式起重機所用搭乘設備之扶手高度及懸吊用鋼索安全係數規定為何？",
 ["周圍設高度九十公分以上扶手並設中欄杆及腳趾板；懸吊用鋼索安全係數應在十以上","周圍設高度七十五公分以上扶手並設中欄杆及腳趾板；懸吊用鋼索安全係數應在六以上","周圍設高度九十公分以上扶手但免設中欄杆及腳趾板；懸吊用鋼索安全係數應在五以上","周圍設高度一百二十公分以上扶手並設中欄杆及腳趾板；懸吊用鋼索安全係數應在四以上"],"a",
 "第36條：搭乘設備應有足夠強度且材料無損傷變形腐蝕；周圍設置高度九十公分以上之扶手，並設中欄杆及腳趾板；懸吊用鋼索或鋼線之安全係數應在十以上，吊鏈、吊帶及其支點之安全係數應在五以上；並應標示自重及最大荷重。",
 "What handrail height and rope safety factor apply to a crane worker carrier?",
 ["Handrails at least 90 cm high with mid-rails and toe boards; rope safety factor 10 or more","Handrails at least 75 cm high with mid-rails and toe boards; rope safety factor 6 or more","Handrails at least 90 cm high without mid-rails or toe boards; rope safety factor 5 or more","Handrails at least 120 cm high with mid-rails and toe boards; rope safety factor 4 or more"],
 "Article 36 sets 90 cm handrails and a rope safety factor of ten."),

("OSH-42","第37條",2,"起重升降-移動式起重機",
 "移動式起重機從事垂直高度二十公尺以下之高處作業時，第三十五條第一項但書之適用為何？",
 ["不適用該但書規定，但使用道路或鄰接道路作業者，不在此限","仍完全適用該但書規定，且使用道路作業者亦得依該但書辦理","不適用該但書規定，且使用道路或鄰接道路作業者亦一律不適用","僅於垂直高度十公尺以下者不適用，超過十公尺者一律得適用"],"a",
 "第37條：移動式起重機從事垂直高度二十公尺以下之高處作業，不適用第三十五條第一項但書規定；但使用道路或鄰接道路作業者，不在此限。換言之低於二十公尺原則上不得以起重機搭載人員，惟道路作業情形另有考量。",
 "How does the Article 35 proviso apply to mobile crane work below 20 metres height?",
 ["The proviso does not apply, except for work on or adjoining a public road","The proviso still fully applies, and road work may also rely on that proviso","The proviso does not apply, and road or adjoining road work is also excluded","Only work below 10 metres is excluded; above 10 metres the proviso applies"],
 "Article 37 disapplies the proviso below 20 metres except for road work."),

("OSH-42","第38條",3,"起重升降-移動式起重機",
 "移動式起重機吊掛搭乘設備載人作業時，設計簽認效期及試吊測試之規定為何？",
 ["委託認可專業機構簽認效期最長二年；試吊升至最大作業高度保持五分鐘以上確認平衡","委託認可專業機構簽認效期最長五年；試吊升至最大作業高度保持三分鐘以上確認平衡","委託檢查機構簽認效期最長二年；試吊升至一半作業高度保持十分鐘以上確認平衡","委託認可專業機構簽認效期最長一年；試吊升至最大作業高度保持一分鐘以上確認平衡"],"a",
 "第38條：搭乘設備及懸掛裝置應委託中央主管機關認可之專業機構簽認，效期最長二年，效期屆滿或構造變更應重新簽認；載人作業前應以預期最大荷重之荷物試吊，吊升至最大作業高度保持五分鐘以上確認平衡性及安全性，起重機移設位置者應重新試吊。作業時具外伸撐座者應全部伸出且不得走行。",
 "What certification period and trial lift requirements apply to crane man-riding work?",
 ["Certification by an approved body valid up to 2 years; trial lift held at least 5 minutes","Certification by an approved body valid up to 5 years; trial lift held at least 3 minutes","Certification by the inspection body valid up to 2 years; trial lift held at least 10 minutes","Certification by an approved body valid up to 1 year; trial lift held at least 1 minute"],
 "Article 38: two-year certification and a five-minute trial lift."),

("OSH-42","第39條",2,"起重升降-移動式起重機",
 "移動式起重機作業時，為防止上部旋轉體之旋轉動作引起碰撞危害，應採何措施？",
 ["禁止人員進入有發生碰撞危害之虞之起重機作業範圍內","禁止人員進入有發生碰撞危害之虞之鋼索內角側範圍內","僅須於上部旋轉體外緣張貼警告標示並設置反光標識","僅須指派一名指揮人員於旋轉半徑外以手勢引導作業"],"a",
 "第39條：雇主於移動式起重機作業時，應採取防止人員進入吊舉物下方及吊舉物通過人員上方之設備或措施；並為防止上部旋轉體之旋轉動作引起碰撞危害，應禁止人員進入有發生碰撞危害之虞之起重機作業範圍內。",
 "How must collision hazards from a mobile crane superstructure slewing be prevented?",
 ["Prohibit entry into the crane working range where collision hazards may occur","Prohibit entry into the inner angle side of the ropes where hazards may occur","Merely post warning signs and reflective markers on the slewing body edge","Merely assign one signaller outside the slewing radius to guide by hand signals"],
 "Article 39 prohibits entry into the slewing collision range."),

("OSH-42","第41條",3,"起重升降-人字臂起重桿",
 "人字臂起重桿經報經檢查機構放寬時，其荷重試驗值及紀錄保存期間為何？",
 ["額定荷重一點二五倍，超過二百公噸者為額定荷重加五十公噸；紀錄保存三年","額定荷重一點二七倍，超過二百公噸者為額定荷重加五十公噸；紀錄保存三年","額定荷重一點二五倍，超過一百公噸者為額定荷重加三十公噸；紀錄保存二年","額定荷重一點五倍，超過二百公噸者為額定荷重加一百公噸；紀錄保存五年"],"a",
 "第41條：人字臂起重桿不得超過額定荷重，必要時經事先實施荷重試驗確認無異狀並指定作業監督人員後，得報經檢查機構放寬至荷重試驗之值。該值為額定荷重一點二五倍（額定荷重超過二百公噸者為額定荷重加五十公噸），實施吊升、旋轉及吊桿起伏等動作，紀錄保存三年。",
 "What load-test value and record period apply when a derrick load limit is relaxed?",
 ["1.25 times rated load, or rated load plus 50 t above 200 t; records kept three years","1.27 times rated load, or rated load plus 50 t above 200 t; records kept three years","1.25 times rated load, or rated load plus 30 t above 100 t; records kept two years","1.5 times rated load, or rated load plus 100 t above 200 t; records kept five years"],
 "Article 41 mirrors Article 10 for derricks."),

("OSH-42","第42條",2,"起重升降-人字臂起重桿",
 "中型人字臂起重桿設置完成時，應實施何種試驗？其荷重為何？",
 ["應實施荷重試驗，以額定荷重一點二五倍之荷重實施吊升、旋轉及吊桿起伏動作","應實施荷重試驗及安定性試驗，分別以額定荷重一點二五倍及一點二七倍實施","應實施安定性試驗，以額定荷重一點二七倍之荷重實施吊升及吊桿起伏動作","應實施荷重試驗，以吊升荷重一點二倍之荷重實施直行及吊運車橫行動作"],"a",
 "第42條：雇主於中型人字臂起重桿設置完成時，應實施荷重試驗，確認安全後方得使用。荷重試驗指將相當於額定荷重一點二五倍之荷重置於吊具上，實施吊升、旋轉及吊桿之起伏等動作之試驗；試驗紀錄應保存三年。與中型固定式起重機不同，本條未要求安定性試驗。",
 "What test is required when a medium derrick is newly installed?",
 ["A load test at 1.25 times rated load covering hoisting, slewing and boom luffing","Both a load test at 1.25 times and a stability test at 1.27 times the rated load","A stability test at 1.27 times rated load covering hoisting and boom luffing","A load test at 1.2 times lifting load covering travelling and trolley traversing"],
 "Article 42 requires only a 1.25 times load test for medium derricks."),

("OSH-42","第43條",2,"起重升降-人字臂起重桿",
 "人字臂起重桿之吊升裝置及起伏裝置應設過捲預防裝置，何種情形不在此限？",
 ["使用絞車為動力之吊升裝置及起伏裝置者","使用液壓為動力之吊升裝置及起伏裝置者","吊升荷重未滿三公噸之吊升裝置及起伏裝置","主柱長度未滿十二公尺之吊升及起伏裝置"],"a",
 "第43條：雇主對於人字臂起重桿之吊升裝置及起伏裝置，應設過捲預防裝置；但使用絞車為動力之吊升裝置及起伏裝置者，不在此限。第44條並定其間距為零點二五公尺以上，直動式為零點零五公尺以上。",
 "Which derrick hoisting or luffing device is exempt from an over-hoisting device?",
 ["Those powered by a winch as the source of driving power","Those powered by hydraulic pressure as the driving power","Those with a lifting load of less than three tonnes in total","Those whose main mast is shorter than twelve metres in length"],
 "Article 43 exempts winch-powered hoisting and luffing devices."),

("OSH-42","第45條",1,"起重升降-人字臂起重桿",
 "具有吊桿之人字臂起重桿，其吊桿傾斜角之限制為何？",
 ["不得超過該起重桿明細表內記載之範圍，吊升荷重未滿三公噸者依製造者指定","不得超過該起重桿明細表內記載之範圍，吊升荷重未滿三公噸者不受限制","不得超過該起重桿設計傾斜角之一點二五倍，未滿三公噸者依雇主指定","不得超過檢查機構核定之傾斜角範圍，未滿五公噸者依作業主管指定"],"a",
 "第45條：具有吊桿之人字臂起重桿之使用，吊桿傾斜角不得超過該人字臂起重桿明細表內記載之範圍；但吊升荷重未滿三公噸者，以製造者指定之傾斜角為準。第55條並要求設置吊桿傾斜角之指示裝置。",
 "What limits the boom inclination angle of a derrick with a boom?",
 ["The range in the derrick specification sheet; under 3 tonnes the maker specifies it","The range in the derrick specification sheet; under 3 tonnes there is no limit","1.25 times the design inclination angle; under 3 tonnes the employer specifies it","The range approved by the inspection body; under 5 tonnes the supervisor decides"],
 "Article 45 mirrors Article 17 for derrick booms."),

("OSH-42","第46條",2,"起重升降-人字臂起重桿",
 "人字臂起重桿除標示額定荷重外，應以銘牌標示哪些事項？",
 ["製造者名稱、製造年月及吊升荷重","製造者名稱、檢查合格日期及積載荷重","進口廠商名稱、製造年月及額定速率","製造者地址、購置年月及容許下降速率"],"a",
 "第46條：雇主應於人字臂起重桿機身明顯易見處標示額定荷重並使操作人員及吊掛作業者周知；該起重桿並應以銘牌標示製造者名稱、製造年月及吊升荷重。固定式起重機安全檢查構造標準第66條有相同之銘牌規定。",
 "Besides the rated load, what must a derrick nameplate show?",
 ["The maker name, the year and month of manufacture, and the lifting load","The maker name, the inspection pass date, and the rated carrying load","The importer name, the year and month of manufacture, and the rated speed","The maker address, the year and month of purchase, and the descent speed"],
 "Article 46 requires maker, manufacture date and lifting load."),

("OSH-42","第47條",1,"起重升降-人字臂起重桿",
 "人字臂起重桿是否得乘載或吊升勞工從事作業？",
 ["以吊物為限，不得乘載或吊升勞工從事作業，本條未設但書","原則不得，但採取防止墜落措施並經檢查機構核准者得為之","原則不得，但於臨時性、短時間作業並指派監督人員者得為之","得乘載勞工，惟搭乘設備最大荷重不得超過額定荷重百分五十"],"a",
 "第47條：雇主對於人字臂起重桿之使用，以吊物為限，不得乘載或吊升勞工從事作業。與第19條固定式起重機及第35條移動式起重機不同，本條並未設有採取防止墜落措施即得例外載人之但書。",
 "May a derrick be used to carry or lift workers?",
 ["No; it is limited to goods and this Article provides no exception at all","In principle no, but it is allowed with fall protection approved by inspectors","In principle no, but temporary short work with a supervisor assigned is allowed","Yes, provided the carrier load stays below fifty per cent of the rated load"],
 "Article 47 bans man-riding on derricks without exception."),

("OSH-42","第48條",2,"起重升降-人字臂起重桿",
 "人字臂起重桿作業時，為防止鋼索震脫或槽輪飛落等危險，應禁止人員進入何處？",
 ["有發生危害之虞之鋼索內角側","有發生危害之虞之鋼索外角側","主桿基座周圍五公尺之範圍內","拉條固定錨附近之地面作業區"],"a",
 "第48條：雇主於人字臂起重桿作業時，應採取防止人員進入吊舉物下方及吊舉物通過人員上方之設備或措施；並為防止鋼索震脫、槽輪或其他安裝部分飛落等危險，應禁止人員進入有發生危害之虞之鋼索內角側。",
 "During derrick work, which area must be kept clear of personnel?",
 ["The inner angle side of the ropes where hazards may occur","The outer angle side of the ropes where hazards may occur","The area within five metres around the derrick mast base","The ground working area near the guy rope anchor fittings"],
 "Article 48 prohibits entry to the inner angle side of the ropes."),

("OSH-42","第49條",2,"起重升降-人字臂起重桿",
 "設置於屋外之人字臂起重桿，瞬間風速有超過每秒幾公尺之虞時應採取吊桿固定措施？",
 ["每秒三十公尺，應將吊桿固定緊縛於主桿或地面固定物","每秒十六公尺，應將吊桿固定緊縛於主桿或地面固定物","每秒三十公尺，應將吊桿放置於水平位置並鬆開拉條","每秒二十公尺，應將吊桿拆卸並存放於地面安全處所"],"a",
 "第49條：設置於屋外之人字臂起重桿，瞬間風速有超過每秒三十公尺之虞時，為預防吊桿動搖致起重桿破損，應採取吊桿固定緊縛於主桿或地面固定物等必要措施；並規定吊有荷重時操作人員不得擅離操作位置，惡劣氣候時應禁止工作。",
 "At what instantaneous wind speed must an outdoor derrick boom be secured?",
 ["30 metres per second; the boom is lashed to the mast or a ground anchorage","16 metres per second; the boom is lashed to the mast or a ground anchorage","30 metres per second; the boom is laid horizontal and the guys are slackened","20 metres per second; the boom is dismantled and stored safely on the ground"],
 "Article 49 requires securing the boom above 30 m/s gusts."),

("OSH-42","第50條",3,"起重升降-人字臂起重桿",
 "牽索人字臂起重桿及單索人字臂起重桿之拉條數各應為多少？",
 ["牽索式六條以上，單索式三條以上","牽索式三條以上，單索式六條以上","牽索式四條以上，單索式二條以上","牽索式八條以上，單索式四條以上"],"a",
 "第50條：人字臂起重桿之拉條，牽索人字臂起重桿之拉條數為六條以上，單索人字臂起重桿為三條以上；拉條不得接近架空電路，以鋼索為拉條時應以鋏、鬆緊螺旋扣、套管等金屬具緊結於支柱或固定錨，並有防止螺旋扣扭轉鬆脫之措施。",
 "How many guys are required for guy derricks and for stiff-leg single derricks?",
 ["Six or more for guy derricks and three or more for single derricks","Three or more for guy derricks and six or more for single derricks","Four or more for guy derricks and two or more for single derricks","Eight or more for guy derricks and four or more for single derricks"],
 "Article 50: six guys for guy derricks, three for single derricks."),

("OSH-42","第51條",2,"起重升降-人字臂起重桿",
 "人字臂起重桿主柱長度超過多少公尺應設攀登梯？其踏板間隔規定為何？",
 ["超過二十公尺應設攀登梯，踏板間隔二十五公分以上三十五公分以下","超過十五公尺應設攀登梯，踏板間隔二十公分以上三十公分以下","超過二十公尺應設攀登梯，踏板間隔三十五公分以上四十五公分以下","超過三十公尺應設攀登梯，踏板間隔二十五公分以上三十五公分以下"],"a",
 "第51條：主柱長度超過二十公尺之人字臂起重桿應設攀登梯；踏板應等距離設置，間隔在二十五公分以上三十五公分以下，踏板與吊桿及其他最近固定物間之水平距離應在十五公分以上，踏板未設側木者應有防止足部橫滑之構造。",
 "Above what mast length is a derrick ladder required, and what rung spacing applies?",
 ["Above 20 metres; rungs spaced at least 25 cm and not more than 35 cm apart","Above 15 metres; rungs spaced at least 20 cm and not more than 30 cm apart","Above 20 metres; rungs spaced at least 35 cm and not more than 45 cm apart","Above 30 metres; rungs spaced at least 25 cm and not more than 35 cm apart"],
 "Article 51: ladders above 20 m masts with 25 to 35 cm rung spacing."),

("OSH-42","第52條",2,"起重升降-人字臂起重桿",
 "人字臂起重桿之吊升裝置及起伏裝置所設制動裝置，應具備何種功能？",
 ["應設起重桿動力被遮斷時能自行制動之設備，但以人力操作者不在此限","應設起重桿動力被遮斷時能自動釋放荷重之設備，人力操作者亦適用","應設起重桿超過額定荷重時能自動遮斷動力之設備，人力操作者除外","應設起重桿吊桿傾斜角過大時能自動回復水平之設備，人力操作除外"],"a",
 "第52條：雇主對於人字臂起重桿之吊升裝置及起伏裝置，應設控制荷重或吊桿下降所必要之制動裝置；該制動裝置應設起重桿動力被遮斷時能自行制動之設備，但以人力操作者不在此限。",
 "What function must the brake on a derrick hoisting or luffing device have?",
 ["It must brake automatically when power is cut off, except for manually operated ones","It must release the load automatically when power is cut, including manual ones","It must cut off power automatically when the rated load is exceeded, except manual","It must restore the boom to horizontal when the angle is excessive, except manual"],
 "Article 52 requires self-braking when power is interrupted."),

("OSH-42","第53條",2,"起重升降-人字臂起重桿",
 "人字臂起重桿之鋼索與捲胴、吊桿、有鉤滑車等之連結，應以何種方法緊結？",
 ["以灌注合金或使用銷、壓夾、栓銷等方法緊結","以纖維索綑綁後再加設一道鐵絲纏繞予以固定","以鋼索自身打結後回穿三次形成編結環首固定","以電焊將鋼索端部熔接於捲胴或吊桿上予以固定"],"a",
 "第53條：雇主對於人字臂起重桿之鋼索與吊升裝置之捲胴、吊桿、有鉤滑車等之連結，應以灌注合金或使用銷、壓夾、栓銷等方法緊結之。固定式起重機安全檢查構造標準第31條亦規定使用合金套筒、壓夾或栓銷等方法。",
 "How must derrick ropes be secured to drums, booms and hook blocks?",
 ["By poured alloy sockets or by pins, swage clamps or cotter pin methods","By binding with fibre rope and adding a further wrapping of steel wire","By knotting the rope on itself and tucking it back three times as an eye","By electrically welding the rope end onto the drum or the boom member"],
 "Article 53 requires alloy sockets, pins or clamps."),

("OSH-42","第54條",2,"起重升降-人字臂起重桿",
 "人字臂起重桿之捲揚用鋼索及吊桿起伏用鋼索，於最低位置時應留置幾捲於捲胴上？",
 ["均應有二捲以上鋼索留置於各該裝置之捲胴上","均應有三捲以上鋼索留置於各該裝置之捲胴上","捲揚用二捲以上，起伏用則不須留置任何捲數","捲揚用五捲以上，起伏用應有二捲以上留置之"],"a",
 "第54條：人字臂起重桿捲揚用鋼索，當吊具置於最低位置時，應有二捲以上鋼索留置於吊升裝置之捲胴上；吊桿起伏用鋼索，當吊桿置於最低位置時，應有二捲以上鋼索留置於起伏裝置之捲胴上。",
 "How many rope turns must remain on the drums at the lowest position?",
 ["At least two turns must remain on the drum of each respective device","At least three turns must remain on the drum of each respective device","Two turns for hoisting rope, while luffing rope needs no turns at all","Five turns for hoisting rope and at least two turns for luffing rope"],
 "Article 54 requires at least two remaining turns on each drum."),

("OSH-42","第55條",1,"起重升降-人字臂起重桿",
 "具有起伏動作之人字臂起重桿，應於操作人員易見處設置何種裝置？",
 ["吊桿傾斜角之指示裝置，以防止過負荷操作","吊桿長度之自動量測裝置，以防止過捲操作","吊鉤高度之數位顯示裝置，以防止碰撞主桿","風速之即時監測裝置，以防止強風時之作業"],"a",
 "第55條：雇主對於具有起伏動作之人字臂起重桿，應於操作人員易見處設置吊桿傾斜角之指示裝置，以防止過負荷操作。固定式起重機安全檢查構造標準第36條及移動式起重機安全檢查構造標準第32條亦有相同要求。",
 "What device must be provided in view of the operator of a luffing derrick?",
 ["A boom inclination angle indicator, to prevent overload operation","A boom length automatic measuring device, to prevent over-hoisting","A digital hook height display device, to prevent striking the mast","A real-time wind speed monitor, to prevent work in strong winds"],
 "Article 55 requires a boom angle indicator."),

("OSH-42","第56條",3,"起重升降-人字臂起重桿",
 "人字臂起重桿結構部分之材料規定，下列敘述何者正確？",
 ["應符合CNS 2473之SS400等國家標準鋼材，結構部分不包括階梯、駕駛室、鋼索及機械部分","應符合CNS 2473之SS330等國家標準鋼材，結構部分包括階梯、駕駛室及所有機械部分","應符合CNS 4435之STK400等國家標準鋼材，且耐蝕鋁合金一律不得作為結構材料使用","應符合CNS 13812之國家標準鋼材，結構部分包括鋼索及供支撐吊升荷物以外之部分"],"a",
 "第56條：人字臂起重桿結構部分之材料，除經中央主管機關認可之耐蝕鋁合金等材料外，應符合CNS 575、CNS 2473之SS400、CNS 2947、CNS 4269、CNS 4435之STK400等九款國家標準或同等以上鋼材；結構部分不包括階梯、駕駛室、護圍、覆蓋、鋼索、機械部分及其他非供支撐吊升荷物之部分。",
 "Which statement about derrick structural materials is correct?",
 ["CNS steels such as SS400 apply; stairs, cabins, ropes and machinery are excluded","CNS steels such as SS330 apply; stairs, cabins and all machinery parts are included","CNS 4435 STK400 steels apply and corrosion resistant aluminium is always banned","CNS 13812 steels apply; ropes and non load bearing parts are counted as structure"],
 "Article 56 lists CNS steels and excludes non load-bearing parts."),
]
