# -*- coding: utf-8 -*-
# 第 12 批（H3）：環境部再生資源再生利用管理辦法（ENV-187）
#                土壤污染評估調查人員管理辦法（ENV-201）
A = "ENV-187"
B = "ENV-201"
Q = [

# ===== ENV-187 環境部再生資源再生利用管理辦法 =====
(A,"第1條",1,"再生資源再生利用-授權依據",
 "環境部再生資源再生利用管理辦法之授權依據為何？",
 ["依資源回收再利用法第十五條第四項規定訂定之",
  "依資源回收再利用法第十九條第二項規定訂定之",
  "依廢棄物清理法第三十九條第二項規定訂定之",
  "依廢棄物清理法第十八條第四項規定所訂定之"],"a",
 "第1條：本辦法依資源回收再利用法第十五條第四項規定訂定之。第2條並定本辦法適用之再生資源項目為依本法第十五條第三項經環境部公告者，及依同條第五項向環境部申請核准者；第19條定本辦法自發布日施行。",
 "What is the legal basis of these Regulations on renewable resource reuse?",
 ["Article 15, paragraph 4 of the Resource Recycling and Reuse Act",
  "Article 19, paragraph 2 of the Resource Recycling and Reuse Act",
  "Article 39, paragraph 2 of the Waste Disposal Act as amended",
  "Article 18, paragraph 4 of the Waste Disposal Act as amended"],
 "Article 1."),

(A,"第2條",1,"再生資源再生利用-適用項目",
 "本辦法適用之再生資源項目為何？",
 ["依本法第十五條第三項經環境部公告之再生利用再生資源項目，及依同條第五項向環境部申請核准之再生利用再生資源項目",
  "依本法第十五條第一項由地方主管機關公告之項目，及依同條第二項向目的事業主管機關申請備查之再生資源項目",
  "依廢棄物清理法第三十九條公告之再利用項目，及依同法第十八條核准之應回收廢棄物項目與其衍生之產出物",
  "依環境影響評估法審查通過之開發行為所產出項目，及經工業主管機關列冊管理之工業原料替代品項目"],"a",
 "第2條：本辦法適用之再生資源項目為依本法第十五條第三項經環境部公告之再生利用再生資源項目，及依本法第十五條第五項規定向環境部申請核准之再生利用再生資源項目。第3條並定環境部得參酌申請人所提經濟及技術可行性評估報告，研擬公告項目。",
 "Which renewable resource items are covered by these Regulations?",
 ["Items announced by the Ministry under Article 15, paragraph 3, and items approved on application under Article 15, paragraph 5",
  "Items announced by local authorities under Article 15, paragraph 1, and items filed with the industry regulator under paragraph 2",
  "Reuse items announced under Article 39 of the Waste Disposal Act, and recyclable waste items approved under its Article 18",
  "Items produced by development projects passing environmental impact review, and substitutes listed by the industrial authority"],
 "Article 2."),

(A,"第3條",1,"再生資源再生利用-公告研擬",
 "環境部研擬再生利用再生資源項目之公告時，得參酌何者所提之何種報告？",
 ["得參酌再生利用用途目的事業主管機關、地方主管機關、團體、事業或個人所提再生資源再生利用之經濟及技術可行性評估報告",
  "得參酌行政院主計總處、財政部、經濟部所提之再生資源市場價格調查報告與年度產業景氣預測分析報告等資料",
  "得參酌國際環保組織、外國政府機關所提之循環經濟政策白皮書與跨國企業自願性減碳承諾報告等文件",
  "得參酌檢測機構、認證機構所提之再生資源品質檢驗報告與各縣市環保稽查取締統計年報等相關資料"],"a",
 "第3條：環境部得參酌再生利用用途目的事業主管機關、地方主管機關、團體、事業或個人（申請人）所提再生資源再生利用之經濟及技術可行性評估報告，研擬再生利用再生資源項目之公告。第4條並列舉該評估報告應包括之七項內容。",
 "Whose reports may the Ministry consider when drafting an announcement of reuse items?",
 ["Economic and technical feasibility assessment reports submitted by industry regulators, local authorities, associations, enterprises or individuals",
  "Market price surveys and annual industry outlook forecasts submitted by the budget agency, the finance ministry and the economic affairs ministry",
  "Circular economy policy white papers and voluntary corporate decarbonisation pledges submitted by international bodies and foreign governments",
  "Quality test reports from testing and accreditation bodies together with annual environmental enforcement statistics from each county and city"],
 "Article 3."),

(A,"第4條",2,"再生資源再生利用-評估報告內容",
 "再生資源再生利用之經濟及技術可行性評估報告應包括哪些內容？",
 ["相關法令標準、國內再生利用再生資源產出現況與特性、國內外回收再利用現況、技術可行性評析、經濟可行性評析、回收再利用影響因子分析、結論與建議",
  "土地使用分區證明、廠房建築結構安全評估、機具設備採購清單與報價、員工人力配置與訓練計畫、財務融資計畫、投資報酬率試算、結論與建議",
  "環境影響說明書、空氣及水污染排放量推估、噪音振動評估、生態調查、居民意見調查、風險評估、健康風險量化分析、結論與建議事項",
  "碳足跡盤查報告、溫室氣體排放係數表、能源使用效率分析、綠色採購比例、環境會計報表、企業社會責任揭露、結論與建議事項"],"a",
 "第4條：評估報告應包括相關法令標準（含環保與產品法規、品質規範）、國內再生利用再生資源產出現況與特性、國內外回收再利用現況、技術可行性評析、經濟可行性評析、回收再利用影響因子分析（含市場評析、廠商配合意願、公告後影響及跨部會協商事項）、結論與建議等七項內容。",
 "What must the economic and technical feasibility assessment report contain?",
 ["Applicable laws and standards, domestic output status and characteristics, domestic and foreign recycling practice, technical feasibility, economic feasibility, influencing factor analysis, and conclusions",
  "Zoning certificates, structural safety assessments of plant buildings, equipment purchase lists and quotations, staffing and training plans, financing plans, return calculations, and conclusions",
  "Environmental impact statements, air and water emission estimates, noise and vibration assessment, ecological surveys, resident opinion surveys, risk assessment, health risk analysis, and conclusions",
  "Carbon footprint inventories, greenhouse gas emission factor tables, energy efficiency analysis, green procurement ratios, environmental accounting reports, CSR disclosure, and conclusions"],
 "Article 4."),

(A,"第5條",2,"再生資源再生利用-審議程序",
 "再生資源再生利用之經濟及技術可行性評估報告，其審議程序為何？公告後應如何處理？",
 ["環境部得邀請申請人、有關機關、業者公會代表及專家學者進行初審；申請人依初審意見修正後送再生資源回收再利用促進委員會審議通過，依本法第十五條第三項公告，並應定期檢討",
  "環境部應逕送行政院國家永續發展委員會審議通過；申請人依審議意見修正報告後，由地方主管機關公告，並應於公告後三年內委外辦理成效評估，不再另行定期檢討",
  "環境部應交由環境影響評估審查委員會審議通過；申請人依審查結論修正報告後，送立法院備查並公告，並應於每屆立法委員任期屆滿時全面檢討公告項目",
  "環境部得委託認證機構辦理書面初步審查；申請人依審查意見修正報告後，由目的事業主管機關公告，公告後除法令變更外不得再行檢討或修正其公告內容"],"a",
 "第5條第1項：環境部接獲評估報告後，得邀請申請人、有關機關、相關業者及其公會代表、專家學者進行初審。第2項：申請人應依初審意見修正報告後，送環境部提交再生資源回收再利用促進委員會審議，經審議通過後依本法第十五條第三項公告。第3項：公告後環境部應依實際執行情形、經濟及技術可行性及影響因子變動情形定期檢討。",
 "What review process applies to the feasibility report, and what follows announcement?",
 ["The Ministry may hold a preliminary review with the applicant, agencies, industry bodies and experts; the revised report goes to the Promotion Committee, and after approval it is announced and reviewed periodically",
  "The Ministry refers it directly to the national sustainable development council; the revised report is announced by the local authority, with an outsourced effectiveness study within three years and no further review",
  "The Ministry refers it to the environmental impact assessment review committee; the revised report is filed with the legislature, and announced items are reviewed at the end of each legislative term",
  "The Ministry may commission accreditation bodies to review it on paper; the revised report is announced by the industry regulator, and once announced it may not be reviewed or amended"],
 "Article 5, paragraphs 1 to 3."),

(A,"第6條",2,"再生資源再生利用-登記申請",
 "從事再生利用再生資源達一定規模之再生利用業者，應向何機關申請登記？應檢具哪些文件？其登記後有何限制？",
 ["應向再生利用場（廠）所在地直轄市、縣（市）主管機關申請登記，檢具公司商業登記文件、負責人身分證明、土地權狀及使用同意文件、再生資源項目技術方法量能及衍生廢棄物處置方式；並不得為未經登記之事項",
  "應向環境部申請登記，檢具工廠登記證、專責人員合格證書、環境影響評估審查結論及土地使用同意書、再生資源項目技術方法量能及衍生廢棄物處置方式；登記後得先行辦理再補行申報未經登記之事項",
  "應向目的事業主管機關申請登記，檢具公會會員證、產品檢驗合格報告、消防安全檢查證明及建物使用執照、再生資源項目技術方法量能及衍生廢棄物處置方式；登記後得經同業公會同意變更事項",
  "應向所在地鄉鎮市公所申請登記，檢具地價稅完納證明、建築物使用執照、公共意外責任保險單及環保稽查紀錄、再生資源項目技術方法量能及衍生廢棄物處置方式；登記後得自行擴充其處理項目"],"a",
 "第6條第1項：再生利用業者應填具申請表，連同公司、商業登記相關文件或目的事業主管機關核准設立證明、負責人身分證明文件、再生利用場（廠）土地所有權狀及土地登記謄本、清冊（都市計畫地區須附使用分區證明，非自有土地須附使用同意書）、再生利用再生資源項目、再生利用技術方法、再生利用量能及衍生廢棄物處置方式等文件，向場（廠）所在地直轄市、縣（市）主管機關申請登記。第2項並定不得為未經登記之事項；第4項定規模由環境部另定。",
 "Where must qualifying reuse operators register, what documents are required, and what limit applies after registration?",
 ["With the municipal or county authority where the site lies, filing company registration papers, identity proof, land title and consent documents, and item, technique, capacity and residue disposal details; unregistered activities are barred",
  "With the Ministry of Environment, filing a factory registration, personnel certificates, EIA review conclusions, and item, technique, capacity and residue disposal details; unregistered activities may be carried out and reported later",
  "With the relevant industry regulator, filing association membership, product test reports, fire safety certificates, and item, technique, capacity and residue disposal details; changes need only trade association consent",
  "With the township office of the site, filing land tax receipts, building use permits, liability insurance policies, and item, technique, capacity and residue disposal details; items may be expanded at the operator's discretion"],
 "Article 6, paragraphs 1, 2 and 4."),

(A,"第7條",1,"再生資源再生利用-補正期限",
 "主管機關受理再生利用業者申請登記文件後，認有應行補正事項者，應於何時通知？並得如何查核？",
 ["應於收文後十日內通知限期補正；必要時並得要求提示申請登記之文件正本供查核",
  "應於收文後三十日內通知限期補正；必要時並得要求申請人重新提出全部之申請",
  "應於收文後六十日內通知限期補正；必要時並得委託公正第三方機構代為查核",
  "應於收文後次一季通知限期補正；必要時並得逕行駁回申請而不另行通知補正"],"a",
 "第7條：主管機關受理再生利用業者申請登記之文件後，認有應行補正事項，應於收文後十日內通知限期補正；必要時，並得要求提示申請登記之文件正本供查核。第6條第3項並定申請文件除申請表應為正本外，其餘得檢送影本供審查。",
 "When must the authority give notice of corrections, and what verification may it require?",
 ["Within ten days of receipt, setting a period for correction; it may also require the original documents to be presented for verification",
  "Within thirty days of receipt, setting a period for correction; it may also require the applicant to submit the whole application afresh",
  "Within sixty days of receipt, setting a period for correction; it may also commission an impartial third-party body to verify them",
  "In the following quarter after receipt, setting a period; it may also reject the application outright without any correction notice"],
 "Article 7."),

(A,"第8條",2,"再生資源再生利用-變更",
 "再生利用業者之變更應如何辦理？因變更致主管機關不同時應向何機關申請？",
 ["機構名稱地址、負責人姓名住址及身分證字號變更者於變更後十五日內辦理；其他登記文件內容變更者應於變更前依申請登記規定辦理；致主管機關不同者，應向原登記主管機關申請並由其轉請新主管機關辦理",
  "機構名稱地址、負責人姓名住址及身分證字號變更者於變更前十五日辦理；其他登記文件內容變更者應於變更後三十日內辦理；致主管機關不同者，應逕向變更後之主管機關重新申請登記",
  "機構名稱地址、負責人姓名住址及身分證字號變更者於次年度併同辦理；其他登記文件內容變更者應於變更後六個月內辦理；致主管機關不同者，應報請環境部指定管轄機關辦理",
  "機構名稱地址、負責人姓名住址及身分證字號變更者於每季結束後辦理；其他登記文件內容變更者免辦理變更登記；致主管機關不同者，由原主管機關繼續管轄至登記期滿為止"],"a",
 "第8條第1項：機構名稱及地址、負責人姓名、住址及身分證明文件字號變更時，應於變更後十五日內檢具變更事項相關證明文件向主管機關辦理；其他申請登記文件內容變更時，應於變更前依本辦法申請登記之規定辦理。第2項：因辦理變更致主管機關不同時，應向原登記之主管機關申請，由原登記之主管機關受理後轉請變更後之主管機關辦理。",
 "How must reuse operators file changes, and where when the competent authority changes?",
 ["Name, address and responsible person details within 15 days after the change; other registered content before the change under the registration rules; where the authority changes, apply to the original authority which forwards the case",
  "Name, address and responsible person details 15 days before the change; other registered content within 30 days after the change; where the authority changes, apply directly to the new authority for fresh registration",
  "Name, address and responsible person details in the following year; other registered content within six months after the change takes place; where the competent authority changes, ask the Ministry to designate the authority in charge",
  "Name, address and responsible person details after each quarter ends; other registered content needs no change filing at all; where the authority changes, the original authority keeps jurisdiction until expiry"],
 "Article 8, paragraphs 1 and 2."),

(A,"第9條",1,"再生資源再生利用-彙送資料",
 "主管機關辦理再生利用業者之登記、變更，應於何時將辦理資料彙送環境部？",
 ["應於每月五日前將前一月辦理資料彙送環境部，留供查核",
  "應於每月十五日前將前一月辦理資料彙送環境部備查",
  "應於每季終了後十日內將前一季資料彙送環境部查核",
  "應於每年一月底前將前一年度資料彙送環境部備查"],"a",
 "第9條：主管機關辦理再生利用業者之登記、變更，應於每月五日前將前一月辦理資料彙送本部，留供查核。第12條第3項並定主管機關應於每年一月、四月、七月及十月底前，彙整再生利用業者申報資料及執行機關辦理情形，彙送環境部備查。",
 "When must the authority forward registration and change data to the Ministry?",
 ["By the 5th of each month, forwarding the previous month's data for inspection",
  "By the 15th of each month, forwarding the previous month's data for the record",
  "Within ten days after each quarter, forwarding that quarter's data for inspection",
  "By the end of January each year, forwarding the previous year's data for record"],
 "Article 9."),

(A,"第10條",2,"再生資源再生利用-終止暫停營業",
 "再生利用業者終止或暫停營業多久以上者，其尚未完成再生利用之再生資源應如何處理？",
 ["暫停營業六個月以上者，尚未完成再生利用之再生資源應依主管機關之指示辦理，所需費用由再生利用業者自行負擔；無法再生利用時應依本法第十九條規定辦理",
  "暫停營業三個月以上者，尚未完成再生利用之再生資源應由主管機關逕行標售，所得價款抵充清理費用；無法再生利用時應依本法第二十六條規定辦理",
  "暫停營業一年以上者，尚未完成再生利用之再生資源應交由執行機關清運處理，所需費用由地方政府編列預算支應；無法再生利用時得逕行掩埋",
  "暫停營業二年以上者，尚未完成再生利用之再生資源得繼續留存廠內貯存，所需費用由環境部再生利用基金支應；無法再生利用時應輸出國外"],"a",
 "第10條第1項：再生利用業者終止或暫停營業六個月以上者，其尚未完成再生利用之再生資源，應依主管機關之指示辦理，所需費用由再生利用業者自行負擔。第2項：前項再生資源無法再生利用時，應依本法第十九條規定辦理。第17條並定違反第10條規定者，主管機關應依本法第二十六條第1項第4款規定辦理。",
 "What happens to unprocessed renewable resources when an operator suspends business?",
 ["Where business stops for six months or more, they must be handled as the authority directs at the operator's own cost; if reuse is impossible, Article 19 of the Act applies",
  "Where business stops for three months or more, the authority sells them by tender and applies the proceeds to costs; if reuse is impossible, Article 26 of the Act applies",
  "Where business stops for one year or more, the executing agency hauls them away at the local government's expense; if reuse is impossible, they may be landfilled",
  "Where business stops for two years or more, they may stay stored on site at the Ministry's fund expense; if reuse is impossible, they must be exported abroad"],
 "Article 10, paragraphs 1 and 2."),

(A,"第11條",2,"再生資源再生利用-辦理主體",
 "家戶或其他非事業所產生再生資源之再生利用，由何者為之？事業所產生者呢？",
 ["家戶等非事業產生者由產生地之直轄市、縣（市）環境保護局為之，但得報經上級主管機關核准後委託合法登記之再生利用業者辦理；事業產生者應自行或委託合法登記之再生利用業者為之",
  "家戶等非事業產生者由環境部統一委外辦理，不得再轉委託其他民間業者；事業產生者應一律委託合法登記之再生利用業者辦理，不得自行從事再生資源之再生利用行為",
  "家戶等非事業產生者由鄉鎮市公所清潔隊辦理，並得逕行委託民間業者代辦；事業產生者應委由目的事業主管機關指定之公營事業統一辦理，不得自行處理",
  "家戶等非事業產生者由回收商自行收購辦理，主管機關一律不予介入；事業產生者應交由所在地環境保護局清運後統一辦理再生利用，其費用由該事業負擔"],"a",
 "第11條第1項：由家戶或其他非事業所產生再生資源之再生利用，由產生地之直轄市、縣（市）環境保護局（執行機關）為之；但執行機關得報經上級主管機關核准後委託合法登記之再生利用業者辦理。第2項：由事業所產生再生資源之再生利用，應自行或委託合法登記之再生利用業者為之；但經執行機關同意者，得委託其為之。",
 "Who carries out reuse of renewable resources from households, and who for enterprises?",
 ["For households and non-enterprises, the local environmental protection bureau, which may with higher approval commission registered reuse operators; enterprises must do it themselves or commission registered reuse operators",
  "For households and non-enterprises, the Ministry contracts the work out centrally with no private subcontracting allowed; enterprises must always commission registered reuse operators and may never do it themselves",
  "For households and non-enterprises, township cleaning squads, which may commission private operators freely; enterprises must instead use a state-owned enterprise designated by the relevant industry regulator",
  "For households and non-enterprises, private buyers acting on their own without any oversight; enterprises must have the local bureau haul the material away and arrange reuse centrally"],
 "Article 11, paragraphs 1 and 2."),

(A,"第12條",2,"再生資源再生利用-紀錄保存",
 "再生利用業者應就哪些事項作成紀錄？應保存多久留供查核？",
 ["應就再生利用之日期、種類、名稱、數量、用途、產生者名稱、再生利用途徑、產銷情形及衍生廢棄物處置證明作成紀錄，妥善保存三年留供查核",
  "應就再生利用之日期、種類、名稱、數量、用途、產生者名稱、再生利用途徑、產銷情形及衍生廢棄物處置證明作成紀錄，妥善保存一年留供查核",
  "應就再生利用之進出料重量、單價、稅額、買受人統一編號及運輸車號作成紀錄，妥善保存五年並每月報請主管機關備查後留存",
  "應就再生利用之用電度數、用水量、操作時數、員工出勤及設備維修情形作成紀錄，妥善保存十年並於年度終了時函報環境部"],"a",
 "第12條第1項：再生利用業者對於再生資源再生利用之日期、種類、名稱、數量、用途、產生者名稱、再生利用途徑、產銷情形及衍生廢棄物處置證明，應作成紀錄，妥善保存三年，留供查核。第17條並定違反第12條第1項規定者，主管機關應依本法第二十六條第1項第4款規定辦理。",
 "What must reuse operators record, and how long must records be kept?",
 ["Date, category, name, quantity, use, producer, reuse route, production and sales, and residue disposal proof, kept properly for three years for inspection",
  "Date, category, name, quantity, use, producer, reuse route, production and sales, and residue disposal proof, kept properly for one year for inspection",
  "Inbound and outbound weight, unit price, tax, buyer tax ID and vehicle numbers, kept for five years and filed monthly with the authority for the record",
  "Electricity and water use, operating hours, staff attendance and equipment maintenance, kept for ten years and reported to the Ministry at year end"],
 "Article 12, paragraph 1."),

(A,"第12條",2,"再生資源再生利用-季報申報",
 "再生利用業者應於何時檢具營運統計報表申報？主管機關應於何時彙送環境部？",
 ["業者應於每年一月、四月、七月及十月十五日前，檢具前一季營運統計報表向主管機關申報；主管機關應於每年一月、四月、七月及十月底前彙整申報資料彙送環境部備查",
  "業者應於每年一月、四月、七月及十月底前，檢具前一季營運統計報表向環境部申報；主管機關應於每年六月及十二月底前彙整申報資料彙送環境部備查",
  "業者應於每月十五日前，檢具前一個月營運統計報表向主管機關申報；主管機關應於每年一月底前彙整全年申報資料一次彙送環境部備查",
  "業者應於每年一月底前，檢具前一年度營運統計報表向主管機關申報；主管機關應於每年三月底前彙整申報資料彙送環境部核定後公告"],"a",
 "第12條第2項：再生利用業者應於每年一月、四月、七月及十月十五日前，檢具前一季營運統計報表向主管機關以書面申報；但屬本法公告應以網路傳輸方式申報者，依其規定辦理。第3項：主管機關應於每年一月、四月、七月及十月底前，彙整再生利用業者所申報資料及執行機關辦理再生資源再生利用情形，彙送本部備查。",
 "When must operators file quarterly statistics, and when must authorities forward them?",
 ["Operators file the previous quarter's statistics by 15 January, April, July and October; authorities compile and forward the data to the Ministry by the end of those months",
  "Operators file the previous quarter's statistics with the Ministry by the end of January, April, July and October; authorities forward compiled data by the end of June and December",
  "Operators file the previous month's statistics by the 15th of each month; authorities compile the whole year's data once and forward it to the Ministry by the end of January",
  "Operators file the previous year's statistics by the end of January; authorities compile and forward the data to the Ministry for approval and announcement by the end of March"],
 "Article 12, paragraphs 2 and 3."),

(A,"第13條",2,"再生資源再生利用-清運規定",
 "清運再生利用再生資源之車輛機具與隨車文件有何規定？發生污染時應如何處理？",
 ["清運過程應防止飛散、濺落、溢漏、惡臭擴散、爆炸等污染環境或危害人體健康情事；應隨車攜帶清運證明文件；不同項目應分類清運；發生污染時清運者應立即採取緊急應變措施",
  "清運過程僅需覆蓋帆布並依規定路線行駛即可；應隨車攜帶行車執照及駕照；不同項目得混合清運以節省成本；發生污染時應於三日內通報主管機關並提報改善計畫",
  "清運過程應全程錄影並即時回傳定位資訊；應隨車攜帶再生利用業者登記證正本；不同項目應於夜間分批清運；發生污染時應由地方環保局代為處理並向業者求償",
  "清運過程應由專責人員隨車監督並填具聯單；應隨車攜帶檢測報告與技師簽證；不同項目得由執行機關統一清運；發生污染時應停止清運並俟主管機關指示後辦理"],"a",
 "第13條第1項：清運車輛機具於清運過程中，應防止再生利用再生資源飛散、濺落、溢漏、惡臭擴散、爆炸等污染環境或危害人體健康之情事發生。第2項：應隨車攜帶清運證明文件。第3項：不同再生利用再生資源項目應分類清運。第4項：清運過程發生污染環境或危害人體健康之情事時，清運者應立即採取緊急應變措施。",
 "What rules govern haulage vehicles and documents, and what if pollution occurs?",
 ["Haulage must prevent scattering, spillage, leakage, odour spread and explosion; a haulage certificate must be carried; different items must be hauled separately; the hauler must take emergency measures at once",
  "Haulage need only use tarpaulins and prescribed routes; vehicle and driving licences must be carried; different items may be mixed to save cost; pollution must be reported within three days with a plan",
  "Haulage must be filmed throughout with live positioning; the original registration certificate must be carried; different items must be hauled at night; the local bureau handles pollution and recovers costs",
  "Haulage must be supervised by dedicated staff with manifests; test reports and engineer certification must be carried; the executing agency may haul all items; haulage stops pending authority instructions"],
 "Article 13, paragraphs 1 to 4."),

(A,"第14條",3,"再生資源再生利用-貯存方法",
 "再生利用再生資源之貯存方法，關於堆置高度及走道有何規定？",
 ["有堆置必要者應分區堆置，堆置高度不得超過五公尺，各區域間應有一公尺以上之分隔走道，並應採行必要措施防止掉落或崩塌",
  "有堆置必要者應分區堆置，堆置高度不得超過三公尺，各區域間應有二公尺以上之分隔走道，並應採行必要措施防止掉落或崩塌",
  "有堆置必要者應分區堆置，堆置高度不得超過十公尺，各區域間應有半公尺以上之分隔走道，並應採行必要措施防止掉落崩塌",
  "有堆置必要者應分區堆置，堆置高度不得超過六公尺，各區域間應有三公尺以上之分隔走道，並應採行必要措施防止掉落崩塌"],"a",
 "第14條第1項第3款：再生利用再生資源有堆置之必要者，應分區堆置，其堆置高度不得超過五公尺，各區域間應有一公尺以上之分隔走道，並應採行必要措施以防止堆置之再生利用再生資源發生掉落或崩塌等情事。第1款並要求貯存地點、容器、設施保持清潔完整，不得有飛揚、逸散、滲出、污染地面或散發惡臭情事。",
 "What stacking height and aisle width apply to storing renewable resources?",
 ["Stacking must be zoned, with height not over five metres and aisles of at least one metre between zones, and measures to prevent falling or collapse",
  "Stacking must be zoned, with height not over three metres and aisles of at least two metres between zones, and measures to prevent falling or collapse",
  "Stacking must be zoned, with height not over ten metres and aisles of at least half a metre between zones, and measures to prevent falling or collapse",
  "Stacking must be zoned, with height not over six metres and aisles of at least three metres between zones, and measures to prevent falling or collapse"],
 "Article 14, paragraph 1, subparagraph 3."),

(A,"第14條",2,"再生資源再生利用-相容性",
 "貯存容器、設施與所存放再生利用再生資源之相容性，其判斷標準為何？",
 ["指兩者接觸不產生熱、激烈反應、火災、爆炸、可燃性流體或有害流體，且不造成容器材料劣化致降低污染防治效果者",
  "指兩者接觸後產生之反應熱不超過攝氏五十度，且容器材料之腐蝕速率每年不超過零點五公釐並經檢測機構認證者",
  "指容器容積大於所存放再生資源體積之一點五倍，且材質須為不鏽鋼或高密度聚乙烯並具備防爆洩壓裝置者",
  "指容器經目的事業主管機關型式認可，且每三年委託檢測機構辦理耐壓、氣密及材質相容性測試均合格者"],"a",
 "第14條第2項：第1項第2款所指相容性，為再生利用再生資源與容器、設施接觸，不產生熱、激烈反應、火災、爆炸、可燃性流體或有害流體，及不造成容器材料劣化致降低污染防治之效果者。第1項第2款並要求貯存容器、設施應與所存放之再生利用再生資源具有相容性，再生資源應分類貯存。",
 "How is compatibility between containers and stored renewable resources judged?",
 ["Contact must not generate heat, violent reactions, fire, explosion, flammable or hazardous fluids, and must not degrade the container so as to weaken pollution control",
  "The heat of reaction on contact must stay below fifty degrees Celsius and the corrosion rate must not exceed 0.5 mm a year as certified by a testing organisation",
  "The container volume must exceed 1.5 times the stored volume, and the material must be stainless steel or high density polyethylene with pressure relief valves",
  "The container must have type approval from the relevant industry regulator and pass pressure, airtightness and material compatibility tests every three years"],
 "Article 14, paragraph 2."),

(A,"第15條",2,"再生資源再生利用-貯存設施",
 "再生利用再生資源之貯存設施應符合哪些規定？",
 ["應有防止污染地面水體、地下水體、空氣、土壤之設備或措施；貯存地點容器設施應於明顯處以中文標示名稱；具防止掉落溢散洩漏散發惡臭之必要設備；場（廠）區四周應設圍籬並設置消防設施",
  "應有防止污染地面水體、地下水體、空氣、土壤之設備或措施；貯存地點容器設施應以英文與條碼標示編號；具防止結露結霜之恆溫設備；場（廠）區四周應設綠籬並設置警衛室",
  "應有防止噪音振動與光害之設備或措施；貯存地點容器設施應於明顯處以中文標示重量；具防止靜電之接地設備；場（廠）區四周應設圍牆並設置二十四小時監視錄影系統",
  "應有防止蚊蠅病媒孳生之設備或措施；貯存地點容器設施應於出入口標示存量；具自動秤重與計量設備；場（廠）區四周應設緩衝綠帶並設置空氣品質監測站"],"a",
 "第15條：貯存設施應有防止污染地面水體、地下水體、空氣、土壤之設備或措施；貯存地點、容器、設施應於明顯處以中文標示再生利用再生資源之名稱；具有防止掉落、溢散、洩漏、散發惡臭及影響四周環境品質之必要設備或措施；貯存場（廠）區四周應設置圍籬；貯存場（廠）區應設置消防設施；並符合環境部公告項目及管理方式或核准計畫書之貯存設施相關規定。",
 "What must storage facilities for renewable resources satisfy?",
 ["Equipment to prevent pollution of surface water, groundwater, air and soil; Chinese name labels in a conspicuous place; measures against falling, scattering, leakage and odour; perimeter fencing and fire-fighting facilities",
  "Equipment to prevent pollution of surface water, groundwater, air and soil; English and barcode number labels; constant temperature equipment against condensation; perimeter hedging and a security guard post",
  "Equipment to prevent noise, vibration and light pollution; Chinese weight labels in a conspicuous place; earthing equipment against static electricity; perimeter walls and round-the-clock video surveillance systems",
  "Equipment to prevent breeding of mosquitoes and flies; stock labels at the entrance and exit; automatic weighing and metering equipment; a perimeter green buffer and an air quality monitoring station"],
 "Article 15."),

(A,"第16條",2,"再生資源再生利用-再生利用設施",
 "再生利用業者進行再生資源再生利用所設置之設施，應符合哪些規定？",
 ["應具堅固之基礎結構；設施與再生利用再生資源接觸之表面採不透水材料構築，必要時應另採抗蝕材料構築；具污染防治設施；具防止及警示火災、爆炸之功能",
  "應具可移動之組合結構；設施與再生利用再生資源接觸之表面採透水材料構築，必要時應另採保溫材料構築；具廢熱回收設施；具自動計量及計費之功能",
  "應具備防震係數達六級之結構；設施表面採耐高溫陶瓷材料構築，必要時應另採隔音材料構築；具備汙水回收再利用設施；具遠端遙控及自動停機功能",
  "應具備符合綠建築標章之結構；設施表面採可回收塑膠材料構築，必要時應另採防滑材料構築；具備太陽能發電設施；具人員進出刷卡管制及紀錄功能"],"a",
 "第16條：再生利用業者進行再生資源再生利用所設置之設施，應具堅固之基礎結構；設施與再生利用再生資源接觸之表面採不透水材料構築，必要時應另採抗蝕材料構築；具污染防治設施；具防止及警示火災、爆炸之功能；並符合環境部公告之再生利用再生資源項目及管理方式或核准計畫書內容之設施規範相關規定。",
 "What requirements apply to the facilities used for reuse operations?",
 ["A solid foundation structure; surfaces in contact with the material built of impermeable and, where needed, corrosion resistant material; pollution control facilities; and fire and explosion prevention and warning functions",
  "A movable modular structure; surfaces in contact with the material built of permeable and, where needed, heat insulating material; waste heat recovery facilities; and automatic metering and billing capabilities built in",
  "A structure rated for level six seismic resistance; surfaces built of heat resistant ceramic and, where needed, soundproof material; wastewater recycling facilities; and remote control and auto shutdown",
  "A structure certified under the green building label; surfaces built of recyclable plastic and, where needed, anti-slip material; solar power facilities; and card access control with entry records"],
 "Article 16."),

(A,"第17條",2,"再生資源再生利用-違反處理",
 "違反第十條、第十二條第一項、第十三條至第十六條規定者，主管機關應如何處理？",
 ["應依本法第二十六條第一項第四款規定辦理",
  "應依本法第十九條第二項規定命其限期改善",
  "應依廢棄物清理法第五十二條規定處以罰鍰",
  "應逕予撤銷其再生利用業者之登記與資格"],"a",
 "第17條：違反第10條（終止暫停營業之處理）、第12條第1項（紀錄保存）、第13條（清運）至第16條（再生利用設施）規定者，主管機關應依本法第二十六條第一項第四款規定辦理。第12條第1項並要求紀錄應妥善保存三年留供查核。",
 "How must the authority act against breaches of Articles 10, 12-1 and 13 to 16?",
 ["Proceed under Article 26, paragraph 1, subparagraph 4 of the Act",
  "Order improvement within a period under Article 19, paragraph 2",
  "Impose a fine under Article 52 of the Waste Disposal Act instead",
  "Revoke the operator's reuse registration and status immediately"],
 "Article 17."),

(A,"第18條",1,"再生資源再生利用-文書格式",
 "本辦法所定之相關文書及證明文件格式，由何機關定之？",
 ["由中央主管機關（環境部）定之","由直轄市、縣（市）主管機關定之","由目的事業主管機關定之","由再生利用業者公會定之"],"a",
 "第18條：本辦法所定之相關文書及證明文件格式，由本部（環境部）定之。第6條並定申請登記應填具申請表並檢具相關文件向場（廠）所在地直轄市、縣（市）主管機關辦理。",
 "Which agency prescribes the forms and certificates used under these Regulations?",
 ["The Ministry of Environment","The municipal or county authority","The relevant industry regulator","The reuse operators' trade association"],
 "Article 18."),

(A,"第19條",1,"再生資源再生利用-施行日",
 "本辦法之施行日期規定為何？",
 ["本辦法自發布日施行，未另定分階段施行之日期",
  "本辦法自發布後三個月施行，並分階段適用之",
  "本辦法自發布後一年施行，並溯及既往而適用",
  "本辦法自中華民國一百十五年一月一日起施行"],"a",
 "第19條：本辦法自發布日施行。第1條並定本辦法依資源回收再利用法第十五條第四項規定訂定；第18條定相關文書及證明文件格式由環境部定之。",
 "When do these Regulations take effect?",
 ["On the date of promulgation, with no phased effective dates",
  "Three months after promulgation, applying in phases over time",
  "One year after promulgation, applying retroactively as well",
  "On 1 January 2026 under a separately designated date"],
 "Article 19."),

# ===== ENV-201 土壤污染評估調查人員管理辦法 =====
(B,"第1條",1,"土污評估調查人員-授權依據",
 "土壤污染評估調查人員管理辦法之授權依據為何？",
 ["依土壤及地下水污染整治法第九條第二項規定訂定之",
  "依土壤及地下水污染整治法第八條第三項規定訂定之",
  "依土壤及地下水污染整治法第十一條第二項規定訂定",
  "依土壤及地下水污染整治法第三十一條第四項規定訂"],"a",
 "第1條：本辦法依土壤及地下水污染整治法第九條第二項規定訂定之。第7條並定完成登記或重新登記之評估調查人員，始得執行本法第八條與第九條之評估調查工作；第14條定本辦法除第8條自發布後六個月施行外，自發布日施行。",
 "What is the legal basis of these Regulations on soil pollution assessment investigators?",
 ["Article 9, paragraph 2 of the Soil and Groundwater Pollution Remediation Act",
  "Article 8, paragraph 3 of the Soil and Groundwater Pollution Remediation Act",
  "Article 11, paragraph 2 of the Soil and Groundwater Pollution Remediation Act",
  "Article 31, paragraph 4 of the Soil and Groundwater Pollution Remediation Act"],
 "Article 1."),

(B,"第2條",1,"土污評估調查人員-名詞定義",
 "本辦法所稱評估調查人員與合格證書之定義分別為何？",
 ["評估調查人員指依本辦法向中央主管機關完成登記之專業人員；合格證書指中央主管機關就土壤污染評估調查人員專業訓練合格者所核發之證書",
  "評估調查人員指依技師法取得執業執照之專業人員；合格證書指中央主管機關就環境檢測機構許可核發之證書及其相關之效期證明文件",
  "評估調查人員指受地方主管機關委託執行採樣之人員；合格證書指目的事業主管機關就土壤及地下水品質檢測合格所核發之證書",
  "評估調查人員指檢測機構內受僱從事檢驗之技術人員；合格證書指認證機構就實驗室能力試驗合格所核發之證書及有效期限"],"a",
 "第2條第1款：評估調查人員指依本辦法向中央主管機關完成登記之專業人員。第2款：合格證書指中央主管機關就土壤污染評估調查人員專業訓練合格者所核發之證書。第3條並定取得合格證書且符合資格者，始得申請登記。",
 "How are assessment investigators and qualification certificates defined?",
 ["Investigators are professionals registered with the central authority under these Regulations; a qualification certificate is issued by the central authority to those passing the specialist training",
  "Investigators are professionals licensed to practise under the Professional Engineers Act; a qualification certificate is issued by the central authority for testing organisation permits",
  "Investigators are personnel commissioned by local authorities to take samples; a qualification certificate is issued by the relevant industry regulator for soil and groundwater quality testing",
  "Investigators are technicians employed by testing organisations to run analyses; a qualification certificate is issued by an accreditation body for laboratory proficiency testing"],
 "Article 2, subparagraphs 1 and 2."),

(B,"第3條",2,"土污評估調查人員-登記資格",
 "取得合格證書者，尚須符合何種資格之一，始得申請評估調查人員之登記？",
 ["領有本國執業執照之環境工程、土木工程、應用地質、大地工程、水土保持、農藝或其他經中央主管機關認可公告之相關專業技師；或具兩年以上土壤或地下水污染調查、整治或場址評估相關工作經驗且有證明文件",
  "領有本國執業執照之機械工程、電機工程、化學工程、工業工程、職業衛生或其他經地方主管機關備查認可之相關專業技師；或具五年以上環境影響評估、廢棄物清理相關工作經驗且有證明文件",
  "領有外國政府核發之環境類專業證照並經駐外館處驗證或國內公證人認證者；或具一年以上檢測機構實驗室分析、品保品管或儀器校正相關工作經驗且經雇主出具證明文件者",
  "領有中央主管機關核發之環境保護專責人員合格證書並完成登記者；或具三年以上營建工程施工、監造或估驗計價相關工作經驗且經技師公會出具推薦證明文件者"],"a",
 "第3條：取得合格證書且符合下列資格之一者，始得向中央主管機關申請登記：一、領有本國執業執照之環境工程、土木工程、應用地質、大地工程、水土保持、農藝或其他經中央主管機關認可公告之相關專業技師；二、具兩年以上土壤或地下水污染調查、整治或場址評估相關工作經驗，且有證明文件。",
 "Besides the certificate, what qualification is required to register as an investigator?",
 ["A domestic practising licence as an environmental, civil, applied geology, geotechnical, soil conservation or agronomy engineer or other recognised field; or two years of relevant soil or groundwater pollution investigation experience with proof",
  "A domestic practising licence as a mechanical, electrical, chemical, industrial or occupational hygiene engineer or other field filed with the local authority; or five years of environmental impact or waste clearance experience with proof",
  "A foreign environmental professional licence authenticated by an overseas mission; or one year of laboratory analysis, quality assurance or instrument calibration experience at a testing organisation certified by the employer",
  "A dedicated environmental personnel certificate issued by the central authority; or three years of construction, supervision or valuation experience with a recommendation letter from the engineers' association"],
 "Article 3."),

(B,"第4條",3,"土污評估調查人員-登記期限",
 "符合登記資格者應於何時申請登記？登記之有效期間為何？重新登記應於何期間內申請？",
 ["應自取得合格證書之次日起三年內申請登記；登記有效期間為四年；評估調查人員自期滿前三個月起至期滿後三年內申請重新登記",
  "應自取得合格證書之次日起一年內申請登記；登記有效期間為二年；評估調查人員自期滿前一個月起至期滿後一年內申請重新登記",
  "應自取得合格證書之次日起五年內申請登記；登記有效期間為六年；評估調查人員自期滿前六個月起至期滿後五年內申請重新登記",
  "應自取得合格證書之當日起六個月內申請登記；登記有效期間為十年；評估調查人員自期滿前一年起至期滿後六個月內申請重新登記"],"a",
 "第4條第1項：符合第3條登記資格者，自取得合格證書之次日起三年內，應檢附申請表、合格證書影本、執業技師執照影本或工作經驗證明文件等向中央主管機關申請登記。第2項：登記之有效期間為四年，評估調查人員自期滿前三個月起至期滿後三年內，應檢附申請表、課程時數證明等申請重新登記。",
 "When must registration be sought, how long is it valid, and when may re-registration be filed?",
 ["Within three years after obtaining the certificate; registration is valid four years; re-registration runs from three months before expiry to three years after it",
  "Within one year after obtaining the certificate; registration is valid two years; re-registration runs from one month before expiry to one year after it",
  "Within five years after obtaining the certificate; registration is valid six years; re-registration runs from six months before expiry to five years after it",
  "Within six months from obtaining the certificate; registration is valid ten years; re-registration runs from one year before expiry to six months after it"],
 "Article 4, paragraphs 1 and 2."),

(B,"第4條",2,"土污評估調查人員-逾期與補正",
 "未於規定期間內完成登記或重新登記者，應如何辦理？申請文件有欠缺時如何處理？",
 ["應自完成登記或重新登記之日起六個月內完成到職訓練；應檢附文件有欠缺者，中央主管機關應以書面通知限期補正，逾期未補正者駁回其申請",
  "應自完成登記或重新登記之日起三個月內完成到職訓練；應檢附文件有欠缺者，中央主管機關應逕予駁回申請，不得再重新提出登記",
  "應自取得合格證書之日起一年內重新參加專業訓練；應檢附文件有欠缺者，得由申請人於現場勘查時當場補正，免另行通知",
  "應重新報考並取得合格證書後始得再申請登記；應檢附文件有欠缺者，中央主管機關應報請上級機關核定後始得通知補正"],"a",
 "第4條第3項：未於第1項及第2項所定期間內完成申請者，應自完成登記或重新登記之日起六個月內完成到職訓練。第4項：第1項及第2項應檢附之文件有欠缺者，中央主管機關應以書面通知限期補正，逾期未補正，駁回其申請。第10條並定完成到職訓練者應於十五日內檢具證明文件陳報中央主管機關。",
 "What applies to late registration, and what if the documents are incomplete?",
 ["Induction training must be completed within six months of registration or re-registration; incomplete documents draw a written correction notice, and the application is rejected if not corrected in time",
  "Induction training must be completed within three months of registration or re-registration; incomplete documents lead to outright rejection with no chance to reapply for registration",
  "The specialist training must be retaken within one year of obtaining the certificate; incomplete documents may be made good on the spot during the site inspection without any notice being given",
  "A new qualification certificate must be obtained by re-examination first; incomplete documents require approval from the higher authority before any correction notice is issued"],
 "Article 4, paragraphs 3 and 4."),

(B,"第5條",3,"土污評估調查人員-課程時數",
 "評估調查人員申請重新登記前，應參加多少小時之相關課程？時數如何計算？",
 ["應參加中央主管機關核定之土壤或地下水相關課程至少三十二小時；課程時數之計算，自完成重新登記之日起重新起算",
  "應參加中央主管機關核定之土壤或地下水相關課程至少十六小時；課程時數之計算，自取得合格證書之日起重新起算",
  "應參加中央主管機關核定之土壤或地下水相關課程至少六十小時；課程時數之計算，自登記有效期間屆滿日起重新起算",
  "應參加中央主管機關核定之土壤或地下水相關課程至少八小時；課程時數之計算，自每年一月一日起按年度重新起算"],"a",
 "第5條第1項：評估調查人員依第4條第2項申請重新登記前，應參加中央主管機關核定之土壤或地下水相關課程至少三十二小時。第2項：前項課程時數之計算，自完成重新登記之日起重新起算。第3項並定課程主辦單位應於辦理前以網路傳輸方式向中央主管機關申請核定時數。",
 "How many hours of courses are required before re-registration, and how are hours counted?",
 ["At least 32 hours of soil or groundwater courses approved by the central authority; the hours are counted afresh from the date re-registration is completed",
  "At least 16 hours of soil or groundwater courses approved by the central authority; the hours are counted afresh from the date the certificate was obtained",
  "At least 60 hours of soil or groundwater courses approved by the central authority; the hours are counted afresh from the date the registration period expires",
  "At least 8 hours of soil or groundwater courses approved by the central authority; the hours are counted afresh from 1 January each year on an annual basis"],
 "Article 5, paragraphs 1 and 2."),

(B,"第5條",2,"土污評估調查人員-課程主辦",
 "課程之主辦單位應如何申請核定時數？課程辦畢後有何義務？",
 ["應於辦理前檢附申請表及課程資料，以網路傳輸方式向中央主管機關申請核定時數；課程辦畢後應以網路傳輸方式上傳出席紀錄",
  "應於辦理後檢附申請表及課程資料，以書面方式向地方主管機關申請核定時數；課程辦畢後應以書面方式函送學員名冊備查",
  "應於辦理前檢附講師名冊及場地證明，以書面方式向目的事業主管機關報備；課程辦畢後應由學員自行上傳出席證明文件",
  "應於辦理前檢附收費標準及保險證明，以網路傳輸方式向認證機構申請認可；課程辦畢後應保存出席紀錄五年以供查核"],"a",
 "第5條第3項：課程之主辦單位應於辦理前，檢附申請表及課程資料，並以網路傳輸方式向中央主管機關申請核定時數。第4項：應檢附之文件有欠缺者，中央主管機關應以書面通知限期補正，逾期未補正駁回其申請。第5項：主辦單位應於課程辦畢後，以網路傳輸方式上傳出席紀錄。",
 "How must course organisers apply for hour approval, and what must they do afterwards?",
 ["Apply online to the central authority before the course with an application form and course materials; after the course, upload the attendance records online",
  "Apply on paper to the local authority after the course with an application form and course materials; after the course, send the participant roster on paper",
  "File on paper with the industry regulator before the course with an instructor roster and venue proof; participants then upload their own attendance proof",
  "Apply online to an accreditation body before the course with fee schedules and insurance proof; attendance records are then kept five years for inspection"],
 "Article 5, paragraphs 3 to 5."),

(B,"第6條",1,"土污評估調查人員-外文文件",
 "第三條及第四條之證明文件為外文者，申請人應如何辦理？",
 ["應檢附駐外館處驗證或國內公證人認證之中文譯本；但證明文件為英文者，免附中文譯本",
  "應檢附中央主管機關指定翻譯社之中文譯本；但證明文件為日文者，免附中文譯本",
  "應檢附申請人自行翻譯並簽名之中文譯本；但證明文件為英文者，仍應附中文譯本",
  "應檢附原核發機關出具之中文對照本；但證明文件為外文者，一律不得作為佐證"],"a",
 "第6條：第3條及第4條之證明文件為外文者，申請人應檢附駐外館處驗證或國內公證人認證之中文譯本；但證明文件為英文者，免附中文譯本。第3條並定登記資格為相關專業技師或具兩年以上相關工作經驗者。",
 "What must applicants do where the supporting documents are in a foreign language?",
 ["Attach a Chinese translation authenticated by an overseas mission or a domestic notary; English documents need no Chinese translation",
  "Attach a Chinese translation by a translation agency designated by the central authority; Japanese documents need no Chinese translation",
  "Attach a Chinese translation made and signed by the applicant personally; English documents still require a Chinese translation",
  "Attach a Chinese version issued by the original issuing agency; foreign language documents may never serve as evidence"],
 "Article 6."),

(B,"第7條",1,"土污評估調查人員-執行資格",
 "何人始得執行土壤及地下水污染整治法第八條與第九條之評估調查工作？",
 ["完成登記或重新登記之評估調查人員",
  "取得合格證書之各類專業技師人員",
  "經中央主管機關許可之檢測機構人員",
  "經地方主管機關委託之專業顧問人員"],"a",
 "第7條：完成登記或重新登記之評估調查人員，始得執行本法第八條與第九條之評估調查工作。第4條並定登記有效期間為四年，應於期滿前三個月起至期滿後三年內申請重新登記；第11條定合格證書經撤銷或廢止者，登記自該日起失其效力。",
 "Who may carry out the assessment investigations under Articles 8 and 9 of the Act?",
 ["Investigators who have completed registration or re-registration",
  "Professional engineers holding the qualification certificate",
  "Personnel of testing organisations permitted by the central authority",
  "Consultants commissioned by the local competent authority"],
 "Article 7."),

(B,"第8條",2,"土污評估調查人員-申報執行內容",
 "評估調查人員應於何時申報執行內容？申報內容應包括哪些事項？",
 ["應於現場勘查之日二日前以網路傳輸方式向中央主管機關申報；內容包括評估調查對象名稱、執行評估調查之地址與地號、評估調查事項及現場勘查日期",
  "應於現場勘查之日七日前以書面方式向地方主管機關申報；內容包括評估調查對象名稱、採樣人員名冊、檢測機構許可文號及檢測方法說明",
  "應於現場勘查之日當日以電話方式向中央主管機關報備；內容包括評估調查對象名稱、負責人姓名、技師簽證文號及預定完成報告日期",
  "應於採樣之日三十日前以網路傳輸方式向受託機關申報；內容包括評估調查對象名稱、土地公告現值、使用分區及土地移轉契約影本"],"a",
 "第8條第1項：評估調查人員應於現場勘查之日二日前，以網路傳輸方式向中央主管機關申報執行內容，包括評估調查對象名稱、執行評估調查之地址與地號、評估調查事項及現場勘查日期，及其他經中央主管機關指定之項目。第14條並定第8條自發布後六個月施行。",
 "When must investigators report their work content, and what must the report include?",
 ["Online to the central authority two days before the site inspection; the report covers the subject's name, the address and parcel number, the matters investigated and the inspection date",
  "On paper to the local authority seven days before the site inspection; the report covers the subject's name, the sampling roster, the testing organisation permit and test methods",
  "By telephone to the central authority on the day of inspection; the report covers the subject's name, the responsible person, the engineer certification and the report due date",
  "Online to the commissioned agency thirty days before sampling; the report covers the subject's name, land value, zoning and a copy of the land transfer contract"],
 "Article 8, paragraph 1."),

(B,"第8條",2,"土污評估調查人員-勘查日期",
 "評估調查人員申報之現場勘查日期，與實際勘查日期及採樣日期有何關係？日期異動時如何處理？",
 ["申報之現場勘查日期應與實際現場勘查日期相同，且現場勘查日期應早於採樣日期；原申報日期有異動者，應重新申報",
  "申報之現場勘查日期得與實際現場勘查日期不同，惟現場勘查日期應晚於採樣日期；原申報日期有異動者，免重新申報",
  "申報之現場勘查日期應與採樣日期為同一日，且不得早於檢測機構申報行程日；原申報日期有異動者，應報請核准",
  "申報之現場勘查日期得由檢測機構代為變更，惟應於採樣後補行申報；原申報日期有異動者，由主管機關逕行更正"],"a",
 "第8條第2項：評估調查人員申報之現場勘查日期應與實際現場勘查日期相同，且現場勘查日期應早於採樣日期；原申報現場勘查日期有異動者，應依第1項規定重新申報。第9條第1項第5款並定未依第8條規定申報執行內容者，屬不得為之情事。",
 "How must the reported inspection date relate to the actual inspection and sampling dates?",
 ["The reported date must match the actual inspection date, and inspection must precede sampling; any change to the reported date requires a fresh report",
  "The reported date may differ from the actual inspection date, and inspection must follow sampling; a change to the reported date needs no fresh report",
  "The reported date must be the same day as sampling and no earlier than the testing organisation's filing; a change requires prior approval instead",
  "The reported date may be changed by the testing organisation, reported after sampling; a change is corrected by the authority on its own motion"],
 "Article 8, paragraph 2."),

(B,"第9條",3,"土污評估調查人員-禁止情事",
 "評估調查人員執行評估調查工作時，不得有下列何種情事？",
 ["調查及檢測資料內容不實或錯誤未予更正或予以隱飾、應說明之事實未予說明、簽署事項與法令或常規不一致未予指明、未親自到現場實地勘查與訪談、未親自到現場全程監督採樣",
  "調查及檢測資料未經技師覆核、報告未於三十日內提送、未使用主管機關指定之報告格式、未於現場張貼公告週知、未於採樣時通知土地所有人到場會同見證",
  "調查及檢測資料未以中文撰寫、未附英文摘要、未提供電子檔、未於報告封面標示登記證號、未於每頁加蓋騎縫章、未依規定裝訂成冊並編製頁碼目次",
  "調查及檢測資料未投保專業責任保險、未收取法定公費、未與委託人簽訂書面契約、未加入公會、未參加年度在職訓練及未辦理執業登記之續期作業"],"a",
 "第9條第1項：評估調查人員不得有土壤污染評估調查及檢測資料內容不實或錯誤未予更正或隱飾、應說明之事實未予說明、簽署事項中之評估調查方式與法令或常規不一致未予指明、未親自到現場實地勘查與訪談、未依第8條申報執行內容、未親自到現場全程監督採樣、規避妨礙或拒絕查核、本人或近親屬為相關事業之董事負責人或受僱人等情事。",
 "Which conduct is prohibited for investigators carrying out assessment work?",
 ["Leaving false or erroneous data uncorrected or concealed, failing to explain facts requiring explanation, not flagging methods inconsistent with law or practice, not attending the site in person, and not supervising sampling throughout",
  "Not having the data reviewed by a licensed engineer, not filing the report within thirty days, not using the prescribed report format, not posting a public notice on the site, and not notifying the landowner to witness the sampling",
  "Not writing the data in Chinese, omitting an English abstract, not providing electronic files, not showing the registration certificate number on the cover, and not binding and paginating the report properly",
  "Not carrying professional liability insurance, not charging statutory fees, not signing a written contract, not joining an association, and not attending annual training or renewing practice registration"],
 "Article 9, paragraph 1."),

(B,"第9條",3,"土污評估調查人員-廢止登記",
 "評估調查人員有第九條第一項各款情事之一者，其法律效果為何？",
 ["由中央主管機關廢止其登記，且自廢止登記之日起三年內不得再申請登記；其再為申請登記者，應於完成登記之日起六個月內完成到職訓練",
  "由中央主管機關廢止其登記，且自廢止登記之日起一年內不得再申請登記；其再為申請登記者，應於完成登記之日起三個月內完成到職訓練",
  "由地方主管機關撤銷其合格證書，且自撤銷之日起五年內不得再參加專業訓練；其再為申請登記者，應重新取得專業技師執業執照",
  "由中央主管機關停止其執業六個月，並命限期改善；屆期未改善者，應於完成改善之日起一年內完成在職訓練並重新申請登記"],"a",
 "第9條第2項：評估調查人員有第1項各款情事之一者，由中央主管機關廢止其登記，且自廢止登記之日起三年內不得再申請登記；其再為申請登記者，應於完成登記之日起六個月內完成到職訓練。第10條並定未依規定完成到職訓練或未依期限陳報者，中央主管機關應廢止其登記。",
 "What are the consequences where an investigator commits any prohibited conduct?",
 ["The central authority revokes the registration, and no new registration may be sought for three years; on reapplying, induction training must be finished within six months",
  "The central authority revokes the registration, and no new registration may be sought for one year; on reapplying, induction training must be finished within three months",
  "The local authority revokes the qualification certificate, barring the specialist training for five years; on reapplying, a new engineer practising licence must be obtained",
  "The central authority suspends practice for six months and orders improvement; failing that, refresher training must be finished within a year before reapplying"],
 "Article 9, paragraph 2."),

(B,"第10條",2,"土污評估調查人員-到職訓練",
 "完成到職訓練者應於何時陳報中央主管機關？未依規定辦理者之效果為何？",
 ["應於完成到職訓練後十五日內，檢具到職訓練證明文件陳報中央主管機關；未依規定完成到職訓練或未依期限陳報者，中央主管機關應廢止其登記",
  "應於完成到職訓練後三十日內，檢具到職訓練證明文件陳報地方主管機關；未依規定完成到職訓練或未依期限陳報者，中央主管機關應停止其執業",
  "應於完成到職訓練後六個月內，檢具到職訓練證明文件陳報中央主管機關；未依規定完成到職訓練或未依期限陳報者，應重新參加專業訓練",
  "應於完成到職訓練當日，檢具到職訓練證明文件陳報受託機關；未依規定完成到職訓練或未依期限陳報者，得申請延長六個月之期限"],"a",
 "第10條第1項：依第4條第3項、第9條第2項完成到職訓練者，應於完成到職訓練後十五日內，檢具土壤污染評估調查人員到職訓練證明文件陳報中央主管機關。第2項：未依第4條第3項、第9條第2項完成到職訓練，或未依前項規定期限陳報中央主管機關者，中央主管機關應廢止其登記。",
 "When must completion of induction training be reported, and what if it is not?",
 ["Within 15 days of completing the training, filing the certificate with the central authority; failure to train or report in time leads the central authority to revoke the registration",
  "Within 30 days of completing the training, filing the certificate with the local authority; failure to train or report in time leads the central authority to suspend practice",
  "Within six months of completing the training, filing the certificate with the central authority; failure to train or report in time requires retaking the specialist training",
  "On the day the training is completed, filing the certificate with the commissioned agency; failure to train or report in time allows a six-month extension to be sought"],
 "Article 10, paragraphs 1 and 2."),

(B,"第11條",1,"土污評估調查人員-證書撤銷效果",
 "評估調查人員經中央主管機關撤銷或廢止合格證書者，其登記之效力為何？",
 ["其登記自合格證書撤銷或廢止之日起失其效力",
  "其登記仍有效至原登記有效期間屆滿之日止",
  "其登記應由地方主管機關另行公告後始失效",
  "其登記得於三個月內申請回復並繼續執業"],"a",
 "第11條：評估調查人員經中央主管機關撤銷或廢止合格證書者，其登記自合格證書撤銷或廢止之日起失其效力。第2條第2款並定合格證書係中央主管機關就土壤污染評估調查人員專業訓練合格者所核發之證書。",
 "What is the effect on registration if the qualification certificate is revoked?",
 ["The registration loses effect from the date the certificate is revoked or annulled",
  "The registration stays valid until the original registration period expires",
  "The registration lapses only after the local authority publishes a notice",
  "The registration may be restored on application within three months"],
 "Article 11."),

(B,"第12條",1,"土污評估調查人員-查核評鑑",
 "中央主管機關對評估調查人員得辦理何種查核？其結果如何處理？",
 ["得派員或委託專業人員進行查核或評鑑，其結果得評列等級或優缺點，並公告之",
  "得派員或委託專業人員進行查核或評鑑，其結果應報請行政院核定後始得公告",
  "得委由地方主管機關進行查核或評鑑，其結果僅供內部參考而不對外公開之",
  "得委託認證機構進行查核或評鑑，其結果應通知本人而不得評列等級或優劣"],"a",
 "第12條：中央主管機關得派員或委託專業人員，針對評估調查人員進行查核或評鑑，其結果得評列等級或優缺點，並公告之。第9條第1項第7款並定規避、妨礙或拒絕各級主管機關查核及命提供有關資料者，屬不得為之情事，將遭廢止登記。",
 "What checks may the central authority conduct on investigators, and how are results used?",
 ["It may send staff or commission experts to audit or appraise them, and the results may be graded or noted and then published",
  "It may send staff or commission experts to audit or appraise them, but results must be approved by the Executive Yuan first",
  "It may have local authorities audit or appraise them, and the results are for internal reference and not made public",
  "It may commission accreditation bodies to audit them, and the results are notified privately without any grading"],
 "Article 12."),

(B,"第13條",1,"土污評估調查人員-在職訓練",
 "中央主管機關對評估調查人員之在職訓練有何權限？",
 ["中央主管機關得要求評估調查人員參加在職訓練",
  "中央主管機關應每年強制辦理二十四小時在職訓練",
  "在職訓練由技師公會自行辦理並報主管機關備查",
  "在職訓練僅限重新登記者參加而不及於初次登記"],"a",
 "第13條：中央主管機關得要求評估調查人員參加在職訓練。第5條第1項另定重新登記前應參加中央主管機關核定之土壤或地下水相關課程至少三十二小時；第4條第3項及第9條第2項則另有到職訓練之規定。",
 "What power does the central authority have over in-service training?",
 ["It may require assessment investigators to attend in-service training",
  "It must run 24 hours of compulsory in-service training every year",
  "In-service training is run by the engineers' association and merely filed",
  "In-service training is limited to those seeking re-registration only"],
 "Article 13."),

(B,"第14條",2,"土污評估調查人員-施行日",
 "本辦法之施行日期規定為何？",
 ["本辦法除第八條自發布後六個月施行外，自發布日施行",
  "本辦法除第五條自發布後一年施行外，自發布日施行",
  "本辦法除第九條自發布後三個月施行外，自發布日施行",
  "本辦法全部條文一律自發布後六個月起始正式施行"],"a",
 "第14條：本辦法除第8條自發布後六個月施行外，自發布日施行。第8條係關於評估調查人員應於現場勘查之日二日前以網路傳輸方式向中央主管機關申報執行內容之規定。",
 "When do these Regulations take effect?",
 ["On promulgation, except Article 8 which takes effect six months later",
  "On promulgation, except Article 5 which takes effect one year later",
  "On promulgation, except Article 9 which takes effect three months later",
  "All provisions take effect only six months after promulgation together"],
 "Article 14."),
(A,"第6條",2,"再生資源再生利用-登記文件與規模",
 "再生利用業者申請登記之文件，其正本與影本規定為何？所稱一定規模由何機關定之？",
 ["申請文件除申請表應為正本外，其餘文件得檢送影本供主管機關審查；再生利用業者之一定規模由環境部另定之",
  "申請文件應全部檢送正本供主管機關審查並於審查後發還；再生利用業者之一定規模由地方主管機關自行認定",
  "申請文件得全部檢送影本並由申請人切結負責；再生利用業者之一定規模由目的事業主管機關會商後公告",
  "申請文件應經公證人認證後檢送正本及影本各一份；再生利用業者之一定規模由再生利用業者公會自行議定"],"a",
 "第6條第3項：再生利用業者申請登記之文件，除申請表應為正本外，其餘文件得檢送影本供主管機關審查。第4項：第1項再生利用業者之規模由本部（環境部）另定之。第7條並定主管機關認有應行補正事項者，應於收文後十日內通知限期補正，必要時得要求提示正本查核。",
 "Which registration documents must be originals, and who sets the scale threshold?",
 ["Only the application form must be an original and the rest may be copies for review; the scale threshold is set separately by the Ministry of Environment",
  "All application documents must be originals for review and are returned afterwards; the scale threshold is determined by each local competent authority itself",
  "All documents may be copies with the applicant giving a written undertaking; the scale threshold is announced by the industry regulator after consultation",
  "Documents must be notarised and filed as one original and one copy each; the scale threshold is agreed among the reuse operators trade association itself"],
 "Article 6, paragraphs 3 and 4."),

(B,"第4條",2,"土污評估調查人員-登記檢附文件",
 "評估調查人員初次申請登記與申請重新登記，應檢附之文件分別為何？",
 ["初次登記應檢附申請表、合格證書影本、執業技師執照影本或工作經驗證明文件；重新登記應檢附申請表及課程時數證明等中央主管機關指定之文件",
  "初次登記應檢附申請表、身分證影本、最高學歷證書及體格檢查表；重新登記應檢附申請表及最近三年執行評估調查案件清冊等指定文件",
  "初次登記應檢附申請表、技師公會會員證及專業責任保險單；重新登記應檢附申請表及主管機關查核評鑑結果證明等相關之指定文件",
  "初次登記應檢附申請表、服務單位在職證明及推薦函二份；重新登記應檢附申請表及在職訓練出席紀錄影本等中央主管機關指定文件"],"a",
 "第4條第1項：應檢附申請表、合格證書影本、執業技師執照影本或工作經驗證明文件及其他經中央主管機關指定之文件申請登記。第2項：申請重新登記應檢附申請表、課程時數證明及其他經中央主管機關指定之文件。第5條第1項並定重新登記前應參加核定課程至少三十二小時。",
 "Which documents are required for first registration and for re-registration?",
 ["First registration needs the form, a copy of the certificate, and an engineer licence copy or work experience proof; re-registration needs the form and course hour certificates as designated",
  "First registration needs the form, an ID copy, the highest diploma and a physical examination form; re-registration needs the form and a list of cases handled over the past three years",
  "First registration needs the form, association membership proof and a professional liability policy; re-registration needs the form and proof of the authority's audit or appraisal results",
  "First registration needs the form, employment proof from the employer and two letters of recommendation; re-registration needs the form and copies of training attendance records"],
 "Article 4, paragraphs 1 and 2."),

(B,"第9條",3,"土污評估調查人員-利益迴避",
 "評估調查人員與評估調查相關事業間，有何利益迴避之規定？",
 ["評估調查人員本人或其配偶、三親等以內之血親或二親等以內之姻親，為評估調查相關事業之董（理、監）事、負責人或受僱人者，不得執行該評估調查工作",
  "評估調查人員本人或其配偶、二親等以內之血親或一親等以內之姻親，為評估調查相關事業之董（理、監）事、負責人或受僱人者，仍得執行該評估調查工作",
  "評估調查人員本人或其配偶、四親等以內之血親或三親等以內之姻親，為評估調查相關事業之股東或債權人者，應報請中央主管機關同意後執行",
  "評估調查人員本人或其配偶、五親等以內之血親或四親等以內之姻親，為評估調查相關事業之顧問或承包商者，應於報告中揭露即得執行工作"],"a",
 "第9條第1項第8款：評估調查人員本人或其配偶、三親等以內之血親或二親等以內之姻親，為評估調查相關事業之董（理、監）事、負責人或受僱人者，屬不得為之情事。第2項並定有各款情事之一者，由中央主管機關廢止其登記，且自廢止之日起三年內不得再申請登記。",
 "What conflict-of-interest rule applies between investigators and the businesses assessed?",
 ["Investigators whose spouse or relatives by blood within three degrees or by marriage within two degrees are directors, principals or employees of the business may not do the work",
  "Investigators whose spouse or relatives by blood within two degrees or by marriage within one degree are directors, principals or employees of the business may still do the work",
  "Investigators whose spouse or relatives by blood within four degrees or by marriage within three degrees are shareholders or creditors must obtain central authority consent",
  "Investigators whose spouse or relatives by blood within five degrees or by marriage within four degrees are advisers or contractors may act if this is disclosed in the report"],
 "Article 9, paragraph 1, subparagraph 8."),
]
