# -*- coding: utf-8 -*-
# ENV-180 廢照明光源回收貯存清除處理方法及設施標準（13 條）
# ENV-182 廢電子電器暨廢資訊物品回收貯存清除處理方法及設施標準（12 條）
# ENV-183 廢輪胎回收貯存清除處理方法及設施標準（9 條）
LG = "ENV-180"
EE = "ENV-182"
TR = "ENV-183"

Q = [

(LG,"第1條",1,"廢照明光源-法源適用",
 "廢照明光源回收貯存清除處理方法及設施標準之法源依據及適用關係為何？",
 ["依廢棄物清理法第十八條第一項規定訂定；廢照明光源回收貯存清除處理方法及設施依本標準規定，未規定者適用其他法令之規定",
  "依廢棄物清理法第十五條第二項規定訂定；廢照明光源回收貯存清除處理方法及設施應優先適用其他法令，本標準僅補充適用之",
  "依廢棄物清理法第二十八條規定訂定；廢照明光源回收貯存清除處理方法及設施依本標準規定，未規定者應報請中央主管機關核定",
  "依資源回收再利用法第十條規定訂定；廢照明光源回收貯存清除處理方法及設施依本標準規定，並得由業者視實際需要自行調整"],"a",
 "第1條第1項、第2項：本標準依廢棄物清理法第18條第1項規定訂定；廢照明光源回收貯存清除處理方法及設施依本標準之規定，未規定者適用其他法令之規定。第2條第1款並將廢照明光源定義為依本法第15條第2項公告應回收之廢照明光源。",
 "What is the legal basis of the Standards for Waste Lighting Sources and how do other laws apply?",
 ["Enacted under Article 18, paragraph 1 of the Waste Disposal Act; the methods and facilities follow these Standards, with other laws applying to uncovered matters",
  "Enacted under Article 15, paragraph 2 of the Waste Disposal Act; other laws apply first and these Standards serve only to supplement what they do not cover",
  "Enacted under Article 28 of the Waste Disposal Act; the methods follow these Standards, and uncovered matters must be submitted for central authority approval",
  "Enacted under Article 10 of the Resource Recycling Act; the methods follow these Standards, and operators may adjust them as their actual needs require"],
 "Article 1, paragraphs 1 and 2."),

(LG,"第2條",3,"廢照明光源-隔離區定義",
 "本標準所稱偵測裝置及隔離區，其定義為何？",
 ["偵測裝置指廢照明光源於處理廠內貯存、處理設施之含汞物質偵測設備之裝置；隔離區指具捕集並輸送區域內氣體至空氣污染防制設備系統功能之空間，且區域內氣體不得於未經處理前與大氣接觸",
  "偵測裝置指設置於貯存區出入口之金屬探測與計量設備之裝置；隔離區指以圍籬與警示標線區隔之管制空間，且區域內人員應著防護衣並經淋浴後始得離開該區域並留存紀錄",
  "偵測裝置指設置於煙道之連續自動監測與連線傳輸設備之裝置；隔離區指設置於廠區邊界之綠帶緩衝空間，且區域內不得堆置任何廢棄物或再生料以維持景觀",
  "偵測裝置指用以量測作業環境噪音與照度之儀器設備之裝置；隔離區指以隔音牆區隔之獨立作業空間，且區域內氣體得經自然通風方式直接排放至大氣中"],"a",
 "第2條第2款：偵測裝置指廢照明光源於處理廠內貯存、處理設施之含汞物質偵測設備之裝置。第8款：隔離區指具有捕集並輸送區域內氣體至空氣污染防制設備系統功能之空間，且該區域內之氣體不得於未經空氣污染防制設備處理前與大氣接觸。第5條並列明應設置或貯存於隔離區之四類設備與物質。",
 "How do these Standards define the detection device and the isolation zone?",
 ["The detection device detects mercury-bearing substances at the plant's storage and treatment facilities; the isolation zone captures and conveys its air to air pollution control equipment, and that air may not meet the atmosphere untreated",
  "The detection device is metal detection and metering equipment at the storage area entrance; the isolation zone is a controlled space marked by fencing and lines, which staff may leave only in protective wear after showering thoroughly",
  "The detection device is continuous automatic stack monitoring with online transmission; the isolation zone is a green buffer belt at the plant boundary, where no waste or recycled material may be piled",
  "The detection device is instrumentation measuring workplace noise and illumination; the isolation zone is a separate area walled for sound, whose air may be vented directly to the atmosphere by natural ventilation"],
 "Article 2, subparagraphs 2 and 8."),

(LG,"第2條",2,"廢照明光源-處理與比率定義",
 "本標準所稱處理及資源回收再利用比率，其定義為何？",
 ["處理指以物理、化學或其他處理方法改變其物理、化學特性或成分，達到純化、精煉、分離、無害化及資源化處理之行為；資源回收再利用比率指經處理後再生料之總和重量占其總處理量之比率",
  "處理指將廢照明光源收集、分類並運輸至處理廠之行為；資源回收再利用比率指經處理後再生料之銷售金額占處理總成本之比率，並以每年度之決算數字為計算基準並報請備查",
  "處理指以焚化或掩埋方式使廢照明光源減量安定之行為；資源回收再利用比率指實際處理數量占核准處理容量之比率，未達一定比率者應報請中央主管機關備查",
  "處理指將廢照明光源置於特定地點或貯存容器內之行為；資源回收再利用比率指再生料重量占公告應回收物品標示重量之比率，並由稽核認證團體逐批認定"],"a",
 "第2條第6款：處理指廢照明光源以物理、化學或其他處理方法，改變其物理、化學特性或成分，達到純化、精煉、分離、無害化及資源化處理之行為。第7款：資源回收再利用比率指廢照明光源經處理後，再生料之總和重量占其總處理量之比率。第3款回收指收集分類、第4款貯存、第5款清除指收集運輸行為。",
 "How do these Standards define treatment and the resource recycling and reuse ratio?",
 ["Treatment changes physical or chemical properties or composition by physical, chemical or other methods to purify, refine, separate, render harmless and recover resources; the ratio is recycled material weight over total treated weight",
  "Treatment means collecting, sorting and hauling the lamps to a licensed treatment plant; the ratio is the sales value of the recycled material over the total treatment cost, computed on the audited annual final accounts each year",
  "Treatment means reducing and stabilizing the lamps by incineration or landfill; the ratio is actual throughput over approved capacity, and falling short must be filed with the central authority",
  "Treatment means placing the lamps at a designated site or in storage containers; the ratio is recycled material weight over the labelled weight of the announced items, verified batch by batch"],
 "Article 2, subparagraphs 6 and 7."),

(LG,"第3條",3,"廢照明光源-貯存量與高度",
 "廢照明光源之貯存量上限及分區貯存尺寸規定為何？",
 ["應貯存於回收、處理場（廠）內且貯存量不得超過該場（廠）前一季營運月報表申報之月平均量；分區貯存高度不得超過六公尺，相鄰高差不得超過一點五公尺，寬度及長度均不得超過二十公尺，各區域間應有一公尺以上分隔走道",
  "應貯存於回收、處理場（廠）內且貯存量不得超過該場（廠）前一年營運年報表申報之年平均量；分區貯存高度不得超過四公尺，相鄰高差不得超過二點五公尺，寬度及長度均不得超過十公尺，各區域間應有二公尺以上分隔走道",
  "應貯存於回收、處理場（廠）外之獨立倉庫且貯存量不得超過核准處理容量之二分之一；分區貯存高度不得超過三公尺，相鄰高差不得超過一公尺，寬度及長度均不得超過三十公尺，各區域間應有零點五公尺以上分隔走道",
  "應貯存於回收、處理場（廠）內且貯存量不得超過該場（廠）當月實際處理量之三倍；分區貯存高度不得超過八公尺，相鄰高差不得超過三公尺，寬度及長度均不得超過五十公尺，各區域間應有三公尺以上分隔走道"],"a",
 "第3條第2款：應貯存於回收、處理場（廠）內，且貯存量不得超過該場（廠）前一季營運月報表申報之月平均量。第5款：應具有分區、分類之貯存設施及標示，分區貯存高度不得超過6公尺，相鄰堆置之高度差不得超過1.5公尺，分區貯存寬度及長度均不得超過20公尺，各區域間應有1公尺以上之分隔走道。",
 "What storage volume cap and zoning dimensions apply to waste lighting sources?",
 ["Storage must be inside the recovery or treatment plant and may not exceed the monthly average reported in the plant's previous quarter monthly returns; zones may not exceed six metres high, one point five metres in height difference, or twenty metres wide or long, with aisles of at least one metre",
  "Storage must be inside the recovery or treatment plant and may not exceed the annual average reported in the previous year's returns; zones may not exceed four metres high, two point five metres in height difference, or ten metres wide or long, with aisles of at least two metres in width",
  "Storage must be in a separate warehouse outside the plant and may not exceed half the approved treatment capacity; zones may not exceed three metres high, one metre in height difference, or thirty metres wide or long, with aisles of at least half a metre",
  "Storage must be inside the recovery or treatment plant and may not exceed three times the current month's actual throughput; zones may not exceed eight metres high, three metres in height difference, or fifty metres wide or long, with aisles of at least three metres"],
 "Article 3, subparagraphs 2 and 5."),

(LG,"第3條",2,"廢照明光源-貯存設施要求",
 "廢照明光源之回收、貯存方法及設施，除貯存量與尺寸限制外，另有哪些規定？",
 ["應置於足以防止非意外破損之堅固貯存容器內；貯存地點容器設施應經常保持清潔完整；回收貯存場地及設施應具防止地面水、雨水及地下水流入滲透之設備且地面應為不透水鋪面；並應採繩索捆綁護網等措施防止掉落傾倒或崩塌",
  "應置於可透氣之網袋或紙箱內以利水氣散逸；貯存地點應每月清洗一次並留存紀錄；回收貯存場地得為露天堆置區但應加設防塵網及排水溝；並應採堆高機集中堆疊之方式以節省貯存空間及作業人力並作成紀錄",
  "應置於具冷藏功能之保溫容器內以防汞蒸氣逸散；貯存地點應保持恆溫恆濕並設置溫濕度紀錄器；回收貯存場地應設置於地下室並維持負壓；並應採取真空包裝方式以完全隔絕光源與空氣之接觸",
  "應置於原廠包裝紙盒內並保留出廠標示；貯存地點應設置警衛及門禁刷卡系統；回收貯存場地應具備地磅及攝影監視設備以配合稽核認證；並應每日以人工方式逐支清點數量並作成書面紀錄備查"],"a",
 "第3條第1款、第3款、第4款、第6款：應置於足以防止非意外破損之堅固貯存容器內；貯存之地點、容器、設施應經常保持清潔完整，不得有溢散、洩漏、飛散、散發惡臭、污染地面或積水；回收、貯存場地及貯存設施應具有防止地面水、雨水及地下水流入、滲透之設備或措施，且貯存地面應為不透水鋪面；分區分類貯存者應採繩索捆綁、護網或其他必要措施防止掉落、傾倒或崩塌。",
 "Besides volume and dimension limits, what do the recovery and storage rules require?",
 ["Placement in sturdy containers preventing non-accidental breakage; storage sites, containers and facilities kept clean and intact; sites and facilities with equipment preventing surface, rain and groundwater ingress and an impervious floor; and roping or netting against falling, toppling or collapse",
  "Placement in breathable mesh bags or cartons so moisture escapes; storage sites washed monthly with records kept; sites may be open-air piles with dust netting and drains added; and forklift stacking to save storage space and labour",
  "Placement in refrigerated insulated containers to stop any mercury vapour escaping; sites kept at a constant temperature and humidity with recorders installed; sites located in basements kept under negative pressure at all times; and vacuum packing to cut off all contact with the outside air",
  "Placement in the original manufacturer's cartons keeping the factory labels; sites with guards and card access control; sites equipped with a weighbridge and video surveillance for audit certification; and daily manual counting recorded in writing"],
 "Article 3, subparagraphs 1, 3, 4 and 6."),

(LG,"第4條",2,"廢照明光源-清除工具",
 "清除廢照明光源之車輛或其他清運工具，應符合哪些規定？",
 ["應設置具有標示之堅固貯存容器；清除過程中應設置防水措施，並避免發生廢照明光源破裂、溢出、洩漏、飛散、掉落等造成污染環境或危害人體健康之情事",
  "應設置具有冷藏功能之密閉貯存槽；清除過程中應設置抽氣設備並全程維持負壓，避免汞蒸氣逸散至車廂外或造成駕駛人員之健康危害情事",
  "應設置經檢驗合格之計量與定位設備；清除過程中應設置即時影像錄影措施，並由二名以上專業技術人員全程隨車押運至處理廠交付卸貨",
  "應設置具有標示之可回收紙箱容器；清除過程中應設置遮陽措施，並避免因日照升溫致廢照明光源內部氣體膨脹而破裂造成環境污染之情事"],"a",
 "第4條第1項：清除廢照明光源之車輛或其他清運工具，應設置具有標示之堅固貯存容器。第2項：清除過程中應設置防水措施，並避免發生廢照明光源破裂、溢出、洩漏、飛散、掉落等造成污染環境或危害人體健康之情事。第9條第1款並要求含汞物質於清除過程中不得洩漏於大氣。",
 "What must vehicles or other haulage tools for waste lighting sources provide?",
 ["Sturdy labelled storage containers; and waterproofing during clearance, avoiding breakage, spillage, leakage, scattering or falling that would pollute the environment or harm human health",
  "Sealed refrigerated storage tanks; and extraction equipment maintaining negative pressure throughout, so mercury vapour cannot escape the compartment or harm the driver",
  "Certified metering and positioning equipment; and live video recording throughout, with at least two professional technicians escorting the load to the treatment plant for unloading",
  "Labelled recyclable carton containers; and shade during clearance, so sunlight does not heat and expand the internal gas and burst the lamps, polluting the environment"],
 "Article 4, paragraphs 1 and 2."),

(LG,"第5條",3,"廢照明光源-隔離區設置",
 "下列何者之處理設備、貯存設施及處理後產生之廢棄物，應設置或貯存於隔離區？",
 ["汞蒸餾處理設備、汞與其化合物之貯存設施、未經汞回收處理作業前之螢光粉，以及未經汞回收處理作業前之活性碳",
  "破碎分選處理設備、含鉛玻璃之貯存設施、已完成汞回收處理作業後之螢光粉，以及已完成汞回收處理後之活性碳",
  "發光二極體處理設備、金屬再生料之貯存設施、經處理後產出之其他玻璃碎屑，以及廠內回收之廢水處理污泥餅",
  "廢氣處理設備之風車機組、包裝作業區之堆高機具、暫存待運之再生料棧板，以及員工休息室與更衣盥洗設施"],"a",
 "第5條：汞蒸餾處理設備、汞與其化合物之貯存設施、未經汞回收處理作業前之螢光粉、未經汞回收處理作業前之活性碳等四類之處理設備、貯存設施及處理後產生之廢棄物，應設置、貯存於隔離區。隔離區之定義見第2條第8款，其內氣體不得未經空氣污染防制設備處理即與大氣接觸。",
 "Which treatment equipment, storage facilities and residues must be placed or stored in the isolation zone?",
 ["Mercury distillation equipment, storage facilities for mercury and its compounds, phosphor powder before mercury recovery, and activated carbon before mercury recovery",
  "Crushing and sorting equipment, storage facilities for leaded glass, phosphor powder after mercury recovery is complete, and activated carbon after mercury recovery",
  "LED treatment equipment, storage facilities for metal recycled material, other glass cullet produced after treatment, and dewatered sludge from the plant's wastewater",
  "Fan units of the waste gas treatment system, forklifts in the packing area, pallets of recycled material awaiting despatch, and staff rest, changing and washing rooms"],
 "Article 5, subparagraphs 1 to 4."),

(LG,"第6條",3,"廢照明光源-處理設施",
 "廢照明光源之處理設施應符合哪些規定？",
 ["應具排水及廢水截流設施；應設置於有屋頂且四周為混凝土結構之場（廠）內且地面為不透水鋪面；應具汞回收設施及防止溢散惡臭污染之措施，處理設備應設防止粉塵逸散措施並維持負壓，且應每日自主檢查設備負壓及粉塵狀況並記錄",
  "應具備雨水回收及貯留設施；應設置於有屋頂但四周開放之棚架內且地面為瀝青鋪面；應具汞回收設施及除臭設備，處理設備應設防止粉塵逸散措施並維持正壓，且應每月委託環境檢測機構檢查設備狀況並記錄備查",
  "應具備廢水回收全量再利用設施；應設置於獨立密閉之地下室內且地面為環氧樹脂鋪面；應具汞蒸氣連續監測設備，處理設備應維持常壓並設置自然通風，且應每季自主檢查粉塵狀況並將紀錄公告於網站",
  "應具備排水及油水分離設施；應設置於四周有圍籬之露天場區並鋪設碎石地面；應具汞回收設施及隔音設備，處理設備應設防爆裝置並維持負壓，且應每年自主檢查設備負壓一次並將紀錄送交地方主管機關"],"a",
 "第6條第1款至第3款、第5款：應具有排水及廢水截流設施；應設置於有屋頂且四周為混凝土結構之場（廠）內，其地面應為不透水鋪面；應具有汞回收設施及防止廢棄物及廢水溢散、散發惡臭、污染地面及影響四周環境品質之必要措施，處理設備應設置防止粉塵逸散措施並維持設備負壓，另應每日自主檢查設備負壓及粉塵狀況並記錄之；並應備有緊急應變措施及污染防治計畫書。",
 "What must a waste lighting source treatment facility satisfy?",
 ["Drainage and wastewater interception; siting in a roofed plant with concrete walls all round on an impervious floor; mercury recovery equipment and measures against scattering, odour and pollution, with dust controls, negative pressure, and daily self-checks of pressure and dust recorded",
  "Rainwater harvesting and storage; siting under a roofed but open-sided shed on an asphalt floor; mercury recovery equipment and deodorizers, with dust controls, positive pressure, and monthly checks by an accredited laboratory recorded",
  "Full wastewater recovery and reuse; siting in a sealed basement on an epoxy floor; continuous mercury vapour monitoring, with equipment at ambient pressure and natural ventilation, and quarterly self-checks of dust posted online",
  "Drainage and oil-water separation facilities; siting in a fenced open-air yard on a gravel floor; mercury recovery equipment and sound insulation, with explosion-proofing and negative pressure maintained, and one annual self-check filed with the local competent authority for the record"],
 "Article 6, subparagraphs 1 to 3 and 5."),

(LG,"第6條",2,"廢照明光源-廠區面積",
 "廢照明光源處理廠之廠區及專用廠房面積下限為何？有何例外？",
 ["廠區面積（含暫存區）不得低於六百坪，其中廢照明光源處理專用廠房面積不得低於三百坪；但僅申請處理發光二極體廢照明光源項目者不在此限",
  "廠區面積（含暫存區）不得低於三百坪，其中廢照明光源處理專用廠房面積不得低於六百坪；但僅申請處理含汞廢照明光源項目者不在此限",
  "廠區面積（含暫存區）不得低於一千坪，其中廢照明光源處理專用廠房面積不得低於五百坪；但已取得工廠登記證明文件之既設廠不在此限",
  "廠區面積（含暫存區）不得低於六百平方公尺，其中專用廠房面積不得低於三百平方公尺；但位於工業區內之處理廠場不在此限而免受限制"],"a",
 "第6條第4款：廠區面積（含暫存區）不得低於600坪，其中廢照明光源處理專用廠房面積不得低於300坪；但僅申請處理發光二極體（LED）廢照明光源項目者，不在此限。第8條第2項並規定LED廢照明光源不得與含汞廢照明光源共用處理設備。",
 "What minimum plant and dedicated building areas apply, and what is excepted?",
 ["The plant area including temporary storage may not be under six hundred ping, of which the dedicated lighting treatment building may not be under three hundred ping; LED-only applicants are excepted",
  "The plant area including temporary storage may not be under three hundred ping, of which the dedicated lighting treatment building may not be under six hundred ping; mercury-only applicants are excepted",
  "The plant area including temporary storage may not be under one thousand ping, of which the dedicated building may not be under five hundred ping; existing plants with factory registration are excepted",
  "The plant area including temporary storage may not be under six hundred square metres, of which the dedicated building may not be under three hundred square metres; plants in industrial parks are excepted"],
 "Article 6, subparagraph 4."),

(LG,"第7條",1,"廢照明光源-境內處理",
 "廢照明光源之處理地點及處理方式有何限制？",
 ["應於境內進行處理，且不得將未經回收、再利用之廢照明光源直接焚化或掩埋處理",
  "得經中央主管機關核准後輸出至經濟合作暨發展組織會員國處理，境內則不得焚化",
  "應於境內進行處理，惟經地方主管機關同意後得將含汞光源直接以掩埋方式處置",
  "得由處理業者視處理成本自行選擇境內或境外處理，並得以焚化方式進行減量處理"],"a",
 "第7條：廢照明光源應於境內進行處理，且不得將未經回收、再利用之廢照明光源直接焚化或掩埋處理。廢電子電器暨廢資訊物品回收貯存清除處理方法及設施標準第6條亦有應於境內處理且不得直接焚化或掩埋之相同限制。",
 "What limits apply to where and how waste lighting sources are treated?",
 ["They must be treated domestically, and lamps not yet recovered or reused may not be directly incinerated or landfilled",
  "They may be exported to an OECD member with central approval, while incineration is barred within the country",
  "They must be treated domestically, but mercury lamps may be landfilled directly once the local authority consents",
  "Operators may choose domestic or overseas treatment on cost grounds, and may incinerate them to reduce volume"],
 "Article 7."),

(LG,"第8條",2,"廢照明光源-合併處理限制",
 "廢照明光源之處理，關於合併處理及設備共用有何限制？",
 ["應回收之廢照明光源不得與其他非屬公告應回收之廢照明光源合併處理；發光二極體廢照明光源不得與含汞廢照明光源共用處理設備",
  "應回收之廢照明光源得與其他非屬公告應回收之廢照明光源合併處理；發光二極體廢照明光源得與含汞廢照明光源共用處理設備以節省成本",
  "應回收之廢照明光源不得與其他事業廢棄物合併處理；含汞廢照明光源與含鉛玻璃光源不得共用貯存容器但得共用同一處理設備",
  "應回收之廢照明光源應與進口廢照明光源分別處理；發光二極體廢照明光源得與含汞廢照明光源共用設備但應於處理前後清洗設備"],"a",
 "第8條第1項：應回收之廢照明光源不得與其他非屬公告應回收之廢照明光源合併處理。第2項：LED廢照明光源不得與含汞廢照明光源共用處理設備。第9條第6款並要求LED廢照明光源與含汞廢照明光源之再生料與廢棄物應分別收集、貯存。",
 "What limits apply to combined treatment and shared equipment for waste lighting sources?",
 ["Announced recyclable lamps may not be treated together with lamps outside the announced scope; LED lamps may not share treatment equipment with mercury-bearing lamps",
  "Announced recyclable lamps may be treated together with lamps outside the announced scope; LED lamps may share treatment equipment with mercury-bearing lamps to save cost",
  "Announced recyclable lamps may not be treated with other industrial waste; mercury lamps and leaded glass lamps may not share containers but may share treatment equipment",
  "Announced recyclable lamps must be treated separately from imported lamps; LED lamps may share equipment with mercury lamps if the equipment is washed before and after"],
 "Article 8, paragraphs 1 and 2."),

(LG,"第9條",3,"廢照明光源-再生料處置",
 "廢照明光源處理及其再生料、衍生廢棄物之處置，應符合哪些規定？",
 ["含汞物質於回收貯存清除處理過程中不得洩漏於大氣；含汞物質、含鉛玻璃及其他衍生廢棄物應妥善處理且螢光粉應妥善收集貯存；廠內應具備汞偵測裝置；含汞螢光粉之處置應依事業廢棄物相關規定辦理",
  "含汞物質得於處理設備維修期間短暫排放至大氣；含鉛玻璃應逕送掩埋場處置而螢光粉得混入一般廢棄物；廠內得以人工目視取代汞偵測裝置；含汞螢光粉之處置得依一般廢棄物相關規定辦理",
  "含汞物質應於處理後經稀釋始得排放至大氣；含鉛玻璃及螢光粉應全數輸出至國外處理；廠內應設置噪音偵測裝置並連線傳輸；含汞螢光粉之處置應依土壤及地下水污染整治法規定辦理",
  "含汞物質應於每季集中一次排放至大氣以利監測；含鉛玻璃應作為道路級配粒料使用而螢光粉得回填；廠內應具備粉塵偵測裝置；含汞螢光粉之處置應依空氣污染防制法相關規定辦理"],"a",
 "第9條第1款至第4款、第6款：含汞物質於回收、貯存、清除、處理過程中不得洩漏於大氣；含汞物質、含鉛玻璃及其他衍生廢棄物應妥善處理，光源處理過程中螢光粉應妥善收集、貯存；廠內應具備汞偵測裝置，廢氣及廢水排放與勞工作業環境空氣品質應依相關法規辦理；含汞螢光粉之處置應依事業廢棄物相關規定辦理；LED與含汞廢照明光源之再生料與廢棄物應分別收集、貯存。",
 "What rules govern the recycled materials and residues from waste lighting source treatment?",
 ["Mercury-bearing substances may not escape to the atmosphere at any stage; mercury substances, leaded glass and other residues must be properly handled and phosphor properly collected and stored; a mercury detector is required in the plant; mercury phosphor follows the industrial waste rules",
  "Mercury-bearing substances may be briefly released during equipment maintenance; leaded glass may go straight to landfill and phosphor may be mixed with general waste; visual checks may replace the mercury detector in the plant; mercury phosphor follows the general waste disposal rules",
  "Mercury-bearing substances may be released after dilution following treatment; leaded glass and phosphor must all be exported for treatment; a noise detector with online transmission is required; mercury phosphor follows the soil and groundwater remediation rules",
  "Mercury-bearing substances may be released once a quarter in one batch for monitoring; leaded glass may be used as road aggregate and phosphor backfilled; a dust detector is required; mercury phosphor follows the air pollution control rules"],
 "Article 9, subparagraphs 1 to 4 and 6."),

(LG,"第10條",3,"廢照明光源-補貼要件",
 "依本法第十八條第五項向資源回收管理基金申請廢照明光源回收清除處理補貼者，應符合哪些規定？",
 ["應為依本法第十六條第四項辦法規範之責任業者或依第十八條第四項辦法辦理登記之回收處理業；依稽核認證作業手冊設置秤重計量設備、攝錄影監視系統及專用電表；資源回收再利用比率應符合中央主管機關公告之補貼費率規定；並提具處置應變計畫及試運轉報告",
  "應為依公司法設立且實收資本額達五千萬元以上之事業；依地方主管機關作業要點設置地磅及門禁刷卡系統；資源回收再利用比率應達百分之九十以上；並提具環境影響評估說明書及公民參與說明會紀錄經核定，並按季辦理稽核認證及查核申報",
  "應為取得甲級廢棄物處理機構許可證之公民營機構；依稽核認證團體要求設置車輛衛星定位及電子聯單系統；資源回收再利用比率應由業者自行訂定並報備；並提具處理設備之保險證明及銀行履約保證文件",
  "應為經目的事業主管機關核准之再利用機構；依中央主管機關公告設置連續自動監測設備並連線傳輸；資源回收再利用比率應逐年提高百分之五；並提具員工職業安全衛生教育訓練紀錄及健康檢查報告"],"a",
 "第10條：申請補貼者應為依本法第16條第4項訂定之辦法規範之責任業者或依本法第18條第4項訂定之辦法向主管機關辦理登記之回收、處理業；依中央主管機關所定稽核認證作業手冊設置用以秤重之計量設備、攝錄影監視系統、專用電表或其他配合稽核認證之設備或措施；資源回收再利用比率應符合中央主管機關公告之應回收廢棄物回收清除處理補貼費率規定；並應提具處置應變計畫經核定及清除處理之型式、設備、流程、質量平衡圖與試運轉報告。",
 "What must an applicant satisfy to claim a recycling subsidy for waste lighting sources?",
 ["Be a responsible enterprise under the Article 16-4 rules or a recovery or treatment operator registered under the Article 18-4 rules; install weighing, video surveillance and dedicated meters per the audit manual; meet the announced subsidy rate ratio; and file a contingency plan and trial run report",
  "Be a company incorporated with paid-in capital of at least fifty million; install a weighbridge and card access per the local authority's directions; achieve a recycling ratio of at least ninety percent; and file an approved environmental impact statement and public hearing records with the authority",
  "Be a licensed institution holding a class A waste treatment permit; install vehicle satellite positioning and electronic manifests as the audit body requires; set and file its own recycling ratio; and file equipment insurance and a bank performance guarantee",
  "Be a reuse institution approved by the industry competent authority; install continuous automatic monitoring with online transmission as announced; raise the recycling ratio by five percent each year; and file safety training records and health check reports"],
 "Article 10, subparagraphs 1 to 5."),

(LG,"第11條",2,"廢照明光源-衍生廢棄物",
 "廢照明光源經回收、貯存、清除、處理後衍生之廢棄物，應如何辦理？",
 ["應依本標準規定辦理，其屬事業廢棄物者除應依事業廢棄物貯存清除處理方法及設施標準辦理分類貯存清除及處理外，並應符合本法第二十八條規定之清理方式；其輸出應符合本法第三十八條規定",
  "應依本標準規定辦理，其屬事業廢棄物者得比照一般廢棄物交由執行機關清運處理，免依事業廢棄物相關標準辦理；其輸出僅需檢附成分分析報告向海關報備即可而免申請許可",
  "應由原回收業者收回自行處置並留存流向紀錄備查，其屬有害事業廢棄物者始應依相關標準辦理；其輸出應經地方主管機關核准並副知中央主管機關備查後辦理",
  "應全數貯存於隔離區內俟中央主管機關指定處理機構處理，其屬事業廢棄物者免另依相關標準辦理；其輸出應依資源回收再利用法規定申請許可後辦理"],"a",
 "第11條第1項：廢照明光源經回收、貯存、清除、處理後衍生之廢棄物，應依本標準規定辦理，其屬事業廢棄物者，除應依事業廢棄物貯存清除處理方法及設施標準規定辦理分類貯存、清除及處理外，並應符合本法第28條規定之清理方式。第2項：前項衍生廢棄物之輸出，應符合本法第38條規定。",
 "How must residues from waste lighting source handling be dealt with?",
 ["Under these Standards; if industrial waste, also under the industrial waste storage, clearance and treatment standards for sorted storage and the disposal methods in Article 28; exports must comply with Article 38",
  "Under these Standards; if industrial waste, it may be cleared by the executing agency like general waste without the industrial waste standards; exports need only a composition report filed with customs",
  "The original recovery operator must take it back and handle it with flow records kept; only hazardous industrial waste follows the relevant standards; exports need local approval copied centrally",
  "All of it must be kept in the isolation zone awaiting a centrally designated institution, industrial waste needing no other standards; exports need a permit under the Resource Recycling Act"],
 "Article 11, paragraphs 1 and 2."),

(LG,"第12條",1,"廢照明光源-刪除條文",
 "廢照明光源回收貯存清除處理方法及設施標準第十二條之現行狀態為何？",
 ["該條業經刪除，現行條文僅保留條次而無任何規範內容，相關事項回歸其他各條規定",
  "該條規定處理業應每季申報營運月報表及資源回收再利用比率之計算方式及格式",
  "該條規定既有處理業者應於修正發布後六個月內完成改善及改善期間免罰之規定",
  "該條規定處理設備汞收集率之檢測方法及頻率，並授權中央主管機關另定作業要點"],"a",
 "第12條：（刪除）。條文刪除後條次仍予保留，以免影響其他條文之引用關係。本標準之補貼要件依第10條、衍生廢棄物依第11條辦理，施行日期則依第13條規定辦理。",
 "What is the current status of Article 12 of the Standards for Waste Lighting Sources?",
 ["It has been deleted, the article number being kept without any substantive content, and related matters follow the other articles",
  "It prescribes quarterly operating returns and the method and format for computing the resource recycling ratio",
  "It gives existing operators six months from promulgation to correct, with an exemption from penalties meanwhile",
  "It prescribes the method and frequency of testing the mercury collection rate and delegates the making of operating directions"],
 "Article 12 is deleted."),

(LG,"第13條",2,"廢照明光源-施行日期",
 "廢照明光源回收貯存清除處理方法及設施標準之施行日期如何規定？",
 ["本標準自發布日施行；中華民國一百零五年十月二十五日修正條文，除第八條第二項及第九條第六款自一百零六年一月一日施行外，自發布日施行",
  "本標準自發布日施行；中華民國一百零五年十月二十五日修正條文，除第六條第四款及第七條自一百零七年一月一日施行外，自發布日施行",
  "本標準自發布後六個月施行；中華民國一百零五年十月二十五日修正條文，除第五條及第十條自一百零六年七月一日施行外，自發布日施行",
  "本標準自發布日施行；中華民國一百零五年十月二十五日修正條文全部自一百零六年一月一日施行，並就既有業者另定一年改善期間"],"a",
 "第13條第1項：本標準自發布日施行。第2項：本標準中華民國105年10月25日修正條文，除第8條第2項（LED不得與含汞光源共用處理設備）及第9條第6款（LED與含汞光源再生料廢棄物應分別收集貯存）自106年1月1日施行外，自發布日施行。本標準最近修正日期為110年7月14日。",
 "When do the Standards for Waste Lighting Sources take effect?",
 ["On the date of promulgation; the amendments of 25 October 2016 took effect on promulgation except Article 8-2 and Article 9-6, which took effect on 1 January 2017",
  "On the date of promulgation; the amendments of 25 October 2016 took effect on promulgation except Article 6-4 and Article 7, which took effect on 1 January 2018",
  "Six months after promulgation; the amendments of 25 October 2016 took effect on promulgation except Articles 5 and 10, which took effect on 1 July 2017",
  "On the date of promulgation; all the amendments of 25 October 2016 took effect on 1 January 2017, with a one-year correction period for existing operators"],
 "Article 13, paragraphs 1 and 2."),

(EE,"第1條",1,"廢電器-法源適用",
 "廢電子電器暨廢資訊物品回收貯存清除處理方法及設施標準之法源依據及適用關係為何？",
 ["依廢棄物清理法第十八條第一項規定訂定；其回收貯存清除處理方法及設施依本標準規定，本標準未規定者適用其他法令之規定",
  "依廢棄物清理法第十五條第二項規定訂定；其回收貯存清除處理方法及設施應優先適用其他法令，本標準僅於無規定時補充適用",
  "依廢棄物清理法第三十九條規定訂定；其回收貯存清除處理方法及設施依本標準規定，本標準未規定者應報請中央主管機關核定",
  "依資源回收再利用法第八條規定訂定；其回收貯存清除處理方法及設施依本標準規定，並得由處理業者依實際作業需要調整"],"a",
 "第1條第1項、第2項：本標準依廢棄物清理法第18條第1項規定訂定；廢電子電器暨廢資訊物品回收貯存清除處理方法及設施依本標準之規定，本標準未規定者適用其他法令之規定。第2條第1款、第2款並將廢電子電器及廢資訊物品定義為依本法第15條第2項公告應回收者。",
 "What is the legal basis of the Standards for Waste Electronics and IT Products and how do other laws apply?",
 ["Enacted under Article 18, paragraph 1 of the Waste Disposal Act; the methods and facilities follow these Standards, with other laws applying to uncovered matters",
  "Enacted under Article 15, paragraph 2 of the Waste Disposal Act; other laws apply first and these Standards supplement them only where nothing is provided",
  "Enacted under Article 39 of the Waste Disposal Act; the methods follow these Standards, and uncovered matters must be submitted for central authority approval",
  "Enacted under Article 8 of the Resource Recycling Act; the methods follow these Standards, and treatment operators may adjust them as operations require"],
 "Article 1, paragraphs 1 and 2."),

(EE,"第2條",2,"廢電器-名詞定義",
 "本標準所稱資源回收再利用比率及機械處理系統，其定義為何？",
 ["資源回收再利用比率指經處理後產出之再生料重量占其處理總量之重量百分比；機械處理系統指由不同機械設備單元組合可連續處理廢電子電器、廢資訊物品之設備系統",
  "資源回收再利用比率指經處理後再生料之銷售金額占處理總成本之百分比；機械處理系統指以人工拆解為主並輔以機械破碎之半自動化處理作業程序及流程",
  "資源回收再利用比率指實際處理重量占核准處理容量之重量百分比；機械處理系統指由單一破碎機所構成並得逐批分次處理各類物品之獨立設備",
  "資源回收再利用比率指再生料重量占公告應回收物品標示重量之百分比；機械處理系統指經中央主管機關認證並取得專利之自動化分選及選別設備"],"a",
 "第2條第7款：資源回收再利用比率指廢電子電器、廢資訊物品經處理後產出之再生料重量，占其處理總量之重量百分比。第8款：機械處理系統指由不同機械設備單元組合可連續處理廢電子電器、廢資訊物品之設備系統。第5條第7款並就以機械處理系統處理含汞零組件者定有試驗程序。",
 "How do these Standards define the recycling ratio and the mechanical treatment system?",
 ["The ratio is the weight of recycled material produced as a percentage of total treated weight; the mechanical treatment system is a system of different machine units able to treat the items continuously",
  "The ratio is the sales value of recycled material as a percentage of total treatment cost; the mechanical treatment system is a semi-automated process of manual dismantling aided by machine crushing",
  "The ratio is actual treated weight as a percentage of approved treatment capacity; the mechanical treatment system is a single crusher able to treat each category in separate batches",
  "The ratio is recycled material weight as a percentage of the labelled weight of announced items; the mechanical treatment system is patented sorting equipment certified by the central authority"],
 "Article 2, subparagraphs 7 and 8."),

(EE,"第3條",3,"廢電器-堆置高度",
 "廢電子電器、廢資訊物品貯存之堆置高度及分區尺寸規定為何？",
 ["堆置貯存高度不得超過三公尺，相鄰堆置高差不得超過一點五公尺；使用固定鋼架、支架或擋樁堆置者高度不得超過四點五公尺；分區貯存寬度及長度不得超過二十公尺，各區域間應有一公尺以上分隔走道",
  "堆置貯存高度不得超過五公尺，相鄰堆置高差不得超過二點五公尺；使用固定鋼架、支架或擋樁堆置者高度不得超過六公尺；分區貯存寬度及長度不得超過三十公尺，各區域間應有二公尺以上分隔走道",
  "堆置貯存高度不得超過二公尺，相鄰堆置高差不得超過零點五公尺；使用固定鋼架、支架或擋樁堆置者高度不得超過三公尺；分區貯存寬度及長度不得超過十公尺，各區域間應有三公尺以上分隔走道",
  "堆置貯存高度不得超過四公尺，相鄰堆置高差不得超過一公尺；使用固定鋼架、支架或擋樁堆置者高度不得超過六公尺；分區貯存寬度及長度不得超過五十公尺，各區域間應有零點五公尺以上分隔走道"],"a",
 "第3條第5款：堆置貯存高度不得超過3公尺，相鄰堆置之高差不得超過1.5公尺；使用固定鋼架、支架或擋樁等進行堆置者，堆置高度不得超過4.5公尺；分區貯存寬度及長度不得超過20公尺，各區域間應有1公尺以上之分隔走道。第6款並要求四周設置圍籬及貯存專區並採繩索捆綁護網等防止掉落倒塌。",
 "What stacking heights and zoning dimensions apply to storing waste electronics and IT products?",
 ["Stacking may not exceed three metres with adjacent stacks differing by no more than one point five metres; with fixed racks, frames or posts, four point five metres; zones may not exceed twenty metres wide or long with aisles of at least one metre",
  "Stacking may not exceed five metres with adjacent stacks differing by no more than two point five metres; with fixed racks, frames or posts, six metres; zones may not exceed thirty metres wide or long with aisles of at least two full metres",
  "Stacking may not exceed two metres with adjacent stacks differing by no more than half a metre; with fixed racks, frames or posts, three metres; zones may not exceed ten metres wide or long with aisles of at least three metres",
  "Stacking may not exceed four metres with adjacent stacks differing by no more than one metre; with fixed racks, frames or posts, six metres; zones may not exceed fifty metres wide or long with aisles of at least half a metre"],
 "Article 3, subparagraph 5."),

(EE,"第3條",2,"廢電器-回收貯存規定",
 "廢電子電器、廢資訊物品之回收、貯存、清除方法及設施，另有哪些規定？",
 ["於回收貯存清除過程不得拆解；運送車輛機具應設防雨水措施；貯存地點不得有冷媒、螢光粉、液晶逸散或洩漏；應依公告項目分類分區貯存並於明顯處以中文標示；貯存廠場應具排水與污染物截流設施且地面為不透水鋪面",
  "於回收貯存清除過程應先行拆解以利分類；運送車輛機具應設防塵網措施；貯存地點得有少量冷媒逸散但應予記錄；得依委託人分區貯存並以英文標示；貯存廠場得為透水性碎石地面以利雨水下滲減少積水情形",
  "於回收貯存清除過程應先破碎減量；運送車輛機具應設冷藏設備；貯存地點應保持恆溫恆濕並記錄溫濕度；應依製造廠牌分類貯存並標示型號年份；貯存廠場應設置於地下室並維持負壓以防氣體外洩",
  "於回收貯存清除過程得由業者決定是否拆解；運送車輛機具應設衛星定位設備；貯存地點應每日消毒一次並留存紀錄；應依重量級距分區貯存並標示重量；貯存廠場應設置圍牆及廢水處理設施並取得排放許可"],"a",
 "第3條第1款至第4款、第7款：於回收、貯存、清除過程不得拆解；運送之車輛機具應設置防雨水措施並避免溢散、洩漏、掉落；貯存地點、容器、設施應經常保持清潔完整，不得有溢散、洩漏、飛散、散發惡臭、污染地面、積水，且不得有冷媒、螢光粉、液晶逸散或洩漏；應依公告項目分類分區貯存並於明顯處以中文標示其種類及名稱；貯存廠（場）應具有排水與污染物截流設施且地面應為不透水鋪面。",
 "What further rules govern the recovery, storage and clearance of waste electronics and IT products?",
 ["No dismantling during recovery, storage or clearance; vehicles must have rain protection; sites must be free of refrigerant, phosphor or liquid crystal escape; sorted zoned storage by announced category labelled conspicuously in Chinese; and drainage and interception with an impervious floor",
  "Dismantling first is required to aid sorting; vehicles must have dust netting; a little refrigerant escape is tolerated if recorded; storage may be zoned by client and labelled in English; and a permeable gravel floor is allowed on site so that rain drains away and ponding is reduced",
  "Crushing to reduce volume must precede storage; vehicles must have refrigeration; sites must be kept at constant temperature and humidity with records; storage must be zoned by brand and labelled with model and year; and sites must be in basements under negative pressure",
  "Operators may decide whether to dismantle; vehicles must carry satellite positioning; sites must be disinfected daily with records kept; storage must be zoned by weight bracket and labelled with weight; and sites must have walls and permitted wastewater treatment"],
 "Article 3, subparagraphs 1 to 4 and 7."),

(EE,"第4條",2,"廢電器-處理廠規定",
 "廢電子電器、廢資訊物品處理廠（場）應符合哪些規定？",
 ["處理作業應在具屋頂且四周有圍牆及具堅固基礎結構之封閉廠房內進行；與處理設施及廢棄物接觸之地面應為混凝土或不透水鋪面；周圍應有油類或液體之截流收集及油水分離設施；破碎粉碎設備應具隔音及粉塵收集設備",
  "處理作業得在有屋頂但四周開放之棚架內進行；與處理設施接觸之地面應為瀝青鋪面並保持水平；周圍應設置雨水貯留及回收再利用之設施；破碎粉碎設備應具備溫度感應警示裝置及自動停機設備",
  "處理作業應在露天但設有防風網之場區內進行；與處理設施接觸之地面應為碎石鋪面以利排水；周圍應設置綠帶緩衝區及景觀圍籬；破碎粉碎設備應具備防爆裝置及惰性氣體充填設備",
  "處理作業應在密閉之地下室內進行並維持負壓；與處理設施接觸之地面應為環氧樹脂鋪面；周圍應設置緊急沖淋及洗眼設備；破碎粉碎設備應具備連續自動監測及即時連線傳輸設備"],"a",
 "第4條第2款至第5款：處理作業應在具有屋頂且四周有圍牆及具堅固基礎結構之封閉廠房內進行；與處理設施、廢棄物接觸之地面應為混凝土或不透水鋪面，且不得將污水、油類等滲入地下污染土壤或地下水體；處理設施周圍應有油類或液體之截流、收集及油水分離之設施；進行破碎、粉碎及其他可能產生噪音及粉塵之處理設備應具備隔音及粉塵收集設備。第6款、第7款並要求良好光線或足夠照明及緊急應變設備與污染防制設施。",
 "What must a treatment plant for waste electronics and IT products satisfy?",
 ["Treatment inside a roofed, walled, structurally sound enclosed building; floors in contact with equipment and waste of concrete or impervious paving; oil or liquid interception, collection and oil-water separation around the equipment; and sound insulation and dust collection on crushing equipment",
  "Treatment under a roofed but open-sided shed; floors in contact with equipment of level asphalt paving; rainwater retention and reuse facilities around the equipment; and temperature alarms and automatic shutdown on crushing equipment",
  "Treatment in an open-air yard behind windbreak netting; floors in contact with the equipment and waste of gravel paving to aid drainage; a green buffer belt and landscaped fencing around the plant area; and explosion-proofing and inert gas filling equipment fitted on all the crushing units",
  "Treatment in a sealed basement kept under negative pressure; floors in contact with equipment of epoxy paving; emergency showers and eyewash stations around it; and continuous automatic monitoring with live transmission on crushing equipment"],
 "Article 4, subparagraphs 2 to 5."),

(EE,"第5條",2,"廢電器-含汞零組件",
 "廢電子電器、廢資訊物品處理過程之分類收集及含汞零組件之處理，有何規定？",
 ["處理過程鐵金屬、非鐵金屬、塑膠、玻璃、二次電池、混合五金廢料等應分類收集；含汞零組件應以非破壞方式收集，汞蒸氣不得外洩於大氣，並應貯存於具備防滲漏及逸出功能之密閉容器內",
  "處理過程各類材質得混合收集後委外分選；含汞零組件應以破碎方式收集以利後續熔煉，汞蒸氣得經稀釋後排放於大氣，並得貯存於一般敞口容器內以利通風散熱並得混合貯存",
  "處理過程僅需將金屬與非金屬二大類分別收集；含汞零組件應以水洗方式收集並將洗滌水排入廢水處理設施，汞蒸氣應於夜間集中排放，並貯存於冷藏設備內",
  "處理過程應依委託人別分類收集並標示來源；含汞零組件應以人工拆解方式收集並由技術員逐件檢視，汞蒸氣得於設備維修時排放，並貯存於具透氣孔之容器內"],"a",
 "第5條第1款：處理過程鐵金屬、非鐵金屬、塑膠、玻璃、二次電池、混合五金廢料等應分類收集。第2款：含汞零組件應以非破壞方式收集，汞蒸氣不得外洩於大氣，並應貯存於具備防滲漏及逸出功能之密閉容器內。第9款並要求處理後產出之再生料及其他廢棄物應分類分區貯存並以中文標示種類及名稱。",
 "What rules govern sorted collection and mercury-bearing components during treatment?",
 ["Ferrous and non-ferrous metals, plastics, glass, secondary batteries and mixed scrap metal must be collected separately; mercury components must be collected without destruction, no vapour may escape, and they must be kept in sealed leak- and escape-proof containers",
  "Materials may be collected mixed and later sorted by an outside contractor; mercury components should be crushed for later smelting, the vapour may be diluted before its release, and open containers may be used in the plant for ventilation and cooling purposes",
  "Only metals and non-metals need be collected separately; mercury components should be collected by washing with the water sent to treatment, vapour released at night in one batch, and stored in refrigeration",
  "Materials must be collected by client with the source labelled; mercury components must be dismantled by hand and inspected piece by piece, vapour may be released during maintenance, and vented containers may be used"],
 "Article 5, subparagraphs 1, 2 and 9."),

(EE,"第5條",3,"廢電器-陰極射線管處理",
 "處理具陰極射線管（CRT）之廢電子電器、廢資訊物品時，應符合哪些規定？",
 ["陰極射線管應先卸除真空並分離錐管玻璃與面板玻璃；螢光粉應妥善收集貯存於密閉容器內並於獨立密閉之運作空間內收集；應於抽氣櫃內收集吸除螢光粉並於排氣口裝設集塵處理裝置；螢光粉吸除時不得逸散或洩漏於環境",
  "陰極射線管應先加熱軟化並整支破碎後篩選玻璃；螢光粉應收集貯存於敞口容器內並得於一般作業區收集；應於露天場地以水沖洗方式收集螢光粉並於排水口裝設攔污柵；螢光粉沖洗時應避免大量流失於廠外",
  "陰極射線管應先浸泡酸液以溶解螢光粉塗層；螢光粉應中和後排入廢水處理設施並免另行貯存；應於一般通風之作業區以吸塵器收集殘留粉塵並於出口裝設濾網；作業時人員應佩戴口罩以防吸入粉塵",
  "陰極射線管應整支送交熔煉業者處理而免拆解；螢光粉應由熔煉業者於熔爐內一併處理；應於熔爐排氣口裝設洗滌塔處理廢氣並定期檢測申報；螢光粉處理時之逸散量應低於排放標準所定限值"],"a",
 "第5條第3款：處理具陰極射線管（CRT）之廢電子電器、廢資訊物品時，陰極射線管應先卸除真空，分離錐管玻璃與面板玻璃；螢光粉應妥善收集貯存於密閉容器內；螢光粉應於獨立密閉之運作空間內收集；應於抽氣櫃（Hood）內收集、吸除螢光粉，並於排氣口裝設集塵處理裝置；螢光粉吸除時不得逸散或洩漏於環境。",
 "What must be done when treating items containing a cathode-ray tube?",
 ["The tube must first be de-vacuumed and the funnel and panel glass separated; phosphor must be collected and stored in sealed containers and collected inside a separate enclosed space; it must be drawn off inside a hood with dust collection at the exhaust; and no phosphor may escape",
  "The tube must first be heated to soften it and crushed whole before screening the glass; phosphor may be stored in open containers and collected in the ordinary work area; it may be washed off outdoors with a screen at the drain; and heavy loss outside the plant must be avoided",
  "The tube must first be soaked in acid to dissolve the phosphor coating; the phosphor may be neutralized into the wastewater system without separate storage; residual dust may be vacuumed in a normally ventilated area with a filter at the outlet; and masks must be worn",
  "The tube may be sent whole to a smelter without dismantling; the smelter treats the phosphor in the furnace together with it; a scrubber must be fitted at the furnace exhaust and tested periodically; and phosphor escape must stay below the emission standard"],
 "Article 5, subparagraph 3."),

(EE,"第5條",3,"廢電器-冷媒與電冰箱",
 "處理含冷媒或潤滑油之廢電子電器，及處理廢電冰箱時，應符合哪些規定？",
 ["應先抽取壓縮機之冷媒及潤滑油，將冷凍系統壓力降至一百零二毫米汞柱以下並取出壓縮機後始得進行後續作業；處理廢電冰箱並應於密閉負壓力設施中破碎箱體，處理碳氫化合物發泡隔熱材應採必要防爆措施，並具備冷媒液化系統或吸附設備回收發泡隔熱材中之冷媒",
  "應先抽取壓縮機之冷媒及潤滑油，將冷凍系統壓力降至五百毫米汞柱以下並取出壓縮機後始得進行後續作業；處理廢電冰箱並應於常壓通風設施中破碎箱體，處理碳氫化合物發泡隔熱材得免防爆措施，並具備冷媒燃燒銷毀設備處理發泡隔熱材中之冷媒",
  "得於未抽取冷媒之情況下直接破碎並於後端集氣處理，冷凍系統壓力降至一大氣壓即可取出壓縮機；處理廢電冰箱並應於露天場地破碎箱體以利散熱，處理碳氫化合物發泡隔熱材應設置滅火器材，並具備冷媒排放稀釋設備以降低環境濃度",
  "應先抽取壓縮機之潤滑油而冷媒得逕行排放至大氣，冷凍系統壓力降至一百零二毫米汞柱以上即得取出壓縮機；處理廢電冰箱並應於正壓潔淨室中破碎箱體，處理發泡隔熱材應採防塵措施，並具備冷媒回收鋼瓶交由業者自行處置"],"a",
 "第5條第4款：處理含冷媒或潤滑油之廢電子電器時，應先抽取壓縮機之冷媒及潤滑油，將其冷凍系統之壓力降至102毫米汞柱以下，取出壓縮機後始可進行後續處理作業。第5款：處理廢電冰箱並應於密閉負壓力設施中破碎箱體；處理碳氫化合物（HCs）之發泡隔熱材應採取必要之防爆措施；粉碎分類處理應具備可分離鐵金屬、非鐵金屬、其他非金屬及泡棉之選別設備；並應具備冷媒液化系統或吸附設備回收發泡隔熱材中之冷媒；處理設施應具備隔音設備及粉塵收集系統。",
 "What applies when treating items containing refrigerant or lubricant, and waste refrigerators?",
 ["The compressor's refrigerant and lubricant must first be drawn off, the system pressure lowered below one hundred and two millimetres of mercury and the compressor removed; refrigerator casings must be crushed in a sealed negative-pressure facility, hydrocarbon foam insulation needs explosion protection, and refrigerant in the foam must be recovered by liquefaction or adsorption",
  "The compressor's refrigerant and lubricant must first be drawn off, the system pressure lowered below five hundred millimetres of mercury and the compressor removed; refrigerator casings may be crushed in a ventilated ambient-pressure facility, hydrocarbon foam needs no explosion protection, and refrigerant in the foam insulation may be destroyed by combustion on site instead",
  "Crushing may proceed without drawing off refrigerant provided gas is captured downstream, and the compressor may be removed once pressure falls to one atmosphere; refrigerator casings may be crushed outdoors for cooling, hydrocarbon foam needs fire extinguishers, and refrigerant may be diluted on release",
  "Only the lubricant need be drawn off while refrigerant may be vented, and the compressor may be removed once pressure exceeds one hundred and two millimetres of mercury; refrigerator casings must be crushed in a positive-pressure clean room, foam needs dust control, and cylinders may be left to the operator"],
 "Article 5, subparagraphs 4 and 5."),

(EE,"第5條",3,"廢電器-液晶顯示器處理",
 "處理具液晶顯示器（LCD）之廢電子電器、廢資訊物品時，應符合哪些規定？",
 ["具冷陰極燈管之液晶顯示器應整機置於抽氣櫃內處理，其抽氣櫃排氣口須裝設汞蒸氣吸附裝置；操作時工作人員須佩戴具防護功能之防護手套；並應設置專區妥善貯存取出後之冷陰極燈管",
  "具冷陰極燈管之液晶顯示器得於一般作業區拆解處理，其作業區應裝設一般排風扇通風；操作時工作人員須佩戴口罩及安全帽；並得將取出後之冷陰極燈管併入混合五金廢料收集",
  "具冷陰極燈管之液晶顯示器應先浸水冷卻後再行破碎，其破碎設備排氣口須裝設袋式集塵器；操作時工作人員須佩戴防塵眼鏡；並應將取出後之冷陰極燈管直接送交熔煉業者處理",
  "具冷陰極燈管之液晶顯示器應整機送交國外處理機構處理，其國內作業區僅得辦理包裝作業；操作時工作人員須佩戴防護面罩；並應設置冷藏專區貯存取出後之液晶面板玻璃"],"a",
 "第5條第6款：處理具液晶顯示器（LCD）之廢電子電器、廢資訊物品時，具冷陰極燈管（CCFL）之液晶顯示器應整機置於抽氣櫃（Hood）內處理，其抽氣櫃排氣口須裝設汞蒸氣吸附裝置；操作時工作人員須佩戴具有防護功能之防護手套；應設置專區妥善貯存取出後之冷陰極燈管。",
 "What must be done when treating items containing a liquid crystal display?",
 ["Displays with cold cathode fluorescent lamps must be handled whole inside a hood whose exhaust carries a mercury vapour adsorption device; workers must wear protective gloves; and a dedicated area must store the lamps once removed",
  "Displays with cold cathode fluorescent lamps may be dismantled in the ordinary work area with a general extraction fan for ventilation; workers must wear masks and helmets; and the lamps removed may be put with mixed scrap metal",
  "Displays with cold cathode fluorescent lamps must be water-cooled before crushing, with a baghouse at the crusher exhaust; workers must wear dust goggles; and the lamps removed must go straight to a smelter",
  "Displays with cold cathode fluorescent lamps must be sent whole to an overseas facility, only packing being done here; workers must wear face shields; and a refrigerated area must store the panel glass removed"],
 "Article 5, subparagraph 6."),

(EE,"第5條",3,"廢電器-機械處理系統試驗",
 "以機械處理系統處理具含汞零組件之廢電子電器、廢資訊物品者，其試驗程序及要求為何？",
 ["應檢具試驗計畫報經所在地直轄市、縣（市）主管機關同意後進行試驗，試驗期間以三個月為限，必要時得申請延長且展延期限不得超過三個月；試驗核准者處理後衍生物之毒性特性溶出程序試驗汞溶出量應低於每公升零點零二五毫克",
  "應檢具試驗計畫報經中央主管機關核准後進行試驗，試驗期間以六個月為限，必要時得申請延長且展延期限不得超過六個月；試驗核准者處理後衍生物之毒性特性溶出程序試驗汞溶出量應低於每公升零點二五毫克",
  "得逕行進行試驗並於試驗後三十日內報請所在地主管機關備查，試驗期間以一年為限且不得申請延長；試驗完成者處理後衍生物之毒性特性溶出程序試驗汞溶出量應低於每公升零點五毫克",
  "應檢具試驗計畫報經目的事業主管機關同意後進行試驗，試驗期間以三個月為限且不得申請延長；試驗核准者處理後衍生物之毒性特性溶出程序試驗汞溶出量應低於每公升一點零毫克"],"a",
 "第5條第7款：以機械處理系統處理具含汞零組件者，應檢具試驗計畫報經所在地直轄市、縣（市）主管機關同意後進行試驗，試驗期間以3個月為限，必要時得申請延長，展延期限不得超過3個月；試驗結果經核准者不受第2款及第6款限制，但不得與其他各項物品混合處理，處理後衍生物之毒性特性溶出程序試驗結果汞溶出量應低於每公升0.025毫克，汞蒸氣產生區域應採密閉系統並維持負壓操作，並應具汞濃度偵測裝置及氣體流量計連續監測。",
 "What trial procedure applies to treating mercury-bearing components with a mechanical treatment system?",
 ["A trial plan must be agreed by the local competent authority before the trial, which is limited to three months and extendable once by no more than three months; if approved, the mercury leachate of residues must be under 0.025 milligrams per litre",
  "A trial plan must be approved by the central competent authority before the trial, which is limited to six months and extendable once by no more than six months; if approved, the mercury leachate of residues must be under 0.25 milligrams per litre",
  "The trial may proceed at once and be filed with the local authority within thirty days, being limited to one year with no extension available; on completion, the mercury leachate of residues must be under 0.5 milligrams per litre",
  "A trial plan must be agreed by the industry competent authority before the trial, which is limited to three months with no extension available; if approved, the mercury leachate of residues must be under 1.0 milligrams per litre"],
 "Article 5, subparagraph 7."),

(EE,"第6條",1,"廢電器-境內處理",
 "廢電子電器、廢資訊物品之處理地點及方式有何限制？",
 ["應於境內處理，且不得直接以焚化或掩埋方式處理，以確保其資源回收再利用之目的",
  "得經中央主管機關核准後輸出至國外處理，境內處理者則不得以焚化方式減量處置",
  "應於境內處理，惟經地方主管機關同意後得將無再利用價值部分直接以掩埋方式處理",
  "得由處理業者依處理成本選擇境內或境外處理，並得以焚化方式進行熱值之能源利用"],"a",
 "第6條：廢電子電器、廢資訊物品應於境內處理，且不得直接以焚化或掩埋方式處理。第5條第8款並要求廢資訊物品之印刷電路板應破碎或依其他經中央主管機關同意之方法處理，均在確保資源回收再利用之目的。",
 "What limits apply to where and how waste electronics and IT products are treated?",
 ["They must be treated domestically and may not be directly incinerated or landfilled, so that resource recovery is achieved",
  "They may be exported for treatment with central approval, while domestic treatment may not use incineration to reduce volume",
  "They must be treated domestically, but parts with no reuse value may be landfilled directly once the local authority consents",
  "Operators may choose domestic or overseas treatment on cost grounds, and may incinerate them to recover their heat value"],
 "Article 6."),

(EE,"第7條",2,"廢電器-氣液態再生料",
 "廢電子電器、廢資訊物品處理後產出之再生料及其他廢棄物屬氣態或液態物質者，應如何貯存？",
 ["應貯存於設有壓力或液位高度顯示設施之密閉容器內，並避免其溢出、洩漏或逸散於環境中",
  "應貯存於設有通風孔及洩壓閥之敞口容器內，並置於室外陰涼處以避免容器內壓力升高",
  "應貯存於具有攪拌功能之地下貯槽內，並每日檢查液位一次且將檢查結果作成紀錄備查",
  "應貯存於原廠回收之鋼瓶內並標示重量，且應於三十日內交由取得許可證之業者收受"],"a",
 "第7條：廢電子電器、廢資訊物品處理後所產出之再生料及其他廢棄物屬氣態或液態物質者，應貯存於設有壓力或液位高度顯示設施之密閉容器內，並避免其溢出、洩漏或逸散。第9條並就處理廢電子電器所回收之冷媒定有交付販賣或銷毀之規定。",
 "How must gaseous or liquid recycled materials and residues from treatment be stored?",
 ["In sealed containers fitted with pressure or liquid level indicators, avoiding any spillage, leakage or escape into the environment",
  "In open containers fitted with vents and pressure relief valves, kept outdoors in the shade so internal pressure cannot build up",
  "In underground tanks fitted with stirrers, with the level checked once a day and the results recorded for inspection",
  "In cylinders returned by the manufacturer and labelled with weight, to be handed within thirty days to a permitted operator"],
 "Article 7."),

(EE,"第8條",2,"廢電器-衍生廢棄物",
 "廢電子電器、廢資訊物品經回收、貯存、清除、處理後之廢棄物，應如何辦理？",
 ["應依本標準規定辦理，其屬事業廢棄物者除應依事業廢棄物貯存清除處理方法及設施標準規定貯存清除處理外，並應符合本法第二十八條規定之清理方式；其輸出應符合本法第三十八條規定",
  "應依本標準規定辦理，其屬事業廢棄物者得比照一般廢棄物由執行機關清運處理而免適用事業廢棄物相關標準；其輸出僅需檢附成分分析檢測報告向海關報備即得辦理",
  "應由原回收業者收回自行處置並留存流向紀錄，其屬有害事業廢棄物者始應依相關標準辦理；其輸出應經地方主管機關核准並副知中央主管機關備查後為之",
  "應全數交由中央主管機關指定之機構處理並繳納處理費，其屬事業廢棄物者免另依相關標準辦理；其輸出應依資源回收再利用法規定申請輸出許可後為之"],"a",
 "第8條第1項：廢電子電器、廢資訊物品經回收、貯存、清除、處理後之廢棄物，應依本標準規定辦理，其屬事業廢棄物者，除應依事業廢棄物貯存清除處理方法及設施標準規定貯存、清除、處理外，並應符合本法第28條規定之清理方式。第2項：前項廢棄物之輸出，應符合本法第38條規定。",
 "How must waste remaining after recovery, storage, clearance and treatment be handled?",
 ["Under these Standards; if industrial waste, also under the industrial waste storage, clearance and treatment standards and the disposal methods in Article 28; exports must comply with Article 38",
  "Under these Standards; if industrial waste, it may be cleared by the executing agency like general waste without the industrial waste standards; exports need only a composition report filed with customs",
  "The original recovery operator must take it back and handle it with flow records kept; only hazardous industrial waste follows the relevant standards; exports need local approval copied centrally",
  "All of it must go to a centrally designated institution with fees paid, industrial waste needing no other standards; exports need an export permit under the Resource Recycling Act"],
 "Article 8, paragraphs 1 and 2."),

(EE,"第9條",2,"廢電器-冷媒去向",
 "處理廢電子電器所回收之冷媒，應如何處置？",
 ["應交由取得主管機關核發之販賣許可證者販賣，或交付主管機關認可之機構銷毀",
  "應交由原製造廠商回收再充填使用，或由處理業者於廠內以焚化方式自行銷毀",
  "應交由取得許可之清除機構運送至掩埋場處置，或於廠內經稀釋後排放至大氣",
  "應交由目的事業主管機關指定之研究機構作為試驗用途，或於廠內自行貯存三年"],"a",
 "第9條：處理廢電子電器所回收之冷媒，應交由取得主管機關核發之販賣許可證者販賣，或交付主管機關認可之機構銷毀。第5條第4款、第5款並要求處理含冷媒之廢電子電器應先抽取冷媒，處理廢電冰箱並應具備冷媒液化系統或吸附設備回收發泡隔熱材中之冷媒。",
 "How must refrigerant recovered from waste electronics be disposed of?",
 ["It must be sold to a holder of a sales permit issued by the competent authority, or handed to an authority-recognized institution for destruction",
  "It must be returned to the original manufacturer for recharging and reuse, or destroyed by the treatment operator through in-plant incineration",
  "It must be hauled by a permitted clearance institution to a landfill, or diluted in the plant and then released to the atmosphere",
  "It must be given to a research institute designated by the industry authority for testing, or kept in the plant for three years"],
 "Article 9."),

(EE,"第10條",2,"廢電器-補貼比率",
 "依本法第十八條第五項向中央主管機關申請廢電子電器、廢資訊物品回收清除處理補貼者，應符合哪些規定？",
 ["廢電子電器、廢資訊物品經處理後其資源回收再利用比率應達百分之七十五；申請補貼者並應具備處理該類各項物品之方法及設施",
  "廢電子電器、廢資訊物品經處理後其資源回收再利用比率應達百分之五十；申請補貼者並得僅具備處理其中單一項目之方法及設施",
  "廢電子電器、廢資訊物品經處理後其資源回收再利用比率應達百分之九十；申請補貼者並應具備輸出至國外處理之許可文件及契約",
  "廢電子電器、廢資訊物品經處理後其資源回收再利用比率應達百分之六十五；申請補貼者並應具備甲級廢棄物處理機構許可證及技術員"],"a",
 "第10條第1款、第2款：廢電子電器、廢資訊物品經處理後，其資源回收再利用比率應達75%；申請廢電子電器、廢資訊物品之回收清除處理補貼者，應具備處理該類各項物品之方法及設施。資源回收再利用比率之定義見第2條第7款，指再生料重量占處理總量之重量百分比。",
 "What must an applicant satisfy to claim a recycling subsidy for waste electronics and IT products?",
 ["The resource recycling and reuse ratio after treatment must reach seventy-five percent, and the applicant must have the methods and facilities to treat every item in that category",
  "The resource recycling and reuse ratio after treatment must reach fifty percent, and the applicant need only have the methods and facilities for one single item in that category",
  "The resource recycling and reuse ratio after treatment must reach ninety percent, and the applicant must hold permits and contracts for exporting the items for treatment abroad",
  "The resource recycling and reuse ratio after treatment must reach sixty-five percent, and the applicant must hold a class A waste treatment permit and employ certified technicians"],
 "Article 10, subparagraphs 1 and 2."),

(EE,"第11條",1,"廢電器-刪除條文",
 "廢電子電器暨廢資訊物品回收貯存清除處理方法及設施標準第十一條之現行狀態為何？",
 ["該條業經刪除，現行條文僅保留條次而無任何規範內容，相關事項回歸其他各條規定",
  "該條規定處理業者應於本標準修正發布後六個月內完成改善及改善期間免罰之規定",
  "該條規定資源回收再利用比率之計算公式及再生料重量之認定方法與查核程序規定",
  "該條規定廢電子電器處理後含汞衍生物之溶出試驗方法及檢測頻率與申報格式規定"],"a",
 "第11條：（刪除）。條文刪除後條次仍予保留，以免影響其他條文之引用關係。本標準之補貼要件依第10條、冷媒去向依第9條、衍生廢棄物依第8條辦理，施行日期則依第12條規定自發布日施行。",
 "What is the current status of Article 11 of these Standards?",
 ["It has been deleted, the article number being kept without any substantive content, and related matters follow the other articles",
  "It gave operators six months from the amendment's promulgation to complete correction, with an exemption from penalties meanwhile",
  "It prescribed the formula for the recycling ratio and how recycled material weight is determined and verified",
  "It prescribed the leaching test method, testing frequency and reporting format for mercury-bearing residues"],
 "Article 11 is deleted."),

(EE,"第12條",1,"廢電器-施行日期",
 "廢電子電器暨廢資訊物品回收貯存清除處理方法及設施標準之施行日期如何規定？",
 ["自發布日施行，未另定分階段生效或既有業者改善期間之過渡適用規定",
  "自發布後六個月施行，並就既有處理業者另定一年之改善期間及免罰規定",
  "自發布後一年施行，其中含汞零組件處理規定自發布日起先行施行適用之",
  "由中央主管機關另以命令定其施行日期，並得就貯存與處理規定分別定之"],"a",
 "第12條：本標準自發布日施行。本標準修正日期為民國107年7月13日，全文共12條（第11條已刪除），依廢棄物清理法第18條第1項授權訂定，規範廢電子電器、廢資訊物品之回收貯存清除方法、處理廠設施、處理方法、境內處理限制、冷媒去向及補貼要件等事項。",
 "When do the Standards for Waste Electronics and IT Products take effect?",
 ["On the date of promulgation, with no phased effectiveness or transitional correction period for existing operators",
  "Six months after promulgation, with a one-year correction period and penalty exemption for existing operators",
  "One year after promulgation, except that the mercury component rules apply from the date of promulgation",
  "On a date set by the central authority by order, which may differ for the storage and treatment provisions"],
 "Article 12."),

(TR,"第1條",1,"廢輪胎-法源適用",
 "廢輪胎回收貯存清除處理方法及設施標準之法源依據及適用關係為何？",
 ["依廢棄物清理法第十八條第一項規定訂定；廢輪胎回收貯存清除處理方法及設施依本標準規定，本標準未規定者適用其他法令之規定",
  "依廢棄物清理法第十五條第二項規定訂定；廢輪胎回收貯存清除處理方法及設施應優先適用其他法令，本標準僅於無規定時補充適用",
  "依廢棄物清理法第三十九條第二項規定訂定；廢輪胎回收貯存清除處理方法及設施依本標準規定，其未規定者應報請中央主管機關核定",
  "依資源回收再利用法第九條規定訂定；廢輪胎回收貯存清除處理方法及設施依本標準規定，並得由處理業者依實際作業需要自行調整"],"a",
 "第1條第1項、第2項：本標準依廢棄物清理法第18條第1項規定訂定；廢輪胎回收貯存清除處理方法及設施依本標準之規定，本標準未規定者適用其他法令之規定。第2條第1款並將廢輪胎定義為依本法第15條第2項公告應回收之廢輪胎。",
 "What is the legal basis of the Standards for Waste Tyres and how do other laws apply?",
 ["Enacted under Article 18, paragraph 1 of the Waste Disposal Act; the methods and facilities follow these Standards, with other laws applying to uncovered matters",
  "Enacted under Article 15, paragraph 2 of the Waste Disposal Act; other laws apply first and these Standards supplement them only where nothing is provided",
  "Enacted under Article 39, paragraph 2 of the Waste Disposal Act; the methods follow these Standards, and uncovered matters must be submitted for central approval",
  "Enacted under Article 9 of the Resource Recycling Act; the methods follow these Standards, and treatment operators may adjust them as operations require"],
 "Article 1, paragraphs 1 and 2."),

(TR,"第2條",3,"廢輪胎-處理方式定義",
 "本標準所稱破碎處理、裂解處理、能源利用及原形利用，其定義為何？",
 ["破碎處理指利用冷凍、機械力、化學溶劑或其他方式使廢輪胎成為碎片或粉粒；裂解處理指在無氧或少氧環境下利用熱能使其分解成油、碳黑及其他氣體殘渣；能源利用指以廢輪胎或其碎片作為產生能源之原料；原形利用指未經處理改變原形態而直接使用之行為",
  "破碎處理指以高溫熔融方式使廢輪胎成為膠塊或膠球；裂解處理指在富氧環境下利用燃燒使其轉變成安定氣體；能源利用指將廢輪胎作為道路級配粒料使用；原形利用指經翻修再生後作為輪胎繼續使用之行為，並得作為新品輪胎對外銷售使用",
  "破碎處理指以人工切割方式使廢輪胎分離成鋼絲與橡膠；裂解處理指以化學藥劑浸泡使其橡膠分子鏈斷裂；能源利用指將廢輪胎碎片掩埋後回收沼氣使用；原形利用指作為消波塊或擋土設施之填充材料使用",
  "破碎處理指以研磨方式使廢輪胎成為橡膠粉並篩分粒徑；裂解處理指在密閉高壓環境下以蒸氣分解其成分；能源利用指以廢輪胎作為水泥窯之替代原料；原形利用指經檢驗合格後外銷至其他國家繼續使用"],"a",
 "第2條第6款至第9款：破碎處理指利用冷凍、機械力、化學溶劑或其他方式使廢輪胎成為碎片或粉粒之處理方式；裂解處理指在無氧或少氧環境下利用熱能使廢輪胎或其碎片分解成油、碳黑及其他氣體、殘渣等之處理方式；能源利用指以廢輪胎或廢輪胎碎片作為產生能源之原料；原形利用指廢輪胎未經處理改變原形態，將其直接使用之行為。第4條並規定原形利用者應符合第3條規定。",
 "How do these Standards define crushing, pyrolysis, energy use and whole-tyre use?",
 ["Crushing turns tyres into chips or granules by freezing, mechanical force, chemical solvents or other means; pyrolysis uses heat with no or little oxygen to break them into oil, carbon black, gas and residue; energy use takes tyres or chips as an energy feedstock; whole-tyre use employs them directly unchanged",
  "Crushing melts tyres at high temperature into rubber blocks or balls; pyrolysis burns them in oxygen-rich conditions into stable gases; energy use employs tyres as road aggregate; whole-tyre use means retreading them for further service as tyres",
  "Crushing separates the steel wire from the rubber by hand cutting; pyrolysis soaks them in chemical agents to break the polymer chains; energy use landfills the chips and recovers the biogas produced for energy; whole-tyre use employs them as fill material in breakwaters, retaining works or coastal defences",
  "Crushing grinds tyres into rubber powder screened by grain size; pyrolysis decomposes them with steam under sealed high pressure; energy use takes tyres as a cement kiln raw material substitute; whole-tyre use exports them abroad after inspection"],
 "Article 2, subparagraphs 6 to 9."),

(TR,"第3條",3,"廢輪胎-堆置高度",
 "廢輪胎堆置貯存之高度、分區尺寸及嚴禁煙火範圍規定為何？",
 ["堆置貯存高度不得超過四公尺，採固定分隔設施貯存者不得超過六公尺；分區貯存寬度及長度不得超過二十公尺，各區域間應有明顯標線且有二公尺以上分隔走道或固定分隔設施；貯存區周圍六公尺範圍內應嚴禁煙火且不可存放易燃性物質",
  "堆置貯存高度不得超過六公尺，採固定分隔設施貯存者不得超過八公尺；分區貯存寬度及長度不得超過三十公尺，各區域間應有明顯標線且有一公尺以上分隔走道或固定分隔設施；貯存區周圍三公尺範圍內應嚴禁煙火且不可存放易燃性物質",
  "堆置貯存高度不得超過三公尺，採固定分隔設施貯存者不得超過四公尺；分區貯存寬度及長度不得超過十公尺，各區域間應有明顯標線且有三公尺以上分隔走道或固定分隔設施；貯存區周圍十公尺範圍內應嚴禁煙火且不可存放易燃性物質",
  "堆置貯存高度不得超過四公尺，採固定分隔設施貯存者不受高度限制；分區貯存寬度及長度不得超過五十公尺，各區域間應有明顯標線且有零點五公尺以上分隔走道；貯存區周圍一公尺範圍內應嚴禁煙火且不可存放易燃性物質"],"a",
 "第3條第6款：廢輪胎堆置貯存高度不得超過4公尺；採固定分隔設施貯存廢輪胎者，堆置高度不得超過6公尺。分區貯存寬度及長度不得超過20公尺，各區域間應有明顯標線，且有2公尺以上之分隔走道或固定分隔設施，並應採繩索捆綁、護網、擋樁、堵牆等措施防止飛散掉落倒塌或崩塌。第7款：貯存區周圍6公尺範圍內應嚴禁煙火，且不可存放任何易燃性物質，並應設置嚴禁煙火標示。",
 "What stacking height, zoning dimensions and no-fire radius apply to waste tyre storage?",
 ["Stacks may not exceed four metres, or six metres where fixed dividers are used; zones may not exceed twenty metres wide or long, with clear marking lines and aisles of at least two metres or fixed dividers; fire and flammables are barred within six metres of the storage area",
  "Stacks may not exceed six metres, or eight metres where fixed dividers are used; zones may not exceed thirty metres wide or long, with clear marking lines and aisles of at least one metre or fixed dividers; fire and flammables are barred within three metres of the storage area",
  "Stacks may not exceed three metres, or four metres where fixed dividers are used; zones may not exceed ten metres wide or long, with clear marking lines and aisles of at least three metres or fixed dividers; fire and flammables are barred within ten metres of the storage area",
  "Stacks may not exceed four metres, with no height limit where fixed dividers are used; zones may not exceed fifty metres wide or long, with clear marking lines and aisles of at least half a metre; fire and flammables are barred within one metre of the storage area"],
 "Article 3, subparagraphs 6 and 7."),

(TR,"第3條",2,"廢輪胎-貯存設施要求",
 "廢輪胎之回收、貯存、清除方法及設施，除高度與走道規定外，另有哪些要求？",
 ["運送車輛機具應設防雨措施並設置緊急滅火設備，貯存廠區應設消防安全設備及避雷或接地設備並定期檢修；應貯存於具排水及污染物截流設施之不透水地面；四周應設圍籬並分區標示；並應有遮雨設施及防止蚊蠅病媒孳生之措施且適時噴藥作成紀錄",
  "運送車輛機具應設防塵網並設置衛星定位設備，貯存廠區應設地磅及攝影監視設備並每季校正；應貯存於具透水性之碎石地面以利排水；四周應設綠帶緩衝區並標示廠名；並應有遮陽設施及防止紫外線劣化之措施且每月翻堆一次作成紀錄",
  "運送車輛機具應設密閉貨櫃並全程錄影，貯存廠區應設門禁刷卡及警衛駐守並每日巡查；應貯存於具通風功能之高架棧板上；四周應設隔音牆並標示噪音管制值；並應有恆溫設施及防止自燃之措施且每週灑水降溫作成紀錄",
  "運送車輛機具應設防雨措施並由技術員押運，貯存廠區應設緊急沖淋及洗眼設備並定期檢修；應貯存於具傾斜度之混凝土地面；四周應設圍牆並設置監測井；並應有覆土設施及防止臭味逸散之措施且每日除臭作成紀錄"],"a",
 "第3條第1款至第5款、第9款：運送時車輛機具應設置防雨措施並避免溢出洩漏飛散掉落；運送車輛機具應設置緊急滅火設備，貯存廠（場）區應設置消防安全設備及避雷設備或接地設備並定期檢修；貯存地點容器設施應經常保持清潔完整；應貯存於具排水及污染物截流設施之不透水地面；貯存廠（場）區四周應設置圍籬及貯存區並依特性或數量分區貯存標示種類名稱；廢輪胎貯存應有遮雨設施並具備防止蚊蠅或其他病媒孳生之設備或措施，且應適時噴灑環境衛生用藥作成紀錄備查。",
 "Besides height and aisle rules, what else do the recovery, storage and clearance requirements cover?",
 ["Vehicles need rain protection and emergency fire extinguishers, and the yard needs fire safety and lightning or earthing equipment regularly inspected; storage on an impervious floor with drainage and interception; fencing with zone labelling; and rain covers plus vector control with pesticide spraying recorded",
  "Vehicles need dust netting and satellite positioning, and the yard needs a weighbridge and video surveillance calibrated quarterly; storage on permeable gravel to aid drainage; a green buffer belt with the plant name; and shading against ultraviolet degradation with monthly turning of the stacks recorded",
  "Vehicles need sealed containers and full video recording, and the yard needs card access and guards with daily patrols; storage on ventilated raised pallets; sound walls with noise limits posted; and temperature control against self-ignition with weekly watering recorded",
  "Vehicles need rain protection and a technician escort, and the yard needs emergency showers and eyewash regularly inspected; storage on a sloped concrete floor; walls with monitoring wells; and soil cover against odour with daily deodorizing recorded"],
 "Article 3, subparagraphs 1 to 5 and 9."),

(TR,"第4條",1,"廢輪胎-原形利用",
 "廢輪胎以原形利用者，應符合何種規定？",
 ["應符合本標準第三條有關回收、貯存、清除方法及設施之各項規定，不因未經處理而免除",
  "應符合本標準第五條有關處理方法及設施之各項規定，並應設置破碎及磨粉設備供備用",
  "免適用本標準各項規定，惟應於使用前報請所在地直轄市、縣（市）主管機關同意備查",
  "應符合本標準第六條有關補貼申請之各項規定，並應提具質量平衡圖及試運轉報告文件"],"a",
 "第4條：廢輪胎以原形利用者，應符合本標準第3條規定。第2條第9款並定義原形利用指廢輪胎未經處理改變原形態，將其直接使用之行為。故原形利用雖不涉及第5條之處理設施要求，其回收、貯存、清除仍應符合第3條之各項規定。",
 "What must be complied with where waste tyres are used in their original form?",
 ["The recovery, storage and clearance methods and facilities in Article 3 must all be met, and are not waived merely because no treatment occurs",
  "The treatment methods and facilities in Article 5 must all be met, and crushing and grinding equipment must be kept available as backup",
  "None of these Standards apply, though prior consent must be filed with the local competent authority before the tyres are used",
  "The subsidy application rules in Article 6 must all be met, including filing a mass balance diagram and a trial run report"],
 "Article 4."),

(TR,"第5條",3,"廢輪胎-破碎處理設施",
 "採破碎處理方式處理廢輪胎者，其設施及作業應符合哪些規定？",
 ["應具備破碎、磨粉設備或其他切割成型設備，並於易產生高溫之處理設備設置溫度感應警示設備或降溫設備；於粉塵發生源設置集塵設備並每月定期清理及記錄；每日應以清理並收集粉塵之方法清掃廠區使不發生粉塵飛揚",
  "應具備破碎、磨粉設備或其他切割成型設備，並於易產生高溫之處理設備設置自動滅火設備；於粉塵發生源設置洗滌塔並每季定期清理及記錄；每週應以灑水方式清掃廠區使不發生粉塵飛揚之情事",
  "應具備冷凍破碎設備及液態氮貯槽，並於易產生低溫之處理設備設置保溫層；於粉塵發生源設置靜電集塵設備並每年定期清理；每月應以真空吸塵方式清掃廠區並將紀錄公告於網站供查閱",
  "應具備人工切割工具及輸送帶設備，並於作業區設置溫度計供人員隨時查看；於粉塵發生源設置抽風扇並於停工時清理；每日應以壓縮空氣吹除方式清潔設備並將粉塵排放至戶外空曠處"],"a",
 "第5條第4款：採破碎處理者，應具備廢輪胎破碎、磨粉設備或其他切割成型設備，並於易產生高溫之處理設備設置溫度感應警示設備或降溫設備；於處理設備粉塵發生源設置集塵設備收集粉塵，並應每月定期清理及記錄，確保集塵系統維持有效運作；每日應以清理並收集粉塵之方法清掃廠區作業環境，使作業廠區不發生粉塵飛揚。",
 "What must crushing treatment of waste tyres provide?",
 ["Crushing, grinding or other cutting and forming equipment, with temperature alarms or cooling equipment on heat-prone units; dust collectors at dust sources cleaned and recorded monthly; and daily cleaning by collecting dust so no dust becomes airborne in the plant",
  "Crushing, grinding or other cutting and forming equipment, with automatic fire suppression systems on heat-prone units; scrubbers at dust sources cleaned and recorded quarterly; and weekly cleaning by watering so that no dust becomes airborne in the plant",
  "Cryogenic crushing equipment and a liquid nitrogen tank, with insulation on cold-prone units; electrostatic precipitators at dust sources cleaned annually; and monthly vacuum cleaning with the records posted online for inspection",
  "Hand cutting tools and conveyor equipment, with thermometers in the work area for staff to check; extraction fans at dust sources cleaned during shutdowns; and daily blow-down with compressed air venting the dust outdoors"],
 "Article 5, subparagraph 4."),

(TR,"第5條",3,"廢輪胎-裂解與能源利用",
 "採裂解處理或能源利用方式處理廢輪胎者，其設施應符合哪些規定？處理作業場所有何要求？",
 ["採裂解處理者應設置油類或液體之截流、收集、油水分離及相關處理設施與集塵設備，並具備煉製油品設備及防止油品洩漏措施；採能源利用者應設置集塵設備並具備窯爐、產生蒸氣設備、煉鋼設備或汽電共生設備；處理作業須在四周有圍牆之廠區內進行且需為混凝土鋪面",
  "採裂解處理者應設置冷凝回收塔及廢氣燃燒塔，並具備油品貯槽及防溢堤設施；採能源利用者應設置除硫設備並具備鍋爐、發電機組或熱媒油加熱設備；處理作業得在四周開放之棚架內進行且得為瀝青鋪面以利機具移動，並應設置消防安全及避雷設備",
  "採裂解處理者應設置真空幫浦及氮氣充填設備，並具備碳黑造粒設備及包裝機；採能源利用者應設置連續自動監測設備並具備焚化爐或熔融爐設備；處理作業須在密閉負壓之地下室內進行且需為環氧樹脂鋪面",
  "採裂解處理者應設置活性碳吸附塔及排放口採樣孔，並具備廢水回收全量再利用設施；採能源利用者應設置飛灰穩定化設備並具備掩埋場或灰渣暫存區；處理作業得在露天場區進行但應設置防風網及碎石鋪面"],"a",
 "第5條第1款至第3款、第5款、第6款：處理作業須在四周有圍牆之廠（場）區內進行；處理作業區應具有排水及污染物截流設施；處理作業區需為混凝土鋪面以防止污水油類滲入地下污染土壤或地下水體；採裂解處理者應設置油類或液體之截流、收集、油水分離及相關處理設施及集塵設備收集粉塵，並具備廢輪胎煉製油品之設備及防止油品洩漏措施；採能源利用者應設置集塵設備收集粉塵，並應具備窯爐、產生蒸氣設備、煉鋼設備或汽電共生設備。",
 "What must pyrolysis or energy-use treatment of waste tyres provide, and what does the work area require?",
 ["Pyrolysis needs oil or liquid interception, collection, oil-water separation and related facilities plus dust collectors, oil refining equipment and leak prevention; energy use needs dust collectors plus a kiln, steam generation, steelmaking or cogeneration equipment; and work must occur in a walled plant on concrete paving",
  "Pyrolysis needs condensation recovery towers and a flare stack plus oil storage tanks and bunding walls; energy use needs desulphurization equipment plus boilers, generator sets or thermal oil heaters; and work may occur under a roofed open-sided shed on asphalt paving that eases machinery movement around the plant area",
  "Pyrolysis needs vacuum pumps and nitrogen filling plus carbon black pelletizing and packing machines; energy use needs continuous automatic monitoring plus an incinerator or melting furnace; and work must occur in a sealed negative-pressure basement on epoxy paving",
  "Pyrolysis needs activated carbon towers and stack sampling ports plus full wastewater recovery and reuse; energy use needs fly ash stabilization plus a landfill or ash storage area; and work may occur outdoors behind windbreak netting on gravel paving"],
 "Article 5, subparagraphs 1 to 3, 5 and 6."),

(TR,"第6條",3,"廢輪胎-補貼要件",
 "依本法第十八條第五項向中央主管機關申請廢輪胎回收清除處理補貼者，應符合哪些規定？",
 ["應符合破碎處理、裂解處理或能源利用之處理方式，並作為橡膠製品、橡膠製品原料、橡膠瀝青原料、油品煉製原料或水泥窯、造紙業、煉鋼業、汽電共生廠等生產能源原料之用途；應具備處理公告應回收各種規格尺寸廢輪胎之能力；並提具質量平衡圖及試運轉報告",
  "應符合原形利用、掩埋處理或翻修再生之處理方式，並作為消波塊、擋土設施、道路級配粒料、景觀造景材料或填地工程材料等用途；應具備處理特定單一規格尺寸廢輪胎之處理能力即可；並提具處理量統計表、委託人名冊及每月營運報表送請備查",
  "應符合輸出國外處理之方式，並取得接受國政府同意輸入之文件及處理機構許可文件；應具備輸出至經濟合作暨發展組織會員國之能力；並提具運輸契約及財務保證文件與退運計畫",
  "應符合翻修再生之處理方式，並取得經濟部標準檢驗局核發之商品驗證登錄證書；應具備翻修各種規格尺寸廢輪胎之能力；並提具品質管制計畫及產品保固說明書與銷售通路資料"],"a",
 "第6條第1款至第3款：申請補貼者應符合第2條第6款至第8款規定廢輪胎之處理方式（破碎處理、裂解處理、能源利用），並作為橡膠製品、橡膠製品原料、橡膠瀝青原料、油品煉製原料或水泥窯、造紙業、煉鋼業、汽電共生廠等生產能源原料之用途；應具備處理依本法第15條第2項公告應回收各種規格尺寸廢輪胎之能力；並提具清除、處理之方法、設備、流程、質量平衡圖及處理設備之試運轉報告。",
 "What must an applicant satisfy to claim a recycling subsidy for waste tyres?",
 ["Use crushing, pyrolysis or energy recovery and direct the output to rubber products, rubber or rubberized asphalt feedstock, oil refining feedstock, or energy feedstock for cement kilns, paper mills, steelworks or cogeneration plants; be able to treat every announced tyre size; and file a mass balance diagram and trial run report",
  "Use whole-tyre application, landfill or retreading and direct the output to breakwaters, retaining works, road aggregate, landscaping materials or land reclamation fill; be able to treat one particular tyre size only; and file throughput statistics, a client roster and monthly operating returns to the central competent authority for the record",
  "Use export for treatment abroad and obtain the receiving state's import consent and the facility's permit documents; be able to export to an OECD member country; and file the carriage contract, financial guarantee and return plan",
  "Use retreading and obtain a commodity verification registration certificate from the Bureau of Standards; be able to retread every tyre size; and file a quality control plan, warranty statement and distribution channel data"],
 "Article 6, subparagraphs 1 to 3."),

(TR,"第7條",2,"廢輪胎-衍生廢棄物",
 "廢輪胎經回收、貯存、清除、處理後產生之廢棄物，應如何辦理？",
 ["應依本標準規定辦理，其屬事業廢棄物者除應依事業廢棄物貯存清除處理方法及設施標準規定貯存清除處理外，並應符合本法第二十八條規定之清理方式；其輸出應符合本法第三十八條規定",
  "應依本標準規定辦理，其屬事業廢棄物者得比照一般廢棄物由執行機關清運處理而免依事業廢棄物相關標準辦理；其輸出僅需檢附成分分析報告向海關報備即得辦理",
  "應由原回收業者收回自行處置並留存流向紀錄備查，其屬有害事業廢棄物者始應依相關標準辦理；其輸出應經地方主管機關核准並副知中央主管機關後為之",
  "應全數作為能源利用原料交由水泥窯或汽電共生廠使用，其屬事業廢棄物者免另依相關標準辦理；其輸出應依資源回收再利用法規定申請輸出許可後為之"],"a",
 "第7條第1項：廢輪胎經回收、貯存、清除、處理後產生之廢棄物，應依本標準規定辦理，其屬事業廢棄物者，除應依事業廢棄物貯存清除處理方法及設施標準規定貯存、清除、處理外，並應符合本法第28條規定之清理方式。第2項：前項廢棄物之輸出，應符合本法第38條規定。",
 "How must waste produced after the recovery, storage, clearance and treatment of tyres be handled?",
 ["Under these Standards; if industrial waste, also under the industrial waste storage, clearance and treatment standards and the disposal methods in Article 28; exports must comply with Article 38",
  "Under these Standards; if industrial waste, it may be cleared by the executing agency like general waste without the industrial waste standards; exports need only a composition report filed with customs",
  "The original recovery operator must take it back and handle it with flow records kept; only hazardous industrial waste follows the relevant standards; exports need local approval copied centrally",
  "All of it must go to cement kilns or cogeneration plants as energy feedstock, industrial waste needing no other standards; exports need an export permit under the Resource Recycling Act"],
 "Article 7, paragraphs 1 and 2."),

(TR,"第8條",2,"廢輪胎-改善期限",
 "本標準修正施行前已從事回收、處理之回收、處理業，對於修正條文之規定應如何因應？",
 ["應自本標準修正施行之日起六個月內完成改善，以符合修正後之回收貯存清除處理規定",
  "應自本標準修正施行之日起三個月內完成改善，逾期未改善者應即停止其回收處理業務",
  "應自本標準修正施行之日起二年內完成改善，並得檢具理由申請展延一年且期間免罰",
  "應自本標準修正發布之日起立即符合規定，僅設備改建部分得申請三個月之緩衝期間"],"a",
 "第8條：本標準修正施行前，已從事回收、處理之回收、處理業，對於本標準修正條文之規定，應自本標準修正施行之日起6個月內完成改善。廢容器回收貯存清除處理方法及設施標準第12條及廢鉛蓄電池回收貯存清除處理方法及設施標準第7條亦定有相同之6個月改善期規定。",
 "How must recovery and treatment operators already in business respond to the amended provisions?",
 ["They must complete correction within six months from the day the amendment takes effect, so as to meet the amended recovery, storage, clearance and treatment rules",
  "They must complete correction within three months from the day the amendment takes effect, and must cease recovery and treatment business if they fail to do so",
  "They must complete correction within two years from the day the amendment takes effect, with a one-year extension available on stated grounds and no penalties meanwhile",
  "They must comply from the day the amendment is promulgated, with only a three-month buffer available for the part involving equipment rebuilding work"],
 "Article 8."),

(TR,"第8條、第9條",1,"廢輪胎-施行日期",
 "廢輪胎回收貯存清除處理方法及設施標準之施行日期如何規定？",
 ["自發布日施行，另於第八條就修正施行前已從事回收處理之業者定有六個月改善期",
  "自發布後六個月施行，並自施行日起同時廢止原有之廢輪胎回收清除處理相關規定",
  "自發布後一年施行，其中原形利用及補貼要件規定自發布日起先行施行並適用之",
  "由中央主管機關另以命令定其施行日期，並得就貯存與處理規定分別定其施行日"],"a",
 "第9條：本標準自發布日施行。本標準修正日期為民國103年5月20日，全文共9條，依廢棄物清理法第18條第1項授權訂定，並於第8條就修正施行前已從事回收、處理之業者定有自修正施行之日起6個月之改善期間。",
 "When do the Standards for Waste Tyres take effect?",
 ["On the date of promulgation, with Article 8 giving existing recovery and treatment operators a six-month correction period",
  "Six months after promulgation, at which point the earlier waste tyre recovery and treatment rules are all repealed",
  "One year after promulgation, except that the whole-tyre use and subsidy rules apply from the promulgation date",
  "On a date set by the central authority by order, which may differ for the storage and treatment provisions"],
 "Article 9."),
]
