# -*- coding: utf-8 -*-
# 第 12 批（D1）：煉鋼業電弧爐戴奧辛管制及排放標準、違反空氣污染防制法按次處罰通知限期改善補正或申報執行準則、
#                違反室內空氣品質管理法罰鍰額度裁罰準則、鉛二次冶煉廠空氣污染物排放標準
A = "ENV-135"
B = "ENV-136"
C = "ENV-137"
D = "ENV-139"
Q = [

# ===== ENV-135 煉鋼業電弧爐戴奧辛管制及排放標準（9 條）=====
(A,"第1條",1,"電弧爐戴奧辛-授權依據",
 "煉鋼業電弧爐戴奧辛管制及排放標準係依據哪些法律條文訂定？",
 ["空氣污染防制法第二十條第二項、第二十二條第二項、第三項及第二十三條第二項","空氣污染防制法第二十條第一項、第二十一條第二項及第二十四條第三項規定","空氣污染防制法第十八條第五項、第二十二條第一項及第三十一條第二項規定","廢棄物清理法第二十條第二項及空氣污染防制法第二十三條第一項規定訂定"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項、第二十二條第二項、第三項及第二十三條第二項規定訂定之。第3條並定明適用於煉鋼業電弧爐，第9條定自發布日施行。",
 "Which statutory provisions authorize this dioxin standard for electric arc furnaces?",
 ["Articles 20-2, 22-2, 22-3 and 23-2 of the Air Pollution Control Act","Articles 20-1, 21-2 and 24-3 of the Air Pollution Control Act as cited","Articles 18-5, 22-1 and 31-2 of the Air Pollution Control Act as cited","Article 20-2 of the Waste Disposal Act plus Article 23-1 of the Air Act"],
 "Article 1 cites Articles 20, 22 and 23 of the Air Pollution Control Act."),

(A,"第2條",2,"電弧爐戴奧辛-名詞定義",
 "本標準所稱電弧爐及 Nm3 之定義各為何？",
 ["電弧爐指利用電弧產生之熱量熔煉礦石及金屬之工業爐；Nm3 指凱氏溫度二百七十三度及一大氣壓下每立方公尺體積","電弧爐指利用電阻加熱熔煉廢鐵之連續式加熱爐；Nm3 指凱氏溫度二百九十三度及一大氣壓下每立方公尺體積","電弧爐指以重油燃燒加熱熔煉金屬之反射爐；Nm3 指攝氏二十五度及一大氣壓下每立方公尺之排氣體積計算基準","電弧爐指利用感應電流熔煉礦石之感應爐；Nm3 指凱氏溫度二百七十三度及零點五大氣壓下每立方公尺體積"],"a",
 "第2條第1款：電弧爐指利用電弧產生之熱量熔煉礦石及金屬之工業爐；第4款：Nm3 指凱氏溫度二百七十三度及一大氣壓下每立方公尺體積。同條另定 ng 為奈克（10-9 公克）、I-TEF 為國際毒性當量因子、I-TEQ 為國際毒性當量。",
 "How are electric arc furnace and Nm3 defined in this standard?",
 ["An industrial furnace smelting ore and metal with heat from an electric arc; Nm3 is volume at 273 K and one atmosphere","A continuous resistance-heating furnace smelting scrap iron; Nm3 is volume at 293 K and one atmosphere pressure","A reverberatory furnace smelting metal by burning heavy oil; Nm3 is volume measured at 25 degrees Celsius and one atm","An induction furnace smelting ore by induced current; Nm3 is volume at 273 K and half of one atmosphere pressure"],
 "Article 2, subparagraphs 1 and 4."),

(A,"第3條",1,"電弧爐戴奧辛-適用範圍",
 "本標準之適用對象為何？",
 ["本標準適用於煉鋼業電弧爐","本標準適用於煉鋼業之所有加熱爐","本標準適用於各行業之工業用電爐","本標準適用於鑄造業之感應電爐"],"a",
 "第3條：本標準適用於煉鋼業電弧爐。第2條第1款並定義電弧爐為利用電弧產生之熱量熔煉礦石及金屬之工業爐；鑄造電爐另有煉鋼及鑄造電爐粒狀污染物管制及排放標準規範。",
 "What does this standard apply to?",
 ["Electric arc furnaces of the steelmaking industry","All heating furnaces of the steelmaking industry","Industrial electric furnaces in every industry","Induction electric furnaces of the foundry industry"],
 "Article 3."),

(A,"第4條",2,"電弧爐戴奧辛-排放標準值",
 "電弧爐之戴奧辛排放標準值為多少？",
 ["零點五 ng I-TEQ／Nm3","零點一 ng I-TEQ／Nm3","一點零 ng I-TEQ／Nm3","五點零 ng I-TEQ／Nm3"],"a",
 "第4條：電弧爐戴奧辛排放標準值為零點五 ng I-TEQ／Nm3。第5條並定檢測應以三次算術平均值超過該值時，即認定不符合本標準；廢棄物焚化爐之戴奧辛標準則為○．一 ng-TEQ/Nm3。",
 "What is the dioxin emission limit for electric arc furnaces?",
 ["0.5 ng I-TEQ per Nm3","0.1 ng I-TEQ per Nm3","1.0 ng I-TEQ per Nm3","5.0 ng I-TEQ per Nm3"],
 "Article 4."),

(A,"第5條",3,"電弧爐戴奧辛-檢測認定",
 "電弧爐戴奧辛檢測如何認定不符合規定？採樣時間間隔與涵蓋範圍有何要求？",
 ["以三次算術平均值超過排放標準值即認定不符合；第一次與第三次採樣間隔不得超過一個月，每次採樣應涵蓋二爐次以上操作循環","以五次測值取中間三數值平均超過標準值即認定不符合；第一次與第五次採樣間隔不得超過三個月，每次採樣涵蓋一爐次即可","以任一次測值超過排放標準值即認定不符合；三次採樣應於同一日內完成，每次採樣時間應涵蓋電弧爐三爐次以上操作循環","以三次幾何平均值超過排放標準值即認定不符合；第一次與第三次採樣間隔不得超過六個月，每次採樣應涵蓋半個爐次循環"],"a",
 "第5條第1項：以三次算術平均值超過第4條排放標準值時，即認定該電弧爐戴奧辛排放不符合本標準。第2項：第一次採樣與第三次採樣時間間隔不得超過一個月，每次採樣時間應涵蓋電弧爐二爐次以上之操作循環。",
 "How is non-compliance determined, and what sampling interval and coverage apply?",
 ["The arithmetic mean of three tests exceeding the limit; first to third sampling within one month, each covering two or more heats","The middle three of five values exceeding the limit; first to fifth sampling within three months, each covering one heat only","Any single value exceeding the limit; all three samplings finished in one day, each covering three or more furnace heats","The geometric mean of three tests exceeding the limit; first to third sampling within six months, each covering half a heat"],
 "Article 5, paragraphs 1 and 2."),

(A,"第6條",2,"電弧爐戴奧辛-濃度計算",
 "電弧爐排氣中戴奧辛檢測濃度應如何計算？",
 ["以凱氏溫度二百七十三度及一大氣壓下之乾燥排氣體積為基準，各項戴奧辛濃度乘以國際毒性當量因子之總和，以 I-TEQ 表示","以凱氏溫度二百九十三度及一大氣壓下之濕潤排氣體積為基準，各項戴奧辛濃度取算術平均後直接以 ng／Nm3 表示","以攝氏二十五度及一大氣壓下之乾燥排氣體積為基準，將各項戴奧辛濃度乘以含氧率校正係數之總和後表示之","以凱氏溫度二百七十三度及半大氣壓下之排氣體積為基準，取毒性最高之單一戴奧辛污染物濃度作為代表值"],"a",
 "第6條：以凱氏溫度二百七十三度及一大氣壓下之乾燥排氣體積為基準；檢測所得依附表所列各項戴奧辛污染物濃度乘以其國際毒性當量因子（I-TEF）之總和計算，以國際毒性當量（I-TEQ）表示。",
 "How is the measured dioxin concentration in stack gas calculated?",
 ["On dry gas volume at 273 K and one atm; each dioxin concentration times its I-TEF, summed and expressed as I-TEQ","On wet gas volume at 293 K and one atm; the arithmetic mean of the dioxin values expressed directly as ng per Nm3","On dry gas volume at 25 degrees Celsius and one atm; each value times an oxygen correction factor and then summed","On gas volume at 273 K and half an atmosphere; the single most toxic dioxin congener taken as the representative value"],
 "Article 6."),

(A,"第7條",3,"電弧爐戴奧辛-操作運轉",
 "電弧爐煉鋼作業對集塵設備入口廢氣溫度有何規定？",
 ["集塵設備入口廢氣溫度應保持在攝氏二百度以下，並應具備可即時顯示該入口廢氣溫度之監測設施","集塵設備入口廢氣溫度應保持在攝氏二百八十度以下，並應每月人工量測記錄該入口廢氣溫度一次","集塵設備出口廢氣溫度應保持在攝氏二百度以下，並應具備可即時顯示該出口廢氣溫度之監測設施","集塵設備入口廢氣溫度應保持在攝氏八百五十度以上，並應具備連續自動監測及紀錄傳輸之設施"],"a",
 "第7條第1款：電弧爐集塵設備入口廢氣溫度應保持在攝氏二百度以下，並具備可即時顯示電弧爐集塵設備入口廢氣溫度之監測設施。此為抑制戴奧辛再合成之重要操作條件。",
 "What rule applies to the flue gas temperature at the dust collector inlet?",
 ["It must be kept below 200 degrees Celsius, with a monitor able to display that inlet temperature in real time","It must be kept below 280 degrees Celsius, with the inlet temperature recorded manually once every month","The dust collector outlet gas must be kept below 200 degrees Celsius, with real time display of that outlet value","It must be kept above 850 degrees Celsius, with continuous automatic monitoring and data transmission installed"],
 "Article 7, subparagraph 1."),

(A,"第7條",3,"電弧爐戴奧辛-活性碳注入",
 "採用活性碳注入設備降低戴奧辛排放者，其注入量有何管制？",
 ["應記錄每小時注入量，正常操作時不得低於最近一次合格檢測期間同規格活性碳之平均每小時注入量","應記錄每日注入總量，正常操作時不得低於最近一次合格檢測期間同規格活性碳之平均每日注入量","應記錄每小時注入量，正常操作時不得高於最近一次合格檢測期間同規格活性碳之平均每小時注入量","應記錄每季注入總量，正常操作時得由業者自行依廢氣量調整，僅需於年度報告中敘明調整理由"],"a",
 "第7條第2款：採用活性碳注入設備者，應記錄每小時活性碳注入量；正常操作時注入量不得低於最近一次檢測結果符合第4條排放標準值之檢測期間所使用同一規格活性碳之平均每小時注入量。若變更活性碳規格或減少注入量，應重新進行戴奧辛檢測以測定注入量下限值。",
 "How is activated carbon injection controlled when used to reduce dioxin emissions?",
 ["Hourly injection must be recorded and, in normal operation, not fall below the hourly average of the last compliant test","Daily injection totals must be recorded and, in normal operation, not fall below the daily average of the last test","Hourly injection must be recorded and, in normal operation, not exceed the hourly average of the last compliant test","Quarterly totals must be recorded and the operator may adjust freely, explaining the change in the annual report"],
 "Article 7, subparagraph 2."),

(A,"第8條",2,"電弧爐戴奧辛-定期檢測",
 "煉鋼業電弧爐排氣中戴奧辛之定期檢測頻率、計畫書及報告期限為何？",
 ["至少每一年檢測一次；定期檢測日七日前檢送檢測計畫書；每次檢測結果於檢測後六十日內提出檢測報告書","至少每二年檢測一次；定期檢測日三十日前檢送檢測計畫書；每次檢測結果於檢測後三十日內提出報告書","至少每半年檢測一次；定期檢測日十四日前檢送檢測計畫書；每次檢測結果於檢測後九十日內提出報告書","至少每一年檢測二次；定期檢測日七日前檢送檢測計畫書；每次檢測結果於檢測後十五日內提出檢測報告書"],"a",
 "第8條第1款至第3款：至少每一年依第5條規定實施定期檢測一次；定期檢測日之七日前檢送檢測計畫書至直轄市、縣（市）主管機關；每次檢測結果於檢測後六十日內提出檢測報告書。",
 "What are the periodic testing frequency, plan filing and report deadlines?",
 ["At least once a year; the test plan is filed seven days before the test; the report is filed within 60 days after it","At least once every two years; the plan is filed 30 days before the test; the report is filed within 30 days after","At least twice a year, i.e. every half year; the plan is filed 14 days before; the report is filed within 90 days","At least twice a year; the plan is filed seven days before the test; the report is filed within 15 days after it"],
 "Article 8, subparagraphs 1 to 3."),

(A,"第8條",3,"電弧爐戴奧辛-檢測頻率調整",
 "電弧爐業者於何種情形得申請調整戴奧辛檢測頻率？調整後之下限與回復條件為何？",
 ["連續二次定期檢測均符合標準值得申請調整，調整後不得低於每二年一次；經稽查或任一次定檢超標應回復原頻率","連續三次定期檢測均符合標準值得申請調整，調整後不得低於每三年一次；經稽查超標者仍得維持已調整之頻率","首次定期檢測符合標準值即得申請調整，調整後不得低於每五年一次；僅連續二次定檢超標時才須回復原頻率","連續二次定期檢測均符合標準值得逕行調整，調整後不得低於每四年一次；經稽查超標者由主管機關另行公告"],"a",
 "第8條第2款：連續二次定期檢測排氣中戴奧辛濃度均符合第4條排放標準值者，得檢具相關證明文件向直轄市、縣（市）主管機關申請調整檢測頻率，調整之檢測頻率不得低於每二年一次；但經稽查結果或任一次定期檢測結果超過排放標準值時，應回復至每年一次。",
 "When may the testing frequency be relaxed, what is the floor, and when must it revert?",
 ["After two consecutive compliant periodic tests, upon application; not less than once every two years; reverts if any test or inspection exceeds","After three consecutive compliant tests, upon application; not less than once every three years; an exceedance found on inspection changes nothing","After the very first compliant periodic test; not less than once every five years; it reverts only after two consecutive exceedances are found","After two consecutive compliant tests, without any application; not less than once every four years; exceedances are handled by separate notice"],
 "Article 8, subparagraph 2."),

(A,"第9條",1,"電弧爐戴奧辛-施行日",
 "煉鋼業電弧爐戴奧辛管制及排放標準之施行日期規定為何？",
 ["本標準自發布日施行","本標準自發布後六個月施行","本標準自發布後一年施行","本標準自次年一月一日施行"],"a",
 "第9條：本標準自發布日施行。本標準最近一次修正日期為民國一百零九年十二月二十三日，第4條所定排放標準值零點五 ng I-TEQ／Nm3 亦自發布日起適用。",
 "When does this standard take effect?",
 ["It takes effect on the date of promulgation","It takes effect six months after promulgation","It takes effect one year after promulgation","It takes effect on January 1 of the next year"],
 "Article 9."),

# ===== ENV-136 違反空氣污染防制法按次處罰通知限期改善補正或申報執行準則（12 條）=====
(B,"第1條",1,"按次處罰準則-授權依據",
 "違反空氣污染防制法按次處罰通知限期改善補正或申報執行準則之授權依據為何？",
 ["空氣污染防制法第八十一條第二項","空氣污染防制法第八十二條第二項","空氣污染防制法第七十五條第三項","行政罰法第十八條第二項規定訂定"],"a",
 "第1條：本準則依空氣污染防制法第八十一條第二項規定訂定之。至於延長改善期限之申請，則另依同法第八十二條第二項規定辦理（見本準則第9條、第10條）。",
 "Which provision authorizes these Enforcement Rules?",
 ["Article 81, paragraph 2 of the Air Pollution Control Act","Article 82, paragraph 2 of the Air Pollution Control Act","Article 75, paragraph 3 of the Air Pollution Control Act","Article 18, paragraph 2 of the Administrative Penalty Act"],
 "Article 1."),

(B,"第2條",2,"按次處罰準則-書面作成",
 "主管機關為按次處罰時，限期改善通知書與裁處書應如何作成？一行為同時違反數規定時如何處理？",
 ["通知書與裁處書應分別作成；一行為違反數規定者，應依不同違規行為在同一通知書分別作成通知內容","通知書與裁處書得合併作成一份文書；一行為違反數規定者，應就每一違規行為分別作成數份通知書","通知書與裁處書應分別作成；一行為違反數規定者，僅須就情節最重之一項違規作成限期改善之通知","通知書與裁處書由主管機關裁量合併或分別；一行為違反數規定者，得免除限期改善通知逕予裁處罰鍰"],"a",
 "第2條第1項：限期改善、補正或申報之通知書與裁處書應分別作成。第2項：一行為同時違反數規定，或同一時間有數違規行為，應依該不同違規行為在同一限期改善、補正或申報通知書分別作成通知內容。",
 "How are the correction notice and the penalty decision issued, and what if one act violates several provisions?",
 ["They are issued as separate documents; several violations are set out separately within one and the same notice","They may be merged into a single document; several violations require several separate notices to be issued","They are issued separately; where several provisions are breached only the most serious one is noticed","The agency may merge or separate them at will; several violations allow a fine without any correction notice"],
 "Article 2, paragraphs 1 and 2."),

(B,"第2條",3,"按次處罰準則-通知書記載",
 "限期改善、補正或申報通知書應記載之事項，下列何者完全正確？",
 ["處分對象、處分事由、應改善補正或申報事項、期限、應檢具之證明文件、屆期未完成按次處罰之規定","處分對象、處分事由、罰鍰金額及繳納帳號、期限、應檢具之證明文件、屆期未完成移送強制執行之規定","處分對象、違規地點座標、應改善事項、期限、行政救濟期間及受理機關、屆期未完成停工停業之規定","處分對象、處分事由、應改善事項、期限、改善費用估算及分攤方式、屆期未完成沒入設備之相關規定"],"a",
 "第2條第3項：通知書應記載處分對象、處分事由、應改善補正或申報事項、改善補正或申報期限、完成改善應檢具之證明文件、屆期未完成者按次處罰之規定及其他經主管機關記載事項。但屬應令立即停止或非以證明文件證明完成者，得免記載。",
 "Which set of items must the correction notice contain?",
 ["The addressee, grounds, items to be corrected, the deadline, the documents to be submitted, and the repeated penalty rule","The addressee, grounds, the fine amount and payment account, the deadline, the documents, and the compulsory execution rule","The addressee, coordinates of the site, items to correct, the deadline, appeal periods and forum, and a shutdown rule","The addressee, grounds, items to correct, the deadline, an estimate of correction cost, and a confiscation of equipment rule"],
 "Article 2, paragraph 3."),

(B,"第3條",2,"按次處罰準則-事項判定",
 "主管機關記載通知書之應改善、補正或申報事項時，應依何為判定基礎？",
 ["應審酌現場稽查結果或違規者陳述之違規原因判定","應依中央主管機關統一公告之標準改善事項表判定","應依違規者所提改善計畫書所載之項目逕予採認判定","應依前一年度同業改善案例之平均改善事項判定之"],"a",
 "第3條：違反本法規定者，主管機關為記載第2條第3項第3款所定應改善、補正或申報事項，應審酌現場稽查結果或其陳述之違規原因判定。此可避免通知內容與實際違規情形脫節。",
 "On what basis does the agency decide the items to be corrected in the notice?",
 ["On the on-site inspection results or the violator's stated cause of the violation","On a uniform national table of standard correction items published centrally","On the items listed in the correction plan submitted by the violator, as accepted","On the average correction items in comparable industry cases of the prior year"],
 "Article 3."),

(B,"第4條",2,"按次處罰準則-期限裁量",
 "主管機關訂定改善、補正或申報期限時應如何裁量？可立即改善之違規行為如何處理？",
 ["應依違規行為態樣所生影響及所需時間裁量；屬可立即改善之違規行為，應令其立即改善","應一律給予三十日之改善期限；屬可立即改善之違規行為，仍應給予至少七日之改善期限","應依業者營業規模及資本額大小裁量；屬可立即改善之違規行為，得免予限期改善之通知","應依中央主管機關公告之期限表裁量；屬可立即改善之違規行為，得由業者自行決定改善日"],"a",
 "第4條：主管機關記載改善、補正或申報期限，應依不同違規行為態樣所生之影響及其改善、補正或申報事項所需之時間，予以裁量；但屬可立即改善之違規行為，應令其立即改善。",
 "How is the correction deadline set, and what about immediately correctable violations?",
 ["By weighing the impact of the violation and the time needed; immediately correctable violations must be corrected at once","A uniform 30-day period always applies; even immediately correctable violations get at least seven days","By reference to the operator's business scale and capital; immediately correctable violations need no notice at all","By a table of deadlines published centrally; for immediately correctable violations the operator picks the date"],
 "Article 4."),

(B,"第5條",3,"按次處罰準則-排放超標證明",
 "固定污染源排放空氣污染物未符合排放標準者，應令其檢具之證明文件包括下列何者？",
 ["污染源名稱設備構造規模、製造流程圖說、原物料燃料種類成分數量、防制設施收集方式、防制設備操作條件、排放型式及許可檢測機構合格報告","污染源名稱設備構造規模、公司財務報表及納稅證明、從業員工名冊、防制設備採購合約、保險單、排放型式及地方環保團體同意文件","污染源名稱設備構造規模、土地所有權狀、建築物使用執照、水權登記證明、消防安全檢查表、排放型式及目的事業主管機關核發之工廠登記","污染源名稱設備構造規模、製造流程圖說、原物料燃料種類成分數量、周界噪音監測紀錄、地下水監測井位置圖及廢棄物清理計畫書"],"a",
 "第5條第1款各目：包括污染源之名稱設備構造及規模、生產製造流程圖說及產製期程、使用原（物）料燃料之種類成分數量及產品產量、防制設施廢氣收集方式及效果、防制設備或措施種類操作條件及處理效果、廢氣排放型式與污染物種類濃度排放量，以及經中央主管機關許可之檢測機構所為合格檢測報告。主管機關得視違規態樣免記載第一目至第六目之任一文件。",
 "Which documents may be required where a stationary source exceeds an emission standard?",
 ["Source name and structure, process drawings, raw material and fuel data, gas collection, control equipment operation, emission profile, and a licensed test report","Source name and structure, financial statements and tax records, staff roster, purchase contracts for control equipment, insurance, emission profile, and NGO consent","Source name and structure, land title deed, building use permit, water right certificate, fire safety checklist, emission profile, and the factory registration certificate","Source name and structure, process drawings, raw material and fuel data, boundary noise records, groundwater well map, and a waste clearance plan"],
 "Article 5, subparagraph 1."),

(B,"第5條",2,"按次處罰準則-其他證明文件",
 "燃料成分或含揮發性有機物之化學製品成分未符合標準者，以及非屬前二款之違規者，應分別檢具何種文件？",
 ["前者應檢具經中央主管機關許可之檢測機構所為之合格檢測報告；後者應檢具經主管機關認可之證明文件","前者應檢具供應商出具之品質保證書即可；後者應檢具經中央主管機關許可之檢測機構合格檢測報告","前者應檢具經目的事業主管機關備查之自主管理紀錄；後者應檢具公會或同業公會出具之同意證明文件","前者應檢具原廠成分分析表及進口報單影本；後者應檢具經地方民意機關備查之改善承諾書及切結書"],"a",
 "第5條第2款：燃料成分或含揮發性有機物之化學製品成分未符合本法所定標準者，應令其檢具許可之檢測機構所為之合格檢測報告。第3款：非屬前二款者，應令其檢具經主管機關認可之證明文件。",
 "What documents are required for non-compliant fuel or VOC chemical composition, and for other violations?",
 ["For the former, a qualified test report from a licensed testing organization; for the latter, documents recognized by the agency","For the former, a supplier's quality warranty suffices; for the latter, a qualified report from a licensed testing organization","For the former, self-management records filed with the industry authority; for the latter, a consent letter from a trade association","For the former, the maker's analysis sheet and import declaration; for the latter, an undertaking filed with the local council"],
 "Article 5, subparagraphs 2 and 3."),

(B,"第6條",2,"按次處罰準則-停工替代文件",
 "以停工、停業或無空氣污染物排放作為改善方式而無法檢具一般證明文件者，得檢具哪些文件？",
 ["自行停工或停業之佐證資料；主要生產設備已搬遷且經認定無製造加工事實之文件；改變製程或防制設施致無排放之文件","自行停工或停業之佐證資料；員工資遣通報名冊及勞保退保證明；主管機關廢止工廠登記證之公文影本及切結書","污染源操作許可證繳銷之證明文件；電力公司出具之停止供電證明；地方民意代表出具之現場無營運事實證明書","自行停工之口頭陳述紀錄；鄰近住戶簽署之無異議書；環保團體現場會勘紀錄及公私場所自行拍攝之現場照片"],"a",
 "第6條：得檢具自行停工或停業之佐證資料；主要生產設備已搬遷且經目的事業主管機關認定無製造、加工事實者之文件；無空氣污染物排放者，其改變生產製造程序或空氣污染防制設施致無空氣污染物排放之文件。",
 "Where correction takes the form of shutdown or zero emission, which documents may be filed instead?",
 ["Evidence of self-imposed shutdown; documents showing main equipment removed and no manufacturing found; proof of process change ending emissions","Evidence of shutdown; a layoff notification roster and labor insurance withdrawal proof; a copy of the revocation of factory registration","Proof that the source operating permit was surrendered; a power company certificate of supply cut-off; a councillor's statement of no operation","A record of an oral statement of shutdown; a no-objection letter signed by neighbours; an NGO site record and the firm's own photographs"],
 "Article 6."),

(B,"第7條",2,"按次處罰準則-查驗方式",
 "違規者經通知限期改善後，其完成改善之認定查驗方式為何？",
 ["檢具規定文件送達主管機關，並經主管機關查驗認定完成應改善事項；必要時得另行辦理檢驗測定查證","僅需將規定文件以電子郵件送達主管機關，即視為完成改善，主管機關不得再行辦理檢驗測定之查證","由公私場所自行委託檢測機構作成報告並自行認定完成，主管機關僅就報告格式進行形式上之書面審查","須經主管機關會同目的事業主管機關及環保團體共同現場會勘，並取得全體出席人員之一致同意始得認定"],"a",
 "第7條第1項：查驗方式為檢具第5條或第6條規定之文件送達主管機關，並經主管機關查驗認定完成應改善、補正或申報事項。第2項：公私場所檢具許可之檢測機構所為合格檢測報告者，必要時主管機關得另行辦理檢驗測定查證認定之。",
 "How is completion of correction verified?",
 ["The required documents are served on the agency and the agency verifies completion; it may additionally carry out its own testing","Emailing the required documents to the agency alone counts as completion, and the agency may not conduct any further testing","The facility commissions its own test report and declares completion; the agency only reviews the report's format on paper","A joint site inspection with the industry authority and NGOs is required, and all attendees must unanimously agree"],
 "Article 7, paragraphs 1 and 2."),

(B,"第8條",2,"按次處罰準則-查驗期限",
 "主管機關應於何時進行完成改善之認定查驗？查驗得以何種方式為之？",
 ["應於收受證明文件之翌日起十個工作日內進行查驗，必要時得延長；查驗方式得以書面審查或現場查驗為之","應於收受證明文件之翌日起三十個工作日內進行查驗，不得延長；查驗方式一律應以現場查驗方式為之","應於收受證明文件之當日起五個工作日內進行查驗，必要時得延長；查驗方式一律應以書面審查方式為之","應於收受證明文件之翌日起十個曆日內進行查驗，不得延長；查驗方式得由違規者自行選擇書面或現場"],"a",
 "第8條第1項：主管機關應於收受改善、補正或申報證明文件之翌日起十個工作日內進行完成認定之查驗，必要時得延長之。第2項：認定查驗方式得以書面審查或現場查驗方式為之。",
 "When must the agency verify completion, and by what means?",
 ["Within ten working days from the day after receiving the documents, extendable if necessary; by paper review or site inspection","Within thirty working days from the day after receipt, not extendable; verification must always be by on-site inspection","Within five working days counted from the day of receipt, extendable; verification must always be by paper review only","Within ten calendar days from the day after receipt, not extendable; the violator chooses paper review or site inspection"],
 "Article 8, paragraphs 1 and 2."),

(B,"第9條",3,"按次處罰準則-改善計畫內容",
 "申請延長改善期限所提具體改善計畫，應包括哪些內容？",
 ["污染源名稱及據以處罰之違規事實、改善目標時程與預定進度、申請延長之日數、改善期間採取之污染防制措施","污染源名稱及據以處罰之違規事實、公司近三年財務報表、股東名冊、申請延長之日數及改善期間營收預估數","污染源名稱及違規事實、鄰近居民陳情紀錄、環境影響評估書件、申請延長日數及改善完成後之產能擴充計畫","污染源名稱及違規事實、改善目標及時程、申請延長之日數、改善期間預定裁減之員工人數及資遣費用估算"],"a",
 "第9條第1項：具體改善計畫應包括污染源名稱及據以處罰並限期改善之違規事實、改善目標時程預定進度及相關證明文件、申請延長之日數、改善期間採取之污染防制措施，以及其他經主管機關指定之事項。",
 "What must the concrete improvement plan for an extension contain?",
 ["Source name and the violation penalized, improvement targets, schedule and progress, the days of extension sought, and interim control measures","Source name and the violation, the company's three-year financial statements, shareholder roster, days sought, and revenue forecasts","Source name and violation, residents' complaint records, the EIA documents, days of extension sought, and a post-correction expansion plan","Source name and violation, improvement targets and schedule, days sought, plus planned staff reductions and severance cost estimates"],
 "Article 9, paragraph 1."),

(B,"第9條",3,"按次處罰準則-受理與進度",
 "延長改善期限之申請由何機關受理？核定期限與執行進度提報規定為何？",
 ["固定污染源由直轄市縣市主管機關受理、汽車召回改正由中央主管機關受理，均於三十日內核定；核定後每月十五日前提報前一月進度","固定污染源與汽車召回改正均由中央主管機關受理，並於六十日內核定；核定後每季結束後十五日內提報上一季之改善進度","固定污染源由中央主管機關受理、汽車召回改正由地方主管機關受理，均於十五日內核定；核定後每月月底前提報當月進度","固定污染源由直轄市縣市主管機關受理、汽車召回改正由目的事業主管機關受理，均於九十日內核定；改善完成後一次提報"],"a",
 "第9條第2項：屬固定污染源者由直轄市、縣（市）主管機關受理並於三十日內核定；屬汽車召回改正者由中央主管機關受理並於三十日內核定。第3項：經核定延長改善期限者，應於每月十五日前向核定機關提報前一月之改善執行進度。",
 "Who accepts an extension application, what is the decision period, and how is progress reported?",
 ["Local agencies for stationary sources and the central agency for vehicle recalls, both deciding within 30 days; progress by the 15th each month","The central agency for both stationary sources and vehicle recalls, deciding within 60 days; progress within 15 days after each quarter","The central agency for stationary sources and local agencies for vehicle recalls, both within 15 days; progress by the end of each month","Local agencies for stationary sources and the industry authority for vehicle recalls, both within 90 days; one report after completion"],
 "Article 9, paragraphs 2 and 3."),

(B,"第10條",3,"按次處罰準則-終止改善期限",
 "有下列何種情形，屬未確實依改善計畫執行，主管機關得立即終止改善期限並從重處罰？",
 ["未按月提報改善進度；非因不可抗力未按核定進度執行且落後達三十日以上；未依核定計畫內容執行；延長期間大量排放嚴重影響空氣品質","未按季提報改善進度；因不可抗力未按核定進度執行且落後達十五日以上；變更計畫主持人；延長期間發生勞工職業災害之情事","未按月提報改善進度；因天災導致工程延誤達七日以上；改善經費超出預算逾百分之十；延長期間曾遭民眾陳情達三件以上","未按月提報改善進度；非因不可抗力落後進度達九十日以上；未依計畫內容執行；延長期間排放任何空氣污染物之情形"],"a",
 "第10條：未依第9條第3項按月提報改善進度、非因不可抗力未按核定改善計畫進度執行且落後達三十日以上、未依核定計畫內容執行、延長改善期間大量排放空氣污染物嚴重影響附近地區空氣品質者，主管機關得依本法第82條第2項立即終止改善期限並從重處罰。",
 "Which circumstances show the improvement plan was not truly followed, allowing immediate termination and a heavier penalty?",
 ["No monthly progress reports; falling 30 days or more behind the approved schedule other than by force majeure; not following the plan; heavy emissions harming air quality","No quarterly progress reports; falling 15 days behind due to force majeure; changing the plan's project leader; an occupational accident during the extension","No monthly reports; weather-related delay of seven days or more; costs exceeding budget by over ten percent; three or more public complaints during the extension","No monthly reports; falling 90 days or more behind other than by force majeure; not following the plan; emitting any air pollutant during the extension"],
 "Article 10."),

(B,"第11條",2,"按次處罰準則-再次通知",
 "經查驗認定仍未完成改善者，主管機關應如何處理？再次通知之期限如何判定？",
 ["按查驗日之情事開立裁處書並再次通知限期改善；再次通知之期限應審酌前次執行情形及再次違反應改善事項判定","按原處分日之情事開立裁處書但不再通知限期改善；後續改善期限一律沿用前次通知書所載之相同改善期限","逕行移送行政執行不再開立裁處書；如需再次通知者，其改善期限不得少於前次通知書所定期限之二倍以上","按查驗日之情事開立裁處書但改善期限由違規者自行決定；主管機關僅得就其所報期限為形式上之備查作業"],"a",
 "第11條第1項：經查驗認定仍未完成改善、補正或申報者，按查驗日之情事開立裁處書，並再次通知限期改善、補正或申報。第2項：再次通知之處分事由與應改善事項與前次相同時，應審酌前次應改善事項執行情形及再次違反應改善事項，判定第2條第3項第4款所定期限。",
 "What happens if verification shows correction is still incomplete, and how is the new deadline set?",
 ["A penalty is issued based on the situation on the verification day and a new notice given; the deadline weighs prior performance and the repeated breach","A penalty is issued based on the original decision date and no further notice is given; the same deadline as before always applies afterwards","The case goes straight to compulsory execution with no penalty decision; any new deadline must be at least twice the previous one","A penalty is issued on the verification day's facts but the violator sets its own deadline, which the agency merely records"],
 "Article 11, paragraphs 1 and 2."),

(B,"第12條",1,"按次處罰準則-施行日",
 "本準則之施行日期規定為何？",
 ["本準則自發布日施行","本準則自發布後三個月施行","本準則自發布後一年施行","本準則自次年七月一日施行"],"a",
 "第12條：本準則自發布日施行。本準則最近一次修正日期為民國一百零八年八月十九日，係配合空氣污染防制法第81條、第82條之修正而訂定按次處罰之作業程序。",
 "When do these Enforcement Rules take effect?",
 ["They take effect on the date of promulgation","They take effect three months after promulgation","They take effect one full year after promulgation","They take effect on July 1 of the following year"],
 "Article 12."),

# ===== ENV-137 違反室內空氣品質管理法罰鍰額度裁罰準則（9 條）=====
(C,"第1條",1,"室內空品裁罰-授權依據",
 "違反室內空氣品質管理法罰鍰額度裁罰準則係依何規定訂定？",
 ["室內空氣品質管理法第十九條第二項","室內空氣品質管理法第二十一條第二項","室內空氣品質管理法第十七條第三項","行政罰法第十八條第一項規定訂定之"],"a",
 "第1條：本準則依室內空氣品質管理法第十九條第二項規定訂定之。第7條另援引本法第二十一條各款所定情節重大情形，得以各該條最高罰鍰額度裁處。",
 "Which provision authorizes these fine-assessment rules?",
 ["Article 19, paragraph 2 of the Indoor Air Quality Management Act","Article 21, paragraph 2 of the Indoor Air Quality Management Act","Article 17, paragraph 3 of the Indoor Air Quality Management Act","Article 18, paragraph 1 of the Administrative Penalty Act"],
 "Article 1."),

(C,"第2條",2,"室內空品裁罰-審酌事項",
 "違反室內空氣品質管理法者，罰鍰額度除依附表所列情事裁處外，尚應審酌哪些事項？",
 ["應審酌違反本法義務行為應受責難程度、所生影響及因違反義務所得之利益，並得考量受處罰者之資力","應審酌受處罰者之營業規模、員工人數及設立年限，並得考量該場所所在行政區之平均所得水準","應審酌違規場所之樓地板面積、使用人數及空調設備型式，並得考量該場所曾否獲頒環保標章","應審酌違規行為發生之季節、當日室外空氣品質指標及氣象條件，並得考量民眾陳情之件數多寡"],"a",
 "第2條：罰鍰額度除依附表所列情事裁處外，依行政罰法第十八條第一項規定，應審酌違反本法義務行為應受責難程度、所生影響及因違反本法義務所得之利益，並得考量受處罰者之資力。",
 "Besides the attached table, what must be weighed when setting the fine?",
 ["The blameworthiness of the breach, its impact, and the gain obtained from it; the offender's financial capacity may also count","The offender's business scale, number of employees and years since establishment, and the average income of the district","The floor area of the venue, its occupancy and the type of air conditioning, and whether it has won an eco-label","The season of the violation, the outdoor air quality index and weather that day, and the number of public complaints"],
 "Article 2, applying Article 18-1 of the Administrative Penalty Act."),

(C,"第3條",2,"室內空品裁罰-法規競合",
 "一行為違反本法數個規定時，罰鍰額度應如何計算裁處？",
 ["應依法定罰鍰額最高之規定及附表所列情事計算罰鍰額度裁處之","應將各該規定之法定罰鍰額分別計算後合併累加裁處其總額","應依法定罰鍰額最低之規定及附表所列情事計算罰鍰額度裁處","應依違規者自行選擇之其中一項規定計算罰鍰額度後裁處之"],"a",
 "第3條：一行為違反本法數個規定，應依法定罰鍰額最高之規定及附表所列情事計算罰鍰額度裁處之。第4條則處理法定罰鍰額均相同之情形，先分別計算再依額度最高者裁處。",
 "Where one act breaches several provisions, how is the fine determined?",
 ["By the provision with the highest statutory maximum, computed with the circumstances listed in the table","By computing the statutory fine for each provision separately and adding them all together","By the provision with the lowest statutory maximum, computed with the circumstances in the table","By whichever single provision the violator itself elects to have the fine computed under"],
 "Article 3."),

(C,"第4條",2,"室內空品裁罰-罰鍰額相同",
 "一行為違反本法數個規定且法定罰鍰額均相同者，應如何裁處？",
 ["應先依附表所列情事分別計算罰鍰額度，再依罰鍰額度最高者裁處之","應先依附表所列情事分別計算罰鍰額度，再依其算術平均值裁處之","應直接以法定罰鍰額之最高額裁處，無須依附表分別計算罰鍰額度","應先依附表分別計算罰鍰額度，再將各該額度合併累加後全額裁處"],"a",
 "第4條：一行為違反本法數個規定，且其法定罰鍰額均相同者，應先依附表所列情事分別計算罰鍰額度，再依罰鍰額度最高者裁處之。此與第3條法定罰鍰額不同時之處理方式相呼應。",
 "If one act breaches several provisions carrying identical statutory fines, how is it handled?",
 ["Compute the fine separately for each under the table, then impose the highest of those amounts","Compute the fine separately for each under the table, then impose their arithmetic average","Impose the statutory maximum directly, without computing amounts separately under the table","Compute each separately under the table, then add all the amounts together and impose the total"],
 "Article 4."),

(C,"第5條",3,"室內空品裁罰-所得利益",
 "違反本法義務所得之利益與法定罰鍰最高額之關係，裁罰時應如何處理？",
 ["未超過法定罰鍰最高額者，依附表計算罰鍰併加計所得利益，但不得超過法定最高額；超過者，於所得利益範圍內酌量加重","未超過法定罰鍰最高額者，一律以法定最高額裁處而不再加計所得利益；超過者，應以所得利益之二倍作為罰鍰額度","未超過法定罰鍰最高額者，應自附表計算之罰鍰中扣除所得利益後裁處；超過者，仍受法定罰鍰最高額之限制不得逾越","未超過法定罰鍰最高額者，得由主管機關裁量是否加計所得利益；超過者，應移送司法機關依刑事程序沒收其利益"],"a",
 "第5條第1項：所得之利益未超過法定罰鍰最高額時，應依第2條附表計算罰鍰，併加計所得之利益裁處，惟最高不得超過法定罰鍰最高額。第2項：所得利益超過法定罰鍰最高額時，應依行政罰法第十八條第二項規定，於所得利益範圍內酌量加重，不受法定罰鍰最高額之限制。",
 "How is the gain from the violation treated against the statutory maximum fine?",
 ["If the gain is below the maximum, add it to the table amount but cap at the maximum; if above, increase within the gain, uncapped","If below the maximum, always impose the statutory maximum without adding the gain; if above, impose twice the gain as the fine","If below the maximum, deduct the gain from the table amount; if above, the statutory maximum still caps the fine imposed","If below the maximum, the agency may choose whether to add the gain; if above, refer the case for criminal confiscation"],
 "Article 5, paragraphs 1 and 2."),

(C,"第6條",3,"室內空品裁罰-按次處罰",
 "依本法所為按次處罰之每次罰鍰額度，應如何決定？",
 ["未於改善期限屆滿前報請查驗而視為未完成改善者，依最近一次所處罰鍰額度裁處；報請查驗而認定未完成者，依查驗當日附表所列情事裁處","未於改善期限屆滿前報請查驗者，依附表最低額度裁處；報請查驗而認定未完成改善者，一律依最近一次所處罰鍰額度加倍裁處之","未於改善期限屆滿前報請查驗者，依查驗當日附表所列情事裁處；報請查驗而認定未完成改善者，依最近一次所處罰鍰額度裁處","未於改善期限屆滿前報請查驗者，應停止其場所使用而免予罰鍰；報請查驗而認定未完成改善者，依法定罰鍰最高額裁處"],"a",
 "第6條：屬未於改善期限屆滿前向主管機關報請查驗，視為未完成改善或補正者，依最近一次所處罰鍰額度裁處；屬報請主管機關查驗而認定未完成改善或補正者，依查驗當日附表所列情事裁處之。",
 "How is each repeated fine determined under this Act?",
 ["Where no verification was requested, by the most recent fine imposed; where verification was requested but failed, by the table on the verification day","Where no verification was requested, by the lowest amount in the table; where verification was requested but failed, always double the most recent fine imposed","Where no verification was requested, by the table on the verification day; where verification was requested but failed, by the most recent fine imposed","Where no verification was requested, close the venue with no fine; where verification was requested but failed, impose the statutory maximum fine"],
 "Article 6."),

(C,"第7條",2,"室內空品裁罰-情節重大",
 "屬本法第二十一條各款規定情節重大情形之一者，得如何裁處？",
 ["得以各該條最高罰鍰額度裁處之","得以各該條最低罰鍰額度裁處之","得逕予停止該場所之全部使用","得免除罰鍰改以書面告誡代之"],"a",
 "第7條：屬本法第二十一條各款規定情節重大情形之一者，得以各該條最高罰鍰額度裁處之。此為附表計算之例外，使情節重大者得逕依法定最高額處罰。",
 "How may a case be fined if it is a serious case under Article 21 of the Act?",
 ["It may be fined at the maximum amount of that provision","It may be fined at the minimum amount of that provision","The venue may simply be ordered to cease all use","The fine may be waived and replaced by a written warning"],
 "Article 7."),

(C,"第8條",2,"室內空品裁罰-改善期間惡化",
 "公告場所所有人於改善期間未進行室內空氣污染物改善及控管，致違規行為更形惡化者，應如何處理？",
 ["經主管機關認定違規行為更形惡化者，按其違規行為依本準則按次處罰","經主管機關認定違規行為更形惡化者，應延長其改善期限一次以利改善","經主管機關認定違規行為更形惡化者，僅得於改善期限屆滿後始得處罰","經主管機關認定違規行為更形惡化者，應逕行移送檢察機關偵辦其刑責"],"a",
 "第8條：公告場所所有人、管理人或使用人於公告場所改善期間，未進行室內空氣污染物改善及控管，經主管機關認定其違規行為更形惡化者，按其違規行為，依本準則按次處罰。",
 "What if the owner does nothing during the correction period and the violation worsens?",
 ["If the agency finds the violation has worsened, repeated fines are imposed under these rules","If the agency finds the violation has worsened, the correction period is extended once","If the agency finds the violation has worsened, a fine is possible only after the deadline","If the agency finds the violation has worsened, the case is referred for criminal prosecution"],
 "Article 8."),

(C,"第9條",1,"室內空品裁罰-施行日",
 "違反室內空氣品質管理法罰鍰額度裁罰準則之施行日期為何？",
 ["自中華民國一百零一年十一月二十三日施行","自中華民國一百零一年十一月二十三日後六個月施行","自中華民國一百零二年一月一日起開始正式施行","自中華民國一百年十一月二十三日起溯及既往施行"],"a",
 "第9條：本準則自中華民國一百零一年十一月二十三日施行，與其修正發布日期相同。至於各項罰鍰額度之計算基準，則依第2條所定附表辦理。",
 "When did these fine-assessment rules take effect?",
 ["They took effect on November 23, 2012","They took effect six months after that date","They took effect on January 1, 2013 as the formal date","They took effect retroactively from November 23, 2011"],
 "Article 9."),

# ===== ENV-139 鉛二次冶煉廠空氣污染物排放標準（8 條）=====
(D,"第1條",1,"鉛二次冶煉-授權依據",
 "鉛二次冶煉廠空氣污染物排放標準係依何規定訂定？",
 ["空氣污染防制法第二十條第二項","空氣污染防制法第二十二條第二項","空氣污染防制法第二十三條第二項","廢棄物清理法第二十條第二項規定"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項規定訂定之。第4條並定適用對象為鉛二次冶煉操作單元，第5條規定值如附表。",
 "Which provision authorizes the emission standard for secondary lead smelters?",
 ["Article 20, paragraph 2 of the Air Pollution Control Act","Article 22, paragraph 2 of the Air Pollution Control Act","Article 23, paragraph 2 of the Air Pollution Control Act","Article 20, paragraph 2 of the Waste Disposal Act"],
 "Article 1."),

(D,"第2條",1,"鉛二次冶煉-未規定事項",
 "本標準未規定之事項應如何處理？",
 ["本標準未規定事項適用其他相關標準之規定","本標準未規定事項由業者自行訂定內部規範","本標準未規定事項一律不受任何排放標準管制","本標準未規定事項應報請中央主管機關個案核定"],"a",
 "第2條：本標準未規定事項適用其他相關標準之規定，例如固定污染源空氣污染物排放標準。第3條並定本標準之專用名詞及符號意義與固定污染源空氣污染物排放標準相同。",
 "How are matters not provided for in this standard handled?",
 ["Matters not provided for are governed by other relevant standards","Matters not provided for are governed by the operator's own rules","Matters not provided for are exempt from any emission standard","Matters not provided for must be decided case by case centrally"],
 "Article 2."),

(D,"第3條",2,"鉛二次冶煉-名詞定義",
 "本標準之專用名詞及符號意義應依何規定？",
 ["與固定污染源空氣污染物排放標準之規定相同","與移動污染源空氣污染物排放標準規定相同","與廢棄物焚化爐空氣污染物排放標準相同","由直轄市、縣（市）主管機關逐案認定之"],"a",
 "第3條：本標準之專用名詞及符號意義與固定污染源空氣污染物排放標準同。故如 mg、Nm3、ppm、Cs、Os 等符號皆援用該標準之定義，不另重複規定。",
 "Where are the terms and symbols used in this standard defined?",
 ["They are the same as in the Stationary Source Air Pollutant Emission Standards","They are the same as in the Mobile Source Air Pollutant Emission Standards","They are the same as in the Waste Incinerator Air Pollutant Standards","They are determined case by case by the municipal or county authority"],
 "Article 3."),

(D,"第4條",1,"鉛二次冶煉-適用對象",
 "本標準之適用對象為何？",
 ["本標準適用於鉛二次冶煉操作單元","本標準適用於所有含鉛金屬冶煉工廠","本標準適用於鉛蓄電池製造之操作單元","本標準適用於原生鉛礦之冶煉操作單元"],"a",
 "第4條：本標準適用於鉛二次冶煉操作單元。所謂二次冶煉係指以含鉛廢料（如廢鉛蓄電池）為原料回收煉製鉛，與原生鉛礦冶煉有別。",
 "What is the scope of application of this standard?",
 ["It applies to secondary lead smelting operation units","It applies to all metal smelting plants containing lead","It applies to operation units making lead-acid batteries","It applies to smelting operation units for primary lead ore"],
 "Article 4."),

(D,"第5條",1,"鉛二次冶煉-規定值",
 "本標準之各項空氣污染物排放規定值如何呈現？",
 ["本標準規定值如附表所列","本標準規定值於條文中列明","本標準規定值由地方機關另訂","本標準規定值準用固定污染源標準"],"a",
 "第5條：本標準規定值如附表。第6條並定各項污染物採樣及測定方法依附表及中央主管機關增訂公告之方法；第8條定該附表與第7條自一百十年七月一日施行。",
 "How are the numerical emission limits set out in this standard?",
 ["The limits are listed in the attached table","The limits are written out article by article","The limits are separately set by local agencies","The limits follow the stationary source standard"],
 "Article 5."),

(D,"第6條",2,"鉛二次冶煉-採樣測定",
 "本標準各項污染物之採樣及測定方法應依何規定辦理？",
 ["依附表所列方法及中央主管機關增訂公告之方法","依業者委託之檢測機構自行選定之標準方法辦理","依直轄市、縣（市）主管機關個案指定之方法辦理","依國際標準組織所公布之最新方法逕行辦理即可"],"a",
 "第6條：各項污染物採樣及測定方法依附表及中央主管機關增訂公告之方法。第5條所定規定值亦列於附表，二者相互配合適用。",
 "Which sampling and testing methods apply to the pollutants under this standard?",
 ["Those listed in the attached table and those additionally announced centrally","Those chosen at will by the testing organization the operator commissions","Those designated case by case by the municipal or county competent authority","The latest methods published by the International Organization for Standardization"],
 "Article 6."),

(D,"第7條",3,"鉛二次冶煉-含氧率基準",
 "鉛二次冶煉廠煙道排氣中污染物濃度之計算基準為何？",
 ["以凱氏溫度二百七十三度及一大氣壓下未經稀釋之乾燥排氣體積為基準，並以百分之十九含氧率為參考基準","以凱氏溫度二百七十三度及一大氣壓下未經稀釋之濕潤排氣體積為基準，並以百分之十一含氧率為參考基準","以攝氏二十五度及一大氣壓下經稀釋後之乾燥排氣體積為基準，並以百分之十五含氧率作為濃度參考基準","以凱氏溫度二百九十三度及一大氣壓下未稀釋之乾燥排氣體積為基準，並以百分之六含氧率為濃度參考基準"],"a",
 "第7條第1項：煙道排氣中各種污染物之濃度計算均以凱氏溫度二百七十三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，並以百分之十九含氧率為參考基準。",
 "What basis is used to calculate stack gas pollutant concentrations here?",
 ["Undiluted dry gas volume at 273 K and one atmosphere, referenced to 19 percent oxygen content","Undiluted wet gas volume at 273 K and one atmosphere, referenced to 11 percent oxygen content","Diluted dry gas volume at 25 degrees Celsius and one atmosphere, referenced to 15 percent oxygen","Undiluted dry gas volume at 293 K and one atmosphere, referenced to 6 percent oxygen content"],
 "Article 7, paragraph 1."),

(D,"第7條",3,"鉛二次冶煉-含氧率校正",
 "排氣中含氧率之高低對污染物濃度計算有何影響？含氧率上限如何處理？",
 ["含氧率小於百分之十九時以實測值計算；含氧率為百分之十九以上時應依公式校正；含氧率大於百分之二十者以百分之二十計","含氧率小於百分之十九時應依公式校正；含氧率為百分之十九以上時以實測值計算；含氧率大於百分之二十者以實測值計","含氧率小於百分之十一時以實測值計算；含氧率為百分之十一以上時應依公式校正；含氧率大於百分之十五者以百分之十五計","含氧率高低均不影響濃度計算而一律以實測值認定；僅於含氧率大於百分之二十一時始須依公式進行濃度之校正計算"],"a",
 "第7條第2項：排氣中含氧率小於百分之十九時，排氣污染物濃度以實測值計算；含氧率為百分之十九以上時依計算式校正之；但排氣中含氧率大於百分之二十，則以百分之二十計。",
 "How does the measured oxygen content affect the concentration, and what cap applies?",
 ["Below 19 percent the measured value is used; at or above 19 percent the formula corrects it; above 20 percent, 20 percent is used","Below 19 percent the formula corrects it; at or above 19 percent the measured value is used; above 20 percent the measured value stands","Below 11 percent the measured value is used; at or above 11 percent the formula corrects it; above 15 percent, 15 percent is used","Oxygen content never affects the calculation and measured values always apply; only above 21 percent is any correction required"],
 "Article 7, paragraph 2."),

(D,"第8條",2,"鉛二次冶煉-施行日",
 "鉛二次冶煉廠空氣污染物排放標準之施行日期如何規定？",
 ["一百十年六月二十九日修正發布之第七條及第五條附表自一百十年七月一日施行，其餘自發布日施行","一百十年六月二十九日修正發布之全部條文均自一百十一年一月一日施行，並無分階段施行之規定","一百十年六月二十九日修正發布之第七條及第五條附表自一百十二年一月一日施行，其餘於發布後三個月施行","一百十年六月二十九日修正發布之條文自公告後六個月施行，第五條附表則授權地方主管機關另定施行日"],"a",
 "第8條：本標準除中華民國一百十年六月二十九日修正發布之第七條及第五條附表，自一百十年七月一日施行外，自發布日施行。可見含氧率參考基準與規定值附表另定較晚之施行日以利業者調整。",
 "How does this standard set its effective dates?",
 ["Article 7 and the Article 5 table as amended on June 29, 2021 take effect July 1, 2021; the rest on promulgation","All provisions amended on June 29, 2021 take effect on January 1, 2022, with no phased effective dates at all","Article 7 and the Article 5 table as amended take effect January 1, 2023; the rest three months after promulgation","The amended provisions take effect six months after announcement, with the table's date left to local authorities"],
 "Article 8."),

]
