# -*- coding: utf-8 -*-
# 第 12 批（A2）：ENV-101 公私場所固定污染源申請改善排放空氣污染物總量及濃度管理辦法、
#                ENV-102 公私場所固定污染源空氣污染物排放量申報管理辦法、
#                ENV-103 公私場所固定污染源復工試車評鑑及管理辦法
D = "ENV-101"
E = "ENV-102"
F = "ENV-103"
Q = [

# ===== ENV-101 申請改善排放空氣污染物總量及濃度管理辦法（14 條）=====
(D,"第1條",1,"排放抵換-授權",
 "公私場所固定污染源申請改善排放空氣污染物總量及濃度管理辦法係依何規定訂定？",
 ["空氣污染防制法第二十七條第三項","空氣污染防制法第二十一條第二項","空氣污染防制法第二十四條第四項","空氣污染防制法第三十一條第三項"],"a",
 "第1條：本辦法依空氣污染防制法第二十七條第三項規定訂定之。該條係規範公私場所以廠內固定污染源間排放量抵換方式，申請改善排放總量及濃度之依據。",
 "Under which provision is this offset improvement regulation issued?",
 ["Article 27, Paragraph 3 of the Air Pollution Control Act","Article 21, Paragraph 2 of the Air Pollution Control Act","Article 24, Paragraph 4 of the Air Pollution Control Act","Article 31, Paragraph 3 of the Air Pollution Control Act"],
 "Article 1: issued under Article 27-3 of the APCA."),

(D,"第2條",3,"排放抵換-適用污染物",
 "關於得申請改善排放之空氣污染物種類及抵換原則，下列敘述何者正確？",
 ["包括粒狀污染物、硫氧化物、氮氧化物、一氧化碳、揮發性有機污染物及其他經認可者；不同污染物之排放量不得互為抵換","包括粒狀污染物、硫氧化物、氮氧化物、戴奧辛及重金屬等五類；不同污染物之排放量得依當量係數互為抵換","僅限硫氧化物及氮氧化物二種；其排放量得跨越不同公私場所之固定污染源互相抵換以擴大改善效益","僅限揮發性有機污染物及一氧化碳二種；抵換前後之排放量得分別採用不同之計算方法計量"],"a",
 "第2條第1項列舉粒狀污染物、硫氧化物、氮氧化物、一氧化碳、揮發性有機污染物及其他經主管機關認可之污染物。第2項限於同一公私場所內固定污染源間抵換，且改善後總量應低於改善前；第3項明定不同污染物不得互為抵換，抵換前後應以同一計算方法為之。",
 "Which statement on covered pollutants and offset principles is correct?",
 ["Particulates, SOx, NOx, CO, VOCs and other approved pollutants; different pollutants may not offset each other","Particulates, SOx, NOx, dioxins and heavy metals; different pollutants may offset each other by equivalence factors","Only SOx and NOx; the volumes may be offset across sources belonging to different premises to widen the benefit","Only VOCs and CO; the volumes before and after offsetting may use different calculation methods"],
 "Article 2 lists the pollutants and bars cross-pollutant offsetting."),

(D,"第3條",2,"排放抵換-空品模擬",
 "公私場所申請改善排放總量及濃度時，空氣品質模式模擬應符合何項要求？",
 ["應依中央主管機關公告或認可之模擬規範，證明各受體點各時段平均濃度低於抵換前，且前後應以相同模式及輸入參數為之","應依公私場所自行選定之國際模式，證明廠區內平均濃度低於抵換前，且前後得使用不同模式以取得較佳結果","應依地方主管機關指定之模式，證明廠界最大落地濃度不超過排放標準，模擬範圍以廠區周界內為限","應依中央主管機關公告之模擬規範，證明年平均濃度低於環境背景值，模擬得僅就抵換後之情境辦理"],"a",
 "第3條：應依中央主管機關公告或認可之空氣品質模式模擬規範進行模擬，證明模擬範圍內各受體點或軌跡線或網格之各時段平均空氣污染物濃度低於抵換前之各時段平均濃度；且排放抵換前後之模擬應以相同空氣品質模式及輸入參數為之。",
 "What are the air quality modelling requirements for such an application?",
 ["Use the announced modelling protocol, show each receptor period average below pre-offset levels, same model and inputs before and after","Use any international model chosen by the premises, show plant-wide averages lower, and different models may be used before and after","Use the model designated by the local authority, show fence-line maximum ground level within the limit, modelling confined to the site","Use the announced protocol, show annual averages below ambient background, and model only the post-offset scenario"],
 "Article 3: same model and inputs, all period averages must fall."),

(D,"第4條",3,"排放抵換-抵換量認定",
 "固定污染源所減少之排放量，何者得作為排放抵換量？",
 ["因改用低污染性原（物）料或燃料、製程改善、增設防制設備或提升防制效率所減少者","因操作時程改變或縮短年度操作小時數所減少者，並經地方主管機關備查即可認列","因停止操作、停工或停業所減少者，得依停工期間長短按比例折算為抵換量","因產品訂單減少致產量下降所減少者，得檢具銷貨憑證申請認列為抵換量"],"a",
 "第4條：因改用低污染性原（物）料或燃料、製程改善、增設防制設備或提升防制效率致排放量減少者，其減少量得作為排放抵換量；因操作時程改變、停止操作、停工或停業所減少之排放量，不得作為排放抵換量。",
 "Which emission reductions may count as offset credits?",
 ["Those from switching to cleaner materials or fuels, process improvement, added controls or higher control efficiency","Those from changing operating schedules or shortening annual operating hours, once filed with the local authority","Those from ceasing operation, shutdown or business closure, prorated according to the length of the shutdown","Those from lower output due to reduced product orders, supported by sales vouchers as evidence"],
 "Article 4: only genuine technical reductions qualify."),

(D,"第5條",2,"排放抵換-申請文件",
 "公私場所向地方主管機關申請改善排放總量及濃度，應檢具之文件為何？",
 ["目的事業主管機關核准登記或核准營運之證明文件影本，及空氣污染物總量及濃度排放改善計畫","公司變更登記表及全體股東名冊，並附具最近三年之營利事業所得稅結算申報書影本","環境影響說明書審查結論及開發許可文件，並附具當地居民同意書及公聽會紀錄","空氣污染防制費繳納證明及排放量申報回執，並附具全廠員工安全衛生教育訓練紀錄"],"a",
 "第5條第1項：應填具申請表並檢具目的事業主管機關核准登記或核准營運之相關證明文件影本，及空氣污染物總量及濃度排放改善計畫。第2項並詳列改善計畫應包括計畫目標、周界外二公里範圍環境座落圖說、污染源資料及模擬結果等事項。",
 "What documents must accompany an application to the local authority?",
 ["A copy of the registration or operating approval from the industry authority, and an emission improvement plan","The company amendment registration form and shareholder roster, plus income tax returns for the past three years","The EIA review conclusion and development permit, plus local resident consent forms and public hearing records","Air pollution fee receipts and emission report acknowledgements, plus employee safety training records"],
 "Article 5, Paragraph 1 lists the two required documents."),

(D,"第5條",3,"排放抵換-改善計畫內容",
 "空氣污染物總量及濃度排放改善計畫之內容，下列何者非屬應包括事項？",
 ["公私場所全體從業人員名冊及其勞工保險投保級距明細資料","污染源廠場周界外二公里範圍內之環境座落圖說及設施平面配置圖說","固定污染源申請前一年監（檢）測紀錄、操作紀錄及排放量資料","排放抵換前、後空氣品質模式模擬結果及防制設施改善經費與進度"],"a",
 "第5條第2項：改善計畫應包括計畫目標、周界外二公里範圍環境座落圖說及廠場設施平面配置圖說、污染源範圍與抵換量分配原則、抵換前後製程流程、原（物）料燃料種類成分用量、產品種類生產量、防制設施種類效能、申請前一年監（檢）測與排放量資料、排放管道口徑高度座標、模擬結果、改善經費及進度等。",
 "Which item is NOT required in the improvement plan?",
 ["A roster of all employees with their labour insurance contribution brackets","A site location map and facility layout covering two kilometres outside the plant boundary","Monitoring, operating and emission records for the year before the application","Modelling results before and after offsetting, plus control equipment costs and schedule"],
 "Article 5, Paragraph 2 lists the plan contents; staff rosters are not among them."),

(D,"第6條",3,"排放抵換-審查期限",
 "地方主管機關受理改善排放總量及濃度申請後之審查期限規定為何？",
 ["受理後三十日內完成書面審查；收到改善完成證明文件後十五日內完成審查並發給核准證明","受理後六十日內完成書面審查；收到改善完成證明文件後三十日內完成審查並發給核准證明","受理後十五日內完成書面審查；收到改善完成證明文件後四十五日內完成審查並發給核准證明","受理後九十日內完成書面審查；收到改善完成證明文件後七日內完成審查並發給核准證明"],"a",
 "第6條第1項、第2項：地方主管機關應於受理後三十日內完成書面審查；審查符合者依核准計畫改善，改善完成後提報排放檢測報告等文件，主管機關應於收到後十五日內完成審查，通過者發給核准證明。第4項並規定總補正日數不得超過九十日。",
 "What review time limits apply after the application is accepted?",
 ["Thirty days for the written review; fifteen days to review completion documents and issue the approval certificate","Sixty days for the written review; thirty days to review completion documents and issue the approval certificate","Fifteen days for the written review; forty-five days to review completion documents and issue the certificate","Ninety days for the written review; seven days to review completion documents and issue the certificate"],
 "Article 6: thirty days and fifteen days respectively."),

(D,"第6條",2,"排放抵換-展延與補正",
 "公私場所未能於改善計畫期限內完成改善，或申請文件經審查不合規定者，應如何處理？",
 ["得於期限屆滿十日前申請延長由主管機關核定期限；文件不合規定者通知限期補正，總補正日數不得超過九十日","得於期限屆滿後三十日內補行申請延長；文件不合規定者應逕予駁回申請，不得再行補正或重新提出","得於期限屆滿十日前申請延長且延長以三次為限；文件不合規定者通知限期補正，總補正日數不得超過三十日","得隨時申請延長且不受任何期限拘束；文件不合規定者由主管機關逕行代為補正並計入審查期間"],"a",
 "第6條第3項、第4項：未能於改善計畫期限內完成改善者，得於期限屆滿十日前向主管機關申請延長，主管機關應依實際狀況核定改善期限；申請文件、檢測報告或證明文件經審查不合規定者，通知限期補正，屆期未補正者駁回申請，各次補正日數不算入審查期間，總補正日數不得超過九十日。",
 "How are missed improvement deadlines and defective documents handled?",
 ["Apply for extension ten days before expiry for the authority to set a new deadline; defects corrected within ninety days total","Apply for extension within thirty days after expiry; defective documents are rejected outright without any correction","Apply ten days before expiry with at most three extensions; defects corrected within thirty days in total","Apply for extension at any time without limit; the authority corrects defects itself within the review period"],
 "Article 6, Paragraphs 3-4 on extension and correction."),

(D,"第7條",2,"排放抵換-合併申請",
 "公私場所申請改善排放總量及濃度，與固定污染源設置或操作許可證之關係為何？",
 ["得與設置或操作許可證合併提出申請，依許可證管理辦法辦理且審查期間得延長三十日","不得與設置或操作許可證合併申請，應於取得核准證明後始得另行申請許可證異動","應強制與設置或操作許可證合併申請，其審查期間應縮短為原定期間之二分之一","得與設置或操作許可證合併申請，惟相同之文件資料仍應分別重複提報以利分案審查"],"a",
 "第7條：申請改善排放總量及濃度得與固定污染源設置或操作許可證合併提出申請；主管機關受理合併申請案件應依固定污染源設置與操作許可證管理辦法規定辦理，其審查期間得延長三十日；合併申請應檢附之文件或資料相同者，得不重複提報。",
 "How does this application relate to installation or operating permits?",
 ["It may be filed jointly with the permit, handled under the permit regulations with review extended by thirty days","It may not be filed jointly; the permit change may only be sought after the approval certificate is issued","It must be filed jointly with the permit, and the review period is shortened to half its normal length","It may be filed jointly, but identical documents must still be submitted twice for separate case handling"],
 "Article 7: joint filing allowed, thirty-day extension, no duplicate documents."),

(D,"第8條",3,"排放抵換-核准證明",
 "改善排放空氣污染物總量及濃度核准證明之記載事項及有效期間為何？",
 ["記載有效期間字號、基本資料及核准內容等；有效期間五年，期滿續用應於屆滿前申請展延，每次不得超過五年","記載有效期間字號、基本資料及核准內容等；有效期間三年，期滿續用應於屆滿前申請展延，每次不得超過三年","僅記載污染物排放種類及年排放量限值；有效期間十年，期滿即自動失效不得申請任何展延","僅記載公私場所名稱及負責人資料；有效期間永久有效，除撤銷或廢止外不因期間經過而失效"],"a",
 "第8條：核准證明應記載有效期間及字號、基本資料（名稱住址、負責人姓名身分證明文件字號及住所）與核准內容（污染源範圍名稱位置、污染改善措施、排放種類與年排放量及濃度限值、操作條件、監檢測項目及頻率等）；有效期間為五年，期滿仍繼續使用者應於屆滿前提出展延申請，每次展延不得超過五年。",
 "What must the approval certificate state, and how long is it valid?",
 ["Validity and number, basic data and approved contents; valid five years, renewable before expiry for up to five years each time","Validity and number, basic data and approved contents; valid three years, renewable before expiry for up to three years each time","Only pollutant types and annual emission limits; valid ten years and automatically void with no renewal allowed","Only the premises name and responsible person data; valid indefinitely unless revoked or annulled by the authority"],
 "Article 8: five-year validity, renewals of up to five years."),

(D,"第9條",2,"排放抵換-遵行與申報",
 "取得核准證明之公私場所，其排放標準之適用及申報保存義務為何？",
 ["以核准之總量及濃度為排放標準並依核准內容操作；應於每年二月底前提報前一年資料並保存二年","以原公告排放標準為準，核准內容僅供參考；應於每年六月底前提報前一年資料並保存五年","以核准之總量及濃度為排放標準；應於每季結束後十五日內提報監測資料並保存十年備查","以核准之總量及濃度為排放標準；資料僅需於主管機關查核時提供，無須定期提報亦無保存年限"],"a",
 "第9條：公私場所應以主管機關核准之空氣污染物總量及濃度為其排放標準，並依核准內容進行各該固定污染源之操作及排放；應於每年二月底前向主管機關提報前一年排放總量及濃度相關監（檢）測及操作紀錄資料，並應保存二年。",
 "What emission standard applies and what reporting duty follows approval?",
 ["The approved total volume and concentration are the standard; report the previous year by end of February and keep records two years","The originally published standard still applies; report the previous year by end of June and keep records for five years","The approved values are the standard; report monitoring data within fifteen days after each quarter and keep records ten years","The approved values are the standard; data need only be produced on inspection, with no periodic report or retention period"],
 "Article 9: approved values are the standard; February reporting, two-year retention."),

(D,"第10條",2,"排放抵換-換發補發",
 "核准證明毀損、滅失或記載基本資料異動者，公私場所應如何辦理？",
 ["得於事實發生後六十日內檢具證明文件申請換發或補發；未辦理者應於主管機關通知後十日內申請","得於事實發生後三十日內檢具證明文件申請換發或補發；未辦理者應於主管機關通知後三日內申請","應於事實發生後九十日內檢具證明文件申請換發或補發；未辦理者由主管機關逕予註銷核准證明","應於事實發生前三十日檢具證明文件申請換發或補發；未辦理者應重新依第五條規定提出申請"],"a",
 "第10條：核准證明因毀損、滅失或其記載之基本資料有異動者，公私場所得於事實發生後六十日內檢具證明文件，向當地主管機關申請換發或補發；未依規定辦理時，應於主管機關通知後十日內申請換發或補發。違反者依第13條依本法第62條第1項第7款辦理。",
 "How must a damaged, lost or outdated approval certificate be handled?",
 ["Apply for replacement within sixty days of the event; if not, apply within ten days of the authority notice","Apply for replacement within thirty days of the event; if not, apply within three days of the authority notice","Apply for replacement within ninety days of the event; if not, the authority cancels the certificate directly","Apply for replacement thirty days before the event; if not, reapply entirely under Article 5 procedures"],
 "Article 10: sixty days, or ten days after notice."),

(D,"第11條",2,"排放抵換-變更",
 "核准證明之核准內容有變更或據以審核之標準有變更者，公私場所應如何辦理？",
 ["應於變更前重新提出申請，並依第五條、第六條及第八條規定辦理","應於變更後三十日內報請備查，無須重新提出申請亦不需重新審查","應俟核准證明有效期間屆滿後，再併同展延申請一併辦理變更事項","應由主管機關逕行註銷原核准證明，公私場所不得再申請新核准證明"],"a",
 "第11條：核准證明之核准內容有變更或據以審核之標準有變更者，公私場所應於變更前重新提出申請，並依第5條（申請文件）、第6條（審查程序）及第8條（核准證明記載與有效期間）規定辦理。",
 "What must be done when approved contents or the underlying standards change?",
 ["Reapply before the change, following the procedures in Articles 5, 6 and 8","File for record within thirty days after the change, with no new application needed","Wait until the certificate expires and handle the change with the renewal application","The authority cancels the certificate and no new application may ever be made"],
 "Article 11: reapply before the change under Articles 5, 6 and 8."),

(D,"第12條",1,"排放抵換-撤銷",
 "公私場所申請核准證明所檢具之文件有虛偽不實者，主管機關得為何種處置？",
 ["得撤銷其核准證明","得處以停工六個月處分","得逕行沒入其防制設備","得命其重新繳納審查費用"],"a",
 "第12條：公私場所申請核准證明所檢具之文件有虛偽不實者，主管機關得撤銷其核准證明。撤銷後該場所即失其以核准總量及濃度為排放標準之依據，應回復適用一般排放標準。",
 "What may the authority do if the application documents are false?",
 ["Revoke the approval certificate","Order a six-month shutdown","Confiscate the control equipment","Order the review fee to be paid again"],
 "Article 12: false documents allow revocation of the certificate."),

(D,"第13條",3,"排放抵換-罰則",
 "公私場所違反第九條或第十條第二項規定者，主管機關應如何處理？",
 ["依本法第六十二條第一項第七款規定辦理；具本法第九十六條第一項第二款至第七款情形者，並得令停工停業及廢止核准證明","依本法第五十九條規定按次處罰；具本法第九十六條情形者，僅得命限期改善而不得廢止其核准證明","依本法第八十條規定移送司法機關偵辦；並應同時撤銷該公私場所之固定污染源設置及操作許可證","依本法第六十二條第一項第七款規定辦理；並應一律逕行廢止其核准證明，不再審酌違規情節輕重"],"a",
 "第13條：公私場所違反第9條（依核准內容操作及提報保存資料）或第10條第2項（經通知後十日內申請換補發）規定者，主管機關依本法第62條第1項第7款規定辦理；具有本法第96條第1項第2款至第7款情形之一者，主管機關除得令其停工或停業外，並得廢止其核准證明。",
 "How are violations of Article 9 or Article 10, Paragraph 2 handled?",
 ["Under Article 62-1(7) of the Act; where Article 96-1(2) to (7) applies, shutdown and revocation of the certificate may follow","Under Article 59 with penalties each time; where Article 96 applies, only an improvement order may issue, never revocation","Referred to judicial authorities under Article 80; the installation and operating permits must also be revoked at the same time","Under Article 62-1(7); the certificate must always be revoked regardless of the seriousness of the violation"],
 "Article 13 cross-refers to Articles 62 and 96 of the APCA."),

(D,"第14條",1,"排放抵換-施行",
 "公私場所固定污染源申請改善排放空氣污染物總量及濃度管理辦法之施行日期為何？",
 ["自發布日施行","自發布後三個月施行","自發布後一年施行","另定施行日期並公告之"],"a",
 "第14條：本辦法自發布日施行。屬形式規定，無緩衝期間，發布當日即生效力。",
 "When does this regulation take effect?",
 ["On the date of promulgation","Three months after promulgation","One year after promulgation","On a separately announced date"],
 "Article 14: effective upon promulgation."),

# ===== ENV-102 空氣污染物排放量申報管理辦法（14 條）=====
(E,"第1條",1,"排放量申報-授權",
 "公私場所固定污染源空氣污染物排放量申報管理辦法係依何規定訂定？",
 ["空氣污染防制法第二十一條第二項","空氣污染防制法第二十七條第三項","空氣污染防制法第二十二條第四項","空氣污染防制法第二十四條第五項"],"a",
 "第1條：本辦法依空氣污染防制法第二十一條第二項規定訂定之。該條課予公私場所定期申報固定污染源空氣污染物排放量之義務，本辦法第3條並定明按季申報之期限。",
 "Under which provision is this emission reporting regulation issued?",
 ["Article 21, Paragraph 2 of the Air Pollution Control Act","Article 27, Paragraph 3 of the Air Pollution Control Act","Article 22, Paragraph 4 of the Air Pollution Control Act","Article 24, Paragraph 5 of the Air Pollution Control Act"],
 "Article 1: issued under Article 21-2 of the APCA."),

(E,"第2條",2,"排放量申報-污染物種類",
 "公私場所應申報固定污染源排放量之空氣污染物種類，包括下列何者？",
 ["粒狀污染物、硫氧化物、氮氧化物、揮發性有機物、甲苯二甲苯等指定物質及其他經指定者","粒狀污染物、戴奧辛、重金屬、惡臭物質及其他經直轄市主管機關逐案指定之空氣污染物","硫氧化物、氮氧化物、二氧化碳、甲烷、氧化亞氮等溫室氣體及其他經中央指定之物質","揮發性有機物、臭氧、光化學氧化物、落塵及其他經目的事業主管機關指定之空氣污染物"],"a",
 "第2條：應申報之空氣污染物種類為粒狀污染物、硫氧化物、氮氧化物、揮發性有機物，以及甲苯、二甲苯、苯、乙苯、苯乙烯、二氯甲烷、二氯乙烷、三氯甲烷、三氯乙烷、四氯化碳、三氯乙烯、四氯乙烯等指定物質，及其他經中央主管機關指定之空氣污染物。",
 "Which pollutants must be reported for stationary sources?",
 ["Particulates, SOx, NOx, VOCs, listed substances such as toluene and xylene, and other designated items","Particulates, dioxins, heavy metals, odorous substances and items designated case by case by the municipality","SOx, NOx, carbon dioxide, methane, nitrous oxide and other greenhouse gases designated centrally","VOCs, ozone, photochemical oxidants, dustfall and items designated by the industry authority"],
 "Article 2 lists the reportable pollutant categories."),

(E,"第3條",3,"排放量申報-申報期限",
 "公私場所申報固定污染源空氣污染物排放量之方式與期限為何？",
 ["依中央主管機關所定格式以網路傳輸，按季於每年一、四、七、十月底前向地方主管機關申報前一季排放量","依中央主管機關所定格式以書面郵寄，按半年於每年一月及七月底前向中央主管機關申報前半年排放量","依地方主管機關自訂格式以網路傳輸，按月於次月十五日前向地方主管機關申報前一個月之排放量","依中央主管機關所定格式以網路傳輸，按年於每年三月底前向中央主管機關申報前一年度之排放量"],"a",
 "第3條第1項：公私場所應依中央主管機關所定格式，以網路傳輸方法，按季於每年一月、四月、七月及十月底前向直轄市、縣（市）主管機關申報全廠（場）之固定污染源前一季空氣污染物排放量。違反者依第13條依本法第62條第1項第2款辦理。",
 "How and when must stationary source emissions be reported?",
 ["In the central format by internet transmission, quarterly by the end of January, April, July and October to the local authority","In the central format by post, half-yearly by the end of January and July to the central authority for the past half year","In a locally set format by internet, monthly by the fifteenth of the next month to the local authority","In the central format by internet, annually by the end of March to the central authority for the previous year"],
 "Article 3, Paragraph 1: quarterly internet reporting to the local authority."),

(E,"第3條",2,"排放量申報-排放量範圍",
 "本辦法所稱應申報之空氣污染物排放量，其範圍包括何者？",
 ["固定污染源正常運作之排放，及因設備故障、維護不當人為疏失或經認定之災害等致大量排放者","僅限固定污染源正常運作之排放，設備故障或人為疏失所致之大量排放不列入申報範圍","僅限經連續自動監測設施記錄之排放，未設監測設施之污染源排放一律免予列入申報","僅限超過排放標準之異常排放，符合排放標準之正常運作排放無須列入申報之範圍"],"a",
 "第3條第2項：排放量指固定污染源正常運作排放空氣污染物，及具有下列情形致大量排放者：設計不良或操作不當導致設備故障、維護不當或人為疏失、非屬前兩款所引起災害導致大量排放或其他經直轄市、縣（市）主管機關認定之情形。",
 "What is included in the emissions that must be reported?",
 ["Normal operating emissions plus large releases from equipment failure, poor maintenance, human error or recognised incidents","Only normal operating emissions; large releases from equipment failure or human error are excluded from reporting","Only emissions recorded by continuous automatic monitors; sources without monitors are entirely exempt from reporting","Only abnormal emissions above the standard; emissions complying with the standard need not be reported at all"],
 "Article 3, Paragraph 2 defines the scope of reportable emissions."),

(E,"第4條",3,"排放量申報-申報內容",
 "公私場所固定污染源應申報之排放量內容，不包括下列何者？",
 ["公私場所歷年繳納空氣污染防制費之金額及繳費收據影本明細","空氣污染物種類、成分及其排放量與排放量計算方法","原（物）料與燃料之種類、用量、揮發性有機物含量及含硫量百分比","與揮發性有機物排放有關之原料回收量、廢水量、廢溶劑量及廢棄物量"],"a",
 "第4條第1項：應申報內容為空氣污染物種類、成分及排放量；排放量計算方法；與排放量有關之參數說明（原物料燃料種類用量與 VOC 含量及含硫量、產品種類生產量、非生產製程有機溶劑用量、與 VOC 排放有關之回收量廢水廢溶劑廢棄物量等）。防制費繳納金額非申報內容。",
 "Which item is NOT part of the required reporting contents?",
 ["The amounts of air pollution control fees paid over the years and copies of the receipts","Pollutant types, composition and emission volumes and the calculation methods used","Types, quantities, VOC content and sulphur percentage of raw materials and fuels","Recovered material, wastewater, waste solvent and waste volumes related to VOC emissions"],
 "Article 4, Paragraph 1 lists the reporting contents; fee payment data is not one."),

(E,"第4條",2,"排放量申報-補正",
 "申報內容有欠缺或不合規定者，地方主管機關應如何處理？補正日數有何限制？",
 ["應通知限期補正，補正日數不計入審查期間，總補正日數不得超過六十日，屆期未補正者駁回並通知重新申報","應通知限期補正，補正日數計入審查期間，總補正日數不得超過九十日，屆期未補正者視為已完成申報","應逕行駁回其申報資料並移送裁處，不得給予任何補正機會，公私場所須於次季重新申報","應由主管機關代為補正並收取代辦費用，補正日數不計入審查期間且次數與日數均不受限制"],"a",
 "第4條第2項：申報內容有欠缺或不合規定者，直轄市、縣（市）主管機關應通知公私場所限期補正，補正日數不計入審查期間內，其補正總日數不得超過六十日，屆期未補正者，駁回其申報資料，並通知其重新申報。",
 "How are defective reports handled and what limits apply to corrections?",
 ["Notice to correct within a period; days excluded from review; sixty days total; otherwise rejected and re-reporting ordered","Notice to correct within a period; days counted in review; ninety days total; otherwise the report is deemed complete","Immediate rejection and referral for penalty with no chance to correct; the premises must re-report next quarter","The authority corrects it for a fee, with the days excluded from review and no limit on times or days"],
 "Article 4, Paragraph 2: sixty-day total correction limit."),

(E,"第5條",3,"排放量申報-計算依據",
 "公私場所申報排放量時，其計算依據之優先順序為何？",
 ["連續自動監測資料優先，其次為公告檢測方法之檢測結果，再次為經認可之自廠係數，其後為公告排放係數等","公告排放係數優先，其次為經認可之自廠係數，再次為連續自動監測資料，最後為公告檢測方法檢測結果","國內外技術論文與測試數據優先，其次為排放量計算手冊之試算方式，最後為連續自動監測資料","公私場所得於各種計算依據中自由選擇任一種辦理，法無優先順序之限制亦無須報請同意"],"a",
 "第5條第1項：計算依據順序為連續自動監測設施監測資料、公告檢測方法所測之檢測結果、經認可之揮發性有機物自廠係數、中央公告之排放係數控制效率質量平衡計量方式、排放量計算手冊試算方式或其他認可替代方式、經認可之國內外技術論文與測試數據。",
 "What is the order of priority for calculating reported emissions?",
 ["Continuous monitoring data first, then results by announced test methods, then approved in-house factors, then published factors","Published emission factors first, then approved in-house factors, then continuous monitoring data, then test method results","Domestic and foreign technical papers first, then the calculation manual estimates, and continuous monitoring data last","The premises may freely choose any basis, since no order of priority or prior consent is required by law"],
 "Article 5, Paragraph 1 sets the six-tier priority order."),

(E,"第5條",3,"排放量申報-VOC計算",
 "公私場所申報固定污染源揮發性有機物排放量者，應如何計算？",
 ["原則應以自廠係數、公告排放係數或計算手冊試算方式計算；採密閉集氣至排放管道者，報經同意後得以監測或檢測結果計算","原則應以連續自動監測資料計算；未設監測設施者，得逕以歷史檢測資料推估而無須報請主管機關同意","應一律以質量平衡計量方式計算，不得採用排放係數或自廠係數，亦不得以檢測結果替代計算","應由公私場所於各期申報時自行選定計算方式，並得於同一年度內隨時變更計算方式而免予報備"],"a",
 "第5條第2項：申報揮發性有機物排放量者，應以第1項第3款至第5款（自廠係數、公告排放係數、計算手冊試算方式）計算；但固定污染源採密閉集氣系統收集揮發性有機物至排放管道者，應檢具相關資料報經直轄市、縣（市）主管機關同意後，得以第1款或第2款計算。",
 "How must VOC emissions be calculated for reporting?",
 ["Normally by in-house factors, published factors or manual estimates; with closed capture, monitoring data on approval","Normally by continuous monitoring data; without monitors, historical test data may be used with no need for approval","Always by mass balance calculation, with emission factors, in-house factors and test results all excluded","Chosen freely by the premises at each report, and changeable at any time within the year without notification"],
 "Article 5, Paragraph 2 restricts VOC calculation methods."),

(E,"第6條",2,"排放量申報-未申報處理",
 "公私場所固定污染源未申報空氣污染物排放量者，地方主管機關得如何處理？",
 ["得逕依原（物）料使用量、燃料購買量、產品產量、歷史檢測資料或其他有關資料計算其排放量","應俟公私場所自行補行申報後始得計算排放量，主管機關不得逕依其他資料代為計算","應逕依該行業別全國平均排放量之二倍推計其排放量，並據以核算應繳之空氣污染防制費","應先命其停工並俟完成檢測後，始得依實測結果認定該公私場所之空氣污染物排放量"],"a",
 "第6條：公私場所固定污染源未申報空氣污染物排放量者，直轄市、縣（市）主管機關得逕依原（物）料使用量、燃料購買量、產品產量、歷史檢測資料或其他有關資料，計算其空氣污染物排放量。違反申報義務另依第13條規定辦理。",
 "What may the local authority do if a source fails to report its emissions?",
 ["Calculate emissions directly from material use, fuel purchases, output, historical test data or other relevant data","Wait until the premises files a late report, since the authority may not calculate the emissions on its own","Estimate emissions at twice the national industry average and assess the air pollution control fee accordingly","Order a shutdown first and determine the emissions only from measured results after testing is complete"],
 "Article 6: the authority may calculate emissions from available data."),

(E,"第7條",3,"排放量申報-差異處理",
 "以排放係數計算揮發性有機物排放量者，申報季排放量與主管機關查核結果差異達何程度時應改變計算方式？",
 ["差異達二倍以上及七．五公噸以上時，應自收到通知之次季起改以質量平衡計量方式計算","差異達一．五倍以上及五公噸以上時，應自收到通知之當季起改以連續自動監測資料計算","差異達三倍以上及十公噸以上時，應自次一年度起改以公告排放係數重新計算並補報","差異達二倍以上及七．五公噸以上時，應自收到通知之次年起改以自廠係數方式計算"],"a",
 "第7條：公私場所選擇以排放係數計算揮發性有機物排放量者，其申報之季排放量與直轄市、縣（市）主管機關查核結果差異達二倍以上及七．五公噸以上時，應於收到通知文件之次季起，以質量平衡計量方式計算該固定污染源之空氣污染物排放量。",
 "When must a source switch calculation methods due to discrepancy?",
 ["When the gap reaches two times and 7.5 tonnes, switch to mass balance from the quarter after the notice","When the gap reaches 1.5 times and 5 tonnes, switch to continuous monitoring data from the same quarter","When the gap reaches three times and 10 tonnes, recalculate with published factors from the next year","When the gap reaches two times and 7.5 tonnes, switch to in-house factors from the year after the notice"],
 "Article 7: two times and 7.5 tonnes triggers mass balance."),

(E,"第8條",3,"排放量申報-優先查核",
 "下列何者非屬地方主管機關應優先查核申報內容之情形？",
 ["同一固定污染源之操作許可證有效期間即將於六個月內屆滿而尚未申請展延者","同一固定污染源申報任一污染物年排放量高於許可證登載年許可排放量百分之十以上者","同一固定污染源申報任一污染物年排放量低於許可證登載年許可排放量百分之五十以下者","同一固定污染源任一污染物季排放量與前一年同季排放量差異達百分之二十以上者"],"a",
 "第8條第1項列舉優先查核情形：年排放量高於年許可排放量百分之十以上、低於百分之五十以下、申報種類或污染源資料與管制資料不符、季排放量與前一年同季差異達百分之二十以上、其他經認有疑義者。許可證即將屆期並非優先查核事由。",
 "Which is NOT a ground for priority audit of a reported emission return?",
 ["The operating permit of the source is due to expire within six months and no renewal has been sought","The reported annual volume exceeds the permitted annual volume on the permit by more than ten per cent","The reported annual volume falls below fifty per cent of the permitted annual volume on the permit","The quarterly volume differs from the same quarter of last year by twenty per cent or more"],
 "Article 8, Paragraph 1 lists the priority audit triggers."),

(E,"第9條",2,"排放量申報-查核資料",
 "地方主管機關為執行排放量查核作業，得限期公私場所提報之資料不包括下列何者？",
 ["公私場所全體員工之勞動契約、薪資清冊及出勤差假紀錄等人事管理資料","原（物）料與燃料購買憑證、成分含量證明文件及使用量、產品產量紀錄月報表","防制設備現場操作紀錄報表、耗材購買憑證及用量紀錄報表與廢棄物聯單資料","連續自動監測設施監測紀錄月報表、品保品管紀錄及排放管道檢測報告書影本"],"a",
 "第9條列舉得限期提報之資料共八款，包括原物料燃料購買憑證與成分證明、防制設備操作與耗材紀錄、VOC 相關回收廢水廢溶劑資料、連續自動監測紀錄與品保品管、排放管道檢測報告、進銷存憑證帳冊、大量排放情形相關資料及其他指定文件。人事薪資資料不在其中。",
 "Which data may the authority NOT require for an emission audit?",
 ["Employment contracts, payroll registers and attendance records of all staff at the premises","Purchase vouchers and composition certificates for materials and fuels, plus usage and output monthly reports","Control equipment operating reports, consumable purchase vouchers and usage reports, and waste manifest data","Continuous monitoring monthly reports, QA/QC records and copies of stack testing reports"],
 "Article 9 lists eight categories of auditable data; HR records are not among them."),

(E,"第10條",3,"排放量申報-計量紀錄",
 "經中央主管機關指定公告應申報季排放量之固定污染源，其計量及記錄頻率規定為何？",
 ["應每日計量及記錄；以質量平衡推估揮發性有機物者得每批計量記錄，且每季至少計量及記錄一次","應每月計量及記錄；以質量平衡推估揮發性有機物者得每季計量記錄，且每年至少計量記錄二次","應每小時計量及記錄；以質量平衡推估揮發性有機物者得每日計量記錄，且每月至少記錄一次","應每季計量及記錄；以質量平衡推估揮發性有機物者得每年計量記錄一次，並免報請主管機關同意"],"a",
 "第10條第1項：經指定公告應申報季排放量之固定污染源，應每日計量及記錄依第9條應提報之相關紀錄報表；但以質量平衡計量方式推估揮發性有機物排放量者，得每批計量及記錄回收量、廢水量、廢溶劑量、廢棄物量與產品產量等項目，且每季至少計量及記錄一次。第2項並允許報經同意後改變記錄項目或頻率。",
 "What measurement and recording frequency applies to designated sources?",
 ["Daily measurement and recording; mass balance VOC estimation may be per batch with at least one record each quarter","Monthly measurement and recording; mass balance VOC estimation may be quarterly with at least two records each year","Hourly measurement and recording; mass balance VOC estimation may be daily with at least one record each month","Quarterly measurement and recording; mass balance VOC estimation may be annual, with no approval needed at all"],
 "Article 10, Paragraph 1: daily records, per-batch option for mass balance."),

(E,"第11條",1,"排放量申報-格式",
 "本辦法所定之相關格式，應由何機關定之？",
 ["中央主管機關","直轄市、縣（市）主管機關","目的事業主管機關","受託之檢驗測定機構"],"a",
 "第11條：本辦法所定之相關格式，由中央主管機關定之。與第3條第1項要求依中央主管機關所定格式以網路傳輸申報之規定相互配合，以維持全國申報格式之一致。",
 "Which authority prescribes the forms used under this regulation?",
 ["The central competent authority","The municipal or county authority","The relevant industry authority","The commissioned testing agency"],
 "Article 11: the central competent authority prescribes the forms."),

(E,"第12條",2,"排放量申報-保存年限",
 "依規定申報之排放量資料及依規定記錄之資料，公私場所應保存多久備查？",
 ["應妥善保存六年備查","應妥善保存二年備查","應妥善保存三年備查","應妥善保存十年備查"],"a",
 "第12條：依第4條申報排放量之資料及依第10條記錄之資料，公私場所應妥善保存六年備查。違反本條規定者，依第13條第4款依本法第62條第1項第2款規定辦理。",
 "How long must reported and recorded emission data be kept?",
 ["Kept properly for six years for inspection","Kept properly for two years for inspection","Kept properly for three years for inspection","Kept properly for ten years for inspection"],
 "Article 12: six-year retention."),

(E,"第13條",3,"排放量申報-罰則",
 "下列何者非屬依本法第六十二條第一項第二款規定辦理之情形？",
 ["公私場所因不可抗力之天災致延誤申報，並於災害結束後已補行申報者","違反按季於一、四、七、十月底前申報前一季排放量之規定者","申報排放量低於查核應申報量百分之七十以下，且應申報年排放量達一公噸以上者","未依規定提報查核資料，或違反每日計量記錄及資料保存六年之規定者"],"a",
 "第13條列舉四款情形依本法第62條第1項第2款辦理：違反第3條第1項申報規定；申報量低於查核應申報量百分之七十以下且年排放量達一公噸以上；未依第9條提報資料；違反第10條或第12條規定。因天災延誤並已補報者不在列舉之中。",
 "Which is NOT a situation handled under Article 62-1(2) of the Act?",
 ["Delay caused by an irresistible natural disaster where the report was filed after the disaster ended","Failing to file the quarterly report by the end of January, April, July or October","Reporting below seventy per cent of the audited volume where the annual volume reaches one tonne","Failing to submit audit data, or breaching the daily recording or six-year retention rules"],
 "Article 13 lists four grounds; force majeure with late filing is not one."),

(E,"第14條",1,"排放量申報-施行",
 "公私場所固定污染源空氣污染物排放量申報管理辦法之施行日期為何？",
 ["自發布日施行","自發布後六個月施行","自發布後一年施行","另定施行日期並公告之"],"a",
 "第14條：本辦法自發布日施行。屬形式規定，無緩衝期間，發布當日即生效力。",
 "When does this reporting regulation take effect?",
 ["On the date of promulgation","Six months after promulgation","One year after promulgation","On a separately announced date"],
 "Article 14: effective upon promulgation."),

# ===== ENV-103 復工試車評鑑及管理辦法（17 條）=====
(F,"第1條",1,"復工試車-授權",
 "公私場所固定污染源復工試車評鑑及管理辦法係依何規定訂定？",
 ["空氣污染防制法第九十七條第二項","空氣污染防制法第八十六條第三項","空氣污染防制法第六十七條第二項","空氣污染防制法第五十九條第四項"],"a",
 "第1條：本辦法依空氣污染防制法第九十七條第二項規定訂定之。該條授權訂定經令停工停業之公私場所，其恢復操作或復工前之試車申請、評鑑及管理程序。",
 "Under which provision is this trial run regulation issued?",
 ["Article 97, Paragraph 2 of the Air Pollution Control Act","Article 86, Paragraph 3 of the Air Pollution Control Act","Article 67, Paragraph 2 of the Air Pollution Control Act","Article 59, Paragraph 4 of the Air Pollution Control Act"],
 "Article 1: issued under Article 97-2 of the APCA."),

(F,"第2條",2,"復工試車-適用對象",
 "本辦法之適用對象為何種公私場所？",
 ["經地方主管機關依本法所定條文令停止污染源操作、停工（業）者，或經通知限期改善而自報停工（業）者","僅限經中央主管機關令停工者，地方主管機關所為之停工處分不適用本辦法之試車評鑑程序","僅限新設固定污染源尚未取得操作許可證而擬進行試車者，既有污染源之復工不適用本辦法","僅限經法院裁定假處分停止營運之公私場所，行政處分所致之停工不適用本辦法之規定"],"a",
 "第2條：適用對象為經直轄市、縣（市）主管機關依本法第59條、第61條、第62條第1項、第64條、第65條第1項、第67條第2項或第68條令停止污染源之操作、停工（業）者；及經地方主管機關通知限期改善而自報停工（業）者。",
 "To which premises does this regulation apply?",
 ["Those ordered by the local authority to halt or shut down under the Act, and those self-reporting shutdown after a notice","Only those ordered to shut down by the central authority; local shutdown orders fall outside this trial run procedure","Only new sources without an operating permit wishing to run trials; restarting existing sources is not covered","Only premises halted by a court injunction; shutdowns caused by administrative dispositions are excluded"],
 "Article 2 defines the two categories of covered premises."),

(F,"第3條",3,"復工試車-試車計畫",
 "公私場所申請試車應檢具之試車計畫內容及試車期間限制為何？",
 ["內容含試車起訖期間、步驟程序及所需日數、污染物產生情形與應變措施、排放檢測計畫及改善措施說明；期間不得超過九十日","內容僅需載明試車起訖期間及預定產能；試車期間不得超過三十日，且不論任何情形均不得申請核准延長","內容含試車起訖期間及排放檢測計畫；試車期間不得超過一百八十日，並得由公私場所自行決定是否延長","內容含試車步驟及應變措施；試車期間不得超過六十日，超過者應改依新設污染源設置許可程序辦理"],"a",
 "第3條第1項：試車計畫內容包括試車預定起訖期間、試車步驟或程序及達到申請最大產能操作條件所需日數、推估各步驟空氣污染物產生情形及防範超標之應變措施、空氣污染物排放檢測計畫、空氣污染改善措施說明及其他經指定文件。第2項規定試車期間不得超過九十日，但經地方主管機關核准者不在此限。",
 "What must a trial run plan contain and how long may the trial last?",
 ["Trial dates, steps and days needed, estimated emissions and contingency measures, a testing plan; up to ninety days","Only the trial dates and planned capacity; the trial may not exceed thirty days and no extension may ever be approved","Trial dates and a testing plan; the trial may last up to one hundred and eighty days, extendable at the premises own discretion","Trial steps and contingency measures; the trial may not exceed sixty days, after which permit procedures apply"],
 "Article 3: the plan contents and the ninety-day limit."),

(F,"第4條",2,"復工試車-資訊公開",
 "公私場所申請試車時，就試車計畫之公開有何規定？",
 ["應登載於中央主管機關指定之公開網站，供利害關係人或公益團體於公開後七日內表示意見","應刊登於當地新聞紙連續三日，供利害關係人於刊登後三十日內以書面提出異議或陳情","應張貼於廠區大門明顯處三十日，並邀請鄰近里長及居民代表列席說明會表示意見","應函送目的事業主管機關轉知同業公會，由公會於十四日內彙整業界意見後轉陳主管機關"],"a",
 "第4條：公私場所申請試車時，應將試車計畫登載於中央主管機關所指定之公開網站，供利害關係人或公益團體於試車計畫公開後七日內表示意見。第5條第2項並要求公私場所回應該等意見並提送主管機關作為審查參考。",
 "How must the trial run plan be made public when applying?",
 ["Posted on the website designated by the central authority, with comments from interested parties within seven days","Published in a local newspaper for three days, with written objections accepted within thirty days of publication","Posted at the plant gate for thirty days, with a briefing session attended by local ward chiefs and residents","Sent to the industry authority for the trade association to collect industry views within fourteen days"],
 "Article 4: seven-day public comment on the designated website."),

(F,"第5條",3,"復工試車-專家審查",
 "地方主管機關受理試車申請後，關於專家學者書面審查之期程規定為何？",
 ["得於計畫公開後三日內送專家學者於七日內完成書面審查，審查完畢後三日內提供意見並通知七日內繳費","得於計畫公開後十四日內送專家學者於三十日內完成書面審查，審查完畢後十四日內提供意見並通知繳費","應於受理當日即送專家學者於三日內完成書面審查，並於審查完畢後當日提供意見且免予繳納審查費","應於計畫公開後三十日內送專家學者於六十日內完成書面審查，審查意見無須提供公私場所知悉"],"a",
 "第5條第1項：地方主管機關受理申請後，得於試車計畫公開後三日內送專家學者於七日內完成書面審查，並於審查完畢後三日內將審查意見提供公私場所，同時通知於七日內繳納審查費。第2項要求公私場所於收到意見翌日起七日內完成詳實說明文件併同意見回應提送主管機關。",
 "What schedule applies to the expert written review of a trial run plan?",
 ["Sent within three days of publication for a seven-day expert review; opinions given within three days and fee notice for seven days","Sent within fourteen days of publication for a thirty-day expert review; opinions given within fourteen days with a fee notice","Sent to experts on the day of acceptance for a three-day review; opinions given the same day and no review fee is charged","Sent within thirty days of publication for a sixty-day expert review; the opinions need not be disclosed to the premises"],
 "Article 5, Paragraph 1 sets the three-, seven- and three-day steps."),

(F,"第6條",3,"復工試車-書面審查",
 "地方主管機關完成試車計畫書面審查之期限及補正規定為何？",
 ["自收到審查參考與繳費證明翌日起三十五日內完成；不合規定者通知限期補正，總補正日數不得超過九十日","自收到審查參考與繳費證明翌日起十五日內完成；不合規定者通知限期補正，總補正日數不得超過三十日","自收到審查參考與繳費證明翌日起六十日內完成；不合規定者逕予駁回，不給予任何補正之機會","自受理申請之日起九十日內完成；不合規定者通知限期補正，補正日數應一併計入審查期間內"],"a",
 "第6條第1項、第3項：主管機關應於收到公私場所提送之審查參考與繳費證明翌日起三十五日內完成試車計畫書面審查，核准後通知依核准內容進行試車；審查不合規定、內容欠缺或未繳費者應通知限期補正，屆期未補正、未更新或未登載者駁回申請，各次補正日數不算入審查期間，總補正日數不得超過九十日。",
 "What is the deadline for the written review and the correction rule?",
 ["Thirty-five days from the day after receiving the review reference and fee proof; corrections capped at ninety days in total","Fifteen days from the day after receiving the review reference and fee proof; corrections capped at thirty days in total","Sixty days from the day after receiving the review reference and fee proof; defective plans rejected with no correction","Ninety days from acceptance of the application; correction days are counted within the review period itself"],
 "Article 6: thirty-five day review, ninety-day correction cap."),

(F,"第7條",3,"復工試車-資訊保密",
 "試車計畫內容涉及工商機密者，申請資訊保密應符合之要件及例外為何？",
 ["須非一般涉及該類資訊之人所知、因秘密性具經濟價值、所有人已採合理保密措施；對公益或保護人民生命健康有必要者得公開","須經目的事業主管機關認定為國防或科技機密，並取得同業公會出具之保密必要性證明文件；核定保密後一律不得對外公開","須由公私場所自行聲明其為營業秘密即可，主管機關應予尊重，並無任何得核定應予公開之例外情形規定","須經法院裁定認定屬營業秘密法所稱之營業秘密；經核定保密者，於任何情形下均不得提供利害關係人閱覽"],"a",
 "第7條第1項：申請資訊保密應符合非一般涉及該類資訊之人所知、因其秘密性而具有實際或潛在之經濟價值、所有人已採取合理之保密措施等三要件。第2項規定主管機關審查認有對公益有必要或為保護人民生命、身體、健康有必要者，得核定應予公開。",
 "What conditions and exceptions apply to a confidentiality request?",
 ["Not generally known, of economic value from its secrecy, reasonably protected; disclosure may be ordered for public interest or health","Certified as defence or technology secrets by the industry authority with a trade association statement; never disclosable once approved","A simple declaration of trade secret by the premises suffices and the authority must respect it, with no exception for disclosure","A court ruling recognising it as a trade secret is required; once approved, it may never be shown to interested parties"],
 "Article 7 sets the three conditions and two disclosure exceptions."),

(F,"第8條",3,"復工試車-保密審查",
 "地方主管機關審查資訊保密申請之期限與補正規定為何？",
 ["受理翌日起七日內完成完整性審查並通知繳費，繳費翌日起十五日內作成准駁；補正以二次為限且總日數不得超過三十日","受理翌日起三十日內完成完整性審查並通知繳費，繳費翌日起六十日內作成准駁；補正次數與日數均不受任何限制","受理翌日起三日內完成完整性審查，並應於當日作成准駁決定；申請文件有欠缺者一律逕予駁回不得補正","受理翌日起十五日內完成完整性審查並通知繳費，繳費翌日起七日內作成准駁；補正以一次為限且不得超過九十日"],"a",
 "第8條：主管機關應於受理資訊保密申請翌日起七日內完成申請資料完整性審查並通知繳納審查費；自完成繳費翌日起十五日內作成准駁決定；文件有欠缺、錯誤或內容不明確者通知限期補正，通知補正次數以二次為限，補正日數不算入審查期間，補正總日數不得超過三十日。",
 "What deadlines and correction limits apply to a confidentiality review?",
 ["Completeness review within seven days and fee notice; decision within fifteen days of payment; two corrections, thirty days total","Completeness review within thirty days and fee notice; decision within sixty days of payment; corrections unlimited in number and days","Completeness review within three days with a decision the same day; defective applications rejected with no correction allowed","Completeness review within fifteen days and fee notice; decision within seven days of payment; one correction of up to ninety days"],
 "Article 8: seven days, fifteen days, two corrections capped at thirty days."),

(F,"第9條",3,"復工試車-許可證併辦",
 "公私場所申請試車致與操作許可證核定內容不一致或許可證失效者，應如何辦理？",
 ["不一致者得併同提出許可證異動申請；許可證失效者得併同重新申請，且試車計畫應經環境工程技師簽證","不一致者應先撤回試車申請並完成許可證異動後始得重新申請試車；許可證失效者不得申請試車","不一致者由主管機關逕行更正許可證內容；許可證失效者得免申請許可證而逕依試車評鑑結果復工","不一致者得併同提出異動申請；許可證失效者僅得由公私場所負責人具結說明，無須技師簽證"],"a",
 "第9條：因試車或改善致與操作許可證核定內容不一致者，得併同提出操作許可證異動申請；固定污染源操作許可證失其效力者，得併同重新申請操作許可證。依後者申請時，其依第3條提出之試車計畫應經依法登記執業之環境工程技師或其他相關專業技師簽證。",
 "How are permit inconsistencies or lapsed permits handled with a trial run?",
 ["Inconsistencies may be filed as a permit change; lapsed permits may be reapplied jointly, with the plan certified by a licensed engineer","The trial application must be withdrawn and the permit changed first; a lapsed permit bars any trial run application at all","The authority corrects the permit directly; with a lapsed permit no new permit is needed before restarting operations","Inconsistencies may be filed jointly; for lapsed permits a statement by the responsible person suffices without certification"],
 "Article 9: joint filing plus engineer certification for lapsed permits."),

(F,"第10條",3,"復工試車-操作條件",
 "公私場所於試車期間進行試車檢測時，其操作條件應如何作為許可證核定內容？",
 ["主要原料及燃料使用量達申請百分之八十以上者依申請內容核定；未達者以試車檢測實際操作條件之一．二倍核定","主要原料及燃料使用量達申請百分之五十以上者依申請內容核定；未達者以試車檢測實際操作條件核定不予放寬","不論使用量多寡一律以申請內容核定；試車檢測之實際操作條件僅供參考，不影響許可證核定內容","主要原料及燃料使用量達申請百分之八十以上者依申請內容核定；未達者應駁回申請並不得再行試車"],"a",
 "第10條第1項：主要原（物）料及燃料使用量達申請之百分之八十以上者，應依申請內容作為操作許可證之核定內容；無法達百分之八十以上者，應以試車檢測時實際操作條件之一．二倍作為核定內容。第2項並要求檢測前七日通知主管機關，第3項規定主管機關應至現場監督。",
 "How do trial testing operating conditions become the permit contents?",
 ["Where material and fuel use reaches eighty per cent of the application, the application governs; otherwise 1.2 times the actual conditions","Where material and fuel use reaches fifty per cent of the application, the application governs; otherwise the actual conditions apply","The application always governs regardless of usage; the actual trial conditions serve only as a reference for the authority","Where usage reaches eighty per cent the application governs; otherwise the application is rejected and no retrial is allowed"],
 "Article 10, Paragraph 1: the eighty per cent threshold and 1.2 multiplier."),

(F,"第11條",3,"復工試車-停止試車",
 "公私場所執行試車計畫期間有違規情形者，主管機關應如何處理？",
 ["依試車計畫試車而違反本法或未依計畫試車者，應令改善或停止試車；經令停止試車者駁回申請並三個月內不受理再試車申請","依試車計畫試車而違反本法者，應逕行移送司法機關偵辦；未依計畫試車者僅需口頭糾正即可繼續試車","不論何種違規情形，一律應令其停止試車並廢止操作許可證，且一年內不受理該場所之再試車申請","依試車計畫試車而違反本法者，得由公私場所自行改善後續行試車，主管機關不得令其停止試車"],"a",
 "第11條：執行試車計畫期間，依計畫試車而違反本法規定或未依計畫內容試車者，主管機關應令改善或停止試車；前者改善完成得繼續試車。後者且違反本法規定者依本法相關規定辦理；經令停止試車者，主管機關應駁回其申請，並於令停止試車之日起三個月內不受理該公私場所之再試車申請。",
 "How are violations during the trial run period handled?",
 ["Order improvement or halt the trial; where the trial is halted the application is rejected and no retrial is accepted for three months","Refer violations of the Act to prosecutors; failure to follow the plan needs only a verbal warning and the trial may continue","Always halt the trial and revoke the operating permit, refusing any retrial application from the premises for one full year","Allow the premises to improve on its own and continue the trial, since the authority may not order the trial to stop"],
 "Article 11: improvement or halt, with a three-month bar on retrial."),

(F,"第12條",3,"復工試車-評鑑申請",
 "公私場所應於何時報請評鑑？未依規定辦理或需展延者其效果為何？",
 ["應於試車期限屆滿十五日前檢具合格檢測報告報請評鑑；未提送者應停止試車並駁回申請；展延應於屆滿十五日前申請且不得超過二次","應於試車期限屆滿三十日前檢具合格檢測報告報請評鑑；未提送者得順延至次一期限辦理；展延之次數及日數均不受限制","應於試車期限屆滿後三十日內補送檢測報告報請評鑑；未提送者僅需書面說明理由即得繼續試車；展延申請以一次為限","應於試車開始前十五日檢具檢測報告報請評鑑；未提送者由主管機關逕行評鑑；展延應於屆滿三日前申請且以三次為限"],"a",
 "第12條：公私場所應於試車期限屆滿十五日前，檢具檢驗測定機構所為之合格檢測報告或其他足以證明已採取改善措施之文件及空氣污染改善成效說明，報請主管機關評鑑；未於期限前提送者，應於試車終止日起停止試車，主管機關並應駁回其申請。無法於核准期間完成試車者，應於期限屆滿十五日前申請展延，展延申請次數不得超過二次。",
 "When must evaluation be requested, and what follows non-compliance or extension?",
 ["Fifteen days before the deadline with compliant test reports; failure means stopping and rejection; extensions at most twice","Thirty days before the deadline; failure simply defers the matter to the next deadline; extensions allowed without any limit","Within thirty days after the deadline; failure needs only a written explanation to continue; one single extension is allowed","Fifteen days before the trial starts; failure means the authority evaluates alone; extensions three days before, three times"],
 "Article 12: fifteen days before expiry, at most two extensions."),

(F,"第13條",2,"復工試車-評鑑期限",
 "地方主管機關受理評鑑文件後之處理期限及現場勘查規定為何？",
 ["應於二十五日內完成評鑑並進行現場勘查，必要時得邀請專家學者協助；已完成試車檢測現場監督且無必要者得免勘查","應於六十日內完成評鑑並一律進行現場勘查，於任何情形下均不得免除，且不得邀請專家學者或技師協助辦理","應於十日內完成評鑑且不進行現場勘查，全部以書面審查方式辦理，必要時得要求公私場所補送照片資料","應於九十日內完成評鑑並得於評鑑後六個月內擇期進行現場勘查，勘查結果不影響原評鑑之結論"],"a",
 "第13條：主管機關受理第12條第1項文件後，應於二十五日內完成評鑑，並於評鑑期間進行現場勘查，必要時得邀請專家、學者或技師協助現場勘查；惟已依第10條第3項完成現場監督試車檢測作業，並評估無須至現場再確認之必要者，得免執行現場勘查。",
 "What deadline and site inspection rules apply to the evaluation?",
 ["Complete within twenty-five days with a site inspection, experts may assist; waivable if trial testing was already supervised","Complete within sixty days with a mandatory site inspection that may never be waived, and no experts may assist the inspection","Complete within ten days with no site inspection, entirely on paper, with photographs requested from the premises if needed","Complete within ninety days and inspect the site any time within six months, with the inspection not affecting the conclusion"],
 "Article 13: twenty-five days, waivable site inspection."),

(F,"第14條",1,"復工試車-繼續試車",
 "公私場所檢具評鑑文件經主管機關受理者，於完成評鑑前之試車狀態為何？",
 ["於完成評鑑前得繼續試車","於受理之日起應即停止試車","於受理後應停工並封存設備","於完成評鑑前得逕行復工生產"],"a",
 "第14條：公私場所檢具第12條第1項規定文件，經直轄市、縣（市）主管機關受理者，於完成評鑑前，得繼續試車。惟依第15條規定，繼續試車期間若經發現未依試車計畫內容試車者，主管機關應即駁回其申請。",
 "What is the status of the trial run after the evaluation documents are accepted?",
 ["The trial run may continue until the evaluation is complete","The trial run must stop on the day of acceptance","Operations must halt and equipment must be sealed","Full production may resume before the evaluation ends"],
 "Article 14: the trial may continue pending evaluation."),

(F,"第15條",2,"復工試車-駁回",
 "於繼續試車期間，經發現公私場所未依試車計畫內容進行試車者，主管機關應如何處理？",
 ["應即駁回其恢復污染源操作或復工（業）之申請，並自駁回處分之日起三個月內不受理再試車之申請","應通知限期改善，改善完成後仍得繼續試車，且不影響其恢復操作或復工（業）申請之准駁","應處以罰鍰後准予繼續試車，僅於同一年度內第三次違規時始得駁回其復工（業）之申請","應即駁回其申請，並自駁回處分之日起一年內不受理再試車之申請並廢止其操作許可證"],"a",
 "第15條：公私場所於第14條繼續試車期間，經直轄市、縣（市）主管機關發現有未依試車計畫內容進行試車者，主管機關應即駁回其恢復污染源操作或復工（業）之申請，並自駁回處分之日起，三個月內不受理再試車之申請。",
 "What happens if the trial deviates from the plan during continued running?",
 ["The restart application is rejected at once and no retrial application is accepted for three months from the rejection","An improvement notice is issued and the trial may continue after improvement, without affecting the restart application","A fine is imposed and the trial continues; rejection follows only on a third violation within the same calendar year","The application is rejected at once, no retrial is accepted for one year, and the operating permit is revoked as well"],
 "Article 15: immediate rejection and a three-month bar."),

(F,"第16條",3,"復工試車-評鑑結果",
 "試車評鑑之結果，其法律效果為何？",
 ["符合計畫內容及排放標準之操作條件應作為核准復工之應遵行事項；評鑑不合格者駁回申請並三個月內不得再申請試車","符合者僅供主管機關內部參考而不作為核准復工之條件；評鑑不合格者仍得於改善後隨時再申請試車復工","符合者應逕予核發新操作許可證且免記載應遵行事項；評鑑不合格者應逕予廢止其操作許可證及登記","符合者仍作為應遵行事項；評鑑不合格者得先行復工並於復工後六個月內完成改善後再接受複評"],"a",
 "第16條：主管機關評鑑符合試車計畫內容及排放標準之操作條件，應作為核准其恢復操作或復工（業）之應遵行事項；受理併同許可證異動或重新申請者，應將該應遵行事項納入操作許可證核定內容。評鑑不合格者，除依本法相關規定辦理外，應駁回復工申請並即停止污染源操作、再進行改善，自駁回處分日起三個月內不得再申請試車。",
 "What is the legal effect of the trial run evaluation result?",
 ["Compliant operating conditions become binding conditions for restart; failure means rejection and no retrial for three months","Compliant results are only internal reference and not restart conditions; failure still allows a retrial at any time after fixing","Compliant results lead directly to a new permit with no binding conditions; failure means the permit is revoked outright","Compliant results become binding conditions; failure still allows restart with improvement completed within six months"],
 "Article 16: binding conditions on success, three-month bar on failure."),

(F,"第17條",1,"復工試車-施行",
 "公私場所固定污染源復工試車評鑑及管理辦法之施行日期為何？",
 ["自發布日施行","自發布後三個月施行","自發布後一年施行","另定施行日期並公告之"],"a",
 "第17條：本辦法自發布日施行。屬形式規定，無緩衝期間，發布當日即生效力。",
 "When does this trial run regulation take effect?",
 ["On the date of promulgation","Three months after promulgation","One year after promulgation","On a separately announced date"],
 "Article 17: effective upon promulgation."),
]
