# -*- coding: utf-8 -*-
# 第 13 批（D2）補題：ENV-82 土壤及地下水污染場址初步評估暨處理等級評定辦法、
#                    ENV-84 氣候變遷因應法施行細則
A = "ENV-82"
B = "ENV-84"
Q = [

# ===== ENV-82 土壤及地下水污染場址初步評估暨處理等級評定辦法 =====
(A,"第1條",1,"初評辦法-授權依據",
 "土壤及地下水污染場址初步評估暨處理等級評定辦法係依據母法何項規定訂定？",
 ["土壤及地下水污染整治法第十二條第十一項及第十四條第五項之規定","土壤及地下水污染整治法第六條第二項及第五十六條所定之授權規定","土壤及地下水污染整治法第二十二條第四項及第二十四條第二項規定","土壤及地下水污染整治法第三十條第二項及第四十條第三項之規定"],"a",
 "第1條：本辦法依土壤及地下水污染整治法第十二條第十一項及第十四條第五項規定訂定之。母法第六條第二項為土壤、地下水污染管制標準之授權依據，第五十六條則為施行細則之授權來源。",
 "Under which provisions of the Act are these Regulations issued?",
 ["Article 12, Paragraph 11 and Article 14, Paragraph 5 of the Remediation Act","Article 6, Paragraph 2 and Article 56 of the Soil and Groundwater Remediation Act","Article 22, Paragraph 4 and Article 24, Paragraph 2 of the Remediation Act","Article 30, Paragraph 2 and Article 40, Paragraph 3 of the Remediation Act"],
 "Article 1: issued under Articles 12-11 and 14-5 of the Act."),

(A,"第2條",2,"初評辦法-初步評估定義",
 "本辦法所稱「初步評估」，其定義為何？",
 ["指進行控制場址污染影響潛勢評估，並依評估結果評定是否公告為整治場址","指依場址污染影響潛勢評估總分，評定由整治基金支出費用之場址優先順序","指調查污染場址之土壤及地下水污染分布狀況並繪製污染調查範圍圖說","指進行土壤污染途徑影響潛勢評分及地下水污染途徑影響潛勢評分作業"],"a",
 "第2條第1款：初步評估指進行土壤、地下水污染控制場址污染影響潛勢評估，並依評估結果評定是否公告為整治場址。同條第2款之處理等級評定則是評定基金支出之優先順序，第3款場址污染影響潛勢評估則指土壤與地下水兩途徑之評分。",
 "What does preliminary assessment mean under these Regulations?",
 ["Assessing a control site's pollution impact potential and deciding whether to announce it as a remediation site","Ranking, by total pollution impact potential score, the priority of sites funded by the remediation fund","Investigating the distribution of soil and groundwater pollution and drawing the survey extent maps","Conducting the soil pollution pathway impact scoring and the groundwater pathway impact scoring"],
 "Article 2-1 defines preliminary assessment."),

(A,"第2條",2,"初評辦法-處理等級評定",
 "本辦法所稱「處理等級評定」及「對環境影響之評估」，其定義分別為何？",
 ["前者係依潛勢評估總分評定基金支出費用之場址優先順序，後者係評估對國民健康及生活環境之危害性","前者係依污染物種類評定應採行之整治技術，後者係評估整治工程對周邊交通及景觀之影響程度","前者係依場址面積大小評定應繳納之整治費用，後者係評估污染土地之市場價值減損之金額","前者係依污染行為人資力評定其分攤比例，後者係評估整治期間對當地產業營運之衝擊程度"],"a",
 "第2條第2款：處理等級評定指依場址污染影響潛勢評估總分，評定由整治基金支出費用之控制場址、整治場址優先順序。同條第5款：對環境影響之評估指依場址污染潛勢評估總分評估污染場址對國民健康及生活環境之危害性。第9條並規定評定之順序。",
 "How are handling-grade evaluation and environmental impact assessment defined?",
 ["The former ranks fund-supported sites by total potential score; the latter assesses harm to public health and living environment","The former decides the remediation technology by contaminant type; the latter assesses effects on traffic and landscape","The former sets the remediation fee by site area; the latter assesses the loss in market value of the polluted land","The former sets the polluter's share by its financial capacity; the latter assesses impacts on local industry operations"],
 "Article 2 items 2 and 5 define these two terms."),

(A,"第4條",2,"初評辦法-多項污染物",
 "進行控制場址初步評估及處理等級評定時，如有二項以上污染物項目達管制標準，應如何處理？",
 ["所有污染物項目均應納入評估，作為判定之依據","僅需就濃度最高之單一污染物項目納入評估即可","僅需就毒性最強之二項污染物項目納入評估即可","由主管機關就其中任選三項污染物項目納入評估"],"a",
 "第4條：如有二項以上污染物項目達土壤、地下水污染管制標準，所有污染物項目均應納入評估，作為判定之依據。第5條、第6條並要求分別計算各污染物項目之分數後加總為總分。",
 "If two or more contaminants reach the control standards, how is the assessment conducted?",
 ["All contaminant items must be included in the assessment as the basis for the decision","Only the single contaminant with the highest concentration needs to be assessed","Only the two most toxic contaminant items need to be included in the assessment","The authority may freely pick any three contaminant items to include in the assessment"],
 "Article 4 requires all contaminants to be assessed."),

(A,"第5條",3,"初評辦法-土壤評分",
 "土壤污染途徑影響潛勢分數（SL）之計算公式及其評分項目為何？",
 ["SL＝SL1×SL2×SL3／20，評分項目為污染程度、土地使用狀況及污染物危害性","SL＝SL1×SL2×SL3／80，評分項目為污染程度、污染面積大小及污染深度分布","SL＝（SL1＋SL2＋SL3）／20，評分項目為污染濃度、污染範圍及暴露人口數","SL＝SL1×SL2÷SL3×20，評分項目為污染物毒性、土壤質地及地下水位深度"],"a",
 "第5條：土壤污染途徑影響潛勢評分項目包括土壤污染程度評分（SL1）、土壤污染場址土地使用狀況評分（SL2）及土壤污染物危害性評分（SL3）；SL＝SL1×SL2×SL3／20。應分別計算各污染物項目分數，其總和為土壤污染途徑影響潛勢總分（SLT）。",
 "What is the formula and the scoring items for the soil pathway impact potential score (SL)?",
 ["SL = SL1×SL2×SL3/20, scoring pollution degree, land use status and contaminant hazard","SL = SL1×SL2×SL3/80, scoring pollution degree, polluted area size and depth distribution","SL = (SL1+SL2+SL3)/20, scoring concentration, pollution extent and exposed population","SL = SL1×SL2÷SL3×20, scoring contaminant toxicity, soil texture and groundwater depth"],
 "Article 5 sets SL = SL1×SL2×SL3/20."),

(A,"第6條",3,"初評辦法-地下水評分",
 "地下水污染途徑影響潛勢分數（GW）之計算公式及其評分項目為何？",
 ["GW＝GW1×GW2×GW3／80，評分項目為污染程度、土地使用狀況及污染物危害性","GW＝GW1×GW2×GW3／20，評分項目為污染程度、土地使用狀況及污染物危害性","GW＝（GW1＋GW2＋GW3）／80，評分項目為含水層厚度、水力傳導係數及流向","GW＝GW1×GW2×GW3／40，評分項目為井深、抽水量及下游飲用水取水口距離"],"a",
 "第6條：地下水污染途徑影響潛勢評分項目包括地下水污染程度評分（GW1）、地下水污染場址土地使用狀況評分（GW2）及地下水污染物危害性評分（GW3）；GW＝GW1×GW2×GW3／80。與第5條土壤途徑之除數20不同，應特別留意。",
 "What is the formula and scoring items for the groundwater pathway impact potential score (GW)?",
 ["GW = GW1×GW2×GW3/80, scoring pollution degree, land use status and contaminant hazard","GW = GW1×GW2×GW3/20, scoring pollution degree, land use status and contaminant hazard","GW = (GW1+GW2+GW3)/80, scoring aquifer thickness, hydraulic conductivity and flow direction","GW = GW1×GW2×GW3/40, scoring well depth, pumping rate and distance to downstream intakes"],
 "Article 6 sets GW = GW1×GW2×GW3/80."),

(A,"第7條",3,"初評辦法-總分計算",
 "場址污染影響潛勢評估總分（TOL）應如何計算？",
 ["以土壤污染途徑總分與地下水污染途徑總分之平方和除以二後開根號計算之","以土壤污染途徑總分與地下水污染途徑總分之算術平均數直接相加後計算之","以土壤污染途徑總分乘以地下水污染途徑總分後再除以二百計算其結果","以土壤污染途徑總分與地下水污染途徑總分兩者中較高者作為總分計算"],"a",
 "第7條：場址污染影響潛勢評估總分（TOL）＝根號下［（SLT）平方＋（GWT）平方］除以二，即以土壤污染途徑影響潛勢總分與地下水污染途徑影響潛勢總分之平方和除以二後開根號。計算結果應填報於附表四。",
 "How is the total site pollution impact potential score (TOL) calculated?",
 ["The square root of the sum of the squares of SLT and GWT divided by two","The arithmetic mean of SLT and GWT added together directly as the total","The product of SLT and GWT divided by two hundred to give the result","The higher of SLT and GWT is taken as the total score for the site"],
 "Article 7 uses the root-mean-square of SLT and GWT."),

(A,"第9條",3,"初評辦法-評定順序",
 "中央主管機關為處理等級評定時，各場址分數相同者應依何種順序決定優先順序？",
 ["先依潛勢評估總分，同分者依地下水污染途徑總分，再同分者依土壤污染途徑總分","先依潛勢評估總分，同分者依土壤污染途徑總分，再同分者依地下水污染途徑總分","先依污染物項目數量多寡，同數者依場址面積大小，再相同者依公告先後順序","先依污染行為人是否明確，同一情形者依場址所在直轄市、縣（市）之順序"],"a",
 "第9條：處理等級評定應先依第七條第二項場址污染影響潛勢評估總分評定；分數相同者，依第六條第三項地下水污染途徑影響潛勢總分評定；再相同者，依第五條第三項土壤污染途徑影響潛勢總分評定；仍相同者優先順序相同。中央主管機關並得視個案實際需要調整。",
 "When scores tie, what order determines the handling-grade priority?",
 ["First the total potential score, then the groundwater pathway total, then the soil pathway total","First the total potential score, then the soil pathway total, then the groundwater pathway total","First the number of contaminants, then the site area, then the order of announcement","First whether the polluter is identified, then the order of the municipality or county"],
 "Article 9 sets a three-tier tie-breaking order."),

(A,"第10條",1,"初評辦法-施行日",
 "土壤及地下水污染場址初步評估暨處理等級評定辦法之施行日期為何？",
 ["本辦法自發布日施行","本辦法自發布後三個月施行","本辦法自發布後一年施行","本辦法自次年一月一日施行"],"a",
 "第10條：本辦法自發布日施行。本辦法現行條文修正日期為民國一百零二年四月二十四日，其第8條並規定總分達一千二百分以上者應報請中央主管機關審核公告為整治場址。",
 "When do these Regulations take effect?",
 ["On the date of promulgation","Three months after promulgation","One year after promulgation","On January 1 of the following year"],
 "Article 10: effective upon promulgation."),

# ===== ENV-84 氣候變遷因應法施行細則 =====
(B,"第1條",1,"氣候法細則-授權",
 "氣候變遷因應法施行細則係依據母法何條規定訂定？",
 ["氣候變遷因應法第六十二條之授權規定","氣候變遷因應法第二十一條第二項規定","氣候變遷因應法第二十七條第二項規定","氣候變遷因應法第三十條第二項之規定"],"a",
 "第1條：本細則依氣候變遷因應法第六十二條規定訂定之。母法第二十一條第二項為溫室氣體排放量盤查登錄及查驗管理辦法之授權依據，第二十七條第二項等則為碳費收費辦法之授權來源。",
 "Under which provision of the Climate Change Response Act are these Rules issued?",
 ["Article 62 of the Climate Change Response Act","Article 21(2) of the Climate Change Response Act","Article 27(2) of the Climate Change Response Act","Article 30(2) of the Climate Change Response Act"],
 "Article 1: issued under Article 62 of the Act."),

(B,"第2條",2,"氣候法細則-中央權責",
 "下列何者屬氣候變遷因應法施行細則所定中央主管機關之主管事項？",
 ["溫室氣體查驗機構之審查、許可、管理及認證機構之管理事項","直轄市、縣（市）氣候變遷因應推動會之規劃及執行等事項","直轄市、縣（市）溫室氣體減量執行方案之訂修規劃及執行","協助執行地方排放源操作與排放相關設施之檢查與輔導事項"],"a",
 "第2條：中央主管機關主管事項共二十二款，包括溫室氣體查驗機構之審查、許可、管理及認證機構之管理。至於推動會之規劃執行、減量執行方案之訂修及協助檢查輔導，則為第3條所定直轄市、縣（市）主管機關之事項。",
 "Which is a matter under the central competent authority's jurisdiction?",
 ["Review, permitting and management of GHG verification bodies and accreditation bodies","Planning and executing the municipal or county climate change response steering committee","Drafting, revising, planning and executing the local GHG reduction implementation plan","Assisting with inspection and guidance of local emission sources and related facilities"],
 "Article 2 lists 22 central matters; the others belong to Article 3."),

(B,"第2條",3,"氣候法細則-碳費與碳足跡",
 "關於中央主管機關之主管事項，下列敘述何者正確？",
 ["全國溫室氣體排放源碳費徵收之訂定審核執行、進口產品碳排放量之申報審查管理均屬之","碳費徵收之訂定及執行屬中央權責，但進口產品碳排放量之申報審查係由關務機關辦理","產品碳足跡之審查核算屬中央權責，但碳費之徵收係由直轄市、縣（市）主管機關辦理","二氧化碳捕捉後封存之審查管理屬地方權責，中央主管機關僅負責訂定相關技術規範"],"a",
 "第2條第14款、第15款、第18款、第20款：全國溫室氣體之排放源碳費徵收之訂定、審核及執行，進口產品碳排放量之申報、審查及管理，產品碳足跡之審查、查驗、核算、核定、查核及檢查，二氧化碳捕捉後封存之審查及管理，均屬中央主管機關主管事項。",
 "Which statement about the central authority's matters is correct?",
 ["Both carbon fee collection nationwide and the reporting and review of imported product emissions belong to it","Carbon fee collection belongs to it, but reporting of imported product emissions is handled by customs","Product carbon footprint review belongs to it, but carbon fee collection is handled by local authorities","Carbon capture and storage review is local, with the central authority only setting technical rules"],
 "Article 2 items 14, 15, 18 and 20 all fall to the central authority."),

(B,"第3條",2,"氣候法細則-地方權責",
 "下列何者屬直轄市、縣（市）主管機關依本細則所定之主管事項？",
 ["執行轄區產品碳足跡查核及檢查事項與氣候變遷因應推動會之規劃執行","溫室氣體查驗機構之許可及認證機構之管理，並辦理查驗員之訓練認證","全國溫室氣體減量額度之審查、核准、移轉及交易事項之核定及管理","溫室氣體總量管制及排放交易制度之訂定及全國性執行事項之推動"],"a",
 "第3條：直轄市、縣（市）主管機關主管事項共十四款，包括執行直轄市、縣（市）產品碳足跡查核及檢查事項、氣候變遷因應推動會之規劃及執行事項。查驗機構許可、減量額度審查及總量管制排放交易則屬第2條中央主管機關事項。",
 "Which matter falls to the municipal or county competent authority?",
 ["Carrying out local product carbon footprint audits and planning the local steering committee","Permitting GHG verification bodies and managing accreditation bodies and verifier training","Reviewing, approving, transferring and trading national GHG emission reduction credits","Setting up the national cap-and-trade system and promoting its nationwide implementation"],
 "Article 3 lists 14 local matters."),

(B,"第3條",2,"氣候法細則-地方調適",
 "關於直轄市、縣（市）主管機關就氣候變遷調適所負之主管事項，下列何者正確？",
 ["包括調適執行方案之訂修規劃執行、調適之教育宣導、協助民間團體推展及人員訓練講習","僅包括調適執行方案之訂修及規劃，教育宣導與人員訓練均屬中央主管機關專責事項","僅包括協助民間團體推展調適工作，方案之訂修規劃執行係由中央目的事業主管機關辦理","僅包括調適之人員訓練與講習，其餘調適相關事項一律由中央主管機關統籌辦理"],"a",
 "第3條第6款至第10款：直轄市、縣（市）主管機關主管事項包括氣候變遷調適執行方案之訂修、規劃及執行、調適之教育及宣導、協助民間團體推展、人員之訓練與講習，以及調適及減量之調查、輔導及研究發展等事項。",
 "Which statement on local authorities' climate adaptation duties is correct?",
 ["They cover drafting and executing the adaptation plan, education, assisting NGOs and staff training","They cover only drafting and planning the adaptation plan, as education and training are central duties","They cover only assisting NGOs, as plan drafting and execution is done by industry authorities","They cover only staff training and workshops, as all other adaptation matters are handled centrally"],
 "Article 3 items 6 to 10 cover local adaptation duties."),

(B,"第4條",2,"氣候法細則-行動綱領",
 "中央主管機關依本法第九條第一項擬訂國家因應氣候變遷行動綱領，其程序及內容為何？",
 ["經行政院核定後公開之，內容包括未來情境、衝擊挑戰、願景目標、基本原則、政策內涵及後續推動","經立法院審議通過後公開之，內容包括減量目標、碳費費率、罰則設計及各部門經費分配比例","經中央目的事業主管機關會銜後公開之，內容包括各縣市減量配額及排放交易市場運作規則","經氣候變遷因應推動會決議後公開之，內容包括各事業盤查登錄期限及查驗機構管理規定"],"a",
 "第4條：國家因應氣候變遷行動綱領經行政院核定後公開之，其內容包括我國氣候變遷之未來情境、調適及減緩所遭遇之衝擊及挑戰、願景及目標、基本原則、政策內涵、後續推動等六項。",
 "How is the National Climate Change Action Guideline adopted and what does it contain?",
 ["Approved by the Executive Yuan and made public; it covers scenarios, challenges, vision, principles, policy and follow-up","Passed by the Legislative Yuan and made public; it covers reduction targets, fee rates, penalties and budget shares","Countersigned by industry authorities and made public; it covers county quotas and trading market rules","Resolved by the steering committee and made public; it covers inventory deadlines and verifier management"],
 "Article 4 lists six content items, approved by the Executive Yuan."),

(B,"第5條",2,"氣候法細則-階段管制目標",
 "為利中央主管機關訂定階段管制目標，中央有關機關應辦理何事？",
 ["應進行排放趨勢推估及情境分析，提出電力排放係數、電力需求成長、減量情境、貢獻及成本估算","應逕行訂定所屬部門之減量配額並函送中央主管機關備查，無須進行趨勢推估及情境分析作業","應委託查驗機構查證所屬部門前一年度之排放量，並將查證結果公開於中央主管機關指定網站","應就所屬部門徵收之碳費金額提出使用計畫，並評估碳費費率調整對產業競爭力之影響程度"],"a",
 "第5條：中央有關機關應進行溫室氣體排放趨勢推估及情境分析，並提出電力排放係數、電力需求成長、各部門溫室氣體減量情境、減量貢獻及減量成本之估算，且評估可能衍生之影響，送中央主管機關彙整及綜合評估；階段管制目標報請行政院核定後實施並公開。",
 "What must central agencies do to support the setting of phased control targets?",
 ["Project emission trends and scenarios, and estimate power emission factors, demand growth, scenarios, contributions and costs","Set their own sectoral reduction quotas and file them with the central authority without trend projection or scenario analysis","Commission verification bodies to verify last year's sectoral emissions and publish the results on the designated website","Submit a spending plan for the carbon fees collected and assess the impact of fee rates on industrial competitiveness"],
 "Article 5 requires trend projection and scenario analysis."),

(B,"第6條",3,"氣候法細則-執行報告",
 "中央主管機關彙整各部門階段管制目標執行狀況，應於每年何時向行政院報告？",
 ["應於每年十一月三十日前向行政院報告該執行狀況","應於每年三月三十一日前向行政院報告該執行狀況","應於每年六月三十日前向行政院報告該執行狀況","應於每年九月三十日前向行政院報告該執行狀況"],"a",
 "第6條第1項：中央主管機關依本法第十條第五項彙整各部門階段管制目標執行狀況，應於每年十一月三十日前向行政院報告。報告內容包括階段管制目標、各部門執行狀況摘要、達成情形、分析及檢討。",
 "By when each year must the central authority report sectoral target progress to the Executive Yuan?",
 ["By November 30 of each year it must submit that report","By March 31 of each year it must submit that report","By June 30 of each year it must submit that report","By September 30 of each year it must submit that report"],
 "Article 6-1 sets November 30."),

(B,"第6條",3,"氣候法細則-階段達成報告",
 "各階段管制期間結束後，中央主管機關應於何時向行政院報告前一階段之達成情形？",
 ["應於各階段管制期間結束後次次年十一月三十日前提出報告","應於各階段管制期間結束後次年十一月三十日前提出報告","應於各階段管制期間結束後六個月內提出該階段之報告","應於各階段管制期間結束當年十二月三十一日前提出報告"],"a",
 "第6條第3項：中央主管機關應於各階段管制期間結束後次次年十一月三十日前，向行政院報告前一階段之達成情形。此與同條第1項每年十一月三十日前之年度報告義務併行。",
 "By when must the achievement of a completed control period be reported to the Executive Yuan?",
 ["By November 30 of the second year after the control period ends","By November 30 of the year following the end of the control period","Within six months after the end of that phase's control period","By December 31 of the year in which the control period ends"],
 "Article 6-3 sets the second following year, November 30."),

(B,"第8條",2,"氣候法細則-部門成果報告",
 "中央目的事業主管機關編寫所屬部門行動方案成果報告，其期限及程序為何？",
 ["應於每年九月三十日前送中央主管機關，報請行政院核定後公開之","應於每年三月三十一日前送中央主管機關，報請行政院核定後公開","應於每年十一月三十日前送中央主管機關，並逕行公開無須核定","應於每年八月三十一日前送中央主管機關，經該機關備查後公開"],"a",
 "第8條：部門行動方案成果報告應於每年九月三十日前送中央主管機關，報請行政院核定後公開之；其內容包括摘要、所屬部門階段管制目標執行狀況及評量指標達成情形、推動策略及措施執行成果含經費執行情形。",
 "What is the deadline and procedure for the sectoral action plan results report?",
 ["Submit to the central authority by September 30 each year, then publish after Executive Yuan approval","Submit to the central authority by March 31 each year, then publish after Executive Yuan approval","Submit to the central authority by November 30 each year and publish directly without approval","Submit to the central authority by August 31 each year and publish after it is filed for reference"],
 "Article 8: September 30, with Executive Yuan approval."),

(B,"第9條",2,"氣候法細則-改善措施",
 "部門行動方案成果報告顯示未達階段管制目標或評量指標者，應如何處理？",
 ["應於提送成果報告時併同提出改善措施，送中央主管機關報請行政院核定後公開之","應於次年度重新提出部門行動方案，並由中央主管機關逕行裁處罰鍰以督促改善","應由中央主管機關逕行代為擬訂改善措施，該部門僅需配合執行無須另行提出","應俟該階段管制期間全部結束後，再一次檢討提出改善措施送行政院核定公開"],"a",
 "第9條：成果報告顯示未達目標或指標者，中央目的主管機關應於提送成果報告時併同提出改善措施，送中央主管機關報請行政院核定後公開之；改善措施內容包括改善措施、期程及經費，以及預期改善成果。",
 "What follows if the sectoral results report shows targets or indicators were not met?",
 ["Improvement measures must accompany the report, be approved by the Executive Yuan and published","The sector must resubmit its action plan next year and the central authority imposes a fine","The central authority drafts the improvement measures itself and the sector merely executes them","Improvement measures are reviewed only once, after the entire control period has ended"],
 "Article 9 requires improvement measures filed with the report."),

(B,"第10條",2,"氣候法細則-排放量調查",
 "中央目的事業主管機關依本法第十三條第一項進行排放量調查及統計成果，其期限及範圍為何？",
 ["應於每年三月三十一日前提送中央主管機關，並應包括前二年之排放量或碳匯量及活動數據","應於每年四月三十日前提送中央主管機關，並應包括前一年之排放量或碳匯量及活動數據","應於每年六月三十日前提送中央主管機關，並應包括前三年之排放量或碳匯量及活動數據","應於每年九月三十日前提送中央主管機關，並應包括前五年之排放量或碳匯量及活動數據"],"a",
 "第10條：中央目的事業主管機關應於每年三月三十一日前提送排放量調查及統計成果供中央主管機關進行全國排放量統計；其成果應包括前二年之溫室氣體排放量或碳匯量，及其活動數據或排放係數。",
 "What is the deadline and scope for sectoral emission surveys and statistics?",
 ["Submit by March 31 each year, covering emissions or carbon sinks of the previous two years and activity data","Submit by April 30 each year, covering emissions or carbon sinks of the previous year and activity data","Submit by June 30 each year, covering emissions or carbon sinks of the previous three years and activity data","Submit by September 30 each year, covering emissions or carbon sinks of the previous five years and activity data"],
 "Article 10: by March 31, covering the previous two years."),

(B,"第12條",2,"氣候法細則-國家報告",
 "中央主管機關編撰溫室氣體國家報告之頻率及期限為何？",
 ["應每三年編撰一次，於每三年之第三年十一月三十日前報請行政院核定後公開之","應每年編撰一次，於每年十一月三十日前報請行政院核定後對外公開該報告","應每五年編撰一次，於每五年之第五年六月三十日前報請行政院核定後公開","應每二年編撰一次，於每二年之第二年三月三十一日前報請行政院核定公開"],"a",
 "第12條：國家報告應每三年編撰一次，於每三年之第三年十一月三十日前報請行政院核定後公開之。相對地，第11條所定國家溫室氣體排放清冊則為每年六月三十日前公開。",
 "How often and by when must the national GHG report be compiled?",
 ["Every three years, submitted for Executive Yuan approval and published by November 30 of the third year","Every year, submitted for Executive Yuan approval and published by November 30 of that same year","Every five years, submitted for Executive Yuan approval and published by June 30 of the fifth year","Every two years, submitted for Executive Yuan approval and published by March 31 of the second year"],
 "Article 12: every three years, by November 30 of the third year."),

(B,"第12條",2,"氣候法細則-國家報告內容",
 "溫室氣體國家報告之內容，不包括下列何者？",
 ["各事業盤查登錄之個別排放量清冊及其查驗機構之查驗聲明書","國情及環境基本資料、溫室氣體排放與吸收統計及趨勢分析","我國溫室氣體減量之政策及措施，以及溫室氣體排放之預測","氣候變遷衝擊影響及調適對策、技術研發需求及移轉與國際合作"],"a",
 "第12條第2項：國家報告內容包括國情及環境基本資料、排放與吸收統計及趨勢分析、減量政策及措施、排放預測、氣候變遷衝擊影響及調適對策、氣候變遷及系統觀測研究、技術研發需求及移轉、國際合作及交流、教育培訓及宣導等九項。個別事業之盤查清冊非其內容。",
 "Which item is NOT part of the national GHG report?",
 ["The individual emission inventories of enterprises and their verification statements","National circumstances and basic environmental data, emission and sink statistics and trends","Domestic greenhouse gas reduction policies and measures, and emission projections","Climate impacts and adaptation responses, technology R&D and transfer, and cooperation"],
 "Article 12-2 lists nine items; enterprise inventories are not among them."),

(B,"第13條",3,"氣候法細則-減量執行方案",
 "直轄市、縣（市）主管機關訂修溫室氣體減量執行方案，其期限、核定程序及檢討頻率為何？",
 ["應於部門行動方案核定後八個月內送推動會，報請中央主管機關會商中央目的事業主管機關核定，每五年至少檢討一次","應於部門行動方案核定後一年內送推動會，報請中央主管機關會商中央目的事業主管機關核定，每四年至少檢討一次","應於部門行動方案核定後六個月內送推動會，由該推動會逕行核定後實施並公開，每三年至少檢討一次","應於階段管制目標核定後八個月內送推動會，報請行政院核定後實施並公開，每二年至少檢討一次"],"a",
 "第13條：減量執行方案應於部門行動方案核定後八個月內，送直轄市、縣（市）氣候變遷因應推動會，報請中央主管機關會商中央目的事業主管機關核定後實施並公開，且每五年至少檢討一次。相對地，第19條調適執行方案為核定後一年內、每四年至少檢討一次。",
 "What are the deadline, approval process and review cycle for the local GHG reduction plan?",
 ["Within eight months of the sectoral plan's approval, to the committee, approved centrally in consultation, reviewed at least every five years","Within one year of the sectoral plan's approval, to the committee, approved centrally in consultation, reviewed at least every four years","Within six months of the sectoral plan's approval, to the committee, approved by that committee itself, reviewed at least every three years","Within eight months of the phased target's approval, to the committee, approved by the Executive Yuan, reviewed at least every two years"],
 "Article 13: eight months, central approval in consultation, five-year review."),

(B,"第14條",2,"氣候法細則-減量成果報告",
 "直轄市、縣（市）主管機關編寫減量執行方案成果報告，其期限及程序為何？",
 ["應於每年九月三十日前送直轄市、縣（市）氣候變遷因應推動會後公開之","應於每年八月三十一日前送中央主管機關報請行政院核定後公開之","應於每年十一月三十日前送中央目的事業主管機關核定後公開之","應於每年三月三十一日前送直轄市、縣（市）議會審議通過後公開"],"a",
 "第14條：減量執行方案成果報告應於每年九月三十日前，送直轄市、縣（市）氣候變遷因應推動會後公開之；其內容包括摘要、推動策略及措施執行成果含經費執行情形、分析及檢討。第20條調適執行方案成果報告則為每年八月三十一日前。",
 "What is the deadline and procedure for the local GHG reduction plan results report?",
 ["Submit to the local climate change response committee by September 30 each year, then publish","Submit to the central authority by August 31 each year and publish after Executive Yuan approval","Submit to the industry competent authority by November 30 each year and publish after approval","Submit to the local council by March 31 each year and publish after it passes the review"],
 "Article 14: September 30, to the local committee, then published."),

(B,"第15條",2,"氣候法細則-調適原則",
 "各級政府推動氣候變遷調適方案及作為，應依循之基本原則不包括下列何者？",
 ["以碳費收入之多寡決定各地區調適經費之分配比例並優先補助工業區","以科學為基礎，檢視現有及最新資料、推估未來氣候變遷並評估其風險","發展因地制宜、由下而上或以社區、原住民族為本之氣候變遷調適作為","強化脆弱群體因應氣候變遷衝擊之能力，並充分考量人權之潛在影響"],"a",
 "第15條：調適方案及作為應依循三項基本原則：以科學為基礎並評估氣候變遷風險、發展因地制宜或由下而上及社區與原住民族為本之調適、強化脆弱群體因應能力並充分考量人權潛在影響。經費分配比例並非本條所定原則。",
 "Which is NOT a basic principle for government climate adaptation programmes?",
 ["Allocating adaptation budgets by carbon fee revenue and prioritizing industrial parks","Being science-based, reviewing current data, projecting change and assessing risk","Developing locally tailored, bottom-up, community- or indigenous-based adaptation","Strengthening vulnerable groups' capacity and fully considering human rights impacts"],
 "Article 15 lists three principles; budget allocation is not one."),

(B,"第16條",2,"氣候法細則-調適行動方案",
 "中央目的事業主管機關訂修易受氣候變遷衝擊權責領域調適行動方案及調適目標，應於何時送中央主管機關？",
 ["應於易受氣候變遷衝擊之權責領域確定後一年內送中央主管機關","應於易受氣候變遷衝擊之權責領域確定後六個月內送中央主管機關","應於國家氣候變遷調適行動計畫核定後三個月內送中央主管機關","應於階段管制目標經行政院核定後八個月內送中央主管機關辦理"],"a",
 "第16條：調適行動方案及調適目標應於易受氣候變遷衝擊之權責領域確定後一年內送中央主管機關；其內容包括領域範疇及執行現況、氣候變遷衝擊情形、未來情境設定及風險評估、調適目標、推動策略措施及檢討、永續發展目標關聯性、推動期程及經費編列、預期效益及管考機制等八項。",
 "By when must sectoral adaptation action plans be submitted to the central authority?",
 ["Within one year after the vulnerable sector under its jurisdiction is determined","Within six months after the vulnerable sector under its jurisdiction is determined","Within three months after the national climate adaptation action plan is approved","Within eight months after the phased control target is approved by the Executive Yuan"],
 "Article 16: within one year of determining the sector."),

(B,"第17條",2,"氣候法細則-國家調適計畫",
 "中央主管機關就國家氣候變遷調適行動計畫之執行情形，應於何時向行政院報告？",
 ["應於各期國家調適計畫結束後次年十一月三十日前報告前一期執行情形","應於各期國家調適計畫結束後次次年十一月三十日前報告前一期執行情形","應於各期國家調適計畫執行期間每年八月三十一日前報告當年執行情形","應於各期國家調適計畫結束後三個月內報告前一期之整體執行情形"],"a",
 "第17條第3項：中央主管機關應於各期國家調適計畫結束後次年十一月三十日前，向行政院報告前一期之執行情形。相對地，第6條第3項階段管制目標之達成情形報告則為結束後次次年十一月三十日前。",
 "By when must the central authority report on a completed national adaptation plan period?",
 ["By November 30 of the year following the end of each national adaptation plan period","By November 30 of the second year following the end of each adaptation plan period","By August 31 of each year during the implementation of the adaptation plan period","Within three months after the end of each national adaptation plan period"],
 "Article 17-3: by November 30 of the following year."),

(B,"第18條",2,"氣候法細則-調適成果報告",
 "中央目的事業主管機關編寫調適行動方案成果報告，其期限及程序為何？",
 ["應於每年八月三十一日前送中央主管機關，報請行政院核定後公開之","應於每年九月三十日前送中央主管機關，報請行政院核定後公開之","應於每年十一月三十日前送中央主管機關，經其備查後對外公開之","應於每年三月三十一日前送中央主管機關，由該機關彙整後公開之"],"a",
 "第18條：調適行動方案成果報告應於每年八月三十一日前送中央主管機關，報請行政院核定後公開之；內容包括摘要、該領域推動進度及調適目標執行狀況、分析及檢討、經費執行情形、未來規劃及需求。第8條之部門行動方案成果報告則為九月三十日前。",
 "What is the deadline and procedure for the sectoral adaptation results report?",
 ["Submit to the central authority by August 31 each year and publish after Executive Yuan approval","Submit to the central authority by September 30 each year and publish after Executive Yuan approval","Submit to the central authority by November 30 each year and publish after it is filed for reference","Submit to the central authority by March 31 each year and publish after it compiles the reports"],
 "Article 18: August 31, with Executive Yuan approval."),

(B,"第19條",3,"氣候法細則-調適執行方案",
 "直轄市、縣（市）主管機關訂修氣候變遷調適執行方案之期限及檢討頻率為何？",
 ["應於調適行動方案及國家調適計畫核定後一年內送推動會報請核定，且每四年至少檢討一次","應於調適行動方案及國家調適計畫核定後八個月內送推動會報請核定，每五年至少檢討一次","應於調適行動方案及國家調適計畫核定後六個月內送推動會報請核定，每三年至少檢討一次","應於調適行動方案及國家調適計畫核定後二年內送推動會報請核定，每二年至少檢討一次"],"a",
 "第19條：調適執行方案應於調適行動方案及國家調適計畫核定後一年內，送直轄市、縣（市）氣候變遷因應推動會，報請中央主管機關會商中央目的事業主管機關核定後實施並公開，且每四年至少檢討一次。第13條減量執行方案則為八個月內、每五年檢討一次。",
 "What are the deadline and review cycle for the local climate adaptation implementation plan?",
 ["Within one year after the sectoral and national adaptation plans are approved, reviewed at least every four years","Within eight months after the sectoral and national adaptation plans are approved, reviewed at least every five years","Within six months after the sectoral and national adaptation plans are approved, reviewed at least every three years","Within two years after the sectoral and national adaptation plans are approved, reviewed at least every two years"],
 "Article 19: one year, with a four-year review cycle."),

(B,"第20條",2,"氣候法細則-調適執行成果",
 "直轄市、縣（市）主管機關編寫調適執行方案成果報告，其期限為何？",
 ["應於完整執行年度後每年八月三十一日前送推動會後公開之","應於完整執行年度後每年九月三十日前送推動會後公開之","應於完整執行年度後每年十一月三十日前送推動會後公開","應於完整執行年度後每年三月三十一日前送推動會後公開"],"a",
 "第20條：調適執行方案成果報告應於完整執行年度後每年八月三十一日前，送直轄市、縣（市）氣候變遷因應推動會後公開之；內容包括摘要、整體進度及執行情形、分析及檢討、未來推動規劃。第14條減量執行方案成果報告則為每年九月三十日前。",
 "By when must the local adaptation implementation results report be submitted and published?",
 ["By August 31 each year after a full implementation year, to the committee, then published","By September 30 each year after a full implementation year, to the committee, then published","By November 30 each year after a full implementation year, to the committee, then published","By March 31 each year after a full implementation year, to the committee, then published"],
 "Article 20: August 31 after a full implementation year."),

(B,"第21條",2,"氣候法細則-公聽會公開",
 "中央目的事業主管機關依本法第十一條或第十九條召開公聽會時，方案初稿內容及開會資訊應於何時公開周知？",
 ["應於會議舉行十日前公開周知，並將會議紀錄一併公開之","應於會議舉行七日前公開周知，並將會議紀錄一併公開之","應於會議舉行三十日前公開周知，並將會議紀錄一併公開","應於會議結束後十日內公開周知，並將會議紀錄一併公開"],"a",
 "第21條：召開公聽會程序時應將部門行動方案或調適行動方案初稿內容、開會資訊、會議紀錄公開之；初稿內容及開會資訊應於會議舉行十日前公開周知。第22條地方舉辦座談會則為舉辦七日前。",
 "How far in advance must the draft and meeting information be made public before the hearing?",
 ["Ten days before the meeting, with the minutes also to be made public","Seven days before the meeting, with the minutes also to be made public","Thirty days before the meeting, with the minutes also to be made public","Within ten days after the meeting, with the minutes also made public"],
 "Article 21: ten days in advance."),

(B,"第22條",2,"氣候法細則-座談會公開",
 "直轄市、縣（市）主管機關舉辦座談會或以其他適當方法廣詢意見時，初稿內容及開會資訊應於何時公開周知？",
 ["應於舉辦七日前公開周知，並將廣詢方法及紀錄一併公開之","應於舉辦十日前公開周知，並將廣詢方法及紀錄一併公開之","應於舉辦三十日前公開周知，並將廣詢方法及紀錄一併公開","應於舉辦後七日內公開周知，並將廣詢方法及紀錄一併公開"],"a",
 "第22條：直轄市、縣（市）主管機關依本法第十五條或第二十條舉辦座談會或以其他適當方法廣詢意見時，應將減量執行方案或調適執行方案之初稿內容、開會資訊或其他適當廣詢方法、紀錄公開之，並於舉辦七日前公開周知。",
 "How far in advance must local authorities publicize a forum's draft and meeting information?",
 ["Seven days before it is held, with the consultation method and records also made public","Ten days before it is held, with the consultation method and records also made public","Thirty days before it is held, with the consultation method and records also made public","Within seven days after it is held, with the method and records also made public"],
 "Article 22: seven days in advance."),

(B,"第23條",1,"氣候法細則-公聽會紀錄",
 "中央主管機關依本法第十條第二項舉辦公聽會，其會議紀錄應如何處理？",
 ["其會議紀錄應對外公開","其會議紀錄應列為密件保存","其會議紀錄應送立法院備查","其會議紀錄應僅供出席者索閱"],"a",
 "第23條：中央主管機關依本法第十條第二項規定舉辦公聽會之會議紀錄應公開之。依第24條規定，本細則所定應公開之事項，除另有規定外，應於辦理完成或核定後三十日內公開於中央主管機關指定網站。",
 "How must the minutes of the central authority's public hearing be handled?",
 ["The minutes shall be made public","The minutes shall be kept confidential","The minutes shall be filed with the Legislative Yuan","The minutes shall be available only to attendees"],
 "Article 23 requires publication of the minutes."),

(B,"第24條",2,"氣候法細則-公開期限",
 "本細則所定應公開之事項，除另有規定外，應於何時、以何種方式公開？",
 ["應於辦理完成或核定後三十日內，公開於中央主管機關指定網站","應於辦理完成或核定後六十日內，公開於中央主管機關指定網站","應於辦理完成或核定後十四日內，刊登於政府公報及全國性報紙","應於辦理完成或核定後九十日內，公開於各該機關之公布欄陳列"],"a",
 "第24條：本細則所定應公開之事項，除另有規定外，應於辦理完成或核定後三十日內，公開於中央主管機關指定網站。第21條至第23條就公聽會、座談會及其紀錄之公開另有特別規定。",
 "When and how must matters required to be disclosed under these Rules be published?",
 ["Within thirty days of completion or approval, on the website designated by the central authority","Within sixty days of completion or approval, on the website designated by the central authority","Within fourteen days of completion or approval, in the government gazette and national newspapers","Within ninety days of completion or approval, on the notice board of the agency concerned"],
 "Article 24: within thirty days, on the designated website."),

(B,"第25條",1,"氣候法細則-施行日",
 "氣候變遷因應法施行細則之施行日期規定為何？",
 ["本細則自發布日起施行","本細則自發布後六個月施行","本細則自一百十三年元旦施行","本細則自發布後一年之次日施行"],"a",
 "第25條：本細則自發布日施行，其現行條文修正日期為民國一百十二年十二月二十九日。相對地，溫室氣體排放量盤查登錄及查驗管理辦法第17條則規定自中華民國一百十三年一月一日施行。",
 "When do the Enforcement Rules of the Climate Change Response Act take effect?",
 ["On the date of promulgation","Six months after promulgation","On January 1, 2024","The day after one year from promulgation"],
 "Article 25: effective upon promulgation."),
]
