# -*- coding: utf-8 -*-
# 第 12 批（E2）：民用航空器噪音管制標準（ENV-109）、陸上運輸系統噪音管制標準（ENV-130）、
#                 違反噪音管制法按日連續處罰執行準則（ENV-138）、海洋放流管線放流水標準（ENV-154）
# ※ 四個選項刻意寫成相近長度。
Q = [

# ── ENV-109 民用航空器噪音管制標準（9 條）──────────────────────
("ENV-109","第1條",1,"航空器噪音-法源",
 "民用航空器噪音管制標準之訂定法源為何？",
 ["依噪音管制法第十一條第一項規定訂定",
  "依噪音管制法第十四條第二項規定訂定",
  "依民用航空法第三十四條第一項規定訂定",
  "依噪音管制法第三十五條第二項規定訂定"],"a",
 "第1條：本標準依噪音管制法第十一條第一項規定訂定。噪音管制法第十四條第二項則為陸上運輸系統噪音管制標準之法源，第三十五條第二項為按日連續處罰執行準則之法源，應予區別。",
 "What is the legal basis of the Noise Control Standards for Civil Aircraft?",
 ["Adopted under Article 11, Paragraph 1 of the Noise Control Act",
  "Adopted under Article 14, Paragraph 2 of the Noise Control Act",
  "Adopted under Article 34, Paragraph 1 of the Civil Aviation Act",
  "Adopted under Article 35, Paragraph 2 of the Noise Control Act"],
 "Article 1."),

("ENV-109","第2條",2,"航空器噪音-測定依據",
 "民用航空器音量之測定依據為何？其評定指標與單位為何？",
 ["依國際標準組織 ISO 三八九一號規定，以有效覺察音量（EPN）、A 權最大音量或噪音曝露位準（SEL）評定，單位為 EPN、LAmax 及 SEL 分貝",
  "依國際標準組織 ISO 三八九一號規定，以八音度頻帶音壓級、C 權平均音量或音功率位準評定，單位分別為 dB、LCeq 分貝及 PWL 分貝",
  "依國際民航組織第十六號附約規定，以有效覺察音量（EPN）、日夜平均音量或百分位音量評定，單位分別為 EPN 分貝、Ldn 分貝及 L10 分貝",
  "依中華民國國家標準 CNS 七一二九規定，以小時均能音量、平均最大音量或事件音量評定，單位分別為 Leq 分貝、Lmax 分貝及 SEL 分貝"],"a",
 "第2條：民用航空器音量之測定依據國際標準組織（ISO）三八九一號規定之有效覺察音量測量（EPN）、A 權最大音量或噪音曝露位準（SEL）評定之，單位分別為 EPN 分貝、LAmax 分貝及 SEL 分貝。第8條並規定航空器噪音量測量程序及計算方式依國際民航公約第十六號附約辦理。",
 "What is the basis for measuring civil aircraft noise, and which indicators and units apply?",
 ["ISO 3891, evaluated by effective perceived noise (EPN), A-weighted maximum level or sound exposure level (SEL), in EPNdB, LAmaxdB and SELdB",
  "ISO 3891, evaluated by octave band sound pressure level, C-weighted average level, or sound power level, in dB, LCeqdB and PWLdB",
  "ICAO Annex 16, evaluated by effective perceived noise (EPN), day-night average level, or percentile level, in EPNdB, LdndB and L10dB",
  "CNS 7129, evaluated by hourly equivalent level, mean maximum level, or event level, in LeqdB, LmaxdB and SELdB"],
 "Article 2; see also Article 8."),

("ENV-109","第3條",3,"航空器噪音-次音速噴射機",
 "中華民國六十六年十月五日以前申請原型機適航證書之次音速噴射飛機，其噪音管制標準值為何？",
 ["起飛重量大於或等於二七二、○○○公斤重者，進場、橫向及起飛音量均為 108 EPN 分貝；小於或等於三四、○○○公斤重者，進場與橫向為 102、起飛為 93 EPN 分貝",
  "起飛重量大於或等於二七二、○○○公斤重者，進場、橫向及起飛音量均為 102 EPN 分貝；小於或等於三四、○○○公斤重者，進場與橫向為 93、起飛為 88 EPN 分貝",
  "起飛重量大於或等於三四、○○○公斤重者，進場、橫向及起飛音量均為 108 EPN 分貝；小於或等於二七、二○○公斤重者，進場與橫向為 102、起飛為 93 EPN 分貝",
  "起飛重量大於或等於二七二、○○○公斤重者，進場為 108、橫向為 102、起飛為 93 EPN 分貝；小於或等於三四、○○○公斤重者，三個測點均為 91 EPN 分貝"],"a",
 "第3條表：六十六年十月五日以前申請原型機適航證書之次音速噴射飛機，起飛重量大於或等於二七二、○○○公斤重者，進場、橫向、起飛音量均為 108；小於或等於三四、○○○公斤重者，進場與橫向為 102、起飛為 93。介於兩者之間，進場與橫向為 91.83＋6.64 log M、起飛為 67.56＋16.61 log M，M 為最大起飛重量（千公斤重），單位為 EPN 分貝。",
 "What are the noise limits for subsonic jets whose prototype airworthiness certificate was applied for before 5 October 1977?",
 ["For takeoff weight 272,000 kg or more, approach, sideline and takeoff are all 108 EPNdB; for 34,000 kg or less, approach and sideline are 102 and takeoff 93 EPNdB",
  "For takeoff weight 272,000 kg or more, approach, sideline and takeoff are all 102 EPNdB; for 34,000 kg or less, approach and sideline are 93 and takeoff 88 EPNdB",
  "For takeoff weight 34,000 kg or more, approach, sideline and takeoff are all 108 EPNdB; for 27,200 kg or less, approach and sideline are 102 and takeoff 93 EPNdB",
  "For takeoff weight 272,000 kg or more, approach is 108, sideline 102 and takeoff 93 EPNdB; for 34,000 kg or less, all three points are 91 EPNdB"],
 "Article 3, table."),

("ENV-109","第3條",3,"航空器噪音-測量點",
 "依本標準備註，進場、橫向及起飛音量之測量點位置分別為何？",
 ["進場為自跑道頭向外延伸二、○○○公尺、垂直高度一二○公尺處；橫向為距跑道中心線六五○公尺之平行位置；起飛為自跑道中心線向外延伸六．五公里處",
  "進場為自跑道頭向外延伸一、○○○公尺、垂直高度三○○公尺處；橫向為距跑道中心線四五○公尺之平行位置；起飛為自跑道中心線向外延伸二．五公里處",
  "進場為自跑道頭向內三○○公尺、垂直高度六五○公尺處；橫向為距跑道中心線一五○公尺之平行位置；起飛為自跑道中心線向外延伸一○公里處",
  "進場為自跑道頭向外延伸二、○○○公尺、垂直高度一二○公尺處；橫向為距跑道中心線九○○公尺之平行位置；起飛為自跑道中心線向外延伸三公里處"],"a",
 "第3條備註：進場音量測量點自跑道頭向內三○○公尺（即著陸點）起，三度下滑角、一二○公尺（三九四呎）垂直高度位置點，即自跑道頭向外延伸二、○○○公尺位置；橫向音量測量點為距跑道中心線六五○公尺之平行位置；起飛音量測量點自跑道中心線向外延伸至六．五公里之位置。第5條備註則將橫向平行距離改為四五○公尺。",
 "Under the notes to this standard, where are the approach, sideline and takeoff measuring points?",
 ["Approach 2,000 m beyond the runway threshold at 120 m height; sideline 650 m parallel to the runway centerline; takeoff 6.5 km along the centerline",
  "Approach 1,000 m beyond the runway threshold at 300 m height; sideline 450 m parallel to the runway centerline; takeoff 2.5 km along the centerline",
  "Approach 300 m inside the runway threshold at 650 m height; sideline 150 m parallel to the runway centerline; takeoff 10 km along the centerline",
  "Approach 2,000 m beyond the runway threshold at 120 m height; sideline 900 m parallel to the runway centerline; takeoff 3 km along the centerline"],
 "Article 3, notes."),

("ENV-109","第4條",3,"航空器噪音-重新修改機型",
 "六十六年十月五日以前曾申請原型機適航證書並於七十年十一月二十六日以後重新修改機型設計之次音速噴射飛機，其進場與橫向音量之上、下限值為何？",
 ["進場音量上限值二八○、○○○公斤重為 108、下限值三五、○○○公斤重為 101；橫向音量上限值四○○、○○○公斤重為 106、下限值三五、○○○公斤重為 97",
  "進場音量上限值二八○、○○○公斤重為 105、下限值三五、○○○公斤重為 98；橫向音量上限值四○○、○○○公斤重為 103、下限值三五、○○○公斤重為 94",
  "進場音量上限值四○○、○○○公斤重為 108、下限值四八、三○○公斤重為 101；橫向音量上限值二八○、○○○公斤重為 106、下限值四八、三○○公斤重為 97",
  "進場音量上限值二八○、○○○公斤重為 110、下限值三五、○○○公斤重為 104；橫向音量上限值四○○、○○○公斤重為 108、下限值三五、○○○公斤重為 99"],"a",
 "第4條表：進場音量上限值二八○、○○○公斤重為 108、下限值三五、○○○公斤重為 101，中間為 89.03＋7.75 log M；橫向音量上限值四○○、○○○公斤重為 106、下限值三五、○○○公斤重為 97，中間為 83.87＋8.51 log M。起飛音量另依引擎數目分二具以下（104／93）、三具（107／93）、四具以上（108／93）規定，單位均為 EPN 分貝。",
 "For subsonic jets certificated before 5 Oct 1977 but redesigned after 26 Nov 1981, what are the upper and lower approach and sideline limits?",
 ["Approach: 108 at the 280,000 kg upper weight and 101 at the 35,000 kg lower weight; sideline: 106 at the 400,000 kg upper weight and 97 at the 35,000 kg lower weight",
  "Approach: 105 at the 280,000 kg upper weight and 98 at the 35,000 kg lower weight; sideline: 103 at the 400,000 kg upper weight and 94 at the 35,000 kg lower weight",
  "Approach: 108 at the 400,000 kg upper weight and 101 at the 48,300 kg lower weight; sideline: 106 at the 280,000 kg upper weight and 97 at the 48,300 kg lower weight",
  "Approach: 110 at the 280,000 kg upper weight and 104 at the 35,000 kg lower weight; sideline: 108 at the 400,000 kg upper weight and 99 at the 35,000 kg lower weight"],
 "Article 4, table."),

("ENV-109","第5條",3,"航空器噪音-新申請機型",
 "六十六年十月六日以後申請原型機適航證書之次音速噴射飛機，其管制標準與測量點有何特徵？",
 ["進場上限 105、下限 98，橫向上限 103、下限 94，起飛二具以下上限 101、下限 89；橫向平行距離改為四五○公尺，其餘測量點同第三條備註",
  "進場上限 108、下限 101，橫向上限 106、下限 97，起飛二具以下上限 104、下限 93；橫向平行距離改為四五○公尺，其餘測量點同第三條備註",
  "進場上限 105、下限 98，橫向上限 103、下限 94，起飛二具以下上限 101、下限 89；橫向平行距離仍為六五○公尺，其餘測量點同第三條備註",
  "進場上限 102、下限 93，橫向上限 100、下限 91，起飛二具以下上限 98、下限 86；橫向平行距離改為三○○公尺，其餘測量點同第三條備註"],"a",
 "第5條表：進場音量上限值二八○、○○○公斤重為 105、下限值三五、○○○公斤重為 98；橫向音量上限值四○○、○○○公斤重為 103、下限值三五、○○○公斤重為 94；起飛音量二具引擎以下上限值三八五、○○○公斤重為 101、下限值四八、一○○公斤重為 89，三具為 104／89、四具以上為 106／89。備註一並載明各測量點除橫向平行距離為四五○公尺外，其餘同第3條備註。",
 "For subsonic jets whose prototype certificate was applied for on or after 6 Oct 1977, what limits and measuring points apply?",
 ["Approach 105/98, sideline 103/94, takeoff with two or fewer engines 101/89; the sideline parallel distance becomes 450 m, other points as in Article 3 notes",
  "Approach 108/101, sideline 106/97, takeoff with two or fewer engines 104/93; the sideline parallel distance becomes 450 m, other points as in Article 3 notes",
  "Approach 105/98, sideline 103/94, takeoff with two or fewer engines 101/89; the sideline parallel distance stays 650 m, other points as in Article 3 notes",
  "Approach 102/93, sideline 100/91, takeoff with two or fewer engines 98/86; the sideline parallel distance becomes 300 m, other points as in Article 3 notes"],
 "Article 5, table and notes."),

("ENV-109","第6條",3,"航空器噪音-螺旋槳飛機",
 "七十三年十二月三十一日以前申請原型機適航證書、最大起飛重量五、七○○公斤重以上之螺旋槳飛機，其管制標準為何？",
 ["進場音量三八四、七○○公斤重以上為 105、三四、○○○公斤重以下為 98；橫向為 103／96；起飛音量三五八、九○○公斤重以上為 106、三四、○○○公斤重以下為 89",
  "進場音量三八四、七○○公斤重以上為 108、三四、○○○公斤重以下為 102；橫向為 106／99；起飛音量三五八、九○○公斤重以上為 108、三四、○○○公斤重以下為 93",
  "進場音量三五八、九○○公斤重以上為 105、三四、○○○公斤重以下為 98；橫向為 96／103；起飛音量三八四、七○○公斤重以上為 89、三四、○○○公斤重以下為 106",
  "進場音量三八四、七○○公斤重以上為 103、二七、二○○公斤重以下為 96；橫向為 101／94；起飛音量三五八、九○○公斤重以上為 104、二七、二○○公斤重以下為 87"],"a",
 "第6條第一款表：進場音量起飛重量大於或等於三八四、七○○公斤重為 105、小於或等於三四、○○○公斤重為 98，中間為 87.83＋6.64 log M；橫向音量為 103／96，中間為 85.83＋6.64 log M；起飛音量大於或等於三五八、九○○公斤重為 106、小於或等於三四、○○○公斤重為 89，中間為 63.56＋16.61 log M；單位為 EPN 分貝。",
 "What limits apply to propeller aircraft over 5,700 kg certificated before 31 December 1984?",
 ["Approach 105 at 384,700 kg or more and 98 at 34,000 kg or less; sideline 103/96; takeoff 106 at 358,900 kg or more and 89 at 34,000 kg or less",
  "Approach 108 at 384,700 kg or more and 102 at 34,000 kg or less; sideline 106/99; takeoff 108 at 358,900 kg or more and 93 at 34,000 kg or less",
  "Approach 105 at 358,900 kg or more and 98 at 34,000 kg or less; sideline 96/103; takeoff 89 at 384,700 kg or more and 106 at 34,000 kg or less",
  "Approach 103 at 384,700 kg or more and 96 at 27,200 kg or less; sideline 101/94; takeoff 104 at 358,900 kg or more and 87 at 27,200 kg or less"],
 "Article 6, subparagraph 1."),

("ENV-109","第6條",3,"航空器噪音-小型螺旋槳機",
 "七十七年十一月十六日以前申請原型機適航證書、最大起飛重量八、六一八公斤重以下之螺旋槳飛機，其管制標準及測量方式為何？",
 ["一、五○○公斤重以上為 80、六○○公斤重以下為 68 LAmax 分貝；飛機保持高度三○○至三○公尺水平飛行通過測點上空，於測點垂直線範圍正負十度內通過",
  "一、五○○公斤重以上為 88、六○○公斤重以下為 76 LAmax 分貝；飛機保持高度三○○至三○公尺水平飛行通過測點上空，於測點垂直線範圍正負三十度內通過",
  "一、四○○公斤重以上為 80、五七○公斤重以下為 68 EPN 分貝；飛機保持高度一五○至三○公尺水平飛行通過測點上空，於測點垂直線範圍正負十度內通過",
  "一、五○○公斤重以上為 85、六○○公斤重以下為 70 SEL 分貝；飛機保持高度三○○至一二○公尺水平飛行通過測點上空，於測點垂直線範圍正負十度內通過"],"a",
 "第6條第三款表：起飛重量大於或等於一、五○○公斤重者為 80、小於或等於六○○公斤重者為 68，介於六○○至一、五○○公斤重間為 68＋13.33 M；備註載明飛機保持高度三○○至三○公尺通過測點上空水平飛行，在測點垂直線範圍正負十度內通過，單位為 LAmax 分貝。第五款（七十七年十一月十七日以後）之對應標準則為 88／76 及 85／70。",
 "What limits and measurement method apply to propeller aircraft of 8,618 kg or less certificated before 16 November 1988?",
 ["80 at 1,500 kg or more and 68 at 600 kg or less in LAmax dB; the aircraft flies level 300 to 30 m above the point, passing within plus or minus 10 degrees of the vertical",
  "88 at 1,500 kg or more and 76 at 600 kg or less in LAmax dB; the aircraft flies level 300 to 30 m above the point, passing within plus or minus 30 degrees of the vertical",
  "80 at 1,400 kg or more and 68 at 570 kg or less in EPN dB; the aircraft flies level 150 to 30 m above the point, passing within plus or minus 10 degrees of the vertical",
  "85 at 1,500 kg or more and 70 at 600 kg or less in SEL dB; the aircraft flies level 300 to 120 m above the point, passing within plus or minus 10 degrees of the vertical"],
 "Article 6, subparagraph 3."),

("ENV-109","第6條",2,"航空器噪音-競合與除外",
 "螺旋槳飛機同時符合第六條第一項第一款及第三款情形時如何適用？何種用途之螺旋槳飛機不適用？",
 ["同時符合第一款及第三款者得擇一適用，同時符合第二款及第三款者亦同；特技、特殊活動、農業及救火用之螺旋槳飛機不適用",
  "同時符合第一款及第三款者應從嚴適用較低標準值，同時符合第二款及第三款者亦同；教練、觀光及商務用之螺旋槳飛機不適用",
  "同時符合第一款及第三款者得擇一適用，同時符合第二款及第三款者亦同；軍用、警用及海巡用之螺旋槳飛機一律不適用",
  "同時符合第一款及第三款者應由民航主管機關指定適用款次；特技、特殊活動及貨運用之螺旋槳飛機得申請免除適用"],"a",
 "第6條第二項：同時符合前項第一款及第三款之情形者，得擇一適用；同時符合前項第二款及第三款者亦同。第三項：第一項噪音管制標準不適用於特技、特殊活動、農業及救火用之螺旋槳飛機。第7條第二項對直昇機飛機亦有相同之除外規定。",
 "If a propeller aircraft meets both subparagraphs 1 and 3, which applies, and which uses are exempt?",
 ["Where subparagraphs 1 and 3 both apply, either may be chosen, as with 2 and 3; aerobatic, special-activity, agricultural and firefighting aircraft are exempt",
  "Where both subparagraphs 1 and 3 apply, the stricter limit governs, and the same holds for 2 and 3; training, sightseeing and business aircraft are exempt",
  "Where both subparagraphs 1 and 3 apply, either may be chosen, and the same holds for 2 and 3; military, police and coast guard aircraft are all exempt",
  "Where both subparagraphs 1 and 3 apply, the aviation authority designates which governs; aerobatic, special-activity and cargo aircraft may seek exemption"],
 "Article 6, Paragraphs 2 and 3."),

("ENV-109","第7條",3,"航空器噪音-直昇機",
 "七十三年十二月三十一日以後申請原型機適航證書之直昇機飛機，其起飛、進場及滯空音量標準值為何？",
 ["起飛重量八○、○○○公斤重以上者起飛 109、進場 110、滯空 108；七八八公斤重以下者起飛 89、進場 90、滯空 88 EPN 分貝",
  "起飛重量八○、○○○公斤重以上者起飛 106、進場 109、滯空 104；七八八公斤重以下者起飛 86、進場 89、滯空 84 EPN 分貝",
  "起飛重量八○、○○○公斤重以上者起飛 110、進場 109、滯空 108；七八八公斤重以下者起飛 90、進場 89、滯空 88 SEL 分貝",
  "起飛重量三、一七五公斤重以上者起飛 109、進場 110、滯空 108；一、四一七公斤重以下者起飛 89、進場 90、滯空 82 EPN 分貝"],"a",
 "第7條第一款表：起飛重量大於或等於八○、○○○公斤重者，起飛音量 109、進場音量 110、滯空音量 108；小於或等於七八八公斤重者分別為 89、90、88，中間各為 90.03、91.03、89.03＋9.97 log M，單位為 EPN 分貝。第二款（九十一年三月二十一日以後）則加嚴為起飛 106／86、進場 109／89、滯空 104／84。",
 "What are the takeoff, approach and flyover limits for helicopters certificated after 31 December 1984?",
 ["At 80,000 kg or more: takeoff 109, approach 110, flyover 108; at 788 kg or less: takeoff 89, approach 90, flyover 88 EPNdB",
  "At 80,000 kg or more: takeoff 106, approach 109, flyover 104; at 788 kg or less: takeoff 86, approach 89, flyover 84 EPNdB",
  "At 80,000 kg or more: takeoff 110, approach 109, flyover 108; at 788 kg or less: takeoff 90, approach 89, flyover 88 SELdB",
  "At 3,175 kg or more: takeoff 109, approach 110, flyover 108; at 1,417 kg or less: takeoff 89, approach 90, flyover 82 EPNdB"],
 "Article 7, subparagraph 1."),

("ENV-109","第7條",3,"航空器噪音-輕型直昇機",
 "最大起飛重量三、一七五公斤重以下直昇機之滯空音量標準，依申請時間有何不同？",
 ["八十二年十一月十一日以後者，七八八公斤重以下為 82；九十一年三月二十一日以後者，一、四一七公斤重以下為 82，單位均為 SEL 分貝",
  "八十二年十一月十一日以後者，一、四一七公斤重以下為 82；九十一年三月二十一日以後者，七八八公斤重以下為 82，單位均為 SEL 分貝",
  "八十二年十一月十一日以後者，七八八公斤重以下為 88；九十一年三月二十一日以後者，一、四一七公斤重以下為 84，單位均為 EPN 分貝",
  "八十二年十一月十一日以後者，七八八公斤重以下為 80；九十一年三月二十一日以後者，一、四一七公斤重以下為 76，單位均為 LAmax 分貝"],"a",
 "第7條第三款：八十二年十一月十一日以後申請原型機或重新修改機型設計、最大起飛重量三、一七五公斤重以下之直昇機，滯空音量七八八公斤重以下為 82，大於七八八公斤重為 83.03＋9.97 log M。第四款：九十一年三月二十一日以後者，一、四一七公斤重以下為 82，大於一、四一七公斤重為 80.49＋9.97 log M；單位均為 SEL 分貝，滯空音量測量點位於飛行航道高度一五○公尺下方。",
 "How does the flyover limit for helicopters of 3,175 kg or less differ by application date?",
 ["From 11 Nov 1993, it is 82 for 788 kg or less; from 21 Mar 2002, it is 82 for 1,417 kg or less, both in SELdB",
  "From 11 Nov 1993, it is 82 for 1,417 kg or less; from 21 Mar 2002, it is 82 for 788 kg or less, both in SELdB",
  "From 11 Nov 1993, it is 88 for 788 kg or less; from 21 Mar 2002, it is 84 for 1,417 kg or less, both in EPNdB",
  "From 11 Nov 1993, it is 80 for 788 kg or less; from 21 Mar 2002, it is 76 for 1,417 kg or less, both in LAmaxdB"],
 "Article 7, subparagraphs 3 and 4."),

("ENV-109","第8條",1,"航空器噪音-測量程序",
 "航空器噪音量之測量程序及計算方式應依何規定辦理？",
 ["依國際民航公約第十六號附約規定辦理",
  "依國際標準組織第三八九一號規定辦理",
  "依中華民國國家標準第七一二九號辦理",
  "依民用航空局所定之作業要點來辦理"],"a",
 "第8條：航空器噪音量測量程序及計算方式，依國際民航公約第十六號附約規定辦理。第2條則規定音量之測定依據國際標準組織（ISO）三八九一號規定之 EPN、A 權最大音量或 SEL 評定，兩者分工不同。",
 "Under what rules are aircraft noise measurement procedures and calculations carried out?",
 ["Under Annex 16 to the Convention on International Civil Aviation",
  "Under International Organization for Standardization No. 3891",
  "Under Chinese National Standard No. 7129 on sound level meters",
  "Under operating directions set by the Civil Aeronautics Administration"],
 "Article 8."),

("ENV-109","第9條",1,"航空器噪音-施行",
 "本標準之施行日期如何規定？",
 ["本標準自發布日起施行","本標準自公告日次月施行","本標準自核定後一年施行","本標準自次年元旦日施行"],"a",
 "第9條：本標準自發布日施行。本標準最近一次修正日期為民國九十八年七月十六日，各條表列標準值即自該時起適用。",
 "How does this standard specify its effective date?",
 ["It takes effect on the date of promulgation",
  "It takes effect the month after announcement",
  "It takes effect one year after approval",
  "It takes effect on 1 January of next year"],
 "Article 9."),

# ── ENV-130 陸上運輸系統噪音管制標準（9 條）─────────────────────
("ENV-130","第1條",1,"陸運噪音-法源",
 "陸上運輸系統噪音管制標準之訂定法源為何？",
 ["依噪音管制法第十四條第二項規定訂定",
  "依噪音管制法第十一條第一項規定訂定",
  "依噪音管制法第九條第三項規定訂定之",
  "依大眾捷運法第四十五條第二項規定訂定"],"a",
 "第1條：本標準依噪音管制法第十四條第二項規定訂定。噪音管制法第十一條第一項則為民用航空器噪音管制標準之法源，二者分別管制陸上運輸系統與航空器噪音。",
 "What is the legal basis of the Noise Control Standards for Land Transportation Systems?",
 ["Adopted under Article 14, Paragraph 2 of the Noise Control Act",
  "Adopted under Article 11, Paragraph 1 of the Noise Control Act",
  "Adopted under Article 9, Paragraph 3 of the Noise Control Act",
  "Adopted under Article 45, Paragraph 2 of the Mass Rapid Transit Act"],
 "Article 1."),

("ENV-130","第2條",2,"陸運噪音-時段區分",
 "本標準所定早、晚、日間及夜間之時段區分為何？",
 ["早指上午五時至上午七時、晚指晚上八時至晚上十時、日間指上午七時至晚上八時、夜間指晚上十時至翌日上午五時",
  "早指上午六時至上午八時、晚指晚上七時至晚上十時、日間指上午八時至晚上七時、夜間指晚上十時至翌日上午六時",
  "早指上午五時至上午七時、晚指晚上六時至晚上九時、日間指上午七時至晚上六時、夜間指晚上九時至翌日上午五時",
  "早指上午四時至上午七時、晚指晚上八時至晚上十一時、日間指上午七時至晚上八時、夜間指晚上十一時至翌日四時"],"a",
 "第2條第五款：早指上午五時至上午七時；晚指晚上八時至晚上十時；日間指上午七時至晚上八時；夜間指晚上十時至翌日上午五時。第4條至第8條之管制標準即分早晚、日間、夜間三欄列示。",
 "How does this standard divide the morning, evening, daytime and night periods?",
 ["Morning 05:00-07:00, evening 20:00-22:00, daytime 07:00-20:00, night 22:00 to 05:00 the next day",
  "Morning 06:00-08:00, evening 19:00-22:00, daytime 08:00-19:00, night 22:00 to 06:00 the next day",
  "Morning 05:00-07:00, evening 18:00-21:00, daytime 07:00-18:00, night 21:00 to 05:00 the next day",
  "Morning 04:00-07:00, evening 20:00-23:00, daytime 07:00-20:00, night 23:00 to 04:00 the next day"],
 "Article 2, subparagraph 5."),

("ENV-130","第2條",2,"陸運噪音-鐵路定義",
 "本標準所稱鐵路之定義及高速鐵路與一般鐵路之區分基準為何？",
 ["指以軌道或於軌道上空架設電線供動力車輛行駛及其有關設施；最高時速二百公里以上者為高速鐵路，低於二百公里者為一般鐵路",
  "指以軌道或於軌道上空架設電線供動力車輛行駛及其有關設施；最高時速一百五十公里以上者為高速鐵路，低於一百五十公里者為一般鐵路",
  "指以專用路線行駛並以密集班次大量輸送旅客之公共運輸系統；最高時速二百公里以上者為高速鐵路，低於二百公里者為一般鐵路",
  "指以軌道或於軌道上空架設電線供動力車輛行駛及其有關設施；營運長度三百公里以上者為高速鐵路，未達三百公里者為一般鐵路"],"a",
 "第2條第三款：鐵路指以軌道或於軌道上空架設電線，供動力車輛行駛及其有關之設施；其最高時速二百公里以上者為高速鐵路，低於二百公里者為一般鐵路。第四款另定義大眾捷運系統為使用專用動力車輛行駛於專用路線、以密集班次大量快速輸送旅客之公共運輸系統。一般鐵路依第6條、高速鐵路依第7條、大眾捷運依第8條分別適用不同標準值。",
 "How is railway defined, and how are high-speed and conventional railways distinguished?",
 ["Tracks or overhead lines for powered vehicles and related facilities; a top speed of 200 km/h or more is high-speed rail, below 200 km/h is conventional rail",
  "Tracks or overhead lines for powered vehicles and related facilities; a top speed of 150 km/h or more is high-speed rail, below 150 km/h is conventional rail",
  "A public transport system on exclusive routes carrying many passengers at frequent headways; 200 km/h or more is high-speed rail, below that conventional rail",
  "Tracks or overhead lines for powered vehicles and related facilities; a route length of 300 km or more is high-speed rail, under 300 km is conventional rail"],
 "Article 2, subparagraphs 3 and 4."),

("ENV-130","第3條",2,"陸運噪音-測量儀器",
 "陸上運輸系統交通噪音測定之儀器規格及測定高度為何？",
 ["須使用符合 CNS 七一二九之一型噪音計或 IEC 61672-1 Class 1 噪音計；聲音感應器應置於離地面或樓板延伸線一．二至一．五公尺之間",
  "須使用符合 CNS 七一二九之二型噪音計或 IEC 61672-1 Class 2 噪音計；聲音感應器應置於離地面或樓板延伸線一．二至一．五公尺之間",
  "須使用符合 CNS 七一二九之一型噪音計或 IEC 61672-1 Class 1 噪音計；聲音感應器應置於離地面或樓板延伸線三．○至五．○公尺之間",
  "須使用經中央主管機關型式認證之任一噪音計或音量計；聲音感應器應置於離地面或樓板延伸線零．五至一．○公尺之間"],"a",
 "第3條第一、二款：測量儀器須使用符合中華民國國家標準（CNS 7129）規定之一型噪音計或國際電工協會標準（IEC 61672-1）Class 1 噪音計；測定高度為聲音感應器置於離地面或樓板延伸線一．二至一．五公尺之間。第三款並規定由直轄市、縣（市）主管機關會同交通營運或管理機關（構）測量，室外測點應距周圍建築物牆面線及其他主要反射面一至二公尺。",
 "What instrument specification and measuring height apply to land transportation noise measurement?",
 ["A CNS 7129 Type 1 or IEC 61672-1 Class 1 sound level meter; the microphone is placed 1.2 to 1.5 m above the ground or floor extension line",
  "A CNS 7129 Type 2 or IEC 61672-1 Class 2 sound level meter; the microphone is placed 1.2 to 1.5 m above the ground or floor extension line",
  "A CNS 7129 Type 1 or IEC 61672-1 Class 1 sound level meter; the microphone is placed 3.0 to 5.0 m above the ground or floor extension line",
  "Any sound level meter type-approved by the central authority; the microphone is placed 0.5 to 1.0 m above the ground or floor extension line"],
 "Article 3, subparagraphs 1 to 3."),

("ENV-130","第3條",3,"陸運噪音-動特性與時間",
 "測量道路系統與軌道系統交通噪音之動特性及測量時間規定為何？",
 ["道路系統使用快特性、軌道系統使用慢特性；於陳情人指定時段連續測定，未指定時段則進行二十四小時連續測定",
  "道路系統使用慢特性、軌道系統使用快特性；於陳情人指定時段連續測定，未指定時段則進行二十四小時連續測定",
  "道路系統使用快特性、軌道系統使用慢特性；於陳情人指定時段連續測定，未指定時段則進行八小時之連續測定",
  "道路與軌道系統均使用脈衝特性；於主管機關指定時段連續測定，未指定時段則進行四十八小時之連續測定"],"a",
 "第3條第四款：測量道路系統交通噪音使用快特性（FAST），測量軌道系統交通噪音使用慢特性（SLOW）。第五款：於陳情人指定時段進行連續測定；陳情人未指定時段則進行二十四小時連續測定。第六款並規定道路系統須測小時均能音量，軌道系統須測小時均能音量及平均最大音量。",
 "What time weighting and measurement duration apply to road and rail traffic noise?",
 ["FAST for road systems and SLOW for rail systems; continuous measurement in the period the complainant designates, or 24 hours continuously if none is designated",
  "SLOW for road systems and FAST for rail systems; continuous measurement in the period the complainant designates, or 24 hours continuously if none is designated",
  "FAST for road systems and SLOW for rail systems; continuous measurement in the period the complainant designates, or 8 hours continuously if none is designated",
  "IMPULSE for both road and rail systems; continuous measurement in the period the authority designates, or 48 hours continuously if none is designated"],
 "Article 3, subparagraphs 4 to 6."),

("ENV-130","第3條",3,"陸運噪音-背景音量修正",
 "測量地點背景音量之要求及整體音量與背景音量差值之處理方式為何？",
 ["背景音量至少與測定音源音量相差十分貝以上；差值介於三至九分貝時依表修正或以能量相減計算；差值小於三分貝時應停止測量另尋適當地點",
  "背景音量至少與測定音源音量相差五分貝以上；差值介於三至九分貝時依表修正或以能量相加計算；差值小於三分貝時仍得直接採計其測量結果",
  "背景音量至少與測定音源音量相差十分貝以上；差值介於一至五分貝時依表修正或以能量相減計算；差值小於一分貝時應停止測量另尋適當地點",
  "背景音量至少與測定音源音量相差二十分貝以上；差值介於三至九分貝時應重新測量三次取平均；差值小於三分貝時由主管機關逕行認定音量"],"a",
 "第3條第七款：測量地點之背景音量至少與欲測定音源音量相差十分貝以上；整體音量與背景音量相差數值介於三分貝至九分貝時，依表進行背景音量修正（差三分貝修正 -3.0、九分貝修正 -0.6），或以音量之能量相減方式修正；相差小於三分貝時應停止測量，另尋其他適當測量地點或排除、減低背景音量後重新測量。",
 "What is required of background noise, and how is the difference from the total level handled?",
 ["Background must be at least 10 dB below the source level; a difference of 3 to 9 dB is corrected by the table or by energy subtraction; below 3 dB measurement stops and another site is sought",
  "Background must be at least 5 dB below the source level; a difference of 3 to 9 dB is corrected by the table or by energy addition; below 3 dB the result may still be used directly",
  "Background must be at least 10 dB below the source level; a difference of 1 to 5 dB is corrected by the table or by energy subtraction; below 1 dB measurement stops and another site is sought",
  "Background must be at least 20 dB below the source level; a difference of 3 to 9 dB requires three repeat measurements averaged; below 3 dB the authority determines the level itself"],
 "Article 3, subparagraph 7."),

("ENV-130","第3條",2,"陸運噪音-氣象條件",
 "陸上運輸系統交通噪音測量時之氣象條件要求為何？",
 ["測量時間內測量地點須無雨、路乾且風速每秒五公尺以下",
  "測量時間內測量地點須無雨、路乾且風速每秒十公尺以下",
  "測量時間內測量地點須無雨、路濕且風速每秒三公尺以下",
  "測量時間內測量地點須無霧、氣溫攝氏三十度以下即可"],"a",
 "第3條第九款：氣象條件為測量時間內測量地點須無雨、路乾且風速每秒五公尺以下。第十款並要求測定紀錄應包括日期時間地點（含高度及座標，座標採 TWD97 以上大地基準）、使用儀器及校正紀錄、測定結果、氣象狀態、適用標準、錄音或錄影資料及原始數據紀錄等。",
 "What weather conditions are required when measuring land transportation traffic noise?",
 ["No rain, dry road surface and wind speed of 5 metres per second or less at the site during measurement",
  "No rain, dry road surface and wind speed of 10 metres per second or less at the site during measurement",
  "No rain, wet road surface and wind speed of 3 metres per second or less at the site during measurement",
  "No fog and an air temperature of 30 degrees Celsius or below at the site during measurement"],
 "Article 3, subparagraph 9."),

("ENV-130","第4條",3,"陸運噪音-快速道路",
 "快速道路交通噪音管制標準之小時均能音量規定值為何？",
 ["第一類、第二類管制區早晚 70、日間 74、夜間 67；第三類、第四類管制區早晚 75、日間 76、夜間 72 分貝",
  "第一類、第二類管制區早晚 70、日間 74、夜間 67；第三類、第四類管制區早晚 75、日間 76、夜間 73 分貝",
  "第一類、第二類管制區早晚 65、日間 70、夜間 60；第三類、第四類管制區早晚 70、日間 75、夜間 65 分貝",
  "第一類、第二類管制區早晚 73、日間 73、夜間 70；第三類、第四類管制區早晚 75、日間 75、夜間 70 分貝"],"a",
 "第4條表：快速道路第一類、第二類管制區早晚 70、日間 74、夜間 67；第三類、第四類管制區早晚 75、日間 76、夜間 72。與第5條高速公路相比，僅第三、四類管制區夜間標準不同（快速道路 72、高速公路 73），為易混淆處。",
 "What are the hourly equivalent noise limits for expressways?",
 ["Class 1 and 2 zones: 70 morning/evening, 74 daytime, 67 night; Class 3 and 4 zones: 75 morning/evening, 76 daytime, 72 night",
  "Class 1 and 2 zones: 70 morning/evening, 74 daytime, 67 night; Class 3 and 4 zones: 75 morning/evening, 76 daytime, 73 night",
  "Class 1 and 2 zones: 65 morning/evening, 70 daytime, 60 night; Class 3 and 4 zones: 70 morning/evening, 75 daytime, 65 night",
  "Class 1 and 2 zones: 73 morning/evening, 73 daytime, 70 night; Class 3 and 4 zones: 75 morning/evening, 75 daytime, 70 night"],
 "Article 4, table."),

("ENV-130","第4條、第5條",3,"陸運噪音-高速公路",
 "高速公路交通噪音管制標準與快速道路標準之差異何在？",
 ["高速公路第三類、第四類管制區夜間為 73 分貝，快速道路同區同時段為 72 分貝，其餘各欄數值兩者相同",
  "高速公路第三類、第四類管制區夜間為 72 分貝，快速道路同區同時段為 73 分貝，其餘各欄數值兩者相同",
  "高速公路第一類、第二類管制區日間為 76 分貝，快速道路同區同時段為 74 分貝，其餘各欄數值兩者相同",
  "高速公路各管制區早晚時段均較快速道路高出五分貝，日間與夜間時段之標準值則兩者完全相同無異"],"a",
 "第5條表：高速公路第一類、第二類管制區早晚 70、日間 74、夜間 67；第三類、第四類管制區早晚 75、日間 76、夜間 73。與第4條快速道路唯一差異在第三、四類管制區夜間標準（高速公路 73、快速道路 72）。",
 "How do the freeway noise limits differ from the expressway limits?",
 ["Freeway Class 3 and 4 zones allow 73 dB at night while expressways allow 72 dB there; all other cells are identical",
  "Freeway Class 3 and 4 zones allow 72 dB at night while expressways allow 73 dB there; all other cells are identical",
  "Freeway Class 1 and 2 zones allow 76 dB in daytime while expressways allow 74 dB there; all other cells are identical",
  "Freeway limits are 5 dB higher than expressway limits in the morning and evening; daytime and night limits are identical"],
 "Article 5, table; compare Article 4."),

("ENV-130","第6條",3,"陸運噪音-一般鐵路",
 "一般鐵路交通噪音管制標準之小時均能音量及平均最大音量規定值為何？",
 ["第一類、第二類早晚與日間 73、夜間 70、平均最大音量 80；第三類、第四類早晚與日間 75、夜間 70、平均最大音量 85 分貝",
  "第一類、第二類早晚與日間 70、夜間 65、平均最大音量 80；第三類、第四類早晚與日間 75、夜間 70、平均最大音量 90 分貝",
  "第一類、第二類早晚 65、日間 70、夜間 60、平均最大音量 80；第三類、第四類早晚 70、日間 75、夜間 65、平均最大音量 85 分貝",
  "第一類、第二類早晚與日間 73、夜間 67、平均最大音量 85；第三類、第四類早晚與日間 76、夜間 72、平均最大音量 90 分貝"],"a",
 "第6條表：一般鐵路第一類、第二類管制區早晚 73、日間 73、夜間 70，平均最大音量（Lmax,mean,1h）80；第三類、第四類管制區早晚 75、日間 75、夜間 70，平均最大音量 85。第3條第六款規定軌道系統須同時測量小時均能音量及平均最大音量。",
 "What are the hourly equivalent and mean maximum noise limits for conventional railways?",
 ["Class 1 and 2: 73 morning/evening and daytime, 70 night, mean maximum 80; Class 3 and 4: 75 morning/evening and daytime, 70 night, mean maximum 85 dB",
  "Class 1 and 2: 70 morning/evening and daytime, 65 night, mean maximum 80; Class 3 and 4: 75 morning/evening and daytime, 70 night, mean maximum 90 dB",
  "Class 1 and 2: 65 morning/evening, 70 daytime, 60 night, mean maximum 80; Class 3 and 4: 70 morning/evening, 75 daytime, 65 night, mean maximum 85 dB",
  "Class 1 and 2: 73 morning/evening and daytime, 67 night, mean maximum 85; Class 3 and 4: 76 morning/evening and daytime, 72 night, mean maximum 90 dB"],
 "Article 6, table."),

("ENV-130","第7條",3,"陸運噪音-高速鐵路",
 "高速鐵路交通噪音管制標準之規定值為何？",
 ["第一類、第二類早晚 65、日間 70、夜間 60、平均最大音量 80；第三類、第四類早晚 70、日間 75、夜間 65、平均最大音量 85 分貝",
  "第一類、第二類早晚 73、日間 73、夜間 70、平均最大音量 80；第三類、第四類早晚 75、日間 75、夜間 70、平均最大音量 85 分貝",
  "第一類、第二類早晚 70、日間 74、夜間 67、平均最大音量 85；第三類、第四類早晚 75、日間 76、夜間 72、平均最大音量 90 分貝",
  "第一類、第二類早晚 60、日間 65、夜間 55、平均最大音量 75；第三類、第四類早晚 65、日間 70、夜間 60、平均最大音量 80 分貝"],"a",
 "第7條表：高速鐵路第一類、第二類管制區早晚 65、日間 70、夜間 60，平均最大音量 80；第三類、第四類管制區早晚 70、日間 75、夜間 65，平均最大音量 85。此組數值與第8條大眾捷運系統完全相同，較第6條一般鐵路更為嚴格。",
 "What are the noise limits for high-speed rail?",
 ["Class 1 and 2: 65 morning/evening, 70 daytime, 60 night, mean maximum 80; Class 3 and 4: 70 morning/evening, 75 daytime, 65 night, mean maximum 85 dB",
  "Class 1 and 2: 73 morning/evening, 73 daytime, 70 night, mean maximum 80; Class 3 and 4: 75 morning/evening, 75 daytime, 70 night, mean maximum 85 dB",
  "Class 1 and 2: 70 morning/evening, 74 daytime, 67 night, mean maximum 85; Class 3 and 4: 75 morning/evening, 76 daytime, 72 night, mean maximum 90 dB",
  "Class 1 and 2: 60 morning/evening, 65 daytime, 55 night, mean maximum 75; Class 3 and 4: 65 morning/evening, 70 daytime, 60 night, mean maximum 80 dB"],
 "Article 7, table."),

("ENV-130","第8條",2,"陸運噪音-大眾捷運",
 "大眾捷運系統交通噪音管制標準與其他陸上運輸系統相較有何特徵？",
 ["其規定值與高速鐵路完全相同，第一、二類為 65／70／60、平均最大音量 80，第三、四類為 70／75／65、平均最大音量 85 分貝",
  "其規定值與一般鐵路完全相同，第一、二類為 73／73／70、平均最大音量 80，第三、四類為 75／75／70、平均最大音量 85 分貝",
  "其規定值與快速道路完全相同，第一、二類為 70／74／67、平均最大音量 80，第三、四類為 75／76／72、平均最大音量 85 分貝",
  "其規定值較高速鐵路寬鬆五分貝，第一、二類為 70／75／65、平均最大音量 85，第三、四類為 75／80／70、平均最大音量 90 分貝"],"a",
 "第8條表：大眾捷運系統第一類、第二類管制區早晚 65、日間 70、夜間 60，平均最大音量 80；第三類、第四類管制區早晚 70、日間 75、夜間 65，平均最大音量 85，與第7條高速鐵路之規定值相同。第2條第四款並定義大眾捷運系統為使用專用動力車輛行駛於專用路線之公共運輸系統。",
 "How do mass rapid transit noise limits compare with other land transportation systems?",
 ["They are identical to high-speed rail: 65/70/60 with mean maximum 80 for Class 1 and 2, and 70/75/65 with mean maximum 85 for Class 3 and 4",
  "They are identical to conventional rail: 73/73/70 with mean maximum 80 for Class 1 and 2, and 75/75/70 with mean maximum 85 for Class 3 and 4",
  "They are identical to expressways: 70/74/67 with mean maximum 80 for Class 1 and 2, and 75/76/72 with mean maximum 85 for Class 3 and 4",
  "They are 5 dB looser than high-speed rail: 70/75/65 with mean maximum 85 for Class 1 and 2, and 75/80/70 with mean maximum 90 for Class 3 and 4"],
 "Article 8, table; compare Article 7."),

("ENV-130","第9條",1,"陸運噪音-施行",
 "本標準之施行日期如何規定？",
 ["本標準自發布日起施行","本標準自公告後一年施行","本標準自次年七月一日施行","本標準自核定日次月施行"],"a",
 "第9條：本標準自發布日施行。本標準最近一次修正日期為民國一百零二年九月十一日，第4條至第8條之各項管制標準值即自該時起適用。",
 "How does this standard specify its effective date?",
 ["It takes effect on the date of promulgation",
  "It takes effect one year after announcement",
  "It takes effect on 1 July of the next year",
  "It takes effect the month after approval"],
 "Article 9."),

# ── ENV-138 違反噪音管制法按日連續處罰執行準則（9 條）──────────────
("ENV-138","第1條",1,"噪音按日處罰-法源",
 "違反噪音管制法按日連續處罰執行準則之訂定法源為何？",
 ["依噪音管制法第三十五條第二項規定訂定",
  "依噪音管制法第二十四條第一項規定訂定",
  "依噪音管制法第十四條第二項規定訂定之",
  "依行政罰法第二十四條第三項規定訂定之"],"a",
 "第1條：本準則依噪音管制法（以下簡稱本法）第三十五條第二項規定訂定。第2條並規定本準則適用於依本法第二十四條第一項規定處按日連續處罰之案件，二者所指條文不同，應予區別。",
 "What is the legal basis of these enforcement rules for daily consecutive penalties under the Noise Control Act?",
 ["Adopted under Article 35, Paragraph 2 of the Noise Control Act",
  "Adopted under Article 24, Paragraph 1 of the Noise Control Act",
  "Adopted under Article 14, Paragraph 2 of the Noise Control Act",
  "Adopted under Article 24, Paragraph 3 of the Administrative Penalty Act"],
 "Article 1; see also Article 2."),

("ENV-138","第2條",1,"噪音按日處罰-適用",
 "本準則之適用範圍為何？",
 ["適用於依噪音管制法第二十四條第一項規定處按日連續處罰之案件",
  "適用於依噪音管制法第三十五條第一項規定處按次處罰之全部案件",
  "適用於依噪音管制法所為之所有罰鍰、停工及停業處分之案件",
  "適用於違反陸上運輸系統噪音管制標準而經陳情之各類案件"],"a",
 "第2條：本準則適用於依本法第二十四條第一項規定處按日連續處罰之案件。第3條進而規定主管機關依該條所為限期改善之處分應以書面記載之事項；第4條第四款並指出不符按日連續處罰要件者，以按次處罰。",
 "What is the scope of application of these rules?",
 ["Cases of daily consecutive penalties under Article 24, Paragraph 1 of the Noise Control Act",
  "Cases of penalties imposed per instance under Article 35, Paragraph 1 of the Noise Control Act",
  "All cases of fines, work suspension and business suspension under the Noise Control Act",
  "All complaint cases involving violation of the land transportation noise control standards"],
 "Article 2."),

("ENV-138","第3條",3,"噪音按日處罰-處分書記載",
 "主管機關所為限期改善之處分，應以書面記載哪些事項？",
 ["違規事由、應改善事項及改善之確認方法、改善期限、屆期未完成改善者按次或按日連續處罰之要件規定，及其他經主管機關記載之事項",
  "違規事由、應改善事項及改善之確認方法、改善期限、罰鍰金額之計算方式與繳納帳號，及訴願及行政訴訟之救濟途徑說明",
  "違規事由、噪音發生源負責人姓名住所、改善期限、屆期未完成改善者移送檢察機關偵辦之要件，及其他經主管機關記載事項",
  "違規事由、應改善事項及改善之確認方法、停工日期、屆期未完成改善者按次或按日連續處罰之要件，及主管機關查驗人員名冊"],"a",
 "第3條第一項：限期改善之處分應以書面記載違規事由、應改善事項及改善之確認方法、改善期限、屆期未完成改善者按次或按日連續處罰之要件規定，及其他經主管機關記載之事項共五款。第二項則就第一款、第二款之具體記載內容再作規定。",
 "What must a written order to improve within a set period record?",
 ["The violation, the items to be improved and how improvement is confirmed, the deadline, the conditions for per-instance or daily penalties on default, and other matters recorded",
  "The violation, the items to be improved and how improvement is confirmed, the deadline, how the fine is calculated and the payment account, and the appeal and litigation remedies",
  "The violation, the name and address of the person in charge of the noise source, the deadline, the conditions for referral to prosecutors on default, and other matters recorded",
  "The violation, the items to be improved and how improvement is confirmed, the shutdown date, the conditions for per-instance or daily penalties, and the list of inspecting officers"],
 "Article 3, Paragraph 1."),

("ENV-138","第3條",3,"噪音按日處罰-記載內容",
 "限期改善處分書中違規事由及應改善事項之具體記載內容為何？",
 ["違規事由應記噪音測定位置、時段、測定值、噪音源運轉操作條件、數量與使用情形、相對位置含相片及違反法條；應改善事項應記可採行之噪音防制措施及申報規劃設計內容",
  "違規事由應記陳情人姓名住所、陳情日期、受理編號、承辦人員及初步查核結論；應改善事項應記主管機關指定之單一防制工法及應委託之技師簽證與監造事項",
  "違規事由應記噪音測定位置、時段、測定值及違反法條；應改善事項應記業者應繳納之罰鍰金額、應停止使用之機具清單及應搬遷之新設置地點座標",
  "違規事由應記噪音源設置許可證號、營業登記事項、負責人身分資料及過去違規紀錄；應改善事項應記主管機關委外之檢測機構名稱及檢測費用分擔比例"],"a",
 "第3條第二項：第一款應記載噪音測定位置、測定時段、測定值、測定時噪音發生源運轉之操作條件、數量與使用情形、噪音發生源相對位置（含相片）及違反法條；第二款應記載進行改善可採行之噪音防制措施（如吸音、隔音、防振、隔振、減振、變更設置地點等）、須於改善期限屆滿前以書面向主管機關申報所決定改善措施之規劃與詳細設計內容，及改善後須符合噪音管制標準值時之測定時段、測定位置及噪音發生源須在全運轉之操作條件。",
 "What must the order record in detail for the violation and the items to be improved?",
 ["For the violation: measuring position, period, measured value, source operating conditions, quantity and use, relative position with photos and the article violated; for improvement: available noise control measures and the design filing",
  "For the violation: the complainant's name and address, complaint date, case number, handling officer and preliminary conclusion; for improvement: a single control method designated by the authority and engineer certification and supervision",
  "For the violation: measuring position, period, measured value and the article violated; for improvement: the fine payable, the list of machinery to be stopped and the coordinates of the new site to move to",
  "For the violation: the source permit number, business registration, the responsible person's identity data and past violations; for improvement: the outsourced testing organization and the cost sharing ratio"],
 "Article 3, Paragraph 2."),

("ENV-138","第4條",3,"噪音按日處罰-認定程序",
 "主管機關認定未完成改善而處按日連續處罰之要件為何？何種情形改處按次處罰？",
 ["須查驗未完成具體吸隔音或防振改善措施，且依原記載時段位置全運轉條件量測音量逾噪音管制標準三分貝以上，二者兼具始按日連續處罰；其餘情形以按次處罰",
  "須查驗未完成具體吸隔音或防振改善措施，或依原記載時段位置全運轉條件量測音量逾噪音管制標準一分貝以上，二者之一即按日連續處罰；其餘情形以按次處罰",
  "須查驗未完成具體吸隔音或防振改善措施，且依原記載時段位置全運轉條件量測音量逾噪音管制標準十分貝以上，二者兼具始按日連續處罰；其餘情形免予處罰",
  "須經陳情人再次陳情且主管機關複查屬實，並由業者自認未完成改善者，始得按日連續處罰；未經陳情者一律改以停工或停業處分替代之"],"a",
 "第4條：查驗該場所或設施未完成具體吸（隔）音或防振、隔振、減振等改善措施，或可變更設置地點而未調整位置（第一款）；且依第3條第二項所記載之時段、位置及噪音發生源全運轉之操作條件量測，現場測定音量逾噪音管制標準三分貝以上（第二款）；兼具第一款及第二款情形者，認定未完成改善須按日連續處罰（第三款）。前款以外情形，或經確認僅須以操作條件管制、毋需增加具體設施即可符合標準者，以按次處罰（第四款）。",
 "What conditions justify a daily consecutive penalty, and when is a per-instance penalty imposed instead?",
 ["Both a failure to complete concrete sound absorption or vibration control measures and a measured level exceeding the standard by 3 dB or more under the recorded conditions; other situations draw per-instance penalties",
  "Either a failure to complete concrete sound absorption or vibration control measures or a measured level exceeding the standard by 1 dB or more under the recorded conditions; other situations draw per-instance penalties",
  "Both a failure to complete concrete sound absorption or vibration control measures and a measured level exceeding the standard by 10 dB or more under the recorded conditions; other situations draw no penalty",
  "A repeat complaint verified by the authority together with the operator's own admission of non-completion; where there is no complaint, suspension of work or business replaces the penalty"],
 "Article 4."),

("ENV-138","第5條",3,"噪音按日處罰-日數計算",
 "按日連續處罰之日數如何計算？查驗延誤時有何上限？",
 ["自改善期限屆滿之翌日起算至主管機關查驗日；查驗於改善期限屆滿翌日起算逾十日始進行者，其日數以十日為上限",
  "自改善期限屆滿之當日起算至主管機關查驗日；查驗於改善期限屆滿翌日起算逾三十日始進行者，其日數以三十日為上限",
  "自主管機關處分書送達之翌日起算至查驗日；查驗於處分書送達翌日起算逾十日始進行者，其日數以二十日為上限",
  "自陳情人再次陳情之翌日起算至主管機關查驗日；查驗逾十日始進行者，其按日連續處罰之日數並無任何上限規定"],"a",
 "第5條第一項：按日連續處罰之日數，自改善期限屆滿之翌日起算至主管機關查驗日。第二項：主管機關之查驗於改善期限屆滿翌日起算逾十日始進行者，其按日連續處罰之日數，以十日為上限。第6條就複查亦定有每次十日之上限。",
 "How are the days of a daily consecutive penalty counted, and what cap applies if inspection is delayed?",
 ["From the day after the improvement deadline expires to the day of inspection; if inspection comes more than ten days after that, the count is capped at ten days",
  "From the day the improvement deadline expires to the day of inspection; if inspection comes more than thirty days after that, the count is capped at thirty days",
  "From the day after the order is served to the day of inspection; if inspection comes more than ten days after service, the count is capped at twenty days",
  "From the day after a repeat complaint to the day of inspection; if inspection comes more than ten days later, there is no cap on the number of days"],
 "Article 5."),

("ENV-138","第6條",2,"噪音按日處罰-複查",
 "按日連續處罰後之複查，其處罰日數如何計算？",
 ["自前次查驗日之翌日起算至主管機關複查日計算，但每次複查處按日連續處罰之日數以十日為上限",
  "自前次查驗日之當日起算至主管機關複查日計算，但每次複查處按日連續處罰之日數以三十日為上限",
  "自改善期限屆滿之翌日起算至主管機關複查日計算，且每次複查處按日連續處罰之日數並無上限規定",
  "自前次處分書送達翌日起算至主管機關複查日計算，但每次複查處按日連續處罰之日數以五日為上限"],"a",
 "第6條：主管機關進行按日連續處罰後之複查，經查驗該場所或設施仍未完成改善且符合第4條按日連續處罰要件者，自前次查驗日之翌日起算至主管機關複查日，計算其按日連續處罰之日數；但每次複查處按日連續處罰之日數以十日為上限。此與第5條第二項之十日上限相呼應。",
 "How are penalty days counted on re-inspection after a daily consecutive penalty?",
 ["From the day after the previous inspection to the day of re-inspection, capped at ten days for each re-inspection",
  "From the day of the previous inspection to the day of re-inspection, capped at thirty days for each re-inspection",
  "From the day after the improvement deadline to the day of re-inspection, with no cap on the days for each re-inspection",
  "From the day after the previous order was served to the day of re-inspection, capped at five days for each re-inspection"],
 "Article 6."),

("ENV-138","第7條",2,"噪音按日處罰-扣除日數",
 "場所或設施於按日連續處罰期間停工、停業或遇例假日者，其日數如何處理？",
 ["因停工、停業未運轉噪音源者，得檢具證明文件送主管機關查證屬實後扣除該日數；遇例假日者除有前述情形外不予扣除",
  "因停工、停業未運轉噪音源者，得逕行自行扣除該日數並於事後陳報主管機關備查；遇例假日者一律應予扣除不計入日數",
  "因停工、停業未運轉噪音源者，仍應計入按日連續處罰之日數不得扣除；惟遇例假日者一律應予扣除而不計入日數",
  "因停工、停業未運轉噪音源者，得檢具證明文件申請免除全部罰鍰；遇例假日者由主管機關視個案情形決定是否扣除"],"a",
 "第7條第一項：場所或設施於按日連續處罰期間，因停工、停業未運轉噪音源者，得檢具證明文件送主管機關查證屬實後，扣除其按日連續處罰期間停工、停業之日數。第二項：按日連續處罰期間遇例假日者，除有前項情形外，不予扣除。",
 "How are days of shutdown, business suspension, or holidays treated during a daily consecutive penalty?",
 ["Days when the source was idle from shutdown or suspension may be deducted once the authority verifies the documents; holidays are not deducted apart from that case",
  "Days when the source was idle due to shutdown or suspension may be deducted by the operator and reported afterwards; holidays are always deducted from the count",
  "Days when the source was idle due to shutdown or suspension still count and may not be deducted; but holidays are always deducted from the count",
  "Days when the source was idle due to shutdown or suspension allow a full waiver of the fine on application; holidays are deducted at the authority's discretion"],
 "Article 7."),

("ENV-138","第8條",1,"噪音按日處罰-查驗頻率",
 "依本準則裁處按日連續處罰時，主管機關是否須逐日查驗？",
 ["不須逐日查驗",
  "須逐日查驗屬實",
  "須每三日查驗一次",
  "須每週查驗二次以上"],"a",
 "第8條：依本準則裁處按日連續處罰，不須逐日查驗。故其日數係依第5條、第6條規定，以改善期限屆滿翌日或前次查驗日翌日起算至查驗（複查）日推計，並各以十日為上限。",
 "Must the authority inspect every day when imposing a daily consecutive penalty under these rules?",
 ["Daily inspection is not required",
  "Daily inspection must be verified",
  "Inspection is needed every three days",
  "Inspection is needed twice a week or more"],
 "Article 8."),

("ENV-138","第9條",1,"噪音按日處罰-施行",
 "本準則之施行日期如何規定？",
 ["自發布日施行",
  "自公告日起施行",
  "自次年一月施行",
  "自核定後施行之"],"a",
 "第9條：本準則自發布日施行。本準則最近一次修正日期為民國九十九年三月十一日，其按日連續處罰之認定要件與日數上限即自該時起適用。",
 "How do these rules specify their effective date?",
 ["They take effect on the promulgation date",
  "They take effect on the announcement date",
  "They take effect in January of next year",
  "They take effect after approval is given"],
 "Article 9."),

# ── ENV-154 海洋放流管線放流水標準（5 條）──────────────────────
("ENV-154","第1條",1,"海放管放流水-法源",
 "海洋放流管線放流水標準之訂定法源為何？",
 ["依水污染防治法第七條第二項規定訂定",
  "依海洋污染防治法第七條第二項規定訂定",
  "依水污染防治法第十八條第一項規定訂定",
  "依下水道法第二十一條第二項規定訂定之"],"a",
 "第1條：本標準依水污染防治法第七條第二項規定訂定。水污染防治法第七條係關於事業、污水下水道系統及建築物污水處理設施排放廢（污）水於地面水體者應符合放流水標準之規定。",
 "What is the legal basis of the Effluent Standards for Ocean Outfall Pipelines?",
 ["Adopted under Article 7, Paragraph 2 of the Water Pollution Control Act",
  "Adopted under Article 7, Paragraph 2 of the Marine Pollution Control Act",
  "Adopted under Article 18, Paragraph 1 of the Water Pollution Control Act",
  "Adopted under Article 21, Paragraph 2 of the Sewerage Act of Taiwan"],
 "Article 1."),

("ENV-154","第2條",1,"海放管放流水-適用對象",
 "本標準之適用對象為何？",
 ["廢（污）水以海洋放流管線排放於海洋之事業或污水下水道系統",
  "廢（污）水以河川放流口排放於地面水體之事業或建築物污水處理設施",
  "以船舶或海洋工程設施於海上傾倒廢棄物之事業或港埠管理機關",
  "海水淡化廠及養殖漁業排放鹵水於海洋之事業或農業灌溉單位"],"a",
 "第2條：本標準適用對象為廢（污）水以海洋放流管線（以下簡稱海放管）排放於海洋之事業或污水下水道系統。第3條並要求其應符合附表一及附表二規定限值。",
 "To whom does this standard apply?",
 ["Enterprises or sewer systems that discharge wastewater to the sea through an ocean outfall pipeline",
  "Enterprises or building wastewater facilities that discharge to surface waters through river outfalls",
  "Enterprises or port authorities that dump waste at sea from vessels or offshore engineering facilities",
  "Desalination plants and aquaculture operations discharging brine to the sea, or irrigation units"],
 "Article 2."),

("ENV-154","第3條",1,"海放管放流水-限值依據",
 "以海放管排放廢（污）水於海洋者，應符合何種規定限值？",
 ["應符合本標準附表一及附表二所定之規定限值",
  "應符合放流水標準中之一般事業類別規定限值",
  "應符合海洋環境品質標準所定之海域水質限值",
  "應符合各縣市主管機關另訂之加嚴排放限值"],"a",
 "第3條：事業或污水下水道系統以海放管排放廢（污）水於海洋者，應符合附表一及附表二規定限值。第4條並就各項目限值之性質與單位加以規定，除氫離子濃度指數外均為最大限值。",
 "Which limits must those discharging wastewater to the sea through an ocean outfall meet?",
 ["The limits set out in attached Tables 1 and 2 of this standard",
  "The limits for general enterprises in the effluent standards",
  "The seawater quality limits in the marine environment standards",
  "The stricter discharge limits set separately by local authorities"],
 "Article 3."),

("ENV-154","第4條",2,"海放管放流水-限值單位",
 "本標準各項目限值之性質及單位如何規定？",
 ["除氫離子濃度指數為一範圍且無單位外均為最大限值；大腸桿菌群為 CFU／一○○mL、水溫為攝氏度、其餘項目為毫克／公升",
  "除水溫為一範圍且無單位外均為最大限值；大腸桿菌群為 MPN／一○○mL、氫離子濃度指數為攝氏度、其餘項目為微克／公升",
  "除氫離子濃度指數為一範圍且無單位外均為最小限值；大腸桿菌群為 CFU／一○○mL、水溫為凱氏度、其餘項目為公克／公升",
  "所有項目均為最大限值且均以毫克／公升表示；大腸桿菌群另以個數計、水溫以華氏度計、氫離子濃度指數以分貝計"],"a",
 "第4條：本標準各項目限值，除氫離子濃度指數為一範圍且無單位外，均為最大限值；大腸桿菌群單位為每一百毫升水樣在濾膜上所產生之菌落數（CFU／一○○mL），水溫單位為攝氏度（℃），其餘各項目單位為毫克／公升（mg/L）。",
 "What is the nature of the limits under this standard and what units apply?",
 ["All are maximum limits except pH, which is a range without units; coliform is CFU/100 mL, water temperature is degrees Celsius, and other items are mg/L",
  "All are maximum limits except water temperature, which is a range without units; coliform is MPN/100 mL, pH is degrees Celsius, and other items are ug/L",
  "All are minimum limits except pH, which is a range without units; coliform is CFU/100 mL, water temperature is Kelvin, and other items are g/L",
  "All items are maximum limits expressed in mg/L; coliform is counted in units, water temperature in Fahrenheit, and pH in decibels"],
 "Article 4."),

("ENV-154","第5條",1,"海放管放流水-施行",
 "本標準之施行日期如何規定？",
 ["除另定施行日期者外，自發布日施行",
  "一律自發布後屆滿一年之日施行",
  "應由中央主管機關另行公告施行",
  "自發布當年七月一日起開始施行"],"a",
 "第5條：本標準除另定施行日期者外，自發布日施行。本標準最近一次修正日期為民國一百零六年十月二十日，附表一及附表二所列各項目限值即自該時起適用。",
 "How does this standard specify its effective date?",
 ["It takes effect on promulgation unless otherwise specified",
  "It uniformly takes effect one year after promulgation",
  "The central authority announces its effect separately",
  "It takes effect on 1 July of the year of promulgation"],
 "Article 5."),
]
