# -*- coding: utf-8 -*-
# 第 9 批（C6）：ENV-57、ENV-61、ENV-95、ENV-97 之「已刪除」條文
# 現行法規原文均僅載「（刪除）」，故本檔各題係測驗該條已無實質規定，及該事項現行所依據之條文。
# 欄位：law_id, article, difficulty, category, q_zh, opts_zh(a,b,c,d), answer, explain_zh, q_en, opts_en, explain_en

Q = [

("ENV-57", "第33條", 2, "一般廢棄物-刪除條文",
 "《一般廢棄物回收清除處理辦法》第33條之現行條文內容為何？",
 ["該條已刪除而無實質規定；灰渣採穩定化法處理後之衛生掩埋，現依第三十一條規定辦理",
  "該條規定灰渣得逕行運至安定掩埋場掩埋；其掩埋作業並依第二十八條規定辦理即可",
  "該條規定飛灰處理後衍生物免辦理戴奧辛檢測；其最終處置依第二十七條規定辦理之",
  "該條規定衛生掩埋場得免設置地下水監測井；其監測作業依第三十條規定辦理即可"], "a",
 "本辦法第33條現行條文僅載「（刪除）」，已無實質規定。灰渣採穩定化法處理後以衛生掩埋處理者，現依第31條規定應獨立分區掩埋、設置獨立滲出水收集系統並以雙層不透水材質構築，並每季檢測滲出水處理後及上下游地下水監測井水質。第27條第4項並規定底渣最終處置應每季檢測戴奧辛及重金屬。",
 "What does Article 33 of these Regulations currently provide?",
 ["The article has been deleted and has no substantive content; stabilized ash placed in sanitary landfill is now governed by Article 31",
  "The article allows incineration ash to be taken directly to a stabilized landfill, with the landfill operation governed by Article 28",
  "The article exempts derivatives of treated fly ash from dioxin testing, with final disposal governed by Article 27",
  "The article exempts sanitary landfills from installing groundwater monitoring wells, with monitoring under Article 30"],
 "Article 33 has been deleted; stabilized ash in sanitary landfill is governed by Article 31."),

("ENV-57", "第36條", 2, "一般廢棄物-刪除條文",
 "《一般廢棄物回收清除處理辦法》第36條之現行條文內容為何？",
 ["該條已刪除而無實質規定；回收處理業設施未符規定之改善期限，現依第三十六條之一辦理",
  "該條規定回收處理業之設施應於三年內完成改善；其改善期限並得申請展延一年為限",
  "該條規定執行機關受託清除事業資源垃圾之準用；其準用範圍依第三十七條規定辦理",
  "該條規定廢食用油輸出國外處理之申請程序；其應檢具文件依第三十五條規定辦理"], "a",
 "本辦法第36條現行條文僅載「（刪除）」，已無實質規定。回收處理業回收貯存清除處理應回收廢棄物，其設施未符合本辦法規定者，現依第36條之一第1項規定應於本辦法修正施行之日起一年內完成改善；第37條則規定執行機關受託清除處理事業產生之資源垃圾得準用本辦法。",
 "What does Article 36 of these Regulations currently provide?",
 ["The article has been deleted and has no substantive content; the correction deadline for recycling enterprises is now in Article 36-1",
  "The article gives recycling enterprises three years to complete improvements, with one further year available on application",
  "The article governs the application of these Regulations where an agency clears enterprise recyclables, as in Article 37",
  "The article governs the procedure for exporting waste cooking oil abroad, with documents listed in Article 35"],
 "Article 36 has been deleted; the one-year correction deadline for recycling enterprises is in Article 36-1."),

("ENV-61", "第15條", 2, "共通性再利用-刪除條文",
 "《共通性事業廢棄物再利用管理辦法》第15條之現行條文內容為何？",
 ["該條已刪除而無實質規定；本辦法施行前已通過再利用登記檢核者之過渡，現依第十四條辦理",
  "該條規定再利用機構得繼續再利用至檢核期滿；其未取得資格者依第十三條規定處分之",
  "該條規定各中央目的事業主管機關辦法之不再適用；其適用關係依第十六條規定辦理之",
  "該條規定再利用機構終止業務者免申報營運紀錄；其免申報要件依第十二條規定辦理"], "a",
 "本辦法第15條現行條文僅載「（刪除）」，已無實質規定。本辦法施行前已通過再利用登記檢核且收受共通性事業廢棄物之再利用機構，其過渡適用現依第14條規定辦理，得繼續再利用至原再利用登記檢核有效期間屆滿；期滿前未依第5條取得再利用資格者，不得再收受。第16條則規定各中央目的事業主管機關所定辦法之相關規定不再適用。",
 "What does Article 15 of these Regulations currently provide?",
 ["The article has been deleted and has no substantive content; the transition for institutions already reviewed is now in Article 14",
  "The article lets institutions continue reuse until their review period ends, with unqualified ones dealt with under Article 13",
  "The article disapplies the regulations made by central industry authorities, a matter now governed by Article 16",
  "The article exempts terminating institutions from declaring operating records, a matter governed by Article 12"],
 "Article 15 has been deleted; the transitional rule is in Article 14."),

("ENV-95", "第26條", 2, "公害糾紛-刪除條文",
 "《公害糾紛處理法施行細則》第26條之現行條文內容為何？",
 ["該條已刪除而無實質規定；調處不成立之通知期限，現依第二十五條規定於七日內作成送達",
  "該條規定調處不成立者應於三十日內作成通知；其送達方式並依第九條規定辦理即可",
  "該條規定調處委員會應每六個月報請備查；其報請備查之內容依第三十二條規定辦理",
  "該條規定管轄法院係指委員會所在地法院；其管轄之認定依第二十七條規定辦理之"], "a",
 "本細則第26條現行條文僅載「（刪除）」，已無實質規定。調處不成立者，現依第25條規定，調處委員會應於七日內作成調處不成立之通知，送達當事人；第24條並規定相對人明示拒絕調處者調處不成立，一造無正當理由連續二次調處期日不到場者視為調處不成立。",
 "What does Article 26 of these Enforcement Rules currently provide?",
 ["The article has been deleted and has no substantive content; the seven-day notice of failed mediation is now in Article 25",
  "The article requires a notice of failed mediation within thirty days, with service governed by Article 9 of the Rules",
  "The article requires the mediation committee to report every six months, the content being set by Article 32",
  "The article defines the court of jurisdiction as that of the committee's seat, a matter set by Article 27"],
 "Article 26 has been deleted; the seven-day notice of failed mediation is in Article 25."),

("ENV-95", "第34條", 2, "公害糾紛-刪除條文",
 "《公害糾紛處理法施行細則》第34條之現行條文內容為何？",
 ["該條已刪除而無實質規定；裁決費用之分擔，現依第三十五條得申請兩造比例分擔或相對人負擔",
  "該條規定裁決費用一律由申請人自行負擔；其繳納方式並依第十三條第六款規定辦理",
  "該條規定多數共同利益當事人之申請方式；其得單獨或共同為之依第三十三條辦理",
  "該條規定公害陳情事務之卷宗編訂管理；其陳報上級機關備查依第三十六條辦理"], "a",
 "本細則第34條現行條文僅載「（刪除）」，已無實質規定。當事人申請裁決時依本法第43條所繳納之費用，現依第35條規定，得申請裁決委員會裁決兩造比例分擔或由相對人負擔；第13條第6款並規定未依本法第43條繳納費用者，屬申請不合法之情形；第37條則規定移送之事件免繳調處費。",
 "What does Article 34 of these Enforcement Rules currently provide?",
 ["The article has been deleted and has no substantive content; apportionment of ruling fees is now governed by Article 35",
  "The article makes the applicant bear all ruling fees itself, with payment governed by Article 13, subparagraph 6",
  "The article governs how parties with a common interest apply, a matter now provided for in Article 33",
  "The article governs the filing of public nuisance complaint records, with reporting set out in Article 36"],
 "Article 34 has been deleted; apportionment of ruling fees is in Article 35."),

("ENV-97", "第24條之1", 2, "檢測機構-刪除條文",
 "《環境檢驗測定機構管理辦法》第24條之1之現行條文內容為何？",
 ["該條已刪除而無實質規定；應依各該環保法律罰則處罰之情形，現依第二十四條所列十款辦理",
  "該條規定檢測機構違規之停業期間及復業程序；其復業之審查依第十三條規定辦理之",
  "該條規定撤銷廢止後不得執行該檢測業務之期日；其效力起算依第二十五條規定辦理",
  "該條規定績效優良機構或個人之獎勵方式；其獎勵之辦理依第二十五條之一規定辦理"], "a",
 "本辦法第24條之1現行條文僅載「（刪除）」，已無實質規定。檢測機構應依空氣污染防制法第70條、水污染防治法第49條、廢棄物清理法第58條、氣候變遷因應法第50條等各該罰則處罰之情形，現依第24條所列十款辦理；第25條規定經撤銷廢止者自處分書送達之日起不得再執行該檢測業務；第25條之一則規定績效優良者得予獎勵。",
 "What does Article 24-1 of these Regulations currently provide?",
 ["The article has been deleted and has no substantive content; the ten punishable situations are now listed in Article 24",
  "The article sets the suspension period and resumption procedure for violations, with review governed by Article 13",
  "The article sets the date from which revoked testing may no longer be performed, a matter now in Article 25",
  "The article sets how outstanding agencies or individuals are rewarded, a matter now in Article 25-1"],
 "Article 24-1 has been deleted; the punishable situations are listed in Article 24."),

("ENV-97", "第27條", 2, "檢測機構-刪除條文",
 "《環境檢驗測定機構管理辦法》第27條之現行條文內容為何？",
 ["該條已刪除而無實質規定；輔導、審查、評鑑及查核之委託辦理，現依第二十六條規定辦理",
  "該條規定中央主管機關應自行辦理全部查核事項；其查核之權限依第二十條規定辦理",
  "該條規定外文文件應檢附驗證中譯本之要求；其例外情形依第二十八條規定辦理之",
  "該條規定評鑑技術審議會之委員人數及任期；其設置之依據依第十四條規定辦理之"], "a",
 "本辦法第27條現行條文僅載「（刪除）」，已無實質規定。中央主管機關得委託相關機關或機構辦理檢測機構之輔導、審查、評鑑及查核事項，現依第26條規定辦理；第20條第1項規定得派員進入機構或採樣現場查核，機構不得規避妨礙拒絕；第14條則規定評鑑技術審議會置委員二十一人至二十五人，任期二年。",
 "What does Article 27 of these Regulations currently provide?",
 ["The article has been deleted and has no substantive content; commissioning of guidance, review and inspection is now in Article 26",
  "The article requires the central competent authority to conduct all inspections itself, with the powers set out in Article 20",
  "The article requires an authenticated Chinese translation of foreign documents, with exceptions set by Article 28",
  "The article sets the membership and term of the technical review board, whose basis is now found in Article 14"],
 "Article 27 has been deleted; commissioning of guidance, review, evaluation and inspection is in Article 26."),

("ENV-97", "第29條", 2, "檢測機構-刪除條文",
 "《環境檢驗測定機構管理辦法》第29條之現行條文內容為何？",
 ["該條已刪除而無實質規定；外文文件應檢附之驗證中譯本及英文例外，現依第二十八條辦理",
  "該條規定本辦法部分條文自一百十年四月一日施行；其施行日期依第三十條規定辦理",
  "該條規定檢測機構自行停業應辦理廢止許可證；其廢止之程序依第二十三條規定辦理",
  "該條規定檢測報告簽署人之資格準用主管規定；其核可期限依第十八條規定辦理之"], "a",
 "本辦法第29條現行條文僅載「（刪除）」，已無實質規定。本辦法所定相關文件為外文者，應檢附駐外單位或外交部授權機構驗證之中譯本，但證明文件為英文者免附，現依第28條規定辦理；第30條則規定除一百十年一月二十七日修正發布之第10條第1項第9款及第24條第1項第2款自一百十年四月一日施行外，自發布日施行。",
 "What does Article 29 of these Regulations currently provide?",
 ["The article has been deleted and has no substantive content; authenticated translations and the English exception are now in Article 28",
  "The article makes certain amended provisions effective from 1 April 2021, a matter of effective dates now set out in Article 30",
  "The article requires a testing agency suspending business to have its permit revoked, a procedure now set out in Article 23",
  "The article makes a report signatory's qualification mirror the supervisor's, with the approval period set by Article 18"],
 "Article 29 has been deleted; the translation requirement and English exception are in Article 28."),

]
