# -*- coding: utf-8 -*-
# 第 12 批（D4）：膠帶製造業揮發性有機物空氣污染管制及排放標準、機車排放空氣污染物檢驗站設置及管理辦法
A = "ENV-146"
B = "ENV-147"
Q = [

# ===== ENV-146 膠帶製造業揮發性有機物空氣污染管制及排放標準（10 條）=====
(A,"第1條",1,"膠帶製造-授權依據",
 "膠帶製造業揮發性有機物空氣污染管制及排放標準係依哪些規定訂定？",
 ["空氣污染防制法第二十條第二項、第二十二條及第二十三條第二項","空氣污染防制法第二十條第一項、第二十一條及第二十四條第二項","空氣污染防制法第十八條第五項、第二十二條及第三十一條第二項","毒性及關注化學物質管理法第二十條第二項及第二十三條第一項"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項、第二十二條及第二十三條第二項規定訂定之，故同時涵蓋排放標準、監測檢測及管制設施等授權事項。第10條並定自一百十一年七月一日施行。",
 "Which provisions authorize this VOC standard for adhesive tape manufacturing?",
 ["Articles 20-2, 22 and 23-2 of the Air Pollution Control Act","Articles 20-1, 21 and 24-2 of the Air Pollution Control Act","Articles 18-5, 22 and 31-2 of the Air Pollution Control Act","Articles 20-2 and 23-1 of the Toxic Chemical Substances Act"],
 "Article 1."),

(A,"第2條",3,"膠帶製造-名詞定義",
 "本標準所稱膠帶製造業及揮發性有機物原（物）料年用量之定義各為何？",
 ["膠帶製造業指以含揮發性有機物溶劑混拌黏著劑或離型劑塗布基材再經烘乾固化製成黏貼成品者；年用量指操作許可證登載各項原料許可核定最大設計量乘以其揮發性有機物成分百分比後之加總","膠帶製造業指以水性黏著劑塗布於紙質基材再經高溫壓合製成成品者；年用量指前一年度實際購入之各項原料數量乘以其揮發性有機物成分百分比後之加總，單位為公斤／年","膠帶製造業指以聚氨基甲酸酯進行塗布或貼合作業形成薄膜之行業；年用量指操作許可證登載各項原料許可核定最大設計量之直接加總，不再乘以揮發性有機物成分之百分比","膠帶製造業指從事各類壓敏膠帶分切包裝之加工業者；年用量指全廠所有排放管道之揮發性有機物年排放總量，依核定年操作時數換算所得，單位為公噸／年"],"a",
 "第2條第1款：膠帶製造業指從事以含揮發性有機物之溶劑，混拌黏著劑或離型劑，塗布於基材上，再經烘乾固化製成具黏貼功能成品之製造者。第2款：揮發性有機物原（物）料年用量指單一公私場所所有固定污染源操作許可證登載之各項原（物）料許可核定最大設計量乘以各該項原（物）料揮發性有機物成分百分比後之加總，單位為公噸／年。",
 "How are adhesive tape manufacturing and annual VOC raw material use defined?",
 ["Making adhesive products by mixing VOC solvent with adhesive or release agent, coating a substrate and curing; annual use sums each permitted maximum design quantity times its VOC percentage","Making products by coating water-based adhesive on paper substrate and hot pressing; annual use sums the prior year's actual purchases times each material's VOC percentage, in kilograms per year","Coating or laminating with polyurethane to form a film; annual use simply sums the permitted maximum design quantities without multiplying by any VOC content percentage at all","Slitting and packaging pressure-sensitive tapes; annual use means the plant's total annual VOC emissions from all stacks converted by approved operating hours, in tonnes per year"],
 "Article 2, subparagraphs 1 and 2."),

(A,"第2條",3,"膠帶製造-處理效率與監測時數",
 "本標準所定污染防制設備處理效率及每季有效監測時數百分率之計算方式為何？",
 ["處理效率＝（E－E0）／E×100％，E 為進防制設備前排放量、E0 為防制設備後逕排大氣排放量；P＝〔T－（Du＋Dm）〕／（T－t）×100％","處理效率＝（E0－E）／E0×100％，E 為進防制設備前排放量、E0 為防制設備後逕排大氣排放量；P＝〔T－（Du＋Dm）〕／（T＋t）×100％","處理效率＝（E－E0）／E0×100％，E 為排放管道總排放量、E0 為許可核定排放量；P＝〔T＋（Du＋Dm）〕／（T－t）×100％，t 為監測設施汰換時間","處理效率＝E0／E×100％，E 為進防制設備前排放量、E0 為防制設備後排放量；P＝（Du＋Dm）／T×100％，Du 為無效數據時間、Dm 為遺失數據時間"],"a",
 "第2條第6款：處理效率＝（E－E0）／E×100％，E 為經集氣系統進入污染防制設備前之單位小時排放量、E0 為經防制設備後逕排大氣之單位小時排放量（公斤／小時）。第8款：每季有效監測時數百分率 P＝〔T－（Du＋Dm）〕／（T－t）×100％，T 為每季操作時間、t 為監測設施汰換時間、Du 為無效數據時間、Dm 為遺失數據時間。",
 "How are control equipment efficiency and quarterly valid monitoring hour percentage computed?",
 ["Efficiency = (E − E0)/E × 100%, E being emissions before and E0 after the control device; P = [T − (Du + Dm)]/(T − t) × 100%","Efficiency = (E0 − E)/E0 × 100%, E being emissions before and E0 after the control device; P = [T − (Du + Dm)]/(T + t) × 100%","Efficiency = (E − E0)/E0 × 100%, E being total stack emissions and E0 the permitted amount; P = [T + (Du + Dm)]/(T − t) × 100%","Efficiency = E0/E × 100%, E being emissions before and E0 after the device; P = (Du + Dm)/T × 100%, with Du invalid and Dm missing data time"],
 "Article 2, subparagraphs 6 and 8."),

(A,"第3條",2,"膠帶製造-適用門檻",
 "本標準適用於膠帶製造業中揮發性有機物原（物）料年用量達多少者？",
 ["年用量達二十五公噸以上者","年用量達二百五十公噸以上者","年用量達二點五公噸以上者","年用量達一千公噸以上之者"],"a",
 "第3條：本標準適用於膠帶製造業，且其揮發性有機物原（物）料年用量達二十五公噸以上者。第5條並以全廠年用量二百五十公噸作為既存製程處理效率要求之分界。",
 "This standard applies to tape makers whose annual VOC raw material use reaches what level?",
 ["Annual use of 25 tonnes or more","Annual use of 250 tonnes or more","Annual use of 2.5 tonnes or more","Annual use of 1,000 tonnes or more"],
 "Article 3."),

(A,"第3條",3,"膠帶製造-排除條件",
 "膠帶製造業之單一製程於何種情形，檢具佐證資料報經地方主管機關認可者，得不適用本標準？",
 ["採水性黏著劑或離型劑並以水為稀釋溶劑，揮發性有機物重量含量比在百分之十以下且該製程排放管道排放量每小時一公斤以下；或採無溶劑原料未使用有機溶劑，重量含量比在百分之一以下且排放量每小時一公斤以下","採水性黏著劑或離型劑並以水為稀釋溶劑，揮發性有機物重量含量比在百分之三十以下且該製程排放管道排放量每小時五公斤以下；或採無溶劑原料，重量含量比在百分之十以下且排放量每小時五公斤以下","採任何黏著劑但已裝設污染防制設備且處理效率達百分之九十以上者；或該單一製程之年操作時數未達一千小時，且其排放管道之揮發性有機物排放量每小時二點二公斤以下者","採水性黏著劑或離型劑者一律得排除適用；或採無溶劑黏著劑者一律得排除適用，均無須就揮發性有機物重量含量比及排放管道排放量另設任何數值上之限制"],"a",
 "第3條但書第1款、第2款：採用水性黏著劑或水性離型劑為原（物）料、以水為稀釋溶劑，且揮發性有機物重量含量比在百分之十以下及該單一製程排放管道之揮發性有機物排放量每小時一公斤以下者；或採用無溶劑黏著劑或無溶劑離型劑且未使用任何有機溶劑，揮發性有機物重量含量比在百分之一以下及排放量每小時一公斤以下者，得不適用本標準。",
 "When may a single process be exempt, on evidence recognized by the local authority?",
 ["Water-based adhesive or release agent diluted with water, VOC content at or below 10 percent by weight and stack emissions at or below 1 kg per hour; or solvent-free materials, content at or below 1 percent and emissions at or below 1 kg per hour","Water-based adhesive or release agent diluted with water, VOC content at or below 30 percent by weight and stack emissions at or below 5 kg per hour; or solvent-free materials, content at or below 10 percent and emissions at or below 5 kg per hour","Any adhesive provided control equipment is installed with efficiency of 90 percent or more; or the process runs fewer than 1,000 hours a year and its stack VOC emissions stay at or below 2.2 kg per hour","Any use of water-based adhesive or release agent is exempt outright; and any use of solvent-free adhesive is exempt outright, with no limit set on VOC weight content or on the stack emission rate at all"],
 "Article 3, proviso, subparagraphs 1 and 2."),

(A,"第4條",1,"膠帶製造-廢氣收集與紀錄",
 "膠帶製造業各操作單元之廢氣收集規定及應記錄項目與頻率，分別規定於何處？",
 ["廢氣收集規定如附表一，應記錄之項目及頻率規定如附表二","廢氣收集規定如附表二，應記錄之項目及頻率規定如附表一","二者均規定於本標準第五條所定之處理效率條文之中","二者均由直轄市、縣（市）主管機關於操作許可證中訂明"],"a",
 "第4條：膠帶製造業各操作單元及操作作業之廢氣收集規定如附表一，應記錄之項目及頻率規定如附表二。第8條第2項第2款並定污染防制設備應設置操作運轉條件之監測設施，並依附表二所列項目及頻率記錄。",
 "Where are the gas collection rules and the items and frequency of records set out?",
 ["Collection rules are in Table 1; the items and frequency of records are in Table 2","Collection rules are in Table 2; the items and frequency of records are in Table 1","Both are set out within the treatment efficiency provisions of Article 5","Both are specified by the local authority in the source operating permit"],
 "Article 4."),

(A,"第5條",3,"膠帶製造-既存製程效率",
 "既存製程之揮發性有機物處理效率或排放量要求為何？",
 ["全廠年用量未達二百五十公噸者處理效率應達百分之九十五以上；達二百五十公噸以上者應達百分之九十六以上或單一排放管道排放量每小時二點二公斤以下","全廠年用量未達二百五十公噸者處理效率應達百分之九十六以上；達二百五十公噸以上者應達百分之九十七以上或單一排放管道排放量每小時二公斤以下","全廠年用量未達二十五公噸者處理效率應達百分之九十以上；達二十五公噸以上者應達百分之九十五以上或單一排放管道排放量每小時六公斤以下","全廠年用量未達二百五十公噸者處理效率應達百分之九十以上；達二百五十公噸以上者應達百分之九十五以上或單一排放管道排放量每小時一公斤以下"],"a",
 "第5條第1款：既存製程且全廠揮發性有機物原（物）料年用量未達二百五十公噸者，處理效率應達百分之九十五以上。第2款：既存製程且年用量達二百五十公噸以上者，處理效率應達百分之九十六以上或單一排放管道之排放量每小時二點二公斤以下。",
 "What efficiency or emission rate applies to existing processes?",
 ["Under 250 tonnes a year, efficiency must reach 95 percent; at 250 tonnes or more, 96 percent or a single stack rate at or below 2.2 kg per hour","Under 250 tonnes a year, efficiency must reach 96 percent; at 250 tonnes or more, 97 percent or a single stack rate at or below 2 kg per hour","Under 25 tonnes a year, efficiency must reach 90 percent; at 25 tonnes or more, 95 percent or a single stack rate at or below 6 kg per hour","Under 250 tonnes a year, efficiency must reach 90 percent; at 250 tonnes or more, 95 percent or a single stack rate at or below 1 kg per hour"],
 "Article 5, subparagraphs 1 and 2."),

(A,"第5條",2,"膠帶製造-新設製程效率",
 "新設製程之揮發性有機物處理效率或單一排放管道排放量要求為何？",
 ["處理效率應達百分之九十七以上，或其單一排放管道之揮發性有機物排放量每小時二公斤以下","處理效率應達百分之九十六以上，或其單一排放管道之揮發性有機物排放量每小時二點二公斤以下","處理效率應達百分之九十五以上，或其單一排放管道之揮發性有機物排放量每小時六公斤以下","處理效率應達百分之九十九以上，或其單一排放管道之揮發性有機物排放量每小時零點五公斤以下"],"a",
 "第5條第3款：新設製程，其揮發性有機物之處理效率應達百分之九十七以上或其單一排放管道之揮發性有機物排放量每小時二公斤以下。此較既存製程之九十五％、九十六％為嚴。",
 "What efficiency or single-stack rate applies to new processes?",
 ["Efficiency must reach 97 percent, or the single stack VOC rate must be at or below 2 kg per hour","Efficiency must reach 96 percent, or the single stack VOC rate must be at or below 2.2 kg per hour","Efficiency must reach 95 percent, or the single stack VOC rate must be at or below 6 kg per hour","Efficiency must reach 99 percent, or the single stack VOC rate must be at or below 0.5 kg per hour"],
 "Article 5, subparagraph 3."),

(A,"第6條",3,"膠帶製造-連續自動監測",
 "膠帶製造業於何種情形應設置非甲烷碳氫化合物連續自動監測設施？",
 ["揮發性有機物單位小時許可排放量達每小時六公斤以上，且非採熱焚化或回收方式處理者，其防制設備廢氣導入處及排放口應設置","揮發性有機物單位小時許可排放量達每小時二公斤以上，且採熱焚化或回收方式處理者，其防制設備廢氣導入處及排放口應設置","揮發性有機物原（物）料年用量達二百五十公噸以上者，不論其處理方式為何，均應於各排放管道之排放口設置該項設施","揮發性有機物單位小時許可排放量達每小時六公斤以上者，不論處理方式為何，均應於防制設備排放口設置該項監測設施"],"a",
 "第6條第1款：揮發性有機物單位小時許可排放量達每小時六公斤以上，且非採熱焚化或回收方式處理者，其揮發性有機物污染防制設備之廢氣導入處及排放口應設置非甲烷碳氫化合物（NMHC）連續自動監測設施。第2款則定非前款者每半年應檢測一次。",
 "When must continuous automatic NMHC monitors be installed?",
 ["Where permitted hourly VOC emissions reach 6 kg per hour and thermal oxidation or recovery is not used, at the inlet and outlet of the control device","Where permitted hourly VOC emissions reach 2 kg per hour and thermal oxidation or recovery is used, at the inlet and outlet of the control device","Where annual VOC raw material use reaches 250 tonnes, regardless of treatment method, at the outlet of every emission stack of the plant","Where permitted hourly VOC emissions reach 6 kg per hour, regardless of treatment method, at the outlet of the control device concerned"],
 "Article 6, subparagraph 1."),

(A,"第6條",2,"膠帶製造-定期檢測",
 "非屬應設置連續自動監測設施之揮發性有機物排放管道，其檢測頻率與要求為何？",
 ["非甲烷碳氫化合物濃度及排放量每半年應檢測一次，每次檢測至少四小時，並應記錄檢測當時製程及防制設備之操作條件","非甲烷碳氫化合物濃度及排放量每年應檢測一次，每次檢測至少二小時，並得免記錄檢測當時製程及防制設備之操作條件","非甲烷碳氫化合物濃度及排放量每季應檢測一次，每次檢測至少八小時，並應記錄檢測當時之氣象條件及周界濃度數值","非甲烷碳氫化合物濃度及排放量每二年應檢測一次，每次檢測至少一小時，檢測報告僅須列出總平均值而免列小時平均"],"a",
 "第6條第2款：非前款規定之揮發性有機物排放管道者，其非甲烷碳氫化合物（NMHC）濃度及排放量每半年應檢測一次；檢測時應記錄檢測當時製程及防制設備之操作條件，每次檢測至少四小時，檢測報告應含檢測濃度之測值、小時平均值及總平均值。",
 "How often must other VOC stacks be tested, and with what requirements?",
 ["NMHC concentration and emissions must be tested every six months, each test lasting at least four hours, recording the process and control equipment conditions","NMHC concentration and emissions must be tested once a year, each test lasting at least two hours, without needing to record process or equipment conditions","NMHC concentration and emissions must be tested each quarter, each test lasting at least eight hours, recording the weather and boundary concentration values","NMHC concentration and emissions must be tested every two years, each test lasting at least one hour, with only a total average shown in the report"],
 "Article 6, subparagraph 2."),

(A,"第7條",2,"膠帶製造-原料紀錄",
 "膠帶製造業者對含揮發性有機物原（物）料之記錄項目、頻率及保存年限為何？",
 ["應每月記錄原（物）料名稱種類、揮發性有機物含量百分比、購入量、使用量及輸出量等資料；相關紀錄應保存六年備查","應每季記錄原（物）料名稱種類、揮發性有機物含量百分比、購入量及使用量等資料；相關紀錄應保存三年以備主管機關查核","應每日記錄原（物）料名稱種類及購入量，並每年申報一次；相關紀錄應保存二年，於主管機關要求時提出即可免罰","應每月記錄原（物）料名稱種類及使用量，惟含量百分比得由供應商代為保存；相關紀錄應保存十年並每年申報一次"],"a",
 "第7條第1項：膠帶製造業者應每月記錄使用含揮發性有機物之原（物）料名稱種類、揮發性有機物含量百分比、購入量、使用量及輸出量等資料。第2項：前項相關紀錄資料，公私場所應保存六年備查。第8條第3項之操作運轉紀錄亦應保存六年。",
 "What must tape makers record about VOC materials, how often, and for how long?",
 ["Monthly records of material names, VOC content percentage, purchases, use and output; the records must be kept six years for inspection","Quarterly records of material names, VOC content percentage and purchases and use; the records must be kept three years for inspection","Daily records of material names and purchases with an annual filing; the records must be kept two years and produced only on request","Monthly records of material names and use, with content percentages kept by the supplier; the records must be kept ten years and filed yearly"],
 "Article 7, paragraphs 1 and 2."),

(A,"第8條",3,"膠帶製造-校正與監測",
 "膠帶製造業對壓差計、氣體流量計及監測設施有效時數之規定為何？",
 ["密閉負壓操作者應於作業區設置壓差計且每年校正一次；防制設備導入處或排放口應設氣體流量計且每年校正一次；監測設施每季有效監測時數百分率應大於百分之八十","密閉負壓操作者應於作業區設置壓差計且每季校正一次；防制設備導入處或排放口應設氣體流量計且每半年校正一次；監測設施每季有效監測時數百分率應大於百分之六十","密閉負壓操作者應於作業區設置壓差計且每二年校正一次；防制設備排放口應設氣體流量計且每二年校正一次；監測設施每年有效監測時數百分率應大於百分之九十五","密閉負壓操作者得免設置壓差計；防制設備導入處應設氣體流量計但無須定期校正；監測設施每季有效監測時數百分率應大於百分之八十始得作為申報依據"],"a",
 "第8條第1項：設置集氣設施型式屬密閉負壓操作者，應於作業區設置壓差計，且其壓差計每年應校正一次。第2項第1款：防制設備之揮發性有機物廢氣導入處或排放口應設置氣體流量計，且每年應校正一次；第3款：監測設施之每季有效監測時數百分率應大於百分之八十。第4項並定因故無法設置者得提替代監測方案報請地方主管機關核可。",
 "What rules govern the differential pressure gauge, gas flow meter and valid monitoring hours?",
 ["Closed negative-pressure collection needs a pressure gauge in the work area calibrated yearly; a gas flow meter at the device inlet or outlet calibrated yearly; quarterly valid monitoring hours must exceed 80 percent","Closed negative-pressure collection needs a pressure gauge calibrated quarterly; a gas flow meter at the device inlet or outlet calibrated every six months; quarterly valid monitoring hours must exceed 60 percent","Closed negative-pressure collection needs a pressure gauge calibrated every two years; a flow meter at the outlet calibrated every two years; annual valid monitoring hours must exceed 95 percent of the time","Closed negative-pressure collection needs no pressure gauge; a flow meter is required at the inlet but needs no calibration; quarterly valid monitoring hours must exceed 80 percent to support reporting"],
 "Article 8, paragraphs 1 and 2."),

(A,"第9條",3,"膠帶製造-既存製程期限",
 "既存製程應自何時起符合本標準？其申請改善期限之期日與最長改善期限為何？",
 ["應自一百十三年七月一日起符合；得於一百十二年十二月三十一日前檢具空氣污染改善計畫申請核定改善期限，最長不得逾一百十三年十二月三十一日","應自一百十一年七月一日起符合；得於一百十一年十二月三十一日前檢具空氣污染改善計畫申請核定改善期限，最長不得逾一百十二年十二月三十一日","應自一百十三年七月一日起符合；得於一百十三年六月三十日前檢具空氣污染改善計畫申請核定改善期限，最長不得逾一百十五年十二月三十一日","應自一百十四年一月一日起符合；改善期限由直轄市、縣（市）主管機關依個案裁量核定，法規並未設有任何最長改善期限之限制"],"a",
 "第9條第1項：既存製程應自中華民國一百十三年七月一日起符合本標準規定。第2項：屆期未能符合而需更新汰換工程者，得於一百十二年十二月三十一日前檢具空氣污染改善計畫向直轄市、縣（市）主管機關申請核定改善期限，最長不得逾一百十三年十二月三十一日。第3項並定改善計畫應包含之內容。",
 "From when must existing processes comply, and what are the plan and deadline dates?",
 ["From July 1, 2024; a plan may be filed by December 31, 2023 for an approved deadline no later than December 31, 2024","From July 1, 2022; a plan may be filed by December 31, 2022 for an approved deadline no later than December 31, 2023","From July 1, 2024; a plan may be filed by June 30, 2024 for an approved deadline no later than December 31, 2026","From January 1, 2025; the deadline is set case by case by the local authority with no statutory maximum period"],
 "Article 9, paragraphs 1 and 2."),

(A,"第10條",1,"膠帶製造-施行日",
 "膠帶製造業揮發性有機物空氣污染管制及排放標準之施行日期為何？",
 ["自中華民國一百十一年七月一日施行","自中華民國一百十三年七月一日施行","自中華民國一百十二年一月一日施行","自本標準發布之日起立即開始施行"],"a",
 "第10條：本標準自中華民國一百十一年七月一日施行。惟第9條第1項另定既存製程應自一百十三年七月一日起始須符合本標準規定，二者應予區辨。",
 "When does this adhesive tape VOC standard take effect?",
 ["On July 1, 2022","On July 1, 2024","On January 1, 2023","On the date of promulgation"],
 "Article 10."),

# ===== ENV-147 機車排放空氣污染物檢驗站設置及管理辦法（23 條）=====
(B,"第1條",1,"機車檢驗站-授權依據",
 "機車排放空氣污染物檢驗站設置及管理辦法係依哪些規定訂定？",
 ["空氣污染防制法第十八條第五項及第四十四條第三項","空氣污染防制法第二十條第二項及第四十條第三項","空氣污染防制法第十八條第一項及第八十條第四項","道路交通管理處罰條例第十八條及第四十四條規定"],"a",
 "第1條：本辦法依空氣污染防制法第十八條第五項及第四十四條第三項規定訂定之。第17條並援引本法第八十條第四項規定作為處以罰鍰之依據。",
 "Which provisions authorize these motorcycle emission testing station regulations?",
 ["Article 18-5 and Article 44-3 of the Air Pollution Control Act","Article 20-2 and Article 40-3 of the Air Pollution Control Act","Article 18-1 and Article 80-4 of the Air Pollution Control Act","Articles 18 and 44 of the Road Traffic Management Penalty Act"],
 "Article 1."),

(B,"第2條",3,"機車檢驗站-名詞定義",
 "本辦法所稱移動式機車排氣檢驗站、檢驗人員及檢驗線之定義各為何？",
 ["移動式指固定式檢驗站以外之檢驗站；檢驗人員指取得汽機車排放控制系統及惰轉狀態訓練合格證書並經地方主管機關備查後登錄者；檢驗線指設有檢驗區電腦設備軟體分析儀及標準氣體各一套供排氣檢驗者","移動式指設於加油站內之檢驗站；檢驗人員指領有機車修護技術士證照並經公會推薦登錄者；檢驗線指設有檢驗區及排氣分析儀二套以上，並得同時供二輛以上機車進行排氣檢驗之作業區域","移動式指得跨縣市執行檢驗之檢驗站；檢驗人員指由中央主管機關直接聘用之技術人員；檢驗線指設有電腦設備及拍攝裝置之區域，其電腦軟體與標準氣體得與其他檢驗線共用而不必各備一套","移動式指固定式檢驗站以外之檢驗站；檢驗人員指取得排氣分析儀操作證明者；檢驗線指設有檢驗區之空間即可，無須配置電腦設備、電腦軟體、排氣分析儀及標準氣體等各項設備"],"a",
 "第2條第3款：移動式機車排氣檢驗站指固定式機車排氣檢驗站以外之檢驗站。第4款：檢驗人員指取得汽機車排放控制系統及惰轉狀態訓練合格證書，於檢驗站從事機車排氣檢驗業務，並經直轄市、縣（市）主管機關備查後登錄之人員。第7款：檢驗線指設有檢驗區、電腦設備、電腦軟體、排氣分析儀、標準氣體各一套，供排氣檢驗者。",
 "How are mobile stations, testing personnel and a testing lane defined?",
 ["Mobile means any station other than a fixed one; personnel must hold the emission control and idle mode training certificate and be locally registered; a lane has a test area, computer, software, analyzer and standard gas, one set each","Mobile means a station inside a filling station; personnel must hold a motorcycle repair technician licence and be nominated by a trade association; a lane has a test area and two or more analyzers serving two motorcycles at once","Mobile means a station allowed to test across counties; personnel are technicians hired directly by the central authority; a lane needs a computer and camera, and its software and standard gas may be shared with other lanes","Mobile means any station other than a fixed one; personnel are those holding an analyzer operation certificate; a lane needs only a test area, with no computer, software, analyzer or standard gas required at all"],
 "Article 2, subparagraphs 3, 4 and 7."),

(B,"第3條",1,"機車檢驗站-委託辦理",
 "直轄市、縣（市）主管機關為執行機車排氣定期檢驗，得如何辦理？",
 ["得委託機車排氣檢驗站辦理","應由主管機關自行設站辦理","得委託各地監理機關代為辦理","應委由中央主管機關統籌辦理"],"a",
 "第3條：直轄市、縣（市）主管機關為執行機車排氣定期檢驗，得委託機車排氣檢驗站辦理。第2條第1款並定機車排氣檢驗站指取得認可證並接受委託從事機車排氣檢驗業務之檢驗站。",
 "How may local authorities carry out periodic motorcycle emission testing?",
 ["They may commission motorcycle emission testing stations","They must set up and run the stations by themselves","They may commission the local vehicle registration offices","They must have the central authority handle it centrally"],
 "Article 3."),

(B,"第4條",3,"機車檢驗站-機車業籌設",
 "機車業申請籌設機車排氣檢驗站，其營業面積與檢驗線之要求為何？",
 ["營業面積三十五平方公尺以上及檢驗線六平方公尺以上，營業面積應實際作為營業用途，檢驗線不得設置於人行道、騎樓及防火巷","營業面積六十平方公尺以上及檢驗線三十五平方公尺以上，營業面積得供其他用途使用，檢驗線得設置於騎樓但不得設於人行道","營業面積三十五平方公尺以上及檢驗線六平方公尺以上，二者均得計入騎樓面積，檢驗線並得視營業需要暫時挪為停車之用","營業面積十五平方公尺以上及檢驗線三平方公尺以上，營業面積應實際作為營業用途，檢驗線不得設置於人行道、騎樓及防火巷"],"a",
 "第4條第1項第1款第5目：機車業應檢附營業面積三十五平方公尺以上及檢驗線六平方公尺以上之圖說；營業面積應實際作為營業用途；檢驗線不得設置於人行道、騎樓及防火巷。第12條第1項第8款並定營業場所環境應保持整潔、檢驗線不得堆放雜物或挪為他用。",
 "What floor area and testing lane does a motorcycle dealer need to apply?",
 ["A business area of at least 35 square metres and a lane of at least 6 square metres; the business area must be genuinely used as such and the lane may not sit on a sidewalk, arcade or fire lane","A business area of at least 60 square metres and a lane of at least 35 square metres; the business area may serve other uses and the lane may sit in an arcade though not on a sidewalk","A business area of at least 35 square metres and a lane of at least 6 square metres; both may count arcade space and the lane may be used temporarily for parking when business requires","A business area of at least 15 square metres and a lane of at least 3 square metres; the business area must be genuinely used as such and the lane may not sit on a sidewalk, arcade or fire lane"],
 "Article 4, paragraph 1, subparagraph 1, item 5."),

(B,"第4條",3,"機車檢驗站-加油站籌設",
 "加油站申請籌設機車排氣檢驗站，較機車業另有何特別要求？偏遠地區有何放寬？",
 ["應檢附檢驗線與儲油槽、加油區及卸油區間隔六公尺以上之圖說，並取得都市計畫、建管、地政、消防等機關會勘同意文件；偏遠地區機車業不受營業面積限制","應檢附檢驗線與儲油槽、加油區及卸油區間隔三公尺以上之圖說，並取得當地消防、建管等機關同意文件即可；偏遠地區之加油站不受檢驗線面積限制","應檢附加油站經營許可執照及公共意外責任保險之證明文件，並經中央主管機關核准後始得籌設；偏遠地區之加油站不受營業面積限制","應檢附檢驗線與儲油槽間隔十公尺以上之圖說，並取得目的事業主管機關核准文件；偏遠地區機車業得免附土地合法使用證明文件"],"a",
 "第4條第1項第2款第5目、第6目：加油站應檢附檢驗線與儲油槽、加油區及卸油區間隔六公尺以上之圖說，及當地加油站、都市計畫、建築管理、地政、消防等主管機關審查或會勘同意之證明文件。第2項：未設置檢驗站之行政區域或車輛登記數密度低於全國平均車輛密度三分之一偏遠地區之機車業，不受營業面積三十五平方公尺以上之限制。",
 "What extra requirement applies to filling stations, and what relaxation applies in remote areas?",
 ["Drawings showing the lane at least 6 metres from tanks, fuelling and unloading areas, plus consent from planning, building, land and fire authorities; remote-area dealers are freed from the business area rule","Drawings showing the lane at least 3 metres from tanks, fuelling and unloading areas, with consent from the fire and building authorities alone; remote-area filling stations are freed from the lane area rule","The filling station operating licence and public liability insurance documents, approved by the central authority before establishment; remote-area filling stations are freed from the business area rule","Drawings showing the lane at least 10 metres from the tanks, plus the industry authority's approval document; remote-area dealers may apply without lawful land use certification documents"],
 "Article 4, paragraph 1, subparagraph 2 and paragraph 2."),

(B,"第5條",2,"機車檢驗站-籌設審查",
 "直轄市、縣（市）主管機關受理籌設許可申請後之審查期限為何？",
 ["應於三十日內完成書面審查；通過者應於五十日內通知有關機關現場會勘，符合規定者應於十日內核發同意籌設之通知","應於六十日內完成書面審查；通過者應於九十日內通知有關機關現場會勘，符合規定者應於三十日內核發同意籌設通知","應於十日內完成書面審查；通過者應於二十日內通知有關機關現場會勘，符合規定者應於五日內核發同意籌設之通知書","應於三十日內完成書面審查；通過者應於五十日內辦理現場會勘，會勘結果不符規定者仍應先行核發同意籌設之通知"],"a",
 "第5條第1項：主管機關受理籌設許可文件後，應於三十日內完成書面審查，經審查不符規定者通知限期補正，逾期未補正者駁回申請。第2項：書面審查通過者，應於五十日內通知有關機關進行現場會勘；符合規定者應於十日內核發同意籌設之通知。",
 "What review timeline applies to a station establishment application?",
 ["Paper review within 30 days; if passed, agencies are notified for a site inspection within 50 days, and approval is issued within 10 days if compliant","Paper review within 60 days; if passed, agencies are notified for a site inspection within 90 days, and approval is issued within 30 days if compliant","Paper review within 10 days; if passed, agencies are notified for a site inspection within 20 days, and approval is issued within 5 days if compliant","Paper review within 30 days; if passed, a site inspection is held within 50 days, and approval is issued even where the inspection finds non-compliance"],
 "Article 5, paragraphs 1 and 2."),

(B,"第6條",3,"機車檢驗站-認可證申請",
 "經同意籌設之檢驗站應於何時完成籌設並申請認可證？其電腦及周邊設備規格有何要求？",
 ["應於同意之日起三個月內完成籌設並申請認可證；網路頻寬應下載二M及上傳二五六K以上且專線專用，顯示器十九吋以上，記憶體一GB以上","應於同意之日起六個月內完成籌設並申請認可證；網路頻寬應下載一M及上傳一二八K以上且得與他人共用，顯示器十五吋以上，記憶體五一二MB以上","應於同意之日起一年內完成籌設並申請認可證；網路頻寬應下載十M及上傳一M以上且專線專用，顯示器二十四吋以上，記憶體八GB以上之規格","應於同意之日起三個月內完成籌設並申請認可證；網路頻寬並無規格限制，顯示器十九吋以上，並得免設置拍攝車牌之裝置及語音喇叭裝置"],"a",
 "第6條：經同意籌設者應於同意之日起三個月內完成籌設，並檢附申請表、同意籌設證明文件、訓練合格證書、設備證明文件及現場完工證明文件申請認可證；電腦及周邊設備規格包括中央處理器 Intel Pentium4 2.4GHz 同等以上、記憶體 1GB 以上、網路頻寬下載 2M 及上傳 256K 以上且專線專用、顯示器十九吋以上、足以清晰拍攝車牌之拍攝裝置及喇叭裝置。",
 "By when must an approved applicant finish setting up and apply, and what equipment specs apply?",
 ["Within three months of approval it must finish and apply; bandwidth at least 2M download and 256K upload on a dedicated line, a 19-inch or larger monitor and at least 1 GB memory","Within six months of approval it must finish and apply; bandwidth at least 1M download and 128K upload which may be shared, a 15-inch or larger monitor and at least 512 MB memory","Within one year of approval it must finish and apply; bandwidth at least 10M download and 1M upload on a dedicated line, a 24-inch or larger monitor and at least 8 GB of memory","Within three months of approval it must finish and apply; bandwidth is unrestricted, a 19-inch monitor suffices, and no plate camera or speaker device need be installed"],
 "Article 6."),

(B,"第7條",2,"機車檢驗站-認可證審查",
 "主管機關受理機車排氣檢驗站認可申請之審查期限與核發程序為何？",
 ["應於三十日內完成書面審查；通過者於五十日內通知有關機關現場會勘，符合規定者於十日內核發認可證並副知中央主管機關","應於三十日內完成書面審查；通過者於五十日內通知有關機關現場會勘，符合規定者於十日內核發認可證，無須副知中央主管機關","應於六十日內完成書面審查；通過者於三十日內通知有關機關現場會勘，符合規定者於十五日內核發認可證並副知中央主管機關","應由中央主管機關於三十日內完成書面審查；通過者於五十日內辦理現場會勘，符合規定者於十日內核發認可證並副知地方主管機關"],"a",
 "第7條第1項、第2項：主管機關受理認可申請後應於三十日內完成書面審查，不符規定者通知限期補正，逾期未補正者駁回申請；書面審查通過者應於五十日內通知有關機關進行現場會勘，符合規定者應於十日內核發認可證，並副知中央主管機關。",
 "What review timeline and issuing procedure apply to the station approval certificate?",
 ["Paper review within 30 days; a site inspection notified within 50 days; the certificate issued within 10 days if compliant and copied to the central authority","Paper review within 30 days; a site inspection notified within 50 days; the certificate issued within 10 days if compliant, with no copy to the central authority","Paper review within 60 days; a site inspection notified within 30 days; the certificate issued within 15 days if compliant and copied to the central authority","The central authority does the paper review within 30 days; a site inspection within 50 days; the certificate issued within 10 days and copied to the local authority"],
 "Article 7, paragraphs 1 and 2."),

(B,"第8條",3,"機車檢驗站-設備認可",
 "電腦軟體、排氣分析儀及標準氣體認可申請之受理機關與審查期限為何？",
 ["向中央主管機關申請，中央主管機關應於三十日內完成審查，必要時得延長為六十日；符合規定者於十日內核發認可證，不符者通知限期補正","向直轄市、縣（市）主管機關申請，該機關應於三十日內完成審查，必要時得延長為九十日；符合規定者於十日內核發認可證並副知中央機關","向中央主管機關申請，中央主管機關應於六十日內完成審查，不得延長；符合規定者於三十日內核發認可證，不符規定者應逕予駁回申請","向目的事業主管機關申請，該機關應於十五日內完成審查，必要時得延長為三十日；符合規定者於五日內核發認可證並公告於資訊網站"],"a",
 "第8條第5項：中央主管機關於受理電腦軟體、排氣分析儀及標準氣體認可申請後，應於三十日內完成審查，必要時得延長為六十日；符合規定者應於十日內核發認可證；不符規定者應通知限期補正，逾期未補正者駁回其申請。第6項並定檢驗站應使用取得中央主管機關認可證之電腦軟體、排氣分析儀及標準氣體。",
 "Which agency reviews software, analyzer and standard gas approvals, and within what time?",
 ["The central authority; review within 30 days, extendable to 60 days; the certificate issued within 10 days if compliant, otherwise a correction notice is given","The municipal or county authority; review within 30 days, extendable to 90 days; the certificate issued within 10 days and copied to the central authority","The central authority; review within 60 days with no extension; the certificate issued within 30 days if compliant, otherwise the application is simply rejected","The industry authority; review within 15 days, extendable to 30 days; the certificate issued within 5 days and posted on the agency's website"],
 "Article 8, paragraph 5."),

(B,"第9條",3,"機車檢驗站-認可證記載變更",
 "機車排氣檢驗站認可證記載事項變更及負責人變更，應如何辦理？電腦軟體等認可證記載事項變更之期限為何？",
 ["記載事項變更前應以書面報經地方主管機關審查核准；負責人變更除有正當理由並經核准外應重新申請認可證；電腦軟體等認可證記載事項變更應於事實發生之日起十四日內報請中央機關辦理變更登記","記載事項變更後三十日內報請地方主管機關備查即可；負責人變更一律應重新申請認可證而無例外；電腦軟體等認可證記載事項變更應於事實發生之日起三十日內報請中央主管機關辦理變更登記","記載事項變更前應以書面報經中央主管機關審查核准；負責人變更僅需報請備查即可繼續使用原認可證；電腦軟體等認可證記載事項變更應於事實發生後六個月內報請地方主管機關變更","記載事項變更前應以書面報經地方主管機關審查核准；負責人變更應由新負責人重新籌設；電腦軟體等認可證記載事項如有變更，得俟認可證有效期限屆滿申請展延時一併辦理即可"],"a",
 "第9條第2項：認可證應記載事項變更前，應以書面報經直轄市、縣（市）主管機關審查核准。第3項：負責人變更，除有正當理由並檢附證明文件報經核准變更外，應重新申請認可證。第6項：電腦軟體、排氣分析儀及標準氣體認可證應記載事項有變更者，應於事實發生之日起十四日內以書面報請中央主管機關辦理變更登記。",
 "How are changes to the station certificate, its responsible person, and equipment certificates handled?",
 ["Changes need prior written approval by the local authority; a change of responsible person needs a new certificate unless justified and approved; equipment certificate changes are filed centrally within 14 days","Changes may be filed with the local authority within 30 days afterwards; a change of responsible person always needs a new certificate; equipment certificate changes are filed centrally within 30 days","Changes need prior written approval by the central authority; a change of responsible person only needs a filing to keep the certificate; equipment changes are filed locally within six months","Changes need prior written approval by the local authority; a change of responsible person requires setting up anew; equipment certificate changes may wait until the renewal application"],
 "Article 9, paragraphs 2, 3 and 6."),

(B,"第10條",3,"機車檢驗站-認可證展延",
 "機車排氣檢驗站認可證與電腦軟體認可證之有效期限及展延規定各為何？",
 ["檢驗站認可證有效期限五年，應於屆滿前三個月至四個月內申請展延，每次展延不得超過五年；電腦軟體認可證有效期限最長一年，每次展延不得超過次年年底","檢驗站認可證有效期限三年，應於屆滿前一個月至二個月內申請展延，每次展延不得超過三年；電腦軟體認可證有效期限最長二年，每次展延不得超過二年之期限","檢驗站認可證有效期限五年，應於屆滿前六個月至八個月內申請展延，每次展延不得超過十年；電腦軟體認可證有效期限最長三年，每次展延不得超過三年之期限","檢驗站認可證有效期限十年，屆滿後應重新申請而不得展延；電腦軟體認可證有效期限最長一年，屆滿後亦應重新申請認可而不得辦理任何展延手續"],"a",
 "第10條第1項：機車排氣檢驗站認可證之有效期限為五年，期限屆滿仍繼續使用者應於屆滿前三個月至四個月內向直轄市、縣（市）主管機關申請展延，每次展延期限不得超過五年。第3項：電腦軟體認可證有效期限最長為一年，應於屆滿前三個月至四個月內向中央主管機關申請展延，每次展延期限不得超過次年年底。",
 "What terms and renewal rules apply to the station certificate and the software certificate?",
 ["The station certificate lasts five years, renewed three to four months before expiry for up to five years; the software certificate lasts at most one year, each renewal running no later than the next year's end","The station certificate lasts three years, renewed one to two months before expiry for up to three years each time; the software certificate lasts at most two years, each renewal running up to two years","The station certificate lasts five years, renewed six to eight months before expiry for up to ten years each time; the software certificate lasts at most three years, each renewal running up to three years","The station certificate lasts ten years and must be applied for anew on expiry; the software certificate lasts at most one year and likewise must be applied for anew with no renewal available"],
 "Article 10, paragraphs 1 and 3."),

(B,"第10條",3,"機車檢驗站-儀器氣體展延",
 "排氣分析儀認可證與標準氣體認可證之有效期限及每次展延期限各為何？",
 ["排氣分析儀認可證有效期限五年，每次展延期限為二年；標準氣體認可證有效期限三年，每次展延期限為三年，均應於屆滿前三至四個月申請","排氣分析儀認可證有效期限二年，每次展延期限為五年；標準氣體認可證有效期限五年，每次展延期限為三年，均應於屆滿前一至二個月申請","排氣分析儀認可證有效期限三年，每次展延期限為三年；標準氣體認可證有效期限一年，每次展延期限為一年，均應於屆滿前六個月內申請","排氣分析儀認可證有效期限五年，每次展延期限為五年；標準氣體認可證有效期限五年，每次展延期限為五年，均應於屆滿前三至四個月申請"],"a",
 "第10條第5項：排氣分析儀認可證有效期限為五年，期限屆滿仍繼續使用者應於屆滿前三個月至四個月內向中央主管機關申請展延，每次展延期限為二年。第7項：標準氣體認可證有效期限為三年，應於屆滿前三個月至四個月內檢附第8條第2項規定文件申請展延，每次展延期限為三年。",
 "What are the terms and per-renewal periods for the analyzer and standard gas certificates?",
 ["The analyzer certificate lasts five years with each renewal for two years; the standard gas certificate lasts three years with each renewal for three years, both applied for three to four months before expiry","The analyzer certificate lasts two years with each renewal for five years; the standard gas certificate lasts five years with each renewal for three years, both applied for one to two months before expiry","The analyzer certificate lasts three years with each renewal for three years; the standard gas certificate lasts one year with each renewal for one year, both applied for within six months of expiry","The analyzer certificate lasts five years with each renewal for five years; the standard gas certificate lasts five years with each renewal for five years, both applied for three to four months before expiry"],
 "Article 10, paragraphs 5 and 7."),

(B,"第11條",2,"機車檢驗站-檢驗費用",
 "自一百十三年四月一日起，機車排氣檢驗站執行檢驗業務所需費用為何？由何機關負擔？",
 ["每輛新臺幣一百元，由中央主管機關補助之；申請核撥經費應依附錄一規定之程序及期限辦理","每輛新臺幣五十元，由直轄市縣市主管機關補助；申請核撥經費應依附錄二規定之程序及期限辦理","每輛新臺幣一百元，由車主於受檢時自行負擔；檢驗站應依附錄一規定之程序按月彙報收費情形","每輛新臺幣三百元，由中央與地方主管機關各負擔半數；申請核撥應依附錄一規定之程序辦理"],"a",
 "第11條第1項：自中華民國一百十三年四月一日起，機車排氣檢驗站執行機車排氣檢驗業務所需費用為每輛新臺幣一百元，由中央主管機關補助之。第2項：申請核撥機車排氣檢驗經費，應依附錄一規定之程序及期限辦理；第21條並定相關證明文件應保存二年。",
 "Since April 1, 2024, what is the testing fee per motorcycle and who bears it?",
 ["NT$100 per motorcycle, subsidized by the central authority; funds are claimed under the procedure and deadlines in Appendix 1","NT$50 per motorcycle, subsidized by the municipal or county authority; funds are claimed under the procedure in Appendix 2","NT$100 per motorcycle, paid by the owner at the time of testing; stations report collections monthly under Appendix 1","NT$300 per motorcycle, shared equally by central and local authorities; funds are claimed under the procedure in Appendix 1"],
 "Article 11, paragraphs 1 and 2."),

(B,"第12條",3,"機車檢驗站-檢驗業務規定",
 "機車排氣檢驗站執行檢驗業務之地點與檢驗時間有何規定？",
 ["應於認可證記載地址並符合核准之營業面積及檢驗線為之，變更前應報經核准；檢驗時間至少為每星期一至星期五上午十一時至下午七時，因故無法服務應事前於資訊管理系統登記暫停","應於認可證記載地址為之，營業面積及檢驗線變更後報請備查即可；檢驗時間至少為每星期一至星期六上午九時至下午五時，因故無法服務者得逕行停止而無須辦理任何登記","應於認可證記載地址或鄰近適當處所為之，變更前應報經核准；檢驗時間至少為每星期一至星期五上午八時至下午五時，因故無法服務應於事後七日內向主管機關補行報備","應於認可證記載地址並符合核准之營業面積及檢驗線為之，變更前應報經核准；檢驗時間由檢驗站視營運需要自行決定，僅須於營業場所明顯處張貼公告周知即可"],"a",
 "第12條第1項第2款：執行排氣檢驗之地點應於認可證記載地址為之，且應符合主管機關核准之營業面積及檢驗線；變更者應於變更前報經核准。第3款：檢驗時間至少為每星期一至星期五上午十一時至下午七時；因故無法於該期間內提供服務者，除國定假日或其他休息日外，應事前於機車排氣定期檢驗資訊管理系統登記暫停執行檢驗業務。",
 "What rules govern where and when testing business is carried out?",
 ["At the certified address within the approved area and lane, with prior approval for changes; testing hours at least Monday to Friday 11:00 to 19:00, with suspensions logged in advance in the information system","At the certified address, with area and lane changes merely filed afterwards; testing hours at least Monday to Saturday 09:00 to 17:00, and service may simply stop without any registration at all","At the certified address or a suitable nearby place, with prior approval for changes; testing hours at least Monday to Friday 08:00 to 17:00, with any suspension reported within seven days afterwards","At the certified address within the approved area and lane, with prior approval for changes; testing hours are set freely by the station, which need only post a notice at the premises"],
 "Article 12, paragraph 1, subparagraphs 2 and 3."),

(B,"第12條",3,"機車檢驗站-暫停與恢復",
 "檢驗站排氣分析儀量測不準確或未經核准變更原認可事項者，應如何處理？其紀錄保存年限為何？",
 ["直轄市縣市主管機關應暫停其檢驗；量測不準確者應檢送測試單位出具之檢測合格報告，未經核准變更者應檢送指定之改善證明文件，經核准後始得恢復；檢驗及保養校正紀錄應保存二年","直轄市縣市主管機關應逕行廢止其認可證；量測不準確者應重新申請認可證，未經核准變更者應繳納罰鍰後即可恢復檢驗業務；檢驗及保養校正紀錄應保存五年以備查核","中央主管機關應暫停撥付檢驗費用但不暫停檢驗業務；量測不準確者僅需自行維修並記錄於保養紀錄中即可繼續執行檢驗；檢驗及保養校正紀錄應保存一年以備查核","直轄市縣市主管機關應暫停其檢驗；量測不準確者由主管機關逕行送測並由主管機關負擔費用，改善完成後自動恢復檢驗業務；檢驗及保養校正紀錄應保存三年備查"],"a",
 "第12條第2項：經查核排氣分析儀量測不準確或未經核准變更原認可事項致影響檢驗業務執行者，直轄市、縣（市）主管機關應暫停其檢驗；屬量測不準確者應檢送測試單位出具之檢測合格報告，屬未經核准變更者應檢送指定之改善證明文件，報經核准後始得恢復執行檢驗業務。第1項第6款並定排氣檢驗及排氣分析儀保養校正應作成紀錄並保存二年。",
 "What follows an inaccurate analyzer or an unapproved change, and how long are records kept?",
 ["The local authority suspends testing; an inaccurate analyzer needs a testing unit's passing report and an unapproved change needs designated proof; approval restores business and records are kept two years","The local authority revokes the certificate outright; an inaccurate analyzer means reapplying for approval and an unapproved change is cured by paying a fine before resuming; records are kept five years","The central authority suspends fee payments but not testing; an inaccurate analyzer may simply be repaired and noted in the maintenance log while testing continues; records are kept one year","The local authority suspends testing; the authority itself sends the analyzer for testing at its own cost and business resumes automatically once corrected; records are kept three years"],
 "Article 12, paragraphs 1 and 2."),

(B,"第12條之1",2,"機車檢驗站-跨轄區遷移",
 "機車排氣檢驗站地址遷移至原主管機關轄區外者，應如何辦理？",
 ["應於遷移前向原主管機關申請廢止認可證並陳送新址籌設申請文件，由原機關廢止認可證並轉送申請文件予新址所在地主管機關受理","應於遷移後三十日內向新址所在地主管機關申請變更認可證記載地址，原認可證於新認可證核發前仍得繼續使用而不受影響","應於遷移前向中央主管機關申請核准，由中央主管機關逕行變更認可證所載地址，無須廢止原認可證亦無須重新辦理籌設程序","應於遷移前向新址所在地主管機關申請籌設，原主管機關之認可證於新站取得認可證之日起一年內仍屬有效並得同時營業"],"a",
 "第12條之1：機車排氣檢驗站地址遷移至原直轄市、縣（市）主管機關之轄區外者，應於遷移前向原主管機關申請廢止認可證及陳送新址籌設之申請文件，由原主管機關廢止認可證並轉送籌設申請文件予新址所在地之直轄市、縣（市）主管機關受理申請。",
 "How is a station relocating outside its original authority's jurisdiction handled?",
 ["Before moving it applies to the original authority to revoke the certificate and files new-site papers, which the original authority revokes and forwards to the new agency","Within 30 days after moving it applies to the new authority to change the address on the certificate, and the old certificate stays valid until the new one issues","Before moving it applies to the central authority, which simply changes the address on the certificate, with no revocation and no fresh establishment procedure","Before moving it applies to the new authority to establish a station, and the original certificate stays valid for a year so both may operate at once"],
 "Article 12-1."),

(B,"第13條",3,"機車檢驗站-檢驗人員",
 "機車排氣檢驗應由何人為之？檢驗人員之訓練與異動報備規定為何？",
 ["應由檢驗人員為之；檢驗人員應接受地方主管機關調訓及每年四小時以上在職訓練，檢驗站不得拒絕；檢驗人員離職或異動時負責人應於事實發生後七日內以書面報請備查","應由檢驗人員為之；檢驗人員應接受中央主管機關調訓及每二年八小時以上在職訓練，檢驗站得因業務繁忙拒絕；離職異動應於事實發生後三十日內報請備查","應由具技術士證照者為之；檢驗人員應每三年接受一次複訓，地方主管機關並得視需要辦理調訓；離職異動應由檢驗人員本人於事實發生後十四日內報請備查","應由檢驗人員為之；檢驗人員應接受地方主管機關調訓及每年二十小時以上在職訓練，檢驗站不得拒絕；離職異動應由負責人於次年度換證時一併辦理報備手續"],"a",
 "第13條第1項：機車排氣檢驗應由檢驗人員為之。第2項：檢驗人員應接受直轄市、縣（市）主管機關之調訓及每年四小時以上之在職訓練，機車排氣檢驗站不得拒絕。第3項：檢驗人員發生離職或異動時，檢驗站負責人應於事實發生後七日內以書面報請直轄市、縣（市）主管機關備查。違反第2項、第3項者依第20條暫停撥付檢驗費用。",
 "Who performs the testing, and what training and personnel-change rules apply?",
 ["Only registered personnel; they must attend local training and at least four hours of on-the-job training a year, which the station may not refuse; departures are filed in writing within seven days","Only registered testing personnel; they must attend central authority training and at least eight hours every two years, which a busy station may refuse; departures are filed within 30 days","Only licensed technicians; they must retrain once every three years and the local authority may call training as needed; departures are filed by the person within 14 days","Only registered testing personnel; they must attend local training and at least twenty hours a year, which the station may not refuse; departures are filed at the next annual renewal"],
 "Article 13, paragraphs 1 to 3."),

(B,"第14條",3,"機車檢驗站-儀器查核",
 "排氣分析儀之查核頻率、送檢時機及費用負擔為何？",
 ["地方主管機關或其委託單位每年應至少執行一次查核；查核不合格或日常氣體比對每季不合格率達百分之十以上者得限期令送測試單位檢驗；相關檢驗費用由機車排氣檢驗站負擔","地方主管機關或其委託單位每二年應至少執行一次查核；查核不合格或日常氣體比對每季不合格率達百分之三十以上者得限期令送檢；相關檢驗費用由中央主管機關全額負擔","中央主管機關每半年應至少執行一次查核；查核不合格或日常氣體比對每年不合格率達百分之十以上者應逕行廢止其認可證；相關檢驗費用由委託之測試單位自行吸收","地方主管機關或其委託單位每年應至少執行一次查核；查核不合格者得由檢驗站自行維修後逕行恢復使用而無須複驗；相關檢驗費用由地方主管機關編列預算支應"],"a",
 "第14條第2項：直轄市、縣（市）主管機關或其委託單位每年應針對機車排氣檢驗站執行至少一次排氣分析儀查核。第3項：查核結果不合格或經中央主管機關統計日常氣體比對結果每季不合格率達百分之十以上者，得限期令送至排氣分析儀測試單位進行檢驗。第4項：檢驗不合格者應於維修完成後複驗，確認改善完成前不得使用。第5項：檢驗站應負擔相關費用。",
 "How often are analyzers audited, when must they be sent for testing, and who pays?",
 ["The local authority or its agent audits at least once a year; failure or a quarterly gas comparison failure rate of 10 percent or more may require testing by a testing unit; the station bears the cost","The local authority or its agent audits at least once every two years; failure or a quarterly failure rate of 30 percent or more may require testing; the central authority bears the whole cost","The central authority audits at least twice a year; failure or an annual failure rate of 10 percent or more leads to revoking the certificate outright; the commissioned testing unit bears the cost","The local authority or its agent audits at least once a year; a failed analyzer may simply be repaired and used again without retesting; the local authority funds the costs from its budget"],
 "Article 14, paragraphs 2 to 5."),

(B,"第15條",1,"機車檢驗站-撤銷認可",
 "申請機車排氣檢驗站、電腦軟體、排氣分析儀或標準氣體認可之文件有虛偽不實者，主管機關得如何處理？",
 ["主管機關得撤銷其認可證","主管機關得科處罰鍰但不撤銷","主管機關應通知限期補正文件","主管機關得暫停其檢驗業務一年"],"a",
 "第15條：申請機車排氣檢驗站、電腦軟體、排氣分析儀或標準氣體認可之文件，有虛偽不實者，主管機關得撤銷其認可證。第16條則另定得撤銷或廢止檢驗站認可證之六款事由。",
 "What may the agency do if approval application documents are false?",
 ["The agency may revoke the approval certificate","The agency may fine but not revoke the certificate","The agency must give a period to correct them","The agency may suspend testing business for a year"],
 "Article 15."),

(B,"第16條",3,"機車檢驗站-撤銷廢止事由",
 "下列何者為直轄市、縣（市）主管機關得撤銷或廢止機車排氣檢驗站認可證之事由？",
 ["業務文書為虛偽記載；以違規或不正方式執行檢驗致影響檢驗數值；認可證有效期限內受停止檢驗業務處分累計達三次；申請暫停檢驗業務累計時間超過一年","業務文書為虛偽記載；檢驗人員未參加在職訓練累計達三次；認可證有效期限內受罰鍰處分累計達二次；申請暫停檢驗業務累計時間超過三個月之情形","營業場所環境未保持整潔；檢驗設備未依規定校正；認可證有效期限內受停止檢驗業務處分累計達一次；申請暫停檢驗業務累計時間超過六個月者","檢驗費用申請核撥資料有誤；排氣分析儀查核不合格一次；認可證有效期限內變更負責人；申請暫停檢驗業務累計時間超過二年之情形者"],"a",
 "第16條第1項：檢驗站執行檢驗於業務上作成之文書為虛偽記載、以違規或不正方式執行檢驗業務致影響檢驗數值、認可證有效期限內受停止檢驗業務處分累計達三次、認可證有效期限內申請暫停檢驗業務累計時間超過一年、違反第9條第3項未經核准變更負責人、其他違反本辦法經認定情節重大者，得撤銷或廢止其認可證。",
 "Which grounds allow revocation or annulment of a station's approval certificate?",
 ["False entries in business documents; irregular or improper testing affecting the readings; three suspensions of testing business within the certificate term; over a year of requested suspension in total","False entries in business documents; personnel missing on-the-job training three times; two fines imposed within the certificate term; over three months of requested suspension in total","Failing to keep the premises tidy; failing to calibrate equipment as required; one suspension of testing business within the certificate term; over six months of requested suspension in total","Errors in the fee reimbursement papers; one failed analyzer audit; a change of responsible person during the term; over two years of requested suspension in total"],
 "Article 16, paragraph 1."),

(B,"第16條",3,"機車檢驗站-一年計算與限制",
 "第十六條所稱暫停檢驗業務累計一年如何計算？認可證經撤銷或廢止後有何限制？",
 ["一年共計五十二週、每週五日、每日八小時計算，包含第十二條第二項暫停檢驗期間但不含第十七條停業處分時數；撤銷廢止後三年內不得以相同或類似站名及統一編號申請，負責人亦同","一年共計三百六十五日、每日二十四小時計算，並包含第十七條停業處分時數；撤銷廢止後一年內不得以相同或類似站名申請認可，負責人於一年內不得重行申請擔任檢驗站之負責人","一年共計五十二週、每週七日、每日十小時計算，且不含第十二條第二項暫停檢驗期間；撤銷廢止後五年內不得以相同統一編號申請認可，負責人五年內不得重行申請為檢驗站負責人","一年共計十二個月，以曆月方式計算而不論實際營業時數；撤銷廢止後三年內不得以相同站名申請，惟負責人得隨時另行申請擔任其他檢驗站之負責人而不受限制"],"a",
 "第16條第2項：所稱一年，共計五十二週、每週五日、以每日八小時計算；該款累計時間應包含依第12條第2項暫停檢驗期間，但不含第17條第2項停止檢驗業務處分之時數。第3項：認可證經撤銷或廢止者，於三年內不得以相同或類似站名及相同統一編號申請認可；其負責人於三年內不得重行申請為檢驗站之負責人。第4項並定違規檢驗人員得註銷登錄且一年內不得登錄。",
 "How is the one year of suspension counted, and what limits follow revocation?",
 ["One year means 52 weeks, five days a week, eight hours a day, counting Article 12-2 suspensions but not Article 17-2 penalties; after revocation, three years barred by station name and tax number, and the person likewise","One year means 365 days of 24 hours each, including Article 17-2 penalty hours; after revocation, one year without the same or similar station name, and the responsible person barred one year from applying again","One year means 52 weeks, seven days a week, ten hours a day, excluding Article 12-2 suspensions; after revocation, five years without the same tax number, and the responsible person barred five years","One year means twelve calendar months regardless of actual business hours; after revocation, three years without the same station name, though the responsible person may apply elsewhere at any time"],
 "Article 16, paragraphs 2 to 4."),

(B,"第17條",3,"機車檢驗站-罰鍰事由",
 "下列何者屬直轄市、縣（市）主管機關得依本法第八十條第四項處以罰鍰之情形？",
 ["違反第十二條第一項第一款至第七款規定一年內累計達三次；未於所定限期內將排氣分析儀送檢；服務態度不佳經檢舉查證屬實；一年內輸入錯誤檢驗日期時間車牌且未主動通報累計達五筆","違反第十二條第一項第一款至第七款規定一年內累計達一次；未於所定限期內將排氣分析儀送檢；營業場所面積不足；一年內輸入錯誤檢驗資料且未主動通報累計達二筆之情形","違反第十二條第一項各款規定一年內累計達五次；排氣分析儀查核不合格一年內累計達一次；檢驗人員未登錄；一年內輸入錯誤檢驗資料經主動通報修正累計達十筆之情形","違反第九條第二項規定未經核准變更記載事項；排氣分析儀日常氣體比對每季不合格率達百分之五以上；服務態度不佳經檢舉；一年內申請暫停檢驗業務累計達三次之情形"],"a",
 "第17條第1項：違反第8條第6項、第9條第2項、第6項、第12條第1項第8款或第13條第1項、第14條第1項及第4項規定；違反第12條第1項第1款至第7款規定一年內累計達三次；未於第14條第3項所定限期內將排氣分析儀送檢；查核不合格或日常氣體比對每季不合格率達百分之十以上者一年內累計達三次；服務態度不佳經檢舉查證屬實；一年內輸入錯誤檢驗日期時間車牌未主動通報累計達五筆者，得處以罰鍰。",
 "Which situations allow the local authority to impose a fine under Article 80-4 of the Act?",
 ["Three breaches within a year of Article 12-1 items 1 to 7; failing to send the analyzer for testing in time; poor service confirmed on complaint; five uncorrected wrong entries of date, time or plate in a year","One breach within a year of Article 12-1 items 1 to 7; failing to send the analyzer for testing in time; insufficient business floor area; two uncorrected wrong-entry records within one year","Five breaches within a year of any item of Article 12-1; one failed analyzer audit in a year; unregistered testing personnel; ten wrong entries in a year that were voluntarily reported and corrected","Changing recorded items without approval under Article 9-2; a quarterly gas comparison failure rate of 5 percent or more; poor service upon complaint; three suspension applications within one year"],
 "Article 17, paragraph 1."),

(B,"第17條",2,"機車檢驗站-停業處分",
 "機車排氣檢驗站一年內受罰鍰處分累計達幾次時，主管機關得為何種處分？",
 ["一年內累計達三次者，得視情節輕重停止機車排氣檢驗業務一至三個月","一年內累計達二次者，得視情節輕重停止機車排氣檢驗業務三至六個月","一年內累計達五次者，得視情節輕重停止機車排氣檢驗業務六至十二個月","一年內累計達三次者，應逕予廢止其認可證並命其立即停止營業之行為"],"a",
 "第17條第2項：一年內受直轄市、縣（市）主管機關罰鍰之處分累計達三次者，直轄市、縣（市）主管機關得視情節輕重停止機車排氣檢驗業務一至三個月。第16條第1項第3款並定認可證有效期限內受停止檢驗業務處分累計達三次者，得撤銷或廢止其認可證。",
 "After how many fines in a year may the agency suspend testing business, and for how long?",
 ["After three fines in a year, testing business may be suspended for one to three months by severity","After two fines in a year, testing business may be suspended for three to six months by severity","After five fines in a year, testing business may be suspended for six to twelve months by severity","After three fines in a year, the certificate must be annulled and business stopped immediately"],
 "Article 17, paragraph 2."),

(B,"第18條",2,"機車檢驗站-移動式檢驗站",
 "移動式機車排氣檢驗站得由何者設置？其管理準用哪些規定？",
 ["直轄市、縣（市）主管機關得委託專業技術機構或固定式機車排氣檢驗站設置；其管理準用第九條至第十四條及第十七條規定","中央主管機關得委託專業技術機構或機車製造業者設置；其管理準用第四條至第八條及第十五條至第十六條規定辦理之","直轄市、縣（市）主管機關應自行設置而不得委託任何機構；其管理準用第九條至第十四條及第十七條至第二十條規定","目的事業主管機關得委託加油站業者設置；其管理準用第十條至第十三條規定，惟不適用罰鍰及停業處分之相關規定"],"a",
 "第18條第1項：直轄市、縣（市）主管機關得委託專業技術機構或固定式機車排氣檢驗站，設置移動式機車排氣檢驗站。第2項：移動式機車排氣檢驗站之管理準用第9條至第14條及第17條規定。第12條第1項第4款並定移動式檢驗站之檢驗地點及時間應報經核准後執行。",
 "Who may set up a mobile testing station, and which provisions govern it?",
 ["The local authority may commission a professional technical body or a fixed station; management follows Articles 9 to 14 and Article 17 mutatis mutandis","The central authority may commission a technical body or motorcycle makers; management follows Articles 4 to 8 and Articles 15 to 16 mutatis mutandis","The local authority must set one up itself and may commission no one; management follows Articles 9 to 14 and Articles 17 to 20 mutatis mutandis","The industry authority may commission filling station operators; management follows Articles 10 to 13, with the fine and suspension rules not applying"],
 "Article 18, paragraphs 1 and 2."),

(B,"第19條",1,"機車檢驗站-文書格式",
 "本辦法所定之相關文書格式由何機關訂定？",
 ["由中央主管機關定之","由直轄市縣市主管機關定之","由目的事業主管機關定之","由中央與地方會銜共同定之"],"a",
 "第19條：本辦法所定之相關文書格式，由中央主管機關定之。第11條第2項所定申請核撥檢驗經費之附錄一程序、第12條第1項第1款所定附錄二標準作業程序亦屬之。",
 "Who prescribes the document formats required by these Regulations?",
 ["The central competent authority","The municipal or county authority","The relevant industry authority","Central and local agencies jointly"],
 "Article 19."),

(B,"第20條",2,"機車檢驗站-暫停撥付",
 "違反第九條第二項或第十三條第二項、第三項規定者，中央主管機關應如何處理？",
 ["經地方主管機關通知後，中央主管機關應暫停撥付檢驗業務檢驗費用，俟改善完成後再行撥款","經地方主管機關通知後，中央主管機關應逕行廢止其認可證，俟改善完成後始得重新申請認可","經地方主管機關通知後，中央主管機關應追繳其已領取之全部補助款並加計利息一併返還","經地方主管機關通知後，中央主管機關應命其停止檢驗業務三個月，並不得申請任何補助款"],"a",
 "第20條第1項：違反第9條第2項規定者，經直轄市、縣（市）主管機關通知中央主管機關後，中央主管機關應暫停撥付執行機車排氣檢驗業務檢驗費用，俟改善完成後再行撥款。第2項：違反第13條第2項及第3項規定者亦同。",
 "What follows a breach of Article 9-2 or Article 13-2 and 13-3?",
 ["On notice from the local authority, the central authority suspends payment of the testing fees until the breach is corrected","On notice from the local authority, the central authority annuls the certificate, and approval must be applied for anew","On notice from the local authority, the central authority recovers all subsidies already paid together with interest","On notice from the local authority, the central authority orders three months' suspension and bars any subsidy claim"],
 "Article 20, paragraphs 1 and 2."),

(B,"第21條",3,"機車檢驗站-經費核撥",
 "機車排氣檢驗站申請核撥檢驗經費之證明文件保存年限，及溢發或不實請領之處理為何？",
 ["證明文件應保存二年；溢發者應通知繳回並作成書面處分命於六十日內繳還，屆時未繳還者依法移送行政執行；明知不實而提出者應返還補助並自補助之日起加計利息","證明文件應保存五年；溢發者應通知繳回並命於三十日內繳還，屆時未繳還者移送司法機關偵辦；明知不實而提出者僅須返還補助而無須加計任何利息之負擔","證明文件應保存二年；溢發者得由檢驗站於次年度補助款中自行抵扣而無須另行繳回；明知不實而提出者應返還補助並自查獲之日起加計利息計算之","證明文件應保存十年；溢發者應通知繳回並命於九十日內繳還；不足者不予補發；明知不實而提出者除返還補助外並應處以該補助金額三倍之罰鍰處分"],"a",
 "第21條第1項：申請核撥檢驗經費之相關證明文件應保存二年備查。第2項：經審核不予補助者得重新核計，不足者應予補發；溢發者應通知繳回並作成書面行政處分命其於六十日內繳還補助款，屆時未繳還者依法移送行政執行。第3項：明知不實而提出者應返還已領取之補助，並自補助領取日起至返還日止加計利息。第4項並定得以尚未領取之補助抵充。",
 "How long are fee claim documents kept, and how are overpayments or false claims handled?",
 ["Documents are kept two years; overpayments must be repaid within 60 days by written order, failing which compulsory execution follows; knowingly false claims are repaid with interest from the payment date","Documents are kept five years; overpayments must be repaid within 30 days, failing which the case is referred for prosecution; knowingly false claims need only be repaid without any interest at all","Documents are kept two years; overpayments may simply be offset against the next year's subsidy without repayment; knowingly false claims are repaid with interest from the date of discovery","Documents are kept ten years; overpayments must be repaid within 90 days; shortfalls are not made up; knowingly false claims are repaid and fined three times the subsidy amount"],
 "Article 21, paragraphs 1 to 3."),

(B,"第22條",1,"機車檢驗站-施行日",
 "機車排放空氣污染物檢驗站設置及管理辦法之施行日期為何？",
 ["本辦法自發布日施行","本辦法自發布後六個月施行","本辦法自一百十三年四月一日施行","本辦法自次年一月一日開始施行"],"a",
 "第22條：本辦法自發布日施行。本辦法最近一次修正日期為民國一百十三年四月十七日；第11條所定一百十三年四月一日則為每輛新臺幣一百元檢驗費用補助之起算日。",
 "When do these Regulations take effect?",
 ["They take effect on the date of promulgation","They take effect six months after promulgation","They take effect on April 1, 2024 in all cases","They take effect on January 1 of the next year"],
 "Article 22."),

]
