# -*- coding: utf-8 -*-
# 第 9 批（D3）：開發行為環境影響評估作業準則（ENV-65）逐條題（第1～30條；第29條已刪除）
GL = "ENV-65"
Q = [
(GL,"第1條",1,"評估準則-法源",
 "開發行為環境影響評估作業準則之訂定依據為何？",
 ["環境影響評估法第五條第二項","環境影響評估法第七條第一項","環境影響評估法第十三條第三項","環境影響評估法第二十六條規定"],"a",
 "第1條：本準則依環境影響評估法第五條第二項規定訂定之。與開發行為應實施環境影響評估細目及範圍認定標準同屬環評法第五條第二項之授權命令，前者定應否實施環評，本準則則定書件之製作方式。",
 "Under which provision are these Guidelines enacted?",
 ["Article 5, paragraph 2 of the Environmental Impact Assessment Act","Article 7, paragraph 1 of the Environmental Impact Assessment Act","Article 13, paragraph 3 of the Environmental Impact Assessment Act","Article 26 of the Environmental Impact Assessment Act"],
 "Article 1."),

(GL,"第2條",1,"評估準則-適用範圍",
 "依認定標準認定應實施環境影響評估之開發行為，其說明書或評估書之製作應依何規定？",
 ["依本準則之規定；本準則未規定者，適用其他法令","依開發單位自訂之作業規範；本準則僅供參考適用","依目的事業主管機關函釋；本準則不生拘束力效果","依環評審查委員會決議；本準則僅適用於政府機關"],"a",
 "第2條：依開發行為應實施環境影響評估細目及範圍認定標準認定應實施環境影響評估之開發行為，其環境影響說明書或環境影響評估報告書之製作，依本準則之規定；本準則未規定者，適用其他法令。第59條並補充規定，環評作業法令未規定者，以主管機關環評審查委員會之決議為準。",
 "How must EIA statements and reports be prepared for developments requiring EIA?",
 ["In accordance with these Guidelines; matters not covered are governed by other laws","In accordance with the developer's own rules; these Guidelines are merely advisory","In accordance with interpretive letters of the industry authority, which bind instead","In accordance with review committee resolutions; the Guidelines bind agencies only"],
 "Articles 2 and 59."),

(GL,"第3條",3,"評估準則-綜合評估者",
 "環評法第6條第2項第3款及第11條第2項第3款所定綜合評估者，應具備何種資格？",
 ["領有本國環境工程技師證書且有一年以上環評工作經歷；或相關專業大學以上學歷、二年以上環評經歷並接受環評專業訓練四十小時以上領有合格證明",
  "領有本國環境工程技師證書且有三年以上環評工作經歷；或相關專業大學以上學歷、五年以上環評經歷並接受環評專業訓練一百小時以上領有合格證明",
  "領有任何類科技師證書且有六個月以上環評工作經歷；或相關專業專科以上學歷、一年以上環評經歷並接受環評專業訓練二十小時以上領有合格證明",
  "領有本國環境工程技師證書且有二年以上環評工作經歷；或相關專業碩士以上學歷、三年以上環評經歷並接受環評專業訓練六十小時以上領有合格證明"],"a",
 "第3條第1項：綜合評估者應具下列資格之一：領有本國環境工程技師證書且有一年以上環評工作經歷；具撰寫內容相關項目專業之大學以上學歷且有二年以上環評工作經歷並接受環評專業訓練達四十小時以上領有合格證明；曾擔任二案以上經主管機關審查通過之綜合評估者；具影響項目撰寫者資格之一且有三年以上環評工作經歷。第2項並定影響項目撰寫者資格（大學以上學歷一年經歷或訓練十小時；專科以上學歷二年經歷或訓練二十小時）。",
 "What qualifications must a comprehensive assessor hold?",
 ["A domestic environmental engineer licence plus one year of EIA experience; or a relevant bachelor's degree, two years of EIA experience and 40 hours of certified EIA training",
  "A domestic environmental engineer licence plus three years of EIA experience; or a relevant bachelor's degree, five years of EIA experience and 100 hours of certified EIA training",
  "Any category of engineer licence plus six months of EIA experience; or a relevant junior college degree, one year of EIA experience and 20 hours of certified EIA training",
  "A domestic environmental engineer licence plus two years of EIA experience; or a relevant master's degree, three years of EIA experience and 60 hours of certified EIA training"],
 "Article 3, paragraphs 1 and 2."),

(GL,"第4條",2,"評估準則-約定值",
 "開發行為對環境之影響及環境品質之評估，於環境特性需要時開發單位應採何種方式？",
 ["採用更嚴格之約定值、最佳可行污染防制（治）技術、總量抵減措施或零排放等方式",
  "採用較寬鬆之替代值、一般常用污染防制技術、排放交易措施或稀釋排放等方式",
  "採用主管機關公告之平均值、既有污染防制設備、異地補償措施或分期排放方式",
  "採用同業慣用之參考值、最低成本污染防制技術、行政指導措施或間歇排放方式"],"a",
 "第4條第1項：開發行為對環境之影響及環境品質之評估均應符合相關環境保護法令規定；其因環境之特性，開發單位應採用更嚴格之約定值、最佳可行污染防制（治）技術、總量抵減措施或零排放等方式為之，以符合環境品質標準或使現已不符環境品質標準者不致繼續惡化。第2項：約定值係指開發單位評估環境負荷後設定之排放值，或於說明書、評估書初稿、評估書所作之承諾值，亦或為主管機關於審查時之設定值。",
 "Where environmental characteristics require it, what approach must the developer adopt?",
 ["Stricter agreed values, best available pollution control technology, total load offsetting measures, or zero discharge","Looser alternative values, commonly used control technology, emission trading measures, or dilution discharge","Announced average values, existing control equipment, off-site compensation measures, or phased discharge","Industry reference values, least-cost control technology, administrative guidance measures, or intermittent discharge"],
 "Article 4."),

(GL,"第5條",2,"評估準則-預審",
 "開發單位得於製作說明書時檢具環評法第6條第2項第4款至第8款資料辦理預審，其程序為何？",
 ["向目的事業主管機關提出，並由目的事業主管機關轉送主管機關預審；預審會議結論應納為環評作業重點",
  "直接向主管機關提出預審申請，主管機關應於三十日內作成預審決定；預審結論僅供開發單位參考之用",
  "向當地鄉鎮市公所提出，由公所轉送地方民意機關預審；預審會議結論對開發單位不生任何拘束效力",
  "向環評審查委員會委員個別徵詢意見後彙整提出；徵詢結果應公告於指定網站三十日並開放民眾表達"],"a",
 "第5條第1項：開發單位得於製作說明書時，檢具本法第6條第2項第4款至第8款資料，向目的事業主管機關提出，並由目的事業主管機關轉送主管機關預審。第2項：主管機關得就環境影響評估有關事項邀集環評審查委員會委員、專家學者及相關機關、團體召開預審會議；其會議結論，開發單位應納為環境影響評估作業重點。",
 "What is the procedure for pre-review of an EIA statement?",
 ["Submit to the industry authority, which forwards it to the competent authority for pre-review; the conclusions must be treated as key points of the EIA work",
  "Apply directly to the competent authority, which must decide within 30 days; the conclusions serve only as a non-binding reference for the developer itself",
  "Submit to the township office, which forwards it to the local council for pre-review; the conclusions do not bind the developer at all",
  "Consult review committee members individually and compile their views; the results are posted online for 30 days for public comment"],
 "Article 5."),

(GL,"第6條",2,"評估準則-程序審查",
 "主管機關收到說明書或評估書初稿時，應進行何種審查？其書件不符規定時如何處理？",
 ["應進行程序審查，依附件一記載確定程序及書件內容符合規定；有未符合者得不予受理並副知目的事業主管機關",
  "應逕行進入實質審查，並於受理後三十日內作成審查結論；書件不符規定者一律退回且不得再行提出申請",
  "應交由環評審查委員會逐條表決是否受理，未經表決通過者，開發單位應重新踐行公開會議程序後再提出",
  "應公告於指定網站徵詢民眾意見三十日後始得受理；書件不符規定者由目的事業主管機關代為補正即可"],"a",
 "第6條：主管機關收到說明書或評估書初稿，應進行程序審查，依附件一記載，確定其程序及書件內容符合相關規定；有未符合者，主管機關得不予受理，並副知目的事業主管機關。但經主管機關同意限期補件者，不在此限。",
 "What review does the competent authority conduct on receiving an EIA statement or draft report?",
 ["A procedural review under Annex 1 confirming the procedure and contents comply; non-compliant documents may be rejected with a copy to the industry authority",
  "An immediate substantive review with conclusions issued within 30 days of acceptance; non-compliant documents are returned and may never be resubmitted",
  "A committee vote on whether to accept it; if the vote fails the developer must repeat the public meeting procedure before resubmitting",
  "A 30-day public consultation on the designated website before acceptance; the industry authority corrects any non-compliant documents"],
 "Article 6."),

(GL,"第7條",2,"評估準則-免程序審查",
 "何種情形下，主管機關得免除說明書或評估書初稿之程序審查？",
 ["經第3條第1項第1款至第3款之綜合評估者簽名，或開發單位委託經中央主管機關最近連續二次評鑑合格之技術顧問機構製作者",
  "經開發單位負責人親自簽名，或委託任何領有公司登記證明之環境工程顧問公司製作，並檢附委託契約書影本者",
  "經目的事業主管機關出具書面推薦，或開發單位曾有三案以上通過環評之紀錄，並向主管機關繳納審查費用者",
  "經環評審查委員會主任委員同意，或開發行為屬政府重大公共建設計畫，並經行政院列入年度施政計畫項目者"],"a",
 "第7條第1項：經第3條第1項第1款至第3款之綜合評估者簽名或開發單位委託經中央主管機關最近連續二次評鑑合格之技術顧問機構製作之說明書或評估書初稿，依本法第7條或第13條送主管機關審查時，主管機關得免程序審查。第2項：書件未依規定記載或不符本準則者，主管機關得公告其不符事項，或對日後由其簽名、製作之書件從嚴程序審查。",
 "When may the competent authority waive the procedural review?",
 ["When signed by a comprehensive assessor under Article 3(1)(1) to (3), or prepared by a consultancy that passed the central authority's two most recent consecutive evaluations",
  "When signed personally by the developer's responsible person, or prepared by any registered environmental engineering consultancy with a copy of the contract attached",
  "When the industry authority issues a written recommendation, or the developer has three prior approved EIA cases and has paid the review fee",
  "When the review committee chair consents, or the development is a major public works project listed in the Executive Yuan's annual policy plan"],
 "Article 7."),

(GL,"第8條",3,"評估準則-環境敏感地區",
 "開發行為基地位於環境敏感地區者，開發單位應如何辦理？",
 ["應敘明選擇該地區為基地之原因；不得位於法律禁止開發利用之地區；不得違反限制開發地區之限制規定；並將應保護範圍納入環境保護對策",
  "應敘明選擇該地區為基地之經濟效益；得位於法律禁止開發利用之地區但須加倍補償；限制開發地區之規定得經主管機關同意後排除適用之",
  "應檢附土地所有權人同意書；位於法律禁止開發利用之地區者應提高綠覆比例；限制開發地區僅需於施工前報請當地公所備查即可辦理",
  "應繳納環境敏感地區開發回饋金；位於法律禁止開發利用之地區者應辦理第二階段環評；限制開發地區之限制規定得以替代方案取代之"],"a",
 "第8條第1項：開發單位應先查明開發行為基地，依附件二環境敏感地區調查表調查所列之地區，並檢附有關單位證明、圖件或實地調查研判資料；基地位於環境敏感地區者，應敘明選擇該地區為基地之原因。第2項：並應辦理：基地不得位於相關法律所禁止開發利用之地區；位於相關法令所限制開發利用之地區者不得違反該限制規定；對環境敏感地區中應予保護之範圍及對象，應詳予評估並納入環境保護對策。",
 "What must a developer do when the site lies in an environmentally sensitive area?",
 ["State why the area was chosen; the site may not lie in areas where law prohibits development; restrictions on restricted areas must not be violated; protected features go into the protection measures",
  "State the economic benefits of the choice; the site may lie in prohibited areas with doubled compensation; restrictions on restricted areas may be waived with the competent authority's written consent",
  "Attach the landowner's consent; raise the green coverage ratio if in a prohibited area; restricted areas need only be filed with the township office before construction",
  "Pay a sensitive-area development feedback levy; conduct a second-stage EIA if in a prohibited area; restrictions on restricted areas may be replaced by alternative plans"],
 "Article 8."),

(GL,"第9條",2,"評估準則-開始評估刊登",
 "開發單位於開始進行環境影響評估時，應於指定網站刊登事項供表達意見之期間為何？並應告知哪些對象？",
 ["自刊登日起二十日內表達意見；並以書面告知目的事業主管機關及基地所在地之縣市政府、縣市議會、鄉鎮市區公所、鄉鎮市代表會及村里辦公處",
  "自刊登日起十日內表達意見；並以口頭告知目的事業主管機關及基地所在地之縣市政府、縣市議會、鄉鎮市區公所、鄉鎮市代表會及村里辦公處等",
  "自刊登日起六十日內表達意見；並以書面告知中央主管機關及基地所在地之警察機關、消防機關、衛生機關、地政機關及戶政事務所等單位",
  "自刊登日起三十日內表達意見；並以公告方式告知目的事業主管機關及基地周界五百公尺內之全體土地所有權人與建築物所有權人等"],"a",
 "第9條第1項：開發單位於開始進行環境影響評估時，應於中央主管機關指定網站刊登開發行為名稱、開發單位名稱、開發行為內容基地及地理位置圖、預定調查或蒐集之項目地點時間及頻率，供民眾、團體及機關於刊登日起二十日內以書面或於指定網站表達意見。第2項：並應以書面告知目的事業主管機關及基地所在地之直轄市或縣市政府、議會、鄉鎮市區公所、鄉鎮市代表會、村里辦公處。第3項：應記載並參酌所表達意見據以檢討規劃評估內容。",
 "What comment period and notification apply when EIA work begins?",
 ["Comments within 20 days of posting; written notice to the industry authority and the local government, council, township office, township representative council and village office",
  "Comments within 10 days of posting; oral notice to the industry authority and the local government, council, township office, township representative council and village office",
  "Comments within 60 days of posting; written notice to the central authority and the local police, fire, health and land administration agencies and household registration office",
  "Comments within 30 days of posting; public notice to the industry authority and all landowners and building owners within 500 m of the site boundary"],
 "Article 9."),

(GL,"第10條",3,"評估準則-環境調查",
 "開發單位依附表七進行環境品質現況調查時，應如何辦理？",
 ["應優先引用政府機關已公布之最新資料或其他單位長期調查累積之具代表性資料，如不引用時應進行現地調查，但應於附表九敘明理由",
  "一律應自行進行現地調查，不得引用任何既有資料，且調查期間不得少於一年，並應於附表九敘明調查人員之學經歷及證照字號",
  "應優先引用開發單位過去自行調查之資料，如無資料時得委託顧問公司以模式推估替代，並免於附表九敘明其理由及推估之依據",
  "應優先引用鄰近開發案之環評書件資料，如不引用時應報請主管機關核准後始得進行現地調查，並將原始數據列為工商機密保密"],"a",
 "第10條第2項：開發單位依附表七進行環境品質現況調查時，應優先引用政府機關已公布之最新資料，或其他單位長期調查累積之具代表性資料，如不引用時，應進行現地調查；但應於附表九敘明理由。第3項：現地調查之資料應於指定網站依規定格式傳輸原始數據。第4項：因區位環境或開發行為特性得調整附表七所規定之調查項目、方法、地點、時間或頻率，但應於附表九敘明理由。",
 "How must the developer conduct the environmental quality baseline survey?",
 ["Give priority to the latest published government data or representative long-term data; otherwise conduct field surveys, stating the reason in Table 9",
  "Always conduct field surveys with no use of existing data, for at least one year, stating surveyors' qualifications and licence numbers in Table 9",
  "Give priority to the developer's own past data; where none exists, use consultant model estimates, with no need to state reasons in Table 9",
  "Give priority to EIA documents of nearby projects; otherwise obtain approval before field surveys and keep the raw data as a trade secret"],
 "Article 10, paragraphs 2 to 4."),

(GL,"第11條",2,"評估準則-書件格式",
 "說明書、評估書初稿及評估書之本文頁數與用紙規格有何限制？",
 ["說明書本文不得超過一百五十頁，評估書初稿、評估書不得超過三百頁；每頁用紙規格為A4並採雙面印製",
  "說明書本文不得超過三百頁，評估書初稿、評估書不得超過六百頁；每頁用紙規格為B4並採單面印製之",
  "說明書本文不得超過五十頁，評估書初稿、評估書不得超過一百頁；每頁用紙規格為A3並採雙面印製之",
  "說明書本文不得超過一百頁，評估書初稿、評估書不得超過二百頁；每頁用紙規格為A4並採單面印製之"],"a",
 "第11條第1項：書件文字以橫式書寫，除圖表外每頁用紙規格為A4紙張（長二十九點七公分、寬二十一公分），並採雙面印製。第2項：說明書之本文不得超過一百五十頁，評估書初稿、評估書之本文不得超過三百頁；相關資料、文件、數據等得以附錄形式編製，但開發行為因規模龐大、環境影響範圍較廣、環境評估項目眾多且經主管機關同意者不在此限。第4項：提出初稿時應依電腦建檔作業規範檢附電腦檔案，提送定稿本時亦同。",
 "What page and paper limits apply to EIA statements and reports?",
 ["Statements no more than 150 pages and draft reports and reports no more than 300 pages; A4 paper printed double-sided","Statements no more than 300 pages and draft reports and reports no more than 600 pages; B4 paper printed single-sided","Statements no more than 50 pages and draft reports and reports no more than 100 pages; A3 paper printed double-sided","Statements no more than 100 pages and draft reports and reports no more than 200 pages; A4 paper printed single-sided"],
 "Article 11."),

(GL,"第12條",1,"評估準則-編排原則",
 "說明書、評估書初稿、評估書內容之編排與陳述，應符合何原則？",
 ["內容應有焦點著重結構性與關鍵性環境影響項目；立論應有客觀科學依據；結論應具體清楚條理清晰文字淺顯易懂",
  "內容應力求詳盡並涵蓋所有環境項目；立論得引用開發單位之內部評估；結論應保留彈性以利日後變更調整之需",
  "內容應以圖表為主並儘量減少文字敘述；立論得參採同業慣例及經驗法則；結論應強調開發行為之經濟效益為主",
  "內容應依主管機關指定之範本逐項填寫；立論應以顧問機構之專業判斷為準；結論應載明開發單位之承諾事項清單"],"a",
 "第12條：說明書、評估書初稿、評估書內容之編排與陳述應符合下列原則：內容應有焦點，著重於與開發行為有關之結構性與關鍵性環境影響項目；立論應有依據，其單項或綜合之環境影響分析必須有客觀、科學之依據；結論應具體清楚，條理清晰、文字淺顯易懂、內容具體。",
 "What principles govern the arrangement and presentation of EIA documents?",
 ["Focused content on structural and key impact items; conclusions grounded in objective scientific evidence; specific, clear, well-organised and plain-language conclusions",
  "Exhaustive content covering every environmental item; reasoning may rest on the developer's internal assessment; conclusions kept flexible for later changes and adjustments",
  "Chart-based content with minimal narrative text; reasoning may follow industry custom and rules of thumb; conclusions emphasising economic benefits",
  "Content filled in per the authority's template; reasoning based on the consultancy's professional judgement; conclusions listing the developer's commitments"],
 "Article 12."),

(GL,"第13條",1,"評估準則-量化呈現",
 "開發單位評估開發行為對環境之影響，其影響程度、範圍及對象可量化者應如何處理？",
 ["應於適當比例尺之圖件上標明其分布、數量或以數據量化敘述","應以文字概略描述即可，無須標示於圖件亦無須量化敘述","應僅於評估書中列表說明，說明書階段免予量化及圖示之","應由審查委員會於審查時另行要求補充，開發單位免主動"],"a",
 "第13條：開發單位評估開發行為對環境之影響，其影響程度、範圍及對象可量化者，應於適當比例尺之圖件上標明其分布、數量或以數據量化敘述。此與第12條立論應有客觀科學依據之原則相呼應，使影響評估結果具可檢驗性。",
 "How must quantifiable impacts be presented?",
 ["Marked on maps of appropriate scale showing distribution and quantity, or described quantitatively with data","Described in general narrative form only, with no marking on maps and no quantitative description of data","Tabulated only in the report, with quantification and mapping omitted at the statement stage","Supplemented only when the review committee later requests it, not on the developer's initiative"],
 "Article 13."),

(GL,"第14條",2,"評估準則-預測模式",
 "開發單位預測開發行為對環境之影響所引用之各項環境因子預測推估模式，應敘明何事項？",
 ["應敘明引用模式之適用條件、設定或假設之重要參數以及應用於開發行為之精確性與適當性",
  "應敘明模式開發者之姓名學歷、軟體之授權費用以及模式在國外被引用之總次數統計",
  "應敘明模式之程式原始碼、電腦硬體規格以及執行運算所耗費之時間與電力消耗情形",
  "應敘明模式之市場售價、購買日期及廠商保固期限，並檢附發票影本供主管機關查核"],"a",
 "第14條：開發單位預測開發行為對環境之影響所引用之各項環境因子預測推估模式，應敘明引用模式之適用條件、設定或假設之重要參數以及應用於開發行為之精確性與適當性。第58條並規定中央主管機關得訂定評估技術規範，涉及開發行為特性應提出相關預測、分析及評估模式者，依該技術規範辦理。",
 "What must be stated about prediction models used for environmental factors?",
 ["The model's applicable conditions, the key parameters set or assumed, and its accuracy and suitability as applied to the development",
  "The model developer's name and education, the software licence fee, and the total number of overseas citations of the model",
  "The model's source code, the computer hardware specification, and the computing time and electricity consumed to run it",
  "The model's market price, purchase date and vendor warranty period, with a copy of the invoice for the authority to check"],
 "Article 14."),

(GL,"第15條",3,"評估準則-公開會議",
 "開發單位作成說明書前應舉行公開會議，其會議通知及會議紀錄之期限規定為何？",
 ["應於會議十日前將會議時間地點及說明書主要內容刊登於指定網站；並於公開會議後四十五日內作成會議紀錄，公布於指定網站至少三十日",
  "應於會議三十日前將會議時間地點及說明書主要內容刊登於指定網站；並於公開會議後十日內作成會議紀錄，公布於指定網站至少七日以上",
  "應於會議五日前以電話通知當地村里長即可；並於公開會議後九十日內作成會議紀錄，送請目的事業主管機關存查而免予公布之",
  "應於會議二十日前刊登於全國性報紙頭版；並於公開會議後六個月內作成會議紀錄，公布於開發單位網站至少一年以上供查閱"],"a",
 "第15條第1項第1款：應將說明書中有關本法第6條第2項第4款至第8款規定之主要內容刊登於指定網站，供民眾、團體及機關於刊登日起二十日內表達意見。第2款：舉行公開會議並於會議十日前將會議時間、地點及說明書主要內容刊登於指定網站，並以書面告知目的事業主管機關及基地所在地之政府、議會、公所、代表會、村里辦公處。第2項：應於公開會議後四十五日內作成會議紀錄，公布於指定網站至少三十日。第4項：符合施行細則第19條附表二或自願進行第二階段環評者免辦理。",
 "What notice and minutes deadlines apply to the public meeting before an EIA statement?",
 ["Post the meeting time, place and main contents on the designated website 10 days before; produce minutes within 45 days and post them for at least 30 days",
  "Post the meeting time, place and main contents on the designated website 30 days before; produce minutes within 10 days and post them for at least 7 days",
  "Telephone the local village chief 5 days before; produce minutes within 90 days and file them with the industry authority without publication",
  "Advertise on the front page of a national newspaper 20 days before; produce minutes within six months and post them on the developer's website for a year"],
 "Article 15."),

(GL,"第16條",2,"評估準則-用水計畫",
 "開發單位施工及營運之用水，依水資源相關法規須檢附用水計畫書者，應如何辦理？抽取地下水者另應如何？",
 ["應先向水資源主管機關提出用水計畫書之申請；抽取地下水者應調查基地內地下水水位、水質，並提出有效防止地下水污染及地盤下陷措施",
  "應於環評審查通過後再向水資源主管機關報備即可；抽取地下水者僅需檢附水權狀影本，免調查水位水質亦免提出防止下陷措施",
  "應向當地自來水事業單位申請供水同意書；抽取地下水者應繳納地下水資源使用費，並由水資源主管機關代為辦理水質監測作業",
  "應由目的事業主管機關逕行核定其用水量；抽取地下水者應於施工完成後補行調查水位水質，並於營運三年後提出地盤監測報告"],"a",
 "第16條第1項：開發單位施工及營運之用水，依水資源相關法規須檢附用水計畫書者，應先向水資源主管機關提出用水計畫書之申請。第2項：基地位於地下水管制區者，如需抽取地下水，應依水利法及地下水管制辦法等相關規定辦理。第3項：抽取地下水者，應調查開發行為基地內地下水水位、水質，並提出有效防止地下水污染及地盤（層）下陷措施。",
 "How must water use plans and groundwater abstraction be handled?",
 ["Apply to the water resources authority for the water use plan first; those abstracting groundwater must survey on-site water levels and quality and propose measures against contamination and subsidence",
  "Merely report to the water resources authority after EIA approval; those abstracting groundwater need only attach a water rights certificate, with no survey of levels or quality and no subsidence measures",
  "Apply to the local water utility for a supply consent letter; those abstracting groundwater pay a resource fee and the authority carries out the monitoring on their behalf",
  "Let the industry authority set the water volume directly; those abstracting groundwater survey levels and quality after construction and report on subsidence after three years"],
 "Article 16."),

(GL,"第17條",2,"評估準則-廢水",
 "開發行為產生之廢（污）水排放，本準則有何規定？",
 ["廢（污）水應妥善處理始得排放；經前處理排放至既有污水下水道系統者應附該主管機構之同意文件；排放至河川海洋等水體者應評估對水質、水域生態之影響",
  "廢（污）水得先行排放再補行處理；排放至既有污水下水道系統者僅需通知管理單位即可；排放至河川海洋等水體者免評估對水質及水域生態之影響",
  "廢（污）水應全部回收不得排放；排放至既有污水下水道系統者應繳納三倍納管費用；排放至河川海洋者應取得下游全體用水人之書面同意文件",
  "廢（污）水處理由主管機關代為規劃；排放至既有污水下水道系統者由下水道機構負責；排放至河川海洋者僅需於營運後每年檢測水質一次即可"],"a",
 "第17條第1項：開發行為對施工及營運期間所產生之點源及非點源污染應予預防、管理並納入環境保護對策；廢（污）水應妥善處理始得排放；其經前處理排放至既有之污水下水道系統者，應附該有關主管機構之同意文件；自行規劃設置廢（污）水處理設施者應併案進行評估、分析及影響預測。第2項：排放至河川、海洋、湖泊、水庫或灌溉、灌排系統者，應評估對該水體水質、水域生態之影響。第3項：承受水體自放流口以下至出海口前有自來水取水口者，應進行分析及評估。",
 "What rules apply to wastewater discharge from a development?",
 ["Wastewater must be properly treated before discharge; pre-treated discharge to an existing sewer needs that authority's consent document; discharge to rivers or seas requires assessment of water quality and aquatic ecology impacts",
  "Wastewater may be discharged first and treated afterwards; discharge to an existing sewer requires only notice to the sewerage operator; discharge to rivers or seas needs no assessment of water quality or aquatic ecology at all",
  "All wastewater must be recycled with no discharge; discharge to an existing sewer incurs triple connection fees; discharge to rivers or seas needs written consent from all downstream users",
  "The competent authority plans the treatment; discharge to an existing sewer is the sewerage operator's responsibility; discharge to rivers or seas requires only annual testing after operation"],
 "Article 17."),

(GL,"第18條",1,"評估準則-土壤地下水",
 "開發單位就廢棄物儲存清除處理設施或儲槽等設施，應評估其對何者之影響？",
 ["土壤及地下水體之影響","空氣品質及噪音之影響","交通流量及停車之影響","景觀美質及日照之影響"],"a",
 "第18條：開發單位應就廢棄物儲存清除處理設施或儲槽等設施，評估其對土壤及地下水體之影響。此與第25條就邊坡穩定、地基沈陷、地質災變、土壤污染及土壤液化等潛在可能性之預測評估，同屬土壤與地下水面向之環境保護對策。",
 "What impacts must be assessed for waste storage, clearance, treatment facilities and tanks?",
 ["Impacts on soil and groundwater bodies","Impacts on air quality and noise levels","Impacts on traffic flow and parking","Impacts on landscape quality and sunlight"],
 "Article 18."),

(GL,"第19條",3,"評估準則-廢棄物",
 "開發單位就施工及營運期間產生之廢棄物及整地土方，應如何評估？",
 ["應規劃設置廢棄物貯存清除及處理系統；委託代為清除處理者須調查合格機構家數並說明許可清除處理數量；並在整地土方地形圖上標示挖填方位置深度及推估數量",
  "應由主管機關統一規劃廢棄物處理系統；委託代為清除處理者僅需檢附契約書即可；整地土方免於地形圖標示，僅需於施工完成後申報實際數量即可",
  "應優先採用焚化方式處理所有廢棄物；委託代為清除處理者須支付三倍處理費用；整地土方應全數運離基地並不得於基地內進行任何挖填方作業",
  "應將廢棄物暫存於基地內至營運後再處理；委託代為清除處理者由目的事業主管機關指定廠商；整地土方之挖填方數量由施工廠商自行決定即可"],"a",
 "第19條第1項：開發單位應規劃設置廢棄物貯存、清除及處理系統，處理施工及營運期間所產生之各種廢棄物並評估其可能之負面影響；如委託執行機關或公民營廢棄物清除處理機構代為清除處理者，須調查合格機構之家數並說明其許可清除處理之數量。第2項：自行設置焚化廠、掩埋場或其他處理設施者，其對環境之影響應併入開發行為同時評估。第3項：應評估整地作業及取土與棄土運輸之負面影響，在整地土方之地形圖上標示挖填方位置、深度及推估數量，施工項目符合再生粒料用途者應評估優先使用再生粒料。",
 "How must waste and earthworks be assessed?",
 ["Plan waste storage, clearance and treatment systems; if outsourcing, survey the number of licensed operators and their permitted volumes; and mark cut and fill locations, depths and estimated volumes on the earthworks topographic map",
  "Let the competent authority plan the waste storage and treatment system centrally; if outsourcing, attach only the signed contract; earthworks need no marking on the topographic map, only a post-construction volume report to the authority",
  "Incinerate all waste as the first option; if outsourcing, pay triple treatment fees; all earthworks material must leave the site with no cut or fill permitted on site",
  "Store waste on site until after operations begin; if outsourcing, the industry authority designates the contractor; the contractor decides cut and fill volumes itself"],
 "Article 19."),

(GL,"第20條",2,"評估準則-空氣污染",
 "開發單位就施工及營運期間之空氣污染物，應如何評估？",
 ["應事前估計不同排放源可能產生之排放量，以適當精確方法計算擴散稀釋距離、濃度，並研判影響程度範圍時間及是否符合空氣品質標準",
  "應於營運後每季實地監測一次並將結果報請備查，無須事前估計排放量，亦無須計算擴散稀釋距離濃度或研判是否符合標準",
  "應委由主管機關代為推估排放量並公告結果，開發單位僅需負擔監測費用，且免研判其影響程度範圍時間及符合標準與否",
  "應以同業平均排放係數直接推估總量即可，免計算擴散稀釋距離及濃度，僅於超過標準時始須納入環境保護對策辦理改善"],"a",
 "第20條：開發單位應事前估計開發行為在施工及營運期間，不同排放源可能產生之空氣污染物排放量，以適當精確方法計算擴散稀釋距離、濃度；或由相關資料推估空氣污染物之稀釋擴散濃度，並研判其影響之程度、範圍、時間以及是否符合空氣品質標準，並納入環境保護對策。第22條並要求評估交通運輸所產生空氣污染及噪音振動之影響。",
 "How must air pollution during construction and operation be assessed?",
 ["Estimate emissions from each source in advance, compute dispersion distances and concentrations by suitably accurate methods, and judge the degree, extent, timing and compliance with air quality standards",
  "Monitor quarterly after operations begin and report the results for the record, with no advance estimate of emissions, no dispersion or concentration calculations and no judgement on compliance with standards",
  "Have the competent authority estimate and publish the emissions, with the developer only paying monitoring costs and making no judgement on extent or compliance",
  "Estimate totals directly from industry average emission factors, omitting dispersion distances and concentrations, and act only if standards are exceeded"],
 "Article 20."),
(GL,"第21條",1,"評估準則-噪音振動",
 "開發單位就施工中及營運時之噪音或振動，應如何評估？",
 ["應由相關資料及量測現場背景噪音或振動數據，計算推估是否符合現行管制法規各項標準，並分析其強度對周圍環境之影響",
  "應於營運滿一年後始進行現場噪音振動量測，並將結果送請當地主管機關備查，無須事前推估亦不必分析對周圍環境影響",
  "應直接引用同類型開發行為之既有監測報告數值，免量測現場背景數據，亦免計算推估是否符合現行管制法規各項標準",
  "應委由當地環保局代為量測背景噪音及振動，開發單位僅負擔費用，並由環保局判定是否符合標準及決定應採行之對策"],"a",
 "第21條：開發單位應由相關資料及量測現場背景噪音或振動數據，計算推估施工中及營運時是否符合現行管制法規中各項標準；同時分析噪音或振動強度對周圍環境之影響，納入環境保護對策。第22條並要求評估施工及營運期間交通運輸所產生空氣污染及噪音振動之影響。",
 "How must construction and operational noise or vibration be assessed?",
 ["Use relevant data and on-site background noise or vibration measurements to project compliance with current standards and analyse the effect of the intensity on the surroundings",
  "Measure noise and vibration only one year after operations begin and file the results with the local authority, with no advance projection and no analysis of surrounding effects",
  "Simply cite existing monitoring reports from similar developments, without measuring on-site background data or projecting compliance with current control standards",
  "Have the local environmental bureau take the background measurements at the developer's cost, and let the bureau decide compliance and the measures to be adopted"],
 "Articles 21 and 22."),

(GL,"第22條",1,"評估準則-交通運輸",
 "開發單位就開發行為於施工及營運期間交通運輸所產生之影響，應評估何項目？",
 ["交通運輸所產生之空氣污染及噪音振動之影響，並納入環境保護對策","交通運輸所產生之票價收入及運量成長，並納入營運計畫書內容","交通運輸所使用之車輛廠牌及購置成本，並納入財務分析報告中","交通運輸所僱用之駕駛人數及薪資結構，並納入社會經濟評估內"],"a",
 "第22條：開發單位應評估開發行為在施工及營運期間交通運輸所產生空氣污染及噪音振動之影響，並納入環境保護對策。此與第20條之空氣污染評估、第21條之噪音振動評估相互配合，涵蓋固定源以外之移動源影響。",
 "What must be assessed regarding transport during construction and operation?",
 ["Air pollution and noise and vibration impacts from transport, incorporated into environmental protection measures","Fare revenue and passenger traffic growth from transport, incorporated into the business operation plan","Vehicle brands and purchase costs for transport, incorporated into the financial analysis report","Driver headcount and pay structure for transport, incorporated into the socio-economic assessment"],
 "Article 22."),

(GL,"第23條",1,"評估準則-景觀綠覆",
 "開發單位就施工及營運期間對周遭環境美質與景觀之負面影響，應如何處理？",
 ["應予推估並納入環境保護對策及訂定綠覆計畫","應予推估但免納入環境保護對策及綠覆計畫中","應由目的事業主管機關代為推估並訂定綠覆計畫","應於營運後視民眾陳情情形再行推估及補行規劃"],"a",
 "第23條：開發單位應推估施工及營運期間對周遭環境美質與景觀之負面影響，納入環境保護對策及訂定綠覆計畫。第24條並規定可能造成噪音、振動、空氣污染、異味、化學災害、電磁波或游離輻射影響者，應於周界內規劃足敷需要之緩衝地帶並訂定密集植樹計畫。",
 "How must negative impacts on landscape and visual amenity be handled?",
 ["Estimated and incorporated into environmental protection measures and a green coverage plan","Estimated but excluded from environmental protection measures and any green coverage plan","Estimated by the industry authority on the developer's behalf, which sets the green plan","Estimated only after operations begin, depending on whether the public complains"],
 "Articles 23 and 24."),

(GL,"第24條",2,"評估準則-緩衝地帶",
 "開發行為可能造成噪音、振動、空氣污染、異味、化學災害、電磁波或游離輻射影響者，應如何規劃？",
 ["應依當地氣象條件、污染質量、控制措施效率、災害風險與人口聚集社區村落之距離等因素，於周界內規劃足敷需要之緩衝地帶並訂定密集植樹計畫",
  "應依開發單位之財務能力及土地取得成本等因素，於周界外購置適當土地作為緩衝地帶，並由當地政府負責辦理綠化及後續維護管理事宜",
  "應依當地居民陳情之件數及媒體報導之次數等因素，決定是否設置緩衝地帶，如無人陳情者得免設置緩衝地帶亦免訂定任何植樹計畫",
  "應依主管機關指定之固定寬度設置緩衝地帶，其寬度一律不得少於五十公尺，且緩衝地帶內不得種植任何喬木以免影響污染物擴散"],"a",
 "第24條：開發行為可能造成噪音、振動、空氣污染、異味、化學災害、電磁波或游離輻射影響者，應依當地氣象條件、污染之質量、污染控制措施之效率、災害風險與人口聚集社區、村落之距離及其他相關因素，於周界內規劃足敷需要之緩衝地帶並訂定密集植樹計畫，以減輕影響及維持景觀。第52條並就火力發電或汽電共生工程之緩衝地帶另有規定。",
 "How must buffer zones be planned for developments causing noise, pollution or radiation effects?",
 ["Plan an adequate buffer zone within the boundary and a dense tree planting plan, based on local weather, pollutant quality and quantity, control efficiency, disaster risk and distance to settlements",
  "Buy suitable land outside the boundary as a buffer zone based on the developer's own finances and land acquisition costs, with the local government handling the greening and later maintenance",
  "Decide whether a buffer is needed from the number of public complaints and media reports; where nobody complains, no buffer zone or tree planting plan is needed at all",
  "Provide a buffer of the fixed width designated by the authority, never less than 50 m wide, in which no trees may be planted so as not to impede pollutant dispersion"],
 "Article 24."),

(GL,"第25條",2,"評估準則-地質災害",
 "開發單位應對開發行為基地及毗鄰之受影響地區，預測評估何種潛在可能性？",
 ["邊坡穩定、地基沈陷、地質災變、土壤污染及土壤液化等潛在可能性","地價漲跌、租金水準、稅收增減及人口遷入等潛在經濟社會變化","建照核發、使照取得、工期延誤及預算追加等潛在行政作業風險","市場需求、產品價格、匯率變動及原料供應等潛在營運財務風險"],"a",
 "第25條：開發單位應對開發行為基地及毗鄰之受影響地區預測評估邊坡穩定、地基沈陷、地質災變、土壤污染及土壤液化等潛在可能性，並納入環境保護對策。第31條並就基礎開挖、抽沙、填土、高填方或地下深開挖可能造成之地面沈陷或地下水位變化予以預測研判。",
 "What potential risks must be assessed for the site and adjoining affected areas?",
 ["Slope stability, foundation settlement, geological hazards, soil contamination and soil liquefaction","Land price movements, rent levels, tax changes and population inflow as socio-economic shifts","Building permit issuance, occupancy permits, schedule delays and budget overruns as risks","Market demand, product prices, exchange rates and raw material supply as financial risks"],
 "Articles 25 and 31."),

(GL,"第26條",2,"評估準則-基地規劃原則",
 "開發行為基地之規劃，應以何種原則進行？",
 ["避免使用地質敏感或坡度過陡土地；林相良好者儘量保存並有相當比率森林綠覆面積；動植物生態豐富者予以保護；考量生態工程並與下游影響區間設緩衝帶",
  "優先使用地質敏感或坡度較陡土地以節省平地資源；林相良好者應全部砍伐後重新造林；動植物生態豐富者應遷移至他處復育；並免設置任何緩衝帶",
  "由開發單位依成本效益自行決定土地使用方式；林相與生態狀況得於施工後再行調查；緩衝帶之設置由當地政府編列預算辦理而非開發單位責任",
  "應依主管機關指定之固定比例保留綠地面積；林相良好者得以繳納代金方式免予保存；動植物生態豐富者應設置圍籬隔離並禁止任何人員進出"],"a",
 "第26條：開發行為基地應以下列原則進行規劃並得以圖面量化呈現保留之比例與區域：應避免使用地質敏感或坡度過陡之土地；基地林相良好者應予儘量保存並有相當比率之森林綠覆面積；基地動植物生態豐富者應予保護；應考量生態工程並維持視覺景觀之和諧；開發行為基地與下游影響區之間應有適當之緩衝帶，或具緩衝效果之遮蔽或阻隔等替代性措施。",
 "What principles govern site planning?",
 ["Avoid geologically sensitive or steep land; preserve good forest stands with a fair proportion of green cover; protect rich flora and fauna; use eco-engineering and a buffer to downstream areas",
  "Use geologically sensitive or steep land first to save flat land; clear-cut good forest stands and replant; relocate rich flora and fauna elsewhere; and provide no buffer zones at all",
  "Let the developer decide land use on cost-benefit grounds; survey forest and ecology after construction; leave buffer zones to be budgeted and built by the local government instead",
  "Retain the fixed proportion of green space designated by the authority; pay a fee in lieu of preserving good forest; fence off rich habitats and bar all human access to them"],
 "Article 26."),

(GL,"第27條",2,"評估準則-海岸地區",
 "開發行為基地位於海岸地區者，其規劃應符合何原則？",
 ["避免影響重要生態棲地或生態系統之正常機能；避免嚴重破壞水產資源；避免海岸侵蝕淤積地層下陷陸域排洪影響；避免破壞海洋景觀遊憩資源及水下文化資產；維持親水空間",
  "得適度影響生態棲地但應提出補償金；得利用水產資源作為觀光賣點；海岸侵蝕淤積由水利機關負責處理；海洋景觀之維護由觀光機關負責；親水空間得改為私人專用",
  "應優先考量土地開發之最大效益；水產資源之影響於營運後再行調查；地層下陷問題由當地居民自行監測；水下文化資產之調查得以文獻回顧替代實地探查作業",
  "應依海岸管理法規定辦理而免適用本準則；生態棲地與水產資源之保護由漁業機關負責；開發單位僅需繳納海岸開發利用費用即可免除各項環境保護對策之訂定"],"a",
 "第27條：開發行為基地位於海岸地區，其規劃應符合下列原則，並得以圖面量化呈現保留之比例與區域：避免影響重要生態棲地或生態系統之正常機能；避免嚴重破壞水產資源；避免海岸侵蝕、淤積、地層下陷、陸域排洪影響等；避免破壞海洋景觀、遊憩資源及水下文化資產；維持親水空間。第43條並就港灣、港埠工程或填海造地之開發另有評估要求。",
 "What principles apply to sites in coastal areas?",
 ["Avoid affecting key habitats or ecosystem function; avoid serious damage to fishery resources; avoid coastal erosion, siltation, subsidence and drainage effects; protect seascape, recreation and underwater cultural assets; keep waterfront access",
  "Habitats may be affected with compensation payments; fishery resources may be marketed as tourism attractions; erosion and siltation are the water authority's problem; waterfront space may become private",
  "Maximum land development benefit takes priority; fishery resource impacts are surveyed only after operations begin; subsidence is monitored by local residents themselves; underwater cultural asset surveys may be replaced by a literature review",
  "The Coastal Act applies instead of these Guidelines; habitat and fishery protection rests with the fisheries authority; paying a coastal development fee exempts the developer from all protection measures"],
 "Article 27."),

(GL,"第28條",2,"評估準則-節能回收",
 "開發單位應評估設置何種節約能源及水資源再利用設施之可能性？",
 ["節約能源措施、雨水截流儲存利用設施、污水處理水回收為中水道沖洗廁所及澆灌利用或其他中水道系統；並評估大量廢棄物廢氣廢熱或廢水之回收再使用可能性",
  "節約人力措施、地下水抽取設施、自來水直接供應沖洗廁所及澆灌利用或其他管線系統；並評估大量廢棄物廢氣廢熱或廢水之直接排放可行性及成本效益",
  "節約成本措施、海水淡化處理設施、工業用水回收為飲用水及食品加工利用；並評估大量廢棄物委外處理之單價及廠商家數是否足敷開發行為所需使用",
  "節約土地措施、溫泉抽取利用設施、雨水直接排入下水道系統；並評估大量廢棄物廢氣廢熱或廢水於基地內長期貯存之空間需求及其可能造成之二次污染"],"a",
 "第28條：開發單位應評估設置節約能源措施、雨水截流儲存利用設施、污水處理水回收為中水道沖洗廁所及澆灌利用或其他中水道系統等之可能性。對於施工及營運期間所產生之大量廢棄物、廢氣、廢熱或廢（污）水，應評估其回收及再使用之可能性。第50條並就新市區建設、舊市區更新要求評估汽電共生、區域供冷供熱、雨水貯留及生活雜排水回收等節能省水措施之可行性。",
 "Which energy-saving and water reuse facilities must be assessed?",
 ["Energy conservation measures, rainwater interception and storage, reclaimed sewage for toilet flushing and irrigation or other greywater systems; plus recovery and reuse of bulk waste, gases, heat and wastewater",
  "Labour-saving measures, groundwater abstraction, tap water supplied directly for toilet flushing and irrigation or other pipe systems; plus the feasibility and cost of directly discharging bulk waste and wastewater",
  "Cost-saving measures, seawater desalination, industrial water reclaimed for drinking and food processing; plus the unit price and number of contractors available for outsourced bulk waste disposal",
  "Land-saving measures, hot spring abstraction, rainwater discharged straight to sewers; plus the space needed for long-term on-site storage of bulk waste and the secondary pollution it may cause"],
 "Articles 28 and 50."),

(GL,"第30條",2,"評估準則-地下工程",
 "開發行為屬地下管線、箱涵、隧道或採地下化方式開發者，開發單位應調查或蒐集何資料？",
 ["地下埋藏之史蹟或考古遺址等文化資產、鄰近建築物以及行經地區河道堤防溝圳排水系統地下管路地下坑道之分布與過去挖填紀錄，並說明現存結構體安全穩定程度",
  "地下埋藏之礦產與地熱資源蘊藏量、鄰近建築物之市場行情以及行經地區之商業活動人潮流量，並說明開發完成後可帶動之周邊土地增值幅度及稅收成長",
  "地下水位與土壤含水率之季節變化、鄰近建築物之屋齡與屋主意願以及行經地區之交通號誌配置，並說明施工期間交通疏導方案及替代道路之設置規劃內容",
  "地下埋藏之廢棄物與污染物種類數量、鄰近建築物之保險投保情形以及行經地區之公共設施使用費率，並說明工程完工後之管線維護權責歸屬及費用分攤方式"],"a",
 "第30條：開發行為屬地下管線、箱涵、隧道或採地下化方式開發者，開發單位應調查或蒐集地下埋藏之史蹟或考古遺址等文化資產，鄰近建築物以及行經地區之河道、堤防、溝圳、排水系統、地下管路、地下坑道等之分布與過去挖填紀錄及資料，說明現存結構體之安全穩定程度，評估開發行為對各該現有結構體可能產生之負面影響，並納入環境保護對策。",
 "What must be surveyed for underground pipelines, culverts, tunnels or underground developments?",
 ["Buried historic sites and archaeological remains, nearby buildings, and the distribution and past excavation records of channels, embankments, ditches, drains, underground pipes and shafts, with the stability of existing structures explained",
  "Buried mineral and geothermal reserves, market prices of nearby buildings, and commercial footfall along the route, with the land appreciation and tax growth the project will generate explained",
  "Seasonal changes in groundwater level and soil moisture content, the age of nearby buildings and their owners' wishes, and traffic signal layouts along the route, with construction-period traffic diversion and alternative route plans explained",
  "Types and volumes of buried waste and contaminants, insurance coverage of nearby buildings, and public facility fee rates, with pipeline maintenance responsibility and cost sharing explained"],
 "Article 30."),

(GL,"第31條",2,"評估準則-地面沈陷",
 "開發單位對於基礎開挖與處理、抽沙、填土、高填方或地下深開挖及營運期間之何種現象，應予預測研判？",
 ["可能造成之各種地面沈陷或地下水位變化等現象，並納入環境保護對策","可能造成之各種房價變動或土地徵收爭議等現象，並納入社會經濟分析","可能造成之各種工期延誤或成本增加等現象，並納入財務可行性之評估","可能造成之各種勞工職災或工安事故等現象，並納入勞動安全衛生計畫"],"a",
 "第31條：開發單位對於開發行為因基礎開挖與處理、抽沙、填土、高填方或地下深開挖包含隧道、涵管以及營運期間可能造成之各種地面沈陷或地下水位變化等現象，應予預測研判其可能影響，並納入環境保護對策。第32條並要求預測評估改變地形地貌對下游及鄰近地區排水系統之影響。",
 "What phenomena must be predicted for excavation, sand extraction, filling and deep underground works?",
 ["Ground subsidence and groundwater level changes, to be incorporated into environmental protection measures","House price movements and land expropriation disputes, to be incorporated into socio-economic analysis","Schedule delays and cost increases, to be incorporated into the financial feasibility assessment","Occupational injuries and safety incidents, to be incorporated into the labour safety and health plan"],
 "Articles 31 and 32."),

(GL,"第32條",1,"評估準則-排水影響",
 "開發單位應預測評估開發行為改變地形地貌，對何者之影響？",
 ["對下游及鄰近地區排水系統之影響，並納入環境保護對策","對上游及遠隔地區供水系統之影響，並納入用水計畫書中","對周邊地區電力系統之影響，並納入能源使用效率報告中","對鄰近地區通訊系統之影響，並納入電磁波影響評估報告"],"a",
 "第32條：開發單位應預測評估開發行為改變地形地貌對下游及鄰近地區排水系統之影響，並納入環境保護對策。此與第31條之地面沈陷及地下水位變化預測、第25條之邊坡穩定與地基沈陷評估，同屬地形地質與水文面向之要求。",
 "What must be assessed regarding changes to topography and landform?",
 ["Impacts on drainage systems downstream and in nearby areas, incorporated into protection measures","Impacts on water supply systems upstream and in distant areas, incorporated into the water use plan","Impacts on power systems in surrounding areas, incorporated into the energy efficiency report","Impacts on communication systems nearby, incorporated into the electromagnetic impact report"],
 "Article 32."),

(GL,"第33條",1,"評估準則-溫排水廢熱",
 "開發行為在施工及營運期間產生溫排水、廢熱或熱島效應者，應如何處理？",
 ["均應事前研究分析其負面影響範圍及程度，並妥善規劃可行之環境保護對策",
  "均得於營運滿三年後再行研究分析，並視實際情形決定是否規劃環境保護對策",
  "均應委由目的事業主管機關研究分析，開發單位僅需配合提供製程資料即可",
  "均免予研究分析，僅需於說明書中敘明產生溫排水廢熱之設備名稱及數量即可"],"a",
 "第33條：開發行為在施工及營運期間產生溫排水、廢熱或熱島效應者，均應事前研究分析其負面影響範圍及程度，並妥善規劃可行之環境保護對策。第52條並就火力發電或汽電共生工程以海水作為冷卻用水及其溫水排放，要求就海域環境調查結果評估對生態與漁業之影響。",
 "How must thermal discharge, waste heat or heat island effects be handled?",
 ["The extent and degree of negative impacts must be studied and analysed in advance, with feasible protection measures properly planned",
  "They may be studied three years after operations begin, with protection measures planned only if the situation appears to warrant it",
  "The industry authority must carry out the study and analysis, with the developer merely supplying its process data on request",
  "No study or analysis is needed; the statement need only name the equipment producing thermal discharge and waste heat and its quantity"],
 "Articles 33 and 52."),

(GL,"第34條",2,"評估準則-意外災害",
 "開發單位應評估開發行為在施工及營運期間發生何種意外災害之風險，並訂定何計畫？",
 ["火災、風災、水災、地震、爆炸、化學災害、油污染等意外災害之風險及對周圍環境可能產生之影響與範圍；並配合周圍道路防災排水系統訂定緊急應變計畫",
  "股價下跌、匯率波動、原料短缺、勞資爭議、罷工停工等營運風險及對公司財務可能產生之衝擊與範圍；並配合金融機構授信條件訂定財務調度應變計畫",
  "工期延誤、預算追加、承包商倒閉、材料漲價等施工風險及對開發時程可能產生之影響與範圍；並配合工程契約條款訂定履約爭議處理及仲裁調解計畫",
  "民眾抗爭、媒體負面報導、民意代表關切、環保團體訴訟等社會風險及對開發許可可能產生之影響；並配合公關公司建議訂定溝通說明及形象維護計畫"],"a",
 "第34條：開發單位應評估開發行為在施工及營運期間發生火災、風災、水災、地震、爆炸、化學災害、油污染等意外災害之風險，以及對周圍環境可能產生之影響與範圍；配合周圍之道路系統、防災系統、排水系統與當地其他條件，訂定緊急應變計畫納入環境保護對策。第38條並就可能運作或衍生危害性化學物質者要求進行健康風險評估。",
 "What accident risks must be assessed and what plan prepared?",
 ["Risks of fire, wind, flood, earthquake, explosion, chemical disaster and oil pollution and their extent; with an emergency response plan matched to surrounding roads, disaster and drainage systems",
  "Risks of share price falls, exchange rate swings, material shortages, labour disputes and strikes and their financial extent; with a treasury contingency plan matched to bank credit terms",
  "Risks of schedule delay, budget overrun, contractor insolvency and material price rises and their extent; with a dispute resolution and arbitration plan matched to the works contract terms",
  "Risks of public protest, negative media coverage, councillor interest and NGO litigation and their permit consequences; with a communication and image plan drafted on PR advice"],
 "Articles 34 and 38."),

(GL,"第35條",3,"評估準則-生態調查",
 "開發單位應依基地特性說明動植物生態，何種情形得免進行調查及預測評估？",
 ["開發行為位於已開發地區，或其基地經勘查認為植物生態貧乏或無野生物棲息環境者，以圖、相片等資料於書件中說明後，得免進行調查及預測評估",
  "開發行為位於非都市土地，或其基地面積未達一公頃且非位於環境敏感地區者，以開發單位切結書於書件中說明後，得免進行調查及預測評估作業",
  "開發行為屬政府重大建設，或其基地曾於十年內辦理過生態調查者，以原調查報告影本於書件中說明後，得免重複進行調查及預測評估之作業",
  "開發行為經目的事業主管機關認定具急迫性，或其基地位於工業區範圍內者，以主管機關同意函於書件中說明後，得免進行調查及預測評估作業"],"a",
 "第35條第1項：開發單位應依基地特性說明基地及毗鄰受影響地區植物之種類群落與分布、動物之種類相對數量及棲息狀況，分析將來因開發對生物數量及棲息地之影響，並提出可行之保護或復育計畫。第2項：在水域中施工者應說明水體之水生物、底質與水質現況。第3項：開發行為位於已開發地區或其基地經勘查認為植物生態貧乏或無野生物棲息環境者，以圖、相片等資料於書件中說明，得免進行第1項及第2項之調查及預測評估。",
 "When may ecological survey and impact prediction be omitted?",
 ["Where the development is in an already developed area, or the site is found on inspection to have poor plant ecology or no wildlife habitat, explained with maps and photographs in the documents",
  "Where the development is on non-urban land, or the site is under one hectare and outside sensitive areas, explained with the developer's own affidavit in the documents",
  "Where the development is a major government construction project, or the site had an ecological survey carried out within the past ten years, explained with a copy of that earlier survey report in the documents",
  "Where the industry authority finds the project urgent, or the site lies within an industrial zone, explained with the authority's letter of consent in the documents"],
 "Article 35."),

(GL,"第36條",2,"評估準則-社會經濟",
 "開發單位應評估開發行為對周遭環境之何種社會經濟項目之影響？基地涉及原住民族土地者應如何辦理？",
 ["文化資產（含水下文化資產）、人口分布、居民生活型態、土地利用型式與限制、社會結構、公共設施負荷、產業經濟結構、教育結構等；涉及原住民族土地或部落及其周邊一定範圍內公有土地者應依原住民族基本法辦理",
  "股東結構、營業額成長、員工薪資水準、原料供應來源與價格、市場占有率、同業競爭情形、產品外銷比重、研發投入等；涉及原住民族土地者僅需取得該土地所有權人之書面同意即可辦理開發而無須踐行諮商同意程序",
  "選舉投票傾向、政黨支持度、地方派系分布、民意代表席次、社團組織數量、宗教信仰比例、節慶活動頻率等；涉及原住民族土地者應由目的事業主管機關代為協商並代表開發單位簽約",
  "房屋交易價格、租金報酬率、土地公告現值、建蔽率與容積率、都市計畫變更進度、公共設施保留地比例等；涉及原住民族土地者得以繳納回饋金方式取代任何諮商同意程序"],"a",
 "第36條第1項：開發單位應評估開發行為在施工與營運期間，對周遭環境之文化資產（含水下文化資產）、人口分布、當地居民生活型態、土地利用型式與限制、社會結構、相關公共設施包括公共給水、電力、電信、瓦斯與排水或污水下水道設施之負荷、產業經濟結構、教育結構等之影響，並對負面影響納入環境保護對策或另覓替代方案。第2項：開發行為基地涉及原住民族土地或部落及其周邊一定範圍內之公有土地者，應依原住民族基本法規定辦理。",
 "Which socio-economic impacts must be assessed, and what applies to indigenous land?",
 ["Cultural assets including underwater ones, population distribution, residents' lifestyles, land use patterns and limits, social structure, public facility loading, industrial structure and education; indigenous land and nearby public land follow the Indigenous Peoples Basic Act",
  "Shareholder structure, revenue growth, staff pay levels, raw material sources and prices, market share, industry competition, export proportion and R&D investment; on indigenous land only the landowner's written consent is needed, with no consultation procedure at all",
  "Voting tendencies, party support, local faction distribution, council seats, civic group numbers, religious composition and festival frequency; on indigenous land the industry authority negotiates and signs for the developer",
  "House transaction prices, rental yields, announced land values, building and floor area ratios, zoning change progress and reserved land ratios; on indigenous land a feedback payment replaces consultation"],
 "Article 36."),

(GL,"第37條",3,"評估準則-範疇界定",
 "開發行為經審查認定須進行第二階段環境影響評估者，開發單位於範疇界定前應如何辦理？",
 ["應依說明書審查結論篩選環境關鍵項目與因子，並填寫範疇界定指引表（附件六），且視需要列出不同可行替代方案之環評範疇，送主管機關依本法第10條召開會議討論確認",
  "應依開發單位內部評估自行決定評估範疇，並填寫自評表送目的事業主管機關備查，無須召開任何會議亦不必列出替代方案之環境影響評估範疇即可逕行製作評估書",
  "應委託技術顧問機構代為決定評估範疇，並將結果公告於指定網站三十日，如無民眾異議即視為範疇確認，主管機關不得再行召開範疇界定會議或要求變更範疇",
  "應由主管機關逕行指定評估範疇並函知開發單位，開發單位僅得就指定範疇提出書面意見一次，且不得列出不同可行替代方案之環境影響評估範疇供會議討論"],"a",
 "第37條第1項：開發行為經審查認定須進行第二階段環境影響評估者，開發單位於範疇界定前，應依說明書審查結論篩選環境關鍵項目與因子，並填寫範疇界定指引表（附件六），且視需要列出不同可行替代方案之環境影響評估範疇，送主管機關依本法第10條召開會議討論確認評估範疇。第2項：開發單位應依本法第11條規定參酌會議所提意見，並於提送之評估書初稿敘明其辦理情形。",
 "Before scoping for a second-stage EIA, what must the developer do?",
 ["Screen key environmental items and factors per the statement review conclusions, complete the scoping guidance table in Annex 6, list alternatives' scopes as needed, and submit for a scoping meeting under Article 10",
  "Decide the assessment scope from its own internal evaluation, file a self-assessment form with the industry authority for record, hold no meeting at all and list no alternative scopes before preparing the draft report",
  "Have a consultancy decide the scope and post it online for 30 days; absent objections the scope is confirmed and the authority may not convene a scoping meeting or change it",
  "Wait for the authority to designate the scope by letter, submit written comments once only, and be barred from listing any alternative assessment scopes for the meeting to discuss"],
 "Article 37."),

(GL,"第38條",2,"評估準則-健康風險",
 "開發行為可能運作或運作時衍生危害性化學物質者，開發單位應如何辦理？",
 ["應依健康風險評估技術規範進行健康風險評估，並將其納入說明書、評估書初稿、評估書",
  "應依勞工作業環境監測實施辦法進行作業環境監測，並將結果送當地勞工主管機關備查",
  "應依毒性化學物質管理法申請運作許可證，並免於說明書或評估書中進行健康風險評估",
  "應由主管機關委託學術機構代為進行健康風險評估，開發單位僅需負擔評估所需之費用"],"a",
 "第38條：開發行為可能運作或運作時衍生危害性化學物質者，開發單位應依健康風險評估技術規範進行健康風險評估，並將其納入說明書、評估書初稿、評估書。第58條第1項並規定中央主管機關得視需要會商有關機關訂定評估技術規範並公告之。",
 "What applies where a development may handle or generate hazardous chemicals?",
 ["Conduct a health risk assessment under the health risk assessment technical guidelines and include it in the statement, draft report and report",
  "Conduct workplace environment monitoring under the workplace monitoring regulations and file the results with the local labour authority",
  "Apply for an operating permit under the Toxic Chemical Substances Act, with no health risk assessment needed in the statement or report",
  "Have the competent authority commission an academic institution to do the assessment, with the developer merely bearing the cost"],
 "Articles 38 and 58."),

(GL,"第39條",2,"評估準則-施工告知",
 "開發單位應於何時以書面告知目的事業主管機關及主管機關其預定施工日期？",
 ["應於開發行為施工前三十日內以書面告知","應於開發行為施工後三十日內以書面告知","應於開發行為施工前六個月內以書面告知","應於開發行為完工後六個月內以書面告知"],"a",
 "第39條第1項：開發單位應於開發行為施工前三十日內，以書面告知目的事業主管機關及主管機關其預定施工日期。第2項：說明書或評估書內容採分段（分期）開發者，以提報各段（期）開發之第一次施工行為預定施工日期為原則。",
 "When must the developer give written notice of the planned construction start date?",
 ["Within 30 days before construction of the development starts","Within 30 days after construction of the development starts","Within six months before construction of the development starts","Within six months after the development has been completed"],
 "Article 39."),

(GL,"第40條",2,"評估準則-免調查評估",
 "開發單位預測開發行為不發生第16條至第36條中任一可能影響事項者，應如何處理？",
 ["對該事項得免進行調查及評估，但應於說明書、評估書初稿、評估書中條列說明理由及根據",
  "對該事項得免進行調查及評估，且無須於說明書或評估書中說明任何理由及其根據資料",
  "對該事項仍應進行調查及評估，並於說明書或評估書中詳列調查數據及分析結果供審查",
  "對該事項得免進行調查及評估，但應報請主管機關核准並公告於指定網站三十日後為之"],"a",
 "第40條：開發單位預測開發行為在規劃、進行及完成後之使用，不發生第16條至第36條中任一可能影響事項者，在說明書、評估書初稿、評估書製作時，對該事項得免進行調查及評估，但應於說明書、評估書初稿、評估書中條列說明理由及根據。此為書件精簡之規定，惟仍須交代免評之理由以利審查。",
 "What applies where none of the impacts in Articles 16 to 36 will occur?",
 ["That item may be omitted from survey and assessment, but the reasons and basis must be listed in the statement, draft report and report",
  "That item may be omitted from survey and assessment, with no need to state any reason or supporting basis in the documents at all",
  "That item must still be surveyed and assessed, with the data and analysis set out in full in the statement or report for review",
  "That item may be omitted from survey and assessment, but only with the authority's approval and a 30-day posting online"],
 "Article 40."),
(GL,"第41條",3,"評估準則-工廠園區",
 "工廠及園區之開發，本準則之評估要求為何？",
 ["工廠應評估各種製程產生污染物之質與量並繪製質量平衡圖表；園區應預測引進產業之種類規模與污染物質量，並訂定園區污染物總量管制方式",
  "工廠僅需列出主要製程名稱及設備清單而免繪製任何圖表；園區僅需說明預定引進產業之家數及預估產值，免訂定園區污染物總量管制之方式",
  "工廠應由目的事業主管機關代為評估污染物質與量；園區之污染物總量管制由地方環保局逕行核定，開發單位僅需配合提供土地使用計畫圖說即可",
  "工廠應評估其產品市場需求與獲利能力並繪製損益圖表；園區應預測引進產業之投資金額與就業人數，並訂定園區廠商進駐之租金收費標準方式"],"a",
 "第41條第1項：工廠之開發應評估各種製程產生各項污染物之質與量，繪製質量平衡圖表，預測各項污染物之增量，評估其影響程度及範圍。第2項：試車及營運期間可能產生有害事業廢棄物或有害空氣污染物者應說明影響範圍程度並提出防制措施及應變計畫。第3項：園區之開發應預測引進產業之種類、規模與各項污染物之質與量，訂定園區污染物總量管制方式。第4項：園區產生之廢（污）水及事業廢棄物以在園區內處理為原則。第6項：園區開發應評估設置汽電共生或區域供冷供熱系統等節能措施之可行性。",
 "What assessment applies to factories and industrial parks?",
 ["Factories must assess the quality and quantity of pollutants from each process and draw mass balance charts; parks must predict the types, scale and pollutant loads of incoming industries and set a park-wide total load control scheme",
  "Factories need only list main process names and an equipment inventory without any charts; parks need only state the number of incoming firms and estimated output value, with no total load control scheme",
  "Factories have pollutant quality and quantity assessed by the industry authority; park total load control is set by the local bureau, with the developer merely supplying land use drawings",
  "Factories must assess product market demand and profitability and draw profit and loss charts; parks must predict incoming investment and job numbers and set the rent tariff for tenants"],
 "Article 41."),

(GL,"第42條",3,"評估準則-道路鐵路捷運",
 "道路、鐵路、大眾捷運系統之開發，位於現有、興建中或已定案之重要水庫集水區者，應如何辦理？",
 ["應以穿越性、封閉型且不得設置機廠（場）、站及交流道為限；但情形特殊經主管機關環評審查委員會審查同意者不在此限",
  "應以停留性、開放型且應設置機廠（場）、站及交流道為原則；但情形特殊經目的事業主管機關同意者得免設置該等設施",
  "應一律禁止開發並不得以任何理由排除適用；縱經主管機關環評審查委員會審查同意亦不得於水庫集水區內進行任何路線開發",
  "應由水庫管理機關逕行核定其路線及設施配置；開發單位僅需依核定內容施工並免進行噪音振動及生態切割影響之評估作業"],"a",
 "第42條第1項：道路、鐵路、大眾捷運系統之開發，如位於現有、興建中或已定案之重要水庫集水區，應以穿越性、封閉型、且不得設置機廠（場）、站及交流道為限；但情形特殊，經主管機關環境影響評估審查委員會審查同意者，不在此限。第2項：應詳細調查分析營運時噪音及振動之影響程度範圍及受體，採路塹或路堤方式者應評估對積水、洩洪、橫交設施、生態棲地切割或動物通過之影響。",
 "What applies to roads, railways or MRT in an important reservoir catchment?",
 ["They must be through-passing and enclosed with no depots, stations or interchanges; unless special circumstances are approved by the EIA review committee",
  "They should be stopping and open in type with depots, stations and interchanges provided; unless the industry authority agrees these may be omitted",
  "They are banned outright with no exception whatsoever; even approval by the EIA review committee cannot permit any route development in the catchment",
  "Their route and facility layout is set directly by the reservoir authority; the developer simply builds to it and skips noise, vibration and habitat assessment"],
 "Article 42."),

(GL,"第43條",2,"評估準則-港灣填海",
 "港灣、港埠工程或填海造地之開發，應說明各該結構物對何者之影響？",
 ["對沿岸流、漂砂、鄰近海域生態、水下文化資產以及未來之海岸地形變遷或對河口之影響，並納入環境保護對策",
  "對船舶噸位、貨櫃裝卸效率、碼頭使用費率以及未來之營運收益成長或對貿易量之影響，並納入財務計畫書中",
  "對港區土地取得成本、填海造地單價、工程發包方式以及未來之土地標售價格或對地價之影響，並納入標售計畫",
  "對周邊道路交通量、聯外鐵路運能、停車空間需求以及未來之觀光人潮成長或對商圈之影響，並納入交通改善計畫"],"a",
 "第43條第1項：港灣、港埠工程或填海造地之開發，應說明各該結構物對沿岸流、漂砂、鄰近海域生態、水下文化資產以及未來之海岸地形變遷、或對河口之影響，並納入環境保護對策。第2項：設有隔離水道者應就相鄰之填海造地與陸域間之各河口、浮游生物與底棲生物、沿岸流、潮汐、海岸地形變遷、沉積物流失、排水、水質交換等問題說明整體負面影響。第3項：在海域抽沙或浚挖航道水域者應詳細調查水域地形及地質探查。",
 "What impacts must be explained for harbour works or land reclamation?",
 ["Impacts on longshore currents, littoral drift, nearby marine ecology, underwater cultural assets and future coastal landform change or on the estuary, incorporated into protection measures",
  "Impacts on vessel tonnage, container handling efficiency, wharf tariffs and future revenue growth or on trade volumes, incorporated into the financial plan for the project",
  "Impacts on port land acquisition costs, reclamation unit prices, tendering methods and future land sale prices or on land values, incorporated into the disposal plan",
  "Impacts on surrounding road traffic, rail capacity, parking demand and future tourist growth or on the shopping district, incorporated into the traffic improvement plan"],
 "Article 43."),

(GL,"第44條",3,"評估準則-機場噪音",
 "機場之開發，應如何評估營運產生噪音之影響？",
 ["應依規劃之最大運量、飛航機種預測航空噪音日夜音量，繪製全年等噪音線圖，標示各級航空噪音防制區範圍及敏感受體分布情況並納入環境保護對策",
  "應依實際發生之投訴案件數量統計噪音影響，於營運滿一年後繪製季節等噪音線圖，標示投訴人住址分布並由航空站負責與陳情人協商補償金額",
  "應依鄰近機場之既有監測資料直接引用推估，免繪製等噪音線圖，僅需標示跑道兩端各一公里範圍為噪音影響區並設置隔音牆即可完成評估",
  "應依民航主管機關公告之標準值判定是否超標，如未超標即免進行任何評估；如超標則由民航主管機關逕行劃定航空噪音防制區並辦理補償事宜"],"a",
 "第44條第1項：機場之開發應評估機場營運產生噪音之影響，應依規劃之最大運量、飛航機種，預測航空噪音日夜音量，繪製全年等噪音線圖，標示各級航空噪音防制區範圍、敏感受體分布情況並納入環境保護對策；在噪音影響範圍內涉及學校、圖書館、醫療安養機構、住宅或其他易受飛航噪音干擾之土地使用，開發單位如採取補償或其他替代方案者，其處理方式及可行性應先行規劃評估。第2項：應評估不透水面積增加對排水系統及地下水之影響。第3項：跑道地區鳥類或野生動物干擾飛航安全者應調查評估。",
 "How must airport operational noise be assessed?",
 ["Predict day-night noise levels from planned maximum traffic and aircraft types, draw annual noise contour maps, mark noise control zone classes and sensitive receptors, and include protection measures",
  "Compile noise effects from actual complaint statistics, draw seasonal contour maps one year after opening, mark complainants' addresses and let the airport negotiate compensation with them",
  "Cite existing monitoring data from nearby airports directly, omit contour maps, and simply mark one kilometre beyond each runway end as the affected zone and build noise barriers",
  "Judge against the civil aviation authority's published standard values, skip all assessment if not exceeded, and let that authority delineate zones and handle compensation if exceeded"],
 "Article 44."),

(GL,"第45條",2,"評估準則-土石採取探採礦",
 "土石採取（含堆積土石）、探礦、採礦之開發，其廢（污）水及廢棄物處理設施應於何時完成試運轉？",
 ["應於計畫實施或引進污染源前完成試運轉","應於計畫實施或引進污染源後一年內完成試運轉","應於開發期限屆滿前六個月內完成試運轉即可","應於環境影響評估審查通過前完成試運轉作業"],"a",
 "第45條第1項：土石採取（含堆積土石）、探礦、採礦之開發，其廢（污）水處理設施與廢棄物處理設施，應於計畫實施或引進污染源前，完成試運轉。第2項：應分析裸露地面與土石渣、礦渣或堆積物之穩定性，訂定防止地下水脈切斷、地表沖刷、水污染與植生綠化等環境保護對策。第3項：應預測開發期限屆滿或計畫停止後可能引起之污染與景觀問題並訂定復整（舊）計畫。",
 "When must wastewater and waste treatment facilities for quarrying and mining be trial-run?",
 ["Before the plan is implemented or pollution sources are introduced","Within one year after the plan is implemented or sources introduced","Within six months before the development period expires","Before the environmental impact assessment review is passed"],
 "Article 45."),

(GL,"第46條",3,"評估準則-堰壩水利",
 "堰壩或其他攔水設施之開發，開發單位應分析何項影響？",
 ["對上下游集水區居民所產生之社會經濟文化正負面影響；河川上下游水道變遷、水量變化（含基流量）、地下水互補、水體涵容能力與水域生態之影響",
  "對上下游集水區土地之市場行情與交易熱度影響；河川砂石之可採取數量、砂石市場售價、砂石業者家數與運輸路線及其對地方稅收之影響",
  "對上下游集水區觀光遊憩人潮之成長幅度影響；水庫營運後之發電售電收益、公共給水收費標準、灌溉用水費率及其對財務自償率之影響",
  "對上下游集水區行政區劃調整之必要性影響；水庫管理機關之組織編制、人員員額配置、預算編列方式及其對地方自治權限劃分之可能影響"],"a",
 "第46條第1項：開發單位應分析堰壩或其他攔水設施於施工期間或興建後，對上、下游集水區之居民所產生之社會、經濟、文化之正、負面影響；另對河川上、下游水道變遷、水量變化（含基流量）、地下水互補、水體涵容能力與水域生態之影響亦應納入評估；對淹沒區內造成保育類野生動物或珍貴稀有植物之不利影響應納入移植復育計畫。第2項：水力發電廠、越域引水工程應分析引水期間對本流上下游可用流量、基流量及下游地下水補注之變化。",
 "What must be analysed for dams and other water-retaining structures?",
 ["Positive and negative social, economic and cultural effects on upstream and downstream catchment residents; plus channel change, flow change including base flow, groundwater recharge, assimilative capacity and aquatic ecology",
  "Effects on the market prices and transaction activity of upstream and downstream catchment land; plus extractable sand and gravel volumes, market prices, operator numbers, haul routes and local tax revenue",
  "Effects on tourist growth in the upstream and downstream catchment; plus post-operation power sales revenue, public water tariffs, irrigation water rates and the project's financial self-liquidating ratio",
  "Effects on the need to adjust administrative boundaries in the catchment; plus the reservoir authority's organisational structure, staffing levels, budgeting method and division of local autonomy powers"],
 "Article 46."),

(GL,"第47條",1,"評估準則-農林漁牧",
 "農、林、漁、牧地之開發，開發單位應分析何事項？",
 ["應分析其土地利用之潛力與適宜性，並說明引進外來物種或生產技術對當地社區、生態、水文環境之影響",
  "應分析其產品之市場售價與通路，並說明引進外來物種或生產技術對公司營收及股東權益報酬率之影響",
  "應分析其土地之公告現值與租金，並說明引進外來物種或生產技術對周邊土地增值幅度及稅收之影響",
  "應分析其僱用人力之來源與成本，並說明引進外來物種或生產技術對當地就業結構及薪資水準之影響"],"a",
 "第47條：農、林、漁、牧地之開發，應分析其土地利用之潛力與適宜性。說明引進外來之物種或生產技術所造成對當地社區或生態、水文環境等之影響，納入環境保護對策。",
 "What must be analysed for agricultural, forestry, fishery and livestock land development?",
 ["The potential and suitability of the land use, and the effects of introduced species or production techniques on the local community, ecology and hydrology",
  "The market prices and sales channels for the products, and the effects of introduced species or techniques on company revenue and return on equity",
  "The announced land value and rental levels, and the effects of introduced species or techniques on surrounding land appreciation and tax revenue",
  "The sources and cost of the labour employed, and the effects of introduced species or techniques on local employment structure and wage levels"],
 "Article 47."),

(GL,"第48條",2,"評估準則-遊樂高球",
 "遊樂區、風景區、高爾夫球場及運動場地之開發，本準則有何規劃限制？",
 ["不宜開挖山頭；坡度超過百分之四十之山坡地其原有樹林地貌儘量保留；原有溪流溝坑之改道或填平應先徵詢有關目的事業主管機關之意見",
  "得適度開挖山頭以利場地平整；坡度超過百分之二十之山坡地應全面剷平重新植生；原有溪流溝坑得逕行改道或填平而無須徵詢任何機關意見",
  "不宜開挖山頭；坡度超過百分之六十之山坡地應設置擋土牆並鋪設人工草皮；原有溪流溝坑之改道或填平應報請中央主管機關核准後始得為之",
  "得依球場設計需要調整地形地貌；坡度超過百分之三十之山坡地應改闢為停車場使用；原有溪流溝坑應一律填平以避免蚊蟲孳生及水域事故發生"],"a",
 "第48條第1項：遊樂區、風景區、高爾夫球場及運動場地之開發，不宜開挖山頭；坡度超過百分之四十之山坡地，其原有樹林地貌儘量保留；原有溪流溝坑之改道或填平，應先徵詢有關目的事業主管機關之意見。第2項：開發單位應預測未來假日或慶典期間所引入大量遊客及車輛，對交通運輸、停車場、用水量以及環境衛生等所造成之影響，納入環境保護對策。",
 "What planning limits apply to amusement areas, scenic areas, golf courses and sports grounds?",
 ["Hilltops should not be excavated; original woodland on slopes steeper than 40% should be kept as far as possible; diverting or filling streams and gullies requires prior consultation with the industry authority",
  "Hilltops may be excavated to level the site; slopes steeper than 20% must be fully flattened and replanted; streams and gullies may be diverted or filled without consulting any authority at all",
  "Hilltops should not be excavated; slopes steeper than 60% require retaining walls and artificial turf; diverting or filling streams and gullies needs the central competent authority's approval",
  "Landform may be adjusted as the course design requires; slopes steeper than 30% must be converted to car parks; all streams and gullies must be filled to prevent mosquitoes and water accidents"],
 "Article 48."),

(GL,"第49條",2,"評估準則-文教醫療",
 "文教建設、醫療建設之開發設有實驗室、解剖室、手術室與感染性事業廢棄物處理設施者，應如何辦理？",
 ["應分別估算廢液、感染性事業廢棄物、污泥及其他廢棄物之產生量，規劃設置分類貯存收集運輸及處理系統；不能自行處理者應檢附合格機構證明或調查當地合格機構家數",
  "應將所有廢液及感染性廢棄物合併計算總量即可，免規劃分類貯存收集運輸系統；不能自行處理者由當地衛生主管機關指定機構代為處理並由其負擔處理費用",
  "應由目的事業主管機關代為估算各類廢棄物產生量並規劃處理系統；開發單位僅需提供樓地板面積及床位數等基本資料，且免調查當地合格清除處理機構家數",
  "應於營運滿一年後依實際產生量補行申報即可，規劃階段免予估算；不能自行處理者得暫存於院內指定區域，俟累積達一定數量後再委託合格機構一次清運處理"],"a",
 "第49條：文教建設、醫療建設之開發，凡設有實驗室、解剖室、手術室與感染性事業廢棄物處理設施者，對所產生之廢液、感染性事業廢棄物、污泥及其它廢棄物等，應分別估算產生量，規劃設置分類、貯存、收集運輸及處理系統。不能自行處理者，應檢附合格清除、處理機構之證明文件或調查當地合格清除、處理機構之家數，且註明最終處理（置）地點之容量負荷。",
 "What applies to cultural, educational or medical developments with laboratories or infectious waste facilities?",
 ["Estimate the volumes of waste liquids, infectious industrial waste, sludge and other wastes separately and plan sorting, storage, collection, transport and treatment systems; if unable to treat them, attach licensed operator certificates or survey local operator numbers",
  "Simply total all waste liquids and infectious waste together with no sorting, storage or transport system; if unable to treat them, the local health authority designates an operator and bears the cost",
  "Have the industry authority estimate the waste volumes and plan the systems; the developer supplies only floor area and bed numbers and need not survey the number of licensed local operators",
  "Report the actual volumes one year after operations begin with no estimate at the planning stage; if unable to treat them, store them on site until enough accumulates for a single licensed collection"],
 "Article 49."),

(GL,"第50條",3,"評估準則-新市區舊市區",
 "新市區建設、舊市區更新及高樓建築之開發，本準則有何評估要求？",
 ["應預測對水源供應排水防洪廢棄物清理及交通設施之影響並評估各項節能省水措施可行性；高樓建築應評估帷幕牆反光、對周遭風場日照電波及空氣污染物擴散之干擾",
  "應預測對房地產價格及銷售去化速度之影響並評估各項行銷推廣措施可行性；高樓建築應評估外牆建材成本、施工工期長短及對建照核發時程之可能影響程度",
  "應預測對當地人口成長及學區劃分之影響並評估各項教育設施增設可行性；高樓建築應評估電梯數量、消防設備規格及對物業管理費用分攤方式之可能影響",
  "應預測對地方稅收及財政收支之影響並評估各項公共設施委外經營可行性；高樓建築應評估屋頂設置直昇機停機坪之必要性及對航空管制之可能干擾情形"],"a",
 "第50條第1項：新市區建設、舊市區更新之開發，應預測其對當地及鄰近地區水源供應、排水或防洪系統、廢棄物清理及交通設施等之影響，並應評估設置汽電共生或汽冷熱共生設備、區域供冷供熱系統、雨水貯留利用系統、生活雜排水回收再利用系統為中水道沖洗廁所及澆灌利用等各項節能省水措施之可行性。第2項：舊市區更新拆除所產生之廢棄物須先詳細調查、規劃運輸路線及適當之處理場。第3項：高樓建築應預測及評估交通、停車或帷幕牆（含太陽能板）反光、室內停車場廢氣排放之影響，以及高層結構體對周遭風場、日照、電波、空氣污染物擴散之干擾。",
 "What assessment applies to new town development, urban renewal and high-rise buildings?",
 ["Predict effects on water supply, drainage or flood systems, waste clearance and transport facilities and assess energy and water saving measures; high-rises must assess curtain wall glare and interference with wind, sunlight, radio waves and pollutant dispersion",
  "Predict effects on property prices and sales absorption rates and assess marketing measures; high-rises must assess facade material costs, construction duration and the effect on building permit timing",
  "Predict effects on local population growth and school catchment zoning and assess added educational facilities; high-rises must assess lift numbers, fire equipment specifications and management fee apportionment",
  "Predict effects on local tax revenue and fiscal balance and assess outsourcing of public facilities; high-rises must assess the need for a rooftop helipad and possible interference with air traffic control"],
 "Article 50."),

(GL,"第51條",3,"評估準則-環境保護工程",
 "環境保護工程之開發，污水下水道系統工程及廢棄物焚化廠之評估要求為何？",
 ["污水下水道系統工程應調查預測分析廢（污）水合流或分流排放對承受水體之影響，承受水體為河川者調查及評估期間應包括豐水期及枯水期；焚化廠應評估臭味及滲出水影響並訂定復育計畫",
  "污水下水道系統工程僅需說明管線長度及埋設深度即可免評估承受水體影響，承受水體為河川者僅需於豐水期調查一次；焚化廠僅需說明爐體規格及處理量而免評估臭味影響",
  "污水下水道系統工程應由下水道主管機關代為評估承受水體影響，開發單位僅需提供設計圖說；焚化廠之臭味及滲出水影響由地方環保局逕行認定並要求改善即可",
  "污水下水道系統工程應調查承受水體之航運量與漁獲量，調查期間應包括春夏秋冬四季；焚化廠應評估飛灰底渣之市場售價及最終處置場之土地取得成本並訂定收購計畫"],"a",
 "第51條第1項：環境保護工程之開發，其污水下水道系統工程應調查、預測、分析廢（污）水合流或分流排放對於承受水體水質、水量及生態之影響；承受水體為河川者，調查及評估期間應包括豐水期及枯水期；採海洋放流者應說明海域生態及環境現況。第2項：廢棄物焚化（資源回收）廠及廢棄物處理場（廠）工程應評估焚燒處理流程中以及儲存或掩埋或其他方式處理廢棄物產生臭味及滲出水之影響，對於掩埋場封閉或使用期限屆滿後之復育計畫、土地利用計畫以及二次污染問題應預為規劃。第4項：應訂定營運管理計畫，內容包括產權歸屬移轉、管理組織、財源籌措、權責分工及試運轉方式。",
 "What assessment applies to sewerage works and waste incineration plants?",
 ["Sewerage works must survey and analyse the effect of combined or separate discharge on the receiving water, covering both wet and dry seasons for rivers; incinerators must assess odour and leachate and plan site restoration",
  "Sewerage works need only state pipe length and burial depth with no receiving water assessment, surveying rivers once in the wet season; incinerators need only state furnace specifications and capacity",
  "Sewerage works have receiving water effects assessed by the sewerage authority from the developer's drawings; odour and leachate from incinerators are determined by the local bureau instead",
  "Sewerage works must survey shipping volumes and fish catches in the receiving water across all four seasons; incinerators must assess fly ash market prices and land costs for final disposal sites"],
 "Article 51."),

(GL,"第52條",3,"評估準則-火力發電",
 "火力發電或汽電共生工程之開發，其輸電線路兩側調查範圍每側不得少於多少公尺？",
 ["每側不得少於五十公尺","每側不得少於一百公尺","每側不得少於十公尺","每側不得少於二百公尺"],"a",
 "第52條第5項：計畫輸電線路之兩側調查範圍，每側不得少於五十公尺，其景觀與當地環境之和諧性應為評估之重點。第6項：超高壓輸電線路工程所產生之電磁效應及對居民之可能影響應予預測及評估。第1項：火力發電或汽電共生工程如以煤、油、天然氣或烏瀝乳為燃料，應依當地氣象條件、污染物質量、控制措施效率、與人口聚集社區村落之距離等因素於周界內規劃設置緩衝地帶。第4項：火力發電廠應評估使用熱電共生系統之可行性並考量採用超超臨界或複循環等高發電效率機組。",
 "For thermal power projects, what is the minimum survey width on each side of the transmission line?",
 ["Not less than 50 metres on each side","Not less than 100 metres on each side","Not less than 10 metres on each side","Not less than 200 metres on each side"],
 "Article 52, paragraphs 5 and 6."),

(GL,"第53條",3,"評估準則-核廢料場所",
 "放射性核廢料儲存或處理場所之興建，其意外事故評估應包括何內容？",
 ["應包括型態、嚴重性、發生之可能性及對環境影響之程度與範圍；評估之影響期間應分短中長期及其他潛在影響期間；型態包括輻射外洩設備故障操作錯誤火災化學爆炸及運輸工具事故",
  "應包括肇事責任歸屬、保險理賠金額、求償訴訟程序及對公司財務之衝擊；評估期間僅需就事故發生當年度計算；型態僅限於輻射外洩一項而不包括其他人為或天然災害類型",
  "應包括媒體報導次數、民眾陳情件數、地方政府態度及對後續開發許可之影響；評估期間以事故後三個月為限；型態包括輻射外洩與運輸事故但不包括設備故障及操作錯誤",
  "應包括搶修所需人力、設備採購清單、預算追加額度及對工程進度之延誤；評估期間依主管機關個案指定；型態由開發單位視場所特性自行決定而無須涵蓋火災及化學爆炸"],"a",
 "第53條第2項：對於可能發生意外事故之評估，應包括型態、嚴重性、發生之可能性及對環境影響之程度與範圍；評估之影響期間應分短、中、長期及其他潛在影響之期間；意外事故型態包括輻射外洩、設備故障、操作錯誤、火災、化學爆炸、運輸工具事故及其他事故，其緊急應變措施應就通知、動員、事故評估與預測、疏散方式、搶救與搶修、防護行動及復原作業等予以評估規劃。第1項：應訂定營運期間環境保護對策，包括核廢料運送規劃、營運廢液或廢棄物處理等。第3項：以各種方式運送放射性核廢料應就運送途徑、時段分析可能之影響。",
 "What must the accident assessment for radioactive waste facilities cover?",
 ["Type, severity, likelihood and the degree and extent of environmental impact; short, medium, long term and other potential periods; types include radiation leaks, equipment failure, operator error, fire, chemical explosion and transport accidents",
  "Liability allocation, insurance payouts, litigation procedures and the financial impact on the company; only the year of the accident; types limited to radiation leaks and excluding other man-made or natural disasters",
  "Media coverage counts, public complaint numbers, local government attitude and the effect on later permits; limited to three months after the accident; types cover leaks and transport but not equipment failure or operator error",
  "Repair manpower, equipment purchase lists, budget increases and the delay to construction progress; periods designated case by case; types decided by the developer without covering fire or chemical explosion"],
 "Article 53."),

(GL,"第54條",3,"評估準則-核能開發",
 "核能及其他能源之開發，既有核能電廠廠址興建或增建機組時應如何評估？",
 ["應將已產生之環境影響與興建、增建機組之環境影響併予加成評估；核能電廠開發及產生放射性核廢料之儲存處理應合併進行評估",
  "應僅就新增機組之環境影響單獨評估，既有機組已產生之環境影響免予納入；核能電廠開發與核廢料儲存處理應分別進行評估而不得合併",
  "應由核能主管機關代為評估既有及新增機組之環境影響；開發單位僅需提供機組規格與發電量資料，並免就核廢料儲存處理進行任何評估",
  "應以既有機組之環境監測資料推估新增機組影響即可；如監測資料顯示符合標準者，得免就新增機組進行環境影響評估並免評估核廢料處理"],"a",
 "第54條第2項：既有核能電廠廠址興建或增建機組，應將已產生之環境影響與興建、增建機組之環境影響併予加成評估；核能電廠開發及產生放射性核廢料之儲存處理，應合併進行評估。第4項：既有核能電廠內興建放射性核廢料儲存或處理場所者，應將相關環境影響予以加成評估。第3項：評估輻射影響應敘明分析原理、程式基本假設、功能限制、曝露途徑、模式程式結構、計算流程、輸入輸出資料、使用參數及分析結果。第5項：緩衝地帶、溫排水及輸電線路之影響評估依第52條辦理。",
 "How must new or added units at an existing nuclear plant site be assessed?",
 ["The impacts already produced must be assessed cumulatively together with those of the new or added units; plant development and radioactive waste storage and treatment must be assessed jointly",
  "Only the new units are assessed on their own, with impacts already produced excluded; plant development and waste storage and treatment must be assessed separately and never jointly",
  "The nuclear authority assesses both existing and new units on the developer's behalf, which supplies only unit specifications and output data and assesses no waste storage at all",
  "New unit impacts may be inferred from existing monitoring data; where that data meets standards, no assessment of the new units or of waste treatment is needed at all"],
 "Article 54."),

(GL,"第55條",1,"評估準則-購物中心",
 "工商綜合區、購物專用區、大型購物中心或展覽會場、地下街工程之開發，應就何情形納入環境保護對策？",
 ["假日或慶典節日所引進之大量人口對周遭地區造成之交通、停車、廢棄物、噪音、環境衛生等影響",
  "平日離峰時段之來客稀少對周遭商圈造成之營業額下滑、店面空置、租金下跌等經濟影響情形",
  "開幕期間之促銷活動對同業競爭者造成之市場占有率變化、價格競爭、人才流動等商業影響",
  "營運期間之員工排班對勞動條件造成之工時延長、加班費計算、輪班間隔等勞動權益影響"],"a",
 "第55條：工商綜合區、購物專用區、大型購物中心，或展覽會、博覽會、展示會場，或地下街工程之開發，對於假日或慶典節日所引進之大量人口對周遭地區所造成之交通、停車、廢棄物、噪音、環境衛生等影響，應納入其環境保護對策及緊急應變措施。",
 "What must be included in protection measures for shopping centres and underground malls?",
 ["Traffic, parking, waste, noise and environmental sanitation effects on surrounding areas from the large crowds drawn on holidays and festivals",
  "Falling turnover, vacant shopfronts and declining rents in the surrounding district caused by sparse custom during weekday off-peak hours",
  "Market share shifts, price competition and staff turnover among competitors caused by promotional activities during the opening period",
  "Longer working hours, overtime calculation and shift interval effects on labour rights caused by staff rostering during operations"],
 "Article 55."),

(GL,"第56條",2,"評估準則-鄰避設施",
 "墳墓、靈（納）骨堂（塔）、屠宰場、動物收容所、殯儀館、煤氣廠等開發行為，應如何辦理？",
 ["應加強植栽綠化及視覺景觀設計，並依污染程度範圍、與人口聚集社區村落之距離、視覺景觀影響等因素於周界內規劃設置適當緩衝綠帶；對野生動植物有影響之虞者植栽應以原生植種為主",
  "應加強圍牆高度及門禁管制設計，並依土地取得成本、施工難易程度、營運收益高低等因素於周界外購置適當緩衝用地；對野生動植物有影響之虞者應設置圍網完全隔離其活動",
  "應加強建築物外觀及照明設計，並依地方民意反映強度、民意代表意見、媒體報導頻率等因素決定是否設置緩衝綠帶；對野生動植物有影響之虞者得以繳納生態補償金替代",
  "應加強空氣污染防制設備效能，並依主管機關指定之統一標準於周界內設置固定寬度緩衝綠帶；對野生動植物有影響之虞者應將其全數捕捉遷移至鄰近保護區內予以安置"],"a",
 "第56條：墳墓、靈（納）骨堂（塔）、屠宰場（含人工屠宰場、電動屠宰場）、動物收容所、殯儀館、煤氣廠或經中央主管機關公告對環境有不良影響之虞之開發行為，應加強植栽綠化及視覺景觀之設計，並依可能產生污染之程度、範圍，開發行為基地與人口聚集社區、村落之距離，視覺景觀之影響及其他相關因素，於周界內規劃設置適當緩衝綠帶。對野生植物、動物生態有影響之虞者，其植栽綠化應以原生植種及保護野生動物棲地為主，並評估可能受影響之生物通道及棲息地屏障，規劃配置綠帶。",
 "What applies to cemeteries, slaughterhouses, animal shelters, funeral parlours and gasworks?",
 ["Strengthen planting and visual design and plan a suitable buffer green belt inside the boundary based on pollution degree and extent, distance to settlements and visual effects; where wildlife may be affected, use native species",
  "Strengthen wall height and access control design and buy suitable buffer land outside the boundary based on land cost, construction difficulty and operating revenue; where wildlife may be affected, fence them off entirely",
  "Strengthen building appearance and lighting design and decide on a buffer belt based on the strength of local opinion, councillors' views and media coverage; where wildlife may be affected, pay ecological compensation",
  "Strengthen air pollution control equipment efficiency and provide a fixed-width buffer belt to the authority's uniform standard; where wildlife may be affected, capture and relocate them all to a nearby reserve"],
 "Article 56."),

(GL,"第57條",1,"評估準則-其他開發行為",
 "其他經中央主管機關公告之開發行為，其環境影響評估作業應如何辦理？",
 ["準用本準則之相關規定辦理","一律免適用本準則之任何規定","由開發單位自訂作業規範辦理","由目的事業主管機關另訂準則"],"a",
 "第57條：其他經中央主管機關公告之開發行為，其環境影響評估作業準用本準則之相關規定。此係配合開發行為應實施環境影響評估細目及範圍認定標準第44條，中央主管機關得另行公告應實施環評之細目及範圍，該等新增開發行為之書件製作即準用本準則。",
 "How is EIA handled for other developments announced by the central competent authority?",
 ["The relevant provisions of these Guidelines apply mutatis mutandis","These Guidelines do not apply to such developments at all","The developer sets its own operating rules for the assessment","The industry authority issues separate guidelines for them"],
 "Article 57."),

(GL,"第58條",2,"評估準則-技術規範",
 "中央主管機關就評估技術規範有何權限？開發單位製作評估書初稿時應依何辦理環境調查？",
 ["中央主管機關得視需要會商有關機關訂定評估技術規範並公告之；開發單位製作評估書初稿時依範疇界定會議決定之評估範疇辦理環境調查作業",
  "中央主管機關應每年修正評估技術規範並報行政院核定；開發單位製作評估書初稿時依說明書審查結論所列項目辦理環境調查作業而不受範疇界定拘束",
  "中央主管機關僅得就技術規範提供諮詢而無訂定權限；開發單位製作評估書初稿時得自行決定環境調查之項目方法地點時間及頻率並免敘明其理由",
  "中央主管機關應委由技術顧問機構訂定評估技術規範；開發單位製作評估書初稿時依目的事業主管機關指定之調查項目辦理並將結果送該機關核定"],"a",
 "第58條第1項：中央主管機關得視需要會商有關機關訂定評估技術規範，並公告之。第2項：開發單位製作說明書時，依第10條第2項辦理環境調查作業；如涉及開發行為特性應提出相關預測、分析及評估模式者，依評估技術規範辦理。第3項：開發單位製作評估書初稿時，依範疇界定會議決定之評估範疇辦理環境調查作業。",
 "What power does the central authority have over technical guidelines, and how is survey scope set for a draft report?",
 ["The central authority may consult relevant agencies to set and announce technical guidelines; draft reports follow the assessment scope decided at the scoping meeting",
  "The central authority must revise the guidelines yearly with Executive Yuan approval; draft reports follow the items in the statement review conclusions and ignore scoping",
  "The central authority may only advise and cannot issue guidelines; developers may set survey items, methods, places, times and frequencies freely without stating reasons",
  "The central authority must commission a consultancy to write the guidelines; draft reports follow survey items designated by the industry authority and are sent to it for approval"],
 "Article 58."),

(GL,"第59條",1,"評估準則-法令未規定",
 "開發行為環境影響評估作業，法令未規定者應以何者為準？",
 ["以主管機關環境影響評估審查委員會之決議為準","以開發單位委託之技術顧問機構意見為準","以目的事業主管機關之個案函釋意見為準","以當地民眾及環保團體之多數意見為準"],"a",
 "第59條：開發行為環境影響評估作業，法令未規定者，以主管機關環境影響評估審查委員會之決議為準。此與第2條「本準則未規定者適用其他法令」之規定相互配合，形成法令、其他法令、審查委員會決議之適用順序。",
 "Where the law is silent on EIA operations, what governs?",
 ["The resolutions of the competent authority's EIA review committee","The opinion of the consultancy retained by the developer","Case-by-case interpretive letters from the industry authority","The majority view of local residents and environmental groups"],
 "Articles 2 and 59."),

(GL,"第60條",2,"評估準則-過渡規定",
 "本準則施行前受理審查中之說明書、評估書初稿、評估書應如何處理？",
 ["得依開發單位提出申請時所依據各該原適用準則之規定辦理","一律應依修正後之本準則規定重新製作書件並重新送審","應由主管機關逕行退回目的事業主管機關不予繼續審查","應暫停審查程序俟本準則施行滿六個月後始得繼續進行"],"a",
 "第60條：本準則施行前受理審查中之說明書、評估書初稿、評估書之處理，得依開發單位提出申請時所依據各該原適用準則之規定辦理。此為信賴保護之過渡規定，避免因準則修正致審查中案件須全面重製書件。第61條並規定本準則自發布日後六個月施行，以給予緩衝期間。",
 "How are EIA documents already under review when these Guidelines take effect handled?",
 ["They may be handled under the guidelines that applied when the application was filed","They must all be redrafted under the amended Guidelines and resubmitted for review","They must be returned by the competent authority to the industry authority unreviewed","Their review must be suspended until six months after these Guidelines take effect"],
 "Articles 60 and 61."),

(GL,"第61條",1,"評估準則-施行日期",
 "開發行為環境影響評估作業準則之施行日期規定為何？",
 ["自發布日後六個月施行","自發布日施行而無緩衝期","自發布日後三個月施行","自發布後次年一月一日施行"],"a",
 "第61條：本準則自發布日後六個月施行。相較於開發行為應實施環境影響評估細目及範圍認定標準第53條之自發布日施行，本準則因涉及書件製作格式、環境調查方法等實務作業，故設有六個月之緩衝期間，並配合第60條之過渡規定。",
 "When do these Guidelines take effect?",
 ["Six months after the date of promulgation","On the date of promulgation with no buffer","Three months after the date of promulgation","On 1 January of the year following promulgation"],
 "Article 61."),
# ---END---
]
