# -*- coding: utf-8 -*-
# 第 2 批（C）：營造安全衛生設施標準（民國115年6月30日）
L = "OSH-36"
Q = [
(L,"第1-1條",2,"營造-總則",
 "營造安全衛生設施標準所稱「露天開挖」，下列敘述何者正確？",
 ["於室外採人工或機械實施土、砂、岩石等之開挖，包括基礎開挖、管溝開挖與整地","僅指於室外採機械實施深度超過五公尺之開挖，不包括基礎開挖、管溝開挖及整地","僅指於室內採人工實施土、砂、岩石等之開挖，包括隧道開挖與坑道支撐作業","僅指採人工實施之地下埋設物管溝開挖，不包括機械開挖、基礎開挖與整地"],"a",
 "第1條之1：露天開挖指於室外採人工或機械實施土、砂、岩石等之開挖，包括土木構造物、建築物之基礎開挖、地下埋設物之管溝開挖與整地及其他相關之開挖。",
 "Under the Construction Safety and Health Facilities Standards, 'open excavation' means:",
 ["Outdoor manual or mechanical excavation of soil, sand or rock, including foundation, trench and grading work","Outdoor mechanical excavation deeper than five metres only, excluding foundation, trench and grading work","Indoor manual excavation of soil, sand or rock only, including tunnel excavation and gallery support work","Manual trenching for underground utilities only, excluding mechanical, foundation and grading excavation"],
 "Article 1-1: open excavation is outdoor manual or mechanical excavation of soil, sand, rock, etc., including foundations for structures and buildings, trenches for underground utilities, grading and related excavation."),

(L,"第3條",2,"營造-總則",
 "依營造標準第3條，雇主應於何階段依設計階段之風險評估及圖說實施風險評估，並將安全衛生設施納入考量？",
 ["施工規劃階段","完工驗收後","發生災害後","保固期滿後"],"a",
 "第3條第1款：於施工規劃階段，應依設計階段之風險評估及圖說等資料，實施風險評估，並將必要之安全衛生設施納入考量；依規定須有施工計畫者應納入施工計畫。工程施工期間包含開工前準備及竣工後驗收、保固維修期間。",
 "Under Article 3, at which stage shall the employer conduct a risk assessment based on the design-stage assessment and drawings?",
 ["The construction planning stage","After completion acceptance","After an accident","After the warranty period"],
 "Article 3(1): at the construction planning stage, based on design-stage risk assessment and drawings, incorporating necessary safety facilities into the construction plan; the construction period includes pre-work preparation and post-completion acceptance and warranty maintenance."),

(L,"第5條",1,"營造-工作場所",
 "工作場所暴露之鋼筋、鋼材等易生職業災害者，應採取何種防護設施？",
 ["彎曲尖端、加蓋或加裝護套","塗上防鏽油漆並標示顏色","以塑膠繩綁紮並固定於支架","設置警告標示並圍以警戒線"],"a",
 "第5條：對於工作場所暴露之鋼筋、鋼材、鐵件、鋁件及其他材料等易生職業災害者，應採取彎曲尖端、加蓋或加裝護套等防護設施。",
 "Exposed rebar, steel and similar materials in the workplace shall be protected by:",
 ["Bending the tips, capping or sleeving them","Painting them with rust-proof paint","Tying them to a bracket with plastic rope","Posting warning signs and roping off the area"],
 "Article 5: exposed rebar, steel, iron, aluminum and other materials shall have their tips bent, capped or fitted with protective sleeves."),

(L,"第8條",2,"營造-工作場所",
 "工作場所之周圍原則上應設置何種圍籬？大規模土木工程得以何者替代？",
 ["固定式圍籬；移動式圍籬或警示帶圍成之警示區","移動式圍籬；固定式圍籬或警示帶圍成之警示區","警示帶圍成之警示區；固定式圍籬或活動護欄","固定式護欄；僅設置警告標示牌即可免設圍籬"],"a",
 "第8條：工作場所周圍應設置固定式圍籬並於明顯位置裝設警告標示；大規模施工之土木工程或設置固定式圍籬有困難者，得以移動式圍籬、警示帶圍成之警示區替代。",
 "What fencing is required around a construction site, and what may large civil works use instead?",
 ["Fixed fencing; movable fencing or warning-tape zones","Movable fencing; fixed fencing or warning-tape zones","Warning-tape zones; fixed fencing or movable guardrails","Fixed guardrails; warning signboards alone, with no fencing"],
 "Article 8: fixed fencing with warning signs; large-scale civil works or where fixed fencing is difficult may use movable fencing or warning-tape zones."),

(L,"第11條",2,"營造-工作場所",
 "工作場所人員及車輛機械出入口處，下列何者正確？",
 ["人員出入口與車輛機械出入口應分隔設置，並置管制人員","人員出入口與車輛機械出入口應合併設置，以節省用地","出入口應設推開式大門，車輛出入頻繁時免設引導人員","車輛機械得自由進出，管制人員僅需查核工程車輛牌照"],"a",
 "第11條：事前調查地下埋設物；出入口應設拉開式大門，車輛出入頻繁時應置交通引導人員；人員出入口與車輛機械出入口應分隔設置（設有足以防止事故之警告標誌者除外）；應置管制人員管制人員防護具及車輛許可文件。",
 "Regarding site entrances for personnel and vehicles, which is correct?",
 ["Personnel and vehicle entrances shall be separate, with gate control personnel","Personnel and vehicle entrances may be combined to save site space and cost","Gates shall be push-open, and traffic guides are not needed at busy entrances","Vehicles may enter freely; gate staff only check vehicle licence plates"],
 "Article 11: survey underground utilities; sliding gates; traffic guides where vehicle traffic is frequent; separate personnel and vehicle entrances (unless warning signs suffice); gate control staff check PPE and vehicle permits."),

(L,"第11-2條、第174條",3,"營造-工作場所",
 "依民國115年修正之營造標準第11條之2，進入營繕工程工作場所作業人員應於事前接受何種訓練？該條自何時施行？",
 ["中央主管機關指定之營造作業安全訓練；一百十六年七月一日","地方主管機關指定之營造作業安全訓練；一百十五年七月一日","一般安全衛生教育訓練六小時；一百十六年一月一日","中央主管機關指定之急救人員訓練；一百十七年七月一日"],"a",
 "第11條之2：進入營繕工程工作場所作業人員，應於事前使其接受中央主管機關指定之營造作業安全訓練（已依教育訓練規則第4、5、7或10條受訓者除外）。第174條：第11條之2自一百十六年七月一日施行。",
 "Under Article 11-2 (2026 amendment), what training must workers receive before entering a construction site, and when does it take effect?",
 ["Construction work safety training designated by the central authority; 1 July 2027 (ROC 116)","Construction work safety training designated by the local authority; 1 July 2026 (ROC 115)","Six-hour general occupational safety and health training; 1 January 2027 (ROC 116)","First-aid responder training designated by the central authority; 1 July 2028 (ROC 117)"],
 "Article 11-2: workers shall receive construction work safety training designated by the central competent authority (exempt if trained under Articles 4, 5, 7 or 10 of the Training Rules); Article 174: effective 1 July ROC 116 (2027)."),

(L,"第14條",3,"營造-水域作業",
 "勞工鄰近水域作業有落水之虞時，備置之救生船筏每艘應配備多長、直徑多少之聚丙烯纖維繩索？",
 ["長度十五公尺、直徑九點五毫米","長度十公尺、直徑六毫米","長度三十公尺、直徑十二毫米","長度五公尺、直徑八毫米"],"a",
 "第14條：應設置防止落水設施或使勞工著用救生衣；備置動力救生船、救生艇等，每艘船筏應配備長度十五公尺、直徑九點五毫米之聚丙烯纖維繩索，並掛繫與最大可救援人數相同數量之救生圈、船鈎及救生衣。",
 "For work near water with drowning risk, each rescue boat shall carry a polypropylene rope of what length and diameter?",
 ["15 m long, 9.5 mm diameter","10 m long, 6 mm diameter","30 m long, 12 mm diameter","5 m long, 8 mm diameter"],
 "Article 14: fall-prevention or life jackets; rescue boats each with a 15 m, 9.5 mm polypropylene rope carrying life rings, boat hooks and life jackets equal to the maximum number of rescuees."),

(L,"第17條",2,"營造-墜落",
 "高度二公尺以上作業有墜落之虞者，應訂定墜落災害防止計畫，其風險控制先後順序中，第一優先為何？",
 ["經由設計或工法之選擇，儘量使勞工於地面完成作業","使勞工佩掛安全帶或安全母索，並全程監督其使用情形","設置警示線系統，並劃定管制區限制人員進入該區域","張掛安全網，並於作業前確認已實施耐衝擊試驗"],"a",
 "第17條順序：一、設計或工法選擇使勞工於地面完成作業；二、施工程序變更優先施作永久構造物之上下設備或防墜設施；三、設置護欄、護蓋；四、張掛安全網；五、警示線系統；六、限制人員進入管制區；七、使勞工佩掛安全帶；八、增加危險之作業應訂保護計畫。",
 "In the fall-hazard prevention plan for work at 2 m or higher, what is the first priority in the hierarchy of controls?",
 ["Choose designs or methods that let workers finish the job at ground level","Have workers wear harnesses or lifelines and supervise their use throughout","Install warning-line systems and restrict entry to the controlled zone","Hang safety nets and verify impact testing before work begins"],
 "Article 17 hierarchy: (1) design/method to work at ground level; (2) change sequence to build permanent access or fall protection first; (3) guardrails and covers; (4) safety nets; (5) warning lines; (6) restricted zones; (7) harnesses; (8) protection plans for higher-risk work."),

(L,"第18條",3,"營造-墜落",
 "屋頂斜度大於幾度（高底比二比三以上）或為滑溜之屋頂從事作業時，應設置護欄及寬度四十公分以上之工作臺？",
 ["三十四度","三十度","四十五度","二十度"],"a",
 "第18條第1項第2款：於斜度大於三十四度，即高底比為二比三以上，或為滑溜之屋頂從事作業者，應設置適當之護欄、寬度四十公分以上之工作臺及安裝牢穩之梯子；設置護欄有困難者應提供背負式安全帶。",
 "On roofs steeper than what angle (rise-to-run 2:3 or more) or slippery roofs must guardrails and 40 cm work platforms be installed?",
 ["34°","30°","45°","20°"],
 "Article 18(1)(2): on roofs steeper than 34° (2:3) or slippery roofs, install guardrails, work platforms at least 40 cm wide and secure ladders; where guardrails are impractical, provide full-body harnesses."),

(L,"第20條",3,"營造-護欄",
 "依營造標準設置之護欄，上欄杆高度應在多少公分以上？上下開口距離不得大於多少公分？",
 ["九十公分；五十五公分","七十五公分；四十五公分","一百公分；六十公分","一百二十公分；五十公分"],"a",
 "第20條第1款：具有高度九十公分以上之上欄杆、中欄杆、腳趾板及杆柱；其上欄杆、中欄杆及地盤面與樓板面間之上下開口距離應不大於五十五公分。",
 "Guardrails under the Standards shall have a top rail at least how high, with vertical openings not exceeding:",
 ["90 cm; 55 cm","75 cm; 45 cm","100 cm; 60 cm","120 cm; 50 cm"],
 "Article 20(1): top rail at least 90 cm, with mid-rail, toe board and posts; vertical openings between top rail, mid-rail and floor not exceeding 55 cm."),

(L,"第20條",3,"營造-護欄",
 "以鋼管構成之護欄，其上欄杆、中欄杆及杆柱之直徑均不得小於多少公分？杆柱相鄰間距不得超過多少公尺？",
 ["三點八公分；二點五公尺","二點五公分；二公尺","五公分；三公尺","三公分；一點五公尺"],"a",
 "第20條第3款：以鋼管構成者，其上欄杆、中欄杆及杆柱之直徑均不得小於三點八公分，杆柱相鄰間距不得超過二點五公尺。木材構成者上欄杆斷面三十平方公分以上、杆柱間距不得超過二公尺。護欄應能抵抗七十五公斤荷重。",
 "For steel-pipe guardrails, the minimum diameter of rails and posts, and the maximum post spacing are:",
 ["3.8 cm; 2.5 m","2.5 cm; 2 m","5 cm; 3 m","3 cm; 1.5 m"],
 "Article 20(3): steel pipes at least 3.8 cm in diameter with posts no more than 2.5 m apart; wooden top rails at least 30 cm² section with posts not over 2 m apart; guardrails must withstand 75 kg."),

(L,"第20條",3,"營造-護欄",
 "護欄前方多少公尺內之樓板、地板，不得堆放物料、設備，並不得使用梯子、合梯作業？",
 ["一公尺","二公尺","三公尺","五公尺"],"b",
 "第20條第7款：護欄前方二公尺內之樓板、地板，不得堆放任何物料、設備，並不得使用梯子、合梯、踏凳作業及停放車輛機械供勞工使用。但護欄高度超過堆放物最高部達九十公分以上或已採適當安全設施者不在此限。",
 "Within how many meters in front of a guardrail may no materials or equipment be stacked and no ladders or stools used?",
 ["1 m","2 m","3 m","5 m"],
 "Article 20(7): within 2 m in front of a guardrail, no materials or equipment may be placed and no ladders, stepladders, stools or parked vehicles used, unless the rail is 90 cm above the top of such items or other safeguards exist."),

(L,"第21條",3,"營造-護蓋",
 "供車輛通行之護蓋，得以車輛後軸載重之幾倍設計？柵狀構造者柵條間隔不得大於多少公分？臨時開口護蓋表面應漆何色？",
 ["二倍；三公分；黃色","一倍；五公分；紅色","三倍；二公分；黃色","二倍；十公分；綠色"],"a",
 "第21條：護蓋應具人員及車輛安全通過之強度；供車輛通行者得以車輛後軸載重之二倍設計；柵狀構造者柵條間隔不得大於三公分；臨時性開口處使用之護蓋表面漆以黃色並書以警告訊息。",
 "Covers for vehicle passage may be designed for how many times the rear-axle load, grating bars spaced no more than what, and temporary-opening covers painted what color?",
 ["2 times; 3 cm; yellow","1 time; 5 cm; red","3 times; 2 cm; yellow","2 times; 10 cm; green"],
 "Article 21: strength for persons and vehicles; vehicle covers designed for twice the rear-axle load; grating gaps not over 3 cm; temporary-opening covers painted yellow with warning text."),

(L,"第22條",3,"營造-安全網",
 "安全網之工作面至安全網架設平面之攔截高度，不得超過多少公尺？安全網及其組件應多久檢查一次？",
 ["七公尺；每週","五公尺；每日","十公尺；每月","三公尺；每週"],"a",
 "第22條：攔截高度不得超過七公尺（鋼構組配作業得依第151條辦理）；安全網應符合CNS 14252或CNS 16079-1、16079-2；攔截後應即測試；每週應檢查一次。",
 "The interception height from the work surface to a safety net shall not exceed how much, and how often are nets inspected?",
 ["7 m; weekly","5 m; daily","10 m; monthly","3 m; weekly"],
 "Article 22: interception height not over 7 m (steel erection may follow Article 151); nets per CNS 14252 or CNS 16079-1/-2; test after arresting a fall; inspect weekly."),

(L,"第22條",3,"營造-安全網",
 "結構物四周之安全網，攔截高度超過三公尺者，至少應延伸多少公尺？",
 ["二點五公尺","三公尺","四公尺","五公尺"],"c",
 "第22條第3款：攔截高度在一點五公尺以下者至少延伸二點五公尺；超過一點五公尺且在三公尺以下者至少延伸三公尺；超過三公尺者至少延伸四公尺。",
 "Perimeter safety nets with an interception height over 3 m shall extend outward at least:",
 ["2.5 m","3 m","4 m","5 m"],
 "Article 22(3): interception height ≤1.5 m: extend 2.5 m; >1.5 to 3 m: 3 m; >3 m: 4 m."),

(L,"第23條",3,"營造-安全帶",
 "安全母索之最小斷裂強度應在多少公斤以上？安全帶或母索繫固之錨錠至少應能承受每人多少公斤之拉力？",
 ["二千三百公斤；二千三百公斤","一千公斤；一千五百公斤","五百公斤；一千公斤","三千公斤；五千公斤"],"a",
 "第23條：安全母索最小斷裂強度應在二千三百公斤以上；錨錠至少應能承受每人二千三百公斤之拉力；安全帶不得鈎掛於護欄杆件（強度符合者除外）。",
 "The minimum breaking strength of a horizontal lifeline, and the anchor strength per person, shall be at least:",
 ["2,300 kg; 2,300 kg","1,000 kg; 1,500 kg","500 kg; 1,000 kg","3,000 kg; 5,000 kg"],
 "Article 23: lifeline breaking strength at least 2,300 kg; anchors at least 2,300 kg per person; harnesses must not be hooked to guardrail members unless of adequate strength."),

(L,"第23條",3,"營造-安全帶",
 "水平安全母索之設置高度應大於多少公尺？相鄰二錨錠點間之最大間距計算值超過多少公尺者以該值計？",
 ["三點八公尺；十公尺","二公尺；五公尺","五公尺；十五公尺","三公尺；八公尺"],"a",
 "第23條第8款：水平安全母索之設置高度應大於三點八公尺，相鄰二錨錠點間之最大間距得採 L=4(H-3) 計算，其計算值超過十公尺者以十公尺計；錨錠點間之母索僅能繫掛一條安全帶。",
 "A horizontal lifeline shall be installed higher than what, and the maximum anchor spacing is capped at:",
 ["3.8 m; 10 m","2 m; 5 m","5 m; 15 m","3 m; 8 m"],
 "Article 23(8): installed above 3.8 m; anchor spacing L = 4(H − 3), capped at 10 m; only one harness per span between anchors."),

(L,"第23條",3,"營造-安全帶",
 "垂直安全母索，每條原則上應僅提供幾名勞工使用？",
 ["一名（作業位置水平間距一公尺以下者得二人共用）","二名（作業位置水平間距二公尺以下者得三人共用）","三名（作業位置垂直間距一公尺以下者得四人共用）","不限人數（母索下端設有防止鎖扣脫落設施者除外）"],"a",
 "第23條第9款：每條垂直安全母索應僅提供一名勞工使用。但勞工作業或爬昇位置之水平間距在一公尺以下者，得二人共用一條安全母索；母索下端應有防止鎖扣脫落之設施。",
 "A vertical lifeline shall in principle serve how many workers?",
 ["One (two may share if their positions are within 1 m horizontally)","Two (three may share if their positions are within 2 m horizontally)","Three (four may share if their positions are within 1 m vertically)","Unlimited (unless the lower end lacks a device stopping the arrester)"],
 "Article 23(9): one worker per vertical lifeline, except two workers whose positions are within 1 m horizontally may share; the lower end must stop the fall-arrester from sliding off."),

(L,"第24條",3,"營造-警示線",
 "坡度小於十五度之作業區域，距開口部分超過多少公尺時，得設置警示線代替護欄？警示線應距開口多少公尺以上？",
 ["二公尺；二公尺","一公尺；一公尺","三公尺；二公尺","五公尺；三公尺"],"a",
 "第24條：坡度小於十五度之作業區域，距離開口部分、開放邊線超過二公尺時，得設置警示線、管制通行區代替護欄；警示線應距開口二公尺以上；每隔二點五公尺以下設高九十公分以上杆柱，警示繩帶張力二百二十五公斤以上。",
 "In work areas with slope under 15°, warning lines may replace guardrails when more than how far from an edge, and lines must be at least how far from the edge?",
 ["2 m; 2 m","1 m; 1 m","3 m; 2 m","5 m; 3 m"],
 "Article 24: more than 2 m from an opening or open edge; warning lines at least 2 m from the edge, posts ≥90 cm every 2.5 m or less, rope/tape tensile strength ≥225 kg."),

(L,"第26條",3,"營造-飛落",
 "置放於高處，位能超過多少公斤‧公尺之物件有飛落之虞者，應予以固定？",
 ["十二公斤‧公尺","五公斤‧公尺","二十公斤‧公尺","五十公斤‧公尺"],"a",
 "第26條：置放於高處，位能超過十二公斤‧公尺之物件有飛落之虞者，應予以固定之。第27條：覆網攔截位能小於十二公斤‧公尺之物件，網目邊長不得大於二公分，覆網最低點離作業平面三公尺以上。",
 "Objects placed at height with potential energy exceeding how much must be secured against falling?",
 ["12 kg·m","5 kg·m","20 kg·m","50 kg·m"],
 "Article 26: objects with potential energy over 12 kg·m must be secured; Article 27: debris nets for smaller objects have mesh not over 2 cm and hang at least 3 m above the work surface."),

(L,"第28條",2,"營造-搬運",
 "雇主得否使勞工以投擲之方式運送物料？",
 ["不得，但設置滑槽、圍屏、警示線及專責監視人員者不在此限","可以，但應設置滑槽、圍屏及警示線，並於白天為之","可以，只要指派專責監視人員全時監視即無須設圍屏","不得，但重量在十公斤以下之輕型物料投擲者不在此限"],"a",
 "第28條：不得使勞工以投擲方式運送任何物料。但劃定滑槽承受區域、設置阻擋彈跳之圍屏並依第24條設警示線，且設專責監視人員全時監視者，不在此限；遇強風大雨應即停止。",
 "May workers throw materials to move them?",
 ["No, unless chutes, screens, warning lines and a full-time watcher are provided","Yes, provided chutes, screens and warning lines are used during daylight hours","Yes, if a full-time watcher is posted, so no screens or chutes are needed","No, unless the items thrown weigh 10 kg or less, which is always permitted"],
 "Article 28: throwing materials is prohibited unless a chute landing zone with screens, warning lines under Article 24 and a full-time watcher are in place; stop in strong wind or heavy rain."),

(L,"第35條",3,"營造-物料儲存",
 "磚、瓦、管料、鋼筋等營建材料之堆放高度不得超過多少公尺？鄰近開口時應距離開口多少公尺以上？",
 ["一點八公尺；二公尺","一點五公尺；一公尺","二公尺；三公尺","三公尺；二公尺"],"a",
 "第35條：磚、瓦、木塊、管料、鋼筋、鋼材等之堆放應置放於穩固平坦處，整齊緊靠堆置，高度不得超過一點八公尺，儲存位置鄰近開口部分時應距離該開口二公尺以上。",
 "Stacks of bricks, tiles, pipes or rebar shall not exceed what height, and shall be at least how far from openings?",
 ["1.8 m; 2 m","1.5 m; 1 m","2 m; 3 m","3 m; 2 m"],
 "Article 35: stacked neatly on firm level ground, not over 1.8 m high, and at least 2 m from any opening."),

(L,"第36條",3,"營造-物料儲存",
 "袋裝材料之儲存，堆放高度不得超過幾層？至少每幾層應交錯一次方向？",
 ["十層；二層","五層；一層","二十層；五層","十五層；三層"],"a",
 "第36條：堆放高度不得超過十層；至少每二層交錯一次方向；五層以上部分應向內退縮以維持穩定。",
 "Bagged materials may be stacked no higher than how many layers, and direction alternated at least every how many layers?",
 ["10 layers; every 2 layers","5 layers; every 1 layer","20 layers; every 5 layers","15 layers; every 3 layers"],
 "Article 36: not over 10 layers; alternate direction at least every 2 layers; layers above the fifth stepped inward."),

(L,"第40條",3,"營造-施工架",
 "高度七公尺以上且立面面積達多少平方公尺之施工架，其構築及拆除應由專任工程人員或執業技師依結構力學設計並簽章？",
 ["三百三十平方公尺","一百五十平方公尺","五百五十平方公尺","二百二十平方公尺"],"a",
 "第40條：施工構臺、懸吊式施工架、懸臂式施工架、高度七公尺以上且立面面積達三百三十平方公尺之施工架、高度七公尺以上之吊料平臺等，應由專任工程人員或委由執業技師依結構力學原理設計，置備施工圖說及強度計算書並簽章。",
 "Scaffolds 7 m or higher with a facade area of at least how much require design and signature by a full-time engineer or licensed professional?",
 ["330 m²","150 m²","550 m²","220 m²"],
 "Article 40: work platforms, suspended and cantilever scaffolds, scaffolds ≥7 m high with facade area ≥330 m², and material platforms ≥7 m require structural design, drawings and calculations signed by a full-time engineer or licensed professional."),

(L,"第41條",2,"營造-施工架",
 "高度幾公尺以上施工架之組配及拆除作業，應指派施工架組配作業主管於現場辦理？",
 ["三公尺","五公尺","七公尺","十公尺"],"b",
 "第41條：懸吊式施工架、懸臂式施工架及高度五公尺以上施工架之組配及拆除作業，應指派施工架組配作業主管於作業現場決定作業方法、實施檢點、監督使用防護具、確認設備有效狀況等。",
 "A scaffold assembly supervisor must be present on site for assembling or dismantling scaffolds of at least what height?",
 ["3 m","5 m","7 m","10 m"],
 "Article 41: suspended, cantilever and scaffolds 5 m or higher require a scaffold assembly supervisor on site to decide methods, inspect, supervise PPE use and confirm safety equipment."),

(L,"第42條",2,"營造-施工架",
 "施工架組配作業於紮緊、拆卸及傳遞構材時，應設寬度多少公分以上之施工架踏板？",
 ["二十公分","三十公分","四十公分","五十公分"],"a",
 "第42條第4款：於紮緊、拆卸及傳遞施工架構材等之作業時，設寬度在二十公分以上之施工架踏板，並採取使勞工使用安全帶等防止墜落之設備與措施；惡劣天候應即停止作業。",
 "During scaffold assembly (tying, dismantling, passing members), planks of at least what width are required?",
 ["20 cm","30 cm","40 cm","50 cm"],
 "Article 42(4): planks at least 20 cm wide plus fall protection such as harnesses; stop work in severe weather."),

(L,"第43條",3,"營造-施工架",
 "構築施工架使用之竹材，應以竹尾末梢外徑多少公分以上之圓竹為限？",
 ["二公分","三公分","四公分","六公分"],"c",
 "第43條：竹材應以竹尾末梢外徑四公分以上之圓竹為限，不得有裂隙或腐蝕；木材不得有顯著損及強度之裂隙等並應剝除樹皮，不得油漆隱蔽缺陷；鋼材應符合CNS 4750同等以上抗拉強度。",
 "Bamboo used for scaffolding must have a tip outer diameter of at least:",
 ["2 cm","3 cm","4 cm","6 cm"],
 "Article 43: round bamboo with tip diameter of at least 4 cm, free of cracks or rot; timber must be debarked without strength-reducing defects and not painted to hide flaws; steel per CNS 4750."),

(L,"第45條",3,"營造-施工架",
 "施工架與構造物之連接，其間隔在垂直方向及水平方向分別以不超過多少公尺為限？",
 ["垂直五點五公尺、水平七點五公尺","垂直三點五公尺、水平五點五公尺","垂直九點五公尺、水平八點五公尺","垂直二點五公尺、水平三點五公尺"],"a",
 "第45條第3款：施工架在適當之垂直、水平距離處與構造物妥實連接，其間隔在垂直方向以不超過五點五公尺，水平方向以不超過七點五公尺為限。施工架不得與模板支撐連接；獨立施工架拆除前至少三分之一踏腳桁不得移動。",
 "Scaffold ties to the structure shall be spaced no more than how far vertically and horizontally?",
 ["5.5 m vertically, 7.5 m horizontally","3.5 m vertically, 5.5 m horizontally","9.5 m vertically, 8.5 m horizontally","2.5 m vertically, 3.5 m horizontally"],
 "Article 45(3): ties at intervals not exceeding 5.5 m vertically and 7.5 m horizontally; scaffolds must not connect to formwork supports; at least one third of ledgers stay until final dismantling."),

(L,"第47條",1,"營造-施工架",
 "雇主得否使勞工在施工架上使用梯子、合梯或踏凳從事作業？",
 ["不得","可以","僅限合梯","僅限踏凳"],"a",
 "第47條：雇主不得使勞工在施工架上使用梯子、合梯或踏凳等從事作業。",
 "May workers use ladders, stepladders or stools on scaffolds?",
 ["Not permitted","Permitted","Only stepladders","Only stools"],
 "Article 47: workers must not use ladders, stepladders or stools to work on scaffolds."),

(L,"第48條",3,"營造-施工架",
 "高度二公尺以上施工架之工作臺寬度應在多少公分以上？踏板間縫隙不得大於多少公分？",
 ["四十公分；三公分","三十公分；五公分","五十公分；二公分","六十公分；一公分"],"a",
 "第48條：工作臺寬度應在四十公分以上並舖滿密接之踏板，支撐點二處以上並綁結固定，踏板間縫隙不得大於三公分；工作臺應低於施工架立柱頂點一公尺以上。",
 "Work platforms on scaffolds 2 m or higher shall be at least how wide, with plank gaps not exceeding:",
 ["40 cm; 3 cm","30 cm; 5 cm","50 cm; 2 cm","60 cm; 1 cm"],
 "Article 48: at least 40 cm wide, fully planked with at least two supports and tied down, gaps not over 3 cm; the platform shall be at least 1 m below the top of the standards."),

(L,"第48條",3,"營造-施工架",
 "活動式踏板使用木板時，寬度應在多少公分以上、厚度多少公分以上、長度多少公尺以上？",
 ["寬二十公分、厚三點五公分、長三點六公尺","寬三十公分、厚二點五公分、長二公尺","寬十五公分、厚五公分、長四點五公尺","寬四十公分、厚六點五公分、長五公尺"],"a",
 "第48條第3款：活動式踏板使用木板時，寬度二十公分以上、厚度三點五公分以上、長度三點六公尺以上；寬度大於三十公分時厚度六公分以上、長度四公尺以上；板端突出支撐點十公分以上但不大於板長十八分之一；重疊部分不得小於二十公分。",
 "Loose wooden scaffold planks shall be at least how wide, thick and long?",
 ["20 cm wide, 3.5 cm thick, 3.6 m long","30 cm wide, 2.5 cm thick, 2 m long","15 cm wide, 5 cm thick, 4.5 m long","40 cm wide, 6.5 cm thick, 5 m long"],
 "Article 48(3): at least 20 cm × 3.5 cm × 3.6 m (if wider than 30 cm: 6 cm thick and 4 m long); overhang 10 cm or more but not over 1/18 of length; overlaps at least 20 cm."),

(L,"第51條",2,"營造-施工架",
 "施工架任一處步行至最近上下設備之距離，應在多少公尺以下？",
 ["十公尺","二十公尺","三十公尺","五十公尺"],"c",
 "第51條：於施工架上設置人員上下設備時，應檢查穩固性並將上下設備架設處之立柱與建築物牢固連接；施工架任一處步行至最近上下設備之距離應在三十公尺以下。",
 "From any point on a scaffold, the walking distance to the nearest access (ladder/stair) shall not exceed:",
 ["10 m","20 m","30 m","50 m"],
 "Article 51: the standards at access points shall be tied to the building; walking distance from any point to the nearest access shall be 30 m or less."),

(L,"第56條",3,"營造-施工架",
 "懸吊式施工架之吊纜或懸吊鋼索安全係數應在多少以上？吊鈎安全係數應在多少以上？",
 ["十；五","五；三","六；四","十五；十"],"a",
 "第56條第3款：吊纜或懸吊鋼索之安全係數應在十以上，吊鈎之安全係數應在五以上，施工架下方及上方支座之安全係數，鋼材二點五以上、木材五以上。每一橫梁應有三處以上懸吊點。",
 "For suspended scaffolds, the safety factor of suspension ropes and of hooks shall be at least:",
 ["10; 5","5; 3","6; 4","15; 10"],
 "Article 56(3): suspension ropes at least 10, hooks at least 5, supports 2.5 for steel and 5 for timber; each beam needs three or more suspension points."),

(L,"第57條",2,"營造-施工架",
 "棧橋式施工架，下列規定何者正確？",
 ["不能構築兩層以上，構築高度不得高出地面四公尺以上","得構築三層以上，構築高度不得高出地面六公尺以上","構築層數不受限制，構築高度亦不受地面高度之限制","得建於輕型懸吊式施工架之上，且構築高度不受限制"],"a",
 "第57條：棧橋式施工架寬度應使工作臺留有足夠運送物料及人員通行空間；架設牢固；不能構築兩層以上；構築高度不得高出地面或地板四公尺以上；不得建於輕型懸吊式施工架之上。",
 "Which is correct for trestle (bridge-type) scaffolds?",
 ["No more than one tier and not higher than 4 m above the floor","Three or more tiers allowed and not higher than 6 m above the floor","Any number of tiers, with no limit on height above the floor level","May be built on light suspended scaffolds with no height limit"],
 "Article 57: wide enough for materials and passage, firmly erected, not more than one tier, not over 4 m above floor level, and not built on light suspended scaffolds."),

(L,"第59條",3,"營造-施工架",
 "鋼管施工架之壁連座間距，單管施工架垂直方向及水平方向分別為多少公尺以下？",
 ["垂直五公尺、水平五點五公尺","垂直九公尺、水平八公尺","垂直三公尺、水平四點五公尺","垂直七公尺、水平六點五公尺"],"a",
 "第59條第5款表：單管施工架垂直五公尺、水平五點五公尺；框式施工架（高度未滿五公尺者除外）垂直九公尺、水平八公尺。移動式施工架勞工作業時腳部應固定，不得移動施工架。",
 "For tube-and-coupler (single-pipe) steel scaffolds, wall ties shall be spaced at most how far vertically and horizontally?",
 ["5 m vertically, 5.5 m horizontally","9 m vertically, 8 m horizontally","3 m vertically, 4.5 m horizontally","7 m vertically, 6.5 m horizontally"],
 "Article 59(5) table: single-pipe scaffolds 5 m vertical / 5.5 m horizontal; frame scaffolds (except under 5 m high) 9 m / 8 m. Mobile scaffolds must have wheels locked and not be moved with workers on them."),

(L,"第60條",3,"營造-施工架",
 "單管式鋼管施工架之立柱間距，縱向及梁間方向分別應在多少公尺以下？立柱載重以多少公斤為限？",
 ["縱向一點八五公尺、梁間一點五公尺；四百公斤","縱向二公尺、梁間二公尺；五百公斤","縱向一點五公尺、梁間一公尺；三百公斤","縱向三公尺、梁間二公尺；六百公斤"],"a",
 "第60條：立柱之間距縱向為一點八五公尺以下，梁間方向為一點五公尺以下；橫檔垂直間距不得大於二公尺；立柱上端量起三十一公尺以下部分應使用二根鋼管；立柱之載重應以四百公斤為限。",
 "For single-pipe steel scaffolds, standards shall be spaced at most how far longitudinally and transversely, and the load per standard limited to:",
 ["1.85 m and 1.5 m; 400 kg","2 m and 2 m; 500 kg","1.5 m and 1 m; 300 kg","3 m and 2 m; 600 kg"],
 "Article 60: standards at most 1.85 m longitudinally and 1.5 m transversely; ledgers not more than 2 m apart vertically; double standards for the top 31 m; load per standard limited to 400 kg."),

(L,"第61條",3,"營造-施工架",
 "框式鋼管式施工架，應於最上層及每隔幾層設置水平梁？高度超過二十公尺者主框架應在多少公尺以下？",
 ["每隔五層；二公尺以下","每隔三層；三公尺以下","每隔十層；一點五公尺以下","每隔二層；二點五公尺以下"],"a",
 "第61條：最上層及每隔五層應設置水平梁；框架與托架應以水平牽條或鉤件防止水平滑動；高度超過二十公尺及架上載有物料者，主框架應在二公尺以下且其間距應保持在一點八五公尺以下。",
 "Frame scaffolds shall have horizontal beams at the top and every how many tiers, and when over 20 m high the main frames shall be no taller than:",
 ["Every 5 tiers; 2 m","Every 3 tiers; 3 m","Every 10 tiers; 1.5 m","Every 2 tiers; 2.5 m"],
 "Article 61: horizontal beams at the top and every 5 tiers; when over 20 m or loaded with materials, main frames not over 2 m high and spaced 1.85 m or less."),

(L,"第62-2條",2,"營造-施工構臺",
 "施工構臺遭遇強風、大雨或幾級以上地震後，使勞工作業前應確認主要構材狀況？",
 ["三級","四級","五級","六級"],"b",
 "第62條之2：施工構臺遭遇強風、大雨等惡劣氣候或四級以上地震後，或局部解體、變更後，作業前應確認支柱滑動下沉、構材損傷、覆工板狀況、連結部分鬆動、護欄等，異常未改善前不得作業。",
 "After strong wind, heavy rain or an earthquake of what intensity or greater must a work platform's main members be checked before work resumes?",
 ["Intensity 3","Intensity 4","Intensity 5","Intensity 6"],
 "Article 62-2: after severe weather, an intensity-4 or stronger earthquake, or partial dismantling/modification, check for settlement, damage, deck condition, loose connections and guardrails before work."),

(L,"第64條",3,"營造-露天開挖",
 "以人工開挖露天開挖作業，砂質土壤地層之開挖面傾斜度不得大於水平與垂直多少之比？開挖面高度不超過多少公尺？",
 ["一．五比一（三十五度）；五公尺","一比一（四十五度）；二公尺","二比一；三公尺","一比二；十公尺"],"a",
 "第64條：砂質土壤開挖面傾斜度不得大於水平一．五與垂直一之比（三十五度），高度不超過五公尺；因爆破易崩壞之地層不得大於一比一（四十五度），高度不超過二公尺；岩磐未滿五公尺九十度以下、五公尺以上七十五度以下。",
 "For manual open excavation in sandy soil, the slope shall not exceed what horizontal-to-vertical ratio, and the face height not exceed:",
 ["1.5:1 (35°); 5 m","1:1 (45°); 2 m","2:1; 3 m","1:2; 10 m"],
 "Article 64: sandy soil 1.5H:1V (35°) up to 5 m; blast-loosened strata 1:1 (45°) up to 2 m; rock under 5 m up to 90°, 5 m or more up to 75°."),

(L,"第65條",2,"營造-露天開挖",
 "露天開挖作業，作業前、大雨或幾級以上地震後，應指定專人確認地面有無龜裂、湧水等情形？",
 ["三級","四級","五級","六級"],"b",
 "第65條第1款：作業前、大雨或四級以上地震後，應指定專人確認作業地點及其附近之地面有無龜裂、湧水、土壤含水狀況、地層變化等，並採取必要安全措施；開挖土石不得堆積於開挖面上方或坡肩寬度範圍內。",
 "Before open excavation work, and after heavy rain or an earthquake of what intensity, must a designated person check the ground for cracks and seepage?",
 ["Intensity 3","Intensity 4","Intensity 5","Intensity 6"],
 "Article 65(1): before work and after heavy rain or an intensity-4 or stronger earthquake; excavated soil must not be piled above the face or within a shoulder width equal to the face height."),

(L,"第66條",2,"營造-露天開挖",
 "露天開挖作業，開挖垂直深度達多少公尺以上者，應指定露天開挖作業主管？",
 ["二點五公尺","一點五公尺","三點五公尺","四點五公尺"],"b",
 "第66條：為防止土石崩塌應指定專人於現場辦理；開挖垂直深度達一點五公尺以上者，應指定露天開挖作業主管，決定作業方法、實施檢點、監督防護具使用、確認設備有效狀況等。",
 "An open-excavation work supervisor must be designated when the vertical depth reaches at least:",
 ["2.5 m","1.5 m","3.5 m","4.5 m"],
 "Article 66: a designated person is required; at vertical depth of 1.5 m or more, an open-excavation work supervisor must direct methods, inspect, supervise PPE and confirm safety equipment."),

(L,"第69條",2,"營造-露天開挖",
 "以機械從事露天開挖作業，車輛機械應裝設何種裝置以警示周遭人員？",
 ["倒車或旋轉之警示燈及蜂鳴器","駕駛室內之空調及通風設備","車內無線電對講機及收音機","衛星定位系統及行車紀錄器"],"a",
 "第69條：應規劃施工方法避免損壞地下埋設物；事前決定運行路線並告知勞工；指派專人指揮防止翻覆；嚴禁操作人員以外之勞工進入操作半徑；車輛機械應裝設倒車或旋轉之警示燈及蜂鳴器。",
 "Machinery used for open excavation shall be fitted with what to warn nearby workers?",
 ["Reversing/rotation warning lights and buzzers","Air conditioning and ventilation in the cab","Two-way radios and a radio receiver in the cab","Satellite positioning and journey recorders"],
 "Article 69: plan methods to avoid damaging utilities, set routes and inform workers, assign a director, bar others from the operating radius, and fit reversing/rotation warning lights and buzzers."),

(L,"第71條",2,"營造-露天開挖",
 "露天開挖深度在多少公尺以上，使勞工進入開挖面作業者，應設擋土支撐？",
 ["○點八公尺","一點五公尺","二點五公尺","三點五公尺"],"b",
 "第71條：開挖深度在一點五公尺以上，使勞工進入開挖面作業者，應設擋土支撐。但地質特殊或採取替代方法，經專任工程人員或執業技師簽認其安全性者，不在此限。",
 "Shoring is required when workers enter an open excavation of at least what depth?",
 ["0.8 m","1.5 m","2.5 m","3.5 m"],
 "Article 71: at 1.5 m or deeper, shoring is required, unless special geology or an alternative method is certified safe by a full-time engineer or licensed professional."),

(L,"第73條",3,"營造-擋土支撐",
 "擋土支撐之構築，壓力構材之接頭應採何種方式？",
 ["對接，並加設護材","搭接，並以鐵線綁紮","斜接，並以夾板固定","重疊搭接，不需護材"],"a",
 "第73條第5款：壓力構材之接頭應採對接，並應加設護材；支撐接頭應墊承鈑並以螺栓或焊接固定；不得以支撐及橫檔作為施工架或承載重物；擋土支撐應由專任工程人員或執業技師依土壤力學設計簽章。",
 "In shoring construction, joints of compression members shall be:",
 ["Butt-jointed with protective members added","Lap-jointed and bound with steel wire ties","Scarf-jointed and fixed with splice plates","Simply overlapped, with no protective members"],
 "Article 73(5): butt joints with added protective members; joints seated on bearing plates and bolted or welded; struts and wales must not serve as scaffolds or carry loads; design by a full-time engineer or licensed professional."),

(L,"第75條",2,"營造-擋土支撐",
 "擋土支撐設置後開挖進行中，除指定專人確認地層變化外，應每隔多久或於何種情況後實施檢查？",
 ["每週或四級以上地震後","每日或三級以上地震後","每月或五級以上地震後","每季或六級以上地震後"],"a",
 "第75條：於每週或於四級以上地震後，或因大雨等致地層有急劇變化之虞，或觀測系統顯示土壓變化未按預期時，檢查構材損傷變形、支撐桿鬆緊、連接部分狀況；有異狀應即補強。",
 "After shoring is installed, inspections are required at what interval or after what event?",
 ["Weekly or after an intensity-4 or stronger earthquake","Daily or after an intensity-3 or stronger earthquake","Monthly or after an intensity-5 or stronger earthquake","Quarterly or after an intensity-6 or stronger earthquake"],
 "Article 75: weekly, after an intensity-4+ earthquake, after heavy rain likely to change strata, or when monitoring shows unexpected earth pressure; check for damage, strut tightness and connections."),

(L,"第79條",2,"營造-露天開挖",
 "傾斜地面上之開挖作業，二人以上同時作業時應如何？",
 ["切實保持連繫，並指派其中一人擔任領班指揮作業","各自獨立作業即可，無須保持連繫或指派領班指揮","應指派其中年資最淺者擔任領班，負責指揮全部作業","由監造單位人員在場指揮，勞工間不必相互保持連繫"],"a",
 "第79條：不得使勞工同時在不同高度之地點從事作業（已採保護措施者除外）；隨時清除開挖面土石方；二人以上同時作業應切實保持連繫並指派其中一人擔任領班指揮；有墜落之虞應使用安全帶。",
 "When two or more workers excavate on sloping ground at the same time, they shall:",
 ["Keep in close contact, with one designated as foreman to direct the work","Work independently, with no contact and no designated foreman needed","Designate the most junior worker as foreman to direct all the work","Let the supervising firm direct on site, with no contact among workers"],
 "Article 79: no simultaneous work at different heights without protection; clear loose material continuously; two or more workers must maintain contact with one designated foreman; use harnesses where fall risk exists."),

(L,"第80條",2,"營造-隧道",
 "隧道、坑道開挖作業，雇主應於勞工進出隧道、坑道時如何辦理？",
 ["予以清點或登記","不需管制","僅記錄進入時間","由承攬商自行處理"],"a",
 "第80條：事前實施地質調查並繪出詳圖；依調查結果訂定施工計畫（開挖方法、支撐、換氣、照明、搬運、通訊、防火、湧水處理等）；雇主應於勞工進出隧道、坑道時予以清點或登記。",
 "For tunnel excavation, what must the employer do when workers enter and exit the tunnel?",
 ["Count or register them","No control needed","Only record entry time","Leave it to the contractor"],
 "Article 80: geological survey with detailed drawings; a construction plan covering excavation method, support, ventilation, lighting, transport, communication, fire and water inflow; workers counted or registered on entry and exit."),

(L,"第87條",2,"營造-隧道",
 "隧道、坑道作業之勞工應佩戴安全帽並穿著何種服裝？",
 ["反光背心或具反光標示之服裝","深色系之棉質長袖工作服裝","個人自備之便服或輕便雨衣","白色實驗衣及防塵口罩即可"],"a",
 "第87條：應使作業勞工佩戴安全帽、穿著反光背心或具反光標示之服裝及其他必要防護具，並置備緊急搶救器材、吊升搶救設施、安全燈、呼吸防護器材、氣體檢知警報系統、通訊信號及備用電源。",
 "Tunnel workers shall wear helmets and what clothing?",
 ["Reflective vests or clothing with reflective markings","Dark-coloured long-sleeved cotton work clothing","Personal casual clothes or a light rain cape","White laboratory coats with dust masks only"],
 "Article 87: helmets, reflective vests or clothing, other PPE; plus emergency rescue equipment, hoisting rescue facilities, safety lamps, respiratory protection, gas detection alarms, communication signals and backup power."),

(L,"第93條",3,"營造-隧道",
 "隧道、坑道之鋼拱支撐，支撐組之間隔應在多少公尺以下？",
 ["○點五公尺","一點五公尺","二點五公尺","四點五公尺"],"b",
 "第93條：鋼拱支撐組之間隔應在一．五公尺以下（以噴凝土或岩栓支撐岩體荷重者除外）；使用連接螺栓、連接桿或斜撐將主構材連接；防止縱向傾倒；設襯板防止土石崩塌。",
 "Steel arch supports in tunnels shall be spaced no more than:",
 ["0.5 m","1.5 m","2.5 m","4.5 m"],
 "Article 93: steel arch sets spaced 1.5 m or less (except where shotcrete or rock bolts carry the load), connected with bolts, rods or braces, braced against longitudinal tipping, with lagging against collapse."),

(L,"第98條",3,"營造-隧道",
 "隧道、坑道開挖作業，豎坑深度超過多少公尺者，應設專供人員緊急出坑之安全吊升設備？",
 ["十公尺","十五公尺","二十公尺","三十公尺"],"c",
 "第98條：豎坑深度超過二十公尺者，應設專供人員緊急出坑之安全吊升設備。第99條：應於每五百公尺設置與外界隨時保持正常通訊之有線通訊設備。",
 "For tunnel work, a dedicated emergency hoist for evacuating personnel is required when a shaft is deeper than:",
 ["10 m","15 m","20 m","30 m"],
 "Article 98: shafts deeper than 20 m need a dedicated safe emergency hoist; Article 99 requires wired communication with the outside every 500 m."),

(L,"第101條",3,"營造-隧道",
 "以潛盾工法施工之隧道開挖作業，下列何者正確？",
 ["柴油引擎以外之內燃機不得在隧道內使用","勞工得未經許可攜帶火柴或打火機進入隧道內","隧道內得自由進行氣體熔接、熔斷及電焊作業","汽油及液化石油氣引擎均得在隧道內使用"],"a",
 "第101條：未經許可禁止在隧道內進行氣體熔接、熔斷或電焊；未經許可禁止攜帶火柴、打火機等火源進入；柴油引擎以外之內燃機不得在隧道內使用。",
 "For shield-tunneling work, which is correct?",
 ["Internal combustion engines other than diesel must not be used in the tunnel","Matches and lighters may be carried into the tunnel without permission","Gas welding, cutting and arc welding may be done freely in the tunnel","Petrol and liquefied petroleum gas engines may be used in the tunnel"],
 "Article 101: no gas welding/cutting or arc welding without permission; no matches, lighters or other ignition sources without permission; no internal combustion engines other than diesel."),

(L,"第103條",3,"營造-沉箱",
 "沉箱、沉筒、井筒內部開挖作業，刃口至頂版或梁底之淨距應在多少公尺以上？刃口下端不得下挖多少公分以上？",
 ["一點八公尺；五十公分","一點五公尺；三十公分","二公尺；一公尺","一公尺；二十公分"],"a",
 "第103條：依下沉關係圖決定開挖方法及載重量；刃口至頂版或梁底之淨距應在一點八公尺以上；刃口下端不得下挖五十公分以上。第104條：開挖深度超過二十公尺應設通信系統及換氣裝置。",
 "Inside caissons or open-well shafts, the clear distance from the cutting edge to the roof slab shall be at least, and digging below the cutting edge shall not exceed:",
 ["1.8 m; 50 cm","1.5 m; 30 cm","2 m; 1 m","1 m; 20 cm"],
 "Article 103: at least 1.8 m clear from cutting edge to slab or beam soffit; no digging more than 50 cm below the cutting edge; Article 104: over 20 m deep requires communication and ventilation."),

(L,"第106條",2,"營造-壓氣施工",
 "藉壓氣沉箱、壓氣潛盾等施工法作業時，應選任何種主管？",
 ["高壓室內作業主管","露天開挖作業主管","模板支撐作業主管","屋頂作業主管"],"a",
 "第106條：應選任高壓室內作業主管，告知可燃物在高氣壓下之危險性、禁止攜帶火源、禁止氣體熔接電焊、禁止可能產生火花之機械與電源開關、規定穿著不易引起靜電之服裝、離開時依異常氣壓危害預防標準辦理。",
 "For compressed-air caisson or shield work, which supervisor must be appointed?",
 ["A hyperbaric chamber work supervisor","An open-excavation supervisor","A formwork support supervisor","A roof work supervisor"],
 "Article 106: a hyperbaric (compressed-air) work supervisor who informs workers of fire risk under pressure, bans ignition sources, welding, spark-producing tools and switches, requires anti-static clothing, and applies decompression rules."),

(L,"第110條",2,"營造-基樁",
 "基樁等施工設備之捲揚鋼纜，下列何種情形不得使用？",
 ["有接頭者","長度超過五十公尺者","新品未使用者","顏色不同者"],"a",
 "第110條：有接頭者、鋼纜一撚間有百分之十以上素線截斷者、直徑減少達公稱直徑百分之七以上者、已扭結者、有顯著變形或腐蝕者，不得使用。第111條：捲胴上至少保留二卷以上。",
 "Which hoisting wire rope on piling equipment must NOT be used?",
 ["One with a splice/joint","One longer than 50 m","A new unused one","One of a different color"],
 "Article 110: ropes with joints, 10% or more broken wires in one lay, diameter reduced 7% or more, kinks, or significant deformation/corrosion are prohibited; Article 111: keep at least two wraps on the drum."),

(L,"第115條",3,"營造-基樁",
 "基樁等施工設備捲揚裝置之捲胴軸與頭一個環槽滑輪軸間之距離，應保持在捲胴寬度多少倍以上？",
 ["五倍","十倍","十五倍","二十倍"],"c",
 "第115條：應將捲揚裝置之捲胴軸與頭一個環槽滑輪軸間之距離，保持在捲揚裝置之捲胴寬度十五倍以上；環槽滑輪應通過捲胴中心且置於軸之垂直面上。",
 "On piling equipment, the distance between the winch drum axis and the first sheave axis shall be at least how many times the drum width?",
 ["5","10","15","20"],
 "Article 115: at least 15 times the drum width, with the sheave passing through the drum center in the vertical plane of the axis."),

(L,"第123條",2,"營造-基樁",
 "基樁等施工設備之作業，應訂定一定信號並如何辦理？",
 ["指派專人於作業時從事傳達信號工作","由操作人員依現場狀況自行判斷作業時機","以行動電話通話替代信號傳達之人員配置","作業前公告信號內容即可，免設傳達人員"],"a",
 "第123條：應訂定一定信號，並指派專人於作業時從事傳達信號工作；操作者應遵從該信號。第124條：裝配、解體、變更或移動作業應指派專人依安全作業標準指揮。",
 "For piling equipment operations, fixed signals shall be established and:",
 ["A designated person assigned to relay signals during work","The operator decides the timing alone from site conditions","Mobile phone calls used instead of a signal relay person","Posting the signal code before work, with no relay person"],
 "Article 123: fixed signals with a designated signal person whom the operator must obey; Article 124: assembly, dismantling, modification or moving requires a designated person directing per safe work standards."),

(L,"第129條",2,"營造-鋼筋混凝土",
 "吊運長度超過多少公尺之鋼筋時，應在適當距離之二端以吊鏈鈎住或拉索捆紮拉緊？",
 ["三公尺","五公尺","八公尺","十公尺"],"b",
 "第129條第5款：吊運長度超過五公尺之鋼筋時，應在適當距離之二端以吊鏈鈎住或拉索捆紮拉緊，保持平穩以防擺動；搬運鋼筋應戴手套；鋼筋不得散放於施工架上；禁止以鋼筋作為拉索支持物或工作架。",
 "When hoisting rebar longer than what must both ends be hooked or tied with tag lines to prevent swinging?",
 ["3 m","5 m","8 m","10 m"],
 "Article 129(5): rebar over 5 m long must be hooked or tied at both ends; wear gloves when handling; do not scatter rebar on scaffolds; do not use rebar as guy supports or work frames."),

(L,"第131條",3,"營造-模板支撐",
 "高度在七公尺以上且面積達多少平方公尺以上之模板支撐，其構築及拆除應由專任工程人員或執業技師依結構力學設計並簽章？",
 ["一百六十平方公尺","二百四十平方公尺","三百三十平方公尺","四百五十平方公尺"],"c",
 "第131條第1款：高度在七公尺以上且面積達三百三十平方公尺以上之模板支撐，應由專任工程人員或委由執業技師依結構力學原理設計，置備施工圖說及強度計算書並簽章；訂定混凝土澆置計畫及查驗機制。",
 "Formwork supports 7 m or higher with an area of at least how much require structural design signed by a full-time engineer or licensed professional?",
 ["160 m²","240 m²","330 m²","450 m²"],
 "Article 131(1): 7 m or higher and 330 m² or more require design, drawings and calculations signed by a full-time engineer or licensed professional, plus a pouring plan and verification mechanism."),

(L,"第133條",2,"營造-模板支撐",
 "模板支撐組配、拆除作業，應指派何種主管於作業現場辦理？",
 ["模板支撐作業主管","施工架組配作業主管","擋土支撐作業主管","鋼構組配作業主管"],"a",
 "第133條：模板支撐組配、拆除作業應指派模板支撐作業主管於作業現場決定作業方法、實施檢點、監督防護具使用、確認設備有效狀況、管制人員進入。",
 "Assembly and dismantling of formwork supports requires which supervisor on site?",
 ["A formwork support work supervisor","A scaffold assembly supervisor","A shoring supervisor","A steel erection supervisor"],
 "Article 133: a formwork support work supervisor to decide methods, inspect, supervise PPE, confirm safety equipment and control entry."),

(L,"第135條",3,"營造-模板支撐",
 "以可調鋼管支柱為模板支撐之支柱時，下列何者正確？",
 ["可調鋼管支柱不得連接使用；高度超過三點五公尺者每隔二公尺內設水平繫條","可調鋼管支柱得連接使用以增加高度；連接處以鋼筋插銷固定即可","調整高度得以鋼筋替代制式插銷；高度超過五公尺者始需設水平繫條","可調鋼管支柱高度在七公尺以下者；均免設縱向及橫向水平繫條"],"a",
 "第135條：可調鋼管支柱不得連接使用；高度超過三點五公尺者，每隔二公尺內設置縱向、橫向水平繫條並與構造物連結；調整高度應以制式金屬附屬配件為之，不得以鋼筋等替代；上端支以貫材時應置鋼製頂板或托架。",
 "When adjustable steel pipe props are used as formwork supports, which is correct?",
 ["Props must not be joined end-to-end; over 3.5 m high, horizontal bracing every 2 m","Props may be joined end-to-end to gain height, fixed with rebar pins at the joint","Rebar may replace the standard adjustment pin; bracing only when over 5 m high","Props up to 7 m high need no longitudinal or transverse horizontal bracing"],
 "Article 135: no end-to-end joining; over 3.5 m, longitudinal and transverse horizontal ties within every 2 m connected to the structure; adjust only with standard metal fittings, never rebar; steel head plates under beams."),

(L,"第138條",3,"營造-模板支撐",
 "以木材為模板支撐之支柱時，每一支柱最多僅能有幾處接頭？每根支柱之淨高不得超過多少公尺？",
 ["一處；四公尺","二處；三公尺","三處；五公尺","不限；六公尺"],"a",
 "第138條：木材以連接方式使用時，每一支柱最多僅能有一處接頭，對接時應以二個以上牽引板固定；每根支柱之淨高不得超過四公尺；木材支柱最小斷面積應大於三十一點五平方公分；每二公尺內設水平繫條。",
 "Timber formwork props may have at most how many joints per prop, and a clear height not exceeding:",
 ["1 joint; 4 m","2; 3 m","3; 5 m","Unlimited; 6 m"],
 "Article 138: at most one joint per prop (butt joints fixed with two or more cleats); clear height not over 4 m; minimum section over 31.5 cm²; horizontal ties every 2 m."),

(L,"第142條",3,"營造-鋼筋混凝土",
 "混凝土澆置作業使用起重機具吊運混凝土桶時，其擺動夾角不得超過幾度？",
 ["二十度","三十度","四十度","六十度"],"c",
 "第142條第5款：混凝土桶之載重量不得超過容許限度，其擺動夾角不得超過四十度；禁止勞工乘坐於混凝土澆置桶上及位於輸送管下方作業；吊運桶下方禁止人員進入。",
 "When hoisting concrete buckets with a crane, the swing angle shall not exceed:",
 ["20°","30°","40°","60°"],
 "Article 142(5): swing angle not over 40°; no riding on buckets or working under delivery pipes; no one beneath hoisted buckets."),

(L,"第148條",3,"營造-鋼構",
 "鋼構吊運長度超過多少公尺之構架時，應在二端以拉索捆紮拉緊？使用多少公尺以上長跨度格柵梁時應安裝臨時構件？",
 ["六公尺；十二公尺","五公尺；十公尺","八公尺；十五公尺","三公尺；六公尺"],"a",
 "第148條：吊運長度超過六公尺之構架應在適當距離之二端以拉索捆紮拉緊；鋼梁於最後安裝吊索鬆放前，二端腹鈑接頭應有二個以上螺栓裝妥；使用十二公尺以上長跨度格柵梁或桁架時於鬆放吊索前應安裝臨時構件。",
 "Steel members longer than what require tag lines at both ends when hoisted, and long-span joists of what length require temporary members before releasing the hoist?",
 ["6 m; 12 m","5 m; 10 m","8 m; 15 m","3 m; 6 m"],
 "Article 148: members over 6 m need tag lines at both ends; beams need at least two bolts at each web connection before releasing; joists or trusses 12 m or longer need temporary bracing before releasing the hoist."),

(L,"第149條",3,"營造-鋼構",
 "營造標準第149條所定應指派鋼構組配作業主管之「鋼構」，其範圍包括高度在多少公尺以上之鋼構建築物？橋梁跨距多少公尺以上之金屬橋梁上部結構？",
 ["五公尺；三十公尺","三公尺；二十公尺","十公尺；五十公尺","七公尺；二十五公尺"],"a",
 "第149條：鋼構範圍包括高度五公尺以上之鋼構建築物、高度五公尺以上之鐵塔或金屬煙囪、高度五公尺以上或跨距三十公尺以上之金屬橋梁上部結構、塔式起重機、人字臂起重桿、室外升降機升降路塔、金屬施工構臺。",
 "The 'steel structures' requiring a steel erection supervisor under Article 149 include steel buildings of at least what height, and metal bridge superstructures of at least what span?",
 ["5 m; 30 m","3 m; 20 m","10 m; 50 m","7 m; 25 m"],
 "Article 149: steel buildings ≥5 m, towers or chimneys ≥5 m, metal bridge superstructures ≥5 m high or ≥30 m span, tower cranes, derricks, exterior hoist towers and metal work platforms."),

(L,"第150條",3,"營造-鋼構",
 "鋼構組配進行組合時，於最高永久性樓板上組合之骨架，不得超過幾層？",
 ["四層","六層","八層","十層"],"c",
 "第150條：應逐次構築永久性之樓板，於最高永久性樓板上組合之骨架不得超過八層（設計已考慮整體安全性者除外）。第152條：地面或最高永久性樓板層上不得有超過四層樓以上之鋼構尚未鉚接、熔接或螺栓緊者。",
 "During steel erection, the frame assembled above the highest permanent floor shall not exceed how many stories?",
 ["4","6","8","10"],
 "Article 150: not more than 8 stories above the highest permanent floor (unless overall stability is designed for); Article 152: no more than 4 stories of steel may remain unriveted, unwelded or unbolted."),

(L,"第151條",3,"營造-鋼構",
 "不適於舖設臨時性構臺之鋼構建築，未使用施工架而落距差超過幾層樓或多少公尺以上者，應張設安全網？",
 ["二層樓或七點五公尺","一層樓或三公尺","三層樓或十公尺","四層樓或十五公尺"],"a",
 "第151條第2款：落距差超過二層樓或七點五公尺以上者應張設安全網，其下方應有足夠淨空；安全網使用前須確認已實施耐衝擊試驗。第3款：鋼梁正下方二層樓或七點五公尺高度內應安裝密實舖板。",
 "For steel buildings without temporary decks or scaffolds, safety nets are required when the potential fall exceeds:",
 ["2 stories or 7.5 m","1 story or 3 m","3 stories or 10 m","4 stories or 15 m"],
 "Article 151(2): nets when the fall distance exceeds 2 stories or 7.5 m, with adequate clearance below and impact testing verified; item 3: solid decking within 2 stories or 7.5 m below beams being worked on."),

(L,"第155條",2,"營造-拆除",
 "拆除構造物前，下列何者為應辦理事項？",
 ["切斷電源並拆除配電設備及線路；切斷可燃性氣體管、蒸汽管或水管","保持電源供電以便使用電動工具；可燃性氣體管於拆除後再行切斷","構件無須事前檢查即可拆除；不穩定部分於拆除中再視情況予以支撐","拆除區域無須設置圍柵或標示；鄰近通道人員保護設施得於拆除後補設"],"a",
 "第155條：檢查預定拆除之各構件；不穩定部分予以支撐；切斷電源並拆除配電設備及線路；切斷可燃性氣體管、蒸汽管或水管，殘存氣體應安全釋放；設置圍柵或標示禁止非作業人員進入；鄰近通道人員保護設施完成前不得拆除。",
 "Before demolishing a structure, which is required?",
 ["Cut off power and remove electrical equipment and wiring; cut off gas, steam and water pipes","Keep power on for power tools; cut off gas pipes only after demolition is finished","Members need no prior inspection; unstable parts are propped as the work proceeds","No fencing or signs are needed; passage protection may be added after demolition"],
 "Article 155: inspect members; support unstable parts; cut power and remove wiring; cut gas, steam and water lines and safely release residual gas; fence and post signs; protect adjacent passages first."),

(L,"第157條",2,"營造-拆除",
 "拆除構造物時，拆除順序應如何？",
 ["按序由上而下逐步拆除","按序由下而上逐層拆除","自中間樓層向上下同時拆除","得不依順序任意選擇拆除"],"a",
 "第157條：不得使勞工同時在不同高度拆除（有適當設施者除外）；應按序由上而下逐步拆除；拆除材料不得過度堆積或靠牆堆放；惡劣氣候應停止；有塵土飛揚應灑水；拉倒方式應使勞工退避。",
 "In what order shall a structure be demolished?",
 ["Progressively from top to bottom","Progressively from bottom to top","From the middle floor upward and downward at once","In any order chosen by the demolition crew"],
 "Article 157: no simultaneous work at different heights without protection; demolish top-down in sequence; do not over-stack or lean debris against walls; stop in severe weather; sprinkle water for dust; keep workers clear when pulling down."),

(L,"第159條",3,"營造-拆除",
 "使用重力錘拆除構造物時，應以撞擊點為中心，構造物高度幾倍以上之距離為半徑設置作業區？使用夾斗或曲臂機具時，作業區周圍應大於運行線多少公尺以上？",
 ["一點五倍；八公尺","一倍；五公尺","二倍；十公尺","三倍；十五公尺"],"a",
 "第159條：使用重力錘時應以撞擊點為中心、構造物高度一點五倍以上之距離為半徑設置作業區；使用夾斗或曲臂機具時，作業區周圍應大於夾斗或曲臂運行線八公尺以上；作業區內除操作人員外禁止進入。",
 "When demolishing with a wrecking ball, the work zone radius shall be at least how many times the structure height, and for grapples or articulated arms the zone shall extend beyond the travel line by at least:",
 ["1.5 times; 8 m","1 time; 5 m","2 times; 10 m","3 times; 15 m"],
 "Article 159: wrecking ball zone radius ≥1.5× the structure height centered on the impact point; grapple/articulated-arm zone ≥8 m beyond the travel line; only operators inside."),

(L,"第160條",3,"營造-拆除",
 "未能設置作業區時，於拆除構造物外牆邊緣設置之承受臺，其寬度應在多少公尺以上？應能承受每平方公尺多少公斤以上之活載重？",
 ["一點五公尺；六百公斤","一公尺；三百公斤","二公尺；一千公斤","○．八公尺；五百公斤"],"a",
 "第160條：承受臺寬應在一點五公尺以上；臺面應由外向內傾斜且密舖板料；應能承受每平方公尺六百公斤以上之活載重；臺面距拆除層位之高度不超過二層（拆除層位距地面三層以下者除外）。",
 "Where a demolition work zone cannot be set up, catch platforms at the outer wall shall be at least how wide and support a live load of at least:",
 ["1.5 m; 600 kg/m²","1 m; 300 kg/m²","2 m; 1,000 kg/m²","0.8 m; 500 kg/m²"],
 "Article 160: at least 1.5 m wide, sloped inward and fully planked, supporting at least 600 kg/m² live load, and no more than two stories below the demolition level."),

(L,"第164條",3,"營造-拆除",
 "以人工拆除高煙囪時，施工架之工作臺不得高出煙囪頂多少公分及低於多少公尺？",
 ["二十五公分；一．五公尺","五十公分；一．二公尺","十五公分；二．五公尺","三十五公分；三．五公尺"],"a",
 "第164條：指派專人監督；不得以爆破或整體翻倒方式拆除高煙囪（四週有足夠地面者除外）；人工拆除應設施工架，工作臺不得高出煙囪頂二十五公分及低於一．五公尺；不得使勞工站立於煙囪壁頂；煙囪底部應有開孔防物料積集。",
 "When manually demolishing a tall chimney, the scaffold work platform shall not be more than how far above the chimney top, nor more than how far below it?",
 ["25 cm above; 1.5 m below","50 cm above; 1.2 m below","15 cm above; 2.5 m below","35 cm above; 3.5 m below"],
 "Article 164: a designated supervisor; no blasting or toppling unless there is enough clear ground; platforms not more than 25 cm above nor 1.5 m below the top; no standing on the chimney wall; a bottom opening to prevent debris build-up."),

(L,"第167條",1,"營造-油漆瀝青",
 "噴漆作業場所，下列何者正確？",
 ["不得有明火、加熱器或其他火源，並揭示嚴禁煙火標示","得使用電熱器加速乾燥，但應揭示嚴禁煙火之標示","作業人員於通風處得吸菸，並免設嚴禁煙火標示","無須通風換氣，僅需於出入口設置滅火器材即可"],"a",
 "第166條：油漆作業場所應有適當通風換氣。第167條：噴漆作業場所不得有明火、加熱器或其他火源發生之虞之裝置或作業，並在該範圍內揭示嚴禁煙火之標示。",
 "In spray-painting areas, which is correct?",
 ["No open flames, heaters or other ignition sources, with 'No fire' signs posted","Electric heaters may be used to speed drying if 'No fire' signs are posted","Smoking is allowed in ventilated spots, and no 'No fire' signs are needed","No ventilation is required; fire extinguishers at the entrance suffice"],
 "Article 166 requires ventilation in painting areas; Article 167 prohibits open flames, heaters or ignition sources in spray-painting areas, with 'no fire' signs posted."),

(L,"第172條",2,"營造-衛生",
 "營造工程之臨時房舍，下列何者正確？",
 ["應選擇乾燥及排水良好之地點搭建，用餐地點、寢室及盥洗設備應分設","得選擇低窪易積水之地點搭建，用餐地點與寢室得合併於同一空間","應搭建於工地開挖面上方，寢室、廚房及盥洗設備得共用同一空間","飲用水及洗濯用水無須符合飲用水衛生標準，亦免設食品貯存設備"],"a",
 "第172條：選擇乾燥及排水良好之地點搭建；適當通風及照明；使用合於飲用水衛生標準之飲用水及洗濯用水；用餐地點、寢室及盥洗設備應分設並保持清潔；設置冰箱、食品貯存及廢物處理等衛生設備。",
 "For temporary site accommodation, which is correct?",
 ["Build on dry, well-drained ground; dining, sleeping and washing areas kept separate","Build on low-lying flood-prone ground; dining and sleeping areas may be combined","Build above the excavation face; bedrooms, kitchen and washrooms may share one space","Drinking and washing water need not meet standards, and no food storage is required"],
 "Article 172: dry, well-drained sites; ventilation and lighting; water meeting drinking-water standards; separate dining, sleeping and washing areas kept clean; refrigerators, food storage and waste facilities."),

(L,"第173-1條",2,"營造-附則",
 "受工作場所負責人指揮或監督從事勞動之人員，於事業單位工作場所從事勞動時，是否適用營造安全衛生設施標準？",
 ["比照該事業單位之勞工適用","一律不適用本標準之規定","僅適用其中有關防護具之規定","依承攬契約約定之範圍決定"],"a",
 "第173條之1：自營作業者獨立作業或以其作業交付承攬時，適用本標準有關雇主義務之規定；受工作場所負責人指揮或監督從事勞動之人員，比照該事業單位之勞工，適用本標準之規定。",
 "Do the Standards apply to persons working under the direction or supervision of a workplace manager at an enterprise's site?",
 ["Yes, they are treated like the enterprise's own laborers","No, the Standards do not apply to such persons at all","Only the provisions on personal protective equipment apply","Only to the extent agreed in the subcontract terms"],
 "Article 173-1: self-employed persons are subject to the employer obligations; persons working under a workplace manager's direction are treated like that enterprise's laborers."),
]
