# -*- coding: utf-8 -*-
Q = [
("OSH-48","第58條",2,"勞基法-退休金請求權",
 "勞工請領退休金之權利，其消滅時效起算點與期間為何？該權利有何處分限制？",
 ["自退休之次月起因五年間不行使而消滅；且不得讓與、抵銷、扣押或供擔保","自退休之當月起因二年間不行使而消滅；且不得讓與、抵銷、扣押或供擔保","自退休之次月起因十年間不行使而消滅；惟經勞工同意者得讓與或供擔保","自知悉得請領之日起因五年間不行使而消滅；並得由雇主逕行抵銷債務"],"a",
 "第58條：勞工請領退休金之權利，自退休之次月起因五年間不行使而消滅，且不得讓與、抵銷、扣押或供擔保。勞工並得檢具證明文件於金融機構開立專戶，專供存入退休金之用，該專戶存款不得作為抵銷、扣押、供擔保或強制執行之標的。第61條對職業災害補償受領權則定二年時效。",
 "When does the right to claim a retirement pension lapse, and what restrictions apply?",
 ["Five years from the month after retirement if unexercised; it cannot be assigned, offset, seized or pledged","Two years from the month of retirement if unexercised; it cannot be assigned, offset, seized or pledged","Ten years from the month after retirement if unexercised; it may be assigned or pledged with consent","Five years from learning of the entitlement; the employer may offset it against debts owed"],
 "Article 58: five years from the month after retirement; no assignment or seizure."),

("OSH-48","第60條",1,"勞基法-職災補償抵充",
 "雇主依第五十九條規定給付之職業災害補償金額，與同一事故所生損害賠償之關係為何？",
 ["得抵充就同一事故所生損害之賠償金額","應另行給付而不得抵充損害賠償金額","僅得抵充損害賠償金額之二分之一為限","須經法院裁定後始得抵充損害賠償金額"],"a",
 "第60條：雇主依第59條規定給付之補償金額，得抵充就同一事故所生損害之賠償金額。第63條之1第4項對要派單位或派遣事業單位所為給付亦有相同抵充規定；第59條本文則規定同一事故已由雇主支付費用補償者亦得抵充。",
 "How does compensation paid under Article 59 relate to damages for the same accident?",
 ["It may be set off against damages arising from the same accident","It is paid separately and may not be set off against damages","It may be set off only up to one half of the damages amount","It may be set off only after a court so rules in the case"],
 "Article 60: such compensation may offset damages for the same accident."),

("OSH-48","第61條",2,"勞基法-補償請求權",
 "第五十九條之職業災害受領補償權，其消滅時效及是否因勞工離職而受影響？",
 ["自得受領之日起因二年間不行使而消滅；受領權不因勞工之離職而受影響","自得受領之日起因五年間不行使而消滅；受領權不因勞工之離職而受影響","自事故發生之日起因二年間不行使而消滅；勞工離職後受領權即歸於消滅","自知悉損害之日起因十年間不行使而消滅；受領權於離職時應一次結清"],"a",
 "第61條：第59條之受領補償權，自得受領之日起因二年間不行使而消滅；受領補償之權利不因勞工之離職而受影響，且不得讓與、抵銷、扣押或供擔保。勞工或其遺屬並得開立專戶專供存入職業災害補償金，該專戶存款不得作為強制執行之標的。",
 "What is the limitation period for occupational accident compensation, and does leaving affect it?",
 ["Two years from when it becomes claimable; the right is unaffected by the worker leaving","Five years from when it becomes claimable; the right is unaffected by the worker leaving","Two years from the date of the accident; the right ends once the worker leaves the job","Ten years from learning of the loss; the right must be settled in full upon separation"],
 "Article 61: two years, and leaving employment does not affect the right."),

("OSH-48","第63條",3,"勞基法-承攬",
 "承攬人工作場所在原事業單位範圍內或為其提供者，原事業單位之責任為何？",
 ["應督促承攬人對其所僱勞工之勞動條件符合法令；違背職安法責任致職災者負連帶補償責任","僅須於招標文件載明勞動條件要求即可；承攬人所僱勞工發生職災與原事業單位無涉","應逕行代承攬人給付全部工資及資遣費；職災補償則由最後承攬人單獨負責","應為承攬人所僱勞工投保商業保險；發生職災時由保險金給付而免除補償責任"],"a",
 "第63條：承攬人或再承攬人工作場所在原事業單位工作場所範圍內或為原事業單位提供者，原事業單位應督促承攬人或再承攬人對其所僱用勞工之勞動條件符合有關法令；事業單位違背職業安全衛生法有關對承攬人應負責任之規定，致其所僱勞工發生職業災害時，應與該承攬人、再承攬人負連帶補償責任。第62條另定承攬人間之連帶補償與求償。",
 "What is the original employer's duty when contractor work occurs on its premises?",
 ["Ensure the contractor's workers' conditions meet the law; joint compensation liability if OSH duties are breached","Only state the required conditions in tender documents; accidents to contractor workers are unrelated to it","Pay all wages and severance for the contractor directly; the last contractor alone bears compensation","Buy commercial insurance for contractor workers; insurance payment removes any compensation duty"],
 "Article 63: supervision duty plus joint compensation liability."),

("OSH-48","第63條之1",3,"勞基法-派遣職災",
 "要派單位使用派遣勞工發生職業災害時，其補償及賠償責任為何？",
 ["應與派遣事業單位連帶負職業災害補償責任；違反安全衛生規定致職災者並連帶負損害賠償責任","應由派遣事業單位單獨負職業災害補償責任；要派單位僅於故意時始負損害賠償責任","應由要派單位單獨負職業災害補償責任；派遣事業單位僅負補償金額二分之一之責任","應先由勞工保險給付後不足部分再由要派單位補償；派遣事業單位不負任何賠償責任"],"a",
 "第63條之1：要派單位使用派遣勞工發生職業災害時，要派單位應與派遣事業單位連帶負本章所定雇主應負職業災害補償之責任；要派單位及派遣事業單位因違反本法或有關安全衛生規定致派遣勞工發生職業災害時，應連帶負損害賠償之責任。已由任一方支付費用補償者得主張抵充，所給付補償金額並得抵充同一事故之損害賠償。",
 "What liability does a client firm bear for a dispatched worker's occupational accident?",
 ["Joint compensation liability with the dispatch agency, and joint damages liability if safety rules are breached","The dispatch agency alone bears compensation; the client firm owes damages only if it acted intentionally","The client firm alone bears compensation; the dispatch agency is liable for only half the amount","Labor insurance pays first and the client covers the gap; the agency bears no liability at all"],
 "Article 63-1: joint compensation and joint damages liability."),

("OSH-48","第64條",2,"勞基法-技術生",
 "雇主招收技術生之年齡限制及本章準用對象為何？",
 ["不得招收未滿十五歲之人，但國民中學畢業者不在此限；養成工、見習生、建教生等準用之","不得招收未滿十六歲之人，但國民中學畢業者不在此限；僅養成工及見習生準用本章規定","不得招收未滿十五歲之人且無任何例外；建教合作班學生應另依建教生權益保障法規定辦理","不得招收未滿十八歲之人，但經法定代理人同意者不在此限；見習生不準用本章規定"],"a",
 "第64條：雇主不得招收未滿十五歲之人為技術生，但國民中學畢業者不在此限；技術生指依中央主管機關規定之技術生訓練職類中以學習技能為目的而接受雇主訓練之人；本章規定於事業單位之養成工、見習生、建教合作班學生及其他性質相類之人準用之。違反第1項依第77條處刑責。",
 "What age limit applies to recruiting apprentices, and who else is covered?",
 ["No one under 15, unless a junior high graduate; trainees, interns and cooperative-education students apply it","No one under 16, unless a junior high graduate; only trainees and interns apply this chapter","No one under 15 with no exception at all; cooperative-education students follow their own protection act","No one under 18, unless the legal representative consents; interns do not apply this chapter"],
 "Article 64: under 15 barred unless a junior high graduate; wide coverage."),

("OSH-48","第65條",2,"勞基法-技術生契約",
 "雇主招收技術生時應簽訂之訓練契約份數、程序及未成年人之特別要求為何？",
 ["應簽訂書面訓練契約一式三份由當事人分執並送主管機關備案；未成年人應得法定代理人允許","應簽訂書面訓練契約一式二份由當事人分執並送工會備查；未成年人應得法定代理人允許","應簽訂書面訓練契約一式三份由當事人分執並報主管機關核准；未成年人應經學校同意","得以口頭約定訓練項目與期限並記載於工作規則；未成年人應由學校代為簽訂訓練契約"],"a",
 "第65條：雇主招收技術生時，須與技術生簽訂書面訓練契約一式三份，訂明訓練項目、訓練期限、膳宿負擔、生活津貼、相關教學、勞工保險、結業證明、契約生效與解除之條件及其他權利義務事項，由當事人分執並送主管機關備案；技術生如為未成年人，其訓練契約應得法定代理人之允許。違反第1項依第79條第3項處罰。",
 "How many copies of the apprentice training contract are required, and what applies to minors?",
 ["Three written copies held by the parties and filed with the authority; minors need their guardian's permission","Two written copies held by the parties and filed with the union; minors need their guardian's permission","Three written copies held by the parties and approved by the authority; minors need school consent","An oral agreement stated in the work rules is enough; the school signs on behalf of a minor"],
 "Article 65: three written copies, filed with the authority; guardian consent for minors."),

("OSH-48","第66條、第79條",1,"勞基法-技術生",
 "雇主可否向技術生收取有關訓練費用？違反者如何處罰？",
 ["不得向技術生收取有關訓練費用；違反者處新臺幣二萬元以上三十萬元以下罰鍰","得於訓練契約中約定收取合理訓練費用；未載明於契約者處三萬元以上罰鍰","得於技術生結業後留用時分期收取費用；違反者處九萬元以上四十五萬元罰鍰","不得向技術生收取訓練費用，但得要求提供保證人；違反者僅限期令其改善"],"a",
 "第66條：雇主不得向技術生收取有關訓練費用。違反者依第79條第3項處新臺幣二萬元以上三十萬元以下罰鍰。第69條並規定本法工作時間、休息、休假、童工女工、災害補償等規定於技術生準用之。",
 "May an employer charge apprentices training fees, and what is the penalty?",
 ["No training fees may be charged; breach is fined NT$20,000 to NT$300,000","Reasonable fees may be agreed in the contract; fines start at NT$30,000 otherwise","Fees may be collected in instalments after retention; breach is fined NT$90,000 upward","No fees, though a guarantor may be required; breach only leads to an order to improve"],
 "Article 66: charging apprentices training fees is prohibited."),

("OSH-48","第67條",2,"勞基法-技術生留用",
 "技術生訓練期滿後雇主留用者，其待遇及留用期間限制為何？",
 ["應與同等工作之勞工享受同等待遇；契約訂明之留用期間不得超過其訓練期間","應按同等工作勞工待遇之八成給付；契約訂明之留用期間不得超過二年為限","應與同等工作之勞工享受同等待遇；契約訂明之留用期間得為訓練期間之二倍","得由雙方另行議定待遇不受限制；留用期間應報請當地主管機關核備後實施"],"a",
 "第67條：技術生訓練期滿，雇主得留用之，並應與同等工作之勞工享受同等之待遇；雇主如於技術生訓練契約內訂明留用期間，應不得超過其訓練期間。第68條並限制技術生人數不得超過勞工人數四分之一。",
 "What terms apply if an apprentice is retained after training?",
 ["Equal treatment with workers doing the same work; any agreed retention period may not exceed the training period","Eighty percent of the pay of workers doing the same work; any retention period is capped at two years","Equal treatment with workers doing the same work; the retention period may be twice the training period","Terms are freely negotiable; the retention period must be filed with the local authority first"],
 "Article 67: equal treatment; retention no longer than the training period."),

("OSH-48","第68條",2,"勞基法-技術生人數",
 "技術生人數之上限如何計算？勞工人數不滿四人者如何處理？",
 ["不得超過勞工人數四分之一；勞工人數不滿四人者，以四人計","不得超過勞工人數三分之一；勞工人數不滿四人者，以四人計","不得超過勞工人數四分之一；勞工人數不滿十人者，以十人計","不得超過勞工人數五分之一；勞工人數不滿五人者，不得招收技術生"],"a",
 "第68條：技術生人數不得超過勞工人數四分之一；勞工人數不滿四人者，以四人計，故最少得招收一名技術生。違反本條者依第79條第3項處新臺幣二萬元以上三十萬元以下罰鍰。",
 "How is the cap on apprentice numbers calculated?",
 ["No more than one quarter of the workers; if fewer than four workers, four is used","No more than one third of the workers; if fewer than four workers, four is used","No more than one quarter of the workers; if fewer than ten workers, ten is used","No more than one fifth of the workers; with fewer than five workers, none may be taken"],
 "Article 68: one quarter, with a floor of four workers."),

("OSH-48","第69條",2,"勞基法-技術生準用",
 "勞動基準法對技術生準用之範圍及災害補償薪資計算標準為何？",
 ["準用工作時間休息休假、童工女工、災害補償及勞工保險等規定；補償薪資不得低於基本工資","準用工作時間休息休假及退休章規定；補償薪資以實際生活津貼數額為計算標準","準用童工女工及工作規則章規定；補償薪資得由勞雇雙方於訓練契約中自行議定","準用災害補償及監督檢查章規定；補償薪資以基本工資之二分之一為計算標準"],"a",
 "第69條：本法第四章工作時間、休息、休假，第五章童工、女工，第七章災害補償及其他勞工保險等有關規定，於技術生準用之；技術生災害補償所採薪資計算之標準，不得低於基本工資。第79條之1並規定違反第69條第1項準用規定之處罰適用罰則章規定。",
 "What provisions apply to apprentices, and how is accident compensation pay calculated?",
 ["Working hours, child and women workers, accident compensation and labor insurance apply; pay not below basic wage","Working hours and the retirement chapter apply; compensation pay equals the actual living allowance","Child and women workers and work rules chapters apply; compensation pay is freely agreed in the contract","Accident compensation and inspection chapters apply; compensation pay is half of the basic wage"],
 "Article 69: broad application, with pay not below the basic wage."),

("OSH-48","第71條",1,"勞基法-工作規則",
 "工作規則於何種情形下無效？",
 ["違反法令之強制或禁止規定，或違反該事業適用之團體協約規定者，無效","未經主管機關核備或未公開揭示者，其全部內容自訂定之日起均屬無效","未經勞資會議同意即實施者無效，經事後追認者溯及訂定時發生效力","僅於勞工個別表示反對之部分無效，其餘部分仍對全體勞工發生效力"],"a",
 "第71條：工作規則違反法令之強制或禁止規定或其他有關該事業適用之團體協約規定者，無效。第70條規定僱用勞工三十人以上者應就工作時間、工資、獎懲等十二款事項訂立工作規則，報請主管機關核備後公開揭示。",
 "When are work rules void?",
 ["When they breach mandatory or prohibitory legal provisions, or the applicable collective agreement","When they are not filed with the authority or posted, in which case all of them are void from adoption","When adopted without labor-management meeting consent, unless later ratified retroactively","Only the parts individual workers object to are void; the rest still binds all workers"],
 "Article 71: void if contrary to mandatory law or a collective agreement."),

("OSH-48","第72條",2,"勞基法-檢查機構",
 "為貫徹勞動基準法及其他勞工法令之執行，勞工檢查機構應如何設置？",
 ["中央主管機關設勞工檢查機構或授權直轄市主管機關專設；直轄市、縣（市）必要時亦得派員實施檢查","由直轄市、縣（市）主管機關分別設置檢查機構；中央主管機關僅負責訂定年度檢查方針","由中央主管機關委託民間專業團體設置檢查機構；地方主管機關不得自行派員實施檢查","由勞動部與經濟部會同設置聯合檢查機構；其組織章程應報請行政院核定後始得設立"],"a",
 "第72條：中央主管機關為貫徹本法及其他勞工法令之執行，設勞工檢查機構或授權直轄市主管機關專設檢查機構辦理之；直轄市、縣（市）主管機關於必要時，亦得派員實施檢查；勞工檢查機構之組織由中央主管機關定之。施行細則第41條並規定中央主管機關應每年定期發布次年度勞工檢查方針。",
 "How are labor inspection agencies established?",
 ["The central authority sets them up or authorizes municipal ones; local authorities may also send inspectors","Each municipal and county authority sets up its own; the central authority only issues annual guidelines","The central authority commissions private bodies; local authorities may not send inspectors themselves","The Ministries of Labor and Economic Affairs jointly set up one agency approved by the Executive Yuan"],
 "Article 72: central establishment or delegation, plus local inspections."),

("OSH-48","第73條",2,"勞基法-檢查程序",
 "檢查員執行職務時之程序要求，及抽取物料樣品時應如何辦理？",
 ["應出示檢查證，事業單位拒絕時得會同當地主管機關或警察機關強制檢查；抽取樣品應事先通知並掣給收據","得逕行進入檢查而無須出示證件，事業單位拒絕時應報請法院核發搜索票；抽取樣品無須通知雇主","應出示檢查證並事先七日通知受檢單位，拒絕時僅得處以罰鍰；抽取樣品應由雇主自行提供並簽名","應由當地主管機關會同工會代表共同檢查，拒絕時得逕行停工；抽取樣品應於檢查後補行通知"],"a",
 "第73條：檢查員執行職務應出示檢查證，各事業單位不得拒絕；事業單位拒絕檢查時，檢查員得會同當地主管機關或警察機關強制檢查之。檢查員得要求事業單位提出必要之報告、紀錄、帳冊及有關文件或書面說明，如需抽取物料、樣品或資料時，應事先通知雇主或其代理人並掣給收據。拒絕、規避或阻撓檢查者依第80條處罰。",
 "What procedures must inspectors follow, and what applies when taking samples?",
 ["Show credentials; if refused, inspect compulsorily with the local authority or police; notify and issue a receipt for samples","Enter without credentials; if refused, obtain a court search warrant; samples need no notice to the employer","Show credentials and give seven days notice; refusal draws only a fine; the employer supplies and signs for samples","Inspect jointly with the local authority and union; refusal allows a work stoppage; notice for samples comes later"],
 "Article 73: credentials, compulsory inspection if refused, notice and receipt for samples."),

("OSH-48","第76條",2,"勞基法-罰則",
 "勞動基準法第七十六條所定三年以下有期徒刑、拘役或科或併科四十五萬元以下罰金，係處罰違反何種行為？",
 ["違反任何人不得介入他人勞動契約抽取不法利益之規定者","違反雇主不得以強暴脅迫拘禁強制勞工從事勞動之規定者","違反雇主不得預扣勞工工資作為違約金或賠償費用之規定者","違反雇主不得僱用未滿十五歲之人從事工作之規定者"],"a",
 "第76條：違反第6條規定者，處三年以下有期徒刑、拘役或科或併科新臺幣四十五萬元以下罰金；第6條即任何人不得介入他人之勞動契約抽取不法利益。至於違反第5條強制勞動禁止者，依第75條處五年以下有期徒刑及七十五萬元以下罰金，刑度更重。",
 "Which violation carries up to three years imprisonment or a NT$450,000 fine?",
 ["Intervening in another person's labor contract to extract unlawful profit","Compelling labor by violence, threat or confinement as an employer","Deducting wages in advance as a penalty or compensation as an employer","Employing a person under fifteen years of age to perform work"],
 "Article 76 punishes violations of Article 6."),

("OSH-48","第77條",3,"勞基法-罰則",
 "違反下列何組規定者，處六個月以下有期徒刑、拘役或科或併科新臺幣三十萬元以下罰金？",
 ["第四十二條、第四十四條第二項、第四十五條第一項、第四十七條、第四十八條、第四十九條第三項或第六十四條第一項","第五條、第六條、第十三條、第二十六條、第五十條、第五十一條或第五十六條第二項所定之各項義務規定","第二十一條第一項、第二十二條至第二十五條、第三十條、第三十二條或第五十九條所定之各項義務規定","第七條、第九條第一項、第十六條、第十九條、第四十六條、第七十條或第七十四條第二項所定義務規定"],"a",
 "第77條：違反第42條（不得強制加班）、第44條第2項（危險有害性工作禁止）、第45條第1項（未滿十五歲僱用禁止）、第47條（童工工時）、第48條（童工夜間工作）、第49條第3項（女工夜間不得強制）或第64條第1項（技術生年齡）規定者，處六個月以下有期徒刑、拘役或科或併科新臺幣三十萬元以下罰金。",
 "Which group of violations carries up to six months imprisonment or a NT$300,000 fine?",
 ["Articles 42, 44(2), 45(1), 47, 48, 49(3) and 64(1) on forced overtime, child and women workers","Articles 5, 6, 13, 26, 50, 51 and 56(2) on forced labor, wage deduction and maternity duties","Articles 21(1), 22 to 25, 30, 32 and 59 on wages, working hours and accident compensation","Articles 7, 9(1), 16, 19, 46, 70 and 74(2) on record cards, notice and work rules duties"],
 "Article 77 lists the provisions punished by up to six months imprisonment."),

("OSH-48","第78條",3,"勞基法-罰則",
 "未依第十七條、第十七條之一第七項或第五十五條規定之標準或期限給付資遣費、退休金者，罰鍰額度為何？",
 ["處新臺幣三十萬元以上一百五十萬元以下罰鍰，並限期令其給付，屆期未給付者應按次處罰","處新臺幣九萬元以上四十五萬元以下罰鍰，並限期令其給付，屆期未給付者應按次處罰","處新臺幣二萬元以上一百萬元以下罰鍰，並得加重其罰鍰至法定最高額二分之一","處新臺幣二萬元以上三十萬元以下罰鍰，並公布事業單位名稱及負責人姓名"],"a",
 "第78條第1項：未依第17條、第17條之1第7項、第55條規定之標準或期限給付者，處新臺幣三十萬元以上一百五十萬元以下罰鍰，並限期令其給付，屆期未給付者應按次處罰。同條第2項對違反第13條、第26條、第50條、第51條或第56條第2項者，處九萬元以上四十五萬元以下罰鍰。",
 "What fine applies for failing to pay severance or pensions to the required standard or deadline?",
 ["NT$300,000 to NT$1,500,000, with an order to pay and repeated fines if the deadline passes","NT$90,000 to NT$450,000, with an order to pay and repeated fines if the deadline passes","NT$20,000 to NT$1,000,000, which may be increased by up to one half of the statutory maximum","NT$20,000 to NT$300,000, together with publication of the firm's and its principal's names"],
 "Article 78(1): NT$300,000 to NT$1,500,000 plus an order to pay."),

("OSH-48","第79條之1",2,"勞基法-罰則",
 "違反第四十五條第二項、第四項、第六十四條第三項及第六十九條第一項準用規定者，應如何處罰？",
 ["其處罰適用本法罰則章之規定，依所準用條文對應之罰則辦理","一律處新臺幣二萬元以上三十萬元以下罰鍰，不適用刑罰規定","由中央主管機關另以辦法定其處罰基準，罰則章規定不適用之","僅得限期令其改善，屆期未改善者始得依罰則章規定處罰之"],"a",
 "第79條之1：違反第45條第2項、第4項、第64條第3項及第69條第1項準用規定之處罰，適用本法罰則章規定。亦即受準用保護之人（如未滿十五歲受僱人、養成工、見習生、建教生、技術生）之相關違反行為，仍依罰則章對應條文論處。",
 "How are violations of the applied-by-reference provisions punished?",
 ["The penalties chapter of this Act applies, following the penalty for the referenced provision","A fine of NT$20,000 to NT$300,000 always applies, with no criminal penalties available","The central authority sets separate penalty standards; the penalties chapter does not apply","Only an order to improve may be issued; penalties follow only if the deadline is missed"],
 "Article 79-1: the penalties chapter applies to these referenced provisions."),

("OSH-48","第80條",1,"勞基法-罰則",
 "拒絕、規避或阻撓勞工檢查員依法執行職務者，其罰鍰額度為何？",
 ["處新臺幣三萬元以上十五萬元以下罰鍰","處新臺幣二萬元以上三十萬元以下罰鍰","處新臺幣九萬元以上四十五萬元以下罰鍰","處新臺幣十五萬元以上七十五萬元以下罰鍰"],"a",
 "第80條：拒絕、規避或阻撓勞工檢查員依法執行職務者，處新臺幣三萬元以上十五萬元以下罰鍰。第73條並規定檢查員執行職務應出示檢查證，事業單位拒絕檢查時，檢查員得會同當地主管機關或警察機關強制檢查。",
 "What fine applies for refusing, evading or obstructing a labor inspector?",
 ["A fine of NT$30,000 to NT$150,000","A fine of NT$20,000 to NT$300,000","A fine of NT$90,000 to NT$450,000","A fine of NT$150,000 to NT$750,000"],
 "Article 80: NT$30,000 to NT$150,000."),

("OSH-48","第80條之1",2,"勞基法-公布",
 "違反本法經主管機關處以罰鍰者，主管機關應為何種處置？裁處罰鍰之量罰標準為何？",
 ["應公布名稱、負責人姓名、處分期日、違反條文及罰鍰金額並限期改善；量罰得審酌違反人數及累計違法次數","僅須將處分書送達事業單位並副知當地工會；罰鍰一律按法定最低額裁處而不得審酌其他情狀","應公布事業單位名稱及罰鍰金額，但無須限期令其改善；量罰標準由勞動檢查機構逐案報請中央核定","應先限期改善屆期未改善者始得處罰並公布名稱；量罰僅得審酌事業單位之資本額及營業規模"],"a",
 "第80條之1：違反本法經主管機關處以罰鍰者，主管機關應公布其事業單位或事業主之名稱、負責人姓名、處分期日、違反條文及罰鍰金額，並限期令其改善，屆期未改善者應按次處罰；主管機關裁處罰鍰得審酌與違反行為有關之勞工人數、累計違法次數或未依法給付之金額，為量罰輕重之標準。",
 "What must the authority do when imposing a fine, and how is the amount weighed?",
 ["Publish the name, principal, date, provision and amount, order improvement; weigh worker numbers and repeat breaches","Only serve the decision on the firm and copy the union; the minimum statutory fine always applies with no discretion","Publish the firm's name and the amount without ordering improvement; standards are approved case by case centrally","Order improvement first and fine only if ignored; only capital and business scale may be weighed"],
 "Article 80-1: publication, order to improve, and stated weighing factors."),

("OSH-48","第81條",3,"勞基法-兩罰",
 "法人之受僱人因執行業務違反本法規定時，對該法人應如何處罰？有無免責規定？",
 ["除處罰行為人外，對該法人並應處以各該條所定之罰金或罰鍰；但代表人已盡力防止者不在此限","僅處罰行為人，法人不受處罰；惟法人仍應負連帶繳納罰鍰之責任且不得主張任何免責事由","僅處罰法人而不處罰行為人；法人得於繳納後向行為人求償全部罰金或罰鍰","對法人及行為人均加重處罰至法定最高額二倍；法人無任何免責之事由可主張"],"a",
 "第81條：法人之代表人、法人或自然人之代理人、受僱人或其他從業人員，因執行業務違反本法規定，除依本章規定處罰行為人外，對該法人或自然人並應處以各該條所定之罰金或罰鍰；但法人之代表人或自然人對於違反之發生已盡力為防止行為者不在此限。法人之代表人或自然人教唆或縱容為違反行為者，以行為人論。",
 "How is a legal person punished when its employee breaches the Act at work?",
 ["Both the actor and the legal person are punished under the same provision, unless the representative took all preventive steps","Only the actor is punished; the legal person remains jointly liable to pay the fine with no defence available at all","Only the legal person is punished; it may then recover the whole fine from the individual actor","Both are punished at twice the statutory maximum; the legal person has no defence at all"],
 "Article 81: dual punishment with a due-diligence defence."),

("OSH-48","第82條",1,"勞基法-罰鍰執行",
 "本法所定之罰鍰，經主管機關催繳仍不繳納時，應如何處理？",
 ["得移送法院強制執行","得逕行停止其營業登記","得按次連續加倍處罰之","得逕行查封其生產設備"],"a",
 "第82條：本法所定之罰鍰，經主管機關催繳仍不繳納時，得移送法院強制執行。第80條之1另規定違反本法經處罰鍰者，主管機關應公布名稱並限期令其改善，屆期未改善者應按次處罰。",
 "What happens if a fine under this Act remains unpaid after a demand?",
 ["It may be referred to the court for compulsory enforcement","The business registration may be suspended outright","The fine may be doubled repeatedly and continuously","Production equipment may be seized directly by the authority"],
 "Article 82: referral to the court for enforcement."),

("OSH-48","第83條",2,"勞基法-勞資會議",
 "事業單位舉辦勞資會議之目的及其辦法之訂定程序為何？",
 ["為協調勞資關係、促進勞資合作及提高工作效率；辦法由中央主管機關會同經濟部訂定並報行政院核定","為協商團體協約及調解勞資爭議；辦法由中央主管機關會同法務部訂定並報立法院備查後實施","為審議工作規則及退休準備金提撥比率；辦法由當地主管機關依地方自治條例自行訂定公布","為監督勞工退休基金之運用績效；辦法由中央主管機關會同財政部訂定並報行政院核定實施"],"a",
 "第83條：為協調勞資關係，促進勞資合作，提高工作效率，事業單位應舉辦勞資會議；其辦法由中央主管機關會同經濟部訂定，並報行政院核定。本法多處規定於無工會時須經勞資會議同意，如第30條變形工時、第32條延長工時等。",
 "What is the purpose of labor-management meetings, and who issues the regulations?",
 ["To coordinate relations, promote cooperation and raise efficiency; rules by the central authority with the MOEA, approved by the Executive Yuan","To negotiate collective agreements and mediate disputes; rules by the central authority with the Ministry of Justice, filed with the Legislative Yuan","To review work rules and reserve contribution rates; rules issued by each local authority under its own ordinance","To supervise the retirement fund's performance; rules by the central authority with the Ministry of Finance"],
 "Article 83: coordination purposes; rules jointly with the MOEA."),

("OSH-48","第84條",2,"勞基法-公務員兼具勞工身分",
 "公務員兼具勞工身分者，其任免、薪資、退休、撫卹及保險等事項應如何適用法令？",
 ["應適用公務員法令之規定；但其他所定勞動條件優於本法規定者，從其規定","應一律適用本法之規定；公務員法令與本法牴觸部分應停止適用其效力","應由服務機關於契約中自行約定；本法及公務員法令均不適用於該等人員","應適用本法之規定；但涉及保險及撫卹事項者，改依公務員法令規定辦理"],"a",
 "第84條：公務員兼具勞工身分者，其有關任（派）免、薪資、獎懲、退休、撫卹及保險（含職業災害）等事項，應適用公務員法令之規定；但其他所定勞動條件優於本法規定者，從其規定。施行細則第50條並界定所稱其他勞動條件係指工作時間、休息、休假、安全衛生、福利、加班費等。",
 "Which rules govern appointment, pay, retirement and insurance for public servants who are also workers?",
 ["Public service laws apply, but other working conditions better than this Act prevail","This Act always applies, and conflicting public service provisions cease to have effect","The agency sets the terms by contract; neither this Act nor public service laws apply","This Act applies, except that insurance and survivor benefits follow public service laws"],
 "Article 84: public service laws, subject to more favorable conditions."),

("OSH-48","第84條之2",3,"勞基法-年資與給與標準",
 "勞工適用本法前後之工作年資，其資遣費及退休金給與標準應如何計算？",
 ["適用本法前依當時應適用之法令，無法令可適用者依事業單位規定或勞雇協商；適用本法後依第十七條及第五十五條計算","適用本法前後一律依第十七條及第五十五條計算；當時無法令可適用者由主管機關逐案核定給與標準","適用本法前之年資一律不予計算；適用本法後之年資依勞工退休金條例之個人專戶制計算給與","適用本法前後均依事業單位自訂規定計算；勞雇雙方協商不成者由勞資會議決議其給與標準"],"a",
 "第84條之2：勞工工作年資自受僱之日起算，適用本法前之工作年資，其資遣費及退休金給與標準依其當時應適用之法令規定計算；當時無法令可資適用者，依各該事業單位自訂之規定或勞雇雙方之協商計算；適用本法後之工作年資，其資遣費及退休金給與標準依第17條及第55條規定計算。",
 "How are severance and pension standards set for service before and after the Act applied?",
 ["Before: the law then applicable, else company rules or agreement; after: Articles 17 and 55 apply","Articles 17 and 55 apply throughout; where no law existed, the authority decides case by case","Service before the Act is disregarded entirely; later service follows the individual pension account system","Company rules apply throughout; if the parties disagree the labor-management meeting decides"],
 "Article 84-2: prior law or company rules before, Articles 17 and 55 after."),

("OSH-48","第85條",1,"勞基法-授權",
 "勞動基準法施行細則之訂定程序為何？",
 ["由中央主管機關擬定，報請行政院核定","由中央主管機關逕行訂定發布，無須報核","由行政院擬定後送請立法院審議通過發布","由中央主管機關會同各地方主管機關訂定"],"a",
 "第85條：本法施行細則，由中央主管機關擬定，報請行政院核定。勞動基準法施行細則第1條亦載明本細則依本法第85條規定訂定之。相對地，第21條之基本工資審議委員會組織辦法則由中央主管機關另以辦法定之。",
 "How are the Enforcement Rules of the Act issued?",
 ["Drafted by the central competent authority and approved by the Executive Yuan","Issued directly by the central competent authority with no approval needed","Drafted by the Executive Yuan and passed by the Legislative Yuan before issue","Jointly issued by the central authority together with all local authorities"],
 "Article 85: drafted centrally, approved by the Executive Yuan."),

("OSH-48","第86條",2,"勞基法-施行日",
 "勞動基準法及其中華民國一百零七年一月十日修正條文之施行日期為何？",
 ["本法自公布日施行；一百零七年一月十日修正之條文自一百零七年三月一日施行","本法自公布日施行；一百零七年一月十日修正之條文自一百零七年一月一日施行","本法自公布後六個月施行；一百零七年一月十日修正之條文自公布日起施行","本法自公布日施行；一百零七年一月十日修正之條文施行日期由行政院另定"],"a",
 "第86條：本法自公布日施行；一百零四年二月四日修正公布之第28條第1項自公布後八個月施行，一百零五年十二月二十一日修正公布之第37條及第38條自一百零六年一月一日施行；本法中華民國一百零七年一月十日修正之條文，自一百零七年三月一日施行。",
 "When did the Act and its 10 January 2018 amendments take effect?",
 ["The Act on promulgation; the 10 January 2018 amendments on 1 March 2018","The Act on promulgation; the 10 January 2018 amendments on 1 January 2018","The Act six months after promulgation; the 2018 amendments on promulgation","The Act on promulgation; the 2018 amendments on a date set by the Executive Yuan"],
 "Article 86: the 2018 amendments took effect on 1 March 2018."),

("OSH-49","第1條",1,"勞基細則-授權",
 "勞動基準法施行細則之訂定法源依據為何？",
 ["勞動基準法第八十五條","勞動基準法第八十六條","勞動基準法第八十三條","勞動基準法第八十四條之一"],"a",
 "施行細則第1條：本細則依勞動基準法（以下簡稱本法）第85條規定訂定之。本法第85條規定施行細則由中央主管機關擬定，報請行政院核定。第86條則為本法之施行日期規定。",
 "What is the statutory basis for the Enforcement Rules of the Labor Standards Act?",
 ["Article 85 of the Labor Standards Act","Article 86 of the Labor Standards Act","Article 83 of the Labor Standards Act","Article 84-1 of the Labor Standards Act"],
 "Rule 1: issued under Article 85 of the Act."),

("OSH-49","第2條",3,"勞基細則-平均工資",
 "計算平均工資時，下列何者屬於應不計入之期日或期間？",
 ["發生計算事由之當日、因職業災害尚在醫療中者、依勞工請假規則請普通傷病假者、留職停薪者","發生計算事由之當日、勞工請特別休假期間、勞工於休息日出勤期間、延長工作時間之期間","勞工請婚假喪假期間、勞工於例假日出勤期間、依本法第五十條第一項請產假而工資照給者","勞工參加職前訓練期間、勞工於國定假日出勤期間、雇主停工而工資照給之期間、輪班期間"],"a",
 "施行細則第2條：計算平均工資時，發生計算事由之當日、因職業災害尚在醫療中者、依本法第50條第2項減半發給工資者、雇主因天災事變等不可抗力不能繼續其事業致勞工未能工作者、依勞工請假規則請普通傷病假者、依性別平等工作法請生理假產假家庭照顧假或安胎休養致減少工資者、留職停薪者，均不計入。",
 "Which periods are excluded when calculating average wages?",
 ["The day the cause arises, ongoing occupational injury treatment, ordinary sick leave, and unpaid leave","The day the cause arises, annual leave periods, rest-day work periods, and overtime hours","Marriage and funeral leave, work on regular days off, and fully paid maternity leave under Article 50(1)","Pre-job training, work on national holidays, paid shutdown periods, and shift rotation periods"],
 "Rule 2 lists seven excluded days and periods."),

("OSH-49","第3條",1,"勞基細則-適用行業",
 "本法第三條第一項第一款至第七款所列各業之認定，應適用何種標準？",
 ["適用中華民國行業標準分類之規定","適用各地方主管機關自行公告之分類","適用經濟部工廠登記所載之營業項目","適用勞工保險投保單位所填報之行業別"],"a",
 "施行細則第3條：本法第3條第1項第1款至第7款所列各業，適用中華民國行業標準分類之規定。第4條並規定第3條第1項第8款所稱中央主管機關指定之事業及第3項所稱適用本法確有窒礙難行者，係指中央主管機關依中華民國行業標準分類之規定指定者。",
 "Which classification governs the industries listed in Article 3(1)(1)-(7)?",
 ["The Standard Industrial Classification of the Republic of China","Classifications published separately by each local authority","The business items recorded in the factory registration","The industry code reported by the labor insurance unit"],
 "Rule 3: the Standard Industrial Classification applies."),

("OSH-49","第4條",2,"勞基細則-指定事業",
 "本法第三條第一項第八款所稱中央主管機關指定之事業及第三項所稱窒礙難行者，其指定方式為何？",
 ["係指中央主管機關依中華民國行業標準分類之規定指定者，並得僅指定各行業中之一部分","係指中央主管機關經徵詢全國性工會團體意見後指定者，且應指定該行業之全部工作者","係指各該目的事業主管機關依其主管法規指定者，並應報請行政院核定後公告實施","係指當地主管機關依事業單位申請個案認定者，並以僱用勞工三十人以上者為限"],"a",
 "施行細則第4條：本法第3條第1項第8款所稱中央主管機關指定之事業及第3項所稱適用本法確有窒礙難行者，係指中央主管機關依中華民國行業標準分類之規定指定者，並得僅指定各行業中之一部分。本法第3條第2項亦規定指定時得就事業之部分工作場所或工作者指定適用。",
 "How does the central authority designate businesses under Article 3(1)(8) and 3(3)?",
 ["By reference to the Standard Industrial Classification, and it may designate only part of an industry","After consulting national union bodies, and it must designate all workers in that industry","By each industry authority under its own statutes, with Executive Yuan approval before publication","By the local authority case by case on application, limited to firms with thirty or more workers"],
 "Rule 4: designation follows the Standard Industrial Classification and may be partial."),

("OSH-49","第4條之1",1,"勞基細則-已刪除條文",
 "關於勞動基準法施行細則第四條之一，下列敘述何者正確？",
 ["該條業經刪除，現行細則已無該條之實體規定內容","該條規定勞工工作年資應自受僱當日起算之原則","該條規定臨時性及短期性工作之期間認定標準","該條規定終止勞動契約時雇主應即結清工資"],"a",
 "施行細則第4條之1現為（刪除），已無實體規範內容。年資自受僱當日起算規定於第5條，臨時性、短期性等非繼續性工作之認定規定於第6條，終止契約應即結清工資則規定於第9條。",
 "Which statement about Rule 4-1 of the Enforcement Rules is correct?",
 ["It has been deleted and no longer contains any substantive provision","It provides that service years start from the first day of employment","It sets the criteria for temporary and short-term work periods","It requires wages to be settled immediately on termination"],
 "Rule 4-1 has been deleted."),

("OSH-49","第5條",2,"勞基細則-年資",
 "勞工工作年資之計算範圍及起算日為何？適用本法前之年資如何處理？",
 ["以服務同一事業單位為限並自受僱當日起算；適用本法前已在同一事業單位工作之年資合併計算","以服務同一事業單位為限並自到職滿三個月起算；適用本法前之年資一律不併入計算","以服務同一雇主為限並自試用期滿之日起算；適用本法前之年資由勞雇雙方協商是否併計","以勞工保險加保日起算並得跨事業單位累計；適用本法前之年資須報主管機關核定後併計"],"a",
 "施行細則第5條：勞工工作年資以服務同一事業單位為限，並自受僱當日起算；適用本法前已在同一事業單位工作之年資合併計算。本法第57條並規定受同一雇主調動之年資及依第20條由新雇主承認之年資應予併計；第24條規定特別休假年資之計算應依本條辦理。",
 "How are service years counted, and how is service before the Act treated?",
 ["Limited to the same establishment and counted from the first day of hire; earlier service there is combined","Limited to the same establishment and counted after three months of service; earlier service is excluded","Limited to the same employer and counted from the end of probation; earlier service is negotiable","Counted from labor insurance enrolment across establishments; earlier service needs official approval"],
 "Rule 5: same establishment, from the hiring date, with prior service combined."),

("OSH-49","第6條",3,"勞基細則-定期契約",
 "臨時性、短期性、季節性及特定性工作之認定標準，下列何者正確？",
 ["臨時性為無法預期之非繼續性工作且期間在六個月以內；季節性期間在九個月以內；特定性逾一年者應報主管機關核備","臨時性為無法預期之非繼續性工作且期間在三個月以內；季節性期間在六個月以內；特定性逾二年者應報主管機關核備","臨時性為可預期於六個月內完成之工作；季節性期間在一年以內；特定性工作無論期間長短均須報主管機關核備","臨時性為無法預期之繼續性工作且期間在九個月以內；季節性期間在六個月以內；特定性工作得由雙方自由約定期間"],"a",
 "施行細則第6條：臨時性工作指無法預期之非繼續性工作，期間在六個月以內；短期性工作指可預期於六個月內完成之非繼續性工作；季節性工作指受季節性原料材料來源或市場銷售影響之非繼續性工作，期間在九個月以內；特定性工作指可在特定期間完成之非繼續性工作，其工作期間超過一年者應報請主管機關核備。",
 "Which describes the criteria for temporary, short-term, seasonal and specified work?",
 ["Temporary: unforeseeable, non-continuous, within six months; seasonal within nine months; specified over one year needs filing","Temporary: unforeseeable, non-continuous, within three months; seasonal within six months; specified over two years needs filing","Temporary: foreseeable completion within six months; seasonal within one year; all specified work needs filing","Temporary: unforeseeable but continuous, within nine months; seasonal within six months; specified work is freely agreed"],
 "Rule 6 defines the four categories and their time limits."),

("OSH-49","第7條",2,"勞基細則-契約內容",
 "勞動契約應依本法有關規定約定之事項，不包括下列何者？",
 ["勞工個人之信用調查結果及婚姻生育規劃等私人事項","工作場所及應從事之工作、工作開始與終止之時間","工資之議定調整計算結算與給付之日期及方法","資遣費、退休金、其他津貼及獎金與災害補償事項"],"a",
 "施行細則第7條列舉勞動契約應約定之十三款事項，包括工作場所及應從事之工作、工作與休息時間及輪班換班、工資議定調整計算與給付、契約訂定終止及退休、資遣費退休金津貼獎金、膳宿費與工作用具費、安全衛生、教育訓練、福利、災害補償及一般傷病補助、應遵守之紀律、獎懲及其他勞資權利義務事項，並不包含勞工私人事項。",
 "Which item is NOT among the matters a labor contract must cover?",
 ["The worker's personal credit checks and plans regarding marriage or childbearing","The workplace and the work to be performed, and starting and ending times","Wage negotiation, adjustment, calculation, settlement dates and methods","Severance, pensions, other allowances and bonuses, and accident compensation"],
 "Rule 7 lists thirteen contract matters; private matters are not among them."),

("OSH-49","第7條之1",2,"勞基細則-競業禁止",
 "離職後競業禁止之約定，其形式要件為何？",
 ["應以書面為之，詳細記載本法第九條之一第一項第三款及第四款內容，並由雙方簽章各執一份","得以口頭約定並記載於工作規則中，經公開揭示後即對全體勞工發生拘束力並得隨時修正","應以書面為之並報請當地主管機關核備後生效，未經核備者其約定一律不生效力","應載明於勞動契約之附件並經工會同意，勞工並得於離職前隨時撤回其同意"],"a",
 "施行細則第7條之1：離職後競業禁止之約定，應以書面為之，且應詳細記載本法第9條之1第1項第3款（期間、區域、職業活動範圍及就業對象未逾合理範疇）及第4款（合理補償）規定之內容，並由雇主與勞工簽章，各執一份。本法第9條之1第4項並規定競業禁止期間最長不得逾二年。",
 "What formal requirements apply to a post-employment non-compete agreement?",
 ["In writing, detailing Article 9-1(1)(3) and (4) content, signed by both parties who each keep a copy","Orally agreed and stated in the work rules, binding all workers once posted and amendable at any time","In writing and filed for approval with the local authority, wholly void without such approval","Attached to the contract with union consent; the worker may withdraw consent before leaving"],
 "Rule 7-1: written, detailed, signed, one copy each."),

("OSH-49","第7條之2",3,"勞基細則-競業禁止",
 "競業禁止之約定未逾合理範疇，應符合之規定不包括下列何者？",
 ["競業禁止之補償金額應一次給付且不得低於勞工一年之平均工資總額","競業禁止之期間不得逾越所保護營業秘密或技術資訊之生命週期且最長不得逾二年","競業禁止之區域應以原雇主實際營業活動之範圍為限","競業禁止之職業活動範圍應具體明確且與勞工原職業活動範圍相同或類似"],"a",
 "施行細則第7條之2規定合理範疇之四款要件：期間不得逾越營業秘密或技術資訊之生命週期且最長不得逾二年、區域以原雇主實際營業活動範圍為限、職業活動範圍具體明確且與原職業活動相同或類似、就業對象具體明確並以與原雇主營業活動相同或類似且有競爭關係者為限。補償金額標準另規定於第7條之3。",
 "Which is NOT among the requirements for a reasonable non-compete scope?",
 ["Compensation must be paid in one lump sum of at least one year's total average wages","The period may not exceed the life cycle of the protected trade secret, and never over two years","The area is limited to the scope of the original employer's actual business activities","The activity scope must be specific and the same as or similar to the worker's former work"],
 "Rule 7-2 lists four scope requirements; the lump-sum figure is not one."),

("OSH-49","第7條之3",3,"勞基細則-合理補償",
 "離職後競業禁止之合理補償，其每月金額下限及給付方式為何？",
 ["每月補償金額不低於勞工離職時一個月平均工資百分之五十；應約定離職後一次預為給付或按月給付","每月補償金額不低於勞工離職時一個月平均工資百分之三十；應約定於競業禁止期間屆滿後一次給付","每月補償金額不低於基本工資之百分之六十；得由雇主自資遣費或退休金中扣抵後給付其餘額","每月補償金額不低於勞工在職期間平均獎金總額；並得以在職期間所受領之給付充抵之"],"a",
 "施行細則第7條之3：合理補償應綜合考量每月補償金額不低於勞工離職時一個月平均工資百分之五十、補償金額足以維持勞工離職後競業禁止期間之生活所需、補償金額與所受損失相當等事項；該合理補償應約定離職後一次預為給付或按月給付。本法第9條之1第2項並明定合理補償不包括勞工於工作期間所受領之給付。",
 "What is the monthly floor for non-compete compensation, and how is it paid?",
 ["At least 50 percent of one month's average wage on leaving; paid in advance in one sum or monthly","At least 30 percent of one month's average wage on leaving; paid in one sum after the period ends","At least 60 percent of the basic wage; the employer may offset it against severance or pension","At least the average bonus received while employed; payments during employment may count toward it"],
 "Rule 7-3: 50 percent floor, paid in advance in a lump sum or monthly."),

("OSH-49","第8條",1,"勞基細則-已刪除條文",
 "關於勞動基準法施行細則第八條，下列敘述何者正確？",
 ["該條業經刪除，現行細則已無該條之實體規定內容","該條規定雇主應於勞工離職時發給服務證明書","該條規定勞動契約應約定之十三款必要事項","該條規定勞工死亡時工資結清之受領順位"],"a",
 "施行細則第8條現為（刪除），已無實體規範內容。勞動契約應約定事項規定於第7條，終止契約應即結清工資規定於第9條，勞工死亡時工資結清及受領順位則規定於第16條。",
 "Which statement about Rule 8 of the Enforcement Rules is correct?",
 ["It has been deleted and no longer contains any substantive provision","It requires a service certificate to be issued when a worker leaves","It lists the thirteen matters a labor contract must cover","It sets the order of persons receiving wages when a worker dies"],
 "Rule 8 has been deleted."),

("OSH-49","第9條",1,"勞基細則-工資結清",
 "依本法終止勞動契約時，雇主對工資之處理義務為何？",
 ["雇主應即結清工資給付勞工","雇主應於終止後三十日內結清","雇主應於次月發薪日一併結清","雇主應俟勞工辦妥交接後結清"],"a",
 "施行細則第9條：依本法終止勞動契約時，雇主應即結清工資給付勞工。第16條並規定勞工死亡時雇主應即結清其工資給付其遺屬，受領順位準用本法第59條第4款；第22條之2、第24條之1並以本條作為契約終止時發給補休或特別休假未休工資之期限依據。",
 "What must the employer do about wages when the contract is terminated?",
 ["Settle and pay the wages immediately","Settle the wages within thirty days after","Settle them on the next monthly payday","Settle them after handover is completed"],
 "Rule 9: wages must be settled immediately on termination."),

("OSH-49","第11條",2,"勞基細則-基本工資",
 "本法第二十一條所稱基本工資之範圍為何？",
 ["指勞工在正常工作時間內所得之報酬，不包括延長工時、休息日、休假日及例假工作之加給","指勞工每月實際領得之工資總額，包括延長工時工資與休息日出勤加給在內","指勞工在正常工作時間內所得之報酬，並包括年終獎金及各項非經常性給與","指勞工前六個月工資總額除以總日數所得之平均工資，並以此作為基本工資之基準"],"a",
 "施行細則第11條：本法第21條所稱基本工資，指勞工在正常工作時間內所得之報酬，不包括延長工作時間之工資與休息日、休假日及例假工作加給之工資。第12條並規定計件工資之勞工所得基本工資以每日工作八小時之生產額或工作量換算，第13條規定每日工時少於八小時者得按比例計算。",
 "What does the basic wage under Article 21 cover?",
 ["Pay for normal working hours only, excluding overtime and rest-day, holiday and day-off premiums","The total wage actually received each month, including overtime pay and rest-day premiums","Pay for normal working hours, plus year-end bonuses and other non-regular payments","The average wage from the prior six months' total divided by the days in that period"],
 "Rule 11: normal working hours pay only, excluding premiums."),

("OSH-49","第12條",2,"勞基細則-計件工資",
 "採計件工資之勞工，其所得基本工資應如何換算？",
 ["以每日工作八小時之生產額或工作量換算之","以每日工作十小時之生產額或工作量換算之","以每月平均生產額除以三十日之結果換算之","以同職類勞工平均產量之八成作為換算基準"],"a",
 "施行細則第12條：採計件工資之勞工所得基本工資，以每日工作八小時之生產額或工作量換算之。第13條並規定勞工工作時間每日少於八小時者，除工作規則、勞動契約另有約定或另有法令規定外，其基本工資得按工作時間比例計算之。",
 "How is the basic wage converted for piece-rate workers?",
 ["By the output or workload of an eight-hour working day","By the output or workload of a ten-hour working day","By dividing the average monthly output by thirty days","By eighty percent of the average output of peers"],
 "Rule 12: converted by the output of an eight-hour day."),

("OSH-49","第13條",2,"勞基細則-部分工時",
 "勞工每日工作時間少於八小時者，其基本工資應如何計算？有無例外？",
 ["得按工作時間比例計算；但工作規則、勞動契約另有約定或另有法令規定者從其規定","應仍按全時勞工基本工資全額給付；不得因工作時間較短而按比例減少其金額","應按工作時間比例計算並再加給三分之一；且不得以契約約定排除本項規定","得由雇主自行決定給付比例；惟不得低於全時勞工基本工資之二分之一為限"],"a",
 "施行細則第13條：勞工工作時間每日少於八小時者，除工作規則、勞動契約另有約定或另有法令規定者外，其基本工資得按工作時間比例計算之。第12條則規定計件工資以每日八小時之生產額或工作量換算基本工資。",
 "How is the basic wage calculated for workers with fewer than eight daily hours?",
 ["Pro rata by hours worked, unless work rules, the contract or another law provides otherwise","Paid in full at the full-time basic wage; it may not be reduced in proportion to shorter hours","Pro rata by hours worked plus one third extra; no contract term may exclude this rule","Set freely by the employer, provided it is at least half the full-time basic wage"],
 "Rule 13: pro rata, subject to contrary rules, contract or law."),

("OSH-49","第14條",1,"勞基細則-已刪除條文",
 "關於勞動基準法施行細則第十四條，下列敘述何者正確？",
 ["該條業經刪除，現行細則已無該條之實體規定內容","該條規定工資各項目計算方式明細應包括之事項","該條規定積欠工資以歇業前六個月內所積欠者為限","該條規定計件工資勞工基本工資之換算方式"],"a",
 "施行細則第14條現為（刪除），已無實體規範內容。工資各項目計算方式明細之應載事項規定於第14條之1，積欠工資以歇業、清算或宣告破產前六個月內所積欠者為限規定於第15條，計件工資換算則規定於第12條。",
 "Which statement about Rule 14 of the Enforcement Rules is correct?",
 ["It has been deleted and no longer contains any substantive provision","It lists what an itemized wage calculation statement must include","It limits wage arrears to those from the six months before closure","It sets out how the basic wage is converted for piece-rate work"],
 "Rule 14 has been deleted."),

("OSH-49","第14條之1",3,"勞基細則-工資明細",
 "本法第二十三條所定工資各項目計算方式明細，應包括之事項及提供方式為何？",
 ["應包括工資總額、各項目給付金額、得扣除項目金額及實際發給金額；得以紙本或電子資料傳輸等方式提供","應包括工資總額及實際發給金額二項即可；且限以紙本方式於發薪日當面交付勞工簽名收執","應包括工資總額、各項目給付金額及勞工保險費用明細；並應同時報送當地主管機關核備","應包括工資總額、獎金紅利及加班時數統計表；得僅於勞工提出書面請求時始行提供之"],"a",
 "施行細則第14條之1：本法第23條所定工資各項目計算方式明細，應包括勞雇雙方議定之工資總額、工資各項目之給付金額、依法令規定或勞雇雙方約定得扣除項目之金額、實際發給之金額等四項；雇主提供之明細得以紙本、電子資料傳輸方式或其他勞工可隨時取得及得列印之資料為之。",
 "What must an itemized wage statement include, and how may it be provided?",
 ["Total wages, each item's amount, deductible amounts and the sum actually paid; on paper or in electronic form","Only the total wages and the sum actually paid; and only on paper handed over and signed for on payday","Total wages, each item's amount and labor insurance details; and it must also be filed with the local authority","Total wages, bonuses and overtime hour statistics; and only when the worker makes a written request"],
 "Rule 14-1: four required items, deliverable on paper or electronically."),
]
