# -*- coding: utf-8 -*-
# 第 9 批（E1）：逐條補齊──土壤污染監測標準、地下水污染監測標準、防止貯存系統污染地下水體設施及監測設備設置管理辦法
SM = "ENV-80"; GM = "ENV-81"; ST = "ENV-83"

Q = [
# ---------- 土壤污染監測標準 ----------
(SM,"第1條",1,"土壤監測-法源",
 "土壤污染監測標準係依何項法律規定訂定？",
 ["依土壤及地下水污染整治法第六條第二項規定訂定",
  "依水污染防治法第三十三條第二項規定訂定之",
  "依環境基本法第八條第一項規定所訂定者",
  "依廢棄物清理法第三十六條規定訂定之"],"a",
 "第1條：本標準依土壤及地下水污染整治法第六條第二項規定訂定之。同法第6條第2項授權中央主管機關訂定土壤及地下水污染監測標準；地下水污染監測標準第1條亦以同一條項為法源。",
 "Under which statutory provision were the Soil Pollution Monitoring Standards issued?",
 ["Article 6, paragraph 2 of the Soil and Groundwater Pollution Remediation Act",
  "Article 33, paragraph 2 of the Water Pollution Control Act as amended",
  "Article 8, paragraph 1 of the Basic Environment Act of the country",
  "Article 36 of the Waste Disposal Act governing contaminated sites"],
 "Article 1."),

(SM,"第2條",2,"土壤監測-背景例外",
 "土壤中物質濃度受區域土壤地質條件及環境背景因素影響而達標準值者，應如何處理？",
 ["經具體科學性數據研判非因外來污染者，得經中央主管機關同意後不適用本標準",
  "經具體科學性數據研判非因外來污染者，得逕由事業自行決定不適用本標準",
  "經具體科學性數據研判非因外來污染者，仍應依標準值辦理污染查證作業",
  "經目的事業主管機關研判後，得將該項目之監測標準值調高為二倍適用"],"a",
 "第2條：本標準所列土壤中物質濃度，受區域土壤地質條件及環境背景因素影響，經具體科學性數據研判非因外來污染而達本標準所列污染物項目之監測值，得經中央主管機關同意後，不適用本標準。地下水污染監測標準第2條就水文地質條件亦有相同之例外規定。",
 "How are levels caused by regional geology and environmental background handled?",
 ["If scientific data show they are not from external pollution, the standard may be waived with central authority consent",
  "If scientific data show they are not from external pollution, the enterprise may decide by itself not to apply it",
  "If scientific data show they are not from external pollution, verification under the standard must still proceed",
  "If the industry competent authority so determines, that item's monitoring value may be doubled when applied"],
 "Article 2."),

(SM,"第6條",1,"土壤監測-施行",
 "土壤污染監測標準之施行日期如何規定？",
 ["本標準自發布日施行，未另定緩衝期間",
  "本標準自發布後六個月施行，並溯及既往",
  "本標準自發布後一年施行，分階段適用",
  "本標準自次年一月一日施行，不溯及既往"],"a",
 "第6條：本標準自發布日施行。相對地，地下水污染監測標準第7條除規定自發布日施行外，並定其一百零二年十二月十八日修正之條文自一百零三年一月一日施行。",
 "When did the Soil Pollution Monitoring Standards take effect?",
 ["On the date of promulgation, with no buffer period provided",
  "Six months after promulgation, and with retroactive effect",
  "One year after promulgation, applied in phased stages",
  "On January 1 of the following year, with no retroactivity"],
 "Article 6."),

# ---------- 地下水污染監測標準 ----------
(GM,"第1條",1,"地下水監測-法源",
 "地下水污染監測標準係依何項法律規定訂定？",
 ["依土壤及地下水污染整治法第六條第二項規定訂定",
  "依水污染防治法第二十八條第一項規定訂定之",
  "依飲用水管理條例第十一條規定所訂定者",
  "依環境影響評估法第六條第二項規定訂定"],"a",
 "第1條：本標準依土壤及地下水污染整治法第六條第二項規定訂定之。土壤污染監測標準第1條亦以同一授權條項為法源，二標準均屬同法第6條第2項授權訂定之監測標準。",
 "Under which statutory provision were the Groundwater Pollution Monitoring Standards issued?",
 ["Article 6, paragraph 2 of the Soil and Groundwater Pollution Remediation Act",
  "Article 28, paragraph 1 of the Water Pollution Control Act as amended",
  "Article 11 of the Drinking Water Management Act on source areas",
  "Article 6, paragraph 2 of the Environmental Impact Assessment Act"],
 "Article 1."),

(GM,"第2條",2,"地下水監測-背景例外",
 "地下水中物質濃度受區域水文地質條件及環境背景因素影響而達標準值者，應如何處理？",
 ["經研判非因外來污染者，得經中央主管機關同意後不適用本標準所列之監測標準值",
  "經研判非因外來污染者，得由檢驗測定機構逕行註記後免列入監測結果報告中",
  "經研判非因外來污染者，仍應全數列入污染調查及查證程序辦理後續改善作業",
  "經直轄市主管機關研判後，該區域之地下水得逕行由第一類變更改列為第二類"],"a",
 "第2條：本標準所列地下水中物質濃度，受區域水文地質條件及環境背景因素影響，經研判非因外來污染而達本標準所列污染物項目之監測值，得經中央主管機關同意後，不適用本標準。此與土壤污染監測標準第2條之背景例外規定相同。",
 "How are groundwater levels caused by regional hydrogeology and background handled?",
 ["If judged not to come from external pollution, the values may be waived with central authority consent",
  "If judged not to come from external pollution, the testing organization may simply note and omit them",
  "If judged not to come from external pollution, they must still enter pollution investigation procedures",
  "If the municipal authority so judges, that area's groundwater may be reclassified from class 1 to class 2"],
 "Article 2."),

(GM,"第6條",1,"地下水監測-修正參考",
 "何者得提出具體科學性數據、資料，供中央主管機關作為地下水污染監測標準修正之參考？",
 ["事業及其所屬公會或環境保護相關團體得提出具體科學性數據及資料",
  "僅限中央目的事業主管機關及各級地方政府得提出相關科學性數據",
  "僅限經認證之學術研究機構及檢驗測定機構得提出相關科學數據",
  "僅限自來水事業及飲用水水源管理機關得提出相關之科學性資料"],"a",
 "第6條：事業及其所屬公會或環境保護相關團體得提出具體科學性數據、資料，供中央主管機關作為本標準修正之參考。土壤污染監測標準第5條亦有相同規定，二者均開放事業、公會及環保團體參與標準檢討。",
 "Who may submit scientific data as reference for revising these standards?",
 ["Enterprises, their guilds, and environmental protection related groups may submit concrete scientific data",
  "Only central industry competent authorities and local governments may submit such scientific data",
  "Only accredited academic institutions and licensed testing organizations may submit such data",
  "Only water supply utilities and drinking water source agencies may submit such scientific data"],
 "Article 6."),

(GM,"第7條",2,"地下水監測-施行日",
 "地下水污染監測標準之施行日期，以及一百零二年十二月十八日修正條文之施行日期各為何？",
 ["本標準自發布日施行；一百零二年十二月十八日修正之條文，自一百零三年一月一日施行",
  "本標準自發布日施行；一百零二年十二月十八日修正之條文，自一百零四年七月一日施行",
  "本標準自發布後六個月施行；一百零二年十二月十八日修正之條文，自發布日即行施行",
  "本標準自發布後一年施行；一百零二年十二月十八日修正之條文，自一百零五年起施行"],"a",
 "第7條：本標準自發布日施行；本標準中華民國一百零二年十二月十八日修正之條文，自一百零三年一月一日施行。此與土壤污染監測標準第6條僅規定自發布日施行不同，該次修正另定緩衝生效日。",
 "When do these standards and their December 18, 2013 amendments take effect?",
 ["The standards take effect on promulgation; the 2013 amendments take effect on January 1, 2014",
  "The standards take effect on promulgation; the 2013 amendments take effect on July 1, 2015",
  "The standards take effect six months after promulgation; the amendments take effect on promulgation",
  "The standards take effect one year after promulgation; the amendments take effect from 2016 onward"],
 "Article 7."),

# ---------- 防止貯存系統污染地下水體設施及監測設備設置管理辦法 ----------
(ST,"第1條",1,"貯存系統-法源",
 "防止貯存系統污染地下水體設施及監測設備設置管理辦法之訂定法源為何？",
 ["依水污染防治法第三十三條第二項及第三項規定訂定",
  "依水污染防治法第二十八條第一項及第二項規定訂定",
  "依土壤及地下水污染整治法第六條第二項規定訂定",
  "依土壤及地下水污染整治法第九條第一項規定訂定"],"a",
 "第1條：本辦法依水污染防治法（本法）第三十三條第二項及第三項規定訂定之。本法第33條第1項授權中央主管機關公告指定物質，第2項、第3項則授權訂定防止污染地下水體設施及監測設備之設置管理事項。第29條所定三小時通報義務即依本法第28條辦理。",
 "Under which provisions was this storage system regulation issued?",
 ["Article 33, paragraphs 2 and 3 of the Water Pollution Control Act",
  "Article 28, paragraphs 1 and 2 of the Water Pollution Control Act",
  "Article 6, paragraph 2 of the Soil and Groundwater Remediation Act",
  "Article 9, paragraph 1 of the Soil and Groundwater Remediation Act"],
 "Article 1."),

(ST,"第3條",2,"貯存系統-排除適用",
 "下列何種設備及其附屬儲槽、輸送設備，非本辦法所稱之貯存系統？",
 ["廢（污）水處理設施、石化製程、公共設施管線、設於公共使用土地之石油管線及廠區外工廠設備",
  "加油站地下儲槽、工廠鍋爐用油儲槽、發電機日用油槽、化學品倉庫及實驗室溶劑貯存櫃等",
  "容積達六百公升以上之貯存容器、雙層槽地下儲槽、具二次阻隔層之輸送設備及槽間監測井",
  "位於工業區內之地上儲槽、已投保責任險之儲槽、公營事業所屬儲槽及軍事單位所屬儲槽"],"a",
 "第3條第1項：水污染防治法所稱廢（污）水處理設施、揮發性有機物空氣污染管制及排放標準所稱石化製程、共同管道法所稱公共設施管線、石油管理法所稱石油管線並設置於公共使用之土地者、工廠管理輔導法所稱廠區外工廠設備，均非本辦法所稱之貯存系統。第3條第2項：貯存容器貯存經登記廢棄之毒性化學物質，不受本辦法之限制。",
 "Which facilities are excluded from the definition of a storage system?",
 ["Wastewater treatment facilities, petrochemical processes, utility conduits, public land oil pipelines, off site factory equipment",
  "Gas station underground tanks, boiler fuel tanks, generator day tanks, chemical warehouses and laboratory solvent cabinets",
  "Containers of 600 liters or more, double wall underground tanks, piping with secondary containment and interstitial wells",
  "Above ground tanks in industrial parks, insured tanks, tanks of state owned enterprises and tanks of military units"],
 "Article 3."),

(ST,"第5條",2,"貯存系統-完工報告書",
 "事業新設或更新地下儲槽系統，其完工報告書之提送規定為何？",
 ["新設者於施工完成後檢具完工報告書送地方主管機關備查；更新者於施工完成日之次日起三十日內提送",
  "新設者於施工完成前檢具完工報告書送中央主管機關核准；更新者於施工完成日之次日起七日內提送",
  "新設者於施工完成後檢具完工報告書送目的事業主管機關核備；更新者於施工完成後一年內提送即可",
  "新設者於開工前檢具完工報告書送地方主管機關備查；更新者於施工完成日之次日起九十日內提送"],"a",
 "第5條第1項：事業新設地下儲槽系統於施工完成後，應檢具完工報告書送直轄市、縣（市）主管機關備查。第5條第3項：更新地下儲槽系統者，於施工完成日之次日起算三十日內檢具更新完工報告書送備查。第5條第4項：報告書內容與經備查之計畫書不符時，應檢附變更內容對照表並敘明理由；第5項並應以網路傳輸方式為之。",
 "What rules govern completion reports for new or renewed underground tank systems?",
 ["New systems file after construction with the local authority; renewals file within thirty days after completion",
  "New systems file before construction ends for central approval; renewals file within seven days after completion",
  "New systems file after construction with the industry authority; renewals may file within one year after completion",
  "New systems file before construction starts with the local authority; renewals file within ninety days after completion"],
 "Article 5."),

(ST,"第7條",3,"貯存系統-地下防污設施",
 "地下儲槽系統之防止污染地下水體設施，其防蝕或防滲漏措施應採取何種方法之一？",
 ["使用非腐蝕材料建造、使用鋼材建造者包覆不導電物質並裝設陰極防蝕系統，或使用二次阻隔層保護",
  "使用一般碳鋼建造並每年塗裝油漆、加裝電子式警報器，或於槽體外圍堆置乾砂作為隔離之保護層",
  "使用非腐蝕材料建造並外覆混凝土、每三年更換槽體襯裡，或於槽底加設集水坑並定期抽水檢查",
  "使用不鏽鋼建造且埋設深度達三公尺以上、加裝防爆閥，或以惰性氣體充填槽體上部空間保護"],"a",
 "第7條第1項第2款：地下儲槽系統應依下列方法之一防蝕或防滲漏：使用非腐蝕材料建造、使用鋼材建造者包覆適當之不導電物質並裝設陰極防蝕系統、使用二次阻隔層保護。同項並要求加注口裝設防止濺溢設施、壓力式輸送設備設自動監測設備、加油機底部設防滲漏設施、新設更新之輸送設備設二次阻隔層。第7條第2項：一百年一月十三日前已設置並取得經營許可者，除更新外得不受陰極防蝕之限制。",
 "Which anti corrosion or anti leak methods may an underground tank system adopt?",
 ["Non corrosive materials, or steel with dielectric coating plus a cathodic protection system, or secondary containment",
  "Ordinary carbon steel repainted yearly, an electronic alarm added, or dry sand piled around the tank as insulation",
  "Non corrosive material wrapped in concrete, liners replaced every three years, or a sump pumped and checked regularly",
  "Stainless steel buried at least three meters deep, an explosion valve added, or inert gas filling the tank headspace"],
 "Article 7."),

(ST,"第8條",3,"貯存系統-總量進出管制",
 "地下儲槽系統之總量進出管制，其實施方式及設施規定為何？",
 ["設置儲槽自動液面計且量測範圍涵蓋底部至頂部、每日記錄進出量及存量、進出物質前後量測、每月人工量測液位一次以上",
  "設置儲槽自動液面計且量測範圍涵蓋中段液位、每週記錄進出量及存量、進出物質前後估算、每季人工量測液位一次以上",
  "設置壓力式流量計且量測範圍涵蓋管線全段、每月記錄進出量及存量、進出物質後量測、每年人工量測液位一次以上",
  "設置儲槽自動液面計且量測範圍涵蓋底部至頂部、每季記錄進出量及存量、進出物質前量測、每半年人工量測一次"],"a",
 "第8條第1項：地下儲槽系統應設置儲槽自動液面計，其量測範圍至少涵蓋儲槽內底部至頂部之距離；每日記錄進出量及儲槽存量；進出物質前、後量測並記錄儲槽內之存量容積；每月以量尺採人工量測方式記錄儲槽液位與槽底水位一次以上。第8條第2項：九十五年七月六日前之地下儲槽系統未設自動液面計者，除更新地下儲槽外得採人工量測方式辦理。",
 "What inventory control measures apply to underground tank systems?",
 ["An automatic gauge covering bottom to top, daily records of throughput and stock, measurement before and after each transfer, monthly manual gauging",
  "An automatic gauge covering the mid level range, weekly records of throughput and stock, estimation before and after transfers, quarterly manual gauging",
  "A pressure flow meter covering the whole pipeline, monthly records of throughput and stock, measurement after transfers only, annual manual gauging",
  "An automatic gauge covering bottom to top, quarterly records of throughput and stock, measurement before transfers only, semiannual manual gauging"],
 "Article 8."),

(ST,"第9條",2,"貯存系統-監測方式",
 "地下儲槽系統得採行之監測方式有哪些？其監測人員資格為何？",
 ["密閉測試、土壤氣體監測、地下水監測、槽間監測或其他中央主管機關核准之方式；監測人員須訓練合格並領有證書",
  "目視巡查、壓力測試、油品品質檢驗、帳面盤點或其他地方主管機關核准之方式；監測人員由事業自行指派即可",
  "密閉測試、土壤氣體監測、地下水監測、空氣品質監測或其他目的事業主管機關核准之方式；監測人員須具技師資格",
  "密閉測試、槽間監測、噪音振動監測、地表沉陷監測或其他經環評委員會核准之方式；監測人員須為專責人員擔任"],"a",
 "第9條第1項：地下儲槽系統應依密閉測試、土壤氣體監測、地下水監測、槽間監測或其他中央主管機關核准之監測方式之一進行監測並記錄，監測範圍應包含儲槽區、輸送區。第9條第3項：監測人員應由經中央主管機關或委託之機構訓練合格並領有證書之人員為之。第9條第2項：地方主管機關得視地震、地質、迷失電流等因素增加監測頻率並報中央備查；第4項委託監測應於五日前通知。",
 "Which monitoring methods may an underground tank system use, and who may perform them?",
 ["Tightness testing, soil gas, groundwater, interstitial monitoring or another approved method; personnel must be trained and certified",
  "Visual patrol, pressure testing, fuel quality testing, book inventory or another locally approved method; any assigned staff may do it",
  "Tightness testing, soil gas, groundwater, air quality monitoring or another industry approved method; personnel must be licensed engineers",
  "Tightness testing, interstitial, noise and vibration, subsidence monitoring or an EIA approved method; only dedicated personnel may do it"],
 "Article 9."),

(ST,"第10條",2,"貯存系統-免監測",
 "地下儲槽系統配置之輸送設備，於何種情形下得免依規定進行監測？",
 ["配置吸取式輸送設備且負壓消失時物質能回流、每段僅有一單向閥、單向閥低於幫浦；或可隨時目視且未接觸土壤地下水",
  "配置吸取式輸送設備且設有二個以上單向閥、單向閥高於幫浦、加裝流量計；或每年委託機構實施一次密閉測試者",
  "配置壓力式輸送設備且裝設自動流量限制設備、連續警報設備、緊急遮斷閥；或已投保環境污染責任保險者亦同",
  "配置任何輸送設備但埋設深度未達一公尺、周圍以混凝土包覆、每月自行巡查一次；或已通過環境影響評估審查者"],"a",
 "第10條：地下儲槽系統配置之輸送設備符合下列情形之一者免依第9條進行監測：配置吸取式輸送設備且負壓消失時輸送設備內之物質能回流至儲槽內、每段輸送設備僅有一單向閥、單向閥低於吸取式幫浦；或輸送設備可隨時以目視檢查且周圍未直接接觸土壤及地下水環境。第7條第1項第5款對後者亦免設二次阻隔層。",
 "When is piping of an underground tank system exempt from monitoring?",
 ["Suction piping where product drains back on vacuum loss, one check valve per run, the valve below the pump; or visible piping not touching soil",
  "Suction piping with two or more check valves, the valve above the pump, a flow meter added; or piping tightness tested once each year",
  "Pressurized piping with automatic flow limiting, continuous alarms and an emergency shut off valve; or a pollution liability policy held",
  "Any piping buried under one meter, encased in concrete and patrolled monthly; or a project that has passed environmental impact review"],
 "Article 10; Article 7(1)(5)."),

(ST,"第12條",3,"貯存系統-土壤氣體監測",
 "地下儲槽系統以土壤氣體監測者，其監測井規格、頻率及研判值為何？",
 ["透氣度小於錶壓五百毫米汞柱、監測半徑不得大於五公尺；自行每月一次、委託每四個月一次；爆炸下限值大於百分之二十五",
  "透氣度小於錶壓一百毫米汞柱、監測半徑不得大於十公尺；自行每季一次、委託每半年一次；爆炸下限值大於百分之五十",
  "透氣度小於錶壓一千毫米汞柱、監測半徑不得大於三公尺；自行每週一次、委託每二個月一次；爆炸下限值大於百分之十",
  "透氣度小於錶壓五百毫米汞柱、監測半徑不得大於二十公尺；自行每年一次、委託每三年一次；爆炸下限值大於百分之四十"],"a",
 "第12條第1項第4、5款：土壤氣體監測井應符合透氣度小於錶壓五百毫米汞柱，並標記加蓋，其監測範圍以監測井為中心半徑不得大於五公尺。第12條第2項：自行監測每月監測爆炸下限值百分比或揮發性有機氣體濃度一次，委託監測每四個月以光離子及火焰離子偵測器監測油氣濃度一次。第12條第3項：爆炸下限值大於百分之二十五或檢測值大於百萬分之五百體積比者得進行污染調查。第4項並定不得採用之情形。",
 "What well specification, frequency and action level apply to soil gas monitoring?",
 ["Permeability under 500 mmHg gauge, radius at most five meters; monthly self and four monthly commissioned checks; LEL above 25 percent",
  "Permeability under 100 mmHg gauge, radius at most ten meters; quarterly self and semiannual commissioned checks; LEL above 50 percent",
  "Permeability under 1,000 mmHg gauge, radius at most three meters; weekly self and bimonthly commissioned checks; LEL above 10 percent",
  "Permeability under 500 mmHg gauge, radius at most twenty meters; annual self and triennial commissioned checks; LEL above 40 percent"],
 "Article 12."),

(ST,"第14條",3,"貯存系統-槽間監測",
 "地下儲槽系統以槽間監測者，其外層阻隔物材質及監測頻率規定為何？",
 ["外層阻隔物使用滲透係數小於十的負六次方公分／秒之材質、高於地下水位且與貯存物相容；自行每月一次、委託每四個月一次",
  "外層阻隔物使用滲透係數小於十的負三次方公分／秒之材質、低於地下水位且與貯存物相容；自行每季一次、委託每半年一次",
  "外層阻隔物使用滲透係數小於十的負九次方公分／秒之材質、高於地表面且與貯存物相容；自行每週一次、委託每二個月一次",
  "外層阻隔物使用滲透係數小於十的負六次方公分／秒之材質、高於地下水位且與貯存物相容；自行每年一次、委託每三年一次"],"a",
 "第14條第1項第1款：具二次阻隔層保護之地下儲槽系統，其外層阻隔物應使用滲透係數小於10的負6次方公分／秒之材質建造，高於地下水位且與儲槽內貯存物質相容，具陰極防蝕系統者其外層阻隔物設計不得妨礙該系統正常操作，槽間監測井並應標記加蓋。第14條第2項：自行監測每月監測滲漏物質一次，委託監測每四個月一次。",
 "What barrier material and frequency apply to interstitial monitoring?",
 ["Outer barrier with permeability below 1e-6 cm/s, above the water table and compatible; monthly self and four monthly commissioned checks",
  "Outer barrier with permeability below 1e-3 cm/s, below the water table and compatible; quarterly self and semiannual commissioned checks",
  "Outer barrier with permeability below 1e-9 cm/s, above ground level and compatible; weekly self and bimonthly commissioned checks",
  "Outer barrier with permeability below 1e-6 cm/s, above the water table and compatible; annual self and triennial commissioned checks"],
 "Article 14."),

(ST,"第15條",2,"貯存系統-其他監測方式",
 "事業申請採用第九條第一項第五款之其他監測方式，應檢附哪些文件並向何機關申請？",
 ["應檢附登記證明及負責人身分證明、認證機構認證之測試成果報告、品保品管規劃書，報經中央主管機關核准後始得為之",
  "應檢附登記證明及負責人身分證明、監測人員訓練合格證書、環境影響說明書，報經地方主管機關備查後即得為之",
  "應檢附登記證明及土地權狀影本、儲槽竣工圖說、洩漏應變計畫，報經目的事業主管機關核轉中央主管機關核准",
  "應檢附登記證明及財力證明文件、國外原廠型錄、保險單影本，報經檢驗測定機構審查同意後函報中央機關備查"],"a",
 "第15條第1項：申請第9條第1項第5款之監測方式者，應檢附公司或商業登記證明文件影本及負責人身分證明文件影本、經認證機構認證之監測方式測試成果報告、品保品管規劃書，引進國外認證方法者並應檢具原文認證文件及經駐外機構驗證之中文譯本（原文為英文者免附），報經中央主管機關核准後始得為之。第15條第2項：其實施頻率、記錄、方法及設施標準依核准內容為之。",
 "What documents are needed to use another monitoring method, and who approves it?",
 ["Registration and identity documents, an accredited test result report and a QA/QC plan, approved by the central authority beforehand",
  "Registration and identity documents, training certificates of monitors and an impact statement, filed with the local authority",
  "Registration and land title documents, as built drawings and a leak response plan, forwarded by the industry authority",
  "Registration and financial documents, foreign catalogs and an insurance policy, agreed by a testing organization first"],
 "Article 15."),

(ST,"第17條",2,"貯存系統-地下適用日",
 "地下儲槽系統應依第八條至第十六條規定進行監測、記錄及申報之起始日期為何？",
 ["貯存汽油、柴油並依第三十二條改善完成者自一百十二年一月一日起；貯存其他指定物質者自一百十六年一月一日起",
  "貯存汽油、柴油並依第三十二條改善完成者自一百十四年一月一日起；貯存其他指定物質者自一百十八年一月一日起",
  "貯存汽油、柴油並依第三十二條改善完成者自一百十年一月一日起；貯存其他指定物質者自一百十二年一月一日起",
  "貯存汽油、柴油並依第三十二條改善完成者自一百十六年一月一日起；貯存其他指定物質者自一百二十年一月一日起"],"a",
 "第17條：貯存汽油、柴油並依第32條改善完成之地下儲槽系統，自一百十二年一月一日起應依第8條至第16條規定進行監測、記錄及申報；貯存汽油、柴油以外指定物質之地下儲槽系統，自一百十六年一月一日起適用。第27條就地上儲槽系統另定一百十二年、一百十四年及一百十六年之分階段適用日期。",
 "From when must underground tank systems monitor, record and report under Articles 8 to 16?",
 ["Gasoline and diesel systems improved under Article 32 from January 1, 2023; other designated substances from January 1, 2027",
  "Gasoline and diesel systems improved under Article 32 from January 1, 2025; other designated substances from January 1, 2029",
  "Gasoline and diesel systems improved under Article 32 from January 1, 2021; other designated substances from January 1, 2023",
  "Gasoline and diesel systems improved under Article 32 from January 1, 2027; other designated substances from January 1, 2031"],
 "Article 17; Article 27 for above ground systems."),

(ST,"第19條",2,"貯存系統-地上總量管制",
 "地上儲槽系統之總量進出管制規定為何？何種情形應設置儲槽自動液面計？",
 ["採人工量測或設置儲槽液面計、每次或每日記錄進出量及存量、進出前後量測；儲槽容積達一千公秉以上者應設自動液面計",
  "一律應設置儲槽自動液面計、每週記錄進出量及存量、進出後量測；儲槽容積達一百公秉以上者應另設置高液位警報設備",
  "採人工量測或設置儲槽液面計、每月記錄進出量及存量、進出前量測；儲槽容積達一萬公秉以上者應設置自動液面計",
  "採目視巡查或設置壓力計、每季記錄進出量及存量、進出前後估算；儲槽容積達五百公秉以上者應設置自動液面計"],"a",
 "第19條第1項：地上儲槽系統應採人工量測方式或設置儲槽液面計（量測範圍至少涵蓋儲槽內底部至頂部），每次或每日記錄進出量及儲槽存量，並於進出物質前、後量測並記錄存量容積。第19條第2項：儲槽容積達一千公秉以上者，應設置儲槽自動液面計進行總量進出管制。第18條第1項第4款並要求容積達一千公秉以上者設高液位警報設備。",
 "What inventory control applies to above ground tank systems, and when is an automatic gauge required?",
 ["Manual gauging or a tank gauge, records per transfer or daily, measurement before and after; an automatic gauge at 1,000 kL or more",
  "An automatic gauge in all cases, weekly records, measurement after transfers; a high level alarm also required at 100 kL or more",
  "Manual gauging or a tank gauge, monthly records, measurement before transfers; an automatic gauge at 10,000 kL or more",
  "Visual patrol or a pressure gauge, quarterly records, estimation before and after; an automatic gauge at 500 kL or more"],
 "Article 19; Article 18(1)(4)."),

(ST,"第20條",3,"貯存系統-地上監測方式",
 "地上儲槽系統依儲槽容積不同，得採行之監測方式各為何？",
 ["容積未達一千公秉者得採密閉測試、土壤氣體監測或地下水監測；容積達一千公秉以上者僅得採土壤氣體監測或地下水監測",
  "容積未達一千公秉者僅得採密閉測試；容積達一千公秉以上者得採密閉測試、土壤氣體監測、地下水監測或槽間監測",
  "容積未達一萬公秉者得採密閉測試或槽間監測；容積達一萬公秉以上者僅得採地下水監測並應每月委託機構辦理一次",
  "容積未達一千公秉者得採目視巡查替代監測；容積達一千公秉以上者得採密閉測試、土壤氣體監測或空氣品質監測"],"a",
 "第20條第1項：地上儲槽系統儲槽容積未達一千公秉者，得採密閉測試、土壤氣體監測或地下水監測；容積達一千公秉以上者，僅得採土壤氣體監測或地下水監測，監測範圍應包含儲槽區、輸送區。第20條第2項：更換儲存物質時得依相關法規實施外部及內部檢查。第20條第4、5項：監測人員須訓練合格領證，委託監測應於五日前通知地方主管機關。",
 "Which monitoring methods may an above ground tank system use, by tank volume?",
 ["Under 1,000 kL may use tightness testing, soil gas or groundwater monitoring; at 1,000 kL or more only soil gas or groundwater",
  "Under 1,000 kL may use tightness testing only; at 1,000 kL or more may use tightness, soil gas, groundwater or interstitial",
  "Under 10,000 kL may use tightness testing or interstitial monitoring; at 10,000 kL or more only monthly commissioned groundwater",
  "Under 1,000 kL may substitute visual patrol for monitoring; at 1,000 kL or more may use tightness, soil gas or air quality"],
 "Article 20."),

(ST,"第21條",2,"貯存系統-地上免監測",
 "地上儲槽系統於何種情形下得免依第二十條規定進行監測？",
 ["儲槽可隨時以目視檢查底部、輸送設備可隨時目視且周圍未直接接觸土壤及地下水環境，或儲槽、輸送設備定著於建築物",
  "儲槽已設置高液位警報設備、輸送設備已設置二次阻隔層並每年檢查一次，或儲槽容積未達一百公秉且已投保責任保險",
  "儲槽已通過環境影響評估審查、輸送設備已取得目的事業主管機關核准，或儲槽設置於工業區內並由專責人員每日巡查",
  "儲槽已完成密閉測試並取得合格報告、輸送設備採用不鏽鋼材質建造，或儲槽底部已鋪設厚度十公分以上之混凝土層"],"a",
 "第21條：地上儲槽系統符合儲槽可隨時以目視檢查底部、輸送設備可隨時以目視檢查且周圍未直接接觸土壤及地下水環境、儲槽或輸送設備定著於建築物等情形之一者，免依第20條規定進行監測。第25條第3項：依第21條免監測者，亦免依第25條第1項規定進行申報。",
 "When is an above ground tank system exempt from the monitoring requirement?",
 ["The tank bottom can be visually inspected at any time, piping is visible and not touching soil or groundwater, or it is fixed to a building",
  "A high level alarm is installed, piping has secondary containment inspected yearly, or the tank is under 100 kL and insured",
  "The project passed environmental impact review, piping was approved by the industry authority, or a patrol is done daily in a park",
  "A tightness test was passed, the piping is built of stainless steel, or the tank bottom rests on ten centimeters of concrete"],
 "Article 21; Article 25(3)."),

(ST,"第22條",2,"貯存系統-地上密閉測試",
 "地上儲槽系統以密閉測試方式監測者，其頻率及得替代之方式為何？",
 ["儲槽每三年一次、輸送設備每年一次，均應委託許可之檢驗測定機構；儲槽密閉測試得以外部及內部檢查替代並作成紀錄",
  "儲槽每年一次、輸送設備每三年一次，均得由事業自行實施；儲槽密閉測試得以每月之目視巡查紀錄替代並作成紀錄",
  "儲槽每五年一次、輸送設備每二年一次，均應委託許可之檢驗測定機構；儲槽密閉測試不得以任何其他檢查方式替代",
  "儲槽每六個月一次、輸送設備每季一次，均應由地方主管機關派員辦理；儲槽密閉測試得以土壤氣體監測結果替代之"],"a",
 "第22條第1項：地上儲槽系統以密閉測試監測者，應委託中央主管機關核發許可證之檢驗測定機構，儲槽每三年一次、輸送設備每年一次。第22條第3項：儲槽密閉測試之實施方式及頻率得依第20條第2項之外部及內部檢查替代，並依該檢查結果作成監測紀錄。第22條第2項之研判值與第11條第2項地下儲槽系統相同。",
 "What frequency applies to tightness testing of above ground tanks, and what may replace it?",
 ["Tanks every three years and piping every year by a licensed organization; external and internal inspection may replace tank testing",
  "Tanks every year and piping every three years, performed by the enterprise itself; monthly visual patrol records may replace it",
  "Tanks every five years and piping every two years by a licensed organization; no other inspection may replace the tank testing",
  "Tanks every six months and piping quarterly, performed by the local authority; soil gas monitoring results may replace it"],
 "Article 22."),

(ST,"第23條",2,"貯存系統-地上土壤氣體",
 "地上儲槽系統以土壤氣體監測者，其監測井位置有何特別限制？",
 ["監測井之數量及位置依開挖區範圍等決定，並不得設置於第十八條第一項第三款所定之防止濺溢設施內",
  "監測井之數量及位置由地方主管機關逐案指定，並應全部設置於防止濺溢設施內以確保能有效攔截",
  "監測井之數量及位置依儲槽容積比例決定，並應設置於事業用地界線外五公尺處以利地方機關查核",
  "監測井之數量及位置依儲槽數目每槽一口決定，並應設置於加油機底部正下方以偵測油品之滲漏"],"a",
 "第23條第1項第3款：應依開挖區範圍、回填孔隙介質、儲存物質及監測設備之功能決定土壤氣體監測井之數量及位置，並不得設置於第18條第1項第3款防止濺溢設施內。此為地上儲槽系統相較第12條地下儲槽系統之特別限制；其餘透氣度五百毫米汞柱、半徑五公尺、自行每月及委託每四個月之頻率則與第12條相同。",
 "What special restriction applies to soil gas well siting for above ground tanks?",
 ["Well number and location follow the excavation area and media, and no well may sit inside the spill prevention barrier",
  "Well number and location are assigned case by case by the local authority, and all wells must sit inside the barrier",
  "Well number and location follow tank volume in proportion, and wells must sit five meters outside the site boundary",
  "Well number and location follow one well per tank, and wells must sit directly beneath the dispenser to detect leaks"],
 "Article 23(1)(3)."),

(ST,"第24條",3,"貯存系統-監測井口數",
 "地上儲槽系統以地下水監測者，其地下水標準監測井口數依事業用地面積如何規定？",
 ["未達一公頃設三口、一至十公頃設五口、十至五十公頃設十口、五十至一百公頃設二十口、一百公頃以上設二十五口",
  "未達一公頃設一口、一至十公頃設三口、十至五十公頃設五口、五十至一百公頃設十口、一百公頃以上設十五口",
  "未達一公頃設五口、一至十公頃設十口、十至五十公頃設二十口、五十至一百公頃設三十口、一百公頃以上設五十口",
  "未達一公頃設二口、一至十公頃設四口、十至五十公頃設八口、五十至一百公頃設十六口、一百公頃以上設三十二口"],"a",
 "第24條第1項第7款：地下水標準監測井口數不得低於下列規定：事業用地面積未達一公頃設三口、達一公頃以上未達十公頃設五口、達十公頃以上未達五十公頃設十口、達五十公頃以上未達一百公頃設二十口、達一百公頃以上設二十五口。第8款：地方主管機關得要求增設。第24條第3項：井口數及監測項目得檢具理由經地方主管機關同意後調整。",
 "How many standard groundwater wells are required by site area for above ground systems?",
 ["Three wells under 1 ha, five for 1 to 10 ha, ten for 10 to 50 ha, twenty for 50 to 100 ha, twenty five at 100 ha or more",
  "One well under 1 ha, three for 1 to 10 ha, five for 10 to 50 ha, ten for 50 to 100 ha, fifteen at 100 ha or more",
  "Five wells under 1 ha, ten for 1 to 10 ha, twenty for 10 to 50 ha, thirty for 50 to 100 ha, fifty at 100 ha or more",
  "Two wells under 1 ha, four for 1 to 10 ha, eight for 10 to 50 ha, sixteen for 50 to 100 ha, thirty two at 100 ha or more"],
 "Article 24(1)(7)-(8)."),

(ST,"第25條",2,"貯存系統-地上申報",
 "地上儲槽系統之申報時程及免申報情形為何？",
 ["應於每年一月、五月、九月之月底前申報前四個月之紀錄；依第二十一條規定免進行監測者，免依規定進行申報",
  "應於每年三月、七月、十一月之月底前申報前四個月之紀錄；依第二十一條規定免進行監測者，仍應按期申報",
  "應於每年六月及十二月之月底前申報前六個月之紀錄；容積未達一千公秉之地上儲槽系統一律免進行申報",
  "應於每年十二月三十一日前申報當年度全年之紀錄；已委託檢驗測定機構監測者，由該機構代為申報即可"],"a",
 "第25條第1項：地上儲槽系統應以網路傳輸方式於每年一月、五月、九月之月底前，向直轄市、縣（市）主管機關申報前四個月依第19條第1項及第20條第1項之總量進出管制紀錄、監測日期及紀錄、洩漏量及處理情形等。第25條第3項：依第21條免進行監測者，免依第1項規定申報。第25條第4項：申報文件欠缺者應限期補正，逾期視為未申報。",
 "What is the reporting schedule for above ground systems, and who is exempt?",
 ["File by the end of January, May and September for the previous four months; those exempt from monitoring need not report",
  "File by the end of March, July and November for the previous four months; those exempt from monitoring must still report",
  "File by the end of June and December for the previous six months; any system under 1,000 kL is exempt from reporting",
  "File by December 31 each year covering the whole year; where monitoring is commissioned the organization files instead"],
 "Article 25."),

(ST,"第26條",2,"貯存系統-地上保存",
 "地上儲槽系統及貯存容器之各項紀錄應保存幾年備查？",
 ["地上儲槽系統之每月巡檢、總量進出管制及監測紀錄均保存三年；貯存容器之每月巡檢紀錄亦應保存三年備查",
  "地上儲槽系統之每月巡檢、總量進出管制及監測紀錄均保存二年；貯存容器之每月巡檢紀錄則應保存一年備查",
  "地上儲槽系統之每月巡檢、總量進出管制及監測紀錄均保存五年；貯存容器之每月巡檢紀錄則應保存十年備查",
  "地上儲槽系統之每月巡檢、總量進出管制及監測紀錄均保存一年；貯存容器之每月巡檢紀錄則免予保存備查"],"a",
 "第26條第1項：地上儲槽系統依第18條第1項之每月巡檢紀錄、第19條第1項之總量進出管制紀錄及第20條第1項之監測紀錄，應保存三年備查。第26條第2項：貯存容器依第18條第2項之每月巡檢紀錄，應保存三年備查。相對地，第16條第3項規定地下儲槽系統監測紀錄保存二年，一百十年一月一日起作成者保存三年。",
 "How long must records of above ground systems and containers be kept?",
 ["Monthly patrol, inventory control and monitoring records of above ground systems for three years; container patrol records also three years",
  "Monthly patrol, inventory control and monitoring records of above ground systems for two years; container patrol records for one year",
  "Monthly patrol, inventory control and monitoring records of above ground systems for five years; container patrol records for ten years",
  "Monthly patrol, inventory control and monitoring records of above ground systems for one year; container patrol records need not be kept"],
 "Article 26; compare Article 16(3)."),

(ST,"第27條",2,"貯存系統-地上適用日",
 "貯存汽油、柴油之地上儲槽系統，應依第十九條至第二十五條規定辦理之起始日期為何？",
 ["儲槽容積達一千公秉以上者自一百十二年一月一日起；未達一千公秉者自一百十四年一月一日起適用",
  "儲槽容積達一千公秉以上者自一百十年一月一日起；未達一千公秉者自一百十二年一月一日起適用",
  "儲槽容積達一千公秉以上者自一百十四年一月一日起；未達一千公秉者自一百十六年一月一日起適用",
  "儲槽容積達一千公秉以上者自一百十六年一月一日起；未達一千公秉者自一百十八年一月一日起適用"],"a",
 "第27條第1項：貯存汽油、柴油之地上儲槽系統，儲槽容積達一千公秉以上者自一百十二年一月一日起、未達一千公秉者自一百十四年一月一日起，應依第19條至第25條規定進行監測、記錄及申報。第27條第2項：貯存汽油、柴油以外指定物質之地上儲槽系統，自一百十六年一月一日起適用。此與第32條之改善完成期限相互對應。",
 "From when must gasoline and diesel above ground tank systems comply with Articles 19 to 25?",
 ["Tanks of 1,000 kL or more from January 1, 2023; tanks under 1,000 kL from January 1, 2025 onward",
  "Tanks of 1,000 kL or more from January 1, 2021; tanks under 1,000 kL from January 1, 2023 onward",
  "Tanks of 1,000 kL or more from January 1, 2025; tanks under 1,000 kL from January 1, 2027 onward",
  "Tanks of 1,000 kL or more from January 1, 2027; tanks under 1,000 kL from January 1, 2029 onward"],
 "Article 27; compare Article 32."),

(ST,"第28條",3,"貯存系統-暫停關閉",
 "地上、地下儲槽系統暫停使用、永久關閉或轉換用途時，應如何辦理？",
 ["暫停使用應持續監測記錄及申報並維護防蝕功能；永久關閉或轉換用途前應清除槽內物質及污泥；並應於十五日前通報",
  "暫停使用得免除全部監測記錄及申報義務；永久關閉或轉換用途後六十日內清除槽內物質及污泥；並應於三日前通報",
  "暫停使用應每月申報一次並停止防蝕措施；永久關閉或轉換用途前應將儲槽拆除運離場址；並應於三十日前通報",
  "暫停使用應報請中央主管機關核准後始得為之；永久關閉或轉換用途前應辦理土壤污染評估調查；並應於一年前通報"],"a",
 "第28條第1項第1款：暫停使用應依第9條至第15條或第20條至第24條持續監測記錄，並依第16條或第25條申報及維護防蝕措施正常功能；但輸送設備抽除輸送物質且儲槽內物質高度低於二．五公分或體積少於總容量百分之三者，不在此限。第1項第2款：永久關閉或轉換用途前應清除槽內物質及污泥，並依廢棄物清理法辦理。第28條第2項：暫停使用、復用、永久關閉或轉換用途十五日前應以網路傳輸通報地方主管機關。",
 "What must be done when a tank system is suspended, permanently closed or changes use?",
 ["Suspension keeps monitoring, recording, reporting and corrosion protection; closure or change of use requires cleaning first; notify 15 days ahead",
  "Suspension ends all monitoring and reporting duties; cleaning follows within sixty days after closure or change of use; notify 3 days ahead",
  "Suspension requires monthly reports and stopping corrosion protection; the tank must be removed before closure; notify 30 days ahead",
  "Suspension requires central authority approval first; a soil pollution assessment precedes closure or change of use; notify one year ahead"],
 "Article 28."),

(ST,"第30條",2,"貯存系統-書件保存",
 "經備查之完工報告書及設置計畫書應保存至何時？貯存系統移轉時應如何處理？",
 ["地下儲槽系統之完工報告書及地上儲槽系統之設置計畫書應保存至更新或永久關閉為止；移轉時應交予移轉後之所有人保存",
  "地下儲槽系統之完工報告書及地上儲槽系統之設置計畫書應保存三年即可；移轉時應由原所有人送交地方主管機關存查",
  "地下儲槽系統之完工報告書及地上儲槽系統之設置計畫書應保存五年即可；移轉時原所有人得逕行銷毀並作成銷毀紀錄",
  "地下儲槽系統之完工報告書及地上儲槽系統之設置計畫書應保存十年即可；移轉時應報請中央主管機關同意後始得交付"],"a",
 "第30條第1至3項：新設、更新地下儲槽系統之完工報告書及更新完工報告書，應保存至地下儲槽系統更新或永久關閉為止；新設、更新地上儲槽系統之設置計畫書及更新設置計畫書，保存至地上儲槽系統更新或永久關閉為止；新設一定規模貯存容器之設置計畫書，保存至永久關閉為止。第30條第4項：前三項書件於貯存系統移轉時，應交予移轉後之所有人保存。",
 "How long must approved completion reports and setup plans be kept, and what happens on transfer?",
 ["Until the system is renewed or permanently closed; on transfer the documents must be handed to the new owner for keeping",
  "For three years only; on transfer the former owner must send the documents to the local competent authority for filing",
  "For five years only; on transfer the former owner may destroy them and simply make a record of the destruction",
  "For ten years only; on transfer central authority consent must be obtained before the documents may be handed over"],
 "Article 30."),

(ST,"第31條",1,"貯存系統-委託查核",
 "各級主管機關執行本辦法相關設施設備及申報查核業務，得如何辦理？",
 ["得委託相關管理機關（構）或法人、團體辦理第七條至第十五條及第十八條至第二十四條之查核業務",
  "得委由事業自行查核後函報備查，主管機關僅就書面資料進行抽查而不再派員辦理現場之查核",
  "應由中央主管機關統一派員辦理，不得委託任何機關（構）、法人或團體代為執行查核業務",
  "得委託事業所屬公會或原設計施工廠商辦理，並由該公會或廠商核發設施設備之合格證明"],"a",
 "第31條：各級主管機關執行第7條至第15條及第18條至第24條相關設施與設備及申報查核業務，得委託相關管理機關（構）或法人、團體辦理。此為查核業務之委託依據，與第9條、第20條所定監測應由訓練合格領證人員為之，分屬不同層次之規定。",
 "How may authorities carry out inspection of facilities, equipment and filings under this regulation?",
 ["They may commission relevant management agencies, juridical persons or groups to perform the inspection duties",
  "They may let enterprises inspect themselves and file the result, reviewing only documents without any site work",
  "Only the central authority may assign staff, and no agency, juridical person or group may be commissioned",
  "They may commission the trade guild or the original contractor, which then issues compliance certificates"],
 "Article 31."),

(ST,"第32條",3,"貯存系統-既有改善",
 "一百十年一月一日前已完成建造而設施未符本辦法規定者，其提報改善計畫及完成改善之期限為何？",
 ["地下儲槽系統及達一千公秉以上地上儲槽並貯汽柴油者六個月內提報、一百十二年一月一日前完成；未達者一年內提報",
  "地下儲槽系統及達一千公秉以上地上儲槽並貯汽柴油者一年內提報、一百十四年一月一日前完成；未達者二年內提報",
  "地下儲槽系統及達一千公秉以上地上儲槽並貯汽柴油者三個月內提報、一百十一年一月一日前完成；未達者六個月內提報",
  "地下儲槽系統及達一千公秉以上地上儲槽並貯汽柴油者二年內提報、一百十六年一月一日前完成；未達者三年內提報"],"a",
 "第32條：一百十年一月一日前已完成建造、建造中、完成招標或已訂立施作契約而設施未符規定者，應檢附改善計畫提報地方主管機關並限期完成改善：地下儲槽系統及儲槽容積達一千公秉以上之地上儲槽系統並貯存汽油、柴油者，自一百十年一月一日起六個月內提報，一百十二年一月一日前改善完成；容積未達一千公秉之地上儲槽系統及貯存容器並貯汽柴油者一年內提報、一百十四年一月一日前完成；貯存其他指定物質者二年內提報、一百十六年一月一日前完成。",
 "What deadlines apply to improvement plans for facilities built before January 1, 2021?",
 ["Underground systems and 1,000 kL or larger gasoline or diesel tanks file within six months and finish by 2023; smaller ones file within a year",
  "Underground systems and 1,000 kL or larger gasoline or diesel tanks file within one year and finish by 2025; smaller ones file within two years",
  "Underground systems and 1,000 kL or larger gasoline or diesel tanks file within three months and finish by 2022; smaller ones within six months",
  "Underground systems and 1,000 kL or larger gasoline or diesel tanks file within two years and finish by 2027; smaller ones within three years"],
 "Article 32."),

(ST,"第33條",1,"貯存系統-施行日",
 "防止貯存系統污染地下水體設施及監測設備設置管理辦法自何日施行？",
 ["自中華民國一百十年一月一日施行",
  "自中華民國一百十一年十月十一日施行",
  "自中華民國一百十二年一月一日施行",
  "自發布日起算滿六個月之翌日施行"],"a",
 "第33條：本辦法自中華民國一百十年一月一日施行。此一施行日與第32條所定既有設施改善起算日（自一百十年一月一日起六個月、一年、二年內提報改善計畫）相互配合。",
 "When did this storage system regulation take effect?",
 ["On January 1, 2021 as expressly provided",
  "On October 11, 2022, the amendment date",
  "On January 1, 2023 for all storage systems",
  "Six months after the date of promulgation"],
 "Article 33."),
]
