# -*- coding: utf-8 -*-
# 第 9 批（A2）：固定污染源設置操作及燃料使用許可證管理辦法──補足全部條文覆蓋
P = "ENV-32"

Q = [

(P,"第1條",1,"固污許可-授權依據",
 "固定污染源設置操作及燃料使用許可證管理辦法之授權訂定依據為何？",
 ["依空氣污染防制法第二十四條第四項及第二十八條第二項規定訂定之",
  "依空氣污染防制法第二十條第二項及第二十二條第一項規定訂定之",
  "依空氣污染防制法第十六條第二項及第十七條第二項規定訂定之",
  "依空氣污染防制法第十三條第二項及第十四條第四項規定訂定之"],"a",
 "第1條：本辦法依空氣污染防制法第二十四條第四項及第二十八條第二項規定訂定之。第24條為設置及操作許可證之依據，第28條為燃料使用許可證之依據。",
 "Under which provisions was the stationary source permit regulation adopted?",
 ["Article 24, paragraph 4 and Article 28, paragraph 2 of the Air Pollution Control Act",
  "Article 20, paragraph 2 and Article 22, paragraph 1 of the Air Pollution Control Act",
  "Article 16, paragraph 2 and Article 17, paragraph 2 of the Air Pollution Control Act",
  "Article 13, paragraph 2 and Article 14, paragraph 4 of the Air Pollution Control Act"],
 "Article 1."),

(P,"第2條",2,"固污許可-污染源分類",
 "中央主管機關得依固定污染源製程、設備之種類、規模，將指定公告之固定污染源分為哪幾類？",
 ["分為第一類固定污染源、第二類固定污染源或第三類可簡化申請之固定污染源，並指定公告之",
  "分為甲級固定污染源、乙級固定污染源或丙級免申請許可之固定污染源，並指定公告之",
  "分為大型固定污染源、中型固定污染源或小型免予管制之固定污染源，並指定公告之",
  "分為高污染潛勢源、中污染潛勢源或低污染潛勢免檢測之固定污染源，並指定公告之"],"a",
 "第2條：公私場所固定污染源經中央主管機關依空污法第24條第1項指定公告者，應申請設置或操作許可證；中央主管機關得依固定污染源製程、設備之種類、規模，將指定公告之固定污染源分為第一類、第二類或第三類可簡化申請之固定污染源，並指定公告之。第55條就第三類固定污染源定有簡化程序。",
 "How may the central authority classify designated stationary sources?",
 ["As Class 1 sources, Class 2 sources, or Class 3 sources eligible for simplified application, as designated and announced",
  "As Grade A sources, Grade B sources, or Grade C sources exempt from permit application, as designated and announced",
  "As large sources, medium sources, or small sources exempt from control, as designated and announced by the authority",
  "As high potential sources, medium potential sources, or low potential sources exempt from testing, as announced"],
 "Article 2."),

(P,"第5條",2,"固污許可-設立定義",
 "空氣污染防制法第八十八條所稱之「設立」，於本辦法係指何種情形？",
 ["指固定污染源已建造完成、建造中、已完成工程招標程序或未經招標程序已訂立工程施作契約者",
  "指固定污染源已取得目的事業主管機關核發之工廠登記證或營業登記證明文件者",
  "指固定污染源已完成環境影響評估審查並取得審查結論公告之核可文件者",
  "指固定污染源已完成試車程序並經審核機關核發操作許可證開始運轉者"],"a",
 "第5條：本法第88條所稱設立，指固定污染源已建造完成、建造中、已完成工程招標程序或未經招標程序已訂立工程施作契約者。此定義與鍋爐空氣污染物排放標準第2條認定既存鍋爐之用語一致。第18條第2項並定有依本法第88條申請操作許可證應檢具之文件。",
 "What does establishment under Article 88 of the Act mean here?",
 ["A source already built, under construction, with tendering completed, or with a works contract signed without tendering",
  "A source that has obtained a factory registration or business registration certificate from the industry authority",
  "A source that has passed environmental impact assessment review and obtained the announced conclusion document",
  "A source that has completed the test run and obtained an operating permit from the reviewing authority"],
 "Article 5."),

(P,"第6條",3,"固污許可-排放量推估",
 "空氣污染物年許可排放量推估依據之優先順序為何？",
 ["連續自動監測設施一年以上監測資料；試車檢測報告或三次以上檢測報告數據；經認可之自廠係數；公告排放係數、控制效率、質量平衡；其他經認可之替代方式",
  "公告之空氣污染物排放係數；經認可之自廠係數；連續自動監測設施一年以上監測資料；試車檢測報告或三次以上檢測報告數據；其他經認可之替代方式",
  "經認可之自廠係數；連續自動監測設施三個月以上監測資料；試車檢測報告或一次以上檢測報告數據；公告排放係數；其他由公私場所自訂之方式",
  "試車檢測報告數據；公告之排放係數與控制效率；連續自動監測設施半年以上監測資料；經目的事業主管機關認可之係數；其他自行選定之方式"],"a",
 "第6條：年許可排放量推估依據順序為：連續自動監測設施一年以上之監測資料；依第20條執行之試車檢測報告數據、主管機關或公私場所自行或委託執行三次以上之檢測報告數據；經中央主管機關認可之自廠係數；中央主管機關公告之排放係數、控制效率、質量平衡計量方式；其他經認可之排放係數或替代計算方式。原則應依第三款至第五款推估，採密閉集氣系統至排放管道者得以第一款或第二款推估。",
 "What is the priority order for estimating the permitted annual emission volume?",
 ["One year or more of continuous monitoring data; test-run or three or more test reports; approved in-house factors; announced factors, control efficiency and mass balance; other approved alternatives",
  "Announced emission factors; approved in-house factors; one year or more of continuous monitoring data; test-run or three or more test reports; other approved alternatives",
  "Approved in-house factors; three months or more of continuous monitoring data; test-run or one or more test reports; announced factors; other methods set by the premises",
  "Test-run report data; announced emission factors and control efficiency; six months or more of continuous monitoring data; factors approved by the industry competent authority; other chosen methods"],
 "Article 6, paragraph 1."),

(P,"第7條",2,"固污許可-用產量核定",
 "許可證記載與空氣污染物排放有關之原（物）料、燃料用量及產品產量，其推估與核定方式為何？",
 ["單位時間用（產）量應以固定污染源最大設計量估算核定；年用（產）量得以申請之最大操作量估算，但不得大於最大設計量",
  "單位時間用（產）量應以固定污染源實際平均操作量估算核定；年用（產）量得以最大設計量之二倍估算後核定之",
  "單位時間用（產）量應以前一年度實際使用量估算核定；年用（產）量得以最大設計量加計百分之二十後估算核定",
  "單位時間用（產）量應以同業平均水準估算核定；年用（產）量得由公私場所自行申報而不受最大設計量之限制"],"a",
 "第7條：單位時間用（產）量應以固定污染源最大設計量估算與核定之；年用（產）量得以公私場所申請固定污染源最大操作量估算與核定之，但申請之最大操作量不得大於固定污染源最大設計量；年用（產）量並得依本法第7條第2項經中央主管機關核定後公告之空氣污染防制計畫核定。",
 "How are material, fuel and product quantities estimated and approved in a permit?",
 ["Per unit time quantities estimated at the source's maximum design capacity; annual quantities at the applied maximum operating capacity, not exceeding design capacity",
  "Per unit time quantities estimated at the source's actual average operating level; annual quantities at twice the maximum design capacity as estimated and approved",
  "Per unit time quantities estimated at last year's actual usage; annual quantities at the maximum design capacity plus twenty percent as approved",
  "Per unit time quantities estimated at the industry average level; annual quantities declared freely by the premises without any design capacity limit"],
 "Article 7."),

(P,"第8條",2,"固污許可-處理效率核定",
 "許可證記載之空氣污染防制設施處理效率及操作條件，其核定方式為何？",
 ["以設計操作條件核定；無設計操作條件時，以試車檢測或實際運轉經驗之防制設施操作條件為依據",
  "以試車檢測結果核定；無試車檢測結果時，以中央主管機關公告之控制效率上限值為依據",
  "以設備原廠型錄標示值核定；無型錄標示值時，以同業最佳可行控制技術之效率為依據",
  "以公私場所自行申報值核定；無自行申報值時，以審核機關認定之保守推估數值為依據"],"a",
 "第8條：許可證記載之空氣污染防制設施處理效率及操作條件之核定方式為：設計操作條件；無設計操作條件時，以試車檢測或實際運轉經驗之空氣污染防制設施操作條件為依據。第50條並要求核定足供監控符合實際運作情形之操作條件、紀錄項目及頻率。",
 "How are control facility efficiency and operating conditions determined in a permit?",
 ["Based on design operating conditions; where none exist, on test-run or actual operating experience of the control facility",
  "Based on test-run results; where none exist, on the upper limit of control efficiency announced by the central authority",
  "Based on the equipment maker's catalogue values; where none exist, on the best available control technology efficiency",
  "Based on values declared by the premises; where none are declared, on a conservative estimate set by the authority"],
 "Article 8."),

(P,"第10條",1,"固污許可-申請方式",
 "公私場所申請固定污染源設置、操作或燃料使用許可證者，應以何種方式辦理？",
 ["應依中央主管機關公告之電子網路傳輸方式辦理申請",
  "應以掛號郵寄書面文件方式向審核機關辦理申請",
  "應由負責人親自至審核機關臨櫃遞件辦理申請",
  "應由環境工程技師代為向中央主管機關辦理申請"],"a",
 "第10條：公私場所固定污染源申請固定污染源設置、操作或燃料使用許可證者，應依中央主管機關公告之電子網路傳輸方式辦理。第31條第1項第1款並規定審核機關應於收到網路申請及書面資料後七日內完成形式審查。",
 "How must permit applications be filed?",
 ["Through the electronic network transmission method announced by the central authority",
  "By sending paper documents to the reviewing authority by registered mail",
  "By the responsible person filing in person at the reviewing authority counter",
  "Through an environmental engineer filing with the central competent authority"],
 "Article 10."),

(P,"第11條",2,"固污許可-審核機關",
 "本辦法所定審核機關，於申請設置或操作許可證及申請燃料使用許可證時，分別指何者？",
 ["申請設置或操作許可證時指地方主管機關或中央主管機關委託之機關；申請燃料使用許可證時指地方主管機關",
  "申請設置或操作許可證時指中央主管機關；申請燃料使用許可證時指中央主管機關委託之專責機構",
  "申請設置或操作許可證時指目的事業主管機關；申請燃料使用許可證時指中央主管機關或其委託機關",
  "申請設置或操作許可證時一律指中央主管機關；申請燃料使用許可證時一律指地方環保稽查大隊"],"a",
 "第11條：本辦法所定審核機關，於依本法第24條第1項或第2項申請設置或操作許可證時，指直轄市、縣（市）主管機關或中央主管機關委託之機關；於依本法第28條第1項申請燃料使用許可證時，指直轄市、縣（市）主管機關。地方主管機關並得委託其他機關辦理燃料使用許可證之申請審查及核發，受委託機關屬審核機關。",
 "Who is the reviewing authority for installation or operating permits and for fuel use permits?",
 ["For installation or operating permits, the local authority or an agency commissioned by the central authority; for fuel use permits, the local authority",
  "For installation or operating permits, the central authority; for fuel use permits, a dedicated institution commissioned by the central authority",
  "For installation or operating permits, the industry competent authority; for fuel use permits, the central authority or its commissioned agency",
  "For installation or operating permits, always the central authority; for fuel use permits, always the local environmental inspection brigade"],
 "Article 11."),

(P,"第12條",2,"固污許可-設置申請",
 "公私場所申請固定污染源設置許可證應檢具何文件？設置於經環評且具排放總量規定區域者另應檢具何者？",
 ["應填具申請表並檢具空氣污染防制計畫；設於該區域者應同時檢具區域管理單位核定之排放量分配證明文件",
  "應填具申請表並檢具試車計畫書；設於該區域者應同時檢具中央主管機關核發之排放量核配許可文件",
  "應填具申請表並檢具檢測報告書；設於該區域者應同時檢具目的事業主管機關核准之產能證明文件",
  "應填具申請表並檢具專責人員名冊；設於該區域者應同時檢具地方主管機關核定之空氣品質模擬報告"],"a",
 "第12條：公私場所依本法第24條第1項規定申請固定污染源設置許可證，應填具申請表並檢具空氣污染防制計畫，向審核機關為之；固定污染源設置於經環境影響評估且具排放總量規定之區域者，於申請設置許可證時，應同時檢具該區域管理單位核定之排放量分配證明文件。",
 "What must an installation permit application include, and what extra document applies in total-quantity areas?",
 ["An application form and an air pollution control plan; in such areas, also the emission allocation certificate approved by the area management unit",
  "An application form and a test-run plan; in such areas, also the emission allocation approval document issued by the central competent authority",
  "An application form and a testing report; in such areas, also the production capacity certificate approved by the industry authority",
  "An application form and a roster of dedicated personnel; in such areas, also the air quality modeling report approved locally"],
 "Article 12."),

(P,"第13條",3,"固污許可-防制計畫內容",
 "設置許可證應檢具之空氣污染防制計畫，其內容應包括下列何者？",
 ["計畫目標、污染源廠場周界外二公里範圍內環境座落圖說、廠場設施平面配置圖說、生產製程流程圖說及產製期程、預估年排放量",
  "計畫目標、污染源廠場周界外五百公尺範圍內環境座落圖說、廠場地籍謄本、生產製程之營業秘密說明、預估年營業額",
  "計畫目標、污染源廠場周界外十公里範圍內人口統計資料、員工名冊、產品市場分析報告、預估年度投資金額",
  "計畫目標、鄰近空氣品質監測站之三年監測資料、公司財務報表、原料供應商契約影本、預估年度用電量"],"a",
 "第13條：空氣污染防制計畫內容應包括計畫目標；污染源廠場周界外二公里範圍內之環境座落圖說；廠場設施平面配置圖說；生產製程流程圖說及產製期程；與排放有關之原（物）料、燃料種類成分用量及產品種類生產量；原（物）料燃料之輸送貯存及堆置方式；排放污染物種類成分及濃度；預估需核定之硫氧化物、氮氧化物、粒狀污染物及揮發性有機物年排放量；收集及排放管道、監測、防制設施之種類構造效能及設計圖說；設置經費及進度；施工期間防制設施等。",
 "What must the air pollution control plan for an installation permit contain?",
 ["Plan objectives, a siting map within two kilometers outside the plant boundary, facility layout drawings, process flow charts and schedules, and estimated annual emissions",
  "Plan objectives, a siting map within five hundred meters outside the boundary, land registry transcripts, trade secret descriptions, and estimated annual turnover",
  "Plan objectives, population statistics within ten kilometers outside the boundary, staff rosters, product market analysis, and estimated annual investment",
  "Plan objectives, three years of nearby monitoring station data, company financial statements, supplier contract copies, and estimated annual electricity use"],
 "Article 13."),

(P,"第14條",2,"固污許可-模式模擬",
 "新設或變更固定污染源依本法規定應經模式模擬證明污染物排放量不超過容許增量限值者，申請設置許可證時應如何辦理？",
 ["應同時檢具符合空氣品質模式模擬規範及污染物容許增量限值之證明文件，向審核機關提出申請",
  "應於取得設置許可證後六個月內補送符合空氣品質模式模擬規範之證明文件，向審核機關備查",
  "應於申請操作許可證時始檢具符合污染物容許增量限值之證明文件，向中央主管機關報請核准",
  "應由環境工程技師出具切結書代替模式模擬證明文件，並於試車完成後補送模擬結果報告書"],"a",
 "第14條：公私場所新設或變更固定污染源依本法第6條第2項、第3項或第8條第2項規定應經模式模擬證明其污染物排放量不超過容許增量限值者，於申請固定污染源設置許可證時，應同時檢具符合空氣品質模式模擬規範及污染物容許增量限值之證明文件。第31條第2項並規定此類申請之實質審查期間得延長四十五日。",
 "How must modeling requirements be met when applying for an installation permit?",
 ["Submit, together with the application, documents showing compliance with the modeling specifications and the allowable increment limits",
  "Submit documents showing compliance with the modeling specifications within six months after the installation permit is obtained",
  "Submit documents showing compliance with the allowable increment limits only when applying for the operating permit",
  "Submit an engineer's affidavit in place of the modeling documents and file the modeling results after the test run"],
 "Article 14."),

(P,"第15條",3,"固污許可-最佳可行技術",
 "新設或變更固定污染源應採最佳可行控制技術或最低可達成排放率控制技術，而未採用公告附表所列技術者，申請設置許可證時應檢具何文件？",
 ["採用低污染性原（物）料、燃料、低污染製程或控制設施之污染減量說明資料；減量措施或控制設施之操作參數、紀錄方式及頻率；質能平衡或其他計算說明資料",
  "採用同業慣用原（物）料及製程之成本效益分析資料；設備採購契約與付款憑證影本；廠內人員教育訓練紀錄及考核成績；財務可行性評估報告書",
  "採用進口設備之原廠型錄與保固文件；工程承攬廠商之資格證明文件；施工進度甘特圖與人力配置表；環境影響評估審查結論之承諾事項對照表",
  "採用之防制設備廠牌價格比較表；同業排放濃度之調查統計資料；地方民意調查與說明會紀錄；未來五年之產能擴充與投資計畫說明書"],"a",
 "第15條：未採用公告最佳可行控制技術附表所列可行控制技術或最低可達成排放率控制技術附表所列可達成排放率控制技術者，於申請設置許可證時應同時檢具：採用低污染性原（物）料、燃料、低污染製程或空氣污染控制設施之污染減量說明資料；空氣污染減量措施或控制設施之相關操作參數、紀錄方式及頻率；空氣污染物質能平衡或其他計算說明資料；其他經中央主管機關指定之資料。",
 "What must be filed when the announced BACT or LAER technologies are not adopted?",
 ["Reduction descriptions for low-pollution materials, fuels, processes or control facilities; operating parameters, recording methods and frequencies; mass and energy balance or other calculations",
  "Cost-benefit analysis of conventional industry materials and processes; equipment purchase contracts and payment records; in-house training records and appraisals; financial feasibility reports",
  "Catalogues and warranty papers for imported equipment; qualification papers of the contractor; construction Gantt charts and manpower tables; a table of EIA commitments",
  "Price comparison tables of control equipment brands; survey statistics of industry emission concentrations; public opinion polls and briefing records; five-year expansion plans"],
 "Article 15."),

(P,"第16條",2,"固污許可-設置證記載",
 "固定污染源設置許可證應記載之事項，下列何者正確？",
 ["設置許可證有效期間及證書字號、公私場所名稱地址與負責人資料、固定污染源名稱與製程流程圖說、核定之四種污染物年許可排放量及其推估依據",
  "設置許可證有效期間及證書字號、公私場所之資本額與員工人數、產品市場占有率、預估年度營業額與繳納空氣污染防制費之金額",
  "設置許可證有效期間及證書字號、承攬施工廠商名稱與工程金額、施工人員名冊、工程保固期限與竣工查驗紀錄及驗收證明",
  "設置許可證有效期間及證書字號、環境影響評估委員名單、公聽會出席人數、地方回饋金額度與支付方式及執行進度說明"],"a",
 "第16條：設置許可證應記載有效期間及證書字號；基本資料（公私場所名稱地址、負責人姓名身分證明文件字號及住址）；設置許可內容（固定污染源名稱、製程流程圖說、主要原（物）料燃料種類成分用量或產品產量、設計操作條件與期程；防制方法及設施名稱型式設計處理容量與效率；收集排放方式、管道口徑、排放口位置及監測設施；排放種類；核定之硫氧化物、氮氧化物、粒狀污染物及揮發性有機物年許可排放量；推估依據；許可公告批次及專責人員規定等）。",
 "What must an installation permit record?",
 ["Validity period and certificate number, premises name, address and responsible person, source name and process flow charts, and the four approved annual pollutant limits with their estimation basis",
  "Validity period and certificate number, the premises' capital and headcount, product market share, estimated annual turnover and the amount of air pollution fees paid",
  "Validity period and certificate number, the construction contractor's name and contract value, worker rosters, warranty period, completion inspection records and final acceptance certificates",
  "Validity period and certificate number, the list of EIA review committee members, attendance at public hearings, local compensation amounts and payment progress"],
 "Article 16."),

(P,"第17條",1,"固污許可-設置時點",
 "公私場所應於何時始得進行固定污染源設備安裝或建造？",
 ["應於取得固定污染源設置許可證後，始得進行設備安裝或建造，並應依許可證內容進行設置或變更",
  "應於提出固定污染源設置許可證申請後，即得進行設備安裝或建造，俟核發後再補正相關內容",
  "應於取得目的事業主管機關核准設立文件後，即得進行設備安裝或建造，不受許可證核發之限制",
  "應於完成環境影響評估審查後，即得進行設備安裝或建造，並於完工後再申請設置許可證補辦"],"a",
 "第17條：公私場所應於取得固定污染源設置許可證後，始得進行固定污染源設備安裝或建造，並應依許可證內容進行設置或變更。第23條第1項並規定應於取得操作許可證後始得操作，並依核定內容操作。",
 "When may equipment installation or construction of a stationary source begin?",
 ["Only after obtaining the installation permit, and installation or modification must follow the permit's contents",
  "Immediately after filing the installation permit application, with contents corrected after the permit is issued",
  "Immediately after obtaining the industry authority's establishment approval, regardless of the permit issuance",
  "Immediately after completing the environmental impact assessment, applying for the permit after completion"],
 "Article 17."),

(P,"第18條",3,"固污許可-操作申請",
 "公私場所依本法第二十四條第二項申請固定污染源操作許可證，應檢具之文件包括下列何者？",
 ["目的事業主管機關核准設立登記或營運文件影本、空氣污染防制計畫差異說明書、試車計畫書、符合燃料成分標準之證明文件",
  "目的事業主管機關核准設立登記或營運文件影本、年度財務報表、員工投保名冊、符合勞工安全衛生法規之證明文件",
  "地方主管機關核發之空污費繳費收據、環境教育訓練時數證明、廠區土地權狀影本、符合建築法規之使用執照影本",
  "中央主管機關核發之排放量核配證明、專責人員合格證書影本、防制設備採購契約、符合消防法規之竣工查驗文件"],"a",
 "第18條第1項：申請操作許可證應填具申請表並檢具目的事業主管機關核准設立、登記或營運之相關證明文件影本；空氣污染防制計畫差異說明書；試車計畫書（含試車步驟或程序及達最大產能操作條件所需日數、各步驟污染物產生情形及防範措施、空氣污染物排放檢測計畫）；符合燃料成分標準之證明文件；應實施環評者之審查通過書件及結論；屬本法第8條第3項者之抵換排放量證明文件等。",
 "Which documents are required for an operating permit application under Article 24(2)?",
 ["Copies of the industry authority's establishment or operation approval, a control plan variance statement, a test-run plan, and fuel composition compliance documents",
  "Copies of the industry authority's establishment or operation approval, annual financial statements, staff insurance rosters, and occupational safety compliance documents",
  "Local authority fee payment receipts, environmental education training records, land title copies, and building use license copies showing code compliance",
  "Central authority emission allocation certificates, personnel qualification copies, equipment purchase contracts, and fire code completion inspection documents"],
 "Article 18, paragraph 1."),

(P,"第19條",2,"固污許可-設施說明書",
 "依本法第八十八條申請操作許可證所檢具之空氣污染防制設施說明書，其內容應包括下列何者？",
 ["防制目標、污染源廠場周界外二公里範圍內環境座落圖說、廠場設施平面配置圖說、生產製程流程圖說及產製期程、預估需核定之年排放量",
  "防制目標、污染源廠場周界外一公里範圍內土地使用分區圖、廠區道路配置圖、產品規格說明書、預估年度產值與獲利金額",
  "防制目標、鄰近居民陳情紀錄與處理情形、地方說明會出席簽到表、環境監測委外契約影本、預估環保支出年度預算金額",
  "防制目標、防制設備廠商之資格文件與報價單、設備安裝進度表、操作人員名冊與訓練紀錄、預估設備維護保養費用金額"],"a",
 "第19條：空氣污染防制設施說明書內容應包括防制目標；污染源廠場周界外二公里範圍內之環境座落圖說；廠場設施平面配置圖說；生產製程流程圖說及產製期程；與排放有關之原（物）料、燃料種類成分用量及產品種類生產量；輸送貯存及堆置方式；排放空氣污染物之種類成分及濃度；預估需核定之硫氧化物、氮氧化物、粒狀污染物及揮發性有機物年排放量；收集及排放管道設施、監測設施、防制設施或儀表之種類構造效能流程使用狀況及設計圖說等。",
 "What must the air pollution control facility statement contain?",
 ["Control objectives, a siting map within two kilometers outside the plant boundary, facility layout drawings, process flow charts and schedules, and estimated annual emissions",
  "Control objectives, a land use zoning map within one kilometer of the boundary, plant road layouts, product specifications, and estimated annual output value and profit",
  "Control objectives, records of nearby residents' complaints and responses, briefing attendance sheets, monitoring contract copies, and estimated annual environmental budget",
  "Control objectives, supplier qualification papers and quotations, equipment installation schedules, operator rosters and training records, and estimated maintenance costs"],
 "Article 19."),

(P,"第22條",2,"固污許可-合併申請",
 "公私場所預計得於多久內完成固定污染源設備安裝或建造者，得同時申請設置許可證及操作許可證？",
 ["預計得於三個月內完成設備安裝或建造者，得填具申請表連同空氣污染防制計畫及試車計畫書等文件同時申請",
  "預計得於六個月內完成設備安裝或建造者，得填具申請表連同空氣污染防制計畫及檢測報告書等文件同時申請",
  "預計得於一年內完成設備安裝或建造者，得填具申請表連同空氣污染防制設施說明書及專責人員名冊同時申請",
  "預計得於一個月內完成設備安裝或建造者，得填具申請表連同工程施作契約及設備採購憑證等文件同時申請"],"a",
 "第22條：公私場所預計得於三個月內完成固定污染源設備安裝或建造者，得填具申請表，連同空氣污染防制計畫及試車計畫書、依第14條或第15條規定之文件、符合燃料成分標準之證明文件、應實施環評者之審查通過書件及結論等，向審核機關同時申請設置許可證及操作許可證。第37條定有合併申請之審查程序。",
 "Within what period of expected completion may installation and operating permits be applied for together?",
 ["Where installation or construction is expected within three months, filing an application with the control plan and test-run plan",
  "Where installation or construction is expected within six months, filing an application with the control plan and testing reports",
  "Where installation or construction is expected within one year, filing an application with the facility statement and personnel roster",
  "Where installation or construction is expected within one month, filing an application with works contracts and purchase records"],
 "Article 22."),

(P,"第23條",3,"固污許可-操作與試驗",
 "公私場所使用非屬操作許可證核定記載之原（物）料或燃料進行試驗者，其核准試驗期間規定為何？",
 ["應逐案檢具試車計畫書向審核機關申請；核准試驗期間最長以三十日為限，必要時得展延一次，展延日數不得超過三十日",
  "應逐案檢具試車計畫書向審核機關申請；核准試驗期間最長以九十日為限，必要時得展延二次，展延日數不得超過九十日",
  "應逐案檢具檢測報告向中央主管機關申請；核准試驗期間最長以一百日為限，必要時得展延一次，展延日數不得超過六十日",
  "應逐案檢具原料成分表向目的事業主管機關報備；核准試驗期間最長以一年為限，必要時得展延一次，展延日數不得超過一年"],"a",
 "第23條：公私場所應於取得操作許可證後始得操作，並依核定內容操作。使用非屬操作許可證核定記載之原（物）料或燃料進行試驗者，應先檢具符合第18條第1項第3款之試車計畫書逐案申請，經核准者於核准試驗期間依試車計畫書試驗；審核機關核准試驗期間最長以三十日為限，必要時得展延一次，展延日數不得超過三十日，並應於試驗期間進行現場勘查。試驗紀錄應保存六年備查，且試驗期間不得以同一污染源再申請其他試驗。",
 "What is the approved trial period when using materials or fuels not recorded in the operating permit?",
 ["Apply case by case with a test-run plan; the approved trial lasts at most 30 days, extendable once by no more than 30 days",
  "Apply case by case with a test-run plan; the approved trial lasts at most 90 days, extendable twice by no more than 90 days",
  "Apply case by case with test reports to the central authority; the trial lasts at most 100 days, extendable once by 60 days",
  "File material composition tables with the industry authority; the trial lasts at most one year, extendable once by one year"],
 "Article 23, paragraphs 3 and 5."),

(P,"第24條",2,"固污許可-燃料申請",
 "公私場所申請燃料使用許可證應檢具之文件為何？同時符合設置操作及燃料許可規定者應如何辦理？",
 ["應檢具目的事業主管機關核准文件影本、燃料種類成分及用量、生產製程流程圖說、收集及防制設施種類及流程；並於申請操作許可證時一併提出",
  "應檢具目的事業主管機關核准文件影本、燃料採購契約與付款憑證、廠區平面圖、鍋爐設備型錄；並應於取得操作許可證後單獨提出申請",
  "應檢具燃料供應商之營業登記證明、燃料檢驗報告書正本、運輸車輛清冊、貯存設施設計圖；並應向中央主管機關單獨提出申請",
  "應檢具燃料成分自主檢測計畫、專責人員合格證書影本、年度使用量預估表、繳費收據；並應於取得設置許可證前一併提出申請"],"a",
 "第24條：申請燃料使用許可證應填具申請表並檢具目的事業主管機關核准設立、登記或營運之相關證明文件影本；燃料之種類、成分及用量；生產製程流程圖說；空氣污染收集設施、防制設施之種類及流程；其他經中央主管機關指定之文件。公私場所同時符合第2條及第3條規定者，應於申請操作許可證時一併提出燃料使用許可證申請，應檢具文件相同者得不重複。第38條定有合併記載規定。",
 "What documents are required for a fuel use permit, and how is it filed when an operating permit is also needed?",
 ["Copies of the industry authority's approval, fuel type, composition and quantity, process flow charts, and collection and control facility types and flows; filed together with the operating permit",
  "Copies of the industry authority's approval, fuel purchase contracts and payment records, plant layout plans, and boiler equipment catalogues; filed separately after the operating permit",
  "The fuel supplier's business registration, original fuel test reports, transport vehicle lists, and storage facility drawings; filed separately with the central authority",
  "A fuel composition self-testing plan, personnel qualification copies, estimated annual usage tables, and fee receipts; filed before the installation permit is obtained"],
 "Article 24."),

(P,"第25條",2,"固污許可-燃料證記載",
 "固定污染源之燃料使用許可證應記載事項及其紀錄保存規定為何？",
 ["應記載有效期間與證書字號、基本資料、燃料種類成分用量及操作期程、防制方法及設施名稱型式、燃料使用紀錄之規定；紀錄應保存六年備查",
  "應記載有效期間與證書字號、基本資料、燃料採購金額與供應商名稱、運輸方式與路線、燃料庫存量之規定；紀錄應保存三年備查",
  "應記載有效期間與證書字號、基本資料、燃料熱值與含硫量檢測方法、檢測機構名稱、檢測費用之規定；紀錄應保存一年備查",
  "應記載有效期間與證書字號、基本資料、燃料使用之空污費費率與繳納方式、罰則規定、申訴管道之規定；紀錄應保存十年備查"],"a",
 "第25條：燃料使用許可證應記載有效期間及證書字號；基本資料（公私場所名稱地址、負責人姓名身分證明文件字號及住址）；燃料使用許可內容（固定污染源名稱、製程流程圖說、與排放有關之燃料種類成分用量及操作期程；防制方法及設施之名稱及型式；燃料使用紀錄之規定；其他經指定之許可事項）。燃料使用紀錄應保存六年備查，並應建立電子化紀錄。",
 "What must a fuel use permit record, and how long are records kept?",
 ["Validity and certificate number, basic data, fuel type, composition, quantity and operating schedule, control method and facility names and types, and fuel record rules; kept six years",
  "Validity and certificate number, basic data, fuel purchase amounts and supplier names, transport methods and delivery routes, and fuel inventory record rules; kept three years",
  "Validity and certificate number, basic data, fuel calorific value and sulfur test methods, testing organization names, and testing cost rules; kept one year",
  "Validity and certificate number, basic data, fee rates and payment methods for fuel use, penalty rules, and complaint channels; kept ten years"],
 "Article 25."),

(P,"第26條",1,"固污許可-燃料申報",
 "公私場所領有燃料使用許可證者，應以何種方式、於何時向主管機關申報燃料使用量？",
 ["應依中央主管機關規定之電子網路傳輸方式，於每年一月、四月、七月及十月底前向地方主管機關申報前季使用量",
  "應以書面郵寄方式，於每年三月、六月、九月及十二月底前向中央主管機關申報前季之燃料使用量",
  "應依中央主管機關規定之電子網路傳輸方式，於每年一月及七月底前向地方主管機關申報前半年使用量",
  "應以現場提送紙本方式，於每月十五日前向地方主管機關申報前一月份之各類燃料實際使用數量"],"a",
 "第26條：公私場所領有燃料使用許可證者，其使用燃料之紀錄，應依中央主管機關規定之電子網路傳輸方式，於每年一月、四月、七月及十月底前，向直轄市、縣（市）主管機關申報前季燃料之使用量。第25條並規定燃料使用紀錄應保存六年備查。",
 "How and when must fuel use permit holders report fuel consumption?",
 ["By the electronic network method prescribed centrally, to the local authority by the end of January, April, July and October for the prior quarter",
  "By registered mail, to the central authority by the end of March, June, September and December for the prior quarter",
  "By the electronic network method prescribed centrally, to the local authority by the end of January and July each year for the prior half-year",
  "By delivering paper copies in person, to the local authority by the 15th of each month for the prior month's fuel use"],
 "Article 26."),

(P,"第27條",3,"固污許可-操作異動",
 "公私場所因操作內容異動而與操作許可證記載不符，未涉及本法第二十四條所稱變更者，應如何重新申請操作許可證？",
 ["製程、設施或操作條件異動者應於異動前依申請及核發程序辦理；改用低污染性原料燃料或增設防制設施者應於事實發生後三十日內提出申請",
  "製程、設施或操作條件異動者應於異動後六十日內依申請及核發程序辦理；改用低污染性原料燃料或增設防制設施者應於事實發生前提出申請",
  "製程、設施或操作條件異動者應於異動前報請中央主管機關核准；改用低污染性原料燃料或增設防制設施者應於年度終了後彙總提出申請",
  "製程、設施或操作條件異動者應於異動後十五日內報請備查即可；改用低污染性原料燃料或增設防制設施者應於事實發生後九十日內申請"],"a",
 "第27條：製程、設施或操作條件異動者，應於異動前依操作許可證申請及核發程序辦理，但推估未增加排放量者得不重新檢測；改用低污染性原（物）料或燃料、拆除或停止使用產生空氣污染之設施、增設防制設施或提升防制效率者，應於事實發生後三十日內檢具證明文件申請。未涉及原許可製程及設施正常運作功能、防制效率及排放量改變之操作條件異動，應報請審核機關備查。取得操作許可證後總異動排放量累計達第4條第1項第2款或第3款者，應辦理許可證變更。",
 "How must an operating permit be re-applied for after operational changes not amounting to a modification?",
 ["Changes to process, facilities or operating conditions require re-application before the change; switching to low-pollution materials or adding control facilities requires application within 30 days after",
  "Changes to process, facilities or operating conditions require re-application within 60 days after; switching to low-pollution materials or adding control facilities requires application beforehand",
  "Changes to process, facilities or operating conditions require central approval before the change; switching to low-pollution materials or adding control facilities is filed after year end",
  "Changes to process, facilities or operating conditions need only be filed for record within 15 days; switching materials or adding facilities requires application within 90 days after"],
 "Article 27."),

(P,"第28條",2,"固污許可-燃料異動",
 "公私場所因燃料使用異動而與燃料使用許可證記載不符者，應如何重新申請燃料使用許可證？",
 ["燃料之使用種類或使用量異動者應於異動前依申請及核發程序辦理；改用低污染性燃料或增設拆除防制設施者應於事實發生後三十日內申請",
  "燃料之使用種類或使用量異動者應於異動後三十日內依申請及核發程序辦理；改用低污染性燃料或增設拆除防制設施者應於異動前提出申請",
  "燃料之使用種類或使用量異動者應報請中央主管機關核准後辦理；改用低污染性燃料或增設拆除防制設施者應於年度終了後一併提出申請",
  "燃料之使用種類或使用量異動者僅需報請備查即可；改用低污染性燃料或增設拆除防制設施者應於事實發生後九十日內向審核機關申請"],"a",
 "第28條：燃料之使用種類或使用量異動者，應於異動前依燃料使用許可證之申請及核發程序辦理；改用低污染性燃料、增設、拆除或停止使用產生空氣污染之設施或防制設施者，應於事實發生後三十日內檢附相關證明文件向審核機關提出申請。依前項第1款重新申請者，應填具申請表並檢具異動所需之工程期程等相關文件。",
 "How must a fuel use permit be re-applied for after fuel changes?",
 ["Changes in fuel type or quantity require re-application before the change; switching to low-pollution fuel or adding or removing facilities requires application within 30 days after",
  "Changes in fuel type or quantity require re-application within 30 days after; switching to low-pollution fuel or adding or removing facilities requires application beforehand",
  "Changes in fuel type or quantity require central approval before proceeding; switching to low-pollution fuel or adding or removing facilities is filed after year end",
  "Changes in fuel type or quantity need only be filed for record; switching to low-pollution fuel or adding or removing facilities requires application within 90 days after"],
 "Article 28."),

(P,"第30條",2,"固污許可-展延文件",
 "公私場所依本法第三十條申請許可證展延者，應檢具之文件為何？",
 ["申請展延設置許可證者應檢具設置工程進度變更說明表；申請展延操作或燃料使用許可證者應檢具一年內最近一次之檢測報告或其他證明文件",
  "申請展延設置許可證者應檢具工程竣工查驗證明；申請展延操作或燃料使用許可證者應檢具三年內最近一次之檢測報告或其他證明文件",
  "申請展延設置許可證者應檢具土地使用同意書；申請展延操作或燃料使用許可證者應檢具最近五年之全部檢測報告及操作紀錄影本",
  "申請展延設置許可證者應檢具環評審查結論；申請展延操作或燃料使用許可證者應檢具最近一季之空污費繳費收據及申報書影本"],"a",
 "第30條：申請許可證展延者應填具申請表並檢具：申請展延設置許可證者，應檢具設置工程進度變更說明表；申請展延操作許可證或燃料使用許可證者，應檢具一年內最近一次之檢測報告，或其他足以說明符合本法相關規定之證明文件，但因停工（業）無法檢具者得報經審核機關同意以替代證明文件辦理；其他經中央主管機關指定之文件。第31條第3項規定許可證展延應進行現場勘查。",
 "What documents accompany a permit renewal application?",
 ["For installation permits, a statement of changes in construction progress; for operating or fuel permits, the latest test report within one year or other supporting documents",
  "For installation permits, a construction completion inspection certificate; for operating or fuel permits, the latest test report within three years or other documents",
  "For installation permits, a land use consent letter; for operating or fuel permits, all test reports and operating records of the past five years",
  "For installation permits, the EIA review conclusion; for operating or fuel permits, the latest quarter's fee receipts and filing form copies"],
 "Article 30."),

(P,"第32條",3,"固污許可-技師簽證",
 "審核機關受理設置及操作許可證申請時，經技師簽證得免再審查之文件，及仍應審查之例外情形為何？",
 ["空氣污染防制計畫、防制計畫差異說明書、試車計畫書、防制設施說明書及檢測計畫、修正試車計畫書；但情節重大、申請試車復工等情形仍應審查",
  "空氣污染防制計畫、專責人員名冊、燃料成分證明文件、空污費申報書、年度操作紀錄；但公私場所曾遭裁處罰鍰者仍應審查其全部文件",
  "廠場設施平面配置圖、製程流程圖說、環評審查結論、目的事業核准文件、土地權狀；但技師執業年資未滿五年者仍應審查其簽證文件",
  "檢測報告書、監測設施校正紀錄、防制設備採購契約、施工進度表、竣工查驗紀錄；但由外國技師簽證者仍應由審核機關重新審查"],"a",
 "第32條：下列申請文件經環境工程技師或其他相關專業技師簽證後得免再審查：第12條第1項空氣污染防制計畫；第18條第1項第2款防制計畫差異說明書及第3款試車計畫書；第18條第2項防制設施說明書及空氣污染排放檢測計畫；第20條第4項修正試車計畫書。但有違反本法第96條第1項情節重大、依第97條第1項申請試車後復工（業）、辦理簽證技師五年內經報請懲戒、簽證後經懲戒廢止執照、或其他經認定有審查必要者，審核機關仍應審查。",
 "Which documents are exempt from further review once certified by an engineer, and what are the exceptions?",
 ["The control plan, plan variance statement, test-run plan, facility statement and testing plan, and revised test-run plan; but serious violations or restart after test run still require review",
  "The control plan, personnel roster, fuel composition documents, fee filings and annual operating records; but any premises previously fined still has all documents reviewed",
  "Facility layout drawings, process flow charts, EIA conclusions, industry approvals and land title copies; but engineers with under five years of practice still have documents reviewed",
  "Testing reports, monitor calibration records, equipment purchase contracts, schedules and completion records; but certifications by foreign engineers are always reviewed again"],
 "Article 32."),

(P,"第33條",2,"固污許可-試車通知",
 "審核機關通知審查結果時，就操作許可證或燃料使用許可證應併同通知辦理何事項？檢測報告之審查期限為何？",
 ["依第十八條第一項申請者通知進行試車，依第十八條第二項申請者通知進行檢測；收到檢測報告後十五日內完成審查，必要時得延長十日",
  "依第十八條第一項申請者通知進行檢測，依第十八條第二項申請者通知進行試車；收到檢測報告後三十日內完成審查，必要時得延長十五日",
  "一律通知公私場所先行繳納證書費並領取許可證後再行試車；收到檢測報告後七日內完成審查，必要時得延長七日辦理現場勘查作業",
  "一律通知公私場所報請中央主管機關指定檢測機構執行檢測；收到檢測報告後六十日內完成審查，必要時得延長三十日並重新檢測"],"a",
 "第33條：審核機關依第31條第1項第2款通知審查結果，屬申請操作許可證或燃料使用許可證者，應併同通知：依第18條第1項申請操作許可證者通知進行試車；依第18條第2項申請者通知進行空氣污染物排放檢測；依第27條第1項第1款申請且須重新檢測者通知進行檢測。審核機關應於試車或檢測期間進行現場勘查，並應於收到檢測報告後十五日內完成審查，必要時得延長十日。",
 "What must accompany the review result notice, and what is the deadline for reviewing test reports?",
 ["Applicants under Article 18(1) are told to run tests, those under Article 18(2) to conduct testing; reports are reviewed within 15 days, extendable by 10 days",
  "Applicants under Article 18(1) are told to conduct testing, those under Article 18(2) to run tests; reports are reviewed within 30 days, extendable by 15 days",
  "All applicants are told to pay fees and collect the permit before running tests; reports are reviewed within 7 days, extendable by 7 days for site inspection",
  "All applicants are told to use a testing organization designated centrally; reports are reviewed within 60 days, extendable by 30 days with retesting"],
 "Article 33."),

(P,"第34條",2,"固污許可-製證領證",
 "審核機關受理各項許可證申請文件經審查符合規定者，應於幾日內完成證書製作並通知繳費領證？核發操作許可證另有何要求？",
 ["應於完成審查後十四日內完成證書製作並通知繳納證書費及領取許可證；核發操作許可證應令檢具目的事業主管機關核准設立登記或營運之許可文件",
  "應於完成審查後三十日內完成證書製作並通知繳納證書費及領取許可證；核發操作許可證應令檢具環境影響評估審查結論及承諾事項對照表",
  "應於完成審查後七日內完成證書製作並通知繳納證書費及領取許可證；核發操作許可證應令檢具最近一年之空污費繳費收據及申報書影本",
  "應於完成審查後六十日內完成證書製作並通知繳納證書費及領取許可證；核發操作許可證應令檢具專責人員合格證書及在職證明文件影本"],"a",
 "第34條：審核機關受理各項許可證申請文件，經審查符合第31條至第33條規定者，應於完成審查後十四日內完成證書製作並通知公私場所繳納證書費及領取許可證；依前項通知領取操作許可證者，應令公私場所檢具目的事業主管機關核准設立、登記或營運之許可文件，始得核發。",
 "Within how long must certificates be prepared, and what extra document is needed for an operating permit?",
 ["Within 14 days of completing review, with notice to pay the certificate fee and collect it; operating permits require the industry authority's establishment or operation approval",
  "Within 30 days of completing review, with notice to pay the certificate fee and collect it; operating permits require the EIA conclusions and a commitments comparison table",
  "Within 7 days of completing review, with notice to pay the certificate fee and collect it; operating permits require the past year's fee receipts and filing copies",
  "Within 60 days of completing review, with notice to pay the certificate fee and collect it; operating permits require personnel qualification and employment certificates"],
 "Article 34."),

(P,"第35條",2,"固污許可-審查意見",
 "審核機關受理許可證申請案件，經認定應補正資料者，其審查意見應如何提出？",
 ["審查意見應一次性提出；除因補正文件而新增之意見外，後續通知限期補正時不應有前次通知未列明之審查意見",
  "審查意見得分次陸續提出；後續通知限期補正時得增列任何前次通知未列明之審查意見，不受次數之限制",
  "審查意見應由中央主管機關統一提出；地方審核機關不得自行增列或減列任何補正事項及審查意見內容",
  "審查意見應經技師公會複核後提出；後續通知限期補正時應重新踐行完整之形式及實質審查程序"],"a",
 "第35條：審核機關受理各項許可證申請案件，經認定應補正資料者，其審查意見應一次性提出，除因公私場所補正文件而新增之審查意見外，後續通知限期補正時，不應有前次通知限期補正未列明之審查意見。此與揮發性有機物空氣污染管制及排放標準第8條第3項就使用計畫書審查之規定相同。",
 "How must review comments requiring supplementation be raised?",
 ["All comments must be raised at once; later supplementation notices may not add comments omitted from the earlier notice, except those arising from the supplements",
  "Comments may be raised in successive rounds; later notices may add any comments omitted earlier, without limit on the number of rounds",
  "Comments must be issued uniformly by the central authority; local reviewing authorities may not add or remove any supplementation items",
  "Comments must be verified by the engineers association before issuance; later supplementation notices must repeat the full formal and substantive review procedures"],
 "Article 35."),

(P,"第36條",2,"固污許可-補正情形",
 "審核機關受理許可證申請、變更、異動或展延，經審查有何情形之一者應即通知限期補正？",
 ["形式審查資料文件欠缺或不完整、未繳納審查費、設置許可證申請文件內容不合規定、操作許可證文件或現場勘查或檢測報告不合規定",
  "公私場所曾遭裁處罰鍰、專責人員人數不足、空污費有欠繳情形、鄰近居民提出陳情、目的事業主管機關表示意見尚未回覆",
  "申請文件未經技師簽證、申請人非負責人本人、申請時間逾越受理期間、申請案件數量超過審核機關年度處理量能上限",
  "廠址位於總量管制區內、製程屬高污染潛勢行業、使用進口燃料、曾申請試驗未完成、鄰近有空氣品質監測站設置"],"a",
 "第36條：審核機關受理各項許可證申請、變更、異動或展延，經審查公私場所有下列情形之一者，應即通知限期補正：形式審查之資料、文件有欠缺或不完整；未繳納審查費；設置許可證申請文件內容不合規定；操作許可證申請文件內容、現場勘查結果或空氣污染排放檢測報告不合規定；燃料使用許可證之申請文件內容不合規定；許可證展延之申請文件內容不合規定。第45條定有補正次數及總日數限制。",
 "Which findings require an immediate notice to supplement the application?",
 ["Missing or incomplete formal documents, unpaid review fees, non-conforming installation permit documents, or non-conforming operating documents, site inspection or test reports",
  "The premises was previously fined, dedicated personnel are insufficient, fees are in arrears, residents have complained, or the industry authority has not yet replied",
  "Documents lack engineer certification, the applicant is not the responsible person, filing is outside the acceptance period, or the caseload exceeds annual capacity",
  "The site lies in a total quantity control zone, the process is high-potential, imported fuel is used, a trial was unfinished, or a monitoring station is nearby"],
 "Article 36."),

(P,"第37條",3,"固污許可-合併審查",
 "審核機關受理設置及操作許可證之合併申請，其審查及核發程序為何？",
 ["依第三十一條及第三十二條審查，通過後通知領取設置許可證，並於檢具目的事業核准文件後通知試車，再依規定審查及通知領取操作許可證",
  "依第三十一條及第三十二條審查，通過後同時核發設置及操作許可證，公私場所得逕行安裝建造並操作，事後補送試車及檢測報告書",
  "依第三十一條及第三十二條審查，通過後先通知領取操作許可證，並於完成試車後始通知領取設置許可證及辦理相關繳費作業",
  "依第三十一條及第三十二條審查，通過後報請中央主管機關複審，經複審同意後一併核發設置及操作許可證並免除試車程序"],"a",
 "第37條：審核機關受理設置及操作許可證之合併申請，應依第31條及第32條規定審查，經審查通過後，通知公私場所領取設置許可證，並於公私場所檢具目的事業主管機關核准設立、登記或營運之相關證明文件影本後，通知公私場所進行試車，再依第20條、第33條及第34條規定審查及通知領取操作許可證。第22條定有合併申請之要件。",
 "What is the procedure for a combined installation and operating permit application?",
 ["Review under Articles 31 and 32, then notice to collect the installation permit, then a test-run notice after industry approval documents, then review and collection of the operating permit",
  "Review under Articles 31 and 32, then both permits are issued at the same time so installation and operation may begin, with test-run and emission testing reports filed afterwards",
  "Review under Articles 31 and 32, then notice to collect the operating permit first, with the installation permit collected only after the test run is completed",
  "Review under Articles 31 and 32, then referral to the central authority for re-examination, after which both permits are issued and the test run is waived"],
 "Article 37."),

(P,"第38條",2,"固污許可-合併記載",
 "審核機關受理第二十四條第二項之申請（申請操作許可證時一併申請燃料使用許可證），應如何辦理？",
 ["應依操作許可證之申請、審查及核發程序辦理，並將燃料使用許可證應記載事項合併於操作許可證記載，相同應記載事項得不重複核定",
  "應依燃料使用許可證之申請、審查及核發程序辦理，並將操作許可證應記載事項合併於燃料使用許可證記載，相同事項得不重複核定",
  "應分別依操作許可證及燃料使用許可證程序各自審查核發，並分別收取審查費及證書費，相同應記載事項亦應分別重複核定記載",
  "應報請中央主管機關指定審查程序後辦理，並將操作及燃料許可內容合併載於同一份許可證，惟有效期間應分別起算並分別展延"],"a",
 "第38條：審核機關受理第24條第2項申請，應依操作許可證之申請、審查及核發程序規定辦理，並將燃料使用許可證應記載事項合併於固定污染源操作許可證記載，其相同應記載事項得不重複核定。第24條第2項規定同時符合第2條及第3條者應於申請操作許可證時一併提出燃料使用許可證申請。",
 "How is a fuel use permit filed together with an operating permit handled?",
 ["Processed under the operating permit procedure, with the fuel permit particulars recorded in the operating permit and identical items not approved twice",
  "Processed under the fuel permit procedure, with the operating permit particulars recorded in the fuel permit and identical items not approved twice",
  "Processed separately under each procedure with separate fees, and identical particulars are approved and recorded separately in each permit",
  "Processed under a procedure designated by the central authority, with both contents in one permit but separate validity periods and renewals"],
 "Article 38."),

(P,"第39條",2,"固污許可-核實記載",
 "審核機關受理補發、換發許可證或改變許可證應記載事項之基本資料者，應如何辦理？",
 ["應依公私場所申請事項及其檢具之證明文件核實記載，不得於申請事項以外任意變更其他應記載事項",
  "得於審查時一併檢視全部許可內容，並依現行法規及實際操作情形逕行變更其他應記載事項",
  "應報請中央主管機關同意後始得記載，並得於申請事項以外增列必要之許可條件及管制項目",
  "應要求公私場所重新提送全部申請文件，並依新申請案之審查程序重新核定全部應記載事項"],"a",
 "第39條：審核機關受理公私場所依第29條規定申請補發、換發許可證或改變許可證應記載事項之基本資料者，應依公私場所申請事項及其檢具之證明文件核實記載，不得於許可證基本資料改變、補發或換發申請事項以外，任意變更其他應記載事項。第40條並限制審核機關不得依職權變更許可證應記載事項。",
 "How must the authority handle re-issuance or changes to a permit's basic data?",
 ["Record faithfully according to the items applied for and the documents filed, without arbitrarily altering other recorded particulars",
  "Review the entire permit content at the same time and alter other recorded particulars in line with current rules and actual operation",
  "Record only after obtaining central approval, and add necessary permit conditions and control items beyond the items applied for",
  "Require the premises to refile all application documents and re-determine all recorded particulars as a new application"],
 "Article 39."),

(P,"第40條",2,"固污許可-職權變更禁止",
 "審核機關就已核發之許可證，於何種情形得予更正？其職權變更之限制為何？",
 ["發現許可證有誤寫、誤算或其他類此顯然錯誤者應即更正並限期換領證書；除此之外不得依職權變更許可證應記載事項",
  "發現許可證所載排放量高於同業平均水準者應即更正並限期換領證書；並得依職權加嚴其應記載之許可排放量數值",
  "發現公私場所有違規紀錄者應即更正許可內容並限期換領證書；並得依職權增列監測、檢測及申報頻率等義務事項",
  "發現法規修正致許可內容與現行規定不符者應即更正證書；並得依職權變更全部許可條件以符合最新法規要求"],"a",
 "第40條：審核機關除發現核發之許可證有誤寫、誤算或其他類此未符合本法規定之顯然錯誤者，應即更正並限期公私場所換領證書外，不得依職權變更許可證應記載事項。第42條並列舉不得以任何形式之處分增加法規所未明定義務之情形。",
 "When may the authority correct an issued permit, and what limits apply?",
 ["Obvious clerical or calculation errors must be corrected with a deadline to exchange the certificate; otherwise recorded particulars may not be changed ex officio",
  "Permits showing emissions above the industry average must be corrected with a deadline to exchange it; permitted emission figures may be tightened ex officio",
  "Permits held by premises with violation records must be corrected with a deadline to exchange it; monitoring and reporting duties may be added ex officio",
  "Permits inconsistent with amended law must be corrected; all permit conditions may be changed ex officio to match the latest legal requirements"],
 "Article 40."),

(P,"第41條",3,"固污許可-操作條件核定",
 "公私場所依第二十條進行試車或檢測時，審核機關核定操作許可證與空氣污染物排放有關之操作條件應依何原則辦理？",
 ["主要原（物）料及燃料使用量達申請之百分之八十以上者依申請內容核定；無法達百分之八十以上者以實際操作條件之一點二倍核定",
  "主要原（物）料及燃料使用量達申請之百分之六十以上者依申請內容核定；無法達百分之六十以上者以實際操作條件之一點五倍核定",
  "主要原（物）料及燃料使用量達申請之百分之九十以上者依申請內容核定；無法達百分之九十以上者以實際操作條件之二倍核定",
  "主要原（物）料及燃料使用量達申請之百分之五十以上者依申請內容核定；無法達百分之五十以上者以最大設計量之一半核定"],"a",
 "第41條：公私場所依第20條規定進行試車或檢測時，審核機關核定操作許可證與空氣污染物排放有關之操作條件，應依下列原則辦理：主要原（物）料及燃料使用量達申請之百分之八十以上者，應依申請內容作為操作許可證之核定內容；無法達申請之百分之八十以上者，應以試車或檢測時之實際操作條件之一．二倍，作為核定內容。第56條之產能快速變動者不受此限。",
 "How are emission-related operating conditions approved after a test run or testing?",
 ["If main materials and fuel reach 80 percent or more of the application, the application content is approved; otherwise 1.2 times the actual conditions",
  "If main materials and fuel reach 60 percent or more of the application, the application content is approved; otherwise 1.5 times the actual conditions",
  "If main materials and fuel reach 90 percent or more of the application, the application content is approved; otherwise 2 times the actual conditions",
  "If main materials and fuel reach 50 percent or more of the application, the application content is approved; otherwise half the maximum design capacity"],
 "Article 41."),

(P,"第42條",3,"固污許可-不得增加義務",
 "審核機關核定操作許可證內容時，不得以任何形式之處分增加法規所未明定之義務，下列何者屬其禁止事項？",
 ["對非屬排放標準適用對象逕予指定適用該標準、對非指定公告應設自動監測設施者指定設置、對非應定期檢驗測定者指定實施定期檢驗",
  "對已取得操作許可證者要求依核定內容操作、對指定公告污染源要求設置專責人員、對應實施環評者納入審查結論於許可證內容",
  "對申請文件不完整者通知限期補正、對未繳納審查費者駁回申請、對停工一年以上者依規定廢止其已核發之各項許可證",
  "對試車期間違反本法者令其停止試車、對未依試車計畫進行者駁回操作許可證申請、對顯然錯誤之許可證予以更正換發"],"a",
 "第42條：審核機關應確實審核據以核定操作許可證內容，不得以任何形式之處分增加法規所未明定之義務，包括：非屬本法第20條第2項所定排放標準之適用對象，逕予指定適用該排放標準；非屬指定公告應設置自動監測設施之固定污染源，指定設置自動監測設施或指定連線；非屬應實施定期檢驗測定之固定污染源，指定實施定期檢驗；非屬中央主管機關所定燃料種類混燒比例及成分標準，逕予指定適用；其他非經法規明定之義務。第51條之環評納入事項不受此限。",
 "Which acts are prohibited as imposing duties not prescribed by law?",
 ["Applying an emission standard to a source not subject to it, ordering automatic monitors where not designated, or ordering periodic testing where not designated",
  "Requiring permit holders to operate as approved, requiring dedicated personnel at designated sources, or incorporating EIA conclusions into permit content",
  "Requiring supplementation of incomplete applications, rejecting applications with unpaid fees, or revoking permits after a year of suspended operation",
  "Ordering a halt to a test run that breaches the Act, rejecting applications where the test-run plan was not followed, or correcting obvious permit errors"],
 "Article 42."),

(P,"第43條",3,"固污許可-展延不得變更",
 "審核機關審查許可證展延時，就許可內容之變更有何限制？",
 ["除符合本法第三十條第四項規定情形得據以變更外，不得變更操作許可內容及燃料使用許可內容之各項記載事項",
  "得於展延審查時一併檢討並加嚴操作許可內容及燃料使用許可內容，以符合最新排放標準及管制規定之要求",
  "應一律重新核定操作許可內容及燃料使用許可內容，並依展延當時之法規重新計算其年許可排放量數值",
  "得依公私場所前三年實際操作情形，逕行減列操作許可內容所載之原（物）料用量、產品產量及排放量"],"a",
 "第43條：審核機關審查許可證展延，應依本法第30條規定辦理，除符合本法第30條第4項規定情形得據以變更外，不得變更第21條第1項第3款操作許可內容及第25條第1項第3款燃料使用許可內容。所稱變更包含以任何形式之處分增加或減少許可內容所載主要原（物）料、燃料之種類成分用量、產品產量、操作條件與期程、防制設施種類處理容量效率、核定年許可排放量、監測與定期檢測及申報之頻率及項目等。",
 "What limits apply to changing permit content during renewal review?",
 ["Except where Article 30, paragraph 4 of the Act applies, the operating permit content and fuel use permit content may not be changed",
  "The operating permit content and fuel use permit content may be reviewed and tightened at renewal to meet the latest standards and controls",
  "The operating permit content and fuel use permit content must be re-determined entirely under the law in force at the time of renewal",
  "The materials, product output and emissions recorded in the operating permit may be reduced based on the past three years of actual operation"],
 "Article 43."),

(P,"第44條",2,"固污許可-原期限核定",
 "審核機關受理依第二十七條、第二十八條申請或依第二十九條申請換補發者，其許可證期限應如何核定？併同展延者如何計算？",
 ["應依原許可證期限核定；申請期間於原許可證期限屆滿前三至六個月內者，得併同提送展延申請，審查與補正日數分別計算",
  "應依申請日重新起算五年核定；申請期間於原許可證期限屆滿前一至三個月內者，得併同提送展延申請，審查日數合併計算",
  "應依中央主管機關指定之期限核定；申請期間於原許可證期限屆滿後三十日內者，得補行提送展延申請並免計補正日數",
  "應依公私場所申請之期限核定；申請期間不受原許可證期限屆滿前後之限制，展延申請與異動申請不得同時提出辦理"],"a",
 "第44條：審核機關受理依第27條申請操作許可證或第28條申請燃料使用許可證者、依第29條申請操作許可證換發或補發者，應依原許可證期限核定；前項申請期間於原許可證期限屆滿前三至六個月內者，公私場所得併同提送許可證展延申請，審查與補正日數分別計算。",
 "How is the permit period set for change or re-issuance applications, and how does renewal combine?",
 ["Set according to the original permit period; if filed three to six months before expiry, a renewal may be filed together, with review and supplementation days counted separately",
  "Set as a fresh five years from the filing date; if filed one to three months before expiry, a renewal may be filed together, with review days counted jointly",
  "Set according to a period designated by the central competent authority; if filed within 30 days after expiry, a renewal may be filed late with supplementation days waived",
  "Set according to the period requested by the premises; filing is unrestricted by expiry timing, and renewal and change applications may not be filed together"],
 "Article 44."),

(P,"第46條",3,"固污許可-駁回情形",
 "審核機關審查許可證申請，有下列何種情形之一者應予以駁回？",
 ["固定污染源設置於不得設置生產設施之處所或用地；經目的事業主管機關認定有違法而不得設置；申請操作許可證之排放量估算大於本法第六條規模",
  "固定污染源鄰近有噪音敏感受體；經目的事業主管機關認定產業別非屬獎勵項目；申請操作許可證之排放量估算高於同業平均水準之數值",
  "固定污染源設置於總量管制區內；經地方民意代表或居民提出反對意見；申請操作許可證之排放量估算大於前一年度之實際排放量數值",
  "固定污染源使用進口生煤或石油焦；經目的事業主管機關認定產能過剩；申請操作許可證時未同時申請燃料使用許可證及設置專責人員"],"a",
 "第46條：審核機關審查有下列情形之一者應予駁回：申請設置許可證，其固定污染源設置於不得設置生產設施之處所或用地；申請設置許可證，其固定污染源經目的事業主管機關認定有違法而不得設置；申請許可證變更、異動或展延，其設置許可證核定之任一污染物年許可排放量未達本法第6條所定規模，而申請操作許可證之任一污染物年排放量估算結果大於該規模；申請變更異動展延而總異動排放量累計達第4條第1項第2款或第3款卻未提出設置許可證申請。",
 "Which findings require rejection of a permit application?",
 ["The source sits on land where production facilities are barred; the industry authority finds it unlawful to install; or the estimated operating emissions exceed the Article 6 scale",
  "The source is near noise-sensitive receptors; the industry authority finds the sector is not an incentivized one; or estimated emissions exceed the industry average level",
  "The source sits within a total quantity control zone; local representatives or residents object; or estimated emissions exceed last year's actual emissions",
  "The source uses imported coal or petroleum coke; the industry authority finds overcapacity; or no fuel permit or dedicated personnel were applied for"],
 "Article 46."),

(P,"第47條",2,"固污許可-停止試車",
 "公私場所執行試車計畫或空氣污染物排放檢測計畫期間，有何情形審核機關應令其改善、停止試車或檢測？其效果為何？",
 ["依計畫進行而有違反本法規定，或未依計畫內容進行試車或檢測；經令停止試車或檢測者，審核機關應駁回其操作許可證申請",
  "依計畫進行而有違反本法規定，或未依計畫內容進行試車或檢測；經令停止試車或檢測者，得於改善完成後逕行核發操作許可證",
  "試車期間產量未達申請量之八成，或檢測結果高於同業平均排放濃度值；經令停止試車或檢測者，應重新提出設置許可證申請",
  "試車期間鄰近居民提出陳情，或檢測機構未經中央主管機關許可；經令停止試車或檢測者，應由中央主管機關重新指定檢測"],"a",
 "第47條：公私場所執行試車計畫或檢測計畫期間，依計畫內容進行而有違反本法規定，或未依計畫內容進行試車或檢測者，審核機關應令其改善、停止試車或檢測。有前者情形經改善完成者得繼續試車；有後者情形且違反本法規定者，地方主管機關應按違規情節依本法處分；經令停止試車或檢測者，審核機關應駁回其操作許可證申請。",
 "When must a test run or testing be halted, and what is the consequence?",
 ["Where the plan is followed but the Act is breached, or the plan is not followed; if ordered to stop, the operating permit application is rejected",
  "Where the plan is followed but the Act is breached, or the plan is not followed; if ordered to stop, the operating permit may still be issued after correction",
  "Where output during the test run is below 80 percent of the application, or results exceed the industry average; if stopped, a new installation permit is required",
  "Where nearby residents complain, or the testing organization lacks a central permit; if stopped, the central authority designates new testing"],
 "Article 47."),

(P,"第48條",2,"固污許可-併同申請",
 "公私場所二以上固定污染源合由同一排放管道排放空氣污染物，其任一固定污染源申請核發許可證時，審核機關得如何辦理？",
 ["經審核機關認定與申請者之空氣污染物排放有關之固定污染源，審核機關得要求其併同申請許可證",
  "經審核機關認定排放管道口徑不足者，審核機關得要求其先行拆除共用管道後再分別提出申請",
  "經審核機關認定屬同一負責人所有者，審核機關應命其合併為單一固定污染源後重新申請許可",
  "經審核機關認定排放量合計超過規模者，審核機關應駁回其申請並命其申請設置許可證變更"],"a",
 "第48條：審核機關辦理公私場所二以上固定污染源合由同一排放管道排放空氣污染物，其任一固定污染源依本法第24條或第88條規定申請核發許可證時，經審核機關認定與申請者之空氣污染物排放有關之固定污染源，審核機關得要求其併同申請。",
 "When two or more sources share one stack, what may the authority require on a permit application?",
 ["Sources found by the authority to be related to the applicant's emissions may be required to apply together",
  "Where the authority finds the stack diameter insufficient, the shared stack must be dismantled before separate applications",
  "Where the authority finds them owned by one responsible person, they must be merged into a single source and re-apply",
  "Where the authority finds combined emissions exceed the scale, the application is rejected and a permit change required"],
 "Article 48."),

(P,"第49條",3,"固污許可-檢測項目",
 "審核機關審查空氣污染物排放檢測計畫時，其檢測項目之限制及得免實施檢測之情形為何？",
 ["檢測以預估需核定之四種污染物及特定業別排放標準規範之污染物為限；因故未能設置採樣設施或證明無特定污染物排放者得免檢測",
  "檢測以中央主管機關公告之全部空氣污染物項目為限；因故未能設置採樣設施或證明無特定污染物排放者仍應委外檢測不得免除",
  "檢測以地方主管機關逐案指定之污染物項目為限；經公私場所自行評估認無檢測必要並報請備查者即得免實施檢測作業",
  "檢測以周界標準所規範之污染物項目為限；因檢測費用過高或檢測機構排程不及者得報經審核機關同意後免實施檢測"],"a",
 "第49條：審核機關審查依第18條提出之空氣污染物排放檢測計畫時，其檢測應以下列項目為限：預估需核定之硫氧化物、氮氧化物、粒狀污染物及揮發性有機物；主管機關依本法第20條第2項訂定特定業別或設施排放標準規範之空氣污染物。非屬前述項目者得以自廠係數、公告係數或替代計算方式推估確認。有固定污染源因故未能依本法第48條第4項設置檢查或鑑定設施致不能採樣、或檢具證明無特定污染物排放之文件者，經同意得免實施檢測。",
 "What limits apply to testing items, and when may testing be waived?",
 ["Testing is limited to the four pollutants to be approved and pollutants under sector-specific standards; waivers apply where sampling facilities cannot be installed or absence is proven",
  "Testing must cover every air pollutant announced by the central competent authority; even where sampling facilities cannot be installed at all, outsourced testing is still required",
  "Testing is limited to pollutants designated case by case by the local authority; a self-assessment filed for record is enough to waive testing",
  "Testing is limited to pollutants under the boundary standard; high testing costs or scheduling difficulties allow a waiver with the authority's consent"],
 "Article 49."),

(P,"第50條",2,"固污許可-操作條件監控",
 "審核機關核定許可證中有關固定污染源與防制設施之操作條件，應如何辦理？",
 ["應依其設計或實際操作情形，核定足供監控符合實際運作情形之操作條件、紀錄項目及頻率，並指定設置足供查驗之監測儀表",
  "應依中央主管機關公告之統一標準值，核定所有行業一致之操作條件、紀錄項目及頻率，並指定設置連續自動監測設施",
  "應依公私場所自行提出之條件全數照案核定操作條件、紀錄項目及頻率，審核機關不得指定設置任何監測儀表或設備",
  "應依鄰近同業之操作條件平均值，核定其操作條件、紀錄項目及頻率，並指定設置與主管機關連線之監測設施設備"],"a",
 "第50條：審核機關核定許可證中有關固定污染源與防制設施之操作條件，應依其設計或實際操作情形，核定足供監控符合實際運作情形之操作條件、紀錄項目及頻率，並指定公私場所固定污染源設置足供查驗符合操作條件之監測儀表。第42條第2款則限制不得對非指定公告者指定設置自動監測設施或指定連線。",
 "How must operating conditions for sources and control facilities be approved?",
 ["Based on design or actual operation, approving conditions, record items and frequencies sufficient to monitor real operation, and designating verifiable monitoring instruments",
  "Based on uniform values announced centrally, approving identical conditions, record items and frequencies for all sectors, and designating continuous automatic monitors",
  "Based entirely on the conditions proposed by the premises, approving them as filed, with the authority barred from designating any monitoring instruments",
  "Based on the average conditions of nearby peers, approving conditions, record items and frequencies, and designating monitors linked to the authority"],
 "Article 50."),

(P,"第51條",2,"固污許可-環評納入",
 "公私場所固定污染源屬應實施環境影響評估者，其許可證內容應如何處理？",
 ["其許可證內容應納入經環境影響評估法審查通過之書件所載內容及審查結論，且該納入事項不受第四十二條規定之限制",
  "其許可證內容得由審核機關斟酌是否納入環境影響評估審查結論，惟納入事項仍應受第四十二條規定之限制",
  "其許可證內容不得納入環境影響評估審查結論，環評承諾事項應由目的事業主管機關另行列管及查核執行",
  "其許可證內容應僅納入環境影響評估書件中有關空氣污染之數值，其餘審查結論由中央主管機關逐案認定"],"a",
 "第51條：審核機關受理公私場所固定污染源許可證之申請，屬應實施環境影響評估者，其許可證內容，應納入經環境影響評估法審查通過之書件所載內容及審查結論；前項納入許可證內容事項，不受第42條規定之限制。第18條第1項第5款並要求申請操作許可證時檢具環評審查通過書件及結論。",
 "How is EIA content handled in permits for sources subject to assessment?",
 ["The permit content must incorporate the approved EIA documents and conclusions, and those incorporated items are not subject to the Article 42 restriction",
  "The authority may decide whether to incorporate the EIA conclusions, and incorporated items remain subject to the Article 42 restriction",
  "The permit content may not incorporate EIA conclusions, which are separately monitored and enforced by the industry competent authority",
  "The permit content incorporates only the air pollution figures in the EIA documents, with all other review conclusions decided case by case centrally"],
 "Article 51."),

(P,"第52條",3,"固污許可-撤銷廢止",
 "審核機關得撤銷或廢止固定污染源許可證之情形，下列何者正確？",
 ["申請文件有虛偽不實、新設公私場所已停止設置設備或無繼續設廠事實、停工或停業一年以上、主要生產設施已搬遷無繼續生產事實",
  "申請文件有虛偽不實、年度排放量超過同業平均值、停工或停業三個月以上、主要生產設施更新未於三十日內報請備查",
  "未依規定申報空污費、專責人員離職未於期限內補齊、停工或停業六個月以上、鄰近居民陳情案件累計達三件以上",
  "未依規定設置連續自動監測設施、檢測結果超過排放標準一次、停工或停業三年以上、未參加主管機關辦理之講習"],"a",
 "第52條：有下列情形之一者，審核機關得撤銷或廢止許可證：申請文件有虛偽不實；新設公私場所已停止設置固定污染源設備或經認定無繼續設廠（場）事實；停工或停業一年以上（有正當理由經目的事業主管機關核准者除外）；主要生產設施已搬遷經認定無繼續生產製造加工之事實；改變生產製程燃料或防制設施致非屬應申請許可之固定污染源；非屬應申請許可者已取得許可證；歇業、繳銷工廠登記證或經公告註銷；違反本辦法並具本法第96條第1項第2款至第7款情形之一。",
 "Which grounds allow revocation of a stationary source permit?",
 ["False application documents; a new premises has stopped installing equipment or shows no intent to build; suspension over one year; main facilities relocated with no production",
  "False application documents; annual emissions above the industry average level; suspension over three months; renewal of main production facilities not filed within 30 days",
  "Failure to report fees; failure to replace departed dedicated personnel in time; suspension over six months; three or more accumulated resident complaints",
  "Failure to install continuous monitors; one exceedance of the emission standard; suspension over three years; failure to attend authority training sessions"],
 "Article 52."),

(P,"第53條",2,"固污許可-檢測通知",
 "公私場所執行本辦法規定之空氣污染物檢測作業時應如何通知？二以上相同污染源得如何辦理？",
 ["應於執行檢測前七日通知審核機關；型式、規模、操作條件及防制設施均相同者，得報經核准擇一定數量污染源進行檢測",
  "應於執行檢測前三十日通知審核機關；型式、規模、操作條件及防制設施均相同者，得逕自擇一定數量污染源進行檢測",
  "應於執行檢測後七日內通知審核機關；型式、規模、操作條件及防制設施均相同者，仍應就每一污染源分別進行檢測",
  "應於執行檢測前一日通知審核機關；型式、規模、操作條件及防制設施均相同者，得由技師簽證代替實際檢測作業"],"a",
 "第53條：公私場所執行本辦法規定之空氣污染物檢測作業時，應於執行檢測前七日通知審核機關；前項檢測作業，公私場所有二個以上固定污染源，其型式、規模、操作條件及污染防制設施均相同者，得準用固定污染源自行或委託檢測及申報管理辦法規定，報經審核機關核准，擇一定數量污染源進行檢測作業。",
 "How must testing be notified, and how may identical sources be handled?",
 ["Notify the reviewing authority seven days before testing; where type, scale, conditions and control facilities are identical, a set number of sources may be tested with approval",
  "Notify the reviewing authority thirty days before testing; where type, scale, conditions and control facilities are identical, a set number may be tested without approval",
  "Notify the reviewing authority within seven days after testing; even where type, scale, conditions and facilities are identical, each source must be tested separately",
  "Notify the reviewing authority one day before testing; where type, scale, conditions and facilities are identical, engineer certification may replace actual testing"],
 "Article 53."),

(P,"第54條",2,"固污許可-定期檢驗替代",
 "公私場所固定污染源依本法第二十二條實施定期檢驗測定期間，適逢操作內容異動且已重新申請操作許可證者，得如何辦理？",
 ["得以試車進行之空氣污染物排放檢測替代該次定期檢驗測定",
  "得申請展延該次定期檢驗測定期限至異動完成後一年內辦理",
  "應分別辦理定期檢驗測定及試車檢測，二者不得相互替代之",
  "得由審核機關逕依前次定期檢驗測定結果核定其排放濃度值"],"a",
 "第54條：公私場所固定污染源依本法第22條規定實施定期檢驗測定期間，適逢固定污染源因操作內容異動，且已重新申請操作許可證者，得於試車進行之空氣污染物排放檢測替代。",
 "How may periodic testing be handled when it coincides with a permit change re-application?",
 ["The emission testing carried out during the test run may substitute for that periodic test",
  "An extension of the periodic testing deadline to one year after the change may be sought",
  "Periodic testing and test-run testing must both be done and cannot substitute for each other",
  "The authority may set the emission concentration based on the previous periodic test result"],
 "Article 54."),

(P,"第55條",2,"固污許可-第三類污染源",
 "公私場所具有第二條指定公告之第三類固定污染源者，其設置及操作許可之程序為何？",
 ["得向審核機關申請同意設置，經確認製程符合公告條件後函復同意；並應於完成設置後三十日內依第十八條提出操作許可證申請",
  "得向審核機關申請同意設置，經確認製程符合公告條件後函復同意；並得於完成設置後逕行操作，免申請操作許可證",
  "應依第十二條申請設置許可證並經核發後始得設置；並應於完成設置後九十日內依第十八條提出操作許可證申請",
  "應報請中央主管機關逐案核准後始得設置；並應於完成設置後六個月內依第二十四條提出燃料使用許可證申請"],"a",
 "第55條：公私場所具有第2條指定公告之第三類固定污染源者，得向審核機關申請同意設置，審核機關經確認固定污染源製程符合公告條件後，得函復同意其設置；公私場所應於前項固定污染源完成設置後三十日內，依第18條規定向審核機關提出操作許可證申請。第三類為可簡化申請之固定污染源。",
 "What procedure applies to Class 3 stationary sources?",
 ["Apply for consent to install; the authority confirms the process meets the announced conditions and replies with consent; an operating permit is then filed within 30 days of completion",
  "Apply for consent to install; the authority confirms the process meets the announced conditions and replies with its consent; operation may then begin without an operating permit",
  "Apply for an installation permit under Article 12 and install only after issuance; an operating permit is then filed within 90 days of completion",
  "Apply case by case for central approval before installing; a fuel use permit is then filed under Article 24 within six months of completion"],
 "Article 55."),

(P,"第56條",3,"固污許可-產能快速變動",
 "公私場所因產能或產品變動快速須持續申請許可產能異動者，得如何申請？審核機關得以何者作為核發依據？",
 ["得一次申請未來五年內將達成之產能條件或最大操作條件許可，並得以一定製程條件作為操作條件；審核機關得以未來五年內最大產能或最大操作條件核發",
  "得一次申請未來三年內將達成之產能條件或最大操作條件許可，並得以一定製程條件作為操作條件；審核機關得以未來三年內平均產能條件核發",
  "得一次申請未來十年內將達成之產能條件或最大操作條件許可，並免除試車及檢測程序；審核機關應以最大設計量之一點五倍核發",
  "得逐年申請當年度之產能條件或最大操作條件許可，並應每次重新試車檢測；審核機關應以前一年度實際產能條件作為核發依據"],"a",
 "第56條：公私場所固定污染源因產能或產品變動快速，須持續申請許可產能異動或變更者，得一次申請未來五年內將達成之產能條件許可或與空氣污染物排放有關之主要原（物）料、燃料使用量之最大操作條件許可；其進行試車或檢測時，得以一定製程條件作為操作條件，不受第41條規定之限制。申請時應檢具五年內預定產能資料、最大條件下預估排放量、變動說明、連續自動監測設施計畫或替代監測方案等。審核機關得以未來五年內最大產能條件或最大操作條件作為核發依據。",
 "How may sources with rapidly changing capacity apply, and what may the authority use as the basis for issuance?",
 ["Apply once for capacity or maximum operating conditions to be reached within five years, using set process conditions; the authority may issue on the five-year maximum capacity or conditions",
  "Apply once for capacity or maximum operating conditions to be reached within three years, using set process conditions; the authority may issue on the three-year average capacity level",
  "Apply once for capacity or maximum operating conditions within ten years and skip test runs and testing; the authority must issue at 1.5 times the maximum design capacity",
  "Apply yearly for that year's capacity or maximum operating conditions with a new test run each time; the authority must issue on last year's actual capacity conditions"],
 "Article 56."),

(P,"第57條",3,"固污許可-快速變動操作",
 "依第五十六條取得操作許可證之產能變動快速者，其操作及檢測規定為何？",
 ["操作條件之產量或原（物）料燃料達許可使用量後每增加核定量百分之二十時，應於一個月內完成檢測，檢測時操作條件應達實際操作條件百分之八十以上",
  "操作條件之產量或原（物）料燃料達許可使用量後每增加核定量百分之五十時，應於三個月內完成檢測，檢測時操作條件應達實際操作條件百分之六十以上",
  "操作條件之產量或原（物）料燃料達許可使用量後每增加核定量百分之十時，應於六個月內完成檢測，檢測時操作條件應達實際操作條件百分之九十以上",
  "操作條件之產量或原（物）料燃料達許可使用量後每增加核定量百分之三十時，應於一年內完成檢測，檢測時操作條件應達最大設計量百分之七十以上"],"a",
 "第57條：產能變動快速者，操作條件之產品產量、與排放有關之原（物）料或燃料達許可使用量後，每增加許可核定量百分之二十時，應於一個月內依規定完成檢測，檢測時操作條件應達實際操作條件百分之八十以上；並應定期記錄相關操作事項，於每年一月、四月、七月及十月之月底前向地方主管機關申報上一季紀錄。產品變動快速者則應每日記錄、至少每半年檢測一次並每半年定期申報。且不受第9條百分之十容許差值之限制。",
 "What operating and testing rules apply to rapidly changing capacity holders?",
 ["Once permitted usage is reached, each further 20 percent of the approved amount requires testing within one month, at operating conditions of at least 80 percent of actual conditions",
  "Once permitted usage is reached, each further 50 percent of the approved amount requires testing within three months, at operating conditions of at least 60 percent of actual conditions",
  "Once permitted usage is reached, each further 10 percent of the approved amount requires testing within six months, at operating conditions of at least 90 percent of actual conditions",
  "Once permitted usage is reached, each further 30 percent of the approved amount requires testing within one year, at operating conditions of at least 70 percent of design capacity"],
 "Article 57, subparagraph 1."),

(P,"第58條",2,"固污許可-工商機密",
 "公私場所依本辦法應由審核機關將申請資料公開於中央主管機關指定網站者，得如何處理？",
 ["得依固定污染源管理資訊公開及工商機密審查辦法申請工商機密審查；經審查通過之核准文件應作為申請許可證檢具之文件",
  "得逕行要求審核機關不予公開全部申請資料；經公私場所自行認定為機密者即免予公開並免檢具任何證明文件",
  "得於資料公開期間屆滿後申請撤回已公開之資料；經審核機關同意後應將已公開資料自指定網站移除並銷毀",
  "得申請延後公開時間至許可證核發後六個月；經中央主管機關核准後始得免除申請資料之公開義務及責任"],"a",
 "第58條：公私場所依本辦法規定應由審核機關將申請資料公開於中央主管機關指定網站者，得依固定污染源管理資訊公開及工商機密審查辦法申請工商機密審查；依前項規定經審查通過之核准（定）文件，應作為公私場所依第12條、第18條或第37條申請許可證檢具之文件。第31條第4項規定申請資料應公開於指定網站七日。",
 "How may trade secrets in publicly disclosed application data be handled?",
 ["Apply for trade secret review under the disclosure and trade secret review regulation; the approval document is then filed with the permit application",
  "Simply require the authority not to disclose any application data; self-designation as confidential suffices without any supporting document",
  "Apply to withdraw disclosed data after the disclosure period; with consent the data is removed from the designated website and destroyed",
  "Apply to postpone disclosure until six months after permit issuance; central approval then removes the disclosure obligation entirely"],
 "Article 58."),

(P,"第59條",2,"固污許可-簽證項目",
 "第三十二條所指申請文件應經技師簽證之內容，應包含下列何項目？",
 ["第十三條第四款至第十一款之空氣污染防制計畫內容、第十八條第一項第二款及第三款、第十九條第四款至第九款之防制設施說明書內容",
  "第十三條全部十二款之空氣污染防制計畫內容、第十八條第一項全部七款文件、第十九條全部十款之防制設施說明書內容",
  "第十六條設置許可證應記載事項、第二十一條操作許可證應記載事項、第二十五條燃料使用許可證應記載事項之全部內容",
  "第六條年許可排放量推估依據、第七條用產量核定方式、第八條處理效率核定方式及第九條容許差值之計算說明資料"],"a",
 "第59條：第32條所指申請文件應經環境工程技師或其他相關專業技師簽證之內容，應包含：第13條第4款至第11款之空氣污染防制計畫內容；第18條第1項第2款及第3款（防制計畫差異說明書及試車計畫書）；第19條第4款至第9款之空氣污染防制設施說明書內容；其他經中央主管機關指定之項目。",
 "Which contents must be covered by the engineer's certification under Article 32?",
 ["Article 13 subparagraphs 4 to 11 of the control plan, Article 18(1) subparagraphs 2 and 3, and Article 19 subparagraphs 4 to 9 of the facility statement",
  "All twelve subparagraphs of Article 13, all seven documents under Article 18(1), and all ten subparagraphs of Article 19 of the facility statement",
  "All recorded particulars of the installation permit under Article 16, the operating permit under Article 21, and the fuel use permit under Article 25",
  "The estimation basis under Article 6, the quantity approval method under Article 7, the efficiency method under Article 8, and the tolerance under Article 9"],
 "Article 59."),

(P,"第60條",1,"固污許可-專責確認",
 "公私場所依本辦法提出之各項許可證申請資料，應由何人確認申請內容並簽章？未設專責單位或人員者如何辦理？",
 ["應由該公私場所設置之空氣污染防制專責人員確認申請內容並簽章；未設置者得由負責人或其指定代理人為之",
  "應由環境工程技師確認申請內容並簽章；未委任技師者得由該公私場所之任一從業人員代為確認並簽章",
  "應由目的事業主管機關指派人員確認申請內容並簽章；未指派者得由地方主管機關代為確認申請內容",
  "應由檢驗測定機構之採樣人員確認申請內容並簽章；未委託檢測機構者得由設備供應商代為確認簽章"],"a",
 "第60條：公私場所依本辦法規定提出之各項許可證申請資料，應由該公私場所設置之空氣污染防制專責人員確認申請內容並簽章；未設置空氣污染防制專責單位或人員者，得由公私場所負責人或其指定代理人為之。",
 "Who must confirm and sign permit application materials?",
 ["The premises' dedicated air pollution control personnel; where none are appointed, the responsible person or a designated deputy may do so",
  "An environmental engineer; where none is engaged, any employee of the premises may confirm and sign the materials",
  "A person assigned by the industry competent authority; where none is assigned, the local competent authority may confirm the materials",
  "The sampling staff of a testing organization; where none is engaged, the equipment supplier may confirm and sign"],
 "Article 60."),

(P,"第61條",2,"固污許可-停止委託",
 "經中央主管機關委託之機關有何情形時，中央主管機關得公告停止部分或全部委託？",
 ["受委託機關無法配合執行許可管制業務經認定、地方主管機關提出不宜繼續委託之理由經認可、依法實施總量管制另有規定、受委託機關提出不再接受委託",
  "受委託機關年度審查案件數量未達目標值、地方主管機關提出增加委託經費之要求、轄區內空氣品質未達標準、受委託機關人事異動頻繁",
  "受委託機關曾發生審查逾期情事一次以上、地方主管機關提出行政區調整之計畫、轄區內公私場所家數減少、受委託機關搬遷辦公處所",
  "受委託機關未依規定辦理教育訓練、地方主管機關提出預算不足之說明、轄區內發生空氣污染陳情案件、受委託機關更換首長人選"],"a",
 "第61條：經中央主管機關委託之機關有下列情形之一者，中央主管機關得公告停止部分或全部委託：受委託機關無法配合中央與地方主管機關執行許可管制業務經中央主管機關認定；地方主管機關提出受委託機關不宜繼續接受委託之理由報經中央主管機關認可；主管機關依法實施總量管制另有相關規定；受委託機關提出不再繼續接受委託理由報經同意；其他經認無委託之必要。此規定於地方委託之機關辦理燃料許可事項準用之。",
 "When may the central authority announce suspension of a delegation?",
 ["The agency cannot support permit control work as determined centrally; the local authority's reasons are endorsed; total quantity control rules apply; or the agency withdraws",
  "The agency's annual caseload misses its target; the local authority requests more funding; local air quality fails standards; or the agency has frequent staff turnover",
  "The agency has been late in review at least once; the local authority plans boundary adjustments; local premises have decreased; or the agency has relocated offices",
  "The agency has not run required training; the local authority reports insufficient budget; local pollution complaints occur; or the agency has changed its head"],
 "Article 61."),

(P,"第62條",3,"固污許可-過渡規定",
 "本辦法發布前已使用燃料之公私場所，及已領有生煤使用許可證者，應如何辦理？",
 ["已使用燃料者應自燃料混燒比例及成分標準發布日起一年內申請燃料使用許可證；已領生煤許可證者得使用至期限屆滿並於屆滿前三至六個月內申請展延換發",
  "已使用燃料者應自本辦法發布日起三個月內申請燃料使用許可證；已領生煤許可證者應即繳回原證並重新申請燃料使用許可證後始得繼續使用",
  "已使用燃料者應自燃料混燒比例及成分標準發布日起三年內申請燃料使用許可證；已領生煤許可證者得無限期繼續使用至設備汰換為止",
  "已使用燃料者免申請燃料使用許可證僅需報請備查；已領生煤許可證者應於本辦法發布日起六個月內申請變更為燃料使用許可證"],"a",
 "第62條：本辦法發布前公私場所已使用燃料者，應自公私場所固定污染源燃料混燒比例及成分標準發布日起一年內，依本辦法申請燃料使用許可證；本辦法發布前已依生煤、石油焦或其他易致空氣污染之物質販賣或使用許可證管理辦法領有生煤使用許可證者，得於該許可證有效期限屆滿前繼續使用，並於屆滿前三至六個月內申請展延並換發燃料使用許可證。審核機關應依生煤許可證內容以操作許可證之製程為單位分別核定各製程燃料使用量。",
 "How are pre-existing fuel users and coal permit holders handled?",
 ["Existing fuel users apply within one year of the fuel blending and composition standard being announced; coal permit holders may continue until expiry and apply to renew three to six months before",
  "Existing fuel users apply within three months of this regulation's promulgation; coal permit holders must surrender their permits and re-apply before continuing to use fuel",
  "Existing fuel users apply within three years of the fuel blending ratio and composition standard being announced; coal permit holders may continue indefinitely until equipment replacement",
  "Existing fuel users need only file for record without a permit; coal permit holders must convert to a fuel use permit within six months of promulgation"],
 "Article 62."),

(P,"第63條",1,"固污許可-施行日",
 "固定污染源設置操作及燃料使用許可證管理辦法之施行日期規定為何？",
 ["本辦法自發布日施行，並未另定施行日期",
  "本辦法自發布日起三個月後開始施行之",
  "本辦法自發布日起一年後開始施行之",
  "本辦法自一百零九年一月一日起施行之"],"a",
 "第63條：本辦法自發布日施行。本辦法最近一次修正日期為民國一百零八年九月二十六日。",
 "When does the stationary source permit regulation take effect?",
 ["It takes effect on the date of promulgation, with no separate effective date",
  "It takes effect three months after the date of promulgation is announced",
  "It takes effect one year after the date of promulgation is announced",
  "It takes effect on 1 January 2020 as separately specified in the text"],
 "Article 63."),
]
