# -*- coding: utf-8 -*-
# 第 10 批（E3）：事業廢棄物貯存清除處理方法及設施標準 第1條～第46條
S = "ENV-11"
Q = [

(S,"第1條",1,"事廢標準-授權依據",
 "本標準係依據廢棄物清理法之何條項規定訂定？",
 ["依廢棄物清理法第三十六條第二項規定訂定之","依廢棄物清理法第二十八條第二項規定訂定之","依廢棄物清理法第三十九條第四項規定訂定之","依廢棄物清理法第四十二條規定授權訂定之"],"a",
 "第1條：本標準依廢棄物清理法第36條第2項規定訂定之。廢棄物清理法第36條第1項規定事業廢棄物之貯存、清除或處理方法及設施應符合中央主管機關之規定，第2項授權訂定本標準。違反本標準有關貯存、清除或處理方法、設施之規定者，依廢棄物清理法第52條第7款處新臺幣六千元以上三百萬元以下罰鍰。",
 "Under which provision of the Waste Disposal Act is this Standard issued?",
 ["Article 36, paragraph 2 of the Waste Disposal Act","Article 28, paragraph 2 of the Waste Disposal Act","Article 39, paragraph 4 of the Waste Disposal Act","Article 42 of the Waste Disposal Act"],
 "Article 1, read with Article 36 of the Waste Disposal Act."),

(S,"第2條",2,"事廢標準-處理定義",
 "本標準所稱處理包括哪三種行為？其中中間處理之定義為何？",
 ["包括中間處理、最終處置及再利用；中間處理指在最終處置或再利用前以物理、化學、生物、熱處理或其他方法改變其特性或成分，達成分離、減積、去毒、固化或穩定之行為","包括貯存、清除及最終處置；中間處理指將事業廢棄物暫置於特定地點或容器內，待清除機構收運前所為之分類、包裝及標示之行為","包括收集、運輸及衛生掩埋；中間處理指將事業廢棄物運至掩埋場後進行之壓實、覆土及滲出水收集處理之全部作業行為","包括再使用、再生利用及能源回收；中間處理指將事業廢棄物送回原生產製程當作原料，或送至同一事業其他分廠使用之行為"],"a",
 "第2條第3款：處理指中間處理、最終處置及再利用三者。中間處理指事業廢棄物在最終處置或再利用前，以物理、化學、生物、熱處理或其他處理方法，改變其物理、化學、生物特性或成分，達成分離、減積、去毒、固化或穩定之行為。最終處置指衛生掩埋、封閉掩埋、安定掩埋或海洋棄置之行為。第1款貯存、第2款清除（收集、運輸）、第4款清理則分別定義。",
 "What three acts does treatment cover under this Standard, and what is intermediate treatment?",
 ["Intermediate treatment, final disposal and reuse; intermediate treatment alters physical, chemical or biological properties or composition before final disposal or reuse to separate, reduce, detoxify, solidify or stabilize","Storage, clearance and final disposal; intermediate treatment means placing waste at a set location or container and sorting, packing and labelling it before collection","Collection, transport and sanitary landfill; intermediate treatment means all compaction, soil covering and leachate collection work carried out after waste reaches the landfill","Reuse, recycling and energy recovery; intermediate treatment means returning waste to the original process as feedstock or sending it to another branch plant"],
 "Article 2, subparagraphs 1 to 4."),

(S,"第2條",3,"事廢標準-滅菌與效率",
 "本標準所稱滅菌法之指標微生物削減率至少須達多少？破壞去除效率（DRE）之定義為何？",
 ["削減率至少須達百分之九九．九九九；破壞去除效率指主要有害有機物質以熱處理法處理時，其處理前總重量減去煙道排氣所含總重量，除以處理前總重量之百分比","削減率至少須達百分之九九．九；破壞去除效率指煙道出口排氣中所含二氧化碳濃度與二氧化碳及一氧化碳濃度總和之百分比，並以連續監測方式量測","削減率至少須達百分之九九．九九；破壞去除效率指焚化後底渣與飛灰之重量總和，除以進料廢棄物總重量所得之百分比，並每半年檢驗一次","削減率至少須達百分之九五；破壞去除效率指經毒性特性溶出程序試驗後，溶出量低於有害事業廢棄物認定標準附表四所列標準之比率"],"a",
 "第2條第13款：滅菌法之指標微生物削減率至少須達百分之九九．九九九；採高溫高壓蒸氣滅菌者以嗜熱桿菌芽孢測試，採其他滅菌法者以枯草桿菌芽孢測試。第16款：破壞去除效率（DRE）指主要有害有機物質（POHCs）以熱處理法處理時，其處理前總重量減去煙道排氣所含總重量，除以處理前總重量之百分比。第17款燃燒效率（CE）則指煙道出口排氣中二氧化碳濃度與二氧化碳及一氧化碳濃度總和之百分比。",
 "What indicator microorganism reduction rate must sterilization achieve, and how is destruction removal efficiency defined?",
 ["At least 99.999 percent; destruction removal efficiency is the pre-treatment total weight of principal organic hazardous constituents minus the weight in flue gas, divided by the pre-treatment total weight","At least 99.9 percent; destruction removal efficiency is the percentage of carbon dioxide against the sum of carbon dioxide and carbon monoxide in the flue gas, measured continuously","At least 99.99 percent; destruction removal efficiency is the combined weight of bottom ash and fly ash divided by the total weight of waste fed, tested every six months","At least 95 percent; destruction removal efficiency is the share of leachate results falling below the criteria in Table 4 of the hazardous industrial waste criteria"],
 "Article 2, subparagraphs 13, 16 and 17."),

(S,"第3條",1,"事廢標準-應回收廢棄物",
 "事業產生或受託清除處理之廢棄物，屬廢棄物清理法第十八條第一項規定之應回收廢棄物者，應如何清除處理？",
 ["應依相關回收清除處理規定清除處理之","應一律依本標準之中間處理方法處理之","應逕送衛生掩埋場以最終處置方式處理","應報請中央主管機關個案核准後處理"],"a",
 "第3條：事業產生或受託清除處理之廢棄物屬本法第18條第1項規定之應回收廢棄物，應依相關回收清除處理規定清除處理之。廢棄物清理法第18條第1項規定應回收廢棄物之回收、貯存、清除、處理方法及設施標準由中央主管機關依其種類定之，故該類廢棄物優先適用各該回收清除處理規定，而非逕依本標準辦理。",
 "How must waste that qualifies as mandatory recycling waste under Article 18 of the Act be handled?",
 ["In accordance with the relevant recovery, clearance and treatment rules","Always by the intermediate treatment methods set out in this Standard","By sending it directly to a sanitary landfill for final disposal","Only after obtaining case-by-case approval from the central authority"],
 "Article 3, read with Article 18 of the Waste Disposal Act."),

(S,"第4條",1,"事廢標準-分類代碼",
 "中央主管機關得依何種依據公告事業廢棄物之分類代碼？",
 ["得依事業廢棄物主要成分特性或有害事業廢棄物之認定方式公告其分類代碼","得依事業之營業規模或資本額大小公告其應適用之廢棄物分類代碼","得依產生廢棄物之縣市轄區及行政區域劃分公告其分類代碼","得依清除處理機構之許可等級及自有設施數量公告其分類代碼"],"a",
 "第4條：中央主管機關得依事業廢棄物主要成分特性或有害事業廢棄物之認定方式，公告其分類代碼。第6條第1項第1款並要求一般事業廢棄物應依事業廢棄物主要成分特性分類貯存；第7條第1項第1款要求有害事業廢棄物應依有害事業廢棄物認定方式或危害特性分類貯存。",
 "On what basis may the central authority announce classification codes for industrial waste?",
 ["The main compositional properties of the waste or the way hazardous industrial waste is determined","The business scale or amount of capital of the enterprise generating the waste","The county or city jurisdiction and administrative district where the waste arises","The permit grade of the clearance institution and the number of facilities it owns"],
 "Article 4, read with Articles 6 and 7."),

(S,"第4條之1",1,"事廢標準-石綿瓦",
 "建築物拆除石綿瓦廢棄物之貯存清除處理，應依何種方式辦理？",
 ["應依本標準所附附件之管理方式辦理","應依一般事業廢棄物之貯存規定辦理","應依生物醫療廢棄物之清除規定辦理","應依中央目的事業主管機關公告辦理"],"a",
 "第4條之1：建築物拆除石綿瓦廢棄物之貯存清除處理，應依附件之管理方式辦理，該條並標有附表／附件。第20條第15款另就屬有害事業廢棄物之石綿及其製品，規定應經潤濕處理，再以厚度萬分之六十公分以上之塑膠袋雙層盛裝，開口綁緊後袋口反折再綑綁一次後置於堅固容器中，或採具防止飛散措施之固化法處理。",
 "How must asbestos sheet waste from building demolition be stored, cleared and treated?",
 ["In accordance with the management methods set out in the annex to this Standard","In accordance with the storage rules applicable to general industrial waste","In accordance with the clearance rules applicable to biomedical waste","In accordance with an announcement by the central industry authority"],
 "Article 4-1, read with Article 20, subparagraph 15."),

(S,"第5條",1,"事廢標準-分開貯存",
 "有害事業廢棄物與一般事業廢棄物之貯存，本標準定有何項基本要求？",
 ["有害事業廢棄物應與一般事業廢棄物分開貯存","二者得於同一容器內混合貯存但須標示清楚","二者應合併貯存以利統一清運及集中管理","二者得依事業自行訂定之作業程序彈性貯存"],"a",
 "第5條：有害事業廢棄物應與一般事業廢棄物分開貯存。第6條、第7條並分別就一般事業廢棄物及有害事業廢棄物之貯存方法定有規定；第14條規定不具相容性之事業廢棄物不得混合清除；第30條第3項規定不具相容性之事業廢棄物不得合併掩埋。",
 "What basic requirement applies to storing hazardous and general industrial waste?",
 ["Hazardous industrial waste must be stored separately from general industrial waste","The two may be mixed in one container provided it is clearly labelled","The two must be stored together to allow unified haulage and central management","The two may be stored flexibly under procedures the enterprise sets itself"],
 "Article 5, read with Articles 6, 7, 14 and 30."),

(S,"第6條",2,"事廢標準-一般貯存方法",
 "一般事業廢棄物之貯存方法應符合下列何項規定？",
 ["應依主要成分特性分類貯存；貯存地點容器設施應保持清潔完整，不得有飛揚逸散滲出污染地面或散發惡臭；貯存容器設施應與所存放廢棄物具相容性；應於明顯處以中文標示廢棄物名稱","應依產生日期先後順序貯存；貯存地點得露天堆置但應加蓋防塵網；貯存容器得與任何廢棄物混用而無須考量相容性；應於容器上標示事業統一編號及負責人姓名","應依委託處理機構別分類貯存；貯存地點應設置於廠區外圍空地；貯存容器應每三個月更換一次；應於明顯處以中英文對照標示處理機構名稱及聯絡電話","應依預定清運車次分批貯存；貯存地點應與辦公區保持五十公尺以上距離；貯存容器應採用金屬材質；應於貯存設施入口標示核准文號及使用期限"],"a",
 "第6條第1項列四款：依事業廢棄物主要成分特性分類貯存；貯存地點、容器、設施應保持清潔完整，不得有廢棄物飛揚、逸散、滲出、污染地面或散發惡臭情事；貯存容器、設施應與所存放之廢棄物具有相容性，不具相容性者應分別貯存；貯存地點、容器及設施應於明顯處以中文標示廢棄物名稱。第2項：中央主管機關得依事業別、特定種類及其數量特性，公告其包裝標示、貯存期限及申請延長貯存期限方式。",
 "Which requirements apply to storing general industrial waste?",
 ["Sort by main compositional properties; keep sites, containers and facilities clean and intact with no scattering, seepage, ground contamination or odour; ensure compatibility with the waste stored; label the waste name in Chinese in a conspicuous place","Sort by date generated; open-air stacking is allowed if covered with dust netting; containers may be shared with any waste regardless of compatibility; label the tax number and the responsible person's name","Sort by the treatment institution engaged; site the store on open land outside the plant; replace containers every three months; label the institution's name and phone number in Chinese and English","Sort by planned haulage trips; keep the site at least fifty metres from offices; use metal containers only; label the approval number and expiry date at the entrance"],
 "Article 6, paragraphs 1 and 2."),

(S,"第7條",3,"事廢標準-有害貯存期限",
 "有害事業廢棄物之貯存期限為何？須延長者應於何時、向何機關申請？延長次數及期間有何限制？",
 ["貯存以一年為限；須延長者應於期限屆滿二個月前向貯存設施所在地之地方主管機關申請延長，並以一次為限，且不得超過一年","貯存以六個月為限；須延長者應於期限屆滿一個月前向中央主管機關申請延長，並以二次為限，每次不得超過六個月","貯存以三年為限；須延長者應於期限屆滿三個月前向中央目的事業主管機關申請延長，並以三次為限，每次不得超過一年","貯存以九十日為限；須延長者應於期限屆滿十五日前向執行機關申請延長，並無次數限制，惟每次不得超過九十日"],"a",
 "第7條第2項：貯存以一年為限，其須延長者，應於期限屆滿二個月前向貯存設施所在地之地方主管機關申請延長，並以一次為限，且不得超過一年。第3項：因事業無法自行處理、國內無處理機構可供委託處理或其他特殊情形致無法於期限內處理者，得檢具貯存計畫書送中央目的事業主管機關初審同意後，轉中央主管機關複審同意，得延長其貯存期限。第4項：廢棄物於清除或輸出入過程有貯存行為者，不適用第2項及第3項規定。",
 "How long may hazardous industrial waste be stored, and how may that period be extended?",
 ["One year; extension must be sought two months before expiry from the local authority where the facility sits, once only and for no more than one year","Six months; extension must be sought one month before expiry from the central authority, twice at most and for no more than six months each time","Three years; extension must be sought three months before expiry from the central industry authority, three times at most and for one year each time","Ninety days; extension must be sought fifteen days before expiry from the executing agency, without limit on times but no more than ninety days each time"],
 "Article 7, paragraphs 2 to 4."),

(S,"第7條",2,"事廢標準-有害貯存方法",
 "有害事業廢棄物之貯存方法，除生物醫療廢棄物之廢尖銳器具及感染性廢棄物外，應符合何項規定？",
 ["應依認定方式或危害特性分類貯存；以固定包裝材料或容器密封盛裝置於貯存設施內，分類編號並標示事業名稱、貯存日期、數量、成分及區別特性之標誌；容器設施應與廢棄物具相容性","應依委託清除機構分類貯存；以透明塑膠袋盛裝置於露天堆置區，依序編號並標示廢棄物代碼及重量；容器設施得選用任何材質而無須考量相容性","應依預定處理方法分類貯存；以敞口容器盛裝置於一般倉庫內，標示產生日期及預定清運日期；容器設施應每月更換一次以維持外觀完整","應依產生製程別分類貯存；以原物料原包裝直接盛裝置於原料倉庫，標示製程代號及班別；容器設施由事業依內部規定自行選定即可"],"a",
 "第7條第1項列四款：應依有害事業廢棄物認定方式或危害特性分類貯存；應以固定包裝材料或容器密封盛裝，置於貯存設施內，分類編號，並標示產生廢棄物之事業名稱、貯存日期、數量、成分及區別有害事業廢棄物特性之標誌；貯存容器或設施應與有害事業廢棄物具有相容性，必要時應使用內襯材料或其他保護措施；貯存容器或包裝材料應保持良好情況，有嚴重生鏽、損壞或洩漏之虞應即更換。第9條並規定採自動辨識及資料擷取系統管制流向者得簡化標示內容。",
 "Which requirements apply to storing hazardous industrial waste other than sharps and infectious waste?",
 ["Sort by the determination method or hazard characteristic; seal in fixed packaging or containers inside the storage facility, number them and label the enterprise name, storage date, quantity, composition and hazard symbol; ensure container compatibility","Sort by the clearance operator engaged; use transparent plastic bags in an open-air stacking area, number them in sequence and label the waste code and weight; any container material may be used","Sort by the intended treatment method; use open containers in an ordinary warehouse labelled with the generation and planned haulage dates; replace containers monthly to keep them intact","Sort by the generating process; keep the material in its original packaging in the raw material warehouse labelled with process and shift codes; the enterprise picks containers under its own rules"],
 "Article 7, paragraph 1, with Article 9."),

(S,"第8條",3,"事廢標準-感染性貯存",
 "感染性廢棄物於廢棄物產出機構之貯存條件為何？以熱處理法及滅菌法處理者應分別以何種顏色容器盛裝？",
 ["於攝氏五度以上貯存以一日為限，五度以下至零度以上冷藏以七日為限，零度以下冷凍以三十日為限；熱處理法者以紅色塑膠袋或紅色可燃容器，滅菌法者以黃色塑膠袋或黃色容器","於攝氏五度以上貯存以三日為限，五度以下冷藏以十四日為限，零度以下冷凍以六十日為限；熱處理法者以黃色塑膠袋或黃色容器，滅菌法者以紅色塑膠袋或紅色容器","於攝氏十度以上貯存以二日為限，十度以下冷藏以十日為限，零度以下冷凍以九十日為限；熱處理法者以黑色塑膠袋或金屬容器，滅菌法者以藍色塑膠袋或藍色容器","於常溫貯存以七日為限，冷藏以三十日為限，冷凍以一百八十日為限；熱處理法者以綠色塑膠袋或綠色容器，滅菌法者以白色塑膠袋或白色容器"],"a",
 "第8條第1項第2款：感染性廢棄物應與其他廢棄物分類貯存；以熱處理法處理者應以防漏、不易破之紅色塑膠袋或紅色可燃容器密封盛裝，以滅菌法處理者應以防漏、不易破之黃色塑膠袋或黃色容器密封貯存。貯存條件依產出機構、清除機構、處理機構分別規定：產出機構於攝氏五度以上以一日為限、五度以下至零度以上冷藏七日為限、零度以下冷凍三十日為限。第1款廢尖銳器具應以不易穿透之堅固容器密封盛裝，貯存以一年為限。",
 "What storage limits apply to infectious waste at the generating institution, and what container colours apply?",
 ["Above 5°C one day, refrigerated between 0 and 5°C seven days, frozen below 0°C thirty days; red bags or red combustible containers for thermal treatment, yellow bags or containers for sterilization","Above 5°C three days, refrigerated fourteen days, frozen below 0°C sixty days; yellow bags or containers for thermal treatment, red bags or containers for sterilization","Above 10°C two days, refrigerated ten days, frozen below 0°C ninety days; black bags or metal containers for thermal treatment, blue bags or containers for sterilization","At room temperature seven days, refrigerated thirty days, frozen one hundred and eighty days; green containers for thermal treatment, white containers for sterilization"],
 "Article 8, paragraph 1, subparagraphs 1 and 2."),

(S,"第8條",2,"事廢標準-清除處理機構貯存",
 "感染性廢棄物於清除機構及處理機構之貯存條件分別為何？",
 ["清除機構不得貯存，但有特殊情形須轉運者經地方主管機關同意後得於攝氏五度以下冷藏或冷凍並以七日為限；處理機構不得於攝氏五度以上貯存，冷藏以七日為限，冷凍以三十日為限","清除機構得於攝氏五度以下貯存三十日；處理機構得於常溫貯存七日，冷藏三十日，冷凍九十日，並得視處理量彈性延長而無須報經主管機關同意","清除機構得比照產出機構於攝氏五度以上貯存一日；處理機構不得為任何貯存行為，須於收受當日完成處理，逾期即應退運回產出機構","清除機構及處理機構均不得為任何貯存行為；如有特殊情形須貯存者，應報請中央主管機關個案核准，並以三日為限且不得延長"],"a",
 "第8條第1項第2款第2目：清除機構不得貯存；但有特殊情形而須轉運者，經地方主管機關同意後，得於攝氏五度以下冷藏或冷凍，並以七日為限。第3目：處理機構不得於攝氏五度以上貯存；於攝氏五度以下至零度以上冷藏者以七日為限，零度以下冷凍者以三十日為限。第3項並規定貯存期限不含清運過程、裝卸貨及等待投料時間；第4項規定貯存期間產生惡臭時應立即清除。",
 "What storage conditions apply to infectious waste at clearance and treatment institutions?",
 ["Clearance institutions may not store it, but with local authority consent for transhipment may refrigerate or freeze below 5°C for up to seven days; treatment institutions may not store above 5°C, seven days refrigerated and thirty days frozen","Clearance institutions may store it below 5°C for thirty days; treatment institutions may store it seven days at room temperature, thirty days refrigerated and ninety days frozen, extendable at will","Clearance institutions may store it above 5°C for one day like generators; treatment institutions may not store it at all and must treat it the same day or return it","Neither clearance nor treatment institutions may store it at all; in special cases central approval is needed and storage is capped at three days without extension"],
 "Article 8, paragraph 1, subparagraph 2, items 2 and 3, with paragraphs 3 and 4."),

(S,"第9條",1,"事廢標準-簡化標示",
 "事業廢棄物採自動辨識及資料擷取系統之電子或光學標籤管制廢棄物流向者，得為何種處置？其作業方式由何機關定之？",
 ["得簡化第七條及第八條規定之標示內容；其簡化標示之項目、內容及作業方式由中央主管機關定之","得完全免除第七條及第八條規定之標示義務；其系統規格及作業方式由事業自行訂定並報備查","得延長第七條所定之貯存期限一倍；其簡化標示之項目及作業方式由地方主管機關逐案核定","得免除聯單填具及申報義務；其系統認證及作業方式由中央目的事業主管機關會商公會定之"],"a",
 "第9條第1項：事業廢棄物採自動辨識及資料擷取系統之電子或光學標籤管制廢棄物流向者，得簡化第7條及前條規定之標示內容。第2項：前項有關簡化標示之項目、內容及作業方式，由中央主管機關定之。第2條第15款並定義自動辨識及資料擷取系統（AIDC）指藉由不同輸入介面之讀取裝置自動辨識物件，並將擷取資料儲存至電腦系統，達到廢棄物識別之系統。",
 "What benefit applies where waste flows are tracked by an automatic identification and data capture system?",
 ["The labelling content required by Articles 7 and 8 may be simplified; the central authority prescribes the simplified items, content and procedures","The labelling duties under Articles 7 and 8 are waived entirely; the enterprise sets the system specification and procedures and files them","The storage period under Article 7 may be doubled; the local authority approves the simplified items and procedures case by case","Manifest and reporting duties are waived; the central industry authority sets certification and procedures with the trade association"],
 "Article 9, paragraphs 1 and 2, with Article 2, subparagraph 15."),

(S,"第10條",2,"事廢標準-一般貯存設施",
 "一般事業廢棄物之貯存設施，除經中央主管機關公告者外，應符合何項規定？",
 ["應有防止地面水、雨水及地下水流入、滲透之設備或措施；由貯存設施產生之廢液、廢氣、惡臭等應有收集或防止其污染地面水體、地下水體、空氣、土壤之設備或措施","應設置抗蝕不透水材料襯墊之專門貯存場所；應於明顯處設置白底紅字黑框之警告標示並配置警報設備、滅火照明設備及緊急沖淋安全設備","應設置地磅及遠端監控資訊設備並保存影像一年；應設置一定寬度之綠帶或植栽圍籬，並於出入口設置清洗設施及沈澱池","應具備抗壓及抗震設施並鋪設五公尺以上進場道路；應以單軸抗壓強度二百四十五公斤每平方公分以上之混凝土構築周圍及底部"],"a",
 "第10條第1項列二款：應有防止地面水、雨水及地下水流入、滲透之設備或措施；由貯存設施產生之廢液、廢氣、惡臭等，應有收集或防止其污染地面水體、地下水體、空氣、土壤之設備或措施。第2項：事業產生與各中央目的事業主管機關所公告之事業廢棄物再利用種類相同，且其再利用管理方式有特別規定者，依其管理方式之規定，不受第1項限制。第11條則就有害事業廢棄物之貯存設施定有更嚴格之七款規定。",
 "Which requirements apply to storage facilities for general industrial waste?",
 ["Equipment or measures preventing inflow or infiltration of surface water, rainwater and groundwater; equipment or measures collecting or preventing waste liquid, gas and odour from polluting water bodies, air and soil","A dedicated store lined with corrosion-resistant impermeable material; a white-ground red-lettered black-framed warning sign plus alarms, fire extinguishing, lighting and emergency shower equipment","A weighbridge and remote monitoring equipment with one year of footage; a green belt or planted screen, with washing facilities and a settling pond at the entrance","Pressure and earthquake resistant structures with an access road of five metres or more; walls and base built of concrete of at least 245 kg per square centimetre uniaxial strength"],
 "Article 10, paragraphs 1 and 2, contrasted with Article 11."),

(S,"第11條",3,"事廢標準-有害貯存設施",
 "有害事業廢棄物之貯存設施，除生物醫療廢棄物之廢尖銳器具及感染性廢棄物外，應符合何項規定？",
 ["應設專門貯存場所，地面堅固且四周採抗蝕及不透水材料襯墊或構築；應於明顯處設置白底、紅字、黑框之警告標示並有災害防止設備；設於地下之貯存容器應有液位檢查、防漏措施及偵漏系統","應設露天貯存區並以碎石級配鋪面；應於明顯處設置黃底、黑字之警告標示並備有急救藥品；設於地下之貯存容器應每五年開挖檢查一次並更換全部管線","應設於廠區最外緣並與圍牆保持十公尺距離；應於入口設置紅底、白字之警告標示並派專人二十四小時看守；設於地下之貯存容器應加裝定位追蹤裝置","應設於獨立建築物並取得使用執照；應於四周設置藍底、白字之警告標示並投保火災保險；設於地下之貯存容器應報請地方主管機關逐案核准設置"],"a",
 "第11條列七款：應設置專門貯存場所，其地面應堅固，四周採用抗蝕及不透水材料襯墊或構築；應有防止地面水、雨水及地下水流入、滲透之設備或措施；應有收集或防止廢液廢氣惡臭污染之設備或措施；應於明顯處設置白底、紅字、黑框之警告標示，並有災害防止設備；設於地下之貯存容器應有液位檢查、防漏措施及偵漏系統；應配置所須之警報設備、滅火、照明設備或緊急沖淋安全設備；屬易燃性、反應性及毒性化學物質廢棄物者應依危害特性配置監測設備。",
 "Which requirements apply to storage facilities for hazardous industrial waste other than sharps and infectious waste?",
 ["A dedicated store with a solid floor lined or built with corrosion-resistant impermeable material; a white-ground red-lettered black-framed warning sign with disaster prevention equipment; underground containers need level checks, leak prevention and leak detection","An open-air area paved with graded gravel; a yellow-ground black-lettered warning sign with first aid supplies; underground containers must be excavated for inspection every five years with all pipework replaced","Siting at the plant's outer edge ten metres from the wall; a red-ground white-lettered sign at the entrance with round-the-clock guards; underground containers need positioning trackers","Siting in a separate building with an occupancy permit; blue-ground white-lettered signs around it and fire insurance; underground containers need case-by-case local authority approval"],
 "Article 11, subparagraphs 1 to 7."),

(S,"第12條",2,"事廢標準-生物醫療貯存設施",
 "生物醫療廢棄物之貯存設施，除基因毒性廢棄物依第十一條規定外，應符合何項規定？",
 ["應於設施入口或設施外明顯處標示區別有害事業廢棄物特性之標誌並備有緊急應變設施，設施應堅固並與治療區、廚房及餐廳隔離；不同顏色容器須分開置放；應有良好之排水及沖洗設備","應於設施內部標示廢棄物成分及重量並備有滅火器材，設施得設於治療區內以便就近投入；不同顏色容器得合併置放；應有恆溫恆濕之空調設備並每日消毒","應於設施外圍設置圍牆及綠帶並備有地磅設備，設施應與廠區主要道路相鄰以利清運；不同顏色容器應依序疊放；應有廢氣收集及滲出水處理設備","應於設施門口張貼負責人聯絡方式並備有防護衣具，設施應設於地下室以避免異味逸散；不同顏色容器應集中壓縮；應有污水處理專責人員駐守"],"a",
 "第12條列七款：應於設施入口或設施外明顯處標示區別有害事業廢棄物特性之標誌，並備有緊急應變設施或措施，其設施應堅固，並與治療區、廚房及餐廳隔離（但診所得於治療區設密封貯存設施）；貯存事業廢棄物之不同顏色容器須分開置放；應有良好之排水及沖洗設備；具防止人員或動物擅自闖入之安全設備或措施；具防止蚊蠅或其他病媒孳生之設備或措施；應有防止地面水、雨水及地下水流入滲透之設備；應有收集或防止廢液廢氣惡臭污染之設備。",
 "Which requirements apply to biomedical waste storage facilities other than genotoxic waste?",
 ["A hazard symbol at or outside the entrance with emergency response measures, a solid structure isolated from treatment areas, kitchens and dining rooms; different coloured containers kept apart; good drainage and washing equipment","Labels inside showing composition and weight with fire extinguishers, siting inside the treatment area for convenience; different coloured containers kept together; constant temperature air conditioning disinfected daily","A perimeter wall and green belt with a weighbridge, siting beside the main plant road for haulage; different coloured containers stacked in sequence; waste gas collection and leachate treatment","The manager's contact details at the door with protective clothing, siting in a basement to contain odour; different coloured containers compacted together; a resident wastewater treatment officer"],
 "Article 12, subparagraphs 1 to 7."),

(S,"第13條",2,"事廢標準-清除防污與污泥",
 "清除事業廢棄物之運送工具於清除過程應防止何種情事？污泥於清除前應如何處理？",
 ["應防止事業廢棄物飛散、濺落、溢漏、惡臭擴散、爆炸等污染環境或危害人體健康之情事；污泥應先脫水或乾燥至含水率百分之八十五以下，未達者應以槽車運載","應防止車輛超載、超速及違規停車等交通違規情事；污泥應先脫水或乾燥至含水率百分之五十以下，未達者應加入固化劑後始得運載","應防止駕駛人疲勞駕駛及未依規定路線行駛之情事；污泥應先經滅菌處理並檢測合格，含水率未達百分之九十者應改以密閉貨櫃運載","應防止清運時間逾越夜間管制時段之情事；污泥應先添加消毒藥劑並靜置二十四小時，含水率超過百分之七十者應分批運載"],"a",
 "第13條第1項：清除事業廢棄物之車輛、船舶或其他運送工具於清除過程中，應防止事業廢棄物飛散、濺落、溢漏、惡臭擴散、爆炸等污染環境或危害人體健康之情事發生。第2項：污泥於清除前，應先脫水或乾燥至含水率百分之八十五以下；未進行脫水或乾燥至含水率百分之八十五以下者，應以槽車運載。第14條並規定不具相容性之事業廢棄物不得混合清除。",
 "What must be prevented during waste haulage, and how must sludge be handled before clearance?",
 ["Scattering, spillage, overflow, odour spread, explosion and similar pollution or health hazards; sludge must be dewatered or dried to 85 percent moisture or less, otherwise hauled by tanker","Overloading, speeding and illegal parking traffic violations; sludge must be dewatered or dried to 50 percent moisture or less, otherwise mixed with solidifying agent first","Driver fatigue and departure from the prescribed route; sludge must be sterilized and pass testing, and hauled in sealed containers if under 90 percent moisture","Haulage during restricted night-time hours; sludge must be dosed with disinfectant and left to stand a day, and hauled in batches above 70 percent moisture"],
 "Article 13, paragraphs 1 and 2, with Article 14."),

(S,"第14條",1,"事廢標準-混合清除",
 "不具相容性之事業廢棄物於清除時，本標準定有何項禁止規定？",
 ["不具相容性之事業廢棄物不得混合清除","不具相容性之事業廢棄物得混合清除但應分艙","不具相容性之事業廢棄物應併同清除以節省運能","不具相容性之事業廢棄物混合清除須報備查即可"],"a",
 "第14條：不具相容性之事業廢棄物不得混合清除。第2條第5款定義相容性指事業廢棄物與容器、材料接觸，或二種以上事業廢棄物混合，不發生產生熱、產生激烈反應火災或爆炸、產生可燃性流體或有害流體、造成容器材料劣化致降低污染防治效果等效應者。第30條第3項並規定不具相容性之事業廢棄物不得合併掩埋。",
 "What prohibition applies to incompatible industrial wastes during clearance?",
 ["Incompatible industrial wastes may not be cleared together in a mixed load","Incompatible industrial wastes may be cleared together in separate compartments","Incompatible industrial wastes should be cleared together to save haulage capacity","Incompatible industrial wastes may be mixed for clearance if merely filed for record"],
 "Article 14, read with Articles 2 and 30."),

(S,"第15條",2,"事廢標準-清除紀錄",
 "事業自行或委託清除其產生之事業廢棄物至該機構以外者，應記錄哪些事項？資料應保留多久？",
 ["應記錄清除廢棄物之日期、種類、數量、車輛車號、清除機構、清除人、處理機構及保留處置證明；資料應保留三年以供查核","應記錄清除廢棄物之日期、重量、委託金額、契約編號及付款方式並保留發票；資料應保留一年以供查核","應記錄清除廢棄物之成分、含水率、檢測結果、採樣人員及檢測機構名稱；資料應保留五年以供查核","應記錄清除廢棄物之產生製程、班別、操作人員、機台編號及原料來源；資料應保留十年以供查核"],"a",
 "第15條第1項：事業自行或委託清除其產生之事業廢棄物至該機構以外，應記錄清除廢棄物之日期、種類、數量、車輛車號、清除機構、清除人、處理機構及保留所清除事業廢棄物之處置證明。第2項：前項資料應保留三年，以供查核。廢棄物清理法第37條第1項並就有害事業廢棄物貯存清除處理之操作及檢測，規定應作成紀錄妥善保存三年以上。",
 "What must be recorded when waste is cleared off site, and how long must records be kept?",
 ["The date, type, quantity, vehicle plate number, clearance institution, clearance personnel and treatment institution, plus the disposal certificate; kept three years for inspection","The date, weight, contract amount, contract number and payment method, plus the invoices; kept one year for inspection","The composition, moisture content, test results, sampler and testing laboratory name; kept five years for inspection","The generating process, shift, operator, machine number and raw material source; kept ten years for inspection"],
 "Article 15, paragraphs 1 and 2."),

(S,"第16條",2,"事廢標準-有害清除車輛",
 "清除有害事業廢棄物之車輛應符合何項規定？運輸途中發生洩漏時應如何處置？",
 ["應標示機構名稱、電話號碼及區別有害事業廢棄物特性之標誌，並隨車攜帶緊急應變方法說明書及緊急應變處理器材；洩漏時清除人應立即採取緊急應變措施並通知相關主管機關","應標示車輛核准文號、載重噸數及駕駛人姓名，並隨車攜帶行車紀錄器及滅火器；洩漏時清除人應先自行清理完畢後再於七日內報請主管機關備查","應標示產生事業名稱、處理機構地址及環保標章，並隨車攜帶處理契約書及保險單；洩漏時清除人應立即返回產生事業並由該事業負全部責任","應標示清運路線、預定到場時間及聯單編號，並隨車攜帶採樣器材及檢測儀器；洩漏時清除人應於現場採樣後續行運送至處理機構"],"a",
 "第16條第1項列二款：應標示機構名稱、電話號碼及區別有害事業廢棄物特性之標誌；隨車攜帶對有害事業廢棄物之緊急應變方法說明書及緊急應變處理器材。第2項：清除有害事業廢棄物於運輸途中有任何洩漏情形發生時，清除人應立即採取緊急應變措施並通知相關主管機關，產生有害事業廢棄物之事業與清除機構應負一切清理善後責任。",
 "What must vehicles hauling hazardous industrial waste display and carry, and what happens on a spill?",
 ["The institution name, phone number and hazard symbol, plus on-board emergency response instructions and response equipment; on a spill the hauler must take emergency measures at once and notify the authorities","The vehicle approval number, load tonnage and driver's name, plus a driving recorder and extinguisher; on a spill the hauler cleans up first and files with the authority within seven days","The generator's name, treatment institution address and eco label, plus the treatment contract and insurance policy; on a spill the hauler returns to the generator, which bears all liability","The haulage route, expected arrival time and manifest number, plus sampling and testing equipment; on a spill the hauler samples on site and continues to the treatment institution"],
 "Article 16, paragraphs 1 and 2."),

(S,"第17條",3,"事廢標準-遞送聯單",
 "事業委託清除有害事業廢棄物至該機構以外之貯存或處理場所時，應填具何種聯單？紙本聯單第一聯之處理方式為何？",
 ["須填具一式六聯之紙本遞送聯單或以網路傳輸方式填具電子聯單；紙本聯單經清除機構簽收後，第一聯由事業於七日內送產生廢棄物所在地之主管機關以供查核","須填具一式四聯之紙本遞送聯單或以傳真方式送交主管機關；紙本聯單經清除機構簽收後，第一聯由清除機構於三日內送處理機構所在地主管機關存查","須填具一式八聯之紙本遞送聯單並同時報請中央主管機關核准；紙本聯單經處理機構簽收後，第一聯由處理機構於十五日內送中央主管機關備查","須填具一式二聯之紙本遞送聯單並由雙方各執一聯存查；紙本聯單經事業簽章後，第一聯由事業自行保存三年而無須送交任何主管機關"],"a",
 "第17條第1項：須填具一式六聯之遞送聯單（紙本聯單）或以網路傳輸方式填具電子化遞送聯單（電子聯單）；但屬依本法第31條第1項公告應以網路傳輸方式申報者不在此限。第2項：紙本聯單經清除機構簽收後，第一聯由事業於七日內送產生廢棄物所在地之主管機關以供查核，第六聯由事業存查，第二聯至第五聯由清除機構於二日內送交處理機構簽收，清除機構保存第五聯；處理機構應於處理後七日內將第三聯送回事業，第四聯送事業所在地主管機關，並自行保存第二聯。",
 "What manifest must be completed when hazardous waste goes off site, and how is copy one handled?",
 ["A six-copy paper manifest or an electronic manifest filed online; after the hauler signs, the enterprise sends copy one to the authority where the waste arose within seven days for inspection","A four-copy paper manifest or a faxed submission to the authority; after the hauler signs, the hauler sends copy one to the authority where the treatment site sits within three days","An eight-copy paper manifest with prior central authority approval; after the treatment institution signs, it files copy one with the central authority within fifteen days","A two-copy paper manifest with one copy each; after the enterprise signs, it keeps copy one for three years and sends it to no authority at all"],
 "Article 17, paragraphs 1 and 2."),

(S,"第17條",3,"事廢標準-聯單追蹤",
 "有害事業廢棄物送達處理機構所載不符時應如何處理？事業應於清運後幾日內主動追蹤？聯單應保存多久？",
 ["處理機構應立即檢視成分特性數量與聯單契約書是否符合，不符者應於翌日起二日內請清除機構或事業補正並向當地主管機關報備；事業應於清運後三十五日內主動追蹤；聯單應保存三年","處理機構應於收受後七日內檢視並比對，不符者應於十五日內請事業補正並報中央主管機關核定；事業應於清運後九十日內主動追蹤；聯單應保存一年","處理機構應於處理完成後檢視並作成紀錄，不符者應於三十日內自行更正並副知目的事業主管機關；事業應於清運後六十日內主動追蹤；聯單應保存五年","處理機構應於每季結束前彙整檢視全部聯單，不符者應於次季報請地方主管機關備查；事業應於清運後十五日內主動追蹤；聯單應保存十年"],"a",
 "第17條第5項：有害事業廢棄物送達處理機構時，處理機構應立即檢視成分、特性、數量與紙本聯單或電子聯單及契約書是否符合，若所載不符者，應於翌日起二日內請清除機構或事業補正，並向當地主管機關報備。第6項：事業於有害事業廢棄物清運後三十五日內，應主動追蹤委託清除、處理之情形；有未清除處理完畢之情形者，應向當地主管機關報備。第8項：紙本聯單或電子聯單應保存三年以供查核。第9項：遞送或申報日期適逢假日時得順延至次一工作日。",
 "How are manifest discrepancies handled, within how many days must the enterprise follow up, and how long are manifests kept?",
 ["The treatment institution checks composition, properties and quantity against the manifest and contract at once and, if they differ, asks for correction within two days from the next day and reports to the local authority; the enterprise follows up within thirty-five days; manifests are kept three years","The institution checks within seven days of receipt and asks for correction within fifteen days with central approval; the enterprise follows up within ninety days; manifests are kept one year","The institution checks after treatment and records it, correcting discrepancies itself within thirty days and copying the industry authority; the enterprise follows up within sixty days; manifests are kept five years","The institution reviews all manifests before each quarter ends and files discrepancies locally the next quarter; the enterprise follows up within fifteen days; manifests are kept ten years"],
 "Article 17, paragraphs 5, 6, 8 and 9."),

(S,"第18條",2,"事廢標準-感染性清除",
 "生物醫療廢棄物之廢尖銳器具及感染性廢棄物之清除方法，除應符合第十三條至第十六條外，尚應符合何項規定？",
 ["以不同顏色容器貯存之廢棄物不得混合清除；於運輸過程不可壓縮及任意開啟；運輸途中應備有冷藏措施並維持正常運轉；裝卸過程若無工作人員在場應保持車輛倉門關閉並上鎖","以不同顏色容器貯存之廢棄物得混合清除以節省車次；於運輸過程得視情形壓縮減積；運輸途中無須冷藏但應加蓋帆布；裝卸過程應由駕駛人全程在場監看並簽名確認","以不同顏色容器貯存之廢棄物應先行拆封分類；於運輸過程應每二小時開啟通風一次；運輸途中應備有加熱滅菌設備；裝卸過程應開啟倉門以利檢視內容物","以不同顏色容器貯存之廢棄物應統一改裝為紅色容器；於運輸過程應保持常溫；運輸途中應由主管機關派員押運；裝卸過程應全程錄影並保存影像三年"],"a",
 "第18條列四款：以不同顏色容器貯存之廢棄物不得混合清除；於運輸過程不可壓縮及任意開啟；運輸途中應備有冷藏措施並維持正常運轉（但離島地區因交通不便者，經廢棄物產生事業所在地之地方主管機關同意後，得於部分運輸路程中不須備有冷藏措施）；於裝卸過程若無工作人員在場，應保持清除車輛倉門關閉並上鎖。第8條第1項第2款並就熱處理法及滅菌法分別規定紅色及黃色容器。",
 "Besides Articles 13 to 16, which rules apply to clearing sharps and infectious waste?",
 ["Waste in different coloured containers may not be cleared in one mixed load; it may not be compacted or opened at will in transit; refrigeration must be fitted and kept running; cargo doors stay closed and locked when no staff are present","Waste in different coloured containers may be mixed to save trips; it may be compacted to reduce volume; no refrigeration is needed if a tarpaulin is used; the driver must watch and sign for all loading","Waste in different coloured containers must be unpacked and re-sorted; the load must be opened for ventilation every two hours; heat sterilizing equipment must be carried; doors stay open for inspection during loading","Waste in different coloured containers must all be repacked into red containers; it travels at room temperature; an official must escort the load; all loading must be filmed and kept three years"],
 "Article 18, subparagraphs 1 to 4, with Article 8."),

(S,"第19條",2,"事廢標準-一般中間處理",
 "下列一般事業廢棄物除再利用或中央主管機關另有規定外應先經中間處理，其處理方法為何？",
 ["可燃性之一般事業廢棄物以熱處理法處理；人體或動物使用之廢藥品以熱處理法處理；製造二氯乙烯或氯乙烯單體之廢水處理污泥以熱處理法處理","可燃性之一般事業廢棄物以固化法處理；人體或動物使用之廢藥品以衛生掩埋法處理；製造二氯乙烯或氯乙烯單體之廢水處理污泥以安定掩埋法處理","可燃性之一般事業廢棄物以物理處理法處理；人體或動物使用之廢藥品以滅菌法處理；製造二氯乙烯或氯乙烯單體之廢水處理污泥以中和法處理","可燃性之一般事業廢棄物以穩定法處理；人體或動物使用之廢藥品以氧化分解法處理；製造二氯乙烯或氯乙烯單體之廢水處理污泥以萃取法處理"],"a",
 "第19條列五款：可燃性之一般事業廢棄物以熱處理法處理；廢變壓器其變壓器油含多氯聯苯重量含量在百萬分之二以上未達百萬分之五十者，應先固液分離，金屬殼體以回收或物理處理法處理、變壓器油或液體以熱處理法處理、其他非金屬固體不可燃物以衛生掩埋法最終處置而可燃物以熱處理法處理；人體或動物使用之廢藥品以熱處理法處理；製造二氯乙烯或氯乙烯單體之廢水處理污泥以熱處理法處理；其他經中央主管機關公告之處理方法。",
 "Which intermediate treatment methods apply to these general industrial wastes?",
 ["Combustible general industrial waste by thermal treatment; waste pharmaceuticals for human or animal use by thermal treatment; wastewater treatment sludge from dichloroethylene or vinyl chloride monomer manufacture by thermal treatment","Combustible general industrial waste by solidification; waste pharmaceuticals by sanitary landfill; wastewater treatment sludge from such manufacture by stable landfill","Combustible general industrial waste by physical treatment; waste pharmaceuticals by sterilization; wastewater treatment sludge from such manufacture by neutralization","Combustible general industrial waste by stabilization; waste pharmaceuticals by oxidative decomposition; wastewater treatment sludge from such manufacture by extraction"],
 "Article 19, subparagraphs 1 to 5."),

(S,"第20條",3,"事廢標準-含汞處理",
 "含汞及其化合物之有害事業廢棄物，其中間處理方法及殘渣溶出標準為何？",
 ["乾基每公斤濃度達二百六十毫克以上者應回收元素汞，其殘渣毒性特性溶出程序試驗結果汞溶出量應低於○‧二毫克／公升；低於二百六十毫克以其他方式中間處理者，殘渣溶出結果應低於○‧○二五毫克／公升","乾基每公斤濃度達一百毫克以上者應回收元素汞，其殘渣毒性特性溶出程序試驗結果汞溶出量應低於○‧五毫克／公升；低於一百毫克者，殘渣溶出結果應低於○‧一毫克／公升","乾基每公斤濃度達五百毫克以上者應以固化法處理，其殘渣毒性特性溶出程序試驗結果汞溶出量應低於一‧○毫克／公升；低於五百毫克者，殘渣溶出結果應低於○‧五毫克／公升","乾基每公斤濃度達五十毫克以上者應以熱處理法處理，其殘渣毒性特性溶出程序試驗結果汞溶出量應低於○‧○五毫克／公升；低於五十毫克者，殘渣溶出結果應低於○‧○一毫克／公升"],"a",
 "第20條第8款：含汞及其化合物者，乾基每公斤濃度達二百六十毫克以上者，應回收元素汞，其殘渣之毒性特性溶出程序試驗結果汞溶出量應低於○‧二毫克／公升；乾基每公斤濃度低於二百六十毫克，以其他方式中間處理者，其殘渣之毒性特性溶出程序試驗結果應低於○‧○二五毫克／公升。第41條第2項並規定採固化法穩定法處理者應採封閉掩埋或衛生掩埋，採衛生掩埋者應符合有害事業廢棄物認定標準附表四之溶出標準並獨立分區掩埋管理。",
 "What treatment and leachate limits apply to mercury-bearing hazardous industrial waste?",
 ["At 260 mg/kg dry basis or above, elemental mercury must be recovered and residue leachate must be below 0.2 mg/L; below 260 mg/kg treated otherwise, residue leachate must be below 0.025 mg/L","At 100 mg/kg dry basis or above, elemental mercury must be recovered and residue leachate must be below 0.5 mg/L; below 100 mg/kg, residue leachate must be below 0.1 mg/L","At 500 mg/kg dry basis or above, solidification must be used and residue leachate must be below 1.0 mg/L; below 500 mg/kg, residue leachate must be below 0.5 mg/L","At 50 mg/kg dry basis or above, thermal treatment must be used and residue leachate must be below 0.05 mg/L; below 50 mg/kg, residue leachate must be below 0.01 mg/L"],
 "Article 20, subparagraph 8, with Article 41."),

(S,"第20條",3,"事廢標準-有害處理方法",
 "下列有害事業廢棄物之中間處理方法，何者符合本標準規定？",
 ["含氰化物以氧化分解法或熱處理法處理；廢溶劑以萃取法、蒸餾法或熱處理法處理；廢酸或廢鹼以蒸發法、蒸餾法、薄膜分離法或中和法處理；戴奧辛廢棄物以熱處理法處理","含氰化物以中和法或固化法處理；廢溶劑以滅菌法或掩埋法處理；廢酸或廢鹼以焚化法或熔融法處理；戴奧辛廢棄物以安定掩埋法或穩定法處理","含氰化物以物理處理法或洗淨法處理；廢溶劑以固化法或穩定法處理；廢酸或廢鹼以氧化分解法或熱解法處理；戴奧辛廢棄物以化學處理法或電解法處理","含氰化物以蒸餾法或萃取法處理；廢溶劑以中和法或電解法處理；廢酸或廢鹼以熱處理法或熔煉法處理；戴奧辛廢棄物以固化法或衛生掩埋法處理"],"a",
 "第20條列十六款有害事業廢棄物之中間處理方法，包括第1款含氰化物以氧化分解法或熱處理法處理；第3款廢溶劑以萃取法、蒸餾法或熱處理法處理；第7款廢酸或廢鹼以蒸發法、蒸餾法、薄膜分離法或中和法處理；第11款戴奧辛廢棄物以熱處理法處理。第9款含有毒重金屬廢棄物以固化法、穩定法、電解法、薄膜分離法、蒸發法、熔融法、化學處理法或熔煉法處理，其可燃分或揮發性固體重量百分比達百分之三十以上者得採熱處理法。",
 "Which intermediate treatment methods comply with this Standard?",
 ["Cyanide-bearing waste by oxidative decomposition or thermal treatment; waste solvents by extraction, distillation or thermal treatment; waste acid or alkali by evaporation, distillation, membrane separation or neutralization; dioxin waste by thermal treatment","Cyanide-bearing waste by neutralization or solidification; waste solvents by sterilization or landfill; waste acid or alkali by incineration or melting; dioxin waste by stable landfill or stabilization","Cyanide-bearing waste by physical treatment or washing; waste solvents by solidification or stabilization; waste acid or alkali by oxidative decomposition or pyrolysis; dioxin waste by chemical treatment or electrolysis","Cyanide-bearing waste by distillation or extraction; waste solvents by neutralization or electrolysis; waste acid or alkali by thermal treatment or smelting; dioxin waste by solidification or sanitary landfill"],
 "Article 20, subparagraphs 1, 3, 7, 9 and 11."),

(S,"第21條",2,"事廢標準-生物醫療處理",
 "生物醫療廢棄物之中間處理方法，除中央主管機關另有規定外，其規定為何？",
 ["基因毒性廢棄物以熱處理法或化學處理法處理；廢尖銳器具以熱處理法處理或滅菌後粉碎處理；感染性廢棄物以熱處理法處理，但部分類別得經滅菌後破壞原型處理","基因毒性廢棄物以滅菌法或固化法處理；廢尖銳器具以衛生掩埋法處理或壓縮後掩埋；感染性廢棄物以安定掩埋法處理，但部分類別得經消毒後直接掩埋","基因毒性廢棄物以物理處理法或洗淨處理法處理；廢尖銳器具以化學處理法處理或溶解後排放；感染性廢棄物以穩定法處理，但部分類別得經冷凍後破碎處理","基因毒性廢棄物以中和法或萃取法處理；廢尖銳器具以熔融法處理或研磨後回收；感染性廢棄物以氧化分解法處理，但部分類別得經高壓後壓縮處理"],"a",
 "第21條第1項列三款：基因毒性廢棄物以熱處理法或化學處理法處理；廢尖銳器具以熱處理法處理或滅菌後粉碎處理；感染性廢棄物以熱處理法處理，但廢棄之微生物培養物、菌株及相關生物製品、手術或驗屍廢棄物、實驗室廢棄物、透析廢棄物、受血液及體液污染廢棄物，得經滅菌後破壞原型處理；未破壞原形者應於包裝容器明顯處標示產出事業名稱、滅菌方式、滅菌操作人員或事業名稱、滅菌日期及滅菌效能測試結果。第2項：滅菌法之處理標準、操作規定及滅菌效能測試之標準程序依中央主管機關之規定辦理。",
 "What intermediate treatment applies to biomedical waste unless the central authority provides otherwise?",
 ["Genotoxic waste by thermal or chemical treatment; sharps by thermal treatment or sterilization then crushing; infectious waste by thermal treatment, though some categories may be sterilized and deformed","Genotoxic waste by sterilization or solidification; sharps by sanitary landfill or compaction then landfill; infectious waste by stable landfill, though some categories may be disinfected and landfilled","Genotoxic waste by physical or washing treatment; sharps by chemical treatment or dissolution and discharge; infectious waste by stabilization, though some categories may be frozen and crushed","Genotoxic waste by neutralization or extraction; sharps by melting or grinding then recovery; infectious waste by oxidative decomposition, though some categories may be pressurized and compacted"],
 "Article 21, paragraphs 1 and 2."),

(S,"第22條",3,"事廢標準-試運轉",
 "有害事業廢棄物採熱處理法者，其試運轉之程序及期限限制為何？",
 ["應提出試運轉計畫報請直轄市或縣（市）主管機關核可後依計畫進行，測試前一個月應先通知主管機關並於其監督下測試；試運轉期間以三個月為限，必要時得申請延長，展延期限不得超過三個月","應提出試運轉計畫報請中央主管機關核可後依計畫進行，測試前三個月應先通知主管機關並自行辦理測試；試運轉期間以六個月為限，必要時得申請延長，展延期限不得超過六個月","應提出試運轉計畫報請中央目的事業主管機關備查後即得進行，測試前七日通知主管機關並得自行委託檢測；試運轉期間以一年為限，必要時得申請延長二次","應提出試運轉計畫報請執行機關同意後依計畫進行，測試前十五日公告周知並邀請民眾參與；試運轉期間以九十日為限，屆期不得申請任何延長"],"a",
 "第22條第1項：有害事業廢棄物採熱處理法者，應提出試運轉計畫，報請直轄市或縣（市）主管機關核可後，依試運轉計畫進行試運轉；試運轉測試前一個月應先通知直轄市、縣（市）主管機關，並於其監督下依計畫進行測試；測試所須之檢測應自行委託經中央主管機關認可之檢驗測定機構或經核准之學術、顧問機構進行；測試完成後應檢具試運轉報告經核准後始得處理。第2項：試運轉期間以三個月為限，必要時得申請延長，展延期限不得超過三個月。第3項：屬共同清除處理機構者由中央目的事業主管機關受理核可。",
 "What procedure and time limits apply to trial runs for thermal treatment of hazardous waste?",
 ["A trial run plan must be approved by the municipal or county authority and followed; the authority must be notified one month before testing and supervises it; the trial run lasts at most three months, extendable once by no more than three months","A trial run plan must be approved by the central authority and followed; the authority must be notified three months before testing, which the operator runs itself; the trial run lasts at most six months, extendable by six months","A trial run plan need only be filed with the central industry authority; the authority is notified seven days before testing, which may be self-commissioned; the trial run lasts at most one year, extendable twice","A trial run plan must be agreed by the executing agency and followed; a public notice fifteen days before testing invites public participation; the trial run lasts at most ninety days with no extension"],
 "Article 22, paragraphs 1 to 3."),

(S,"第23條",2,"事廢標準-中間處理設施",
 "事業廢棄物之中間處理設施，除中央主管機關另有規定外，應符合何項規定？",
 ["應有堅固之基礎結構；設施與廢棄物接觸之表面採抗蝕及不透水材料構築；設施周圍應有防止地面水、雨水及地下水流入滲透之設施；應具防止廢棄物飛散流出惡臭擴散之措施；應有污染防制設備及防蝕措施","應有雙層不透水材質構築之防溢堤；設施表面採耐高溫陶瓷材料構築；設施周圍應設置寬度五公尺以上之緩衝綠帶；應具備連續自動監測及即時傳輸設備；應有備援發電機及消防栓","應取得建築物使用執照及工廠登記證；設施應設於都市計畫工業區內；設施周圍應設置圍牆及地磅設施；應具備遠端監控攝影並保存影像一年；應有專責人員全日駐廠","應通過環境影響評估審查並取得操作許可證；設施應與住宅區保持一公里距離；設施周圍應設置監測井三口以上；應具備廢氣連續監測系統；應有緊急應變小組編組"],"a",
 "第23條列五款：應有堅固之基礎結構；設施與廢棄物接觸之表面，採抗蝕及不透水材料構築；設施周圍應有防止地面水、雨水及地下水流入、滲透之設施或措施；應具有防止廢棄物飛散、流出、惡臭擴散及影響四周環境品質之必要措施；應有污染防制設備及防蝕措施。第24條並就有害事業廢棄物之焚化處理設施定有更嚴格之要求；第28條規定固化及穩定化處理設施除依第23條外並應具有將廢棄物及固化劑或化學劑混合均勻之設備。",
 "Which requirements apply to intermediate treatment facilities for industrial waste?",
 ["A solid foundation structure; surfaces contacting waste built of corrosion-resistant impermeable material; measures preventing inflow or infiltration of surface water, rainwater and groundwater; measures preventing scattering, outflow and odour spread; pollution control equipment and corrosion protection","A double-layer impermeable containment dyke; surfaces built of high temperature ceramic material; a buffer green belt at least five metres wide; continuous automatic monitoring with real-time transmission; a backup generator and fire hydrants","A building occupancy permit and factory registration; siting inside an urban plan industrial zone; a perimeter wall and weighbridge; remote monitoring cameras with one year of footage; dedicated personnel on site all day","A passed environmental impact assessment and operating permit; siting one kilometre from residential zones; at least three monitoring wells around it; a continuous waste gas monitoring system; an emergency response team"],
 "Article 23, subparagraphs 1 to 5, with Articles 24 and 28."),

(S,"第24條",3,"事廢標準-焚化設施",
 "有害事業廢棄物之焚化處理設施，其燃燒室出口中心溫度、燃燒氣體滯留時間及焚化感染性廢棄物之燃燒效率規定為何？",
 ["燃燒室出口中心溫度應保持攝氏一千度以上；燃燒氣體滯留時間，廢尖銳器具及感染性廢棄物在一秒以上，其他有害事業廢棄物在二秒以上；焚化感染性廢棄物者燃燒效率達百分之九十九‧九以上","燃燒室出口中心溫度應保持攝氏八百度以上；燃燒氣體滯留時間，廢尖銳器具及感染性廢棄物在二秒以上，其他有害事業廢棄物在四秒以上；焚化感染性廢棄物者燃燒效率達百分之九十九以上","燃燒室出口中心溫度應保持攝氏一千二百度以上；燃燒氣體滯留時間，廢尖銳器具及感染性廢棄物在三秒以上，其他有害事業廢棄物在五秒以上；焚化感染性廢棄物者燃燒效率達百分之九十五以上","燃燒室出口中心溫度應保持攝氏六百度以上；燃燒氣體滯留時間，廢尖銳器具及感染性廢棄物在半秒以上，其他有害事業廢棄物在一秒以上；焚化感染性廢棄物者燃燒效率達百分之九十以上"],"a",
 "第24條第1項列五款：燃燒室出口中心溫度應保持攝氏一千度以上，燃燒氣體滯留時間生物醫療廢棄物之廢尖銳器具及感染性廢棄物在一秒以上、其他有害事業廢棄物在二秒以上；焚化感染性廢棄物者燃燒效率達百分之九十九‧九以上；除焚化感染性廢棄物外，其他有害事業廢棄物之有機氯化物破壞去除效率達百分之九十九‧九九以上，多氯聯苯及戴奧辛有害事業廢棄物破壞去除效率達百分之九十九‧九九九以上，其他毒性化學物質達百分之九十九‧九以上；應具自動監測、燃燒條件自動監測及控制、燃燒室出口中心溫度連續記錄及緊急應變處理裝置。第2項：流體化床廢棄物焚化爐不受第1款及第2款之限制。",
 "What combustion chamber outlet temperature, gas residence time and combustion efficiency apply to hazardous waste incinerators?",
 ["Outlet centre temperature at least 1,000°C; gas residence at least one second for sharps and infectious waste and at least two seconds for other hazardous waste; combustion efficiency at least 99.9 percent when incinerating infectious waste","Outlet centre temperature at least 800°C; gas residence at least two seconds for sharps and infectious waste and at least four seconds for other hazardous waste; combustion efficiency at least 99 percent for infectious waste","Outlet centre temperature at least 1,200°C; gas residence at least three seconds for sharps and infectious waste and at least five seconds for other hazardous waste; combustion efficiency at least 95 percent for infectious waste","Outlet centre temperature at least 600°C; gas residence at least half a second for sharps and infectious waste and at least one second for other hazardous waste; combustion efficiency at least 90 percent for infectious waste"],
 "Article 24, paragraphs 1 and 2."),

(S,"第25條",1,"事廢標準-其他熱處理",
 "有害事業廢棄物採焚化法以外之熱處理法處理者，其設施應符合何項規定？",
 ["應符合第二十三條及第二十四條第一項第三款至第五款之規定","應符合第二十三條及第二十四條第一項全部五款之規定","應符合第二十三條及第二十四條第一項第一款、第二款之規定","應僅須符合第二十三條之規定而不適用第二十四條各款"],"a",
 "第25條：有害事業廢棄物採焚化法以外之熱處理法處理者，其設施應符合第23條及前條第1項第3款至第5款之規定，亦即應符合中間處理設施之一般規定，並符合破壞去除效率、自動監測控制及其他經中央主管機關公告事項之要求，但不受第1款燃燒室出口溫度及滯留時間、第2款燃燒效率規定之限制。第2條第8款所定熱處理法包括焚化法、熱解法、熔融法、熔煉法及其他熱處理法。",
 "Which rules apply to facilities using thermal treatment other than incineration for hazardous waste?",
 ["Article 23 and Article 24, paragraph 1, subparagraphs 3 to 5","Article 23 and all five subparagraphs of Article 24, paragraph 1","Article 23 and Article 24, paragraph 1, subparagraphs 1 and 2","Only Article 23, with none of the Article 24 subparagraphs applying"],
 "Article 25, read with Articles 2, 23 and 24."),

(S,"第26條",1,"事廢標準-一般熱處理設施",
 "一般事業廢棄物之熱處理設施應符合何項規定？採焚化法處理者另有何規定？",
 ["應符合第二十三條及第二十四條第一項第四款、第五款之規定；採焚化法處理者準用一般廢棄物焚化處理設施規定","應符合第二十三條及第二十四條第一項第一款至第三款之規定；採焚化法處理者準用有害事業廢棄物焚化設施規定","應符合第二十三條及第十一條有害貯存設施之全部規定；採焚化法處理者應另行取得中央主管機關個案核准","應符合第二十三條及第三十四條衛生掩埋設施之規定；採焚化法處理者應由中央目的事業主管機關逐案核定"],"a",
 "第26條第1項：一般事業廢棄物之熱處理設施，應符合第23條及第24條第1項第4款、第5款之規定，亦即應符合中間處理設施之一般規定，並具有自動監測、燃燒條件自動監測及控制、燃燒室出口中心溫度連續記錄及緊急應變處理裝置，及其他經中央主管機關公告之事項。第2項：前項處理設施採焚化法處理者，準用一般廢棄物焚化處理設施規定。第27條並規定經熱處理法處理後產生之飛灰、底渣或灰渣應每半年檢驗一次。",
 "Which rules apply to thermal treatment facilities for general industrial waste, and to incineration among them?",
 ["Article 23 and Article 24, paragraph 1, subparagraphs 4 and 5; where incineration is used, the rules for general waste incineration facilities apply by analogy","Article 23 and Article 24, paragraph 1, subparagraphs 1 to 3; where incineration is used, the hazardous waste incinerator rules apply by analogy","Article 23 and all the hazardous storage facility rules in Article 11; where incineration is used, separate central approval is needed for each case","Article 23 and the sanitary landfill rules in Article 34; where incineration is used, the central industry authority approves each case"],
 "Article 26, paragraphs 1 and 2, with Article 27."),

(S,"第27條",1,"事廢標準-飛灰檢驗",
 "經熱處理法處理後產生之飛灰、底渣或灰渣，應多久檢驗一次？並如何判定處理？",
 ["應每半年檢驗一次，並依有害事業廢棄物認定標準分別判定處理","應每一年檢驗一次，並依一般事業廢棄物之規定逕行掩埋處理","應每一個月檢驗一次，並依中央目的事業主管機關指定方式處理","應每三年檢驗一次，並由處理機構自行認定其屬性後分別處理"],"a",
 "第27條：經熱處理法處理後產生之飛灰、底渣或灰渣，應每半年檢驗一次，並依有害事業廢棄物認定標準分別判定處理。經判定屬有害事業廢棄物者，應依第20條、第38條、第41條等有害事業廢棄物之處理及最終處置規定辦理；經判定屬一般事業廢棄物者，則依第19條、第32條至第37條等規定辦理。",
 "How often must fly ash, bottom ash or residue from thermal treatment be tested, and how is it then handled?",
 ["Every six months, and handled according to the hazardous industrial waste determination criteria","Every year, and landfilled directly under the rules for general industrial waste","Every month, and handled in the manner designated by the central industry authority","Every three years, with the treatment institution classifying it itself and handling it accordingly"],
 "Article 27, read with Articles 19, 20, 32 to 38 and 41."),

(S,"第28條",1,"事廢標準-固化穩定設施",
 "固化及穩定化處理設施除依第二十三條規定外，尚應具備何種設備？",
 ["應具有將廢棄物及固化劑或化學劑混合均勻之設備","應具有將廢棄物加熱至熔流點以上之高溫熔融設備","應具有連續量測滲出水導電度及酸鹼值之監測設備","應具有將固化物切割成規定尺寸之自動裁切設備"],"a",
 "第28條：固化及穩定化處理設施，除依第23條規定外，並應具有將廢棄物及固化劑或化學劑混合均勻之設備。第2條第6款定義固化法指利用固化劑與事業廢棄物混合固化之處理方法；第7款定義穩定法指利用化學劑與事業廢棄物混合或反應使事業廢棄物穩定化之處理方法。第41條第1項並規定經固化法處理後之固化物採衛生掩埋者，其單軸抗壓強度應在十公斤／平方公分以上。",
 "Besides Article 23, what equipment must solidification and stabilization facilities have?",
 ["Equipment that mixes the waste evenly with the solidifying or chemical agent","Equipment that heats the waste above its melting flow point for high temperature melting","Equipment that continuously measures the conductivity and pH of leachate","Equipment that automatically cuts the solidified product to prescribed dimensions"],
 "Article 28, read with Articles 2, 23 and 41."),

(S,"第29條",2,"事廢標準-處理期限",
 "事業廢棄物處理機構或再利用機構應於收到廢棄物後多久內完成處理或再利用作業？有何例外？",
 ["應於收到廢棄物三十日內完成；因特殊情形無法完成者得報經原許可文件核發之主管機關或目的事業主管機關同意，另許可文件已註明處理期程者亦不受限制","應於收到廢棄物七日內完成；因特殊情形無法完成者得逕行延長一次並於事後報備查，另許可文件已註明處理期程者仍應優先適用三十日規定","應於收到廢棄物九十日內完成；因特殊情形無法完成者應報請中央主管機關核准，另許可文件未註明處理期程者不受任何期限限制","應於收到廢棄物一年內完成；因特殊情形無法完成者由處理機構自行決定展延期間，另許可文件所載期程僅供參考而無拘束力"],"a",
 "第29條第1項：事業廢棄物處理機構或再利用機構應於收到廢棄物三十日內完成廢棄物處理或再利用作業。第2項：因特殊情形無法於三十日內完成者，得報經原許可文件核發之主管機關或再利用之目的事業主管機關同意，並由該機關將同意文件副知中央主管機關，不受第1項規定之限制。第3項：處理機構或再利用機構於許可文件核發時已註明其處理或再利用期程者，不受第1項規定之限制。",
 "Within how long must a treatment or reuse institution finish processing received waste, and what exceptions apply?",
 ["Within thirty days of receipt; in special circumstances it may seek the consent of the permitting or industry authority, and a permit that already states a schedule is not bound by the limit","Within seven days of receipt; in special circumstances it may extend once and file afterwards, and a permit stating a schedule still yields to the thirty-day rule","Within ninety days of receipt; in special circumstances central approval is needed, and a permit that states no schedule is subject to no time limit at all","Within one year of receipt; in special circumstances the institution sets its own extension, and any schedule in the permit is merely advisory"],
 "Article 29, paragraphs 1 to 3."),

(S,"第30條",2,"事廢標準-最終處置方式",
 "事業廢棄物之最終處置應以何種方式為之？液體廢棄物及不具相容性廢棄物有何限制？",
 ["應以安定掩埋法、衛生掩埋法、封閉掩埋法或海洋棄置法為之；非屬水污染防治法所規範之液體廢棄物除經中央主管機關核可外禁止直接以掩埋法處理；不具相容性之事業廢棄物不得合併掩埋","應以焚化法、熱解法、熔融法或固化法為之；非屬水污染防治法所規範之液體廢棄物得逕行以掩埋法處理；不具相容性之事業廢棄物得於分區後合併掩埋以節省用地","應以再利用法、再生利用法或能源回收法為之；液體廢棄物應一律先行固化後始得掩埋；不具相容性之事業廢棄物應先經中和處理後合併掩埋","應以衛生掩埋法或封閉掩埋法二者擇一為之；液體廢棄物經地方主管機關同意後得直接掩埋；不具相容性之事業廢棄物由處理機構自行判斷是否合併掩埋"],"a",
 "第30條第1項列四款最終處置方式：安定掩埋法、衛生掩埋法、封閉掩埋法、海洋棄置法。第2項：非屬水污染防治法所規範之液體廢棄物，除經中央主管機關核可者外，禁止直接以掩埋法處理。第3項：不具相容性之事業廢棄物不得合併掩埋。第31條並規定經認定以再利用方式較符資源永續使用方式者，不得以再利用以外方式最終處置；第40條規定採海洋棄置者依海洋污染防治法之規定。",
 "By what means must industrial waste be finally disposed of, and what limits apply to liquids and incompatible wastes?",
 ["Stable landfill, sanitary landfill, secure landfill or ocean dumping; liquid waste outside the Water Pollution Control Act may not be landfilled directly without central approval; incompatible wastes may not be landfilled together","Incineration, pyrolysis, melting or solidification; liquid waste outside that Act may be landfilled directly; incompatible wastes may be landfilled together in separate zones to save land","Reuse, recycling or energy recovery; liquid waste must always be solidified before landfilling; incompatible wastes must be neutralized first and then landfilled together","Either sanitary landfill or secure landfill; liquid waste may be landfilled directly with local authority consent; the treatment institution decides whether incompatible wastes go together"],
 "Article 30, paragraphs 1 to 3, with Articles 31 and 40."),

(S,"第31條",1,"事廢標準-再利用優先",
 "事業廢棄物經認定以再利用方式較符資源永續使用方式者，其最終處置有何限制？認定機關為何？",
 ["不得以再利用以外方式最終處置；由中央主管機關及中央目的事業主管機關認定","得由事業自行選擇最終處置方式；由直轄市、縣（市）主管機關逐案認定","仍得以衛生掩埋法最終處置；由中央目的事業主管機關會商公會認定","應優先以焚化法最終處置；由行政院指定之專案小組會同地方機關認定"],"a",
 "第31條：事業廢棄物經中央主管機關及中央目的事業主管機關認定，以再利用方式較符資源永續使用方式者，不得以再利用以外方式最終處置。第30條第1項則列舉安定掩埋法、衛生掩埋法、封閉掩埋法及海洋棄置法四種最終處置方式；廢棄物清理法第39條並就事業廢棄物再利用之方式、清理計畫書提送及再利用許可等定有規定。",
 "What limit applies where reuse is recognized as the more resource-sustainable route, and who makes that recognition?",
 ["No final disposal route other than reuse may be used; the central authority and the central industry authority make the recognition","The enterprise may still choose its own final disposal route; the municipal or county authority decides case by case","Sanitary landfill remains available as final disposal; the central industry authority decides with the trade association","Incineration must be preferred for final disposal; an Executive Yuan task force decides jointly with local agencies"],
 "Article 31, read with Article 30 and Article 39 of the Waste Disposal Act."),

(S,"第32條",2,"事廢標準-安定掩埋設施",
 "玻璃屑、陶瓷屑、廢鑄砂、混凝土塊、廢磚瓦等一般事業廢棄物得以安定掩埋法處理，其設施應符合何項規定？",
 ["於入口處豎立標示牌標示廢棄物種類、使用期限及管理人；於掩埋場周圍設有圍牆或障礙物；有地盤滑動沈陷之虞者應設置防止措施；依廢棄物特性及場址地形地質設置水土保持措施；防止廢棄物飛散之措施","於入口處設置地磅及自動辨識系統；於掩埋場周圍設置監測井三口以上；應設置雙層人造不透水材料襯裡；設置滲出液收集及處理設施；設置廢氣收集處理設施及連續監測系統","於入口處設置門禁管制及訪客登記簿；於掩埋場周圍設置寬度十公尺之綠帶；應以抗壓混凝土構築周圍及底部；設置地下水監測裝置並每季檢測；設置緊急沖淋及警報設備","於入口處張貼環境影響評估審查結論；於掩埋場周圍設置消防通道；應鋪設寬度五公尺以上之進場道路；設置滅火器及照明設備；設置專責人員辦公室及檢驗室"],"a",
 "第32條列六款：於入口處豎立標示牌，標示廢棄物種類、使用期限及管理人；於掩埋場周圍設有圍牆或障礙物；有地盤滑動、沈陷之虞者應設置防止之措施；依掩埋廢棄物之特性及掩埋場址地形、地質設置水土保持措施；防止廢棄物飛散之措施；其他經中央主管機關公告者。第2條第14款第1目定義安定掩埋法指將一般事業廢棄物置於掩埋場，設有防止地盤滑動、沈陷及水土保持設施或措施之處理方法。第33條並規定安定掩埋場終止使用者應覆蓋厚度五十公分以上之砂質或泥質黏土。",
 "Which requirements apply to stable landfill facilities for glass, ceramic, casting sand, concrete and brick waste?",
 ["An entrance sign showing waste type, service period and manager; a wall or barrier around the site; measures against ground slippage or subsidence where that risk exists; soil and water conservation suited to the waste and terrain; measures preventing waste from scattering","A weighbridge and automatic identification system at the entrance; at least three monitoring wells around the site; a double-layer artificial impermeable liner; leachate collection and treatment; waste gas collection with continuous monitoring","Access control and a visitor register at the entrance; a ten metre green belt around the site; pressure-resistant concrete walls and base; groundwater monitoring devices tested quarterly; emergency shower and alarm equipment","The environmental impact conclusions posted at the entrance; fire access lanes around the site; an access road at least five metres wide; extinguishers and lighting; an office and laboratory for dedicated personnel"],
 "Article 32, subparagraphs 1 to 6, with Articles 2 and 33."),

(S,"第33條",1,"事廢標準-安定掩埋覆土",
 "安定掩埋場終止使用者，應覆蓋何種材料及厚度？",
 ["應覆蓋厚度五十公分以上之砂質或泥質黏土","應覆蓋厚度十五公分以上之砂質或泥質黏土","應覆蓋厚度六十公分以上之人造不透水材料","應覆蓋厚度三十公分以上之細砂或碎石級配"],"a",
 "第33條：安定掩埋場終止使用者，應覆蓋厚度五十公分以上之砂質或泥質黏土。第35條第1項第1款就衛生掩埋場規定於每工作日結束時應覆蓋厚度十五公分以上之土並予壓實，於終止使用時應覆蓋厚度五十公分以上之砂質或泥質黏土。第36條並規定安定掩埋場、衛生掩埋場之覆蓋能以其他有效方法或無須每日覆蓋者，得向直轄市、縣（市）主管機關申請核准後為之。",
 "What cover material and thickness apply when a stable landfill ceases operation?",
 ["Sandy or silty clay at least fifty centimetres thick","Sandy or silty clay at least fifteen centimetres thick","Artificial impermeable material at least sixty centimetres thick","Fine sand or graded gravel at least thirty centimetres thick"],
 "Article 33, read with Articles 35 and 36."),

(S,"第34條",3,"事廢標準-衛生掩埋設施",
 "一般事業廢棄物無須中間處理者得以衛生掩埋法處理，其掩埋場底層及周圍之基礎材料規定為何？",
 ["應以透水係數低於10-7公分／秒、與廢棄物或其滲出液具相容性、厚度六十公分以上之砂質或泥質黏土或相當材料為基礎，或以透水係數低於10-10公分／秒、單位厚度○．二公分以上之人造不透水材料為基礎","應以透水係數低於10-5公分／秒、厚度三十公分以上之細砂或碎石為基礎，或以透水係數低於10-8公分／秒、單位厚度○．五公分以上之人造不透水材料為基礎","應以單軸抗壓強度二百四十五公斤／平方公分以上、厚度十五公分以上之混凝土為基礎，或以厚度九十公分以上之黏土再覆雙層人造不透水材料為基礎","應以透水係數大於10-2公分／秒、厚度三十公分以上之細砂或碎石為基礎，或以厚度五十公分以上之砂質黏土並設置滲出液偵測設施為基礎"],"a",
 "第34條第1項第3款：掩埋場之底層及周圍應以透水係數低於10-7公分／秒，並與廢棄物或其滲出液具相容性，厚度六十公分以上之砂質或泥質黏土或其他相當之材料做為基礎，或以透水係數低於10-10公分／秒，並具相容性，單位厚度○．二公分以上之人造不透水材料做為基礎。第3項並規定一百十年二月二十二日修正施行後新設之衛生掩埋場，應同時以前述黏土做為基礎及以人造不透水材料做為襯裡，不適用第1項第3款規定。第1項另定入口標示牌、廢氣處理設施、滲出液收集處理設施、上下游監測井各一口以上、消防設備等要求。",
 "What base material requirements apply to the bottom and sides of a sanitary landfill?",
 ["Sandy or silty clay or equivalent at least sixty centimetres thick with permeability below 10-7 cm/s and compatible with the waste or leachate, or artificial impermeable material below 10-10 cm/s and at least 0.2 cm thick","Fine sand or gravel at least thirty centimetres thick with permeability below 10-5 cm/s, or artificial impermeable material below 10-8 cm/s and at least 0.5 cm thick","Concrete at least fifteen centimetres thick with uniaxial strength of at least 245 kg per square centimetre, or ninety centimetres of clay covered with a double artificial impermeable layer","Fine sand or gravel at least thirty centimetres thick with permeability above 10-2 cm/s, or fifty centimetres of sandy clay with leachate detection facilities"],
 "Article 34, paragraphs 1 and 3."),

(S,"第35條",3,"事廢標準-衛生掩埋覆土監測",
 "衛生掩埋場之覆土及監測應符合何項規定？監測結果達地下水污染監測標準時應如何處理？",
 ["每工作日結束時應覆蓋厚度十五公分以上之土並壓實，終止使用時應覆蓋五十公分以上之砂質或泥質黏土；每季定期檢測上下游地下水監測井水質，項目包括砷鎘鉻銅鉛汞鎳及鋅；達監測標準者應於一個月內提報因應措施經核准後執行","每工作日結束時應覆蓋厚度三十公分以上之土並壓實，終止使用時應覆蓋六十公分以上之黏土；每半年檢測上下游地下水監測井水質，項目包括氨氮及生化需氧量；達監測標準者應於三個月內提報因應措施","每週結束時應覆蓋厚度十公分以上之土，終止使用時應覆蓋四十公分以上之砂土；每年檢測地下水監測井水質一次，項目由事業自行決定；達監測標準者應立即停止收受廢棄物並封場","每月結束時應覆蓋厚度二十公分以上之土，終止使用時應覆蓋七十公分以上之黏土；每二年檢測地下水一次，項目包括戴奧辛及多氯聯苯；達監測標準者應報請中央主管機關核定後處理"],"a",
 "第35條第1項第1款：於每工作日結束時應覆蓋厚度十五公分以上之土並予以壓實；於終止使用時應覆蓋厚度五十公分以上之砂質或泥質黏土。第2款：每季定期檢測上下游之地下水監測井水質，檢測項目應包括砷、鎘、鉻、銅、鉛、汞、鎳及鋅。第2項：監測結果低於地下水污染管制標準而達地下水污染監測標準者，事業應於取得監測結果一個月內提報因應措施，經許可文件核發之主管機關或目的事業主管機關核准後執行之。第41條之5並規定監測執行情形應作成紀錄妥善保存五年。",
 "What cover and monitoring rules apply to sanitary landfills, and what follows when results reach the groundwater monitoring standard?",
 ["At least fifteen centimetres of compacted soil at the end of each working day and at least fifty centimetres of sandy or silty clay on closure; quarterly upstream and downstream groundwater testing for arsenic, cadmium, chromium, copper, lead, mercury, nickel and zinc; response measures filed within one month and carried out once approved","At least thirty centimetres daily and sixty centimetres of clay on closure; half-yearly groundwater testing for ammonia nitrogen and biochemical oxygen demand; response measures filed within three months","At least ten centimetres weekly and forty centimetres of sandy soil on closure; annual groundwater testing with items chosen by the enterprise; waste receipt stopped and the site closed at once","At least twenty centimetres monthly and seventy centimetres of clay on closure; groundwater testing every two years for dioxins and PCBs; response measures approved by the central authority"],
 "Article 35, paragraphs 1 and 2, with Article 41-5."),

(S,"第36條",1,"事廢標準-覆蓋替代",
 "安定掩埋場、衛生掩埋場之覆蓋，能以其他有效方法或無須每日覆蓋者，應如何辦理？",
 ["得向直轄市、縣（市）主管機關申請核准後為之","得由事業逕行採行並於事後三十日內報備查","應報請中央主管機關會商目的事業主管機關核定","應經環境影響評估審查通過後始得變更覆蓋方式"],"a",
 "第36條：安定掩埋場、衛生掩埋場之覆蓋，能以其他有效方法或無須每日覆蓋者，得向直轄市、縣（市）主管機關申請核准後為之。第33條規定安定掩埋場終止使用應覆蓋五十公分以上砂質或泥質黏土；第35條第1項第1款規定衛生掩埋場每工作日結束應覆蓋十五公分以上之土並壓實，終止使用時應覆蓋五十公分以上之砂質或泥質黏土。",
 "How may an alternative or non-daily cover method be adopted at a stable or sanitary landfill?",
 ["By applying to the municipal or county authority and obtaining its approval","By adopting it directly and filing for record within thirty days afterwards","By obtaining central authority approval in consultation with the industry authority","By passing an environmental impact assessment before changing the cover method"],
 "Article 36, read with Articles 33 and 35."),

(S,"第37條",1,"事廢標準-進場管制基準",
 "事業廢棄物採衛生掩埋者應符合何項基準始得掩埋？該基準由何機關依何種factors分別定之？",
 ["應符合衛生掩埋場進場管制基準；該基準由中央主管機關依行業、製程、廢棄物種類、處理方法及有害物質管制項目分別定之","應符合有害事業廢棄物認定標準附表四之溶出標準；該基準由中央目的事業主管機關依事業規模及產量分別定之","應符合地下水污染管制標準及土壤污染管制標準；該基準由直轄市、縣（市）主管機關依轄區特性分別訂定公告","應符合放流水標準及事業廢水排放標準；該基準由中央主管機關會商水利主管機關依流域分區分別定之"],"a",
 "第37條第1項：事業廢棄物採衛生掩埋者須符合衛生掩埋場進場管制基準，始得進行衛生掩埋。第2項：前項衛生掩埋場進場管制基準，由中央主管機關依行業、製程、廢棄物種類、處理方法及有害物質管制項目分別定之。第41條第2項並規定有害事業廢棄物採固化法、穩定法處理者採衛生掩埋時，除第37條另有規定外應符合有害事業廢棄物認定標準附表四之毒性特性溶出程序溶出標準，並應獨立分區掩埋管理。",
 "What criteria must waste meet for sanitary landfill, and who sets them on what basis?",
 ["The sanitary landfill acceptance control criteria; the central authority sets them separately by industry, process, waste type, treatment method and hazardous substance control items","The leachate limits in Table 4 of the hazardous waste criteria; the central industry authority sets them by enterprise scale and output","The groundwater and soil pollution control standards; each municipal or county authority sets and announces them for local conditions","The effluent and industrial wastewater discharge standards; the central authority sets them with the water authority by river basin"],
 "Article 37, paragraphs 1 and 2, with Article 41."),

(S,"第38條",3,"事廢標準-封閉掩埋設施",
 "有害事業廢棄物應以封閉掩埋法處理，其進場道路寬度、周圍及底部設施強度、間隔規定為何？",
 ["掩埋場應舖設進場道路其寬度為五公尺以上；周圍及底部設施應以單軸抗壓強度二百四十五公斤／平方公分以上、厚度十五公分以上之混凝土或同等封閉能力材料構築；掩埋面積每超過五十平方公尺或掩埋容積超過二百五十立方公尺者應予間隔","掩埋場應舖設進場道路其寬度為三公尺以上；周圍及底部設施應以單軸抗壓強度一百公斤／平方公分以上、厚度十公分以上之混凝土構築；掩埋面積每超過一百平方公尺或容積超過五百立方公尺者應予間隔","掩埋場應舖設進場道路其寬度為八公尺以上；周圍及底部設施應以單軸抗壓強度三百五十公斤／平方公分以上、厚度二十公分以上之混凝土構築；掩埋面積每超過二十平方公尺或容積超過一百立方公尺者應予間隔","掩埋場應舖設進場道路其寬度為十公尺以上；周圍及底部設施應以厚度六十公分以上之砂質黏土構築；掩埋面積每超過二百平方公尺或容積超過一千立方公尺者應予間隔"],"a",
 "第38條第1項列九款，包括掩埋場應有抗壓及抗震之設施；應舖設進場道路其寬度為五公尺以上；應有防止地面水、雨水及地下水流入滲透之設施；周圍及底部設施應以具有單軸抗壓強度二百四十五公斤／平方公分以上、厚度十五公分以上之混凝土或其他具同等封閉能力之材料構築；掩埋面積每超過五十平方公尺或掩埋容積超過二百五十立方公尺者應予間隔，其隔牆及掩埋完成面以具單軸抗壓強度二百四十五公斤／平方公分、壁厚十公分以上之混凝土構築；掩埋場底層應以透水係數低於10-7公分／秒厚度六十公分以上黏土為基礎並以低於10-10公分／秒、○‧二公分以上人造不透水材料為襯裡。",
 "What access road width, wall and base strength and compartment limits apply to secure landfills?",
 ["An access road at least five metres wide; walls and base of concrete or equivalent with uniaxial strength of at least 245 kg per square centimetre and at least fifteen centimetres thick; compartments required beyond fifty square metres of area or 250 cubic metres of volume","An access road at least three metres wide; walls and base of concrete of at least 100 kg per square centimetre and ten centimetres thick; compartments beyond one hundred square metres or 500 cubic metres","An access road at least eight metres wide; walls and base of concrete of at least 350 kg per square centimetre and twenty centimetres thick; compartments beyond twenty square metres or 100 cubic metres","An access road at least ten metres wide; walls and base of sandy clay at least sixty centimetres thick; compartments beyond two hundred square metres or 1,000 cubic metres"],
 "Article 38, paragraph 1, subparagraphs 2, 4, 5 and 7."),

(S,"第39條",2,"事廢標準-封閉掩埋覆土",
 "封閉掩埋場於終止使用時之覆蓋規定為何？終止使用後之土地利用有何限制？",
 ["應先覆以厚度十五公分砂質或泥質黏土，再覆蓋透水係數低於10-10公分／秒、單位厚度○．二公分以上之人造不透水材料及厚度六十公分以上之砂質或泥質黏土並予壓實；終止使用後不得做為建築用地或其他工作場所","應先覆以厚度三十公分細砂，再覆蓋單位厚度○．五公分以上之人造不透水材料及厚度三十公分以上之黏土並予壓實；終止使用後得做為建築用地但須經環境影響評估審查通過","應先覆以厚度五十公分砂質黏土，再覆蓋厚度九十公分之黏土層並予壓實；終止使用後得做為停車場、公園或低密度開發社區使用而無須任何限制","應先覆以厚度十公分碎石，再覆蓋雙層人造不透水材料及厚度二十公分之表土並植生綠化；終止使用後得由土地所有人自由變更使用用途"],"a",
 "第39條第1項第1款：於終止使用時，應先覆以厚度十五公分砂質或泥質黏土，再覆蓋透水係數低於10-10公分／秒、單位厚度○．二公分以上之人造不透水材料及厚度六十公分以上之砂質或泥質黏土，並予壓實。第2款：每季定期檢測上下游之地下水監測井水質，檢測項目應包括砷、鎘、鉻、銅、鉛、汞、鎳及鋅。第2項：監測結果達地下水污染監測標準者應於一個月內提報因應措施經核准後執行。第3項：封閉掩埋場終止使用後，不得做為建築用地或其他工作場所。",
 "What cover applies when a secure landfill closes, and what land use limit follows?",
 ["First fifteen centimetres of sandy or silty clay, then artificial impermeable material below 10-10 cm/s and at least 0.2 cm thick, then at least sixty centimetres of sandy or silty clay, all compacted; the site may not become building land or any other workplace","First thirty centimetres of fine sand, then artificial impermeable material at least 0.5 cm thick, then thirty centimetres of clay, compacted; the site may become building land after a passed environmental review","First fifty centimetres of sandy clay, then a ninety centimetre clay layer, compacted; the site may freely become a car park, park or low density community","First ten centimetres of gravel, then a double impermeable layer and twenty centimetres of topsoil with planting; the landowner may freely change the land use afterwards"],
 "Article 39, paragraphs 1 to 3."),

(S,"第40條",1,"事廢標準-海洋棄置",
 "事業廢棄物之處理採海洋棄置者，應依何種法律規定辦理？",
 ["依海洋污染防治法之規定","依水污染防治法之規定","依環境影響評估法之規定","依商港法及船舶法之規定"],"a",
 "第40條：事業廢棄物之處理採海洋棄置者，依海洋污染防治法之規定。第30條第1項第4款將海洋棄置法列為四種最終處置方式之一；第2條第14款則就安定掩埋法、衛生掩埋法及封閉掩埋法分別定義。第31條並規定經認定以再利用方式較符資源永續使用方式者，不得以再利用以外方式最終處置。",
 "Which law governs ocean dumping of industrial waste?",
 ["The Marine Pollution Control Act","The Water Pollution Control Act","The Environmental Impact Assessment Act","The Commercial Port Act and the Ship Act"],
 "Article 40, read with Articles 2, 30 and 31."),

(S,"第41條",3,"事廢標準-固化物掩埋",
 "經固化法處理後之固化物採衛生掩埋者，其單軸抗壓強度應達多少？有害事業廢棄物採固化穩定法處理者應如何處置？",
 ["固化物之單軸抗壓強度應在十公斤／平方公分以上；有害事業廢棄物採固化法、穩定法或經公告方法處理者應採封閉掩埋法或衛生掩埋法處置，採衛生掩埋者應符合溶出標準並獨立分區掩埋管理","固化物之單軸抗壓強度應在五十公斤／平方公分以上；有害事業廢棄物採固化法、穩定法處理者應一律採封閉掩埋法處置，不得採衛生掩埋法或安定掩埋法處置","固化物之單軸抗壓強度應在二百四十五公斤／平方公分以上；有害事業廢棄物採固化法、穩定法處理者得採安定掩埋法處置，並無須符合任何溶出標準","固化物之單軸抗壓強度應在三公斤／平方公分以上；有害事業廢棄物採固化法、穩定法處理者應報請中央主管機關個案指定處置方式後辦理"],"a",
 "第41條第1項：經固化法處理後之固化物，採衛生掩埋法處理者，其固化物之單軸抗壓強度應在十公斤／平方公分以上。第2項：有害事業廢棄物採固化法、穩定法或其他經中央主管機關公告之處理方法處理者，應採封閉掩埋法或衛生掩埋法處置；採衛生掩埋者除第37條另有規定外，應符合有害事業廢棄物認定標準附表四之毒性特性溶出程序（TCLP）溶出標準，並應獨立分區掩埋管理。第3項：前二項採再利用者，應依再利用相關規定申請。",
 "What uniaxial strength must solidified product reach for sanitary landfill, and how must such hazardous waste be disposed of?",
 ["At least 10 kg per square centimetre; hazardous waste treated by solidification, stabilization or an announced method must go to secure or sanitary landfill, and sanitary landfill requires meeting the leachate limits and separate zoned management","At least 50 kg per square centimetre; such hazardous waste must always go to secure landfill and may never go to sanitary or stable landfill","At least 245 kg per square centimetre; such hazardous waste may go to stable landfill and need not meet any leachate limits","At least 3 kg per square centimetre; such hazardous waste needs a disposal route designated case by case by the central authority"],
 "Article 41, paragraphs 1 to 3."),

(S,"第41條之1",3,"事廢標準-封場復育計畫",
 "掩埋場終止使用時應依何辦理？封場復育計畫應包括哪些內容？完成封場復育之期限為何？",
 ["應依許可文件之封場復育計畫辦理；計畫應包括基本資料、封場復育作業項目（最終覆土、排水工程、植被復育）、定期巡檢及設施維護規劃、環境監測類別項目方法及頻率、緊急應變計畫；應於完成最後一批廢棄物最終處置之次日起一年內完成","應依中央主管機關公告之標準作業程序辦理；計畫應包括土地買賣契約、地價評估報告及開發計畫書；應於完成最後一批廢棄物最終處置之次日起三年內完成封場復育作業","應依地方議會決議之復育方案辦理；計畫應包括景觀設計圖說、遊憩設施配置及營運收費標準；應於取得處理完成證明文件之次日起五年內完成封場復育作業","應依目的事業主管機關指定之方式辦理；計畫應包括員工安置計畫、設備處分清冊及財務結算報告；應於掩埋場停止收受廢棄物之次日起六個月內完成封場復育"],"a",
 "第41條之1第1項：掩埋場終止使用時，應依許可文件之封場復育計畫辦理。第2項列五款計畫內容：基本資料（掩埋場名稱類型起訖日填埋面積深度廢棄物種類數量清冊、土地所有權狀地籍資料土地清冊、基礎結構平面立面橫截面及結構圖）；封場復育之作業項目（最終覆土、排水工程、植被復育）；定期巡檢及設施維護規劃；環境監測類別、項目、方法及頻率；緊急應變計畫。第5項：應於完成最後一批廢棄物最終處置之次日起一年內完成封場復育作業，須延長者應於期間屆滿二個月前申請延長，並以一次為限且不得超過一年。",
 "What governs landfill closure, what must the closure and restoration plan contain, and by when must it be done?",
 ["The closure and restoration plan in the permit; it must cover basic data, closure works (final cover, drainage, revegetation), inspection and maintenance planning, environmental monitoring categories, items, methods and frequency, and an emergency response plan; it must be completed within one year from the day after the last waste is finally disposed of","Standard operating procedures announced by the central authority; it must cover land sale contracts, land value appraisal and a development plan; it must be completed within three years from the day after final disposal","A restoration scheme resolved by the local council; it must cover landscape drawings, recreational facility layout and fee schedules; it must be completed within five years of the completion certificate","A method designated by the industry authority; it must cover staff redeployment, an equipment disposal list and financial accounts; it must be completed within six months of ceasing waste receipt"],
 "Article 41-1, paragraphs 1, 2 and 5."),

(S,"第41條之2",3,"事廢標準-封場環境監測",
 "掩埋場封場復育計畫之環境監測應含何項目及頻率？封場後環境監測至少應執行幾年？",
 ["應含上下游地下水監測井水質，檢測項目包括砷鎘鉻銅鉛汞鎳及鋅，且每半年監測一次；封場後之環境監測至少執行七年，最後二年連續監測符合規定者得報請核准後終止","應含上下游地下水監測井水質，檢測項目包括氨氮及總有機碳，且每季監測一次；封場後之環境監測至少執行三年，最後一年符合規定者得逕行終止而無須報准","應含土壤及空氣品質，檢測項目包括戴奧辛及揮發性有機物，且每年監測一次；封場後之環境監測至少執行十五年，期間不得申請終止監測作業","應含放流水及底泥品質，檢測項目由事業自行決定，且每二年監測一次；封場後之環境監測至少執行五年，屆滿即自動終止而無須任何程序"],"a",
 "第41條之2第1項：掩埋場之封場復育計畫，其環境監測類別應含上下游之地下水監測井水質，檢測項目應包括砷、鎘、鉻、銅、鉛、汞、鎳及鋅，且每半年監測一次。第2項：監測結果低於地下水污染管制標準而達地下水污染監測標準者，應於一個月內提報因應措施經核准後執行。第3項：封場後之環境監測至少執行七年，最後二年連續監測符合下列規定者得檢附證明文件報請核准後終止：未經處理滲出水污染物濃度低於放流水標準（但確認已無滲出水流出者不在此限）；地下水水質八項重金屬濃度低於地下水污染監測標準；其他經主管機關規定事項。",
 "What monitoring items and frequency apply to a closure plan, and for how long must post-closure monitoring run?",
 ["Upstream and downstream groundwater well quality for arsenic, cadmium, chromium, copper, lead, mercury, nickel and zinc, monitored every six months; post-closure monitoring runs at least seven years and may end on approval if the last two years comply continuously","Upstream and downstream groundwater quality for ammonia nitrogen and total organic carbon, monitored quarterly; post-closure monitoring runs at least three years and ends automatically if the final year complies","Soil and air quality for dioxins and volatile organic compounds, monitored annually; post-closure monitoring runs at least fifteen years and may not be ended early","Effluent and sediment quality with items chosen by the enterprise, monitored every two years; post-closure monitoring runs at least five years and then ends automatically"],
 "Article 41-2, paragraphs 1 to 3."),

(S,"第41條之3",2,"事廢標準-封場計畫提報",
 "一百十年二月二十二日修正施行後設置之掩埋場，及修正施行前未封場之掩埋場，其封場復育計畫應分別於何時提報？",
 ["修正施行後設置者應於申請事業廢棄物設置或處理許可文件時併同封場復育計畫送核准；修正施行前未封場者應於一百十年二月二十二日修正發布後一年內檢具封場復育計畫送核准","修正施行後設置者應於取得操作許可證後三年內補送封場復育計畫；修正施行前未封場者應於一百十年二月二十二日修正發布後五年內檢具封場復育計畫送備查","修正施行後設置者應於掩埋場啟用滿五年時提報封場復育計畫；修正施行前未封場者應於實際終止使用之次日起一年內檢具封場復育計畫送核准","修正施行後設置者應於環境影響評估審查時併同提報封場復育計畫；修正施行前未封場者無須補提封場復育計畫而依原核准文件辦理"],"a",
 "第41條之3第1項：本標準中華民國一百十年二月二十二日修正施行後設置之掩埋場，事業應於申請事業廢棄物設置或處理許可文件時，併同封場復育計畫，送許可文件核發之主管機關或目的事業主管機關核准。第2項：本標準一百十年二月二十二日修正施行前未封場之掩埋場，事業應於該日修正發布後一年內，檢具封場復育計畫，送許可文件核發之主管機關或目的事業主管機關核准。第41條之4則就修正施行前已封場之掩埋場定有因應措施提報規定。",
 "When must closure plans be filed for landfills built after 22 February 2021 and for those not yet closed before it?",
 ["Those built afterwards file the closure plan together with the waste facility or treatment permit application for approval; those not yet closed file within one year of the 22 February 2021 amendment","Those built afterwards file within three years of obtaining the operating permit; those not yet closed file for record within five years of the amendment","Those built afterwards file when the landfill reaches five years of operation; those not yet closed file within one year of actually ceasing use","Those built afterwards file together with the environmental impact assessment; those not yet closed need file no plan and follow their original approval"],
 "Article 41-3, paragraphs 1 and 2, with Article 41-4."),

(S,"第41條之4",2,"事廢標準-已封場因應",
 "一百十年二月二十二日修正施行前已封場之掩埋場，經主管機關監測調查結果達地下水污染監測標準者，應如何辦理？",
 ["事業應於接獲主管機關通知後一個月內提報因應措施，經許可文件核發之主管機關或目的事業主管機關核准後執行；完成改善後應檢附證明文件報請原核發機關核准","事業應於接獲主管機關通知後三個月內提報整治計畫，經中央主管機關核定後執行；完成改善後由主管機關逕行認定而無須報請核准","事業應於接獲主管機關通知後立即停止一切土地利用行為並圍籬管制；完成改善後應經環境影響評估審查通過始得恢復土地使用","事業應於接獲主管機關通知後六個月內完成全部污染整治作業；完成改善後應由地方議會決議同意後始得解除列管"],"a",
 "第41條之4第1項：本標準中華民國一百十年二月二十二日修正施行前已封場之掩埋場，經主管機關環境監測調查之結果低於地下水污染管制標準而達地下水污染監測標準者，事業應於接獲主管機關通知後一個月內提報因應措施，經許可文件核發之主管機關或目的事業主管機關核准後執行之。第2項：事業依前項因應措施完成改善後，應檢附相關證明文件，報請原許可文件核發之主管機關或目的事業主管機關核准。",
 "What must be done where an already closed pre-2021 landfill is found to reach the groundwater monitoring standard?",
 ["The enterprise files response measures within one month of notice, carries them out once the permitting or industry authority approves, and files evidence for approval after the improvement is complete","The enterprise files a remediation plan within three months of notice for central approval, and the authority confirms completion without any further approval","The enterprise stops all land use at once and fences the site, and may resume use only after a passed environmental impact assessment","The enterprise completes all remediation within six months of notice, and delisting requires a local council resolution"],
 "Article 41-4, paragraphs 1 and 2."),

(S,"第41條之5",2,"事廢標準-監測紀錄保存",
 "第三十五條、第三十九條、第四十一條之二所定監測作業之執行情形，應如何記錄、保存及公開？",
 ["應作成紀錄妥善保存五年，並於取得監測結果之次月月底前將環境監測執行成果登錄於政府網站；許可文件核發之主管機關或目的事業主管機關得予公開","應作成紀錄妥善保存三年，並於取得監測結果之次季結束前將成果函報主管機關備查；監測成果屬營業秘密不得對外公開或登錄於任何網站","應作成紀錄妥善保存十年，並於每年度終了後三個月內彙整報中央主管機關核定；監測成果應於核定後始得由事業自行公開於公司網站","應作成紀錄妥善保存一年，並於取得監測結果後七日內通知鄰近居民及里辦公處；監測成果應報地方議會審議通過後始得對外公開"],"a",
 "第41條之5第1項：第35條第1項第2款、第39條第1項第2款、第41條之2第1項之監測作業執行情形應作成紀錄，妥善保存五年，並於取得監測結果之次月月底前，將環境監測執行成果登錄於政府網站。第2項：前項環境監測執行成果，許可文件核發之主管機關或目的事業主管機關得予公開。第35條、第39條分別為衛生掩埋場及封閉掩埋場之每季地下水監測；第41條之2為封場後每半年之地下水監測。",
 "How must monitoring results under Articles 35, 39 and 41-2 be recorded, kept and published?",
 ["Recorded and properly kept for five years, with results uploaded to a government website by the end of the month after they are obtained; the permitting or industry authority may make them public","Recorded and properly kept for three years, with results filed with the authority by the end of the next quarter; results are trade secrets and may not be published anywhere","Recorded and properly kept for ten years, compiled and submitted for central approval within three months of each year end; results may be published on the company site only after approval","Recorded and properly kept for one year, with neighbouring residents and the neighbourhood office notified within seven days; results may be published only after local council review"],
 "Article 41-5, paragraphs 1 and 2, with Articles 35, 39 and 41-2."),

(S,"第42條",3,"事廢標準-替代處理方法",
 "能以本標準規定以外之其他處理方法更有效去毒、減容、減積處理事業廢棄物者，應如何申請？經核准公告後有何效果？",
 ["應檢具廢棄物特性組成成分分析、處理方法原理及流程、主要設備及功能說明、污染防治計畫書、商業運轉實績證明等文件，向處理設施所在地之地方主管機關提出申請並由其核轉中央主管機關核准；經核准並公告者其他事業於相同條件設備情形下免再申請","應檢具環境影響說明書及操作許可證影本，逕向中央目的事業主管機關提出申請並由其核准後實施；經核准者僅該申請事業得適用，其他事業仍應逐案重新提出申請","應檢具同業公會推薦函及專家學者審查意見書，向直轄市、縣（市）主管機關提出申請並由其逕行核准；經核准者應每年重新申請一次，逾期未申請即失其效力","應檢具財務報表及履約保證金證明，向行政院提出申請並由其會商相關部會核准；經核准並公告者全國事業均得逕行採用而無須具備相同條件及設備"],"a",
 "第42條第1項列六款應檢具文件：廢棄物特性、組成及成分分析；處理方法、原理及流程；主要設備及功能說明；污染防治計畫書；商業運轉實績證明（為國外文件者應經公證認證並譯成中文，為大陸地區者應經海基會驗證，國內外無實績者應檢附相關證明文件）；其他經中央主管機關指定之事項。應向處理設施所在地之地方主管機關提出申請，並由地方主管機關核轉中央主管機關核准，不受第19條至第21條處理方法之限制。第2項：經中央主管機關核准之處理方法並經公告者，其他事業於相同條件、設備之情形下，免依第1項規定提出申請。",
 "How is an alternative treatment method approved, and what follows once it is approved and announced?",
 ["Submit waste characteristics and composition analysis, the method's principles and flow, main equipment and functions, a pollution control plan and commercial operation records to the local authority where the facility sits, which forwards it to the central authority for approval; once approved and announced, other enterprises with the same conditions and equipment need not apply","Submit an environmental impact statement and a copy of the operating permit directly to the central industry authority for approval; only the applicant may use it and others must each apply afresh","Submit a trade association recommendation and expert review opinions to the municipal or county authority, which approves it directly; approval must be renewed yearly or it lapses","Submit financial statements and a performance bond certificate to the Executive Yuan, which approves it with the relevant ministries; once announced, any enterprise nationwide may adopt it regardless of conditions or equipment"],
 "Article 42, paragraphs 1 and 2, with Articles 19 to 21."),

(S,"第43條",3,"事廢標準-書面契約",
 "事業採共同清除處理或委託清除處理方式者，清除前應踐行何種程序？契約應載明何事項？",
 ["清除前應先與受託處理者簽訂書面契約或取得執行機關出具同意處理之證明文件，並應與受託清除者簽訂書面契約；契約或證明文件須載明事業廢棄物種類、數量及期限，始得自行清除或委託清除至該受託處理者處理","清除前僅須以口頭約定並於事後補行簽約即可，無須取得任何同意處理證明文件；契約僅須載明委託金額及付款方式，即得自行清除或委託清除至受託處理者處理","清除前應報請直轄市、縣（市）主管機關逐案核准並繳納保證金；契約須載明雙方負責人身分證字號及公司登記資料，並經法院公證後始生效力","清除前應完成環境影響評估並取得中央主管機關同意函；契約須載明處理設施之操作參數及污染防制設備規格，並報中央主管機關備查後始得執行"],"a",
 "第43條第1項：事業採本法第28條第1項第2款至第4款規定之方式清除、處理事業廢棄物者，清除前應先與受託處理者簽訂書面契約或取得執行機關出具同意處理之證明文件，並應與受託清除者簽訂書面契約。第2項：書面契約或同意處理證明文件須載明事業廢棄物種類、數量及期限，始得自行清除或委託清除至該廢棄物受託處理者處理。第3項：屬公告應檢附廢棄物檢測報告書者，應於簽訂書面契約時檢附六個月內經認可檢驗測定機構採樣檢測所出具之報告書。第4項：受託清除及處理者非屬同一時應分別簽訂契約，但未達公告一定規模之事業得共同簽訂。",
 "What must an enterprise do before clearance under joint or contracted arrangements, and what must the contract state?",
 ["Sign a written contract with the treatment party or obtain the executing agency's consent document, and sign a written contract with the clearance party; the contract or document must state the waste type, quantity and period before clearance may proceed","Reach an oral agreement and sign afterwards, with no consent document needed; the contract need only state the fee and payment method before clearance may proceed","Obtain case-by-case approval from the municipal or county authority and post a bond; the contract must state both parties' identity and registration details and be notarized to take effect","Complete an environmental impact assessment and obtain central consent; the contract must state facility operating parameters and pollution control specifications and be filed centrally"],
 "Article 43, paragraphs 1 to 4."),

(S,"第44條",1,"事廢標準-條文刪除",
 "關於事業廢棄物清理之契約及替代處理方法規範，本標準第四十四條之現行狀態及該領域現行規範依據為何？",
 ["該條業經刪除而無現行內容；替代處理方法之申請核准、委託清理之書面契約及檢測報告書檢附等事項，現依第四十二條、第四十三條及第四十五條等規定辦理","該條規定委託清理契約之應記載事項與範本；書面契約簽訂事項現仍應優先適用該條規定，而非第四十三條所定之程序辦理","該條規定標誌之圖樣尺寸及顏色規格；有害事業廢棄物標誌事項現由該條授權之公告優先於第四十五條規定辦理相關作業","該條規定本標準之施行日期及過渡條款；封場復育計畫提報期限事項現由該條取代第四十一條之三規定辦理相關作業"],"a",
 "第44條業經刪除。現行相關規範分見於：第42條（本標準規定以外其他處理方法之申請與核准公告）、第43條（採共同清除處理或委託清除處理者應簽訂書面契約、契約應載明事項及檢測報告書之檢附）、第45條（本標準所稱之標誌由中央主管機關公告）、第46條（本標準自發布日施行）。",
 "What is the current status of Article 44, and what governs this field now?",
 ["It has been deleted and has no current content; approval of alternative treatment methods, written clearance contracts and attaching test reports are now governed by Articles 42, 43 and 45","It governs the required contents and template of clearance contracts and still takes precedence over the procedure in Article 43","It governs the design, size and colour of symbols, and its announcements still take precedence over Article 45 on hazardous waste symbols","It governs the effective date and transitional provisions and still replaces Article 41-3 on closure plan filing deadlines"],
 "Article 44 is deleted; see Articles 42, 43, 45 and 46."),

(S,"第45條",1,"事廢標準-標誌公告",
 "本標準所稱之標誌，由何機關公告？",
 ["由中央主管機關公告之","由中央目的事業主管機關公告之","由直轄市、縣（市）主管機關公告之","由國家標準檢驗主管機關公告之"],"a",
 "第45條：本標準所稱之標誌，由中央主管機關公告之。第7條第1項第2款要求有害事業廢棄物貯存應標示區別有害事業廢棄物特性之標誌；第11條第4款要求貯存設施應設置白底、紅字、黑框之警告標示；第12條第1款要求生物醫療廢棄物貯存設施應標示區別有害事業廢棄物特性之標誌；第16條第1項第1款要求清除車輛應標示該標誌。",
 "Who announces the symbols referred to in this Standard?",
 ["The central competent authority","The central industry competent authority","The municipal or county competent authority","The national standards inspection authority"],
 "Article 45, read with Articles 7, 11, 12 and 16."),

(S,"第46條",1,"事廢標準-施行日期",
 "本標準之施行日期為何？",
 ["自發布日施行","自發布後六個月施行","自發布後一年施行","自中央主管機關另行公告之日施行"],"a",
 "第46條：本標準自發布日施行。本標準最近一次修正日期為民國112年11月1日。第41條之3並就一百十年二月二十二日修正施行前後設置之掩埋場，分別定有封場復育計畫之提報期限；第34條第3項及第41條之4亦分別就該修正施行日前後之衛生掩埋場基礎構築及已封場掩埋場之因應措施定有規定。",
 "When does this Standard take effect?",
 ["On the date of promulgation","Six months after promulgation","One year after promulgation","On a date separately announced by the central authority"],
 "Article 46, read with Articles 34, 41-3 and 41-4."),
]
