# -*- coding: utf-8 -*-
# 第 3 批（B）：異常氣壓危害預防標準、危害性化學品標示及通識規則
YC = "OSH-18"   # 異常氣壓危害預防標準（民國103年6月25日）
HC = "OSH-12"   # 危害性化學品標示及通識規則（民國115年8月26日）
Q = [
# ---------- 異常氣壓危害預防標準 ----------
(YC,"第2條",2,"異常氣壓-定義",
 "異常氣壓危害預防標準所稱「潛水作業」，指於水深超過多少公尺之水中實施之作業？",
 ["五公尺","十公尺","二十公尺","三十公尺"],"b",
 "第2條：高壓室內作業指沈箱、壓氣潛盾等壓氣施工法中於表壓力超過大氣壓之作業室或豎管內部實施之作業；潛水作業指使用水肺或水面供氣設備等，於水深超過十公尺之水中實施之作業。",
 "Under the Abnormal Pressure Hazard Prevention Standards, 'diving work' means work in water deeper than:",
 ["5 m","10 m","20 m","30 m"],
 "Article 2: hyperbaric chamber work is work in caissons or compressed-air shields above atmospheric pressure; diving work uses scuba or surface-supplied air at depths exceeding 10 m."),

(YC,"第3條",3,"異常氣壓-定義",
 "「耐氧試驗」係指對從事異常氣壓作業勞工在高壓艙以每平方公分多少公斤之壓力，使其呼吸純氧多久之試驗？",
 ["一點八公斤（六十呎）；三十分鐘","一公斤（三十呎）；十分鐘","三公斤（一百呎）；六十分鐘","零點五公斤（十五呎）；十五分鐘"],"a",
 "第3條第2款：耐氧試驗指在高壓艙以每平方公分一點八公斤（六十呎）之壓力，使其呼吸純氧三十分鐘之試驗；氣閘室指對高壓室內作業勞工實施加減壓之處所。",
 "The 'oxygen tolerance test' exposes the worker in a chamber to what pressure breathing pure oxygen for how long?",
 ["1.8 kg/cm² (60 ft); 30 minutes","1 kg/cm² (30 ft); 10 minutes","3 kg/cm² (100 ft); 60 minutes","0.5 kg/cm² (15 ft); 15 minutes"],
 "Article 3(2): 1.8 kg/cm² (60 ft) breathing pure oxygen for 30 minutes; an air lock is where workers are compressed and decompressed."),

(YC,"第5條、第6條",3,"異常氣壓-設備",
 "高壓室內作業，作業室內每一勞工占有之氣積應在多少立方公尺以上？氣閘室內每一勞工占有之氣積應在多少立方公尺以上？",
 ["四立方公尺；零點六立方公尺","二立方公尺；零點三立方公尺","十立方公尺；一立方公尺","六立方公尺；二立方公尺"],"a",
 "第5條：作業室每一勞工占有之氣積應在四立方公尺以上。第6條：氣閘室每一勞工占有之氣積應在零點六立方公尺以上，底面積應在零點三平方公尺以上。",
 "In hyperbaric work, the minimum air volume per worker in the working chamber and in the air lock is:",
 ["4 m³; 0.6 m³","2 m³; 0.3 m³","10 m³; 1 m³","6 m³; 2 m³"],
 "Article 5: at least 4 m³ per worker in the working chamber; Article 6: at least 0.6 m³ per worker and 0.3 m² floor area in the air lock."),

(YC,"第9條",3,"異常氣壓-設備",
 "氣閘室內供勞工減壓用之排氣管，其內徑應在多少公厘以下？",
 ["二十五公厘","五十三公厘","七十五公厘","一百公厘"],"b",
 "第9條：作業室或氣閘室應設置專用之排氣管；氣閘室內供勞工減壓用之排氣管，其內徑在五十三公厘以下。第7條：輸氣管不得通過豎管，接近作業室處應設逆止閥。",
 "The exhaust pipe used for decompressing workers in the air lock shall have an inside diameter no greater than:",
 ["25 mm","53 mm","75 mm","100 mm"],
 "Article 9: dedicated exhaust pipes; the air-lock decompression exhaust pipe inside diameter must be 53 mm or less; Article 7: air supply lines must not pass through the shaft and need a check valve near the chamber."),

(YC,"第10條",3,"異常氣壓-設備",
 "高壓室內作業所用壓力表之刻度盤，應使用單位刻度在每平方公分多少公斤以下者？",
 ["零點一公斤","零點二公斤","零點五公斤","一公斤"],"b",
 "第10條第2項：壓力表之刻度盤，應使用單位刻度在每平方公分零點二公斤以下者。操作場所設於外部時應設壓力表，設於內部時操作勞工應攜帶攜帶式壓力表。",
 "Pressure gauges for hyperbaric work shall have a scale graduation no larger than:",
 ["0.1 kg/cm²","0.2 kg/cm²","0.5 kg/cm²","1 kg/cm²"],
 "Article 10(2): graduations of 0.2 kg/cm² or finer; gauges are required at external valve-operating positions, and operators inside carry portable gauges."),

(YC,"第13條",2,"異常氣壓-設備",
 "雇主使勞工從事高壓室內作業時，應置備何種用具？",
 ["呼吸用防護具、繩索、緊急照明裝置及緊急避難或救出之必要用具","防塵口罩、擴音喇叭、緊急照明裝置及作業室內用之滅火器材","安全帽、反光背心、備用電池及水中作業用之救生衣具","手套、雨衣、可攜式空氣清淨裝置及室內用之暖氣設備"],"a",
 "第13條：應置備呼吸用防護具、繩索、緊急照明裝置及發生緊急狀況時可使勞工迅即避難或救出之必要用具。第12條：氣閘室外應設觀察孔或可掌握室內狀況之設施。",
 "For hyperbaric chamber work the employer shall provide:",
 ["Respirators, ropes, emergency lighting and equipment for rapid evacuation or rescue","Dust masks, loudspeakers, emergency lighting and fire extinguishers for the chamber","Helmets, reflective vests, spare batteries and life jackets for underwater work","Gloves, raincoats, portable air cleaners and space heaters for the working chamber"],
 "Article 13: respiratory protection, ropes, emergency lighting and equipment for rapid evacuation or rescue; Article 12: an observation port or means to monitor inside the air lock."),

(YC,"第14條",3,"異常氣壓-潛水設備",
 "潛水作業使用水面供氣時，備用氣槽內空氣壓力應經常維持在最深潛水深度時壓力之幾倍以上？",
 ["一點二倍","一點五倍","二點五倍","三點零倍"],"b",
 "第14條：應對每一潛水勞工設置調節用氣槽及緊急備用氣槽；備用氣槽內空氣壓力應經常維持在最深潛水深度時壓力之一點五倍以上，內容積應大於 V=(0.03D+4)×60/P。",
 "For surface-supplied diving, the emergency reserve air tank pressure shall be kept at least how many times the pressure at the deepest diving depth?",
 ["1.2","1.5","2.5","3.0"],
 "Article 14: a regulating tank and an emergency reserve tank per diver; reserve tank pressure at least 1.5× the pressure at maximum depth, with volume greater than V = (0.03D + 4) × 60 / P."),

(YC,"第15-1條",3,"異常氣壓-潛水設備",
 "潛水作業深度超過多少公尺且超過免減壓潛水時間限制者，應於現場設置減壓艙？",
 ["十二點二公尺（四十呎）","二十四點四公尺（八十呎）","三十點五公尺（一百呎）","四十五點七公尺（一百五十呎）"],"c",
 "第15條之1：潛水作業深度超過三十點五公尺（一百呎），且超過附表所定免減壓潛水時間限制者，應於現場設置減壓艙。",
 "A decompression chamber must be on site when diving exceeds what depth and the no-decompression time limits?",
 ["12.2 m (40 ft)","24.4 m (80 ft)","30.5 m (100 ft)","45.7 m (150 ft)"],
 "Article 15-1: deeper than 30.5 m (100 ft) and beyond the no-decompression limits in the tables."),

(YC,"第16條",2,"異常氣壓-管理",
 "高壓室內作業，應於每一高壓室內置何種人員？",
 ["高壓室內作業主管","缺氧作業主管","潛水作業主管","施工架組配作業主管"],"a",
 "第16條：應於每一高壓室內置高壓室內作業主管，負責勞工配置及指揮、檢點氣體濃度測定儀器、清點進出勞工、與閥操作勞工連繫維持壓力及加減壓速率、健康異常時採緊急措施。",
 "Each hyperbaric working chamber must have:",
 ["A hyperbaric chamber work supervisor","An oxygen-deficiency supervisor","A diving supervisor","A scaffold assembly supervisor"],
 "Article 16: a hyperbaric chamber work supervisor to assign and direct workers, check gas instruments, count workers, coordinate pressure and compression/decompression rates, and respond to health emergencies."),

(YC,"第18條",3,"異常氣壓-管理",
 "在氣閘室對高壓室內作業實施加壓時，其加壓速率每分鐘應維持在每平方公分多少公斤以下？",
 ["零點三公斤","零點五公斤","零點八公斤","一公斤"],"c",
 "第18條：加壓速率每分鐘應維持在每平方公分零點八公斤以下。第25條：減壓速率亦為每分鐘零點八公斤以下，並依附表於各減壓階停止。",
 "When compressing workers in the air lock, the rate shall not exceed per minute:",
 ["0.3 kg/cm²","0.5 kg/cm²","0.8 kg/cm²","1 kg/cm²"],
 "Article 18: compression rate 0.8 kg/cm² per minute or less; Article 25: decompression also 0.8 kg/cm²/min with stops per the tables."),

(YC,"第20條",3,"異常氣壓-管理",
 "勞工當日從事二次以上高壓室內作業時，為減少體內氮氣殘留，前次減壓終了起應給與之時間稱為何？在此時間內不得從事何種作業？",
 ["中間壓減時間；重體力作業","終工壓減時間；輕度文書作業","加壓間隔時間；輕度搬運作業","工後休息時間；閥類操作作業"],"a",
 "第20條：當日二次以上作業，於前次減壓終了時起算連續給與「中間壓減時間」，且在此時間內不得使其從事重體力作業。第21條：當日終了後之時間稱「終工壓減時間」，同樣不得從事重體力作業。",
 "For a second hyperbaric session on the same day, the interval after the previous decompression is called what, and what work is prohibited during it?",
 ["Intermediate decompression interval; heavy physical work","End-of-work decompression interval; light clerical work","Compression interval time; light manual handling work","Post-shift rest interval; valve operation work"],
 "Article 20: the 'intermediate decompression interval' during which heavy physical work is prohibited; Article 21: the 'end-of-work decompression interval' after the last session, also without heavy work."),

(YC,"第23條",3,"異常氣壓-管理",
 "為防止二氧化碳危害高壓室內作業勞工，應抑制二氧化碳之分壓，使其不超過相當一大氣壓下之濃度多少 ppm？",
 ["一千 ppm","三千 ppm","五千 ppm","一萬 ppm"],"c",
 "第23條：應在作業室及氣閘室採取換氣及其他措施，抑制二氧化碳之分壓，使其不超過相當一大氣壓下之濃度為五千 ppm；換算公式 C=P1×1,000,000/P。",
 "In hyperbaric chambers, CO2 partial pressure shall be kept below the equivalent of what concentration at one atmosphere?",
 ["1,000 ppm","3,000 ppm","5,000 ppm","10,000 ppm"],
 "Article 23: not exceeding 5,000 ppm equivalent at 1 atm, via ventilation and other measures; C = P1 × 1,000,000 / P."),

(YC,"第27條",3,"異常氣壓-管理",
 "氣閘室實施減壓時，氣閘室底面之照明應在多少米燭光以上？溫度在攝氏幾度以下時應供給毛毯？",
 ["二十米燭光；十度","五十米燭光；十五度","一百米燭光；五度","十米燭光；二十度"],"a",
 "第27條：氣閘室底面之照明應在二十米燭光以上；氣閘室溫度在攝氏十度以下時應供給毛毯或其他保暖用具；減壓時間在一小時以上者應供給椅子等休憩用具；事前將當次減壓時間告知勞工。",
 "During decompression in the air lock, the floor illumination shall be at least, and blankets are provided when the temperature is at or below:",
 ["20 lux; 10°C","50 lux; 15°C","100 lux; 5°C","10 lux; 20°C"],
 "Article 27: at least 20 lux; blankets at 10°C or below; seats when decompression exceeds one hour; workers told the decompression time beforehand."),

(YC,"第28條",3,"異常氣壓-紀錄",
 "高壓室內作業之氣閘室壓力自動記錄表紀錄（併同勞工姓名、減壓日期及時間），應保存幾年？",
 ["三年","十年","二十年","十五年"],"d",
 "第28條：應在氣閘室內設置壓力自動記錄表，將每一勞工受減壓之狀況併同姓名、減壓日期及時間每日作成紀錄，並保存十五年。第30條檢點紀錄保存三年。",
 "Automatic pressure recorder logs of each worker's decompression in the air lock shall be kept for:",
 ["3 years","10 years","20 years","15 years"],
 "Article 28: daily records with worker name, date and time, kept 15 years; Article 30 inspection records are kept 3 years."),

(YC,"第30條",3,"異常氣壓-檢點",
 "高壓室內作業之輸氣管、排氣管及通話設備應多久檢點一次？自動警報裝置與輸氣用空氣壓縮機應多久檢點一次？",
 ["每日；每週","每週；每月","每月；每季","每日；每月"],"a",
 "第30條：每日檢點輸氣管、排氣管、通話設備、輸排氣調節閥旋塞、空壓機附屬冷卻裝置、緊急用具；每週檢點自動警報裝置、輸氣用空氣壓縮機；每月檢點壓力表、空氣清淨裝置、電路。紀錄保存三年。",
 "For hyperbaric work, air supply/exhaust pipes and communication equipment are inspected how often, and the automatic alarm and air compressor how often?",
 ["Daily; weekly","Weekly; monthly","Monthly; quarterly","Daily; monthly"],
 "Article 30: daily for supply/exhaust pipes, communication, valves, compressor cooling and emergency tools; weekly for the automatic alarm and compressor; monthly for gauges, air cleaners and circuits; records kept 3 years."),

(YC,"第34條",2,"異常氣壓-防火",
 "實施高壓室內作業前，就沈箱、壓氣潛盾等應有之防火設備及措施，下列何者正確？",
 ["嚴禁煙火，禁止攜帶火柴打火機進入，不得在作業室內從事熔接熔斷或電弧作業","嚴禁煙火，但得攜帶打火機備用，作業室內從事熔接作業時應設置滅火器","得使用一般電燈泡照明，並得在作業室內從事熔斷及電弧作業","作業室內得使用明火暖氣設備，僅需於施工前告知勞工著燃危險性"],"a",
 "第34條：應將高壓下可著燃物質之燃燒危險性告知勞工；使用置有護罩之安全電燈；使用不發生火花或電弧之電路開關；不因高溫引火之暖氣設備；嚴禁煙火並禁止攜帶火源進入；不得在作業室內從事熔接、熔斷或使用煙火、電弧作業。",
 "Regarding fire prevention in caissons or compressed-air shields, which is correct?",
 ["No fire; no matches or lighters brought in; no welding, cutting or arc work inside the chamber","No fire, but lighters may be carried; extinguishers are required when welding inside the chamber","Ordinary light bulbs may be used for lighting, and cutting or arc work is allowed in the chamber","Open-flame heaters are permitted inside once workers are told of the combustion risk under pressure"],
 "Article 34: inform workers of combustion risk under pressure; guarded safety lamps; spark-free switches; safe heaters; strict no-fire rule with ignition sources banned; no welding, cutting, open flame or arc work inside."),

(YC,"第35條",2,"異常氣壓-管理",
 "為防止沈箱之異常沈降致危害高壓室內作業勞工，刃口下方之掘深度不得超過多少公分？",
 ["三十公分","五十公分","一百公分","一百五十公分"],"b",
 "第35條：刃口下方之掘深度不得超過五十公分。第36條：高壓室內作業主管應攜帶手電筒、緊急用信號設備、壓力表及高壓下可測定二氧化碳等濃度之測定儀器。",
 "To prevent abnormal caisson sinking, excavation below the cutting edge shall not exceed:",
 ["30 cm","50 cm","100 cm","150 cm"],
 "Article 35: not more than 50 cm below the cutting edge; Article 36: the supervisor carries a flashlight, emergency signaling device, pressure gauge and a CO2/gas meter usable under pressure."),

(YC,"第37條",3,"異常氣壓-潛水人員",
 "水肺空氣潛水作業之最大深度限制為多少？水面供氣空氣潛水為多少？",
 ["三十九點六公尺（一百三十呎）；五十七點九公尺（一百九十呎）","二十四點四公尺（八十呎）；四十二點七公尺（一百四十呎）","三十點五公尺（一百呎）；六十七點一公尺（二百二十呎）","三十九點六公尺（一百三十呎）；九十一點五公尺（三百呎）"],"a",
 "第37條第2項：水肺空氣潛水最大深度三十九點六公尺（一百三十呎）；水面供氣空氣潛水五十七點九公尺（一百九十呎）；人工調和混合氣潛水最大九十一點五公尺（三百呎），氮氧混合氣不得超過四十二點七公尺（一百四十呎）。",
 "The maximum depth for scuba air diving and for surface-supplied air diving is:",
 ["39.6 m (130 ft); 57.9 m (190 ft)","24.4 m (80 ft); 42.7 m (140 ft)","30.5 m (100 ft); 67.1 m (220 ft)","39.6 m (130 ft); 91.5 m (300 ft)"],
 "Article 37(2): scuba air 39.6 m (130 ft); surface-supplied air 57.9 m (190 ft); mixed gas up to 91.5 m (300 ft), nitrox not beyond 42.7 m (140 ft)."),

(YC,"第37條",3,"異常氣壓-潛水人員",
 "人工調和混合氣潛水，潛水深度達多少公尺至九十一點五公尺，或減壓時間超過多少分鐘者，需使用潛水鐘？",
 ["六十七點一公尺（二百二十呎）；一百二十分鐘","三十點五公尺（一百呎）；六十分鐘","五十七點九公尺（一百九十呎）；九十分鐘","四十二點七公尺（一百四十呎）；一百八十分鐘"],"a",
 "第37條第2項第2款：潛水深度達六十七點一公尺（二百二十呎）至九十一點五公尺（三百呎）或減壓時間超過一百二十分鐘者，需使用潛水鐘。",
 "In mixed-gas diving, a diving bell is required at depths from what to 91.5 m, or when decompression exceeds how long?",
 ["67.1 m (220 ft); 120 minutes","30.5 m (100 ft); 60 minutes","57.9 m (190 ft); 90 minutes","42.7 m (140 ft); 180 minutes"],
 "Article 37(2)(2): from 67.1 m (220 ft) to 91.5 m (300 ft), or when decompression time exceeds 120 minutes, a diving bell must be used."),

(YC,"第37條",2,"異常氣壓-潛水人員",
 "雇主實施潛水作業所僱用之勞工，應具備下列何種資格之一？",
 ["職業潛水職類職業訓練結訓證書、潛水人員技術士證，或國外相當執照經中央主管機關認可","游泳教練證書、水上救生員證照，或經雇主自行辦理之潛水訓練合格證明","船舶駕駛執照、甲級船員適任證書，或漁業從業人員登記證經航政機關備查","潛水醫學體格檢查合格證明、水肺潛水休閒證照，或投保潛水傷害保險之證明文件"],"a",
 "第37條第1項：持有依法設立訓練機構辦理之職業潛水職類職業訓練結訓證書；領有中央主管機關認可之潛水人員技術士證；或於國外受訓領有相當職業潛水執照經報請中央主管機關認可。",
 "Divers employed for diving work must hold one of:",
 ["A commercial diving vocational training certificate, a diver technician license, or an approved equivalent foreign license","A swimming instructor certificate, a water lifesaving certificate, or an in-house diving course certificate from the employer","A vessel master's license, a certificate of competency as a senior crew member, or a fishery worker registration card","A diving medical fitness certificate, a recreational scuba certification, or proof of diving accident insurance cover"],
 "Article 37(1): a commercial diving training certificate from a legally established institution, a diver technician certificate recognized by the central authority, or an equivalent foreign license approved by the central authority."),

(YC,"第37-1條",2,"異常氣壓-潛水管理",
 "雇主使勞工從事潛水作業前，應訂定何種計畫據以實施？",
 ["潛水作業安全衛生計畫","水域環境影響評估計畫","潛水器材採購維護計畫","職業災害善後處理計畫"],"a",
 "第37條之1：應訂定潛水作業安全衛生計畫，內容包括潛水目的、作業環境、作業編組、人員名冊與資格、器具設備、作業時間、正常程序及緊急應變處理程序等。",
 "Before diving work, the employer shall formulate:",
 ["A diving work safety and health plan","A marine environmental impact plan","A diving equipment procurement plan","An occupational accident aftercare plan"],
 "Article 37-1: a diving safety and health plan covering purpose, environment, team organization, personnel roster and qualifications, equipment, work time, normal procedures and emergency response."),

(YC,"第38條",2,"異常氣壓-潛水管理",
 "潛水作業現場應設置幾名救援潛水員？其應如何待命？",
 ["一名，全程穿著潛水裝備待命下水","二名，於岸上待命必要時著裝下水","一名，於船上休息待接獲通知後著裝","一名，由連絡員兼任並於岸上待命"],"a",
 "第38條：作業現場應設置救援潛水員一名，該救援潛水員應於潛水作業全程穿著潛水裝備（水面供氣之頭盔及配重帶除外），待命下水。",
 "How many standby rescue divers are required on site, and how do they stand by?",
 ["One, fully dressed in dive gear throughout the operation, ready to enter the water","Two, waiting on shore and dressing in dive gear only when a rescue is actually needed","One, resting on the boat and dressing in dive gear after being notified of an emergency","One, whose duties are covered by the tender, standing by on shore in ordinary clothing"],
 "Article 38: one standby diver wearing dive equipment (except surface-supply helmet and weight belt) for the entire operation, ready to dive."),

(YC,"第39條",3,"異常氣壓-潛水管理",
 "潛水作業主管之設備檢點與作業檢點紀錄應保存幾年？潛水日誌應保存幾年？",
 ["五年；十五年","三年；五年","一年；三年","十年；二十年"],"a",
 "第39條：潛水作業主管應確認潛水計畫、現場技術指揮、確認連繫方法、待命船隻及後送程序、確認工作手冊、實施設備與作業檢點（紀錄保存五年）、填具潛水日誌記錄每位潛水人員作業情形及減壓時間（保存十五年）。",
 "Diving supervisor equipment/work inspection records are kept how long, and the diving log how long?",
 ["5 years; 15 years","3 years; 5 years","1 year; 3 years","10 years; 20 years"],
 "Article 39: the diving supervisor confirms the plan, directs on site, confirms communications, standby vessel and evacuation, work handbooks, inspects equipment and personnel (records 5 years), and keeps a diving log with decompression times (15 years)."),

(YC,"第39條",3,"異常氣壓-潛水管理",
 "使用水面供氣設備潛水作業期間，應每小時檢查何事？",
 ["風向及調整空壓機進氣口位置","水溫及調整潛水員之停留深度","潮流及更換供氣管之過濾濾芯","船隻油量及補充緊急備用氣瓶"],"a",
 "第39條第3項第1款：使用水面供氣設備者，應檢點潛水器、供氣管、信號索、安全索及壓力調節器，並於作業期間每小時檢查風向及調整空壓機進氣口位置。",
 "During surface-supplied diving, what must be checked every hour?",
 ["Wind direction, adjusting the compressor air intake position","Water temperature, adjusting the diver's stop depth","Tidal current, replacing the air hose filter element","Boat fuel level, refilling the emergency reserve cylinder"],
 "Article 39(3)(1): inspect the diving apparatus, air hose, signal line, safety line and regulator, and check wind direction hourly to adjust the compressor intake."),

(YC,"第40條",2,"異常氣壓-潛水管理",
 "雇主使勞工從事潛水作業前應公告之資料，包括下列何者？",
 ["減壓艙所在地、潛水病醫療機構及醫師、海陸空運輸資訊、國軍或急難救援單位","工程承攬金額、施工進度表及工期、材料供應廠商資訊、監造單位聯絡方式","潛水員薪資給付標準、勞保投保級距、加班時數統計、退休金提繳紀錄","氣瓶充填廠商名稱、潛水裝備採購價格、船舶租賃合約、保險理賠流程"],"a",
 "第40條：應備置必要之急救藥品及器材，並公告減壓艙所在地、潛水病醫療機構及醫師、海陸空運輸有關資訊、國軍或其他急難救援單位。",
 "Before diving work, the employer shall post information including:",
 ["Location of the decompression chamber, diving-medicine facilities and doctors, sea/land/air transport, military or rescue units","Contract value of the works, the construction schedule and duration, material suppliers, and the supervising firm's contacts","Divers' wage rates, labor insurance grades, overtime hour statistics, and pension contribution records for each diver","Cylinder filling contractors, purchase prices of diving equipment, vessel charter contracts, and insurance claim procedures"],
 "Article 40: first-aid supplies plus posted information on the chamber location, hyperbaric medical facilities and physicians, transport options, and military or other rescue units."),

(YC,"第43條",3,"異常氣壓-減壓",
 "使用水肺或水面供氣空氣潛水，正常上浮速率不得超過每分鐘多少公尺？潛水紀錄應保存幾年？",
 ["九點一公尺（三十呎）；五年","十八點三公尺（六十呎）；三年","三點零公尺（十呎）；十年","十五點二公尺（五十呎）；一年"],"a",
 "第43條：正常上浮速率不得超過每分鐘九點一公尺（三十呎），潛水程序依深度、滯底時間、減壓站停留時間、總上浮時間、重複潛水組群等從事，不得超過附表規定，並每次作成紀錄保存五年。",
 "For scuba or surface-supplied air diving, the normal ascent rate shall not exceed, and dive records are kept for:",
 ["9.1 m (30 ft) per minute; 5 years","18.3 m (60 ft) per minute; 3 years","3 m (10 ft) per minute; 10 years","15.2 m (50 ft) per minute; 1 year"],
 "Article 43: ascent not faster than 9.1 m (30 ft) per minute, following the tables for depth, bottom time, stops, total ascent time and repetitive groups; records kept 5 years."),

(YC,"第44條",3,"異常氣壓-減壓",
 "水面使用氧氣減壓時，自十二點二公尺減壓站上浮至水面、卸裝、進入減壓艙並加壓至十五點二公尺深度，此水面間歇總時間不得超過幾分鐘？",
 ["三分鐘","五分鐘","十分鐘","十五分鐘"],"b",
 "第44條：於離開十二點二公尺（四十呎）減壓站開始，以每分鐘十二點二公尺速率上浮至水面、卸裝、進入減壓艙，以每分鐘三十點五公尺速率加壓至艙內十五點二公尺（五十呎），正常水面間歇總時間不得超過五分鐘；每一氧氣呼吸單元為呼吸純氧三十分鐘及呼吸空氣休息五分鐘。",
 "For surface oxygen decompression, the total surface interval from leaving the 12.2 m stop to reaching 15.2 m in the chamber shall not exceed:",
 ["3 minutes","5 minutes","10 minutes","15 minutes"],
 "Article 44: ascend from the 12.2 m (40 ft) stop at 12.2 m/min, undress, enter the chamber and pressurize at 30.5 m/min to 15.2 m (50 ft); total surface interval not over 5 minutes; each oxygen unit is 30 min oxygen plus 5 min air break."),

(YC,"第45-1條",3,"異常氣壓-減壓",
 "使用氮氧人工調和混合氣潛水時，其氧氣濃度不得超過百分之多少？氧分壓不得超過多少絕對大氣壓力？",
 ["百分之四十；一點四","百分之二十一；一","百分之五十；二","百分之三十；一點六"],"a",
 "第45條之1：使用氮氧人工調和混合氣供氣時，應參照相當空氣潛水深度依減壓時程作業，其氧氣濃度不得超過百分之四十，且氧分壓不得超過一點四絕對大氣壓力。",
 "For nitrox diving, oxygen concentration shall not exceed, and oxygen partial pressure shall not exceed:",
 ["40%; 1.4 ATA","21%; 1 ATA","50%; 2 ATA","30%; 1.6 ATA"],
 "Article 45-1: follow the equivalent air depth tables; oxygen not over 40% and oxygen partial pressure not over 1.4 ATA."),

(YC,"第48條",3,"異常氣壓-緊急",
 "因緊急事故增加上浮速率或縮短減壓站停留後，進入減壓艙再加壓時，加壓速率不得超過每分鐘多少公尺？",
 ["十二點二公尺（四十呎）","二十四點四公尺（八十呎）","三十點五公尺（一百呎）","九點一公尺（三十呎）"],"b",
 "第48條：緊急救出後，有症狀者立即送醫；無症狀者依附表四之三處置；進入減壓艙再加壓時，加壓速率依潛水人員可容忍範圍為之，但不得超過每分鐘二十四點四公尺（八十呎）。",
 "After an emergency rapid ascent, recompression in the chamber shall not exceed a rate of:",
 ["12.2 m (40 ft) per minute","24.4 m (80 ft) per minute","30.5 m (100 ft) per minute","9.1 m (30 ft) per minute"],
 "Article 48: symptomatic divers go to hospital; asymptomatic ones follow the table; recompression at a tolerable rate not exceeding 24.4 m (80 ft) per minute."),

(YC,"第50條",3,"異常氣壓-供氣",
 "使用水面供氣設備供氣時，應於潛水深度壓力下對每一潛水勞工每分鐘供給多少公升以上？",
 ["三十公升","六十公升","一百公升","一百五十公升"],"b",
 "第50條：使用水面供氣設備供氣時，應於潛水深度壓力下，對每一潛水作業勞工每分鐘供給六十公升以上。",
 "Surface-supplied air must deliver to each diver, at depth pressure, at least how many liters per minute?",
 ["30 L","60 L","100 L","150 L"],
 "Article 50: at least 60 liters per minute per diver at the pressure of the diving depth."),

(YC,"第52條",3,"異常氣壓-供氣",
 "使用充填壓力超過每平方公分多少公斤之氣瓶供氣時，應使用二段以上減壓方式的壓力調節器？",
 ["五公斤","十公斤","二十公斤","五十公斤"],"b",
 "第52條：使用充填壓力超過每平方公分十公斤之氣瓶供氣時，應使用有二段以上減壓方式的壓力調節器。第51條：單人潛水需有繩索繫著，二人共潛需在互相視線可及之處。",
 "Cylinders filled above what pressure require a two-stage (or more) regulator?",
 ["5 kg/cm²","10 kg/cm²","20 kg/cm²","50 kg/cm²"],
 "Article 52: above 10 kg/cm², a regulator with two or more stages; Article 51: solo divers must be tethered and buddy divers within sight of each other."),

(YC,"第54條",3,"異常氣壓-檢點",
 "充填氧氣、空氣、混合氣之水肺氣瓶及高壓氣瓶，每幾年應送合格檢驗單位以工作壓力之幾倍實施水壓測試？",
 ["每五年；一點五倍","每年；一倍","每三年；二倍","每十年；一點二倍"],"a",
 "第54條第5款：充填氧氣、空氣、混合氣之水肺氣瓶、緊急備用氣瓶、高壓氣瓶每五年應送至合格檢驗單位，以工作壓力之一點五倍實施水壓測試。檢點紀錄保存五年。",
 "Scuba and high-pressure cylinders must be hydrostatically tested every how many years, at how many times the working pressure?",
 ["Every 5 years; 1.5 times","Every year; 1 time","Every 3 years; 2 times","Every 10 years; 1.2 times"],
 "Article 54(5): every 5 years at 1.5× working pressure by a qualified testing body; inspection records kept 5 years."),

(YC,"第55條",3,"異常氣壓-供氣",
 "潛水作業之呼吸供氣不得使用純氧；其供氣氣體標準中一氧化碳應低於多少 ppm？二氧化碳應低於多少 ppm？",
 ["十 ppm；一千 ppm","五十 ppm；五千 ppm","一 ppm；一百 ppm","一百 ppm；一萬 ppm"],"a",
 "第55條：呼吸供氣不得使用純氧；換算一大氣壓下水氣低於六十七 ppm、一氧化碳低於十 ppm、二氧化碳低於一千 ppm、油霧低於每立方公尺五毫克。",
 "Diving breathing air must not be pure oxygen; CO must be below, and CO2 below:",
 ["10 ppm; 1,000 ppm","50 ppm; 5,000 ppm","1 ppm; 100 ppm","100 ppm; 10,000 ppm"],
 "Article 55: no pure oxygen; at 1 atm equivalent, water vapor below 67 ppm, CO below 10 ppm, CO2 below 1,000 ppm, oil mist below 5 mg/m³."),

(YC,"第56條",3,"異常氣壓-連絡員",
 "使用水面供氣設備潛水時應至少置連絡員一名；潛水勞工超過一人者，每增加幾人再置連絡員一名？",
 ["一人","二人","三人","五人"],"b",
 "第56條：應至少置連絡員一名，潛水作業勞工超過一人者，每增加二人再置連絡員一名，負責與潛水勞工連繫指導下潛上浮、與供氣設備操作勞工連繫、異常時立即連繫、確認頭盔式潛水器正確著裝。",
 "Surface-supplied diving requires at least one tender; for more than one diver, one additional tender per how many additional divers?",
 ["1","2","3","5"],
 "Article 56: at least one tender; one more per two additional divers, to guide descent/ascent, liaise with the air supply operator, respond to faults, and check helmet dress."),

(YC,"第57條",2,"異常氣壓-裝備",
 "使用水肺從事潛水作業時，除攜帶水中計時器、深度表及潛水刀外，並應使勞工著用何物？",
 ["救生衣","安全帽","反光衣","工作手套"],"a",
 "第57條：水面供氣潛水應攜帶緊急用水肺、信號索、水中計時器、深度表及潛水刀（可通話者得免信號索）；使用水肺潛水應攜帶水中計時器、深度表及潛水刀，並應著用救生衣。",
 "Scuba divers must carry a dive timer, depth gauge and dive knife, and also wear:",
 ["A life jacket","A safety helmet","A reflective vest","Work gloves"],
 "Article 57: surface-supplied divers carry a bailout scuba, signal line, timer, depth gauge and knife; scuba divers carry timer, depth gauge and knife and wear a life jacket."),

(YC,"第64條",2,"異常氣壓-再壓室",
 "使用再壓室時，下列何者正確？",
 ["不得使用純氧加壓；應持續監視並記錄每次加減壓狀況","得使用純氧加壓以縮短療程；每週彙總記錄一次即可","使用前免予檢點輸排氣設備；加減壓狀況由艙內人員事後回報","主室與副室間之門應保持開啟；各室壓力得維持不同"],"a",
 "第64條：當日使用前檢點輸排氣設備、通話設備及警報裝置；不得使用純氧加壓；除進出必要外應關閉主室與副室間之門且使各室壓力相等；應持續監視加減壓狀況並記錄每次狀況。",
 "When using a recompression chamber, which is correct?",
 ["Never pressurize with pure oxygen; continuously monitor and record every compression and decompression","Pure oxygen may be used to shorten treatment; a weekly summary record of the sessions is sufficient","Pre-use checks of the supply and exhaust equipment may be skipped; occupants report pressures afterwards","Keep the door between the main and auxiliary chambers open; the two chambers may hold different pressures"],
 "Article 64: daily pre-use checks; no pure oxygen pressurization; keep the inner door closed except when passing with pressures equalized; monitor continuously and record each session."),

(YC,"第73條",2,"異常氣壓-再壓室",
 "再壓室及減壓艙內部，下列何者為正確規定？",
 ["內部不得設置開關及插座等電路連接器，電路不得有分歧","內部得設置一般插座供器具使用，電路應加裝漏電斷路器","內部得使用明火式暖氣設備，照明器具得以延長線供電","照明器具得任意安裝於側壁，地面床具得使用一般木質材料"],"a",
 "第73、75、89、91條：再壓室及減壓艙內部不得設置開關及插座等電路連接器；內部電路不得有分歧；電氣機械器具不得產生火花電弧；照明器具應直接附置於頂上、可耐最高使用壓力、具金屬護罩；地面床具應為不燃性材料。",
 "Inside recompression and decompression chambers, which is correct?",
 ["No switches, sockets or other electrical connectors inside, and no branched circuits","Ordinary sockets may be fitted inside, provided the circuits have earth-leakage breakers","Open-flame heaters may be used inside, and lighting may be powered by extension cords","Lighting may be mounted anywhere on the side walls, and floors may use ordinary timber"],
 "Articles 73/75/89/91: no switches or sockets inside; no branched circuits; no spark- or arc-producing electrical equipment; ceiling-mounted pressure-rated lights with metal guards; non-combustible floors and furnishings."),

(YC,"第86條",3,"異常氣壓-減壓艙",
 "減壓艙主供氣系統之氣量應足夠供減壓艙加壓至多少公尺深度幾次並安全上升至水面？",
 ["五十公尺；兩次","三十公尺；一次","一百公尺；三次","二十公尺；五次"],"a",
 "第86條：主供氣系統應足夠供減壓艙加壓至五十公尺深度兩次並安全上升至水面全程供氣；副供氣系統足夠加壓至五十公尺一次及安全上升之一小時供氣；並應有呼吸用專用空壓機及過濾器、純氧供氣瓶組。",
 "A decompression chamber's main air supply must suffice to pressurize the chamber to what depth how many times and return safely to the surface?",
 ["50 m; twice","30 m; once","100 m; three times","20 m; five times"],
 "Article 86: main system: two pressurizations to 50 m plus full ascent; backup: one pressurization to 50 m plus one hour of ascent supply; plus a dedicated breathing-air compressor with filter and pure-oxygen cylinders."),

# ---------- 危害性化學品標示及通識規則 ----------
(HC,"第2條",1,"化學品標示-定義",
 "危害性化學品標示及通識規則所稱「危害性化學品」，其分類依據為何？",
 ["國家標準 CNS 15030","國家標準 CNS 4750","國家標準 CNS 9328","國際標準 ISO 9001"],"a",
 "第2條：危險物指符合國家標準CNS 15030分類具有物理性危害者；有害物指符合CNS 15030分類具有健康危害者。",
 "'Hazardous chemicals' under the Labeling and Hazard Communication Rules are classified according to:",
 ["National standard CNS 15030","National standard CNS 4750","National standard CNS 9328","International standard ISO 9001"],
 "Article 2: dangerous substances have physical hazards and harmful substances have health hazards, both classified per CNS 15030 (the GHS-based standard)."),

(HC,"第4條",2,"化學品標示-適用",
 "下列何者不適用危害性化學品標示及通識規則？",
 ["食品、飲料、藥品、醫療器材、化粧品","工業用有機溶劑、稀釋劑、清潔劑、接著劑","工業用強酸、強鹼、氧化劑、腐蝕性藥品","工業用可燃性氣體、液化石油氣、乙炔"],"a",
 "第4條不適用：事業廢棄物、菸草或菸草製品、食品飲料藥品醫療器材化粧品、製成品、非工業用途之一般民生消費商品、滅火器、反應槽或製程中正在反應之中間產物、其他指定者。",
 "Which is NOT covered by the Hazardous Chemicals Labeling and Communication Rules?",
 ["Food, beverages, pharmaceuticals, medical devices and cosmetics","Industrial organic solvents, thinners, detergents and adhesives","Industrial strong acids, alkalis, oxidizers and corrosives","Industrial flammable gases, liquefied petroleum gas and acetylene"],
 "Article 4 exemptions: industrial waste; tobacco products; food, beverages, drugs, medical devices, cosmetics; articles (manufactured items); non-industrial consumer goods; fire extinguishers; intermediates reacting in process vessels; others designated."),

(HC,"第3條",2,"化學品標示-定義",
 "規則所稱「製成品」，其特徵為何？",
 ["已形成特定形狀或設計，最終用途決定於該形狀，且正常使用下不會釋放危害性化學品","已完成包裝並標示之化學品，最終用途由使用者決定，且運送過程中不會外洩","經檢驗合格之進口化學品，最終用途載明於報單，且在正常倉儲下不會變質","由二種以上成分組成之混合物，其危害性依含量最高者認定，且不需另作測試"],"a",
 "第3條第1款：製成品指在製造過程中已形成特定形狀或依特定設計，其最終用途全部或部分決定於該特定形狀或設計，且在正常使用狀況下不會釋放出危害性化學品之物品。",
 "An 'article' (manufactured item) under the Rules is characterized by:",
 ["A specific shape or design that determines its end use, and no release of hazardous chemicals in normal use","A packaged and labeled chemical whose end use is chosen by the buyer, with no leakage during transport","An imported chemical that has passed inspection, with its end use stated on the customs declaration","A mixture of two or more ingredients whose hazard follows its largest ingredient, needing no testing"],
 "Article 3(1): an article has a specific shape or design that wholly or partly determines its end-use function and does not release hazardous chemicals under normal use."),

(HC,"第5條",2,"化學品標示-標示",
 "裝有危害性化學品之容器，應標示之事項不包括下列何者？",
 ["危害圖式","危害成分","危害防範措施","產品售價"],"d",
 "第5條：應標示危害圖式，及名稱、危害成分、警示語、危害警告訊息、危害防範措施、製造者輸入者或供應者之名稱地址及電話；文字以中文為主，必要時輔以外文。",
 "Which is NOT a required element on a hazardous chemical container label?",
 ["Hazard pictogram","Hazardous ingredients","Precautionary measures","Product selling price"],
 "Article 5: pictogram; name; hazardous ingredients; signal word; hazard statements; precautionary statements; manufacturer/importer/supplier name, address and phone; Chinese text, with foreign language where needed."),

(HC,"第5條",3,"化學品標示-標示",
 "容器之容積在多少毫升以下者，得僅標示名稱、危害圖式及警示語？",
 ["五十毫升","一百毫升","二百五十毫升","五百毫升"],"b",
 "第5條第3項：容器之容積在一百毫升以下者，得僅標示名稱、危害圖式及警示語。",
 "Containers of what volume or less may be labeled with only the name, pictogram and signal word?",
 ["50 mL","100 mL","250 mL","500 mL"],
 "Article 5(3): containers of 100 mL or less may show only the name, hazard pictogram and signal word."),

(HC,"第7條",2,"化學品標示-圖式",
 "危害圖式之形狀及顏色規定為何？",
 ["直立四十五度角之正方形（菱形），符號黑色、背景白色、紅框","直立四十五度角之正方形（菱形），符號白色、背景紅色、黑框","圓形，符號黑色、背景黃色、外緣黑框且需加註警示語","正三角形，符號黑色、背景黃色、紅框且大小固定為十公分"],"a",
 "第7條：危害圖式形狀為直立四十五度角之正方形，大小需能辨識清楚；圖式符號應使用黑色，背景為白色，圖式之紅框有足夠警示作用之寬度。",
 "What are the shape and colors of a hazard pictogram?",
 ["A square set at 45° (diamond) with black symbol, white background and red border","A square set at 45° (diamond) with white symbol, red background and black border","A circle with a black symbol on a yellow background, a black rim and a signal word","An equilateral triangle, black symbol on yellow, red border and a fixed 10 cm size"],
 "Article 7: a square rotated 45°, clearly legible, with a black symbol on a white background inside a sufficiently wide red frame."),

(HC,"第8條",3,"化學品標示-免標示",
 "下列何種容器得免標示？",
 ["勞工使用之可攜帶容器，其化學品取自有標示之容器，且僅供裝入之勞工當班立即使用","勞工使用之可攜帶容器，其化學品取自有標示之容器，且供全體勞工於當月內使用","容積在五百毫升以下之小型容器，且已於外箱標示名稱者，得免除全部標示事項","所有玻璃製容器，因材質透明可直接辨識內容物，且置於實驗室內者"],"a",
 "第8條免標示：外部容器已標示僅供內襯且不再取出之內部容器；內部容器已標示且由外部可見之外部容器；勞工使用之可攜帶容器取自有標示容器且僅供裝入之勞工當班立即使用；取自有標示容器供實驗室自行實驗研究之用。",
 "Which container may be exempt from labeling?",
 ["A portable container filled from a labeled container for immediate use by that worker during the shift","A portable container filled from a labeled container for use by all workers at any time that month","A small container of 500 mL or less whose outer carton already shows the name of the chemical","Any glass container, since the transparent material lets the contents be identified directly"],
 "Article 8 exemptions: inner liners not removed when the outer container is labeled; outer containers through which an inner label is visible; portable containers filled from labeled containers for the filling worker's immediate use that shift; lab containers for the lab's own research."),

(HC,"第9條",3,"化學品標示-公告板",
 "裝有危害性化學品之導管或配管系統，得以何種方式代替容器標示？",
 ["設置公告板，或掛使用牌、漆規定識別顏色及記號","於作業場所入口設置警戒線，或由現場主管每日口頭告知","設置公告板，或於管線兩端各貼一張小型標籤代替","檢附安全資料表送勞動檢查機構備查，即得免除標示"],"a",
 "第9條：裝同一種化學品之數個容器置於同一處所、導管或配管系統、反應器蒸餾塔等化學設備、冷卻攪拌壓縮裝置、輸送裝置，得於明顯處設置公告板代替容器標示；屬管系者得掛使用牌或漆有規定識別顏色及記號替代。",
 "For pipelines and piping systems carrying hazardous chemicals, container labels may be replaced by:",
 ["A posted notice board, or hanging usage tags or painting the prescribed identification colors and marks","A warning line at the entrance to the work area, or a daily verbal briefing given by the site supervisor","A posted notice board, or one small sticker attached at each end of the pipeline in place of the labels","Filing the safety data sheet with the labor inspection agency, which then exempts the piping from labeling"],
 "Article 9: notice boards may replace labels for grouped containers, pipelines, chemical equipment (reactors, columns), cooling/mixing/compression equipment and conveyors; piping may use tags or prescribed color codes."),

(HC,"第11條、第13條",2,"化學品標示-供應者",
 "製造者、輸入者或供應者提供危害性化學品與事業單位前，應辦理何事？",
 ["於容器上予以標示，並提供安全資料表","於容器上予以標示，並附送商品保證書","開立統一發票並檢附運送清單即可","以口頭說明危害性，並由買方簽收確認"],"a",
 "第11條：提供危害性化學品與事業單位或自營作業者前，應於容器上予以標示，準用第5至9條規定。第13條：並應提供安全資料表，混合物應依混合後之危害性製作。",
 "Before supplying hazardous chemicals to an enterprise, manufacturers, importers or suppliers shall:",
 ["Label the container and provide a safety data sheet","Label the container and enclose a product warranty","Issue a uniform invoice together with a delivery list","Explain the hazards verbally and have the buyer sign"],
 "Article 11: label containers per Articles 5–9; Article 13: provide an SDS, prepared for the mixture's overall hazards."),

(HC,"第12條",2,"化學品標示-SDS",
 "雇主對含有危害性化學品之每一化學品，應提供勞工何種文件？其文字規定為何？",
 ["安全資料表；以中文為主，必要時輔以勞工能瞭解之外文","安全資料表；以英文為主，必要時輔以中文摘要說明","危害物質清單；以中文為主，經勞工簽名後存查即可","產品說明書；得使用任意語言，由供應商自行決定"],"a",
 "第12條：雇主對含有危害性化學品或符合附表三規定之每一化學品，應依附表四提供勞工安全資料表；所用文字以中文為主，必要時並輔以作業勞工所能瞭解之外文。",
 "For each hazardous chemical, the employer shall provide workers with what document, in which language?",
 ["A safety data sheet; mainly Chinese, supplemented by a language workers understand where needed","A safety data sheet; mainly in English, supplemented by a Chinese summary where necessary","A hazardous substance inventory; mainly Chinese, kept on file once workers have signed it","A product manual; in any language the supplier chooses, entirely at its own discretion"],
 "Article 12: an SDS per Annex 4 for each hazardous chemical, mainly in Chinese with a foreign language workers understand where necessary."),

(HC,"第15條",3,"化學品標示-SDS",
 "安全資料表至少應每幾年檢討一次？其更新紀錄應保存幾年？",
 ["三年；三年","一年；一年","五年；五年","二年；十年"],"a",
 "第15條：製造者、輸入者、供應者或雇主應依實際狀況檢討安全資料表內容正確性，適時更新，並至少每三年檢討一次；更新之內容、日期、版次等紀錄應保存三年。",
 "SDSs must be reviewed at least every how many years, and update records kept how long?",
 ["3 years; 3 years","1 year; 1 year","5 years; 5 years","2 years; 10 years"],
 "Article 15: review accuracy and update as needed, at least every three years; keep update records (content, date, version) for three years."),

(HC,"第17條",2,"化學品標示-通識",
 "雇主為使勞工知悉危害性化學品之危害資訊，應採取之措施不包括下列何者？",
 ["訂定危害通識計畫並執行，紀錄保存三年","製作危害性化學品清單","將安全資料表置於工作場所易取得之處","將安全資料表鎖在主管辦公室"],"d",
 "第17條：依實際狀況訂定危害通識計畫並執行（紀錄保存三年）；製作危害性化學品清單；將安全資料表置於工作場所易取得之處；使勞工接受製造處置使用危害性化學品之教育訓練；其他必要措施。",
 "Which is NOT a required hazard communication measure?",
 ["A hazard communication program, implemented with 3-year records","A hazardous chemicals inventory","SDSs placed where workers can easily access them","Locking SDSs in the manager's office"],
 "Article 17: a hazard communication program (records 3 years), a chemical inventory, SDSs readily accessible in the workplace, training per the Training Rules, and other necessary measures."),

(HC,"第17條",3,"化學品標示-通識",
 "危害通識計畫應包含哪些必要項目？",
 ["危害性化學品清單、安全資料表、標示、危害通識教育訓練之擬訂執行紀錄及修正","危害性化學品清單、進貨發票、庫存盤點表、供應商評鑑之擬訂執行紀錄及修正","人員名冊、健康檢查紀錄、勞工保險資料、出勤紀錄之擬訂執行紀錄及修正","財務報表、採購預算、成本分析、年度營運計畫之擬訂執行紀錄及修正"],"a",
 "第17條第2項：危害通識計畫應含危害性化學品清單、安全資料表、標示、危害通識教育訓練等必要項目之擬訂、執行、紀錄及修正措施。",
 "A hazard communication program must include:",
 ["Planning, implementation, records and revision of the chemical inventory, SDSs, labeling and hazard communication training","Planning, implementation, records and revision of the chemical inventory, purchase invoices, stock counts and supplier audits","Planning, implementation, records and revision of personnel rosters, health check records, insurance files and attendance","Planning, implementation, records and revision of financial statements, purchase budgets, cost analyses and business plans"],
 "Article 17(2): the program covers the chemical inventory, SDSs, labels and training, with planning, implementation, records and revisions."),

(HC,"第18條",3,"化學品標示-營業秘密",
 "製造者、輸入者或供應者為保護商品營業秘密，欲保留揭示安全資料表中之危害成分名稱等，應向何機關申請核定？",
 ["中央主管機關","地方政府","勞動檢查機構","經濟部"],"a",
 "第18條：為維護國家安全或商品營業秘密，保留揭示成分名稱、CAS號碼、含量或供應者名稱時，應檢附證明、對策、經濟利益評估、危害性分類說明等文件，向中央主管機關申請核定；補正以二次為限，每次三十日內。",
 "To withhold trade-secret ingredient information from an SDS, the manufacturer, importer or supplier must apply for approval to:",
 ["The central competent authority","The local government","The labor inspection agency","The Ministry of Economic Affairs"],
 "Article 18: apply to the central competent authority with proof of national security or trade secret, protective measures, economic impact assessment and hazard classification; corrections within 30 days, at most twice."),

(HC,"第18-1條",3,"化學品標示-營業秘密",
 "下列何種危害性化學品成分，不得申請保留安全資料表內容之揭示？",
 ["致癌物質、生殖毒性物質、勞工作業場所容許暴露標準所列之化學物質","一般有機溶劑、稀釋劑、勞工作業場所未設容許暴露標準之化學物質","顏料、染料及色母粒等，經中央主管機關公告為低危害之化學物質","黏著劑、樹脂單體，及未列入 CNS 15030 分類之化學物質"],"a",
 "第18條之1：勞工作業場所容許暴露標準所列之化學物質；CNS 15030分類之急毒性物質第一至三級、腐蝕或刺激皮膚第一級、嚴重損傷眼睛第一級、呼吸道或皮膚致敏物質、生殖細胞致突變性物質、致癌物質、生殖毒性物質、特定標的器官毒性單一及重複暴露第一級、吸入性危害第一級，不得申請保留揭示。",
 "Which ingredients can NOT be withheld from SDS disclosure as trade secrets?",
 ["Carcinogens, reproductive toxicants and substances listed in the workplace exposure standards","Common organic solvents, thinners and substances with no workplace exposure standard set","Pigments, dyes and colour masterbatches announced by the central authority as low hazard","Adhesives, resin monomers and substances not classified under the CNS 15030 standard"],
 "Article 18-1: substances in the permissible exposure standards; CNS 15030 acute toxicity categories 1–3, skin corrosion/irritation cat. 1, serious eye damage cat. 1, respiratory/skin sensitizers, germ cell mutagens, carcinogens, reproductive toxicants, STOT single/repeated cat. 1, aspiration hazard cat. 1."),

(HC,"第19條",2,"化學品標示-揭示",
 "主管機關、勞動檢查機構或醫師、緊急應變人員因緊急醫療及搶救需要，要求提供安全資料表及其保留揭示之資訊時，製造者、供應者或事業單位得否拒絕？",
 ["不得拒絕；取得營業秘密者有保密義務","得予拒絕；除非另取得法院核發之搜索票","僅提供部分內容；保留揭示部分仍得拒絕","應於收費後提供；並得要求簽訂保密契約"],"a",
 "第19條：主管機關、勞動檢查機構為執行業務或醫師、緊急應變人員為緊急醫療及搶救之需要，得要求提供安全資料表及其保留揭示之資訊，不得拒絕；取得商品營業秘密者有保密之義務。",
 "When authorities, inspectors, physicians or emergency responders request an SDS and withheld information for emergency care, may the supplier or enterprise refuse?",
 ["No; recipients of trade secrets must keep them confidential","Yes, unless the requester produces a court search warrant","Only partial content; withheld items may still be refused","Only after a fee is paid and a confidentiality contract signed"],
 "Article 19: they must not refuse; anyone who obtains trade secrets this way has a duty of confidentiality."),

(HC,"第23條",3,"化學品標示-施行",
 "民國115年8月26日修正發布之第5條附表一及第12條附表四，自何時施行？",
 ["一百十八年一月一日","一百十五年九月一日","一百十六年一月一日","一百十七年七月一日"],"a",
 "第23條：一百十五年八月二十六日修正發布之第五條附表一、第十二條附表四，自一百十八年一月一日施行；其餘修正條文自發布日施行。",
 "The 2026 (ROC 115) amendments to Annex 1 of Article 5 and Annex 4 of Article 12 take effect on:",
 ["1 January 2029 (ROC 118)","1 September 2026 (ROC 115)","1 January 2027 (ROC 116)","1 July 2028 (ROC 117)"],
 "Article 23: the Annex 1 and Annex 4 amendments promulgated on 26 August ROC 115 take effect on 1 January ROC 118 (2029); other amendments took effect on promulgation."),

(HC,"第6條",3,"化學品標示-混合物",
 "混合物未作整體測試者，其健康危害性應如何認定？",
 ["除有科學資料佐證外，依 CNS 15030 之混合物分類標準","一律視為無害，除非勞動檢查機構另行認定其具健康危害性","依成分中含量最高者之危害性認定，其餘成分得免予分類","由雇主自行決定分類結果，並報請勞動檢查機構備查即可"],"a",
 "第6條：混合物已作整體測試者依整體測試結果；未作整體測試者，其健康危害性除有科學資料佐證外，應依CNS 15030分類之混合物分類標準；燃燒、爆炸及反應性等物理性危害使用有科學根據之資料評估。",
 "How is the health hazard of an untested mixture determined?",
 ["Per the CNS 15030 mixture classification criteria, unless scientific data show otherwise","Always treated as harmless unless the labor inspection agency determines otherwise","By the hazard of the ingredient with the highest content, ignoring the other ingredients","At the employer's discretion, with the classification filed with the labor inspection agency"],
 "Article 6: tested mixtures use test results; untested ones follow CNS 15030 mixture classification for health hazards unless scientific evidence exists; physical hazards are assessed with scientifically based data."),

(HC,"第10條",2,"化學品標示-運輸",
 "裝有危害性化學品之容器於運輸時已依交通法規設置標示者，該容器於工作場所內運輸時是否須再依附表一標示？",
 ["得免再標示","仍須重新標示","須同時貼兩種標示","須移除交通標示"],"a",
 "第10條：於運輸時已依交通法規有關運輸之規定設置標示者，該容器於工作場所內運輸時得免再依附表一標示；但勞工從事卸放、搬運、處置或使用時，雇主仍應依本規則辦理。",
 "If a container already bears transport labeling under traffic regulations, must it be relabeled per Annex 1 while transported within the workplace?",
 ["No, it is exempt during in-plant transport","Yes, it must be relabeled","Both labels are required","The transport label must be removed"],
 "Article 10: exempt during transport within the workplace, but once workers unload, handle, process or use the chemical the Rules apply."),
]
