# -*- coding: utf-8 -*-
# 第 11 批（N2）：粉塵危害預防標準（103/6/25）與危害性化學品評估及分級管理辦法（103/12/31）補題
DU = "OSH-45"
GR = "OSH-43"
Q = [
(DU,"第1條",1,"粉塵標準-授權依據",
 "粉塵危害預防標準係依何項法律授權訂定？",
 ["依職業安全衛生法第六條第三項規定訂定","依職業安全衛生法第十一條第二項規定訂定","依職業安全衛生法第二十三條第四項規定訂定","依職業安全衛生法第十二條第五項規定訂定"],"a",
 "第1條：本標準依職業安全衛生法第六條第三項規定訂定之，與特定化學物質危害預防標準之授權依據相同。至危害性化學品評估及分級管理辦法則依同法第十一條第二項授權訂定。第25條並定本標準自發布日施行。",
 "Under which statutory provision are the Dust Hazard Prevention Standards enacted?",
 ["Article 6, Paragraph 3 of the Occupational Safety and Health Act","Article 11, Paragraph 2 of the Occupational Safety and Health Act","Article 23, Paragraph 4 of the Occupational Safety and Health Act","Article 12, Paragraph 5 of the Occupational Safety and Health Act"],
 "Article 1 cites Article 6(3) of the OSH Act."),

(DU,"第2條",1,"粉塵標準-適用範圍",
 "粉塵危害預防標準之適用對象為何？",
 ["適用於附表一甲欄所列粉塵作業之有關事業","適用於附表一乙欄所列特定粉塵發生源之事業","適用於附表一丙欄所列應戴呼吸防護具之事業","適用於附表二所列氣罩型式之有關製造業事業"],"a",
 "第2條：本標準適用於附表一甲欄所列粉塵作業之有關事業。第3條第1款並將粉塵作業定義為附表一甲欄所列之作業，第2款將特定粉塵發生源定義為附表一乙欄所列作業之處所。第23條則就附表一丙欄所列作業定有呼吸防護具之提供義務。",
 "To whom do the Dust Hazard Prevention Standards apply?",
 ["Enterprises engaged in the dust operations listed in column A of Appendix 1","Enterprises with the specified dust sources listed in column B of Appendix 1","Enterprises whose work requires respirators as listed in column C of Appendix 1","Manufacturing enterprises using the hood types listed in Appendix 2 of the Standards"],
 "Article 2 refers to column A of Appendix 1."),

(DU,"第2條",2,"粉塵標準-附表一",
 "附表一甲欄、乙欄、丙欄所列內容之區分為何？",
 ["甲欄為粉塵作業，乙欄為特定粉塵發生源，丙欄為應使用呼吸防護具之作業","甲欄為特定粉塵發生源，乙欄為粉塵作業，丙欄為應設置密閉設備之作業","甲欄為應使用呼吸防護具之作業，乙欄為粉塵作業，丙欄為特定粉塵發生源","甲欄為坑內之粉塵作業，乙欄為室內粉塵作業，丙欄為室外特定粉塵作業"],"a",
 "附表一分甲、乙、丙三欄：甲欄所列為粉塵作業（第2條、第3條第1款）；乙欄所列為特定粉塵發生源，第6條要求就每一特定粉塵發生源設置對應之設備；丙欄所列作業則依第23條應提供並令勞工使用適當之呼吸防護具。第3條第3款並定義特定粉塵作業為粉塵發生源屬特定粉塵發生源之粉塵作業。",
 "How do columns A, B and C of Appendix 1 differ?",
 ["Column A lists dust operations, column B specified dust sources, column C work requiring respirators","Column A lists specified dust sources, column B dust operations, column C work requiring enclosures","Column A lists work requiring respirators, column B dust operations, column C specified dust sources","Column A lists underground dust work, column B indoor dust work, column C outdoor specified work"],
 "Appendix 1 columns A, B and C, applied by Articles 2, 6 and 23."),

(DU,"第2條、第3條、第4條",1,"粉塵標準-條文刪除",
 "粉塵危害預防標準第四條之現行狀態為何？粉塵作業之適用範圍現如何界定？",
 ["第四條業經刪除；粉塵作業之適用範圍依第二條及第三條，以附表一甲欄所列作業之有關事業為準","第四條仍有效施行；粉塵作業之適用範圍依該條規定，以勞工人數三十人以上之事業單位為準","第四條業經刪除；粉塵作業之適用範圍改依附表二所列氣罩型式及第七條規定之作業處所為準","第四條仍有效施行；粉塵作業之適用範圍依該條規定，以坑內及隧道等特定場所之作業為準"],"a",
 "第4條已刪除。現行粉塵作業之適用範圍係由第2條（適用於附表一甲欄所列粉塵作業之有關事業）及第3條之定義規定界定。第8條同屬已刪除之條文，氣罩型式改依第7條及第9條規範。",
 "What is the status of Article 4, and how is the scope of dust work now defined?",
 ["Article 4 is deleted; the scope follows Articles 2 and 3, covering enterprises in column A of Appendix 1","Article 4 remains in force; under it the scope covers enterprises with thirty or more workers only","Article 4 is deleted; the scope now follows the hood types in Appendix 2 and the sites under Article 7","Article 4 remains in force; under it the scope covers only underground and tunnel work locations"],
 "Article 4 is deleted; scope comes from Articles 2 and 3."),

(DU,"第5條",2,"粉塵標準-免適用",
 "粉塵作業之設備以連續注水或注油操作時，該作業得免適用本標準之哪些條文？",
 ["該作業得免適用第六條至第二十四條之規定","該作業得免適用第六條至第十四條之規定","該作業得免適用第十條至第二十五條之規定","該作業得免適用第九條至第二十二條之規定"],"a",
 "第5條規定符合該條所列六款粉塵作業之設備，如以連續注水或注油操作時，該作業得免適用第六條至第二十四條之規定。第1條、第2條至第5條及第25條則不在免適用之列。第12條、第13條另有以呼吸防護具替代第六條設備之特別規定。",
 "If equipment is operated with continuous water or oil injection, which articles do not apply?",
 ["The operation is exempt from the provisions of Articles 6 through 24 of these Standards","The operation is exempt from the provisions of Articles 6 through 14 of these Standards","The operation is exempt from the provisions of Articles 10 through 25 of these Standards","The operation is exempt from the provisions of Articles 9 through 22 of these Standards"],
 "Article 5 exempts Articles 6 to 24."),

(DU,"第5條",3,"粉塵標準-免適用",
 "下列何組粉塵作業，於以連續注水或注油操作時得適用前述免除規定？",
 ["礦物等之篩選、以研磨材吹噴研磨或動力研磨岩石礦物、以動力篩選土石或碳原料及砂再生等作業","坑內之鑿岩與裝載、隧道內噴凝土襯砌、水泥之袋裝拆袋及室內金屬電銲切割等之作業","石綿之吹噴拆除、玻璃纖維之裁切成型、活性碳之填充及室內油漆噴塗研磨等之作業","鑄件之造模與砂心製作、耐火磚之堆砌、爐渣之搬運及室內鍋爐之清掃等之作業"],"a",
 "第5條列六款：粉塵作業（三）之礦物等篩選作業；粉塵作業（六）；粉塵作業（七）中以研磨材吹噴研磨或以動力研磨岩石、礦物、金屬削除毛邊或切斷金屬之作業；粉塵作業（八）中以動力篩選土石、岩石、礦物或碳原料之作業；粉塵作業（八）中在室外以動力搗碎或粉碎者；及粉塵作業（十五）之砂再生作業。",
 "Which group of dust operations may use the continuous water or oil injection exemption?",
 ["Screening of minerals, abrasive blasting or powered grinding of rock, powered screening of stone or carbon, and sand reclamation","Underground drilling and loading, tunnel shotcrete lining, cement bagging and unbagging, and indoor metal welding and cutting","Asbestos spraying and removal, glass fibre cutting and forming, activated carbon filling, and indoor paint spraying and sanding","Foundry moulding and core making, refractory brick laying, slag transport, and indoor boiler cleaning operations"],
 "Article 5, subparagraphs 1 to 6."),

(DU,"第7條",2,"粉塵標準-氣罩",
 "依第六條設置之局部排氣裝置（特定粉塵發生源設有磨床、鼓式砂磨機等者除外），其氣罩應如何設置？",
 ["應就附表二所列之特定粉塵發生源，設置同表所列型式以外之氣罩","應就附表二所列之特定粉塵發生源，設置同表所列型式之包圍型氣罩","應就附表一乙欄所列之粉塵作業，設置可覆蓋擴散方向之接受型氣罩","應就附表一丙欄所列之粉塵作業，設置全部包圍回轉體之外裝型氣罩"],"a",
 "第7條：雇主依第六條設置之局部排氣裝置，應就附表二所列之特定粉塵發生源，設置同表所列型式以外之氣罩；亦即附表二係列出不得採用之氣罩型式。至設有磨床、鼓式砂磨機等回轉機械者，則依第9條之三種方式擇一設置氣罩。第15條另定局部排氣裝置之整體構造要求。",
 "How must hoods be arranged for local exhaust installed under Article 6?",
 ["For the specified dust sources listed in Appendix 2, hoods other than the types listed in that table","For the specified dust sources listed in Appendix 2, enclosing hoods of the types listed in that table","For the dust operations in column B of Appendix 1, receiving hoods covering the dispersion direction","For the dust operations in column C of Appendix 1, exterior hoods fully enclosing the rotating body"],
 "Article 7 requires hoods other than those listed in Appendix 2."),

(DU,"第7條、第8條、第9條",1,"粉塵標準-條文刪除",
 "粉塵危害預防標準第八條之現行狀態為何？局部排氣裝置氣罩型式現由何條規範？",
 ["第八條業經刪除；氣罩型式現分別依第七條之附表二規定及第九條回轉機械氣罩之三種方式辦理","第八條仍有效施行；氣罩型式現依該條規定，一律應採用可完全包圍發生源之包圍型氣罩辦理","第八條業經刪除；氣罩型式現一律依第十五條規定，採用外裝型氣罩並儘量接近粉塵發生源","第八條仍有效施行；氣罩型式現依該條規定，得由雇主視作業性質自行選定並報檢查機構備查"],"a",
 "第8條已刪除，與第4條同。現行氣罩型式之規定分見於第7條（就附表二所列特定粉塵發生源，設置同表所列型式以外之氣罩）及第9條（磨床、鼓式砂磨機等回轉機械之三種氣罩方式）。第15條第1款另要求氣罩宜設於每一粉塵發生源，外裝型氣罩應儘量接近發生源。",
 "What is the status of Article 8, and where are hood types now regulated?",
 ["Article 8 is deleted; hood types now follow Article 7 with Appendix 2 and the three methods in Article 9","Article 8 remains in force; under it enclosing hoods fully surrounding the source must always be used","Article 8 is deleted; hood types now follow Article 15 alone, using exterior hoods placed close to the source","Article 8 remains in force; under it the employer may choose the type and report it to the inspection agency"],
 "Article 8 is deleted; see Articles 7 and 9."),

(DU,"第9條",2,"粉塵標準-氣罩",
 "特定粉塵發生源設有磨床、鼓式砂磨機等回轉機械時，氣罩得依哪幾種方式設置？",
 ["可將回轉體機械裝置等全部包圍之方式、氣罩開口面可覆蓋粉塵擴散方向之方式，或僅將回轉體部分包圍之方式","可將整個作業場所全部密閉之方式、氣罩開口面朝向勞工呼吸帶之方式，或僅將作業人員部分隔離之方式","可將回轉體機械裝置全部浸水之方式、氣罩開口面背對粉塵擴散方向之方式，或僅將導管部分保溫之方式","可將回轉體機械裝置全部加蓋之方式、氣罩開口面加裝濾網過濾之方式，或僅將排氣機部分包覆之方式"],"a",
 "第9條列三款氣罩設置方式：可將回轉體機械裝置等全部包圍之方式；設置之氣罩可在氣罩開口面覆蓋粉塵之擴散方向；僅將回轉體部分包圍之方式。此係第7條附表二氣罩型式規定之例外處理，蓋磨床、鼓式砂磨機等回轉機械已明文排除於第7條之外。",
 "For grinders and drum sanders, which hood arrangements are permitted?",
 ["Fully enclosing the rotating machine, a hood opening covering the dust dispersion direction, or partly enclosing the rotor","Fully sealing the whole workplace, a hood opening facing the worker breathing zone, or partly isolating the operator","Fully immersing the rotating machine in water, a hood opening facing away from dispersion, or insulating the duct","Fully covering the rotating machine with a lid, a hood opening fitted with a filter screen, or covering the exhaust fan"],
 "Article 9, subparagraphs 1 to 3."),

(DU,"第9條",2,"粉塵標準-氣罩",
 "前述三種回轉機械氣罩之設置方式，適用於何種情形？",
 ["適用於依第六條或第二十三條但書設置局部排氣裝置之特定粉塵發生源，設有磨床、鼓式砂磨機等回轉機械時","適用於依第十條設置整體換氣裝置之非特定粉塵作業室內作業場所，設有輸送帶或斗提機等機械時","適用於依第十一條設置換氣裝置之坑內作業場所，設有鑿岩機或裝載機等移動式動力機械時","適用於依第十三條設置整體換氣裝置之特定粉塵作業場所，設有搗碎機或混合機等固定機械時"],"a",
 "第9條之適用前提為：雇主就第六條或第二十三條但書設置局部排氣裝置之特定粉塵發生源，設置有磨床、鼓式砂磨機等回轉機械時。第23條但書係指粉塵發生源已設有效之密閉設備、局部排氣裝置或維持濕潤狀態者，得免提供呼吸防護具。",
 "In what situation do those three hood arrangements apply?",
 ["Where local exhaust is installed under Article 6 or the proviso to Article 23 at a source with grinders or drum sanders","Where general ventilation is installed under Article 10 in an indoor non-specified dust site with conveyors or elevators","Where ventilation is installed under Article 11 in an underground site with rock drills or mobile powered loaders","Where general ventilation is installed under Article 13 at a specified dust site with crushers or mixing machines"],
 "Article 9 applies to rotating machines at sources under Article 6 or the Article 23 proviso."),

(DU,"第11條",2,"粉塵標準-坑內換氣",
 "對從事特定粉塵作業以外之粉塵作業之坑內作業場所（平水坑除外），為防止粉塵擴散應如何辦理？",
 ["應設置換氣裝置或同等以上性能之設備；但臨時性作業、作業時間短暫或作業期間短暫，且供給適當呼吸防護具者除外","應設置密閉設備或局部排氣裝置；但臨時性作業、作業時間短暫或作業期間短暫，且已實施每日灑水清掃者除外","應設置整體換氣裝置及除塵裝置；但作業勞工人數未滿十人，或坑內斷面積超過二十平方公尺者，不在此限","應設置維持濕潤狀態之設備；但已設置粉塵濃度連續監測裝置，並指定粉塵作業主管監督作業者，不在此限"],"a",
 "第11條第1項：對從事特定粉塵作業以外之粉塵作業之坑內作業場所（平水坑除外），應設置換氣裝置或同等以上性能之設備；但臨時性作業、作業時間短暫或作業期間短暫，且供給勞工使用適當之呼吸防護具時，不在此限。第10條就室內作業場所之整體換氣裝置定有相同結構之但書。",
 "For underground non-specified dust work other than level drifts, what is required?",
 ["Ventilation or equivalent equipment; unless the work is temporary, brief or short-term and suitable respirators are supplied","Enclosures or local exhaust ventilation; unless the work is temporary, brief or short-term and daily water cleaning is done","General ventilation plus dust collectors; unless fewer than ten workers are engaged or the section exceeds twenty square metres","Equipment keeping the source wetted; unless a continuous dust monitor is installed and a dust work supervisor is appointed"],
 "Article 11, Paragraph 1."),

(DU,"第11條",2,"粉塵標準-坑內換氣",
 "前述坑內作業場所所設置之換氣裝置，應具備何種性能？",
 ["前項換氣裝置應具動力輸入外氣置換坑內空氣之設備","前項換氣裝置應具自然通風排出坑內空氣之導風設備","前項換氣裝置應具過濾除塵及靜電集塵之複合式設備","前項換氣裝置應具連續注水潤濕坑內壁面之給水設備"],"a",
 "第11條第2項：前項換氣裝置應具動力輸入外氣置換坑內空氣之設備，亦即不得僅依自然通風。第11條之1並要求密閉設備、局部排氣裝置或整體換氣裝置應由專業人員妥為設計並維持其性能，第16條要求作業時間內不得停止運轉。",
 "What performance must the underground ventilation device have?",
 ["It must have powered equipment introducing outside air to replace the air inside the pit","It must have wind-guiding equipment discharging the pit air by natural ventilation alone","It must have combined filtration and electrostatic dust collection equipment fitted to it","It must have a water supply device continuously wetting the walls inside the pit area"],
 "Article 11, Paragraph 2 requires powered replacement air."),

(DU,"第11條之1",2,"粉塵標準-設備設計",
 "雇主設置之密閉設備、局部排氣裝置或整體換氣裝置，應由何人設計？並應如何維護？",
 ["應由專業人員妥為設計，並維持其性能","應由原製造廠商設計，並每年校正一次","應由勞動檢查機構設計，並核發合格標章","應由粉塵作業主管設計，並保存設計文件"],"a",
 "第11條之1：雇主設置之密閉設備、局部排氣裝置或整體換氣裝置，應由專業人員妥為設計，並維持其性能。與特定化學物質危害預防標準第38條第1項規定意旨相同；該標準第38條第2項至第4項並就局部排氣裝置另定設計報告書及原始性能測試之要求。",
 "Who must design enclosures, local exhaust and general ventilation, and how are they kept?",
 ["A professional must properly design them, and their performance must be maintained","The original manufacturer must design them, and they must be calibrated once a year","The labor inspection agency must design them and issue a certificate of conformity","The dust work supervisor must design them and keep the design documents on file"],
 "Article 11-1 mirrors Article 38(1) of the specified chemicals standards."),

(DU,"第12條",2,"粉塵標準-免適用",
 "特定粉塵作業於何種情形下，雇主已供給勞工適當呼吸防護具者，即不適用第六條之規定？",
 ["從事臨時性作業時，或從事同一特定粉塵發生源之作業時間短暫或作業期間短暫時","從事夜間作業時，或從事同一特定粉塵發生源之作業勞工人數未滿五人時","從事戶外作業時，或從事同一特定粉塵發生源之粉塵濃度低於容許濃度時","從事維修作業時，或從事同一特定粉塵發生源之作業已指定作業主管監督時"],"a",
 "第12條列二款：從事臨時性作業時；從事同一特定粉塵發生源之作業時間短暫或作業期間短暫時。符合其一且已供給適當呼吸防護具者，不適用第6條設置設備之規定。第13條另就小型研磨輪、搗碎機、篩選機、混合機定有併設整體換氣裝置及呼吸防護具之替代方式。",
 "When does supplying suitable respirators exempt specified dust work from Article 6?",
 ["When the work is temporary, or when work at the same specified dust source is brief or short-term","When the work is at night, or when fewer than five workers engage at the same specified dust source","When the work is outdoors, or when dust concentration at the same source is below the permissible limit","When the work is maintenance, or when a work supervisor has been appointed for the same dust source"],
 "Article 12, subparagraphs 1 and 2."),

(DU,"第3條、第12條",3,"粉塵標準-用詞定義",
 "適用前述免除規定時，臨時性作業、作業時間短暫及作業期間短暫之判斷標準各為何？",
 ["臨時性作業指期間不超過三個月且一年內不再重覆；時間短暫指每日不超過一小時；期間短暫指不超過一個月且六個月內不再實施","臨時性作業指期間不超過一個月且半年內不再重覆；時間短暫指每日不超過三小時；期間短暫指不超過三個月且一年內不再實施","臨時性作業指期間不超過六個月且三年內不再重覆；時間短暫指每日不超過二小時；期間短暫指不超過二個月且一年內不再實施","臨時性作業指期間不超過一年且五年內不再重覆；時間短暫指每班不超過四小時；期間短暫指不超過六個月且三年內不再實施"],"a",
 "第3條第8款至第10款定義：臨時性作業指正常作業以外之作業，其作業期間不超過三個月且一年內不再重覆；作業時間短暫指同一特定粉塵發生源之特定粉塵作業每日作業不超過一小時；作業期間短暫指作業期間不超過一個月，且確知自該作業終了日起六個月以內不再實施該作業。第12條即據此判斷。",
 "How are temporary work, brief work time and short work period defined for this exemption?",
 ["Temporary: under three months and not repeated within a year; brief: under one hour a day; short period: under one month and none within six months","Temporary: under one month and not repeated within half a year; brief: under three hours a day; short period: under three months and none within a year","Temporary: under six months and not repeated within three years; brief: under two hours a day; short period: under two months and none within a year","Temporary: under one year and not repeated within five years; brief: under four hours a shift; short period: under six months and none within three years"],
 "Article 3, subparagraphs 8 to 10, applied by Article 12."),

(DU,"第16條",2,"粉塵標準-運轉管理",
 "局部排氣裝置或整體換氣裝置於粉塵作業時間內之運轉，應如何管理？",
 ["局部排氣裝置或整體換氣裝置，於粉塵作業時間內，應不得停止運轉","局部排氣裝置或整體換氣裝置，於粉塵作業時間內，得間歇停止運轉","局部排氣裝置或整體換氣裝置，僅於粉塵濃度超標時，始須開始運轉","局部排氣裝置或整體換氣裝置，於每日作業開始前運轉三十分鐘即可"],"a",
 "第16條第1項：局部排氣裝置或整體換氣裝置，於粉塵作業時間內，應不得停止運轉。第2項並要求置於使排氣或換氣不受阻礙之處，使之有效運轉。第11條之1則要求該等設備應由專業人員妥為設計並維持其性能。",
 "How must local exhaust or general ventilation be run during dust work?",
 ["Local exhaust or general ventilation must not be stopped during the dust work period","Local exhaust or general ventilation may be stopped intermittently during dust work","Local exhaust or general ventilation need start only when dust exceeds the limit value","Local exhaust or general ventilation need run only thirty minutes before work starts"],
 "Article 16, Paragraph 1."),

(DU,"第16條",2,"粉塵標準-運轉管理",
 "局部排氣裝置或整體換氣裝置之設置位置，有何規定？",
 ["應置於使排氣或換氣不受阻礙之處所，使之有效運轉","應置於接近勞工呼吸帶之處所，使之集中吸引粉塵","應置於室外上風處之處所，使之免受雨水侵蝕損壞","應置於便於維修保養之處所，使之易於每月拆卸清洗"],"a",
 "第16條第2項：局部排氣裝置或整體換氣裝置，應置於使排氣或換氣不受阻礙之處，使之有效運轉。第15條另就局部排氣裝置定五款構造要求，包括氣罩宜設於每一粉塵發生源、導管長度儘量縮短、排氣機置於空氣清淨裝置後、排氣口應設於室外等。",
 "Where must local exhaust or general ventilation equipment be placed?",
 ["At a place where exhaust or ventilation is not obstructed, so that it operates effectively","At a place close to the worker breathing zone, so that dust is drawn in at one point","At an outdoor upwind place, so that it is protected from rain erosion and damage","At a place convenient for maintenance, so that it can be dismantled and washed monthly"],
 "Article 16, Paragraph 2."),

(DU,"第17條",2,"粉塵標準-濕式作業",
 "依第六條規定設置之濕式衝擊式鑿岩機，於實施特定粉塵作業時應如何操作？",
 ["依第六條規定設置之濕式衝擊式鑿岩機，於實施特定粉塵作業時，應使之有效給水","依第六條規定設置之濕式衝擊式鑿岩機，於實施特定粉塵作業時，應使之有效抽氣","依第十條規定設置之濕式衝擊式鑿岩機，於實施粉塵作業前後，應使之有效洗淨","依第十三條規定設置之乾式衝擊式鑿岩機，於實施特定粉塵作業時，應使之有效除塵"],"a",
 "第17條：雇主依第六條規定設置之濕式衝擊式鑿岩機於實施特定粉塵作業時，應使之有效給水。第18條則就依第六條或第二十三條但書設置之維持粉塵發生源濕潤狀態設備，要求於粉塵作業時對該處所保持濕潤狀態，二者同屬濕式抑塵之管理規定。",
 "How must a wet impact rock drill installed under Article 6 be operated?",
 ["A wet impact rock drill installed under Article 6 must be effectively supplied with water during specified dust work","A wet impact rock drill installed under Article 6 must be effectively exhausted with air during specified dust work","A wet impact rock drill installed under Article 10 must be effectively washed before and after any dust work","A dry impact rock drill installed under Article 13 must be effectively dedusted during specified dust work"],
 "Article 17 requires effective water supply."),

(DU,"第18條",2,"粉塵標準-濕潤狀態",
 "依第六條或第二十三條但書設置維持粉塵發生源濕潤狀態之設備者，於粉塵作業時應如何辦理？",
 ["依第六條或第二十三條但書設置該設備者，於粉塵作業時，對該粉塵發生處所應保持濕潤狀態","依第六條或第二十三條但書設置該設備者，僅於作業終了後，對該處所實施一次沖洗即可","依第十條或第十一條設置整體換氣裝置者，於粉塵作業時，對地面及設備每小時灑水一次","依第十五條設置局部排氣裝置者，於粉塵作業時，對氣罩開口面保持連續噴霧之濕潤狀態"],"a",
 "第18條：雇主依第六條或第二十三條但書規定設置維持粉塵發生源之濕潤狀態之設備，於粉塵作業時，對該粉塵發生處所應保持濕潤狀態。第23條但書即以粉塵發生源設有效之密閉設備、局部排氣裝置或維持濕潤狀態者，作為免提供呼吸防護具之要件。",
 "Where wetting equipment is installed under Article 6 or the Article 23 proviso, what applies?",
 ["Where such equipment is installed, the dust generating place must be kept in a wetted state during dust work","Where such equipment is installed, a single rinse of the place after work has finished is sufficient","Where general ventilation is installed under Articles 10 or 11, floors and equipment are sprinkled hourly","Where local exhaust is installed under Article 15, the hood opening is kept wetted by continuous spray"],
 "Article 18 requires the wetted state to be maintained."),

(DU,"第19條",2,"粉塵標準-作業管理",
 "雇主使勞工從事粉塵作業時，對作業場所應隨時確認之事項為何？",
 ["應對粉塵作業場所實施通風設備運轉狀況、勞工作業情形、空氣流通效果及粉塵狀況等隨時確認，並採取必要措施","應對粉塵作業場所實施照明照度、噪音音壓、溫濕度及地面平整狀況等每月確認一次，並記錄於檢點表中","應對粉塵作業場所實施勞工出勤紀錄、防護具領用情形及教育訓練時數等每季確認，並函報勞動檢查機構","應對粉塵作業場所實施機械設備折舊、保養費用及零件庫存狀況等每年確認，並納入年度預算編列辦理"],"a",
 "第19條第1款：對粉塵作業場所應實施通風設備運轉狀況、勞工作業情形、空氣流通效果及粉塵狀況等隨時確認，並採取必要措施。第2款則要求將預防粉塵危害之必要注意事項通告全體有關勞工。第20條並要求指定粉塵作業主管從事監督作業。",
 "What must be checked at any time when workers engage in dust operations?",
 ["Ventilation operation, worker practices, air circulation effectiveness and dust conditions must be checked at any time, with measures taken","Illumination, noise pressure, temperature, humidity and floor evenness must be checked each month and recorded on a check sheet form","Attendance records, protective gear issuance and training hours must be checked quarterly and reported to the inspection agency","Equipment depreciation, maintenance costs and spare part stocks must be checked yearly and included in the annual budget"],
 "Article 19, subparagraph 1."),

(DU,"第19條",1,"粉塵標準-作業管理",
 "預防粉塵危害之必要注意事項，應如何處理？",
 ["預防粉塵危害之必要注意事項，應通告全體有關勞工","預防粉塵危害之必要注意事項，僅須通告粉塵作業主管","預防粉塵危害之必要注意事項，應函報勞動檢查機構備查","預防粉塵危害之必要注意事項，應於每年年終彙整後公告"],"a",
 "第19條第2款：預防粉塵危害之必要注意事項，應通告全體有關勞工。此與第21條應公告粉塵作業場所禁止飲食或吸菸並揭示於明顯易見處所之規定，同屬告知與揭示義務。第20條並要求指定粉塵作業主管實際從事監督。",
 "How must the necessary precautions for preventing dust hazards be handled?",
 ["The necessary precautions for preventing dust hazards must be notified to all workers concerned","The necessary precautions for preventing dust hazards need be notified to the dust supervisor only","The necessary precautions for preventing dust hazards must be filed with the labor inspection agency","The necessary precautions for preventing dust hazards must be compiled and posted at each year end"],
 "Article 19, subparagraph 2."),

(DU,"第20條",1,"粉塵標準-作業主管",
 "雇主僱用勞工從事粉塵作業時，應如何辦理監督事宜？",
 ["雇主僱用勞工從事粉塵作業時，應指定粉塵作業主管，從事監督作業","雇主僱用勞工從事粉塵作業時，應指定急救人員，從事該監督之作業","雇主僱用勞工從事粉塵作業時，應指定職業安全衛生管理師代為監督","雇主僱用勞工從事粉塵作業時，應由勞動檢查機構指派人員到場監督"],"a",
 "第20條：雇主僱用勞工從事粉塵作業時，應指定粉塵作業主管，從事監督作業。此與特定化學物質危害預防標準第37條指定現場主管擔任特定化學物質作業主管之規定體例相同。第19條並要求隨時確認通風設備運轉狀況及粉塵狀況並採必要措施。",
 "How must supervision be arranged when workers are engaged in dust operations?",
 ["The employer must designate a dust operations supervisor to carry out supervision of the work","The employer must designate a first aid attendant to carry out supervision of the work instead","The employer must designate a safety and health manager to supervise the work on its behalf","The labor inspection agency must assign personnel to attend the site and supervise the work"],
 "Article 20 requires a designated dust operations supervisor."),

(DU,"第21條",1,"粉塵標準-作業場所管理",
 "對粉塵作業場所之飲食及吸菸，雇主應如何管理？",
 ["應公告粉塵作業場所禁止飲食或吸菸，並揭示於明顯易見之處所","應公告粉塵作業場所禁止飲食或吸菸，並函報主管機關核備存查","應公告粉塵作業場所得限時飲食及吸菸，並揭示於明顯易見處所","應公告粉塵作業場所全面禁止勞工進入，並揭示於明顯易見處所"],"a",
 "第21條：雇主應公告粉塵作業場所禁止飲食或吸菸，並揭示於明顯易見之處所。第22條並要求室內粉塵作業場所至少每日清掃一次以上，且至少每月定期以真空吸塵器或水沖洗等方法清除地面、設備。特定化學物質危害預防標準第40條亦有相同之禁止飲食吸菸規定。",
 "How must eating and smoking at dust work sites be managed?",
 ["A notice prohibiting eating or smoking at the dust work site must be posted where it is clearly visible","A notice prohibiting eating or smoking at the dust work site must be filed with the competent authority","A notice allowing eating and smoking at set times must be posted where it is clearly visible on site","A notice prohibiting all workers from entering the dust work site must be posted where clearly visible"],
 "Article 21 requires a conspicuously posted prohibition."),

(DU,"第24條",2,"粉塵標準-呼吸防護具",
 "雇主使勞工戴用輸氣管面罩從事連續作業時，其時間有何限制？",
 ["使勞工戴用輸氣管面罩之連續作業時間，每次不得超過一小時","使勞工戴用輸氣管面罩之連續作業時間，每次不得超過二小時","使勞工戴用輸氣管面罩之連續作業時間，每日不得超過四小時","使勞工戴用輸氣管面罩之連續作業時間，每次不得超過三十分鐘"],"a",
 "第24條：雇主使勞工戴用輸氣管面罩之連續作業時間，每次不得超過一小時。第23條則規定從事附表一丙欄所列作業應提供並令勞工使用適當之呼吸防護具，但該作業場所粉塵發生源設有效之密閉設備、局部排氣裝置或維持濕潤狀態者，不在此限。",
 "What time limit applies to continuous work wearing an air-line respirator?",
 ["Continuous work wearing an air-line respirator must not exceed one hour each time","Continuous work wearing an air-line respirator must not exceed two hours each time","Continuous work wearing an air-line respirator must not exceed four hours in a day","Continuous work wearing an air-line respirator must not exceed thirty minutes each time"],
 "Article 24 caps each continuous period at one hour."),

(DU,"第25條",1,"粉塵標準-施行日期",
 "粉塵危害預防標準及其一百零三年六月二十五日修正條文之施行日期為何？",
 ["本標準自發布日施行；一百零三年六月二十五日修正條文，自一百零三年七月三日施行","本標準自發布日施行；一百零三年六月二十五日修正條文，自一百零四年一月一日施行","本標準自發布後六個月施行；一百零三年六月二十五日之修正條文，則自發布日施行","本標準自發布日施行；一百零三年六月二十五日修正條文，自一百十二年七月一日施行"],"a",
 "第25條：本標準自發布日施行；本標準中華民國一百零三年六月二十五日修正條文，自一百零三年七月三日施行。同日修正之特定化學物質危害預防標準條文亦自一百零三年七月三日施行，係配合職業安全衛生法之施行日期。",
 "When did these Standards and the 2014 amendments take effect?",
 ["The Standards took effect on promulgation; the 25 June 2014 amendments took effect on 3 July 2014","The Standards took effect on promulgation; the 25 June 2014 amendments took effect on 1 January 2015","The Standards took effect six months after promulgation; the 25 June 2014 amendments on promulgation","The Standards took effect on promulgation; the 25 June 2014 amendments took effect on 1 July 2023"],
 "Article 25."),

(GR,"第1條",1,"分級管理-授權依據",
 "危害性化學品評估及分級管理辦法係依何項法律授權訂定？",
 ["依職業安全衛生法第十一條第二項規定訂定","依職業安全衛生法第六條第三項規定訂定","依職業安全衛生法第十二條第五項規定訂定","依職業安全衛生法第二十條第四項規定訂定"],"a",
 "第1條：本辦法依職業安全衛生法第十一條第二項規定訂定之。職業安全衛生法第十一條第一項規定雇主對於前條之化學品應依其健康危害、散布狀況及使用量等情形，評估風險等級並採分級管理措施。至粉塵危害預防標準、特定化學物質危害預防標準則係依同法第六條第三項授權訂定。",
 "Under which statutory provision are the Chemical Assessment and Grading Regulations enacted?",
 ["Article 11, Paragraph 2 of the Occupational Safety and Health Act","Article 6, Paragraph 3 of the Occupational Safety and Health Act","Article 12, Paragraph 5 of the Occupational Safety and Health Act","Article 20, Paragraph 4 of the Occupational Safety and Health Act"],
 "Article 1 cites Article 11(2) of the OSH Act."),

(GR,"第4條",2,"分級管理-評估義務",
 "雇主使勞工製造、處置或使用之化學品，符合國家標準化學品分類具有健康危害者，應如何辦理？",
 ["應評估其危害及暴露程度，劃分風險等級，並採取對應之分級管理措施","應委託認可機構檢驗其成分，取得許可文件，並每年報請主管機關備查","應優先辦理作業環境監測，公告其監測結果，並將該化學品全面停止使用","應建立安全資料表，張貼於作業場所，並由勞工簽名確認已知悉其內容"],"a",
 "第4條：雇主使勞工製造、處置或使用之化學品，符合國家標準CNS15030化學品分類具有健康危害者，應評估其危害及暴露程度，劃分風險等級，並採取對應之分級管理措施。第2條並定義暴露評估與分級管理；第6條要求至少每三年執行一次，第10條則定第一級至第三級管理之對應措施。",
 "For chemicals with health hazards under the national classification standard, what must be done?",
 ["Assess their hazard and exposure, classify risk levels, and take corresponding grading management measures","Commission an accredited body to test the composition, obtain a permit, and report to the authority each year","Carry out workplace exposure monitoring first, announce the results, and stop using the chemical entirely","Prepare a safety data sheet, post it at the workplace, and have workers sign to confirm they have read it"],
 "Article 4 requires assessment, risk grading and grading management."),

(GR,"第4條",2,"分級管理-適用判準",
 "本辦法所定應評估及分級管理之化學品，係依何項國家標準判定其具有健康危害？",
 ["國家標準CNS15030化學品分類中具有健康危害者","國家標準CNS15030化學品分類中具有物理危害者","國家標準CNS14253職業安全衛生管理系統之分類","國家標準CNS12680危害物質標示之圖式分類規定"],"a",
 "第4條以國家標準CNS15030化學品分類具有健康危害者為適用對象，故物理性危害（如易燃、爆炸）非本辦法評估及分級管理之範圍。第5條另列不適用本辦法之情形；第3條則規定本辦法所定化學品優先適用特定化學物質危害預防標準、有機溶劑中毒預防規則及粉塵危害預防標準等法規之控制設備規定。",
 "Under which national standard classification are the chemicals judged to have health hazards?",
 ["Chemicals classified as having health hazards under national standard CNS 15030","Chemicals classified as having physical hazards under national standard CNS 15030","Chemicals classified under national standard CNS 14253 on safety management systems","Chemicals classified under national standard CNS 12680 on hazardous substance labelling"],
 "Article 4 refers to health hazards under CNS 15030."),

(GR,"第5條",2,"分級管理-不適用情形",
 "下列何組物品之製造、處置或使用，不適用危害性化學品評估及分級管理辦法？",
 ["有害事業廢棄物、菸草或菸草製品、食品飲料藥物化粧品、製成品、非工業用途之一般民生消費商品及滅火器","有害事業廢棄物、工業用有機溶劑、實驗室試藥、金屬切削油、工業用途之清潔劑原料及壓縮氣體鋼瓶等","菸草或菸草製品、食品飲料藥物化粧品、電鍍用酸鹼槽液、農藥原體、含鉛塗料及工業用之黏著劑等","製成品、非工業用途之一般民生消費商品、滅火器、燻蒸用氰化氫、石綿建材及含苯之工業用稀釋劑"],"a",
 "第5條第1款列七目不適用之物品：有害事業廢棄物、菸草或菸草製品、食品飲料藥物化粧品、製成品、非工業用途之一般民生消費商品、滅火器，以及在反應槽或製程中正進行化學反應之中間產物。第2款、第3款另定僅作貯存用途且無暴露危害之虞者及其他經中央主管機關指定者亦不適用。",
 "Which group of items falls outside the scope of these grading management regulations?",
 ["Hazardous industrial waste, tobacco products, food drink medicine cosmetics, finished articles, consumer goods and fire extinguishers","Hazardous industrial waste, industrial organic solvents, laboratory reagents, cutting oils, industrial detergent bases and gas cylinders","Tobacco products, food drink medicine cosmetics, electroplating bath liquids, pesticide actives, leaded paints and industrial adhesives","Finished articles, non-industrial consumer goods, fire extinguishers, fumigation hydrogen cyanide, asbestos boards and benzene thinners"],
 "Article 5, subparagraph 1."),

(GR,"第5條",2,"分級管理-不適用情形",
 "除特定物品外，本辦法尚有哪些不適用之情形？",
 ["化學品僅作為貯存用途且勞工不致有暴露危害之虞者，及其他經中央主管機關指定者","化學品之年使用量未達一公噸者，及事業單位勞工人數未滿三十人並經檢查機構核備者","化學品已取得管制性化學品運作許可者，及作業場所已設置局部排氣裝置並定期檢查者","化學品之暴露濃度低於容許暴露標準二分之一者，及該作業已納入自動檢查計畫實施者"],"a",
 "第5條第2款、第3款：化學品僅作為貯存用途且勞工不致有暴露危害之虞者，及其他經中央主管機關指定者，均不適用本辦法。另第1款第7目將在反應槽或製程中正進行化學反應之中間產物排除適用。第3條則定本辦法與特定化學物質危害預防標準等法規之適用順序。",
 "Apart from listed items, what other situations fall outside these regulations?",
 ["Chemicals used only for storage where workers face no exposure risk, and other cases designated by the central authority","Chemicals used under one tonne a year, and enterprises with fewer than thirty workers approved by the inspection agency","Chemicals already holding a controlled chemical operating permit, and sites with local exhaust inspected periodically","Chemicals whose exposure is below half the permissible limit, and work already covered by the self-inspection plan"],
 "Article 5, subparagraphs 2 and 3."),

(GR,"第7條",2,"分級管理-辦理方法",
 "雇主辦理化學品之評估及分級管理，應依何種方法辦理？",
 ["應參照中央主管機關公告之技術指引，或採取其他具同等科學基礎之評估及管理方法辦理","應委託中央主管機關認可之驗證機構，依國際標準組織公告之風險評估標準辦理","應依勞動檢查機構逐案核定之作業指引，並於實施前檢送評估計畫書報請核准","應由事業單位職業安全衛生委員會決議之方法辦理，免參照任何外部技術指引"],"a",
 "第7條：雇主辦理前條之評估及分級管理，應參照中央主管機關公告之技術指引，或採取其他具同等科學基礎之評估及管理方法辦理。第6條規定評估及分級管理至少每三年執行一次，種類、操作程序或製程條件變更而有增加暴露風險之虞者，應於變更前或變更後三個月內重新評估。",
 "By what method must the employer carry out the assessment and grading management?",
 ["By reference to the technical guidelines announced by the central authority, or another method of equal scientific basis","By commissioning a verification body accredited by the central authority under an international risk assessment standard","By following case-specific guidance approved by the labor inspection agency, submitting a plan for approval beforehand","By a method resolved by the enterprise safety and health committee, without reference to any external technical guideline"],
 "Article 7 allows the guidelines or an equally science-based method."),

(GR,"第7條",2,"分級管理-辦理方法",
 "雇主未參照中央主管機關公告之技術指引辦理評估及分級管理時，是否即屬違反本辦法？",
 ["不必然違反；本辦法允許採取其他具同等科學基礎之評估及管理方法辦理","一律違反；本辦法規定僅得依中央主管機關公告之技術指引辦理不得變通","不必然違反；惟應事先報請勞動檢查機構核准始得採用其他評估管理方法","一律違反；除非事業單位總勞工人數未滿五百人且未從事特別危害健康作業"],"a",
 "第7條係採參照技術指引或同等科學基礎方法之雙軌設計，故未採技術指引者，仍得以其他具同等科學基礎之評估及管理方法辦理，並不當然違法。第8條則就定有容許暴露標準且達一定規模之事業單位，另課予以採樣分析或定量推估模式實施暴露評估之義務。",
 "Is it necessarily a breach if the employer does not follow the announced technical guidelines?",
 ["Not necessarily; the regulations allow other assessment and management methods of equal scientific basis","Always a breach; the regulations permit only the technical guidelines announced by the central authority","Not necessarily; but prior approval from the labor inspection agency is needed to use another method","Always a breach; unless the enterprise has fewer than five hundred workers and no special hazard work"],
 "Article 7 permits equally science-based alternatives."),

(GR,"第9條",2,"分級管理-暴露評估",
 "雇主實施第八條所定化學品之暴露評估，應依何規定之監測及期程辦理？",
 ["應依勞工作業環境監測實施辦法所定之監測及期程實施，必要時得輔以其他半定量、定量之評估模式或工具","應依危害性化學品標示及通識規則所定之標示及期程實施，必要時得輔以問卷調查或訪談等方式辦理","應依職業安全衛生管理辦法所定之自動檢查期程實施，必要時得輔以承攬人所提供之檢測報告替代之","應依勞工健康保護規則所定之特殊健康檢查期程實施，必要時得輔以醫師臨場健康服務之紀錄辦理"],"a",
 "第9條：雇主應依勞工作業環境監測實施辦法所定之監測及期程，實施前條化學品之暴露評估，必要時並得輔以其他半定量、定量之評估模式或工具實施之。第8條第2項並依暴露濃度與容許暴露標準之比較，定每三年、每年、每三個月之定期評估頻率。",
 "Under which regulations must the exposure assessment monitoring and schedule be carried out?",
 ["Under the Regulations for Workplace Environment Monitoring, with semi-quantitative or quantitative models added where needed","Under the labelling and hazard communication rules, with questionnaire surveys or interviews added where this is needed","Under the self-inspection schedule of the safety and health management regulations, using contractor test reports instead","Under the special health examination schedule of the health protection rules, with on-site physician service records added"],
 "Article 9 refers to the Regulations for Workplace Environment Monitoring."),

(GR,"第9條",2,"分級管理-暴露評估",
 "依作業環境監測實施辦法實施暴露評估時，得否輔以其他評估模式或工具？",
 ["必要時得輔以其他半定量或定量之評估模式或工具實施之，以補強評估之結果","不得輔以任何其他模式或工具，評估結果應完全以採樣分析數據為其唯一依據","得完全以定性之評估模式或工具取代作業環境監測，免再實施任何採樣分析工作","僅於勞工人數未滿一百人之事業單位，始得輔以半定量之評估模式或工具實施之"],"a",
 "第9條後段允許必要時輔以其他半定量、定量之評估模式或工具，但不得取代依勞工作業環境監測實施辦法所定之監測。第8條第1項則要求依有科學根據之採樣分析方法或運用定量推估模式實施暴露評估，適用對象為特別危害健康作業勞工一百人以上或總勞工人數五百人以上之事業單位。",
 "May other assessment models or tools supplement the required environment monitoring?",
 ["Where necessary other semi-quantitative or quantitative models or tools may supplement the assessment result","No other model or tool may be used, and the result must rest solely on sampling and analysis data alone","Qualitative models or tools may wholly replace environment monitoring, so no sampling analysis is needed","Only enterprises with fewer than one hundred workers may supplement with semi-quantitative models or tools"],
 "Article 9 allows supplementary models where necessary."),

(GR,"第11條",2,"分級管理-紀錄保存",
 "雇主依本辦法採取之評估方法及分級管理措施，其紀錄應如何處理及保存多久？",
 ["應作成紀錄留存備查，至少保存三年","應作成紀錄留存備查，至少保存一年","應作成紀錄留存備查，至少保存十年","應作成紀錄陳報檢查機構保存三十年"],"a",
 "第11條：雇主依本辦法採取之評估方法及分級管理措施，應作成紀錄留存備查，至少保存三年。相較之下，特定化學物質危害預防標準第34條之搶救訓練紀錄保存三年，第41條特定管理物質之作業紀錄則須自作業之日起保存三十年。",
 "How must records of assessment methods and grading measures be kept, and for how long?",
 ["They must be made into records kept on file for inspection for at least three years","They must be made into records kept on file for inspection for at least one year","They must be made into records kept on file for inspection for at least ten years","They must be reported to the inspection agency and kept on file for thirty years"],
 "Article 11 requires records kept at least three years."),

(GR,"第12條",1,"分級管理-施行日期",
 "危害性化學品評估及分級管理辦法之施行日期為何？",
 ["本辦法自中華民國一百零四年一月一日施行","本辦法自中華民國一百零三年七月三日施行","本辦法自中華民國一百零三年十二月三十一日施行","本辦法自中華民國一百零五年一月一日施行"],"a",
 "第12條：本辦法自中華民國一百零四年一月一日施行。本辦法係一百零三年十二月三十一日訂定發布，惟明定自一百零四年一月一日始行施行。至粉塵危害預防標準一百零三年六月二十五日修正條文則自一百零三年七月三日施行。",
 "When did the Chemical Assessment and Grading Management Regulations take effect?",
 ["These Regulations took effect on 1 January 2015, being year 104 of the ROC calendar","These Regulations took effect on 3 July 2014, being year 103 of the ROC calendar","These Regulations took effect on 31 December 2014, being year 103 of the ROC calendar","These Regulations took effect on 1 January 2016, being year 105 of the ROC calendar"],
 "Article 12 sets effect from 1 January 2015."),
]
