# -*- coding: utf-8 -*-
# 第 12 批（J3）：溫室氣體認證機構及查驗機構管理辦法（ENV-166）第1條～第38條；環境檢驗測定機構違反環保法規罰鍰額度裁罰準則（ENV-207）第1條～第7條
L = "ENV-166"
P = "ENV-207"
Q = [
(L,"第1條",1,"查驗機構-授權依據",
 "溫室氣體認證機構及查驗機構管理辦法係依據下列何項規定訂定？",
 ["氣候變遷因應法第二十二條第二項及第三項","氣候變遷因應法第二十一條第一項及第二項","空氣污染防制法第二十二條第二項及第三項","溫室氣體減量及管理法第二十五條第二項規定"],"a",
 "第1條：本辦法依氣候變遷因應法第22條第2項及第3項規定訂定之。第2條第7款至第9款並以本法第21條第1項、第25條第2項、第37條第1項及第2項分別界定組織型、專案型及產品碳足跡查驗。",
 "Under which provision are these Regulations on accreditation and verification bodies issued?",
 ["Article 22, Paragraphs 2 and 3 of the Climate Change Response Act","Article 21, Paragraphs 1 and 2 of the Climate Change Response Act","Article 22, Paragraphs 2 and 3 of the Air Pollution Control Act","Article 25, Paragraph 2 of the Greenhouse Gas Reduction Act"],
 "Article 1."),

(L,"第2條",3,"查驗機構-名詞定義",
 "本辦法所稱「查證」與「確證」之區別為何？",
 ["查證係就盤查、自願減量專案或產品碳足跡結果之歷史數據與資訊等聲明評估是否實質上正確；確證係對未來活動結果之聲明評估其假設、限制及方法之合理性","查證係對未來活動結果之聲明評估其假設限制及方法之合理性；確證則係就歷史數據與資訊等聲明評估其是否實質上正確之查核作業程序","查證係由認證機構對查驗機構所為之能力評估；確證則係由查驗機構對事業所提出之各項歷史排放數據所進行之書面審查及現場評鑑作業","查證係指以書面審查總部評鑑及見證評鑑方式認可查驗能力；確證則指評估排放量調查過程累積之錯誤遺漏及誤導是否逾越實質性門檻"],"a",
 "第2條第10款：查證指查驗機構依據事業或各級政府執行盤查、自願減量專案或產品碳足跡結果之歷史數據與資訊等聲明，評估是否實質上正確之過程。第11款：確證指查驗機構對於所提出之自願減量專案未來活動結果之聲明，評估其各項假設、限制及方法合理性之過程。",
 "How do verification and validation differ under these Regulations?",
 ["Verification assesses whether historical data statements from inventories, projects or footprints are materially correct; validation assesses assumptions, limits and methods of future claims","Verification assesses assumptions, limits and methods of statements about future results; validation checks whether historical data and information statements are materially correct","Verification is the accreditation body assessment of a verification body capability; validation is the body documentary and on-site review of an enterprise historical emission data","Verification means recognizing capability by document review, headquarters and witness assessment; validation means judging whether errors exceed the materiality threshold"],
 "Article 2, Subparagraphs 10 and 11."),

(L,"第3條",2,"查驗機構-認證機構資格",
 "認證機構除應符合ISO／IEC 17011資格外，尚應符合下列何種條件之一？",
 ["國際認證論壇（IAF）會員、已簽訂國際溫室氣體多邊相關承認協議，或其他經中央主管機關認可之國際或區域性驗證機構認證組織之會員或附屬會員","經濟部標準檢驗局所核發之實驗室認證證書持有者、已與三個以上國家簽署雙邊合作備忘錄，或經目的事業主管機關指定之財團法人研究機構","國內大專校院所設立之環境研究中心、已於國內執行溫室氣體查驗業務滿五年之機構，或經中央主管機關公告之公營事業所屬檢驗單位","聯合國氣候變化綱要公約秘書處登錄之指定經營實體、已取得產品碳足跡查驗許可證之機構，或國內外經教育部承認之大專校院附屬機構"],"a",
 "第3條：認證機構除應符合ISO／IEC 17011建立及實施查驗機構認證評鑑制度之資格外，並應符合下列條件之一：一、國際認證論壇（IAF）會員；二、已簽訂國際溫室氣體多邊相關承認協議；三、其他經中央主管機關認可之國際或區域性驗證機構認證組織之會員或附屬會員。",
 "Besides ISO/IEC 17011, which condition must an accreditation body satisfy?",
 ["Membership of the International Accreditation Forum, a signed international greenhouse gas multilateral recognition arrangement, or membership of another recognized regional accreditation organization","Holding a laboratory accreditation certificate from the Bureau of Standards, having bilateral memoranda with three or more countries, or being a designated research foundation","Being an environmental research centre of a domestic university, having five years of domestic verification practice, or being an inspection unit of an announced state enterprise","Being a designated operational entity registered with the UNFCCC secretariat, already holding a product carbon footprint verification permit, or being affiliated with a recognized university"],
 "Article 3."),

(L,"第4條",2,"查驗機構-認證機構核可",
 "執行溫室氣體查驗機構認證業務之機關（構），應檢具何種文件報請中央主管機關核可？",
 ["第三條資格證明文件影本、品質手冊、辦理查驗機構認證評鑑及監督作業規範及程序，以及其他中央主管機關指定文件","查驗作業計畫書、查驗實績證明文件、查驗人員名單及其學經歷證明，以及其他經中央主管機關所指定之相關文件","機構設立證明文件、負責人身分證明影本、溫室氣體認證證書影本，以及查驗聲明書樣本與查驗總結報告樣本文件","前一年度執行成果報告、外部評鑑報告及處理結果、申訴紀錄及辦理情形，以及評鑑人力之遴選訓練派遣考核紀錄"],"a",
 "第4條：執行溫室氣體查驗機構認證業務之機關（構）應檢具第3條資格證明文件影本、品質手冊、辦理查驗機構認證評鑑及監督作業規範及程序、其他中央主管機關指定文件，報請中央主管機關核可，始得作為中央主管機關委託之認證機構。",
 "What documents must a body file to be recognized as an accreditation body?",
 ["Copies of the Article 3 qualification proofs, a quality manual, its accreditation, assessment and surveillance rules and procedures, and other designated documents","A verification work plan, verification performance proofs, a roster of verification personnel with their credentials, and other documents designated by the authority","Establishment certificates, the representative identity document, a copy of the greenhouse gas accreditation certificate, and sample statements and summary reports","The prior year performance report, external assessment reports and outcomes, complaint records and handling, and assessor selection and training records"],
 "Article 4."),

(L,"第5條",1,"查驗機構-認證業務",
 "認證機構之認證業務範圍包括下列何者？",
 ["受理及審查查驗機構申請認證案件、依認證合格查驗項目發給認證證書、對認證合格之查驗機構實施評鑑及監督作業","核發查驗機構許可證、審查查驗人員資格並登錄人員清冊、對查驗機構違規行為裁處罰鍰及廢止其許可證等事項","訂定溫室氣體盤查登錄辦法、核定事業年度排放量、核發減量額度並核撥至排放源帳戶等溫室氣體管理相關業務","辦理查驗人員在職訓練並核發合格證明、受理事業排放量申報、執行事業排放源之現場稽查及採樣分析等事項"],"a",
 "第5條：認證機構之認證業務為受理及審查查驗機構申請認證之案件、依認證合格之查驗項目發給查驗機構認證證書、對經其認證合格之查驗機構實施評鑑及監督作業、其他經中央主管機關公告與認證有關之業務。查驗機構許可證則由中央主管機關核發（第14條、第16條）。",
 "What falls within an accreditation body accreditation business?",
 ["Accepting and reviewing accreditation applications, issuing accreditation certificates for approved scopes, and assessing and monitoring accredited verification bodies","Issuing verification body permits, reviewing personnel qualifications and registering the roster, and fining or revoking the permits of non-compliant bodies","Setting inventory registration rules, approving annual enterprise emissions, and issuing reduction credits into emission source accounts under the Act","Running in-service training and issuing certificates, receiving emission reports, and conducting on-site inspection and sampling at emission sources"],
 "Article 5."),

(L,"第6條",3,"查驗機構-認證機構義務",
 "認證機構執行認證業務時，關於文件修訂及成果報告之規定為何？",
 ["品質手冊及作業規範程序有增刪修訂必要者，應於變更後十五日內檢附修正前後對照表送中央主管機關；並應於每年三月三十一日前提送前一年度執行成果報告","品質手冊及作業規範程序有增刪修訂必要者，應於變更前六十日檢附對照表報請中央主管機關核准；並應於每年十二月三十一日前提送當年度執行成果報告","品質手冊及作業規範程序有增刪修訂必要者，得自行修訂無須送中央主管機關；並應於每二年六月三十日前提送前二年度之認證業務執行成果報告","品質手冊及作業規範程序有增刪修訂必要者，應於變更後九十日內函報備查；並應於每年一月三十一日前提送前一年度執行成果報告及財務報表"],"a",
 "第6條第1項第2款：品質手冊及認證評鑑監督作業規範程序有增刪修訂之必要，應於變更後十五日內檢附修正前後對照表送中央主管機關。第4款：應於每年三月三十一日前向中央主管機關提送前一年度之執行成果報告。第2項並列成果報告應包含外部評鑑報告及處理結果、對查驗機構之評鑑及處置結果、申訴紀錄、評鑑人力遴選訓練派遣及考核紀錄等。",
 "What are the rules on document revision and the annual performance report?",
 ["Revisions to the quality manual and procedures must be filed with a comparison table within fifteen days; the prior year performance report is due by 31 March each year","Revisions must be approved by the authority sixty days in advance with a comparison table; the current year performance report is due by 31 December each year","Revisions may be made freely without filing them with the authority at all; a performance report covering two years is due by 30 June every second year","Revisions must be reported for recordation within ninety days; the prior year performance report and financial statements are due by 31 January each year"],
 "Article 6."),

(L,"第7條",1,"查驗機構-認證稽查",
 "中央主管機關對認證機構之稽查作業，其規定為何？",
 ["得不定期派員攜帶證明文件，進入認證機構或認證現場進行稽查，認證機構應提供必要文件及說明資料","應於每年固定日期會同認證機構代表辦理稽查，並須於稽查前三十日以書面通知認證機構預作準備","僅得就認證機構提送之書面成果報告進行審閱，不得進入認證機構或認證現場執行任何實地稽查作業","應委由國際認證論壇派員辦理稽查，中央主管機關不得自行派員進入認證機構或認證現場進行查核"],"a",
 "第7條：中央主管機關得不定期派員攜帶證明文件，進入認證機構或認證現場進行稽查作業，稽查時認證機構應提供必要文件及說明資料。第8條第1款並定違反第7條規定者，中央主管機關得停止委託其認證業務。",
 "How may the central competent authority inspect an accreditation body?",
 ["It may send officers with credentials at any time into the body or the accreditation site, and the body must supply the necessary documents and explanations","It must inspect on a fixed date each year together with the body representatives, giving thirty days written notice before the inspection takes place","It may only review the written performance reports submitted, and may never enter the body premises or an accreditation site for any field inspection","It must commission the International Accreditation Forum to inspect, and may not send its own officers into the body or the accreditation site"],
 "Article 7."),

(L,"第8條",2,"查驗機構-停止委託",
 "認證機構有下列何種情形，中央主管機關得停止委託其認證業務？",
 ["違反第三條資格條件或第七條稽查規定、未依核可品質手冊執行認證經限期改善屆期未改善、經稽查認有影響認證品質之重大缺失、自行停止認證業務停業歇業或解散","認證機構所認證之查驗機構家數未達五家、認證收費標準高於中央主管機關公告費率、未於國內設置分支機構或未聘用具本國籍之評鑑人員等情形","認證機構未參加中央主管機關舉辦之年度研討會、未於官方網站公開所有認證作業紀錄、未定期辦理員工滿意度調查等程序性未盡事項","認證機構之評鑑人員曾任職於受認證之查驗機構、認證作業採用外文文件而未附中文譯本、認證證書有效期限超過三年等情形"],"a",
 "第8條：認證機構有違反第3條所定資格條件或第7條規定、未依第6條第1項第1款執行認證業務經通知限期改善屆期未完成改善、經稽查認有足以影響認證品質之重大缺失、自行停止認證業務停業歇業或解散等情形之一者，中央主管機關得停止委託其認證業務。",
 "When may the authority stop entrusting accreditation business to a body?",
 ["Breach of the Article 3 qualifications or Article 7 inspection duty, failure to follow the approved manual after an improvement order, major quality defects found on inspection, or ceasing business","Having accredited fewer than five verification bodies, charging fees above the announced rate, lacking a domestic branch office, or not employing assessors of local nationality","Not attending the annual seminar held by the authority, not publishing all accreditation records on its website, or not conducting regular staff satisfaction surveys","Employing assessors who once worked for an accredited verification body, using foreign-language documents without any Chinese translation, or issuing accreditation certificates valid for over three years"],
 "Article 8."),

(L,"第9條",2,"查驗機構-查驗類別",
 "中央主管機關許可查驗機構執行查驗業務之查驗類別為何？",
 ["組織型、專案型、產品碳足跡，及其他經中央主管機關公告之查驗類別及其查驗項目","組織型、專案型、碳費申報型，及其他經目的事業主管機關指定之查驗類別及項目","盤查登錄型、抵換專案型、碳權交易型，及其他經行政院核定公告之查驗類別項目","確證型、查證型、重要項目評估型，及其他經國際認證論壇認可之查驗類別及項目"],"a",
 "第9條：中央主管機關許可查驗機構執行查驗業務之查驗類別為組織型（查驗項目如附表一）、專案型（如附表二）、產品碳足跡（如附表三）及其他經中央主管機關公告之查驗類別及其查驗項目。第2條第7款至第9款並分別定義各查驗類別所依據之本法條文。",
 "What verification categories may be permitted?",
 ["Organization type, project type, product carbon footprint, and other categories and scopes announced by the central competent authority","Organization type, project type, carbon fee filing type, and other categories designated by the relevant industry regulator","Inventory registration type, offset project type, carbon trading type, and other categories approved and announced by the Executive Yuan","Validation type, verification type, key item assessment type, and other categories recognized by the International Accreditation Forum"],
 "Article 9."),

(L,"第10條",3,"查驗機構-許可條件",
 "申請查驗機構許可證者，各查驗類別應配置之查驗人員員額為何？",
 ["組織型至少三名查驗人員其中二名為專職主導查驗員；專案型至少二名專職主導查驗員；產品碳足跡至少二名專職主導查驗員","組織型至少二名查驗人員其中一名為專職主導查驗員；專案型至少三名專職主導查驗員；產品碳足跡至少三名專職主導查驗員","組織型至少五名查驗人員其中三名為專職主導查驗員；專案型至少四名專職主導查驗員；產品碳足跡至少一名專職主導查驗員","組織型至少三名專職主導查驗員；專案型至少二名查驗員即可無須主導查驗員；產品碳足跡至少一名兼職之主導查驗員亦可"],"a",
 "第10條第2款：組織型查驗類別下置至少三名查驗人員，其中二名為專職主導查驗員；專案型查驗類別下置至少二名專職主導查驗員；產品碳足跡查驗類別下置至少二名專職主導查驗員。第1款並定申請者應為非公營事業之公司、財團法人、公營事業或非環境保護主管機關之政府機關（構）；第3款應取得溫室氣體認證證書。",
 "What personnel numbers must an applicant verification body maintain?",
 ["Organization type needs at least three personnel including two full-time lead verifiers; project type and product footprint each need at least two full-time lead verifiers","Organization type needs at least two personnel including one full-time lead verifier; project type and product footprint each need at least three full-time lead verifiers","Organization type needs at least five personnel including three full-time lead verifiers; project type needs four and product footprint needs one full-time lead verifier","Organization type needs at least three full-time lead verifiers; project type needs only two verifiers with no lead verifier; product footprint may use a part-time lead"],
 "Article 10, Subparagraph 2."),

(L,"第11條",3,"查驗機構-人員資格",
 "查驗人員之基本資格條件為何？",
 ["國內外經教育部承認之大專以上畢業或同等學歷；從事環境保護管理、能源、職安衛、風險或品質管理、農牧、森林管理等二年經驗或查驗經驗二年以上；並完成指定訓練課程取得合格證明","國內外經教育部承認之碩士以上畢業或同等學歷；從事環境保護或能源管理等五年經驗或查驗經驗三年以上；並取得國際認證論壇核發之主導稽核員國際證照","高中職以上畢業或同等學歷即可；從事任何行業之工作經驗一年以上；並經查驗機構自行辦理之內部訓練評核及格後即得登錄於人員清冊執行查驗","國內外經教育部承認之大專以上畢業或同等學歷；並具備會計師、律師或技師等專門職業及技術人員證照；且完成中央主管機關辦理之訓練課程二十四小時以上取得合格證明"],"a",
 "第11條第1項：查驗人員應具大專以上畢業或同等學歷；從事環境保護或管理、能源技術或管理、職業安全衛生、風險管理、品質管理、農牧經營、森林管理等二年經驗，或從事查驗經驗二年以上；並完成中央主管機關或其指定機關（構）辦理之訓練課程並取得訓練合格證明文件。第2項另定各類查驗人員之查驗實績。",
 "What basic qualifications must verification personnel meet?",
 ["A recognized college degree or equivalent; two years experience in environment, energy, safety, risk or quality management, farming or forestry, or two years of verification work; plus designated training","A recognized master degree or equivalent; five years in environmental or energy management or three years of verification work; plus an international lead auditor certificate from the IAF","A senior high school diploma or equivalent; one year of work experience in any industry; plus passing internal training run by the verification body before being registered on the roster","A recognized college degree or equivalent; a professional and technical licence as an accountant, lawyer or engineer; plus at least twenty-four hours of training courses run by the central competent authority"],
 "Article 11, Paragraph 1."),

(L,"第12條",3,"查驗機構-增列項目",
 "組織型及專案型查驗人員欲增列查驗項目，至少應具備之相關經歷為何？",
 ["與申請查驗項目相關工作經驗至少六個月、全程參與該查驗項目至少二件查驗案件，或完成相關訓練課程至少十六小時及全程參與至少一件查驗案件","與申請查驗項目相關工作經驗至少三年、全程參與該查驗項目至少五件查驗案件，或完成相關訓練課程至少四十小時及全程參與至少三件查驗案件","與申請查驗項目相關工作經驗至少一個月、全程參與該查驗項目至少一件查驗案件，或完成相關訓練課程至少四小時而無須參與任何案件","僅需取得認證機構核發之該查驗項目認證證書，或經查驗機構負責人書面推薦，即得逕行增列該查驗項目而無須任何工作經驗"],"a",
 "第12條第1項：組織型及專案型查驗人員至少應具備下列與申請查驗項目相關經歷之一始得增列該查驗項目：一、相關工作經驗至少六個月（申請組織型查驗項目屬使用電力之生產及服務者，得以查驗工作經驗二年以上為之）；二、全程參與該查驗項目至少二件查驗案件；三、完成相關訓練課程至少十六小時及全程參與至少一件查驗案件。",
 "What experience lets organization or project type personnel add a verification scope?",
 ["At least six months of related work experience, full participation in at least two cases of that scope, or sixteen hours of related training plus one full case","At least three years of related work experience, full participation in at least five cases of that scope, or forty hours of related training plus three full cases","At least one month of related work experience, full participation in at least one case of that scope, or four hours of related training with no case at all","Merely holding an accreditation certificate for that scope, or a written recommendation from the head of the body, with no work experience required"],
 "Article 12, Paragraph 1."),

(L,"第13條",3,"查驗機構-首批人員",
 "申請查驗機構許可證之首批查驗人員未能符合查驗實績規定者，其「同等能力」指為何？",
 ["組織型及專案型指經認證機構派員見證下完成一件現場查驗案件且通過評鑑、三年內具ISO 14064查驗實績並通過認證機構評鑑，或其他經中央主管機關認可之條件","組織型及專案型指經查驗機構負責人推薦並具備五年以上相關產業工作經驗、或曾任職於國外驗證機構滿三年，並取得該機構所出具之工作證明文件","組織型及專案型指已完成中央主管機關辦理之訓練課程四十小時以上、或取得國內大專校院碩士以上學位且主修環境工程相關系所之畢業證書影本","組織型及專案型指三年內具ISO 14067產品碳足跡查驗實績、或曾參與國家溫室氣體排放清冊編製作業並經行政院環境部出具服務年資證明文件"],"a",
 "第13條第1項及第2項：首批查驗人員未能符合第11條第2項查驗實績規定者應具備同等能力並於申請時併同檢具證明文件；組織型及專案型之同等能力指經認證機構派員見證下完成一件現場查驗案件且該案件需通過評鑑、三年內具ISO 14064組織型或專案型查驗實績並通過認證機構評鑑，或其他經中央主管機關認可之條件。第3項產品碳足跡首批人員則以ISO 14067實績認定。",
 "What counts as equivalent capability for first-batch verification personnel?",
 ["For organization and project types: one witnessed on-site case that passes assessment, ISO 14064 verification experience within three years passing assessment, or other recognized conditions","For organization and project types: a recommendation from the head of the body plus five years of industry experience, or three years at a foreign verification body with proof of service","For organization and project types: completing at least forty hours of training run by the central authority, or holding a domestic master degree in an environmental engineering programme","For organization and project types: ISO 14067 product carbon footprint experience within three years, or participation in the national inventory compilation with a service certificate"],
 "Article 13, Paragraphs 1 and 2."),

(L,"第14條",3,"查驗機構-許可申請",
 "申請查驗機構許可證者，應上傳至指定資訊平台之資料包括下列何者？",
 ["設立證明及負責人身分證明文件影本、溫室氣體認證證書影本、查驗作業計畫書、查驗實績證明文件、依查驗類別設置之查驗人員名單及其學經歷訓練證明","品質手冊、辦理查驗機構認證評鑑及監督作業規範及程序、前一年度接受外部評鑑或稽核之報告及處理結果、評鑑人力之遴選訓練派遣及考核紀錄","事業溫室氣體盤查報告書、排放量登錄資料、查驗總結報告正本、內部技術審查紀錄、獨立性公正性及利益衝突評估紀錄與簽發之聲明或意見","減量方法草案及其應用範例、查驗機構出具之評估報告、專案計畫書、監測報告書，以及未向其他國內外機關重複申請減量額度之證明文件"],"a",
 "第14條：申請查驗機構許可證者應上傳設立證明文件及負責人身分證明文件影本、溫室氣體認證證書影本、查驗作業計畫書、查驗實績證明文件（查驗聲明書樣本、查驗總結報告樣本及查驗作業過程紀錄文件）、依許可查驗類別設置之查驗人員名單及其簽名身分學經歷查驗項目實績訓練合格證明文件影本及其他指定文件。",
 "What must be uploaded when applying for a verification body permit?",
 ["Establishment and representative identity copies, the accreditation certificate copy, the verification work plan, performance proofs, and the personnel roster with credentials and training proofs","The quality manual, accreditation assessment and surveillance rules and procedures, last year external assessment reports and outcomes, and assessor selection and training records","The enterprise inventory report, registered emission data, original verification summary reports, internal technical review records, impartiality assessments and issued statements","The draft reduction methodology and its application examples, a verification body assessment report, the project plan, the monitoring report, and proof of no duplicate credit application"],
 "Article 14."),

(L,"第15條",3,"查驗機構-作業計畫書",
 "查驗作業計畫書所定「查驗程序及方法」應涵蓋之執行重點為何？",
 ["合約審查確認實質性門檻及保證等級、組成查驗小組、策略分析與風險評估、查驗作業規劃含取樣計畫及人天數安排原則、查驗作業執行應遵循事項、查驗總結報告撰寫","機構組織編制人員配置與職掌、查驗類別查驗項目及依據標準、品質保證程序、查驗結果之審查及決定、機構標誌使用條件及處理方式與抱怨申訴處理程序","查驗人員之遴選資格訓練評估及組成查驗小組規定、內部技術審查人員及技術專家資格規定、公正性及利益衝突迴避之評估及落實方式之說明事項","查驗機構名稱及地址、機構負責人姓名、許可證有效期限、許可查驗類別及查驗項目，以及其他經中央主管機關所指定應記載之各項事項"],"a",
 "第15條第4款：查驗程序及方法應涵蓋合約審查、確認實質性門檻及保證等級、組成查驗小組、策略分析與風險評估、查驗作業規劃（至少包含取樣計畫及人天數安排原則）、查驗作業執行應遵循事項、查驗總結報告撰寫。其餘各款另定組織編制、品質保證程序、標誌使用、公正性及抱怨申訴處理程序等內容。",
 "What must the verification procedures and methods section cover?",
 ["Contract review with materiality threshold and assurance level, team formation, strategic analysis and risk assessment, sampling and person-day planning, execution rules, and report writing","Organizational structure and duties, verification categories, scopes and reference standards, quality assurance procedures, review and decision on results, logo use and complaint handling","Rules on selecting, training and assessing verification personnel and forming teams, qualifications of internal technical reviewers and experts, and impartiality assessment methods","The body name and address, the name of its responsible person, the permit validity period, the permitted categories and scopes, and other items designated by the authority"],
 "Article 15, Subparagraph 4."),

(L,"第16條",1,"查驗機構-許可證記載",
 "查驗機構許可證應記載之事項為何？",
 ["機構名稱及地址、機構負責人姓名、有效期限、許可查驗類別及查驗項目，及其他經中央主管機關指定事項","機構名稱及地址、查驗人員姓名及身分證字號、查驗實績件數、營業額，及其他經中央主管機關指定事項","機構名稱及地址、認證機構名稱、認證證書字號、品質手冊版次，及其他經中央主管機關所指定之事項","機構名稱及地址、實質性門檻百分比、保證等級、查驗收費標準，及其他經中央主管機關指定之事項"],"a",
 "第16條：查驗機構許可證應記載機構名稱及地址、機構負責人姓名、有效期限、許可查驗類別及查驗項目及其他經中央主管機關指定事項。第22條第1項並定許可證有效期限最長為三年，每次展延期限最長為三年。",
 "What must a verification body permit state?",
 ["The body name and address, the responsible person name, the validity period, the permitted categories and scopes, and other designated matters","The body name and address, personnel names and ID numbers, the number of cases performed, turnover, and other designated matters","The body name and address, the accreditation body name, certificate number, quality manual version, and other designated matters","The body name and address, the quantitative materiality threshold percentage, the assurance level, the fee schedule, and other designated matters"],
 "Article 16."),

(L,"第17條",2,"查驗機構-人員清冊",
 "查驗機構之查驗人員經中央主管機關審查許可後，應登錄納入人員清冊之事項為何？",
 ["姓名、身分證明文件字號及簽名、主導查驗員及查驗員之查驗類別及查驗項目、查驗機構任用方式，及其他經中央主管機關指定事項","姓名、學歷及畢業科系、歷年查驗案件清單及其查驗結果、每年在職訓練時數、薪資給付標準，及其他經指定之事項","姓名、身分證明文件字號、戶籍地址及聯絡電話、緊急聯絡人、健康檢查紀錄，及其他經中央主管機關所指定之事項","姓名、認證機構所核發之個人認證證書字號、國際證照種類及有效期限、外語能力證明，及其他經指定之事項"],"a",
 "第17條：查驗機構之查驗人員及其許可查驗項目經中央主管機關審查許可後，由查驗機構登錄姓名、身分證明文件字號及簽名、主導查驗員及查驗員之查驗類別及查驗項目、查驗機構任用方式及其他經中央主管機關指定事項，納入人員清冊。第2條第5款並定人員清冊之定義。",
 "What items are registered in the personnel roster after approval?",
 ["Name, identity document number and signature, the categories and scopes of lead verifiers and verifiers, the employment arrangement, and other designated matters","Name, education and major, a list of past cases and their outcomes, annual in-service training hours, salary levels, and other designated matters","Name, identity document number, household address and phone, emergency contact, health examination records, and other designated matters","Name, the individual accreditation certificate number issued by the accreditation body, international licences and validity, language proof, and other matters"],
 "Article 17."),

(L,"第18條",3,"查驗機構-增減列類別",
 "查驗機構申請增列或減列許可查驗類別或查驗項目，其應上傳資料之規定為何？",
 ["增列應上傳第十四條第二款至第六款規定資料；減列應上傳第十四條第三款及第六款規定資料，並均檢具申請書向中央主管機關提出申請","增列應上傳第十四條第一款至第三款規定資料；減列應上傳第十四條第四款及第五款規定資料，並均檢具申請書向認證機構提出申請","增列及減列均應上傳第十四條全部各款規定資料，並檢具申請書向中央主管機關提出申請，經核准後始得辦理類別或項目之異動","增列應報請中央主管機關核准；減列僅需於事實發生後九十日內函知中央主管機關備查，無須上傳任何資料至指定資訊平台"],"a",
 "第18條第1項：增列許可查驗類別或查驗項目，應上傳第14條第2款至第6款規定之資料並檢具申請書向中央主管機關提出申請。第2項：減列者應上傳第14條第3款及第6款規定之資料。第3項並定配合政策需求申請增列查驗項目經認可者，得以認證機構受理該查驗項目認證申請之證明文件替代第14條第2款文件。",
 "What must be uploaded to add or remove a permitted category or scope?",
 ["Adding requires the items in Article 14, Subparagraphs 2 to 6; removing requires Subparagraphs 3 and 6; both are filed with an application to the central authority","Adding requires the items in Article 14, Subparagraphs 1 to 3; removing requires Subparagraphs 4 and 5; both are filed with an application to the accreditation body","Both adding and removing require all items listed in Article 14, filed with an application to the central competent authority and effective only after approval","Adding requires approval by the authority; removing only requires a notice for recordation within ninety days, with nothing uploaded to the designated platform"],
 "Article 18."),

(L,"第19條",2,"查驗機構-變更登載",
 "查驗機構變更機構名稱、地址或負責人時，應於何時、如何辦理？",
 ["應於事實發生後三十日內上傳第十四條第一款及第二款規定資料至指定資訊平台，並檢具申請書向中央主管機關申請變更許可證登載事項","應於事實發生前六十日上傳第十四條第三款及第四款規定資料至指定資訊平台，並檢具申請書向中央主管機關申請核准後始得變更","應於事實發生後九十日內以書面函知認證機構辦理認證證書換發，中央主管機關之許可證則俟有效期限屆滿申請展延時一併更新","應於事實發生後三十日內於機構網站公告變更內容即可，無須上傳資料至指定資訊平台，亦無須向中央主管機關申請變更登載"],"a",
 "第19條：查驗機構變更機構名稱、地址或負責人，應於事實發生後三十日內，依中央主管機關指定格式上傳第14條第1款及第2款規定資料至指定資訊平台，並檢具申請書向中央主管機關申請變更許可證登載事項。第33條第7款並定違反第19條規定一年內累計達三次者，依本法第49條第2項規定辦理。",
 "How must a change of body name, address or responsible person be handled?",
 ["Upload the Article 14 Subparagraph 1 and 2 items to the platform within thirty days of the event and apply to the authority to amend the permit entries","Upload the Article 14 Subparagraph 3 and 4 items sixty days before the event and obtain the authority approval before the change may take effect","Notify the accreditation body in writing within ninety days to reissue the certificate, updating the permit only when applying for renewal at expiry","Announce the change on the body website within thirty days; no upload to the platform and no application to amend the permit entries are required"],
 "Article 19."),

(L,"第20條",3,"查驗機構-人員清冊變更",
 "查驗機構申請變更人員清冊，關於「減列查驗人員」之辦理期限規定為何？",
 ["減列查驗人員或查驗人員減列部分查驗類別或查驗項目者，應於事實發生後三十日內檢具相關證明文件辦理","減列查驗人員或查驗人員減列部分查驗類別或查驗項目者，應於事實發生前三十日檢具相關證明文件辦理","減列查驗人員或查驗人員減列部分查驗類別或查驗項目者，應於事實發生後九十日內檢具相關證明文件辦理","減列查驗人員或查驗人員減列部分查驗類別或查驗項目者，應於當年度十二月三十一日前彙整後一併辦理"],"a",
 "第20條第2款：減列查驗人員或查驗人員減列部分查驗類別或查驗項目，應於事實發生後三十日內檢具相關證明文件為之。第1款增列查驗人員、查驗員與主導查驗員互換及增列查驗類別項目者，應檢具第14條第4款至第6款規定資料；第3款其他變更事項亦應於事實發生後三十日內辦理。",
 "What deadline applies to removing personnel from the roster?",
 ["Removal of personnel or of part of their categories or scopes must be filed with supporting documents within thirty days after the event","Removal of personnel or of part of their categories or scopes must be filed with supporting documents thirty days before the event","Removal of personnel or of part of their categories or scopes must be filed with supporting documents within ninety days after the event","Removal of personnel or of part of their categories or scopes may be compiled and filed together by 31 December of that year"],
 "Article 20, Subparagraph 2."),

(L,"第21條",2,"查驗機構-員額補足",
 "查驗機構之查驗人員因變更致不符合第十條第二款員額規定時，應如何處理？",
 ["應於事實發生後三十日內補足；未於期限內補足員額者，查驗機構應停止查驗業務","應於事實發生後九十日內補足；未於期限內補足員額者，中央主管機關應廢止許可證","應於事實發生後六個月內補足；於補足前仍得繼續執行原許可之全部查驗業務項目","應於次年度一月三十一日前補足；未補足者僅減列該查驗類別而不影響其他業務執行"],"a",
 "第21條：查驗機構之查驗人員因變更致不符合第10條第2款規定員額時，應於事實發生後三十日內補足之；未於期限內補足員額者，查驗機構應停止查驗業務。第33條第2款：未依第21條於期限內補足員額且未停止查驗業務者，依本法第49條第2項規定辦理。",
 "What happens when personnel changes drop the body below the required numbers?",
 ["The shortfall must be made up within thirty days of the event; if not, the body must stop its verification business","The shortfall must be made up within ninety days of the event; if not, the authority must revoke the permit","The shortfall must be made up within six months; all permitted verification business may continue meanwhile","The shortfall must be made up by 31 January of the next year; otherwise only that category is removed"],
 "Article 21."),

(L,"第22條",2,"查驗機構-許可證展延",
 "查驗機構許可證之有效期限及展延申請期間為何？",
 ["有效期限最長為三年，每次展延期限最長為三年；應於有效期限屆滿前三至四個月內上傳規定資料並檢具申請書提出申請","有效期限最長為五年，每次展延期限最長為五年；應於有效期限屆滿前一至二個月內上傳規定資料並檢具申請書提出申請","有效期限最長為三年，每次展延期限最長為一年；應於有效期限屆滿後三個月內補行上傳規定資料並檢具申請書申請","有效期限最長為十年，每次展延期限最長為十年；應於有效期限屆滿前六個月至一年內上傳規定資料並提出展延申請"],"a",
 "第22條第1項：查驗機構許可證有效期限最長為三年，每次展延期限最長為三年。第2項：申請許可證展延應於有效期限屆滿前三至四個月內上傳第14條第2款及第6款規定資料至指定資訊平台，並檢具申請書向中央主管機關提出申請。第23條並定展延審查期間之作業規定。",
 "What are the permit validity period and renewal application window?",
 ["Valid for up to three years and renewable for up to three years each time; apply three to four months before expiry by uploading the required data","Valid for up to five years and renewable for up to five years each time; apply one to two months before expiry by uploading the required data","Valid for up to three years and renewable for only one year each time; apply within three months after expiry by uploading the required data","Valid for up to ten years and renewable for up to ten years each time; apply between six months and one year before expiry with the data"],
 "Article 22."),

(L,"第23條",3,"查驗機構-展延審查",
 "查驗機構依規定期間申請展延，因中央主管機關審查致許可證屆滿前未作成准駁決定者，其效果為何？",
 ["查驗機構於許可證期限屆滿後至作成展延准駁期間內，得依原許可證內容執行查驗作業","查驗機構應自許可證期限屆滿之翌日起停止執行查驗業務，俟准駁決定作成後始得恢復","查驗機構之許可證自期限屆滿之翌日起失其效力，如需繼續執行業務應重新提出申請","查驗機構得繼續執行查驗業務，但應於期限屆滿後三十日內重新申請許可證換發手續"],"a",
 "第23條第2項：查驗機構依第22條第2項規定期間申請展延者，因中央主管機關之審查致許可證期限屆滿前未作成展延准駁決定者，查驗機構於許可證期限屆滿後至作成展延准駁期間內，得依原許可證內容執行查驗作業。第3項未依規定期間申請或展延未通過而再次申請者則應停止執行；第4項未申請展延者許可證失其效力。第1項並定審查期限九十日、補正總日數不得超過九十日。",
 "What follows if a timely renewal application is still under review at expiry?",
 ["The body may keep performing verification under the original permit from expiry until the renewal decision is made","The body must stop verification business from the day after expiry and may resume only once the decision is made","The permit loses effect from the day after expiry, and a fresh application is needed to continue the business","The body may continue business but must reapply for a reissued permit within thirty days after expiry"],
 "Article 23, Paragraph 2."),

(L,"第24條",2,"查驗機構-撤銷廢止",
 "中央主管機關得撤銷、廢止查驗機構許可證或廢止部分查驗類別或查驗項目之情形為何？",
 ["申請文件虛偽不實、經認證機構減列終止或撤銷認證、自行停業或停止查驗項目、歇業或解散、其他違反本辦法規定且情節重大","查驗案件數量連續二年未達十件、查驗收費低於同業平均水準、查驗人員流動率過高、未於指定資訊平台公開營業額等情形","查驗總結報告曾遭受查事業提出異議、查驗人員曾參加中央主管機關在職訓練未取得合格證明、機構標誌設計未經核准等情形","查驗機構未於國內設置實驗室、未取得ISO 17025測試實驗室認證、未聘用具技師資格之查驗人員等未符國際標準之情形"],"a",
 "第24條：查驗機構有依本辦法規定所提申請文件虛偽不實、經認證機構減列終止或撤銷認證、自行停業或停止查驗項目、歇業或解散、其他違反本辦法規定且情節重大等情形之一者，中央主管機關得撤銷、廢止查驗機構許可證或廢止部分查驗類別或查驗項目。",
 "When may a verification body permit be revoked or annulled in whole or part?",
 ["False application documents, reduction, termination or withdrawal of accreditation, voluntary suspension of business or scope, closure or dissolution, or other serious breaches","Fewer than ten cases in two consecutive years, fees below the industry average, high personnel turnover, or failure to publish turnover on the designated platform","An objection raised by a verified enterprise against a summary report, failure of staff to pass in-service training, or an unapproved design of the body logo","Failure to set up a domestic laboratory, lack of ISO 17025 testing laboratory accreditation, or not employing licensed professional engineers as its verification personnel"],
 "Article 24."),

(L,"第25條",3,"查驗機構-公正性",
 "下列何種情況即違反獨立性、公正性及利益衝突迴避規範，中央主管機關得不予認可其查驗結果？",
 ["曾參與該案件之合作協議或顧問服務、過去三年曾輔導該事業執行盤查或建置管理系統、查驗人員過去三年曾受聘於該事業、結案後一年內受聘該事業擔任有給職","查驗機構與該受查事業位於同一直轄市或縣市轄區範圍內、查驗人員與該事業員工曾就讀同一學校科系、查驗機構曾為該事業所屬同業公會之會員等情形","查驗機構之收費金額高於該事業前次所委託之查驗費用、查驗人員曾於公開學術研討會發表與該事業生產製程相關之學術論文等情形","查驗機構所屬查驗人員未滿三名、查驗人員年齡超過六十五歲、查驗人員未取得國際主導稽核員證照等資格面之相關情形"],"a",
 "第25條第2項：查驗機構或查驗人員曾參與該查驗案件之合作協議或顧問服務、過去三年間曾輔導該事業執行盤查自願減量專案抵換專案產品碳足跡或協助建置溫室氣體管理系統、查驗人員過去三年曾受聘於該事業、查驗人員於案件結案後一年內受聘於該事業並擔任有給職、與該事業間有確證查證行為以外之密切商業行為者，即違反獨立性公正性及利益衝突迴避規範，該查驗結果中央主管機關得不予認可。",
 "Which situations breach independence and conflict-of-interest rules?",
 ["Prior participation in a cooperation agreement or consultancy for the case, coaching the enterprise within three years, employment there within three years, or paid employment within a year after closing","The body and the enterprise being located in the same municipality or county, staff having attended the same school, or the body once belonging to the same trade association","The body charging more than the enterprise paid for its previous verification exercise, or a verifier having published an academic conference paper about the production process of that enterprise","The body having fewer than three verification personnel, personnel being over sixty-five years old, or personnel lacking an international lead auditor certificate"],
 "Article 25, Paragraph 2."),

(L,"第26條",3,"查驗機構-實質性門檻",
 "查驗機構執行查證時，其定量實質性門檻及主導查驗員之輪替規定為何？",
 ["應以事業溫室氣體盤查報告書所載總排放量百分之五為定量實質性門檻，並規劃符合合理保證等級之查驗計畫；查證作業不得連續六年由同一主導查驗員執行","應以事業溫室氣體盤查報告書所載總排放量百分之十為定量實質性門檻，並規劃符合有限保證等級之查驗計畫；查證作業不得連續三年由同一主導查驗員執行","應以事業溫室氣體盤查報告書所載總排放量百分之一為定量實質性門檻，並規劃符合合理保證等級之查驗計畫；查證作業不得連續十年由同一查驗機構執行","應由查驗機構與受查事業於合約中自行議定實質性門檻百分比，並規劃符合雙方同意之保證等級；同一主導查驗員之連續執行年限亦不予限制"],"a",
 "第26條第1項第2款：查驗機構執行查證時應以事業溫室氣體盤查報告書所載總排放量百分之五為定量實質性門檻，並規劃符合合理保證等級之查驗計畫；查證作業不得連續六年由同一主導查驗員執行，但更換查驗員確有困難經事業檢具證明文件向中央主管機關提出並經同意者不在此限。第2條第12款並定實質性門檻之定義。",
 "What materiality threshold and lead verifier rotation rules apply?",
 ["Five percent of the total emissions stated in the inventory report is the quantitative materiality threshold with a reasonable assurance plan; one lead verifier may not serve six consecutive years","Ten percent of the total emissions stated in the inventory report is the threshold with a limited assurance plan; one lead verifier may not serve three consecutive years","One percent of the total emissions stated in the inventory report is the threshold with a reasonable assurance plan; one body may not serve ten consecutive years","The body and the enterprise agree the quantitative threshold percentage in their own contract together with a mutually agreed assurance level; no limit applies to consecutive years of service"],
 "Article 26, Paragraph 1, Subparagraph 2."),

(L,"第26條",3,"查驗機構-上傳期限",
 "查驗機構於指定資訊平台辦理上傳作業之期限規定為何？",
 ["執行查驗作業七日前上傳預定行程及查驗人員資料；完成內部技術審查後十五日內上傳實際行程、查驗結果及查驗總結報告；每年二月二十八日前提報前一年案件數量營業額及訓練紀錄","執行查驗作業三十日前上傳預定行程及查驗人員資料；完成內部技術審查後三日內上傳實際行程、查驗結果及查驗總結報告；每年十二月三十一日前提報當年度案件數量","執行查驗作業當日上傳預定行程及查驗人員資料；完成內部技術審查後三個月內上傳實際行程、查驗結果及查驗總結報告；每年六月三十日前提報前一年案件數量","執行查驗作業完成後始須上傳全部行程及查驗人員資料；查驗總結報告得由受查事業自行上傳；案件數量及營業額屬營業秘密無須提報中央主管機關"],"a",
 "第26條第1項第6款：查驗機構應依指定格式至指定資訊平台辦理：執行查驗作業七日前上傳預定行程及查驗人員資料；完成內部技術審查後十五日內上傳實際行程、查驗人員資料、查驗結果、內部技術審查日期及查驗總結報告；確認受查驗者上傳相關資料之正確性；每年二月二十八日前提報前一年查驗項目之案件數量與營業額及人員訓練紀錄。",
 "What upload deadlines apply on the designated information platform?",
 ["Upload the planned schedule and personnel seven days before verification; upload the actual schedule, results and summary report within fifteen days of internal review; report case counts, turnover and training by 28 February","Upload the planned schedule and personnel thirty days before verification; upload the actual schedule, results and summary report within three days of internal review; report case counts by 31 December","Upload the planned schedule and personnel on the day of verification; upload the actual schedule, results and summary report within three months of internal review; report case counts by 30 June","Upload all schedules and personnel details only after the verification is finished; the verified enterprise may upload the summary report itself; case counts and turnover are trade secrets and need not be reported at all"],
 "Article 26, Paragraph 1, Subparagraph 6."),

(L,"第26條",2,"查驗機構-紀錄保存",
 "查驗作業相關紀錄之保存年限規定為何？",
 ["執行組織型及產品碳足跡查驗作業之相關紀錄應至少保存六年；專案型查驗作業之相關紀錄應至少保存至專案計入期結束後六年","執行組織型及產品碳足跡查驗作業之相關紀錄應至少保存三年；專案型查驗作業之相關紀錄應至少保存至專案計入期結束時止","執行組織型及產品碳足跡查驗作業之相關紀錄應至少保存十年；專案型查驗作業之相關紀錄應至少保存至專案註冊完成後十年","執行組織型及產品碳足跡查驗作業之相關紀錄應至少保存一年；專案型查驗作業之相關紀錄由查驗機構視需要自行決定保存年限"],"a",
 "第26條第1項第7款：執行組織型及產品碳足跡查驗作業之相關紀錄應至少保存六年，專案型查驗作業之相關紀錄應至少保存至專案計入期結束後六年。第2項並定紀錄應包含獨立性公正性或利益衝突評估紀錄、各階段查驗紀錄、決定查驗結果之相關紀錄、查驗總結報告、內部技術審查相關紀錄及簽發之聲明或意見。",
 "How long must verification records be retained?",
 ["Organization-type and product footprint verification records for at least six years; project-type records until at least six years after the crediting period ends","Organization-type and product footprint verification records for at least three years; project-type records only until the crediting period ends","Organization-type and product footprint verification records for at least ten years; project-type records until at least ten years after registration","Organization-type and product footprint verification records for at least one year; project-type record retention is decided by the verification body itself as needed"],
 "Article 26, Paragraph 1, Subparagraph 7."),

(L,"第27條",2,"查驗機構-執行件數",
 "查驗機構就其經許可之查驗項目，每年應執行之案件數量及未達成時之補救措施為何？",
 ["每年應至少執行一件案件；未符合者應於當年年底前辦理至少八小時與該查驗項目有關之訓練課程","每年應至少執行三件案件；未符合者應於當年年底前辦理至少二十小時與該查驗項目有關之訓練課程","每年應至少執行五件案件；未符合者應於次年三月底前向中央主管機關申請減列該項查驗項目辦理","每年應至少執行一件案件；未符合者中央主管機關應逕行廢止該查驗項目之許可，不得以訓練替代"],"a",
 "第27條第1項及第2項：查驗機構就其經中央主管機關許可之查驗項目每年應至少執行一件案件；未符合者應於當年年底前辦理至少八小時與該查驗項目有關之訓練課程。第3項：屬增列查驗項目者，應於增列年度之次一年度十二月三十一日前依前二項規定辦理。",
 "How many cases must a body perform each year per permitted scope?",
 ["At least one case per year; if not met, at least eight hours of training on that scope must be held before the end of that year","At least three cases per year; if not met, at least twenty hours of training on that scope must be held before the end of that year","At least five cases per year; if not met, the body must apply by the end of March next year to remove that scope","At least one case per year; if not met, the authority revokes that scope outright and training cannot substitute"],
 "Article 27."),

(L,"第28條",1,"查驗機構-在職訓練",
 "中央主管機關令查驗機構指派查驗人員接受在職訓練時，查驗機構及查驗人員之義務為何？",
 ["查驗機構不得拒絕，經中央主管機關指定參加在職訓練之查驗人員亦不得拒絕；參加訓練之查驗人員應完成訓練取得合格證明","查驗機構得斟酌業務需要決定是否指派人員參加，經指定之查驗人員得以書面敘明理由申請免除參加該次在職訓練之義務","查驗機構應自行辦理在職訓練並報請中央主管機關備查，中央主管機關不得指定特定查驗人員參加其所辦理之訓練課程","查驗機構應指派人員參加但參加者無須取得合格證明，僅需於年度執行成果報告中載明參訓時數即符合本辦法之規定"],"a",
 "第28條第1項：中央主管機關得令查驗機構指派適當之查驗人員接受在職訓練，查驗機構不得拒絕；經中央主管機關指定參加在職訓練之查驗人員亦同。第2項：參加在職訓練之查驗人員應完成訓練取得合格證明。第32條第1項第2款：連續三次未取得訓練合格證明者，得逕予減列該查驗人員。",
 "What duties arise when the authority orders in-service training?",
 ["The body may not refuse, nor may a designated verifier; those attending must complete the training and obtain a certificate of qualification","The body may decide whether to send anyone based on workload, and a designated verifier may apply in writing to be excused from that session","The body must run its own in-service training and file it for recordation; the authority may not designate particular verifiers to attend","The body must send personnel but attendees need no certificate; stating the hours in the annual performance report is sufficient compliance"],
 "Article 28."),

(L,"第29條",2,"查驗機構-人員執行件數",
 "登錄於人員清冊之查驗人員，每年應執行之案件數量及未達成時之補救措施為何？",
 ["每年應至少執行一件全程查驗案件；未符合者應於當年年底前完成至少八小時與查驗技巧方法技術或案例分析有關之訓練課程","每年應至少執行三件全程查驗案件；未符合者應於當年年底前完成至少二十四小時與查驗技巧方法技術有關之訓練課程","每年應至少執行二件全程查驗案件；未符合者應由查驗機構逕予減列該查驗人員，不得以完成訓練課程之方式替代辦理","每年應至少執行一件全程查驗案件；未符合者應於次年度重新參加中央主管機關辦理之查驗人員資格訓練並重新取得合格證明"],"a",
 "第29條第1項及第2項：登錄於人員清冊之查驗人員每年應至少執行一件全程查驗案件；未符合者應於當年年底前完成至少八小時與溫室氣體查驗技巧、方法、技術或案例分析之訓練課程。第3項：屬新增登錄於人員清冊者，應於登錄年度之次一年度十二月三十一日前依前二項規定辦理。第32條第1項第3款並定違反第29條經限期補正屆期未補正者得逕予減列。",
 "How many full cases must each registered verifier perform annually?",
 ["At least one full verification case per year; if not met, at least eight hours of training on verification skills, methods or case analysis by year end","At least three full verification cases per year; if not met, at least twenty-four hours of training on verification skills and methods by year end","At least two full verification cases per year; if not met, the body must remove the verifier and training cannot substitute for the shortfall","At least one full verification case per year; if not met, the verifier must retake the qualification training next year and regain the certificate"],
 "Article 29."),

(L,"第30條",3,"查驗機構-計畫書變更",
 "查驗機構變更查驗作業計畫書之品質保證程序或查驗程序及方法時，應於何時辦理？",
 ["應於事實發生前上傳查驗作業計畫書及修正前後對照表至指定資訊平台，並檢具申請書向中央主管機關提出申請","應於事實發生後三十日內上傳查驗作業計畫書及修正前後對照表至指定資訊平台，向中央主管機關報請備查即可","應於事實發生後九十日內函報中央主管機關，並於下次許可證展延申請時一併檢附修正後之查驗作業計畫書辦理","應於每年年度結束後彙整當年度所有變更事項，於次年三月三十一日前一併上傳修正前後對照表至指定資訊平台"],"a",
 "第30條第1項：查驗機構變更查驗作業計畫書之人員配置與職掌、查驗作業依據、品質保證程序、查驗程序及方法、查驗結果之審查及決定、查驗人員內部技術審查人員及技術專家資格規定、公正性與利益衝突迴避之評估及落實方式，應於事實發生前上傳查驗作業計畫書及修正前後對照表至指定資訊平台並檢具申請書提出申請。第2項：變更組織編制應於完成變更後三十日內為之。",
 "When must changes to the quality assurance or verification procedures be filed?",
 ["Before the change takes place, uploading the revised work plan and a before-and-after comparison table with an application to the authority","Within thirty days after the change, uploading the revised work plan and comparison table to the platform for recordation only","Within ninety days after the change by written notice, attaching the revised work plan when next applying for permit renewal","Compiled after the year ends and uploaded together with all the before-and-after comparison tables by 31 March of the following year"],
 "Article 30, Paragraph 1."),

(L,"第31條",1,"查驗機構-稽查",
 "中央主管機關對查驗機構之稽查權限為何？",
 ["得不定期派員攜帶證明文件，進入查驗機構或查驗現場進行書面或現場稽查工作，並命其提供有關資料","僅得於查驗機構申請許可證或展延時進行書面審查，不得於平時進入查驗機構或查驗現場實施稽查","應委由認證機構代為執行查驗機構之評鑑及監督，中央主管機關本身不得派員進入查驗現場稽查","得進入查驗機構稽查，但不得進入受查事業之查驗現場，且應於稽查前十四日以書面通知查驗機構"],"a",
 "第31條：中央主管機關得不定期派員攜帶證明文件，進入查驗機構或查驗現場，進行書面或現場稽查工作，並命其提供有關資料。第33條第6款：違反第31條規定者，中央主管機關依本法第49條第2項規定辦理。",
 "What inspection powers does the authority have over verification bodies?",
 ["It may send officers with credentials at any time into the body or a verification site for document or on-site inspection and demand relevant data","It may only conduct documentary review when a permit or renewal is applied for, and may not inspect the body or sites at other times","It must commission the accreditation body to assess and monitor verification bodies, and may not send its own officers to a verification site","It may enter the body but not a verified enterprise site, and must give the body fourteen days written notice before inspecting"],
 "Article 31."),

(L,"第32條",3,"查驗機構-人員減列",
 "查驗人員有下列何種情形，中央主管機關得逕予減列人員清冊所載之該查驗人員？並有何後續限制？",
 ["學經歷或訓練合格等證明文件虛偽不實、連續三次未取得在職訓練合格證明、違反第二十九條經限期補正屆期未補正、其他違反本辦法情節重大；因虛偽不實或情節重大而減列者三年內不得登錄","查驗案件曾遭事業客訴、連續二年未執行任何查驗案件、未參加公會舉辦之研習活動、其他經查驗機構認定不適任之情形；經減列者一年內不得登錄於人員清冊","未於期限內繳納查驗人員年費、未於指定資訊平台更新個人聯絡資料、未取得國際主導稽核員證照等情形；經減列之查驗人員五年內不得登錄於任何查驗機構之人員清冊","同時受聘於二家以上之查驗機構、年度執行查驗案件數超過二十件、未依規定穿著識別服裝進入查驗現場等情形；經減列之查驗人員得於次年度隨時重新申請登錄"],"a",
 "第32條第1項：查驗人員有學經歷、查驗項目實績、訓練合格等證明文件虛偽不實、參加第28條在職訓練連續三次未取得訓練合格證明、違反第29條經通知限期補正屆期未補正、其他違反本辦法規定且經認定情節重大者，中央主管機關得逕予減列。第2項：依第1款或第4款減列之查驗人員，三年內不得登錄於查驗機構之人員清冊。",
 "When may the authority remove a verifier from the roster, and what follows?",
 ["False credentials or training proofs, three consecutive failures in in-service training, uncured breach of Article 29, or other serious breaches; removal for falsity or serious breach bars registration for three years","Client complaints about a case, two years without any case, not attending association seminars, or being judged unsuitable by the body; removal bars registration for one year","Not paying the annual verifier fee, not updating contact details on the platform, or lacking an international lead auditor certificate; removal bars registration for five years","Serving two or more verification bodies at the same time, handling more than twenty cases in a year, or not wearing identification clothing on site; a removed verifier may reapply at any time in the following year"],
 "Article 32."),

(L,"第33條",3,"查驗機構-移送裁處",
 "查驗機構有下列何種情形，中央主管機關依氣候變遷因應法第四十九條第二項規定辦理？",
 ["未依第十四條取得許可證逕行辦理查驗、未依第二十一條於期限內補足員額且未停止查驗業務、違反第二十六條第一項第一款至第三款或第三十條第一項規定等情形","查驗機構之查驗費用高於中央主管機關公告之收費基準、未於官方網站公開查驗總結報告全文、未定期辦理受查事業滿意度調查等程序性事項","查驗機構所屬查驗人員之平均年資未達三年、未設置專責之品質管理部門、未取得國際認證論壇會員資格等組織與人力配置面之情形","查驗機構未主動檢舉受查事業之違規行為、未協助中央主管機關辦理政策宣導、未參與國家溫室氣體清冊編製工作等協力義務未盡之情形"],"a",
 "第33條：查驗機構有未依第14條取得許可證逕行辦理查驗、未依第21條於期限內補足員額且未停止查驗業務、違反第26條第1項第1款至第3款或第30條第1項規定、違反第26條第1項第4款第5款或第7款規定、違反第26條第1項第6款第4目規定、違反第27條第28條或第31條規定、違反第19條第20條第2款第3款第26條第1項第6款第1目至第3目或第30條第2項規定一年內累計達三次等情事之一者，依本法第49條第2項規定辦理。",
 "Which situations are handled under Article 49, Paragraph 2 of the Act?",
 ["Verifying without a permit under Article 14, failing to restore staffing under Article 21 while continuing business, or breaching Article 26(1)(1)-(3) or Article 30(1)","Charging fees above the announced schedule, not publishing full summary reports on the website, or not surveying verified enterprises for satisfaction regularly","Average staff seniority below three years, having no dedicated quality management department, or not holding membership of the International Accreditation Forum","Not reporting violations by verified enterprises, not assisting the authority with policy promotion, or not joining the national inventory compilation work"],
 "Article 33."),

(L,"第34條",1,"查驗機構-外文文件",
 "本辦法所定之相關文件為外文者，應如何處理？",
 ["應檢附中文譯本","應經駐外館處驗證","應由查驗機構逐頁簽章","應經法院公證人認證"],"a",
 "第34條：本辦法所定之相關文件為外文者，應檢附中文譯本。第36條並定中央主管機關執行本辦法所取得之資料，涉及受查者之個人隱私、工商秘密、軍事秘密應予保密。",
 "How must documents in a foreign language be handled?",
 ["A Chinese translation must be attached","They must be authenticated by an overseas mission","Each page must be signed by the body","They must be notarized by a court notary"],
 "Article 34."),

(L,"第35條",1,"查驗機構-委託辦理",
 "中央主管機關得委託（任）相關機關（構）辦理之事項為何？",
 ["認證機構、查驗機構之輔導、審查、評鑑及稽查事項","查驗機構許可證之核發、罰鍰之裁處及訴願決定事項","事業溫室氣體排放量之核定及碳費費率之審議事項","減量額度之核發、抵換權重因子之訂定及帳戶管理事項"],"a",
 "第35條：中央主管機關得委託（任）相關機關（構）辦理認證機構、查驗機構之輔導、審查、評鑑及稽查事項。第4條所定認證機構亦為中央主管機關委託執行查驗機構認證業務之機關（構）。",
 "Which matters may be entrusted to other agencies or institutions?",
 ["Guidance, review, assessment and inspection of accreditation and verification bodies","Issuing verification body permits, imposing fines and deciding administrative appeals","Approving enterprise greenhouse gas emissions and reviewing carbon fee rates","Issuing reduction credits, setting offset weighting factors and managing accounts"],
 "Article 35."),

(L,"第36條",1,"查驗機構-保密義務",
 "中央主管機關執行本辦法所取得之資料，其保密規定為何？",
 ["涉及受查者之個人隱私、工商秘密、軍事秘密應予保密","涉及受查者之任何資料一律應予保密不得對外提供","僅涉及軍事秘密者應予保密，其餘資料均應主動公開","涉及受查者之營業額及查驗費用應予保密，其餘公開"],"a",
 "第36條：中央主管機關執行本辦法所取得之資料，涉及受查者之個人隱私、工商秘密、軍事秘密應予保密。第31條並定中央主管機關得進入查驗機構或查驗現場稽查並命其提供有關資料。",
 "What confidentiality applies to data obtained under these Regulations?",
 ["Personal privacy, trade secrets and military secrets of the audited party must be kept confidential","Any and all data concerning the audited party must be kept confidential and never released","Only military secrets must be kept confidential, while all other data must be published","Only the turnover and verification fees of the audited party must be kept confidential"],
 "Article 36."),

(L,"第37條",2,"查驗機構-過渡換發",
 "本辦法修正發布前已取得查驗機構許可證者，應於何時辦理何種手續？",
 ["應於本辦法施行日起六個月內，向中央主管機關申請許可證換發、變更查驗作業計畫書及人員清冊","應於本辦法施行日起三個月內，向認證機構申請認證證書換發，並於換發後重新申請查驗機構許可證","應於本辦法施行日起一年內，重新依第十四條規定檢具全部文件向中央主管機關申請核發新許可證","應俟原許可證有效期限屆滿時，依第二十二條規定辦理展延即可，無須另行申請換發或變更相關文件"],"a",
 "第37條：本辦法修正發布前已取得中央主管機關核發之查驗機構許可證者，應於本辦法施行日起六個月內，向中央主管機關申請許可證換發、變更查驗作業計畫書及人員清冊。第37條之1並對產品碳足跡認證機構及查驗機構另定過渡期限。",
 "What must bodies holding a permit before the amendment do?",
 ["Apply within six months of the effective date to have the permit reissued and the work plan and personnel roster amended","Apply within three months to the accreditation body for a reissued certificate, then reapply for a verification body permit","Refile all documents under Article 14 within one year of the effective date to obtain a newly issued permit","Simply apply for renewal under Article 22 when the existing permit expires, with no reissue or amendment needed"],
 "Article 37."),

(L,"第37條之1",3,"查驗機構-碳足跡過渡",
 "本辦法一百十四年三月十九日修正施行前，已備查之產品碳足跡認證機構及已取得產品碳足跡認證證書之查驗機構，應如何辦理？",
 ["認證機構應於修正施行後三個月內依第四條規定報請核可後始得執行認證業務；查驗機構應於修正施行後六個月內依第十四條規定申請許可，經許可後始得執行查驗業務","認證機構應於修正施行後六個月內依第四條規定報請核可後始得執行認證業務；查驗機構應於修正施行後三個月內依第十四條規定申請許可，經許可後始得執行查驗業務","認證機構及查驗機構均得繼續依原備查或原認證證書內容執行業務，無須另行報請核可或申請許可，俟原證書有效期限屆滿時再依本辦法辦理","認證機構應於修正施行後一年內重新取得國際認證論壇會員資格；查驗機構應於修正施行後二年內重新取得認證證書，逾期者其原有資格即失效"],"a",
 "第37條之1第1項：修正施行前業經中央主管機關備查之產品碳足跡認證機構，應於修正施行後三個月內依第4條規定報請核可後，始得執行產品碳足跡認證業務。第2項：修正施行前已取得產品碳足跡認證證書之查驗機構，應於修正施行後六個月內依第14條規定申請許可，經許可後始得執行產品碳足跡查驗業務。第3項並定得免具部分查驗實績證明文件。",
 "What must existing product carbon footprint bodies do after the 2025 amendment?",
 ["Accreditation bodies must obtain approval under Article 4 within three months before accrediting; verification bodies must obtain a permit under Article 14 within six months before verifying","Accreditation bodies must obtain approval under Article 4 within six months before accrediting; verification bodies must obtain a permit under Article 14 within three months before verifying","Both may continue operating under their existing recordation or certificates without any new approval, dealing with these Regulations only when those certificates expire","Accreditation bodies must regain IAF membership within one year; verification bodies must obtain fresh accreditation within two years or lose their existing status"],
 "Article 37-1, Paragraphs 1 and 2."),

(L,"第38條",1,"查驗機構-施行日",
 "溫室氣體認證機構及查驗機構管理辦法之施行日期規定為何？",
 ["本辦法自發布日起施行","本辦法自發布後六個月施行","本辦法自發布後一年施行","本辦法自一百十五年元旦施行"],"a",
 "第38條：本辦法自發布日施行。第37條並定修正發布前已取得許可證者應於施行日起六個月內申請換發；第37條之1對產品碳足跡相關機構另定三個月及六個月之過渡期限。",
 "When do these Regulations take effect?",
 ["On the date of promulgation","Six months after promulgation","One year after promulgation","On 1 January 2026"],
 "Article 38."),

(P,"第1條",2,"檢測裁罰-授權依據",
 "環境檢驗測定機構違反環保法規罰鍰額度裁罰準則係依據下列何項規定訂定？",
 ["空氣污染防制法第八十五條第二項、水污染防治法第六十六條之一第二項、廢棄物清理法第六十三條之一第一項、毒性及關注化學物質管理法第六十五條第三項及氣候變遷因應法第五十九條","空氣污染防制法第四十九條第一項、水污染防治法第二十三條第二項、廢棄物清理法第四十三條第一項、毒性及關注化學物質管理法第四十四條第三項及氣候變遷因應法第四十一條","行政罰法第十八條第一項、行政程序法第九十六條第一項、環境基本法第二十八條、環境教育法第二十三條第三項及環境影響評估法第二十三條第九項規定","環境檢驗測定機構管理辦法第三十條、機動車輛排放空氣污染物及噪音檢驗測定機構管理辦法第二十八條及行政院環境部組織法第五條規定"],"a",
 "第1條：本準則依空氣污染防制法第85條第2項、水污染防治法第66條之1第2項、廢棄物清理法第63條之1第1項、毒性及關注化學物質管理法第65條第3項及氣候變遷因應法第59條規定訂定之。第7條並定本準則自發布日施行。",
 "Under which provisions are these Penalty Criteria promulgated?",
 ["Article 85-2 of the Air Act, Article 66-1-2 of the Water Act, Article 63-1-1 of the Waste Act, Article 65-3 of the Toxic Chemicals Act, and Article 59 of the Climate Act","Article 49-1 of the Air Act, Article 23-2 of the Water Act, Article 43-1 of the Waste Act, Article 44-3 of the Toxic Chemicals Act, and Article 41 of the Climate Act","Article 18-1 of the Administrative Penalty Act, Article 96-1 of the Administrative Procedure Act, Article 28 of the Basic Environment Act, and related provisions","Article 30 of the Environmental Testing Organization Regulations, Article 28 of the Vehicle Testing Organization Regulations, and Article 5 of the Ministry organization act"],
 "Article 1."),

(P,"第2條",3,"檢測裁罰-計算公式",
 "檢測機構及測定機構違規時，應適用之裁罰計算公式附表為何？",
 ["違反空污法第四十九條第一項、廢清法第四十三條第一項或氣候法第四十一條第一項者依附表一；違反管理辦法規定者依附表二；測定機構違反機動車輛管理辦法規定者依附表三","違反空污法第四十九條第一項、廢清法第四十三條第一項或氣候法第四十一條第一項者依附表三；違反管理辦法規定者依附表一；測定機構違反機動車輛管理辦法規定者依附表二","不論違反何種法律或管理辦法規定，均一律依附表一所列裁罰計算公式計算應裁處之罰鍰，附表二及附表三僅供主管機關裁量時之參考","檢測機構之違規一律依附表二計算，測定機構之違規一律依附表一計算，附表三則專供違反水污染防治法規定之案件計算罰鍰額度使用"],"a",
 "第2條第1項：檢測機構違反空氣污染防制法第49條第1項、廢棄物清理法第43條第1項或氣候變遷因應法第41條第1項規定，或測定機構違反空污法第49條第1項規定者，依附表一所列裁罰計算公式計算。第2項：檢測機構違反環境檢驗測定機構管理辦法規定者依附表二；第3項：測定機構違反機動車輛管理辦法規定者依附表三。",
 "Which annex formula applies to each type of violation?",
 ["Breaches of Air Act 49-1, Waste Act 43-1 or Climate Act 41-1 use Annex 1; breaches of the Testing Organization Regulations use Annex 2; vehicle testing body breaches use Annex 3","Breaches of Air Act 49-1, Waste Act 43-1 or Climate Act 41-1 use Annex 3; breaches of the Testing Organization Regulations use Annex 1; vehicle testing body breaches use Annex 2","All breaches of any statute or regulation are calculated under Annex 1 alone, with Annexes 2 and 3 serving only as reference material for the authority discretion","All testing organization breaches use Annex 2 and all vehicle testing body breaches use Annex 1, while Annex 3 applies only to Water Pollution Control Act cases"],
 "Article 2."),

(P,"第3條",3,"檢測裁罰-最高額",
 "依計算公式所得之裁罰額度逾法定罰鍰最高額者，應如何裁處？",
 ["依法定罰鍰最高額裁處；但違反廢棄物清理法所得之利益超過法定罰鍰最高額者，得於所得利益範圍內酌量加重裁處，不受法定罰鍰最高額之限制","依法定罰鍰最高額裁處；不論違反何種法規，均不得超過法定罰鍰最高額，縱使違規所得利益遠高於該最高額亦不得於利益範圍內加重","依計算所得之全額裁處；法定罰鍰最高額僅為參考性質，主管機關得逕依公式計算結果裁處而不受任何法定最高額之限制","依法定罰鍰最低額裁處；計算所得額度逾最高額者視為公式適用錯誤，應重新以最低額為基準並加計違規次數後裁處之"],"a",
 "第3條：依第2條計算之裁罰額度逾法定罰鍰最高額者，依法定罰鍰最高額裁處；但違反廢棄物清理法所得之利益超過法定罰鍰最高額者，得於所得利益之範圍內酌量加重裁處，不受法定罰鍰最高額之限制。",
 "How is a calculated penalty exceeding the statutory maximum handled?",
 ["It is imposed at the statutory maximum; but where gains from a Waste Act breach exceed that maximum, the penalty may be increased within the range of those gains","It is imposed at the statutory maximum; no statute allows exceeding it, even where the gains from the violation greatly exceed that statutory maximum amount","It is imposed at the full calculated amount; the statutory maximum is only advisory and the authority may impose the formula result without any ceiling","It is imposed at the statutory minimum; a result above the maximum means the formula was misapplied and must be recalculated from the minimum upward"],
 "Article 3."),

(P,"第4條",1,"檢測裁罰-條文刪除",
 "環境檢驗測定機構違反環保法規罰鍰額度裁罰準則第四條之現行狀態為何？",
 ["該條已刪除，現行條文並無規範內容，罰鍰額度之計算及加重回歸第二條及第三條規定辦理","該條規定檢測機構違規之減輕裁罰事由，包括自動陳報及配合調查等情形之罰鍰減半","該條規定裁處罰鍰時應審酌之因素，包括違規情節、所得利益及機構之資力等事項","該條規定檢測機構違規紀錄之保存年限及公開方式，並授權主管機關另定作業要點"],"a",
 "第4條：（刪除）。條文刪除後條次仍予保留以免影響其他條文之引用關係。現行罰鍰額度依第2條所列附表之裁罰計算公式計算，逾法定罰鍰最高額者依第3條規定辦理；一行為違反數規定者依第5條、數行為者依第6條規定處理。",
 "What is the current status of Article 4 of these Penalty Criteria?",
 ["It has been deleted and has no content; penalty calculation and aggravation now follow Articles 2 and 3","It sets out mitigating grounds such as voluntary reporting and cooperation, halving the fine","It lists factors to weigh in setting fines, such as severity, gains obtained and the body resources","It sets the retention period and disclosure of violation records and authorizes further guidelines"],
 "Article 4 (deleted)."),

(P,"第5條",2,"檢測裁罰-一行為數違反",
 "一行為違反管理辦法或機動車輛管理辦法數個規定者，應如何裁處？",
 ["應先依附表所列情事分別計算罰鍰額度，再依罰鍰額度最高者裁處之","應先依附表所列情事分別計算罰鍰額度，再將各該額度合計後裁處之","應先依附表所列情事分別計算罰鍰額度，再取其平均值作為裁處金額","應依最先發現之違規情事計算罰鍰額度裁處，其餘違規情事不另處罰"],"a",
 "第5條：一行為違反管理辦法或機動車輛管理辦法數個規定者，應先依附表所列情事分別計算罰鍰額度，再依罰鍰額度最高者裁處之。第6條則規定數行為違反同一或不同管理辦法規定者，應分別處罰之。",
 "How is a single act breaching several provisions penalized?",
 ["Calculate the fine for each item under the annexes separately, then impose the highest of those amounts","Calculate the fine for each item under the annexes separately, then impose the sum of all amounts","Calculate the fine for each item under the annexes separately, then impose the average of the amounts","Impose only the fine for the violation discovered first, leaving the remaining violations unpenalized"],
 "Article 5."),

(P,"第6條",2,"檢測裁罰-數行為",
 "數行為違反同一或不同管理辦法或機動車輛管理辦法規定者，應如何處罰？",
 ["應就各行為分別處罰之","應合併為一行為從重處罰","應僅就情節最重者處罰一次","應依行為次數平均計算後處罰"],"a",
 "第6條：數行為違反同一或不同管理辦法或機動車輛管理辦法規定者，應分別處罰之。第5條則規定一行為違反數個規定者，應先分別計算罰鍰額度再依最高者裁處。",
 "How are several acts breaching the same or different regulations penalized?",
 ["Each act is penalized separately","They merge into one heavier penalty","Only the most serious one is penalized once","The number of acts is averaged before penalty"],
 "Article 6."),

(P,"第7條",1,"檢測裁罰-施行日",
 "環境檢驗測定機構違反環保法規罰鍰額度裁罰準則之施行日期規定為何？",
 ["本準則自發布日起施行","本準則自發布後三個月施行","本準則自發布後六個月施行","本準則自發布後一年施行"],"a",
 "第7條：本準則自發布日施行。本準則第1條所列授權依據包括空氣污染防制法第85條第2項等五部法律，第2條並定各類違規適用之附表裁罰計算公式。",
 "When do these Penalty Criteria take effect?",
 ["On the date of promulgation","Three months after promulgation","Six months after promulgation","One year after promulgation"],
 "Article 7."),
]
