# -*- coding: utf-8 -*-
# 第 3 批（C）：補題——缺氧、高架、高溫、異常氣壓、化學品標示、標示準則
QY = "OSH-34"; GJ = "OSH-15"; GW = "OSH-14"; YC = "OSH-18"; HC = "OSH-12"; BS = "OSH-24"
Q = [
# ---------- 缺氧 ----------
(QY,"第1條",1,"缺氧-法源",
 "缺氧症預防規則係依職業安全衛生法第幾條規定訂定？",
 ["第六條第三項","第十條第三項","第十九條第二項","第二十三條"],"a",
 "第1條：本規則依職業安全衛生法第六條第三項規定訂定之。",
 "The Hypoxia Prevention Rules are enacted under which article of the OSH Act?",
 ["Article 6, paragraph 3","Article 10, paragraph 3","Article 19, paragraph 2","Article 23"],
 "Article 1: enacted under Article 6(3) of the Occupational Safety and Health Act."),

(QY,"第2條",3,"缺氧-適用",
 "貫通或鄰接下列何種地層之坑井、隧道內部屬缺氧危險場所？",
 ["含有亞鐵鹽類或亞錳鹽類之地層","含有大量石英砂之堅硬地層","含水量豐富且湧水量大之砂礫層","經人工回填夯實之一般黏土層"],"a",
 "第2條第2項第2款：上層覆有不透水層之砂礫層中無含水或湧水較少之部分；含有亞鐵鹽類或亞錳鹽類之地層；含有甲烷、乙烷或丁烷之地層；湧出碳酸水之虞之地層；腐泥層。",
 "Shafts or tunnels penetrating or adjacent to which stratum are hazardous places?",
 ["Strata containing ferrous or manganous salts","Strata composed mainly of hard quartz sand","Gravel layers rich in water with heavy seepage","Ordinary clay layers backfilled and compacted"],
 "Article 2(2)(2): dry gravel under impermeable layers; strata with ferrous or manganous salts; strata with methane, ethane or butane; strata that may emit carbonated water; putrid mud layers."),

(QY,"第2條",2,"缺氧-適用",
 "置放煤、褐煤、硫化礦石、鋼材、鐵屑、原木片、乾性油、魚油等物質之儲槽或倉庫內部屬缺氧危險場所，原因為何？",
 ["該等物質易吸收空氣中之氧氣","該等物質會放出大量純氧氣體","該等物質會揮發劇毒之硫化氫","該等物質受潮即自行爆炸起火"],"a",
 "第2條第2項第7款：置放煤、褐煤、硫化礦石、鋼材、鐵屑、原木片、木屑、乾性油、魚油或其他易吸收空氣中氧氣之物質之儲槽、船艙、倉庫、地窖、貯煤器等之內部。",
 "Why are storages of coal, sulfide ore, steel, iron scrap, wood chips, drying oil or fish oil hazardous places?",
 ["These materials readily absorb oxygen from the air","These materials release large amounts of pure oxygen","These materials give off highly toxic hydrogen sulfide","These materials ignite and explode when they get damp"],
 "Article 2(2)(7): such materials readily absorb atmospheric oxygen, so tanks, holds, warehouses, cellars and coal bunkers holding them are hazardous."),

(QY,"第2條",2,"缺氧-適用",
 "使用乾冰從事冷凍、冷藏之冷凍庫、冷凍貨車或冷凍貨櫃內部，屬缺氧危險場所之原因為何？",
 ["乾冰昇華產生二氧化碳排擠氧氣","庫內低溫使空氣中氧氣液化沉降","密閉庫內照明不足導致視線不良","冷媒外洩產生具毒性之氨氣"],"a",
 "第2條第2項第12款：使用乾冰從事冷凍、冷藏或水泥乳之脫鹼等之冷藏庫、冷凍庫、冷凍貨車、船艙或冷凍貨櫃之內部。乾冰昇華釋出二氧化碳而降低氧氣濃度。",
 "Why are freezers, reefer trucks or containers using dry ice hazardous places?",
 ["Sublimating dry ice releases CO2 that displaces oxygen","The low temperature liquefies oxygen in the air","Poor lighting in the sealed store impairs vision","Leaking refrigerant produces toxic ammonia gas"],
 "Article 2(2)(12): cold rooms, freezers, reefer trucks, holds or containers using dry ice; sublimation releases CO2 and reduces oxygen."),

(QY,"第9條",2,"缺氧-設施",
 "於儲槽、鍋爐內部使用氬、二氧化碳或氦從事熔接作業時，應保持氧氣濃度在百分之多少以上？",
 ["百分之十六","百分之十八","百分之十九","百分之二十"],"b",
 "第9條：於儲槽、鍋爐或反應槽內部或其他通風不充分場所使用氬、二氧化碳或氦等從事熔接作業時，應予適當換氣以保持氧氣濃度在百分之十八以上；不得使用純氧換氣。",
 "During welding with argon, CO2 or helium inside tanks or boilers, oxygen must be kept at or above:",
 ["16%","18%","19%","20%"],
 "Article 9: ventilate to keep oxygen at 18% or more inside tanks, boilers or other poorly ventilated places; never ventilate with pure oxygen."),

(QY,"第11條",3,"缺氧-設施",
 "於通風不充分之室內作業場所，為防止儲槽、反應槽安全閥排出之惰性氣體流入，應設置何種設施？",
 ["可使安全閥排出之氣體直接排放於外部之設施","於室內加裝局部排氣抽風機即可之設施","作業期間將安全閥完全關閉之管制措施","於安全閥出口處設置水幕阻隔氣體之設施"],"a",
 "第11條：應設置可使安全閥等所排出之氣體直接排放於外部之設施。",
 "In poorly ventilated indoor workplaces, to prevent inert gas from tank relief valves flowing in, the employer shall install:",
 ["Facilities that discharge relief-valve gas directly outdoors","Local exhaust fans installed inside the workroom only","Administrative rules to keep relief valves fully closed","A water curtain fitted at the relief valve outlet duct"],
 "Article 11: facilities to vent gases from safety valves directly to the outside."),

(QY,"第13條",3,"缺氧-設施",
 "採用壓氣施工法之作業場所，鄰近特定地層時應調查何事？",
 ["作業之井或配管有否空氣漏洩、漏洩程度及作業場所氧氣濃度","作業場所之土壤承載力、沉陷量及基樁之埋設深度","鄰近地區地下水位之高低、水質酸鹼值及其含鹽量","作業場所之噪音音壓級、振動頻率及其照明照度值"],"a",
 "第13條：採用壓氣施工法之場所存有或鄰近第2條第2項第2款第1目或第2目地層時，應調查該作業之井或配管有否空氣之漏洩、漏洩之程度及該作業場所空氣中氧氣之濃度。第19條發現漏洩時應即通知並公告緊急措施。",
 "For compressed-air construction near specified strata, the employer shall survey:",
 ["Air leakage from wells or piping, its extent, and the oxygen concentration at the site","Soil bearing capacity at the site, its settlement, and the pile embedment depth","Groundwater level nearby, its extent, and the pH and salt content of the water","Noise pressure level at the site, vibration frequency, and the lighting illuminance"],
 "Article 13: check for air leakage from wells or piping, its extent, and the oxygen concentration; Article 19: on finding oxygen-deficient air leaking in, notify personnel and post emergency measures."),

(QY,"第15條",3,"缺氧-設施",
 "於地下室或溝內部從事拆卸或安裝輸送甲烷、乙烷、丙烷、丁烷等氣體配管作業時，應採取何種措施？",
 ["確實遮斷該氣體之設施，使其不致流入作業場所","加快配管拆卸速度，使氣體不致大量流入場所","使勞工配戴防塵口罩，即可於該場所內作業","以火焰接近配管接頭，檢測氣體有無漏洩情形"],"a",
 "第15條：於地下室或溝之內部及其他通風不充分之室內作業場所拆卸或安裝輸送主成分為甲烷、乙烷、丙烷、丁烷或此類混入空氣的氣體配管作業時，應採取確實遮斷該氣體之設施。",
 "When removing or installing piping for methane, ethane, propane or butane in basements or trenches, the employer shall:",
 ["Reliably isolate the gas so it cannot flow into the work area","Dismantle the piping quickly so little gas enters the area","Have workers wear dust masks and then work in the area","Hold a flame near the joints to check the gas for leaks"],
 "Article 15: install facilities that positively shut off the gas so it cannot enter the removal or installation area."),

(QY,"第22條",2,"缺氧-管理",
 "從事缺氧危險作業受鄰接作業場所影響致有缺氧危險之虞時，雇主應如何？",
 ["與各該作業場所密切保持聯繫","應立即停止鄰接作業場所之作業","僅需於作業前通報檢查機構","要求鄰接作業場所負損害賠償責任"],"a",
 "第22條：如受鄰接作業場所之影響致有發生缺氧危險之虞時，應與各該作業場所密切保持聯繫。",
 "When adjacent worksites could cause an oxygen-deficiency risk, the employer shall:",
 ["Maintain close liaison with those worksites","Immediately shut down all work at those worksites","Merely notify the inspection agency before starting","Claim damages from the adjacent worksite operator"],
 "Article 22: keep in close contact with the adjacent worksites."),

(QY,"第26條",2,"缺氧-防護",
 "勞工從事缺氧危險作業有因缺氧致墜落之虞時，雇主應供給何物？",
 ["梯子、安全帶或救生索","護目鏡、防塵面罩或耳罩","防音耳塞、耳罩或安全帽","反光背心、口哨或手電筒"],"a",
 "第26條：應供給該勞工使用之梯子、安全帶或救生索，並使勞工確實使用。第29條：應定期或每次作業開始前確認第25至28條防護設備之數量及效能。",
 "When a worker may fall due to hypoxia, the employer shall provide:",
 ["A ladder, safety harness or lifeline","Goggles, a dust face shield or earmuffs","Earplugs, earmuffs or a safety helmet","A reflective vest, whistle or flashlight"],
 "Article 26: ladders, harnesses or lifelines, and ensure their use; Article 29: check the quantity and function of protective equipment regularly or before each job."),

(QY,"第31條",2,"缺氧-健康",
 "下列何者屬缺氧症之末期症狀？",
 ["意識不明、痙攣、呼吸停止或心臟停止跳動","顏面蒼白、口唇發紺、脈搏微弱或盜汗","脈搏加快、呼吸急促、頭暈或注意力不集中","頭痛、耳鳴、噁心嘔吐或四肢無力感"],"a",
 "第31條第2款：意識不明、痙攣、呼吸停止或心臟停止跳動等為缺氧症之末期症狀，應即由醫師診治。",
 "Which are late-stage symptoms of hypoxia?",
 ["Unconsciousness, convulsions, respiratory arrest or cardiac arrest","Pale face, cyanotic lips, weak pulse or cold sweating","Rapid pulse, fast breathing, dizziness or poor concentration","Headache, ringing ears, nausea and vomiting or limb weakness"],
 "Article 31(2): unconsciousness, convulsions, respiratory or cardiac arrest are late symptoms requiring immediate medical care."),

# ---------- 高架 ----------
(GJ,"第1條",1,"高架-法源",
 "高架作業勞工保護措施標準係依職業安全衛生法第幾條規定訂定？",
 ["第十九條第二項","第六條第三項","第十條第三項","第二十條第一項"],"a",
 "第1條：本標準依職業安全衛生法第十九條第二項規定訂定之（高溫作業標準、異常氣壓標準亦依第19條第2項）。",
 "The Work-at-Height Protection Standards are enacted under which OSH Act article?",
 ["Article 19, paragraph 2","Article 6, paragraph 3","Article 10, paragraph 3","Article 20, paragraph 1"],
 "Article 1: under Article 19(2) of the OSH Act, the same basis as the high-temperature and abnormal-pressure standards."),

(GJ,"第3條",2,"高架-定義",
 "室內作業或儲槽等場所之高架作業高度，如何計算？",
 ["自勞工站立位置與地板間之垂直距離","自建築物地面至屋頂之最高點垂直高度","自勞工頭頂至天花板間之垂直距離","自建築物基礎底面起算之垂直距離"],"a",
 "第3條第2項第2款：室內作業或儲槽等場所，自勞工站立位置與地板間之垂直距離。",
 "Indoors or in tanks, the height of work at height is measured as:",
 ["The vertical distance from the worker's standing position to the floor","The vertical height from the building ground to the roof peak","The vertical distance from the worker's head to the ceiling","The vertical distance measured from the building's foundation base"],
 "Article 3(2)(2): the vertical distance between the worker's standing position and the floor."),

(GJ,"第8條",2,"高架-禁止",
 "身體虛弱經醫師診斷認為身體狀況不良之勞工，雇主得否使其從事高架作業？",
 ["不得","得","加薪後得","經勞工同意即得"],"a",
 "第8條第2款：身體虛弱，經醫師診斷認為身體狀況不良者，雇主不得使其從事高架作業；第3款情緒不穩定有安全顧慮者、第4款勞工自覺不適者亦同。",
 "May an employer assign work at height to a worker a physician has diagnosed as physically unfit?",
 ["Not permitted","Permitted","Permitted with extra pay","Permitted if the worker consents"],
 "Article 8(2): no; likewise for emotionally unstable workers with safety concerns and workers who feel unfit."),

# ---------- 高溫 ----------
(GW,"第2條",2,"高溫-適用",
 "高溫作業已採取自動化操作方式且勞工無暴露熱危害之虞者，是否適用高溫作業標準？",
 ["不包括在高溫作業內","仍包括在高溫作業內","僅半數工時計入高溫作業","由檢查人員個別認定"],"a",
 "第2條第2項：前項作業，不包括已採取自動化操作方式且勞工無暴露熱危害之虞者。",
 "Are automated operations with no worker heat exposure covered as high-temperature work?",
 ["No, they are excluded","Yes, they remain covered","Only half the hours count","Decided by the inspectors"],
 "Article 2(2): operations that are automated with no risk of heat exposure are excluded."),

(GW,"第3條",3,"高溫-熱指數",
 "時量平均綜合溫度熱指數之計算方式為何？",
 ["各次熱指數乘各次工作時間之總和，除以總工作時間","各次熱指數之總和，除以測定次數之簡單平均","各次熱指數中取最高者，作為代表值計算","各次熱指數中取最低者，除以總工作時間"],"a",
 "第3條第2項：時量平均綜合溫度熱指數＝(第一次熱指數×第一次工作時間＋…＋第n次熱指數×第n次工作時間)÷(第一次工作時間＋…＋第n次工作時間)，均以攝氏表示。",
 "The time-weighted average WBGT is calculated as:",
 ["Sum of each WBGT times its work period, divided by total work time","Sum of all WBGT readings divided by the number of readings","The highest single WBGT reading taken as the representative value","The lowest single WBGT reading divided by total work time"],
 "Article 3(2): sum of WBGT × time for each period, divided by total time, in degrees Celsius."),

(GW,"第4條",2,"高溫-定義",
 "於走動中提舉或推動一般重量物體之工作，屬何種工作？",
 ["中度工作","輕工作","重工作","特殊工作"],"a",
 "第4條：中度工作指於走動中提舉或推動一般重量物體者。",
 "Lifting or pushing ordinary loads while walking is classified as:",
 ["Moderate work","Light work","Heavy work","Special work"],
 "Article 4: moderate work means lifting or pushing objects of ordinary weight while walking."),

(GW,"第5條",3,"高溫-作息",
 "中度工作之時量平均綜合溫度熱指數達攝氏 29.4 度時，每小時作息比例為何？",
 ["25%休息、75%作業","0%休息、100%作業","50%休息、50%作業","75%休息、25%作業"],"a",
 "第5條表：中度工作 28.0 連續作業、29.4 為 25% 休息、31.1 為 50% 休息、32.6 為 75% 休息。",
 "For moderate work at a time-weighted WBGT of 29.4°C, the hourly ratio is:",
 ["25% rest / 75% work","0% rest / 100% work","50% rest / 50% work","75% rest / 25% work"],
 "Article 5 table: moderate work 28.0 continuous, 29.4 = 25% rest, 31.1 = 50% rest, 32.6 = 75% rest."),

(GW,"第5條",3,"高溫-作息",
 "重工作之時量平均綜合溫度熱指數達攝氏 32.1 度時，每小時作業比例最多為多少？",
 ["百分之二十五","百分之五十","百分之七十五","百分之百"],"a",
 "第5條表：重工作 32.1 對應 75% 休息、25% 作業。",
 "For heavy work at a time-weighted WBGT of 32.1°C, the maximum hourly work proportion is:",
 ["25%","50%","75%","100%"],
 "Article 5 table: heavy work at 32.1 = 75% rest / 25% work."),

(GW,"第8條",1,"高溫-管理",
 "雇主原訂高溫作業勞工之工作條件優於高溫作業標準者，應如何？",
 ["從其規定","一律改依標準","須報主管機關核准","無效"],"a",
 "第8條：雇主原訂高溫作業勞工之工作條件優於本標準者，從其規定。",
 "If an employer's existing conditions for high-temperature workers are better than the Standards:",
 ["The employer's terms apply","They must be lowered to the Standards","Approval is required","They are void"],
 "Article 8: the more favorable employer terms prevail."),

# ---------- 異常氣壓 ----------
(YC,"第4條",1,"異常氣壓-健康",
 "雇主僱用勞工從事異常氣壓作業時，應依何規定實施健康檢查及管理？",
 ["勞工健康保護規則","全民健康保險法","醫療機構設置標準","職業安全衛生設施規則"],"a",
 "第4條：應依勞工健康保護規則之規定，實施勞工健康檢查及管理。",
 "Health examinations for abnormal-pressure workers shall follow:",
 ["The Labor Health Protection Rules","The National Health Insurance Act","The Medical Institutions Standards","The OSH Facilities Rules"],
 "Article 4: per the Labor Health Protection Rules."),

(YC,"第8條",2,"異常氣壓-設備",
 "空氣壓縮機與作業室或氣閘室之間應設置何種裝置？",
 ["空氣清淨裝置","空氣加熱裝置","空氣消音裝置","空氣加濕裝置"],"a",
 "第8條：應於空氣壓縮機與作業室或與氣閘室之間設置空氣清淨裝置，以清淨輸往各該室之空氣。第11條：另應設置防止異常升溫之自動警報裝置。",
 "Between the air compressor and the working chamber or air lock, the employer shall install:",
 ["An air cleaning device","An air heating device","An air silencing device","An air humidifying device"],
 "Article 8: an air purifier to clean the supplied air; Article 11: an automatic alarm for abnormal temperature rise."),

(YC,"第11條",2,"異常氣壓-設備",
 "為防止空氣壓縮機輸往作業室之空氣發生異常升溫，應設置何種裝置？",
 ["能迅即告知操作勞工之自動警報裝置","能自動降低空氣溫度之冷卻除濕裝置","於作業室內設置溫度計供人員查看即可","由操作勞工每小時記錄溫度之管理措施"],"a",
 "第11條：應設置能迅即告知操作該空氣壓縮機之勞工及其他有關人員之自動警報裝置。",
 "To guard against abnormal temperature rise in compressed air sent to the chamber, the employer shall install:",
 ["An automatic alarm that immediately alerts the compressor operator","An automatic cooling and dehumidifying unit on the air line","A thermometer in the working chamber for staff to read","Hourly temperature logging by the compressor operator"],
 "Article 11: an automatic alarm notifying the compressor operator and related personnel immediately."),

(YC,"第17條",1,"異常氣壓-管理",
 "雇主對與工作無關人員擅進作業室及氣閘室，應如何？",
 ["嚴禁，並將禁止事項揭示於沈箱外面顯明處","得允許參觀，惟須由主管人員陪同進入","收取安全管理費用後，即得准許人員進入","不需管制，僅須於作業日誌記錄進出人數"],"a",
 "第17條：應嚴禁與工作無關人員擅進作業室及氣閘室，並將有關禁止事項揭示於沈箱、壓氣潛盾等之外面顯明易見之處所。",
 "Regarding unauthorized persons entering the working chamber or air lock, the employer shall:",
 ["Strictly prohibit it and post the prohibition conspicuously outside the caisson","Allow visits so long as a supervisor escorts the visitors inside the chamber","Allow entry once a safety management fee has been collected at the gate","No control is needed if the daily log records the number entering"],
 "Article 17: strictly prohibit entry and post the prohibition clearly outside the caisson or shield."),

(YC,"第19條",3,"異常氣壓-管理",
 "高壓室內作業「高壓下時間」係指何段時間？作業壓力在每平方公分四公斤以下且一日作業次數二次以下者依何附表？",
 ["自開始加壓至開始減壓之時間；附表一","自進入作業室至離開作業室之時間；附表二","僅計加壓中所經過之時間；附表三","僅計減壓中所經過之時間；附表四"],"a",
 "第19條：高壓下時間指自開始加壓至開始減壓之時間；作業壓力四公斤以下且一日二次以下者依附表一；超過四公斤或超過二次者依附表二並依附表三修正。",
 "'Time under pressure' in hyperbaric work runs from when to when, and which table applies at 4 kg/cm² or less with at most two sessions a day?",
 ["From start of compression to start of decompression; Table 1","From entering the working chamber to leaving it; Table 2","Only the time spent under compression; Table 3","Only the time spent under decompression; Table 4"],
 "Article 19: from the start of compression to the start of decompression; Table 1 for 4 kg/cm² or less and two sessions or fewer; Table 2 with Table 3 corrections otherwise."),

(YC,"第24條",2,"異常氣壓-管理",
 "為防止作業室內危險或有害氣體危害高壓室內作業勞工，應採取何措施？",
 ["換氣、測定氣體濃度及其他必要措施","僅提供防塵口罩及其他個人防護具","禁止進食、飲水及在作業室內吸菸","縮短工作時間及增加休息次數之措施"],"a",
 "第24條：應採取換氣、測定氣體濃度及其他必要措施。第16條主管亦須檢點測定二氧化碳、一氧化碳、甲烷、硫化氫等濃度之儀器。",
 "To protect hyperbaric workers from dangerous or harmful gases, the employer shall:",
 ["Ventilate, measure gas concentrations and take other necessary measures","Provide dust masks and other personal protective equipment only","Ban eating, drinking and smoking inside the working chamber","Shorten working hours and increase the number of rest breaks"],
 "Article 24: ventilation, gas measurement and other measures; Article 16: the supervisor checks meters for CO2, CO, methane and H2S."),

(YC,"第26條",3,"異常氣壓-緊急",
 "因緊急事故增加減壓速率使高壓室內勞工避難後，雇主應如何處置？",
 ["迅即送入再壓室或氣閘室，加壓至原作業相等之壓力","使勞工於常壓下休息，並於當日自行返家休養","由現場人員持續觀察其症狀，無需再加壓","給予溫熱飲水及氧氣吸入，即可繼續作業"],"a",
 "第26條：緊急時得在必要限度內增加減壓速率或縮短停止時間，但應於勞工避難或救出後迅即送入再壓室或氣閘室，加壓至原高壓室內作業相等之壓力，加壓速率依第18條。",
 "After an emergency rapid decompression to evacuate hyperbaric workers, the employer shall:",
 ["Promptly recompress them in a recompression chamber or air lock to the original pressure","Let them rest at normal pressure and send them home at once to recover that day","Have site staff keep watching their symptoms, with no recompression needed","Give them warm drinks and oxygen, after which work may continue as normal"],
 "Article 26: recompress promptly to the original pressure in a recompression chamber or air lock, at the rate in Article 18."),

(YC,"第29條",2,"異常氣壓-管理",
 "高壓室內作業之通話設備故障時之連絡方法，雇主應如何處理？",
 ["事前告知相關勞工並揭示於易見處","俟通話設備故障發生時再由主管決定","無須另訂連絡方法由現場人員處理","以行動電話通知氣閘室連絡員即可"],"a",
 "第29條：應設置通話設備並於氣閘室附近配置連絡員；應規定通話設備故障時之連絡方法，事前告知相關勞工並揭示於勞工易見之處所。",
 "The contact method for when the hyperbaric communication system fails must be:",
 ["Set in advance, told to workers and posted where they can see it","Decided by the supervisor when the equipment actually fails","Not required; site personnel handle it on their own","Phoning the air-lock liaison on a mobile phone is enough"],
 "Article 29: install communication equipment with a liaison near the air lock, and pre-establish, communicate and post the fallback contact method."),

(YC,"第31條",2,"異常氣壓-緊急",
 "輸氣設備發生故障、出水或其他異常致高壓室內勞工有遭受危害之虞時，雇主應如何？",
 ["迅即使勞工撤離並採取避難措施，確認安全前不得使指定人員以外者進入","維持原有輸氣量並繼續作業，俟交接班時再行檢修輸氣設備","僅通知作業室主管到場查看，勞工得於室內繼續等候","減少作業室內人員數量，留置指定人員繼續進行作業"],"a",
 "第31條：應迅即使勞工撤離並採取避難措施；之後確認輸氣設備是否正常、沈箱有無異常沈降傾斜；非確認安全前不得使指定人員以外之人員進入。",
 "When the air supply fails or water enters and hyperbaric workers are endangered, the employer shall:",
 ["Evacuate workers immediately, and let only designated personnel in until safety is confirmed","Keep the air supply as it is and continue work, repairing the equipment at shift change","Only notify the chamber supervisor to come and look, while workers wait inside","Reduce the number of people in the chamber and let the designated staff work on"],
 "Article 31: evacuate immediately, then verify the air supply and check for abnormal sinking or tilting; only designated personnel may enter before safety is confirmed."),

(YC,"第32條",2,"異常氣壓-管理",
 "為沈降沈箱而抽出作業室內空氣時，應先如何？",
 ["撤出該室內作業之勞工","加派人員進入該室協助作業","關閉該室內照明及通訊設備","增加該室內之供氣量及壓力"],"a",
 "第32條：為沈降沈箱而抽出作業室內之空氣時，應先撤出該室內作業之勞工；之後確認無出水或有害氣體，安全前不得使指定人員以外者進入。",
 "Before extracting air from the working chamber to sink the caisson, the employer shall:",
 ["Withdraw the workers from the chamber","Send more workers into the chamber","Turn off the lighting and intercom","Raise the air supply and pressure"],
 "Article 32: withdraw workers first; afterwards confirm there is no water ingress or harmful gas before non-designated personnel enter."),

(YC,"第33條",2,"異常氣壓-管理",
 "於作業室內施炸後，在何種條件下始可允許人員進入？",
 ["確認作業室內空氣恢復至正常狀態","施炸後經過五分鐘即可進入作業室","以目視確認作業室內煙霧已完全散去","經作業室主管人員口頭同意後進入"],"a",
 "第33條：作業室內施炸後，為防止缺氧或有害氣體之危害，在確認該作業室內之空氣恢復至正常狀態前，應嚴禁任何人進入作業室。",
 "After blasting in the working chamber, entry is allowed only when:",
 ["The air in the chamber is confirmed to be back to normal","Five minutes have passed since the blast was fired","The smoke in the chamber is seen to have cleared","The chamber supervisor has given verbal consent"],
 "Article 33: no one may enter until the chamber air is confirmed normal, to prevent hypoxia or harmful gases."),

(YC,"第41條",2,"異常氣壓-潛水管理",
 "潛水作業場所有船隻進入或進行爆破、拖網之虞時，雇主應如何？",
 ["安排船舶戒護，並設置潛水作業警告旗誌、警示燈及錨標","由雇主公告停止該海域內所有船隻通行及作業","由潛水人員以無線電向鄰近船隻口頭警告","於作業日誌記錄船舶動態，不需其他措施"],"a",
 "第41條：應安排船舶戒護，並於作業場所設置必要而顯著之警告標示及措施，包括符合規定之潛水作業警告旗誌、警示燈、錨標。",
 "When vessels, blasting or trawling may endanger divers, the employer shall:",
 ["Arrange guard vessels and post dive flags, warning lights and anchor buoys","Publicly close the whole sea area to all vessels and operations","Have divers warn nearby vessels verbally by radio","Log vessel movements in the daily record; nothing else is needed"],
 "Article 41: guard boats plus conspicuous warnings including the prescribed dive flag, warning lights and anchor buoys."),

(YC,"第42條",2,"異常氣壓-潛水管理",
 "下列何者屬應提供必要裝備並告知特殊危害預防事項之特殊危險潛水作業？",
 ["水下切割及熔接、進出沈船洞穴、夜間低能見度水域、高速水流水域","一般游泳池清潔、水質檢測、池底刷洗、更換濾材作業","岸邊淺水撿拾貝類、採集海藻、淨灘及潮間帶觀察","水面漂浮休憩、浮潛拍照、船邊下水及岸際涉水作業"],"a",
 "第42條列舉：水下爆破、水下切割及熔接、進出沈船洞穴佈設海底管線、寒冷或高溫水域、海域探測、遭受污染水域、夜間及低能見度水域、高速水流或渦流水域、特殊海洋生物危害等潛水作業。",
 "Which are 'special hazardous diving operations' requiring extra equipment and hazard briefing?",
 ["Underwater cutting/welding, wreck or cave entry, night or low-visibility water, strong currents","Swimming pool cleaning, water quality testing, floor scrubbing, filter media changing","Shallow shore shellfish gathering, seaweed picking, beach cleanup, tidal observation","Surface floating, snorkel photography, boat-side entry, shoreline wading"],
 "Article 42: underwater blasting, cutting and welding, wrecks/caves/pipelines, cold or hot water, ocean surveys, polluted water, night or low visibility, strong currents or eddies, dangerous marine life."),

(YC,"第45條",3,"異常氣壓-減壓",
 "於海拔多少公尺以上高海拔地區從事潛水作業，應依附表四之四、四之五規定辦理？",
 ["九十一點五公尺（三百呎）","三百零五公尺（一千呎）","一千公尺（三千呎）","二千公尺（六千呎）"],"a",
 "第45條：於九十一點五公尺（三百呎）以上高海拔地區潛水應依附表四之四、四之五辦理；作業後離開據點高程壓力差超過三百零五公尺（一千呎）者，應依附表四之六完成水面上休息並記錄保存五年。",
 "Diving at altitudes above what elevation must follow Tables 4-4 and 4-5?",
 ["91.5 m (300 ft)","305 m (1,000 ft)","1,000 m (3,000 ft)","2,000 m (6,000 ft)"],
 "Article 45: above 91.5 m (300 ft); leaving to a site with over 305 m (1,000 ft) elevation difference requires a surface interval per Table 4-6, recorded and kept 5 years."),

(YC,"第51條",2,"異常氣壓-供氣",
 "使用水肺供氣（緊急用氣瓶外）潛水時，單人潛水應如何？二人共潛應如何？",
 ["單人需有繩索繫著；二人需隨時在互相視線可及之處","單人無需繩索繫著；二人得於水下各自分開作業","單人需配置連絡員；二人共潛則無須任何規定","單人及二人共潛均無須繩索或視線之要求"],"a",
 "第51條：潛水前告知氣瓶供氣能力；設置潛水作業主管全程掌握；單人潛水需有繩索繫著，二人共潛需隨時在互相視線可及之處。",
 "For scuba diving, a solo diver must be, and buddy divers must be:",
 ["Tethered by a line; within each other's sight at all times","Untethered; free to work apart underwater as they wish","Given a tender; buddy pairs are under no requirement","No line or sight requirement for solo or buddy divers"],
 "Article 51: brief the diver on cylinder capacity, assign a supervisor, tether solo divers, and keep buddy pairs within sight."),

(YC,"第53條",2,"異常氣壓-供氣",
 "潛水作業供下潛或上浮使用之安全索，應如何標記？",
 ["依減壓站之停留深度以木標或布條作記錄","依潛水深度以油漆每五公尺標示一次","將整條安全索以紅色油漆均勻塗布標示","自水面起每一公尺打一個繩結作為記號"],"a",
 "第53條：應供給下潛或上浮使用之安全索並監督確實使用；安全索應依減壓站之停留深度以木標或布條作記錄。",
 "The descent/ascent safety line must be marked:",
 ["At decompression stop depths with wooden tags or cloth strips","With paint at every five meters of dive depth","By coating the whole safety line evenly in red paint","With a knot tied every meter from the surface down"],
 "Article 53: provide and enforce use of the safety line, marked at decompression stop depths with wooden markers or cloth strips."),

(YC,"第54條",3,"異常氣壓-檢點",
 "使用水面供氣設備潛水時，空氣壓縮機或手動氣泵應多久檢點一次？流量計應多久檢點一次？",
 ["每週；每半年","每日；每月","每月；每季","每季；每年"],"a",
 "第54條第1款：每週檢點空氣壓縮機或手動氣泵；每月檢點空氣清淨裝置及深度表；每季檢點水中計時器；每半年檢點流量計。紀錄保存五年。",
 "For surface-supplied diving, the compressor or hand pump is inspected how often, and the flow meter how often?",
 ["Weekly; every six months","Daily; every month","Monthly; every quarter","Quarterly; every year"],
 "Article 54(1): compressor weekly; air cleaner and depth gauge monthly; dive timer quarterly; flow meter every six months; records 5 years."),

(YC,"第54條",3,"異常氣壓-檢點",
 "使用水肺供氣潛水者，其氣瓶應多久檢點一次？",
 ["每半年","每一週","每一個月","每一年"],"a",
 "第54條第2款：使用緊急用氣瓶外之水肺供氣者，每月檢點深度表、每季檢點水中計時器、每半年檢點氣瓶。",
 "For scuba diving, cylinders must be inspected every:",
 ["Six months","One week","One month","One year"],
 "Article 54(2): depth gauge monthly, dive timer quarterly, cylinders every six months."),

(YC,"第62條",2,"異常氣壓-再壓室",
 "實施高壓室內作業時應設再壓室；再壓室應避免接近何種場所？",
 ["危險物、火藥類或大量易燃性物質儲存場所，及有出水、土砂崩塌之虞場所","工地辦公室、監工休息室及會議室等一般行政管理用房舍場所","員工餐廳、茶水間及休息室等供膳食使用之場所","機具停車場、材料堆置區及臨時倉庫等場所"],"a",
 "第62條：應設再壓室或採取可隨時利用再壓室之措施；再壓室應避免接近危險物火藥類或大量易燃性物質之處置儲存場所，及有出水、土砂崩塌之虞之場所。",
 "A recompression chamber for hyperbaric work must be kept away from:",
 ["Storage of dangerous goods, explosives or bulk flammables, and places at risk of flooding or collapse","Site offices, supervisor rest rooms, meeting rooms and other general administrative buildings","Staff canteens, tea rooms and rest rooms used for meals and refreshments","Equipment parking areas, material stacking yards and temporary storerooms"],
 "Article 62: keep away from dangerous goods, explosives or bulk flammables storage, and from places prone to water ingress or earth collapse."),

(YC,"第66條",2,"異常氣壓-再壓室",
 "再壓室應設置主再壓室及副再壓室，但何者不在此限？",
 ["移動型者","固定型者","室外設置者","新購置者"],"a",
 "第66條：再壓室應設置主再壓室及副再壓室，但移動型者不在此限。第67條：兩室之門應保持氣密，壓力相等時可易於開啟；第68條：均應設置可自外面觀察之視窗。",
 "A recompression chamber needs main and auxiliary compartments, except for:",
 ["Mobile chambers","Fixed chambers","Outdoor chambers","Newly bought chambers"],
 "Article 66: mobile chambers are exempt; Articles 67–68: airtight doors that open easily when pressures are equal, and viewing windows on both compartments."),

(YC,"第77條",2,"異常氣壓-再壓室",
 "再壓室內應置滅火所必要之水、砂或其他物品，但下列何者不在此限？",
 ["設有防火用灑水裝置、軟質水管或移動型再壓室者","再壓室內全面禁菸並設有煙霧偵測警報器者","室內備有乾粉滅火器及防火毯者","室外配置值班人員全程監視者"],"a",
 "第77條：再壓室內應置滅火所必要之水、砂或其他物品，但設有防火用灑水裝置、軟質水管或移動型再壓室者不在此限。第93條減壓艙亦同。",
 "Water, sand or similar firefighting items must be inside a recompression chamber, except when:",
 ["It has a sprinkler system, a soft water hose, or is a mobile chamber","Smoking is fully banned and smoke detectors and alarms are fitted","Dry powder extinguishers and a fire blanket are kept inside","A duty attendant outside keeps watch throughout the operation"],
 "Article 77: exempt if equipped with sprinklers or a soft water hose, or if mobile; Article 93 applies the same to decompression chambers."),

(YC,"第78條",2,"異常氣壓-減壓艙",
 "下列何者屬減壓艙應具備之設備？",
 ["內外雙向通話系統、可調節式氧氣呼吸口罩、視窗、深度表、計時表、安全閥","冷氣機、除濕機、空氣清淨機、電風扇、暖氣機、排油煙機及照明燈","電視機、收音機、音響設備、投影機、遊戲機及網路設備","冰箱、飲水機、微波爐、電磁爐、烘碗機及製冰機"],"a",
 "第78條：內外雙向通話系統、可調節式氧氣呼吸口罩、內外控制供排氣系統、水砂桶等滅火器具、內部照明系統、視窗、供排氣之深度控制閥及深度表、計時表、安全閥；並應置於潛水工作船或工作站等安全處所。",
 "Which are required decompression chamber equipment?",
 ["Two-way intercom, adjustable oxygen masks, viewports, depth gauge, timer, safety valve","Air conditioner, dehumidifier, air purifier, fan, heater, range hood and lamps","Television, radio, stereo system, projector, game console, network gear","Refrigerator, water dispenser, microwave, hotplate, dish dryer, ice maker"],
 "Article 78: intercom, adjustable oxygen masks, inside/outside supply and exhaust controls, water/sand fire kit, lighting, viewports, depth control valves and gauge, timer, safety valve; located in a safe place on the dive vessel or station."),

(YC,"第80條",3,"異常氣壓-減壓艙",
 "使潛水人員於減壓艙呼吸純氧減壓時，應先確認何事？",
 ["該潛水人員曾通過耐氧試驗，並於執行前通知該人員","該潛水人員已於下水前二小時內完成用餐進食","該潛水人員已於作業前連續休息滿八小時","減壓艙內溫度及濕度均維持於規定範圍"],"a",
 "第80條：由具資格之操作員操作；治療潛水病依醫師指示；使用前檢點；依減壓表執行；如醫療需要呼吸純氧減壓時應確定曾通過耐氧試驗並事前通知；持續監視；事先與最近潛水醫療單位連絡；記錄每次作業。",
 "Before having a diver breathe pure oxygen for decompression in the chamber, the operator must confirm:",
 ["The diver has passed an oxygen tolerance test and is informed beforehand","The diver finished a meal within two hours before entering the water","The diver has had eight straight hours of rest before the job","The chamber temperature and humidity are within the set range"],
 "Article 80: qualified operator; treatment per physician; pre-use check; follow tables; oxygen only for divers who passed the oxygen tolerance test and are notified; continuous monitoring; contact the nearest dive medical unit; record each session."),

(YC,"第80條",2,"異常氣壓-減壓艙",
 "減壓艙使用前，應事先與何單位連絡並保持通訊？",
 ["最近之潛水醫療單位","承保之產物保險公司","當地航政或港務機關","中央氣象主管機關"],"a",
 "第80條第6款：減壓艙使用前，應事先與最近之潛水醫療單位連絡，並保持通訊，以利緊急支援。",
 "Before using a decompression chamber, the employer shall contact and stay in touch with:",
 ["The nearest diving medical unit","The underwriting insurance company","The local port or shipping authority","The central weather authority"],
 "Article 80(6): contact the nearest diving medical unit in advance and maintain communication for emergency support."),

# ---------- 化學品標示 ----------
(HC,"第3條",2,"化學品標示-定義",
 "規則所稱「容器」，不包含下列何者？",
 ["交通工具內之引擎、燃料槽或其他操作系統","盛裝化學品之袋、筒、瓶、箱及金屬罐","製程用之反應器、儲槽及貯存容器","管路、軟管及其連接配件"],"a",
 "第3條第2款：容器指任何袋、筒、瓶、箱、罐、桶、反應器、儲槽、管路及其他可盛裝危害性化學品者，但不包含交通工具內之引擎、燃料槽或其他操作系統。",
 "The term 'container' under the Rules does NOT include:",
 ["Engines, fuel tanks or operating systems of vehicles","Bags, drums, bottles, boxes and metal cans for chemicals","Process reactors, storage tanks and holding vessels","Piping, hoses and their connecting fittings"],
 "Article 3(2): any bag, drum, bottle, box, can, barrel, reactor, tank, piping or other vessel, excluding vehicle engines, fuel tanks and operating systems."),

(HC,"第3條",1,"化學品標示-定義",
 "規則所稱「供應者」係指何者？",
 ["批發或零售危害性化學品之廠商","製造危害性化學品供處置使用之廠商","自國外輸入危害性化學品之廠商","使用危害性化學品之事業單位雇主"],"a",
 "第3條：製造者指製造危害性化學品供批發零售處置或使用之廠商；輸入者指從國外進口之廠商；供應者指批發或零售危害性化學品之廠商。",
 "A 'supplier' under the Rules is:",
 ["A business that wholesales or retails hazardous chemicals","A business that manufactures hazardous chemicals for use","A business that imports hazardous chemicals from abroad","An employer whose workplace uses hazardous chemicals"],
 "Article 3: manufacturer makes the chemicals; importer brings them in from abroad; supplier wholesales or retails them."),

(HC,"第5條",2,"化學品標示-混合物",
 "容器內之危害性化學品為混合物者，其應標示之「危害成分」指何者？",
 ["符合 CNS 15030 分類具物理性或健康危害之所有成分","混合物中依重量百分比計算含量最高之單一化學物質成分","混合物中作為主要溶劑使用之單一有機溶劑成分","混合物中任一含量超過百分之五之化學物質成分"],"a",
 "第5條第2項：混合物之危害成分指混合物之危害性中符合CNS 15030分類，具有物理性危害或健康危害之所有危害物質成分。",
 "For a mixture, the 'hazardous ingredients' to be labeled are:",
 ["All ingredients with physical or health hazards under CNS 15030 classification","The single ingredient with the highest weight percent in the mixture","Only the organic solvent used as the main solvent in the mixture","Any ingredient present in the mixture above five percent"],
 "Article 5(2): all hazardous ingredients classified under CNS 15030 as having physical or health hazards."),

(HC,"第9條",3,"化學品標示-公告板",
 "導管、化學設備等以公告板代替標示時，因製造者、輸入者或供應者名稱地址電話經常變更，在何條件下得免標示該事項？",
 ["備有安全資料表者","經主管簽名確認者","每月定期更新者","任何情形均不得免標示"],"a",
 "第9條第2項：第2至5款之容器有公告板者，其製造者輸入者或供應者名稱地址電話經常變更，但備有安全資料表者，得免標示第5條第1項第2款第6目之事項。",
 "When a notice board replaces labels on piping or chemical equipment, the supplier name/address/phone may be omitted if:",
 ["A safety data sheet is available","A manager has signed it off","It is updated every month","It can never be omitted at all"],
 "Article 9(2): where supplier details change frequently, they may be omitted if an SDS is kept available."),

(HC,"第14條",2,"化學品標示-SDS",
 "同一種類之混合物濃度不同而危害成分、用途及危害性相同時，得否使用同一份安全資料表？",
 ["得，但應註明不同化學品名稱","不得，應分別製作安全資料表","得，且無須註明化學品名稱","僅實驗室試藥得共用資料表"],"a",
 "第14條：混合物屬同一種類之化學品，其濃度不同而危害成分、用途及危害性相同時，得使用同一份安全資料表，但應註明不同化學品名稱。",
 "May mixtures of the same type but different concentrations, with identical hazardous ingredients, use and hazards, share one SDS?",
 ["Yes, but the different product names must be noted","No, a separate sheet must be made for each","Yes, and no product names need be noted","Only laboratory reagents may share one sheet"],
 "Article 14: one SDS may be shared, provided the different chemical names are indicated."),

(HC,"第15-1條",3,"化學品標示-SDS",
 "製造者提供之安全資料表有誤寫、缺漏等顯然錯誤時，主管機關應如何處理？",
 ["令其限期補正，屆期未補正者依職安法第44條第1項及第49條辦理","不經通知即直接吊銷其登記證照，並公告該事業單位名稱","不予處理，由製造者自行決定是否更正其內容","逕處新臺幣三百萬元罰鍰，並命令停工三個月"],"a",
 "第15條之1：安全資料表內容有誤寫、缺漏或其他類此顯然錯誤，主管機關或勞動檢查機構應令其限期補正；屆期未補正者，依本法第44條第1項及第49條規定辦理。",
 "If an SDS contains obvious clerical errors or omissions, the authority shall:",
 ["Order correction within a deadline; failure is handled under OSH Act Articles 44(1) and 49","Revoke the registration licence without notice and publicly publish the firm's name","Take no action and let the manufacturer decide whether to revise it","Fine NT$3 million outright and order a three-month work stoppage"],
 "Article 15-1: order correction by a deadline; if not corrected, apply Articles 44(1) and 49 of the OSH Act."),

(HC,"第17條",2,"化學品標示-通識",
 "危害性化學品清單之內容格式，應參照何附表？",
 ["附表五","附表一","附表三","附表四"],"a",
 "第17條第1項第2款：製作危害性化學品清單，其內容、格式參照附表五。附表一為分類及標示要項，附表三為應提供SDS之化學品，附表四為SDS格式。",
 "The hazardous chemical inventory format follows which annex?",
 ["Annex 5","Annex 1","Annex 3","Annex 4"],
 "Article 17(1)(2): inventory per Annex 5; Annex 1 covers classification and label elements, Annex 3 the chemicals needing SDSs, Annex 4 the SDS format."),

(HC,"第18條",3,"化學品標示-營業秘密",
 "申請保留揭示安全資料表資訊，檢附文件不齊全時，應於補正通知後幾日內補正？補正次數以幾次為限？",
 ["三十日；二次","十五日；一次","六十日；三次","七日；不限"],"a",
 "第18條第2項：申請者應於收受補正通知後三十日內補正，補正次數以二次為限；逾期未補正者不予受理。核定後查有不實得撤銷或廢止。",
 "For a trade-secret withholding application with incomplete documents, the deadline and maximum number of corrections are:",
 ["30 days; twice","15 days; once","60 days; three times","7 days; unlimited"],
 "Article 18(2): correct within 30 days of notice, at most twice; otherwise not accepted. Approval may be revoked if information is false."),

(HC,"第20條",2,"化學品標示-其他法規",
 "裝有危害性化學品之船舶、航空器或運送車輛之標示，應依何規定辦理？",
 ["交通法規有關運輸之規定","本規則附表一之規定","消防法有關危險物品之規定","環境用藥管理法之規定"],"a",
 "第20條：對裝有危害性化學品之船舶、航空器或運送車輛之標示，應依交通法規有關運輸之規定辦理。",
 "Labeling of ships, aircraft or vehicles carrying hazardous chemicals follows:",
 ["Transport provisions of traffic regulations","The provisions of Annex 1 of these Rules","Dangerous goods provisions of the Fire Services Act","The provisions of the Environmental Agents Control Act"],
 "Article 20: per the transport provisions of traffic regulations."),

(HC,"第21條",2,"化學品標示-其他法規",
 "放射性物質及 CNS 15030 分類之環境危害性化學品之標示，應依何規定辦理？",
 ["游離輻射及環境保護相關法規","本規則第5條之標示規定","交通法規有關運輸之規定","農藥管理法及動物用藥品管理法"],"a",
 "第21條：對放射性物質、CNS 15030分類之環境危害性化學品之標示，應依游離輻射及環境保護相關法規規定辦理。第22條：農藥及環境用藥依農藥及環境用藥相關法規。",
 "Labeling of radioactive substances and environmentally hazardous chemicals (CNS 15030) follows:",
 ["Ionizing radiation and environmental protection laws","The labeling provisions of Article 5 of these Rules","Transport provisions of traffic regulations","The Agro-pesticides and Veterinary Drugs Acts"],
 "Article 21: ionizing radiation and environmental laws; Article 22: pesticides and environmental agents follow their own laws."),

# ---------- 標示準則 ----------
(BS,"第1條",1,"標示-法源",
 "職業安全衛生標示設置準則係依職業安全衛生法第幾條規定訂定？",
 ["第六條第三項","第十條第三項","第十九條第二項","第三十二條"],"a",
 "第1條：本準則依職業安全衛生法第六條第三項規定訂定之。第2條：雇主設置之標示，除其他法規或國家標準另有規定外，依本準則辦理。",
 "The OSH Sign Installation Guidelines are enacted under which OSH Act article?",
 ["Article 6, paragraph 3","Article 10, paragraph 3","Article 19, paragraph 2","Article 32"],
 "Article 1: under Article 6(3); Article 2: employer signs follow these Guidelines unless other laws or national standards provide otherwise."),

(BS,"第3條",2,"標示-種類",
 "「高壓電」、「墜落」、「高熱」、「輻射」等危險之標示，屬何種標示？",
 ["警告標示","禁止標示","注意標示","說明標示"],"a",
 "第3條第1款第2目：警告標示：警告既存之危險或有害狀況，包括高壓電、墜落、高熱、輻射等危險。",
 "Signs for high voltage, falls, extreme heat or radiation are:",
 ["Warning signs","Prohibition signs","Caution signs","Information signs"],
 "Article 3(1)(2): warning signs warn of existing dangerous or harmful conditions such as high voltage, falls, heat and radiation."),

(BS,"第3條",2,"標示-種類",
 "反應塔、鍋爐房、安全門、急救箱、消防栓、機房等之標示，屬何種用途？",
 ["一般說明或提示之用途或處所標示","禁止不安全行為或狀況之禁止標示","警告既存危險或有害狀況之警告標示","提醒注意可能危害之注意標示"],"a",
 "第3條第2款：一般說明或提示包括用途或處所之標示（反應塔、鍋爐房、安全門、伐木區、急救箱、急救站、救護車、診所、消防栓、機房）、操作或儀控之標示、說明性質之標示。",
 "Signs for reactor towers, boiler rooms, emergency exits, first-aid kits, hydrants or machine rooms are:",
 ["General information signs indicating use or location","Prohibition signs banning unsafe acts or conditions","Warning signs for existing dangerous or harmful conditions","Caution signs alerting to possible harm"],
 "Article 3(2): general information covers location/use signs, operation/instrument signs, and explanatory signs such as directions and signal meanings."),
]
