# -*- coding: utf-8 -*-
# 第 9 批（A）：空氣品質惡化警告、固定污染源許可證、空污費、VOC 標準、鍋爐排放標準、
#              停車怠速、行為管制準則、空品監測站準則、噪音管制區、易發生噪音設施、機動車輛噪音
W = "ENV-29"; P = "ENV-32"; F = "ENV-33"; V = "ENV-34"; B = "ENV-35"; I = "ENV-36"
C = "ENV-37"; M = "ENV-38"; N = "ENV-41"; S = "ENV-42"; R = "ENV-43"

Q = [

# ---------- ENV-29 空氣品質嚴重惡化警告發布及緊急防制辦法（115/3/18） ----------
(W,"第2條",1,"空品惡化-警告等級",
 "空氣品質惡化警告依污染程度區分為幾類別幾等級？各類別之等級細分為何？",
 ["預警（初級、中級）及嚴重惡化（輕度、中度、重度）二類別五等級",
  "預警（初級、中級、高級）及嚴重惡化（輕度、重度）二類別五等級",
  "預警（輕度、中度）及嚴重惡化（初級、中級、重度）二類別五等級",
  "預警（初級）及嚴重惡化（輕度、中度、重度、極重度）二類別五等級"],"a",
 "第2條：空氣品質惡化警告等級依污染程度區分為預警（細分初級、中級）及嚴重惡化（細分輕度、中度或重度）二類別五等級，依懸浮微粒、細懸浮微粒、二氧化硫、二氧化氮、一氧化碳及臭氧之濃度條件依附件一判定。所稱空氣品質嚴重惡化，包含任一空氣污染物濃度達附件一所定輕度、中度或重度嚴重惡化等級者。",
 "Air quality deterioration warnings are divided into how many categories and levels, and how are they subdivided?",
 ["Alert (primary, intermediate) and severe deterioration (mild, moderate, heavy): two categories, five levels",
  "Alert (primary, intermediate, advanced) and severe deterioration (mild, heavy): two categories, five levels",
  "Alert (mild, moderate) and severe deterioration (primary, intermediate, heavy): two categories, five levels",
  "Alert (primary only) and severe deterioration (mild, moderate, heavy, extreme): two categories, five levels"],
 "Article 2 sets two categories and five levels, judged against the pollutant concentrations in Annex 1."),

(W,"第3條",2,"空品惡化-預報通報",
 "中央主管機關空氣品質預報資料應至少每日發布幾次？第一次應於何時前發布？可能達預警或嚴重惡化等級時應於何時前通報地方？",
 ["每日至少二次；第一次於當日十二時以前發布；預報當日十七時三十分前通報地方主管機關",
  "每日至少一次；第一次於當日八時以前發布；預報當日十二時三十分前通報地方主管機關",
  "每日至少三次；第一次於當日六時以前發布；預報次日八時三十分前通報地方主管機關",
  "每日至少二次；第一次於當日十五時以前發布；預報當日二十時三十分前通報地方主管機關"],"a",
 "第3條：中央主管機關應發布空氣品質預報資料，至少每日發布二次，且第一次應於當日十二時以前發布；預報顯示可能達預警或嚴重惡化等級者，應於預報當日十七時三十分前通報空氣品質區內各直轄市、縣（市）主管機關，地方應於公開平台或網頁登載氣象、空氣品質變化趨勢等預測資料。",
 "How often must central air quality forecasts be issued, by when is the first one, and by when must local authorities be notified?",
 ["At least twice daily; the first before 12:00 that day; local authorities notified before 17:30 on the forecast day",
  "At least once daily; the first before 08:00 that day; local authorities notified before 12:30 on the forecast day",
  "At least three times daily; the first before 06:00 that day; local authorities notified before 08:30 the next day",
  "At least twice daily; the first before 15:00 that day; local authorities notified before 20:00 on the forecast day"],
 "Article 3: twice daily, first before noon, notification before 17:30."),

(W,"第7條",3,"空品惡化-指揮中心",
 "直轄市、縣（市）主管機關「應」成立空氣污染防制指揮中心之條件為何？",
 ["預報顯示隔日起轄區連續二日達中級預警或嚴重惡化；或轄區內二分之一以上測站達中級預警，或任一測站達輕度嚴重惡化以上",
  "預報顯示隔日起轄區連續三日達初級預警等級；或轄區內三分之一以上測站達中級預警，或任一測站達中度嚴重惡化以上",
  "預報顯示隔日起轄區連續二日達初級預警等級；或轄區內四分之三以上測站達初級預警，或任一測站達重度嚴重惡化等級",
  "預報顯示隔日起轄區連續五日達中級預警等級；或轄區內全部測站均達中級預警，或任一測站達中度嚴重惡化以上"],"a",
 "第7條第1款第2目：應成立於預報顯示隔日起轄區空氣品質可能有連續二日達中級預警或嚴重惡化等級；或轄區內二分之一以上測站達中級預警等級，或任一測站達輕度嚴重惡化或以上等級。指揮官由地方主管機關首長或其授權之人擔任，成員包含環保、衛生、勞工、水利、農業、教育及交通等機關代表；成立時應立即通報中央主管機關。",
 "When must a local authority establish an air pollution control command center?",
 ["Forecast shows two consecutive days at intermediate alert or severe deterioration; or half of stations at intermediate alert, or any station at mild severe deterioration or above",
  "Forecast shows three consecutive days at primary alert level; or one third of all stations at intermediate alert, or any station at moderate severe deterioration or above",
  "Forecast shows two consecutive days at primary alert; or three quarters of stations at primary alert, or any station at heavy severe deterioration",
  "Forecast shows five consecutive days at intermediate alert; or all stations at intermediate alert, or any station at moderate severe deterioration or above"],
 "Article 7, item 1(2)."),

(W,"第16條",2,"空品惡化-中央指揮中心",
 "中央空氣污染防制指揮中心之成立條件及指揮官為何？",
 ["全國除連江、金門及澎湖縣外，同時有九個以上地方主管機關成立指揮中心時成立；指揮官由環境部部長或其授權之人擔任",
  "全國除連江、金門及澎湖縣外，同時有六個以上地方主管機關成立指揮中心時成立；指揮官由行政院院長或其授權之人擔任",
  "全國除連江、金門及澎湖縣外，同時有十二個以上地方主管機關成立指揮中心時成立；指揮官由經濟部部長或其授權之人擔任",
  "全國除連江、金門及澎湖縣外，同時有三個以上地方主管機關成立指揮中心時成立；指揮官由各地方首長輪流擔任之"],"a",
 "第16條：當全國除連江縣、金門縣及澎湖縣以外，同時有九個以上直轄市、縣（市）主管機關成立空氣污染防制指揮中心時，中央主管機關應成立中央空氣污染防制指揮中心，協調處理跨區域污染源管制事宜；指揮官由環境部部長或其授權之人擔任，成員包含環境部、經濟部、國科會、勞動部、衛福部、教育部、交通部、農業部等機關代表。",
 "When is the central air pollution control command center established, and who commands it?",
 ["When nine or more local authorities (excluding Lienchiang, Kinmen, Penghu) have set up command centers; commanded by the Minister of Environment or a delegate",
  "When six or more local authorities (excluding Lienchiang, Kinmen, Penghu) have set up command centers; commanded by the Premier or a delegate",
  "When twelve or more local authorities (excluding Lienchiang, Kinmen, Penghu) have set up command centers; commanded by the Minister of Economic Affairs or a delegate",
  "When three or more local authorities (excluding Lienchiang, Kinmen, Penghu) have set up command centers; commanded by local heads in rotation"],
 "Article 16: nine or more local command centers; Minister of Environment commands."),

(W,"第9條",2,"空品惡化-警告通知",
 "地方主管機關發布空氣品質預警或嚴重惡化警告時之通知方式，及發布嚴重惡化警告時應額外執行之事項為何？",
 ["以書面、傳真、電子郵件或通訊軟體通知相關單位；並協調新聞傳播媒體適時插播，至嚴重惡化警告解除為止",
  "僅以公文郵寄方式通知相關單位；並協調新聞傳播媒體適時插播，至警告發布之當日二十四時為止",
  "以口頭或電話方式通知相關單位即可；並協調新聞傳播媒體於警告期間每週至少插播一次相關訊息",
  "以政府公報公告方式通知相關單位；並協調新聞傳播媒體於警告發布後三日內插播一次相關訊息"],"a",
 "第9條：發布警告時應以書面、傳真、電子郵件或通訊軟體等方式，載明警告區域、氣象及空氣品質變化趨勢、應變防制措施、健康防護引導措施等，通知政府機關、各級學校、幼兒園、福利機構、護理機構、車站、醫院等公共場所及指定公私場所；發布嚴重惡化警告時，並應協調新聞傳播媒體適時插播至警告解除為止，及啟動通報機制。",
 "How are warnings communicated, and what extra step applies to severe deterioration warnings?",
 ["Written notice, fax, email or messaging apps; plus coordinating media inserts until the severe deterioration warning is lifted",
  "Mailed official letters only; plus coordinating media inserts until 24:00 on the day on which the warning is issued",
  "Oral or telephone notice suffices; plus coordinating media inserts at least once a week during the warning",
  "Notice by government gazette; plus coordinating one media insert within three days after the warning"],
 "Article 9."),

(W,"第14條",3,"空品惡化-調降解除",
 "空氣品質預警或嚴重惡化警告發布後，於何種條件下得調降等級？於何種條件下得解除預警警告？",
 ["濃度未達原等級且預測未來六小時有減緩惡化趨勢得調降；濃度未達初級預警等級得解除預警警告",
  "濃度未達原等級且預測未來十二小時有減緩惡化趨勢得調降；濃度未達中級預警等級得解除預警警告",
  "濃度未達原等級且預測未來二十四小時有減緩趨勢得調降；濃度未達輕度嚴重惡化等級得解除警告",
  "濃度低於原等級之半數且預測未來三小時有減緩趨勢得調降；須報經中央主管機關核准後始得解除"],"a",
 "第14條：於空氣污染物濃度未達原預警或嚴重惡化等級，且預測未來六小時有減緩惡化趨勢，地方主管機關得調降等級；於濃度未達初級預警等級，得解除預警警告，通知相關單位停止應變防制措施，並提報執行結果送中央主管機關備查。第4條第2項則以預測未來十二小時無減緩趨勢作為發布依據。",
 "When may a warning level be lowered, and when may the alert be lifted?",
 ["Below the original level and forecast easing within six hours to lower it; below primary alert level to lift it",
  "Below the original level and forecast easing within twelve hours to lower it; below intermediate alert level to lift it",
  "Below the original level and forecast easing within twenty-four hours to lower it; below mild severe deterioration to lift it",
  "Below half the original level and easing within three hours to lower it; central approval is required to lift it"],
 "Article 14."),

(W,"第12條",2,"空品惡化-行為管制",
 "地方主管機關應於每年何期間依空氣品質預報資料執行附件六之行為管制？嚴重惡化警告發布後中央應多久蒐集氣象資料一次？",
 ["每年一月至三月及十月至十二月執行行為管制；中央主管機關至少每六小時蒐集氣象資料一次",
  "每年四月至六月及九月至十一月執行行為管制；中央主管機關至少每十二小時蒐集氣象資料一次",
  "每年一月至四月及十一月至十二月執行行為管制；中央主管機關至少每三小時蒐集氣象資料一次",
  "每年全年不分月份均執行行為管制；由地方主管機關至少每二十四小時蒐集氣象資料一次"],"a",
 "第12條：直轄市、縣（市）主管機關應於每年一月至三月及十月至十二月，依空氣品質預報資料執行附件六之行為管制，限制相關易致空氣污染之行為。第13條：空氣品質嚴重惡化警告發布後，中央主管機關應至少每六小時蒐集氣象資料一次，並視濃度及氣象變化提供地方，以調整警告等級及警告區域。",
 "During which months is behavioral control carried out, and how often must the central authority collect weather data after a severe deterioration warning?",
 ["January to March and October to December; the central authority collects weather data at least every six hours",
  "April to June and September to November; the central authority collects weather data at least every twelve hours",
  "January to April and November to December; the central authority collects weather data at least every three hours",
  "All year round without distinction; the local authority collects weather data at least every twenty-four hours"],
 "Articles 12 and 13."),

# ---------- ENV-32 固定污染源設置操作及燃料使用許可證管理辦法（108/9/26） ----------
(P,"第3條",2,"固污許可-燃料許可",
 "公私場所固定污染源使用生煤或指定公告燃料應申請燃料使用許可證，但何種情形不在此限？",
 ["僅使用石油煉製業煉製販售符合國家標準之石油製品，或每年總設計、實際燃料使用量低於五百公斤或五百公升者",
  "僅使用石油煉製業煉製販售符合國家標準之石油製品，或每年總設計、實際燃料使用量低於五千公斤或五千公升者",
  "僅使用經目的事業主管機關核准之進口燃料，或每年總設計、實際燃料使用量低於一百公斤或一百公升者",
  "僅使用經環境工程技師簽證之低硫燃料，或每年總設計、實際燃料使用量低於一千公斤或一千公升者"],"a",
 "第3條：使用生煤或其他依空污法第28條第1項指定公告之燃料應申請燃料使用許可證，但僅使用石油煉製業煉製販售符合國家標準之石油製品，或每年總設計、實際燃料使用量低於五百公斤或五百公升者，不在此限。第26條：領有燃料使用許可證者應於每年一、四、七、十月底前申報前季燃料使用量。",
 "Which situation exempts a source from applying for a fuel use permit?",
 ["Using only national-standard petroleum products refined and sold by refiners, or annual design or actual fuel use below 500 kg or 500 liters",
  "Using only national-standard petroleum products refined and sold by refiners, or annual design or actual fuel use below 5,000 kg or 5,000 liters",
  "Using only imported fuel approved by the industry competent authority, or annual design or actual fuel use below 100 kg or 100 liters",
  "Using only low-sulfur fuel certified by an environmental engineer, or annual design or actual fuel use below 1,000 kg or 1,000 liters"],
 "Article 3."),

(P,"第4條",3,"固污許可-變更認定",
 "空污法第24條所稱固定污染源之「變更」，其排放量門檻為何？",
 ["任一污染物年排放量推估較許可證記載增加達百分之二十及五公噸以上；或氮氧化物達五公噸、硫氧化物達十公噸、揮發性有機物達五公噸、粒狀物達十公噸以上",
  "任一污染物年排放量推估較許可證記載增加達百分之十及一公噸以上；或氮氧化物達十公噸、硫氧化物達五公噸、揮發性有機物達十公噸、粒狀物達五公噸以上",
  "任一污染物年排放量推估較許可證記載增加達百分之三十及十公噸以上；或氮氧化物達二公噸、硫氧化物達二公噸、揮發性有機物達二公噸、粒狀物達二公噸以上",
  "任一污染物年排放量推估較許可證記載增加達百分之五及零點五公噸以上；或氮氧化物達一公噸、硫氧化物達一公噸、揮發性有機物達一公噸、粒狀物達一公噸以上"],"a",
 "第4條：所稱變更指設備更換或擴增、製程、原（物）料、燃料或產品改變，致增加空氣污染物排放種類；或任一污染物年排放量推估較許可證記載之年許可排放量增加達百分之二十及五公噸以上；或增加達氮氧化物五公噸、硫氧化物十公噸、揮發性有機物五公噸、粒狀物十公噸以上者。因增設空氣污染防制設施而致增加者，得依操作許可證異動程序辦理。",
 "What emission thresholds define a modification under Article 24 of the Act?",
 ["Any pollutant increasing by 20 percent and 5 tonnes or more over the permitted annual amount; or NOx 5 t, SOx 10 t, VOC 5 t, particulates 10 t or more",
  "Any pollutant increasing by 10 percent and 1 tonne or more over the permitted annual amount; or NOx 10 t, SOx 5 t, VOC 10 t, particulates 5 t or more",
  "Any pollutant increasing by 30 percent and 10 tonnes or more over the permitted annual amount; or NOx 2 t, SOx 2 t, VOC 2 t, particulates 2 t or more",
  "Any pollutant increasing by 5 percent and 0.5 tonne or more over the permitted annual amount; or NOx 1 t, SOx 1 t, VOC 1 t, particulates 1 t or more"],
 "Article 4."),

(P,"第9條",2,"固污許可-容許差值",
 "許可證記載之各項許可條件或數值得有多少容許差值？試車或檢測時主要原（物）料及燃料使用量未達申請量百分之八十者應如何核定操作條件？",
 ["得有百分之十容許差值；以試車或檢測時實際操作條件之一點二倍作為操作許可證核定內容",
  "得有百分之二十容許差值；以試車或檢測時實際操作條件之一點五倍作為操作許可證核定內容",
  "得有百分之五容許差值；以試車或檢測時實際操作條件之二倍作為操作許可證之核定內容",
  "得有百分之十五容許差值；以申請書所載之最大設計量作為操作許可證之核定內容"],"a",
 "第9條：許可證記載之各項許可條件或數值，於未超過防制設施最大處理容量且符合排放標準及相關管制規定者，得有百分之十之容許差值。第41條：主要原（物）料及燃料使用量達申請之百分之八十以上者，依申請內容核定；無法達百分之八十以上者，應以試車或檢測時實際操作條件之一點二倍作為核定內容。",
 "What tolerance applies to permit values, and how are operating conditions set when test-run usage is below 80 percent of the application?",
 ["A 10 percent tolerance; operating conditions set at 1.2 times the actual test-run conditions",
  "A 20 percent tolerance; operating conditions set at 1.5 times the actual test-run conditions",
  "A 5 percent tolerance; operating conditions set at 2 times the actual test-run conditions",
  "A 15 percent tolerance; operating conditions set at the maximum design capacity in the application"],
 "Articles 9 and 41."),

(P,"第20條",3,"固污許可-試車期限",
 "公私場所接到空氣污染物排放檢測通知後應於幾日內完成檢測？核准試車期限上限及含展延之試車總日數上限各為何？",
 ["接到通知後六十日內完成檢測；核准試車期限不得超過一百日；含展延之試車總日數不得超過一百九十日",
  "接到通知後三十日內完成檢測；核准試車期限不得超過六十日；含展延之試車總日數不得超過一百二十日",
  "接到通知後九十日內完成檢測；核准試車期限不得超過一百五十日；含展延之試車總日數不得超過三百日",
  "接到通知後十五日內完成檢測；核准試車期限不得超過九十日；含展延之試車總日數不得超過一百八十日"],"a",
 "第20條：接到試車通知者應依試車計畫書完成試車，並於核准試車期限屆滿前十五日內提送檢測報告；接到空氣污染物排放檢測通知者，應於六十日內完成檢測。核准試車期限不得超過一百日，展延申請次數不得超過二次，且含原核准期限之試車總日數不得超過一百九十日。第33條：審核機關應於收到檢測報告後十五日內完成審查，必要時得延長十日。",
 "Deadlines for completing emission testing, the approved test-run period, and total test-run days with extensions:",
 ["Testing within 60 days of notice; approved test run up to 100 days; total test-run days up to 190",
  "Testing within 30 days of notice; approved test run up to 60 days; total test-run days up to 120",
  "Testing within 90 days of notice; approved test run up to 150 days; total test-run days up to 300",
  "Testing within 15 days of notice; approved test run up to 90 days; total test-run days up to 180"],
 "Article 20."),

(P,"第31條",3,"固污許可-審查期限",
 "審核機關受理許可證申請之形式審查及實質審查期限各為何？",
 ["形式審查自收件日起七日內完成並通知七日內繳費；實質審查自完成繳費翌日起三十五日內完成並通知結果",
  "形式審查自收件日起十四日內完成並通知十五日內繳費；實質審查自完成繳費翌日起六十日內完成並通知結果",
  "形式審查自收件日起三日內完成並通知三日內繳費；實質審查自完成繳費翌日起二十日內完成並通知結果",
  "形式審查自收件日起十日內完成並通知七日內繳費；實質審查自受理申請之日起四十五日內完成並通知結果"],"a",
 "第31條：形式審查應於收到網路申請及書面資料後七日內完成，並通知公私場所於七日內繳納審查費；實質審查應自完成繳費翌日起三十五日內完成審查、諮詢及通知結果。必要時得延長實質審查十五日；第一類固定污染源設置、操作許可證得延長三十日；符合第14條或第15條之設置許可證申請得延長四十五日。",
 "What are the formal and substantive review deadlines for permit applications?",
 ["Formal review within 7 days of receipt with 7 days to pay fees; substantive review within 35 days after payment",
  "Formal review within 14 days of receipt with 15 days to pay fees; substantive review within 60 days after payment",
  "Formal review within 3 days of receipt with 3 days to pay fees; substantive review within 20 days after payment",
  "Formal review within 10 days of receipt with 7 days to pay fees; substantive review within 45 days of acceptance"],
 "Article 31."),

(P,"第45條",3,"固污許可-補正期限",
 "審核機關通知限期補正之總補正次數及總補正日數規定為何？",
 ["總補正次數以三次為限；形式資料欠缺或未繳費不得超過十四日，設置、操作及燃料文件不合規定不得超過九十日，展延文件不合規定不得超過三十日",
  "總補正次數以二次為限；形式資料欠缺或未繳費不得超過七日，設置、操作及燃料文件不合規定不得超過六十日，展延文件不合規定不得超過十四日",
  "總補正次數以五次為限；形式資料欠缺或未繳費不得超過三十日，設置、操作及燃料文件不合規定不得超過一百二十日，展延文件不得超過六十日",
  "總補正次數並無限制；形式資料欠缺或未繳費不得超過十日，設置、操作及燃料文件不合規定不得超過四十五日，展延文件不得超過二十日"],"a",
 "第45條：屆期未補正或超過總補正日數者應駁回申請；屬第36條第3款至第6款者，期限內補正仍不合規定得再通知限期補正，總補正次數以三次為限。總補正日數：第36條第1款或第2款不得超過十四日、第3款至第5款不得超過九十日、第6款不得超過三十日；補正日數不算入審查期間。",
 "How many rounds of supplementation are allowed and what are the total day limits?",
 ["Up to three rounds; 14 days for missing formal documents or unpaid fees, 90 days for non-conforming installation, operation and fuel documents, 30 days for renewal documents",
  "Up to two rounds; 7 days for missing formal documents or unpaid fees, 60 days for non-conforming installation, operation and fuel documents, 14 days for renewal documents",
  "Up to five rounds; 30 days for missing formal documents or unpaid fees, 120 days for non-conforming installation, operation and fuel documents, 60 days for renewal documents",
  "No limit on rounds; 10 days for missing formal documents or unpaid fees, 45 days for non-conforming installation, operation and fuel documents, 20 days for renewal documents"],
 "Article 45."),

(P,"第29條",2,"固污許可-換發補發",
 "許可證於有效期間內因毀損、滅失或基本資料改變者，應於幾日內申請換發或補發？審核機關應於幾日內完成審查及製證？",
 ["應於事實發生後六十日內申請；審核機關應於十四日內完成審查及證書製作，並通知十四日內繳費領證",
  "應於事實發生後三十日內申請；審核機關應於七日內完成審查及證書製作，並通知七日內繳費領證",
  "應於事實發生後十五日內申請；審核機關應於三十日內完成審查及證書製作，並通知三十日內繳費領證",
  "應於事實發生後九十日內申請；審核機關應於二十日內完成審查及證書製作，並通知十日內繳費領證"],"a",
 "第29條：許可證於有效期間內因毀損、滅失或所載基本資料改變者，得於事實發生後六十日內檢具證明文件申請換發或補發；逾期經通知者應於通知翌日起十日內申請。審核機關應於十四日內完成審查及證書製作，並通知審查符合規定者於十四日內繳納證書費及領取許可證。",
 "Within how long must a damaged, lost or changed permit be re-issued, and how fast must the authority act?",
 ["Apply within 60 days of the event; the authority completes review and issuance within 14 days and gives 14 days to pay and collect",
  "Apply within 30 days of the event; the authority completes review and issuance within 7 days and gives 7 days to pay and collect",
  "Apply within 15 days of the event; the authority completes review and issuance within 30 days and gives 30 days to pay and collect",
  "Apply within 90 days of the event; the authority completes review and issuance within 20 days and gives 10 days to pay and collect"],
 "Article 29."),

(P,"第21條",2,"固污許可-紀錄申報",
 "操作許可證所載監測、檢測、操作及維修紀錄應保存幾年？領有燃料使用許可證者應於何時申報前季燃料使用量？",
 ["應保存六年備查；應於每年一月、四月、七月及十月底前申報前季燃料使用量",
  "應保存三年備查；應於每年三月、六月、九月及十二月底前申報前季燃料使用量",
  "應保存五年備查；應於每年二月、五月、八月及十一月底前申報前季燃料使用量",
  "應保存十年備查；應於每年一月及七月底前申報前半年之燃料使用量"],"a",
 "第21條：操作許可證所列監測、定期檢測、紀錄、申報及操作與維修紀錄，應保存六年備查，並應建立電子化紀錄，未能電子化者經主管機關同意得以紙本代之。第26條：領有燃料使用許可證者，應依電子網路傳輸方式，於每年一月、四月、七月及十月底前，向直轄市、縣（市）主管機關申報前季燃料之使用量。",
 "How long must operating permit records be kept, and when is quarterly fuel use reported?",
 ["Kept six years; reported by the end of January, April, July and October each year",
  "Kept three years; reported by the end of March, June, September and December each year",
  "Kept five years; reported by the end of February, May, August and November each year",
  "Kept ten years; reported by the end of January and July each year for the prior half-year"],
 "Articles 21 and 26."),

# ---------- ENV-33 空氣污染防制費收費辦法（111/3/24） ----------
(F,"第2條",2,"空污費-申報期限",
 "依油燃料種類成分數量徵收之空污費應於何時申報繳納？依排放空氣污染物種類數量徵收者應於何時申報？",
 ["銷售者或進口者於每月十五日前申報前月份；固定污染源於每年四月、七月、十月及次年一月底前申報前季",
  "銷售者或進口者於每月月底前申報前月份；固定污染源於每年三月、六月、九月及十二月底前申報前季",
  "銷售者或進口者於每季十五日前申報前季；固定污染源於每年一月及七月底前申報前半年之排放量",
  "銷售者或進口者於每月五日前申報前月份；固定污染源於每年二月、五月、八月及十一月底前申報前季"],"a",
 "第2條：依銷售數量或油燃料種類成分與數量徵收者，銷售者或進口者應於每月十五日前填具申報書及繳款單，自行繳納後以網路傳輸向中央主管機關申報前月份費額。第3條：依排放空氣污染物種類及數量徵收者，固定污染源之所有人、實際使用人或管理人應於每年四月、七月、十月及次年一月底前申報並繳納前季費額。",
 "When are fuel-based and emission-based air pollution control fees reported?",
 ["Sellers or importers by the 15th of each month for the prior month; stationary sources by end of April, July, October and next January for the prior quarter",
  "Sellers or importers by the end of each month for the prior month; stationary sources by end of March, June, September and December for the prior quarter",
  "Sellers or importers by the 15th of each quarter for the prior quarter; stationary sources by end of January and July for the prior half-year",
  "Sellers or importers by the 5th of each month for the prior month; stationary sources by end of February, May, August and November for the prior quarter"],
 "Articles 2 and 3."),

(F,"第3條",3,"空污費-小量年申報",
 "固定污染源當年度各季排放量甚小者，得如何調整申報方式？其後任一季超過門檻應如何處理？",
 ["經核定各季個別污染物排放量皆在一公噸以下者，得調整為每年一月底前一次申報繳納；任一季超過一公噸應即恢復按季申報",
  "經核定各季個別污染物排放量皆在十公噸以下者，得調整為每年七月底前一次申報繳納；任一季超過十公噸應即恢復按季申報",
  "經核定各季個別污染物排放量皆在五公噸以下者，得調整為每半年申報繳納一次；任一季超過五公噸應即改為按月申報",
  "經核定各季個別污染物排放量皆在零點五公噸以下者，得免予申報及繳納；任一季超過零點五公噸應改為按月申報"],"a",
 "第3條第3項：公私場所固定污染源當年度各季排放之空氣污染物，經中央主管機關核定其個別污染物種類排放量皆於一公噸以下者，得於次年一月底前報經中央主管機關同意，調整為每年一月底前將前一年各季排放量與費額一次申報及繳納。第4項：其個別污染物排放量任一季超過一公噸者，應即依第1項規定按季申報、繳費。",
 "How may small emitters adjust their reporting, and what if a quarter exceeds the threshold?",
 ["If each quarter's individual pollutant emissions are approved at 1 tonne or less, report once yearly by end of January; exceeding 1 tonne in any quarter restores quarterly reporting",
  "If each quarter's individual pollutant emissions are approved at 10 tonnes or less, report once yearly by end of July; exceeding 10 tonnes in any quarter restores quarterly reporting",
  "If each quarter's individual pollutant emissions are approved at 5 tonnes or less, report once every half year; exceeding 5 tonnes in any quarter switches to monthly reporting",
  "If each quarter's individual pollutant emissions are approved at 0.5 tonne or less, reporting is waived; exceeding 0.5 tonne in any quarter switches to monthly reporting"],
 "Article 3, paragraphs 3 and 4."),

(F,"第6條",2,"空污費-營建繳納",
 "營建工程空氣污染防制費之繳納期限規定為何？",
 ["費額一萬元以下應於開工前全額繳納；超過一萬元未滿五百萬元得先繳二分之一；五百萬元以上得於工程期間分期平均繳納",
  "費額五萬元以下應於開工前全額繳納；超過五萬元未滿一千萬元得先繳三分之一；一千萬元以上得於工程期間分期平均繳納",
  "費額十萬元以下應於開工前全額繳納；超過十萬元未滿三百萬元得先繳四分之一；三百萬元以上得於工程期間分期平均繳納",
  "費額一千元以下應於開工前全額繳納；超過一千元未滿一百萬元得先繳二分之一；一百萬元以上得於工程期間分期平均繳納"],"a",
 "第6條：依法不須申請開工、使用執照、工程驗收或費額為一萬元以下者，應於開工前全額繳納；超過一萬元未滿五百萬元者，得於開工前全額繳納，或申請開工前先繳二分之一，於申請使用執照或工程驗收前繳納剩餘費額；五百萬元以上者，得於開工前全額繳納或於工程期間分期平均繳納。第21條：每件營建工程核算應繳費額一百元以下者免繳納。",
 "What are the payment deadlines for construction project air pollution fees?",
 ["Under NT$10,000 paid in full before starting work; over NT$10,000 but under NT$5 million may pay half first; NT$5 million or more may pay in equal installments during construction",
  "Under NT$50,000 paid in full before starting work; over NT$50,000 but under NT$10 million may pay one third first; NT$10 million or more may pay in equal installments during construction",
  "Under NT$100,000 paid in full before starting work; over NT$100,000 but under NT$3 million may pay one quarter first; NT$3 million or more may pay in equal installments during construction",
  "Under NT$1,000 paid in full before starting work; over NT$1,000 but under NT$1 million may pay half first; NT$1 million or more may pay in equal installments during construction"],
 "Article 6."),

(F,"第5條",3,"空污費-工期起算",
 "營建業主未依規定申報而經查獲已施工，且依法不須取得執照或許可者，其工期起算日如何推算？",
 ["地上層工程每層最多以九十日計算；地下層工程每層最多以一百二十日計算；開挖整地等雜項工程最多以一百八十日計算",
  "地上層工程每層最多以六十日計算；地下層工程每層最多以九十日計算；開挖整地等雜項工程最多以一百二十日計算",
  "地上層工程每層最多以一百二十日計算；地下層工程每層最多以九十日計算；開挖整地等雜項工程最多以三百六十日計算",
  "地上層工程每層最多以三十日計算；地下層工程每層最多以六十日計算；開挖整地等雜項工程最多以九十日計算"],"a",
 "第5條第3項第2款：依法不須取得執照或許可者，自地方主管機關查獲之日起往前推算工期起算日，地上層工程每層最多以九十日計算、地下層工程每層最多以一百二十日計算、建築法規定之開挖整地、倉庫、煙囪或圍牆等雜項工程最多以一百八十日計算。屬須取得執照者，原則以核准開工日期認定。",
 "How is the construction start date back-calculated when no license is legally required?",
 ["At most 90 days per above-ground floor; at most 120 days per below-ground floor; at most 180 days for excavation and other miscellaneous works",
  "At most 60 days per above-ground floor; at most 90 days per below-ground floor; at most 120 days for excavation and other miscellaneous works",
  "At most 120 days per above-ground floor; at most 90 days per below-ground floor; at most 360 days for excavation and other miscellaneous works",
  "At most 30 days per above-ground floor; at most 60 days per below-ground floor; at most 90 days for excavation and other miscellaneous works"],
 "Article 5, paragraph 3, subparagraph 2."),

(F,"第11條",3,"空污費-查核差異",
 "以檢測結果計算排放量之固定污染源，其檢測結果與申報數值差異達多少應重新核算？以質量平衡計量方式者，原（物）料成分檢測查核差異達多少應重新核算？",
 ["檢測結果換算單位活動強度排放量與申報值差異達百分之二十以上；質量平衡之成分檢測查核差異達百分之十以上",
  "檢測結果換算單位活動強度排放量與申報值差異達百分之十以上；質量平衡之成分檢測查核差異達百分之二十以上",
  "檢測結果換算單位活動強度排放量與申報值差異達百分之三十以上；質量平衡之成分檢測查核差異達百分之十五以上",
  "檢測結果換算單位活動強度排放量與申報值差異達百分之五以上；質量平衡之成分檢測查核差異達百分之二十五以上"],"a",
 "第11條：中央主管機關檢測結果換算單位活動強度之排放量，與公私場所申報數值差異達百分之二十以上者，應以查驗結果重新核算排放量並核定費額。第12條：以質量平衡計量方式計算者，其原（物）料中揮發性有機物成分含量重量百分比之檢測查核結果與申報結果差異達百分之十以上者，應重新核算排放量。",
 "What discrepancy triggers recalculation for test-based and for mass-balance-based emission reporting?",
 ["Test results per unit activity differing from the declared value by 20 percent or more; mass balance composition testing differing by 10 percent or more",
  "Test results per unit activity differing from the declared value by 10 percent or more; mass balance composition testing differing by 20 percent or more",
  "Test results per unit activity differing from the declared value by 30 percent or more; mass balance composition testing differing by 15 percent or more",
  "Test results per unit activity differing from the declared value by 5 percent or more; mass balance composition testing differing by 25 percent or more"],
 "Articles 11 and 12."),

(F,"第13條",3,"空污費-改採質量平衡",
 "公私場所以排放係數計算揮發性有機物排放量者，於何種情形應改以質量平衡計量方式計算？自何時起適用？",
 ["申報季排放量與中央主管機關查核結果差異達二倍以上及七點五公噸以上；自收到通知文件之次季起改以質量平衡計量方式計算",
  "申報季排放量與中央主管機關查核結果差異達三倍以上及十公噸以上；自收到通知文件之次年起改以質量平衡計量方式計算",
  "申報季排放量與中央主管機關查核結果差異達一點五倍以上及五公噸以上；自收到通知文件之當季起改以排放係數方式計算",
  "申報季排放量與中央主管機關查核結果差異達五倍以上及二十公噸以上；自收到通知文件之次月起改以連續監測方式計算"],"a",
 "第13條：公私場所選擇以排放係數計算揮發性有機物排放量者，其申報季排放量與中央主管機關查核結果差異達二倍以上及七．五公噸以上時，應於收到中央主管機關通知文件之次季起，以質量平衡計量方式計算該固定污染源之排放量。第10條並定有排放量計算依據之優先順序。",
 "When must an emission-factor reporter switch to mass balance, and from when?",
 ["When the declared quarterly emissions differ from the audit result by two times or more and 7.5 tonnes or more; from the quarter after the notice is received",
  "When the declared quarterly emissions differ from the audit result by three times or more and 10 tonnes or more; from the year after the notice is received",
  "When the declared quarterly emissions differ from the audit result by 1.5 times or more and 5 tonnes or more; from the same quarter, using emission factors",
  "When the declared quarterly emissions differ from the audit result by five times or more and 20 tonnes or more; from the month after, using continuous monitoring"],
 "Article 13."),

(F,"第14條",2,"空污費-結算補繳",
 "公私場所申報空污費經審查結算不足者應如何處理？溢繳未達一定金額者如何處理？申報及紀錄資料應保存幾年？",
 ["結算不足者加徵差額並限期九十日內繳納；溢繳未達二千元者充作其後應繳費額之一部分；相關資料應保存六年備查",
  "結算不足者加徵差額並限期三十日內繳納；溢繳未達一千元者充作其後應繳費額之一部分；相關資料應保存三年備查",
  "結算不足者加徵差額並限期六十日內繳納；溢繳未達五千元者充作其後應繳費額之一部分；相關資料應保存五年備查",
  "結算不足者加徵差額並限期一百八十日內繳納；溢繳金額一律無息退還申請人；相關資料應保存十年備查"],"a",
 "第14條：各級主管機關應審查核算並通知結果，結算不足者加徵差額並限期於九十日內繳納，屆期未繳清者依空污法第74條辦理；溢繳者充作其後應繳費額之一部分或依申請退還，溢繳未達二千元者應充作其後費額（營建工程除外）。第26條：申報資料、繳費收據、相關紀錄及證明資料應保存六年備查。",
 "How is a shortfall handled, how is a small overpayment treated, and how long are records kept?",
 ["Shortfall surcharged and payable within 90 days; overpayments under NT$2,000 credited against future fees; records kept six years",
  "Shortfall surcharged and payable within 30 days; overpayments under NT$1,000 credited against future fees; records kept three years",
  "Shortfall surcharged and payable within 60 days; overpayments under NT$5,000 credited against future fees; records kept five years",
  "Shortfall surcharged and payable within 180 days; all overpayments refunded without interest; records kept ten years"],
 "Articles 14 and 26."),

(F,"第21條",3,"空污費-免繳免申報",
 "公私場所固定污染源當季何種情形得免申報該項空污費？每件營建工程核算應繳費額多少以下得免繳納？",
 ["當季總硫氧化物、總氮氧化物、總揮發性有機物或總粒狀污染物排放量十公斤以下者得免申報；營建工程費額一百元以下者免繳",
  "當季總硫氧化物、總氮氧化物、總揮發性有機物或總粒狀污染物排放量一公斤以下者得免申報；營建工程費額五十元以下者免繳",
  "當季總硫氧化物、總氮氧化物、總揮發性有機物或總粒狀污染物排放量一百公斤以下者得免申報；營建工程費額一千元以下者免繳",
  "當季總硫氧化物、總氮氧化物、總揮發性有機物或總粒狀污染物排放量五十公斤以下者得免申報；營建工程費額五百元以下者免繳"],"a",
 "第21條：符合免繳納各款規定者仍應申報，但公私場所固定污染源當季之總硫氧化物、總氮氧化物、總揮發性有機物或總粒狀污染物排放量十公斤以下者，得免申報該項空污費；每件營建工程核算應繳費額一百元以下者得免繳納。經查核個別污染物總排放量超過十公斤者，應令其自次一季起依第3條第1項申報。",
 "What quarterly emission level exempts a source from reporting, and what construction fee amount is exempt from payment?",
 ["Quarterly total SOx, NOx, VOC or particulates of 10 kg or less exempts reporting; construction fees of NT$100 or less are exempt from payment",
  "Quarterly total SOx, NOx, VOC or particulates of 1 kg or less exempts reporting; construction fees of NT$50 or less are exempt from payment",
  "Quarterly total SOx, NOx, VOC or particulates of 100 kg or less exempts reporting; construction fees of NT$1,000 or less are exempt from payment",
  "Quarterly total SOx, NOx, VOC or particulates of 50 kg or less exempts reporting; construction fees of NT$500 or less are exempt from payment"],
 "Article 21."),

# ---------- ENV-34 揮發性有機物空氣污染管制及排放標準（112/12/4） ----------
(V,"第2條",2,"VOC-定義",
 "揮發性有機物、揮發性有機液體及洩漏定義值之定義為何？",
 ["一大氣壓下初始沸點攝氏二百五十度以下之有機化合物；VOC 占重量百分比十以上之液體；淨檢測值一千 ppm 以上，氣體釋壓裝置為一百 ppm",
  "一大氣壓下初始沸點攝氏一百度以下之有機化合物；VOC 占重量百分比五以上之液體；淨檢測值五百 ppm 以上，氣體釋壓裝置為五十 ppm",
  "一大氣壓下初始沸點攝氏三百度以下之有機化合物；VOC 占重量百分比二十以上之液體；淨檢測值二千 ppm 以上，氣體釋壓裝置為二百 ppm",
  "一大氣壓下初始沸點攝氏一百五十度以下之有機化合物；VOC 占重量百分比十五以上之液體；淨檢測值一萬 ppm 以上，氣體釋壓裝置為一千 ppm"],"a",
 "第2條：揮發性有機物指一大氣壓下測量所得初始沸點在攝氏二百五十度以下有機化合物之空氣污染物總稱，但不包括甲烷、一氧化碳、二氧化碳等；揮發性有機液體指 VOC 成分占其重量百分比十以上之液體；洩漏定義值指設備元件之淨檢測值一千 ppm 以上，但氣體釋壓裝置之淨檢測值為一百 ppm。淨檢測值指初檢測值減背景濃度值。",
 "How are VOC, volatile organic liquid, and the leak definition value defined?",
 ["Organic compounds with initial boiling point at or below 250 degrees C at one atmosphere; liquids with 10 percent VOC by weight or more; net reading of 1,000 ppm, or 100 ppm for gas pressure relief devices",
  "Organic compounds with initial boiling point at or below 100 degrees C at one atmosphere; liquids with 5 percent VOC by weight or more; net reading of 500 ppm, or 50 ppm for gas pressure relief devices",
  "Organic compounds with initial boiling point at or below 300 degrees C at one atmosphere; liquids with 20 percent VOC by weight or more; net reading of 2,000 ppm, or 200 ppm for gas pressure relief devices",
  "Organic compounds with initial boiling point at or below 150 degrees C at one atmosphere; liquids with 15 percent VOC by weight or more; net reading of 10,000 ppm, or 1,000 ppm for gas pressure relief devices"],
 "Article 2, subparagraphs 1, 3 and 50."),

(V,"第5條",2,"VOC-廢氣燃燒塔",
 "廢氣燃燒塔之母火及蒸氣輔助燃燒型式之蒸氣量規定為何？",
 ["母火不可熄滅且應使用獨立穩定之燃料系統；蒸氣量與廢氣量之重量比應介於百分之十五至百分之五十",
  "母火得於停爐期間熄滅並共用製程燃料系統；蒸氣量與廢氣量之重量比應介於百分之五至百分之二十",
  "母火不可熄滅且應使用獨立穩定之燃料系統；蒸氣量與廢氣量之重量比應介於百分之三十至百分之七十",
  "母火應每日熄滅一次進行檢查及保養作業；蒸氣量與廢氣量之重量比應介於百分之十至百分之二十五"],"a",
 "第5條：廢氣燃燒塔之母火不可熄滅，且應使用獨立穩定之燃料系統；使用蒸氣輔助燃燒型式者，其蒸氣量與廢氣量之重量比應介於百分之十五至百分之五十，但因製程特性報經主管機關核可者不在此限。第4條：正常操作下排放之廢氣不得使用廢氣燃燒塔處理，但遇緊急狀況、開車、停車、歲修或經核可之必要操作不在此限。",
 "What are the pilot flame and steam-assist requirements for flares?",
 ["The pilot flame must not be extinguished and must use an independent stable fuel system; steam to waste gas weight ratio between 15 and 50 percent",
  "The pilot flame may be extinguished during shutdown and share the process fuel system; steam to waste gas weight ratio between 5 and 20 percent",
  "The pilot flame must not be extinguished and must use an independent stable fuel system; steam to waste gas weight ratio between 30 and 70 percent",
  "The pilot flame must be extinguished daily for inspection and maintenance; steam to waste gas weight ratio between 10 and 25 percent"],
 "Articles 4 and 5."),

(V,"第9條",3,"VOC-燃燒塔事件",
 "發生廢氣燃燒塔使用事件時，公私場所之通報、公開及提報期限為何？未裝設廢氣成分及濃度監測設施者應於多久內完成採樣？",
 ["一小時內通報地方主管機關；三日內公開說明原因；十五日內提報使用事件報告書；未裝監測設施者三十分鐘內完成採樣",
  "二十四小時內通報地方主管機關；七日內公開說明原因；三十日內提報使用事件報告書；未裝監測設施者二小時內完成採樣",
  "三十分鐘內通報地方主管機關；一日內公開說明原因；七日內提報使用事件報告書；未裝監測設施者十五分鐘內完成採樣",
  "六小時內通報地方主管機關；五日內公開說明原因；二十日內提報使用事件報告書；未裝監測設施者一小時內完成採樣"],"a",
 "第9條：發生廢氣燃燒塔使用事件時，應於一小時內通報地方主管機關，並於三日內上傳網站或以其他方式公開說明事件原因及防止再發生方法，並於十五日內提報廢氣燃燒塔使用事件報告書；未裝設廢氣成分及濃度監測設施者，應於三十分鐘內完成廢氣採樣並分析 VOC 成分、濃度及總淨熱值。第11條：預定使用者應於預定使用前至少二日通報。",
 "What are the notification, disclosure and reporting deadlines for a flare use event?",
 ["Notify the local authority within one hour; disclose the cause within three days; submit the event report within 15 days; sample within 30 minutes if no monitor is installed",
  "Notify the local authority within 24 hours; disclose the cause within seven days; submit the event report within 30 days; sample within two hours if no monitor is installed",
  "Notify the local authority within 30 minutes; disclose the cause within one day; submit the event report within seven days; sample within 15 minutes if no monitor is installed",
  "Notify the local authority within six hours; disclose the cause within five days; submit the event report within 20 days; sample within one hour if no monitor is installed"],
 "Article 9."),

(V,"第10條",3,"VOC-改善計畫",
 "公私場所使用廢氣燃燒塔達何種情形，應於發生日起三個月內提交改善計畫書？",
 ["使用事件日數每年累計達三十日；石油煉製或輕油裂解製程之廢氣燃燒塔 VOC 年排放量累積達五公噸以上，其餘石化製程達二點五公噸以上",
  "使用事件日數每年累計達十日；石油煉製或輕油裂解製程之廢氣燃燒塔 VOC 年排放量累積達二公噸以上，其餘石化製程達一公噸以上",
  "使用事件日數每年累計達六十日；石油煉製或輕油裂解製程之廢氣燃燒塔 VOC 年排放量累積達十公噸以上，其餘石化製程達五公噸以上",
  "使用事件日數每年累計達九十日；石油煉製或輕油裂解製程之廢氣燃燒塔 VOC 年排放量累積達二十公噸以上，其餘石化製程達十公噸以上"],"a",
 "第10條：使用廢氣燃燒塔達下列情形者應於發生日起三個月內提交改善計畫書：使用事件日數每年累計達三十日；具石油煉製或輕油裂解製程者所有廢氣燃燒塔 VOC 年排放量累積達五公噸以上，其餘公私場所石化製程達二點五公噸以上；石油煉製製程前一年度處理每百萬桶原油之廢氣燃燒塔二氧化硫排放累積達零點二五公噸以上。核定後三十日內應申請變更使用計畫書。",
 "Which conditions require submitting a flare improvement plan within three months?",
 ["Flare use event days reaching 30 per year; annual flare VOC emissions of 5 tonnes or more for refining or naphtha cracking, and 2.5 tonnes or more for other petrochemical processes",
  "Flare use event days reaching 10 per year; annual flare VOC emissions of 2 tonnes or more for refining or naphtha cracking, and 1 tonne or more for other petrochemical processes",
  "Flare use event days reaching 60 per year; annual flare VOC emissions of 10 tonnes or more for refining or naphtha cracking, and 5 tonnes or more for other petrochemical processes",
  "Flare use event days reaching 90 per year; annual flare VOC emissions of 20 tonnes or more for refining or naphtha cracking, and 10 tonnes or more for other petrochemical processes"],
 "Article 10, paragraph 1."),

(V,"第15條",3,"VOC-儲槽納管",
 "揮發性有機液體儲槽應依本標準第四章管制之納管條件為何？",
 ["實際蒸氣壓一百七十mmHg以上且單槽容積十五立方公尺以上；實際蒸氣壓二十一mmHg以上且單槽容積一百立方公尺以上；相同物料總儲槽容積五百立方公尺以上",
  "實際蒸氣壓七十mmHg以上且單槽容積五立方公尺以上；實際蒸氣壓十一mmHg以上且單槽容積五十立方公尺以上；相同物料總儲槽容積二百立方公尺以上",
  "實際蒸氣壓五百七十mmHg以上且單槽容積五十立方公尺以上；實際蒸氣壓一百mmHg以上且單槽容積三百立方公尺以上；相同物料總儲槽容積一千立方公尺以上",
  "實際蒸氣壓二百七十mmHg以上且單槽容積二十立方公尺以上；實際蒸氣壓三十一mmHg以上且單槽容積二百立方公尺以上；相同物料總儲槽容積八百立方公尺以上"],"a",
 "第15條：本章適用對象為儲存物料實際蒸氣壓一百七十mmHg以上且單一儲槽容積十五立方公尺以上者；實際蒸氣壓二十一mmHg以上或含空污費收費費率公告個別污染物種類且單一儲槽容積一百立方公尺以上者；同一公私場所相同儲存物料實際蒸氣壓二十一mmHg以上且總儲槽容積五百立方公尺以上者。儲存食用酒精、變性燃料乙醇、天然氣之儲槽或加油站儲油槽不在此限。",
 "Which VOL storage tanks are covered by Chapter 4?",
 ["True vapor pressure 170 mmHg or more with single tank 15 m3 or more; 21 mmHg or more with single tank 100 m3 or more; same material with total tank volume 500 m3 or more",
  "True vapor pressure 70 mmHg or more with single tank 5 m3 or more; 11 mmHg or more with single tank 50 m3 or more; same material with total tank volume 200 m3 or more",
  "True vapor pressure 570 mmHg or more with single tank 50 m3 or more; 100 mmHg or more with single tank 300 m3 or more; same material with total tank volume 1,000 m3 or more",
  "True vapor pressure 270 mmHg or more with single tank 20 m3 or more; 31 mmHg or more with single tank 200 m3 or more; same material with total tank volume 800 m3 or more"],
 "Article 15."),

(V,"第16條",3,"VOC-儲槽管制",
 "儲存物料實際蒸氣壓五百七十mmHg以上之儲槽，非採壓力槽者應如何處理？小於五百七十mmHg而採固定頂槽者又應如何？",
 ["應裝設密閉集氣系統連通至爐膛火焰區，或使削減率達百分之九十五或排放濃度一百ppm以下；固定頂槽者削減率百分之九十五或濃度一百五十ppm以下",
  "應裝設密閉集氣系統連通至爐膛火焰區，或使削減率達百分之八十五或排放濃度三百ppm以下；固定頂槽者削減率百分之八十或濃度五百ppm以下",
  "應裝設密閉集氣系統連通至爐膛火焰區，或使削減率達百分之九十或排放濃度二百ppm以下；固定頂槽者削減率百分之九十或濃度二百ppm以下",
  "應裝設密閉集氣系統連通至爐膛火焰區，或使削減率達百分之七十或排放濃度五十ppm以下；固定頂槽者削減率百分之九十五或濃度五十ppm以下"],"a",
 "第16條：實際蒸氣壓五百七十mmHg以上者應採壓力槽，或裝設密閉集氣系統連通至鍋爐或加熱爐爐膛火焰區，或其他使削減率達百分之九十五或排放濃度一百ppm以下之防制設備；小於五百七十mmHg者應採浮頂槽，採固定頂槽者應連通至爐膛火焰區或使削減率達百分之九十五或濃度一百五十ppm以下。採非破壞性物料回收者削減率百分之八十五或濃度三百ppm以下。",
 "How must tanks at or above 570 mmHg be controlled if not pressure tanks, and fixed-roof tanks below 570 mmHg?",
 ["Closed vent system to the furnace flame zone, or 95 percent reduction or 100 ppm or less; fixed-roof tanks need 95 percent reduction or 150 ppm or less",
  "Closed vent system to the furnace flame zone, or 85 percent reduction or 300 ppm or less; fixed-roof tanks need 80 percent reduction or 500 ppm or less",
  "Closed vent system to the furnace flame zone, or 90 percent reduction or 200 ppm or less; fixed-roof tanks need 90 percent reduction or 200 ppm or less",
  "Closed vent system to the furnace flame zone, or 70 percent reduction or 50 ppm or less; fixed-roof tanks need 95 percent reduction or 50 ppm or less"],
 "Article 16, paragraphs 1 and 2."),

(V,"第30條",3,"VOC-設備元件洩漏",
 "設備元件之洩漏管制規定為何？輕質液及氣體設備元件之定期檢測頻率為何？",
 ["軸封處製程流體滴漏每分鐘不得超過三滴；自一百十四年一月一日起淨檢測值不得大於一千ppm；輕質液及氣體設備元件每三個月檢測一次",
  "軸封處製程流體滴漏每分鐘不得超過十滴；自一百十四年一月一日起淨檢測值不得大於一萬ppm；輕質液及氣體設備元件每六個月檢測一次",
  "軸封處製程流體滴漏每分鐘不得超過五滴；自一百十四年一月一日起淨檢測值不得大於五千ppm；輕質液及氣體設備元件每一個月檢測一次",
  "軸封處製程流體滴漏每分鐘不得超過一滴；自一百十四年一月一日起淨檢測值不得大於五百ppm；輕質液及氣體設備元件每一年檢測一次"],"a",
 "第30條：設備元件軸封處之製程流體滴漏每分鐘不得超過三滴；設備元件之淨檢測值不得大於一萬ppm，並自一百十四年一月一日起不得大於一千ppm。第31條：輕質液泵浦應每週目視檢查軸封處，重質液設備元件每週目視或簡易檢漏，發現洩漏跡象應於二十四小時內檢測；輕質液及氣體設備元件應每三個月檢測一次，符合低洩漏比例並經核可者得放寬頻率。",
 "What are the component leak limits and the routine test frequency for light liquid and gas components?",
 ["Process fluid dripping at the seal not exceeding three drops per minute; net reading not above 1,000 ppm from 1 January 2025; light liquid and gas components tested every three months",
  "Process fluid dripping at the seal not exceeding ten drops per minute; net reading not above 10,000 ppm from 1 January 2025; light liquid and gas components tested every six months",
  "Process fluid dripping at the seal not exceeding five drops per minute; net reading not above 5,000 ppm from 1 January 2025; light liquid and gas components tested every month",
  "Process fluid dripping at the seal not exceeding one drop per minute; net reading not above 500 ppm from 1 January 2025; light liquid and gas components tested every year"],
 "Articles 30 and 31."),

(V,"第32條",3,"VOC-洩漏修護",
 "設備元件經發現為洩漏源者，其修護期限規定為何？",
 ["發現時起二十四小時內以鎖緊或密封方式修護，經核准得再延長二十四小時；無法者於發現日起七日內更換零件或克漏，經核准得再延長八日",
  "發現時起四十八小時內以鎖緊或密封方式修護，經核准得再延長四十八小時；無法者於發現日起十五日內更換零件或克漏，經核准得再延長十五日",
  "發現時起十二小時內以鎖緊或密封方式修護，經核准得再延長十二小時；無法者於發現日起三日內更換零件或克漏，經核准得再延長三日",
  "發現時起七日內以鎖緊或密封方式修護，經核准得再延長七日；無法者於發現日起三十日內更換零件或克漏，經核准得再延長三十日"],"a",
 "第32條：設備元件經發現為洩漏源者，應於發現時起二十四小時內以鎖緊或密封等方式修護，因情形特殊報經地方主管機關核准後始得再延長二十四小時；無法以鎖緊或密封修護者，應於發現日起七日內以更換零件或克漏等方式修護，經核准得再延長修護時間八日。完成修護指修護後洩漏源淨檢測值低於洩漏定義值。第33條：紀錄應保存五年備查。",
 "What are the repair deadlines once a component is confirmed as a leak source?",
 ["Tighten or seal within 24 hours of discovery, extendable by 24 hours with approval; otherwise replace parts or plug within 7 days of discovery, extendable by 8 days with approval",
  "Tighten or seal within 48 hours of discovery, extendable by 48 hours with approval; otherwise replace parts or plug within 15 days of discovery, extendable by 15 days with approval",
  "Tighten or seal within 12 hours of discovery, extendable by 12 hours with approval; otherwise replace parts or plug within 3 days of discovery, extendable by 3 days with approval",
  "Tighten or seal within 7 days of discovery, extendable by 7 days with approval; otherwise replace parts or plug within 30 days of discovery, extendable by 30 days with approval"],
 "Article 32."),

# ---------- ENV-35 鍋爐空氣污染物排放標準（114/1/2） ----------
(B,"第2條",2,"鍋爐-新設既存",
 "本標準所稱新設鍋爐及既存鍋爐之認定時點為何？",
 ["新設鍋爐指一百十四年一月四日後設立者；既存鍋爐指一百十四年一月三日前已完成建造、建造中、完成招標或已訂立工程施作契約者",
  "新設鍋爐指一百十三年一月四日後設立者；既存鍋爐指一百十三年一月三日前已完成建造、建造中、完成招標或已訂立工程施作契約者",
  "新設鍋爐指一百十五年一月一日後設立者；既存鍋爐指一百十四年十二月三十一日前已完成建造、建造中或已訂立工程施作契約者",
  "新設鍋爐指一百零九年四月一日後設立者；既存鍋爐指一百零九年三月三十一日前已完成建造、建造中或已訂立工程施作契約者"],"a",
 "第2條：新設鍋爐指中華民國一百十四年一月四日後設立之鍋爐；既存鍋爐指一百十四年一月三日前已完成建造、建造中、完成工程招標程序或未經招標程序已訂立工程施作契約之鍋爐，其中屬指定公告之固定污染源者以已取得操作許可證者為限；既存鍋爐符合固定污染源設置操作及燃料使用許可證管理辦法第4條變更條件者，以新設鍋爐論。",
 "How are new and existing boilers defined?",
 ["New boilers are those established after 4 January 2025; existing boilers are those built, under construction, tendered or contracted before 3 January 2025",
  "New boilers are those established after 4 January 2024; existing boilers are those built, under construction, tendered or contracted before 3 January 2024",
  "New boilers are those established after 1 January 2026; existing boilers are those built, under construction or contracted before 31 December 2025",
  "New boilers are those established after 1 April 2020; existing boilers are those built, under construction or contracted before 31 March 2020"],
 "Article 2, subparagraphs 2 and 3."),

(B,"第2條",1,"鍋爐-用詞定義",
 "本標準所稱備用鍋爐及雙燃料系統鍋爐之定義為何？",
 ["備用鍋爐指原鍋爐因故中斷運作時，為維持熱能或蒸汽供給系統正常運作而啟動之鍋爐；雙燃料系統鍋爐指可互相切換液體或氣體物質作為燃料之鍋爐",
  "備用鍋爐指僅於歲修期間使用且每年運轉不超過三十日之鍋爐；雙燃料系統鍋爐指可同時燃燒固體與液體物質作為燃料之鍋爐",
  "備用鍋爐指供應蒸汽量低於主鍋爐一半之輔助性小型鍋爐；雙燃料系統鍋爐指以生質燃料混燒煤炭作為燃料之鍋爐",
  "備用鍋爐指設置完成但尚未取得操作許可證之待用鍋爐；雙燃料系統鍋爐指得切換氣體與固體物質作為燃料之鍋爐"],"a",
 "第2條：備用鍋爐指原鍋爐因故中斷運作時，為維持熱能或蒸汽供給系統正常運作而啟動之鍋爐；雙燃料系統鍋爐指可互相切換液體或氣體物質作為燃料之鍋爐。鍋爐則指以氣體、液體或固體物質作為燃料，加熱於水、熱媒，致產生熱水、超過大氣壓之壓力蒸汽或熱能之設備。",
 "How are standby boilers and dual-fuel boilers defined?",
 ["A standby boiler is started to maintain normal heat or steam supply when the original boiler is interrupted; a dual-fuel boiler can switch between liquid and gaseous fuels",
  "A standby boiler is used only during the annual overhaul and runs no more than 30 days a year; a dual-fuel boiler burns solid and liquid fuels at the same time only",
  "A standby boiler is an auxiliary small boiler supplying less than half the main boiler steam; a dual-fuel boiler co-fires biomass fuel with coal",
  "A standby boiler is one installed but not yet holding an operating permit; a dual-fuel boiler can switch between gaseous and solid fuels"],
 "Article 2, subparagraphs 4 and 5."),

(B,"第5條",3,"鍋爐-備用切換報備",
 "因蒸汽供應或氣體燃料供應中斷等不可歸責因素啟動備用鍋爐或切換為液體燃料者，其報備及核定期限為何？",
 ["應於啟動或切換後三小時內向地方主管機關報備；無法於二十四小時內排除因素需持續運作者，應於二十四小時內檢具證明文件報經核定",
  "應於啟動或切換後六小時內向地方主管機關報備；無法於四十八小時內排除因素需持續運作者，應於四十八小時內檢具證明文件報經核定",
  "應於啟動或切換後一小時內向地方主管機關報備；無法於十二小時內排除因素需持續運作者，應於十二小時內檢具證明文件報經核定",
  "應於啟動或切換後二十四小時內向地方主管機關報備；無法於七日內排除因素需持續運作者，應於七日內檢具證明文件報經核定"],"a",
 "第5條：因蒸汽供應來源中斷、原鍋爐氣體燃料供應中斷等不可歸責之因素啟動備用鍋爐或切換雙燃料系統鍋爐為液體燃料者，應於啟動或切換後三小時內向直轄市、縣（市）主管機關報備；無法於二十四小時內排除因素需持續運作者，應於二十四小時內檢具證明文件報經核定，提報期限逢例假日得順延至次一工作日。此時排放應符合固定污染源空氣污染物排放標準。",
 "What are the reporting deadlines when a standby boiler is started for reasons beyond the operator's control?",
 ["Report to the local authority within three hours of start-up or switching; if the cause cannot be cleared within 24 hours, file supporting documents for approval within 24 hours",
  "Report to the local authority within six hours of start-up or switching; if the cause cannot be cleared within 48 hours, file supporting documents for approval within 48 hours",
  "Report to the local authority within one hour of start-up or switching; if the cause cannot be cleared within 12 hours, file supporting documents for approval within 12 hours",
  "Report to the local authority within 24 hours of start-up or switching; if the cause cannot be cleared within seven days, file supporting documents for approval within seven days"],
 "Article 5, subparagraph 1."),

(B,"第6條",3,"鍋爐-氧氣基準",
 "本標準污染物濃度計算之含氧參考基準為何？既存鍋爐改善計畫展延核定之改善期限不得逾何時？",
 ["燃燒過程排氣中以百分之六氧氣為參考基準；既存鍋爐改善計畫展延核定之改善期限不得逾一百十六年七月一日",
  "燃燒過程排氣中以百分之十二氧氣為參考基準；既存鍋爐改善計畫展延核定之改善期限不得逾一百十八年十二月三十一日",
  "燃燒過程排氣中以百分之十五氧氣為參考基準；既存鍋爐改善計畫展延核定之改善期限不得逾一百十四年一月三日",
  "燃燒過程排氣中以百分之三氧氣為參考基準；既存鍋爐改善計畫展延核定之改善期限不得逾一百二十年一月一日"],"a",
 "第6條：各種污染物濃度均以凱氏溫度二百七十三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，燃燒過程排氣中之氧氣百分率以百分之六氧氣為參考基準；既存鍋爐使用固態生質燃料等者，附表三之氧氣參考基準自一百十四年一月四日至一百十八年十二月三十一日為實測值，自一百十九年一月一日起為百分之六。第7條：展延核定之改善期限不得逾一百十六年七月一日。",
 "What is the reference oxygen basis, and the latest date for an extended improvement deadline?",
 ["Six percent oxygen in combustion exhaust as the reference basis; the extended improvement deadline may not exceed 1 July 2027",
  "Twelve percent oxygen in combustion exhaust as the reference basis; the extended improvement deadline may not exceed 31 December 2029",
  "Fifteen percent oxygen in combustion exhaust as the reference basis; the extended improvement deadline may not exceed 3 January 2025",
  "Three percent oxygen in combustion exhaust as the reference basis; the extended improvement deadline may not exceed 1 January 2031"],
 "Articles 6 and 7."),

# ---------- ENV-36 汽車停車怠速管理辦法（108/1/25） ----------
(I,"第3條",1,"怠速-關閉引擎",
 "汽車於哪些場所停車怠速等候逾多久應關閉引擎？",
 ["於公私立停車場、道路（不含高速公路、快速公路及快速道路）等場所，停車怠速等候逾三分鐘者應關閉引擎",
  "於公私立停車場、道路（包含高速公路及快速公路）等場所，停車怠速等候逾一分鐘者應關閉引擎",
  "於公私立停車場、道路（不含高速公路、快速公路及快速道路）等場所，停車怠速等候逾十分鐘者應關閉引擎",
  "於所有道路（包括高速公路及快速道路）及加油站等場所，停車怠速等候逾五分鐘者應關閉引擎"],"a",
 "第3條：汽車於公私立停車場、道路（不包含高速公路、快速公路及快速道路）及其他供汽車停放、接駁、轉運之場所，停車怠速等候逾三分鐘者，應關閉引擎。本辦法依空氣污染防制法第38條第2項訂定。",
 "Where and after how long must an idling vehicle switch off its engine?",
 ["In public or private parking lots and roads (excluding freeways, expressways and rapid roads), the engine must be switched off after idling over three minutes",
  "In public or private parking lots and roads (including freeways and expressways), the engine must be switched off after idling over one minute",
  "In public or private parking lots and roads (excluding freeways, expressways and rapid roads), the engine must be switched off after idling over ten minutes",
  "On all roads (including freeways and rapid roads) and at gas stations, the engine must be switched off after idling over five minutes"],
 "Article 3: three minutes."),

(I,"第2條",1,"怠速-汽車定義",
 "本辦法所稱汽車之定義為何？",
 ["指在道路上不依軌道或電力架設，而以原動機行駛之車輛，但不包含電動車輛",
  "指在道路上不依軌道或電力架設，而以原動機行駛之車輛，並包含電動車輛",
  "指在道路上依軌道或電力架設行駛之車輛，但不包含機車及電動車輛",
  "指在道路上以原動機行駛且總重量三點五公噸以上之車輛，不包含小客車"],"a",
 "第2條：本辦法所稱汽車，指在道路上不依軌道或電力架設，而以原動機行駛之車輛，但不包含電動車輛。故電動車輛不適用第3條停車怠速逾三分鐘應關閉引擎之規定。",
 "How does this regulation define an automobile?",
 ["A vehicle driven on roads by a prime mover, not running on rails or overhead electric lines, excluding electric vehicles",
  "A vehicle driven on roads by a prime mover, not running on rails or overhead electric lines, including electric vehicles",
  "A vehicle running on roads by rails or overhead electric lines, excluding motorcycles and electric vehicles",
  "A vehicle driven on roads by a prime mover weighing 3.5 tonnes or more in total, excluding passenger cars"],
 "Article 2 excludes electric vehicles."),

(I,"第4條",2,"怠速-例外情形",
 "下列有關停車怠速免關閉引擎例外情形之敘述，何者正確？",
 ["幼童專用車、遊覽車及大客車得於乘客上車前十五分鐘啟動引擎；當日預報最高溫度超過攝氏三十度時不適用",
  "幼童專用車、遊覽車及大客車得於乘客上車前三十分鐘啟動引擎；當日預報最高溫度超過攝氏三十五度時不適用",
  "幼童專用車、遊覽車及大客車得於乘客上車前五分鐘啟動引擎；當日預報最高溫度超過攝氏二十五度時不適用",
  "幼童專用車、遊覽車及大客車得於乘客上車前十分鐘啟動引擎；當日預報最高溫度超過攝氏二十八度時不適用"],"a",
 "第4條：基於乘客健康及安全考量，幼童專用車、遊覽車及大客車得於乘客上車前十五分鐘啟動引擎，乘客下車停妥後須關閉引擎；中央氣象局於前一日下午五時以後或當日天氣預報中任一次，停車所在直轄市、縣（市）最高溫度超過攝氏三十度時，不適用第3條。其他例外包括作業中特種車、裝卸貨中冷凍冷藏車、排班候客且駕駛未離座之計程車、停車時正值下雨等。",
 "Which statement about idling exemptions is correct?",
 ["Kindergarten buses, tour buses and large passenger buses may start the engine 15 minutes before boarding; the rule does not apply when the forecast high exceeds 30 degrees C",
  "Kindergarten buses, tour buses and large passenger buses may start the engine 30 minutes before boarding; the rule does not apply when the forecast high exceeds 35 degrees C",
  "Kindergarten buses, tour buses and large passenger buses may start the engine 5 minutes before boarding; the rule does not apply when the forecast high exceeds 25 degrees C",
  "Kindergarten buses, tour buses and large passenger buses may start the engine 10 minutes before boarding; the rule does not apply when the forecast high exceeds 28 degrees C"],
 "Article 4, subparagraphs 3 and 6."),

# ---------- ENV-37 空氣污染行為管制執行準則（108/7/25） ----------
(C,"第3條",2,"行為管制-判定位置",
 "主管機關執行空氣污染行為管制之判定位置應如何？",
 ["應於廠房外、周界或周界外，並能明確判定污染物係由受稽查污染源所逸散",
  "應於廠房內之操作區域，並以連續自動監測設施之數據判定污染物來源",
  "應於排放管道出口處，並以檢驗測定機構之檢測報告判定污染物來源",
  "應於陳情人住所之室內，並由陳情人自行拍照佐證污染物之來源"],"a",
 "第2條：本準則適用於主管機關執行未經排放管道排放空氣污染物之空氣污染行為管制。第3條：判定位置應於廠房外、周界或周界外，並能明確判定污染物係由受稽查污染源所逸散。第12條：執行行為管制於必要時，得會同陳情人或污染源附近之居民為之。",
 "Where must the authority make its determination when enforcing air pollution behavior controls?",
 ["Outside the plant building, at or beyond the site boundary, with clear attribution of the pollutant to the inspected source",
  "Inside the plant operating area, using continuous automatic monitoring data to attribute the pollutant source clearly",
  "At the stack outlet, using a testing organization's report to attribute the pollutant source",
  "Inside the complainant's residence, with the complainant photographing the pollutant source"],
 "Articles 2 and 3."),

(C,"第4條",3,"行為管制-判定方式",
 "主管機關執行空氣污染行為管制時，對粒狀污染物、異味污染物及有毒氣體之判定方式為何？",
 ["粒狀污染物以目視確認明顯可見排放並敘明排除水蒸氣干擾；異味應繪製記錄發生源位置並描述氣味；有毒氣體應確認原料或產出物含毒性物質",
  "粒狀污染物以連續自動監測數據確認排放；異味應以檢測儀器量測周界濃度值；有毒氣體應以目視煙羽顏色判定是否含毒性物質",
  "粒狀污染物以周界檢測報告確認排放情形；異味應由三人以上嗅覺判定小組評定；有毒氣體應以排放管道採樣分析結果確認",
  "粒狀污染物以行車紀錄器影像確認排放；異味應由陳情人簽名確認氣味種類；有毒氣體應以原料進貨憑證推估毒性物質"],"a",
 "第4條：判定粒狀污染物逸散行為時，應以目視確認明顯可見粒狀污染物排放，逸散廢氣含水蒸氣者應於稽查紀錄敘明排除水蒸氣干擾之情形；判定異味污染物污染行為時，應繪製或記錄判定異味發生源之相關位置並描述現場聞到之氣味；判定有毒氣體逸散行為時，應確認污染源使用之原料、燃料、物料或其產出物含有毒性物質。",
 "How are particulates, odors and toxic gases determined during behavior control enforcement?",
 ["Particulates by visible observation with steam noted; odors by mapping the source and describing the smell; toxic gases by confirming toxic content in materials or products",
  "Particulates by continuous automatic monitoring data; odors by instrument measurement of boundary concentrations; toxic gases by judging the plume color visually",
  "Particulates by boundary testing reports; odors by a panel of three or more olfactory judges; toxic gases by stack sampling and analysis results",
  "Particulates by dashcam footage; odors by the complainant signing to confirm the smell; toxic gases by estimating from raw material purchase receipts"],
 "Article 4."),

(C,"第5條",2,"行為管制-稽查紀錄",
 "主管機關執行空氣污染行為管制應填載之稽查工作紀錄表，其內容應包括下列何者？",
 ["公私場所名稱與負責人或行為人姓名、污染源名稱及位置、稽查時間、稽查判定位置與污染發生源位置之相關性",
  "公私場所之工廠登記證號與資本額、員工人數及年度營業額、污染源購置金額與折舊年限、預定裁處金額",
  "陳情人之姓名住址與聯絡電話、歷年陳情次數統計資料、預定裁處之金額及法條依據、複查預定日期",
  "污染源負責人之學經歷與訓練紀錄、防制設備之廠牌型號與保固期限、公私場所稅籍與財產資料"],"a",
 "第5條：稽查工作紀錄表內容應包括公私場所名稱、負責人或行為人之姓名；污染源名稱及位置；稽查時間；稽查判定位置及與污染發生源位置之相關性；發生污染行為之具體事實及判定方式；污染源及污染防制設施設置及操作情形；判定污染行為之相關佐證資料；其他必要之稽查事項。",
 "What must the inspection record form contain?",
 ["Name of the premises and the responsible person or actor, source name and location, inspection time, and the relation between the determination point and the source location",
  "Factory registration number and capital, headcount and annual turnover, source purchase price and depreciation period, and the planned penalty amount and legal basis",
  "Complainant's name, address and phone, historical complaint statistics, planned penalty amount and legal basis, and the planned re-inspection date",
  "The responsible person's education and training records, control equipment brand, model and warranty period, and the premises' tax and property data"],
 "Article 5."),

(C,"第7條",3,"行為管制-塵土飛揚",
 "主管機關執行空污法第32條第1項第2款（引起塵土飛揚或污染空氣）行為管制時，應確認符合下列何種情形之一？",
 ["施工區、施工道路或工地出入口未有效灑水或清掃；周界未設防塵罩網或圍籬等設施；裸露地面未灑水、栽植或噴灑化學藥劑",
  "施工區未設置臨時廁所及工人休息區；周界未設置夜間照明及監視器材；裸露地面未劃設臨時停車格及動線標示",
  "施工人員未配戴防塵口罩及識別證件；工地未張貼施工告示牌及工期表；裸露地面未設置排水溝渠及沉砂設施",
  "工地未設置專責環保人員及聯絡電話；周界未設置噪音計及風速計；裸露地面未依規定進行土壤採樣分析"],"a",
 "第7條：除確認污染源有引起塵土飛揚或污染空氣行為外，並應確認符合下列情形之一：施工區、施工道路、運輸道路或工地出入口未有效灑水或清掃；周界未設置防塵罩網、靜電幕、防塵屏、圍籬或防風柵；施工道路未舖設鋼板、瀝青等舖面；裸露地面未灑水、栽植、造林、植生被覆或噴灑化學藥劑；出入口未設專用清洗設施；運輸車輛車斗未覆蓋防塵罩等。",
 "Which finding supports enforcement of Article 32(1)(2) of the Act on raising dust?",
 ["Work areas, haul roads or site entrances not effectively watered or swept; no dust nets or fences at the boundary; bare ground not watered, planted or chemically sprayed",
  "No temporary toilets or worker rest areas on site; no night lighting or surveillance at the boundary; bare ground without marked temporary parking",
  "Workers not wearing dust masks or ID badges; no construction notice board or schedule posted; bare ground without drainage ditches or sand traps",
  "No dedicated environmental staff or contact number on site; no sound level or wind meters at the boundary; bare ground not sampled for detailed soil analysis reports"],
 "Article 7."),

(C,"第10條",2,"行為管制-堆置場",
 "主管機關執行礦物、土石或其他粒狀物堆置場之行為管制時，應確認符合下列何種情形之一？",
 ["未設密閉式堆置場、未設灑水系統或未定時灑水、未覆蓋防塵布或防塵罩網、未噴灑化學穩定劑或壓實、未設圍籬擋風牆或靜電幕",
  "未設置地磅及進出場登記簿、未鋪設柏油地面、未張貼堆置高度告示牌、未設置消防設備、未投保公共意外責任保險",
  "未設置專用道路及洗車台紀錄、未申請水土保持計畫、未設置廢水處理池、未設置監視錄影設備、未辦理環境教育訓練",
  "未設置警衛室及夜間照明設備、未取得工廠登記證明、未設置沉砂池設施、未辦理定期檢測申報、未設置防溢堤"],"a",
 "第10條：除確認污染源有明顯粒狀污染物逸散於空氣中外，並應確認符合下列情形之一：未設置有效防止粒狀物質飛散之密閉式堆置場；未設置灑水系統或未定時於堆置物質表面灑水；未覆蓋防塵布或防塵罩網；未於堆置物質表面噴灑化學穩定劑或將其壓實；未設置圍籬、擋風牆或靜電幕；雖有其他防制設施但仍無法有效防制粒狀物逸散。第11條就輸送系統另有類似規定。",
 "Which finding supports behavior control enforcement at mineral or aggregate stockpiles?",
 ["No enclosed stockpile, no sprinkler system or untimely watering, no dust cloth or netting cover, no chemical stabilizer or compaction, no fence, windbreak or electrostatic curtain",
  "No weighbridge or entry log, no asphalt paving, no stacking height notice, no fire-fighting equipment, no public liability insurance",
  "No dedicated road or wheel-wash log, no soil and water conservation plan approved, no wastewater treatment pond, no surveillance recording, no environmental education training",
  "No guard house or night lighting, no factory registration, no sedimentation basin, no periodic testing and reporting, no overflow dike"],
 "Article 10."),

# ---------- ENV-38 空氣品質監測站設置及監測準則（108/9/9） ----------
(M,"第2條",2,"監測站-種類",
 "本準則所定空氣品質監測站之種類，下列組合何者正確？",
 ["一般、交通、工業、國家公園、背景、光化學評估、粒狀污染物化學成分及其他空氣品質監測站",
  "一般、交通、工業、農業、海洋、噪音、氣象觀測及其他空氣品質監測站等八種類別",
  "都市、鄉村、工業、國家公園、水源、光化學評估、酸雨沉降及其他空氣品質監測站",
  "一般、車站、港區、機場、背景、輻射偵測、粒狀污染物化學成分及其他監測站"],"a",
 "第2條：空氣品質監測站種類包括一般、交通、工業、國家公園、背景、光化學評估、粒狀污染物化學成分及其他空氣品質監測站共八類。第3條：中央應以反映全國性、跨縣市及長期空氣品質狀況為目的，地方應以反映當地污染情形為目的，並考量監測站種類、污染源分布、地形氣象、人口與交通等因素選定站址。",
 "Which list correctly gives the types of air quality monitoring stations?",
 ["General, traffic, industrial, national park, background, photochemical assessment, particulate chemical composition, and other stations",
  "General, traffic, industrial, agricultural, marine, noise, meteorological, and other stations",
  "Urban, rural, industrial, national park, water source, photochemical assessment, acid deposition, and other air quality stations",
  "General, bus station, port, airport, background, radiation, particulate chemical composition, and other stations"],
 "Article 2 lists eight types."),

(M,"第2條",2,"監測站-設置地點",
 "背景空氣品質監測站及工業空氣品質監測站之設置地點分別為何？",
 ["背景站設於較少人為污染地區或總量管制區之盛行風上風區；工業站設於工業區之盛行風下風區或反映工業排放高污染之地區",
  "背景站設於工業區之盛行風下風區或反映工業排放高污染之地區；工業站設於較少人為污染地區或總量管制區之盛行風上風區",
  "背景站設於人口密集且交通流量頻繁反映交通排放之地區；工業站設於國家公園內之適當地點或風景保護區周邊地區",
  "背景站設於高臭氧及其前驅物濃度反映高臭氧之地區；工業站設於總量管制區之盛行風上風區或人口密集之地區"],"a",
 "第2條：背景空氣品質監測站設置於較少人為污染地區或總量管制區之盛行風上風區；工業空氣品質監測站設置於工業區之盛行風下風區或能反映因工業排放發生高污染之地區；一般站設於人口密集及可能發生高污染、人員曝露之平均污染濃度地區；光化學評估監測站設於高臭氧及其前驅物濃度之地區。",
 "Where are background stations and industrial stations located?",
 ["Background stations in areas with little human pollution or upwind of total quantity control zones; industrial stations downwind of industrial parks or reflecting high industrial emissions",
  "Background stations downwind of industrial parks or reflecting high industrial emissions; industrial stations in areas with little human pollution or upwind of total control zones",
  "Background stations in densely populated areas with heavy traffic reflecting traffic emissions; industrial stations at suitable points inside national parks",
  "Background stations in areas of high ozone and precursor concentrations; industrial stations upwind of total quantity control zones or in dense population areas"],
 "Article 2, subparagraphs 3 and 5."),

(M,"第10條",3,"監測站-有效數據",
 "各級主管機關對監測數據有效性之規定為何？",
 ["每小時至少有效取樣四十五分鐘；一日內有效小時數至少十六小時；一個月內有效日數至少二十天；每季有效日數達百分之七十五",
  "每小時至少有效取樣三十分鐘；一日內有效小時數至少十二小時；一個月內有效日數至少十五天；每季有效日數達百分之五十",
  "每小時至少有效取樣五十分鐘；一日內有效小時數至少二十小時；一個月內有效日數至少二十五天；每季有效日數達百分之九十",
  "每小時至少有效取樣四十分鐘；一日內有效小時數至少十八小時；一個月內有效日數至少二十二天；每季有效日數達百分之八十"],"a",
 "第10條：每小時至少有效取樣四十五分鐘以上，該小時方為有效小時值；一日內有效小時數至少十六小時以上，該日平均值方為有效日平均值；一個月內有效日數至少二十天以上，該月平均值方為有效月平均值；每季有效日數達百分之七十五，該年平均值方為有效之年平均值。自動監測設施除粒狀污染物等外，其他項目應以分鐘值作為數據紀錄值。",
 "What are the data validity requirements for monitoring records?",
 ["At least 45 valid sampling minutes per hour; at least 16 valid hours per day; at least 20 valid days per month; 75 percent valid days per quarter",
  "At least 30 valid sampling minutes per hour; at least 12 valid hours per day; at least 15 valid days per month; 50 percent valid days per quarter",
  "At least 50 valid sampling minutes per hour; at least 20 valid hours per day; at least 25 valid days per month; 90 percent valid days per quarter",
  "At least 40 valid sampling minutes per hour; at least 18 valid hours per day; at least 22 valid days per month; 80 percent valid days per quarter"],
 "Article 10, subparagraph 2."),

(M,"第11條",2,"監測站-公布期限",
 "各級主管機關定期公布空氣品質狀況之期限規定為何？",
 ["每月月底前地方公布前一月監測統計值；每年三月十五日前公布前一年統計值；每年六月三十日前公布前一年分析及檢討報告",
  "每季季底前地方公布前一季監測統計值；每年一月三十一日前公布前一年統計值；每年十二月三十一日前公布分析及檢討報告",
  "每月十五日前地方公布前一月監測統計值；每年六月十五日前公布前一年統計值；每年九月三十日前公布前一年分析及檢討報告",
  "每半年公布前半年監測統計值；每年三月三十一日前公布前一年統計值；每年十二月三十一日前公布分析及檢討報告"],"a",
 "第11條：每月月底前，直轄市、縣（市）主管機關應公布前一月之各項空氣污染物監測統計值；每年三月十五日前，各級主管機關應公布前一年之監測統計值；每年六月三十日前，各級主管機關應公布前一年空氣品質之分析及檢討報告。空氣品質有嚴重惡化之虞者，應即時公布當時測得之空氣品質狀況。",
 "What are the deadlines for publishing air quality status?",
 ["Local authorities publish the prior month's statistics by month end; prior year statistics by 15 March; prior year analysis and review report by 30 June",
  "Local authorities publish the prior quarter's statistics by quarter end; prior year statistics by 31 January; analysis and review report by 31 December",
  "Local authorities publish the prior month's statistics by the 15th; prior year statistics by 15 June; prior year analysis and review report by 30 September",
  "Authorities publish half-year statistics semi-annually; prior year statistics by 31 March; analysis and review report by 31 December"],
 "Article 11."),

(M,"第9條",1,"監測站-紀錄保存",
 "空氣品質監測站各項監測設施之操作維護紀錄至少應保存幾年？中央已公告或認可自動檢測方法者應如何辦理？",
 ["操作維護紀錄至少應保存三年；中央已公告或認可自動檢測方法者，應以自動檢測方法為之",
  "操作維護紀錄至少應保存一年；中央已公告或認可自動檢測方法者，仍得選擇採用人工檢測方法",
  "操作維護紀錄至少應保存五年；應以中央主管機關指定之檢驗測定機構人工採樣分析方式為之",
  "操作維護紀錄至少應保存十年；應每年報請中央主管機關核准該站所採用之空氣品質檢測方法"],"a",
 "第9條：各級主管機關應正常操作及維護監測設施，作成操作維護紀錄並至少保存三年，紀錄應記載監測項目及量測濃度值、零點及全幅偏移檢查與調整、預防與修復性維護、標準品、校正與查核、數據有效性確認等。第7條：監測方法應符合中央主管機關公告或認可之檢測方法，且中央已公告或認可自動檢測方法者，應以自動檢測方法為之。",
 "How long are operation and maintenance records kept, and what if an automatic method has been announced?",
 ["Records kept at least three years; where an automatic testing method is announced or recognized, that automatic method must be used",
  "Records kept at least one year; where an automatic testing method is announced, manual testing methods may still be chosen",
  "Records kept at least five years; manual sampling by a testing organization designated by the central authority must be used",
  "Records kept at least ten years; the testing method used by the station must be approved annually by the central authority"],
 "Articles 7 and 9."),

(M,"第4條",2,"監測站-站數連線",
 "一般空氣品質監測站應設置站數之最低數量如何規定？何種情形得酌減？地方設置之監測站是否應與中央連線？",
 ["最低數量規定於附表一；監測站連續三年以上符合空氣品質標準且提出調整計畫者得酌減；地方設置之監測站應與中央連線",
  "最低數量規定於本準則條文本身；監測站連續一年符合空氣品質標準即得逕予酌減；地方設置之監測站得自行決定是否連線",
  "最低數量由地方主管機關自行公告；監測站連續五年符合空氣品質標準並經中央核准得酌減；地方監測站僅需每年報送資料",
  "最低數量依人口數每十萬人一站計算；監測站連續二年符合空氣品質標準即得酌減；地方監測站應與環境檢驗機構連線"],"a",
 "第4條：一般空氣品質監測站應設置站數之最低數量規定如附表一，但各級主管機關設置之監測站連續三年以上符合空氣品質標準且提出空氣品質監測站調整計畫者得酌減之；一般站以外之其他種類監測站視實際需要設置。第12條：直轄市、縣（市）主管機關設置之監測站應與中央主管機關連線，各級主管機關並應將原始資料公開於網頁。",
 "How is the minimum number of general stations set, when may it be reduced, and must local stations link to the central authority?",
 ["The minimum is set in Annex 1; a reduction is allowed where stations meet air quality standards for three consecutive years with an adjustment plan; local stations must link to the central authority",
  "The minimum is set in the text of the regulation; a reduction is allowed after one year meeting standards; local stations may decide themselves whether to link",
  "The minimum is announced by each local authority; a reduction needs five consecutive years meeting air quality standards plus central approval; local stations only submit annual data reports",
  "The minimum is one station per hundred thousand people; a reduction is allowed after two years meeting standards; local stations must link to testing organizations"],
 "Articles 4 and 12."),

# ---------- ENV-41 噪音管制區劃定作業準則（109/8/5） ----------
(N,"第2條",1,"噪音管制區-分類",
 "噪音管制區分為四類，其第一類、第二類及第四類之定義分別為何？",
 ["第一類為環境亟需安寧之地區；第二類為供住宅使用為主且需要安寧之地區；第四類為供工業或交通使用為主且需防止噪音影響附近住宅安寧之地區",
  "第一類為供住宅使用為主且需要安寧之地區；第二類為環境亟需安寧之地區；第四類為以住宅使用為主但混合商業或工業使用且需維護住宅安寧之地區",
  "第一類為供工業或交通使用為主之地區；第二類為環境亟需安寧之地區；第四類為供住宅使用為主且需要安寧並防止噪音影響之地區",
  "第一類為以住宅混合商業使用之地區；第二類為供工業或交通使用為主之地區；第四類為環境亟需安寧且應禁止任何噪音行為之地區"],"a",
 "第2條：噪音管制區依土地使用現況、行政區域、地形地物、人口分布劃分為四類：第一類為環境亟需安寧之地區；第二類為供住宅使用為主且需要安寧之地區；第三類為以住宅使用為主但混合商業或工業等使用且需維護其住宅安寧之地區；第四類為供工業或交通使用為主且需防止噪音影響附近住宅安寧之地區。",
 "How are noise control zones 1, 2 and 4 defined?",
 ["Zone 1 urgently needs quiet; Zone 2 is mainly residential and needs quiet; Zone 4 is mainly industrial or transport use needing to prevent noise affecting nearby homes",
  "Zone 1 is mainly residential and needs quiet; Zone 2 urgently needs quiet; Zone 4 is mainly residential mixed with commercial or industrial use needing quiet",
  "Zone 1 is mainly industrial or transport use; Zone 2 urgently needs quiet; Zone 4 is mainly residential needing quiet and noise prevention",
  "Zone 1 is residential mixed with commercial use; Zone 2 is mainly industrial or transport use; Zone 4 urgently needs quiet and bans all noise"],
 "Article 2."),

(N,"第6條",3,"噪音管制區-音量標準",
 "一般地區音量標準值中，第一類噪音管制區之日間、晚間、夜間均能音量分別為何？第一、二類之日間時段如何界定？",
 ["第一類日間五十五、晚間五十、夜間四十五分貝；第一、二類日間指上午六時至晚上八時",
  "第一類日間六十、晚間五十五、夜間五十分貝；第一、二類日間指上午七時至晚上八時",
  "第一類日間五十、晚間四十五、夜間四十分貝；第一、二類日間指上午六時至晚上十時",
  "第一類日間六十五、晚間六十、夜間五十五分貝；第一、二類日間指上午五時至晚上九時"],"a",
 "第6條：一般地區音量標準值第一類為日間五十五、晚間五十、夜間四十五分貝；第二類為六十、五十五、五十；第三類為六十五、六十、五十五；第四類為七十五、七十、六十五。時段區分：第一、二類日間指上午六時至晚上八時、晚間八時至十時、夜間十時至翌日上午六時；第三、四類日間指上午七時至晚上八時、晚間八時至十一時、夜間十一時至翌日上午七時。",
 "For Zone 1, what are the day, evening and night equivalent sound levels, and how is daytime defined for Zones 1 and 2?",
 ["Zone 1 at 55 day, 50 evening, 45 night dB; daytime for Zones 1 and 2 runs 06:00 to 20:00",
  "Zone 1 at 60 day, 55 evening, 50 night dB; daytime for Zones 1 and 2 runs 07:00 to 20:00",
  "Zone 1 at 50 day, 45 evening, 40 night dB; daytime for Zones 1 and 2 runs 06:00 to 22:00",
  "Zone 1 at 65 day, 60 evening, 55 night dB; daytime for Zones 1 and 2 runs 05:00 to 21:00"],
 "Article 6."),

(N,"第6條",3,"噪音管制區-測量條件",
 "劃定噪音管制區蒐集全日環境音量時，其測量條件規定為何？",
 ["聲音感應器置於離地面一點二至一點五公尺；使用快特性；二十四小時連續測量；測量時間內須無雨、路乾且風速每秒五公尺以下",
  "聲音感應器置於離地面零點五至一公尺；使用慢特性；八小時連續測量；測量時間內風速每秒十公尺以下即可進行測量",
  "聲音感應器置於離地面二至三公尺；使用衝擊特性；十二小時連續測量；測量時間內須有雨且風速每秒三公尺以下",
  "聲音感應器置於離地面一至二公尺；使用快特性；四十八小時連續測量；測量時間內須無雨且風速每秒八公尺以下"],"a",
 "第6條：測量高度為聲音感應器置於離地面一．二至一．五公尺之間；動特性須使用快（Fast）特性；測量時間為二十四小時連續測量；氣象條件為測量時間內須無雨、路乾且風速每秒五公尺以下；測量地點應為不受交通噪音影響且具代表性之地點，並距建築物牆面線一公尺以上；附近有明顯噪音源時應停止測量另尋地點。",
 "What measurement conditions apply when collecting all-day environmental sound levels?",
 ["Microphone 1.2 to 1.5 m above ground; Fast dynamic characteristic; 24-hour continuous measurement; no rain, dry road and wind speed 5 m/s or less",
  "Microphone 0.5 to 1 m above ground; Slow dynamic characteristic; 8-hour continuous measurement; wind speed of 10 m/s or less suffices",
  "Microphone 2 to 3 m above ground; Impulse dynamic characteristic; 12-hour continuous measurement; rain required and wind speed 3 m/s or less",
  "Microphone 1 to 2 m above ground; Fast dynamic characteristic; 48-hour continuous measurement; no rain and wind speed 8 m/s or less"],
 "Article 6, subparagraphs 4 to 8."),

(N,"第7條",3,"噪音管制區-劃定原則",
 "各類別噪音管制區劃定原則，下列敘述何者正確？",
 ["不得將第四類相鄰之地區劃為第一類或第二類；不得將第三類相鄰之地區劃為第一類；各類陸上運輸系統應劃定為第四類",
  "不得將第一類相鄰之地區劃為第三類或第四類；不得將第二類相鄰之地區劃為第四類；各類陸上運輸系統應劃定為第三類",
  "不得將第四類相鄰之地區劃為第三類；不得將第二類相鄰之地區劃為第一類；各類陸上運輸系統應劃定為第二類",
  "得將第四類相鄰之地區逕劃為第一類；亦得將第三類相鄰之地區劃為第一類；各類陸上運輸系統應劃定為第一類"],"a",
 "第7條：相鄰二噪音管制區之劃定不得將第四類相鄰之地區劃為第一類或第二類，亦不得將第三類相鄰之地區劃為第一類；各類陸上運輸系統應劃定為第四類噪音管制區；相鄰管制區得以最小街廓、道路中心線、防火巷、建築界線定之；同一建築物劃定為不同類別者，應以較嚴格之噪音管制區劃定。",
 "Which statement on zoning principles is correct?",
 ["Areas adjoining Zone 4 may not be zoned 1 or 2; areas adjoining Zone 3 may not be zoned 1; land transport systems must be zoned 4",
  "Areas adjoining Zone 1 may not be zoned 3 or 4; areas adjoining Zone 2 may not be zoned 4; land transport systems must be zoned 3",
  "Areas adjoining Zone 4 may not be zoned 3; areas adjoining Zone 2 may not be zoned 1; land transport systems must be zoned 2",
  "Areas adjoining Zone 4 may be zoned 1; areas adjoining Zone 3 may also be zoned 1; land transport systems must be zoned 1"],
 "Article 7, subparagraphs 1 and 2."),

(N,"第8條",2,"噪音管制區-特定管制區",
 "距大眾運輸系統、非地下化鐵路、高速公路及快速道路周界多少範圍內應劃為第三類？學校、圖書館及醫療機構得將周界外多少範圍劃為特定噪音管制區？",
 ["距周界至少三十公尺以內之區域應劃定為第三類；學校等場所周界外五十公尺範圍內得劃為特定噪音管制區",
  "距周界至少五十公尺以內之區域應劃定為第三類；學校等場所周界外三十公尺範圍內得劃為特定噪音管制區",
  "距周界至少一百公尺以內之區域應劃定為第四類；學校等場所周界外一百公尺範圍內得劃為特定噪音管制區",
  "距周界至少二十公尺以內之區域應劃定為第二類；學校等場所周界外十公尺範圍內得劃為特定噪音管制區"],"a",
 "第7條第2款第3目：距離大眾運輸系統、非地下化鐵路系統、高速公路及快速道路周界至少三十公尺以內之區域應劃定為第三類噪音管制區，但實施都市計畫、區域計畫地區作為住宅使用而應劃為第二類者不在此限。第8條：學校、圖書館、醫療機構及其他有特別需要安寧之場所，得將該場所周界外五十公尺範圍內劃為各該類噪音管制區之特定噪音管制區。",
 "Which zone applies within a set distance of mass transit, non-underground rail and freeways, and how far out may schools set special zones?",
 ["Within at least 30 m of the boundary must be Zone 3; schools and similar sites may set special zones within 50 m outside their boundary",
  "Within at least 50 m of the boundary must be Zone 3; schools and similar sites may set special zones within 30 m outside their boundary",
  "Within at least 100 m of the boundary must be Zone 4; schools and similar sites may set special zones within 100 m outside their boundary",
  "Within at least 20 m of the boundary must be Zone 2; schools and similar sites may set special zones within 10 m outside their boundary"],
 "Articles 7 and 8."),

(N,"第9條",2,"噪音管制區-公告檢討",
 "劃定或重新劃定公告噪音管制區前應公開展覽多久？圖例顏色第一類至第四類分別為何？公告後應多久檢討一次？",
 ["應公開展覽一個月；第一類淺藍、第二類淺綠、第三類淺黃、第四類淺紅色系；公告後應每二年檢討公告",
  "應公開展覽二星期；第一類淺綠、第二類淺藍、第三類淺紅、第四類淺黃色系；公告後應每五年檢討公告",
  "應公開展覽三個月；第一類淺黃、第二類淺紅、第三類淺藍、第四類淺綠色系；公告後應每一年檢討公告",
  "應公開展覽一星期；第一類淺紅、第二類淺黃、第三類淺綠、第四類淺藍色系；公告後應每三年檢討公告"],"a",
 "第9條：地方主管機關劃定或重新劃定公告噪音管制區前，應會商相關機關並公開展覽一個月徵求修正意見，檢討定案後公告並報中央主管機關備查。第10條：以圖例表示者，第一類為淺藍色系、第二類淺綠色系、第三類淺黃色系、第四類淺紅色系，並應於邊界加註文字說明。第11條：劃定公告後應每二年檢討公告，有特殊情形得提前或延後一年檢討。",
 "How long is the public exhibition, what colors mark Zones 1 to 4, and how often is the zoning reviewed?",
 ["Public exhibition of one month; light blue, light green, light yellow and light red for Zones 1 to 4; reviewed and announced every two years",
  "Public exhibition of two weeks; light green, light blue, light red and light yellow for Zones 1 to 4; reviewed and announced every five years",
  "Public exhibition of three months; light yellow, light red, light blue and light green for Zones 1 to 4; reviewed and announced every year",
  "Public exhibition of one week; light red, light yellow, light green and light blue for Zones 1 to 4; reviewed and announced every three years"],
 "Articles 9 to 11."),

# ---------- ENV-42 易發生噪音設施設置及操作許可辦法（99/7/16） ----------
(S,"第3條",2,"噪音設施-設置申請",
 "申請設施設置許可證所檢具之設置位置圖，須含周圍多少範圍之鄰近關係道路及噪音敏感受體？公告指定前已設置之設施應如何辦理？",
 ["須含周圍一百公尺之鄰近關係道路及噪音敏感受體位置與距離；公告指定前已設置者免申請設置許可證，逕申請操作許可證",
  "須含周圍五十公尺之鄰近關係道路及噪音敏感受體位置與距離；公告指定前已設置者仍應先申請設置許可證再申請操作許可證",
  "須含周圍五百公尺之鄰近關係道路及噪音敏感受體位置與距離；公告指定前已設置者免申請操作許可證，僅申請設置許可證",
  "須含周圍一公里之鄰近關係道路及噪音敏感受體位置與距離；公告指定前已設置者免申請任何許可證，僅需報請主管機關備查"],"a",
 "第3條：申請設施設置許可證應檢具申請人身分證明及目的事業主管機關核准文件影本、設施名稱型式規格數量、設施設置位置圖（須含周圍一百公尺鄰近關係道路、噪音敏感受體相關位置及距離）、設計聲功率及作業條件、其他噪音源種類與噪音防制措施及最大總噪音量評估表等；公告指定前已設置者免申請設置許可證，逕依第6條申請操作許可證。",
 "What radius must the siting map cover, and how are facilities installed before designation handled?",
 ["Roads and noise-sensitive receptors within 100 m of the site with distances; facilities installed before designation skip the installation permit and apply for the operating permit",
  "Roads and noise-sensitive receptors within 50 m of the site with distances; facilities installed before designation must still obtain an installation permit first",
  "Roads and noise-sensitive receptors within 500 m of the site with distances; facilities installed before designation skip the operating permit and apply only for installation",
  "Roads and noise-sensitive receptors within 1 km of the site with distances; facilities installed before designation need no permit and only file a record with the authority"],
 "Article 3."),

(S,"第4條",2,"噪音設施-審查期限",
 "地方主管機關受理公私場所設施設置許可證申請後之繳費、審查及補正通知期限為何？",
 ["應通知於七日內繳納審查費及證書費；受理之日起三十日內完成審查；文件欠缺者於受理之日起十五日內通知限期補正",
  "應通知於十五日內繳納審查費及證書費；受理之日起六十日內完成審查；文件欠缺者於受理之日起三十日內通知限期補正",
  "應通知於三日內繳納審查費及證書費；受理之日起十四日內完成審查；文件欠缺者於受理之日起七日內通知限期補正",
  "應通知於三十日內繳納審查費及證書費；受理之日起九十日內完成審查；文件欠缺者於受理之日起二十日內通知限期補正"],"a",
 "第4條：受理設置許可證申請後應通知所有人或操作人於七日內繳納審查費及證書費，並應於受理之日起三十日內完成審查，符合規定者核發設置許可證；申請文件有欠缺或不合規定者，應於受理之日起十五日內通知限期補正，補正日數不算入審查期間，核准補正之總日數不得超過九十日。第7條：操作許可證審查程序準用第4條。",
 "What are the fee, review and supplementation deadlines for a facility installation permit?",
 ["Notify to pay fees within 7 days; complete review within 30 days of acceptance; notify supplementation within 15 days of acceptance",
  "Notify to pay fees within 15 days; complete review within 60 days of acceptance; notify supplementation within 30 days of acceptance",
  "Notify to pay fees within 3 days; complete review within 14 days of acceptance; notify supplementation within 7 days of acceptance",
  "Notify to pay fees within 30 days; complete review within 90 days of acceptance; notify supplementation within 20 days of acceptance"],
 "Article 4."),

(S,"第10條",3,"噪音設施-營建工程審查",
 "營建工程直接承包商申請設施操作許可證，地方主管機關之審查及補正期限為何？",
 ["應於受理之日起十五日內完成審查；文件欠缺者於受理之日起十日內通知限期補正；核准補正之總日數不得超過九十日",
  "應於受理之日起三十日內完成審查；文件欠缺者於受理之日起十五日內通知限期補正；核准補正之總日數不得超過六十日",
  "應於受理之日起七日內完成審查；文件欠缺者於受理之日起三日內通知限期補正；核准補正之總日數不得超過三十日",
  "應於受理之日起四十五日內完成審查；文件欠缺者於受理之日起二十日內通知限期補正；核准補正之總日數不得超過一百八十日"],"a",
 "第10條：受理營建工程直接承包商操作許可證申請後，應通知其於七日內繳納審查費及證書費，並應於受理之日起十五日內完成審查，符合本辦法、噪音管制標準及地方主管機關依噪音管制法第8條公告規定者核發操作許可證；文件欠缺者應於受理之日起十日內通知限期補正，核准補正之總日數不得超過九十日。第9條並定有噪音估算表等應檢具文件。",
 "What review and supplementation deadlines apply to a construction contractor's operating permit application?",
 ["Complete review within 15 days of acceptance; notify supplementation within 10 days of acceptance; total supplementation days may not exceed 90",
  "Complete review within 30 days of acceptance; notify supplementation within 15 days of acceptance; total supplementation days may not exceed 60",
  "Complete review within 7 days of acceptance; notify supplementation within 3 days of acceptance; total supplementation days may not exceed 30",
  "Complete review within 45 days of acceptance; notify supplementation within 20 days of acceptance; total supplementation days may not exceed 180"],
 "Article 10."),

(S,"第13條",2,"噪音設施-有效期間",
 "公私場所之設施設置及操作許可證有效期間為何？許可期間屆滿仍繼續使用者應於何時申請展延？",
 ["公私場所之許可證有效期間為五年；公私場所設施應於屆滿前三至六個月內申請展延，營建工程設施應於屆滿前一至二個月內申請",
  "公私場所之許可證有效期間為三年；公私場所設施應於屆滿前一至三個月內申請展延，營建工程設施應於屆滿前三至六個月內申請",
  "公私場所之許可證有效期間為十年；公私場所設施應於屆滿前六至十二個月內申請展延，營建工程設施應於屆滿前二至四個月內申請",
  "公私場所之許可證有效期間為二年；公私場所設施應於屆滿前十五日內申請展延，營建工程設施應於屆滿前三十日內申請展延"],"a",
 "第13條：公私場所之設施設置及操作許可證有效期間為五年；營建工程之設施操作許可證有效期間依營建工程之工期定之。許可期間屆滿仍繼續使用者，公私場所之設施應於屆滿前三至六個月內、營建工程之設施應於屆滿前一至二個月內，檢具申請書及噪音檢測報告書向地方主管機關申請展延。",
 "How long are permits valid, and when must renewal be sought?",
 ["Permits for premises last five years; premises facilities apply for renewal three to six months before expiry, construction facilities one to two months before",
  "Permits for premises last three years; premises facilities apply for renewal one to three months before expiry, construction facilities three to six months before",
  "Permits for premises last ten years; premises facilities apply for renewal six to twelve months before expiry, construction facilities two to four months before",
  "Permits for premises last two years; premises facilities apply for renewal 15 days before expiry, construction facilities 30 days before expiry"],
 "Article 13; construction permits run for the works period."),

(S,"第12條",2,"噪音設施-張掛變更",
 "易發生噪音設施在指定管制區內操作時應如何？許可證毀損、滅失或基本資料變更應於幾日內申請？變更原許可內容應如何辦理？",
 ["應張掛操作許可證影本於設施上並能明顯辨識；自事實發生之日起十五日內申請補發換發或變更；變更原許可內容應於變更前重新申請",
  "應將操作許可證正本存放辦公室備查即可；自事實發生之日起六十日內申請補發換發或變更；變更原許可內容得於變更後三十日內報備",
  "應張掛設置許可證正本於工地出入口處；自事實發生之日起三十日內申請補發換發或變更；變更原許可內容應於變更後十五日內換發",
  "應由設施操作人隨身攜帶許可證影本備查；自事實發生之日起七日內申請補發換發或變更；變更原許可內容得逕行變更後年度彙報"],"a",
 "第12條：易發生噪音設施在指定管制區內操作時，應張掛操作許可證影本於設施上，並能明顯辨識所載事項。第14條：許可證於有效期間內因毀損、滅失或基本資料變更者，應自事實發生之日起十五日內檢具證明文件申請補發、換發或辦理變更登記。第15條：應依許可證所載內容設置或操作，有變更原許可內容者，應於變更前重新申請設置或操作許可證。",
 "What display, re-issuance and change rules apply to these permits?",
 ["Post a copy of the operating permit legibly on the facility; apply within 15 days of the event for re-issuance or change; re-apply before changing permitted content",
  "Keep the original permit in the office for inspection; apply within 60 days of the event for re-issuance or change; report changes within 30 days afterwards",
  "Post the original installation permit at the site entrance; apply within 30 days of the event for re-issuance or change; apply for re-issuance within 15 days after changes",
  "The operator carries a copy of the permit at all times; apply within 7 days of the event for re-issuance or change; changes may be made and reported annually"],
 "Articles 12, 14 and 15."),

(S,"第16條",2,"噪音設施-撤銷廢止",
 "直轄市、縣（市）主管機關得撤銷或廢止易發生噪音設施許可證之情形，下列何者正確？",
 ["申請文件有虛偽不實、設施已停止設置或操作、停工或停業一年以上、搬遷或經認定無繼續設立登記或營運之事實",
  "申請文件有虛偽不實、設施每月操作未滿十日、停工或停業三個月以上、負責人變更未於期限內報請主管機關備查",
  "未依規定申報年度操作紀錄、設施操作噪音超過標準一次、停工或停業六個月以上、未依規定參加環境教育訓練",
  "許可證影本未張掛於設施上、單日設施操作時間超過八小時、停工或停業三年以上、未依規定投保公共意外責任險"],"a",
 "第16條：有下列情形之一者，地方主管機關得撤銷或廢止其許可證：申請文件有虛偽不實；設施已停止設置或操作；停工或停業一年以上（有正當理由無法復工報經目的事業主管機關核准者除外）；搬遷或經認定無繼續設立、登記或營運之事實；設施改變為非屬公告應申請許可之設施；非屬公告應申請許可之設施取得許可證；歇業、繳銷登記證明文件或經公告註銷。",
 "Which circumstances allow revocation of a noise facility permit?",
 ["False application documents; the facility has stopped installation or operation; suspension of work or business for over one year; relocation or no continuing operation",
  "False application documents; the facility operates fewer than ten days a month; suspension for over three months; failure to report a change of responsible person",
  "Failure to report annual operating records; one exceedance of the noise standard; suspension for over six months; failure to attend environmental education training",
  "Failure to post the permit copy on the facility; daily operation exceeding eight hours; suspension for over three years; failure to carry public liability insurance"],
 "Article 16."),

# ---------- ENV-43 機動車輛噪音管制標準（109/12/1） ----------
(R,"第2條",2,"車輛噪音-定義",
 "本標準所稱加速噪音標準值及功率質量比之定義為何？",
 ["加速噪音標準值指車輛於一定路程、一定檔位行駛狀態下測出之加速噪音量；功率質量比為引擎最大馬力與受測車重之比值",
  "加速噪音標準值指車輛於原地在一定引擎轉速下測出之原地噪音量；功率質量比為受測車重與引擎最大馬力之比值",
  "加速噪音標準值指車輛於車道行駛時以固定儀器測得之行駛噪音量；功率質量比為引擎排氣量與受測車重之比值",
  "加速噪音標準值指車輛於怠速運轉狀態下測出之最大噪音量；功率質量比為引擎最大扭力與車輛總重量之比值"],"a",
 "第2條：加速噪音標準值指車輛於一定路程、一定檔位行駛狀態下測出之加速噪音量；原地噪音標準值指車輛於原地在一定引擎轉速下測出之原地噪音量；功率質量比（PMR）指引擎最大馬力與受測車重之比值，即最大馬力（kW）／受測車重（公噸）。本標準依噪音管制法第11條第1項訂定。",
 "How are the acceleration noise standard value and power to mass ratio defined?",
 ["The acceleration noise value is measured while driving a set distance in a set gear; the power to mass ratio is maximum engine power divided by tested vehicle weight",
  "The acceleration noise value is measured stationary at a set engine speed; the power to mass ratio is tested vehicle weight divided by maximum engine power",
  "The acceleration noise value is measured by fixed instruments as the vehicle drives in a lane; the power to mass ratio is engine displacement divided by tested weight",
  "The acceleration noise value is the maximum noise measured while idling; the power to mass ratio is maximum engine torque divided by gross vehicle weight"],
 "Article 2, subparagraphs 1, 2 and 8."),

(R,"第2條",2,"車輛噪音-檢驗種類",
 "本標準所稱新車型審驗及新車檢驗之定義分別為何？",
 ["新車型審驗指各車型車輛於製造或進口後、銷售或使用前，對該車型噪音所為之審查檢驗測定；新車檢驗指經新車型審驗合格且製造或進口達規定數量時所為之檢驗測定",
  "新車型審驗指車輛於出廠滿一年後由主管機關所為之定期審查檢驗測定；新車檢驗指車輛完成領牌後第一次定期檢驗時對其噪音所為之檢驗測定",
  "新車型審驗指主管機關於停車場或路旁不定期執行之原地噪音檢驗；新車檢驗指以固定或非固定設置科學儀器對車輛行駛噪音所為之測定",
  "新車型審驗指車輛所有人自行委託檢驗測定機構所為之噪音檢驗；新車檢驗指同一車型每年出廠數量超過一千輛時所為之抽驗測定"],"a",
 "第2條：新車型審驗指各車型車輛於製造或進口後，銷售或使用前，對該車型噪音所為之審查檢驗測定；新車檢驗指車輛經新車型審驗合格，於其製造或進口達規定之數量時，對其噪音所為之檢驗測定；使用中車輛檢驗測定則指主管機關不定期於停車場（站）、路旁、柴油車動力計排煙檢測站、港區或其他適當地點執行之原地噪音檢驗測定。",
 "How are new model verification and new vehicle inspection defined?",
 ["New model verification examines a model's noise after manufacture or import but before sale or use; new vehicle inspection tests noise once an approved model reaches the prescribed production or import quantity",
  "New model verification is a periodic review by the authority one year after the vehicle leaves the factory; new vehicle inspection is the noise test at the first periodic inspection after registration",
  "New model verification is the stationary noise test performed irregularly at parking lots or roadsides; new vehicle inspection is the measurement of driving noise by fixed instruments",
  "New model verification is a noise test commissioned by the vehicle owner from a testing organization; new vehicle inspection is sampling when annual output exceeds one thousand units"],
 "Article 2, subparagraphs 4 and 5."),

(R,"第3條",2,"車輛噪音-標準值",
 "機動車輛噪音管制標準值之規定方式為何？",
 ["第一期至第五期車輛之加速及原地噪音標準值列於附表一；第六期車輛列於附表二；機動車輛行駛噪音標準值列於附表三",
  "第一期至第三期車輛之加速及原地噪音標準值列於附表一；第四期以後車輛列於附表二；機動車輛行駛噪音標準值列於附表三",
  "各期車輛之加速噪音標準值列於附表一；各期車輛之原地噪音標準值列於附表二；行駛噪音標準值由地方主管機關逐年公告",
  "第一期至第五期車輛之行駛噪音標準值列於附表一；第六期車輛之原地噪音列於附表二；加速噪音標準值由中央主管機關另行公告"],"a",
 "第3條：機動車輛噪音管制標準值如下：第一期至第五期機動車輛加速噪音、原地噪音之噪音管制標準值如附表一；第六期機動車輛加速噪音、原地噪音之噪音管制標準值如附表二；機動車輛行駛噪音之噪音管制標準值如附表三。第4條：本標準除另定施行日期者外，自發布日施行。",
 "How are the motor vehicle noise control standard values set out?",
 ["Acceleration and stationary noise values for phases 1 to 5 in Annex 1; phase 6 in Annex 2; driving noise values in Annex 3",
  "Acceleration and stationary noise values for phases 1 to 3 in Annex 1; phase 4 onward in Annex 2; driving noise values in Annex 3",
  "Acceleration noise values for all phases in Annex 1; stationary noise values in Annex 2; driving noise values announced yearly by local authorities",
  "Driving noise values for phases 1 to 5 in Annex 1; phase 6 stationary noise in Annex 2; acceleration noise values announced separately by the central authority"],
 "Article 3."),
]
