# -*- coding: utf-8 -*-
# 第 11 批（F4）：碼頭裝卸安全衛生設施標準 第41條～第68條（補題）
WH = "OSH-46"
Q = [
(WH,"第41條",2,"碼頭裝卸-起重作業",
 "使用起重機具從事貨艙內部貨物之捲升作業時，對於艙口正下方以外之貨物應如何處理？",
 ["應將貨物移至艙口正下方後，方得使勞工從事捲升作業","應以吊索斜拉方式直接捲升，並指派人員在旁指揮作業","應先拆除艙口樑及蓋板後，再以斜吊方式將貨物捲升之","應由船方確認吊掛角度未超過三十度後，即得斜吊捲升"],"a",
 "第41條：雇主於使用起重機具從事貨艙內部貨物之捲升作業時，對於在艙口正下方以外之貨物，應將貨物移至正下方後，方得使勞工從事作業。第53條並要求由艙口裝卸貨物者應指派人員擔任指揮作業。",
 "How must cargo not directly under the hatch be handled when hoisting?",
 ["It must first be moved to a position directly under the hatch opening","It may be hoisted by a slanting pull with a signaller standing alongside","The hatch beams and covers must be removed and the load hoisted aslant","The ship may allow a slanting lift once the angle is under thirty degrees"],
 "Article 41."),

(WH,"第42條",1,"碼頭裝卸-貨櫃",
 "貨櫃裝卸時須拆除或安放墊腳鎖栓之作業，雇主應備置何種設備？",
 ["應備置安全扶梯或其他安全上下貨櫃之設備，供勞工使用","應備置安全帽及安全帶等個人防護具，供勞工於高處使用","應備置移動式起重機及吊籠等設備，供勞工上下貨櫃使用","應備置警示標誌及交通錐等設備，供劃定作業區域之使用"],"a",
 "第42條：雇主於貨櫃裝卸時，須拆除或安放墊腳鎖栓之作業，應備置安全扶梯或其他安全上下貨櫃之設備，供勞工使用。第66條並要求依作業危害性質使勞工戴用安全帽、使用安全帶或穿著反光背心等防護具。",
 "What must be provided for fitting or removing container twist locks?",
 ["A safe ladder or other equipment for getting on and off the container","Helmets and safety belts as personal protective equipment for the work","A mobile crane and a man-cage for lifting workers onto the container","Warning signs and traffic cones for marking out the working area off"],
 "Article 42."),

(WH,"第44條",1,"碼頭裝卸-裝卸作業",
 "貨艙、甲板或陸上裝卸作業時，雇主應禁止勞工進入何種區域？",
 ["吊舉物下方及其他有發生危害之虞之區域","吊舉物側方三公尺以內之作業指揮區域","起重機具駕駛座後方之視線死角區域者","艙口緣圍外側一公尺以內之堆貨區域者"],"a",
 "第44條：貨艙、甲板或陸上裝卸作業時，雇主應禁止勞工進入吊舉物下方及其他有發生危害之虞之區域。第45條並列舉艙口蓋板開閉、艙口樑安裝拆卸下方及起重機具伸臂起伏之危險區域。",
 "Which area must workers be kept out of during cargo handling?",
 ["The area under a suspended load and any other area where harm may occur","The area within three metres beside the load where the signaller stands","The blind spot area behind the driving seat of the lifting appliance used","The stacking area within one metre outside of the hatch coaming itself"],
 "Article 44."),

(WH,"第45條",2,"碼頭裝卸-裝卸作業",
 "雇主不得使勞工進入之場所，除艙口蓋板作業下方外，尚包括何者？",
 ["實施起重機具伸臂、吊桿起伏作業，有傾倒之虞之危險區域","實施起重機具定期自動檢查作業，有感電之虞之維修區域者","實施貨櫃墊腳鎖栓拆裝作業，有夾傷之虞之貨櫃底盤區域者","實施艙內通風換氣作業，有缺氧之虞之貨艙底層作業區域者"],"a",
 "第45條第2款：雇主不得使勞工進入實施起重機具之伸臂、吊桿起伏作業，有傾倒之虞之危險區域。同條第1款則為艙口蓋板開閉、艙口樑安裝拆卸等作業場所之下方，蓋板、艙口樑有掉落之虞之危險區域。",
 "Besides areas under hatch cover work, where else must workers not enter?",
 ["Areas at risk of toppling during luffing of a crane jib or derrick boom","Areas at risk of electric shock during periodic self-inspection of cranes","Areas at risk of crushing on the chassis during twist lock removal work","Areas at risk of oxygen deficiency at the bottom of a hold being aired"],
 "Article 45, subparagraph 2."),

(WH,"第45條",2,"碼頭裝卸-裝卸作業",
 "實施艙口蓋板開閉、艙口樑安裝拆卸等作業時，何處為禁止勞工進入之危險區域？",
 ["作業場所之下方，蓋板、艙口樑有掉落之虞之危險區域","作業場所之上方，蓋板、艙口樑有翻覆之虞之危險區域","作業場所之側方，蓋板、艙口樑有滑動之虞之危險區域","作業場所之艙底，蓋板、艙口樑有堆置之虞之危險區域"],"a",
 "第45條第1款：雇主不得使勞工進入實施艙口蓋板之開閉、艙口樑之安裝、拆卸等作業場所之下方，蓋板、艙口樑有掉落之虞之危險區域。第30條並要求作業前將艙口樑及蓋板適度移去或妥為固定安置。",
 "Which zone is off limits during opening or removal of hatch covers and beams?",
 ["Below the work place, where covers or beams are liable to fall onto people","Above the work place, where covers or beams are liable to overturn on people","Beside the work place, where covers or beams are liable to slide onto people","At the hold bottom, where covers or beams are liable to be stacked on people"],
 "Article 45, subparagraph 1."),

(WH,"第46條",2,"碼頭裝卸-卸貨",
 "待卸貨物在下層而中上層另有其他貨物時，雇主於卸貨前應如何辦理？",
 ["應先翻艙或洽由船方採取有效之圍檔處理，經確認無礙安全者除外","應先將中上層貨物全部卸至碼頭堆置，不得以圍檔方式替代處理","應先由貨方出具切結書載明貨物穩定，即得逕行卸取下層之貨物","應先報請港口管理機關（構）派員在場監督，始得卸取下層貨物"],"a",
 "第46條：雇主於從事船舶卸貨前，待卸貨物在下層，而中上層有其他貨物者，應先翻艙或洽由船方採取有效之圍檔處理；但經確認無礙作業安全者，不在此限。第63條並要求甲板作業有物料移位、倒塌之虞時妥為固定。",
 "What must be done before discharging lower cargo with other cargo above it?",
 ["Restow the hold or have the ship set effective shifting boards, unless safety is confirmed","Land all the cargo above onto the quay first, since shifting boards may not be used here","Obtain a written undertaking from the cargo interest that the stow is stable, then discharge","Report to the port authority so that it sends a supervisor before the lower cargo is taken"],
 "Article 46."),

(WH,"第47條",2,"碼頭裝卸-共同作業",
 "出貨、進貨、堆貨或卸貨作業須借助他方始能安全作業時，應如何辦理？",
 ["應與船方、港口管理機關（構）或碼頭經營者共同採取預防災變之適當措施","應由雇主單獨採取預防災變之適當措施，他方僅負提供場地及設備之責任","應由船方統籌採取預防災變之適當措施，雇主僅負指揮所屬勞工之責任者","應報請港口管理機關（構）指定專責機構，由該機構採取預防災變之措施"],"a",
 "第47條：雇主對於出貨、進貨、堆貨、卸貨或其他類似作業，須借助船方、港口管理機關（構）或碼頭經營者始能安全作業者，應共同採取預防災變之適當措施。第49條並定危險物質裝卸時船方、貨方之告知義務。",
 "What is required where safe cargo work depends on another party?",
 ["The employer and the ship, port authority or terminal operator jointly take preventive measures","The employer alone takes preventive measures, the others only providing the site and equipment","The ship operator takes charge of preventive measures, the employer only directing its workers","The port authority designates a dedicated body which then takes the preventive measures itself"],
 "Article 47."),

(WH,"第48條",2,"碼頭裝卸-詢問書",
 "實施船舶裝卸作業前，船舶裝卸設施及作業環境詢問書應由何人填具？其內容為何？",
 ["由船方填具雇主所提供之詢問書，預先說明安全顧慮事項及已採取之改善措施","由雇主填具船方所提供之詢問書，預先說明安全顧慮事項及已採取之改善措施","由貨方填具碼頭經營者提供之詢問書，載明貨物性質及所採取之包裝方式者","由碼頭經營者填具港口管理機關（構）提供之詢問書，載明碼頭設施之現況"],"a",
 "第48條第1項：實施船舶裝卸作業前，船方應填具雇主所提供之船舶裝卸設施及作業環境詢問書（如附表），預先說明與標明與船舶裝卸作業有安全顧慮事項，及已採取之改善措施。該詢問書並由船長、大副簽字。",
 "Who fills in the ship handling facility inquiry sheet, and what does it state?",
 ["The ship fills in the sheet the employer supplies, stating safety concerns and measures taken","The employer fills in the sheet the ship supplies, stating safety concerns and measures taken","The cargo interest fills in the terminal operator's sheet, stating cargo nature and packing","The terminal operator fills in the port authority's sheet, stating the state of quay facilities"],
 "Article 48, paragraph 1."),

(WH,"第48條",3,"碼頭裝卸-詢問書",
 "雇主對詢問書之記載事項，認有影響裝卸作業安全之虞時，應如何處理？",
 ["應使勞工知悉，並要求船方即採必要改善措施；必要時報請港口管理機關（構）責成改善","應使勞工知悉，並逕行報請勞動檢查機構停止該船舶之全部裝卸作業後始得再行作業","應由雇主自行改善該船舶設施後向船方求償，並將改善結果通知碼頭經營者備查之","應請貨方協調船方改善，改善期間得由雇主指派監視人員在場後繼續進行裝卸作業"],"a",
 "第48條第2項：雇主對於詢問書所定記載事項，應使勞工知悉，認有影響裝卸作業安全之虞者，應要求船方即採必要改善措施；必要時，報請港口管理機關（構）責成船方改善後，再行作業。第6條第3項亦有相同之改善程序。",
 "What must the employer do if the inquiry sheet reveals a safety concern?",
 ["Inform the workers, require the ship to fix it, and if needed ask the port authority to enforce it","Inform the workers, and report to the labour inspector to halt all cargo work on that ship first","Repair the ship facility itself and claim the cost, notifying the terminal operator of the result","Ask the cargo interest to coordinate repairs and keep working meanwhile with a watcher posted"],
 "Article 48, paragraph 2."),

(WH,"第48條",2,"碼頭裝卸-詢問書",
 "船舶裝卸設施及作業環境詢問書之附表，包括下列何項詢問內容？",
 ["作業艙間有無使用乾冰、冷劑或可能缺氧情形，及有無殘留爆炸性、有毒性物質","作業艙間之貨物重量、貨櫃編號及裝卸順序，及預定完成裝卸作業之日期時間","作業勞工之姓名、證照號碼及投保紀錄，及雇主所指派裝卸作業主管之經歷","碼頭岸肩承載力、繫船柱拉力及水深資料，及港口管理機關（構）核准文號"],"a",
 "第48條附表：船舶裝卸設施及作業環境詢問書列有十三項詢問內容，包括有無裝載危險品過境、作業艙間有無殘留爆炸性、有毒性或其他易燃性物質、有無使用乾冰、冷劑或可能缺氧情形、有機物質有無經海水浸濕等；備註欄並應註明已採取之改善措施。",
 "Which item appears in the inquiry sheet attached to this Standard?",
 ["Whether holds use dry ice or coolant or may lack oxygen, and whether explosive or toxic residues remain","Whether the cargo weight, container numbers and handling order and the planned completion time are set","Whether the workers names, licence numbers and insurance records and the supervisor experience are held","Whether the apron bearing capacity, bollard pull and water depth and the port approval number are stated"],
 "Article 48 and the attached inquiry sheet."),

(WH,"第48條",2,"碼頭裝卸-詢問書",
 "詢問書就船舶裝卸設備所詢問之事項，主要為何？",
 ["是否曾由檢驗機構於規定期限內檢驗、有無檢查合格證明文件可供隨時查閱","是否已投保機具損壞責任保險、有無理賠紀錄文件可供裝卸公司隨時查閱","是否為五年內新購之裝卸設備、有無原廠保證書可供港口管理機關查驗之","是否已向碼頭經營者辦理設備登記、有無繳納使用費之收據可供查驗之者"],"a",
 "第48條附表第五項、第六項：詢問貴輪所有裝卸設備及其附件是否曾由檢驗機構於規定期限內予以檢驗、有無檢查合格證明文件隨時提供查閱，並填載檢查日期及檢驗機構代號；另詢問有無完成自動檢查、起重設備是否穩定安全。",
 "What does the inquiry sheet mainly ask about the ship cargo gear?",
 ["Whether it was surveyed within the prescribed period and whether certificates can be shown at any time","Whether damage liability insurance was taken out and whether claim records can be shown at any time","Whether the gear was bought new within five years and whether a maker warranty can be shown at all","Whether the gear was registered with the terminal operator and whether fee receipts can be produced"],
 "Article 48, inquiry sheet items 5 and 6."),

(WH,"第50條",3,"碼頭裝卸-吊掛",
 "貨艙作業空間因艙口方孔限制時，關於索鈎之使用有何禁止規定？",
 ["除解除或連結吊索外，不得使勞工以索鈎鈎住捆包之打包帶、箍帶、繩索或緊固件","除解除或連結吊索外，不得使勞工以索鈎鈎住貨櫃之角件、吊耳或墊腳鎖栓等處","除吊運圓桶貨物外，不得使勞工以索鈎鈎住麻袋、棉花等貨物捆包之外層包裝物","除吊運散裝貨物外，不得使勞工以索鈎鈎住輸送帶、抓斗及吸穀機等機具構件者"],"a",
 "第50條第1項：貨艙作業空間因艙口方孔之限制，除從事解除或連結吊索外，雇主不得使勞工利用索鈎鈎住捆紮於棉花、羊毛、軟木、麻袋或其他類似貨物捆包之打包帶、箍帶、繩索或緊固件上。第2項並禁止使用構造或狀況不安全之圓桶貨物掛鈎。",
 "What use of cargo hooks is prohibited where the hatch square limits space?",
 ["Except when slinging or unslinging, hooking the straps, bands, ropes or fastenings of bales is barred","Except when slinging or unslinging, hooking the corner castings, lugs or twist locks of boxes is barred","Except when handling drums, hooking the outer wrapping of sacks and cotton bales is barred entirely","Except when handling bulk cargo, hooking parts of conveyors, grabs and grain suckers is barred here"],
 "Article 50, paragraph 1."),

(WH,"第50條",2,"碼頭裝卸-吊掛",
 "圓桶貨物之掛鈎構造或狀況不安全時，雇主應如何處理？",
 ["不得使勞工使用該貨桶之掛鈎起降貨桶","應使勞工加繫安全索後再以該掛鈎起降","應使勞工降低吊升速度後再以掛鈎起降","應由船方確認後即得以該掛鈎起降貨桶"],"a",
 "第50條第2項：圓桶貨物及其掛鈎之構造或狀況不安全者，雇主不得使勞工使用該貨桶之掛鈎起降貨桶。第58條並要求作業前檢點吊鏈、鋼索及纜繩等吊具，不得使用不符規格及不堪用之吊具。",
 "What if the hook of a drum cargo is unsafe in construction or condition?",
 ["Workers must not use that drum hook to raise or lower the drum","Workers may use it after an extra safety line has been attached","Workers may use it once the hoisting speed has been reduced","Workers may use it once the ship operator has confirmed it"],
 "Article 50, paragraph 2."),

(WH,"第51條",2,"碼頭裝卸-堆貨",
 "堆置於船舶中層艙之貨物與艙口緣圍間之距離，船方應保持多少？",
 ["應保持一公尺以上，以利開啟艙口蓋板或移動艙口樑","應保持五十五公分以上，以利開啟蓋板或移動艙口樑","應保持七十五公分以上，以利開啟蓋板或移動艙口樑","應保持三公尺以上，以利開啟艙口蓋板或移動艙口樑"],"a",
 "第51條第1項：船方對於堆置於船舶中層艙之貨物與艙口緣圍間之距離，應保持一公尺以上，以利開啟艙口蓋板或移動艙口樑，並防止貨物移動造成掉落事故。第9條並定碼頭通道寬度應保持一公尺以上。",
 "What clearance must be kept between tween deck cargo and the hatch coaming?",
 ["At least one metre, so that hatch covers can be opened or beams moved","At least fifty-five centimetres, so covers can be opened or beams moved","At least seventy-five centimetres, so covers can be opened or beams moved","At least three metres, so that hatch covers can be opened or beams moved"],
 "Article 51, paragraph 1."),

(WH,"第51條",3,"碼頭裝卸-堆貨",
 "露天甲板之艙口蓋板與艙口緣圍並置時，船方應如何放置？",
 ["應放置整齊，堆放高度不得超過艙口緣圍高度，且與緣圍保持一公尺以上距離並固定","應放置整齊，堆放高度不得超過艙口緣圍二倍，且與緣圍保持五十公分以上距離固定","應放置整齊，堆放高度不得低於艙口緣圍高度，且與緣圍保持三公尺以上距離並固定","應放置整齊，堆放高度不得超過一點五公尺，且與緣圍保持七十五公分以上距離固定"],"a",
 "第51條第2項：船方對於露天甲板之艙口蓋板與艙口緣圍並置時，應放置整齊，堆放高度不得超過艙口緣圍之高度，且與艙口緣圍保持一公尺以上之距離，並妥為固定之。第29條第2項並定留置碼頭上時應設圍欄或警告標示。",
 "How must hatch covers stowed beside the coaming on deck be placed?",
 ["Neatly, not higher than the coaming, at least one metre from it, and properly secured","Neatly, not higher than twice the coaming, at least fifty centimetres from it, secured","Neatly, not lower than the coaming height, at least three metres from it, and secured","Neatly, not higher than one and a half metres, at least 75 centimetres from it, secured"],
 "Article 51, paragraph 2."),

(WH,"第52條",1,"碼頭裝卸-機具",
 "起重機具、絞盤或其他裝卸機具上懸留物件，本標準如何規定？",
 ["除正在運轉操作者外，雇主不得任令物件懸留其上","除吊舉物重量未達五百公斤者外，不得任令其懸留","除夜間停止作業期間外，得任令物件懸留於機具上","除經指揮人員同意者外，不得任令物件懸留其上者"],"a",
 "第52條：雇主對於起重機具、絞盤或其他裝卸機具，除正在運轉操作者外，不得任令物件懸留其上。第44條並禁止勞工進入吊舉物下方及其他有發生危害之虞之區域。",
 "What is the rule on leaving loads suspended on cargo handling gear?",
 ["Except while actually being operated, loads may not be left hanging on it","Except where the load is under five hundred kilograms, none may be left","Except during the night when work has stopped, loads may be left hanging","Except where the signaller has agreed to it, loads may not be left hanging"],
 "Article 52."),

(WH,"第53條",2,"碼頭裝卸-指揮",
 "使用起重機具或吊索由艙口裝卸貨物者，雇主應如何辦理？",
 ["應指派人員擔任指揮作業","應指派人員擔任監視作業","應指派人員擔任檢點作業","應指派人員擔任警戒作業"],"a",
 "第53條第1項：使用起重機具或吊索由艙口裝卸貨物者，雇主應指派人員擔任指揮作業。同條第2項並定同一艙口在同一時間有二組以上人員分別作業者，雇主應各指派人員負責指揮。",
 "What must the employer do when cargo is worked through the hatch by crane?",
 ["Assign a person to direct the operation","Assign a person to watch the operation","Assign a person to inspect the operation","Assign a person to guard the operation"],
 "Article 53, paragraph 1."),

(WH,"第53條",2,"碼頭裝卸-指揮",
 "同一艙口在同一時間有二組以上人員分別作業時，指揮人員應如何指派？",
 ["雇主應各指派人員負責指揮各該組作業","雇主得指派一人同時指揮各該組之作業","雇主應由船方派員統一指揮各該組作業","雇主得由各組推派一人輪流指揮該作業"],"a",
 "第53條第2項：使用起重機具或吊索由艙口裝卸貨物之作業，於同一艙口在同一時間有二組以上人員分別作業者，雇主應各指派人員負責指揮。第64條並定總噸位五百公噸以上船舶應指派船舶裝卸作業主管。",
 "How are directors assigned where two or more gangs work one hatch at once?",
 ["The employer assigns a separate director for each gang","The employer may assign one person to direct all the gangs","The employer has the ship assign one director for all gangs","Each gang may elect one member to direct the work in turn"],
 "Article 53, paragraph 2."),

(WH,"第55條",2,"碼頭裝卸-車輛",
 "使用裝卸車輛至貨艙內作業前，雇主應先經何人確認何事項？",
 ["應經船方確認貨艙內空間配置、行車動線及裝卸作業流程確無危險之虞","應經貨方確認貨艙內貨物性質、包裝方式及堆疊高度確無危險之虞者","應經碼頭經營者確認車輛檢驗、駕駛資格及保險文件確無欠缺之情形","應經港口管理機關（構）確認船舶噸位、吃水及靠泊位置確無異常者"],"a",
 "第55條：雇主於使用裝卸車輛至貨艙內作業前，應經船方確認貨艙內之空間配置、行車動線及裝卸作業流程等確無危險之虞，始得使勞工作業。第56條並要求貨艙內不得使用內燃機之機械以免廢氣危害。",
 "Whose confirmation and of what is needed before vehicles enter a hold?",
 ["The ship must confirm hold layout, traffic routes and the work flow are free of danger","The cargo interest must confirm cargo nature, packing and stack height are free of risk","The terminal operator must confirm vehicle tests, driver licences and insurance papers","The port authority must confirm ship tonnage, draught and berthing position are normal"],
 "Article 55."),

(WH,"第58條",1,"碼頭裝卸-吊具",
 "從事起重吊掛作業前，雇主應對陸上起重機具之吊具如何辦理？",
 ["應檢點吊鏈、鋼索及纜繩等吊具，不得使用不符規格及不堪用之吊具","應檢點吊鏈、鋼索及纜繩等吊具，不堪用者得於減半荷重下繼續使用","應委由船方檢點吊鏈、鋼索及纜繩等吊具，並由船方出具檢點紀錄表","應每三個月檢點吊鏈、鋼索及纜繩等吊具一次，作業前得免再行檢點"],"a",
 "第58條：雇主於從事起重吊掛作業前，應檢點陸上起重機具使用之吊鏈、鋼索及纜繩等吊具，不得使用不符規格及不堪用之吊具。第6條第2項並要求裝卸機具使用前實施檢點，發現異常應妥為處理。",
 "What must be done with shore crane slings before hoisting work?",
 ["Check chains, wire ropes and ropes, and never use slings off spec or unfit for use","Check chains, wire ropes and ropes; unfit ones may still be used at half the load","Have the ship check the chains, wire ropes and ropes and issue a check record","Check chains, wire ropes and ropes every three months, with no check before work"],
 "Article 58."),

(WH,"第59條",2,"碼頭裝卸-吊掛",
 "從事起重吊掛作業時，關於鋼索、鏈條長度之調整有何規定？",
 ["不得以打結方式縮短綱索、鏈條等之長度","不得以焊接方式加長綱索、鏈條等之長度","不得以夾具方式固定綱索、鏈條等之末端","不得以襯墊方式包覆綱索、鏈條等之表面"],"a",
 "第59條第1款：雇主於從事起重吊掛作業時，不得以打結方式縮短綱索、鏈條等之長度。同條第2款、第3款並要求避免麻繩、鋼索、鏈條與尖銳邊緣接觸或使用襯墊防止磨損，及注意包裝綑綁並採安全吊掛方法。",
 "What rule applies to shortening wire ropes or chains in slinging work?",
 ["Wire ropes and chains may not be shortened by tying knots in them","Wire ropes and chains may not be lengthened by welding them here","Wire ropes and chains may not be secured at the ends by clamps","Wire ropes and chains may not be wrapped over with any padding"],
 "Article 59, subparagraph 1."),

(WH,"第59條",2,"碼頭裝卸-吊掛",
 "為防止吊具磨損，起重吊掛作業應採取何種措施？",
 ["麻繩、鋼索、鏈條應避免與所吊堅硬物體之尖銳邊緣接觸，或使用襯墊","麻繩、鋼索、鏈條應以打結方式縮短長度，使其避開堅硬物體之邊緣者","麻繩、鋼索、鏈條應每次作業後浸油保養，並於磨損後以焊接方式修補","麻繩、鋼索、鏈條應僅用於吊運軟質包裝貨物，堅硬物體改以抓斗吊運"],"a",
 "第59條第2款：麻繩、鋼索、鏈條應避免與所吊堅硬物體之尖銳邊緣相接觸，或使用襯墊，以防止磨損。同條第3款並要求吊運貨物注意包裝及綑綁，並採取安全吊掛方法。",
 "How must sling wear be prevented in hoisting operations?",
 ["Keep ropes, wire ropes and chains off sharp edges of hard loads, or use packing pads","Shorten ropes, wire ropes and chains by knots so that they clear the hard load edges","Oil ropes, wire ropes and chains after each job and weld them up once they are worn","Use ropes, wire ropes and chains only for soft packages, hard loads going by grab"],
 "Article 59, subparagraph 2."),

(WH,"第60條",2,"碼頭裝卸-視線",
 "起重機具或絞盤之原動機排出廢氣或蒸汽妨礙工作者視線時，應如何處理？",
 ["船方應採取適當措施防止其妨礙視線；雇主使勞工從事起重作業者亦同","船方應採取適當措施防止其妨礙視線；雇主僅需於作業前提醒勞工注意","雇主應於作業區設置抽風設備排除廢氣；船方不負任何防止妨礙之責任","貨方應協調船方停止該原動機運轉；雇主得於視線不良時繼續指揮作業"],"a",
 "第60條：船方應採取適當措施，防止起重機具或絞盤之原動機排出廢氣或蒸汽妨礙工作者之視線；雇主使勞工從事起重作業者，亦同。第27條並定船上裝卸作業場所之照明由船方提供必要照度。",
 "What must be done when engine exhaust or steam blocks workers vision?",
 ["The ship must take suitable measures to prevent it, and so must the employer","The ship must take suitable measures to prevent it; the employer only warns","The employer must fit extraction fans in the area; the ship bears no duty here","The cargo interest asks the ship to stop the engine; work may go on meanwhile"],
 "Article 60."),

(WH,"第61條",2,"碼頭裝卸-起重機具",
 "為預防貨櫃起重機等機架底盤出軌或人字臂起重桿脫離基座，應由何人辦理？",
 ["應由雇主及船方採適當設備或措施加以預防","應由碼頭經營者單獨採適當設備加以預防之","應由港口管理機關（構）採適當措施以預防","應由貨方與碼頭經營者共同採措施加以預防"],"a",
 "第61條：雇主及船方應採適當設備或措施，預防貨櫃起重機等之機架底盤意外出軌或人字臂起重桿脫離基座。第38條並要求船方提供適當設備預防起重機具、吊桿及所吊物件掉落。",
 "Who must prevent gantry cranes derailing or derrick posts leaving their steps?",
 ["The employer and the ship operator must take suitable equipment or measures","The terminal operator alone must take suitable equipment to prevent it here","The port authority must take suitable measures to prevent it from happening","The cargo interest and terminal operator jointly take measures to prevent it"],
 "Article 61."),

(WH,"第62條",2,"碼頭裝卸-天候",
 "遭遇強風、大雨或雷電交加等惡劣天候致作業有危險之虞時，雇主應如何辦理？",
 ["不得使勞工從事船舶裝卸作業","應加派指揮人員後繼續作業","應縮短工時並降低吊升荷重","應由船方確認後始繼續作業"],"a",
 "第62條第1項：遭遇強風、大雨或雷電交加等惡劣天候，致作業有危險之虞時，雇主不得使勞工從事船舶裝卸作業。同條第2項並定停止作業得由當地港口管理機關（構）統一規定，以供雇主遵循。",
 "What must the employer do in strong wind, heavy rain or lightning?",
 ["Workers must not be engaged in ship cargo handling work","More signallers must be added and the work may continue","Working hours are cut and the hoisting load is lowered","Work may continue once the ship operator has confirmed"],
 "Article 62, paragraph 1."),

(WH,"第62條",2,"碼頭裝卸-天候",
 "碼頭裝卸之停止作業，得由何人依何項因素統一規定，以供雇主遵循？",
 ["由當地港口管理機關（構）依地理環境、氣象預報及實際天候等狀況統一規定","由當地勞動檢查機構依災害統計、勞工人數及作業種類等狀況統一規定之者","由碼頭經營者依碼頭設施、貨物性質及船舶噸位等狀況統一規定並公告之","由船方依船舶構造、繫泊狀況及貨艙配置等狀況統一規定並通知雇主遵循"],"a",
 "第62條第2項：碼頭裝卸之停止作業，得由當地港口管理機關（構）依各該港口之地理環境、氣象預報及實際天候等狀況，統一規定，以供雇主遵循。同條第1項則定惡劣天候有危險之虞時雇主不得使勞工作業。",
 "Who may lay down uniform rules for suspending quay work, and on what basis?",
 ["The local port authority, based on the geography, weather forecast and actual weather","The local labour inspector, based on accident statistics, worker numbers and work type","The terminal operator, based on quay facilities, cargo nature and the tonnage of ships","The ship operator, based on ship structure, mooring condition and the hold arrangement"],
 "Article 62, paragraph 2."),

(WH,"第63條",1,"碼頭裝卸-甲板作業",
 "於船舶甲板從事裝卸作業有物料移位、倒塌之虞時，雇主應如何辦理？",
 ["應妥為固定或採取其他安全措施","應立即停止作業並撤離全部勞工","應加派監視人員在旁警戒後作業","應報請船方於下一港口改善處理"],"a",
 "第63條：雇主於船舶甲板從事裝卸作業，有物料移位、倒塌之虞時，應妥為固定或採取其他安全措施。第46條並定卸貨前貨物在下層而中上層有其他貨物者應先翻艙或圍檔。",
 "What must be done when materials on deck may shift or collapse?",
 ["They must be properly secured or other safety measures taken","Work must stop at once and all workers be evacuated ashore","Extra watchers must be posted alongside before work goes on","The ship must be asked to put it right at the next port call"],
 "Article 63."),

(WH,"第65條",1,"碼頭裝卸-防護具",
 "為防止作業人員落水，雇主應於各作業艙碼頭舷側採取何種措施？",
 ["應加掛護網，或採取其他安全措施","應加掛救生圈，並派員全程監視之","應加設欄柵，並禁止勞工接近舷側","應加設照明，並劃設反光警示標線"],"a",
 "第65條：雇主應於各作業艙碼頭舷側加掛護網，或採取其他安全措施，以防止作業人員落水。第16條並要求勞工經由水上往返作業場所時搭乘符合船舶法規之交通船。",
 "What must be provided at the shipside of each working hatch to stop falls into water?",
 ["Safety nets must be hung, or other safety measures taken","Lifebuoys must be hung and a watcher posted throughout","Rails must be added and workers kept away from the side","Lighting must be added and reflective warning lines set"],
 "Article 65."),

(WH,"第67條",2,"碼頭裝卸-防護具",
 "從事處理毒性物質、有害物質或有粉塵飛揚等作業時，雇主應如何辦理？",
 ["應使勞工佩戴適當防護具、穿著必要防護衣物或使用相關安全裝備","應使勞工縮短連續作業時間並每二小時輪換一次以減少暴露之時間","應使勞工於上風處作業並由船方於作業前實施艙內灑水抑制粉塵者","應使勞工先接受特殊健康檢查合格後始得從事該類物質之裝卸作業"],"a",
 "第67條：雇主於從事處理毒性物質、有害物質、易於飛散物質或有粉塵飛揚等之作業時，應使勞工佩戴適當防護具、穿著必要防護衣物或使用相關安全裝備。第66條並定依作業危害性質使用安全帽、安全帶及反光背心等。",
 "What must be done for work with toxic, harmful or dust-raising substances?",
 ["Workers must wear suitable protective equipment, clothing or related safety gear","Workers must work in shorter spells and be rotated every two hours to cut exposure","Workers must stand upwind while the ship sprays water in the hold to damp dust","Workers must first pass a special health examination before handling such cargo"],
 "Article 67."),

(WH,"第67條之1",2,"碼頭裝卸-適用對象",
 "自營作業者於碼頭從事裝卸作業時，本標準如何適用？",
 ["自營作業者準用本標準有關雇主義務之規定","自營作業者準用本標準有關勞工義務之規定","自營作業者不適用本標準，另依商港法辦理","自營作業者僅適用本標準防護具章節之規定"],"a",
 "第67條之1第1項：自營作業者準用本標準有關雇主義務之規定。同條第2項並定受工作場所負責人指揮或監督從事勞動之人員，於碼頭從事裝卸作業，比照該事業單位之勞工，適用本標準之規定。",
 "How does this Standard apply to self-employed workers on the quay?",
 ["They are subject mutatis mutandis to the employer duties in this Standard","They are subject mutatis mutandis to the worker duties in this Standard","They are outside this Standard and fall under the Commercial Port Act","They are subject only to the protective equipment chapter of this Standard"],
 "Article 67-1, paragraph 1."),

(WH,"第67條之1",2,"碼頭裝卸-適用對象",
 "受工作場所負責人指揮或監督從事勞動之人員於碼頭裝卸時，如何適用本標準？",
 ["比照該事業單位之勞工，適用本標準之規定","比照自營作業者，準用雇主義務之相關規定","比照船方之工作者，僅適用扶梯章節之規定","比照承攬人之受僱人，另由承攬人負責辦理"],"a",
 "第67條之1第2項：受工作場所負責人指揮或監督從事勞動之人員，於碼頭從事裝卸作業，比照該事業單位之勞工，適用本標準之規定。同條第1項並定自營作業者準用有關雇主義務之規定。",
 "How does the Standard apply to people working under a site manager direction?",
 ["They are treated as workers of that undertaking and the Standard applies","They are treated as self-employed and the employer duties apply to them","They are treated as ship workers and only the ladder chapter applies here","They are treated as a contractor employee for whom the contractor answers"],
 "Article 67-1, paragraph 2."),

(WH,"第68條",1,"碼頭裝卸-施行日期",
 "碼頭裝卸安全衛生設施標準之施行日期為何？",
 ["本標準自發布日施行","本標準自公布日施行","本標準自發布後六個月施行","本標準自發布後一年施行之"],"a",
 "第68條：本標準自發布日施行。第1條並定明本標準依職業安全衛生法第六條第三項規定訂定之。",
 "When does this Standard take effect?",
 ["It takes effect on the day of promulgation","It takes effect on the day it is published","It takes effect six months after promulgation","It takes effect one year after promulgation"],
 "Article 68."),
]
