# -*- coding: utf-8 -*-
# 第 4 批（C）：危險性工作場所審查及檢查辦法（109/7/17）、製程安全評估定期實施辦法（109/7/17）
DW = "OSH-08"
PS = "OSH-32"
Q = [
# ---------- 危險性工作場所審查及檢查辦法 ----------
(DW,"第1條",1,"危工-法源",
 "危險性工作場所審查及檢查辦法係依何法規定訂定？",
 ["勞動檢查法第二十六條第二項","職業安全衛生法第十五條第三項","勞動檢查法第二十八條第一項","職業安全衛生法第六條第三項"],"a",
 "第1條：本辦法依勞動檢查法第二十六條第二項規定訂定之。",
 "The Regulations for Review and Inspection of Dangerous Workplaces are enacted under:",
 ["Labor Inspection Act Article 26(2)","OSH Act Article 15, paragraph 3","Labor Inspection Act Article 28(1)","OSH Act Article 6, paragraph 3"],
 "Article 1: under Article 26(2) of the Labor Inspection Act."),

(DW,"第2條",2,"危工-分類",
 "從事石油產品之裂解反應以製造石化基本原料之工作場所，屬何類危險性工作場所？",
 ["甲類","乙類","丙類","丁類"],"a",
 "第2條：甲類為石油裂解製造石化基本原料之工作場所，及製造處置使用危險物有害物達勞檢法施行細則附表一、二數量之工作場所。",
 "A workplace cracking petroleum products to make basic petrochemicals is which class of dangerous workplace?",
 ["Class A (甲)","Class B (乙)","Class C (丙)","Class D (丁)"],
 "Article 2: Class A covers petroleum cracking and workplaces handling dangerous or harmful substances above the threshold quantities."),

(DW,"第2條",2,"危工-分類",
 "使用異氰酸甲酯、氯化氫、氨、甲醛、過氧化氫或吡啶從事農藥原體合成之工作場所，屬何類？",
 ["乙類","甲類","丙類","丁類"],"a",
 "第2條第2款：乙類包括使用異氰酸甲酯、氯化氫、氨、甲醛、過氧化氫或吡啶從事農藥原體合成之工作場所；製造爆竹煙火類物品之工廠；以化學物質製造爆炸性物品之火藥類製造工作場所。",
 "A workplace synthesizing pesticide active ingredients using methyl isocyanate, hydrogen chloride, ammonia, formaldehyde, hydrogen peroxide or pyridine is:",
 ["Class B (乙)","Class A (甲)","Class C (丙)","Class D (丁)"],
 "Article 2(2): Class B also includes fireworks factories and explosives manufacturing workplaces."),

(DW,"第2條",3,"危工-分類",
 "丙類危險性工作場所指蒸汽鍋爐之傳熱面積在多少平方公尺以上，或高壓氣體類壓力容器一日冷凍能力在多少公噸以上者？",
 ["五百平方公尺；一百五十公噸","一百平方公尺；五十公噸","一千平方公尺；三百公噸","二百平方公尺；一百公噸"],"a",
 "第2條第3款：丙類指蒸汽鍋爐傳熱面積五百平方公尺以上，或高壓氣體類壓力容器一日冷凍能力一百五十公噸以上，或處理能力一千立方公尺以上之氧氣有毒性及可燃性高壓氣體、五千立方公尺以上之其他高壓氣體者。",
 "Class C dangerous workplaces have steam boilers with heating surface of at least, or HP gas pressure vessels with daily refrigeration capacity of at least:",
 ["500 m²; 150 tonnes","100 m²; 50 tonnes","1,000 m²; 300 tonnes","200 m²; 100 tonnes"],
 "Article 2(3): 500 m² heating surface, 150 tonnes/day refrigeration, or processing capacity of 1,000 m³ (oxygen, toxic, flammable gases) or 5,000 m³ (other gases)."),

(DW,"第2條",3,"危工-分類",
 "丙類危險性工作場所之高壓氣體處理能力，氧氣、有毒性及可燃性高壓氣體為多少立方公尺以上？其他高壓氣體為多少以上？",
 ["一千立方公尺；五千立方公尺","五百立方公尺；一千立方公尺","一百立方公尺；五百立方公尺","五千立方公尺；一萬立方公尺"],"a",
 "第2條第3款：一千立方公尺以上之氧氣、有毒性及可燃性高壓氣體；五千立方公尺以上之前款以外之高壓氣體。",
 "Class C processing capacity thresholds are how much for oxygen, toxic and flammable HP gases, and for other HP gases?",
 ["1,000 m³; 5,000 m³","500 m³; 1,000 m³","100 m³; 500 m³","5,000 m³; 10,000 m³"],
 "Article 2(3): 1,000 m³ for oxygen/toxic/flammable gases; 5,000 m³ for others."),

(DW,"第2條",2,"危工-分類",
 "建築物高度在幾公尺以上之建築工程，屬丁類危險性工作場所？",
 ["八十公尺","五十公尺","一百公尺","三十公尺"],"a",
 "第2條第4款：丁類營造工程包括建築物高度八十公尺以上、單跨橋墩跨距七十五公尺以上或多跨五十公尺以上之橋梁、壓氣施工、長度一千公尺以上或需開挖十五公尺以上豎坑之隧道、開挖深度十八公尺以上且面積五百平方公尺以上、模板支撐高度七公尺以上且面積三百三十平方公尺以上之工程。",
 "Building projects of at least what height are Class D dangerous workplaces?",
 ["80 m","50 m","100 m","30 m"],
 "Article 2(4): buildings 80 m+, bridges with spans 75 m+ (single) or 50 m+ (multi), compressed-air work, tunnels 1,000 m+ or shafts 15 m+, excavations 18 m+ deep and 500 m²+, formwork 7 m+ high and 330 m²+."),

(DW,"第2條",3,"危工-分類",
 "開挖深度達幾公尺以上且開挖面積達多少平方公尺以上之工程，屬丁類危險性工作場所？",
 ["十八公尺；五百平方公尺","十公尺；三百平方公尺","十五公尺；一千平方公尺","二十公尺；二百平方公尺"],"a",
 "第2條第4款第5目：開挖深度達十八公尺以上，且開挖面積達五百平方公尺以上之工程。",
 "Excavation works of at least what depth and area are Class D dangerous workplaces?",
 ["18 m; 500 m²","10 m; 300 m²","15 m; 1,000 m²","20 m; 200 m²"],
 "Article 2(4)(5): 18 m deep and 500 m² in area."),

(DW,"第2條",3,"危工-分類",
 "工程中模板支撐高度幾公尺以上且面積達多少平方公尺以上者，屬丁類危險性工作場所？",
 ["七公尺；三百三十平方公尺","五公尺；二百平方公尺","十公尺；五百平方公尺","三公尺；一百平方公尺"],"a",
 "第2條第4款第6目：工程中模板支撐高度七公尺以上，且面積達三百三十平方公尺以上者。",
 "Formwork shoring of at least what height and area makes a project a Class D dangerous workplace?",
 ["7 m; 330 m²","5 m; 200 m²","10 m; 500 m²","3 m; 100 m²"],
 "Article 2(4)(6): 7 m high and 330 m² in area."),

(DW,"第2條",3,"危工-分類",
 "長度幾公尺以上或需開挖幾公尺以上豎坑之隧道工程，屬丁類危險性工作場所？",
 ["一千公尺；十五公尺","五百公尺；十公尺","二千公尺；二十公尺","三百公尺；五公尺"],"a",
 "第2條第4款第4目：長度一千公尺以上或需開挖十五公尺以上豎坑之隧道工程。第3目：採用壓氣施工作業之工程。",
 "Tunnel projects of at least what length, or requiring shafts of at least what depth, are Class D?",
 ["1,000 m; 15 m","500 m; 10 m","2,000 m; 20 m","300 m; 5 m"],
 "Article 2(4)(4): 1,000 m long or 15 m shafts; compressed-air construction is also Class D."),

(DW,"第3條",2,"危工-定義",
 "危險性工作場所審查及檢查辦法所稱「審查」與「檢查」有何不同？",
 ["審查為勞檢機構對資料之書面審查；檢查為對資料及設施之現場檢查","審查為勞檢機構對設施之現場檢查；檢查為對資料之書面審查","審查與檢查均為事業單位自行辦理之書面查核，無須勞檢機構參與","審查為中央主管機關對資料之審查；檢查為地方主管機關之現場檢查"],"a",
 "第3條：審查指勞動檢查機構對工作場所有關資料之書面審查；檢查指勞動檢查機構對工作場所有關資料及設施之現場檢查；製程修改指既有安全防護措施未能控制新潛在危害之製程化學品技術設備操作程序或規模之變更。",
 "What is the difference between 'review' and 'inspection' under the Regulations?",
 ["Review is the agency's documentary review; inspection is its on-site check of documents and facilities","Review is the agency's on-site check of facilities; inspection is its documentary review of submitted data","Both are documentary checks carried out by the enterprise itself, with no involvement of the inspection agency","Review is done by the central competent authority; inspection is the on-site check made by the local authority"],
 "Article 3: review = document review; inspection = on-site inspection of documents and facilities; 'process modification' = changes existing safeguards cannot control."),

(DW,"第4條",2,"危工-申請",
 "事業單位應於甲類、丁類工作場所使勞工作業幾日前申請審查？乙類、丙類幾日前申請審查及檢查？",
 ["三十日前；四十五日前","十五日前；三十日前","六十日前；九十日前","七日前；十四日前"],"a",
 "第4條：甲類、丁類工作場所應於使勞工作業三十日前向當地勞動檢查機構申請審查；乙類、丙類應於四十五日前申請審查及檢查。",
 "Applications for review of Class A/D workplaces must be filed how many days before workers start, and for review and inspection of Class B/C?",
 ["30 days; 45 days","15 days; 30 days","60 days; 90 days","7 days; 14 days"],
 "Article 4: 30 days for Class A and D (review); 45 days for Class B and C (review and inspection)."),

(DW,"第5條",3,"危工-甲類",
 "申請審查甲類工作場所應檢附之資料為何？",
 ["安全衛生管理基本資料及製程安全評估定期實施辦法附表一至十四各三份，並登錄於指定資訊網站","施工計畫書及施工安全評估報告書各三份，並經專任工程人員及開業建築師簽章","環境影響評估報告書及消防安全設備檢查表各二份，並登錄於指定資訊網站","公司登記證明文件及工廠登記證影本各三份，並副知當地消防主管機關備查"],"a",
 "第5條：應填具申請書並檢附安全衛生管理基本資料（附件一）及製程安全評估定期實施辦法第4條附表一至十四各三份；申請應登錄於中央主管機關指定之資訊網站。",
 "What must accompany an application for review of a Class A workplace?",
 ["Basic OSH management data and Annexes 1–14 of the Periodic Process Safety Assessment Regulations, three copies each, registered online","The construction plan and construction safety assessment report, three copies each, signed by the full-time engineer and a licensed architect","An environmental impact assessment report and fire safety equipment checklists, two copies each, registered on the designated website","Company registration certificates and factory registration copies, three copies each, filed with the local fire authority for record"],
 "Article 5: application form, basic OSH management data (Attachment 1), and PSM Annexes 1–14, three copies, registered on the designated website."),

(DW,"第6條",2,"危工-評估小組",
 "甲類工作場所之評估小組應由哪些人員組成？",
 ["工作場所負責人、製程安全評估人員、職業安全衛生人員、作業主管、熟悉作業之勞工","雇主、董事長、財務主管、廠務經理、人力資源人員","外部安全顧問、環境工程技師、保險公司代表、消防設備師、政府特聘專家","勞動檢查員、地方主管機關代表、工會理事、職業醫學科醫師、勞工代表"],"a",
 "第6條：工作場所負責人、製程安全評估人員（受訓或具能力經認可）、依管理辦法設置之職業安全衛生人員、工作場所作業主管、熟悉該場所作業之勞工；未置評估人員者得以完成訓練之工業安全技師及化工／職業衛生／機械／電機技師之一任之；評估過程及結果應記錄。",
 "The assessment team for a Class A workplace consists of:",
 ["Workplace manager, process safety assessor, OSH personnel, operation supervisors and workers familiar with the operations","The employer, the chairman, the finance manager, the plant manager and the human resources staff","External safety consultants, environmental engineers, insurance representatives, fire equipment specialists and government experts","Labor inspectors, local competent authority delegates, union officers, occupational medicine physicians and worker representatives"],
 "Article 6: the five listed; without an accredited assessor, trained industrial safety engineers together with chemical/hygiene/mechanical/electrical engineers may serve; records required."),

(DW,"第6條",3,"危工-評估小組",
 "事業單位未置製程安全評估人員者，得以完成製程安全評估人員訓練之工業安全技師及下列何種技師之一任之？",
 ["化學工程、職業衛生、機械工程或電機工程技師","土木工程、結構工程、大地工程或水利工程技師","食品科學、環境工程、農業工程或礦業工程技師","冶金材料、造船工程、航空工程或核子工程技師"],"a",
 "第6條第2項：得以在國內完成製程安全評估人員訓練之工業安全技師及化學工程、職業衛生、機械工程、電機工程技師之一任之；兼具兩種資格者得為同一人。丁類則為工業安全技師及建築師土木結構大地水利技師之一。",
 "Without an accredited process safety assessor, a trained industrial safety engineer plus which other engineer may serve?",
 ["Chemical, occupational hygiene, mechanical or electrical engineer","Civil engineering, structural, geotechnical or hydraulic engineer","Food science, environmental, agricultural or mining engineer","Metallurgical, naval architecture, aeronautical or nuclear engineer"],
 "Article 6(2): chemical, hygiene, mechanical or electrical engineers (one person may hold both); Class D uses architects or civil/structural/geotechnical/hydraulic engineers."),

(DW,"第7條",2,"危工-審查",
 "檢查機構對甲類工作場所之審查結果，應於受理申請後幾日內以書面通知事業單位？",
 ["三十日內","十五日內","四十五日內","六十日內"],"a",
 "第7條：檢查機構依檢附資料實施審查並得就職業安全衛生設施及管理實施檢查；審查結果應於受理申請後三十日內書面通知，但可歸責於事業單位者不在此限。第11條、第15條：乙類丙類為四十五日內。第19條：丁類三十日內。",
 "The inspection agency must notify the enterprise in writing of the Class A review result within how many days of receipt?",
 ["30 days","15 days","45 days","60 days"],
 "Article 7: 30 days (unless attributable to the enterprise); Articles 11 and 15: 45 days for Class B and C; Article 19: 30 days for Class D."),

(DW,"第8條",2,"危工-重新評估",
 "經審查合格之甲類工作場所，應於何時重新評估檢附之資料並報請檢查機構備查？",
 ["製程修改時或至少每五年","製程修改時或至少每一年","製程修改時或至少每十年","僅於發生重大職業災害後"],"a",
 "第8條：應於製程修改時或至少每五年重新評估第5條檢附之資料，為必要之更新及記錄，並報請檢查機構備查；重新評估準用第6條。第12條、第16條：乙類丙類亦於製程修改或至少每五年重新評估。",
 "An approved Class A workplace must re-evaluate its submitted data:",
 ["On process modification or at least every five years, reporting to the inspection agency","On process modification or at least every year, reporting to the inspection agency","On process modification or at least every ten years, reporting to the central authority","Only after a major occupational accident, reporting to the local fire authority"],
 "Article 8: on process modification or at least every 5 years, updated, recorded and filed; Articles 12 and 16 apply the same to Class B and C."),

(DW,"第9條",3,"危工-乙類",
 "申請審查及檢查乙類工作場所應檢附之資料，不包括下列何者？",
 ["施工安全評估報告書","製程安全評估報告書","製程修改安全計畫","緊急應變計畫"],"a",
 "第9條：乙類應檢附安全衛生管理基本資料、製程安全評估報告書、製程修改安全計畫、緊急應變計畫、稽核管理計畫各三份。施工安全評估報告書為丁類（第17條）所需。",
 "Which is NOT required for a Class B workplace application?",
 ["Construction safety assessment report","Process safety assessment report","Process modification safety plan","Emergency response plan"],
 "Article 9: basic OSH data, process safety assessment report, process modification safety plan, emergency response plan and audit management plan; the construction safety report belongs to Class D."),

(DW,"第11條",3,"危工-乙類",
 "檢查機構對乙類工作場所審查後，應對何種設施實施檢查？",
 ["火災爆炸危害預防設施、有害物洩漏及中毒危害預防設施","蒸汽鍋爐設施、第一種壓力容器及冷凍設施","一般高壓氣體製造設施、液化石油氣製造設施","施工架組配設施、模板支撐及開挖擋土設施"],"a",
 "第11條：審查後應對火災爆炸危害預防設施（附件七）及有害物洩漏及中毒危害預防設施（附件八）實施檢查；結果於受理後四十五日內書面通知。",
 "After reviewing a Class B workplace, the inspection agency inspects which facilities?",
 ["Fire/explosion prevention facilities and harmful-substance leakage/poisoning prevention facilities","Steam boiler facilities and first-category pressure vessel and refrigeration facilities","General high-pressure gas production facilities and liquefied petroleum gas production facilities","Scaffold erection facilities and formwork shoring and excavation earth-retaining facilities"],
 "Article 11: fire and explosion prevention (Attachment 7) and leakage/poisoning prevention (Attachment 8); notice within 45 days."),

(DW,"第15條",3,"危工-丙類",
 "檢查機構對丙類工作場所審查後，應對下列何種設施實施檢查？",
 ["一般高壓氣體、液化石油氣、冷凍用高壓氣體、加氣站製造設施及鍋爐設施","火災爆炸、有害物洩漏、中毒危害預防設施及緊急應變控制設施","施工計畫書、施工安全評估報告書及專任工程人員簽章文件","模板支撐、施工架、擋土支撐及露天開挖等營造安全設施"],"a",
 "第15條：一般高壓氣體製造設施、液化石油氣製造設施、冷凍用高壓氣體製造設施、加氣站製造設施、鍋爐設施（附件九至十三）；結果於四十五日內書面通知。第13條：丙類申請檢附第9條各款資料。",
 "After reviewing a Class C workplace, the inspection agency inspects:",
 ["General HP gas, LPG, refrigeration HP gas, gas filling station production facilities and boiler facilities","Fire and explosion, harmful-substance leakage and poisoning prevention facilities and emergency control facilities","Construction plan, construction safety assessment report and the full-time engineer's signed documents","Formwork shoring, scaffolds, earth-retaining supports and open-cut excavation safety facilities"],
 "Article 15: the five facility types in Attachments 9–13; notice within 45 days."),

(DW,"第17條",3,"危工-丁類",
 "申請審查丁類工作場所應檢附何種資料？",
 ["施工安全評估人員及專任工程人員、執業技師或開業建築師之簽章文件，及施工計畫書、施工安全評估報告書各三份","製程安全評估報告書及製程修改安全計畫，經職業安全衛生人員簽章後，連同緊急應變計畫各三份","稽核管理計畫及安全衛生管理基本資料，經工作場所負責人簽章後，連同製程安全評估報告書各二份","製程修改安全計畫及環境影響評估報告書，經開業建築師簽章後，連同工廠登記證影本各三份"],"a",
 "第17條：應填具申請書並檢附施工安全評估人員及所僱專任工程人員、相關執業技師或開業建築師之簽章文件，及施工計畫書（附件十四）、施工安全評估報告書（附件十五）各三份；簽章以涉及專業技術部分為限；特殊狀況得報經同意分段申請審查。",
 "An application for review of a Class D workplace must include:",
 ["Signatures of the construction safety assessor and full-time engineer, licensed engineer or architect, plus the construction plan and construction safety assessment report in triplicate","A process safety assessment report and a process modification safety plan, signed by the OSH personnel, together with the emergency response plan, three copies of each document","An audit management plan and the basic occupational safety and health management data, signed by the workplace manager, together with the process safety assessment report, two copies each","A process modification safety plan and an environmental impact assessment report, signed by a licensed architect, together with a copy of the factory registration certificate, in triplicate"],
 "Article 17: signed documents, construction plan (Attachment 14) and construction safety assessment report (Attachment 15), three copies; phased review allowed for complex projects."),

(DW,"第18條",2,"危工-丁類",
 "丁類工作場所之評估小組，除工作場所負責人、施工安全評估人員、職業安全衛生人員外，尚包括何者？",
 ["專任工程人員、工作場所作業主管（含承攬人之人員）","熟悉作業之勞工、緊急應變小組成員（含醫護人員）","勞動檢查員、當地主管機關代表（含消防人員）","保險公司代表、建築師事務所人員（含監造人員）"],"a",
 "第18條：工作場所負責人、施工安全評估人員、專任工程人員、職業安全衛生人員、工作場所作業主管（含承攬人之人員）；未置評估人員者得以完成訓練之工業安全技師及建築師、土木、結構、大地、水利技師之一任之；評估過程及結果應記錄。",
 "Besides the workplace manager, construction safety assessor and OSH personnel, a Class D assessment team includes:",
 ["The full-time engineer and operation supervisors (including contractors' personnel)","Workers familiar with the operation and emergency response team members (including nurses)","Labor inspectors and local competent authority delegates (including fire officers)","Insurance representatives and architectural firm staff (including site supervisors)"],
 "Article 18: full-time engineer and operation supervisors including contractors'; alternative assessors are trained industrial safety engineers with an architect or civil/structural/geotechnical/hydraulic engineer."),

(DW,"第20條",2,"危工-丁類",
 "經審查合格之丁類工作場所，於施工過程中變更主要分項工程施工方法時，應如何？",
 ["就變更部分重新評估，採取預防措施，更新施工計畫書及施工安全評估報告書並記錄","就變更部分重新評估，採取預防措施後，報請勞動檢查機構重新審查合格始得施工","無須重新評估，僅需將變更情形口頭告知監造單位並登載於施工日誌","應立即停工三十日，並就變更部分重新申請丁類工作場所審查後始得復工"],"a",
 "第20條：變更主要分項工程施工方法時，應就變更部分重新評估後，就評估之危害採取必要預防措施，更新施工計畫書及施工安全評估報告書並記錄；重新評估準用第18條；施工方法變更情形如附件十六例示。",
 "When an approved Class D worksite changes the construction method of a major sub-work item, the enterprise shall:",
 ["Re-assess the change, take precautions, update the construction plan and safety assessment report, and record it","Re-assess the change, take precautions, and apply to the inspection agency for a fresh review before resuming work","No re-assessment is needed; simply inform the supervising firm verbally and note the change in the site diary","Stop work for thirty days and re-apply for Class D workplace review of the changed part before resuming work"],
 "Article 20: re-evaluate the changed part per Article 18, take preventive measures, update documents and record; Attachment 16 gives examples."),

(DW,"第22條",2,"危工-列席",
 "檢查機構實施危險性工作場所審查、檢查時，何人應列席說明？",
 ["製程安全評估小組、施工安全評估小組成員","公司股東會代表、董事會監察人成員","承辦銀行代表、產物保險公司查勘人員","當地消防機關人員、環境保護主管機關人員"],"a",
 "第22條：檢查機構實施審查檢查時，製程安全評估小組、施工安全評估小組成員應列席說明。第21條：得邀請專家學者協助。第23條：應摘要記錄過程及決議。第23條之1：爆竹煙火工廠應檢附製造許可文件影本。",
 "Who must attend and explain during the agency's review or inspection of a dangerous workplace?",
 ["Members of the process safety or construction safety assessment team","Representatives of the shareholders meeting and the board of supervisors","Representatives of the financing bank and the property insurance surveyors","Officers of the local fire authority and the environmental protection authority"],
 "Article 22: assessment team members; Article 21: experts may be invited; Article 23: proceedings summarized; Article 23-1: fireworks factories attach their manufacturing permit."),

# ---------- 製程安全評估定期實施辦法 ----------
(PS,"第1條",1,"製程安全-法源",
 "製程安全評估定期實施辦法係依職業安全衛生法第幾條規定訂定？",
 ["第十五條第三項","第六條第三項","第二十三條第五項","第三十二條第三項"],"a",
 "第1條：本辦法依職業安全衛生法第十五條第三項規定訂定之。",
 "The Regulations for Periodic Process Safety Assessment are enacted under which OSH Act article?",
 ["Article 15, paragraph 3","Article 6, paragraph 3","Article 23, paragraph 5","Article 32, paragraph 3"],
 "Article 1: under Article 15(3) of the OSH Act."),

(PS,"第2條",2,"製程安全-適用",
 "製程安全評估定期實施辦法適用於何種工作場所？",
 ["石油裂解製造石化基本原料之工作場所，及製造處置使用危險物有害物達勞檢法施行細則附表數量之工作場所","從事石油產品儲存及分裝之工作場所，及製造處置使用危險物達勞檢法施行細則附表數量之營造工程","使用異氰酸甲酯從事農藥原體合成之工作場所，及製造爆竹煙火類物品之工廠與火藥類製造工作場所","蒸汽鍋爐傳熱面積五百平方公尺以上之工作場所，及高壓氣體類壓力容器一日冷凍能力一百五十公噸以上者"],"a",
 "第2條：適用於勞檢法第26條第1項第1款石油裂解之石化工作場所，及第5款製造處置使用危險物及有害物達勞動檢查法施行細則附表一及附表二規定數量之工作場所。",
 "The Regulations apply to which workplaces?",
 ["Petroleum cracking petrochemical workplaces, and workplaces handling dangerous/harmful substances above the Labor Inspection Act Enforcement Rules' threshold quantities","Petroleum product storage and repackaging workplaces, and construction projects handling dangerous substances above the Labor Inspection Act Enforcement Rules' threshold quantities","Pesticide synthesis workplaces using methyl isocyanate, together with fireworks factories and explosives manufacturing workplaces of any production scale","Workplaces with steam boilers of at least 500 m² heating surface, and high-pressure gas pressure vessels with a daily refrigeration capacity of at least 150 tonnes"],
 "Article 2: the two workplace types under Labor Inspection Act Article 26(1)(1) and (5)."),

(PS,"第3條",2,"製程安全-定義",
 "製程安全評估定期實施辦法所稱「製程安全評估」係指何者？",
 ["利用結構化、系統化方式辨識、分析工作場所潛在危害而採取必要預防措施之評估","利用會計及統計方法分析事業單位財務風險而採取避險措施之評估","依環境影響評估法辨識開發行為對環境之影響而提出減輕對策之評估","依品質管理系統標準查核作業程序符合性而開立矯正措施之稽核"],"a",
 "第3條：製程安全評估指利用結構化、系統化方式，辨識、分析工作場所潛在危害，而採取必要預防措施之評估；製程修改指既有安全防護措施未能控制新潛在危害之製程化學品技術設備操作程序或規模之變更。",
 "'Process safety assessment' means:",
 ["A structured, systematic assessment to identify and analyze potential workplace hazards and take necessary precautions","An accounting and statistical assessment to identify and analyze an enterprise's financial risks and take hedging measures","A statutory assessment to identify and analyze the impact of a development project on the environment and propose mitigation measures","A systematic audit of conformity with quality management system standards that identifies non-conformities and issues corrective actions"],
 "Article 3: structured, systematic hazard identification and analysis with precautions; 'process modification' is a change existing safeguards cannot control."),

(PS,"第4條",2,"製程安全-週期",
 "適用製程安全評估定期實施辦法之工作場所，事業單位應每幾年實施製程安全評估？",
 ["五年","一年","三年","十年"],"a",
 "第4條：應每五年就製程安全資訊（附表一）及製程危害控制措施（附表二）實施製程安全評估，記錄過程及結果並製作評估報告及採取預防措施；製程修改時亦適用。",
 "Enterprises covered by the Regulations must conduct a process safety assessment every:",
 ["5 years","1 year","3 years","10 years"],
 "Article 4: every five years, covering process safety information and process hazard controls, with a report and precautions; also on process modification."),

(PS,"第4條",3,"製程安全-報告內容",
 "製程安全評估報告內容應包括下列何者？",
 ["勞工參與、標準作業程序、教育訓練、承攬管理、啟動前安全檢查、機械完整性、動火許可、變更管理、事故調查、緊急應變、符合性稽核、商業機密","勞工參與、標準作業程序、教育訓練、承攬管理、財務稽核、行銷計畫、人事考核、薪資結構、股東名冊、董事會決議、公司章程、營運計畫","環境影響說明書、空氣污染防制計畫、水污染防治措施、廢棄物清理計畫、土壤污染調查、噪音防制、溫室氣體盤查、環境監測、環保稽核、環境教育","財務報表、資產負債表、損益表、現金流量表、股東權益變動表、會計師查核意見、內部控制聲明、稅務申報、預算編列、成本分析、投資計畫、風險準備"],"a",
 "第4條第2項：評估報告包括評估過程文件及結果、勞工參與、標準作業程序、教育訓練、承攬管理、啟動前安全檢查、機械完整性、動火許可、變更管理、事故調查、緊急應變、符合性稽核、商業機密（附表三至十四）。",
 "A process safety assessment report must include:",
 ["Employee participation, SOPs, training, contractor management, pre-startup safety review, mechanical integrity, hot work permits, management of change, incident investigation, emergency response, compliance audits, trade secrets","Employee participation, SOPs, training, contractor management, financial audits, marketing plans, personnel appraisals, pay structures, shareholder registers, board resolutions, articles of association, business plans","Environmental impact statements, air pollution control plans, water pollution control measures, waste disposal plans, soil contamination surveys, noise control, greenhouse gas inventories, environmental monitoring, green audits, environmental education","Financial statements, balance sheets, income statements, cash flow statements, statements of changes in equity, auditor opinions, internal control declarations, tax filings, budgets, cost analyses, investment plans, risk reserves"],
 "Article 4(2): the twelve process safety management elements (Annexes 3–14) plus assessment documents and results."),

(PS,"第5條",2,"製程安全-方法",
 "製程安全評估應使用下列何種安全評估方法一種以上？",
 ["如果-結果分析、檢核表、危害及可操作性分析、失誤模式及影響分析、故障樹分析等","SWOT 分析、五力分析、損益平衡分析、投資報酬率分析、敏感度分析等","問卷調查法、腦力激盪法、魚骨圖分析、柏拉圖分析、管制圖分析等","作業環境測定、健康檢查分析、人因工程檢核、危害告知、職業病調查等"],"a",
 "第5條：如果-結果分析、檢核表、如果-結果分析／檢核表、危害及可操作性分析（HazOp）、失誤模式及影響分析（FMEA）、故障樹分析（FTA）、其他經中央主管機關認可具同等功能之方法，應使用一種以上。",
 "A process safety assessment must use at least one of which methods?",
 ["What-if, checklist, HAZOP, FMEA, fault tree analysis, etc.","SWOT, five forces, break-even, ROI, sensitivity analysis, etc.","Questionnaires, brainstorming, fishbone, Pareto chart analysis, etc.","Environmental monitoring, health exams, ergonomic checks, etc."],
 "Article 5: what-if, checklist, what-if/checklist, HAZOP, FMEA, FTA, or other approved equivalent methods."),

(PS,"第5條",3,"製程安全-方法",
 "下列何者不是製程安全評估定期實施辦法所列之安全評估方法？",
 ["魚骨圖分析","危害及可操作性分析","失誤模式及影響分析","故障樹分析"],"a",
 "第5條所列方法為如果-結果分析、檢核表、如果-結果分析／檢核表、危害及可操作性分析、失誤模式及影響分析、故障樹分析及其他經認可之同等方法；魚骨圖並未列入。",
 "Which is NOT a listed process safety assessment method?",
 ["Fishbone diagram analysis","Hazard and operability study","Failure mode and effects analysis","Fault tree analysis"],
 "Article 5 lists what-if, checklist, what-if/checklist, HAZOP, FMEA and FTA; the fishbone diagram is not listed."),

(PS,"第7條",2,"製程安全-小組",
 "製程安全評估應由哪些人員組成評估小組實施？",
 ["工作場所負責人、製程安全評估人員、職業安全衛生人員、作業主管、熟悉作業之勞工","外部安全顧問、環境工程技師、保險公司代表、消防設備師、政府特聘專家","雇主、董事長、財務主管、廠務經理、人力資源人員","工廠工程師、維修技術員、品保人員、採購人員、資訊人員"],"a",
 "第7條：工作場所負責人、製程安全評估人員（受訓或具能力經認可）、依管理辦法設置之職業安全衛生人員、工作場所作業主管、熟悉該場所作業之勞工；未置評估人員者得以完成訓練之工業安全技師及化工／職業衛生／機械／電機技師之一任之。",
 "The process safety assessment team consists of:",
 ["Workplace manager, process safety assessor, OSH personnel, operation supervisors and workers familiar with the operations","External safety consultants, environmental engineers, insurance representatives, fire equipment specialists and government experts","The employer, the chairman, the finance manager, the plant manager and the human resources staff","Plant engineers, maintenance technicians, quality assurance staff, purchasing staff and IT personnel"],
 "Article 7: the five listed; alternative assessors are trained industrial safety engineers with chemical/hygiene/mechanical/electrical engineers."),

(PS,"第8條",2,"製程安全-報備",
 "事業單位應於製程安全評估五年期間屆滿日或製程修改日之幾日前，填具報備書並檢附評估報告報請勞動檢查機構備查？",
 ["三十日前","十五日前","六十日前","七日前"],"a",
 "第8條：應於五年期間屆滿日之三十日前或製程修改日之三十日前，填具製程安全評估報備書（附表十五）並檢附評估報告報請勞動檢查機構備查；報告應登錄於指定資訊網站；評估過程資料得留存備查。第9條：內容不完備者得限期補正。",
 "The process safety assessment report must be filed with the labor inspection agency how many days before the five-year deadline or the process modification date?",
 ["30 days","15 days","60 days","7 days"],
 "Article 8: 30 days before, with the Annex 15 filing form, registered online; Article 9: incomplete reports may be ordered corrected."),

(PS,"第6條",3,"製程安全-起算",
 "每五年實施製程安全評估之期間，依下列何者起算？",
 ["完成評估報經勞動檢查機構備查之日、或施行前依危工辦法審查合格之日、或完成重新評估之日","事業單位設立登記之日、或工廠登記證核發之日、或營利事業登記證變更之日","廠房建造完工之日、或設備安裝試車完成之日、或取得使用執照之日","第一批產品出貨之日、或勞工開始作業之日、或投保勞工保險之日"],"a",
 "第6條：自依本辦法完成製程安全評估並報經勞動檢查機構備查之日、本辦法施行前依危險性工作場所審查及檢查辦法審查合格取得合格之日、或施行前完成製程安全重新評估之日起算。",
 "The five-year assessment period is counted from:",
 ["The date of filing the completed assessment, or the pre-existing dangerous-workplace approval date, or the date of the last re-assessment","The date of the company's incorporation registration, or the date the factory registration was issued, or the date of a business registration change","The date the plant was completed, or the date equipment installation and commissioning finished, or the date the use permit was obtained","The date of the first product shipment, or the date workers began operations, or the date labor insurance coverage started"],
 "Article 6: from filing of the completed assessment, or from prior approval or re-assessment under the dangerous workplace regulations."),

(PS,"第10條",2,"製程安全-檢討",
 "事業單位發生下列何種情事時，應檢討並修正製程安全評估報告後留存備查？",
 ["職安法第37條第2項之職業災害、火災、爆炸、有害氣體洩漏或其他製程風險情形","勞工大量離職、勞資爭議調解、工會改組或其他人力資源管理情形","公司股價下跌、營業額衰退、財務報表虧損或其他營運風險情形","更換原料供應商、變更產品包裝、調整輪班表或其他日常作業管理情形"],"a",
 "第10條：發生職安法第37條第2項之職業災害、火災、爆炸、有害氣體洩漏、其他認有製程風險之情形時，應檢討並修正評估報告後留存備查；勞動檢查機構得請說明並邀請專家學者建議。",
 "The process safety assessment report must be reviewed and revised after:",
 ["Reportable occupational accidents under OSH Act Article 37(2), fires, explosions, harmful gas leaks or other process risk events","Mass resignations of workers, labor dispute mediation, union reorganization or other human resource management events","A fall in the company's share price, declining turnover, losses in the financial statements or other business risk events","Changing raw material suppliers, altering product packaging, adjusting shift rosters or other routine operational events"],
 "Article 10: after reportable accidents, fires, explosions, gas leaks or other process risks; the agency may request explanations and expert advice."),

(PS,"第11條",3,"製程安全-施行",
 "製程安全評估定期實施辦法自何時施行？",
 ["中華民國一百零四年一月一日","中華民國一百零三年七月三日","中華民國一百零九年七月十七日","中華民國一百一十年一月一日"],"a",
 "第11條：本辦法自中華民國一百零四年一月一日施行；修正條文自發布日施行（最近修正 109 年 7 月 17 日）。",
 "The Regulations for Periodic Process Safety Assessment took effect on:",
 ["1 January 2015 (ROC 104)","3 July 2014 (ROC 103)","17 July 2020 (ROC 109)","1 January 2021 (ROC 110)"],
 "Article 11: effective 1 January ROC 104 (2015); amendments effective on promulgation, most recently 17 July 2020."),
]
