# -*- coding: utf-8 -*-
# 第 12 批（A4）：ENV-108 半導體製造業空氣污染管制及排放標準、
#                ENV-110 光電材料及元件製造業空氣污染管制及排放標準、
#                ENV-111 汽車製造業表面塗裝作業空氣污染物排放標準
K = "ENV-108"
L = "ENV-110"
M = "ENV-111"
Q = [

# ===== ENV-108 半導體製造業空氣污染管制及排放標準（8 條）=====
(K,"第1條",1,"半導體空污-授權",
 "半導體製造業空氣污染管制及排放標準係依何規定訂定？",
 ["空氣污染防制法第二十條第二項及第二十三條第二項","空氣污染防制法第二十一條第二項及第二十二條第一項","空氣污染防制法第二十四條第三項及第二十七條第二項","空氣污染防制法第二十八條第二項及第三十一條第三項"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項及第二十三條第二項規定訂定之。第20條為排放標準之授權，第23條則為空氣污染物收集及防制設施管理之授權。",
 "Under which provisions is the semiconductor industry standard issued?",
 ["Articles 20-2 and 23-2 of the Air Pollution Control Act","Articles 21-2 and 22-1 of the Air Pollution Control Act","Articles 24-3 and 27-2 of the Air Pollution Control Act","Articles 28-2 and 31-3 of the Air Pollution Control Act"],
 "Article 1: issued under Articles 20-2 and 23-2 of the APCA."),

(K,"第2條",2,"半導體空污-行業定義",
 "本標準所稱半導體製造業，指從事下列何種作業者？",
 ["積體電路晶圓製造、晶圓封裝、磊晶、光罩製造、導線架製造等作業","印刷電路板製造、電子零組件組裝、面板模組貼合等下游作業","太陽能電池模組製造、發光二極體封裝及光纖纜線拉製等作業","電子產品維修、廢電子物品回收拆解及貴金屬提煉等作業"],"a",
 "第2條第1款：半導體製造業指從事積體電路晶圓製造、晶圓封裝、磊晶、光罩製造、導線架製造等作業者。第2款、第3款並就晶圓製造與晶圓封裝作業之製程內容分別定義。",
 "What operations define the semiconductor manufacturing industry here?",
 ["Wafer fabrication, wafer packaging, epitaxy, photomask making and lead frame making","Printed circuit board making, component assembly and panel module bonding downstream","Solar cell module making, LED packaging and optical fibre cable drawing operations","Electronics repair, waste electronics dismantling and precious metal recovery work"],
 "Article 2(1) lists the covered semiconductor operations."),

(K,"第2條",3,"半導體空污-揮發性有機物",
 "本標準所稱揮發性有機物之定義為何？",
 ["一大氣壓下初始沸點在攝氏二百五十度以下之有機化合物總稱，但不包括甲烷、一氧化碳、二氧化碳、二硫化碳、碳酸鹽、氰化物等","一大氣壓下初始沸點在攝氏一百度以下之有機化合物總稱，但不包括甲醇、乙醇、丙酮及異丙醇等常用清洗溶劑","一大氣壓下蒸氣壓大於零點五毫米汞柱之有機化合物總稱，但不包括含氯及含氟之各類鹵化有機化合物","一大氣壓下初始沸點在攝氏二百五十度以上之有機化合物總稱，但不包括光阻劑及顯影液所含之各類成分"],"a",
 "第2條第6款：揮發性有機物指在一大氣壓下，測量所得初始沸點在攝氏二百五十度以下有機化合物之空氣污染物總稱；但不包括甲烷、一氧化碳、二氧化碳、二硫化碳、碳酸、碳酸鹽、碳酸銨、氰化物及硫氰化物等化合物。",
 "How are volatile organic compounds defined in this standard?",
 ["Organic compounds with an initial boiling point of 250 degrees C or below at one atmosphere, excluding methane, CO, CO2, CS2, carbonates and cyanides","Organic compounds with an initial boiling point of 100 degrees C or below at one atmosphere, excluding methanol, ethanol, acetone and isopropanol","Organic compounds with a vapour pressure above 0.5 mm Hg at one atmosphere, excluding all chlorinated and fluorinated halogenated organics","Organic compounds with an initial boiling point above 250 degrees C at one atmosphere, excluding all photoresist and developer constituents"],
 "Article 2(6): boiling point of 250 degrees C or below, with listed exclusions."),

(K,"第2條",3,"半導體空污-排放削減率",
 "本標準所稱排放削減率及每季有效監測率之定義為何？",
 ["排放削減率指污染物經防制設備處理後之排放量削減百分比，依同步監測前後端濃度及排放量計算；有效監測率為扣除失效小時數後之操作小時數比率","排放削減率指防制設備設計去除效率之保證值，由設備廠商出具證明；有效監測率為監測設施每季實際運轉時數占全年時數之比率","排放削減率指原（物）料減量使用之百分比，以年度用量差額計算；有效監測率為監測數據經人工判讀後認定為有效者之比率","排放削減率指排放濃度低於排放標準之百分比，以檢測值與標準值相除計算；有效監測率為每季完成比測次數占應比測次數之比率"],"a",
 "第2條第8款、第13款：排放削減率指空氣污染物經污染防制設備處理後之排放量削減百分比，依同步監測或檢測污染防制設備前端及後端廢氣濃度及排放量進行計算；每季有效監測率＝（每季污染源操作小時數－每季操作期間流量計或濃度監測器失效小時數）／每季污染源操作小時數。",
 "How are the emission reduction rate and quarterly valid monitoring rate defined?",
 ["Reduction is the percentage cut in emissions after control from simultaneous inlet and outlet data; validity is operating hours less failed hours","Reduction is the guaranteed design removal efficiency certified by the equipment maker; validity is quarterly running hours over annual total hours","Reduction is the percentage cut in raw material use, from the annual usage difference; validity is the share of data judged valid by manual review","Reduction is how far the measured concentration falls below the limit; validity is completed comparison tests over required comparison tests"],
 "Article 2(8) and (13) define both terms."),

(K,"第2條",2,"半導體空污-新舊製程",
 "本標準所稱既存製程與新設製程之區分為何？",
 ["既存製程指發布施行日前已建造完成、建造中或已訂立工程施作契約者；新設製程指發布施行日起設立者及符合許可證變更條件者","既存製程指已取得操作許可證滿三年之製程；新設製程指尚未取得操作許可證而正在申請設置許可之各項半導體製程","既存製程指本標準發布施行日前已完成環境影響評估者；新設製程指發布施行日起始送審環境影響說明書之各項製程","既存製程指產能未達每月一萬片晶圓之製程；新設製程指產能達每月一萬片晶圓以上並經中央主管機關公告列管者"],"a",
 "第2條第9款、第10款：既存製程指本標準發布施行日前已建造完成、建造中、已完成工程招標程序或未經招標程序已訂立工程施作契約之半導體製造業製程；新設製程指本標準發布施行日起設立之半導體製程，及既存半導體製程符合固定污染源設置操作及燃料使用許可證管理辦法規定之變更條件者。",
 "How are existing and new processes distinguished in this standard?",
 ["Existing means completed, building, tendered or contracted before promulgation; new means set up from promulgation or meeting permit change conditions","Existing means holding an operating permit for three years; new means not yet holding an operating permit and still applying for installation approval","Existing means having completed environmental impact assessment before promulgation; new means submitting an EIA statement only from promulgation onward","Existing means capacity below ten thousand wafers a month; new means capacity of ten thousand wafers or more and designated by the central authority"],
 "Article 2(9)-(10) define existing and new processes."),

(K,"第3條",2,"半導體空污-適用範圍",
 "本標準對於半導體製造業原（物）料年用量較小者，有何規定？",
 ["原（物）料年用量小於本標準表列數量者，該項物質不適用本標準之規定","原（物）料年用量小於本標準表列數量者，仍應全部適用本標準之規定","原（物）料年用量小於本標準表列數量者，應改適用固定污染源一般排放標準之二倍值","原（物）料年用量小於本標準表列數量者，得由公私場所自行決定是否適用本標準"],"a",
 "第3條：本標準適用於半導體製造業；但半導體製造業原（物）料年用量小於該條表列數量者，該項物質不適用本標準之規定。此為以年用量門檻劃定管制對象之設計。",
 "How does the standard treat raw materials used below the listed annual quantity?",
 ["Where annual use is below the listed quantity, that substance is not subject to this standard","Where annual use is below the listed quantity, the standard still applies in full to it","Where annual use is below the listed quantity, twice the general emission standard applies","Where annual use is below the listed quantity, the premises may decide whether it applies"],
 "Article 3: below-threshold substances fall outside the standard."),

(K,"第4條",3,"半導體空污-收集與替代",
 "半導體製造業產生之空氣污染物應如何處理？酸性廢氣無法證明符合標準時得如何辦理？",
 ["應經密閉集氣系統收集並符合表列標準後始得排放；酸性廢氣因安全之虞無法證明符合者，得檢具證明文件申請替代認可","得以自然通風方式逸散排放；酸性廢氣因安全之虞無法證明符合者，得逕行免除排放標準之適用而不需申請認可","應經密閉集氣系統收集但無須符合任何排放標準；酸性廢氣應一律改以焚化方式處理後始得排放至大氣中","應經密閉集氣系統收集並符合表列標準；酸性廢氣無法符合者應立即停止製程操作，不得申請任何替代方案"],"a",
 "第4條：半導體製造業產生之空氣污染物應經密閉集氣系統收集，並符合該條表列規定後始得排放；硝酸、鹽酸、磷酸、氫氟酸及硫酸等排放之廢氣，因安全之虞而無法證明符合前項標準時，應檢具相關證明文件佐證具備同等處理效果或較優之控制條件，向直轄市、縣（市）主管機關申請替代認可。",
 "How must emissions be handled, and what if acid gases cannot be shown compliant?",
 ["Collect by closed capture and meet the listed limits before release; acid gases unprovable for safety may seek an equivalent alternative","Natural ventilation release is allowed; acid gases unprovable for safety reasons are simply exempt with no application needed at all","Closed capture is required but no emission limit applies; acid gases must always be incinerated before being released to the air","Closed capture and the listed limits apply; acid gases that cannot comply require an immediate halt with no alternative available"],
 "Article 4: closed capture plus an alternative approval route for acid gases."),

(K,"第5條",3,"半導體空污-監測設施",
 "半導體製造業設置流量計及揮發性有機物濃度監測器之規定為何？",
 ["均應設置流量計；VOC 原料年用量大於二十五噸或總排放量大於每小時零點六公斤，且既存製程大於十四ppm或新設製程大於十ppm之管道應設濃度監測器","均應設置濃度監測器；流量計僅於 VOC 原料年用量大於五十噸或工廠總排放量大於每小時二公斤，且排放濃度大於二十ppm之管道始需設置","流量計及濃度監測器均由公私場所視實際需要自行決定是否設置；主管機關不得要求其設置，亦不得要求提出替代監測方案","均應同時設置流量計及濃度監測器，不論原料年用量多寡或排放濃度高低，且一律不得提出任何替代監測方案"],"a",
 "第5條第1項第1款、第2款：適用本標準之半導體製造業均應設置流量計；揮發性有機物原（物）料年用量大於二十五噸或工廠總排放量大於每小時零點六公斤者，屬既存製程其 VOC 排放大於十四ppm、或屬新設製程其排放大於十ppm 之排放管道，應設置濃度監測器證明符合排放削減率；既存與新設合併設置管道者以新設製程規定認定。",
 "What rules govern flow meters and VOC concentration monitors?",
 ["All plants need flow meters; monitors where VOC use exceeds 25 t or plant emissions exceed 0.6 kg/hr and stacks exceed 14 ppm existing or 10 ppm new","All plants need monitors; flow meters only where VOC use exceeds 50 t or plant emissions exceed 2 kg/hr and stack concentration exceeds 20 ppm","Both flow meters and monitors are optional at the discretion of the premises; the authority may not require them or any alternative","All covered plants need both flow meters and monitors regardless of usage or concentration, and no alternative may be proposed"],
 "Article 5, Paragraph 1(1)-(2) sets the installation thresholds."),

(K,"第5條",3,"半導體空污-比測校正",
 "流量計及濃度監測器之有效監測率、比測規定及替代方案為何？",
 ["有效每季監測率應大於八十％，每年至少以標準檢測方法比測一次且每次至少二小時，結果應以上次比測結果修正；未能設置者得提替代方案報請同意","有效每季監測率應大於九十五％，每半年至少比測一次且每次至少四小時，結果無須修正；未能設置者一律不得排放廢氣","有效每季監測率應大於六十％，每三年至少比測一次且每次至少一小時，結果應以設計值修正；未能設置者得逕行免除監測義務","有效每季監測率應大於八十％，每年至少比測四次且每次至少八小時，結果應以最大值修正；未能設置者應改採人工每日檢測"],"a",
 "第5條第1項第3款及第2項：流量計及濃度監測器之有效每季監測率應大於八十％，每年至少以標準檢測方法比測一次，比測時間每次至少二小時，所得結果應以上次比測結果修正之；未能依規定設置者，公私場所得提出其他可證明排放符合第4條標準之替代方案，報請直轄市、縣（市）主管機關同意。",
 "What validity, comparison testing and alternative rules apply to the monitors?",
 ["Quarterly validity above 80%, at least one two-hour comparison test a year, results corrected by the last comparison; alternatives may be approved","Quarterly validity above 95%, a four-hour comparison test every six months, no correction needed; without monitors no emission is permitted","Quarterly validity above 60%, a one-hour comparison test every three years, corrected by design values; monitoring may simply be waived","Quarterly validity above 80%, four eight-hour comparison tests a year, corrected by the maximum value; otherwise daily manual testing applies"],
 "Article 5: 80% validity, annual two-hour comparison, alternative on approval."),

(K,"第6條",3,"半導體空污-紀錄項目",
 "半導體製造業就污染防制設備之紀錄規定，下列敘述何者正確？",
 ["酸鹼洗滌吸收設施應每日記錄各洗滌槽循環水量及pH值；冷凝器應每月記錄冷凝液量並每日記錄出口溫度；熱焚化爐應每日記錄燃燒溫度","酸鹼洗滌吸收設施應每月記錄循環水量及pH值；冷凝器應每季記錄冷凝液量及出口溫度；熱焚化爐應每年記錄燃燒溫度一次","酸鹼洗滌吸收設施僅需記錄保養維護事項而免記錄水質；冷凝器及熱焚化爐之操作參數均由業者自行決定是否記錄","酸鹼洗滌吸收設施應每日記錄廢水排放流量；冷凝器應每日記錄冷凝劑進口溫度；熱焚化爐應每日記錄氣體滯留時間"],"a",
 "第6條第2款、第4款、第6款：酸鹼洗滌吸收設施應記錄保養維護事項並每日記錄各洗滌槽洗滌循環水量及pH值；冷凝器應每月記錄冷凝液量及每日記錄冷凝器出口溫度；熱焚化爐應每日記錄燃燒溫度。清水洗滌設施則每日記錄循環水量及廢水排放流量。",
 "Which statement on control equipment recording requirements is correct?",
 ["Acid-alkali scrubbers record water and pH daily; condensers record condensate monthly and outlet temperature daily; thermal oxidisers record temperature daily","Acid-alkali scrubbers record water and pH monthly; condensers record condensate and outlet temperature quarterly; thermal oxidisers record temperature yearly","Acid-alkali scrubbers record only maintenance and no water quality; condenser and oxidiser parameters are recorded at the discretion of the operator","Acid-alkali scrubbers record wastewater discharge daily; condensers record coolant inlet temperature daily; thermal oxidisers record residence time daily"],
 "Article 6(2), (4) and (6) set these recording frequencies."),

(K,"第6條",2,"半導體空污-觸媒生物",
 "污染防制設備為觸媒焚化爐或生物處理設施者，其紀錄規定為何？",
 ["觸媒焚化爐應記錄觸媒種類及更換日期並每日記錄進出口氣體溫度；生物處理設施應每日記錄風量、進口溫度及出口相對濕度","觸媒焚化爐應每月記錄觸媒種類及觸媒床更換日期而免記錄溫度；生物處理設施應每季記錄處理氣體風量及進口溫度即可","觸媒焚化爐應每日記錄燃燒室滯留時間及排氣含氧量；生物處理設施應每日記錄菌種數量、營養鹽添加量及出口濁度","觸媒焚化爐應每年記錄觸媒床壓損及觸媒更換次數；生物處理設施應每年記錄填充材種類、更換頻率及處理水量"],"a",
 "第6條第5款、第7款：污染防制設備為生物處理設施者，應記錄保養維護事項以確保設施狀態適合生物生長代謝，並每日記錄處理氣體風量、進口溫度及出口相對濕度；為觸媒焚化爐者，應記錄觸媒種類、觸媒床更換日期，並每日記錄觸媒床進、出口氣體溫度。",
 "What recording applies to catalytic oxidisers and biological treatment units?",
 ["Catalytic units record catalyst type and change dates plus daily inlet and outlet temperatures; biological units record flow, inlet temperature and humidity","Catalytic units record catalyst type and change dates monthly with no temperature record; biological units record flow and inlet temperature quarterly","Catalytic units record chamber residence time and oxygen daily; biological units record daily strain counts, nutrient dosing and outlet turbidity","Catalytic units record bed pressure drop and change counts yearly; biological units record packing type, change frequency and treated water yearly"],
 "Article 6(5) and (7) set these requirements."),

(K,"第6條",3,"半導體空污-申報保存",
 "半導體製造業依規定作成之各項紀錄，其保存及申報規定為何？",
 ["應以電子化方式保存備查至少六年，並依中央主管機關規定格式於每年一、四、七、十月月底前申報上一季紀錄","應以書面方式保存備查至少二年，並依中央主管機關規定格式於每年一月月底前申報上一年度之全部紀錄","應以電子化方式保存備查至少三年，並僅於主管機關稽查時提供，無須定期主動向主管機關申報","應以電子化方式保存備查至少十年，並於每月十五日前申報上一月份紀錄，主管機關不得調整頻率"],"a",
 "第6條第10款：前九款之紀錄需以電子化方式保存備查至少六年，並依中央主管機關規定之格式於每年一、四、七、十月月底前向當地主管機關申報上一季之紀錄；主管機關得適時調整申報內容及頻率。",
 "How must the records be retained and reported?",
 ["Kept electronically for at least six years and reported quarterly by the end of January, April, July and October in the prescribed format","Kept on paper for at least two years and reported once by the end of January each year covering the whole previous year","Kept electronically for at least three years and produced only during inspections, with no periodic reporting obligation","Kept electronically for at least ten years and reported by the fifteenth of each month, with the frequency fixed and unchangeable"],
 "Article 6(10): six-year electronic retention and quarterly reporting."),

(K,"第7條",3,"半導體空污-改善計畫",
 "既存製程未能符合排放標準或監測設施設置規定者，應如何申請改善期限？",
 ["應於本標準修正施行後六個月內檢具空氣污染改善計畫向地方主管機關申請核定改善期限，改善期限不得逾十八個月","應於本標準修正施行後二年內檢具空氣污染改善計畫向中央主管機關申請核定改善期限，改善期限不得逾三十六個月","應於本標準修正施行後三個月內向地方主管機關報備即可自行決定改善期限，主管機關不得核定期限長短","應於本標準修正施行後六個月內停止該製程操作，並俟完成改善並經檢測合格後始得重新申請操作許可證"],"a",
 "第7條第1項、第2項：既存製程未能符合第4條排放標準或第5條設置規定者，應於本標準修正施行後六個月內，檢具空氣污染改善計畫向直轄市、縣（市）主管機關申請核定改善期限；改善計畫至少應包含製程原（物）料、設施或防制設備改善種類、構造、效能、流程、設計圖說、設置經費及進度，改善期限不得逾十八個月。",
 "How may an existing process obtain an improvement deadline?",
 ["File an air pollution improvement plan with the local authority within six months of the amendment; the deadline may not exceed eighteen months","File an improvement plan with the central authority within two years of the amendment; the deadline may not exceed thirty-six months","Simply notify the local authority within three months and set its own deadline, which the authority may not determine","Halt the process within six months of the amendment and reapply for an operating permit only after passing testing"],
 "Article 7: six-month filing, eighteen-month improvement cap."),

(K,"第7條",2,"半導體空污-展延",
 "既存製程未能於核定改善期限內完成改善者，其展延規定為何？",
 ["得於期限屆滿前一至三個月內檢具展延說明、規劃及變更改善計畫申請展延，展延之改善期限不得逾十二個月","得於期限屆滿後一個月內檢具展延說明申請展延，展延之改善期限不得逾二十四個月且次數不受限制","得於期限屆滿前六個月內向中央主管機關申請展延，展延之改善期限不得逾六個月且以一次為限","不得申請任何展延，未能於核定期限內完成改善者應即停止製程操作並廢止其操作許可證"],"a",
 "第7條第3項：未能於第1項核定改善期限內完成改善者，公私場所得於期限屆滿前一至三個月內，檢具展延說明、規劃及變更改善計畫，向直轄市、縣（市）主管機關申請核准展延改善期限，展延之改善期限不得逾十二個月；但展延改善經地方主管機關另予核准改善期限者，不在此限。",
 "What extension rules apply when the improvement deadline cannot be met?",
 ["Apply one to three months before expiry with an extension explanation, plan and amended programme; the extension may not exceed twelve months","Apply within one month after expiry with an extension explanation; the extension may not exceed twenty-four months and repeats are unlimited","Apply to the central authority within six months before expiry; the extension may not exceed six months and only once","No extension is available; failure to finish within the approved period means halting the process and revoking the permit"],
 "Article 7, Paragraph 3: one to three months before expiry, twelve-month cap."),

(K,"第8條",1,"半導體空污-施行",
 "半導體製造業空氣污染管制及排放標準之施行日期為何？",
 ["本標準自發布日起施行","本標準自發布後六個月施行","本標準自發布後十八個月施行","本標準另定施行日期公告之"],"a",
 "第8條：本標準自發布日施行。既存製程之緩衝則另依第7條規定，以核定改善期限方式處理，改善期限不得逾十八個月。",
 "When does the semiconductor industry standard take effect?",
 ["On the date of promulgation","Six months after promulgation","Eighteen months after promulgation","On a separately announced date"],
 "Article 8: effective upon promulgation."),

# ===== ENV-110 光電材料及元件製造業空氣污染管制及排放標準（10 條）=====
(L,"第1條",1,"光電業空污-授權",
 "光電材料及元件製造業空氣污染管制及排放標準係依何規定訂定？",
 ["空氣污染防制法第二十條第二項、第二十一條、第二十二條第一項第二項及第二十三條第二項","空氣污染防制法第十四條第一項、第十六條第二項、第十八條第三項及第十九條第一項","空氣污染防制法第二十四條第三項、第二十七條第二項、第二十八條第一項及第三十條第二項","空氣污染防制法第三十二條第一項、第三十四條第二項、第三十六條第三項及第四十條第一項"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項、第二十一條、第二十二條第一項、第二項、第二十三條第二項規定訂定之，涵蓋排放標準、排放量申報、監測與檢測及防制設施管理等授權。",
 "Under which provisions is the optoelectronics industry standard issued?",
 ["Articles 20-2, 21, 22-1, 22-2 and 23-2 of the Air Pollution Control Act","Articles 14-1, 16-2, 18-3 and 19-1 of the Air Pollution Control Act","Articles 24-3, 27-2, 28-1 and 30-2 of the Air Pollution Control Act","Articles 32-1, 34-2, 36-3 and 40-1 of the Air Pollution Control Act"],
 "Article 1 cites Articles 20, 21, 22 and 23 of the APCA."),

(L,"第2條",2,"光電業空污-行業定義",
 "本標準所稱光電材料及元件製造業之定義及例外為何？",
 ["指從事液晶面板製造及其相關材料、元件或產品製造者；但僅從事二極體元件製造者不在此限","指從事所有光學鏡片、照明燈具及太陽能板製造者；但兼營液晶面板製造者不在此限","指從事積體電路晶圓製造及封裝作業者；但僅從事液晶面板模組組裝者不在此限","指從事光纖纜線、光碟片及影像感測器製造者；但年營業額未達一億元者不在此限"],"a",
 "第2條第1款：光電材料及元件製造業指從事液晶面板製造及其相關材料、元件或產品製造者；但僅從事二極體元件製造者不在此限。第3條並定明管制項目為揮發性有機物、氫氟酸及鹽酸。",
 "How is the optoelectronic materials and components industry defined?",
 ["Making LCD panels and their related materials, components or products; those making only diode components are excluded","Making all optical lenses, lighting fixtures and solar panels; those also making LCD panels are excluded","Wafer fabrication and packaging of integrated circuits; those doing only LCD module assembly are excluded","Making optical fibre cable, optical discs and image sensors; those with turnover under one hundred million are excluded"],
 "Article 2(1): LCD panel related manufacturing, excluding diode-only makers."),

(L,"第2條",3,"光電業空污-處理效率",
 "本標準所稱污染防制設備處理效率之計算方式為何？",
 ["處理效率＝（E－E0）／E×100％；E 為進入防制設備前之單位小時排放量，E0 為經防制設備後逕排大氣之單位小時排放量","處理效率＝（E0－E）／E0×100％；E 為經防制設備後逕排大氣之排放量，E0 為進入防制設備前之排放量","處理效率＝E0／E×100％；E 為排放標準值，E0 為實際檢測所得之單位小時管道排放量","處理效率＝（E－E0）／E0×100％；E 為年許可排放總量，E0 為依核定年操作時數換算之單位小時排放量"],"a",
 "第2條第6款：處理效率指空氣污染物經污染防制設備處理後之排放量削減百分比，依同步檢測防制設備前端及後端廢氣濃度及排放量計算，公式為處理效率＝（E－E0）／E×100％；E 為經密閉排氣系統進入防制設備前之單位小時排放量，E0 為經防制設備後逕排大氣之單位小時排放量。",
 "How is control equipment treatment efficiency calculated?",
 ["Efficiency = (E − E0) / E x 100%, where E is the rate entering the control device and E0 the rate released after it","Efficiency = (E0 − E) / E0 x 100%, where E is the rate released after the device and E0 the rate entering it","Efficiency = E0 / E x 100%, where E is the emission limit value and E0 the measured hourly stack emission rate","Efficiency = (E − E0) / E0 x 100%, where E is the permitted annual total and E0 the hourly rate converted from it"],
 "Article 2(6): efficiency = (E − E0) / E x 100%."),

(L,"第3條",2,"光電業空污-適用範圍",
 "本標準之適用範圍及管制空氣污染物項目為何？",
 ["適用於光電業之煙道排氣，管制項目為揮發性有機物、氫氟酸及鹽酸","適用於光電業之周界逸散排放，管制項目為揮發性有機物、氨及硫酸","適用於光電業之全部作業場所，管制項目為粒狀污染物、氮氧化物及硫氧化物","適用於光電業之廢水處理設施，管制項目為揮發性有機物、硝酸及磷酸"],"a",
 "第3條：本標準適用於光電業之煙道排氣，管制空氣污染物項目為揮發性有機物、氫氟酸及鹽酸。第4條並就此三項污染物分別訂定處理效率或管道排放量之排放標準。",
 "What is the scope and which pollutants are controlled?",
 ["Stack gas of the optoelectronics industry; VOCs, hydrofluoric acid and hydrochloric acid","Fence-line fugitive emissions of the industry; VOCs, ammonia and sulphuric acid","All work areas of the industry; particulates, nitrogen oxides and sulphur oxides","Wastewater treatment facilities of the industry; VOCs, nitric acid and phosphoric acid"],
 "Article 3: stack gas, VOCs, HF and HCl."),

(L,"第4條",3,"光電業空污-排放標準",
 "光電業揮發性有機物之排放標準，依新設及既存製程如何規定？",
 ["新設製程處理效率應達百分之八十五或管道排放量零點四公斤／小時以下；既存製程處理效率應達百分之七十五或管道排放量零點四公斤／小時以下","新設製程處理效率應達百分之九十五或管道排放量零點一公斤／小時以下；既存製程處理效率應達百分之八十五或管道排放量零點二公斤／小時以下","新設製程處理效率應達百分之七十五或管道排放量零點六公斤／小時以下；既存製程處理效率應達百分之六十或管道排放量一點三公斤／小時以下","新設及既存製程處理效率均應達百分之八十或管道排放量零點四公斤／小時以下，不因設立時間先後而有差異"],"a",
 "第4條第1項附表：揮發性有機物新設製程處理效率應達百分之八十五或管道排放量零點四公斤／小時以下（以甲烷為計算基準）；既存製程處理效率應達百分之七十五或管道排放量零點四公斤／小時以下。氫氟酸及鹽酸則另依防制設備前端廢氣濃度是否達三ppm 區分處理效率。",
 "What VOC emission standards apply to new and existing processes?",
 ["New processes: 85% efficiency or stack emissions of 0.4 kg/hr; existing processes: 75% efficiency or 0.4 kg/hr","New processes: 95% efficiency or 0.1 kg/hr or less; existing processes: 85% efficiency or 0.2 kg/hr or less","New processes: 75% efficiency or 0.6 kg/hr or less; existing processes: 60% efficiency or 1.3 kg/hr or less","Both new and existing processes: 80% efficiency or 0.4 kg/hr or less, with no difference by date of establishment"],
 "Article 4: 85% for new and 75% for existing, or 0.4 kg/hr."),

(L,"第4條",3,"光電業空污-無機酸標準",
 "光電業氫氟酸及鹽酸之排放標準如何規定？",
 ["防制設備前端廢氣濃度三ppm 以上者處理效率應達百分之八十五，小於三ppm 者應達百分之七十五；管道排放量氫氟酸零點一、鹽酸零點二公斤／小時以下","防制設備前端廢氣濃度五ppm 以上者處理效率應達百分之九十，小於五ppm 者應達百分之八十；管道排放量氫氟酸零點二、鹽酸零點四公斤／小時以下","不論防制設備前端廢氣濃度高低，處理效率一律應達百分之九十五；管道排放量氫氟酸及鹽酸均為零點四公斤／小時以下","防制設備前端廢氣濃度三ppm 以上者處理效率應達百分之七十五，小於三ppm 者免予管制；管道排放量氫氟酸及鹽酸均為零點一公斤／小時"],"a",
 "第4條第1項附表：氫氟酸與鹽酸均以防制設備前端廢氣濃度三ppm 為界，達三ppm 以上者處理效率應達百分之八十五，小於三ppm 者應達百分之七十五；管道排放量部分氫氟酸為零點一公斤／小時以下，鹽酸為零點二公斤／小時以下。",
 "What standards apply to hydrofluoric and hydrochloric acid emissions?",
 ["Inlet concentration of 3 ppm or more: 85% efficiency; below 3 ppm: 75%; stack rates of 0.1 kg/hr for HF and 0.2 kg/hr for HCl","Inlet concentration of 5 ppm or more: 90% efficiency; below 5 ppm: 80%; stack rates of 0.2 kg/hr for HF and 0.4 kg/hr for HCl","Regardless of inlet concentration, 95% efficiency is required; stack rates of 0.4 kg/hr for both HF and HCl apply","Inlet concentration of 3 ppm or more: 75% efficiency; below 3 ppm no control at all; stack rates of 0.1 kg/hr for both acids"],
 "Article 4: the 3 ppm inlet threshold and the 0.1 and 0.2 kg/hr rates."),

(L,"第4條",3,"光電業空污-標準適用",
 "光電業單一空氣污染物之單位小時許可排放量達零點六公斤／小時者，應以何者為排放標準？",
 ["應以處理效率為排放標準；但同一場所經二個以上管道排放時，排放量較小或僅含模組製程廢氣之管道經核可者得以管道排放量為準","應以管道排放量為排放標準；但同一場所經二個以上管道排放時，排放量較大之管道經核可者得改以處理效率為準","得由光電業於處理效率與管道排放量二者中自由選擇，無須報請地方主管機關核可即可適用","應同時符合處理效率及管道排放量二項標準，任一項不符合者即認定為違反本標準之規定"],"a",
 "第4條第3項：單一空氣污染物之單位小時許可排放量小於零點六公斤／小時者，其個別排放管道適用之排放標準應報經地方主管機關核可；達零點六公斤／小時之光電業應以處理效率為排放標準。但同一公私場所單一污染物經二個以上排放管道排放時，排放量較小或僅含模組製程廢氣之排放管道，報經地方主管機關核可者，得以管道排放量為適用之排放標準。",
 "Which standard applies where the permitted hourly rate reaches 0.6 kg/hr?",
 ["Treatment efficiency governs; but where several stacks exist, a smaller or module-only stack may use the stack rate if approved","The stack emission rate governs; but where several stacks exist, the larger stack may switch to efficiency if approved","The firm may freely choose between efficiency and stack rate, with no need for local authority approval at all","Both the efficiency and the stack rate must be met, and failing either one constitutes a violation of the standard"],
 "Article 4, Paragraph 3: efficiency at or above 0.6 kg/hr, with an approved exception."),

(L,"第5條",3,"光電業空污-標準登載",
 "光電業排放標準之適用，應如何完成程序？既設光電業之檢測期限為何？",
 ["應於申請操作許可證時併同排放檢測報告提出並經核可後登載於許可證；既設者應於九十六年三月三十一日前完成三項污染物檢測","應於申請設置許可證時逕行選定即可，無須提出檢測報告；既設者應於九十七年十二月三十一日前完成三項污染物檢測","應由地方主管機關逕行指定適用之排放標準並登載於許可證；既設者無須辦理任何檢測即得沿用原標準","應於每年排放量申報時併同提出檢測報告；既設者應於本標準發布施行日起一個月內完成三項污染物檢測"],"a",
 "第5條第1項、第2項：排放標準之適用應於申請固定污染源操作許可證時，併同空氣污染物排放檢測報告提出，並經地方主管機關或中央主管機關委託之政府其他機關核可後登載於操作許可證內容；本標準發布施行日前已設立之光電業，應於中華民國九十六年三月三十一日前完成所有排放管道之揮發性有機物、氫氟酸及鹽酸檢測作業並報請核可登載。",
 "How is the applicable standard confirmed, and what deadline binds existing firms?",
 ["Submit with the permit application plus a test report, approved and entered in the permit; existing firms test all three by 31 March 2007","Simply select it when applying for an installation permit with no test report; existing firms test all three by 31 December 2008","The local authority designates the standard and enters it in the permit; existing firms need no testing and keep the old standard","Submit a test report with the annual emission report; existing firms test all three within one month of promulgation"],
 "Article 5: permit-linked approval and the March 2007 deadline."),

(L,"第6條",3,"光電業空污-紀錄申報",
 "光電業就原物料使用之紀錄、排放量申報及資料保存規定為何？",
 ["原物料種類含量購入量使用量輸出量等應每月記錄；應於每年一月底前向地方主管機關申報前一年排放量；紀錄及排放量資料應保存五年","原物料相關資料應每季記錄；應於每年七月底前向中央主管機關申報前一年排放量；紀錄及排放量資料應保存二年","原物料相關資料應每日記錄；應於每季結束後十五日內向地方主管機關申報前一季排放量；資料應保存十年","原物料相關資料僅需於稽查時提供；排放量無須主動申報；紀錄資料保存年限由光電業自行決定"],"a",
 "第6條：光電業使用含揮發性有機物、氫氟酸或鹽酸之原物料種類、含量百分比、購入量、使用量、輸出量等資料應每月記錄；並應配合紀錄、監測及檢測結果計算全廠三項污染物之年排放量，於每年一月底前向地方主管機關申報前一年排放量；第1項紀錄及第2項排放量資料應保存五年備查。",
 "What recording, reporting and retention rules apply to raw material data?",
 ["Record type, content, purchase, use and output monthly; report last year emissions locally by end of January; keep data five years","Record the data quarterly; report the previous year emissions to the central authority by end of July; keep data for two years","Record the data daily; report the previous quarter emissions within fifteen days of quarter end; keep the data for ten years","Produce the data only at inspections; no active emission reporting is required; the retention period is set by the firm"],
 "Article 6: monthly records, January reporting, five-year retention."),

(L,"第7條",3,"光電業空污-監測檢測",
 "光電業排放管道之監測及檢測作業規定，下列敘述何者正確？",
 ["揮發性有機物單位小時許可排放量達一．三公斤以上者應設連續自動監測設施；非屬者其非甲烷碳氫化合物濃度及排放量每半年應檢測一次","揮發性有機物單位小時許可排放量達零點六公斤以上者應設連續自動監測設施；非屬者其非甲烷碳氫化合物每二年應檢測一次","所有排放管道均應設置連續自動監測設施，不論許可排放量大小，且不得以任何理由申請免予設置或替代","揮發性有機物單位小時許可排放量達三公斤以上者應設連續自動監測設施；非屬者得由光電業自行決定檢測頻率"],"a",
 "第7條第1款、第2款：揮發性有機物單位小時許可排放量達一．三公斤以上者，其防制設備廢氣導入處及排放口應設置連續自動監測設施；但同一場所單一污染物經二個以上管道排放時，排放量較小或僅含模組製程廢氣之管道經核可者得免設。非前款規定之管道，其非甲烷碳氫化合物濃度及排放量每半年應檢測一次，每次檢測應達四小時。",
 "Which statement on stack monitoring and testing is correct?",
 ["VOC permitted rates of 1.3 kg/hr or more require continuous monitors; other stacks test NMHC concentration and rate every six months","VOC permitted rates of 0.6 kg/hr or more require continuous monitors; other stacks test NMHC concentration and rate every two years","All stacks require continuous automatic monitors whatever the permitted rate, with no exemption or alternative available","VOC permitted rates of 3 kg/hr or more require continuous monitors; other stacks may set their own testing frequency"],
 "Article 7(1)-(2): the 1.3 kg/hr monitor threshold and semi-annual testing."),

(L,"第7條",3,"光電業空污-無機酸檢測",
 "光電業無機酸排放管道之氫氟酸及鹽酸檢測規定為何？",
 ["排放濃度及排放量每年應檢測一次，每次採樣應達三十分鐘且採樣測定應達三次以上，處理效率及排放量以濃度總平均值計算","排放濃度及排放量每半年應檢測一次，每次採樣應達四小時且採樣測定應達一次即可，處理效率以最大值計算","排放濃度及排放量每三年應檢測一次，每次採樣應達十分鐘且採樣測定應達二次以上，處理效率以最小值計算","排放濃度及排放量每季應檢測一次，每次採樣應達六十分鐘且採樣測定應達五次以上，處理效率以中位數計算"],"a",
 "第7條第3款：無機酸排放管道之氫氟酸及鹽酸排放濃度及排放量每年應檢測一次，檢測時需記錄當時製程及污染防制設備之操作條件；每次採樣應達三十分鐘，採樣及測定應達三次以上；檢測報告應含所測得各次濃度之測值及總平均值，處理效率及排放量應採濃度總平均值計算之。",
 "What testing rules apply to HF and HCl stacks?",
 ["Test concentration and rate annually, each sampling at least thirty minutes and at least three samples, using the overall mean for efficiency and rate","Test concentration and rate every six months, each sampling at least four hours and one sample only, using the maximum value for efficiency","Test concentration and rate every three years, each sampling at least ten minutes and at least two samples, using the minimum for efficiency","Test concentration and rate quarterly, each sampling at least sixty minutes and at least five samples, using the median for efficiency"],
 "Article 7(3): annual testing, thirty-minute samples, three or more runs."),

(L,"第8條",3,"光電業空污-流量計監測",
 "光電業裝設污染防制設備者，其流量計及監測設施規定為何？",
 ["揮發性有機物廢氣導入處或排放口應設氣體流量計，濕式洗滌設備循環管線應設液體流量計；每季有效監測時數百分率應大於百分之八十","揮發性有機物排放口應設液體流量計，濕式洗滌設備應設氣體流量計；每季有效監測時數百分率應大於百分之五十","僅濕式洗滌設備需設置液體流量計，其餘防制設備均免設流量計；每季有效監測時數百分率應大於百分之九十五","所有防制設備均應設置氣體及液體流量計各一具；每季有效監測時數百分率無最低要求，由光電業自行掌握"],"a",
 "第8條第1項第1款、第3款：污染防制設備之揮發性有機物廢氣導入處或排放口應設置氣體流量計，濕式洗滌設備之洗滌水循環管線應設置液體流量計；防制設備並應設置操作運轉條件之監測設施，依附表所列項目及頻率記錄；監測設施之每季有效監測時數百分率應大於百分之八十，氣體及液體流量計每年應校正一次。",
 "What flow meter and monitoring rules apply to control equipment?",
 ["Gas flow meters at the VOC inlet or outlet and liquid meters on wet scrubber circulation lines; quarterly valid monitoring above 80 per cent","Liquid flow meters at the VOC outlet and gas flow meters on wet scrubbers; quarterly valid monitoring above fifty per cent","Only wet scrubbers need liquid flow meters and all other devices are exempt; quarterly valid monitoring above ninety-five per cent","Every device needs one gas and one liquid flow meter; there is no minimum quarterly valid monitoring percentage at all"],
 "Article 8, Paragraph 1(1) and (3): meter placement and the eighty per cent rule."),

(L,"第8條",2,"光電業空污-紀錄替代",
 "光電業污染防制設備操作運轉紀錄之保存年限，及無法設置流量計時之處理方式為何？",
 ["操作運轉紀錄應保存五年備查；流量計及監測設施因故無法設置者，得提出替代監測方案報請地方主管機關核可","操作運轉紀錄應保存二年備查；流量計及監測設施因故無法設置者，得逕行免除監測義務而無須報請核可","操作運轉紀錄應保存十年備查；流量計及監測設施因故無法設置者，應立即停止該防制設備之操作運轉","操作運轉紀錄應保存三年備查；流量計及監測設施因故無法設置者，應改由中央主管機關派員每月到廠檢測"],"a",
 "第8條第2項、第3項：污染防制設備操作運轉紀錄應保存五年備查；第1項流量計及監測設施因故無法設置者，得提出替代監測方案，報請地方主管機關核可。與第6條紀錄及排放量資料保存五年之規定一致。",
 "How long are operating records kept, and what if meters cannot be installed?",
 ["Operating records kept five years; where meters or monitors cannot be installed, an alternative monitoring plan may be approved locally","Operating records kept two years; where meters or monitors cannot be installed, monitoring is simply waived without any approval","Operating records kept ten years; where meters or monitors cannot be installed, the control device must cease operating at once","Operating records kept three years; where meters or monitors cannot be installed, the central authority tests on site monthly"],
 "Article 8, Paragraphs 2-3: five-year records and approved alternatives."),

(L,"第9條",2,"光電業空污-既存期限",
 "光電業既存製程應自何時起符合本標準規定？",
 ["應自中華民國九十六年一月一日起符合本標準規定","應自中華民國九十五年一月五日起符合本標準規定","應自中華民國九十七年七月一日起符合本標準規定","應自中華民國九十八年一月一日起符合本標準規定"],"a",
 "第9條：既存製程應自中華民國九十六年一月一日起符合本標準規定。第5條第2項並要求既設光電業於九十六年三月三十一日前完成所有排放管道之三項污染物檢測作業並報請核可登載。",
 "From when must existing optoelectronics processes comply?",
 ["From 1 January 2007","From 5 January 2006","From 1 July 2008","From 1 January 2009"],
 "Article 9: compliance from 1 January 2007."),

(L,"第10條",1,"光電業空污-施行",
 "光電材料及元件製造業空氣污染管制及排放標準之施行日期為何？",
 ["除另定施行日期者外，自發布日施行","一律自發布後六個月施行，不得另定日期","除另定施行日期者外，自發布後一年施行","一律自中華民國九十六年一月一日起施行"],"a",
 "第10條：本標準除另定施行日期者外，自發布日施行。既存製程之適用日期則另依第9條規定，自中華民國九十六年一月一日起應符合本標準。",
 "When does the optoelectronics industry standard take effect?",
 ["On the date of promulgation, unless a separate date is set","Always six months after promulgation with no exceptions","One year after promulgation, unless a separate date is set","Always on 1 January 2007 for every provision of the standard"],
 "Article 10: effective on promulgation unless otherwise provided."),

# ===== ENV-111 汽車製造業表面塗裝作業空氣污染物排放標準（11 條）=====
(M,"第1條",1,"汽車塗裝-授權",
 "汽車製造業表面塗裝作業空氣污染物排放標準係依何規定訂定？",
 ["空氣污染防制法第二十條第二項、第二十二條、第二十三條及第四十四條第三項","空氣污染防制法第十四條第一項、第十六條、第十八條及第二十一條第二項","空氣污染防制法第二十四條第三項、第二十七條、第二十八條及第三十一條第一項","空氣污染防制法第三十二條第二項、第三十四條、第三十六條及第四十條第三項"],"a",
 "第1條：本標準依空氣污染防制法第二十條第二項、第二十二條、第二十三條及第四十四條第三項規定訂定之，分別為排放標準、檢測申報、防制設施管理及相關授權依據。",
 "Under which provisions is the automobile coating standard issued?",
 ["Articles 20-2, 22, 23 and 44-3 of the Air Pollution Control Act","Articles 14-1, 16, 18 and 21-2 of the Air Pollution Control Act","Articles 24-3, 27, 28 and 31-1 of the Air Pollution Control Act","Articles 32-2, 34, 36 and 40-3 of the Air Pollution Control Act"],
 "Article 1 cites Articles 20, 22, 23 and 44 of the APCA."),

(M,"第2條",2,"汽車塗裝-名詞定義",
 "本標準所稱表面塗裝作業、底塗及乾燥室之定義分別為何？",
 ["表面塗裝作業指為保護或裝飾車體而於其表面覆以膜層者；底塗指保護鋼板表面或承受後續塗膜之第一道作業；乾燥室指烘烤使塗料聚合固化之場所","表面塗裝作業指車體鋼板之研磨與除鏽前處理作業；底塗指塗裝完成後之最後一道保護面漆作業；乾燥室指以冷風吹拂使塗料自然風乾之場所","表面塗裝作業指車體各項零組件之電鍍處理作業；底塗指車體底部防鏽蠟之噴塗作業；乾燥室指存放待塗裝車體之恆溫恆濕倉儲場所","表面塗裝作業指車體之清洗與脫脂前處理作業；底塗指中塗與面塗間之中間層塗裝作業；乾燥室指以紫外線照射使塗料固化之場所"],"a",
 "第2條第2款、第3款、第7款：表面塗裝作業指為保護或裝飾車體，於其表面覆以膜層之作業；底塗指為保護車體鋼板表面，或用以承受後續塗膜之第一道表面塗裝作業；乾燥室指加熱、烘烤使車體表面塗料產生聚合、乾燥或固化之場所。",
 "How are surface coating, primer coating and the drying room defined?",
 ["Coating means applying a film to protect or decorate the body; primer is the first coat protecting the panel or receiving later films; the drying room cures coatings by heat","Coating means grinding and derusting the body panels; primer is the final protective topcoat applied after coating; the drying room air-dries coatings with cool air","Coating means electroplating of body components; primer is spraying anti-rust wax under the body; the drying room is a climate-controlled store for bodies awaiting coating","Coating means washing and degreasing the body before treatment; primer is the intermediate layer between mid and top coats; the drying room cures coatings by ultraviolet light"],
 "Article 2(2), (3) and (7) define these terms."),

(M,"第2條",3,"汽車塗裝-底塗面積",
 "本標準所稱底塗面積之計算方法，下列何者正確？",
 ["得以二倍鋼板淨重除以鋼板原始厚度與鋼板密度之乘積計算，或以電著塗料乾膜淨重除以其平均厚度與密度之乘積計算","得以車體外觀長寬高相乘之表面積計算，或以塗料採購總量除以單位面積用量標準值計算","得以每月生產車輛數乘以車廠自訂之單車面積係數計算，或以塗裝線輸送帶長度乘以噴塗寬度計算","得以鋼板總重量除以塗料密度計算，或以塗裝作業總工時乘以每工時平均塗裝面積之經驗值計算"],"a",
 "第2條第4款：底塗面積之計算應採下列公式之一：二乘鋼板淨重（kg）除以鋼板原始厚度（m）乘鋼板密度（kg/m3）；電著塗料乾膜淨重除以電著塗料乾膜平均厚度乘密度；電腦輔助設計系統設計之鈑金鋼板面積；其他經中央主管機關認定之計算方法。",
 "Which calculation method for primer coated area is correct?",
 ["Twice net panel weight divided by original panel thickness times panel density, or dry electrocoat weight divided by its thickness times density","The exterior surface area from multiplying vehicle length, width and height, or total coating purchased divided by a standard unit area usage","Monthly vehicle output times a per-vehicle area factor set by the plant, or coating line conveyor length times spray width","Total panel weight divided by coating density, or total coating labour hours times an empirical area coated per hour"],
 "Article 2(4) sets the permitted area formulas."),

(M,"第2條",2,"汽車塗裝-VOC定義",
 "本標準所稱揮發性有機物及後處理單元之定義為何？",
 ["揮發性有機物指含碳化合物於儲運塗裝烘烤等作業排放者，但不含一氧化碳、二氧化碳、甲烷及氟氯碳化物；後處理單元指回收及以吸收吸附或焚化去除之單元","揮發性有機物指所有含碳之化合物，包括一氧化碳、二氧化碳及甲烷等在內；後處理單元指塗裝前之脫脂清洗及磷酸鹽皮膜處理之前處理單元","揮發性有機物指沸點在攝氏一百度以下之各類有機溶劑及稀釋劑；後處理單元指塗裝完成後之打蠟研磨及外觀檢查等品質管制單元","揮發性有機物指塗料中所含之重金屬顏料與各項添加助劑；後處理單元指廢塗料桶之清洗及廢溶劑委外處理之單元"],"a",
 "第2條第5款、第6款：揮發性有機物指含碳之化合物或其混合物於儲運、混合、攪拌、清洗、塗裝、烘烤及各種作業過程排放出者，但不包括一氧化碳、二氧化碳、碳酸、金屬碳化物或碳酸鹽、碳酸銨、甲烷及氟氯碳化物；後處理單元指揮發性有機物或其混合物之回收單元及以吸收、吸附或焚化等方式去除揮發性有機物之單元。",
 "How are VOCs and the post-treatment unit defined in this standard?",
 ["VOCs are carbon compounds released in storage, coating and baking, excluding CO, CO2, methane and CFCs; post-treatment covers recovery and removal by adsorption or incineration","VOCs are all carbon-containing compounds including carbon monoxide, carbon dioxide and methane; post-treatment covers degreasing and phosphate film pretreatment before coating","VOCs are organic solvents with a boiling point below 100 degrees C; post-treatment covers waxing, polishing and appearance inspection quality units after coating","VOCs are the heavy metal pigments and additives in the coatings; post-treatment covers cleaning waste paint drums and outsourcing waste solvent disposal"],
 "Article 2(5)-(6) define VOCs and post-treatment units."),

(M,"第3條",2,"汽車塗裝-適用範圍",
 "本標準適用於汽車製造程序之哪些作業？",
 ["表面塗裝相關作業，包括儲運、混合、攪拌、清洗、塗裝、乾燥及其後處理單元","僅限噴漆房內之塗裝作業本身，儲運及乾燥等前後端作業均不納入適用範圍","僅限車體焊接、沖壓及組裝等機械加工作業，塗裝作業另依一般排放標準辦理","僅限廢塗料及廢溶劑之貯存清除處理作業，塗裝作業本身不適用本標準規定"],"a",
 "第3條：本標準適用於汽車製造程序之表面塗裝相關作業，包括儲運、混合、攪拌、清洗、塗裝、乾燥及其後處理單元。與第2條第5款揮發性有機物定義所列之作業範圍一致。",
 "Which operations of the automobile process does this standard cover?",
 ["Surface coating related work, including storage, mixing, stirring, cleaning, coating, drying and post-treatment units","Only the coating operation inside the spray booth, excluding storage, drying and other upstream or downstream work","Only welding, stamping and assembly machining operations, with coating governed by the general emission standard","Only the storage, clearance and disposal of waste coatings and solvents, excluding the coating operation itself"],
 "Article 3 lists the covered coating-related operations."),

(M,"第4條",2,"汽車塗裝-濃度基準",
 "本標準濃度計算之基準及單位為何？",
 ["以凱氏溫度二七三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，單位為 mg／Nm3","以攝氏二十五度及一大氣壓下稀釋後之濕排氣體積為計算基準，單位為 ppm","以凱氏溫度二七三度及二大氣壓下未經稀釋之濕排氣體積為計算基準，單位為 g／m3","以攝氏零度及一大氣壓下稀釋後之乾燥排氣體積為計算基準，單位為 kg／hr"],"a",
 "第4條：本標準濃度計算均以凱氏溫度二七三度及一大氣壓下未經稀釋之乾燥排氣體積為計算基準，單位為 mg／Nm3。第7條乾燥室排放標準六〇mg/Nm3 即依此基準且未經含氧量校正。",
 "What calculation basis and unit apply to concentrations in this standard?",
 ["273 K and one atmosphere, undiluted dry exhaust gas volume, expressed in mg per Nm3","25 degrees C and one atmosphere, diluted moist exhaust gas volume, expressed in ppm","273 K and two atmospheres, undiluted moist exhaust gas volume, expressed in g per m3","0 degrees C and one atmosphere, diluted dry exhaust gas volume, expressed in kg per hour"],
 "Article 4: undiluted dry gas at 273 K, in mg per Nm3."),

(M,"第5條",3,"汽車塗裝-紀錄申報",
 "汽車製造程序使用含揮發性有機物之物質，其紀錄及申報規定為何？",
 ["應記錄購置、貯存、使用及處理等資料並保存二年以上；應按月做成報告書於次月十五日前申報揮發性有機物排放量","應記錄購置及使用資料並保存六年以上；應按季做成報告書於次季首月月底前申報揮發性有機物排放量","應記錄貯存及處理資料並保存五年以上；應按年做成報告書於次年一月底前申報揮發性有機物排放量","應記錄購置、貯存、使用及處理等資料但無保存年限；僅於主管機關要求時提報，無須定期申報排放量"],"a",
 "第5條：汽車製造程序使用含揮發性有機物之物質應記錄其購置、貯存、使用及處理等資料，紀錄應保存二年以上，以供主管機關查驗；並應依中央主管機關規定之格式按月做成報告書，於次月十五日前向主管機關申報揮發性有機物之排放量。",
 "What recording and reporting rules apply to VOC-containing materials?",
 ["Record purchase, storage, use and disposal and keep two years or more; make monthly reports and file VOC emissions by the fifteenth of the next month","Record purchase and use and keep six years or more; make quarterly reports and file VOC emissions by the end of the first month of the next quarter","Record storage and disposal and keep five years or more; make annual reports and file VOC emissions by the end of January of the next year","Record purchase, storage, use and disposal with no retention period; submit only on request with no periodic emission reporting"],
 "Article 5: two-year records and monthly reporting by the fifteenth."),

(M,"第6條",3,"汽車塗裝-報告書內容",
 "含揮發性有機物物質之貯存、使用及處理報告書內容，下列何者非屬應包括項目？",
 ["塗裝作業員工之健康檢查結果、教育訓練時數及個人防護具配發紀錄等人員管理資料","製程型式、污染排放型式說明、平面配置圖說及各車型底塗面積與計算方法說明","各塗裝單元之型式、塗裝次數、月塗裝量、乾燥方式及設計最低乾燥溫度等資料","揮發性有機物質量平衡計算項目，包括月進貨量、月使用量、月回收量及月排放量"],"a",
 "第6條列舉報告書應包括一般性項目（製程型式、作業時間、揮發性有機物百分率測定計算方法、各車型底塗面積）、表面塗裝作業項目、塗料及溶劑回收處理方式、收集系統型式與效率、後處理單元及廢氣處理項目、質量平衡計算項目及其他經指定項目。員工健康檢查等人員資料不在其中。",
 "Which item is NOT required in the storage, use and disposal report?",
 ["Health check results, training hours and protective equipment issue records for coating operators","Process type, emission type description, layout drawings and primer area with calculation methods for each model","Type, number of coats and monthly coating volume of each unit, drying method and minimum design drying temperature","VOC mass balance items including monthly purchases, usage, recovery and monthly emission volumes"],
 "Article 6 lists the report contents; personnel health data is not one."),

(M,"第6條",3,"汽車塗裝-後處理紀錄",
 "報告書中後處理單元及廢氣處理項目之紀錄規定，下列敘述何者正確？",
 ["以熱焚化爐者應記錄燃燒溫度及氣體滯留時間；以觸媒焚化爐者應記錄觸媒種類、滯留時間、出口溫度及觸媒床更換日期","以熱焚化爐者應記錄觸媒種類及更換日期；以觸媒焚化爐者應記錄燃燒溫度及燃燒室壓力等主要操作參數","以冷凝器者應記錄吸附劑種類與使用量；以吸附器者應記錄冷凝劑進出口溫度及冷卻水循環量","以熱焚化爐及觸媒焚化爐者均免予記錄任何操作參數；僅需記錄每月處理之廢氣總風量即可"],"a",
 "第6條第5款：以熱焚化爐為後處理單元者，應記錄燃燒溫度及燃燒氣體滯留時間；以觸媒焚化爐者應記錄觸媒種類、氣體滯留時間、出口氣體溫度及觸媒床更換日期；以冷凝器者應記錄冷凝劑進、出口溫度；以吸附器者應記錄吸附劑種類、使用量、使用期限、更換頻率、吸附床數目及進口氣體溫度。",
 "Which statement on post-treatment unit recording is correct?",
 ["Thermal oxidisers record combustion temperature and residence time; catalytic oxidisers record catalyst type, residence time, outlet temperature and bed change dates","Thermal oxidisers record catalyst type and change dates; catalytic oxidisers record combustion temperature and chamber pressure as key operating parameters","Condensers record adsorbent type and quantity used; adsorbers record coolant inlet and outlet temperatures and cooling water circulation volume","Both thermal and catalytic oxidisers are exempt from recording any operating parameter and need only log monthly total gas volume treated"],
 "Article 6(5) sets the recording items for each post-treatment type."),

(M,"第7條",3,"汽車塗裝-乾燥室標準",
 "乾燥室廢氣之揮發性有機物應符合何項排放標準？",
 ["總破壞去除效率九〇％及排放管道排放標準未經含氧量校正六〇mg/Nm3","總破壞去除效率七五％及排放管道排放標準經含氧量校正一一〇mg/Nm3","總破壞去除效率九五％及排放管道排放標準未經含氧量校正一〇〇mg/Nm3","總破壞去除效率八五％及排放管道排放標準經含氧量校正四〇mg/Nm3"],"a",
 "第7條：乾燥室廢氣之揮發性有機物應符合總破壞去除效率九〇％及排放管道排放標準未經含氧量校正六〇mg/Nm3。第4條並定明濃度以凱氏溫度二七三度及一大氣壓下未經稀釋乾燥排氣體積為計算基準。",
 "What standard applies to VOCs in drying room exhaust?",
 ["Overall destruction and removal efficiency of 90% and a stack limit of 60 mg/Nm3 without oxygen correction","Overall destruction and removal efficiency of 75% and a stack limit of 110 mg/Nm3 with oxygen correction","Overall destruction and removal efficiency of 95% and a stack limit of 100 mg/Nm3 without oxygen correction","Overall destruction and removal efficiency of 85% and a stack limit of 40 mg/Nm3 with oxygen correction"],
 "Article 7: 90% DRE and 60 mg/Nm3 uncorrected."),

(M,"第8條",3,"汽車塗裝-單位面積標準",
 "汽車製造程序表面塗裝相關作業之揮發性有機物排放標準及其計算方式為何？",
 ["排放標準應符合一一〇g/㎡；以每月表面塗裝相關作業所排放之揮發性有機物總量除以底塗總面積為基準計算","排放標準應符合六〇g/㎡；以每年表面塗裝作業排放之揮發性有機物總量除以車輛生產總數為基準計算","排放標準應符合二二〇g/㎡；以每季表面塗裝作業排放之揮發性有機物總量除以塗料總使用量為基準計算","排放標準應符合一一〇mg/Nm3；以每月排放管道實測濃度之算術平均值為基準計算並經含氧量校正"],"a",
 "第8條：汽車製造程序表面塗裝相關作業之揮發性有機物排放標準應符合一一〇g/㎡；其計算係以每月表面塗裝相關作業所排放之揮發性有機物總量除以底塗總面積為基準。底塗面積之計算方法則依第2條第4款規定。",
 "What VOC standard applies to automobile coating work and how is it computed?",
 ["A limit of 110 g per square metre, computed as monthly total VOC released from coating work divided by total primer coated area","A limit of 60 g per square metre, computed as annual total VOC released from coating work divided by total vehicles produced","A limit of 220 g per square metre, computed as quarterly total VOC released from coating work divided by total coating used","A limit of 110 mg per Nm3, computed as the monthly arithmetic mean of measured stack concentrations with oxygen correction"],
 "Article 8: 110 g per square metre of primer coated area, monthly basis."),

(M,"第9條",1,"汽車塗裝-測定頻率",
 "揮發性有機物之測定項目及頻率應如何辦理？",
 ["應符合中央主管機關之規定","由汽車製造業者自行訂定辦理","由地方主管機關逐案指定辦理","由受託檢驗測定機構自行決定"],"a",
 "第9條：揮發性有機物測定項目及頻率應符合中央主管機關之規定。第10條並定明測定方法依中央主管機關公告之標準檢測方法辦理，二者相互配合。",
 "How are the VOC measurement items and frequency determined?",
 ["They must comply with the rules of the central competent authority","They are set by the automobile manufacturer on its own initiative","They are designated case by case by the local competent authority","They are decided by the commissioned testing agency itself"],
 "Article 9: as prescribed by the central competent authority."),

(M,"第10條",1,"汽車塗裝-測定方法",
 "揮發性有機物之測定方法應依何者辦理？",
 ["依中央主管機關公告之標準檢測方法","依國際標準組織公告之檢測方法","依設備製造廠商建議之檢測方法","依汽車同業公會自訂之檢測方法"],"a",
 "第10條：揮發性有機物測定方法依中央主管機關公告之標準檢測方法。與第9條測定項目及頻率應符合中央主管機關規定之要求相互配合，確保檢測結果具可比性。",
 "Which method must be used to measure VOCs?",
 ["The standard test method announced by the central competent authority","The test method announced by the international standards organisation","The test method recommended by the equipment manufacturer","The test method set by the automobile trade association"],
 "Article 10: the centrally announced standard test method."),

(M,"第11條",1,"汽車塗裝-施行",
 "汽車製造業表面塗裝作業空氣污染物排放標準之施行日期為何？",
 ["本標準自發布日起施行","本標準自發布後六個月施行","本標準自發布後一年施行","本標準另定施行日期公告之"],"a",
 "第11條：本標準自發布日施行。屬形式規定，無緩衝期間，發布當日即生效力。",
 "When does the automobile surface coating emission standard take effect?",
 ["On the date of promulgation","Six months after promulgation","One year after promulgation","On a separately announced date"],
 "Article 11: effective upon promulgation."),
]
