# -*- coding: utf-8 -*-
# 第 9 批（D）：開發行為應實施環境影響評估細目及範圍認定標準、開發行為環境影響評估作業準則、
#              政府政策環境影響評估作業辦法、毒性及關注化學物質標示與安全資料表管理辦法、
#              毒性及關注化學物質運送管理辦法、毒性及關注化學物質許可登記核可管理辦法、
#              毒性及關注化學物質運作與釋放量紀錄管理辦法、毒性及關注化學物質應變器材與偵測警報設備管理辦法、
#              新化學物質及既有化學物質資料登錄辦法、環境用藥管理法
# ※ 四個選項刻意寫成相近長度。
SC = "ENV-64"; GL = "ENV-65"; PL = "ENV-66"; LB = "ENV-70"; TR = "ENV-71"; PM = "ENV-72"
RC = "ENV-73"; EQ = "ENV-74"; RG = "ENV-75"; EA = "ENV-76"
Q = [
# ---------- 開發行為應實施環境影響評估細目及範圍認定標準（ENV-64） ----------
(SC,"第2條",1,"環評認定-用詞定義",
 "本標準所稱「興建」與「擴建（含擴大）」，其定義為何？",
 ["興建指開發單位向目的事業主管機關申請開發行為許可；擴建指原已取得許可之開發行為申請擴增其開發基地面積",
  "興建指開發單位取得建造執照並實際動工開挖整地；擴建指原已取得許可之開發行為申請提高其生產設備產能",
  "興建指開發行為完工後首次向主管機關申請營運登記；擴建指原開發行為變更其負責人或變更營業項目登記",
  "興建指目的事業主管機關核發開發許可之日起算；擴建指開發基地內既有建築物之改建、修繕或汰舊換新"],"a",
 "第2條第1款：興建指開發單位向目的事業主管機關申請開發行為許可。第2款：擴建（含擴大）指原已取得目的事業主管機關許可之開發行為，開發單位申請擴增其開發基地面積。同條並定義水庫集水區分為第一級、第二級水庫集水區及攔河堰集水區，農業用地指依區域計畫法編定之農牧、林業、養殖、水利、生態保護用地。",
 "How does this Standard define construction and expansion?",
 ["Construction is the developer applying to the industry authority for development permission; expansion is an already permitted development applying to enlarge its site area",
  "Construction is the developer obtaining a building permit and actually starting excavation; expansion is an already permitted development applying to raise its production capacity",
  "Construction is applying for an operating registration for the first time after completion; expansion is registering a change of responsible person or of business items",
  "Construction is the date the industry authority issues the development permit; expansion is rebuilding, repairing or replacing existing buildings inside the site"],
 "Article 2, subparagraphs 1 and 2."),

(SC,"第3條",2,"環評認定-工廠",
 "附表一之工業類別工廠，其擴建或擴增產能，於下列何種情形應實施環境影響評估？",
 ["擴增產能百分之十以上；位於都市土地申請開發或累積開發面積五公頃以上；位於非都市土地十公頃以上",
  "擴增產能百分之二十以上；位於都市土地申請開發或累積開發面積十公頃以上；位於非都市土地二十公頃以上",
  "擴增產能百分之五以上；位於都市土地申請開發或累積開發面積二公頃以上；位於非都市土地五公頃以上",
  "擴增產能百分之三十以上；位於都市土地申請開發或累積開發面積十五公頃以上；位於非都市土地三十公頃"],"a",
 "第3條第1項第2款：附表一工業類別擴建或擴增產能，位於國家公園、野生動物保護區、重要濕地、水庫集水區、自來水水質水量保護區或海拔一千五百公尺以上者不分規模應實施環評；位於山坡地、國家風景區或特定農業區之農業用地一公頃以上；擴增產能百分之十以上（但空氣污染、水污染排放總量及廢棄物產生量未增加並經審核同意者除外）；位於都市土地五公頃以上；非都市土地十公頃以上。",
 "For a factory in the Table 1 industry categories, expansion triggers EIA when:",
 ["Capacity expansion of 10% or more; 5 hectares or more of development on urban land; 10 hectares or more on non-urban land",
  "Capacity expansion of 20% or more; 10 hectares or more of development on urban land; 20 hectares or more on non-urban land",
  "Capacity expansion of 5% or more; 2 hectares or more of development on urban land; 5 hectares or more on non-urban land",
  "Capacity expansion of 30% or more; 15 hectares or more of development on urban land; 30 hectares or more on non-urban land"],
 "Article 3, paragraph 1, subparagraph 2."),

(SC,"第3條",3,"環評認定-工廠免評",
 "工廠設立於經環境影響評估審查完成之園區內，以及工廠屬汰舊換新工程者，本標準如何規定？",
 ["設於已完成環評之園區內者，其開發或累積開發面積門檻均增為二倍；汰舊換新工程產能及污染量未增加且單位能耗降低，經目的事業主管機關審核同意者免實施環評",
  "設於已完成環評之園區內者，其開發或累積開發面積門檻均減為二分之一；汰舊換新工程只要產能未增加即當然免實施環境影響評估，無須任何機關審核同意",
  "設於已完成環評之園區內者一律免實施環境影響評估；汰舊換新工程須產能及污染量減少百分之十以上，並經中央主管機關核准後始得免實施環境影響評估",
  "設於已完成環評之園區內者，其開發面積門檻增為三倍；汰舊換新工程之污染量未增加者應報請主管機關備查，並於三年內補行完成第二階段環境影響評估"],"a",
 "第3條第2項：工廠依第1項第3款第8目至第11目、第4款第7目或第8目，申請設立於經環境影響評估審查完成之園區內，其開發或累積開發面積均增為二倍。第3項：工廠屬汰舊換新工程，其產能及污染量未增加，且單位能耗降低，經目的事業主管機關審核同意者，免實施環境影響評估。第4項：申請設立於已完成公共設施及整地之園區內者，免依位於山坡地區位之規定實施環評。",
 "How does the Standard treat factories inside a park that has completed EIA, and like-for-like replacement projects?",
 ["Area thresholds are doubled inside a park that completed EIA; a replacement project with no rise in capacity or pollution and lower unit energy use is exempt with the industry authority's approval",
  "Area thresholds are halved inside a park that completed EIA; a replacement project is automatically exempt so long as capacity does not increase, needing no approval from any authority at all",
  "Factories inside a park that completed EIA are always exempt; a replacement project must cut capacity and pollution by 10% or more and be approved by the central competent authority",
  "Area thresholds are tripled inside a park that completed EIA; a replacement project with no added pollution is filed for record and must complete a second-stage EIA within three years"],
 "Article 3, paragraphs 2 to 4."),

(SC,"第5條",2,"環評認定-道路",
 "依本標準，道路之開發於下列何種情形應實施環境影響評估？",
 ["高速公路或快速道（公）路之興建不分規模；道路興建位於非都市土地長度十公里以上；位於山坡地長度二．五公里以上，同時位於自來水水質水量保護區者一．五公里以上",
  "高速公路或快速道（公）路之興建須長度五公里以上；道路興建位於非都市土地長度二十公里以上；位於山坡地長度五公里以上，同時位於自來水水質水量保護區者三公里以上",
  "高速公路或快速道（公）路之興建須長度十公里以上；道路興建位於非都市土地長度三十公里以上；位於山坡地長度一公里以上，同時位於自來水水質水量保護區者○．五公里",
  "高速公路或快速道（公）路之拓寬不分規模；道路興建位於非都市土地長度五公里以上；位於山坡地長度二公里以上，其同時位於水庫集水區者長度一公里以上者始須實施"],"a",
 "第5條第1項第1款：高速公路或快速道（公）路之興建，不論規模一律應實施環境影響評估。第2款：道（公）路興建或延伸工程位於山坡地或一般保護區長度二．五公里以上，其同時位於自來水水質水量保護區者長度一．五公里以上；位於非都市土地長度十公里以上；位於國家公園、水庫集水區等區位者不分規模。",
 "Which road developments must undergo EIA?",
 ["Any freeway or expressway construction regardless of scale; road construction 10 km or more on non-urban land; 2.5 km or more on slopeland, or 1.5 km if also in a water quality protection area",
  "Freeway or expressway construction only if 5 km or longer; road construction 20 km or more on non-urban land; 5 km or more on slopeland, or 3 km if also in a water quality protection area",
  "Freeway or expressway construction only if 10 km or longer; road construction 30 km or more on non-urban land; 1 km or more on slopeland, or 0.5 km if also in a water quality protection area",
  "Any freeway or expressway widening regardless of scale; road construction 5 km or more on non-urban land; 2 km or more on slopeland, or 1 km if also inside a reservoir catchment area"],
 "Article 5, paragraph 1, subparagraphs 1 and 2."),

(SC,"第5條",3,"環評認定-道路隧道",
 "道（公）路興建或延伸工程，其附屬隧道、地下化工程及高架路橋、橋梁、立體交叉工程之長度門檻為何？",
 ["位於山坡地、一般保護區、都市土地或非都市土地，附屬隧道或地下化工程長度合計一公里以上；位於都市或非都市土地，附屬高架路橋、橋梁或立體交叉工程長度合計五公里以上",
  "位於山坡地、一般保護區、都市土地或非都市土地，附屬隧道或地下化工程長度合計三公里以上；位於都市或非都市土地，附屬高架路橋、橋梁或立體交叉工程長度合計十公里以上",
  "位於山坡地、一般保護區、都市土地或非都市土地，附屬隧道或地下化工程長度合計五百公尺以上；位於都市或非都市土地，附屬高架路橋或立體交叉工程長度合計二公里以上",
  "位於山坡地、一般保護區、都市土地或非都市土地，附屬隧道或地下化工程長度合計二公里以上；位於都市或非都市土地，附屬高架路橋、橋梁工程長度合計二．五公里以上"],"a",
 "第5條第1項第2款第9目：位於山坡地、臺灣沿海地區一般保護區、都市土地或非都市土地，其附屬隧道或地下化工程長度合計一公里以上者應實施環評。第10目：位於都市土地或非都市土地，其附屬高架路橋、橋梁或立體交叉工程長度合計五公里以上。第2項：長度應將高架路橋、橋梁、立體交叉工程、隧道、地下化工程、匝道或引道合併計算。",
 "What length thresholds apply to attached tunnels and elevated structures for road construction or extension?",
 ["Attached tunnels or underground works totalling 1 km or more on slopeland, general protection areas, urban or non-urban land; attached elevated roads, bridges or grade separations totalling 5 km or more",
  "Attached tunnels or underground works totalling 3 km or more on slopeland, general protection areas, urban or non-urban land; attached elevated roads, bridges or grade separations totalling 10 km or more",
  "Attached tunnels or underground works totalling 500 m or more on slopeland, general protection areas, urban or non-urban land; attached elevated roads or grade separations totalling 2 km or more",
  "Attached tunnels or underground works totalling 2 km or more on slopeland, general protection areas, urban or non-urban land; attached elevated roads and bridges totalling 2.5 km or more"],
 "Article 5, paragraph 1, subparagraph 2, items 9 and 10, and paragraph 2."),

(SC,"第12條",2,"環評認定-蓄水工程",
 "蓄水工程之興建，其堰壩高度、蓄水容量及蓄水範圍面積達多少應實施環境影響評估？",
 ["堰壩高度十五公尺以上或蓄水容量五百萬立方公尺以上；位於自來水水質水量保護區者為七．五公尺或二百五十萬立方公尺；申請蓄水範圍面積一百公頃以上",
  "堰壩高度三十公尺以上或蓄水容量一千萬立方公尺以上；位於自來水水質水量保護區者為十五公尺或五百萬立方公尺；申請蓄水範圍面積二百公頃以上者始應實施",
  "堰壩高度十公尺以上或蓄水容量二百萬立方公尺以上；位於自來水水質水量保護區者為五公尺或一百萬立方公尺；申請蓄水範圍面積五十公頃以上者始應實施",
  "堰壩高度二十公尺以上或蓄水容量八百萬立方公尺以上；位於自來水水質水量保護區者為十公尺或四百萬立方公尺；申請蓄水範圍面積三百公頃以上者始實施"],"a",
 "第12條第1款第7目：堰壩高度十五公尺以上或蓄水容量五百萬立方公尺以上；其位於自來水水質水量保護區者，堰壩高度七．五公尺以上或蓄水容量二百五十萬立方公尺以上。第8目：申請蓄水範圍面積一百公頃以上。第2款：堰壩或洩洪道加高高度二公尺以上者亦應實施；第3款：越域引水工程不分規模應實施環評。",
 "What dam height, storage volume and inundation area trigger EIA for impoundment works?",
 ["Dam height 15 m or more or storage 5 million m3 or more; 7.5 m or 2.5 million m3 in a water quality and quantity protection area; inundation area 100 hectares or more",
  "Dam height 30 m or more or storage 10 million m3 or more; 15 m or 5 million m3 in a water quality and quantity protection area; inundation area 200 hectares or more",
  "Dam height 10 m or more or storage 2 million m3 or more; 5 m or 1 million m3 in a water quality and quantity protection area; inundation area 50 hectares or more",
  "Dam height 20 m or more or storage 8 million m3 or more; 10 m or 4 million m3 in a water quality and quantity protection area; inundation area 300 hectares or more"],
 "Article 12, subparagraph 1, items 7 and 8."),

(SC,"第13條",3,"環評認定-抽引水",
 "抽水、引水工程及海水淡化廠，達何種規模應實施環境影響評估？",
 ["抽引地面水或伏流水每秒二立方公尺以上；抽取地下水每秒○．二立方公尺以上；抽取溫泉每秒○．○二立方公尺以上；海水淡化廠每日設計出水量一千公噸以上",
  "抽引地面水或伏流水每秒五立方公尺以上；抽取地下水每秒○．五立方公尺以上；抽取溫泉每秒○．○五立方公尺以上；海水淡化廠每日設計出水量五千公噸以上者",
  "抽引地面水或伏流水每秒一立方公尺以上；抽取地下水每秒○．一立方公尺以上；抽取溫泉每秒○．○一立方公尺以上；海水淡化廠每日設計出水量五百公噸以上者",
  "抽引地面水或伏流水每秒十立方公尺以上；抽取地下水每秒二立方公尺以上；抽取溫泉每秒○．二立方公尺以上；海水淡化廠每日設計出水量二萬公噸以上者始須實施"],"a",
 "第13條第1項第1款：抽、引取地面水、伏流水每秒抽水量二立方公尺以上（抽海水供冷卻或養殖、引水供農業灌溉者除外）；抽取地下水每秒○．二立方公尺以上；抽取溫泉每秒○．○二立方公尺以上；抽取地下水位於地下水管制區。第2款：海水淡化廠興建或擴增處理量，申請每日設計出水量一千公噸以上。第3款第8目：淨水處理廠每日設計出水量二十萬噸以上。",
 "What scale of water abstraction or desalination triggers EIA?",
 ["Surface or subsurface water 2 m3/s or more; groundwater 0.2 m3/s or more; hot spring water 0.02 m3/s or more; desalination plant design output 1,000 tonnes per day or more",
  "Surface or subsurface water 5 m3/s or more; groundwater 0.5 m3/s or more; hot spring water 0.05 m3/s or more; desalination plant design output 5,000 tonnes per day or more",
  "Surface or subsurface water 1 m3/s or more; groundwater 0.1 m3/s or more; hot spring water 0.01 m3/s or more; desalination plant design output 500 tonnes per day or more",
  "Surface or subsurface water 10 m3/s or more; groundwater 2 m3/s or more; hot spring water 0.2 m3/s or more; desalination plant design output 20,000 tonnes per day or more"],
 "Article 13, paragraph 1, subparagraphs 1 and 2."),

(SC,"第25條、第26條",1,"環評認定-高樓建築",
 "高樓建築及三戶以上集合住宅或社區之開發，其應實施環境影響評估之門檻為何？",
 ["高樓建築高度一百二十公尺以上；集合住宅或社區位於山坡地申請開發或累積開發面積一公頃以上，位於非都市土地十公頃以上",
  "高樓建築高度六十公尺以上；集合住宅或社區位於山坡地申請開發或累積開發面積○．五公頃以上，位於非都市土地五公頃以上者",
  "高樓建築高度二百公尺以上；集合住宅或社區位於山坡地申請開發或累積開發面積五公頃以上，位於非都市土地二十公頃以上",
  "高樓建築樓層三十層以上；集合住宅或社區位於山坡地申請開發或累積開發面積二公頃以上，位於非都市土地十五公頃以上"],"a",
 "第26條：高樓建築，其高度一百二十公尺以上者，應實施環境影響評估。第25條第1項第1款：三戶以上之集合住宅或社區興建或擴建，位於山坡地或一般保護區申請開發或累積開發面積一公頃以上、位於特定農業區之農業用地一公頃以上、位於非都市土地十公頃以上者應實施環評。同條第2項並就毗連土地合計逾一公頃之情形定有合併認定規定。",
 "What thresholds trigger EIA for high-rise buildings and for housing complexes of three or more households?",
 ["High-rise buildings 120 m or taller; housing complexes 1 hectare or more on slopeland, or 10 hectares or more on non-urban land",
  "High-rise buildings 60 m or taller; housing complexes 0.5 hectare or more on slopeland, or 5 hectares or more on non-urban land",
  "High-rise buildings 200 m or taller; housing complexes 5 hectares or more on slopeland, or 20 hectares or more on non-urban land",
  "High-rise buildings of 30 storeys or more; housing complexes 2 hectares or more on slopeland, or 15 hectares or more on non-urban land"],
 "Articles 25 and 26."),
]
